// html quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Getting Started & Document Structure",
  desc: "Doctype, head, DOM, elements & attributes",
  questions: [
  { q: "What does HTML stand for?", options: ["HighText Machine Language", "HyperText Markup Language", "Hyperlink and Text Management Language"], answer: 1,
    explain: "HyperText = documents linked to each other; Markup = tags that annotate content with structure and meaning." },
  { q: "What happens if a page has no <!DOCTYPE html>?", options: ["The browser uses quirks mode with legacy layout behavior", "Nothing — it's optional decoration", "It fails to load"], answer: 0,
    explain: "Quirks mode emulates 1990s bugs (e.g., the old box model) for backward compatibility — modern CSS behaves unpredictably." },
  { q: "HTML is best described as a…", options: ["Markup language describing structure and meaning", "Programming language", "Styling language"], answer: 0,
    explain: "It has no logic, loops, or variables — it declares what content IS; CSS styles it, JS adds behavior." },
  { q: "The browser parses HTML into…", options: ["The DOM — a tree of nodes", "Bytecode", "A string cache"], answer: 0,
    explain: "Every element becomes a node with parent/children. CSS selectors, JS, and accessibility all operate on this tree." },
  { q: "Which is a void element (no closing tag)?", options: ["<span>", "<p>", "<img>"], answer: 2,
    explain: "Void elements carry no content: img, br, hr, input, meta, link, source." },
  { q: "Why must <meta charset=\"UTF-8\"> appear within the first 1024 bytes?", options: ["The parser needs the encoding before decoding text; late discovery can force a re-parse", "It's alphabetical convention", "It compresses the page"], answer: 0,
    explain: "Wrong/late encoding is why you see 'JosÃ©' instead of 'José'." },
  { q: "How many <main> elements may a page have?", options: ["One per section", "Unlimited", "One"], answer: 2,
    explain: "Screen-reader users jump straight to main with one key — multiple mains break that contract." },
  { q: "What's wrong with <p><strong>hi</p></strong>?", options: ["Nothing", "Crossed (overlapping) nesting — last opened must close first", "strong can't be inside p"], answer: 1,
    explain: "The parser silently 'repairs' crossed tags, often not how you intended — then JS/CSS act on the repaired tree." },
  { q: "class vs id — which is correct?", options: ["They're interchangeable", "id is unique per page; class is reusable and multiple per element", "class is unique; id is reusable"], answer: 1,
    explain: "Duplicate ids break getElementById, label-for, and anchor links. Style with classes." },
  { q: "Where do custom data values for JS belong?", options: ["Hidden spans", "Made-up attributes like userid=\"42\"", "data-* attributes, read via el.dataset"], answer: 2,
    explain: "data-user-id=\"42\" → el.dataset.userId — valid HTML with a dedicated JS API." },
  { q: "HTML comments <!-- like this -->…", options: ["Are encrypted", "Are stripped by browsers before sending", "Ship to every visitor via view-source"], answer: 2,
    explain: "Never leave secrets, internal URLs, or TODO gossip in comments — they're public." },
  { q: "Multiple spaces and newlines in HTML source render as…", options: ["A single space (whitespace collapsing)", "Exactly as typed", "An error"], answer: 0,
    explain: "That's why indentation is free — and why <pre> exists for when whitespace must be preserved." },
  { q: "Which viewport meta is correct for responsive sites?", options: ["width=device-width, initial-scale=1", "width=980", "user-scalable=no, width=device-width"], answer: 0,
    explain: "Without it phones render a 980px virtual page. Never block zoom (user-scalable=no) — accessibility failure." },
  { q: "A <script src> without attributes in <head>…", options: ["Is ignored until the page loads", "Downloads in parallel, runs later", "Halts HTML parsing while it downloads AND executes"], answer: 2,
    explain: "That's the classic blank-page-on-3G bug. Use type=module or defer for app code." },
  { q: "defer vs async — which preserves execution order?", options: ["defer", "async", "Both"], answer: 0,
    explain: "defer queues scripts to run after parsing in document order; async runs each the moment it arrives — any order." },
  { q: "<script type=\"module\"> behaves like…", options: ["A blocking script", "async always", "A deferred script (parallel download, runs after parse)"], answer: 2,
    explain: "Modules defer by default — one reason they're the modern default for app code." },
  { q: "The <title> element…", options: ["Is optional eye-candy", "Names the tab, bookmarks, and the blue link in Google — required for valid HTML", "Only matters for SEO"], answer: 1,
    explain: "Convention: 'Page · Product' keeps the unique part visible in narrow tabs. 50–60 chars before Google truncates." },
  { q: "What does <base href=\"https://cdn.x.com/\"> do?", options: ["Changes how EVERY relative URL on the page resolves", "Sets the favicon source", "Preconnects to the CDN"], answer: 0,
    explain: "Powerful and dangerous — if all relative links suddenly 404, hunt for a <base> tag." },
  { q: "Which head element is render-blocking by design?", options: ["<link rel=\"stylesheet\">", "<meta description>", "<link rel=\"icon\">"], answer: 0,
    explain: "The browser won't paint until CSS arrives (avoiding a flash of unstyled content) — so head CSS must stay lean." },
  { q: "Visible content accidentally placed in <head>…", options: ["Makes the parser close head early and open body — subtle breakage", "Throws a console error", "Renders in the head area"], answer: 0,
    explain: "The forgiving parser 'fixes' it silently — another reason to validate rather than trust rendering." },
]},
{ title: "Quiz 2 · Text, Headings & Entities",
  desc: "Document outline, inline semantics, escaping",
  questions: [
  { q: "How many <h1> elements should a page have?", options: ["One per major section", "Exactly one", "No limit, it's stylistic"], answer: 1,
    explain: "The sectioning outline that would've allowed more was never implemented by browsers and was dropped from the spec." },
  { q: "Jumping from <h2> directly to <h4>…", options: ["Breaks the outline for screen-reader navigation", "Is a syntax error", "Is fine if it looks right"], answer: 0,
    explain: "~65–70% of screen-reader users navigate by headings — level holes disorient them." },
  { q: "You need smaller heading text. Correct move?", options: ["Keep the correct level, change font-size in CSS", "Use a lower heading level", "Use <small>"], answer: 0,
    explain: "Heading level = document structure; size = presentation. Never choose tags by their default look." },
  { q: "strong vs b?", options: ["strong conveys importance to assistive tech/parsers; b is visual-only offset", "Identical", "b is deprecated"], answer: 0,
    explain: "Same bold rendering, different meaning. Same story for em (stress emphasis) vs i (other voice: ship names, terms)." },
  { q: "Legitimate use of <br>?", options: ["Spacing between paragraphs", "Indenting text", "Line breaks WITHIN content: addresses, poetry"], answer: 2,
    explain: "Spacing between blocks is CSS margin. <br><br> is the classic beginner tell." },
  { q: "<hr> semantically means…", options: ["A thematic shift between content", "A gray line", "End of page"], answer: 0,
    explain: "It's meaning, not decoration — scene change in a story, topic change in an article." },
  { q: "Marking up a keyboard shortcut: which element?", options: ["<code>", "<samp>", "<kbd>"], answer: 2,
    explain: "kbd = user input, samp = program output, code = code. <kbd>Ctrl</kbd>+<kbd>C</kbd>." },
  { q: "Block of code preserving indentation uses…", options: ["<pre><code>…</code></pre>", "<code> alone", "<p class=\"code\">"], answer: 0,
    explain: "pre preserves whitespace (presentation), code declares it's code (semantics) — together for blocks." },
  { q: "<time datetime=\"2026-07-05\">tonight</time> exists so that…", options: ["Timezones convert automatically", "Machines (search, calendars) can parse the real date behind human phrasing", "The text renders as a clock"], answer: 1,
    explain: "Human-friendly text outside, machine-readable ISO date in the attribute." },
  { q: "A price cut from $79 to $49 is best marked as…", options: ["$79 → $49 in a span", "<del>$79</del> <ins>$49</ins>", "<s>$79</s> $49"], answer: 1,
    explain: "del/ins carry edit semantics (with optional datetime attributes) — exactly what a price change is." },
  { q: "<abbr> is for…", options: ["Chemical formulas", "Abbreviations, with the expansion in title", "Foreign words"], answer: 1,
    explain: "<abbr title=\"Cascading Style Sheets\">CSS</abbr> — expansions available to tooltips and assistive tech." },
  { q: "When should you reach for <span>?", options: ["Only when no semantic inline element fits", "Never", "Whenever styling inline text"], answer: 0,
    explain: "span is the semantic-free last resort — check strong/em/code/mark/time/abbr first." },
  { q: "H₂O and x² use which elements?", options: ["CSS only", "<sub> and <sup>", "<small> twice"], answer: 1,
    explain: "Subscript and superscript are content meaning in chemistry/math — not just styling." },
  { q: "To display literal '<' in content you write…", options: ["&lt;", "<<", "\\<"], answer: 0,
    explain: "& and < are the two characters that MUST be escaped in content — the habit that later prevents XSS." },
  { q: "&nbsp; is for…", options: ["Indentation", "Keeping tokens together on one line, like 10&nbsp;km", "Extra spacing anywhere"], answer: 1,
    explain: "It's a non-BREAKING space, not a layout tool. Spacing = CSS." },
  { q: "<blockquote cite=\"url\"> vs <q>?", options: ["q is deprecated", "Block-level quotation vs inline quotation (auto quote marks)", "They're aliases"], answer: 1,
    explain: "blockquote for standalone quotes, q inline within a sentence — browsers add locale-correct quotation marks to q." },
  { q: "<mark> semantically means…", options: ["Highlighted relevance — e.g., search-term hits", "Bold", "A form label"], answer: 0,
    explain: "Default yellow highlight; meaning is 'relevant in this context'." },
  { q: "<small> is meant for…", options: ["Captions under photos", "Fine print: legal notices, disclaimers", "Any smaller text"], answer: 1,
    explain: "It's the side-comment/fine-print element — photo captions have figcaption." },
  { q: "A heading with no content following it is…", options: ["Fine", "Probably not a heading — headings label the content below them", "A section break"], answer: 1,
    explain: "If nothing follows, it's likely a styled paragraph wearing a heading costume." },
  { q: "Reader modes and SEO both rely on headings because…", options: ["They're the largest text", "They load first", "They form the machine-readable outline of the document"], answer: 2,
    explain: "One h1 + nested h2/h3 = the skeleton every consumer (crawler, reader mode, screen reader) reconstructs." },
]},
{ title: "Quiz 3 · Links & Images",
  desc: "URLs, security attributes, responsive images",
  questions: [
  { q: "From /docs/guide/intro.html, href=\"../api/rest.html\" resolves to…", options: ["/docs/guide/api/rest.html", "/docs/api/rest.html", "/api/rest.html"], answer: 1,
    explain: ".. climbs one directory (guide → docs), then descends into api/." },
  { q: "Root-relative URLs (/pricing) are preferred for app navigation because…", options: ["They load faster", "They survive the linking page moving elsewhere", "They're shorter"], answer: 1,
    explain: "File-relative links break when the page relocates; root-relative resolve from the domain root regardless." },
  { q: "rel=\"noopener\" on target=\"_blank\" prevents…", options: ["SEO penalties", "The new tab controlling your page via window.opener (tabnabbing)", "Cookies being shared"], answer: 1,
    explain: "A malicious opened page could redirect YOUR tab to a phishing clone. Modern browsers imply noopener, but write it anyway." },
  { q: "href=\"#faq\" does what?", options: ["Loads faq.html", "Scrolls to the element with id=\"faq\" on this page", "Opens a popup"], answer: 1,
    explain: "Fragment links jump to ids — also the mechanism behind skip links and tables of contents." },
  { q: "Which link opens the user's email client?", options: ["href=\"mailto:team@app.com\"", "href=\"email:team@app.com\"", "href=\"@team@app.com\""], answer: 0,
    explain: "mailto: (with optional ?subject=…) — likewise tel:+14155550132 for phone links." },
  { q: "The download attribute on a link…", options: ["Speeds up the transfer", "Suggests saving the file (with optional filename) instead of navigating", "Zips the file"], answer: 1,
    explain: "download=\"q3-report.pdf\" — same-origin files get the suggested name." },
  { q: "\"Click here\" link text is bad because…", options: ["It's too short", "Links can't contain verbs", "Out of context (screen-reader link lists, SEO) it says nothing about the destination"], answer: 2,
    explain: "Screen-reader users often browse a list of links alone; anchor text is also an SEO relevance signal." },
  { q: "When should target=\"_blank\" be used?", options: ["Never", "All links", "External references / when leaving would lose unsaved work"], answer: 2,
    explain: "Forcing new tabs on same-site nav breaks the back button — the user's most-used control." },
  { q: "alt text for a decorative flourish image should be…", options: ["alt=\"\" — empty but present", "Omitted entirely", "A short description anyway"], answer: 0,
    explain: "Empty alt = 'skip me'. MISSING alt makes screen readers read the filename aloud — the worst outcome." },
  { q: "alt for a logo that links to the homepage?", options: ["\"Image\"", "\"Company logo\"", "\"Acme — home\" (the link's function)"], answer: 2,
    explain: "For functional images, alt describes the FUNCTION (where the link goes), not the pixels." },
  { q: "Why set width and height attributes on img?", options: ["Required by validators", "They compress the image", "Browser reserves the space pre-download → no layout shift (CLS)"], answer: 2,
    explain: "The browser derives aspect-ratio from them; CSS max-width:100%; height:auto keeps it responsive." },
  { q: "loading=\"lazy\" belongs on…", options: ["Below-the-fold images only — never the hero/LCP image", "Every image", "Only iframes"], answer: 0,
    explain: "Lazy-loading the hero delays the exact metric (LCP) Google ranks you on — the classic self-inflicted wound." },
  { q: "The hero image should get…", options: ["fetchpriority=\"high\" (and possibly a preload)", "decoding=\"sync\"", "loading=\"lazy\""], answer: 0,
    explain: "Boost the LCP image's priority; lazy-load everything below the fold instead." },
  { q: "Best photo format stack in 2026?", options: ["BMP → JPEG", "AVIF → WebP → JPEG fallback", "GIF → PNG"], answer: 1,
    explain: "AVIF ≈ half the bytes of JPEG; picture/source picks the first supported type." },
  { q: "Icons and logos should usually be…", options: ["JPEG", "PNG", "SVG — vector, sharp at any size, CSS-styleable"], answer: 2,
    explain: "Vector formats scale infinitely and weigh almost nothing for simple shapes." },
  { q: "srcset with sizes solves…", options: ["Art direction", "Format fallback", "Serving the right RESOLUTION per device/viewport"], answer: 2,
    explain: "The browser picks among hero-400/800/1600.jpg using viewport, layout width (sizes), and pixel density." },
  { q: "<picture> with media attributes solves…", options: ["Resolution switching", "Lazy loading", "Art direction (different crops per breakpoint) and format switching"], answer: 2,
    explain: "You dictate: portrait crop under 600px, AVIF where supported. srcset = browser decides; picture = you decide." },
  { q: "A phone downloading a 1600px image for a 400px slot wastes roughly…", options: ["~90% of the bytes", "~10% of the bytes", "Nothing, it's cached"], answer: 0,
    explain: "Bytes scale with pixel AREA — responsive images are routinely the single biggest page-weight win." },
  { q: "An image with its caption belongs in…", options: ["<table>", "<figure> + <figcaption>", "<div> + <p>"], answer: 1,
    explain: "figure ties the caption to the media semantically — also correct for charts, code listings, diagrams." },
  { q: "rel=\"nofollow\"/\"sponsored\"/\"ugc\" tell search engines…", options: ["Open in a sandbox", "Don't render the link", "Don't pass ranking credit (paid/user-generated links)"], answer: 2,
    explain: "SEO hygiene for comment sections and paid placements — crawlers treat the endorsement differently." },
]},
{ title: "Quiz 4 · Lists & Tables",
  desc: "List semantics, nesting, accessible data tables",
  questions: [
  { q: "Order the shopping steps 'Cart → Pay → Confirm' with…", options: ["<ol> — sequence matters", "<ul>", "<dl>"], answer: 0,
    explain: "The shuffle test: reordering changes meaning → ordered list." },
  { q: "A glossary of term/definition pairs is a…", options: ["<ul> of bolded terms", "two-column table", "<dl> with <dt>/<dd>"], answer: 2,
    explain: "dl is the forgotten key/value element — glossaries, FAQs, spec sheets, metadata panels." },
  { q: "The only valid direct children of <ul>/<ol> are…", options: ["<li> and <div>", "Any block element", "<li> (plus script/template)"], answer: 2,
    explain: "Divs directly inside a ul are invalid — wrappers go inside the li." },
  { q: "A nested sublist goes…", options: ["Inside a div between li's", "INSIDE the parent <li>, before its closing tag", "After the parent <li>, as a sibling"], answer: 1,
    explain: "ul > li > ul — the sublist belongs to its parent item. This is how every nav submenu is built." },
  { q: "<ol start=\"5\" reversed> renders…", options: ["Counting DOWN from 5", "5,6,7…", "An error"], answer: 0,
    explain: "start sets the first number; reversed counts down — top-10 countdowns." },
  { q: "One <dt> with several <dd> elements is…", options: ["Invalid", "Valid — a term may have multiple definitions", "Only valid in tables"], answer: 1,
    explain: "And multiple dt sharing one dd works too (synonyms)." },
  { q: "Screen readers announce lists as…", options: ["Nothing special", "\"List, 5 items\" — structure users literally hear", "Plain text"], answer: 1,
    explain: "That count is why real lists beat div stacks — users know the menu's size before reading it." },
  { q: "The standard production nav pattern is…", options: ["nav > div > span", "nav > ul > li > a", "ul > nav > a"], answer: 1,
    explain: "Semantics + list announcements + CSS handles all styling. Submenus nest a ul inside the li." },
  { q: "<caption> must be…", options: ["The last child of table", "The FIRST child of table — its announced title", "Outside the table"], answer: 1,
    explain: "It's the first thing screen-reader users hear when entering the table." },
  { q: "scope=\"col\" on a th does what?", options: ["Sorts the column", "Styles the column", "Binds that header to its column so cells announce with context"], answer: 2,
    explain: "Cell '$3.1M' announces as 'APAC, Revenue, $3.1M' instead of a naked number." },
  { q: "Row headers (first cell of each row) should be…", options: ["<td> bolded", "<th scope=\"row\">", "<caption>"], answer: 1,
    explain: "Both axes get headers: column headers scope=col in thead, row headers scope=row in tbody." },
  { q: "thead/tbody/tfoot exist to…", options: ["Give semantic bands enabling sticky headers and print-repeated headers", "Add borders", "Speed up rendering"], answer: 0,
    explain: "CSS position:sticky on thead th and repeated headers when printing long tables both rely on the structure." },
  { q: "colspan=\"2\" on a cell…", options: ["Doubles its font", "Hides a column", "Merges it across two columns"], answer: 2,
    explain: "rowspan merges vertically. Keep merges rare — each one complicates screen-reader navigation." },
  { q: "Complex tables where scope can't express header relationships use…", options: ["aria-label per cell", "title attributes", "headers=\"id1 id2\" pointing at th ids"], answer: 2,
    explain: "The headers/id mechanism handles multi-level headers explicitly." },
  { q: "The default responsive-table pattern is…", options: ["Convert to divs", "Shrink the font", "Wrap in an overflow-x:auto container so the TABLE scrolls, not the page"], answer: 2,
    explain: "The page must never scroll horizontally; the table scrolls within its own container." },
  { q: "Styling a whole column's width belongs to…", options: ["<colgroup>/<col>", "Every td", "The tfoot"], answer: 0,
    explain: "col targets a column once — width/background without touching each cell." },
  { q: "Why not use tables for page layout?", options: ["Screen readers announce them as data; source order scrambles; mobile breaks", "They're deprecated", "They render slowly"], answer: 0,
    explain: "CSS Grid does everything layout-tables did, correctly. Tables = data, full stop." },
  { q: "You inherit a legacy layout table you can't rewrite. Stopgap?", options: ["role=\"presentation\" to mute its table semantics", "Delete the table", "aria-hidden on it"], answer: 0,
    explain: "role=presentation keeps rendering but removes the data-table announcements. aria-hidden would hide the CONTENT too." },
  { q: "value=\"10\" on an <li> in an ordered list…", options: ["Sets that item's number (list continues from it)", "Is invalid", "Sets indentation"], answer: 0,
    explain: "Handy for split lists and legal numbering." },
  { q: "A 10-column table on mobile — first question to ask?", options: ["Does mobile NEED all 10 columns, or a summary + detail view?", "Which scroll library to use", "Which font is smallest"], answer: 0,
    explain: "Rethink before rescuing: scroll container, stacked cards, or column-priority hiding are the fallbacks." },
]},
{ title: "Quiz 5 · Forms & Validation",
  desc: "Submission, input types, labels, constraint API",
  questions: [
  { q: "A field without a name attribute…", options: ["Is silently NOT submitted", "Throws an error", "Won't validate"], answer: 0,
    explain: "name is the key the server receives — the #1 'backend gets nothing' bug." },
  { q: "method=\"get\" puts form data…", options: ["In cookies", "In the URL query string — bookmarkable, logged, cached", "In the request body"], answer: 1,
    explain: "Perfect for searches/filters; catastrophic for passwords (history, logs, Referer leaks)." },
  { q: "State-changing or sensitive submissions use…", options: ["post — data in the body", "get", "put"], answer: 0,
    explain: "HTML forms support get/post; the Post/Redirect/Get pattern then avoids double-submit dialogs." },
  { q: "File uploads require…", options: ["method=\"get\"", "type=\"binary\"", "enctype=\"multipart/form-data\""], answer: 2,
    explain: "Without it the file input submits only the filename." },
  { q: "A placeholder can replace a label.", options: ["True — it's visible text", "False — it vanishes on typing and isn't announced as a label", "Only for search boxes"], answer: 1,
    explain: "Placeholder is a HINT. Every input needs a real <label for> — clicking it also focuses the field." },
  { q: "Radio buttons form a group when they…", options: ["Share the same name", "Are inside one div", "Share the same id"], answer: 0,
    explain: "Same name = one-of-many + arrow-key navigation. The group's question lives in fieldset/legend." },
  { q: "The question above a radio group ('Choose a plan') belongs in…", options: ["An h3", "<legend> inside the group's <fieldset>", "The first radio's label"], answer: 1,
    explain: "Screen readers announce legend + individual label together: 'Plan, Pro, radio button'." },
  { q: "Credit card / ZIP / OTP digit fields should use…", options: ["type=\"number\"", "type=\"tel\" always", "text with inputmode=\"numeric\" pattern=\"[0-9]*\""], answer: 2,
    explain: "type=number is for QUANTITIES: it eats leading zeros and scroll-wheel changes values. inputmode gives the numeric keyboard safely." },
  { q: "Wrong input type on mobile costs you…", options: ["Only aesthetics", "Nothing measurable", "The right keyboard — and measurably, conversions"], answer: 2,
    explain: "type=email brings the @-keyboard, tel brings the dial pad — friction is abandonment." },
  { q: "required + <option value=\"\">— choose —</option> in a select…", options: ["Is a hack", "Makes 'required' actually enforceable (empty value = unfilled)", "Disables the select"], answer: 1,
    explain: "If the first option has a real value, the select is 'filled' from the start and required never triggers." },
  { q: "A <button> inside a form with no type attribute…", options: ["Defaults to type=\"submit\" — it WILL submit the form", "Defaults to type=\"button\"", "Does nothing"], answer: 0,
    explain: "Why did 'Show password' submit the form? Exactly this. Secondary buttons need explicit type=\"button\"." },
  { q: "pattern=\"[A-Za-z0-9-]{4,}\" is…", options: ["Anchored automatically — must match the ENTIRE value", "Case-insensitive", "Matched anywhere in the value"], answer: 0,
    explain: "Pair it with title=\"…\" to explain the rule in the native error bubble." },
  { q: ":user-invalid is better than :invalid because…", options: ["It waits until the user has interacted — no red borders on pristine forms", "It's faster", "It validates on the server"], answer: 0,
    explain: ":invalid applies immediately on load to every empty required field — hostile UX." },
  { q: "setCustomValidity(\"Passwords don't match\") does what?", options: ["Shows a toast", "Blocks typing", "Marks the field invalid with your message in native validation UI"], answer: 2,
    explain: "Set it to \"\" to clear. This is the Constraint Validation API extending native validation." },
  { q: "novalidate on a form…", options: ["Disables native validation UI — the API still works for custom rendering", "Disables the Constraint Validation API entirely", "Skips server validation"], answer: 0,
    explain: "Teams with custom error designs keep checkValidity()/validity state and render their own messages." },
  { q: "autocomplete=\"new-password\" vs \"current-password\"?", options: ["Managers GENERATE on new-password, FILL on current-password", "One is deprecated", "Aliases"], answer: 0,
    explain: "Correct tokens make password managers work perfectly — signup vs login fields differ." },
  { q: "autocomplete=\"one-time-code\" enables…", options: ["Passkey login", "SMS OTPs autofilling on mobile", "Emailed magic links"], answer: 1,
    explain: "The OS offers the incoming code straight into the field — massive login-flow win." },
  { q: "Disabling autocomplete on login forms 'for security'…", options: ["Is required by PCI", "Fights password managers — the best security tool users have", "Helps security"], answer: 1,
    explain: "Browsers largely ignore it on password fields anyway, precisely for this reason." },
  { q: "Client-side validation is…", options: ["Sufficient with HTTPS", "UX only — anyone can bypass it with curl/DevTools; the server re-validates", "A security boundary if thorough"], answer: 1,
    explain: "The trust boundary is the server. Always both: instant feedback client-side, enforcement server-side." },
  { q: "<datalist> provides…", options: ["A dropdown that restricts choices", "Multi-select", "Suggestions on a free-text input (list attribute)"], answer: 2,
    explain: "Unlike select, the user may type anything — the options are hints." },
]},
);
