// HTML quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Semantic HTML & Media",
  desc: "Landmarks, article/section, details/dialog, video, audio, iframes",
  questions: [
  { q: "Content that would stand alone if extracted (a blog post, a product card) belongs in…", options: ["<section>", "<article>", "<aside>"], answer: 1,
    explain: "article = self-contained and redistributable; section = a themed grouping WITH a heading; aside = tangential content." },
  { q: "The main visual difference between div-soup and semantic markup for sighted users is…", options: ["Huge — semantics change rendering", "None — the difference is for screen readers, SEO, reader modes, and maintainers", "Semantic pages load faster"], answer: 1,
    explain: "Both render identically. Semantics create the landmark/outline map that assistive tech and crawlers navigate." },
  { q: "A page's major navigation blocks should use…", options: ["<nav> for every list of links", "<nav> only for major navigation, labeled when repeated", "<menu>"], answer: 1,
    explain: "Not every link list is a nav. With two navs, aria-label=\"Main\" / \"Breadcrumbs\" tells users which is announced." },
  { q: "An accordion without JavaScript uses…", options: ["<details> + <summary>", "<div> + display:none", "<dialog>"], answer: 0,
    explain: "details/summary gives open/close behavior, keyboard support, and an open attribute — free." },
  { q: "dialog.showModal() gives you what for free?", options: ["Just styling", "Focus trapping, Escape-to-close, ::backdrop, top-layer rendering", "Nothing — it's sugar over div"], answer: 1,
    explain: "The dialog element solves the hardest modal problems (focus management!) natively." },
  { q: "Navigating somewhere = <a href>; performing an action = …", options: ["<a href=\"#\">", "<button>", "<div onclick>"], answer: 1,
    explain: "The button-vs-link law. Clickable divs are invisible to keyboards and screen readers; href=\"#\" scrolls to top and pollutes history." },
  { q: "Autoplaying video works in modern browsers only when…", options: ["The file is small", "It's muted (+ playsinline on iOS)", "It's an MP4"], answer: 1,
    explain: "Browsers block autoplay with sound — that's why every hero background video is silent." },
  { q: "preload=\"metadata\" on <video> loads…", options: ["The whole file", "Only duration/dimensions — saving mobile data for videos nobody plays", "The first 10 seconds"], answer: 1,
    explain: "Full preload on a page of videos burns users' data plans for content they may never play." },
  { q: "Captions for <video> are provided by…", options: ["<track kind=\"captions\" src=\"….vtt\">", "A JS library", "The subtitles attribute"], answer: 0,
    explain: "WebVTT tracks; legally required in many markets (ADA/EAA) and useful to every viewer in a loud café." },
  { q: "Multiple <source> elements inside <video> exist so that…", options: ["All formats download", "The browser picks the FIRST format it supports (WebM smaller, MP4 universal)", "Playback is faster"], answer: 1,
    explain: "Order matters: put the most efficient format first, the universal fallback last." },
  { q: "The poster attribute on <video>…", options: ["Sets the thumbnail shown before playback", "Adds a watermark", "Is deprecated"], answer: 0,
    explain: "Without it users stare at a black rectangle until they press play." },
  { q: "An <iframe> embedding third-party content should have…", options: ["title, loading=\"lazy\", and sandbox", "Just src", "allow-everything"], answer: 0,
    explain: "title for a11y, lazy for performance, sandbox to limit what the embedded page can do." },
  { q: "sandbox=\"allow-scripts\" on an iframe means…", options: ["Scripts + same-origin access", "Scripts may run but the frame stays cross-origin-isolated (no cookies/DOM of your page)", "Nothing loads"], answer: 1,
    explain: "Exactly how this site's Playground executes user code safely. Never combine allow-scripts + allow-same-origin on untrusted content." },
  { q: "Slotted heading rule: <section> without a heading is…", options: ["Invalid HTML", "Valid but a smell — section exists to group content UNDER a heading", "Required by SEO"], answer: 1,
    explain: "If there's no natural heading, you probably wanted a div (pure grouping) instead." },
  { q: "<figure> + <figcaption> is for…", options: ["Any image", "Content referenced from the text (charts, diagrams, code listings) with a caption", "Decorative icons"], answer: 1,
    explain: "The caption is programmatically associated — screen readers announce it with the figure." },
  { q: "<time datetime=\"2026-07-05\">last Sunday</time> exists because…", options: ["It styles dates", "Humans read one form, machines (crawlers, calendars, JS) read the ISO attribute", "Dates need timezones"], answer: 1,
    explain: "Human-friendly text + machine-readable data in one element." },
  { q: "Which heading structure is correct inside an <article>?", options: ["Start at whatever h-level looks right", "One heading per article, always h1", "Continue the page's outline — e.g., h2 for article titles under the page h1"], answer: 2,
    explain: "The document outline is page-wide; skipping levels or restarting at h1 mid-page confuses AT users navigating by heading level." },
  { q: "The <address> element is for…", options: ["Any postal address", "Contact information for the nearest article/body author", "Geolocation"], answer: 1,
    explain: "Semantic: 'how to contact the author of this content' — not a generic address container." },
  { q: "Reader mode in browsers (and Pocket etc.) extracts content using…", options: ["AI only", "Semantic structure — article, headings, paragraphs", "The largest div"], answer: 1,
    explain: "Sites with clean semantics get beautiful reader-mode rendering; div-soup gets mangled or rejected." },
  { q: "Embedding YouTube with youtube-nocookie.com is an example of…", options: ["Faster streaming", "Privacy-conscious embedding (no tracking cookies until play)", "A CDN trick"], answer: 1,
    explain: "Small choices in embed URLs affect your site's GDPR/privacy posture." }
]},

{ title: "Quiz 7 · Accessibility (ARIA)",
  desc: "Screen readers, keyboard nav, ARIA attributes, focus management",
  questions: [
  { q: "The first rule of ARIA is…", options: ["Add roles to everything", "Don't use ARIA when a native element exists", "ARIA is required for HTML5 validity"], answer: 1,
    explain: "<button> ships keyboard handling, focus, and semantics for free; role=\"button\" on a div recreates it badly in 4+ attributes plus JS." },
  { q: "An icon-only button (✕) needs…", options: ["title=\"Close\"", "aria-label=\"Close\"", "Nothing — the icon is obvious"], answer: 1,
    explain: "aria-label gives it an accessible name; title only shows on mouse hover and isn't reliably announced." },
  { q: "aria-hidden=\"true\" is for…", options: ["Hiding decorative elements from screen readers while keeping them visible", "Hiding elements visually", "Password fields"], answer: 0,
    explain: "Visual hiding is CSS; aria-hidden removes it from the accessibility tree only. Never put it on focusable elements." },
  { q: "A dropdown trigger should expose its state with…", options: ["class=\"open\"", "aria-expanded=\"true|false\"", "data-open"], answer: 1,
    explain: "Screen readers announce 'button, collapsed' / 'expanded' — the class name is invisible to them." },
  { q: "Dynamic updates like '3 results found' are announced via…", options: ["alert()", "aria-live=\"polite\" regions", "Focus jumping to the text"], answer: 1,
    explain: "Live regions announce changes without moving focus. polite waits for a pause; assertive/role=alert interrupts — reserve for errors." },
  { q: "Which tabindex value is essentially always a bug?", options: ["0", "-1", "3"], answer: 2,
    explain: "Positive values create a parallel tab order that fights the DOM order. 0 = join natural order; -1 = programmatically focusable only." },
  { q: "After closing a modal, focus should…", options: ["Go to body", "Return to the element that opened it", "Stay wherever it was inside the modal"], answer: 1,
    explain: "Otherwise keyboard users are dumped at the top of the page and must Tab through everything again." },
  { q: "The 'skip to content' link exists because…", options: ["SEO rewards it", "Keyboard users otherwise Tab through 40 nav links on EVERY page", "It looks professional"], answer: 1,
    explain: "First focusable element, visually hidden until focused, jumps to #main." },
  { q: "outline: none on :focus without a replacement…", options: ["Is fine if the design is clean", "Makes keyboard navigation invisible — a WCAG failure", "Improves performance"], answer: 1,
    explain: "Use :focus-visible for keyboard-only rings if mouse-click rings bother the design team." },
  { q: "Automated a11y checkers (Lighthouse, axe) catch about…", options: ["~30% of issues — they can't judge meaning or logic", "~95% of issues", "All WCAG violations"], answer: 0,
    explain: "They can't tell if alt text is meaningful or focus order is logical. Manual keyboard + screen-reader passes are required." },
  { q: "Alt text for a chart image should…", options: ["Say 'chart'", "Convey the FINDING: 'Revenue grew 40% QoQ in 2025'", "List every data point"], answer: 1,
    explain: "Describe meaning, not appearance. Complex charts also get a data table or long description nearby." },
  { q: "Minimum touch-target size per accessibility guidance is about…", options: ["24×24px", "44×44px", "60×60px"], answer: 1,
    explain: "Pad small icons/links — motor-impaired users (and everyone on a bumpy bus) miss small targets." },
  { q: "role=\"alert\" differs from aria-live=\"polite\" in that it…", options: ["Is quieter", "Interrupts immediately — for urgent errors only", "Only works on forms"], answer: 1,
    explain: "Overusing assertive announcements trains users to ignore them." },
  { q: "Form inputs are associated with their labels via…", options: ["Proximity", "<label for=\"id\"> or wrapping the input in the label", "aria-describedby only"], answer: 1,
    explain: "Clicking the label focuses the field; screen readers announce it. Placeholder text is NOT a label — it vanishes on typing." },
  { q: "A screen-reader-only text utility (.sr-only) works by…", options: ["display:none", "Clipping a 1px absolutely-positioned box (visible to AT, invisible on screen)", "opacity:0"], answer: 1,
    explain: "display:none and visibility:hidden remove content from the accessibility tree too — the clip technique doesn't." },
  { q: "Communicating error state by turning the border red alone violates…", options: ["Nothing", "'Don't rely on color alone' — add an icon + message", "The box model"], answer: 1,
    explain: "~8% of men have color-vision deficiency; icon + text + color covers everyone." },
  { q: "prefers-reduced-motion matters because…", options: ["It saves battery", "Vestibular disorders make animated UIs physically unpleasant — respecting it is required", "It's an iOS-only quirk"], answer: 1,
    explain: "Provide a reduced-motion path: kill parallax, large translations, and auto-playing motion." },
  { q: "The accessibility tree is…", options: ["A React feature", "The browser's parallel structure (from DOM + ARIA) that assistive tech consumes", "A testing library"], answer: 1,
    explain: "Inspect it in DevTools → Accessibility panel; it shows exactly what a screen reader will announce." },
  { q: "aria-describedby is used to…", options: ["Rename an element", "Attach supplementary text (hints, error messages) to a field's announcement", "Group radio buttons"], answer: 1,
    explain: "Name (label) says WHAT it is; description adds details like 'Must be at least 12 characters'." },
  { q: "Landmark navigation lets screen-reader users…", options: ["Read faster", "Jump between header/nav/main/aside/footer with single keystrokes", "Skip ads automatically"], answer: 1,
    explain: "This only works if the landmarks exist — the payoff of semantic structure." }
]},

{ title: "Quiz 8 · SEO & Performance",
  desc: "Meta tags, Open Graph, structured data, Core Web Vitals, loading",
  questions: [
  { q: "The strongest on-page SEO signal among these is…", options: ["meta keywords", "The <title> element", "The favicon"], answer: 1,
    explain: "meta keywords has been ignored by Google since ~2009. Title + content + links carry ranking weight." },
  { q: "meta description affects…", options: ["Ranking directly", "Click-through rate (it's the snippet under the blue link)", "Page speed"], answer: 1,
    explain: "~155 chars; compelling copy here wins clicks even at the same rank position." },
  { q: "rel=\"canonical\" solves…", options: ["Broken links", "Duplicate-content dilution when one page is reachable at multiple URLs (?utm=…, http/https, trailing slash)", "Pagination"], answer: 1,
    explain: "It tells crawlers which URL is 'the real one' so ranking signals consolidate." },
  { q: "Open Graph tags (og:title, og:image…) control…", options: ["Google ranking", "The preview card when your link is shared in Slack/LinkedIn/iMessage", "Browser caching"], answer: 1,
    explain: "No og:image = gray placeholder card = dramatically fewer clicks. Standard size: 1200×630." },
  { q: "The ⭐ star ratings and prices in Google results come from…", options: ["Paying Google", "JSON-LD structured data (schema.org)", "og: tags"], answer: 1,
    explain: "Product/Review/Recipe/JobPosting markup → rich results. Validate with Google's Rich Results Test." },
  { q: "A staging site should be kept out of Google via…", options: ["Not linking to it", "noindex (meta robots) and/or auth — robots.txt alone doesn't remove indexed pages", "A small font"], answer: 1,
    explain: "robots.txt blocks crawling but the URL can still be indexed from external links; noindex removes it." },
  { q: "Crawlers follow links primarily through…", options: ["<a href> elements", "onclick handlers", "sitemap.xml only"], answer: 0,
    explain: "JS-only navigation (clickable divs) is invisible or expensive for crawlers — real hrefs matter." },
  { q: "LCP measures…", options: ["Time to first byte", "When the largest content element becomes visible (good < 2.5s)", "JavaScript execution time"], answer: 1,
    explain: "Usually the hero image or headline. Fix: preload the hero, don't lazy-load it, server fast." },
  { q: "CLS is caused by…", options: ["Slow servers", "Content shifting after load — images without dimensions, injected banners, late fonts", "Too much JavaScript"], answer: 1,
    explain: "Reserve space: width/height on media, fixed slots for ads/embeds, font-display strategy." },
  { q: "INP measures…", options: ["Install time", "Responsiveness to user interactions across the page's lifetime (good < 200ms)", "Network latency"], answer: 1,
    explain: "Long main-thread tasks are the killer — break them up, ship less JS." },
  { q: "The one image you should NEVER lazy-load is…", options: ["Footer logos", "The LCP/hero image", "Avatars"], answer: 1,
    explain: "Lazy-loading it delays the page's main content — the most common self-inflicted LCP regression. Use fetchpriority=\"high\" instead." },
  { q: "rel=\"preload\" vs rel=\"prefetch\":", options: ["Same thing", "preload = needed for THIS page now; prefetch = probably needed for the NEXT page, fetch when idle", "prefetch is deprecated"], answer: 1,
    explain: "Preload only 2–3 truly critical resources (hero image, fonts) — preloading everything cancels the benefit." },
  { q: "Fonts loaded without font-display: swap cause…", options: ["Nothing visible", "FOIT — invisible text while the font downloads", "Layout shift only"], answer: 1,
    explain: "swap shows fallback text immediately, then swaps the webfont in. Pair with preloading the font file." },
  { q: "width and height attributes on <img> prevent CLS because…", options: ["They make images load faster", "The browser reserves the exact space before the image arrives", "They enable caching"], answer: 1,
    explain: "CSS max-width:100%; height:auto keeps them responsive while the ratio is known upfront." },
  { q: "srcset with width descriptors (400w, 800w…) lets the browser…", options: ["Pick a format", "Download the smallest file adequate for the layout slot and screen density", "Zoom images"], answer: 1,
    explain: "Phones stop downloading desktop-sized images — often the single biggest byte saving on media-heavy pages." },
  { q: "<picture> with AVIF, WebP, JPEG sources exists because…", options: ["Browsers differ in format support; first supported source wins — modern formats are 30–50% smaller", "It loads all three", "JPEG is deprecated"], answer: 0,
    explain: "AVIF/WebP first, JPEG as the universal fallback in the <img>." },
  { q: "Third-party scripts (analytics, chat, ads) typically…", options: ["Are free performance-wise", "Cost more main-thread time than your own code combined — audit and async/defer them", "Only affect SEO"], answer: 1,
    explain: "Every tag manager pixel is someone else's code on your users' phones. Measure, prune, load late." },
  { q: "Which loading order for app JS is correct in 2026?", options: ["<script src> at top of head", "type=\"module\" (or defer) in head", "Inline everything"], answer: 1,
    explain: "Parallel download, execute after parse, order preserved — no parser blocking." },
  { q: "hreflang annotations tell search engines…", options: ["The page's coding language", "Which language/region variants of a page exist so users get the right one", "To translate the page"], answer: 1,
    explain: "Prevents the German page ranking for French users and vice versa." },
  { q: "The correct first step of any performance work is…", options: ["Rewrite in a faster framework", "Measure (Lighthouse/DevTools/RUM) and fix the top bottleneck", "Add a CDN"], answer: 1,
    explain: "Optimizing without measuring is superstition — the bottleneck is rarely where you guess." }
]},

{ title: "Quiz 9 · Security & Web Components",
  desc: "XSS, CSP, sanitization, Shadow DOM, custom elements",
  questions: [
  { q: "el.innerHTML = userComment is dangerous because…", options: ["It's slow", "Attacker markup executes — e.g., <img onerror=…> runs JS for every visitor", "It breaks caching"], answer: 1,
    explain: "Stored XSS: one malicious comment → code running in every session. No <script> tag needed; event handlers suffice." },
  { q: "The safe default for rendering user text is…", options: ["innerHTML with a regex filter", "textContent (or framework auto-escaping)", "escape() from 1999"], answer: 1,
    explain: "textContent never parses HTML. React {expr}, Vue/Angular {{ }} do this automatically." },
  { q: "Reflected XSS differs from stored XSS in that…", options: ["It's harmless", "The payload arrives via the URL/request and is echoed back, rather than saved for everyone", "It only affects admins"], answer: 1,
    explain: "Delivered through crafted links; stored XSS persists in your database and hits every visitor." },
  { q: "When you MUST render user-authored rich HTML, you should…", options: ["Trust it after login", "Sanitize with DOMPurify/Sanitizer API using an allowlist", "Strip <script> tags with a regex"], answer: 1,
    explain: "Blocklists always lose (onerror=, javascript: URLs, mXSS parser tricks). Allowlist sanitizers are the only sane path." },
  { q: "javascript:alert(1) in an href demonstrates why…", options: ["Links need titles", "User-supplied URLs must be scheme-validated (http/https/mailto only)", "alert is deprecated"], answer: 1,
    explain: "URL sanitization is separate from HTML sanitization — both are required." },
  { q: "CSP protects you even after injection because…", options: ["It removes the payload", "Injection ≠ execution: inline script is refused, exfil domains can't connect, a report fires", "It encrypts the page"], answer: 1,
    explain: "Defense in depth: the payload sits inert in the DOM. Start with Report-Only mode, then enforce." },
  { q: "CSP nonces work by…", options: ["Hashing the page", "A per-response random value on allowed <script> tags; injected scripts lack it and are blocked", "Blocking all scripts"], answer: 1,
    explain: "script-src 'nonce-R4nd0m' + <script nonce=\"R4nd0m\"> — yours run, attacker's don't." },
  { q: "frame-ancestors 'none' prevents…", options: ["Your page loading iframes", "Anyone iframing YOUR page — killing clickjacking overlays", "Popups"], answer: 1,
    explain: "Clickjacking = your page in an invisible iframe under fake buttons. This directive (or X-Frame-Options) ends it." },
  { q: "HttpOnly on the session cookie means…", options: ["HTTPS only", "JavaScript cannot read it — even successful XSS can't steal the session token", "It expires hourly"], answer: 1,
    explain: "Pair with Secure (HTTPS-only transmission) and SameSite=Lax (CSRF mitigation)." },
  { q: "Auth tokens in localStorage are risky because…", options: ["localStorage is slow", "ANY script running on the page (i.e., XSS) can read them", "They expire"], answer: 1,
    explain: "That's why HttpOnly cookies are preferred for sessions despite the CSRF considerations they bring." },
  { q: "X-Content-Type-Options: nosniff stops…", options: ["Slow uploads", "Browsers 'sniffing' an uploaded .txt into executable HTML", "Ad blockers"], answer: 1,
    explain: "Without it, user-uploaded files can become XSS vectors when served." },
  { q: "Trusted Types is…", options: ["A TypeScript feature", "A CSP-enforced rule: innerHTML-style sinks THROW unless values pass a registered sanitizing policy", "A lint rule"], answer: 1,
    explain: "Turns 'did everyone remember to sanitize?' into a browser guarantee. Google runs it on Gmail/Docs." },
  { q: "A custom element's tag name must…", options: ["Start with x-", "Contain a hyphen", "Be uppercase"], answer: 1,
    explain: "The hyphen namespaces custom elements away from every current and future standard tag." },
  { q: "Shadow DOM's core promise is…", options: ["Faster rendering", "Style/DOM encapsulation — page CSS can't break the component, component CSS can't leak", "Server rendering"], answer: 1,
    explain: "The global-CSS-collision problem, solved at the platform level." },
  { q: "What DOES cross the shadow boundary (by design)?", options: ["All page selectors", "CSS custom properties and ::part() — the deliberate theming API", "IDs"], answer: 1,
    explain: "Expose --knobs and part=\"\" hooks; everything else stays sealed." },
  { q: "Events from inside shadow DOM…", options: ["Never escape", "Bubble out retargeted — outside listeners see the host element as target", "Crash listeners"], answer: 1,
    explain: "Encapsulation holds: outsiders can't see internal structure even in event targets." },
  { q: "Slotted content (<h3 slot=\"title\">) is styled by…", options: ["The component only", "The page (it stays in light DOM); the component can only reach it via ::slotted()", "Neither"], answer: 1,
    explain: "Projection, not adoption: consumer content remains the consumer's." },
  { q: "Declarative Shadow DOM (<template shadowrootmode>) matters because…", options: ["It's shorter", "The parser builds shadow roots from HTML — SSR for web components, no JS for first paint", "It disables slots"], answer: 1,
    explain: "Before it, web components were invisible until JS ran — a hydration/SEO problem." },
  { q: "Web components vs frameworks — the senior answer is…", options: ["WCs replace React", "Different layers: WCs for shared design-system primitives; frameworks for app state/routing/data flow", "Frameworks always win"], answer: 1,
    explain: "Big-company pattern: Lit-based design system consumed by React/Angular/Vue product teams." },
  { q: "Shadow DOM as a SECURITY boundary is…", options: ["Equivalent to an iframe", "Not one — closed mode is obscurity, not isolation; untrusted code needs a sandboxed iframe", "Stronger than CSP"], answer: 1,
    explain: "Style isolation ≠ security isolation. Never run untrusted code relying on shadow DOM." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 mixed questions across the whole track — interview difficulty",
  questions: [
  { q: "A page renders differently ONLY on one legacy URL. Most likely cause:", options: ["CDN issue", "Missing doctype → quirks mode on that page", "Old jQuery"], answer: 1,
    explain: "The classic symptom: same CSS, one page computes the old box model. Check the first line of the HTML." },
  { q: "Every relative link on a page 404s after a refactor. First thing to check:", options: ["The server", "A <base href> tag someone added", "DNS"], answer: 1,
    explain: "base rewrites how EVERY relative URL resolves — one tag, sitewide breakage." },
  { q: "Search results show your page's URL instead of a headline. Why?", options: ["Slow server", "Missing/empty <title>", "No sitemap"], answer: 1,
    explain: "Title is the headline; without it engines synthesize something (often the URL or an H1 fragment)." },
  { q: "Form data isn't reaching the server for one field. The field probably lacks…", options: ["An id", "A name attribute", "A label"], answer: 1,
    explain: "name is the submission key. id is for labels/anchors/JS — no name, no data." },
  { q: "Passwords appeared in the server access logs. The form was using…", options: ["method=\"post\"", "method=\"get\" — data went into the URL", "AJAX"], answer: 1,
    explain: "GET puts fields in the query string: logged, cached, in history, in Referer headers. Mutations use POST." },
  { q: "Your modal has z-index 9999 yet renders under the header. Likely cause:", options: ["Header has z-index 10000", "An ancestor with transform/opacity created a stacking context that caps the modal", "Browser bug"], answer: 1,
    explain: "z-index competes within stacking contexts. (Yes, this is a CSS question — real exams cross-cut.) Portals/top-layer (dialog) avoid it." },
  { q: "Clicking a row's Delete button also opens the row link. Missing:", options: ["preventDefault on the row", "stopPropagation on the button click (or better: check the event target in delegation)", "A bigger button"], answer: 1,
    explain: "Bubbling means the click reaches both handlers — handle it deliberately." },
  { q: "The page 'jumps' as it loads on mobile. Highest-probability fix:", options: ["Reduce JS", "Add width/height to every image and reserve embed slots (CLS)", "Use HTTP/3"], answer: 1,
    explain: "Unsized media is the dominant CLS cause; the fix is one attribute pair per image." },
  { q: "A React SSR page logs 'Hydration failed'. A likely culprit:", options: ["Too much CSS", "Rendering new Date()/Math.random() during render — server HTML ≠ client HTML", "Wrong npm version"], answer: 1,
    explain: "Non-deterministic render output differs between server and client; defer it to a post-hydration effect or mark client-only." },
  { q: "Your comment section executes attacker JS. The fastest correct fix:", options: ["Regex-strip <script>", "Switch rendering to textContent (or sanitize if rich text is required)", "Ban the user"], answer: 1,
    explain: "Blocklists lose to onerror= and mXSS. Change the sink, then add CSP as the net." },
  { q: "The hero image paints at 4.2s. Best combined fix:", options: ["Lazy-load it", "preload + fetchpriority=\"high\", AVIF/WebP sources, correct srcset size", "Move it to JS"], answer: 1,
    explain: "Fetch it earlier (preload/priority), make it smaller (format/size) — and never lazy-load the LCP element." },
  { q: "A keyboard user can't operate your custom dropdown built from divs. The RIGHT fix:", options: ["Add tabindex=5", "Rebuild on native <select>/<button> + proper ARIA pattern (or details) with keyboard handlers", "Tell them to use a mouse"], answer: 1,
    explain: "Recreating widgets means owning ALL their keyboard/ARIA behavior — native elements give it free." },
  { q: "Which trio is announced usefully by screen readers?", options: ["div.header, div.nav, div.content", "header, nav aria-label=\"Main\", main", "b, i, u"], answer: 1,
    explain: "Landmarks + labels = single-keystroke navigation between page regions." },
  { q: "og:image is set but Slack previews still show no image. Common cause:", options: ["Slack is down", "Relative URL — social scrapers need an absolute https URL (and ~1200×630 size)", "Wrong file name"], answer: 1,
    explain: "Scrapers don't resolve relative paths against your page reliably; alway ship absolute og URLs." },
  { q: "You need one component to work in React, Angular, AND a legacy JSP app. Reach for…", options: ["Three implementations", "A web component (Lit) with tokens/parts as its styling API", "An iframe widget"], answer: 1,
    explain: "Framework-agnostic by standard; each host consumes it as plain HTML." },
  { q: "The team wants inline onclick handlers everywhere 'for speed'. Your CSP counterpoint:", options: ["They're fine", "unsafe-inline for scripts guts CSP's XSS protection; use addEventListener + nonced scripts", "Only performance matters"], answer: 1,
    explain: "Inline handlers force 'unsafe-inline', which is exactly what injected payloads need to run." },
  { q: "1M product pages, mostly static, occasional price changes. Rendering strategy:", options: ["Pure SSR", "ISR/on-demand revalidation (static speed + freshness)", "Pure CSR"], answer: 1,
    explain: "Build-time SSG of 1M pages is too slow; per-request SSR wastes compute on unchanged pages." },
  { q: "Which is TRUE about <script async>?", options: ["Preserves document order", "Executes the moment it arrives — only safe for independent scripts like analytics", "Waits for DOMContentLoaded"], answer: 1,
    explain: "Order-dependent app code with async = intermittent race-condition bugs." },
  { q: "A dialog opened with .showModal() gives you which for free?", options: ["Focus trap, Escape close, ::backdrop, top layer", "Form validation", "Animation"], answer: 0,
    explain: "The hardest modal a11y problems are solved natively — recreating them in a div is 200 lines of liability." },
  { q: "The single highest-leverage habit this track taught:", options: ["Memorize all tags", "Semantic-first HTML: meaning in markup buys a11y, SEO, reader modes, and maintainability at once", "Always use frameworks"], answer: 1,
    explain: "Every advanced topic (ARIA, SEO, performance, security) got easier because the structure was honest. That's the award-winning habit. 🏆" }
]}
);
