// database-concepts quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · MVCC, Locking & Latches",
  desc: "Visibility rules, undo logs, vacuum, wraparound, lock conflict matrix, deadlocks",
  questions: [
  { q: "MVCC's central promise is that…", options: ["Only one transaction runs at a time", "Writers block readers", "Readers never block writers and writers never block readers"], answer: 2,
    explain: "Each reader sees a consistent snapshot instead of waiting for a lock." },
  { q: "Postgres implements MVCC by…", options: ["Keeping old versions in an undo log", "Storing every row version in the table itself, stamped with xmin/xmax", "Locking rows"], answer: 1,
    explain: "That is why UPDATE creates a new tuple and why VACUUM is needed to clean up." },
  { q: "InnoDB and Oracle instead keep old versions in…", options: ["A separate undo log, reconstructing old versions on demand", "The table", "The WAL"], answer: 0,
    explain: "The trade: no table bloat, but long-running readers can blow up undo and cause 'snapshot too old'." },
  { q: "A row version is visible to a snapshot when…", options: ["It exists on disk", "Its ctid is low", "Its xmin committed before the snapshot and its xmax did not commit before it"], answer: 2,
    explain: "Visibility is a function of transaction IDs, not physical position." },
  { q: "VACUUM cannot remove a dead row version if…", options: ["The row was deleted", "The table is large", "An older transaction or replication slot might still need to see it"], answer: 2,
    explain: "Long-running transactions, idle-in-transaction sessions, abandoned slots and stale prepared transactions are the four classic blockers." },
  { q: "Transaction ID wraparound risk arises because…", options: ["The WAL fills", "The XID space is 32-bit and old rows must be frozen before it wraps", "IDs are strings"], answer: 1,
    explain: "Postgres will refuse writes to protect data if autovacuum has been prevented from freezing for long enough." },
  { q: "Hint bits exist to…", options: ["Lock rows", "Compress rows", "Cache the commit status of a transaction on the row, avoiding repeated commit-log lookups"], answer: 2,
    explain: "This is why the first SELECT after a bulk load can be surprisingly write-heavy." },
  { q: "A snapshot gives you consistent reads but NOT…", options: ["Durability", "Atomicity", "Serializability — write skew is still possible at Repeatable Read"], answer: 2,
    explain: "Snapshot isolation ≠ serializable; SSI adds the extra conflict detection." },
  { q: "The difference between a lock and a latch is…", options: ["None", "Locks protect logical data for a transaction's duration; latches protect in-memory structures for a few instructions", "Latches last longer"], answer: 1,
    explain: "Latches are not deadlock-detected — ordering discipline prevents latch deadlocks instead." },
  { q: "Row locks in Postgres are stored…", options: ["In a central lock table", "In the tuple itself (xmax), which is why there is no lock escalation", "In the WAL"], answer: 1,
    explain: "Engines with an in-memory lock table (e.g. SQL Server) must escalate row locks to page/table locks under memory pressure." },
  { q: "'Lock escalation' is a problem because…", options: ["A batch of row locks becomes a table lock, suddenly blocking unrelated transactions", "It aborts transactions", "It frees memory"], answer: 0,
    explain: "Postgres avoids it structurally; MySQL/SQL Server users must design around it." },
  { q: "SELECT … FOR UPDATE is used to…", options: ["Speed up reads", "Skip MVCC", "Take a row lock so a read-modify-write cycle is not lost"], answer: 2,
    explain: "Without it, two concurrent read-then-write cycles silently lose one update." },
  { q: "FOR UPDATE SKIP LOCKED is the standard trick for…", options: ["Reporting", "Queue workers claiming rows without contending on the same head row", "Backups"], answer: 1,
    explain: "Each worker takes the next unlocked row instead of queuing behind one." },
  { q: "A deadlock is resolved by…", options: ["Restarting the server", "Waiting longer", "The engine detecting the cycle and aborting one transaction as the victim"], answer: 2,
    explain: "Applications must therefore be prepared to retry on the deadlock error code." },
  { q: "The most effective way to prevent deadlocks is…", options: ["Longer timeouts", "Acquiring locks in a consistent order across all code paths", "More indexes"], answer: 1,
    explain: "Two code paths updating the same two rows in opposite order is the textbook cause." },
  { q: "An ACCESS EXCLUSIVE lock (e.g. from a careless ALTER TABLE) can cause an outage because…", options: ["It rewrites the table", "It queues behind running queries and every later query queues behind IT", "It is slow to acquire"], answer: 1,
    explain: "The lock queue is the mechanism — a short DDL behind a long SELECT stalls the whole table." },
  { q: "The safe way to run DDL on a busy table is to…", options: ["Run it at any time", "Set a short lock_timeout and retry, so you never park an exclusive lock in the queue", "Disable locks"], answer: 1,
    explain: "Fail fast instead of building a queue behind you." },
  { q: "Advisory locks are useful for…", options: ["Row-level integrity", "Index maintenance", "Application-level mutual exclusion (e.g. one cron worker at a time) using the DB as a coordinator"], answer: 2,
    explain: "They are not tied to any row and are the pragmatic distributed-lock choice when you already have Postgres." },
  { q: "A shared (read) lock conflicts with…", options: ["Other shared locks", "Nothing", "Exclusive locks only"], answer: 2,
    explain: "The conflict matrix is what determines which operations can run concurrently." },
  { q: "'Idle in transaction' sessions are dangerous because…", options: ["They consume CPU", "They cause deadlocks", "They hold their snapshot and locks open, blocking vacuum and DDL indefinitely"], answer: 2,
    explain: "Set idle_in_transaction_session_timeout — this is one of the most common production footguns." },
]},
{ title: "Quiz 7 · The Query Planner",
  desc: "The five stages, rewriting, join-order search, pushdown, generic plans",
  questions: [
  { q: "The five stages of query processing are…", options: ["Lock, read, write, commit, log", "Compile, link, load, run, exit", "Parse, rewrite, plan, execute, return"], answer: 2,
    explain: "The rewrite stage is the one most people forget — it expands views, RLS and some CTEs." },
  { q: "The parser's job stops at…", options: ["Choosing indexes", "Reading pages", "Turning text into a syntax tree and resolving names/types"], answer: 2,
    explain: "It knows nothing about cost — a syntactically valid query can still be catastrophically slow." },
  { q: "A view is handled by…", options: ["The executor", "Materialising it always", "The rewriter, which inlines its definition into the query before planning"], answer: 2,
    explain: "Which is why a view is not inherently slow — but nested views can produce enormous rewritten trees." },
  { q: "Row-Level Security policies are applied…", options: ["In the client", "During rewriting, as extra predicates on the query", "After results return"], answer: 1,
    explain: "That is also why an RLS predicate that isn't sargable can quietly wreck a plan." },
  { q: "Since Postgres 12, a plain CTE is…", options: ["Always inlined", "Inlined by default when referenced once and side-effect free, unless MATERIALIZED is specified", "Always materialised"], answer: 1,
    explain: "Pre-12 the optimisation fence was unconditional — a classic source of upgrade-time plan changes." },
  { q: "The number of possible join orders for n tables grows…", options: ["Factorially, which is why the search must be bounded", "Not at all", "Linearly"], answer: 0,
    explain: "Dynamic programming handles small n; beyond a threshold the planner switches strategy." },
  { q: "Postgres switches to GEQO (a genetic algorithm) when…", options: ["A query is slow", "Statistics are stale", "The join count exceeds geqo_threshold (default 12)"], answer: 2,
    explain: "GEQO finds a good-enough plan quickly but is non-deterministic — plans can differ run to run." },
  { q: "Predicate pushdown means…", options: ["Filters are applied as early as possible, shrinking rows before joins", "Filters run last", "Filters are removed"], answer: 0,
    explain: "Fewer rows entering a join is the single most valuable transformation the planner makes." },
  { q: "The planner chooses a plan based on…", options: ["Estimated costs derived from statistics", "Actual row counts", "Query text length"], answer: 0,
    explain: "Every bad plan is ultimately either a bad estimate or a bad cost constant." },
  { q: "A prepared statement's generic plan is a problem when…", options: ["Parameter values have wildly different selectivities, so one plan cannot suit all", "Parameters are always similar", "The query is short"], answer: 0,
    explain: "plan_cache_mode = force_custom_plan is the escape hatch for skewed parameters." },
  { q: "Postgres decides between custom and generic plans by…", options: ["Comparing average custom-plan cost against the generic cost after ~5 executions", "Random choice", "Always generic"], answer: 0,
    explain: "So the sixth execution of a prepared statement can suddenly get slower — a genuinely confusing symptom." },
  { q: "Subquery flattening/decorrelation turns a correlated subquery into…", options: ["A join, so the planner can pick any join algorithm", "A CTE", "A loop"], answer: 0,
    explain: "When it fails, you get a per-row subplan — the plan-shape signature of an accidental N+1." },
  { q: "EXPLAIN without ANALYZE shows…", options: ["Nothing useful", "The plan and estimates only, without running the query", "Real execution times"], answer: 1,
    explain: "EXPLAIN ANALYZE actually executes it — dangerous on a DML statement unless wrapped in a rolled-back transaction." },
  { q: "In EXPLAIN ANALYZE output, comparing 'rows=' estimated vs actual reveals…", options: ["Buffer usage", "Estimation error, the root cause of most bad plans", "Lock waits"], answer: 1,
    explain: "Find the deepest node where the ratio first blows up — that is where the plan went wrong." },
  { q: "A node's 'loops=' value matters because…", options: ["It counts locks", "It is cosmetic", "Reported per-loop time and rows must be multiplied by loops for the true total"], answer: 2,
    explain: "A '0.05ms' inner node executed 200,000 times is 10 seconds — the single most misread number in EXPLAIN." },
  { q: "The planner ignoring a perfectly good index usually means…", options: ["It estimated that too many rows match, making a sequential scan cheaper", "The index is broken", "Indexes are disabled"], answer: 0,
    explain: "Often correct! When it is wrong, the fix is statistics, not a hint." },
  { q: "Join elimination lets the planner…", options: ["Reorder columns", "Cache results", "Skip a join whose table contributes no columns and cannot change row counts (guaranteed by a FK)"], answer: 2,
    explain: "A concrete example of constraints improving performance, not just integrity." },
  { q: "The executor's volcano/iterator model works by…", options: ["Each node pulling rows one at a time from its children", "Running nodes in parallel always", "Materialising every intermediate result"], answer: 0,
    explain: "It is why LIMIT can make a whole plan cheap — the pipeline stops early." },
  { q: "A LIMIT changes plan choice because…", options: ["It filters rows", "Fast-start plans (index scan in ORDER BY order) beat plans that must sort everything", "It disables joins"], answer: 1,
    explain: "That is also why LIMIT queries can degrade dramatically when the matching rows are rare." },
  { q: "The right first response to a bad plan is to…", options: ["Rewrite the schema", "Add a hint", "Check estimates vs actuals and the freshness of statistics"], answer: 2,
    explain: "Hints freeze today's mistake into the codebase; fixing estimates helps every query." },
]},
{ title: "Quiz 8 · Cost Models & Join Algorithms",
  desc: "Cost formulas, statistics, independence assumption, the three join methods, hash spills",
  questions: [
  { q: "A plan's cost in Postgres is expressed in…", options: ["Rows", "Milliseconds", "Arbitrary units anchored to seq_page_cost = 1.0"], answer: 2,
    explain: "Costs are comparable to each other, not to wall-clock time." },
  { q: "random_page_cost defaults to 4.0, meaning…", options: ["There are 4 disks", "Pages are 4KB", "Random reads are assumed 4× a sequential page read"], answer: 2,
    explain: "On SSD/NVMe, 1.1–2.0 is far more realistic — leaving it at 4 biases the planner against index scans." },
  { q: "The classic seq-scan cost formula is roughly…", options: ["rows × 2", "pages only", "(pages × seq_page_cost) + (rows × cpu_tuple_cost) + (rows × cpu_operator_cost per filter)"], answer: 2,
    explain: "Being able to compute it by hand demystifies the planner's choices completely." },
  { q: "Selectivity is…", options: ["The estimated fraction of rows a predicate keeps", "Index depth", "The number of columns"], answer: 0,
    explain: "Row estimates are just selectivity multiplied by the table's row count." },
  { q: "For a common value, the planner's estimate comes from…", options: ["The most-common-values (MCV) list and its frequencies", "A random guess", "The index only"], answer: 0,
    explain: "For values outside the MCV list, it interpolates from the histogram instead." },
  { q: "n_distinct is used to estimate…", options: ["Equality selectivity for non-MCV values (roughly 1/n_distinct)", "Table size", "Join order"], answer: 0,
    explain: "A badly-sampled n_distinct on a large table is a very common source of catastrophic underestimates." },
  { q: "The independence assumption causes underestimates when…", options: ["Predicates are on correlated columns (e.g. city and postcode)", "Columns are unrelated", "There is one predicate"], answer: 0,
    explain: "It multiplies selectivities, so 0.1 × 0.1 = 0.01 even when the two conditions are the same fact twice." },
  { q: "The fix for correlated-column misestimates in Postgres is…", options: ["CREATE STATISTICS with dependencies / ndistinct on the column group", "More indexes", "Increasing work_mem"], answer: 0,
    explain: "It gives the planner real multi-column statistics instead of the independence guess." },
  { q: "Estimation errors are dangerous mainly because they…", options: ["Propagate and multiply up the plan tree, so a small error at a leaf becomes huge at the top", "Stay constant", "Only affect EXPLAIN"], answer: 0,
    explain: "That is why you diagnose from the deepest wrong node upward." },
  { q: "A nested loop join costs roughly…", options: ["outer × inner always with no index", "outer + inner", "outer_rows × inner_lookup_cost"], answer: 2,
    explain: "It is excellent when the outer side is tiny and the inner side is indexed — and disastrous when the outer estimate was wrong." },
  { q: "A nested loop over a large outer side is usually a symptom of…", options: ["Too much RAM", "A row-count underestimate on the outer relation", "A missing LIMIT"], answer: 1,
    explain: "The planner thought it was joining 5 rows; it is joining 500,000. Fix the estimate." },
  { q: "A hash join works by…", options: ["Building a hash table on the smaller input, then probing it with the larger", "Sorting both inputs", "Scanning both repeatedly"], answer: 0,
    explain: "It is the workhorse for large unsorted equi-joins." },
  { q: "Hash joins support…", options: ["Range conditions only", "Any join condition", "Equality conditions only"], answer: 2,
    explain: "A range or inequality join must fall back to nested loop or merge." },
  { q: "When the hash table exceeds work_mem, the join…", options: ["Spills to disk in batches, adding significant I/O", "Fails", "Switches to nested loop"], answer: 0,
    explain: "'Batches: 1' in EXPLAIN means it fit; more than 1 means it spilled." },
  { q: "work_mem is allocated…", options: ["Once per connection", "Per sort/hash node per query — so one query can use many multiples of it", "Per database"], answer: 1,
    explain: "This is why a global increase can trigger OOM; set it per-role or per-session for heavy jobs." },
  { q: "A merge join requires…", options: ["Both inputs sorted on the join key (often free from index order)", "A single row", "Hash tables"], answer: 0,
    explain: "It is the natural pick when both sides already arrive sorted, and it handles inequality merge cases." },
  { q: "Severe skew in a hash join key hurts because…", options: ["Hashing fails", "One bucket receives a disproportionate share of rows, degrading toward a scan", "Memory is freed"], answer: 1,
    explain: "A single dominant key (a 'null customer', a default tenant) is the usual real-world cause." },
  { q: "HashAggregate vs GroupAggregate differ in that GroupAggregate…", options: ["Requires sorted input but uses bounded memory", "Cannot spill", "Is always faster"], answer: 0,
    explain: "The planner picks based on estimated group count and available work_mem." },
  { q: "Calibrating random_page_cost should be based on…", options: ["Measured storage behaviour and cache residency on your actual hardware", "Defaults", "Table count"], answer: 0,
    explain: "With most of the working set cached, effective random cost is close to sequential." },
  { q: "The most reliable way to confirm a cost-model theory is…", options: ["Reading source", "EXPLAIN (ANALYZE, BUFFERS) before and after the change, comparing estimates vs actuals", "Guessing"], answer: 1,
    explain: "Measure the node, not the whole query." },
]},
{ title: "Quiz 9 · Physical Design, OLTP vs OLAP & Engine Choice",
  desc: "Reversibility, key choice, columnar storage, engine personalities, choosing a database",
  questions: [
  { q: "The reversibility hierarchy says the most expensive decisions to change later are…", options: ["Column names", "Primary key choice, partitioning key, and the engine itself", "Index choices"], answer: 1,
    explain: "Spend your design effort where reversal is costly; indexes can be added or dropped any afternoon." },
  { q: "UUIDv7 is preferred over UUIDv4 for primary keys because…", options: ["It is shorter", "It is more random", "It is time-ordered, so inserts pack densely at the right edge of the B-tree"], answer: 2,
    explain: "You keep global uniqueness without the random-insert locality penalty." },
  { q: "Row width matters for OLTP because…", options: ["Wide rows are illegal", "It affects locking", "Narrower rows mean more rows per page and fewer pages read per query"], answer: 2,
    explain: "Column ordering and type choice are cheap wins here." },
  { q: "Choosing a partition key should be driven by…", options: ["Alphabetical order", "The predicates in your actual query logs, so partition pruning applies", "Table size only"], answer: 1,
    explain: "A partition key nobody filters on gives you all the complexity and none of the pruning." },
  { q: "Partitioning by itself does NOT…", options: ["Enable cheap bulk deletes", "Allow pruning", "Increase write capacity — all partitions still live on one node"], answer: 2,
    explain: "Confusing partitioning with sharding is a very common architectural error." },
  { q: "Columnar storage wins on analytics mainly because…", options: ["It has no indexes", "It compresses images", "A query reading 3 of 80 columns touches only those columns' data"], answer: 2,
    explain: "The I/O reduction is roughly the column-selection ratio, before compression even helps." },
  { q: "Run-length encoding compresses best when…", options: ["The column is sorted or has long runs of repeated values", "Values are random", "The column is unique"], answer: 0,
    explain: "Sort order inside a columnar file is a tuning knob, not an accident." },
  { q: "Dictionary encoding replaces values with…", options: ["Hashes", "Small integer codes into a dictionary of distinct values", "Nulls"], answer: 1,
    explain: "It also allows predicates to be evaluated directly on the codes." },
  { q: "Vectorised execution speeds up analytics by…", options: ["Skipping the planner", "Using more threads only", "Processing batches of values per operator call instead of one row at a time"], answer: 2,
    explain: "It amortises interpreter overhead and lets the CPU use SIMD and cache lines properly." },
  { q: "Columnar storage is a poor fit for…", options: ["Aggregations", "Single-row lookups and frequent small updates", "Full scans"], answer: 1,
    explain: "Fetching one whole row means touching every column segment." },
  { q: "The pragmatic 'middle ground' for a mixed workload is usually…", options: ["Two databases from day one", "One OLTP database plus a read replica or a columnar extension, until scale demands separation", "Only OLAP"], answer: 1,
    explain: "Premature separation buys you a data pipeline and a consistency problem you did not need yet." },
  { q: "SQLite's defining characteristic is that it…", options: ["Is a client/server system", "Runs in-process with no server, making it ideal for embedded and single-writer use", "Is columnar"], answer: 1,
    explain: "Its write concurrency ceiling (one writer) is the trade you accept for that simplicity." },
  { q: "DuckDB is best described as…", options: ["A distributed OLTP store", "A key-value cache", "An in-process columnar analytics engine — 'SQLite for OLAP'"], answer: 2,
    explain: "It excels at local analytical queries over Parquet/CSV without a cluster." },
  { q: "InnoDB's clustered primary key means a wide PK is costly because…", options: ["Every secondary index stores the full primary key value", "It slows the WAL", "It cannot be indexed"], answer: 0,
    explain: "A concrete case of engine internals dictating schema design." },
  { q: "The six questions that characterise an engine include storage structure, concurrency control and…", options: ["Durability mechanism, indexing options, execution model and distribution model", "Vendor and licence only", "Logo colour"], answer: 0,
    explain: "Answering those six for any new database tells you far more than a feature matrix." },
  { q: "Postgres is a sensible default choice because…", options: ["It is competent across a very wide range of workloads, so you rarely design yourself into a corner", "It is fastest at everything", "It has no trade-offs"], answer: 0,
    explain: "'Boring, broadly capable, well understood' beats a specialised store you will outgrow differently." },
  { q: "A proof of concept is only useful if…", options: ["It is allowed to fail — with a defined failure criterion decided beforehand", "It is short", "It always succeeds"], answer: 0,
    explain: "A PoC that cannot fail is a procurement ritual, not an evaluation." },
  { q: "Costs that database evaluations most often miss are…", options: ["Licence fees", "Operational burden: expertise, backup/restore, upgrades, monitoring and on-call", "Disk price"], answer: 1,
    explain: "The second database in a stack roughly doubles the operational surface for one team." },
  { q: "An Architecture Decision Record is valuable mainly because it records…", options: ["The context and trade-offs, so a future reader knows when the decision should be revisited", "The final schema", "Who approved it"], answer: 0,
    explain: "Decisions without recorded context get cargo-culted forever or reversed blindly." },
  { q: "The strongest signal that you genuinely need a specialised store is…", options: ["Team preference", "A conference talk", "A measured workload dimension your current engine demonstrably cannot meet after tuning"], answer: 2,
    explain: "Measure first — most 'we need a new database' problems are missing-index problems." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Full-track exam: storage, durability, concurrency, query processing and design",
  questions: [
  { q: "The page is the unit of I/O, so reading a single 100-byte row costs…", options: ["Nothing", "At least one full page read", "100 bytes"], answer: 1,
    explain: "Everything about database performance follows from this one fact." },
  { q: "A HOT update is prevented by…", options: ["Changing an indexed column, or having no free space on the page", "A missing WAL", "A small row"], answer: 0,
    explain: "Fillfactor and restrained indexing are the two levers that keep updates HOT." },
  { q: "Sequential primary keys pack B-tree pages densely because…", options: ["They are shorter", "They avoid the WAL", "Inserts concentrate at the right edge instead of splitting random leaves"], answer: 2,
    explain: "UUIDv7 buys the same benefit while staying globally unique." },
  { q: "A bloom filter can tell you…", options: ["The exact value", "A key is definitely absent, or possibly present", "A key is definitely present"], answer: 1,
    explain: "False positives cost an unnecessary read; false negatives would break correctness and never occur." },
  { q: "Going from a 99% to 95% buffer-pool hit rate multiplies physical reads by about…", options: ["No change", "1.04×", "5×"], answer: 2,
    explain: "1% miss → 5% miss. Always reason in miss rate." },
  { q: "The write-ahead rule requires that…", options: ["Log records reach durable storage before the corresponding data page does", "Data pages flush first", "Both flush at commit"], answer: 0,
    explain: "Force-at-commit then applies specifically to the commit record." },
  { q: "Full-page writes exist to protect against…", options: ["Deadlocks", "Replication lag", "Torn pages from a crash mid-write"], answer: 2,
    explain: "They are also a major share of WAL volume after each checkpoint." },
  { q: "A long-running idle transaction is dangerous because it…", options: ["Fills the buffer pool", "Uses CPU", "Holds a snapshot that blocks vacuum, causing bloat and wraparound pressure"], answer: 2,
    explain: "Set idle_in_transaction_session_timeout in every production deployment." },
  { q: "Postgres has no lock escalation because row locks are…", options: ["Held in a fixed-size lock table", "Stored in the tuple itself, so their count costs no shared memory", "Not supported"], answer: 1,
    explain: "Engines with an in-memory lock table must escalate under pressure." },
  { q: "The most common root cause of a catastrophically bad plan is…", options: ["A missing hint", "A row-count misestimate, often from correlated columns or stale statistics", "Too much RAM"], answer: 1,
    explain: "Fix the estimate (ANALYZE, CREATE STATISTICS) rather than pinning the plan." },
  { q: "In EXPLAIN ANALYZE, an inner node's cost must be multiplied by…", options: ["Nothing", "Its loops value, to get the true total", "The row width"], answer: 1,
    explain: "The single most misread number in a plan." },
  { q: "'Batches: 8' on a Hash node means…", options: ["The hash table exceeded work_mem and spilled to disk", "Eight threads", "Eight joins"], answer: 0,
    explain: "Raise work_mem for that session, or reduce the build side." },
  { q: "The independence assumption produces underestimates for…", options: ["Sorted data", "Predicates on correlated columns, since selectivities are multiplied", "Single predicates"], answer: 1,
    explain: "CREATE STATISTICS teaches the planner the real dependency." },
  { q: "A nested loop join is a great choice when…", options: ["There is no index", "The outer side is small and the inner side has a usable index", "Both sides are huge"], answer: 1,
    explain: "And a disaster when the outer estimate was wrong by orders of magnitude." },
  { q: "Levelled compaction trades write amplification for…", options: ["Better read and space amplification", "Worse reads", "Loss of durability"], answer: 0,
    explain: "Size-tiered makes the opposite trade; time-window suits TTL'd time series." },
  { q: "Tombstone accumulation in an LSM hurts…", options: ["The WAL", "Range scans, which must read and skip them until compaction removes them", "Writes"], answer: 1,
    explain: "Delete-heavy queue workloads are a classic LSM anti-pattern." },
  { q: "Columnar storage's biggest weakness is…", options: ["Compression", "Single-row lookups and small frequent updates", "Aggregation"], answer: 1,
    explain: "Reconstructing one whole row requires touching every column segment." },
  { q: "Partitioning helps most with…", options: ["Write scaling across machines", "Reducing index size to zero", "Pruning and cheap bulk data lifecycle (DETACH/DROP a partition)"], answer: 2,
    explain: "Sharding, not partitioning, is what adds write capacity across nodes." },
  { q: "The decision that is hardest to reverse later is…", options: ["Adding an index", "The primary key and partitioning strategy", "A column name"], answer: 1,
    explain: "Design effort belongs where reversal is expensive." },
  { q: "The best default reasoning tool this track gives you is…", options: ["Memorised parameter values", "Trusting defaults", "Asking how many pages a operation touches, whether they are cached, and what it costs to make them durable"], answer: 2,
    explain: "Pages, cache residency and durability ordering explain nearly every behaviour in the stack." },
]},
);
