// Database Concepts & Architecture quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · How a Database Stores Data",
  desc: "The six layers, the memory/disk gap, pages as the unit of I/O, the RUM conjecture",
  questions: [
  { q: "A database reads and writes data in units of…", options: ["Single rows", "Fixed-size pages (typically 4–16KB)", "Whole tables"], answer: 1,
    explain: "The page is the atom of I/O. Reading one 200-byte row still pulls its entire page off disk." },
  { q: "The reason pages exist at all is…", options: ["Encryption alignment", "Storage devices and the OS transfer fixed-size blocks — per-row I/O would be catastrophically slow", "SQL requires it"], answer: 1,
    explain: "Amortising a fixed per-I/O cost over many rows is the whole point." },
  { q: "The rough latency gap between RAM and an NVMe SSD read is…", options: ["About 2×", "Roughly 1000× (~100ns vs ~100µs)", "They are equal"], answer: 1,
    explain: "This gap is why the buffer pool exists and why hit rate dominates performance." },
  { q: "The RUM conjecture says you can optimise for at most two of…", options: ["Reads, Updates, Memory", "Rows, Users, Metrics", "Replication, Uptime, Migration"], answer: 0,
    explain: "Every storage-engine design is a pick-two: extra indexes buy reads with update and space cost." },
  { q: "Adding a secondary index primarily trades…", options: ["Nothing — it is free", "Faster reads for slower writes and more space", "Durability for speed"], answer: 1,
    explain: "Every write must now maintain the index too. RUM in its most everyday form." },
  { q: "In the layered view, the component that turns SQL text into a plan is…", options: ["The buffer pool", "The query processor (parser → planner → executor)", "The WAL"], answer: 1,
    explain: "Storage layers sit below it; the planner never touches disk directly." },
  { q: "The buffer pool sits between…", options: ["The client and the parser", "The executor and the disk, caching pages in RAM", "The WAL and the replica"], answer: 1,
    explain: "It is the layer that makes the memory/disk gap survivable." },
  { q: "'The database is slow' most often actually means…", options: ["CPU is saturated", "The workload is missing cache and hitting disk far more than expected", "The network is down"], answer: 1,
    explain: "Random I/O amplification is the usual culprit — measure hit rate before tuning SQL." },
  { q: "A row that is physically larger than a page is handled by…", options: ["Rejecting the insert", "Splitting oversized values out into overflow/TOAST storage", "Compressing the whole table"], answer: 1,
    explain: "Postgres calls this TOAST; other engines use overflow pages. The main row keeps a pointer." },
  { q: "Sequential reads beat random reads on SSD mainly because…", options: ["SSDs have platters", "Read-ahead and larger effective transfer sizes amortise per-request overhead", "Random reads are forbidden"], answer: 1,
    explain: "The gap narrowed vs spinning disks but did not vanish — it is now ~an order of magnitude, not three." },
  { q: "Durability at the storage layer ultimately depends on…", options: ["Replication", "Data reaching stable storage before the commit is acknowledged", "The client retrying"], answer: 1,
    explain: "This is the write-ahead rule — everything else is an optimisation around it." },
  { q: "Column-store vs row-store is fundamentally a decision about…", options: ["SQL dialect", "Which access pattern gets locality — whole rows vs whole columns", "Licensing"], answer: 1,
    explain: "Locality is the design lever; everything downstream (compression, vectorisation) follows from it." },
  { q: "'Fanout' in a storage context means…", options: ["Replica count", "How many children a tree node holds — driving how shallow the tree is", "Fan speed"], answer: 1,
    explain: "High fanout is why a B-tree over a billion rows is only ~4 levels deep." },
  { q: "The reason a database does not simply mmap the file and let the OS cache it is…", options: ["mmap is illegal", "It loses control over eviction order and, critically, over when pages hit disk (durability ordering)", "mmap is slower always"], answer: 1,
    explain: "Some engines do use mmap (SQLite optionally); most want explicit control over write ordering for WAL correctness." },
  { q: "Free-space tracking inside a table exists so that…", options: ["The table can shrink", "Inserts can find a page with room without scanning the whole file", "Indexes stay sorted"], answer: 1,
    explain: "Postgres uses a Free Space Map; without it every insert would be a search." },
  { q: "In the six-layer model, the layer directly responsible for surviving a crash is…", options: ["The parser", "The write-ahead log and recovery manager", "The connection pool"], answer: 1,
    explain: "Recovery replays the log to restore a consistent state." },
  { q: "Storing a 12-byte value in a row does not usually cost 12 bytes because of…", options: ["Compression", "Per-row header overhead plus alignment padding", "Encryption"], answer: 1,
    explain: "A 24-byte header and 8-byte alignment can double the effective cost of narrow rows." },
  { q: "Which statement about the memory hierarchy is correct?", options: ["Cache line misses are irrelevant to databases", "Each level down is roughly an order of magnitude slower and larger", "Disk is faster than RAM for random access"], answer: 1,
    explain: "The hierarchy is the reason locality is the central design concern at every layer." },
  { q: "'Write amplification' means…", options: ["Logging too verbosely", "One logical write causing several physical writes (WAL, index updates, compaction)", "Duplicate INSERTs"], answer: 1,
    explain: "LSM compaction and full-page writes are the classic sources." },
  { q: "The single best mental habit for reasoning about DB performance is…", options: ["Memorising syntax", "Asking 'how many pages does this touch, and are they cached?'", "Counting rows"], answer: 1,
    explain: "Page counts and cache residency explain most latency surprises." }
]},

{ title: "Quiz 2 · Pages, Heap Files & Row Layout",
  desc: "Slotted pages, ctid, alignment padding, HOT updates, TOAST",
  questions: [
  { q: "A slotted page keeps a line pointer array so that…", options: ["Rows stay sorted", "Rows can move within the page without changing their external identifier", "Pages compress better"], answer: 1,
    explain: "Indexes point at the slot, not the byte offset — so compaction inside a page is free." },
  { q: "In Postgres a ctid identifies…", options: ["A transaction", "The physical location of a row version: (page number, slot number)", "A column type"], answer: 1,
    explain: "It changes whenever the row version moves — which is why indexes must be updated on most updates." },
  { q: "Alignment padding means a row of INT, BIGINT, INT columns may…", options: ["Be smaller than the sum of its columns", "Waste bytes on padding to satisfy 8-byte alignment", "Fail to insert"], answer: 1,
    explain: "Reordering wide-to-narrow can recover meaningful space on large tables." },
  { q: "Reordering columns from widest to narrowest helps because…", options: ["It aids readability only", "It minimises inter-column padding, shrinking the row and raising rows-per-page", "The planner prefers it"], answer: 1,
    explain: "More rows per page = fewer pages read = faster scans, for free." },
  { q: "A HOT (Heap-Only Tuple) update avoids…", options: ["Writing WAL", "Updating every index, by keeping the new row version on the same page and chaining it", "Taking a lock"], answer: 1,
    explain: "HOT requires no indexed column changed and free space on the page — hence fillfactor tuning." },
  { q: "HOT updates are blocked when…", options: ["The table has no primary key", "An indexed column changed, or the page has no free space", "The row is small"], answer: 1,
    explain: "Both conditions must hold; losing HOT is a common silent cause of index bloat." },
  { q: "Lowering fillfactor on a heavily-updated table…", options: ["Always wastes space with no benefit", "Reserves free space per page so more updates can stay HOT", "Disables the buffer pool"], answer: 1,
    explain: "You trade space for a much cheaper update path." },
  { q: "TOAST kicks in when…", options: ["A row exceeds a threshold (~2KB in Postgres) and values move to a side table", "A table has >100 columns", "A query is slow"], answer: 0,
    explain: "Large values are compressed and/or moved out of line, leaving a pointer in the main row." },
  { q: "A SELECT that does not reference a TOASTed column…", options: ["Still reads the TOAST data", "Avoids the extra TOAST fetch entirely", "Errors"], answer: 1,
    explain: "This is exactly why SELECT * on a table with big text columns can be dramatically slower." },
  { q: "The per-row header in Postgres is about…", options: ["2 bytes", "23–24 bytes plus alignment", "128 bytes"], answer: 1,
    explain: "For a table of two integers, the header dwarfs the data — this is why narrow tables surprise people." },
  { q: "A heap file is…", options: ["Sorted by primary key", "An unordered collection of pages — insert order, not key order", "A tree"], answer: 1,
    explain: "Postgres uses heaps; InnoDB instead clusters the table on the primary key." },
  { q: "In a clustered (index-organised) table the row data lives…", options: ["In a separate heap", "In the leaves of the primary key index", "In the WAL"], answer: 1,
    explain: "InnoDB works this way, which is why secondary indexes there store the PK, not a physical pointer." },
  { q: "A consequence of InnoDB's clustered layout is that a secondary index lookup…", options: ["Is always faster", "May need a second lookup through the primary key ('bookmark lookup')", "Cannot exist"], answer: 1,
    explain: "It also makes a wide primary key expensive — every secondary index embeds it." },
  { q: "Deleting a row in an MVCC engine typically…", options: ["Frees the space instantly", "Marks the row version dead; space is reclaimed later by vacuum/purge", "Rewrites the table"], answer: 1,
    explain: "This is why a big DELETE does not shrink the file." },
  { q: "Table bloat is best described as…", options: ["Too many columns", "Pages full of dead row versions that are no longer visible to anyone", "A large index"], answer: 1,
    explain: "It inflates every sequential scan because the dead space is still read." },
  { q: "NULL storage in Postgres uses…", options: ["A full-width placeholder value", "A null bitmap in the row header, so NULLs cost about a bit each", "A separate table"], answer: 1,
    explain: "Which is why a wide table of mostly-NULL columns is cheaper than it looks." },
  { q: "Variable-length columns are usually stored…", options: ["Fixed-width padded", "With a length prefix, after fixed-width columns", "In an index"], answer: 1,
    explain: "The length header is 1 byte for short values, 4 for long ones in Postgres." },
  { q: "The practical reason to care about rows-per-page is…", options: ["Disk price", "It directly determines how many pages a scan must read", "Backup speed only"], answer: 1,
    explain: "Halving row width nearly halves scan I/O." },
  { q: "An UPDATE that changes one indexed column out of ten indexes costs…", options: ["One index write", "Potentially all ten, since a new row version means every index must point at it", "Zero"], answer: 1,
    explain: "This is the strongest argument against over-indexing write-heavy tables." },
  { q: "Vacuum's job on the heap is to…", options: ["Rebuild indexes", "Reclaim space from dead row versions and update visibility metadata", "Re-sort rows"], answer: 1,
    explain: "It also advances the frozen horizon, which prevents transaction ID wraparound." }
]},

{ title: "Quiz 3 · B-Trees & LSM-Trees",
  desc: "Fanout and depth, splits, key density, bloom filters, compaction strategies",
  questions: [
  { q: "A B+Tree keeps all actual data pointers in…", options: ["The root", "The leaf level, with internal nodes holding only separator keys", "Every node equally"], answer: 1,
    explain: "Separator-only internal nodes maximise fanout, which minimises depth." },
  { q: "With ~8-byte keys on 8KB pages, a B-tree over a billion rows is roughly…", options: ["30 levels deep", "3–4 levels deep", "1 level deep"], answer: 1,
    explain: "Fanout of several hundred means depth grows logarithmically and stays tiny in practice." },
  { q: "The top levels of a hot B-tree are effectively free to traverse because…", options: ["They are compressed", "They are almost always resident in the buffer pool", "They are skipped"], answer: 1,
    explain: "A 4-level lookup usually costs one physical read — the leaf." },
  { q: "A page split happens when…", options: ["A query is slow", "An insert does not fit in the target leaf, so it is divided into two", "Vacuum runs"], answer: 1,
    explain: "Splits propagate upward if the parent is also full." },
  { q: "Inserting monotonically increasing keys (e.g. a sequence) produces…", options: ["Random splits and half-empty pages", "Right-most splits and densely packed pages", "No splits"], answer: 1,
    explain: "This is why serial/identity keys pack far better than random UUIDv4." },
  { q: "Random UUIDv4 primary keys hurt B-trees because…", options: ["They are too long only", "Inserts hit random leaves — poor cache locality and pages left ~50–70% full", "They cannot be indexed"], answer: 1,
    explain: "UUIDv7 (time-ordered) recovers most of the sequential-insert benefit." },
  { q: "Index bloat mainly comes from…", options: ["Too many columns", "Splits and dead entries leaving pages partly empty over time", "Compression"], answer: 1,
    explain: "REINDEX CONCURRENTLY rebuilds densely; monitoring index size vs row count catches it." },
  { q: "B-link trees add right-sibling pointers so that…", options: ["Range scans are possible", "A concurrent reader that lands on a just-split page can follow the link instead of blocking", "Splits are avoided"], answer: 1,
    explain: "This is the standard high-concurrency B-tree refinement — readers never take tree-wide locks." },
  { q: "An LSM-tree absorbs writes first into…", options: ["A leaf page on disk", "An in-memory memtable (plus the WAL for durability)", "A bloom filter"], answer: 1,
    explain: "Writes become sequential appends — the core LSM advantage." },
  { q: "When a memtable fills, it is…", options: ["Discarded", "Flushed to disk as an immutable, sorted SSTable", "Merged into the WAL"], answer: 1,
    explain: "Immutability is what makes compaction and snapshot reads simple." },
  { q: "A bloom filter lets an LSM read…", options: ["Return the value directly", "Skip SSTables that definitely do not contain the key", "Sort keys"], answer: 1,
    explain: "It has false positives but never false negatives — a 'maybe' still costs a read." },
  { q: "Roughly, ~10 bits per key of bloom filter gives a false-positive rate near…", options: ["50%", "1%", "0%"], answer: 1,
    explain: "Sizing is the classic memory-vs-read-amplification knob in an LSM." },
  { q: "Size-tiered compaction optimises for…", options: ["Read latency", "Write throughput, at the cost of more space and read amplification", "Space only"], answer: 1,
    explain: "Levelled compaction flips the trade: better reads and space, more write amplification." },
  { q: "Levelled compaction's main cost is…", options: ["Read amplification", "Write amplification — data is rewritten as it moves down levels", "Loss of durability"], answer: 1,
    explain: "RocksDB defaults to levelled for exactly the read/space benefit." },
  { q: "A tombstone in an LSM is…", options: ["A corrupted page", "A marker recording a delete, since SSTables are immutable", "A lock"], answer: 1,
    explain: "Tombstones only disappear once compaction has merged past every older version." },
  { q: "Scanning a range that was mass-deleted can be slow because…", options: ["The index is gone", "The scan must still read and skip accumulated tombstones", "Bloom filters block it"], answer: 1,
    explain: "The classic Cassandra 'tombstone hell' — delete-heavy queues are an LSM anti-pattern." },
  { q: "Time-window compaction is designed for…", options: ["Random-key OLTP", "Time-series data with TTLs, so whole SSTables expire together", "Graph data"], answer: 1,
    explain: "Dropping an entire file beats merging rows individually." },
  { q: "Compared with a B-tree, an LSM generally offers…", options: ["Better point reads, worse writes", "Better write throughput, more variable read latency", "Identical behaviour"], answer: 1,
    explain: "Read amplification depends on how many levels/files a key may live in." },
  { q: "A B-tree write is expensive relative to an LSM write because…", options: ["It is compressed", "It performs a random in-place page update rather than a sequential append", "It bypasses the WAL"], answer: 1,
    explain: "Both write a WAL record; the difference is the data-file update pattern." },
  { q: "Choosing between B-tree and LSM should be driven by…", options: ["Fashion", "The read/write ratio, key ordering, and delete patterns of the workload", "Language of the client"], answer: 1,
    explain: "Write-heavy append workloads favour LSM; read-heavy mixed OLTP favours B-tree." }
]},

{ title: "Quiz 4 · The Buffer Pool",
  desc: "Hit rate non-linearity, pinning, clock sweep, ring buffers, checkpoint storms",
  questions: [
  { q: "The buffer pool caches…", options: ["Query results", "Data and index pages in memory", "Connections"], answer: 1,
    explain: "It is a page cache, not a result cache — the same page serves many different queries." },
  { q: "Going from a 99% to a 98% hit rate is significant because…", options: ["It is a 1% slowdown", "Misses doubled — physical I/O, the expensive part, doubled", "Nothing changes"], answer: 1,
    explain: "Hit-rate effects are non-linear: reason about the miss rate, not the hit rate." },
  { q: "A pinned page is one that…", options: ["Is dirty", "Is currently in use and must not be evicted", "Is compressed"], answer: 1,
    explain: "Pin counts are held for the duration of a page access, then released." },
  { q: "A dirty page is…", options: ["Corrupted", "Modified in memory but not yet written to the data file", "Read-only"], answer: 1,
    explain: "Eviction of a dirty page requires writing it out first — and its WAL records before that." },
  { q: "Clock sweep approximates LRU by…", options: ["Sorting pages by age", "Cycling a pointer and decrementing usage counters, evicting when a counter hits zero", "Random eviction"], answer: 1,
    explain: "True LRU needs a global list with contended locking; clock sweep is cheap and close enough." },
  { q: "Strict LRU is avoided in real engines mainly because of…", options: ["Its memory cost", "Lock contention on the shared list at high concurrency", "Patents"], answer: 1,
    explain: "The list head becomes a hot spot every single access touches." },
  { q: "A large sequential scan uses a ring buffer so that…", options: ["It runs faster", "It does not evict the entire working set with pages it will never reuse", "It skips the WAL"], answer: 1,
    explain: "Without it, one analytics scan trashes the cache for every OLTP query." },
  { q: "Postgres conventionally sets shared_buffers to about…", options: ["25% of RAM, relying on the OS cache too", "75% of RAM", "1GB always"], answer: 0,
    explain: "InnoDB, which does not double-cache through the OS, is typically set near 70–80%." },
  { q: "The reason Postgres and InnoDB differ on that ratio is…", options: ["Licensing", "Postgres also benefits from the OS page cache (double buffering); InnoDB uses direct I/O", "Postgres is older"], answer: 1,
    explain: "Sizing advice is engine-specific for a concrete architectural reason." },
  { q: "A checkpoint's job is to…", options: ["Delete the WAL", "Flush dirty pages so recovery does not have to replay from the beginning of time", "Vacuum tables"], answer: 1,
    explain: "It bounds recovery time — the trade-off is I/O spikes." },
  { q: "A 'checkpoint storm' is…", options: ["A replication failure", "A burst of write I/O when many dirty pages are flushed at once, stalling queries", "A deadlock"], answer: 1,
    explain: "Spreading the checkpoint (checkpoint_completion_target) smooths the burst." },
  { q: "Raising checkpoint frequency…", options: ["Speeds recovery but increases steady-state write I/O", "Slows recovery", "Has no effect"], answer: 0,
    explain: "It is a straight trade between recovery time objective and running write cost." },
  { q: "Measuring cache effectiveness in Postgres uses…", options: ["EXPLAIN only", "blks_hit vs blks_read in pg_stat_database, or per-query with EXPLAIN (ANALYZE, BUFFERS)", "OS top"], answer: 1,
    explain: "BUFFERS output shows shared hit vs read per plan node — the most actionable form." },
  { q: "A 'hit' recorded by the database may still be a physical read because…", options: ["Statistics lie", "It may have been served from the OS page cache, which the DB counts as a miss it didn't do itself", "Hits are always memory"], answer: 1,
    explain: "In Postgres a 'read' may be satisfied by the OS cache — so misses are not necessarily disk seeks." },
  { q: "The working set is…", options: ["All data ever stored", "The subset of pages actually touched by the live workload", "The WAL"], answer: 1,
    explain: "Performance falls off a cliff when the working set stops fitting in the buffer pool, not when the database gets big." },
  { q: "Adding RAM stops helping once…", options: ["Immediately", "The working set already fits — further memory caches cold data nobody reads", "The table has an index"], answer: 1,
    explain: "This is why 'just add RAM' has a ceiling you can predict." },
  { q: "The background writer exists to…", options: ["Run VACUUM", "Trickle dirty pages out so foreground queries rarely have to write during eviction", "Compress pages"], answer: 1,
    explain: "It shifts write cost off the query path." },
  { q: "A page must not be written to the data file before…", options: ["The next checkpoint", "Its WAL records are durable (the write-ahead rule)", "It is compressed"], answer: 1,
    explain: "Violating that ordering makes crash recovery unable to reconstruct a consistent state." },
  { q: "Prefetching / read-ahead helps most with…", options: ["Point lookups", "Sequential and bitmap scans, where upcoming pages are predictable", "Index root nodes"], answer: 1,
    explain: "Effective prefetch turns many small random reads into fewer large ones." },
  { q: "The most common real cause of a sudden 'the database got slow' incident is…", options: ["A new SQL keyword", "The working set outgrew memory, flipping cached reads into disk reads", "Too few connections"], answer: 1,
    explain: "The change is nonlinear and often follows ordinary data growth, not a code deploy." }
]},

{ title: "Quiz 5 · WAL, Recovery & Durability",
  desc: "Write-ahead rule, LSN, ARIES, torn pages, fsync, group commit",
  questions: [
  { q: "The write-ahead rule states…", options: ["Data pages are written before log records", "Log records describing a change must reach stable storage before the changed data page does", "Both are written simultaneously"], answer: 1,
    explain: "This single ordering constraint is what makes crash recovery possible." },
  { q: "Force-at-commit means…", options: ["The data pages must be flushed at commit", "The commit's log records must be durable before the client is told 'committed'", "Nothing is flushed"], answer: 1,
    explain: "Flushing a small sequential log is far cheaper than flushing scattered data pages." },
  { q: "An LSN is…", options: ["A lock identifier", "A monotonically increasing Log Sequence Number identifying a position in the WAL", "A row version"], answer: 1,
    explain: "It orders log records, stamps pages, and marks replication progress — three jobs from one counter." },
  { q: "Each data page stores the LSN of…", options: ["The first change ever", "The most recent log record that modified it", "The next checkpoint"], answer: 1,
    explain: "Recovery compares the page LSN with the log record LSN to decide whether to reapply a change." },
  { q: "ARIES 'repeating history' means recovery…", options: ["Skips uncommitted work", "Redoes ALL changes — including uncommitted ones — then undoes the losers", "Only undoes"], answer: 1,
    explain: "Redoing everything first restores the exact pre-crash state, which makes undo well-defined." },
  { q: "The three ARIES phases in order are…", options: ["Undo, Redo, Analysis", "Analysis, Redo, Undo", "Redo, Analysis, Undo"], answer: 1,
    explain: "Analysis rebuilds the dirty page table and transaction table from the last checkpoint." },
  { q: "A torn page is…", options: ["A deleted page", "A page partially written when a crash hit mid-write, since 8KB is not atomic on the device", "A locked page"], answer: 1,
    explain: "Devices guarantee atomicity at sector size (512B/4KB), not at database page size." },
  { q: "Postgres defends against torn pages with…", options: ["Checksums only", "Full-page writes: the first change to a page after a checkpoint logs the whole page", "Replication"], answer: 1,
    explain: "That is a major share of WAL volume — and why more frequent checkpoints inflate WAL." },
  { q: "InnoDB's equivalent mechanism is…", options: ["The doublewrite buffer", "The undo log", "The adaptive hash index"], answer: 0,
    explain: "Pages are written twice: first to a contiguous doublewrite area, then to their final home." },
  { q: "fsync() may still fail to guarantee durability if…", options: ["The file is small", "A disk or controller write cache lies about having persisted the data", "The table is unlogged"], answer: 1,
    explain: "Battery-backed cache or disabling the volatile write cache is the real fix." },
  { q: "Group commit improves throughput by…", options: ["Skipping fsync", "Batching many transactions' commit records into a single fsync", "Committing asynchronously"], answer: 1,
    explain: "Under load, per-commit latency stays similar while throughput rises sharply." },
  { q: "Postgres synchronous_commit = off means…", options: ["Data is never written", "Commits return before the WAL is flushed — you can lose the last few hundred ms on a crash, but not corrupt the DB", "Transactions are disabled"], answer: 1,
    explain: "A deliberate, bounded durability trade — atomicity and consistency are preserved." },
  { q: "The WAL also enables which of these features?", options: ["Only recovery", "Physical replication, PITR, and consistent snapshots/backups", "Query planning"], answer: 1,
    explain: "One log, four features — the classic argument for shipping the log rather than the pages." },
  { q: "Point-in-time recovery works by…", options: ["Reversing every INSERT", "Restoring a base backup and replaying archived WAL up to a chosen LSN or timestamp", "Copying replicas"], answer: 1,
    explain: "Retention of the WAL archive is what actually determines your recovery window." },
  { q: "A checkpoint bounds recovery time because…", options: ["It empties the WAL", "Redo can start from the checkpoint rather than the start of the log", "It locks the DB"], answer: 1,
    explain: "The classic RTO vs steady-state-I/O trade." },
  { q: "Logical replication differs from physical in that it ships…", options: ["Byte-level page changes", "Decoded row-level changes, allowing cross-version and partial replication", "SQL text always"], answer: 1,
    explain: "Physical is byte-exact and cheaper; logical is flexible and version-tolerant." },
  { q: "An UNLOGGED table trades…", options: ["Speed for correctness within a transaction", "Crash safety (it is truncated after a crash) for much faster writes", "Space for speed"], answer: 1,
    explain: "Appropriate only for regenerable data — staging, caches, scratch." },
  { q: "WAL volume grows most sharply when…", options: ["Reads increase", "Checkpoints are frequent, so more first-touch full-page writes occur", "Indexes are dropped"], answer: 1,
    explain: "Counter-intuitive but common: spreading checkpoints out reduces WAL bytes." },
  { q: "Recovery is idempotent because…", options: ["Log records are deleted after use", "The page LSN check skips changes already applied", "Redo runs once only"], answer: 1,
    explain: "This is what makes crashing during recovery safe." },
  { q: "The most reliable way to verify your durability story is…", options: ["Reading the docs", "Actually testing recovery — restore a backup and replay to a target time", "Enabling checksums"], answer: 1,
    explain: "An untested backup is a hypothesis, not a backup." }
]}
);
