// SQL quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Schema Design & Normalization",
  desc: "Keys, relationships, normal forms, denormalization, types",
  questions: [
  { q: "A FOREIGN KEY guarantees…", options: ["Uniqueness", "The referenced row EXISTS (referential integrity)", "An index in Postgres"], answer: 1,
    explain: "The DB blocks orphaning inserts/deletes; index the FK yourself in Postgres." },
  { q: "Many-to-many is modeled with…", options: ["An FK column", "A junction table (both FKs, one row per pairing)", "A JSON list"], answer: 1,
    explain: "It can also hold relationship attributes (enrolled_at)." },
  { q: "Normalization eliminates…", options: ["Joins", "Redundancy and its update/insert/delete anomalies", "Indexes"], answer: 1,
    explain: "Each fact stored once, referenced by key." },
  { q: "3NF in one phrase:", options: ["No NULLs", "Non-key columns depend on the key, the whole key, and nothing but the key", "One table"], answer: 1,
    explain: "No partial or transitive dependencies." },
  { q: "product1, product2, product3 columns violate…", options: ["3NF only", "1NF (repeating groups) — use a child table", "Nothing"], answer: 1,
    explain: "Also can't query/index a CSV-in-a-column." },
  { q: "Denormalization is…", options: ["Always wrong", "A deliberate read-optimization (duplication) with a sync strategy", "The default"], answer: 1,
    explain: "Counter columns, snapshots, materialized views — driven by measured reads." },
  { q: "Money columns should be…", options: ["FLOAT", "NUMERIC/DECIMAL (exact)", "TEXT"], answer: 1,
    explain: "Floats can't represent 0.10 exactly." },
  { q: "Timestamps should be stored as…", options: ["Local time strings", "TIMESTAMPTZ (UTC)", "Integers only"], answer: 1,
    explain: "Convert to local time at display, not storage." },
  { q: "A surrogate key is…", options: ["A natural unique value", "An artificial id (BIGSERIAL/UUID) as the PK", "A constraint"], answer: 1,
    explain: "Natural candidates (email) still get UNIQUE constraints." },
  { q: "Storing product price on order_items (snapshot) is…", options: ["Redundant always", "Correct history modeling — the price AT purchase time", "A bug"], answer: 1,
    explain: "Some 'denormalization' is actually correct temporal modeling." },
  { q: "One-to-one relationships use…", options: ["Junction tables", "FK + UNIQUE (or shared PK)", "Arrays"], answer: 1,
    explain: "UNIQUE makes the many side single." },
  { q: "JSONB columns are best for…", options: ["Everything", "Sparse/variable attributes — not core relational data", "Money"], answer: 1,
    explain: "You lose constraints/joins; index JSONB paths you query." },
  { q: "Update anomaly example:", options: ["Slow query", "User email duplicated across order rows → one missed update = inconsistency", "Deadlock"], answer: 1,
    explain: "The problem normalization exists to prevent." },
  { q: "Status fields are best constrained by…", options: ["App code only", "CHECK constraint or a lookup table", "Comments"], answer: 1,
    explain: "The DB enforces the allowed set." },
  { q: "UUID keys are chosen when…", options: ["Always", "Distributed generation / merge scenarios / non-guessability matter", "Never"], answer: 1,
    explain: "Trade-off: bigger indexes, random insert patterns (v7 mitigates)." },
  { q: "Premature denormalization causes…", options: ["Speed", "Sync bugs and complexity with no proven benefit", "Better design"], answer: 1,
    explain: "Normalize first; denormalize on measured need." },
  { q: "2NF addresses…", options: ["Transitive deps", "Partial dependency on part of a COMPOSITE key", "NULLs"], answer: 1,
    explain: "Non-key columns must depend on the whole key." },
  { q: "A lookup table (roles) vs a TEXT column:", options: ["Same", "Lookup centralizes values + enables FK integrity and metadata", "TEXT is safer"], answer: 1,
    explain: "CHECK is the lightweight alternative for small fixed sets." },
  { q: "ON DELETE options include…", options: ["CASCADE only", "CASCADE, RESTRICT, SET NULL — choose per relationship", "None"], answer: 1,
    explain: "What should happen to children when the parent goes?" },
  { q: "The design question 'entity or value?' decides…", options: ["Nothing", "Identity table vs embedded/snapshot columns (and record-vs-class in code)", "Storage engine"], answer: 1,
    explain: "The same value-vs-entity distinction as the Java/Python lessons." }
]},

{ title: "Quiz 7 · Indexes & Query Plans",
  desc: "B-trees, sargability, composite indexes, EXPLAIN",
  questions: [
  { q: "A B-tree index provides…", options: ["O(n) scans", "O(log n) lookups over sorted values", "Hashing"], answer: 1,
    explain: "Plus ranges, prefixes, and ORDER BY service." },
  { q: "Indexes cost…", options: ["Nothing", "Slower writes + storage (every write updates every index)", "Read speed"], answer: 1,
    explain: "A read-vs-write trade — index for measured patterns." },
  { q: "WHERE LOWER(email) = :x with an index on email…", options: ["Uses the index", "Can't (function on the column) — expression index or rewrite", "Errors"], answer: 1,
    explain: "CREATE INDEX ON users(LOWER(email)) fixes it." },
  { q: "LIKE '%gmail.com'…", options: ["Uses a B-tree", "Can't (no leading prefix) — full-text/trigram approaches instead", "Is invalid"], answer: 1,
    explain: "The tree is sorted by prefix." },
  { q: "Composite index (user_id, status, created_at) serves WHERE status='paid'…", options: ["Yes", "No — leftmost-prefix rule (user_id must be constrained first)", "Only with LIMIT"], answer: 1,
    explain: "Columns usable left→right; equality chain then one range." },
  { q: "Composite column order should be…", options: ["Alphabetical", "Equality-filtered (selective) columns first, range last", "Random"], answer: 1,
    explain: "Match your real WHERE shapes." },
  { q: "Seq Scan on a big table with a selective filter means…", options: ["All good", "Missing or defeated index", "Locked table"], answer: 1,
    explain: "The #1 thing to hunt in EXPLAIN." },
  { q: "Index Only Scan means…", options: ["Slow path", "Answered entirely from the index (covering) — no table visits", "Bitmap"], answer: 1,
    explain: "INCLUDE extra columns to achieve it." },
  { q: "Estimated rows wildly ≠ actual rows →", options: ["Fine", "Stale statistics — run ANALYZE", "Add RAM"], answer: 1,
    explain: "Bad estimates → bad plan choices." },
  { q: "EXPLAIN vs EXPLAIN ANALYZE:", options: ["Same", "ANALYZE actually executes and shows real times/rows", "ANALYZE is estimate-only"], answer: 1,
    explain: "Trust actuals; estimates lie." },
  { q: "A partial index (WHERE deleted_at IS NULL)…", options: ["Indexes everything", "Indexes only matching rows — smaller and faster for that predicate", "Is invalid"], answer: 1,
    explain: "Great for soft-delete and status subsets." },
  { q: "PK and UNIQUE constraints…", options: ["Need manual indexes", "Automatically create indexes", "Slow reads"], answer: 1,
    explain: "FKs do NOT auto-index in Postgres — add those." },
  { q: "GIN indexes are for…", options: ["Numbers", "JSONB, arrays, full-text search", "Simple equality"], answer: 1,
    explain: "B-tree is the default for scalar columns." },
  { q: "score + 10 > 100 vs score > 90:", options: ["Identical to the planner", "Only the bare-column form is sargable (index-usable)", "Neither uses indexes"], answer: 1,
    explain: "Keep the column clean on one side." },
  { q: "Unused indexes should be…", options: ["Kept forever", "Found (pg_stat_user_indexes) and dropped — they tax every write", "Rebuilt"], answer: 1,
    explain: "Index hygiene matters on write-heavy tables." },
  { q: "An index on a 3-value status column alone is…", options: ["Great", "Low-selectivity — the planner often ignores it; composite/partial instead", "Required"], answer: 1,
    explain: "Selectivity drives index usefulness." },
  { q: "ORDER BY created_at DESC LIMIT 10 with an index on created_at…", options: ["Sorts everything", "Reads 10 entries off the index — no sort step", "Errors"], answer: 1,
    explain: "Indexes serve ordering, not just filtering." },
  { q: "Type mismatch (text column compared to int)…", options: ["Fine", "Can defeat the index via implicit casts", "Speeds it up"], answer: 1,
    explain: "Match types in predicates and parameters." },
  { q: "BRIN indexes fit…", options: ["Random data", "Huge append-only tables with natural ordering (time-series)", "Small tables"], answer: 1,
    explain: "Tiny indexes storing block ranges." },
  { q: "The index workflow is…", options: ["Index everything", "Slow query → EXPLAIN ANALYZE → add/fix ONE index or rewrite → re-measure", "Guess"], answer: 1,
    explain: "Same measure-first discipline as all performance work." }
]},

{ title: "Quiz 8 · Isolation, Locking & Concurrency",
  desc: "Anomalies, levels, MVCC, optimistic vs pessimistic, deadlocks",
  questions: [
  { q: "A dirty read is…", options: ["Reading twice", "Reading another transaction's UNCOMMITTED data", "A NULL read"], answer: 1,
    explain: "Prevented by Read Committed and above." },
  { q: "Non-repeatable read means…", options: ["Query fails", "Re-reading a row in one txn returns a different committed value", "Phantoms"], answer: 1,
    explain: "Prevented by Repeatable Read (snapshot)." },
  { q: "A phantom read is…", options: ["A dirty read", "Re-running a query finds NEW rows inserted by others", "A deadlock"], answer: 1,
    explain: "Serializable (and PG's Repeatable Read) prevents it." },
  { q: "Postgres's default isolation level is…", options: ["Serializable", "Read Committed", "Repeatable Read"], answer: 1,
    explain: "MySQL/InnoDB defaults to Repeatable Read — know your engine." },
  { q: "MVCC means…", options: ["Locks everywhere", "Multiple row versions — readers don't block writers (snapshots)", "No transactions"], answer: 1,
    explain: "Conflicts are about write-write, not reads." },
  { q: "A lost update happens when…", options: ["Disk fails", "Two read-modify-write transactions overwrite each other", "COMMIT fails"], answer: 1,
    explain: "Fix: atomic UPDATE, FOR UPDATE, or optimistic versioning." },
  { q: "SELECT ... FOR UPDATE…", options: ["Reads faster", "Locks the rows (pessimistic) — others' FOR UPDATE waits", "Copies rows"], answer: 1,
    explain: "Guaranteed exclusivity; holds locks (throughput cost)." },
  { q: "Optimistic locking uses…", options: ["Table locks", "A version column checked in the UPDATE's WHERE; 0 rows = conflict → retry", "No checks"], answer: 1,
    explain: "No locks held — best under low contention (ORM @Version)." },
  { q: "Pessimistic vs optimistic — choose pessimistic when…", options: ["Always", "Hot rows / high contention / retries unacceptable", "Never"], answer: 1,
    explain: "Optimistic wins for typical rare-conflict web traffic." },
  { q: "SERIALIZABLE transactions may…", options: ["Never fail", "Abort with serialization errors — the app MUST retry", "Deadlock only"], answer: 1,
    explain: "Retry loops are part of using Serializable." },
  { q: "Write skew is…", options: ["A typo", "Two txns each check a condition then write different rows, jointly breaking an invariant", "A dirty write"], answer: 1,
    explain: "The two-doctors-on-call example; only Serializable (or explicit locks) stops it." },
  { q: "A deadlock is resolved by…", options: ["Waiting forever", "The DB killing one transaction (victim) — the app retries", "COMMIT"], answer: 1,
    explain: "Prevent with consistent lock ordering + short transactions." },
  { q: "Deadlock prevention rule #1:", options: ["More locks", "Acquire locks in a consistent global order", "Longer timeouts"], answer: 1,
    explain: "E.g., always lock the lower id first." },
  { q: "Read-your-writes can break under…", options: ["One primary", "Async replica reads right after a write (replication lag)", "MVCC"], answer: 1,
    explain: "Route recent writers to the primary (scaling lesson)." },
  { q: "The simplest lost-update fix when expressible:", options: ["Serializable", "A single atomic UPDATE (SET x = x - 1 WHERE ...)", "Retry loops"], answer: 1,
    explain: "One statement = atomic; check affected rows." },
  { q: "Repeatable Read gives a transaction…", options: ["Latest data per statement", "A consistent SNAPSHOT from its start", "Locks on all reads"], answer: 1,
    explain: "Re-reads are stable within the transaction." },
  { q: "Long transactions harm because…", options: ["Nothing", "Held locks, blocked vacuum/bloat, replication lag", "Speed"], answer: 1,
    explain: "Keep them short; no external I/O inside." },
  { q: "Raising the isolation level trades…", options: ["Nothing", "Fewer anomalies for less concurrency (and possible retries)", "Memory"], answer: 1,
    explain: "Choose per-transaction by the invariants at stake." },
  { q: "The ORM @Version annotation implements…", options: ["Pessimistic locks", "Optimistic concurrency control", "Serializable"], answer: 1,
    explain: "Version-checked updates with conflict exceptions." },
  { q: "Two sessions incrementing the same counter safely requires…", options: ["Nothing (MVCC)", "Atomicity: atomic UPDATE / lock / atomic level — MVCC alone doesn't prevent lost updates at Read Committed", "Indexes"], answer: 1,
    explain: "Snapshots don't serialize read-modify-write logic." }
]},

{ title: "Quiz 9 · Optimization & Scaling",
  desc: "Workflow, sargability, caching, replicas, partitioning, sharding",
  questions: [
  { q: "Performance work starts with…", options: ["Adding indexes", "Finding the slow queries (pg_stat_statements/APM) — measure first", "Sharding"], answer: 1,
    explain: "Never guess; fix the top offender, re-measure." },
  { q: "An endpoint slow but every query fast usually means…", options: ["Network", "N+1 — many queries per request", "Bad index"], answer: 1,
    explain: "Count queries per request; batch/join." },
  { q: "WHERE DATE(created_at) = '2026-01-15' should become…", options: ["A cast", "A half-open range (>= day AND < next day) — sargable", "A trigger"], answer: 1,
    explain: "Functions on columns defeat indexes." },
  { q: "A materialized view is…", options: ["A saved query", "A stored query RESULT refreshed on demand — precomputed reads", "An index"], answer: 1,
    explain: "For expensive aggregates tolerating staleness." },
  { q: "statement_timeout exists to…", options: ["Speed queries", "Bound worst-case damage from runaway queries", "Kill idle sessions"], answer: 1,
    explain: "A guardrail every production DB should set." },
  { q: "Read replicas scale…", options: ["Writes", "READS (most traffic) via WAL streaming; async = lag", "Storage only"], answer: 1,
    explain: "Also failover targets." },
  { q: "Replication lag breaks…", options: ["Nothing", "Read-your-writes (user doesn't see their own change on a replica)", "Backups"], answer: 1,
    explain: "Sticky-to-primary reads after writes." },
  { q: "Partitioning (RANGE by month) buys…", options: ["More write capacity", "Pruned scans + instant old-data drops WITHIN one server", "Sharding"], answer: 1,
    explain: "Manageability for big tables; still one node." },
  { q: "Partition pruning requires…", options: ["Nothing", "Queries filtering on the partition key", "Hash keys"], answer: 1,
    explain: "Otherwise every partition is scanned." },
  { q: "Sharding scales…", options: ["Reads only", "WRITES/data across independent databases", "Nothing"], answer: 1,
    explain: "The last resort — cross-shard queries/txns get hard." },
  { q: "A good shard key…", options: ["Is the timestamp", "Keeps most queries single-shard, distributes evenly, co-locates transacting data", "Is random"], answer: 1,
    explain: "tenant_id/user_id in SaaS; time keys create hot shards." },
  { q: "Resharding pain is minimized by…", options: ["Bigger shards", "Consistent hashing (moves ~1/N of keys)", "TRUNCATE"], answer: 1,
    explain: "The System Design track's lesson applied." },
  { q: "The scaling ladder order is…", options: ["Shard first", "Tune → cache → replicas → partition → shard", "Random"], answer: 1,
    explain: "Buy complexity only when the cheaper rung is exhausted." },
  { q: "Connection pooling matters because…", options: ["SQL requires it", "Connections are expensive; too many thrash the DB (PgBouncer/app pools)", "It caches rows"], answer: 1,
    explain: "Size pools to DB capacity." },
  { q: "Caching a hot expensive query needs…", options: ["Nothing else", "A staleness budget + explicit invalidation (TTL/events)", "More RAM only"], answer: 1,
    explain: "The System Design caching lesson applied to SQL." },
  { q: "COUNT(*) on every page of a huge table should be…", options: ["Kept", "Cached/estimated (reltuples) or redesigned", "Indexed"], answer: 1,
    explain: "Exact counts scan; most UIs tolerate estimates." },
  { q: "'External sort' in a plan hints…", options: ["Corruption", "work_mem too small — sort spilled to disk", "A lock"], answer: 1,
    explain: "Raise work_mem or add an ORDER BY-matching index." },
  { q: "Huge IN (:ids) lists are better as…", options: ["Longer INs", "JOIN VALUES / temp table / batched queries", "LIKE"], answer: 1,
    explain: "Planner handles joins better than 10k-item INs." },
  { q: "A well-tuned single Postgres node handles…", options: ["Hundreds of QPS max", "Tens of thousands of QPS — exhaust it before distributing", "Everything forever"], answer: 1,
    explain: "Distributed complexity is a last resort." },
  { q: "UNION vs UNION ALL:", options: ["Same", "UNION dedupes (costly); UNION ALL doesn't — prefer ALL when dupes are impossible", "ALL dedupes"], answer: 1,
    explain: "A free win in many reports." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "Rows 'missing' from a report — first suspect?", options: ["Cache", "NULL semantics (comparison/NOT IN filtering UNKNOWN rows)", "Locks"], answer: 1,
    explain: "The three-valued-logic bug class." },
  { q: "Your LEFT JOIN 'lost' its unmatched rows after adding a filter. Cause?", options: ["Index", "The right-table condition went in WHERE (→ INNER) instead of ON", "Lag"], answer: 1,
    explain: "ON preserves; WHERE filters NULLs out." },
  { q: "An endpoint issues 201 queries for a 200-row list. Fix?", options: ["Faster DB", "N+1 → one JOIN or IN-batch / eager fetch", "Sharding"], answer: 1,
    explain: "The classic ORM lazy-loading bug." },
  { q: "UPDATE ran without WHERE in prod. The prevention ritual you skipped?", options: ["Nothing helps", "SELECT-first + transaction + row-count check before COMMIT", "A comment"], answer: 1,
    explain: "Plus safe-update mode / statement review." },
  { q: "Two signups with the same email both succeeded. Root cause?", options: ["Bad luck", "App-level check without a UNIQUE constraint (race) — constraint + upsert", "Replication"], answer: 1,
    explain: "The DB is the race-safe enforcement point." },
  { q: "Balance updates occasionally lose increments. Fix hierarchy?", options: ["Retry more", "Atomic UPDATE → optimistic version → FOR UPDATE", "Serializable only"], answer: 1,
    explain: "Read-modify-write in app code is the bug." },
  { q: "A query ignores its index after wrapping the column in DATE(). Why?", options: ["Index corrupt", "Non-sargable predicate — rewrite as a range or expression index", "Stats"], answer: 1,
    explain: "Bare column on one side of the operator." },
  { q: "WHERE status='paid' skips your (user_id, status) index. Why?", options: ["Bug", "Leftmost-prefix rule — user_id isn't constrained", "Too many rows"], answer: 1,
    explain: "Composite indexes serve left→right." },
  { q: "EXPLAIN shows rows=100 but actual=2M. Action?", options: ["Add RAM", "ANALYZE the table (stale statistics misleading the planner)", "Rewrite in NoSQL"], answer: 1,
    explain: "Estimates drive plan choice." },
  { q: "Page 5000 of results takes 30s. Fix?", options: ["More OFFSET", "Keyset pagination (seek by last sort key + id)", "Remove ORDER BY"], answer: 1,
    explain: "OFFSET scans-and-discards linearly." },
  { q: "User edits profile, refreshes, sees the OLD value. Likely cause?", options: ["Browser cache only", "Read hit an async replica (replication lag) — read-your-writes routing", "Deadlock"], answer: 1,
    explain: "Route post-write reads to the primary." },
  { q: "Nightly job deadlocks with the app. Prevention?", options: ["Run faster", "Consistent lock ordering + short transactions + retry on deadlock", "Serializable"], answer: 1,
    explain: "Circular waits need inconsistent ordering to exist." },
  { q: "Storing order items as a JSON array on orders loses…", options: ["Nothing", "Constraints, joins, indexing, per-item queries — use a child table", "Speed only"], answer: 1,
    explain: "1NF exists for a reason; JSONB is for sparse extras." },
  { q: "Dashboard aggregate takes 20s per view. Best fix?", options: ["Bigger box", "Materialized view (or cache) refreshed on schedule", "More indexes always"], answer: 1,
    explain: "Precompute reads that tolerate staleness." },
  { q: "'Top 3 products per category' needs…", options: ["GROUP BY alone", "ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC) ≤ 3 via subquery", "DISTINCT"], answer: 1,
    explain: "The canonical window-function pattern." },
  { q: "Deleting 50M old rows safely:", options: ["One DELETE", "Chunked deletes — or better, DROP old partitions if partitioned by time", "TRUNCATE"], answer: 1,
    explain: "Partitioning turns purges into metadata operations." },
  { q: "Two txns both check 'at least one on-call remains' then both go off duty. Anomaly + fix?", options: ["Dirty read; Read Committed", "Write skew; SERIALIZABLE (with retries) or explicit locking", "Phantom; index"], answer: 1,
    explain: "Snapshot levels miss it — no write-write conflict." },
  { q: "Writes exceed one primary's capacity after all tuning. Next step?", options: ["More replicas", "Sharding by a query-aligned key (accepting cross-shard costs)", "Partitioning"], answer: 1,
    explain: "Replicas scale reads; partitioning stays on one node." },
  { q: "A migration must not break running old code. Strategy?", options: ["Big-bang ALTER", "Expand/contract: add new alongside, backfill, switch code, remove old", "Downtime"], answer: 1,
    explain: "Backward-compatible steps for zero-downtime deploys." },
  { q: "The single most important SQL mental model is…", options: ["Memorize syntax", "Execution order + NULL logic + 'the planner uses indexes if predicates let it'", "Always use ORMs"], answer: 1,
    explain: "Correctness (order/NULL) and speed (sargable + EXPLAIN) both derive from it. 🏆" }
]}
);
