// sql quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Schema Design & Normalization",
  desc: "Keys, relationships, normal forms, denormalization, types",
  questions: [
  { q: "A FOREIGN KEY guarantees…", options: ["An index in Postgres", "Uniqueness", "The referenced row EXISTS (referential integrity)"], answer: 2,
    explain: "The DB blocks orphaning inserts/deletes; index the FK yourself in Postgres." },
  { q: "Many-to-many is modeled with…", options: ["A JSON list", "A junction table (both FKs, one row per pairing)", "An FK column"], answer: 1,
    explain: "It can also hold relationship attributes (enrolled_at)." },
  { q: "Normalization eliminates…", options: ["Joins", "Redundancy and its update/insert/delete anomalies", "Indexes"], answer: 1,
    explain: "Each fact stored once, referenced by key." },
  { q: "3NF in one phrase:", options: ["One table", "Non-key columns depend on the key, the whole key, and nothing but the key", "No NULLs"], answer: 1,
    explain: "No partial or transitive dependencies." },
  { q: "product1, product2, product3 columns violate…", options: ["1NF (repeating groups) — use a child table", "Nothing", "3NF only"], answer: 0,
    explain: "Also can't query/index a CSV-in-a-column." },
  { q: "Denormalization is…", options: ["The default", "Always wrong", "A deliberate read-optimization (duplication) with a sync strategy"], answer: 2,
    explain: "Counter columns, snapshots, materialized views — driven by measured reads." },
  { q: "Money columns should be…", options: ["NUMERIC/DECIMAL (exact)", "FLOAT", "TEXT"], answer: 0,
    explain: "Floats can't represent 0.10 exactly." },
  { q: "Timestamps should be stored as…", options: ["Integers only", "TIMESTAMPTZ (UTC)", "Local time strings"], answer: 1,
    explain: "Convert to local time at display, not storage." },
  { q: "A surrogate key is…", options: ["A constraint", "An artificial id (BIGSERIAL/UUID) as the PK", "A natural unique value"], answer: 1,
    explain: "Natural candidates (email) still get UNIQUE constraints." },
  { q: "Storing product price on order_items (snapshot) is…", options: ["Redundant always", "A bug", "Correct history modeling — the price AT purchase time"], answer: 2,
    explain: "Some 'denormalization' is actually correct temporal modeling." },
  { q: "One-to-one relationships use…", options: ["Junction tables", "FK + UNIQUE (or shared PK)", "Arrays"], answer: 1,
    explain: "UNIQUE makes the many side single." },
  { q: "JSONB columns are best for…", options: ["Everything", "Money", "Sparse/variable attributes — not core relational data"], answer: 2,
    explain: "You lose constraints/joins; index JSONB paths you query." },
  { q: "Update anomaly example:", options: ["User email duplicated across order rows → one missed update = inconsistency", "Deadlock", "Slow query"], answer: 0,
    explain: "The problem normalization exists to prevent." },
  { q: "Status fields are best constrained by…", options: ["Comments", "CHECK constraint or a lookup table", "App code only"], answer: 1,
    explain: "The DB enforces the allowed set." },
  { q: "UUID keys are chosen when…", options: ["Always", "Distributed generation / merge scenarios / non-guessability matter", "Never"], answer: 1,
    explain: "Trade-off: bigger indexes, random insert patterns (v7 mitigates)." },
  { q: "Premature denormalization causes…", options: ["Sync bugs and complexity with no proven benefit", "Better design", "Speed"], answer: 0,
    explain: "Normalize first; denormalize on measured need." },
  { q: "2NF addresses…", options: ["Partial dependency on part of a COMPOSITE key", "NULLs", "Transitive deps"], answer: 0,
    explain: "Non-key columns must depend on the whole key." },
  { q: "A lookup table (roles) vs a TEXT column:", options: ["TEXT is safer", "Same", "Lookup centralizes values + enables FK integrity and metadata"], answer: 2,
    explain: "CHECK is the lightweight alternative for small fixed sets." },
  { q: "ON DELETE options include…", options: ["CASCADE, RESTRICT, SET NULL — choose per relationship", "None", "CASCADE only"], answer: 0,
    explain: "What should happen to children when the parent goes?" },
  { q: "The design question 'entity or value?' decides…", options: ["Nothing", "Identity table vs embedded/snapshot columns (and record-vs-class in code)", "Storage engine"], answer: 1,
    explain: "The same value-vs-entity distinction as the Java/Python lessons." },
]},
{ title: "Quiz 7 · Indexes & Query Plans",
  desc: "B-trees, sargability, composite indexes, EXPLAIN",
  questions: [
  { q: "A B-tree index provides…", options: ["O(n) scans", "O(log n) lookups over sorted values", "Hashing"], answer: 1,
    explain: "Plus ranges, prefixes, and ORDER BY service." },
  { q: "Adding an index to a live production table should use…", options: ["CREATE INDEX CONCURRENTLY — plain CREATE INDEX blocks ALL writes for the whole build", "A maintenance window only", "CREATE INDEX"], answer: 0,
    explain: "CONCURRENTLY does two passes without blocking writes. It cannot run inside a transaction and can leave an INVALID index on failure — check pg_index.indisvalid afterwards." },
  { q: "WHERE LOWER(email) = :x with an index on email…", options: ["Errors", "Uses the index", "Can't (function on the column) — expression index or rewrite"], answer: 2,
    explain: "CREATE INDEX ON users(LOWER(email)) fixes it." },
  { q: "LIKE '%gmail.com'…", options: ["Can't (no leading prefix) — full-text/trigram approaches instead", "Is invalid", "Uses a B-tree"], answer: 0,
    explain: "The tree is sorted by prefix." },
  { q: "Composite index (user_id, status, created_at) serves WHERE status='paid'…", options: ["No — leftmost-prefix rule (user_id must be constrained first)", "Yes", "Only with LIMIT"], answer: 0,
    explain: "Columns usable left→right; equality chain then one range." },
  { q: "Composite column order should be…", options: ["Alphabetical", "Equality-filtered (selective) columns first, range last", "Random"], answer: 1,
    explain: "Match your real WHERE shapes." },
  { q: "On SSD hardware, the planner keeps choosing Seq Scans over good indexes. A likely cause is…", options: ["Too much RAM", "Broken indexes", "random_page_cost still at its spinning-disk default of 4.0 — lower it to ~1.1"], answer: 2,
    explain: "random_page_cost encodes how much dearer a random read is than a sequential one. Left at 4.0 it systematically over-charges index scans on SSD/NVMe." },
  { q: "Index Only Scan means…", options: ["Slow path", "Bitmap", "Answered entirely from the index (covering) — no table visits"], answer: 2,
    explain: "INCLUDE extra columns to achieve it." },
  { q: "Estimated rows wildly ≠ actual rows →", options: ["Stale statistics — run ANALYZE", "Add RAM", "Fine"], answer: 0,
    explain: "Bad estimates → bad plan choices." },
  { q: "In EXPLAIN ANALYZE, a node reads 'actual time=0.030..0.031 rows=1 loops=40000'. Its real cost is…", options: ["About 40000 x 0.031 = 1.2 seconds — per-loop timings must be multiplied by loops", "Unknowable", "0.031 ms — it is fast"], answer: 0,
    explain: "The loops multiplier is the #1 misreading of EXPLAIN. A node that looks trivial can be the whole query." },
  { q: "A partial index (WHERE deleted_at IS NULL)…", options: ["Indexes only matching rows — smaller and faster for that predicate", "Indexes everything", "Is invalid"], answer: 0,
    explain: "Great for soft-delete and status subsets." },
  { q: "A plan shows 'Index Only Scan … Heap Fetches: 48213'. This means…", options: ["The index is corrupt", "The visibility map is stale, so it still reads heap rows — vacuum the table", "Heap fetches are normal and free"], answer: 1,
    explain: "An index entry does not record row visibility. If the page is not marked all-visible, the 'index-only' scan fetches the heap anyway — the most commonly missed line in EXPLAIN." },
  { q: "GIN indexes are for…", options: ["Simple equality", "Numbers", "JSONB, arrays, full-text search"], answer: 2,
    explain: "B-tree is the default for scalar columns." },
  { q: "score + 10 > 100 vs score > 90:", options: ["Neither uses indexes", "Only the bare-column form is sargable (index-usable)", "Identical to the planner"], answer: 1,
    explain: "Keep the column clean on one side." },
  { q: "Unused indexes should be…", options: ["Found (pg_stat_user_indexes) and dropped — they tax every write", "Kept forever", "Rebuilt"], answer: 0,
    explain: "Index hygiene matters on write-heavy tables." },
  { q: "An index on a 3-value status column alone is…", options: ["Required", "Low-selectivity — the planner often ignores it; composite/partial instead", "Great"], answer: 1,
    explain: "Selectivity drives index usefulness." },
  { q: "ORDER BY created_at DESC LIMIT 10 with an index on created_at…", options: ["Reads 10 entries off the index — no sort step", "Sorts everything", "Errors"], answer: 0,
    explain: "Indexes serve ordering, not just filtering." },
  { q: "Type mismatch (text column compared to int)…", options: ["Fine", "Speeds it up", "Can defeat the index via implicit casts"], answer: 2,
    explain: "Match types in predicates and parameters." },
  { q: "BRIN indexes fit…", options: ["Random data", "Huge append-only tables with natural ordering (time-series)", "Small tables"], answer: 1,
    explain: "Tiny indexes storing block ranges." },
  { q: "WHERE city='Paris' AND country='France' gets a wildly wrong row estimate because…", options: ["Text columns cannot be estimated", "The planner multiplies selectivities assuming independence; the columns are correlated — fix with CREATE STATISTICS", "The index is missing"], answer: 1,
    explain: "Every Paris row is France, so the true selectivity is far higher than P(Paris) x P(France). Extended statistics teach the planner the dependency." },
]},
{ title: "Quiz 8 · Isolation, Locking & Concurrency",
  desc: "Anomalies, levels, MVCC, optimistic vs pessimistic, deadlocks",
  questions: [
  { q: "A dirty read is…", options: ["Reading twice", "Reading another transaction's UNCOMMITTED data", "A NULL read"], answer: 1,
    explain: "Prevented by Read Committed and above." },
  { q: "Non-repeatable read means…", options: ["Query fails", "Phantoms", "Re-reading a row in one txn returns a different committed value"], answer: 2,
    explain: "Prevented by Repeatable Read (snapshot)." },
  { q: "A phantom read is…", options: ["A deadlock", "Re-running a query finds NEW rows inserted by others", "A dirty read"], answer: 1,
    explain: "Serializable (and PG's Repeatable Read) prevents it." },
  { q: "Postgres's default isolation level is…", options: ["Repeatable Read", "Read Committed", "Serializable"], answer: 1,
    explain: "MySQL/InnoDB defaults to Repeatable Read — know your engine." },
  { q: "MVCC means…", options: ["No transactions", "Multiple row versions — readers don't block writers (snapshots)", "Locks everywhere"], answer: 1,
    explain: "Conflicts are about write-write, not reads." },
  { q: "A lost update happens when…", options: ["Two read-modify-write transactions overwrite each other", "COMMIT fails", "Disk fails"], answer: 0,
    explain: "Fix: atomic UPDATE, FOR UPDATE, or optimistic versioning." },
  { q: "SELECT ... FOR UPDATE…", options: ["Reads faster", "Copies rows", "Locks the rows (pessimistic) — others' FOR UPDATE waits"], answer: 2,
    explain: "Guaranteed exclusivity; holds locks (throughput cost)." },
  { q: "Optimistic locking uses…", options: ["Table locks", "No checks", "A version column checked in the UPDATE's WHERE; 0 rows = conflict → retry"], answer: 2,
    explain: "No locks held — best under low contention (ORM @Version)." },
  { q: "Pessimistic vs optimistic — choose pessimistic when…", options: ["Hot rows / high contention / retries unacceptable", "Never", "Always"], answer: 0,
    explain: "Optimistic wins for typical rare-conflict web traffic." },
  { q: "SERIALIZABLE transactions may…", options: ["Deadlock only", "Abort with serialization errors — the app MUST retry", "Never fail"], answer: 1,
    explain: "Retry loops are part of using Serializable." },
  { q: "Write skew is…", options: ["Two txns each check a condition then write different rows, jointly breaking an invariant", "A dirty write", "A typo"], answer: 0,
    explain: "The two-doctors-on-call example; only Serializable (or explicit locks) stops it." },
  { q: "A deadlock is resolved by…", options: ["COMMIT", "Waiting forever", "The DB killing one transaction (victim) — the app retries"], answer: 2,
    explain: "Prevent with consistent lock ordering + short transactions." },
  { q: "Deadlocks are prevented most effectively by…", options: ["More indexes", "Shorter queries", "Acquiring rows in a CONSISTENT ORDER — e.g. ORDER BY id before FOR UPDATE"], answer: 2,
    explain: "A deadlock cycle requires two parties to disagree about lock order. Sorting the ids makes the cycle structurally impossible. Retry on 40P01 regardless." },
  { q: "A retry loop for SERIALIZABLE transactions must retry on…", options: ["Only serialization failure (40001) and deadlock (40P01), with backoff AND jitter", "Timeouts too", "Every exception"], answer: 0,
    explain: "Those two mean nothing was applied, so a retry is safe. Retrying a constraint violation or timeout re-runs work that may have partly happened. Without jitter, conflicting retries collide in lockstep." },
  { q: "The simplest lost-update fix when expressible:", options: ["Serializable", "Retry loops", "A single atomic UPDATE (SET x = x - 1 WHERE ...)"], answer: 2,
    explain: "One statement = atomic; check affected rows." },
  { q: "Repeatable Read gives a transaction…", options: ["Latest data per statement", "Locks on all reads", "A consistent SNAPSHOT from its start"], answer: 2,
    explain: "Re-reads are stable within the transaction." },
  { q: "An ALTER TABLE that takes 2ms caused an 8-minute outage. Why?", options: ["The table was locked forever", "The ALTER was actually slow", "It queued for ACCESS EXCLUSIVE behind a long query, and every later query queued behind IT"], answer: 2,
    explain: "Lock ACQUISITION, not holding, took the site down: lock requests are ordered, so a waiting ALTER blocks everything after it. Always SET lock_timeout before DDL." },
  { q: "Raising the isolation level trades…", options: ["Memory", "Nothing", "Fewer anomalies for less concurrency (and possible retries)"], answer: 2,
    explain: "Choose per-transaction by the invariants at stake." },
  { q: "SELECT ... FOR UPDATE SKIP LOCKED is the basis for…", options: ["A job queue where N workers claim disjoint rows with no blocking", "Deadlock prevention", "Faster reads"], answer: 0,
    explain: "SKIP LOCKED ignores rows another transaction has locked instead of waiting, so throughput scales with workers. Plain FOR UPDATE makes every worker queue on the same row." },
  { q: "Two sessions incrementing the same counter safely requires…", options: ["Indexes", "Nothing (MVCC)", "Atomicity: atomic UPDATE / lock / atomic level — MVCC alone doesn't prevent lost updates at Read Committed"], answer: 2,
    explain: "Snapshots don't serialize read-modify-write logic." },
]},
{ title: "Quiz 9 · Optimization & Scaling",
  desc: "Workflow, sargability, caching, replicas, partitioning, sharding",
  questions: [
  { q: "In pg_stat_statements you should rank queries by…", options: ["total_exec_time — calls x mean; a 1ms query called 400k times outranks a 5s report", "mean_exec_time", "calls"], answer: 0,
    explain: "The most expensive query is rarely the slowest one, and a fast high-frequency query never appears in a slow-query log." },
  { q: "An endpoint slow but every query fast usually means…", options: ["Network", "Bad index", "N+1 — many queries per request"], answer: 2,
    explain: "Count queries per request; batch/join." },
  { q: "WHERE DATE(created_at) = '2026-01-15' should become…", options: ["A half-open range (>= day AND < next day) — sargable", "A cast", "A trigger"], answer: 0,
    explain: "Functions on columns defeat indexes." },
  { q: "A materialized view is…", options: ["A stored query RESULT refreshed on demand — precomputed reads", "A saved query", "An index"], answer: 0,
    explain: "For expensive aggregates tolerating staleness." },
  { q: "statement_timeout exists to…", options: ["Kill idle sessions", "Speed queries", "Bound worst-case damage from runaway queries"], answer: 2,
    explain: "A guardrail every production DB should set." },
  { q: "Ten read replicas give you…", options: ["10x storage", "More read capacity only — every replica applies EVERY write", "10x write throughput"], answer: 1,
    explain: "Replicas replay the primary's WAL, so they multiply the write load rather than dividing it. A replica is also not a backup: it replicates your DELETE in milliseconds." },
  { q: "The precise way to get read-your-writes from a replica is…", options: ["Sleep 1 second", "Capture the primary's LSN after the write and read from a replica only once it has replayed past it", "Always use the primary"], answer: 1,
    explain: "A sticky-primary window (longer than p99 lag) is the simpler alternative. Both must stay correct when lag is seconds, not just at the median." },
  { q: "The biggest practical win from RANGE-partitioning a time-series table is…", options: ["Extra write capacity", "Smaller backups", "Retention becomes DETACH + DROP (milliseconds) instead of a huge DELETE"], answer: 2,
    explain: "A million-row DELETE costs hours of I/O and leaves a vacuum backlog. Partitioning adds NO write capacity — it is still one server." },
  { q: "Partition pruning requires…", options: ["Hash keys", "Nothing", "Queries filtering on the partition key"], answer: 2,
    explain: "Otherwise every partition is scanned." },
  { q: "Sharding scales…", options: ["WRITES/data across independent databases", "Reads only", "Nothing"], answer: 0,
    explain: "The last resort — cross-shard queries/txns get hard." },
  { q: "A good shard key…", options: ["Is random", "Is the timestamp", "Keeps most queries single-shard, distributes evenly, co-locates transacting data"], answer: 2,
    explain: "tenant_id/user_id in SaaS; time keys create hot shards." },
  { q: "For a multi-tenant system, routing via a shard-map lookup table beats hash % N because…", options: ["You can relocate ONE tenant, isolate a whale on its own shard, and rebalance incrementally", "It is faster", "It needs no cache"], answer: 0,
    explain: "Changing N in hash % N remaps nearly every key at once. The map costs a cached lookup per request and is what most mature systems converge on." },
  { q: "Before sharding the core domain, the cheaper step usually worth trying is…", options: ["Bigger indexes", "More replicas", "A functional split — move events/audit/sessions to their own database"], answer: 2,
    explain: "Those tables are typically large, append-heavy and barely joined to the core domain — often most of the write relief for a fraction of sharding's permanent cost." },
  { q: "work_mem should usually be raised…", options: ["Per session or per role — it is allocated PER sort/hash node PER connection", "Never", "Globally, to a large value"], answer: 0,
    explain: "A complex query with several sort/hash nodes at high concurrency can commit many multiples of work_mem. Setting it globally to a large value is a common route to OOM." },
  { q: "Caching a hot expensive query needs…", options: ["More RAM only", "Nothing else", "A staleness budget + explicit invalidation (TTL/events)"], answer: 2,
    explain: "The System Design caching lesson applied to SQL." },
  { q: "COUNT(*) on every page of a huge table should be…", options: ["Kept", "Indexed", "Cached/estimated (reltuples) or redesigned"], answer: 2,
    explain: "Exact counts scan; most UIs tolerate estimates." },
  { q: "'External sort' in a plan hints…", options: ["work_mem too small — sort spilled to disk", "Corruption", "A lock"], answer: 0,
    explain: "Raise work_mem or add an ORDER BY-matching index." },
  { q: "REFRESH MATERIALIZED VIEW without CONCURRENTLY…", options: ["Cannot be used", "Takes an ACCESS EXCLUSIVE lock, so readers BLOCK for the whole refresh", "Is faster and safe"], answer: 1,
    explain: "CONCURRENTLY keeps the old data readable until the swap, but requires a unique index on the view." },
  { q: "A well-tuned single Postgres node handles…", options: ["Everything forever", "Tens of thousands of QPS — exhaust it before distributing", "Hundreds of QPS max"], answer: 1,
    explain: "Distributed complexity is a last resort." },
  { q: "UNION vs UNION ALL:", options: ["Same", "ALL dedupes", "UNION dedupes (costly); UNION ALL doesn't — prefer ALL when dupes are impossible"], answer: 2,
    explain: "A free win in many reports." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "Rows 'missing' from a report — first suspect?", options: ["NULL semantics (comparison/NOT IN filtering UNKNOWN rows)", "Cache", "Locks"], answer: 0,
    explain: "The three-valued-logic bug class." },
  { q: "Your LEFT JOIN 'lost' its unmatched rows after adding a filter. Cause?", options: ["Index", "Lag", "The right-table condition went in WHERE (→ INNER) instead of ON"], answer: 2,
    explain: "ON preserves; WHERE filters NULLs out." },
  { q: "An endpoint issues 201 queries for a 200-row list. Fix?", options: ["Faster DB", "Sharding", "N+1 → one JOIN or IN-batch / eager fetch"], answer: 2,
    explain: "The classic ORM lazy-loading bug." },
  { q: "UPDATE ran without WHERE in prod. The prevention ritual you skipped?", options: ["Nothing helps", "A comment", "SELECT-first + transaction + row-count check before COMMIT"], answer: 2,
    explain: "Plus safe-update mode / statement review." },
  { q: "Two signups with the same email both succeeded. Root cause?", options: ["Replication", "Bad luck", "App-level check without a UNIQUE constraint (race) — constraint + upsert"], answer: 2,
    explain: "The DB is the race-safe enforcement point." },
  { q: "Balance updates occasionally lose increments. Fix hierarchy?", options: ["Serializable only", "Retry more", "Atomic UPDATE → optimistic version → FOR UPDATE"], answer: 2,
    explain: "Read-modify-write in app code is the bug." },
  { q: "A query ignores its index after wrapping the column in DATE(). Why?", options: ["Index corrupt", "Non-sargable predicate — rewrite as a range or expression index", "Stats"], answer: 1,
    explain: "Bare column on one side of the operator." },
  { q: "WHERE status='paid' skips your (user_id, status) index. Why?", options: ["Leftmost-prefix rule — user_id isn't constrained", "Bug", "Too many rows"], answer: 0,
    explain: "Composite indexes serve left→right." },
  { q: "EXPLAIN shows rows=100 but actual=2M. Action?", options: ["Rewrite in NoSQL", "ANALYZE the table (stale statistics misleading the planner)", "Add RAM"], answer: 1,
    explain: "Estimates drive plan choice." },
  { q: "Page 5000 of results takes 30s. Fix?", options: ["More OFFSET", "Keyset pagination (seek by last sort key + id)", "Remove ORDER BY"], answer: 1,
    explain: "OFFSET scans-and-discards linearly." },
  { q: "User edits profile, refreshes, sees the OLD value. Likely cause?", options: ["Deadlock", "Read hit an async replica (replication lag) — read-your-writes routing", "Browser cache only"], answer: 1,
    explain: "Route post-write reads to the primary." },
  { q: "Nightly job deadlocks with the app. Prevention?", options: ["Run faster", "Consistent lock ordering + short transactions + retry on deadlock", "Serializable"], answer: 1,
    explain: "Circular waits need inconsistent ordering to exist." },
  { q: "Storing order items as a JSON array on orders loses…", options: ["Speed only", "Nothing", "Constraints, joins, indexing, per-item queries — use a child table"], answer: 2,
    explain: "1NF exists for a reason; JSONB is for sparse extras." },
  { q: "Dashboard aggregate takes 20s per view. Best fix?", options: ["Bigger box", "Materialized view (or cache) refreshed on schedule", "More indexes always"], answer: 1,
    explain: "Precompute reads that tolerate staleness." },
  { q: "'Top 3 products per category' needs…", options: ["DISTINCT", "ROW_NUMBER() OVER (PARTITION BY category ORDER BY sales DESC) ≤ 3 via subquery", "GROUP BY alone"], answer: 1,
    explain: "The canonical window-function pattern." },
  { q: "Deleting 50M old rows safely:", options: ["One DELETE", "Chunked deletes — or better, DROP old partitions if partitioned by time", "TRUNCATE"], answer: 1,
    explain: "Partitioning turns purges into metadata operations." },
  { q: "Two txns both check 'at least one on-call remains' then both go off duty. Anomaly + fix?", options: ["Write skew; SERIALIZABLE (with retries) or explicit locking", "Phantom; index", "Dirty read; Read Committed"], answer: 0,
    explain: "Snapshot levels miss it — no write-write conflict." },
  { q: "Writes exceed one primary's capacity after all tuning. Next step?", options: ["More replicas", "Partitioning", "Sharding by a query-aligned key (accepting cross-shard costs)"], answer: 2,
    explain: "Replicas scale reads; partitioning stays on one node." },
  { q: "A migration must not break running old code. Strategy?", options: ["Downtime", "Big-bang ALTER", "Expand/contract: add new alongside, backfill, switch code, remove old"], answer: 2,
    explain: "Backward-compatible steps for zero-downtime deploys." },
  { q: "The single most important SQL mental model is…", options: ["Execution order + NULL logic + 'the planner uses indexes if predicates let it'", "Always use ORMs", "Memorize syntax"], answer: 0,
    explain: "Correctness (order/NULL) and speed (sargable + EXPLAIN) both derive from it. 🏆" },
]},
);
