// sql quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · SELECT, Filtering & NULL",
  desc: "Query anatomy, execution order, WHERE toolkit, three-valued logic",
  questions: [
  { q: "SQL is declarative, meaning…", options: ["You describe WHAT data you want; the planner decides HOW", "You write loops", "It's interpreted"], answer: 0,
    explain: "The query planner picks the execution strategy — you specify the result." },
  { q: "The logical execution order starts with…", options: ["SELECT", "ORDER BY", "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT"], answer: 2,
    explain: "Explains why aliases work in ORDER BY but not WHERE." },
  { q: "WHERE email = NULL …", options: ["Errors", "Finds NULL emails", "Never matches anything — use IS NULL"], answer: 2,
    explain: "NULL = NULL evaluates to UNKNOWN, not TRUE (three-valued logic)." },
  { q: "Rows where score IS NULL under WHERE score > 50 are…", options: ["Errors", "EXCLUDED (comparison is UNKNOWN)", "Included"], answer: 1,
    explain: "And NOT (score > 50) STILL excludes them — NULL propagates." },
  { q: "COALESCE(discount, 0) does…", options: ["Rounds", "Sums", "Replaces NULL with a default value"], answer: 2,
    explain: "The standard NULL-default function." },
  { q: "A SELECT alias can be used in…", options: ["ORDER BY (runs after SELECT), not WHERE (runs before)", "FROM", "WHERE"], answer: 0,
    explain: "Execution order strikes again." },
  { q: "LIKE 'A%' vs LIKE '%A':", options: ["Both indexed", "Leading-anchored can use a B-tree index; leading % cannot", "Same speed"], answer: 1,
    explain: "No known prefix = can't descend the sorted tree." },
  { q: "BETWEEN 80 AND 100 is…", options: ["Inclusive on both ends", "Exclusive on the right", "Exclusive"], answer: 0,
    explain: "80 and 100 both match." },
  { q: "SELECT * in application code is…", options: ["Best practice", "Required", "Discouraged: breaks on schema change, extra data, blocks index-only scans"], answer: 2,
    explain: "Name columns explicitly in production queries." },
  { q: "NULL means…", options: ["Zero", "UNKNOWN — not zero, not empty string", "False"], answer: 1,
    explain: "The root of three-valued logic." },
  { q: "IN ('admin','editor') is equivalent to…", options: ["role='admin' OR role='editor'", "A JOIN", "LIKE"], answer: 0,
    explain: "Set membership shorthand." },
  { q: "CASE WHEN ... THEN ... END is…", options: ["A function only in MySQL", "SQL's conditional expression (computed columns/buckets)", "A loop"], answer: 1,
    explain: "Grade bucketing, conditional aggregation, etc." },
  { q: "DISTINCT does…", options: ["Removes duplicate result rows", "Filters NULLs", "Sorts"], answer: 0,
    explain: "Applied to the selected column set." },
  { q: "WHERE can't reference aggregates because…", options: ["Aggregates are slow", "Syntax", "It runs BEFORE grouping — that's HAVING's job"], answer: 2,
    explain: "Execution order: WHERE → GROUP BY → HAVING." },
  { q: "ILIKE is…", options: ["Case-insensitive LIKE (Postgres)", "An index type", "Invalid"], answer: 0,
    explain: "Or use LOWER() with an expression index." },
  { q: "x NOT IN (1, NULL) returns…", options: ["Rows where x≠1", "NO rows ever (UNKNOWN) — the NOT IN + NULL trap", "An error"], answer: 1,
    explain: "Use NOT EXISTS or filter NULLs from the subquery." },
  { q: "'_' in a LIKE pattern matches…", options: ["Exactly one character", "Underscore only", "Any string"], answer: 0,
    explain: "% = any run of chars; _ = single char." },
  { q: "Comparing dates like created_at >= '2026-01-01'…", options: ["Works naturally; half-open ranges [from, to) are the robust idiom", "Needs casting always", "Is invalid"], answer: 0,
    explain: ">= start AND < end avoids end-of-day edge cases." },
  { q: "UNKNOWN in a WHERE clause is treated as…", options: ["TRUE", "Not-TRUE → row filtered out", "An error"], answer: 1,
    explain: "Only TRUE rows pass the filter." },
  { q: "The biggest 'missing rows' bug source is…", options: ["Typos", "NULL semantics in filters (comparisons, NOT, NOT IN)", "Sorting"], answer: 1,
    explain: "Always ask 'what happens to NULLs here?'." },
]},
{ title: "Quiz 2 · Aggregates & Grouping",
  desc: "COUNT variants, GROUP BY rules, HAVING, pagination",
  questions: [
  { q: "COUNT(*) vs COUNT(email):", options: ["COUNT(*) counts rows; COUNT(email) skips NULL emails", "COUNT(email) is faster", "Identical"], answer: 0,
    explain: "Aggregates ignore NULLs in their argument." },
  { q: "AVG(score) with NULL scores divides by…", options: ["Total rows", "The count of NON-NULL scores", "Rows + 1"], answer: 1,
    explain: "NULLs silently change averages." },
  { q: "Every SELECT column must be…", options: ["Indexed", "In GROUP BY or inside an aggregate", "Aliased"], answer: 1,
    explain: "Postgres errors otherwise; enable ONLY_FULL_GROUP_BY on MySQL." },
  { q: "Filter GROUPS (COUNT(*) > 100) with…", options: ["HAVING (after aggregation)", "WHERE", "LIMIT"], answer: 0,
    explain: "WHERE = rows before grouping; HAVING = groups after." },
  { q: "Row-level conditions belong in WHERE because…", options: ["Style", "They shrink data BEFORE the expensive grouping (faster)", "HAVING can't filter"], answer: 1,
    explain: "Filter early, aggregate less." },
  { q: "ORDER BY score DESC without a tiebreaker gives…", options: ["An error", "Nondeterministic order among ties → pagination can skip/dupe", "Stable order"], answer: 1,
    explain: "Add a unique column (id) to ORDER BY." },
  { q: "LIMIT 20 OFFSET 40 returns…", options: ["Rows 41–60 (page 3 of 20)", "40 rows", "Rows 40-60"], answer: 0,
    explain: "OFFSET skips, LIMIT caps." },
  { q: "Deep OFFSET is slow because…", options: ["The DB generates and DISCARDS all skipped rows", "Network", "Locks"], answer: 0,
    explain: "Cost grows with page number — use keyset pagination." },
  { q: "Keyset pagination works by…", options: ["Random sampling", "WHERE (sort_col, id) < (last values) ORDER BY ... LIMIT n", "Bigger OFFSETs"], answer: 1,
    explain: "Index-seeks straight to the next page; can't jump to page N." },
  { q: "COUNT(DISTINCT country) counts…", options: ["Distinct non-NULL countries", "All rows", "Countries incl. NULL"], answer: 0,
    explain: "DISTINCT inside an aggregate." },
  { q: "GROUP BY country, role produces…", options: ["Two result sets", "An error", "One row per unique (country, role) combination"], answer: 2,
    explain: "Multi-column grouping." },
  { q: "SUM over zero rows returns…", options: ["0", "NULL (wrap with COALESCE for 0)", "Error"], answer: 1,
    explain: "COUNT returns 0, but SUM/AVG/MIN/MAX return NULL on empty input." },
  { q: "NULLS LAST in ORDER BY…", options: ["Filters NULLs", "Controls where NULLs sort", "Errors on MySQL"], answer: 1,
    explain: "Postgres syntax; default NULL placement differs by DESC/ASC." },
  { q: "Old MySQL selecting a non-grouped column returned…", options: ["An error", "An ARBITRARY value from the group — silent wrong results", "NULL"], answer: 1,
    explain: "Why ONLY_FULL_GROUP_BY matters." },
  { q: "Conditional aggregation (COUNT(CASE WHEN paid THEN 1 END)) gives…", options: ["Slower queries always", "Errors", "Per-condition counts within one GROUP BY pass"], answer: 2,
    explain: "Or FILTER (WHERE ...) in Postgres — pivot-style reports." },
  { q: "MIN/MAX work on…", options: ["Indexes only", "Numbers only", "Numbers, text, dates (any orderable type)"], answer: 2,
    explain: "MAX(created_at) = latest timestamp." },
  { q: "HAVING without GROUP BY…", options: ["Treats the whole result as one group (filter on a global aggregate)", "Is invalid", "Equals WHERE"], answer: 0,
    explain: "e.g., HAVING COUNT(*) > 1000 on the whole table." },
  { q: "A stable feed/infinite scroll should paginate via…", options: ["Random LIMIT", "Keyset (cursor) pagination", "OFFSET"], answer: 1,
    explain: "Fast at any depth and stable under inserts." },
  { q: "GROUP BY collapses rows; to keep rows AND add group stats use…", options: ["Subqueries only", "HAVING", "Window functions (later lesson)"], answer: 2,
    explain: "AVG() OVER (PARTITION BY ...) keeps every row." },
  { q: "COUNT(*) on a huge table every page load is…", options: ["Expensive — cache/estimate it", "O(1)", "Free"], answer: 0,
    explain: "Exact counts scan; use estimates or counter caches." },
]},
{ title: "Quiz 3 · JOINs",
  desc: "Join types, ON vs WHERE, anti-joins, N+1, fan-out",
  questions: [
  { q: "INNER JOIN returns…", options: ["Left rows always", "Only rows with a match on BOTH sides", "All rows from both"], answer: 1,
    explain: "The intersection by the join condition." },
  { q: "LEFT JOIN returns…", options: ["Matches only", "ALL left rows; NULLs for unmatched right columns", "All right rows"], answer: 1,
    explain: "The 'keep everything from the left' join." },
  { q: "Users who never ordered:", options: ["INNER JOIN", "LEFT JOIN orders + WHERE o.id IS NULL (anti-join)", "CROSS JOIN"], answer: 1,
    explain: "Unmatched rows are exactly those with NULL right columns." },
  { q: "A right-table condition in WHERE on a LEFT JOIN…", options: ["Silently converts it to an INNER JOIN (NULLs fail the filter)", "Errors", "Is fine"], answer: 0,
    explain: "Put right-side filters in the ON clause to keep unmatched left rows." },
  { q: "Filtering the right table while keeping unmatched left rows:", options: ["HAVING", "LEFT JOIN ... ON o.user_id=u.id AND o.status='paid'", "WHERE o.status='paid'"], answer: 1,
    explain: "ON is applied during the join, before NULL generation." },
  { q: "COUNT(*) vs COUNT(o.id) after a LEFT JOIN:", options: ["COUNT(o.id) errors", "COUNT(*) counts unmatched rows as 1; COUNT(o.id) gives 0 (NULL skipped)", "Same"], answer: 1,
    explain: "Count the right table's column for true child counts." },
  { q: "Joining two one-to-many relations then SUMming…", options: ["Double-counts (fan-out cross product) — pre-aggregate each side first", "Is safe", "Errors"], answer: 0,
    explain: "Aggregate in CTEs, then join the aggregates." },
  { q: "A missing ON clause creates…", options: ["A CROSS JOIN (cartesian product) — row explosion", "A LEFT JOIN", "An error always"], answer: 0,
    explain: "Every left row × every right row." },
  { q: "The N+1 problem is…", options: ["A math error", "An index issue", "1 list query + 1 query PER item for relations (ORM lazy loading)"], answer: 2,
    explain: "Fix: JOIN, WHERE fk IN (:ids), or eager fetch." },
  { q: "N+1 detection:", options: ["EXPLAIN", "SQL logging/APM showing many identical fast queries per request", "Slow query log only"], answer: 1,
    explain: "The DB looks 'fine'; the endpoint is slow." },
  { q: "FULL OUTER JOIN is used for…", options: ["Speed", "Filtering", "Reconciliation — all rows from both sides, matched where possible"], answer: 2,
    explain: "Diffing datasets (e.g., ledger vs payments)." },
  { q: "RIGHT JOIN is usually…", options: ["Required", "Faster", "Rewritten as a LEFT JOIN (swap table order) for readability"], answer: 2,
    explain: "Convention: keep the 'preserved' table on the left." },
  { q: "Join (FK) columns should be…", options: ["Unique always", "TEXT", "Indexed — otherwise joins scan"], answer: 2,
    explain: "FKs don't auto-create indexes in Postgres — add them." },
  { q: "Self-join is…", options: ["Invalid", "A CROSS JOIN", "Joining a table to itself (employee → manager)"], answer: 2,
    explain: "Alias the table twice (e JOIN employees m ON e.manager_id = m.id)." },
  { q: "Table aliases (users u) are…", options: ["Slower", "Convention for readable multi-table queries", "Required"], answer: 1,
    explain: "Qualify columns (u.name, o.total) to avoid ambiguity." },
  { q: "USING (user_id) is…", options: ["Shorthand for ON a.user_id = b.user_id (same column name)", "A hint", "Invalid"], answer: 0,
    explain: "Cleaner when names match." },
  { q: "One user with 3 orders joined to orders yields…", options: ["NULL", "3 rows (one per match)", "1 row"], answer: 1,
    explain: "Joins multiply by matches — the root of fan-out." },
  { q: "CROSS JOIN's legitimate use is…", options: ["Generating combinations (sizes × colors, date spines)", "Everything", "None"], answer: 0,
    explain: "Deliberate cartesian products only." },
  { q: "EXISTS vs JOIN for 'has any order':", options: ["CROSS", "EXISTS — short-circuits and avoids duplicate rows", "JOIN always"], answer: 1,
    explain: "Existence checks don't need the joined columns." },
  { q: "Join choice drives correctness AND…", options: ["Nothing else", "Row multiplicity (dupes/fan-out) — think about cardinality every join", "Style only"], answer: 1,
    explain: "Ask: one-to-one, one-to-many, many-to-many?" },
]},
{ title: "Quiz 4 · DML & Transactions",
  desc: "INSERT/UPDATE/DELETE safety, upserts, ACID, atomic updates",
  questions: [
  { q: "UPDATE users SET score = 0 (no WHERE)…", options: ["Errors", "Updates one row", "Resets EVERY row — the classic disaster"], answer: 2,
    explain: "SELECT first; transaction + row-count check; safe-update mode." },
  { q: "An UPDATE with a guard (WHERE ... AND balance >= :amt) reports 0 rows affected. That means…", options: ["Retry it", "The statement failed", "It succeeded and changed nothing — the guard did not match; that count IS the business result"], answer: 2,
    explain: "0 rows = insufficient funds / lost the race. Ignoring the affected-row count is how check-then-act bugs hide." },
  { q: "SELECT-then-INSERT for 'create if missing' has…", options: ["Syntax errors", "No issues", "A race window → duplicates/errors; use an UPSERT"], answer: 2,
    explain: "ON CONFLICT (Postgres) / ON DUPLICATE KEY (MySQL) is atomic." },
  { q: "Upserts require…", options: ["Nothing", "A UNIQUE constraint on the conflict target", "A trigger"], answer: 1,
    explain: "The constraint defines what 'conflict' means." },
  { q: "Sending an email inside the transaction that wrote the order is wrong because…", options: ["Email is slow", "It can be sent for a transaction that then rolls back, and cannot be undone — use an outbox table", "SMTP needs a lock"], answer: 1,
    explain: "Write the intent to an outbox in the SAME transaction (atomic), and let a worker send it. Delivery becomes at-least-once, so handlers must be idempotent." },
  { q: "RETURNING id (Postgres) gives you…", options: ["Row count", "A lock", "Generated values without a second query"], answer: 2,
    explain: "INSERT ... RETURNING id, created_at." },
  { q: "Deleting millions of rows should be…", options: ["One statement", "Chunked (LIMIT batches) to avoid long locks/replication lag", "TRUNCATE always"], answer: 1,
    explain: "Repeat until 0 rows affected." },
  { q: "Soft delete means…", options: ["Flagging (deleted_at) instead of removing — recoverable, needs filters everywhere", "DELETE quietly", "TRUNCATE"], answer: 0,
    explain: "Audit/recovery vs added query complexity." },
  { q: "ACID's Atomicity guarantees…", options: ["All statements in a transaction commit or none do", "Speed", "Ordering"], answer: 0,
    explain: "The money-transfer example: never half-moved." },
  { q: "Durability means…", options: ["Once COMMIT returns, the change survives crashes (WAL)", "Backups exist", "Replicas have it"], answer: 0,
    explain: "Committed = on durable storage; replicas may lag." },
  { q: "Read-modify-write in app code (read bal, compute, write)…", options: ["Races: concurrent runs lose updates — use an atomic UPDATE", "Is fine", "Is required"], answer: 0,
    explain: "SET balance = balance - x WHERE ... AND balance >= x, check row count." },
  { q: "Constraints belong in the DB (not just the app) because…", options: ["Style", "Multiple writers exist and races bypass app checks — the DB is the last line", "Speed"], answer: 1,
    explain: "UNIQUE blocks duplicate-email races an app check misses." },
  { q: "CHECK (price >= 0) guarantees…", options: ["Indexing", "Fast queries", "Invalid data CANNOT be inserted, by any writer"], answer: 2,
    explain: "Invariants enforced at the source of truth." },
  { q: "Long transactions are bad because…", options: ["They're fine", "They hold locks, bloat, block writers, lag replicas", "Syntax"], answer: 1,
    explain: "Keep transactions short; no external I/O inside." },
  { q: "SAVEPOINT lets you…", options: ["Roll back part of a transaction and continue", "Lock rows", "Commit twice"], answer: 0,
    explain: "ROLLBACK TO savepoint_name." },
  { q: "ON DELETE CASCADE means…", options: ["Delete is blocked", "Nothing", "Deleting a parent auto-deletes referencing children"], answer: 2,
    explain: "Choose CASCADE/RESTRICT/SET NULL deliberately per FK." },
  { q: "TRUNCATE vs DELETE:", options: ["TRUNCATE is slower", "Same", "TRUNCATE empties the whole table fast (no WHERE); DELETE is row-level"], answer: 2,
    explain: "TRUNCATE also resets sequences." },
  { q: "A session sitting in 'idle in transaction' is dangerous because…", options: ["It uses CPU", "It fills the WAL", "It holds locks, pins a pooled connection, AND blocks vacuum database-wide"], answer: 2,
    explain: "The third effect surprises people: the oldest open transaction pins the snapshot horizon, so dead tuples cannot be reclaimed in tables it never touched." },
  { q: "Idempotent money writes use…", options: ["Retries alone", "Idempotency keys / unique constraints so retries don't double-charge", "Timeouts"], answer: 1,
    explain: "The REST + payments pattern, enforced at the DB." },
  { q: "Consistency (ACID) means…", options: ["Replicas match", "Caching", "Constraints hold before and after every transaction"], answer: 2,
    explain: "The DB never commits a rule-violating state." },
]},
{ title: "Quiz 5 · Subqueries, CTEs & Window Functions",
  desc: "EXISTS, NOT IN trap, recursive CTEs, rankings, frames",
  questions: [
  { q: "A correlated subquery…", options: ["Runs once", "Is invalid", "References the outer row — conceptually runs per outer row"], answer: 2,
    explain: "Readable but can be slow; JOIN+GROUP BY is set-based." },
  { q: "EXISTS is efficient because it…", options: ["Sorts", "Short-circuits at the first matching row", "Counts all"], answer: 1,
    explain: "Ideal for 'has any' checks." },
  { q: "Prefer NOT EXISTS over NOT IN because…", options: ["NOT IN returns zero rows if the subquery has ANY NULL", "Speed only", "Style"], answer: 0,
    explain: "Three-valued logic strikes; NOT EXISTS is NULL-safe." },
  { q: "A CTE (WITH) primarily provides…", options: ["Indexes", "Named, readable steps (pipelines) + recursion", "Speed"], answer: 1,
    explain: "Modern Postgres inlines them by default." },
  { q: "A recursive CTE has…", options: ["No termination", "An anchor (base) UNION ALL a recursive step joining the CTE", "One part"], answer: 1,
    explain: "Repeats until the recursive step returns no rows." },
  { q: "Recursive CTEs are for…", options: ["Aggregates", "Big tables", "Hierarchies/graphs: org charts, category trees, BOM"], answer: 2,
    explain: "Add depth guards for cyclic data." },
  { q: "Window functions differ from GROUP BY by…", options: ["KEEPING all rows while computing across related rows", "Requiring indexes", "Being slower"], answer: 0,
    explain: "Detail + aggregate in one result." },
  { q: "ROW_NUMBER vs RANK vs DENSE_RANK on ties:", options: ["Identical", "All skip", "unique / same-then-skip (1,2,2,4) / same-no-skip (1,2,2,3)"], answer: 2,
    explain: "Pick by tie behavior; ROW_NUMBER for dedup/latest-per-key." },
  { q: "Top 3 per department requires…", options: ["HAVING", "WHERE rn <= 3 directly", "ROW_NUMBER in a subquery/CTE, filter the alias outside"], answer: 2,
    explain: "Window functions compute in SELECT — after WHERE." },
  { q: "PARTITION BY inside OVER is like…", options: ["ORDER BY", "GROUP BY but WITHOUT collapsing rows", "LIMIT"], answer: 1,
    explain: "Defines the window's group." },
  { q: "A running total uses…", options: ["HAVING", "SUM(x) OVER (ORDER BY date)", "GROUP BY"], answer: 1,
    explain: "ORDER BY inside OVER = cumulative ordering." },
  { q: "LAG(revenue) OVER (ORDER BY day) gives…", options: ["The average", "The PREVIOUS row's value (day-over-day deltas)", "Next day"], answer: 1,
    explain: "LEAD looks forward — no self-joins needed." },
  { q: "A 7-day moving average uses…", options: ["GROUP BY 7", "ROWS BETWEEN 6 PRECEDING AND CURRENT ROW", "LIMIT 7"], answer: 1,
    explain: "The frame clause defines the window extent." },
  { q: "'Latest order per user' idiom:", options: ["MAX + join back", "ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) = 1", "DISTINCT"], answer: 1,
    explain: "The cleanest latest-per-key pattern." },
  { q: "A scalar subquery must…", options: ["Return rows", "Return exactly ONE value (else error)", "Be correlated"], answer: 1,
    explain: "Use aggregates/LIMIT 1 to guarantee it." },
  { q: "Derived tables are…", options: ["Views", "Subqueries in the FROM clause", "Temp tables"], answer: 1,
    explain: "Alias them; CTEs are usually clearer." },
  { q: "Converting a correlated COUNT subquery to set-based uses…", options: ["LEFT JOIN + GROUP BY", "DISTINCT", "EXISTS"], answer: 0,
    explain: "One pass instead of per-row execution." },
  { q: "NTILE(4) OVER (ORDER BY salary)…", options: ["Buckets rows into quartiles", "Rounds salaries", "Ranks with gaps"], answer: 0,
    explain: "Equal-sized buckets for percentile-style grouping." },
  { q: "Window ORDER BY defaults can surprise because…", options: ["They error", "They sort backwards", "The default RANGE frame includes ties — specify ROWS explicitly"], answer: 2,
    explain: "Be explicit with the frame for running calcs." },
  { q: "groupby-like reports with detail rows intact are the job of…", options: ["Window functions", "HAVING", "DISTINCT"], answer: 0,
    explain: "The defining use case." },
]},
);
