// SQL quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · SELECT, Filtering & NULL",
  desc: "Query anatomy, execution order, WHERE toolkit, three-valued logic",
  questions: [
  { q: "SQL is declarative, meaning…", options: ["You write loops", "You describe WHAT data you want; the planner decides HOW", "It's interpreted"], answer: 1,
    explain: "The query planner picks the execution strategy — you specify the result." },
  { q: "The logical execution order starts with…", options: ["SELECT", "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT", "ORDER BY"], answer: 1,
    explain: "Explains why aliases work in ORDER BY but not WHERE." },
  { q: "WHERE email = NULL …", options: ["Finds NULL emails", "Never matches anything — use IS NULL", "Errors"], answer: 1,
    explain: "NULL = NULL evaluates to UNKNOWN, not TRUE (three-valued logic)." },
  { q: "Rows where score IS NULL under WHERE score > 50 are…", options: ["Included", "EXCLUDED (comparison is UNKNOWN)", "Errors"], answer: 1,
    explain: "And NOT (score > 50) STILL excludes them — NULL propagates." },
  { q: "COALESCE(discount, 0) does…", options: ["Rounds", "Replaces NULL with a default value", "Sums"], answer: 1,
    explain: "The standard NULL-default function." },
  { q: "A SELECT alias can be used in…", options: ["WHERE", "ORDER BY (runs after SELECT), not WHERE (runs before)", "FROM"], answer: 1,
    explain: "Execution order strikes again." },
  { q: "LIKE 'A%' vs LIKE '%A':", options: ["Same speed", "Leading-anchored can use a B-tree index; leading % cannot", "Both indexed"], answer: 1,
    explain: "No known prefix = can't descend the sorted tree." },
  { q: "BETWEEN 80 AND 100 is…", options: ["Exclusive", "Inclusive on both ends", "Exclusive on the right"], answer: 1,
    explain: "80 and 100 both match." },
  { q: "SELECT * in application code is…", options: ["Best practice", "Discouraged: breaks on schema change, extra data, blocks index-only scans", "Required"], answer: 1,
    explain: "Name columns explicitly in production queries." },
  { q: "NULL means…", options: ["Zero", "UNKNOWN — not zero, not empty string", "False"], answer: 1,
    explain: "The root of three-valued logic." },
  { q: "IN ('admin','editor') is equivalent to…", options: ["A JOIN", "role='admin' OR role='editor'", "LIKE"], answer: 1,
    explain: "Set membership shorthand." },
  { q: "CASE WHEN ... THEN ... END is…", options: ["A loop", "SQL's conditional expression (computed columns/buckets)", "A function only in MySQL"], answer: 1,
    explain: "Grade bucketing, conditional aggregation, etc." },
  { q: "DISTINCT does…", options: ["Sorts", "Removes duplicate result rows", "Filters NULLs"], answer: 1,
    explain: "Applied to the selected column set." },
  { q: "WHERE can't reference aggregates because…", options: ["Syntax", "It runs BEFORE grouping — that's HAVING's job", "Aggregates are slow"], answer: 1,
    explain: "Execution order: WHERE → GROUP BY → HAVING." },
  { q: "ILIKE is…", options: ["Invalid", "Case-insensitive LIKE (Postgres)", "An index type"], answer: 1,
    explain: "Or use LOWER() with an expression index." },
  { q: "x NOT IN (1, NULL) returns…", options: ["Rows where x≠1", "NO rows ever (UNKNOWN) — the NOT IN + NULL trap", "An error"], answer: 1,
    explain: "Use NOT EXISTS or filter NULLs from the subquery." },
  { q: "'_' in a LIKE pattern matches…", options: ["Any string", "Exactly one character", "Underscore only"], answer: 1,
    explain: "% = any run of chars; _ = single char." },
  { q: "Comparing dates like created_at >= '2026-01-01'…", options: ["Needs casting always", "Works naturally; half-open ranges [from, to) are the robust idiom", "Is invalid"], answer: 1,
    explain: ">= start AND < end avoids end-of-day edge cases." },
  { q: "UNKNOWN in a WHERE clause is treated as…", options: ["TRUE", "Not-TRUE → row filtered out", "An error"], answer: 1,
    explain: "Only TRUE rows pass the filter." },
  { q: "The biggest 'missing rows' bug source is…", options: ["Typos", "NULL semantics in filters (comparisons, NOT, NOT IN)", "Sorting"], answer: 1,
    explain: "Always ask 'what happens to NULLs here?'." }
]},

{ title: "Quiz 2 · Aggregates & Grouping",
  desc: "COUNT variants, GROUP BY rules, HAVING, pagination",
  questions: [
  { q: "COUNT(*) vs COUNT(email):", options: ["Identical", "COUNT(*) counts rows; COUNT(email) skips NULL emails", "COUNT(email) is faster"], answer: 1,
    explain: "Aggregates ignore NULLs in their argument." },
  { q: "AVG(score) with NULL scores divides by…", options: ["Total rows", "The count of NON-NULL scores", "Rows + 1"], answer: 1,
    explain: "NULLs silently change averages." },
  { q: "Every SELECT column must be…", options: ["Indexed", "In GROUP BY or inside an aggregate", "Aliased"], answer: 1,
    explain: "Postgres errors otherwise; enable ONLY_FULL_GROUP_BY on MySQL." },
  { q: "Filter GROUPS (COUNT(*) > 100) with…", options: ["WHERE", "HAVING (after aggregation)", "LIMIT"], answer: 1,
    explain: "WHERE = rows before grouping; HAVING = groups after." },
  { q: "Row-level conditions belong in WHERE because…", options: ["Style", "They shrink data BEFORE the expensive grouping (faster)", "HAVING can't filter"], answer: 1,
    explain: "Filter early, aggregate less." },
  { q: "ORDER BY score DESC without a tiebreaker gives…", options: ["Stable order", "Nondeterministic order among ties → pagination can skip/dupe", "An error"], answer: 1,
    explain: "Add a unique column (id) to ORDER BY." },
  { q: "LIMIT 20 OFFSET 40 returns…", options: ["Rows 40-60", "Rows 41–60 (page 3 of 20)", "40 rows"], answer: 1,
    explain: "OFFSET skips, LIMIT caps." },
  { q: "Deep OFFSET is slow because…", options: ["Network", "The DB generates and DISCARDS all skipped rows", "Locks"], answer: 1,
    explain: "Cost grows with page number — use keyset pagination." },
  { q: "Keyset pagination works by…", options: ["Bigger OFFSETs", "WHERE (sort_col, id) < (last values) ORDER BY ... LIMIT n", "Random sampling"], answer: 1,
    explain: "Index-seeks straight to the next page; can't jump to page N." },
  { q: "COUNT(DISTINCT country) counts…", options: ["All rows", "Distinct non-NULL countries", "Countries incl. NULL"], answer: 1,
    explain: "DISTINCT inside an aggregate." },
  { q: "GROUP BY country, role produces…", options: ["Two result sets", "One row per unique (country, role) combination", "An error"], answer: 1,
    explain: "Multi-column grouping." },
  { q: "SUM over zero rows returns…", options: ["0", "NULL (wrap with COALESCE for 0)", "Error"], answer: 1,
    explain: "COUNT returns 0, but SUM/AVG/MIN/MAX return NULL on empty input." },
  { q: "NULLS LAST in ORDER BY…", options: ["Filters NULLs", "Controls where NULLs sort", "Errors on MySQL"], answer: 1,
    explain: "Postgres syntax; default NULL placement differs by DESC/ASC." },
  { q: "Old MySQL selecting a non-grouped column returned…", options: ["An error", "An ARBITRARY value from the group — silent wrong results", "NULL"], answer: 1,
    explain: "Why ONLY_FULL_GROUP_BY matters." },
  { q: "Conditional aggregation (COUNT(CASE WHEN paid THEN 1 END)) gives…", options: ["Errors", "Per-condition counts within one GROUP BY pass", "Slower queries always"], answer: 1,
    explain: "Or FILTER (WHERE ...) in Postgres — pivot-style reports." },
  { q: "MIN/MAX work on…", options: ["Numbers only", "Numbers, text, dates (any orderable type)", "Indexes only"], answer: 1,
    explain: "MAX(created_at) = latest timestamp." },
  { q: "HAVING without GROUP BY…", options: ["Is invalid", "Treats the whole result as one group (filter on a global aggregate)", "Equals WHERE"], answer: 1,
    explain: "e.g., HAVING COUNT(*) > 1000 on the whole table." },
  { q: "A stable feed/infinite scroll should paginate via…", options: ["OFFSET", "Keyset (cursor) pagination", "Random LIMIT"], answer: 1,
    explain: "Fast at any depth and stable under inserts." },
  { q: "GROUP BY collapses rows; to keep rows AND add group stats use…", options: ["Subqueries only", "Window functions (later lesson)", "HAVING"], answer: 1,
    explain: "AVG() OVER (PARTITION BY ...) keeps every row." },
  { q: "COUNT(*) on a huge table every page load is…", options: ["Free", "Expensive — cache/estimate it", "O(1)"], answer: 1,
    explain: "Exact counts scan; use estimates or counter caches." }
]},

{ title: "Quiz 3 · JOINs",
  desc: "Join types, ON vs WHERE, anti-joins, N+1, fan-out",
  questions: [
  { q: "INNER JOIN returns…", options: ["All rows from both", "Only rows with a match on BOTH sides", "Left rows always"], answer: 1,
    explain: "The intersection by the join condition." },
  { q: "LEFT JOIN returns…", options: ["Matches only", "ALL left rows; NULLs for unmatched right columns", "All right rows"], answer: 1,
    explain: "The 'keep everything from the left' join." },
  { q: "Users who never ordered:", options: ["INNER JOIN", "LEFT JOIN orders + WHERE o.id IS NULL (anti-join)", "CROSS JOIN"], answer: 1,
    explain: "Unmatched rows are exactly those with NULL right columns." },
  { q: "A right-table condition in WHERE on a LEFT JOIN…", options: ["Is fine", "Silently converts it to an INNER JOIN (NULLs fail the filter)", "Errors"], answer: 1,
    explain: "Put right-side filters in the ON clause to keep unmatched left rows." },
  { q: "Filtering the right table while keeping unmatched left rows:", options: ["WHERE o.status='paid'", "LEFT JOIN ... ON o.user_id=u.id AND o.status='paid'", "HAVING"], answer: 1,
    explain: "ON is applied during the join, before NULL generation." },
  { q: "COUNT(*) vs COUNT(o.id) after a LEFT JOIN:", options: ["Same", "COUNT(*) counts unmatched rows as 1; COUNT(o.id) gives 0 (NULL skipped)", "COUNT(o.id) errors"], answer: 1,
    explain: "Count the right table's column for true child counts." },
  { q: "Joining two one-to-many relations then SUMming…", options: ["Is safe", "Double-counts (fan-out cross product) — pre-aggregate each side first", "Errors"], answer: 1,
    explain: "Aggregate in CTEs, then join the aggregates." },
  { q: "A missing ON clause creates…", options: ["An error always", "A CROSS JOIN (cartesian product) — row explosion", "A LEFT JOIN"], answer: 1,
    explain: "Every left row × every right row." },
  { q: "The N+1 problem is…", options: ["A math error", "1 list query + 1 query PER item for relations (ORM lazy loading)", "An index issue"], answer: 1,
    explain: "Fix: JOIN, WHERE fk IN (:ids), or eager fetch." },
  { q: "N+1 detection:", options: ["EXPLAIN", "SQL logging/APM showing many identical fast queries per request", "Slow query log only"], answer: 1,
    explain: "The DB looks 'fine'; the endpoint is slow." },
  { q: "FULL OUTER JOIN is used for…", options: ["Speed", "Reconciliation — all rows from both sides, matched where possible", "Filtering"], answer: 1,
    explain: "Diffing datasets (e.g., ledger vs payments)." },
  { q: "RIGHT JOIN is usually…", options: ["Required", "Rewritten as a LEFT JOIN (swap table order) for readability", "Faster"], answer: 1,
    explain: "Convention: keep the 'preserved' table on the left." },
  { q: "Join (FK) columns should be…", options: ["TEXT", "Indexed — otherwise joins scan", "Unique always"], answer: 1,
    explain: "FKs don't auto-create indexes in Postgres — add them." },
  { q: "Self-join is…", options: ["Invalid", "Joining a table to itself (employee → manager)", "A CROSS JOIN"], answer: 1,
    explain: "Alias the table twice (e JOIN employees m ON e.manager_id = m.id)." },
  { q: "Table aliases (users u) are…", options: ["Required", "Convention for readable multi-table queries", "Slower"], answer: 1,
    explain: "Qualify columns (u.name, o.total) to avoid ambiguity." },
  { q: "USING (user_id) is…", options: ["Invalid", "Shorthand for ON a.user_id = b.user_id (same column name)", "A hint"], answer: 1,
    explain: "Cleaner when names match." },
  { q: "One user with 3 orders joined to orders yields…", options: ["1 row", "3 rows (one per match)", "NULL"], answer: 1,
    explain: "Joins multiply by matches — the root of fan-out." },
  { q: "CROSS JOIN's legitimate use is…", options: ["None", "Generating combinations (sizes × colors, date spines)", "Everything"], answer: 1,
    explain: "Deliberate cartesian products only." },
  { q: "EXISTS vs JOIN for 'has any order':", options: ["JOIN always", "EXISTS — short-circuits and avoids duplicate rows", "CROSS"], answer: 1,
    explain: "Existence checks don't need the joined columns." },
  { q: "Join choice drives correctness AND…", options: ["Nothing else", "Row multiplicity (dupes/fan-out) — think about cardinality every join", "Style only"], answer: 1,
    explain: "Ask: one-to-one, one-to-many, many-to-many?" }
]},

{ title: "Quiz 4 · DML & Transactions",
  desc: "INSERT/UPDATE/DELETE safety, upserts, ACID, atomic updates",
  questions: [
  { q: "UPDATE users SET score = 0 (no WHERE)…", options: ["Errors", "Resets EVERY row — the classic disaster", "Updates one row"], answer: 1,
    explain: "SELECT first; transaction + row-count check; safe-update mode." },
  { q: "The safe big-UPDATE ritual is…", options: ["Just run it", "SELECT with the same WHERE → BEGIN → UPDATE → verify count → COMMIT", "Backup only"], answer: 1,
    explain: "Know the affected rows before committing." },
  { q: "SELECT-then-INSERT for 'create if missing' has…", options: ["No issues", "A race window → duplicates/errors; use an UPSERT", "Syntax errors"], answer: 1,
    explain: "ON CONFLICT (Postgres) / ON DUPLICATE KEY (MySQL) is atomic." },
  { q: "Upserts require…", options: ["Nothing", "A UNIQUE constraint on the conflict target", "A trigger"], answer: 1,
    explain: "The constraint defines what 'conflict' means." },
  { q: "Multi-row INSERT vs N single INSERTs:", options: ["Same", "Multi-row is far faster (one round trip/statement)", "Single is safer"], answer: 1,
    explain: "COPY/LOAD DATA for huge loads." },
  { q: "RETURNING id (Postgres) gives you…", options: ["Row count", "Generated values without a second query", "A lock"], answer: 1,
    explain: "INSERT ... RETURNING id, created_at." },
  { q: "Deleting millions of rows should be…", options: ["One statement", "Chunked (LIMIT batches) to avoid long locks/replication lag", "TRUNCATE always"], answer: 1,
    explain: "Repeat until 0 rows affected." },
  { q: "Soft delete means…", options: ["DELETE quietly", "Flagging (deleted_at) instead of removing — recoverable, needs filters everywhere", "TRUNCATE"], answer: 1,
    explain: "Audit/recovery vs added query complexity." },
  { q: "ACID's Atomicity guarantees…", options: ["Speed", "All statements in a transaction commit or none do", "Ordering"], answer: 1,
    explain: "The money-transfer example: never half-moved." },
  { q: "Durability means…", options: ["Backups exist", "Once COMMIT returns, the change survives crashes (WAL)", "Replicas have it"], answer: 1,
    explain: "Committed = on durable storage; replicas may lag." },
  { q: "Read-modify-write in app code (read bal, compute, write)…", options: ["Is fine", "Races: concurrent runs lose updates — use an atomic UPDATE", "Is required"], answer: 1,
    explain: "SET balance = balance - x WHERE ... AND balance >= x, check row count." },
  { q: "Constraints belong in the DB (not just the app) because…", options: ["Style", "Multiple writers exist and races bypass app checks — the DB is the last line", "Speed"], answer: 1,
    explain: "UNIQUE blocks duplicate-email races an app check misses." },
  { q: "CHECK (price >= 0) guarantees…", options: ["Fast queries", "Invalid data CANNOT be inserted, by any writer", "Indexing"], answer: 1,
    explain: "Invariants enforced at the source of truth." },
  { q: "Long transactions are bad because…", options: ["Syntax", "They hold locks, bloat, block writers, lag replicas", "They're fine"], answer: 1,
    explain: "Keep transactions short; no external I/O inside." },
  { q: "SAVEPOINT lets you…", options: ["Commit twice", "Roll back part of a transaction and continue", "Lock rows"], answer: 1,
    explain: "ROLLBACK TO savepoint_name." },
  { q: "ON DELETE CASCADE means…", options: ["Nothing", "Deleting a parent auto-deletes referencing children", "Delete is blocked"], answer: 1,
    explain: "Choose CASCADE/RESTRICT/SET NULL deliberately per FK." },
  { q: "TRUNCATE vs DELETE:", options: ["Same", "TRUNCATE empties the whole table fast (no WHERE); DELETE is row-level", "TRUNCATE is slower"], answer: 1,
    explain: "TRUNCATE also resets sequences." },
  { q: "A failed statement mid-transaction should lead to…", options: ["COMMIT anyway", "ROLLBACK in the app's error handling", "Ignore"], answer: 1,
    explain: "Otherwise partial state or a dangling open transaction." },
  { q: "Idempotent money writes use…", options: ["Retries alone", "Idempotency keys / unique constraints so retries don't double-charge", "Timeouts"], answer: 1,
    explain: "The REST + payments pattern, enforced at the DB." },
  { q: "Consistency (ACID) means…", options: ["Replicas match", "Constraints hold before and after every transaction", "Caching"], answer: 1,
    explain: "The DB never commits a rule-violating state." }
]},

{ title: "Quiz 5 · Subqueries, CTEs & Window Functions",
  desc: "EXISTS, NOT IN trap, recursive CTEs, rankings, frames",
  questions: [
  { q: "A correlated subquery…", options: ["Runs once", "References the outer row — conceptually runs per outer row", "Is invalid"], answer: 1,
    explain: "Readable but can be slow; JOIN+GROUP BY is set-based." },
  { q: "EXISTS is efficient because it…", options: ["Counts all", "Short-circuits at the first matching row", "Sorts"], answer: 1,
    explain: "Ideal for 'has any' checks." },
  { q: "Prefer NOT EXISTS over NOT IN because…", options: ["Style", "NOT IN returns zero rows if the subquery has ANY NULL", "Speed only"], answer: 1,
    explain: "Three-valued logic strikes; NOT EXISTS is NULL-safe." },
  { q: "A CTE (WITH) primarily provides…", options: ["Speed", "Named, readable steps (pipelines) + recursion", "Indexes"], answer: 1,
    explain: "Modern Postgres inlines them by default." },
  { q: "A recursive CTE has…", options: ["One part", "An anchor (base) UNION ALL a recursive step joining the CTE", "No termination"], answer: 1,
    explain: "Repeats until the recursive step returns no rows." },
  { q: "Recursive CTEs are for…", options: ["Big tables", "Hierarchies/graphs: org charts, category trees, BOM", "Aggregates"], answer: 1,
    explain: "Add depth guards for cyclic data." },
  { q: "Window functions differ from GROUP BY by…", options: ["Being slower", "KEEPING all rows while computing across related rows", "Requiring indexes"], answer: 1,
    explain: "Detail + aggregate in one result." },
  { q: "ROW_NUMBER vs RANK vs DENSE_RANK on ties:", options: ["Identical", "unique / same-then-skip (1,2,2,4) / same-no-skip (1,2,2,3)", "All skip"], answer: 1,
    explain: "Pick by tie behavior; ROW_NUMBER for dedup/latest-per-key." },
  { q: "Top 3 per department requires…", options: ["WHERE rn <= 3 directly", "ROW_NUMBER in a subquery/CTE, filter the alias outside", "HAVING"], answer: 1,
    explain: "Window functions compute in SELECT — after WHERE." },
  { q: "PARTITION BY inside OVER is like…", options: ["ORDER BY", "GROUP BY but WITHOUT collapsing rows", "LIMIT"], answer: 1,
    explain: "Defines the window's group." },
  { q: "A running total uses…", options: ["GROUP BY", "SUM(x) OVER (ORDER BY date)", "HAVING"], answer: 1,
    explain: "ORDER BY inside OVER = cumulative ordering." },
  { q: "LAG(revenue) OVER (ORDER BY day) gives…", options: ["Next day", "The PREVIOUS row's value (day-over-day deltas)", "The average"], answer: 1,
    explain: "LEAD looks forward — no self-joins needed." },
  { q: "A 7-day moving average uses…", options: ["LIMIT 7", "ROWS BETWEEN 6 PRECEDING AND CURRENT ROW", "GROUP BY 7"], answer: 1,
    explain: "The frame clause defines the window extent." },
  { q: "'Latest order per user' idiom:", options: ["MAX + join back", "ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) = 1", "DISTINCT"], answer: 1,
    explain: "The cleanest latest-per-key pattern." },
  { q: "A scalar subquery must…", options: ["Return rows", "Return exactly ONE value (else error)", "Be correlated"], answer: 1,
    explain: "Use aggregates/LIMIT 1 to guarantee it." },
  { q: "Derived tables are…", options: ["Views", "Subqueries in the FROM clause", "Temp tables"], answer: 1,
    explain: "Alias them; CTEs are usually clearer." },
  { q: "Converting a correlated COUNT subquery to set-based uses…", options: ["EXISTS", "LEFT JOIN + GROUP BY", "DISTINCT"], answer: 1,
    explain: "One pass instead of per-row execution." },
  { q: "NTILE(4) OVER (ORDER BY salary)…", options: ["Rounds salaries", "Buckets rows into quartiles", "Ranks with gaps"], answer: 1,
    explain: "Equal-sized buckets for percentile-style grouping." },
  { q: "Window ORDER BY defaults can surprise because…", options: ["They error", "The default RANGE frame includes ties — specify ROWS explicitly", "They sort backwards"], answer: 1,
    explain: "Be explicit with the frame for running calcs." },
  { q: "groupby-like reports with detail rows intact are the job of…", options: ["HAVING", "Window functions", "DISTINCT"], answer: 1,
    explain: "The defining use case." }
]}
);
