// mongodb quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Indexes: Explain Plans & Query Tuning",
  desc: "Reading stage trees, index bounds, the plan cache and production tuning",
  questions: [
  { q: "Bare explain() without arguments…", options: ["Runs all candidate plans", "Runs nothing and reports no keys, documents or time", "Runs the query and reports timings"], answer: 1,
    explain: "queryPlanner is the default. Type explain(\"executionStats\") every time — the extra characters are the difference between a plan and a measurement." },
  { q: "An explain stage tree should be read…", options: ["Bottom up — the deepest inputStage runs first", "Top down", "Left to right"], answer: 0,
    explain: "The outermost stage is the last thing that happens, which is the opposite of the reading order." },
  { q: "docsExamined equal to keysExamined and far above nReturned means…", options: ["A filter field is not in the index, so candidates are fetched then rejected", "The index is missing entirely", "A blocking sort"], answer: 0,
    explain: "You will see it as a filter on the FETCH stage. Add that field to the index in ESR position." },
  { q: "keysExamined far above docsExamined means…", options: ["A covered query", "Disk contention", "Loose index bounds — often a skipped compound field or a multikey range"], answer: 2,
    explain: "The index is rejecting rows without fetching, so the fix is reordering rather than adding a field." },
  { q: "[MinKey, MaxKey] in indexBounds means…", options: ["The bounds are optimal", "That field contributed nothing to bounding the scan", "The field is unindexed"], answer: 1,
    explain: "Read the bounds top to bottom and stop at the first one — every field below it is dead weight for this query." },
  { q: "A SORT stage in the plan means…", options: ["Results are streamed in order", "A blocking in-memory sort, capped at 32 MB", "The index supplied the order"], answer: 1,
    explain: "Nothing is returned until the last input is read, and any limit above it saves no work." },
  { q: "Low examined counts but high executionTimeMillis suggests…", options: ["Disk reads, lock contention or a saturated server", "A missing index", "A bad plan"], answer: 0,
    explain: "Run it twice — if the second run is fast, the first was reading from disk and it is a capacity problem." },
  { q: "The plan cache stores one plan per…", options: ["Query shape", "Query values", "Collection"], answer: 0,
    explain: "Chosen from a trial that stops at roughly 101 results, then applied to every set of values." },
  { q: "\"Fast for six months, now 4 seconds, nothing changed\" is the signature of…", options: ["Index fragmentation", "Disk failure", "The plan cache choosing a plan wrong for some values"], answer: 2,
    explain: "Measured: 6 ms for a small tenant and 4,200 ms for a large one, same shape, plan decided by whoever queried first after a restart." },
  { q: "The right response to a plan-cache incident is…", options: ["A permanent hint()", "Build the compound index that serves the whole shape", "Clear the cache on a schedule"], answer: 1,
    explain: "The cache only mis-chooses when two plans are close, which means no single index serves the query. A hint is a stopgap that freezes today's data distribution." },
  { q: "In an aggregation explain, the first thing to check is…", options: ["usedDisk", "The $cursor section — is the opening stage an IXSCAN, and how many documents does it produce?", "The merge type"], answer: 1,
    explain: "Nothing downstream can recover the cost of reading the whole collection." },
  { q: "usedDisk: true means…", options: ["The query used the journal", "A blocking stage exceeded 100 MB and spilled", "The index was read from disk"], answer: 1,
    explain: "Correct behaviour, and orders of magnitude slower — a signal to reduce the input rather than to enable spilling." },
  { q: "On a sharded collection the first number to read is…", options: ["docsExamined", "nReturned", "shardsTargeted"], answer: 2,
    explain: "The top-level summary sums all shards, so excellent-looking ratios can hide a 12-shard broadcast." },
  { q: "Slow queries should be ranked by…", options: ["Documents examined", "Worst single execution", "Total time (count × mean)"], answer: 2,
    explain: "A 41 ms query run 98,000 times an hour cost 67 minutes; the 4-second report everyone complained about cost 8 seconds." },
  { q: "planSummary in the profiler is valuable because it…", options: ["Lists candidate plans", "Gives COLLSCAN or the index name without running an explain", "Shows execution time"], answer: 1,
    explain: "It makes the first triage pass free — every COLLSCAN on a large namespace is a finding." },
  { q: "Profiling level 2 on a busy primary…", options: ["Only records writes", "Is the recommended default", "Records every operation and can measurably degrade the node"], answer: 2,
    explain: "Level 1 with a threshold, a capped collection and a reminder to turn it off." },
  { q: "explain reports 4 ms while users wait 900 ms. The time is in…", options: ["The plan cache", "Lock waits", "Serialisation, network transfer and cursor round trips"], answer: 2,
    explain: "182,000 documents with no projection was 740 MB across roughly 40 batches. Check nReturned and responseLength." },
  { q: "A $or with one unindexed branch…", options: ["Raises an error", "Uses the indexed branch", "Makes the whole query a collection scan"], answer: 2,
    explain: "Every branch needs an index. Where branches share a field, $in is better than $or." },
  { q: "maxTimeMS matters because a client timing out…", options: ["Does not stop the server operation", "Kills the server operation", "Rolls back the write"], answer: 0,
    explain: "140 abandoned operations held CPU at 100% for 20 minutes after the traffic had gone." },
  { q: "After an index change you should also…", options: ["Rebuild all indexes", "Check $indexStats for indexes the change made redundant", "Restart the server"], answer: 1,
    explain: "A process that only ever adds indexes becomes a cache problem — one team reached 19 through diligent optimisation and ended up slower." },
]},
{ title: "Quiz 7 · Aggregation: Pipeline, Advanced Stages & Performance",
  desc: "Stage ordering, blocking stages, $group, windows, $merge and pipeline cost",
  questions: [
  { q: "The single most important stage for aggregation performance is…", options: ["$group", "$sort", "The first one"], answer: 2,
    explain: "Only the first stage can use an index to reduce the input — measured 118 s with $group first versus 0.9 s with a selective indexed $match." },
  { q: "Which of these is a blocking stage?", options: ["$match", "$project", "$group"], answer: 2,
    explain: "It must consume its entire input before emitting anything. $sort, $bucket and $facet are the others." },
  { q: "$group memory is proportional to…", options: ["Input document count", "The number of distinct group keys", "Document size"], answer: 1,
    explain: "Measured on identical input: 4 keys used 1.2 MB, 2.1M keys used 410 MB and spilled. Staging never reproduces it." },
  { q: "A stage placed between $sort and $limit…", options: ["Has no effect", "Improves memory use", "Blocks coalescence — 3.2 GB peak memory instead of 40 MB"], answer: 2,
    explain: "Adjacent, they become a bounded top-k sort holding only k documents." },
  { q: "The optimiser cannot push a $match forward when…", options: ["It references a field created by an earlier stage", "It uses $and", "It follows a $sort"], answer: 0,
    explain: "Which is why a mixed $match after a $lookup must be split by hand — often a two-line edit removing 97% of the work." },
  { q: "$unwind on a document with an empty array produces…", options: ["Zero documents", "An error", "One document with null"], answer: 0,
    explain: "Unless preserveNullAndEmptyArrays is set. It silently converts a left join into an inner join." },
  { q: "$push over a very large group risks…", options: ["A slow sort", "Exceeding the 16 MB output document limit", "Losing precision"], answer: 1,
    explain: "One group of 312,000 events failed a pipeline that had worked for 14 months. $topN is bounded by construction." },
  { q: "$first in a $group is meaningful only…", options: ["On indexed fields", "In a $facet", "After an explicit sort establishes an order"], answer: 2,
    explain: "Otherwise \"first\" is whatever the scan happened to produce first. $top with a sortBy says what it means and sorts within each group." },
  { q: "In an expression, \"status\" (without $) means…", options: ["The status field", "The literal string \"status\"", "A variable"], answer: 1,
    explain: "$field is a field reference, $$var is a variable, and a bare string is a literal. Confusing them matches nothing and raises no error." },
  { q: "$divide with a data-derived zero denominator…", options: ["Aborts the entire pipeline with an error", "Returns Infinity", "Returns null"], answer: 0,
    explain: "Guard every such division with $cond." },
  { q: "Omitting timezone from $dateTrunc or $dateToString…", options: ["Uses UTC, misassigning local evening activity", "Uses the client's timezone", "Raises an error"], answer: 0,
    explain: "One daily rollup was consistently about 4% low every Monday because of the boundary shift." },
  { q: "$facet branches…", options: ["Run on separate shards", "Can use indexes", "Cannot use indexes — they operate on the stage's input"], answer: 2,
    explain: "Filter before the facet, not inside each branch: measured 9.4 s versus 2.1 s." },
  { q: "A time series with missing days breaks a documents-based window because…", options: ["Windows require dense data", "The sort fails", "A 7-row window can span 9 calendar days, silently"], answer: 2,
    explain: "Use range with a unit, and $densify plus $fill so absent periods exist with the right value." },
  { q: "Filling a missing sales count should use…", options: ["locf", "value: 0", "linear"], answer: 1,
    explain: "Choose by meaning: zero for flows, last-observation-carried-forward for levels like a balance, linear for smooth measurements." },
  { q: "$setWindowFields replaced the self-join for running totals, measured at…", options: ["Roughly equal", "Twice as fast", "41 s versus 340 ms"], answer: 2,
    explain: "One stage instead of four, and no per-row array that could hit 16 MB." },
  { q: "$unionWith is…", options: ["An inner join", "UNION ALL — duplicates pass through", "UNION (deduplicated)"], answer: 1,
    explain: "Put the $match inside the sub-pipeline so it can use indexes, and $group afterwards if you need distinct." },
  { q: "A $merge rollup is made safe to re-run by…", options: ["An accumulating whenMatched pipeline", "Recomputing the period and using whenMatched: \"replace\"", "Running it only once"], answer: 1,
    explain: "An accumulating merge double-counts on retry — one day reported 2× revenue and went unnoticed for eleven days." },
  { q: "A rollup watermark should be advanced…", options: ["On a fixed schedule", "Before the pipeline runs", "Only after $merge succeeds"], answer: 2,
    explain: "Advancing first means a failed run permanently skips a window of data. Re-process with an overlap sized from observed arrival lag." },
  { q: "allowDiskUse: true as a response to a memory error…", options: ["Has no effect on speed", "Is the correct fix", "Converts a failure into roughly a 19× slowdown"], answer: 2,
    explain: "The limit is doing its job: a blocking stage needing more than 100 MB is processing data it should have filtered." },
  { q: "On a sharded cluster, $group…", options: ["Runs partially on each shard and finally on the merger", "Cannot be used", "Runs only on the merger"], answer: 0,
    explain: "Which is why it parallelises well, unlike $facet and $graphLookup which run only on the merging node." },
]},
{ title: "Quiz 8 · Distribution: Replica Sets & Transactions",
  desc: "Oplog, elections, write concern, rollback, read preference and transaction semantics",
  questions: [
  { q: "Replication in MongoDB works by…", options: ["Shipping data files", "Secondaries tailing the primary's oplog and replaying it", "Block-level mirroring"], answer: 1,
    explain: "Entries are idempotent — $inc is recorded as $set — and per-document, which is why bulk writes cause lag." },
  { q: "An updateMany touching 1M documents produces…", options: ["One entry per batch", "One oplog entry", "One million oplog entries"], answer: 2,
    explain: "A bulk operation is not bulk in the oplog. This is the mechanism behind backfill-induced replication lag." },
  { q: "The oplog window (timeDiff) tells you…", options: ["How large the oplog is", "How long a secondary can be down before needing a full resync", "How often checkpoints occur"], answer: 1,
    explain: "It is size divided by write rate, so a backfill collapsed one from 26 hours to 5." },
  { q: "A 4-member replica set survives…", options: ["Two failures", "One failure — the same as three members", "Three failures"], answer: 1,
    explain: "Majority rises with member count, so even numbers buy nothing and cost 33% more." },
  { q: "An arbiter is dangerous because when the data secondary fails…", options: ["The primary steps down", "Reads fail", "Redundancy drops to zero and majority writes stall, with no \"no primary\" alert"], answer: 2,
    explain: "One team spent 40 minutes investigating an \"application bug\" before running rs.status()." },
  { q: "A measured failover took 11 seconds to elect a new primary and…", options: ["7m12s to recovered service", "11 seconds to recover service", "Under a second"], answer: 0,
    explain: "DNS TTL, a JVM DNS cache and connection pools accounted for the rest. Tuning took it to 1m35s." },
  { q: "A rollback happens when…", options: ["The disk fills", "A primary that accepted non-majority writes rejoins after a failover", "A transaction aborts"], answer: 1,
    explain: "Those documents go to rollback files and are not reapplied — 2,140 acknowledged orders in one incident, found four days later." },
  { q: "w: \"majority\" without j: true survives…", options: ["Everything", "Only a clean shutdown", "Any single node failure, but not a simultaneous power loss across the majority"], answer: 2,
    explain: "Majority means \"in memory on a majority\". j: true adds the journal fsync, measured at about 1.3 ms." },
  { q: "primaryPreferred is usually the worst read preference because it…", options: ["Relieves nothing normally and goes stale exactly during a failover", "Is slowest", "Cannot be used with tags"], answer: 0,
    explain: "Choose primary or secondaryPreferred deliberately, and set maxStalenessSeconds on any secondary read." },
  { q: "The cheapest fix for read-your-own-writes is…", options: ["Increasing write concern", "Always read the primary", "Not re-reading — return the document you just wrote"], answer: 2,
    explain: "findOneAndUpdate with returnDocument: \"after\" removes both the bug and a round trip. Causal consistency is the general mechanism." },
  { q: "Replication lag's most damaging effect is…", options: ["Higher CPU", "Majority writes stalling — a write outage", "Stale secondary reads"], answer: 1,
    explain: "Flow control exists to convert that cliff into a slope by slowing the primary deliberately." },
  { q: "A delayed member protects against…", options: ["Regional loss", "Hardware failure", "Operator error, within the delay window"], answer: 2,
    explain: "It needs votes: 0 and an oplog window longer than its delay, or it silently loses its guarantee." },
  { q: "A transaction is genuinely required when…", options: ["You need isolation", "Any two writes must succeed together", "An invariant spans documents and cannot be folded into one document or an update filter"], answer: 2,
    explain: "A single-document write is already atomic across every field, array and subdocument." },
  { q: "withTransaction is preferred over manual begin/commit because it handles…", options: ["Index selection", "Both TransientTransactionError and UnknownTransactionCommitResult, which need different responses", "Connection pooling"], answer: 1,
    explain: "The first means replay the body; the second means retry only the commit, because the body may already have applied." },
  { q: "Omitting { session } on one operation inside a transaction…", options: ["Raises an error", "Makes that write commit immediately and never roll back", "Aborts the transaction"], answer: 1,
    explain: "Silent, and measured at roughly 40 half-applied records per million in one payment system." },
  { q: "Snapshot isolation does not prevent…", options: ["Lost updates on one document", "Write skew", "Dirty reads"], answer: 1,
    explain: "Two transactions each verified a cross-document invariant and wrote different documents — no conflict, both committed, invariant broken." },
  { q: "The standard fix for write skew is to…", options: ["Increase isolation", "Retry more", "Make the concurrent transactions touch a shared document so one conflicts"], answer: 2,
    explain: "A counter on the parent updated in the same transaction, for instance — it is there to create the conflict, not to be read." },
  { q: "A 44-second transaction within the 60-second limit was measured to…", options: ["Take unrelated p99 from 2.1 ms to 180 ms by pinning cache", "Work fine", "Abort"], answer: 0,
    explain: "An open snapshot prevents eviction of page versions. Raising transactionLifetimeLimitSeconds converts a failed job into a degraded cluster." },
  { q: "External side effects such as sending an email belong…", options: ["Inside the transaction callback", "In an outbox written atomically and performed by a separate idempotent worker", "After commit, inline"], answer: 1,
    explain: "The callback can run several times, and the transaction can abort after the effect." },
  { q: "A multi-shard transaction versus a single-shard one was measured at…", options: ["Twice as slow", "31 ms versus 2 ms", "Roughly equal"], answer: 1,
    explain: "Two-phase commit, with locks held on participants during the prepare phase. Co-locate transactionally-related documents." },
]},
{ title: "Quiz 9 · Production: Sharding, Durability & Operations",
  desc: "Shard keys, routing, backups, RTO/RPO, monitoring, upgrades and security",
  questions: [
  { q: "The two legitimate reasons to shard are…", options: ["Slow queries and large collections", "Disk space and backup speed", "A working set that exceeds one machine's RAM, and write throughput beyond one primary"], answer: 2,
    explain: "One team sharded 900 GB to fix p99; the cause was two unindexed queries, and sharding made it worse (240 → 410 ms)." },
  { q: "mongos can target a query to one shard only when the query…", options: ["Contains the shard key", "Is a point lookup on _id", "Uses an index"], answer: 0,
    explain: "Without it the query broadcasts — measured 2 ms targeted versus 380 ms across twelve shards." },
  { q: "A broadcast-heavy workload…", options: ["Scales linearly with shards", "Is unaffected by shard count", "Gets more expensive as you add shards"], answer: 2,
    explain: "Which is the exact opposite of what sharding is for, and why the shard key is chosen from query patterns." },
  { q: "Sharding on _id (an ObjectId) causes…", options: ["Even distribution", "A write hotspot, because ObjectIds increase monotonically", "Slow reads only"], answer: 1,
    explain: "Measured: 8 shards, all 40,000 inserts/sec on one at 98% CPU, seven idle. A read-only load test will not catch it." },
  { q: "A jumbo chunk is one that…", options: ["Exceeds 128 MB", "Cannot be split because every document shares one shard key value", "Contains orphans"], answer: 1,
    explain: "It also cannot be migrated, so that shard stays oversized — one reached 340 GB." },
  { q: "The usual right answer for a shard key is…", options: ["A single hashed field", "The _id field", "A compound key such as { tenantId: 1, createdAt: 1 }"], answer: 2,
    explain: "It distributes, targets, supports ranges within a tenant, and gives the splitter boundaries so a large tenant cannot become one jumbo chunk." },
  { q: "A unique index on a sharded collection must…", options: ["Be created before sharding", "Be prefixed by the shard key", "Use a hashed field"], answer: 1,
    explain: "Uniqueness cannot be enforced across shards, so a globally-unique requirement can make a key non-viable — verify before sharding." },
  { q: "Resharding a 900 GB collection was measured at…", options: ["Instant with a brief lock", "26 hours, +100% disk on every shard, with degraded write latency throughout", "Minutes"], answer: 1,
    explain: "Possible, but not a casual correction — the key deserves the care of an expensive-to-revisit decision." },
  { q: "Replication is a backup for…", options: ["Accidental deletes", "Everything except region loss", "Node and disk failure only"], answer: 2,
    explain: "An accidental deleteMany reached all three nodes in 11 ms — the system working exactly as designed." },
  { q: "Backups stored in the same account as production…", options: ["Restore faster", "Do not protect against credential compromise", "Are fine if encrypted"], answer: 1,
    explain: "An attacker deletes reachable backups first. Immutability in a separate account is what makes a backup a control." },
  { q: "mongodump on a 900 GB sharded cluster was measured at…", options: ["14 h to dump and 26 h to restore, with no cross-shard consistency", "Faster than snapshots", "Under an hour"], answer: 0,
    explain: "Coordinated volume snapshots took about 4 minutes with a 1h20m restore." },
  { q: "A consistent sharded backup requires…", options: ["Only shard snapshots", "A primary-only dump", "Stopping the balancer and capturing config servers plus all shards at one cluster time"], answer: 2,
    explain: "A chunk migration between snapshots can leave documents that no shard claims after a restore — silent loss on read." },
  { q: "Backup retention should be set from…", options: ["Compliance minimums", "How long it might take to notice a problem", "Storage cost"], answer: 1,
    explain: "Corruption found on day 9 with 7-day retention meant every available snapshot already contained it." },
  { q: "A designed 4-hour RTO was first measured at…", options: ["Under 4 hours", "9h47m — mostly permissions, endpoints, cold cache and missing alarms", "Exactly 4 hours"], answer: 1,
    explain: "Three engineer-days of preparation took the next drill to 52 minutes. Measure time to serving, not time to started." },
  { q: "Binary upgrade and setFeatureCompatibilityVersion should be separate steps because…", options: ["The gap between them is your rollback window", "It is faster", "FCV requires a restart"], answer: 0,
    explain: "Once FCV is raised, new formats become active and downgrading can fail outright." },
  { q: "The correct upgrade order for a sharded cluster is…", options: ["Config servers, shards, mongos", "mongos, shards, config servers", "Shards, mongos, config servers"], answer: 0,
    explain: "And check driver compatibility first — a new driver against an old server often breaks." },
  { q: "maxPoolSize defaults to 100…", options: ["Per cluster", "Per client instance", "Per collection"], answer: 1,
    explain: "Forty pods with one client each is 4,000 possible connections at roughly 1 MB of server RAM apiece." },
  { q: "Timeouts should be nested so that…", options: ["They are all equal", "maxTimeMS < server selection < application < load balancer", "The outermost is shortest"], answer: 1,
    explain: "Inverted, a layer keeps working on a request nobody is waiting for — and under load that becomes a feedback loop." },
  { q: "An application credential with the root role means…", options: ["An application bug becomes a total compromise, and the credential cannot be rotated or attributed", "Better performance", "Simpler operations"], answer: 0,
    explain: "One team's rotation of a shared credential broke four unknown systems and took three weeks." },
  { q: "Encryption at rest protects against…", options: ["A breached running server", "A stolen disk or copied snapshot", "A curious DBA"], answer: 1,
    explain: "A running mongod decrypts transparently for any authenticated session. Client-side field-level encryption is the layer that protects data from the server itself." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Interview-difficulty questions spanning the whole track",
  questions: [
  { q: "The most common serious MongoDB design mistake is…", options: ["Missing indexes", "The unbounded array", "Too many collections"], answer: 1,
    explain: "It does not degrade — it works for 14 months and then every write to that document fails at 16 MB." },
  { q: "To find documents at risk of the 16 MB limit, use…", options: ["db.stats()", "$bsonSize: \"$$ROOT\" in an aggregation", "collStats"], answer: 1,
    explain: "Monitor document size, not count — the size trend is the only warning an unbounded array gives you." },
  { q: "A growing count of distinct transaction call sites signals…", options: ["The schema drifting toward a relational model", "Good isolation", "Increased traffic"], answer: 0,
    explain: "It is a better signal than code review because it trends, and the conversation is cheaper at twenty sites than two hundred." },
  { q: "40,000 collections in one deployment consumed…", options: ["Only extra disk", "Negligible RAM", "18 GB of RAM in catalogue entries before any document was cached"], answer: 2,
    explain: "Plus four-minute startups and a schema change that means 40,000 operations. Use a tenantId field instead." },
  { q: "A single counter document written by every request produced…", options: ["Replication lag", "High CPU", "40% write conflicts and API 503s from a database at 12% CPU"], answer: 2,
    explain: "No retry policy or pool size fixes contention. Shard the counter, move it off the request path, or delete it." },
  { q: "Fourteen indexes accumulated through six months of optimisation resulted in…", options: ["No measurable change", "Write throughput halved and a system slower than before the effort began", "A faster system"], answer: 1,
    explain: "Prefix-deduping to six recovered 4.1 GB of cache and 22% write throughput with no query regression." },
  { q: "Moving analytics off the primary changed the analytics latency by nothing but…", options: ["Took unrelated p99 from 34 ms to 4 ms", "Increased lag", "Broke consistency"], answer: 0,
    explain: "Large scans and low-latency point reads want opposite things from a cache, and the cost lands on queries nobody connects to the dashboard." },
  { q: "A collection with no retention policy has…", options: ["No particular risk", "Unbounded index growth only", "A calculable date on which its working set exceeds cache"], answer: 2,
    explain: "(cache − working set) ÷ growth per day. Writing that number down is the most persuasive artefact for getting the work scheduled." },
  { q: "The first check in a live incident should be…", options: ["The slow-query log", "currentOp for long-running operations", "Replication status"], answer: 1,
    explain: "One runaway operation explains a surprising share of incidents, and killOp is triage you can perform immediately." },
  { q: "Validators, roles and indexes should be…", options: ["Managed by the DBA team only", "Applied by hand in mongosh", "Defined as code and applied by a migration"], answer: 2,
    explain: "Hand-applied configuration drifts between environments, cannot be reviewed, and turns incident forensics into archaeology." },
  { q: "Operator injection happens when a client controls…", options: ["The query's structure — the type of a value", "The query's values", "The collection name"], answer: 0,
    explain: "{\"password\": {\"$ne\": null}} logs in as any user. The fix is type validation at the boundary, not stripping $ characters." },
  { q: "Spreading a request body into $set risks…", options: ["Nothing, if the body is validated", "Privilege escalation via a field like { role: \"admin\" }", "A validation error"], answer: 1,
    explain: "No operator is even required. Allowlist the fields that may be updated." },
  { q: "The correct way to express a check-then-write on one document is…", options: ["A transaction", "A conditional update filter", "findOneAndReplace"], answer: 1,
    explain: "Measured 0.9 ms versus 4.8 ms for the transaction version, and no write conflicts to retry." },
  { q: "A backfill applies natural backpressure when written with…", options: ["w: \"majority\" and a lag-aware sleep", "w: 1 and a large batch", "A single updateMany"], answer: 0,
    explain: "With w: 1 the job outruns replication by design; 34 minutes and 4m12s lag became 9 hours with 6.4 s lag and no impact." },
  { q: "A partial index is the right tool when…", options: ["The interesting value is rare and always present in the query", "The collection is small", "You need uniqueness"], answer: 0,
    explain: "9.2 GB became 140 MB on a 0.6% subset, with the write cost falling proportionally." },
  { q: "$merge turns an expensive aggregation into…", options: ["A faster aggregation", "A point read against a small summary collection", "A materialised index"], answer: 1,
    explain: "On one dashboard, tuning gave 4.6× and pre-computation gave another 55× — with cost independent of traffic." },
  { q: "Testing pipelines against staging data misses…", options: ["Cardinality-driven memory failures", "Index usage", "Syntax errors"], answer: 0,
    explain: "40 group keys in staging and 2.1M in production, same code — only one of them spills." },
  { q: "An untested backup is…", options: ["Sufficient if monitored", "A hypothesis", "Adequate for most cases"], answer: 1,
    explain: "First drills usually fail on missing permissions, undocumented steps and an endpoint nobody thought about — not on corrupt data." },
  { q: "Across a single region, w: \"majority\" versus w: 1 costs roughly…", options: ["10× latency", "Nothing measurable", "About 0.9 ms extra at p50"], answer: 2,
    explain: "Which makes w: 1 a deliberate exception for a specific high-volume path rather than a sensible default." },
  { q: "The most useful habit this track can leave you with is…", options: ["Asking of every design: what does this look like at 100× the data?", "Indexing every queried field", "Reading the release notes"], answer: 0,
    explain: "Every measurement in these lessons is what happened to someone who did not ask it." },
]},
);
