// MongoDB quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Documents & Collections",
  desc: "Document model, BSON, ObjectId, schema flexibility",
  questions: [
  { q: "MongoDB stores data as…", options: ["Rows in tables", "Documents (BSON) in collections", "Key-value pairs only"], answer: 1,
    explain: "Flexible JSON-like documents; collections hold them." },
  { q: "The MongoDB equivalent of a SQL row is a…", options: ["Collection", "Document", "Field"], answer: 1,
    explain: "table→collection, row→document, column→field, id→_id." },
  { q: "_id (ObjectId) is…", options: ["Random only", "A time-ordered, globally-unique, client-generatable primary key", "Sequential like SQL auto-increment"], answer: 1,
    explain: "12 bytes: timestamp + machine/process + counter — no central sequence." },
  { q: "BSON adds to JSON…", options: ["Nothing", "Types like ObjectId, ISODate, Decimal128, Binary", "Only compression"], answer: 1,
    explain: "Binary JSON with richer types." },
  { q: "MongoDB is best described as…", options: ["Schemaless", "Schema-FLEXIBLE (enforce where you choose)", "Rigid schema"], answer: 1,
    explain: "Real apps have implicit schemas; add $jsonSchema validation." },
  { q: "The document model's core idea is…", options: ["Normalize everything", "Store data accessed together, together (locality)", "Avoid arrays"], answer: 1,
    explain: "Single fast reads without joins for the right access patterns." },
  { q: "For money, use…", options: ["double", "Decimal128 (NumberDecimal)", "String"], answer: 1,
    explain: "Same float-rounding trap as everywhere." },
  { q: "Two documents in one collection with different fields are…", options: ["Illegal", "Legal (schema-flexible)", "Auto-corrected"], answer: 1,
    explain: "Flexibility helps evolution; discipline prevents chaos." },
  { q: "$jsonSchema validation…", options: ["Is impossible", "Enforces required fields/types at write time", "Slows all reads"], answer: 1,
    explain: "'Flexible' doesn't mean 'no rules'." },
  { q: "The max BSON document size is…", options: ["Unlimited", "16MB", "1GB"], answer: 1,
    explain: "Drives bounded-array and bucket/subset patterns." },
  { q: "You can override _id with…", options: ["Never", "Your own unique value (natural key)", "Only integers"], answer: 1,
    explain: "Must remain unique per collection." },
  { q: "ObjectId embeds a…", options: ["Password", "Creation timestamp (roughly time-ordered)", "Shard id"], answer: 1,
    explain: "Doubles as a creation time and sorts chronologically." },
  { q: "A collection is like a SQL…", options: ["Database", "Table (but schema-flexible)", "Row"], answer: 1,
    explain: "Created on first write." },
  { q: "Nested/embedded documents are…", options: ["Not allowed", "First-class (address inside user)", "Stored separately always"], answer: 1,
    explain: "Enables locality — data read together stored together." },
  { q: "Arrays as field values are…", options: ["Discouraged", "First-class and queryable", "Stored as strings"], answer: 1,
    explain: "With multikey indexing and array operators." },
  { q: "The main trade-off vs relational is…", options: ["None", "Locality/flexibility vs native joins & some consistency guarantees", "Speed only"], answer: 1,
    explain: "Great for document-shaped access; harder for highly relational data." },
  { q: "'Schemaless dumping ground' leads to…", options: ["Speed", "Inconsistent data + defensive code (an anti-pattern)", "Better design"], answer: 1,
    explain: "Model for access patterns; validate." },
  { q: "Atlas is…", options: ["A driver", "MongoDB's managed cloud service", "A shard key"], answer: 1,
    explain: "Common production deployment; connect via a URI." },
  { q: "Client-side _id generation matters for…", options: ["Nothing", "Distributed writes/sharding (no central sequence needed)", "Encryption"], answer: 1,
    explain: "A key ObjectId advantage over auto-increment." },
  { q: "The first question before modeling a MongoDB schema is…", options: ["What indexes?", "What are the queries, and how often? (access patterns)", "Which driver?"], answer: 1,
    explain: "Access patterns dictate embed/reference, indexes, shard key." }
]},

{ title: "Quiz 2 · CRUD Operations",
  desc: "insert/find/update/delete, operators, upsert, atomicity",
  questions: [
  { q: "Update without operators like $set…", options: ["Updates one field", "REPLACES the whole document (or errors in modern drivers)", "Does nothing"], answer: 1,
    explain: "Use $set etc. for partial updates; replaceOne for full replace." },
  { q: "$inc is used to…", options: ["Insert", "Atomically increment a numeric field", "Index"], answer: 1,
    explain: "Race-safe counters/balances in one update." },
  { q: "upsert: true…", options: ["Deletes", "Inserts if the filter matches nothing, else updates (atomic create-or-update)", "Errors on no match"], answer: 1,
    explain: "Avoids the SELECT-then-insert race." },
  { q: "A single-document write is…", options: ["Never atomic", "ATOMIC (even across embedded arrays/subdocs)", "Atomic only in a transaction"], answer: 1,
    explain: "Why embedding avoids many transactions." },
  { q: "$push vs $addToSet:", options: ["Same", "$push always appends; $addToSet appends only if absent", "$push dedupes"], answer: 1,
    explain: "$addToSet = set semantics." },
  { q: "find() returns…", options: ["An array", "A cursor (lazy, batched)", "One document"], answer: 1,
    explain: "toArray() materializes; iterate once." },
  { q: "insertMany with { ordered: false }…", options: ["Stops on first error", "Continues past errors (parallel-ish)", "Is invalid"], answer: 1,
    explain: "Default ordered:true stops on first error." },
  { q: "deleteMany({})…", options: ["Deletes one", "Deletes EVERYTHING (like DELETE without WHERE)", "Errors"], answer: 1,
    explain: "Test filters with find() first." },
  { q: "Safe balance decrement uses…", options: ["Read then write in app", "updateOne with $inc guarded by $gte + check matchedCount", "Two queries"], answer: 1,
    explain: "Atomic; app read-modify-write races." },
  { q: "$set on a missing field…", options: ["Errors", "Creates it", "Ignored"], answer: 1,
    explain: "$unset removes; $rename renames." },
  { q: "Multi-document atomicity requires…", options: ["Nothing", "An explicit transaction", "$set"], answer: 1,
    explain: "Single-doc is atomic by default; multi-doc needs a transaction." },
  { q: "findOneAndUpdate can…", options: ["Only find", "Update AND return the document (before/after)", "Only delete"], answer: 1,
    explain: "With upsert + returnDocument options." },
  { q: "Checking matchedCount/modifiedCount…", options: ["Is pointless", "Confirms whether the write actually applied", "Slows writes"], answer: 1,
    explain: "0 matched = filter matched nothing." },
  { q: "$currentDate does…", options: ["Sorts", "Sets a field to the current date/timestamp", "Filters"], answer: 1,
    explain: "Handy for updatedAt." },
  { q: "Projection in find(query, projection)…", options: ["Filters rows", "Selects which FIELDS return", "Sorts"], answer: 1,
    explain: "Smaller payloads; covered queries." },
  { q: "replaceOne is for…", options: ["Partial updates", "Explicit full-document replacement", "Deletes"], answer: 1,
    explain: "Use operators for partial changes." },
  { q: "$pull removes…", options: ["A field", "Array elements matching a condition", "The document"], answer: 1,
    explain: "$pull for array element removal." },
  { q: "Iterating a cursor twice…", options: ["Works", "The second pass is empty — re-query or toArray()", "Errors"], answer: 1,
    explain: "Cursors are single-pass." },
  { q: "The upsert insert is built from…", options: ["Nothing", "The filter + update operators", "A template"], answer: 1,
    explain: "Filter equality fields + $set values seed the new doc." },
  { q: "Embedding + single-doc atomicity means…", options: ["More transactions", "Most 'transactions' become one atomic update", "Slower writes"], answer: 1,
    explain: "A core MongoDB design advantage." }
]},

{ title: "Quiz 3 · Query Operators & Projection",
  desc: "Operators, array queries, $elemMatch, projection, regex",
  questions: [
  { q: "{ score: { $gt: 80 } } means…", options: ["score = 80", "score > 80", "score >= 80"], answer: 1,
    explain: "$gt/$gte/$lt/$lte/$ne/$in/$nin comparison operators." },
  { q: "{ tags: 'admin' } on an array field…", options: ["Exact-array match", "Array CONTAINS 'admin'", "First element only"], answer: 1,
    explain: "Membership in the array." },
  { q: "$elemMatch is needed when…", options: ["Never", "Multiple conditions must hold on the SAME array element", "Sorting arrays"], answer: 1,
    explain: "Plain dot-notation matches across DIFFERENT elements." },
  { q: "{ 'items.product':'A', 'items.qty':{$gt:3} } without $elemMatch…", options: ["Same element only", "Can match A in one element and qty>3 in ANOTHER", "Errors"], answer: 1,
    explain: "The classic array-condition bug." },
  { q: "Projection { name:1, score:1 } returns…", options: ["All fields", "name, score (+ _id by default)", "Nothing"], answer: 1,
    explain: "Include mode; add _id:0 to drop it." },
  { q: "Mixing include (1) and exclude (0) in projection…", options: ["Is fine", "Errors (except _id:0 alongside includes)", "Ignores one"], answer: 1,
    explain: "All 1s or all 0s." },
  { q: "$in does…", options: ["Range", "Membership in a set of values", "Negation"], answer: 1,
    explain: "role: { $in: ['admin','editor'] }." },
  { q: "$exists checks…", options: ["Value equality", "Whether a field is present", "Type"], answer: 1,
    explain: "$type checks the BSON type." },
  { q: "Left-anchored regex /^A/…", options: ["Always scans", "Can use a B-tree index (prefix)", "Is invalid"], answer: 1,
    explain: "Unanchored/case-insensitive regex scans." },
  { q: "For real text search, use…", options: ["Regex always", "A text index + $text, or Atlas Search", "$in"], answer: 1,
    explain: "Tokenized/stemmed matching vs slow regex." },
  { q: "$all on an array means…", options: ["Any element", "Contains ALL listed values", "Exactly these"], answer: 1,
    explain: "$size checks length." },
  { q: "AND across different fields is…", options: ["Explicit $and required", "Implicit (just list them)", "Not supported"], answer: 1,
    explain: "$and needed mainly for same-field conditions." },
  { q: "The positional $ in projection returns…", options: ["All array elements", "The FIRST matching array element", "The last"], answer: 1,
    explain: "{ 'items.$': 1 }." },
  { q: "$slice in projection…", options: ["Filters docs", "Limits returned array elements", "Sorts"], answer: 1,
    explain: "e.g., first 5 comments." },
  { q: "Deep skip() pagination is…", options: ["Fast", "Slow (like SQL OFFSET) — use range/keyset on _id", "Impossible"], answer: 1,
    explain: "Scans-and-discards." },
  { q: "distinct('plan') returns…", options: ["Counts", "The unique values of the field", "Sorted docs"], answer: 1,
    explain: "Like SQL DISTINCT on one field." },
  { q: "Sorting without a tiebreaker gives…", options: ["Stable order", "Unstable pagination — add _id", "Errors"], answer: 1,
    explain: "Same as SQL." },
  { q: "$ne excludes but also…", options: ["Includes NULLs cleanly", "May behave subtly with missing fields — verify intent", "Errors"], answer: 1,
    explain: "Test negation queries against missing/NULL fields." },
  { q: "Dot notation ('address.city') queries…", options: ["Top-level only", "Into nested subdocuments", "Arrays only"], answer: 1,
    explain: "Reach into embedded documents." },
  { q: "Projection improves performance by…", options: ["Nothing", "Reducing payload and enabling covered queries", "Sorting faster"], answer: 1,
    explain: "Like naming columns instead of SELECT *." }
]},

{ title: "Quiz 4 · Schema Design (Embed vs Reference)",
  desc: "The core MongoDB skill: access patterns, patterns, duplication",
  questions: [
  { q: "MongoDB schema design is driven by…", options: ["Normalization rules", "ACCESS PATTERNS (what queries run, how often)", "Data types"], answer: 1,
    explain: "The reframing that unlocks MongoDB." },
  { q: "Embed when…", options: ["Data is queried independently", "Data is read together, one-to-few, bounded", "One-to-many unbounded"], answer: 1,
    explain: "Single fast read + single-doc atomicity." },
  { q: "Reference when…", options: ["One-to-one", "One-to-many unbounded / shared / independently-queried", "Always"], answer: 1,
    explain: "Avoids unbounded arrays and 16MB limit." },
  { q: "The subset pattern…", options: ["Embeds everything", "Embeds the frequently-read portion (latest N), keeps full set in a collection", "Shards data"], answer: 1,
    explain: "Fast common read + full data available." },
  { q: "The bucket pattern…", options: ["Splits collections", "Groups many small items (time-series) into fewer bucket documents", "Deletes old data"], answer: 1,
    explain: "Bounded arrays, less overhead." },
  { q: "Extended reference means…", options: ["A bigger _id", "Duplicating a few rarely-changing fields to avoid a join", "Sharding"], answer: 1,
    explain: "Denormalization for read speed." },
  { q: "$lookup should be…", options: ["The default join", "A tool used sparingly (default = SQL-style modeling)", "Never used"], answer: 1,
    explain: "$lookup-on-every-request signals wrong modeling." },
  { q: "Duplicating an author's name onto orders is…", options: ["Always a bug", "Fine if it rarely changes (with a sync plan)", "Required"], answer: 1,
    explain: "Duplicate rarely-changing/snapshot data." },
  { q: "Storing price-at-purchase on the order is…", options: ["Denormalization to fix", "Correct temporal modeling (historical snapshot)", "A mistake"], answer: 1,
    explain: "The historical price must not change with the product." },
  { q: "The same entities can be modeled…", options: ["Only one way", "Differently depending on access patterns", "Only normalized"], answer: 1,
    explain: "No universal 'correct' schema." },
  { q: "An unbounded embedded array (all comments)…", options: ["Is best", "Hits 16MB, slows updates — reference/subset/bucket", "Is required"], answer: 1,
    explain: "Keep embedded arrays bounded." },
  { q: "One-to-squillions (logs per host) uses…", options: ["Embed all", "Parent-reference (host_id on each log)", "$lookup"], answer: 1,
    explain: "The child references the parent." },
  { q: "The computed pattern…", options: ["Recomputes per read", "Stores precomputed totals updated on write", "Uses $lookup"], answer: 1,
    explain: "Avoid recomputing aggregates each read." },
  { q: "SQL-style modeling in MongoDB causes…", options: ["Speed", "$lookup sprawl and lost locality (an anti-pattern)", "Better design"], answer: 1,
    explain: "Embed data read together." },
  { q: "The heuristic for embed vs reference is…", options: ["Always normalize", "'Data accessed together, stored together' + cardinality", "Random"], answer: 1,
    explain: "Cardinality and update frequency break ties." },
  { q: "One-to-few relationships…", options: ["Reference", "Embed (bounded array)", "Shard"], answer: 1,
    explain: "e.g., a user's few addresses." },
  { q: "The write-side cost of duplication buys…", options: ["Nothing", "Read-side speed (fewer joins)", "Smaller storage"], answer: 1,
    explain: "The core denormalization trade." },
  { q: "Reference frequently-changing shared data because…", options: ["It's faster to embed", "Keeping duplicates in sync becomes painful/stale", "It's required"], answer: 1,
    explain: "Duplicate only rarely-changing data." },
  { q: "The schema-design lesson is also a…", options: ["Syntax lesson", "PERFORMANCE lesson (most perf issues are schema issues)", "Security lesson"], answer: 1,
    explain: "Access-pattern modeling prevents scale problems." },
  { q: "Before modeling, you should…", options: ["Pick indexes", "List the queries and their frequencies", "Choose a shard key"], answer: 1,
    explain: "Everything else follows from access patterns." }
]},

{ title: "Quiz 5 · Aggregation Pipeline",
  desc: "Stages, $group, $unwind, ordering, performance",
  questions: [
  { q: "The aggregation pipeline is…", options: ["A single query", "Ordered stages transforming a stream of documents", "An index"], answer: 1,
    explain: "MongoDB's GROUP BY + reshape + join engine." },
  { q: "$match should be placed…", options: ["Last", "FIRST (filter early, use indexes, shrink data)", "Anywhere"], answer: 1,
    explain: "The #1 aggregation performance rule." },
  { q: "$group requires…", options: ["Nothing", "_id (the group key) + accumulators", "$sort first"], answer: 1,
    explain: "_id null groups the whole collection." },
  { q: "$sum, $avg, $push are…", options: ["Filters", "Accumulators used in $group", "Indexes"], answer: 1,
    explain: "$push collects values into an array." },
  { q: "$unwind does…", options: ["Sorts arrays", "Emits one document per array element (flattens)", "Removes arrays"], answer: 1,
    explain: "For element-level grouping/analysis." },
  { q: "$lookup performs…", options: ["A filter", "A left join to another collection", "A sort"], answer: 1,
    explain: "Use sparingly — not the default." },
  { q: "An index helps aggregation only…", options: ["Anywhere in the pipeline", "When $match/$sort are near the FRONT", "Never"], answer: 1,
    explain: "After $group the stream is no longer index-backed." },
  { q: "The per-stage memory limit is…", options: ["Unlimited", "100MB (use allowDiskUse for big $group/$sort)", "16MB"], answer: 1,
    explain: "Or add supporting indexes." },
  { q: "$project / $set (addFields)…", options: ["Filter docs", "Reshape: include/exclude/compute fields", "Join"], answer: 1,
    explain: "Like SELECT with expressions." },
  { q: "$facet lets you…", options: ["Shard", "Run multiple sub-pipelines at once (dashboards)", "Index"], answer: 1,
    explain: "e.g., count + top-N in one query." },
  { q: "Grouping by multiple fields uses…", options: ["Two $group stages", "_id as a subdocument { a:'$a', b:'$b' }", "$facet"], answer: 1,
    explain: "Composite group key." },
  { q: "$unwind on a huge array unfiltered…", options: ["Is fine", "Explodes document count — $match first", "Sorts it"], answer: 1,
    explain: "Watch cardinality/memory." },
  { q: "$setWindowFields provides…", options: ["Sharding", "Window functions (running totals/rank)", "Text search"], answer: 1,
    explain: "MongoDB's SQL-window equivalent." },
  { q: "explain('executionStats') on aggregation shows…", options: ["Nothing", "Whether stages used an index (IXSCAN vs COLLSCAN)", "The schema"], answer: 1,
    explain: "Verify $match uses an index." },
  { q: "$merge / $out…", options: ["Filter", "Write pipeline results to a collection", "Join"], answer: 1,
    explain: "Materialize aggregation output." },
  { q: "$dateToString is used to…", options: ["Sort", "Format dates (e.g., group by %Y-%m)", "Filter"], answer: 1,
    explain: "Common in time-based reports." },
  { q: "The right stage order for a report is roughly…", options: ["$group→$match", "$match→$group→$sort→$project", "$sort→$match"], answer: 1,
    explain: "Filter, aggregate, order, reshape." },
  { q: "$count returns…", options: ["Sums", "The number of documents at that stage", "Averages"], answer: 1,
    explain: "A terminal counting stage." },
  { q: "$bucket creates…", options: ["Shards", "Histogram-style groupings by ranges", "Indexes"], answer: 1,
    explain: "For distributions/histograms." },
  { q: "Heavy $lookup on hot paths signals…", options: ["Good design", "SQL-style modeling — reconsider embedding", "Missing index"], answer: 1,
    explain: "The schema, not the query, is often the fix." }
]}
);
