// mongodb quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations: The Document Model & BSON",
  desc: "Atomicity, BSON types, _id, working set, write and read concern",
  questions: [
  { q: "What is MongoDB's core atomicity guarantee?", options: ["Only inserts are atomic", "All writes in a session are atomic", "A write to a single document is atomic, however many fields it touches"], answer: 2,
    explain: "Single-document atomicity is the primitive every design rule follows from — it is why embedding what changes together removes the need for transactions." },
  { q: "\"Schemaless\" in MongoDB accurately describes…", options: ["The database, which does not enforce a schema — your data still has one", "A mode you enable", "Your data, which has no structure"], answer: 0,
    explain: "One system held 2.1M users in 6 shapes with defensive branches in 14 call sites. The schema moved into the application; it did not disappear." },
  { q: "Why should money be stored as Decimal128 rather than double?", options: ["Decimal128 is faster", "double cannot represent decimal fractions exactly, so sums drift", "double has a lower maximum value"], answer: 1,
    explain: "Binary floating point cannot represent 19.99 exactly. Accumulated over millions of rows the error is visible in a finance report." },
  { q: "BSON differs from JSON principally because it is…", options: ["Text-based", "Typed and length-prefixed, so fields can be skipped without parsing", "Compressed"], answer: 1,
    explain: "Length prefixes let the engine skip a subdocument it does not need; JSON must be parsed character by character." },
  { q: "Type bracketing means that a range query…", options: ["Compares across all BSON types", "Only matches values of the same type as the operand", "Fails on mixed types"], answer: 1,
    explain: "It is silent data loss: { total: { $gt: 100 } } with a double operand skips every Decimal128 document and returns a confidently wrong answer." },
  { q: "An ObjectId encodes…", options: ["A timestamp plus machine/process identity plus a counter", "A random 12 bytes", "A hash of the document"], answer: 0,
    explain: "That is why ObjectIds are time-ordered — and why they are a poor ranged shard key." },
  { q: "Updating one small field in a 6 MB document writes…", options: ["The whole document", "Only the changed bytes", "Nothing until a checkpoint"], answer: 0,
    explain: "Whole-document rewrite amplification is one of the four costs of an unbounded array." },
  { q: "The WiredTiger cache holds…", options: ["Compressed blocks", "Only indexes", "Uncompressed pages, competing between indexes and documents"], answer: 2,
    explain: "The OS filesystem cache holds compressed blocks; both matter, but the WiredTiger cache is the one that produces the cliff." },
  { q: "Which metric warns you before the cache cliff?", options: ["Cache utilisation percentage", "CPU above 80%", "pages evicted by application threads > 0"], answer: 2,
    explain: "Healthy is exactly zero, so any sustained value is a clean alert. Measured: p99 1.9 ms at 97% of cache, 340 ms at 112%." },
  { q: "The default write concern since MongoDB 5.0 is…", options: ["w: \"majority\"", "w: 1", "w: 0"], answer: 0,
    explain: "Majority-acknowledged writes cannot be rolled back, because any node that can win an election already has them." },
  { q: "The default read concern is…", options: ["\"majority\"", "\"snapshot\"", "\"local\""], answer: 2,
    explain: "Majority writes with local reads is the default mismatch — a read can return data that a rollback later removes." },
  { q: "A query examining 8.4M documents to return 50 tells you…", options: ["There is no usable index for that predicate", "The server is overloaded", "The collection is too big"], answer: 0,
    explain: "Index-or-scan: the same query with the right index went from 41 s to 9 ms examining 50 documents." },
  { q: "An array field in a document is stored internally as…", options: ["A packed binary blob", "A special array type", "A document with numeric string keys"], answer: 2,
    explain: "Which is why positional operators and dotted paths like items.0.sku work the way they do." },
  { q: "Round-tripping a document through JSON risks…", options: ["Nothing", "Retyping — Decimal128 and Date become strings or doubles", "Data truncation only"], answer: 1,
    explain: "The classic source of a half-typed collection that then breaks range queries via type bracketing." },
  { q: "wtimeout firing means…", options: ["The write was rejected", "The write already applied and its durability is unknown", "The write was cancelled"], answer: 1,
    explain: "Retrying without an idempotency key double-applies. One payment system created 340 duplicate charges this way." },
  { q: "Which is true of the 16 MB document limit?", options: ["It can be raised in configuration", "It applies only to inserts", "It applies to any document, including aggregation output documents"], answer: 2,
    explain: "A $group building an array with $push produces an output document subject to the same limit." },
  { q: "Choosing your own _id rather than an ObjectId is…", options: ["Never allowed", "Only for sharded collections", "Allowed, and worth it when a natural unique key exists — it removes an index"], answer: 2,
    explain: "The _id index always exists, so a natural key stored there saves the second unique index you would otherwise need." },
  { q: "The right way to think about capacity is…", options: ["Total collection size", "The working set — indexes plus hot documents", "Document count"], answer: 1,
    explain: "A 4 TB collection with a 20 GB hot set is comfortable on 64 GB; a 200 GB randomly-accessed one is not." },
  { q: "The best mental model for MongoDB schema design is…", options: ["Mirror your entity-relationship diagram", "Normalise, then denormalise for speed", "Model what one request needs"], answer: 2,
    explain: "A relational model describes entities and lets the engine assemble them; a document model describes the assembled result." },
  { q: "MongoDB is a poor fit when…", options: ["You need complex ad-hoc joins across many entities and full relational integrity", "You need high write throughput", "Documents vary in shape"], answer: 0,
    explain: "An honest fit assessment beats a migration. Record the decision with a dated revisit trigger." },
]},
{ title: "Quiz 2 · Foundations: CRUD, Queries & Operators",
  desc: "Conditional updates, upserts, arrays, projections, sorts and pagination",
  questions: [
  { q: "The safe way to do check-then-write on one document is…", options: ["find() then updateOne()", "Put the condition in the update filter", "Wrap both in a transaction"], answer: 1,
    explain: "updateOne({ _id, balance: { $gte: amt } }, { $inc: { balance: -amt } }) is an atomic compare-and-swap and needs no transaction." },
  { q: "replaceOne differs from updateOne in that it…", options: ["Cannot upsert", "Is faster", "Replaces the entire document, silently dropping fields you did not send"], answer: 2,
    explain: "The classic data-loss operation: a client that reads an old document shape and replaces with it deletes every newer field." },
  { q: "Two concurrent upserts on the same key can both insert unless…", options: ["You retry", "A unique index exists on that key", "You use w: majority"], answer: 1,
    explain: "The unique index is what turns the race into a duplicate-key error you can handle." },
  { q: "matchedCount of 0 from updateOne means…", options: ["An error occurred", "The document was unchanged", "The filter matched nothing — often your precondition failed"], answer: 2,
    explain: "Distinguish it from modifiedCount 0, which means the document matched but the update was a no-op." },
  { q: "{ scores: { $gte: 80, $lte: 90 } } on an array field matches when…", options: ["Any element is ≥ 80 AND any (possibly different) element is ≤ 90", "All elements satisfy both", "One element satisfies both"], answer: 0,
    explain: "Array conditions match independently. $elemMatch is what requires a single element to satisfy all conditions." },
  { q: "$elemMatch exists to…", options: ["Match array length", "Project one element", "Require one array element to satisfy all conditions"], answer: 2,
    explain: "It also makes the query indexable as a single contiguous range — measured 310,000 keys examined versus 340." },
  { q: "$ne and $nin generally cannot use an index because…", options: ["They are unsupported", "They describe two disjoint ranges covering nearly the whole index", "They require a collection scan by design"], answer: 1,
    explain: "Rewrite as $in over the positive set so each value becomes its own indexed seek." },
  { q: "A blocking in-memory sort is capped at…", options: ["100 MB", "32 MB", "16 MB"], answer: 1,
    explain: "Above it the query fails unless allowDiskUse is set. Getting the sort from the index avoids the stage entirely." },
  { q: "skip() for deep pagination is slow because it…", options: ["Locks the collection", "Walks and discards the skipped entries", "Re-runs the query"], answer: 1,
    explain: "Measured 4 ms on page 1 and 2,100 ms on page 5,000 — with a perfect index. It is not an indexing problem." },
  { q: "Keyset pagination requires an _id tie-break because…", options: ["The driver requires it", "Equal sort-key values across a page boundary would duplicate or skip rows", "It is faster"], answer: 1,
    explain: "The bug appears only under load and is nearly impossible to reproduce from a user report." },
  { q: "An unanchored regex like /smith/ on an indexed field…", options: ["Cannot bound the scan", "Uses the index efficiently", "Is rejected"], answer: 0,
    explain: "/^smith/ is anchored and bounded; adding the i flag defeats the anchor because case folding changes key ordering." },
  { q: "findOneAndUpdate is particularly useful for…", options: ["Replacing documents", "Bulk writes", "Atomically claiming a work item and getting it back"], answer: 2,
    explain: "The claim pattern: filter on the pending state, set it to claimed, and return the document — all in one atomic operation." },
  { q: "An unordered bulkWrite differs from an ordered one because it…", options: ["Continues after an error and can be executed in parallel", "Is atomic", "Guarantees ordering per document"], answer: 0,
    explain: "Ordered stops at the first error; unordered reports all errors at the end and is usually faster." },
  { q: "retryWrites in the driver covers…", options: ["Every operation", "Retryable write operations, once, through a failover", "Only inserts"], answer: 1,
    explain: "It absorbs a step-down transparently — but it does not make your own application-level retries idempotent." },
  { q: "Returning whole documents when you need six fields costs…", options: ["Nothing measurable", "Only disk", "BSON size, network, driver CPU — and the chance of a covered query"], answer: 2,
    explain: "Measured 740 MB versus 31 MB on one endpoint, none of which appears in executionTimeMillis." },
  { q: "countDocuments({}) on 41M documents versus estimatedDocumentCount()…", options: ["Both are instant", "6.4 seconds versus about 1 ms", "estimatedDocumentCount is slower"], answer: 1,
    explain: "The estimate reads metadata and takes no filter; countDocuments runs a real aggregation over every matching key." },
  { q: "A TTL index deletes expired documents…", options: ["Immediately at expiry", "At the next checkpoint", "In background batches, which fall behind under load"], answer: 2,
    explain: "Measured 12 minutes late on average and 47 at peak — never rely on it for security enforcement." },
  { q: "A date stored as an ISO string with a TTL index…", options: ["Is never expired, silently", "Raises an error", "Expires normally"], answer: 0,
    explain: "The field must be a BSON Date. One collection accumulated 340 GB of \"expiring\" sessions this way." },
  { q: "$where and $function are best avoided because they…", options: ["Only work on secondaries", "Are deprecated", "Run server-side JavaScript, cannot use indexes, and are an injection surface"], answer: 2,
    explain: "Measured 94 s versus 3.1 s for logic expressible with native operators." },
  { q: "Projecting only indexed fields with _id: 0 can produce…", options: ["A slower query", "A covered query that never reads a document", "An error"], answer: 1,
    explain: "Verify with totalDocsExamined: 0. Forgetting _id: 0 is the most common reason covering silently fails." },
]},
{ title: "Quiz 3 · Schema Design: Embed vs Reference & Patterns",
  desc: "Locality, duplication, the killers of embedding, and the classic patterns",
  questions: [
  { q: "The strongest argument for embedding is…", options: ["One atomic write and one read for data used together", "It saves disk", "It normalises the model"], answer: 0,
    explain: "Locality plus single-document atomicity is what makes the document model worth using." },
  { q: "Which is a killer for embedding?", options: ["Any duplication", "Unbounded growth of the embedded array", "More than three fields"], answer: 1,
    explain: "The other two killers are independent access (you need the child without the parent) and write contention on a single hot parent document." },
  { q: "Duplication in a document model is…", options: ["A deliberate trade — the question is whether the copy is a snapshot or a stale live value", "Only acceptable for small fields", "Always a bug"], answer: 0,
    explain: "A price on an order line is a snapshot and should never change. A user's display name is a live reference and needs a propagation plan." },
  { q: "The extended reference pattern stores…", options: ["Only the id", "The id plus the few fields the read actually needs", "The whole referenced document"], answer: 1,
    explain: "It removes the join for the common read while keeping the reference authoritative." },
  { q: "The subset pattern is used when…", options: ["You need a bounded slice embedded and the full set in its own collection", "Documents are small", "You need a transaction"], answer: 0,
    explain: "Recent comments on a post, recent orders on a customer — the page renders from one document and the archive lives elsewhere." },
  { q: "The bucket pattern groups many small records into…", options: ["A capped collection", "One document per time period or key range", "One document per record"], answer: 1,
    explain: "Far fewer documents and far less per-document overhead, with growth bounded per bucket." },
  { q: "The computed pattern means…", options: ["Using $expr in queries", "Computing values in the driver", "Storing a derived value at write time instead of recomputing it on read"], answer: 2,
    explain: "A maintained count or total turns an expensive aggregation into a field read — at the cost of a reconciler." },
  { q: "A 1-to-many relationship where \"many\" is unbounded should be…", options: ["A single array with $slice", "A separate collection with a reference", "Embedded"], answer: 1,
    explain: "Unbounded growth is the first killer of embedding, and it fails at 16 MB with no warning." },
  { q: "Write contention on a single hot parent document argues for…", options: ["Adding an index", "Embedding more", "Splitting the children into their own documents"], answer: 2,
    explain: "Every child write rewrites the parent, so concurrent writers conflict on one document." },
  { q: "The polymorphic pattern handles…", options: ["Schema versions", "Mixed types in one field", "Documents of different shapes sharing a collection, with a type discriminator"], answer: 2,
    explain: "Common when several related entities share access patterns; a type field plus per-type validation keeps it manageable." },
  { q: "The attribute pattern turns unpredictable keys into…", options: ["Separate collections", "A wildcard index", "An array of { k, v } pairs that one compound index can serve"], answer: 2,
    explain: "It avoids an index per attribute, which is the alternative when every product category has different fields." },
  { q: "The outlier pattern exists because…", options: ["A small number of entities are far larger than the rest and would otherwise dictate the design", "Indexes skew", "Some documents are corrupt"], answer: 0,
    explain: "Flag the outliers and handle them with an overflow collection instead of designing the whole schema around them." },
  { q: "Choosing embed versus reference should be driven mainly by…", options: ["The queries you run and how the data changes", "Entity relationships", "Data size alone"], answer: 0,
    explain: "Cardinality, access independence, growth, update frequency and contention are the five decision inputs." },
  { q: "A snapshot copy differs from a live reference in that it…", options: ["Must never be updated when the source changes", "Is always denormalised", "Is smaller"], answer: 0,
    explain: "Conflating the two is why \"denormalisation is dangerous\" gets repeated — the danger is only in the live-reference case." },
  { q: "Embedding a bounded array of about 20 subdocuments is…", options: ["Usually correct if they are owned by the parent and read with it", "Only acceptable if indexed", "Always wrong"], answer: 0,
    explain: "Bounded, owned and co-accessed is exactly the case embedding is for." },
  { q: "Reading a 4 KB document to display three fields wastes…", options: ["Nothing", "Only network", "Cache, since the whole document is loaded"], answer: 2,
    explain: "It is one of the four costs of oversized documents, and a covered query avoids it entirely." },
  { q: "A join table containing only two ids is…", options: ["Required for many-to-many", "A relational habit worth reconsidering in a document model", "Good normalisation"], answer: 1,
    explain: "An array of ids on whichever side is queried is usually simpler and one read fewer." },
  { q: "The correct response to \"we need a transaction for this\" is first to ask…", options: ["Is the cluster sharded?", "Could these be one document, or the condition be part of the update filter?", "Which isolation level?"], answer: 1,
    explain: "A transaction on every write is a signal that the schema is modelled relationally." },
  { q: "Schema design should be revisited when…", options: ["Access patterns change — the design serves the queries, not the entities", "The collection doubles in size", "Never, once shipped"], answer: 0,
    explain: "New features introduce new query shapes, and a model tuned to the old ones stops paying off." },
  { q: "The most reliable schema-design question is…", options: ["What does this look like at 100× the data?", "Is this normalised?", "How many collections is this?"], answer: 0,
    explain: "Almost every anti-pattern in the track is a design that works at 1× and fails at 100×." },
]},
{ title: "Quiz 4 · Schema Design: Relationships, Validation & Evolution",
  desc: "$lookup semantics, integrity, $jsonSchema, migrations and backfills",
  questions: [
  { q: "A reference between two MongoDB documents is enforced by…", options: ["A foreign key", "A unique index", "Nothing — integrity is entirely an application concern"], answer: 2,
    explain: "One audit found 3,100 orders pointing at customers that had been deleted, accumulated silently over three years." },
  { q: "$lookup always returns…", options: ["An array, even for a 1:1 relationship", "Null when unmatched", "A single subdocument"], answer: 0,
    explain: "And an unmatched input gets an empty array rather than being dropped — until $unwind removes it." },
  { q: "An unindexed foreignField in a $lookup…", options: ["Falls back to a hash join", "Raises an error", "Silently scans the foreign collection per input document"], answer: 2,
    explain: "Measured 47 s versus 2.1 s indexed, visible only in the nested inner plan of an executionStats explain." },
  { q: "$unwind without preserveNullAndEmptyArrays…", options: ["Errors", "Silently drops documents with empty or missing arrays", "Keeps empty arrays"], answer: 1,
    explain: "It converts a left join into an inner join without saying so." },
  { q: "The $lookup sub-pipeline form with let lets you…", options: ["Filter, sort and limit inside the join", "Avoid indexes", "Join more collections"], answer: 0,
    explain: "Measured 2,100 ms to 180 ms, and it makes the 16 MB output failure impossible by construction." },
  { q: "Inside a $lookup sub-pipeline, $$cid refers to…", options: ["A field of the foreign document", "A let variable from the outer document", "The current pipeline stage"], answer: 1,
    explain: "$field is the foreign document's field. Confusing the two matches nothing and raises no error." },
  { q: "$graphLookup must always specify…", options: ["a unique index", "maxDepth", "allowDiskUse"], answer: 1,
    explain: "Your data will contain a cycle eventually, and its 100 MB limit is not lifted by allowDiskUse." },
  { q: "For a page of 20 rows, a batched $in join in the application versus $lookup was measured at…", options: ["7 ms versus 2,100 ms", "Slower in the application", "Roughly equal"], answer: 0,
    explain: "One extra round trip beats twenty server-side joins." },
  { q: "Adding a validator with collMod…", options: ["Scans and validates existing documents", "Locks the collection", "Completes in milliseconds and inspects nothing already stored"], answer: 2,
    explain: "A collection can permanently contain documents its own validator would reject." },
  { q: "A validator is evaluated against…", options: ["Only the fields your update touches", "The resulting document", "The update operators"], answer: 1,
    explain: "Which is why a new validator can reject a one-field $set on a document written years earlier." },
  { q: "validationLevel: \"moderate\" guarantees that…", options: ["Only inserts are checked", "The set of non-conforming documents can only shrink", "Nothing is validated"], answer: 1,
    explain: "New inserts are always validated, conforming documents cannot regress, and legacy documents stay writable." },
  { q: "required: [\"email\"] in $jsonSchema means…", options: ["email must be a string", "The key must exist — null and \"\" both satisfy it", "email must be non-null"], answer: 1,
    explain: "Constrain the value with bsonType, minLength or enum; required only checks presence." },
  { q: "Use bsonType rather than type because type: \"number\"…", options: ["Accepts int, long, double and decimal interchangeably", "Is deprecated", "Rejects integers"], answer: 0,
    explain: "Which defeats the entire point on a money field." },
  { q: "additionalProperties: false is valuable because it catches…", options: ["Missing fields", "Wrong types", "Fields you did not think about, such as a typo'd field name"], answer: 2,
    explain: "It caught 4,200 writes a day using custmerId — 46,000 documents no reader ever matched." },
  { q: "A conditional rule in a validator needs $cond with…", options: ["$expr disabled", "A $match stage", "An explicit else: true"], answer: 2,
    explain: "A bare $expr clause applies to every document and is a total write outage, not a subtle bug." },
  { q: "The correct validator rollout order is…", options: ["strict + error, then relax", "off, then strict", "warn + moderate, count, backfill, then error, then strict"], answer: 2,
    explain: "The measured failure of skipping it: 28% of updates failing within 90 seconds of a collMod." },
  { q: "To count documents that would fail a proposed validator, use…", options: ["validate()", "countDocuments({ $nor: [ validator ] })", "collStats"], answer: 1,
    explain: "A validator is just a query document, so $nor inverts it — and nothing needs to be enabled to test it." },
  { q: "Backfilling 11M documents with one updateMany was measured to cause…", options: ["4m12s replication lag, stalled majority writes and a 24h→5h oplog window", "No impact", "A duplicate key error"], answer: 0,
    explain: "The batched version took 9 hours with 6.4 s peak lag and zero customer impact. A backfill has no deadline; users do." },
  { q: "Backfills should paginate on _id ranges rather than skip() because skip is…", options: ["Quadratic — each batch re-walks everything before it", "Not restartable", "Deprecated"], answer: 0,
    explain: "Re-checking the predicate in the finder is what makes the job idempotent and resumable." },
  { q: "Changing a field's type in place on a live collection risks…", options: ["Type bracketing splitting every range query into two wrong answers", "A validation error", "Index corruption"], answer: 0,
    explain: "A finance dashboard ran a half-migrated query for nine days. Migrate into a new field and cut over." },
]},
{ title: "Quiz 5 · Indexes: How They Work & Index Types",
  desc: "B-trees, ESR, prefixes, covering, multikey, partial, unique and TTL",
  questions: [
  { q: "An index is physically…", options: ["A copy of the documents", "A hash table", "A sorted B-tree of the indexed fields plus a pointer to each document"], answer: 2,
    explain: "Every rule about prefixes, sorts and covering follows from \"sorted, and you can only scan a contiguous range\"." },
  { q: "The three jobs one index can do for a query are…", options: ["Filter, join, group", "Bound the scan, supply the sort, cover the projection", "Read, write, sort"], answer: 1,
    explain: "Measured on one query: 1,910 ms with bound only, 4 ms with bound plus sort, 0.9 ms covered." },
  { q: "ESR stands for…", options: ["Exact, Scan, Reduce", "Equality, Selectivity, Range", "Equality, Sort, Range"], answer: 2,
    explain: "A range field placed before the sort field destroys the sort — measured 41,000 keys and 310 ms versus 112 keys and 2 ms." },
  { q: "A query on { city } cannot use the index { country: 1, city: 1 } because…", options: ["The index is multikey", "The matching keys are scattered across every country — no contiguous range", "city is a string"], answer: 1,
    explain: "The prefix rule: an index is usable by any prefix of its fields and nothing else." },
  { q: "limit() bounds the work done only when…", options: ["The collection is small", "The sort comes from the index", "Always"], answer: 1,
    explain: "With a blocking sort, every match is read and sorted before the limit applies." },
  { q: "A covered query requires…", options: ["A unique index", "A hint", "Every returned field in the index, including excluding _id"], answer: 2,
    explain: "Verify with totalDocsExamined: 0 and a PROJECTION_COVERED stage." },
  { q: "Index intersection in practice is…", options: ["Real but rarely chosen, and measured slower than one compound index", "The normal plan for multi-field queries", "Unsupported"], answer: 0,
    explain: "Measured: 410 ms intersected, 240 ms single-index, 9 ms with one compound index." },
  { q: "An index on a boolean field where you query the common value was measured…", options: ["Much faster than a scan", "Identical", "Slower than a collection scan"], answer: 2,
    explain: "4.1 s indexed versus 3.4 s scanning — 2.1M random fetches lose to one sequential pass." },
  { q: "An index becomes multikey when…", options: ["One document stores an array in the indexed field", "It exceeds a size threshold", "You declare it"], answer: 0,
    explain: "Each array element becomes its own key pointing at the same document — and the flag is sticky." },
  { q: "A compound index may contain at most…", options: ["One array field", "One unique field", "Two fields"], answer: 0,
    explain: "Violating it is a write-time error (\"cannot index parallel arrays\"), discovered when the first such document arrives." },
  { q: "A multikey index cannot…", options: ["Be compound", "Support a sort on the array field", "Be unique"], answer: 1,
    explain: "The keys for one document are scattered, so there is no single position for it in the ordering." },
  { q: "unique: true on an optional field rejects the second document without it because…", options: ["Of a driver bug", "unique requires the field", "A missing field is indexed as null"], answer: 2,
    explain: "Fix with partialFilterExpression on the type, which only indexes documents that actually have a value." },
  { q: "sparse: true excludes…", options: ["Only documents where the field is missing", "All duplicates", "Explicit nulls too"], answer: 0,
    explain: "Which is why partial indexes have effectively replaced sparse ones." },
  { q: "A partial index over 0.6% of a 200M-document collection was measured at…", options: ["The same size", "Twice the size", "140 MB instead of 9.2 GB"], answer: 2,
    explain: "It also removes the write cost for the 99.4% of inserts that do not match the filter." },
  { q: "A partial index is used by the planner only when…", options: ["The collection is small", "It is hinted", "The query predicate logically implies the filter expression"], answer: 2,
    explain: "The planner reasons about predicates, never about whether your data happens to match." },
  { q: "How many text indexes may one collection have?", options: ["One per field", "Unlimited", "Exactly one"], answer: 2,
    explain: "And $text does no typo tolerance and no prefix/autocomplete matching at all — zero results, not poor ones." },
  { q: "GeoJSON coordinates are ordered…", options: ["[longitude, latitude]", "[latitude, longitude]", "Either"], answer: 0,
    explain: "Reversing them produces results that are wrong but plausible — the hardest kind of bug to notice." },
  { q: "$near differs from $geoWithin in that $near…", options: ["Returns results sorted by distance, consuming the sort", "Requires a 2d index", "Is less accurate"], answer: 0,
    explain: "Use $geoWithin when you want a region and your own ordering — often much faster." },
  { q: "Each additional index costs roughly…", options: ["Half the write throughput", "6–8% of insert throughput, plus cache", "Nothing measurable"], answer: 1,
    explain: "Measured 14,200 inserts/sec at one index and 7,400 at nine." },
  { q: "Before dropping an index you should…", options: ["Rebuild it first", "hideIndex() it for a full business cycle", "Take a backup"], answer: 1,
    explain: "Hiding is instant and instantly reversible; rebuilding a 41M-document index took 22 minutes under load." },
]},
);
