// MongoDB quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Indexes",
  desc: "B-trees, ESR rule, multikey, explain, covered queries",
  questions: [
  { q: "MongoDB indexes are…", options: ["Hash-only", "B-tree (like SQL) with document-specific types", "Not supported"], answer: 1,
    explain: "_id is always indexed." },
  { q: "The ESR rule orders compound-index fields as…", options: ["Random", "Equality → Sort → Range", "Range → Sort → Equality"], answer: 1,
    explain: "Lets one index serve match + sort + range." },
  { q: "Putting Sort before Range in the index avoids…", options: ["Nothing", "An in-memory sort (memory-capped, can fail)", "Writes"], answer: 1,
    explain: "The index provides the ordering directly." },
  { q: "Indexing an array field creates a…", options: ["Text index", "Multikey index (an entry per element)", "Hash index"], answer: 1,
    explain: "Automatic for array fields." },
  { q: "A compound index can include…", options: ["Two array fields", "At most ONE array field", "No arrays"], answer: 1,
    explain: "Two arrays would explode entry combinations." },
  { q: "COLLSCAN in explain means…", options: ["Index used", "Full collection scan — add/fix an index", "Covered query"], answer: 1,
    explain: "IXSCAN is what you want." },
  { q: "A covered query is…", options: ["Slow", "Answered entirely from the index (no doc fetch)", "A scan"], answer: 1,
    explain: "PROJECTION_COVERED; needs all fields in the index." },
  { q: "A prefix of a compound index is…", options: ["Unusable", "Usable ({a} and {a,b} of index {a,b,c})", "Only the full index"], answer: 1,
    explain: "Leftmost-prefix, like SQL." },
  { q: "TTL indexes…", options: ["Speed reads", "Auto-delete documents after a time (sessions/logs)", "Shard data"], answer: 1,
    explain: "expireAfterSeconds." },
  { q: "docsExamined ≫ nReturned indicates…", options: ["Great index", "A non-selective/poor index", "Covered query"], answer: 1,
    explain: "Want examined ≈ returned." },
  { q: "Unique indexes…", options: ["Allow duplicates", "Enforce uniqueness of the field(s)", "Are automatic"], answer: 1,
    explain: "Beyond the automatic _id uniqueness." },
  { q: "Text indexes enable…", options: ["Geo queries", "$text tokenized/stemmed search", "Sharding"], answer: 1,
    explain: "Better than regex for text search." },
  { q: "Indexes cost…", options: ["Nothing", "Slower writes + RAM (working set)", "Read speed"], answer: 1,
    explain: "Read-vs-write trade; drop unused." },
  { q: "An in-memory SORT stage means…", options: ["All good", "The index didn't cover the sort — apply ESR", "COLLSCAN"], answer: 1,
    explain: "Add a sort-covering index." },
  { q: "Partial indexes…", options: ["Index everything", "Index only matching docs (smaller/faster)", "Are invalid"], answer: 1,
    explain: "e.g., active: true only." },
  { q: "Geospatial (2dsphere) indexes support…", options: ["Text", "Location queries ($near/$geoWithin)", "TTL"], answer: 1,
    explain: "For maps/location features." },
  { q: "The index working set should…", options: ["Exceed RAM", "Fit in RAM (else disk lookups slow queries)", "Be on disk"], answer: 1,
    explain: "Indexes on disk = slow even indexed queries." },
  { q: "Finding unused indexes uses…", options: ["Guessing", "$indexStats", "explain only"], answer: 1,
    explain: "Drop them to save cache + write cost." },
  { q: "Hashed indexes are for…", options: ["Range queries", "Hashed sharding (even distribution)", "Text"], answer: 1,
    explain: "Sharding lesson." },
  { q: "The index workflow is…", options: ["Index all", "Slow query → explain → add/fix ONE index → re-measure", "Guess"], answer: 1,
    explain: "Measure-first, like SQL." }
]},

{ title: "Quiz 7 · Transactions & Consistency",
  desc: "Single-doc atomicity, multi-doc transactions, write/read concern",
  questions: [
  { q: "Single-document writes are…", options: ["Never atomic", "Always atomic (incl. embedded arrays)", "Atomic only in transactions"], answer: 1,
    explain: "Why embedding avoids many transactions." },
  { q: "Multi-document ACID transactions…", options: ["Don't exist", "Exist (4.0+), require a replica set, used sparingly", "Are the default"], answer: 1,
    explain: "For genuine cross-document invariants." },
  { q: "MongoDB's guidance is…", options: ["Transactions for everything", "Single-doc atomicity first, transactions as an exception", "Never use transactions"], answer: 1,
    explain: "Needing them everywhere = SQL-style modeling." },
  { q: "Write concern w:'majority'…", options: ["Fastest", "Waits for a majority to ack (survives failover)", "Primary only"], answer: 1,
    explain: "w:1 can lose acknowledged writes on failover." },
  { q: "j: true means…", options: ["JSON", "Wait until written to the on-disk journal", "Majority"], answer: 1,
    explain: "Durability across a crash." },
  { q: "Critical (money) writes should use…", options: ["w:1", "w:'majority', j:true", "No concern"], answer: 1,
    explain: "Durability over latency." },
  { q: "Reading from a secondary can return…", options: ["Fresh data always", "Stale data (replication lag)", "Errors"], answer: 1,
    explain: "Read from primary for read-your-writes." },
  { q: "readConcern 'majority'…", options: ["Reads latest uncommitted", "Reads only majority-committed data (won't roll back)", "Is fastest"], answer: 1,
    explain: "Guards against post-failover rollback." },
  { q: "A multi-doc transaction requires…", options: ["A standalone server", "A replica set (or sharded cluster)", "Nothing"], answer: 1,
    explain: "Built on the oplog." },
  { q: "Transactions can abort on…", options: ["Never", "Write conflicts (retry needed) and the time limit", "Reads"], answer: 1,
    explain: "Use retryable-transaction patterns." },
  { q: "A two-account transfer needs…", options: ["Single-doc update", "A multi-doc transaction (or clever single-doc modeling)", "Nothing"], answer: 1,
    explain: "Both updates commit or neither." },
  { q: "Higher write concern trades…", options: ["Nothing", "Durability for latency", "Consistency for speed only"], answer: 1,
    explain: "Your explicit CAP/durability knob." },
  { q: "Default read preference is…", options: ["secondary", "primary (freshest)", "nearest"], answer: 1,
    explain: "Change it deliberately to scale reads." },
  { q: "Long-running transactions…", options: ["Are ideal", "Hit the 60s default limit and hold locks", "Are free"], answer: 1,
    explain: "Keep them short; no external I/O inside." },
  { q: "The philosophy for consistency is…", options: ["Always transactions", "Embed → duplicate carefully → transaction (in that order)", "Never embed"], answer: 1,
    explain: "Schema first, transactions last." },
  { q: "An atomic $inc vs read-modify-write:", options: ["Same", "$inc is race-safe; app read-modify-write loses updates", "App is safer"], answer: 1,
    explain: "Single-doc atomicity." },
  { q: "readConcern 'linearizable' is…", options: ["The default", "The strictest read level", "Fastest"], answer: 1,
    explain: "local → majority → linearizable." },
  { q: "Multi-doc transactions are meant to be…", options: ["The norm", "The exception (schema usually avoids them)", "Impossible"], answer: 1,
    explain: "Reserve for true cross-document needs." },
  { q: "Embedding related data gives you…", options: ["More transactions", "Atomicity without multi-doc transactions", "Slower reads"], answer: 1,
    explain: "The core design payoff." },
  { q: "w:1 is acceptable for…", options: ["Money", "High-volume non-critical writes (metrics)", "Everything"], answer: 1,
    explain: "Match durability to the workload." }
]},

{ title: "Quiz 8 · Replication & Change Streams",
  desc: "Replica sets, oplog, failover, read preference, change streams",
  questions: [
  { q: "A replica set is…", options: ["One server", "1 primary (writes) + N secondaries (copies)", "A shard"], answer: 1,
    explain: "Foundation of HA and read scaling." },
  { q: "The oplog is…", options: ["A log file", "A capped collection of idempotent write operations secondaries replay", "An index"], answer: 1,
    explain: "Drives replication + change streams + recovery." },
  { q: "Automatic failover requires…", options: ["Any number", "A MAJORITY to elect a new primary (odd members)", "Two members"], answer: 1,
    explain: "No majority = read-only (no split-brain)." },
  { q: "An oplog that's too small causes…", options: ["Nothing", "Lagging secondaries to need a full resync", "Faster writes"], answer: 1,
    explain: "Size for write volume + downtime." },
  { q: "Read preference 'primary' gives…", options: ["Stale data", "Freshest data (read-your-writes)", "Errors"], answer: 1,
    explain: "Default; secondaries may lag." },
  { q: "An arbiter…", options: ["Holds data", "Votes in elections but holds no data (break ties)", "Is a shard"], answer: 1,
    explain: "For even-numbered sets." },
  { q: "Secondary reads are useful for…", options: ["Read-your-writes", "Scaling reads/analytics (tolerating lag)", "Writes"], answer: 1,
    explain: "Trade freshness for throughput." },
  { q: "Change streams push…", options: ["Query results", "Real-time change events (no polling)", "Indexes"], answer: 1,
    explain: "Built on the oplog; need a replica set." },
  { q: "Resume tokens let change-stream consumers…", options: ["Filter", "Resume EXACTLY where they left off after a crash", "Sort"], answer: 1,
    explain: "Persist the token after handling each event." },
  { q: "A resume token is valid only while…", options: ["Forever", "Its position is still in the oplog window", "The consumer is up"], answer: 1,
    explain: "Size the oplog for consumer downtime." },
  { q: "fullDocument: 'updateLookup'…", options: ["Speeds writes", "Includes the whole doc on update events (else only the delta)", "Filters"], answer: 1,
    explain: "Updates emit changes, not full docs, by default." },
  { q: "Filtering change streams uses…", options: ["Client code only", "A server-side $match pipeline in watch()", "Indexes"], answer: 1,
    explain: "Avoid shipping irrelevant events." },
  { q: "w:'majority' writes survive failover because…", options: ["Luck", "A majority already has them before ack", "Journaling only"], answer: 1,
    explain: "Majority is the recurring theme." },
  { q: "A 2-member set with one down…", options: ["Elects fine", "Can't reach majority → read-only", "Shards"], answer: 1,
    explain: "Need odd/majority for elections." },
  { q: "Change stream use cases include…", options: ["Only logging", "Live UIs, cache invalidation, search sync, CDC/outbox", "Sharding"], answer: 1,
    explain: "Turns the DB into an event source." },
  { q: "Change stream handlers should be…", options: ["Stateful", "Idempotent (rare duplicates on resume)", "Synchronous only"], answer: 1,
    explain: "Not strictly exactly-once." },
  { q: "Standalone servers support change streams?", options: ["Yes", "No — a replica set is required", "Only with sharding"], answer: 1,
    explain: "They read the oplog." },
  { q: "Elections are triggered after…", options: ["Every write", "The primary is unreachable past electionTimeout (~10s)", "A read"], answer: 1,
    explain: "Heartbeats detect failure." },
  { q: "Read preference 'nearest'…", options: ["Always primary", "Lowest-latency member (geo)", "Random"], answer: 1,
    explain: "For geo-distributed low-latency reads." },
  { q: "The oplog being idempotent means…", options: ["Ordered only", "Safe to re-apply (recovery/resync)", "Encrypted"], answer: 1,
    explain: "Enables reliable replay." }
]},

{ title: "Quiz 9 · Sharding, Performance & Anti-Patterns",
  desc: "Shard keys, targeted queries, working set, anti-patterns",
  questions: [
  { q: "Sharding scales…", options: ["Reads only", "Writes/data horizontally across servers", "Nothing"], answer: 1,
    explain: "Last resort after other rungs." },
  { q: "A good shard key has…", options: ["Low cardinality", "High cardinality, even distribution, query alignment", "One value"], answer: 1,
    explain: "And avoids monotonicity." },
  { q: "A monotonic shard key (timestamp/_id)…", options: ["Balances well", "Creates a write HOTSPOT on one shard", "Is required"], answer: 1,
    explain: "Use hashed or a distributed/compound key." },
  { q: "A query WITHOUT the shard key is…", options: ["Targeted", "Scatter-gather (asks every shard) — slow", "Blocked"], answer: 1,
    explain: "Include the shard key for targeted routing." },
  { q: "mongos is…", options: ["A shard", "The query router (uses config-server metadata)", "A replica"], answer: 1,
    explain: "Routes to the right shard(s)." },
  { q: "Each shard is…", options: ["A single server", "Itself a replica set (HA within the shard)", "An index"], answer: 1,
    explain: "Config servers hold the chunk map." },
  { q: "Hashed sharding gives…", options: ["Range locality", "Even write distribution (but range queries scatter)", "Nothing"], answer: 1,
    explain: "Ranged gives locality but risks hotspots." },
  { q: "The MongoDB working set is…", options: ["All data", "Indexes + frequently-accessed docs (must fit RAM)", "The oplog"], answer: 1,
    explain: "The central performance constraint." },
  { q: "When the working set exceeds RAM…", options: ["Nothing changes", "Page faults to disk → latency spikes", "Faster"], answer: 1,
    explain: "Even indexed queries slow down." },
  { q: "Most MongoDB perf problems are…", options: ["Hardware", "Schema problems (ignoring access patterns)", "Network"], answer: 1,
    explain: "Remodel for access patterns." },
  { q: "An unbounded array anti-pattern is fixed by…", options: ["Bigger docs", "Reference / subset / bucket patterns", "Sharding"], answer: 1,
    explain: "Keep embedded arrays bounded." },
  { q: "The shard key is…", options: ["Easy to change", "Near-permanent — design up front", "Optional"], answer: 1,
    explain: "Wrong keys are painful to fix." },
  { q: "The scaling ladder is…", options: ["Shard first", "Indexes/schema → replicas+cache → patterns → shard", "Random"], answer: 1,
    explain: "Same as SQL — cheaper rungs first." },
  { q: "Diagnose slow queries with…", options: ["Guessing", "The profiler + explain (COLLSCAN, sorts) + Atlas advisor", "Restarting"], answer: 1,
    explain: "Measure first." },
  { q: "Over-indexing causes…", options: ["Faster writes", "Slow writes + cache pressure", "Nothing"], answer: 1,
    explain: "Index for real queries; drop unused." },
  { q: "bulkWrite improves…", options: ["Reads", "Write throughput (fewer round trips)", "Indexes"], answer: 1,
    explain: "ordered:false for parallelism." },
  { q: "'MongoDB doesn't scale' usually means…", options: ["True always", "The schema fights the model (anti-patterns)", "Bad hardware"], answer: 1,
    explain: "Fix schema + indexes for the queries." },
  { q: "Choose relational over MongoDB when…", options: ["Never", "Data is highly relational, queried many ways, needs pervasive multi-row ACID", "Always"], answer: 1,
    explain: "Pick per workload; polyglot is fine." },
  { q: "Regex text search at scale is…", options: ["Fine", "An anti-pattern (scans) — use text index/Atlas Search", "Fastest"], answer: 1,
    explain: "Tokenized search vs full scans." },
  { q: "The two root causes of anti-patterns are…", options: ["Bad drivers", "Ignoring access patterns + fighting the document model's limits", "Slow disks"], answer: 1,
    explain: "Design for queries within the model's constraints." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "An update wiped every field except one. Cause?", options: ["A bug", "Update document without operators → full replacement", "Sharding"], answer: 1,
    explain: "Use $set; replaceOne for intentional replace." },
  { q: "Concurrent balance debits lose updates. Fix?", options: ["Read-then-write", "Atomic updateOne with $inc guarded by $gte, check matchedCount", "Two queries"], answer: 1,
    explain: "Single-doc atomicity." },
  { q: "A query { 'items.product':'A','items.qty':{$gt:3} } returns false positives. Fix?", options: ["Add index", "$elemMatch (conditions on the SAME element)", "Sort"], answer: 1,
    explain: "The array-condition trap." },
  { q: "A blog post document keeps growing with comments and hit 16MB. Redesign?", options: ["Bigger limit", "Subset (latest N) + comments in a separate collection", "Shard"], answer: 1,
    explain: "Unbounded-array anti-pattern." },
  { q: "$lookup runs on every request and it's slow. Root cause?", options: ["Missing index only", "SQL-style modeling — embed / extended reference", "Bad hardware"], answer: 1,
    explain: "Model for access patterns." },
  { q: "A find+sort does an in-memory SORT. Fix?", options: ["More RAM", "Index ordered by ESR (Sort field before Range)", "allowDiskUse"], answer: 1,
    explain: "Cover the sort with the index." },
  { q: "New writes all hit one shard. Cause?", options: ["Too few shards", "Monotonic shard key — use hashed/compound", "Bad index"], answer: 1,
    explain: "The #1 sharding mistake." },
  { q: "A query scatter-gathers across all shards. Why?", options: ["Random", "It doesn't include the shard key", "Too many indexes"], answer: 1,
    explain: "Include the shard key for targeted routing." },
  { q: "Latency spikes under load though queries are indexed. Likely cause?", options: ["Slow network", "Working set exceeds RAM → page faults", "Bad schema only"], answer: 1,
    explain: "Indexes must fit in cache." },
  { q: "A user saves a profile then sees the old value. Cause?", options: ["Browser cache", "Read hit a lagging secondary — read from primary", "Deadlock"], answer: 1,
    explain: "Read-your-writes via primary." },
  { q: "A critical write was lost after a primary crash. Fix?", options: ["w:1", "w:'majority', j:true", "No concern"], answer: 1,
    explain: "Majority survives failover." },
  { q: "A transfer between two accounts must be all-or-nothing. Use?", options: ["Two updates", "A multi-document transaction (with retry on abort)", "$inc"], answer: 1,
    explain: "Genuine cross-document invariant." },
  { q: "A change-stream consumer missed events after a restart. Cause?", options: ["Bug", "Didn't persist/use a resume token", "Sharding"], answer: 1,
    explain: "Resume tokens make it crash-safe." },
  { q: "Regex search /name/i is slow on millions of docs. Fix?", options: ["Add RAM", "Text index + $text or Atlas Search", "Shard"], answer: 1,
    explain: "Unanchored/case-insensitive regex scans." },
  { q: "Collection has inconsistent document shapes causing bugs. Fix?", options: ["Ignore", "$jsonSchema validation + app models", "Shard"], answer: 1,
    explain: "'Flexible' isn't 'no schema'." },
  { q: "An aggregation is slow. First move?", options: ["allowDiskUse", "$match/$sort first + supporting indexes", "$lookup more"], answer: 1,
    explain: "Filter early to use indexes." },
  { q: "You need atomicity but keep reaching for transactions. Better approach?", options: ["More transactions", "Embed related data → single-doc atomicity", "Shard"], answer: 1,
    explain: "Schema-first consistency." },
  { q: "Storing the product price on each order — bug or feature?", options: ["Bug", "Feature — correct historical snapshot", "Neither"], answer: 1,
    explain: "Temporal modeling, not denormalization to fix." },
  { q: "Deciding MongoDB vs relational should be based on…", options: ["Popularity", "Access patterns + relationality + transactional needs", "Language"], answer: 1,
    explain: "Pick per workload; polyglot is legitimate." },
  { q: "The single most important MongoDB skill is…", options: ["Memorizing operators", "Access-pattern-driven schema design (embed vs reference)", "Sharding"], answer: 1,
    explain: "It dictates indexes, shard key, performance — everything. 🏆" }
]}
);
