// System Design quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Fundamentals I",
  desc: "Scaling basics, estimation, CAP theorem, consistent hashing",
  questions: [
  { q: "Vertical scaling means…", options: ["Adding more machines", "Adding more power (CPU/RAM) to ONE machine", "Adding a cache"], answer: 1,
    explain: "Has a hard ceiling — a single machine's max spec." },
  { q: "Horizontal scaling means…", options: ["Upgrading one machine", "Adding MORE machines", "Reducing load"], answer: 1,
    explain: "Requires the system to be designed to distribute work." },
  { q: "A load balancer's core job is…", options: ["Storing data", "Distributing incoming requests across multiple servers", "Caching responses"], answer: 1,
    explain: "Enables horizontal scaling of stateless services." },
  { q: "Back-of-envelope estimation is used to…", options: ["Write exact code", "Quickly gauge SCALE (QPS, storage) to inform architecture decisions", "Replace testing"], answer: 1,
    explain: "The number's architectural IMPLICATION matters more than precision." },
  { q: "The CAP theorem states you can have at most 2 of…", options: ["Cost, Availability, Performance", "Consistency, Availability, Partition tolerance", "Caching, API, Performance"], answer: 1,
    explain: "During a network partition, you must choose C or A." },
  { q: "In practice, partition tolerance is…", options: ["Optional", "Effectively REQUIRED — networks WILL partition", "The same as consistency"], answer: 1,
    explain: "The real choice is C vs A during a partition, not whether to have P." },
  { q: "A CP system during a partition…", options: ["Stays available with stale data", "Rejects requests rather than risk inconsistency", "Ignores the partition"], answer: 1,
    explain: "Prioritizes correctness over uptime." },
  { q: "An AP system during a partition…", options: ["Refuses all writes", "Stays available, accepting possible temporary inconsistency", "Crashes"], answer: 1,
    explain: "Prioritizes uptime; reconciles later." },
  { q: "Consistent hashing maps both keys AND nodes onto…", options: ["A sorted array", "A RING (hash space)", "A binary tree"], answer: 1,
    explain: "A key is stored on the first node clockwise from its hash position." },
  { q: "Without consistent hashing, adding/removing a node in simple modulo hashing (hash % N) causes…", options: ["No remapping", "MASSIVE remapping — nearly every key changes owner", "Faster lookups"], answer: 1,
    explain: "Changing N changes hash % N for almost every key." },
  { q: "Consistent hashing's benefit when a node is added/removed is…", options: ["Only that node's neighborhood remaps", "The whole ring remaps", "Nothing changes ever"], answer: 0,
    explain: "Only keys in the immediate vicinity of the change are affected." },
  { q: "Virtual nodes in consistent hashing solve…", options: ["Security", "UNEVEN load distribution across physical nodes", "Data loss"], answer: 1,
    explain: "Each physical node maps to many points on the ring." },
  { q: "Strong consistency guarantees…", options: ["Eventual agreement, no timing guarantee", "Every read sees the MOST RECENT write, immediately", "Faster reads always"], answer: 1,
    explain: "The strictest consistency model." },
  { q: "Eventual consistency guarantees…", options: ["Immediate consistency", "Replicas WILL converge eventually, but reads may be stale in the meantime", "No consistency ever"], answer: 1,
    explain: "A common trade-off for higher availability/lower latency." },
  { q: "Estimating storage for '100M records × 500 bytes' gives roughly…", options: ["500 GB", "50 GB", "5 TB"], answer: 1,
    explain: "100,000,000 × 500 bytes ≈ 50GB." },
  { q: "A read-heavy system with a 100:1 read:write ratio suggests prioritizing…", options: ["Write throughput", "READ optimization (caching, replicas)", "Neither matters"], answer: 1,
    explain: "The dominant traffic pattern shapes architecture priorities." },
  { q: "Latency vs throughput is a trade-off where…", options: ["They're identical", "Batching improves throughput but can increase individual latency", "Throughput never matters"], answer: 1,
    explain: "A recurring trade-off axis across many designs." },
  { q: "A single point of failure (SPOF) is…", options: ["A desirable simplification", "Any component whose failure takes down the WHOLE system", "Only relevant for databases"], answer: 1,
    explain: "Eliminating SPOFs is a core resilience goal." },
  { q: "'Reads can go to any replica' scaling is called…", options: ["Write scaling", "READ scaling via replication", "Sharding"], answer: 1,
    explain: "Distributes read load across multiple copies of the data." },
  { q: "The CAP theorem's trade-off applies…", options: ["Always, even without a partition", "SPECIFICALLY during a network partition", "Only to SQL databases"], answer: 1,
    explain: "Outside of a partition, systems can often be both available and consistent." }
]},
{ title: "Quiz 2 · Fundamentals II",
  desc: "Caching, replication, bloom filters/merkle trees/inverted index",
  questions: [
  { q: "Cache-aside pattern: on a write, you should…", options: ["Update the cache", "DELETE the cache key (force a fresh read next time)", "Ignore the cache"], answer: 1,
    explain: "Updating risks stale data from concurrent interleaved writes." },
  { q: "Read-through caching means…", options: ["The app manages cache population", "The CACHE ITSELF loads from the DB on a miss", "No caching occurs"], answer: 1,
    explain: "Cleaner app code; needs cache-side loader logic." },
  { q: "Write-back caching…", options: ["Writes synchronously to both cache and DB", "Writes to cache first, flushes to DB ASYNC in batches", "Never writes to the DB"], answer: 1,
    explain: "Fastest writes, but risks data loss if the cache dies before flush." },
  { q: "LRU eviction removes…", options: ["The most recently used item", "The LEAST recently used item", "A random item"], answer: 1,
    explain: "The default eviction policy in most caches." },
  { q: "A cache stampede/thundering herd happens when…", options: ["A cache never expires", "A hot key expires and thousands of requests simultaneously hit the DB", "Too many cache hits occur"], answer: 1,
    explain: "Fixed with per-key mutexes or jittered TTLs." },
  { q: "Cache PENETRATION refers to…", options: ["Too much data cached", "Requests for keys that DON'T EXIST always missing the cache", "A cache being too large"], answer: 1,
    explain: "Fixed with caching null results or a Bloom filter pre-check." },
  { q: "Cache AVALANCHE refers to…", options: ["One key expiring", "The WHOLE cache tier restarting cold, causing 100% miss rate", "Too many writes"], answer: 1,
    explain: "Fixed with cache warming and replicated/persistent caches." },
  { q: "Leader-follower replication: writes go to…", options: ["Any node", "The LEADER only", "Followers only"], answer: 1,
    explain: "Single writer avoids write-conflict resolution." },
  { q: "Synchronous replication vs asynchronous: synchronous…", options: ["Has lower latency", "Waits for follower confirmation — higher latency, no data loss on leader failure", "Never confirms writes"], answer: 1,
    explain: "A durability vs latency trade-off." },
  { q: "Replication lag can cause…", options: ["Faster reads", "A user not seeing their own recent write on a follower", "No issues ever"], answer: 1,
    explain: "Fixed with read-your-writes consistency routing." },
  { q: "Split brain occurs when…", options: ["A node crashes cleanly", "TWO nodes both believe they're the leader and accept writes", "Replication is too fast"], answer: 1,
    explain: "Prevented by consensus protocols and fencing tokens." },
  { q: "A Bloom filter can produce…", options: ["False negatives only", "False POSITIVES, but NEVER false negatives", "Neither false positives nor negatives"], answer: 1,
    explain: "The one-directional guarantee is its entire value." },
  { q: "A Bloom filter's 'definitely not present' answer is…", options: ["Uncertain", "CERTAIN — never wrong", "Always a false positive"], answer: 1,
    explain: "No false negatives, ever." },
  { q: "Bloom filters are commonly used to…", options: ["Store full data", "Cheaply pre-check before an expensive operation (e.g., a disk read)", "Replace a database entirely"], answer: 1,
    explain: "Skip expensive lookups for definitely-absent keys." },
  { q: "A Merkle tree lets you compare two large datasets by…", options: ["Comparing every record", "Comparing ROOT HASHES first — O(1) if they match", "Downloading both fully"], answer: 1,
    explain: "Recurse into mismatched subtrees only if roots differ." },
  { q: "Merkle trees are used in databases for…", options: ["Encryption", "ANTI-ENTROPY — detecting/repairing replica divergence", "Load balancing"], answer: 1,
    explain: "Cassandra/Dynamo-style databases use this for repair." },
  { q: "An inverted index maps…", options: ["Document → words", "WORD → documents containing it", "Nothing useful"], answer: 1,
    explain: "The reverse of the 'obvious' forward index — enables fast search." },
  { q: "A forward index (document → words) makes 'which docs contain X' queries…", options: ["Fast, O(1)", "SLOW — requires scanning every document", "Impossible"], answer: 1,
    explain: "This is exactly why the index gets 'inverted'." },
  { q: "Production inverted indexes store, beyond just doc IDs…", options: ["Nothing extra", "POSITIONS (for phrase search) and term frequency (for ranking)", "Only timestamps"], answer: 1,
    explain: "This extra metadata enables a real ranked search engine." },
  { q: "A Counting Bloom Filter differs from a standard one by…", options: ["Being smaller", "Using COUNTERS instead of bits, allowing element REMOVAL", "Never having false positives"], answer: 1,
    explain: "Standard Bloom filters can't safely support deletion." }
]},
{ title: "Quiz 3 · Fundamentals III",
  desc: "Pub/Sub vs queues, REST/serverless, microservices, heartbeat/gossip/backoff",
  questions: [
  { q: "In a message QUEUE, each message is processed by…", options: ["Every consumer", "EXACTLY ONE consumer (within a group) — competing consumption", "No consumer"], answer: 1,
    explain: "Used to distribute/parallelize work." },
  { q: "In PUB/SUB, each subscriber…", options: ["Competes for messages", "Gets its OWN copy of EVERY message — broadcast", "Never receives messages"], answer: 1,
    explain: "Used when multiple independent systems must react to the same event." },
  { q: "Kafka supports both queue-like and pub/sub-like semantics via…", options: ["Nothing special", "CONSUMER GROUPS — groups broadcast, members within a group compete", "Only pub/sub"], answer: 1,
    explain: "A key reason Kafka is the default event-streaming choice." },
  { q: "At-least-once delivery means consumers must be…", options: ["Stateless", "IDEMPOTENT — the same message might arrive more than once", "Synchronous"], answer: 1,
    explain: "True exactly-once is very hard; effectively-once = at-least-once + idempotency." },
  { q: "Ordering in Kafka is guaranteed…", options: ["Globally across the whole topic", "Within a single PARTITION only", "Never"], answer: 1,
    explain: "Route related messages to the same partition via a consistent key." },
  { q: "REST is generally best suited for…", options: ["Internal microservice calls needing max performance", "Public APIs and CRUD-heavy services with broad tooling support", "Client-driven variable data needs"], answer: 1,
    explain: "Broad compatibility and caching support." },
  { q: "gRPC is generally best suited for…", options: ["Public third-party APIs", "Internal service-to-service calls needing low latency/high throughput", "Simple CRUD apps"], answer: 1,
    explain: "Binary protocol, codegen, both ends controlled internally." },
  { q: "GraphQL is best suited for…", options: ["Simple public APIs", "Client apps with highly variable data needs (avoiding over/under-fetching)", "Internal RPC"], answer: 1,
    explain: "Client specifies exactly the fields it needs." },
  { q: "An idempotency key is used to…", options: ["Speed up requests", "Make a retried POST request safe (not double-charge/double-process)", "Encrypt data"], answer: 1,
    explain: "Critical for payment APIs and any non-naturally-idempotent endpoint." },
  { q: "Serverless (FaaS) scales to…", options: ["A fixed minimum always running", "ZERO — pay only for actual invocations", "Infinity with no limits"], answer: 1,
    explain: "A key cost benefit, at the cost of cold-start latency." },
  { q: "Serverless is generally a poor fit for…", options: ["Bursty, event-driven workloads", "SUSTAINED high-throughput services", "Webhooks"], answer: 1,
    explain: "Provisioned servers/containers are cheaper at sustained high volume." },
  { q: "Microservices' main benefit is…", options: ["Simpler operations", "TEAM-LEVEL independent deployment", "Cheaper infrastructure always"], answer: 1,
    explain: "That trade only pays off past a certain organizational size." },
  { q: "A 'distributed monolith' results from…", options: ["Good service boundaries", "BAD boundaries — services too coupled, must deploy together anyway", "Too few services"], answer: 1,
    explain: "Pays network overhead AND coupling costs simultaneously." },
  { q: "The Saga pattern handles…", options: ["Single-service transactions", "DISTRIBUTED transactions across services via compensating actions", "Caching"], answer: 1,
    explain: "No cross-service ACID transactions exist — sagas 'undo' rather than 'rollback'." },
  { q: "A circuit breaker's purpose is to…", options: ["Always retry forever", "STOP calling a known-failing dependency, failing fast", "Cache responses"], answer: 1,
    explain: "Complements retry-with-backoff for sustained outages." },
  { q: "A heartbeat timeout that's too SHORT risks…", options: ["Slow failure detection", "FALSE POSITIVES — a slow/GC-paused node looks dead", "No risk"], answer: 1,
    explain: "A genuine tuning trade-off." },
  { q: "Gossip protocols spread information…", options: ["Via a central coordinator", "By nodes randomly exchanging state with a FEW peers, exponentially", "Never — it's static"], answer: 1,
    explain: "No single point of failure; reaches the cluster in O(log n) rounds." },
  { q: "Exponential backoff without JITTER risks…", options: ["Nothing", "Synchronized RETRY STORMS — many clients retrying at the same moment", "Faster recovery"], answer: 1,
    explain: "Jitter desynchronizes retries, spreading load smoothly." },
  { q: "A retry storm can make an outage…", options: ["Recover faster", "WORSE — overwhelming a server that's trying to recover", "Have no effect"], answer: 1,
    explain: "Exactly what backoff + jitter is designed to prevent." },
  { q: "The distinction between backoff and a circuit breaker is…", options: ["They're identical", "Backoff handles TRANSIENT failures; circuit breakers handle SUSTAINED outages", "Circuit breakers are for caching"], answer: 1,
    explain: "Complementary resilience mechanisms." }
]},
{ title: "Quiz 4 · Deep Dives I",
  desc: "Concurrency control (ACID/isolation), authentication (JWT/OAuth2/OIDC)",
  questions: [
  { q: "Atomicity guarantees…", options: ["Partial transaction application is fine", "A transaction's operations ALL succeed or ALL roll back", "Fast execution"], answer: 1,
    explain: "No partial application ever." },
  { q: "A dirty read means…", options: ["Reading committed data", "Reading data another transaction WROTE but hasn't COMMITTED yet", "A slow query"], answer: 1,
    explain: "If that transaction rolls back, you read data that never 'really' existed." },
  { q: "A non-repeatable read means…", options: ["The same query returns a different ROW COUNT", "Reading the SAME row twice yields DIFFERENT values due to a committed update in between", "A query fails"], answer: 1,
    explain: "Distinct from a phantom read, which is about row COUNT." },
  { q: "A phantom read means…", options: ["A single row's value changes", "Re-running the SAME query yields a DIFFERENT SET of rows", "A deadlock"], answer: 1,
    explain: "Caused by concurrent inserts/deletes matching the query." },
  { q: "Read Committed isolation prevents…", options: ["All anomalies", "DIRTY reads only", "Nothing"], answer: 1,
    explain: "Non-repeatable and phantom reads are still possible." },
  { q: "Serializable isolation prevents…", options: ["Nothing", "ALL THREE classic anomalies (dirty, non-repeatable, phantom)", "Only dirty reads"], answer: 1,
    explain: "The strongest isolation level, at a locking/blocking cost." },
  { q: "Higher isolation levels generally mean…", options: ["Better performance always", "MORE locking/blocking, fewer anomalies — a real trade-off", "No difference"], answer: 1,
    explain: "Not 'always pick the strongest' — match to actual correctness needs." },
  { q: "Pessimistic concurrency control…", options: ["Never locks", "Acquires a LOCK before touching data — good under HIGH contention", "Only works for reads"], answer: 1,
    explain: "Avoids wasted work from conflicts when contention is common." },
  { q: "Optimistic concurrency control…", options: ["Locks immediately", "Checks a VERSION at write time, aborts/retries on conflict — good under LOW contention", "Is always slower"], answer: 1,
    explain: "No locking overhead for the common no-conflict case." },
  { q: "Two-Phase Locking's growing phase…", options: ["Releases locks", "Acquires ALL needed locks, releases NONE yet", "Does nothing"], answer: 1,
    explain: "Followed by the shrinking phase (release only, no new acquires)." },
  { q: "2PL's strict discipline can produce…", options: ["Faster transactions always", "DEADLOCKS — two transactions each holding a lock the other needs", "No side effects"], answer: 1,
    explain: "Requires deadlock detection and aborting one transaction." },
  { q: "Session-based auth requires…", options: ["No storage", "SHARED session storage across server instances (or sticky sessions)", "Nothing special to scale"], answer: 1,
    explain: "A scaling cost token-based auth avoids." },
  { q: "JWT-based auth is…", options: ["Stateful", "STATELESS — any server validates independently, no shared storage needed", "Slower to validate"], answer: 1,
    explain: "Scales trivially across server instances." },
  { q: "JWT revocation (e.g., instant logout) is…", options: ["Trivial", "HARD — a signed token remains valid until expiry regardless", "Automatic"], answer: 1,
    explain: "Mitigated with short expiries + revocable refresh tokens." },
  { q: "OAuth 2.0 is designed for…", options: ["Proving identity", "DELEGATED AUTHORIZATION — scoped access on a user's behalf", "Encrypting passwords"], answer: 1,
    explain: "Not originally an authentication/identity protocol." },
  { q: "OIDC adds to OAuth2…", options: ["Nothing new", "A standardized ID TOKEN for AUTHENTICATION (proving identity)", "Faster tokens"], answer: 1,
    explain: "'Sign in with Google' uses OIDC specifically for this reason." },
  { q: "Using a raw OAuth2 access token to prove identity is…", options: ["The correct standard approach", "A historical MISUSE — access tokens aren't standardized to carry identity", "Required"], answer: 1,
    explain: "OIDC's ID token is the correct tool for authentication." },
  { q: "In a microservices architecture, auth validation is often centralized at…", options: ["Every individual service", "The API GATEWAY/edge — validated once", "The database"], answer: 1,
    explain: "Avoids every service needing independent IdP connectivity." },
  { q: "A refresh token, unlike a short-lived access token, is typically…", options: ["Never revocable", "Longer-lived and REVOCABLE server-side", "The same as an access token"], answer: 1,
    explain: "Enables token refresh without forcing re-login, while remaining controllable." },
  { q: "The overarching theme of session vs token auth is…", options: ["Security only", "A SCALABILITY trade-off — server-side state vs client-held state", "Cost only"], answer: 1,
    explain: "Simple + easy revocation vs stateless + hard revocation." }
]},
{ title: "Quiz 5 · Deep Dives II",
  desc: "Security (TLS/encryption), realtime apps, concurrent programming/deadlocks, observability",
  questions: [
  { q: "TLS uses asymmetric crypto to…", options: ["Encrypt all bulk traffic", "BOOTSTRAP a shared symmetric key — too slow for bulk data itself", "Nothing — it's unused"], answer: 1,
    explain: "Symmetric crypto (fast) handles the actual data after the handshake." },
  { q: "Encryption at rest protects against…", options: ["A compromised application making legitimate queries", "Storage-level compromise (stolen disks, DB file leaks)", "Every possible attack"], answer: 1,
    explain: "Does NOT protect against app-level compromise — a classic interview trap." },
  { q: "Field-level (application) encryption protects against…", options: ["Nothing extra", "Even DBAs/operators with full DB access reading specific sensitive fields", "Network attacks only"], answer: 1,
    explain: "A finer-grained layer than disk/DB-level encryption." },
  { q: "Secrets should be…", options: ["Hardcoded in config files", "Fetched at RUNTIME from a secrets manager, short-lived and rotated", "Committed to git for backup"], answer: 1,
    explain: "Never bake credentials into artifacts." },
  { q: "Defense in depth means…", options: ["One strong layer is sufficient", "MULTIPLE layered security controls — no single layer assumed sufficient", "Avoiding all security overhead"], answer: 1,
    explain: "A breach of one layer shouldn't mean total compromise." },
  { q: "A WebSocket connection is…", options: ["Stateless like HTTP", "STATEFUL and STICKY — bound to one server instance for its lifetime", "Always short-lived"], answer: 1,
    explain: "This breaks the usual 'add more servers' scaling story." },
  { q: "Scaling WebSocket servers requires…", options: ["Nothing special", "A shared MESSAGE BROKER (Redis Pub/Sub/Kafka) connecting server instances", "A single server only"], answer: 1,
    explain: "Lets one server reach a client connected to a different instance." },
  { q: "A connection registry tracks…", options: ["Message content", "WHICH server instance holds a given client's connection", "Nothing useful"], answer: 1,
    explain: "Lets other services route messages to the right server." },
  { q: "Server-Sent Events (SSE) support…", options: ["Bidirectional communication", "SERVER → CLIENT only, over plain HTTP", "No live updates"], answer: 1,
    explain: "Simpler than WebSockets when client→server isn't needed." },
  { q: "A race condition in concurrent programming produces…", options: ["No progress at all", "WRONG results from unsynchronized concurrent access", "Faster execution"], answer: 1,
    explain: "Distinct from a deadlock, which produces no progress." },
  { q: "A deadlock's four necessary conditions include…", options: ["Only mutual exclusion", "Mutual exclusion, hold-and-wait, no preemption, circular wait — ALL four", "Just circular wait"], answer: 1,
    explain: "Breaking ANY ONE condition prevents deadlock." },
  { q: "The most practical deadlock prevention strategy is…", options: ["Using more threads", "Always acquiring locks in a CONSISTENT GLOBAL ORDER", "Ignoring the problem"], answer: 1,
    explain: "Breaks the circular-wait condition by convention." },
  { q: "A semaphore differs from a mutex by…", options: ["Being identical", "Allowing up to N concurrent threads, not just 1", "Never blocking"], answer: 1,
    explain: "Used to cap concurrency (e.g., limit concurrent DB connections)." },
  { q: "Compare-And-Swap (CAS) enables…", options: ["Blocking locks only", "LOCK-FREE atomic 'update only if unchanged' operations", "Slower updates"], answer: 1,
    explain: "The hardware primitive behind lock-free structures and optimistic concurrency." },
  { q: "Metrics answer…", options: ["Why did THIS request fail", "Is the system healthy RIGHT NOW, in aggregate", "Which service was slow for one request"], answer: 1,
    explain: "Aggregated numbers over time." },
  { q: "Logs answer…", options: ["Aggregate health", "What exactly happened for ONE specific event/request", "Cross-service latency breakdown"], answer: 1,
    explain: "Discrete, detailed events." },
  { q: "Distributed traces answer…", options: ["Aggregate error rate", "Where did the TIME GO across multiple services for ONE request", "Historical trends"], answer: 1,
    explain: "The full journey of one request across services." },
  { q: "SLO stands for…", options: ["Service Level Outage", "Service Level OBJECTIVE — the target", "Server Load Optimization"], answer: 1,
    explain: "SLI = measurement, SLO = target, SLA = contractual promise." },
  { q: "An error budget is…", options: ["1 + SLO", "1 − SLO — a spendable resource for risky deploys/maintenance", "Always zero"], answer: 1,
    explain: "Reframes reliability as quantified and spendable, not just 'be careful'." },
  { q: "Alerts should fire on…", options: ["Specific infrastructure causes (e.g., high CPU)", "USER-FACING SYMPTOMS (error rate, latency) — agnostic to the cause", "Nothing automated"], answer: 1,
    explain: "Root-cause investigation happens AFTER the alert, using metrics/logs/traces." }
]}
);
