// system-design quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Case Studies I",
  desc: "TinyURL, Rate Limiter, Unique ID Generator, Key-Value Store",
  questions: [
  { q: "TinyURL's read:write ratio is typically…", options: ["Read-HEAVY (e.g., 100:1) — redirects vastly outnumber shortenings", "1:1", "Write-heavy"], answer: 0,
    explain: "Shapes the design toward aggressive READ caching." },
  { q: "Base62-encoding an auto-incrementing ID for short codes gives…", options: ["NO collisions by construction, unlike hashing", "Frequent collisions", "Slower generation than hashing"], answer: 0,
    explain: "The standard 'correct' TinyURL answer." },
  { q: "TinyURL's read path is a textbook example of…", options: ["Write-through caching", "CACHE-ASIDE (check cache, miss → DB → populate cache)", "No caching needed"], answer: 1,
    explain: "High cache hit ratio determines real-world scalability here." },
  { q: "Token Bucket rate limiting allows…", options: ["No bursts ever", "Bounded BURSTS up to the bucket capacity, sustained rate capped by refill rate", "Unlimited requests"], answer: 1,
    explain: "The industry-standard default algorithm." },
  { q: "Fixed Window Counter's main flaw is…", options: ["BOUNDARY BURST — double the limit possible across a window edge", "It's too strict", "Too much memory use"], answer: 0,
    explain: "100 requests at 12:00:59 + 100 at 12:01:00 = 200 in ~1 second." },
  { q: "A distributed rate limiter needs shared state because…", options: ["Local counters are always accurate", "Each stateless server having its OWN counter lets clients bypass the limit via other servers", "State isn't needed"], answer: 1,
    explain: "Redis (with atomic operations) is the standard shared-state choice." },
  { q: "Check-then-decrement in a rate limiter (two separate calls) is…", options: ["Faster than atomic operations", "Always safe", "A RACE CONDITION — concurrent requests can both pass the check"], answer: 2,
    explain: "Fixed with an atomic Lua script or built-in atomic primitives." },
  { q: "A single DB auto-increment column for ID generation is problematic because…", options: ["IDs are too short", "It's a SINGLE POINT OF FAILURE / throughput bottleneck", "It's too fast"], answer: 1,
    explain: "Every ID request serializes through one database." },
  { q: "Snowflake IDs are structured as…", options: ["TIMESTAMP + MACHINE ID + SEQUENCE — ordered, no coordination needed", "A UUID v4", "Pure random bits"], answer: 0,
    explain: "Uniqueness through structure, not a central coordinator." },
  { q: "Snowflake's machine ID segment allows…", options: ["Only one machine ever", "Slower generation", "Multiple machines to generate IDs SIMULTANEOUSLY with no collision risk"], answer: 2,
    explain: "Up to 1,024 machines with a 10-bit segment." },
  { q: "UUIDs (v4, random) compared to Snowflake IDs are…", options: ["Smaller and ordered", "128 bits, NOT time-ordered — worse DB index locality", "Identical in every way"], answer: 1,
    explain: "Random inserts scatter across a B-tree index, hurting write performance." },
  { q: "Clock skew (a machine's clock moving backward) in Snowflake-style IDs risks…", options: ["Breaking the roughly-ordered property or causing collisions", "No issue", "Faster ID generation"], answer: 0,
    explain: "Mitigated by detecting regression and pausing generation." },
  { q: "In Dynamo-style key-value stores, N/W/R stands for…", options: ["Network/Web/Redis", "Replication factor / write quorum / read quorum", "Nodes/Writes/Reads counts unrelated to quorums"], answer: 1,
    explain: "The tunable consistency knobs." },
  { q: "W + R > N guarantees…", options: ["Nothing meaningful", "STRONG consistency — every read overlaps the most recent write", "Faster writes only"], answer: 1,
    explain: "At least one node in the read set saw the latest write." },
  { q: "W + R ≤ N gives…", options: ["Strong consistency", "No availability", "EVENTUAL consistency — higher availability, lower latency, possibly stale reads"], answer: 2,
    explain: "A deliberate trade-off, tunable per operation." },
  { q: "Vector clocks in Dynamo-style stores are used to…", options: ["Speed up reads", "Replace replication", "Detect TRUE CONFLICTS between concurrent writes (not resolved by simple timestamps)"], answer: 2,
    explain: "Last-write-wins can silently lose data; vector clocks surface genuine conflicts." },
  { q: "Hinted handoff handles…", options: ["A TEMPORARILY down replica — another node stores a 'hint' to deliver later", "Nothing useful", "Permanent node failure only"], answer: 0,
    explain: "Maintains availability without permanently losing a write." },
  { q: "Dynamo-style stores exemplify the CAP theorem's…", options: ["Neither C nor A", "CP choice", "AP choice — every reachable node accepts writes during a partition"], answer: 2,
    explain: "Reconciled later via vector clocks + anti-entropy." },
  { q: "A key-value store's consistent hashing + N/W/R design demonstrates…", options: ["A purely theoretical exercise", "How Fundamentals lessons COMPOSE into a real system", "Unrelated, standalone concepts"], answer: 1,
    explain: "The 'synthesis' case study of the whole Fundamentals section." },
  { q: "TinyURL's custom alias uniqueness check should use…", options: ["A UNIQUE CONSTRAINT (atomic reject on violation), not check-then-insert", "No validation", "Check-then-insert"], answer: 0,
    explain: "Check-then-insert has the same race condition as check-then-decrement." },
]},
{ title: "Quiz 7 · Case Studies II",
  desc: "Real-Time Chat, Notification System, Geo-Spatial/Uber",
  questions: [
  { q: "Scaling WebSocket-based chat across servers requires…", options: ["Nothing extra", "A shared message broker (Redis Pub/Sub/Kafka) + a connection registry", "A single server"], answer: 1,
    explain: "The Realtime Apps Deep Dive's pattern, applied to chat specifically." },
  { q: "In chat systems, you should…", options: ["Skip persistence for speed", "PERSIST the message FIRST, deliver second", "Deliver first, persist later"], answer: 1,
    explain: "Reversing this order risks losing messages on a crash." },
  { q: "Per-conversation sequence numbers in chat are used for…", options: ["Encryption", "Detecting gaps/reordering messages that arrive out of order", "Rate limiting"], answer: 1,
    explain: "Common with retries/multiple server hops." },
  { q: "Fan-out on WRITE for group chat means…", options: ["Storing the message once, fetched on read", "Pushing/queueing the message for ALL recipients AT SEND TIME", "No delivery at all"], answer: 1,
    explain: "Fast reads, but expensive writes for huge groups." },
  { q: "Fan-out on READ is preferred for…", options: ["Small normal-sized groups", "VERY LARGE broadcast channels (e.g., 100,000+ members)", "1:1 chats"], answer: 1,
    explain: "Fan-out-on-write becomes prohibitively expensive at that scale." },
  { q: "A notification system decouples 'something happened' from 'how it's delivered' using…", options: ["A message QUEUE between event producers and channel workers", "Direct synchronous calls", "No intermediary"], answer: 0,
    explain: "Absorbs bursts (e.g., a viral post triggering millions of notifications)." },
  { q: "Separate channel WORKERS (push/email/SMS) in a notification system provide…", options: ["No benefit", "Independent scaling/failure isolation — one provider's outage doesn't affect others", "Slower delivery"], answer: 1,
    explain: "Only that channel's queue backs up if its provider is down." },
  { q: "Idempotency keys in notification delivery prevent…", options: ["DUPLICATE notifications from retries", "Faster sending", "Encryption issues"], answer: 0,
    explain: "A retry must not double-notify the user." },
  { q: "Transactional notifications (OTP, password reset) should…", options: ["Respect quiet hours strictly", "Be batched/digested", "Typically BYPASS quiet hours — security/critical info shouldn't wait"], answer: 2,
    explain: "Unlike marketing notifications, which do respect quiet hours." },
  { q: "Geohashing encodes a 2D (lat, lon) pair into…", options: ["A SINGLE 1D string, with nearby locations sharing a common PREFIX", "Two separate indexes", "A random hash"], answer: 0,
    explain: "Turns 'find nearby points' into 'find strings sharing a prefix'." },
  { q: "A normal B-tree index on separate lat/lon columns is inefficient for proximity queries because…", options: ["It's too fast", "It's automatically spatial", "It requires intersecting TWO large result sets"], answer: 2,
    explain: "Proximity in 2D doesn't map onto a simple sorted 1D range." },
  { q: "Geohashing's edge-case failure mode is…", options: ["No failure modes exist", "Adjacent points straddling a grid boundary having DIFFERENT prefixes", "Being too precise"], answer: 1,
    explain: "Fixed by querying neighboring cells too, not just the exact prefix." },
  { q: "Quadtrees differ from geohashing by…", options: ["Using a fixed grid always", "Being simpler to implement", "Subdividing MORE finely where DENSITY is higher — adapting to real-world skew"], answer: 2,
    explain: "Geohashing uses a fixed grid; quadtrees adapt." },
  { q: "Driver location updates (Uber-style) are best stored in…", options: ["A data warehouse", "An IN-MEMORY store (Redis) — ephemeral, only the latest position matters", "A durable relational DB for every ping"], answer: 1,
    explain: "Historical GPS trails, if needed, go through a separate async stream." },
  { q: "Rider-driver matching is naturally implemented as…", options: ["A QUEUE-based dispatch with accept/decline/timeout/retry logic", "A synchronous 'pick one instantly' operation", "A single atomic transaction"], answer: 0,
    explain: "Drivers can decline or already be taken by a concurrent request." },
  { q: "Preventing two riders from matching the SAME driver requires…", options: ["A slower matching algorithm", "An ATOMIC 'claim' operation on driver availability", "Nothing special"], answer: 1,
    explain: "Same class of race condition as inventory oversell." },
  { q: "Sharding driver location data by REGION works well because…", options: ["It's the only option", "A driver's geohash naturally partitions by geography", "Regions are unrelated to geohashes"], answer: 1,
    explain: "Maps cleanly onto sharding." },
  { q: "The chat and notification case studies share which underlying trade-off?", options: ["Encryption approach", "Caching strategy", "Fan-out-on-write vs fan-out-on-read for delivering to many recipients"], answer: 2,
    explain: "The same push-vs-pull trade-off in different products." },
  { q: "'Delivered' vs 'Read' receipts in chat are…", options: ["Not needed", "DISTINCT state transitions, each needing their own reliable delivery back to the sender", "The same signal"], answer: 1,
    explain: "Delivered = reached device; Read = user's explicit action." },
  { q: "A recipient reconnecting after being offline should…", options: ["SYNC — fetch everything since their last-seen message ID/timestamp", "Wait for a manual refresh", "Lose missed messages"], answer: 0,
    explain: "The 'catch up on reconnect' pattern from the Realtime Apps lesson." },
]},
{ title: "Quiz 8 · Case Studies III",
  desc: "Amazon/E-Commerce, Recommendation System, Search Engine",
  questions: [
  { q: "Preventing overselling requires…", options: ["An ATOMIC conditional decrement (check AND write as one operation)", "Check stock, then decrement in two steps", "No stock tracking"], answer: 0,
    explain: "Same race-condition class as the rate limiter's check-then-decrement." },
  { q: "At extreme flash-sale contention, the recommended pattern is…", options: ["Hit the DB directly for every request", "Queue all requests indefinitely", "Reserve stock in Redis (atomic DECR) BEFORE touching the durable DB"], answer: 2,
    explain: "Absorbs the burst in memory, protecting the database." },
  { q: "Product catalog data (descriptions, images) typically needs…", options: ["Strong consistency", "No caching at all", "EVENTUAL consistency — heavily cached, rarely changes"], answer: 2,
    explain: "Very different consistency needs than inventory counts." },
  { q: "E-commerce checkout across Inventory/Payment/Order services is handled with…", options: ["A single ACID transaction", "The SAGA pattern — compensating actions if a step fails", "No coordination needed"], answer: 1,
    explain: "No cross-service ACID transactions exist." },
  { q: "'Reserve, don't immediately decrement' inventory matters because…", options: ["It's slower", "It prevents all bugs", "A RESERVATION can be safely UNDONE (compensating action) if a later saga step fails"], answer: 2,
    explain: "Enables clean rollback if payment fails after reservation." },
  { q: "Recommendation systems use a TWO-STAGE architecture because…", options: ["It's simpler to build", "Expensive model computation can't happen on the FAST request path", "Online computation is always faster"], answer: 1,
    explain: "Offline batch does heavy lifting; online just reads precomputed results." },
  { q: "Candidate generation vs ranking in recommendations is…", options: ["Only ranking matters", "The same step", "Broad-and-cheap (narrow to plausible candidates) THEN narrow-and-precise (score them)"], answer: 2,
    explain: "A funnel pattern that reappears in the Search Engine case study too." },
  { q: "The cold-start problem refers to…", options: ["A slow server", "No data yet for a NEW user or NEW item", "A caching issue"], answer: 1,
    explain: "Fallback: popular items for new users, content-based similarity for new items." },
  { q: "Recommendation freshness is often achieved via…", options: ["Only daily batch retraining", "Real-time full retraining", "A HYBRID — heavy batch retraining + a lightweight STREAMING signal layer"], answer: 2,
    explain: "Balances responsiveness with computational cost." },
  { q: "Recommendation model quality is ultimately evaluated via…", options: ["Only offline metrics", "Code review", "A/B TESTING against a real business metric (CTR, conversion)"], answer: 2,
    explain: "Offline metrics inform, but A/B testing is the ground truth." },
  { q: "A search engine's core data structure is…", options: ["A forward index", "A hash set of URLs", "The INVERTED INDEX — word → documents"], answer: 2,
    explain: "Directly reuses the Bloom/Merkle/Inverted-Index Fundamentals lesson." },
  { q: "At search-engine scale, the inverted index is…", options: ["Not needed", "SHARDED across many machines", "Held on one machine"], answer: 1,
    explain: "No single machine holds the whole index." },
  { q: "TF-IDF ranking weighs a term by…", options: ["Only how often it appears in one document", "Alphabetical order", "Frequency in THIS doc × RARITY across ALL documents"], answer: 2,
    explain: "Common words contribute little signal (low IDF)." },
  { q: "PageRank-style ranking measures…", options: ["A document's IMPORTANCE based on links from other important documents", "Keyword density only", "Page load speed"], answer: 0,
    explain: "A recursive 'importance flows through links' definition." },
  { q: "Search query processing follows a…", options: ["Random sampling", "RETRIEVAL (broad, fast) then RANKING (narrow, precise) funnel", "Single-stage exact match"], answer: 1,
    explain: "Never runs expensive ranking against the entire corpus." },
  { q: "Document-partitioned index sharding means…", options: ["Each shard holds a SUBSET of documents with its own full index", "Each shard holds specific TERMS across all docs", "No sharding occurs"], answer: 0,
    explain: "A query scatter-gathers across all shards; more predictable load balancing." },
  { q: "Term-partitioned sharding risks…", options: ["An UNBALANCED shard for very common terms (hot spots)", "No risk at all", "Perfectly even load always"], answer: 0,
    explain: "Why document-partitioning is more common in practice (e.g., Elasticsearch)." },
  { q: "Incremental crawling uses ETags/Last-Modified to…", options: ["Re-crawl every page constantly", "Ignore page changes", "SKIP unchanged pages, saving crawl resources"], answer: 2,
    explain: "Balances freshness against crawl cost." },
  { q: "Phrase search ('New York' as an exact phrase) requires the inverted index to store…", options: ["Nothing extra", "Term POSITIONS within each document", "Only doc IDs"], answer: 1,
    explain: "Enables checking adjacency, not just co-occurrence." },
  { q: "The recurring 'funnel' pattern (broad-cheap → narrow-precise) appears in…", options: ["Neither case study", "Only the Search Engine case study", "BOTH the Recommendation System AND Search Engine case studies"], answer: 2,
    explain: "The general answer to applying expensive scoring at massive scale." },
]},
{ title: "Quiz 9 · Case Studies IV & Senior/Staff I",
  desc: "Gmail, Instagram Feed, Trade-off Driven Design, Distributed Consensus",
  questions: [
  { q: "Email delivery (SMTP) uses a STORE-AND-FORWARD model where…", options: ["Only the final server stores anything", "Each HOP durably stores the message before forwarding", "Messages are never persisted mid-route"], answer: 1,
    explain: "Tolerates a recipient server being briefly down without losing the message." },
  { q: "Gmail separates email METADATA from CONTENT/attachments because…", options: ["Metadata is small/hot/structured; attachments are large/cold/write-once — different storage fits", "They have identical access patterns", "It's required by SMTP"], answer: 0,
    explain: "Attachments belong in object storage (S3), never inline in the metadata DB." },
  { q: "Full-text search over a mailbox is sharded by…", options: ["Random assignment", "The entire global corpus", "USER (or user-range) — a query only touches that user's shard"], answer: 2,
    explain: "Unlike web search, which must search across ALL documents for any query." },
  { q: "Spam filtering runs as…", options: ["An early PIPELINE STAGE before storage/indexing, using an offline-trained model applied inline", "Nothing automated", "A post-storage batch job only"], answer: 0,
    explain: "Similar in spirit to the Recommendation case study's offline/online split." },
  { q: "Instagram's celebrity problem refers to…", options: ["A caching bug", "Slow authentication", "Fan-out-on-write to 100M+ followers being prohibitively slow/expensive for ONE post"], answer: 2,
    explain: "The textbook 'hot key' problem at social-graph scale." },
  { q: "The hybrid feed solution uses fan-out-on-write for…", options: ["No one", "NORMAL users (the majority, low follower counts)", "Celebrity accounts only"], answer: 1,
    explain: "Fan-out-on-read is reserved for accounts above a follower threshold." },
  { q: "For celebrity accounts, feed reads instead…", options: ["MERGE the precomputed feed with a LIVE query for recent celebrity posts at read time", "Use only precomputed data", "Fail entirely"], answer: 0,
    explain: "Cheap because there are relatively few celebrity accounts to check." },
  { q: "Modern feed ranking uses…", options: ["Random ordering", "Pure reverse-chronological order only", "Predicted ENGAGEMENT scoring via a retrieval-then-ranking funnel"], answer: 2,
    explain: "Reuses the Recommendation System's funnel pattern." },
  { q: "'It depends' is a complete senior-level answer when…", options: ["Only in Fundamentals-level interviews", "Always — no further explanation needed", "NEVER — you must name the deciding variable and state which way it points for THIS system"], answer: 2,
    explain: "The discipline of finishing the sentence is the actual skill." },
  { q: "A strong trade-off answer derives the technical choice from…", options: ["Whatever is newest/trendiest", "A STATED PRIORITY specific to the system's requirements", "A memorized default"], answer: 1,
    explain: "Priority first, technology second." },
  { q: "When an interviewer asks 'what if traffic increased 100x,' they're testing…", options: ["Whether your original answer was wrong", "Memorization of a fixed answer", "Whether you can RE-DERIVE the trade-off under a new constraint"], answer: 2,
    explain: "Showing reasoning ADAPT is the point of the follow-up." },
  { q: "The FLP impossibility result states…", options: ["In an ASYNCHRONOUS network with even one faulty node, consensus can't be GUARANTEED in bounded time", "Consensus is always easy", "Only synchronous networks exist"], answer: 0,
    explain: "Real systems sidestep this with practical partial-synchrony assumptions." },
  { q: "A quorum (majority) with N=5 requires…", options: ["Any 2 nodes", "3 (more than half) nodes to agree", "All 5 nodes"], answer: 1,
    explain: "Majority guarantees overlap with any other majority." },
  { q: "Why do two majority quorums from the same N nodes always overlap?", options: ["They never overlap", "Only if N is even", "By definition — two majority-sized sets from the same pool MUST share at least one member"], answer: 2,
    explain: "This overlap is what prevents split-brain." },
  { q: "In Raft, a write is COMMITTED once…", options: ["A MAJORITY of nodes have replicated it", "Every single node has it", "The leader alone has it"], answer: 0,
    explain: "Ensures durability even if the leader immediately crashes." },
  { q: "Raft's randomized election timeouts prevent…", options: ["Leader failures", "Every node becoming a candidate SIMULTANEOUSLY and splitting the vote repeatedly", "Faster elections"], answer: 1,
    explain: "Desynchronizes candidacy attempts." },
  { q: "A 5-node Raft cluster split into groups of 2 and 3 during a partition…", options: ["Both sides can elect a leader", "Neither side can function", "Only the 3-node side (holding a majority) can elect a leader and make progress"], answer: 2,
    explain: "Correctly prevents split-brain by requiring majority." },
  { q: "Raft's quorum-based commit is conceptually the same idea as…", options: ["A Bloom filter", "Nothing else in this track", "Dynamo's W+R > N overlap guarantee"], answer: 2,
    explain: "Both rely on overlapping-set mathematics." },
  { q: "etcd (used by Kubernetes) relies on…", options: ["RAFT for distributed configuration/coordination", "Gossip only", "No consensus protocol"], answer: 0,
    explain: "A concrete real-world use of the consensus lesson." },
  { q: "The meta-skill across all case studies in this track is…", options: ["Using microservices everywhere", "RECOMBINING a small toolbox of Fundamentals based on each system's specific requirements", "Memorizing 12 fixed architectures"], answer: 1,
    explain: "The actual transferable, interview-tested skill." },
]},
{ title: "Quiz 10 · Mixed Mock Exam (Senior/Staff II + Comprehensive Review)",
  desc: "Data platforms, multi-region/DR, cost/capacity, migrations, interview framework — plus cross-track review",
  questions: [
  { q: "Change Data Capture (CDC) works by…", options: ["Polling the database every second", "TAILING the database's own internal change log (WAL/binlog)", "The app explicitly publishing events on every write"], answer: 1,
    explain: "Requires zero application code changes; avoids the dual-write problem." },
  { q: "The 'dual-write problem' CDC avoids is…", options: ["A DB write succeeding but an explicit event-publish failing (or vice versa), causing silent drift", "Too much storage use", "Slow writes"], answer: 0,
    explain: "CDC derives events from the DB's own committed log — can't diverge." },
  { q: "Event Sourcing stores the SOURCE OF TRUTH as…", options: ["A single snapshot", "Only current state", "The SEQUENCE OF EVENTS — current state is DERIVED by replaying them"], answer: 2,
    explain: "Gives a complete audit trail and point-in-time reconstruction for free." },
  { q: "Event Sourcing's replay cost is mitigated with…", options: ["Deleting old events", "Never replaying", "Periodic SNAPSHOTS — replay only events after the snapshot"], answer: 2,
    explain: "Avoids replaying a very long history every time." },
  { q: "Streaming processing is best suited for…", options: ["Daily reports and ML retraining", "Low-latency needs like fraud detection and live dashboards", "Large batch aggregations only"], answer: 1,
    explain: "Batch suits high-throughput periodic work instead." },
  { q: "RPO (Recovery Point Objective) measures…", options: ["How much DATA you can afford to LOSE, in time", "How long the system can be down", "Server cost"], answer: 0,
    explain: "RTO measures downtime duration instead." },
  { q: "Multi-region Active-Active provides the best RTO/RPO but…", options: ["Is the cheapest option", "Requires no trade-offs", "Is the MOST EXPENSIVE and complex — permanent cross-region consistency challenges"], answer: 2,
    explain: "Not automatically 'the best' — match strategy to actual RTO/RPO needs." },
  { q: "Pilot Light DR strategy keeps…", options: ["MINIMAL core infrastructure running, scaled up on disaster", "Nothing at all in the DR region", "Full production traffic running in the DR region"], answer: 0,
    explain: "Low-medium cost, tens-of-minutes RTO." },
  { q: "An untested disaster recovery plan is…", options: ["A reliable safety net", "A LIABILITY — DR must be validated via drills/chaos engineering", "Unnecessary to test"], answer: 1,
    explain: "You don't know it works until you've actually exercised it." },
  { q: "Capacity planning's safety margin (2-3x peak load) balances…", options: ["Under-provisioning (outages) vs over-provisioning (wasted cost)", "Nothing meaningful", "Only security concerns"], answer: 0,
    explain: "A real, quantifiable engineering trade-off." },
  { q: "Total Cost of Ownership (TCO) includes…", options: ["Only engineering salaries", "Only the infrastructure bill", "Infrastructure cost + engineering time to operate + cost of operational outages"], answer: 2,
    explain: "A self-hosted 'cheaper' option can have higher TCO once operational cost is counted." },
  { q: "The Strangler Fig pattern migrates a monolith by…", options: ["INCREMENTALLY routing one piece of functionality at a time to new services", "A risky big-bang rewrite", "Deleting the monolith immediately"], answer: 0,
    explain: "The system stays fully functional at every step." },
  { q: "A database migration's 'shadow read' phase…", options: ["Skips verification for speed", "Is optional and rarely useful", "Compares OLD vs NEW answers on real traffic BEFORE cutover, with zero user risk"], answer: 2,
    explain: "The highest-leverage risk-reduction step in a careful migration." },
  { q: "Feature flags during a migration enable…", options: ["No control over rollout", "GRADUAL percentage rollout with an INSTANT rollback (no redeploy)", "Only an all-or-nothing switch"], answer: 1,
    explain: "Flip back in seconds if problems appear at any rollout percentage." },
  { q: "The system design interview's Phase 1 (requirements) is important because…", options: ["You CANNOT make correct trade-offs without first knowing what you're trading FOR", "It wastes interview time", "It's optional if you're experienced"], answer: 0,
    explain: "The most-skipped, most-costly step for otherwise-strong engineers." },
  { q: "Back-of-envelope estimation's real value is…", options: ["What the NUMBER IMPLIES architecturally (e.g., sharding is/isn't needed)", "The exact arithmetic", "Showing off math skills"], answer: 0,
    explain: "State the number, then its architectural consequence." },
  { q: "A strong interview wrap-up proactively…", options: ["Names a SPECIFIC bottleneck and how you'd address it", "Avoids discussing limitations", "Claims the design has no weaknesses"], answer: 0,
    explain: "Demonstrates seeing past your own design's edges." },
  { q: "The CAP theorem, Dynamo's N/W/R, and Raft's quorum majority all share…", options: ["The mathematical guarantee that OVERLAPPING sets ensure at least one node enforces consistency", "The same exact algorithm", "No common idea"], answer: 0,
    explain: "Recognizing this as ONE recurring principle is a staff-level connection." },
  { q: "Across Amazon's inventory, the Rate Limiter, and general concurrency control, the recurring bug pattern is…", options: ["Too much caching", "CHECK-THEN-ACT as two separate non-atomic steps — always a race condition under concurrency", "Slow queries"], answer: 1,
    explain: "The fix is always making the check part of an atomic operation." },
  { q: "The overarching lesson of this entire System Design track is…", options: ["A small toolbox of Fundamentals, recombined via explicit trade-off reasoning, solves any new system", "Always choose the most complex/scalable option", "Memorize as many architectures as possible"], answer: 0,
    explain: "The transferable skill this track is built to teach." },
]},
);
