// react quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Routing",
  desc: "Nested routes, params, URL state, loaders, guards",
  questions: [
  { q: "Client-side routing works via…", options: ["Server rewrites", "History API (pushState/popstate) + matching the path to a route tree", "Hash polling"], answer: 1,
    explain: "Link intercepts clicks → pushState → render. Servers must serve index.html for all paths (SPA fallback)." },
  { q: "<a href> for internal links causes…", options: ["Faster navigation", "A full page reload — all state wiped", "Nothing"], answer: 1,
    explain: "<Link> renders a real <a> (SEO, cmd-click) but intercepts for SPA navigation." },
  { q: "Nested routes render children via…", options: ["Slots", "<Outlet /> in the parent layout", "props.children"], answer: 1,
    explain: "URL segments map to nested layouts; only the changed level swaps." },
  { q: "useParams() values are…", options: ["Typed", "Numbers when numeric", "Always STRINGS — Number()/schema-parse them"], answer: 2,
    explain: "id === 42 fails silently; parse params like any external input." },
  { q: "Redirects should navigate with…", options: ["push (default)", "window.location", "replace: true — no history entry, back button doesn't loop"], answer: 2,
    explain: "Otherwise back returns to the redirecting URL and bounces again." },
  { q: "Route loaders beat effect-fetching because…", options: ["They cache forever", "Fetching starts AT navigation, before render — no mount-then-fetch waterfall", "They're synchronous"], answer: 1,
    explain: "Nested effect-fetching compounds into waterfalls; loaders parallelize per level." },
  { q: "An index route is…", options: ["The 404", "The default child rendered at the parent's exact path", "The first route"], answer: 1,
    explain: "{ index: true, element: <Home/> } — '/' inside the layout." },
  { q: "NavLink exists for…", options: ["Buttons", "External links", "Active-state styling (isActive) on navigation menus"], answer: 2,
    explain: "className={({isActive}) => …} — current-page highlighting (+ aria-current)." },
  { q: "A client-side RequireAuth guard is…", options: ["UX only — the API must enforce auth server-side", "Enough for private data", "Security"], answer: 0,
    explain: "Anyone can bypass client code with curl — the forms lesson's trust boundary again." },
  { q: "After redirect-to-login, returning the user uses…", options: ["history.back()", "localStorage", "location.state.from captured by the guard, navigated to after login"], answer: 2,
    explain: "<Navigate state={{from: location}}/> then navigate(from ?? '/')." },
  { q: "Route-level code splitting uses…", options: ["Separate HTML files", "iframes", "lazy(() => import(...)) + Suspense at route boundaries"], answer: 2,
    explain: "Routes are the natural chunk seams (modules lesson applied)." },
  { q: "path='*' handles…", options: ["The 404 catch-all", "Wildcarded params", "All routes"], answer: 0,
    explain: "Plus errorElement per level for loader/render errors — no white screens." },
  { q: "Filters in useState instead of the URL break…", options: ["Nothing", "Performance", "Sharing, refresh persistence, and back-button expectations"], answer: 2,
    explain: "useSearchParams makes the view a shareable artifact." },
  { q: "useSearchParams returns…", options: ["[URLSearchParams, setter] — get()/set() and functional updates", "A plain object", "A string"], answer: 0,
    explain: "?q=shoes&page=2 — the URL is typed-ish state you must parse." },
  { q: "Deep links 404 in production because…", options: ["Missing sitemap", "The server doesn't fall back to index.html for unknown paths", "Router bug"], answer: 1,
    explain: "SPA hosting rule: rewrite all paths to the app shell (except real assets/APIs)." },
  { q: "useNavigate is for…", options: ["Query params", "Programmatic navigation after events (submit success) — links stay <Link>", "All links"], answer: 1,
    explain: "Links for navigation UI (a11y, SEO); navigate() for imperative flow." },
  { q: "Persisting layout state (sidebar scroll) across child navigation works because…", options: ["Magic", "Parent layout components DON'T remount when only child segments change", "localStorage"], answer: 1,
    explain: "Nested routing's under-appreciated payoff: stable shells." },
  { q: "Loaders + React Query together…", options: ["Are redundant", "Conflict", "Compose: loaders for route-shaped initial data, Query for cache/mutations/interactive data"], answer: 2,
    explain: "Production apps commonly seed Query's cache from loaders." },
  { q: "URL state should hold…", options: ["Auth tokens", "Form drafts", "View-defining state: filters, sort, tab, page, selected id"], answer: 2,
    explain: "Tokens in URLs leak via logs/referrers (security lesson); drafts belong local." },
  { q: "The router lesson's core insight is…", options: ["The URL is state — free, persistent, shareable — and routes map it to layout hierarchy", "SPAs don't need URLs", "Routing is styling"], answer: 0,
    explain: "Design URLs first and half your state management disappears." },
]},
{ title: "Quiz 7 · Performance",
  desc: "Re-render causes, memo trio, structure, virtualization, transitions",
  questions: [
  { q: "A component re-renders when…", options: ["Its state changes, its PARENT renders, or its context value changes", "Its props change (only)", "Every second"], answer: 0,
    explain: "Parent rendering is the big one — children render by default; memo makes props the gate." },
  { q: "Re-renders are…", options: ["Always a problem", "Free", "Usually cheap (object creation + diff) — optimize the proven exceptions"], answer: 2,
    explain: "Profile first; most 'optimization' without measurement is noise." },
  { q: "React.memo fails to help when…", options: ["Props are primitives", "Props include inline objects/functions — new references every render", "The child is big"], answer: 1,
    explain: "Object.is per prop: () => {} and {} are always 'changed'." },
  { q: "useCallback is…", options: ["Required for all handlers", "useMemo for FUNCTIONS — stable identity for memo children and effect deps", "A faster useEffect"], answer: 1,
    explain: "It exists largely to make memo actually work." },
  { q: "useMemo should wrap…", options: ["Everything", "Only sorting", "Provably expensive computes and reference-stability needs — not trivial expressions"], answer: 2,
    explain: "Memoization has its own cost; the profiler decides what's hot." },
  { q: "Typing lags because query state lives at page level. The FREE fix:", options: ["memo everything", "Push the state DOWN into the search box", "Web workers"], answer: 1,
    explain: "Structure beats memo: only the box re-renders per keystroke." },
  { q: "children-as-props helps because…", options: ["Smaller bundles", "Children created by the PARENT keep identity when the wrapper's state changes — skipped", "It's required by hooks"], answer: 1,
    explain: "The theme-wrapper pattern: state changes in the wrapper don't re-render passed-in children." },
  { q: "10,000 table rows need…", options: ["Virtualization — render only the visible window (~30 nodes)", "Pagination only", "More memo"], answer: 0,
    explain: "DOM size is the bottleneck no memo fixes; constant node count wins." },
  { q: "useTransition marks updates as…", options: ["Async", "Low-priority/interruptible — urgent input stays responsive while big renders lag", "Batched"], answer: 1,
    explain: "startTransition(() => setFilter(v)) — React can interrupt and restart the expensive render." },
  { q: "useDeferredValue is…", options: ["A debounce", "The value-flavored transition: UI reads a lagging copy while typing stays fresh", "A cache"], answer: 1,
    explain: "Unlike setTimeout debouncing, React can interrupt in-progress renders." },
  { q: "React DevTools Profiler shows…", options: ["Network calls", "Bundle sizes", "Who rendered, how long, and WHY (which props/state changed)"], answer: 2,
    explain: "The 'why did this render' feature names your unstable prop directly." },
  { q: "Context for rapidly-changing values causes…", options: ["All consumers re-rendering per change — use stores with selectors instead", "Nothing", "Memory leaks"], answer: 0,
    explain: "Context has no subscription granularity (state lesson)." },
  { q: "The React Compiler…", options: ["Auto-memoizes — manual memo/useCallback shrink where it's adopted", "Compiles to WASM", "Replaces the DOM"], answer: 0,
    explain: "The mental model (reference stability) still explains what it automates." },
  { q: "Key-related performance in lists:", options: ["Random keys are fastest", "Stable ids minimize diff churn; index keys cause re-renders AND state bugs", "Keys are only for warnings"], answer: 1,
    explain: "Identity stability = minimal reconciliation work." },
  { q: "An expensive initial computation for useState:", options: ["Lazy initializer: useState(() => expensive())", "useEffect it", "Compute inline"], answer: 0,
    explain: "Inline runs every render (result discarded); the initializer runs once." },
  { q: "The fix ladder for slow interactions:", options: ["Rewrite in another framework", "memo first, always", "Profile → structure (state down/children up) → memo trio → defer/transition → virtualize"], answer: 2,
    explain: "Cheap structural fixes first; measured memoization after; DOM-size tools last." },
  { q: "Inline style={{...}} on a memo'd child…", options: ["Is faster than classes", "Defeats the memo (new object) — hoist or useMemo it", "Fine"], answer: 1,
    explain: "Same rule as handlers: reference stability is the contract." },
  { q: "'Highlight updates' in DevTools reveals…", options: ["Slow network", "Re-render storms visually — which components flash on each interaction", "Memory leaks"], answer: 1,
    explain: "The quickest smell test before formal profiling." },
  { q: "Transitions vs debouncing for filter-as-you-type:", options: ["Transitions keep rendering interruptible with no artificial delay; debounce adds latency", "Debounce is always better", "Identical"], answer: 0,
    explain: "Often combined: debounce network, transition rendering." },
  { q: "The prerequisite fact behind ALL of this:", options: ["React is slow", "Reference semantics (arrays lesson): new references signal change; stable references signal same", "GC pauses"], answer: 1,
    explain: "memo, deps, selectors, context — all Object.is on references." },
]},
{ title: "Quiz 8 · Testing",
  desc: "RTL philosophy, queries, userEvent, MSW, the trophy",
  questions: [
  { q: "RTL's guiding principle is…", options: ["Test what users experience — queries resemble how software is used", "Test every function", "100% coverage"], answer: 0,
    explain: "Behavior-coupled tests survive refactors and fail when UX actually breaks." },
  { q: "The query priority order starts with…", options: ["getByTestId", "getByClassName", "getByRole (with accessible name) — a11y and testing in one"], answer: 2,
    explain: "Roles come from semantic HTML; testid is the last resort (and often a semantics smell)." },
  { q: "getBy vs queryBy vs findBy:", options: ["Sync/async/batch", "Aliases", "exists-now(throws) / null-if-absent(absence checks) / await-appearance(async)"], answer: 2,
    explain: "expect(queryByText('Error')).not.toBeInTheDocument(); await findByText('Saved')." },
  { q: "userEvent beats fireEvent because…", options: ["It simulates real interaction SEQUENCES (focus, keydown, input) — not synthetic single events", "It's faster", "It's newer"], answer: 0,
    explain: "userEvent.setup() + await user.type/click — catches what real users trigger." },
  { q: "MSW mocks at…", options: ["The component level", "The NETWORK boundary — components run their real fetch/parsing code", "The function level"], answer: 1,
    explain: "URL building, params, error mapping all get tested; one handler set serves tests/dev/Storybook." },
  { q: "Testing an error state with MSW:", options: ["Mock console.error", "server.use(http.get(url, () => HttpResponse.error())) per test", "throw in the component"], answer: 1,
    explain: "Per-test overrides make failure branches one-liners." },
  { q: "Tests asserting internal state values…", options: ["Are thorough", "Break on refactors while missing UX bugs — test visible outcomes", "Are required for hooks"], answer: 1,
    explain: "False negatives + false positives: the worst of both." },
  { q: "The testing trophy's biggest layer is…", options: ["Integration (RTL component flows) — best confidence per cost", "Unit", "E2E"], answer: 0,
    explain: "Types+lint at the base; few unit for pure logic; few Playwright E2E for critical paths." },
  { q: "Role queries double as…", options: ["Accessibility audits — no accessible name means the query fails", "Snapshots", "Performance tests"], answer: 0,
    explain: "Inaccessible UI becomes untestable UI — the incentive aligns." },
  { q: "Async UI assertions require…", options: ["await findBy… (and awaiting userEvent calls)", "act() wrappers everywhere", "setTimeout in tests"], answer: 0,
    explain: "Un-awaited async is the source of flaky tests and act warnings." },
  { q: "Custom hooks with logic are tested via…", options: ["Rendering a full page", "console.log", "renderHook + act"], answer: 2,
    explain: "The hooks lesson's payoff: logic without UI." },
  { q: "Snapshot tests are best for…", options: ["Small, stable output — snapshot-everything is churn without meaning", "Never", "Everything"], answer: 0,
    explain: "Giant snapshots get approved blindly; targeted assertions carry meaning." },
  { q: "What layer tests 'checkout works end-to-end in a real browser'?", options: ["RTL", "Unit", "Playwright E2E — few, on critical paths, against staging"], answer: 2,
    explain: "E2E is slow/flaky at volume; reserve it for the flows that pay the bills." },
  { q: "expect(await screen.findByRole('alert')).toHaveTextContent(/failed/i) tests…", options: ["Styling", "Error UI appears AND is announced (role=alert) — behavior + a11y", "The API"], answer: 1,
    explain: "The errors lesson's role=alert becomes an assertable contract." },
  { q: "Pure domain logic (pricing, validators) belongs in…", options: ["Fast unit tests — exhaustive edge cases are cheap there", "E2E", "RTL tests"], answer: 0,
    explain: "The architecture lesson's pure layers exist partly FOR this." },
  { q: "vi.mock('axios') style mocking risks…", options: ["Slow tests", "Nothing", "Testing a stub of your own imagination — request building/parsing untested, drift from reality"], answer: 2,
    explain: "MSW keeps the real pipeline in play." },
  { q: "Coverage as a goal should be…", options: ["Ignored", "Behavior/branch coverage of flows — line % is gameable and meaningless alone", "100% lines"], answer: 1,
    explain: "A 100%-covered suite asserting nothing catches nothing." },
  { q: "Test files live…", options: ["In /tests only", "In a separate repo", "Next to their subjects (feature folders) — ownership and discovery"], answer: 2,
    explain: "The architecture lesson's feature organization includes tests." },
  { q: "beforeAll(server.listen) / afterEach(resetHandlers) / afterAll(close) is…", options: ["Overkill", "Jest-only", "The standard MSW lifecycle — clean state per test"], answer: 2,
    explain: "resetHandlers prevents one test's override leaking into the next." },
  { q: "The refactor test of a good suite:", options: ["Rename internals/restructure components → behavior tests still pass", "All tests break", "Tests are skipped"], answer: 0,
    explain: "If a rename breaks 40 tests, they were testing the implementation." },
]},
{ title: "Quiz 9 · RSC, Next.js & Architecture",
  desc: "Server components, actions, streaming, app structure",
  questions: [
  { q: "Server components' defining property:", options: ["They can't use JSX", "Their code NEVER ships to the browser — zero bundle contribution", "They render faster"], answer: 1,
    explain: "Markdown renderers, data layers, heavy libs stay server-side; bundle ∝ interactivity." },
  { q: "\"use client\" marks…", options: ["A BOUNDARY — the entire import subtree becomes client code", "A performance hint", "A single component"], answer: 0,
    explain: "Place it at the interactive LEAVES; high placement drags everything client-side." },
  { q: "RSC vs SSR:", options: ["SSR = first-paint HTML but ships all JS; RSC = server code ships NO JS. They compose", "Same thing", "RSC replaces SSR"], answer: 0,
    explain: "Next.js does both: streamed HTML + server-only tree + hydrated islands." },
  { q: "Server components can…", options: ["Use useState", "await databases/secrets directly — no API layer for first-party reads", "Attach onClick"], answer: 1,
    explain: "Hooks/events need the client; data access is the server side's superpower." },
  { q: "Props crossing server→client must be…", options: ["Strings only", "Anything", "Serializable — no functions/class instances (Server Actions are the exception)"], answer: 2,
    explain: "The boundary is a network boundary; structured-clone rules apply." },
  { q: "Server Actions are…", options: ["Middleware", "Typed server functions callable from forms/clients — mutations without hand-rolled API routes", "Cron jobs"], answer: 1,
    explain: "form action={addTodo} works pre-hydration; revalidatePath refreshes the tree." },
  { q: "Server Actions still require…", options: ["CORS headers", "Validation + authorization — they are PUBLIC endpoints", "Nothing — React secures them"], answer: 1,
    explain: "Treat every action like any API route (zod + auth checks)." },
  { q: "loading.tsx in the App Router is…", options: ["A spinner component", "An automatic Suspense fallback while the segment streams", "A route guard"], answer: 1,
    explain: "Streaming SSR: shell immediately, slow parts replace fallbacks as they resolve." },
  { q: "Sequential awaits in a server page cause…", options: ["Nothing", "Client waterfalls", "SERVER waterfalls — slow TTFB; Promise.all or Suspense-per-section"], answer: 2,
    explain: "The async lesson's waterfall, relocated — same fix." },
  { q: "Secrets are safe in…", options: ["Client components if not logged", "Server components/actions only; NEXT_PUBLIC_ env vars are bundled and public", "Any component"], answer: 1,
    explain: "The JS security lesson's iron law, enforced by the RSC boundary." },
  { q: "Client components CAN receive server components via…", options: ["children/props — composition crosses back through the boundary", "Import", "iframes"], answer: 0,
    explain: "Interactive wrappers stay thin: <ClientTabs>{serverRenderedPanels}</ClientTabs>." },
  { q: "Feature-folder organization beats type folders because…", options: ["Shorter imports", "Alphabetical order", "Changes localize to one owned folder with a public API (index.ts) — enforced boundaries"], answer: 2,
    explain: "Cross-feature deep imports = invisible coupling; lint the boundaries." },
  { q: "UI components in the layered architecture…", options: ["Are pure props→JSX; data access lives in hooks/loaders; policy in one api client", "Fetch their own data", "Own business logic"], answer: 0,
    explain: "The swap test: REST→GraphQL should touch only the data layers." },
  { q: "Error boundaries catch…", options: ["RENDER-phase throws in their subtree — handlers/async still use try/catch", "Network errors", "All errors"], answer: 0,
    explain: "Route-level + widget-level boundaries bound the blast radius; report to telemetry." },
  { q: "The provider stack (composition root) exists so…", options: ["Providers are required", "Contexts nest deeply", "The app is assembled in ONE place — tests/Storybook swap dependencies there"], answer: 2,
    explain: "Dependency injection, React-style." },
  { q: "State classification's four buckets:", options: ["Big/small/fast/slow", "Hot/cold/warm/frozen", "Server (Query/RSC) · URL (router) · client (store) · local (useState)"], answer: 2,
    explain: "Classify first; the global store should be embarrassingly small." },
  { q: "Architecture survives at scale via…", options: ["CI enforcement: boundary lint, bundle budgets, test suites, visual regression", "Documentation", "Seniority"], answer: 0,
    explain: "Convention erodes in a quarter; automation doesn't (the CSS design-systems twin)." },
  { q: "revalidatePath/revalidateTag do…", options: ["Reload the page", "Clear the browser cache", "Invalidate server-side cached renders/data so the next request is fresh"], answer: 2,
    explain: "The cache-invalidation half of Next's data story — pair with mutations." },
  { q: "A layout.tsx in App Router…", options: ["Re-renders per navigation", "Is client-only", "Persists across child navigations — nested shells (the router lesson's insight)"], answer: 2,
    explain: "Stable shells + swapped segments = the nested-routing model." },
  { q: "The bundle-size consequence of RSC done right:", options: ["Zero JS ever", "JS ∝ interactive islands, not page count/content size", "Bigger bundles"], answer: 1,
    explain: "Content-heavy pages ship almost nothing; dashboards ship their widgets." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "A todo's input text jumps to the wrong row after deleting another row. Root cause:", options: ["Missing memo", "Stale closure", "Index keys — state stayed with the slot, not the item"], answer: 2,
    explain: "The rendering lesson's fingerprint bug. Stable ids fix identity." },
  { q: "onClick={save()} fires on render. Why?", options: ["save() CALLS it — pass the reference or () => save(id)", "React bug", "Missing useCallback"], answer: 0,
    explain: "The functions lesson's call-vs-pass, in JSX clothing." },
  { q: "A [] effect's interval always logs 1. Name the concept and the best fix.", options: ["Batching; use setTimeout", "Stale closure; functional update setCount(c => c+1)", "Race; AbortController"], answer: 1,
    explain: "Each render's functions capture that render's values — hooks are closures." },
  { q: "Fast typing shows results for an OLD query. The fix:", options: ["Debounce only", "useMemo", "AbortController in the effect cleanup (cancel stale requests)"], answer: 2,
    explain: "Debounce reduces requests; only cancellation fixes the ordering race." },
  { q: "memo'd <Row onSelect={() => …} /> re-renders anyway because…", options: ["The inline arrow is a new reference each parent render", "Rows can't be memo'd", "memo is broken"], answer: 0,
    explain: "useCallback the handler — reference semantics all the way down." },
  { q: "The whole page re-renders per keystroke in a header search. Cheapest fix:", options: ["Move query state INTO the search component", "memo every component", "Redux"], answer: 0,
    explain: "Structure first: state down / children up, before any memo." },
  { q: "setCount(count+1) in a Promise.then adds stale values. Why?", options: ["The closure captured an old snapshot — functional updates read the latest", "Promises break React", "Missing await"], answer: 0,
    explain: "Snapshots + closures: the two lessons that explain most React bugs." },
  { q: "Choosing state homes: filters, fetched products, cart, open-modal flag →", options: ["All Redux", "URL · Query cache · store/context · local useState", "All context"], answer: 1,
    explain: "Classification is the architecture answer interviews grade." },
  { q: "A chart widget's crash white-screens the app. Missing:", options: ["try/catch in render", "Sentry", "Error boundaries at route AND widget level"], answer: 2,
    explain: "Boundaries bound blast radius; telemetry attaches at the boundary." },
  { q: "Your form resets when the parent re-renders. Likely cause:", options: ["Missing keys", "The form component is defined INSIDE the parent — new type each render, remounts", "Controlled inputs"], answer: 1,
    explain: "Top-level definitions only; nested definitions = identity churn." },
  { q: "Test breaks: 'getByText(\"3 items\")' after refactoring to '3 products'. The deeper issue:", options: ["RTL is wrong", "Asserting copy is fine — but role/label queries + behavior assertions survive better; update the assertion", "Flaky test"], answer: 1,
    explain: "Behavior tests still assert SOMETHING visible — choose stable user-facing contracts." },
  { q: "Next.js page ships a huge bundle though it's mostly text. First suspect:", options: ["Images", "\"use client\" placed at the page/layout level dragging the tree client-side", "CSS"], answer: 1,
    explain: "Push the directive to the leaves; verify with the bundle analyzer." },
  { q: "value={{user, login}} on an AuthProvider — consumers re-render constantly. Fix:", options: ["More context", "useMemo the value (and/or split state/dispatch contexts)", "Zustand only"], answer: 1,
    explain: "New object per render = every consumer invalidated." },
  { q: "10k-row table with memo'd rows still janks on scroll. Next move:", options: ["Server components", "Virtualize — DOM node count is the bottleneck memo can't fix", "More useCallback"], answer: 1,
    explain: "The fix ladder's last rung: constant DOM size." },
  { q: "A Server Action inserts rows without checking the session. Severity:", options: ["Fine — React handles it", "Critical: it's a public endpoint; validate + authorize inside", "Low"], answer: 1,
    explain: "Actions ≈ API routes; the trust boundary never moved." },
  { q: "Filter list janks while typing. The React-native (non-debounce) tool:", options: ["useDeferredValue/useTransition — interruptible low-priority rendering", "setTimeout", "Web Worker"], answer: 0,
    explain: "Urgent input, laggy results — time-slicing as API." },
  { q: "Two components call useLocalStorage('theme') and disagree after one updates. Why?", options: ["Hooks share logic, not state — each call owns its useState; sync needs context/store/events", "localStorage is async", "JSON parsing"], answer: 0,
    explain: "The custom-hooks misconception, live." },
  { q: "Loader vs effect fetching for a product page — the waterfall difference:", options: ["Effect: render→mount→fetch→render (per nesting level); loader: fetch AT navigation, parallel", "None", "Loaders cache"], answer: 0,
    explain: "Data-before-render is the shared philosophy of loaders and RSC." },
  { q: "StrictMode 'breaks' an effect by subscribing twice. Verdict:", options: ["The effect lacks cleanup — StrictMode exposed a real leak", "Disable StrictMode", "React bug"], answer: 0,
    explain: "setup→cleanup→setup is a resilience test; production code needs the cleanup anyway." },
  { q: "The single most award-worthy React habit this track taught:", options: ["Memorize hook APIs", "Reason from the model: UI=f(state), snapshots+closures, reference identity, boundaries — everything else derives", "Always use the newest framework"], answer: 1,
    explain: "Four ideas explain every 'weird React behavior' question ever asked. 🏆" },
]},
);
