// react quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Components & JSX",
  desc: "Elements, JSX rules, composition, purity",
  questions: [
  { q: "React's core model is…", options: ["Manipulate the DOM directly", "Templates with two-way binding", "UI = f(state): describe the UI, React reconciles the DOM"], answer: 2,
    explain: "You describe what the UI looks like for current data; React diffs and patches minimally." },
  { q: "JSX compiles to…", options: ["HTML strings", "DOM nodes", "Function calls producing element OBJECTS"], answer: 2,
    explain: "Elements are cheap immutable descriptions — that's why they can live in variables, arrays, and props." },
  { q: "className instead of class exists because…", options: ["Style preference", "JSX is JavaScript — class is a reserved word; props are JS object keys", "CSS modules require it"], answer: 1,
    explain: "Same reason for htmlFor and camelCase event props (onClick)." },
  { q: "<usercard /> (lowercase) renders…", options: ["The component", "An error", "An unknown HTML tag — components MUST be Capitalized"], answer: 2,
    explain: "Capitalization is how JSX distinguishes your components from HTML tags." },
  { q: "A component returning two sibling elements needs…", options: ["Nothing — JSX allows it", "An array", "A Fragment <>…</> (or one wrapper)"], answer: 2,
    explain: "A function returns one value; fragments group without adding DOM nodes." },
  { q: "{userInput} in JSX is…", options: ["Auto-escaped — safe by default", "Only safe with sanitize()", "An XSS risk"], answer: 0,
    explain: "The escape hatch is deliberately named dangerouslySetInnerHTML — every use is a review event." },
  { q: "Render functions must be pure because…", options: ["Purity is faster", "Style guides say so", "React may call them many times (StrictMode ×2, concurrent may discard renders)"], answer: 2,
    explain: "Impure renders (mutations, API calls) run unpredictably often — StrictMode double-render exposes them in dev." },
  { q: "Defining a component INSIDE another component causes…", options: ["Remounting (state loss) every parent render — new function identity each time", "Better encapsulation", "Nothing"], answer: 0,
    explain: "React sees a different component type each render → unmount/remount. Always define at top level." },
  { q: "children is…", options: ["Just a prop containing whatever was nested — React's slot mechanism", "A special React object", "The DOM children"], answer: 0,
    explain: "Layout({children}) — composition via children replaces inheritance entirely." },
  { q: "React reuse is built on…", options: ["Composition: nesting, props, children, hooks", "Mixins", "Class inheritance"], answer: 0,
    explain: "There is no extends in idiomatic React; the docs explicitly recommend composition." },
  { q: "A re-render means…", options: ["The DOM is rebuilt", "The page reloads", "Component functions run again; React diffs element trees; only real changes touch the DOM"], answer: 2,
    explain: "Rendering is cheap object creation; committing is the minimal DOM patch." },
  { q: "style={{ fontSize: 14 }} — the double braces are…", options: ["A JS object inside a JSX expression; CSS properties camelCase", "Special JSX syntax", "A Sass map"], answer: 0,
    explain: "Outer braces = expression; inner = object literal." },
  { q: "Statements (if/for) in JSX…", options: ["Work fine", "Aren't allowed — use ternaries, &&, and map (expressions produce values)", "Need a plugin"], answer: 1,
    explain: "JSX holes take EXPRESSIONS; branch with ternaries or early returns before the JSX." },
  { q: "StrictMode in development…", options: ["Enables strict TypeScript", "Slows the app in prod", "Double-invokes renders/effects to expose impurity and missing cleanup"], answer: 2,
    explain: "If double-running breaks your component, the component was already broken." },
  { q: "An element vs a component:", options: ["Component = the function; element = the object a JSX expression returns", "Synonyms", "Element = DOM node"], answer: 0,
    explain: "Render calls components to get elements; the renderer syncs the DOM to the element tree." },
  { q: "The standard 2026 React starter is…", options: ["Webpack by hand", "Vite (npm create vite -- --template react-ts) or Next.js for full-stack", "create-react-app"], answer: 1,
    explain: "CRA is deprecated; Vite for SPAs, Next for RSC/SSR apps." },
  { q: "Void elements in JSX (img, input)…", options: ["Work like HTML", "Must self-close: <img />", "Need children"], answer: 1,
    explain: "JSX is stricter than HTML's forgiving parser." },
  { q: "Returning null from a component…", options: ["Renders nothing — the idiomatic 'skip me'", "Renders 'null'", "Crashes"], answer: 0,
    explain: "null/undefined/false render nothing (but 0 renders! — the && trap)." },
  { q: "Passing JSX as a prop (<Layout sidebar={<Nav/>} />)…", options: ["Is an anti-pattern", "Is normal composition — elements are just values", "Breaks reconciliation"], answer: 1,
    explain: "Elements are objects; slots-via-props is idiomatic (and powers the lift-content-up perf pattern)." },
  { q: "React attaches event listeners…", options: ["Via delegation at the root — the DOM lesson's pattern industrialized", "On every element", "With inline onclick attributes"], answer: 0,
    explain: "Synthetic events route through root-level delegation; your onClick props are the routing table." },
]},
{ title: "Quiz 2 · Props & State",
  desc: "useState, snapshots, batching, immutability, lifting",
  questions: [
  { q: "Props are…", options: ["Mutable inputs", "Global config", "Read-only inputs from the parent; events flow back via callback props"], answer: 2,
    explain: "Props down, events up — the one-way data flow." },
  { q: "setCount(count+1) then console.log(count) logs…", options: ["undefined", "The OLD value — state is a per-render snapshot", "The new value"], answer: 1,
    explain: "Setting state requests a re-render; the running function keeps its snapshot." },
  { q: "Three setCount(count+1) calls in one handler yield…", options: ["Three renders", "+1 — same snapshot three times, batched into one render", "+3"], answer: 1,
    explain: "Functional updates (c => c+1) queue transformations and give +3." },
  { q: "items.push(x) doesn't re-render because…", options: ["push is async", "Same reference — React detects change by Object.is", "Arrays aren't reactive"], answer: 1,
    explain: "setItems([...items, x]) creates a new reference — detectable in O(1)." },
  { q: "Updating one todo immutably:", options: ["todos.splice(i, 1, updated)", "setTodos(todos.map(t => t.id === id ? {...t, done: !t.done} : t))", "todos[i].done = true"], answer: 1,
    explain: "map + spread = new array, new object for the changed item, others by reference." },
  { q: "useState(() => readLocalStorage()) vs useState(readLocalStorage()):", options: ["The function form runs ONCE; the direct call runs every render (wasted work)", "The function form is async", "Identical"], answer: 0,
    explain: "Lazy initializer for expensive initial state." },
  { q: "Two siblings need the same data. State lives…", options: ["In a global store immediately", "In both, synced by effects", "In their closest common parent, passed down (lifting state)"], answer: 2,
    explain: "Single source of truth; escalate to context/stores only by proven scope." },
  { q: "Storing filteredItems in state alongside items and query is…", options: ["Required for performance", "Good caching", "Duplicated derivable state — compute it during render instead"], answer: 2,
    explain: "Litmus: can it get out of sync with its source? Then derive it (useMemo only if provably expensive)." },
  { q: "Mirroring a prop into state (useState(props.user))…", options: ["Is the standard pattern", "Freezes the initial value — the UI ignores later prop changes", "Causes infinite loops"], answer: 1,
    explain: "Use the prop directly, derive, or name it initialX and reset via key." },
  { q: "A controlled input is…", options: ["Disabled", "Read-only", "value={state} + onChange updating it — React state is the source of truth"], answer: 2,
    explain: "The input displays state; typing updates state; state re-renders the input." },
  { q: "Nested state update (user.address.city):", options: ["user.address.city = x; setUser(user)", "setUser(user.address.city = x)", "setUser({...user, address: {...user.address, city}})"], answer: 2,
    explain: "Spread each level you change — shallow copies share the untouched rest." },
  { q: "Batching means…", options: ["Multiple set-calls in one event = ONE re-render", "State updates are delayed a second", "Requests are merged on the server"], answer: 0,
    explain: "React 18 batches everywhere (including async callbacks) — renders are per-event, not per-set." },
  { q: "Callback props like onDismiss are…", options: ["How children notify parents — events flow up", "An anti-pattern", "Only for forms"], answer: 0,
    explain: "The child stays reusable; the parent owns the behavior." },
  { q: "Object.is-equal state set (setUser(sameRef))…", options: ["Bails out — no re-render", "Throws", "Re-renders anyway"], answer: 0,
    explain: "Another reason mutation is invisible: same reference = bail-out." },
  { q: "Where does 'derive, don't store' NOT apply?", options: ["Filtered lists", "Computed totals", "Values that are genuinely independent inputs (the query text itself)"], answer: 2,
    explain: "Inputs are state; everything computable FROM state derives." },
  { q: "Resetting a form when switching records is best done by…", options: ["Manually clearing each field", "An effect watching the id", "key={recordId} — remount with fresh state"], answer: 2,
    explain: "Key change = new identity = fresh useState initials (rendering lesson)." },
  { q: "props.role = 'admin' inside a component…", options: ["Is fine for defaults", "Violates read-only props / render purity", "Updates the parent"], answer: 1,
    explain: "Mutating props breaks f(state) and purity; defaults belong in destructuring." },
  { q: "The functional update form is REQUIRED when…", options: ["Using objects", "Always", "New state depends on previous (increments, toggles, async/stale contexts)"], answer: 2,
    explain: "c => c+1 reads the latest queued state — immune to stale snapshots (and the effects lesson's stale closures)." },
  { q: "useState vs useRef for a mutable value:", options: ["Interchangeable", "useState re-renders on change; useRef persists WITHOUT re-rendering (timers, DOM handles, latest-value)", "useRef is deprecated"], answer: 1,
    explain: "Refs are render-invisible instance variables; state drives UI." },
  { q: "'Single source of truth' means…", options: ["Each piece of data has ONE owner; everything else derives or receives it", "One global store", "The server owns everything"], answer: 0,
    explain: "Duplication is where sync bugs are born — the theme of the whole lesson." },
]},
{ title: "Quiz 3 · Rendering, Lists & Keys",
  desc: "Conditionals, map, key identity, reconciliation",
  questions: [
  { q: "{items.length && <List/>} with an empty array renders…", options: ["The list", "A literal 0 — 0 is falsy but renderable", "Nothing"], answer: 1,
    explain: "Fix: items.length > 0 && … or a ternary. The most-shipped React bug." },
  { q: "Keys exist so React can…", options: ["Encrypt props", "Match list items across renders by IDENTITY instead of position", "Sort lists"], answer: 1,
    explain: "Without keys (or with index keys), matching is positional — wrong after insert/delete/reorder." },
  { q: "Index-as-key + deleting the first row causes…", options: ["Every row's STATE (inputs, checkboxes) shifts to the wrong item", "Nothing visible", "A key warning only"], answer: 0,
    explain: "Old item 1 matches new key 0's slot — state stays with the slot, not the data." },
  { q: "key={Math.random()}…", options: ["Is required for dynamic lists", "Remounts everything every render — state wiped, focus lost", "Guarantees uniqueness, good"], answer: 1,
    explain: "New key = new identity = unmount/remount. Ids must be born with the data." },
  { q: "Index keys are acceptable when…", options: ["Never", "The list is long", "The list is static: no reorder, no filter, no insert/delete, stateless items"], answer: 2,
    explain: "Then position IS identity. Anything dynamic → stable ids." },
  { q: "key must be unique…", options: ["Per page", "Globally", "Among siblings in one list"], answer: 2,
    explain: "Reconciliation matches within one parent's children; different lists can reuse ids." },
  { q: "Reading props.key in the child gives…", options: ["An error", "undefined — key is consumed by React, not passed", "The key"], answer: 1,
    explain: "Pass the value as a second prop if the child needs it." },
  { q: "Deliberately changing key on a component…", options: ["Breaks reconciliation", "Is a hack", "Is the idiomatic RESET: unmount + remount with fresh state"], answer: 2,
    explain: "key={userId} on a form = fresh form per user, no effect gymnastics." },
  { q: "Early returns for loading/error/empty states are…", options: ["The cleanest whole-component branching — happy path last", "Slower than ternaries", "Forbidden in React"], answer: 0,
    explain: "if (loading) return <Spinner/>; keeps the main JSX unindented and readable." },
  { q: "The key goes on…", options: ["The OUTERMOST element returned by map()", "The container ul", "The innermost element"], answer: 0,
    explain: "React needs it on what the list directly renders." },
  { q: "Conditional attributes like disabled={!valid} work because…", options: ["JSX magic", "false/null attribute values are omitted from the DOM", "disabled is special-cased"], answer: 1,
    explain: "Booleans render as presence/absence — same for aria-* with strings." },
  { q: "Rendering nothing conditionally:", options: ["display:none always", "return ''", "return null (or false from &&)"], answer: 2,
    explain: "null = no output, component still mounted (state kept); display:none keeps DOM; unmounting drops state." },
  { q: "filter().map() chains in JSX are…", options: ["Too slow", "Idiomatic — it's just JavaScript producing element arrays", "Only allowed in loops"], answer: 1,
    explain: "Arrays of elements render in order; that's why keys matter." },
  { q: "Nested ternary pyramids should become…", options: ["More ternaries", "Early returns, extracted components, or a status→component lookup map", "Switch statements in JSX"], answer: 1,
    explain: "{views[status]} with a lookup object reads best for multi-state UI." },
  { q: "Reconciliation on type change (<div> → <span>)…", options: ["Reuses children", "Patches attributes", "Tears down the subtree and rebuilds — different type = different identity"], answer: 2,
    explain: "Same type = update in place; different type = remount. Keys extend this identity model to lists." },
  { q: "A stable id should come from…", options: ["The data (db id) or creation time (uuid when the item is CREATED)", "The render function", "The array index at save time"], answer: 0,
    explain: "Identity belongs to the data's lifecycle, never to a render pass." },
  { q: "List + detail with selection: clicking rows loses input text in rows. Likely cause:", options: ["Missing memo", "Index keys (or key tied to selection) remounting rows", "Slow network"], answer: 1,
    explain: "State-shifts-with-slot is the fingerprint of key identity bugs." },
  { q: "{user && <Profile user={user}/>} guards against…", options: ["Rendering with missing data (null user) — render-if", "XSS", "Slow renders"], answer: 0,
    explain: "&& renders nothing when falsy — just mind numeric left-hands (the 0 trap)." },
  { q: "Fragments with keys (<Fragment key={id}>) exist for…", options: ["Keyed multi-element list items without wrapper divs", "Styling", "Performance only"], answer: 0,
    explain: "The long-form Fragment accepts a key; <>…</> cannot." },
  { q: "The deep principle behind keys is…", options: ["Sorting stability", "Reconciliation matches by identity; state lives with the matched identity", "Memory efficiency"], answer: 1,
    explain: "Understand that sentence and every key bug becomes predictable." },
]},
{ title: "Quiz 4 · Forms, Events & Effects",
  desc: "Controlled/uncontrolled, submit, useEffect, cleanup, races",
  questions: [
  { q: "React's onChange on a text input fires…", options: ["On blur (like DOM change)", "Every keystroke (like DOM input)", "On Enter"], answer: 1,
    explain: "A naming quirk: React onChange = DOM input event." },
  { q: "Intercept form submission with…", options: ["onKeyDown for Enter", "onClick on the button", "onSubmit on the FORM + preventDefault — Enter key included"], answer: 2,
    explain: "Button clicks miss keyboard submission; the form event catches all paths." },
  { q: "value without onChange produces…", options: ["Two-way binding", "A normal input", "A frozen (read-only) input + warning"], answer: 2,
    explain: "Controlled means state drives the value; without onChange nothing updates state." },
  { q: "Controlled vs uncontrolled decision rule:", options: ["Always controlled", "Need the value DURING editing → controlled; only at submit → uncontrolled (FormData)", "Always uncontrolled"], answer: 1,
    explain: "Live validation/counters need state; submit-only forms don't need a render per keystroke." },
  { q: "defaultValue is for…", options: ["Uncontrolled inputs' initial value (DOM owns it after)", "Placeholders", "Controlled inputs"], answer: 0,
    explain: "value = controlled; defaultValue = uncontrolled. Mixing them earns the switching warning." },
  { q: "The controlled↔uncontrolled warning usually means…", options: ["Missing name attribute", "A React bug", "value flipped between undefined and defined — initialize state to ''"], answer: 2,
    explain: "Keep value always defined, or commit to defaultValue." },
  { q: "Validation errors should be…", options: ["Stored in refs", "DERIVED from form state during render (+ touched flags for UX)", "State set by effects"], answer: 1,
    explain: "Derived errors can't go stale; touched keeps pristine fields quiet (:user-invalid, React-style)." },
  { q: "useEffect's purpose is…", options: ["Anything after render", "Synchronizing with EXTERNAL systems (network, subscriptions, DOM APIs, widgets)", "Computing derived state"], answer: 1,
    explain: "No external system? You probably don't need the effect." },
  { q: "Effect cleanup runs…", options: ["Before every re-run AND at unmount, with the previous render's values", "After every render", "Only at unmount"], answer: 0,
    explain: "Setup/teardown pairs per dependency change — StrictMode proves the pair works." },
  { q: "Fetch effects need AbortController because…", options: ["Fast dep changes race: a stale response can overwrite the newer one", "fetch leaks otherwise", "React requires it"], answer: 0,
    explain: "Abort in cleanup; ignore AbortError. The classic search-box bug (async lesson) inside React." },
  { q: "An [] effect reading count via setInterval logs…", options: ["The mount render's count forever — stale closure", "undefined", "Live values"], answer: 0,
    explain: "Fixes: functional update, honest deps, or a ref. Deps exist because closures capture." },
  { q: "The exhaustive-deps lint rule should be…", options: ["Obeyed: list everything read; fix the design, not the warning", "Only for effects with fetch", "Disabled — it's noisy"], answer: 0,
    explain: "Silencing it is how stale-value bugs are farmed weeks later." },
  { q: "The effect function can't be async because…", options: ["await is banned in React", "Syntax error", "It must return a cleanup function, not a promise — use an inner async fn"], answer: 2,
    explain: "useEffect(() => { (async () => {...})(); return cleanup; })." },
  { q: "Deriving filtered results belongs…", options: ["In a ref", "In render (const filtered = …), useMemo if expensive", "In an effect setting state"], answer: 1,
    explain: "Effect-derived state = extra render + sync bugs — the top 'you might not need an effect' case." },
  { q: "Reacting to a button click belongs…", options: ["In useMemo", "In the event handler — effects are for 'being on screen'", "In an effect watching a clicked flag"], answer: 1,
    explain: "Handler logic in handlers; state→effect→state chains are cascade bugs." },
  { q: "Object literal in deps ([{id}]) causes…", options: ["A lint error only", "Effect re-runs every render — new reference each time", "Nothing"], answer: 1,
    explain: "Depend on primitives, memoize the object, or build it inside the effect." },
  { q: "StrictMode double-mounting effects catches…", options: ["Type errors", "Missing cleanup (duplicate subscriptions/timers) and non-resilient effects", "Slow effects"], answer: 1,
    explain: "setup→cleanup→setup in dev; production runs once." },
  { q: "Reading a whole uncontrolled form:", options: ["Object.fromEntries(new FormData(e.currentTarget))", "Query every input", "refs on each field"], answer: 0,
    explain: "The DOM lesson's FormData trick — name attributes are the keys." },
  { q: "Production data fetching typically uses…", options: ["XMLHttpRequest", "TanStack Query/SWR or router loaders/RSC — cache, dedupe, revalidate", "Raw useEffect everywhere"], answer: 1,
    explain: "Hand-rolled effect fetching re-implements caching badly and creates waterfalls." },
  { q: "The litmus question for any effect:", options: ["'Which external system does this synchronize with?'", "Is it fast?", "Does it have deps?"], answer: 0,
    explain: "No answer → derive in render or move to the handler." },
]},
{ title: "Quiz 5 · Hooks Deep Dive",
  desc: "Rules of hooks, custom hooks, refs, context basics",
  questions: [
  { q: "Hooks must be called at the top level because…", options: ["Style", "Hook state lives in call-ORDER slots — skipping one misaligns every later slot", "Performance"], answer: 1,
    explain: "Conditional hooks = 'rendered fewer hooks than expected' crash. Branch INSIDE hooks." },
  { q: "A custom hook is…", options: ["A React plugin", "A class", "A useX-named function calling other hooks — sharing LOGIC, not state"], answer: 2,
    explain: "Each caller gets independent state; shared state needs context/stores." },
  { q: "Two components calling useCart() (a plain custom hook)…", options: ["Each get their OWN state — hooks don't share state", "Crash", "Share cart state"], answer: 0,
    explain: "The #1 custom-hook misconception. Sharing requires context or an external store." },
  { q: "The use prefix is required because…", options: ["Convention only", "The lint rule identifies hooks by name to enforce the rules of hooks", "React parses the name"], answer: 1,
    explain: "getWidth() calling useState would evade rule checking — name it useWidth." },
  { q: "useRef differs from useState in that…", options: ["Mutating .current does NOT re-render — persistent render-invisible storage", "It's for DOM only", "It's faster state"], answer: 0,
    explain: "DOM handles, timer ids, latest-value escape hatches — instance variables for functions." },
  { q: "useDebouncedValue is implemented with…", options: ["setInterval", "An effect setting state after a timeout, CLEANUP clearing it on value change", "useMemo"], answer: 1,
    explain: "Effect cleanup IS the debounce reset — closures + effects unified." },
  { q: "Hook APIs should accept…", options: ["No arguments", "Options objects always", "Primitives where possible — object args are new references → effect churn"], answer: 2,
    explain: "useUser(id) beats useUser({id}) unless the object is memoized." },
  { q: "Functions returned by hooks should be…", options: ["useCallback-stabilized so consumers can use them in deps safely", "Global", "Fresh each render"], answer: 0,
    explain: "Unstable returns force consumers to choose between lint violations and re-runs." },
  { q: "Testing a hook without UI:", options: ["Impossible", "renderHook + act from Testing Library", "console.log"], answer: 1,
    explain: "Extraction's payoff: stateful logic tested standalone." },
  { q: "useContext(ThemeContext) reads…", options: ["The value from the NEAREST provider above (default only if none)", "The default always", "All providers merged"], answer: 0,
    explain: "Nested providers shadow outer ones — scoped overrides." },
  { q: "When a context value changes…", options: ["Only changed consumers render", "EVERY consumer re-renders (Object.is on value) — memo can't save them", "Nothing renders"], answer: 1,
    explain: "Why: split contexts, memo the value, keep contexts low-frequency." },
  { q: "value={{user, setUser}} on a provider…", options: ["Creates a new object every render → all consumers re-render every time", "Is fine", "Is required"], answer: 0,
    explain: "useMemo the value or split state/dispatch contexts." },
  { q: "useReducer shines when…", options: ["Transitions are complex/interdependent with many update sites — logic centralized and PURE", "State is a boolean", "You need async"], answer: 0,
    explain: "Unit-test the reducer alone; components just dispatch named events." },
  { q: "Reducers must not…", options: ["Use switch", "Contain side effects (fetch, random, Date.now) — they must be pure", "Return objects"], answer: 1,
    explain: "Effects go in handlers/middleware; purity = testability + replayability (StrictMode double-dispatch!)." },
  { q: "Server data (fetched lists) belongs in…", options: ["Context", "TanStack Query/SWR — it's CACHE with staleness semantics, not client state", "Redux/Zustand"], answer: 1,
    explain: "The insight that shrank Redux apps by 80%: classify state before choosing a tool." },
  { q: "Filters/tabs/pagination belong in…", options: ["The URL (searchParams) — shareable, refresh-proof, back-button-correct", "useState", "localStorage"], answer: 0,
    explain: "'Would a user share/bookmark this view?' → URL state." },
  { q: "Zustand's selector (useCart(s => s.items)) buys…", options: ["Type safety", "Re-render only when THAT slice changes — granularity context lacks", "Shorter code"], answer: 1,
    explain: "Selector subscriptions are the store's core perf feature." },
  { q: "The escalation ladder for state is…", options: ["Context first", "useState → lift → useReducer → context (low-freq) → store (high-freq shared)", "Global first"], answer: 1,
    explain: "Scope decides the tool; never start global." },
  { q: "useId is for…", options: ["List keys", "Stable unique ids for accessibility attributes (label htmlFor) — SSR-safe", "Database keys"], answer: 1,
    explain: "Never use it for list keys (those come from data); it exists to match server/client generated ids." },
  { q: "Composing hooks (useOnScreen feeding useQuery's enabled)…", options: ["Is too clever", "Breaks the rules", "Is the point — atomic hooks compose into behaviors (lazy-load on visibility)"], answer: 2,
    explain: "Flat function composition is why hooks replaced HOCs/render-props." },
]},
);
