// Kubernetes quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Architecture & Reconciliation",
  desc: "Control plane, nodes, the reconciliation loop, key objects",
  questions: [
  { q: "Kubernetes' core operating model is…", options: ["Imperative scripts", "Declarative desired state + continuous reconciliation", "Manual SSH"], answer: 1,
    explain: "Controllers converge actual state to desired state." },
  { q: "What is the single source of truth for cluster state?", options: ["The kubelet", "etcd", "kube-proxy"], answer: 1,
    explain: "A consistent key-value store; only the API server writes to it." },
  { q: "The ONLY component that writes to etcd is…", options: ["The scheduler", "The kube-apiserver", "The kubelet"], answer: 1,
    explain: "Everything goes through the API server." },
  { q: "The kube-scheduler's job is to…", options: ["Run containers", "Decide which node an unscheduled Pod runs on", "Store state"], answer: 1,
    explain: "Based on resources, affinity, taints." },
  { q: "The kubelet runs…", options: ["On the API server only", "On every node — ensures its assigned Pods are healthy", "In etcd"], answer: 1,
    explain: "The node agent talking to the runtime." },
  { q: "Does Kubernetes require Docker?", options: ["Yes always", "No — it uses the CRI (containerd/CRI-O)", "Only on Windows"], answer: 1,
    explain: "OCI/CRI decouple it from Docker." },
  { q: "A reconciliation loop does…", options: ["Runs once", "Observe actual → compare to desired → act to converge, continuously", "Nothing"], answer: 1,
    explain: "Why K8s self-heals." },
  { q: "kube-proxy is responsible for…", options: ["Scheduling", "Programming node network rules so Service IPs route to Pods", "Storage"], answer: 1,
    explain: "Service networking on each node." },
  { q: "The smallest deployable unit in Kubernetes is…", options: ["A container", "A Pod", "A node"], answer: 1,
    explain: "One or more containers sharing network/storage." },
  { q: "The kube-controller-manager runs…", options: ["The UI", "The control loops (Deployment, ReplicaSet, Node…)", "etcd"], answer: 1,
    explain: "The reconciling controllers." },
  { q: "When you kubectl apply, the object first goes to…", options: ["The kubelet", "The API server (which validates + persists to etcd)", "The scheduler"], answer: 1,
    explain: "The front door for all requests." },
  { q: "A Namespace is…", options: ["A physical machine", "A virtual cluster for isolating/organizing resources", "A container"], answer: 1,
    explain: "Logical partitioning." },
  { q: "If a Pod dies, actual < desired replicas, so…", options: ["Nothing", "The ReplicaSet controller creates a replacement", "The node reboots"], answer: 1,
    explain: "Self-healing via reconciliation." },
  { q: "A Node is…", options: ["A control loop", "A worker machine (VM/physical) that runs Pods", "A Service"], answer: 1,
    explain: "The 'muscle' of the cluster." },
  { q: "The cloud-controller-manager…", options: ["Runs containers", "Integrates with the cloud (LBs, volumes, nodes)", "Stores secrets"], answer: 1,
    explain: "Cloud provider integration." },
  { q: "Which best describes why K8s adds complexity worth justifying?", options: ["It's always simplest", "Self-healing/scaling/HA across machines has operational cost", "It removes YAML"], answer: 1,
    explain: "Small apps may prefer Compose/PaaS." },
  { q: "The container runtime (containerd/CRI-O) actually…", options: ["Schedules Pods", "Runs the containers via the CRI", "Writes to etcd"], answer: 1,
    explain: "Started by the kubelet." },
  { q: "Deployment → ReplicaSet → Pod is…", options: ["Random", "A management hierarchy (each layer manages the next)", "Three names for one thing"], answer: 1,
    explain: "Deployment manages ReplicaSets manage Pods." },
  { q: "'Desired state, continuously reconciled' explains…", options: ["Only networking", "Nearly all Kubernetes behavior", "Only storage"], answer: 1,
    explain: "The unifying mental model." },
  { q: "You manage a cluster primarily by…", options: ["Running imperative commands", "Editing declarative YAML (the desired state)", "SSHing to nodes"], answer: 1,
    explain: "Controllers do the rest." }
]},
{ title: "Quiz 2 · Pods, ReplicaSets & Deployments",
  desc: "Pod lifecycle, ReplicaSets, rolling updates, labels",
  questions: [
  { q: "A Pod is…", options: ["Always one container", "One or more containers sharing network + storage", "A node"], answer: 1,
    explain: "Usually one app container + optional sidecars." },
  { q: "Pods are best treated as…", options: ["Pets (unique, healed)", "Cattle (disposable, replaced)", "Permanent"], answer: 1,
    explain: "Replaced, never healed in place." },
  { q: "You should point clients at…", options: ["A Pod IP", "A Service (stable IP/DNS)", "A node IP"], answer: 1,
    explain: "Pod IPs change on recreation." },
  { q: "A ReplicaSet ensures…", options: ["One Pod max", "N identical Pods exist (via a label selector)", "Rolling updates"], answer: 1,
    explain: "Recreates lost Pods." },
  { q: "For stateless apps you usually create a…", options: ["Bare Pod", "Deployment", "StatefulSet"], answer: 1,
    explain: "It manages ReplicaSets + rollouts." },
  { q: "A Deployment enables…", options: ["Only scaling", "Rolling updates and instant rollbacks", "Storage"], answer: 1,
    explain: "Via versioned ReplicaSets." },
  { q: "Each image change in a Deployment creates…", options: ["A new Pod only", "A new ReplicaSet", "A new Namespace"], answer: 1,
    explain: "Old one kept scaled to 0 for rollback." },
  { q: "Zero-downtime rolling update settings are…", options: ["maxUnavailable: 100%", "maxSurge: 1, maxUnavailable: 0", "replicas: 1"], answer: 1,
    explain: "Add new before removing old." },
  { q: "kubectl rollout undo deploy/web…", options: ["Deletes the app", "Rolls back to the previous ReplicaSet instantly", "Scales to zero"], answer: 1,
    explain: "The old ReplicaSet is scaled back up." },
  { q: "An init container…", options: ["Runs alongside the app forever", "Runs to completion BEFORE app containers start", "Is the main app"], answer: 1,
    explain: "Migrations, waiting on deps." },
  { q: "Containers in the same Pod share…", options: ["Nothing", "Network (localhost) and can share volumes", "Only CPU"], answer: 1,
    explain: "Tightly-coupled sidecars." },
  { q: "Labels and selectors provide…", options: ["Hardcoded references", "Loose coupling between controllers/Services and Pods", "Encryption"], answer: 1,
    explain: "matchLabels selects Pods." },
  { q: "If a Deployment's selector doesn't match its template labels…", options: ["It's fine", "It can't manage its Pods", "It runs faster"], answer: 1,
    explain: "Selector must match template labels." },
  { q: "State stored in a Pod's filesystem is…", options: ["Persistent", "Lost when the Pod is replaced", "Backed up"], answer: 1,
    explain: "Use volumes / StatefulSets / external DB." },
  { q: "kubectl set image deploy/web web=myapp:1.5.0…", options: ["Deletes the deploy", "Triggers a rolling update", "Rolls back"], answer: 1,
    explain: "Changes the desired image." },
  { q: "kubectl get pods -l app=web…", options: ["Gets all pods", "Filters Pods by label", "Deletes pods"], answer: 1,
    explain: "Label queries." },
  { q: "A sidecar container is…", options: ["The main app", "A helper container in the same Pod (proxy, log shipper)", "A node"], answer: 1,
    explain: "Shares the Pod's network/volumes." },
  { q: "Editing a live Pod's spec…", options: ["Persists forever", "Is lost when the Pod is recreated", "Updates the Deployment"], answer: 1,
    explain: "Edit the Deployment (desired state)." },
  { q: "kubectl rollout status deploy/web…", options: ["Rolls back", "Shows the rollout's progress", "Deletes it"], answer: 1,
    explain: "Watch the update proceed." },
  { q: "Readiness probes during a rollout ensure…", options: ["Faster builds", "Traffic only goes to Ready new Pods", "Rollback"], answer: 1,
    explain: "Gate the rollout on readiness." }
]},
{ title: "Quiz 3 · Services & Ingress",
  desc: "Service types, ClusterIP, Ingress controllers, DNS",
  questions: [
  { q: "A Service provides…", options: ["Persistent storage", "A stable virtual IP/DNS load-balancing to matching Pods", "A container runtime"], answer: 1,
    explain: "Service discovery for shifting Pods." },
  { q: "The default Service type is…", options: ["LoadBalancer", "ClusterIP (internal-only)", "NodePort"], answer: 1,
    explain: "Internal microservice traffic." },
  { q: "To expose a service via a cloud load balancer, use…", options: ["ClusterIP", "LoadBalancer", "Headless"], answer: 1,
    explain: "Provisions an external IP." },
  { q: "A Service finds its Pods via…", options: ["IP list", "A label selector (Ready Pods → endpoints)", "Node names"], answer: 1,
    explain: "Same loose coupling as ReplicaSets." },
  { q: "An Ingress operates at…", options: ["L4 (TCP)", "L7 (HTTP/HTTPS routing by host/path + TLS)", "The kernel"], answer: 1,
    explain: "One entry point for many Services." },
  { q: "An Ingress object alone…", options: ["Routes traffic", "Does nothing without an Ingress Controller", "Provisions a disk"], answer: 1,
    explain: "The controller enforces the rules." },
  { q: "A classic 'my Ingress isn't working' cause is…", options: ["Too many Pods", "No Ingress Controller installed", "Wrong Namespace name"], answer: 1,
    explain: "Install nginx/Traefik/cloud controller." },
  { q: "A headless Service (clusterIP: None)…", options: ["Load-balances via a VIP", "Returns Pod IPs directly via DNS", "Blocks traffic"], answer: 1,
    explain: "Used with StatefulSets." },
  { q: "An empty endpoints list usually means…", options: ["Healthy Service", "Selector mismatch or no Ready Pods", "Too much traffic"], answer: 1,
    explain: "503s follow." },
  { q: "In a Service, port vs targetPort:", options: ["Same thing", "port = Service port, targetPort = container port", "Both are node ports"], answer: 1,
    explain: "Map Service:80 → Pod:8080." },
  { q: "NodePort…", options: ["Is internal-only", "Opens a static port on every node to the Service", "Needs a cloud LB"], answer: 1,
    explain: "Basic external access." },
  { q: "CoreDNS gives Services…", options: ["Storage", "DNS names for discovery (my-svc.ns.svc.cluster.local)", "Nothing"], answer: 1,
    explain: "How microservices find each other." },
  { q: "A cost-effective way to expose many HTTP services is…", options: ["A LoadBalancer each", "One Ingress in front of ClusterIP Services", "NodePort each"], answer: 1,
    explain: "Fewer LBs, HTTP routing + TLS." },
  { q: "ExternalName Services…", options: ["Provision an LB", "Map to an external DNS name (CNAME)", "Expose Pods"], answer: 1,
    explain: "Alias an out-of-cluster dependency." },
  { q: "A Pod that isn't Ready is…", options: ["Still in endpoints", "Removed from Service endpoints (no traffic)", "Restarted"], answer: 1,
    explain: "Readiness gates traffic." },
  { q: "Traffic flow into a cloud web app is roughly…", options: ["Pod → Service → LB", "LB → Ingress Controller → ClusterIP Service → Pod", "etcd → Pod"], answer: 1,
    explain: "Edge to Pod." },
  { q: "kube-proxy makes…", options: ["Ingress rules", "ClusterIP virtual IPs route to Pod IPs", "Volumes"], answer: 1,
    explain: "Programs node routing." },
  { q: "Ingress can terminate…", options: ["Storage", "TLS (HTTPS) at the edge", "Pods"], answer: 1,
    explain: "Central cert management." },
  { q: "For internal-only microservices use…", options: ["LoadBalancer", "ClusterIP", "NodePort"], answer: 1,
    explain: "Don't over-expose." },
  { q: "The Gateway API is…", options: ["A database", "A more expressive successor to Ingress", "A CNI"], answer: 1,
    explain: "Newer L7 routing standard." }
]},
{ title: "Quiz 4 · ConfigMaps & Secrets",
  desc: "Externalizing config, env vs files, Secret security, reloads",
  questions: [
  { q: "ConfigMaps and Secrets exist to…", options: ["Store images", "Externalize config so one image runs everywhere", "Schedule Pods"], answer: 1,
    explain: "12-factor config at runtime." },
  { q: "ConfigMaps hold…", options: ["Sensitive credentials", "Non-sensitive configuration", "Container images"], answer: 1,
    explain: "Secrets are for sensitive data." },
  { q: "Kubernetes Secrets are…", options: ["Encrypted by default", "Only base64-ENCODED (not encrypted)", "Hashed"], answer: 1,
    explain: "A classic dangerous assumption." },
  { q: "To actually protect Secrets, enable…", options: ["Nothing", "Encryption-at-rest + RBAC + external managers", "More replicas"], answer: 1,
    explain: "Base64 is not security." },
  { q: "Both can be injected as…", options: ["Only env vars", "Env vars OR mounted files", "Only files"], answer: 1,
    explain: "env/envFrom or volumes." },
  { q: "For sensitive values, prefer…", options: ["Env vars", "Mounted files (less leak-prone)", "ARG"], answer: 1,
    explain: "Env leaks via inspect/child procs/dumps." },
  { q: "You updated a ConfigMap used as env vars but nothing changed because…", options: ["A bug", "Env is read once at start — Pods need a restart", "It's encrypted"], answer: 1,
    explain: "kubectl rollout restart." },
  { q: "envFrom on a ConfigMap…", options: ["Mounts a file", "Imports all keys as env vars", "Creates a volume"], answer: 1,
    explain: "Bulk env injection." },
  { q: "Committing raw Secrets to git is…", options: ["Fine", "A leak risk — use Sealed Secrets/SOPS/External Secrets", "Encrypted"], answer: 1,
    explain: "Repos get cloned/forked." },
  { q: "secretKeyRef is used to…", options: ["Mount a ConfigMap", "Inject a specific Secret key as an env var", "Delete a Secret"], answer: 1,
    explain: "One key → one env var." },
  { q: "Putting secrets in ConfigMaps…", options: ["Is best practice", "Loses access separation — use Secrets + RBAC", "Encrypts them"], answer: 1,
    explain: "Secrets get stricter handling." },
  { q: "Mounted config files (volume) update…", options: ["Never", "Eventually, but the app must reload them", "Instantly restart the Pod"], answer: 1,
    explain: "Env-based needs a restart." },
  { q: "For production secrets, source from…", options: ["The Dockerfile", "A secrets manager (Vault/cloud) via External Secrets/CSI", "Git plaintext"], answer: 1,
    explain: "Rotation, audit, least privilege." },
  { q: "Baking config into the image causes…", options: ["Reproducibility", "One image per environment (drift)", "Nothing"], answer: 1,
    explain: "Inject config at runtime instead." },
  { q: "Huge (>1MB) blobs in ConfigMaps…", options: ["Are recommended", "Hit etcd limits / bloat", "Encrypt automatically"], answer: 1,
    explain: "Use volumes/object storage." },
  { q: "A Secret's type Opaque means…", options: ["Encrypted", "Arbitrary user-defined key/value data", "Immutable"], answer: 1,
    explain: "The generic secret type." },
  { q: "To apply a ConfigMap change to running Pods…", options: ["Wait", "kubectl rollout restart deploy/...", "Delete the cluster"], answer: 1,
    explain: "Recreate Pods to re-read env." },
  { q: "Tools like Reloader…", options: ["Encrypt secrets", "Auto-roll Pods when their config changes", "Scale nodes"], answer: 1,
    explain: "Or use a config-hash annotation." },
  { q: "Base64-decoding a Secret value…", options: ["Fails", "Reveals the plaintext (proving it's not encrypted)", "Needs a key"], answer: 1,
    explain: "Encoding, not encryption." },
  { q: "envFrom/secretKeyRef and volume mounts are the two ways to…", options: ["Schedule Pods", "Consume ConfigMaps/Secrets", "Expose Services"], answer: 1,
    explain: "Env vars or files." }
]},
{ title: "Quiz 5 · Probes, Resources & QoS",
  desc: "Liveness/readiness/startup, requests vs limits, QoS classes",
  questions: [
  { q: "A livenessProbe failure causes…", options: ["Removal from endpoints", "A container RESTART", "Nothing"], answer: 1,
    explain: "For wedged/deadlocked processes." },
  { q: "A readinessProbe failure causes…", options: ["A restart", "Removal from Service endpoints (no traffic)", "Node drain"], answer: 1,
    explain: "Gate traffic without restarting." },
  { q: "A startupProbe is for…", options: ["Fast apps", "Slow-starting apps (holds off liveness/readiness)", "Storage"], answer: 1,
    explain: "Avoid premature kills at boot." },
  { q: "Putting a downstream-dependency check in liveness…", options: ["Is best practice", "Causes restart loops when the dependency blips", "Speeds startup"], answer: 1,
    explain: "Dependency checks belong in readiness." },
  { q: "A resource REQUEST is used for…", options: ["Runtime cap", "Scheduling (guaranteed reservation)", "Nothing"], answer: 1,
    explain: "Scheduler places on a node with enough free." },
  { q: "A resource LIMIT is…", options: ["A suggestion", "A hard runtime ceiling", "For scheduling only"], answer: 1,
    explain: "Enforced at runtime." },
  { q: "Exceeding the MEMORY limit…", options: ["Throttles", "OOM-kills the container (exit 137)", "Is ignored"], answer: 1,
    explain: "Then it restarts." },
  { q: "Exceeding the CPU limit…", options: ["OOM-kills", "Throttles (slows) the container", "Evicts it"], answer: 1,
    explain: "CPU is compressible; memory isn't." },
  { q: "QoS Guaranteed means…", options: ["No limits set", "requests == limits for CPU & memory", "Only CPU set"], answer: 1,
    explain: "Evicted last (most protected)." },
  { q: "QoS BestEffort Pods…", options: ["Are protected", "Have no requests/limits — evicted first", "Get more CPU"], answer: 1,
    explain: "Least protected under pressure." },
  { q: "Under memory pressure the kubelet…", options: ["Adds nodes", "Evicts Pods starting with BestEffort", "Reboots"], answer: 1,
    explain: "QoS decides eviction order." },
  { q: "No resource requests leads to…", options: ["Better packing", "Overcommitted nodes, OOMs, noisy neighbors", "Faster Pods"], answer: 1,
    explain: "Scheduler can't reason about capacity." },
  { q: "1000m CPU equals…", options: ["1 millicore", "1 full CPU core", "1 GB"], answer: 1,
    explain: "m = millicores." },
  { q: "1 core, no memory limit, leaky app →", options: ["Safe", "One Pod can consume the node, harming neighbors", "Auto-fixed"], answer: 1,
    explain: "Always consider memory limits." },
  { q: "A too-low CPU limit causes…", options: ["Crashes", "Silent throttling / latency spikes (no crash)", "OOM"], answer: 1,
    explain: "Hard to spot without metrics." },
  { q: "QoS Burstable is…", options: ["No limits", "requests < limits (or partial)", "requests == limits"], answer: 1,
    explain: "Middle eviction priority." },
  { q: "A readiness probe also…", options: ["Deletes Pods", "Gates rolling updates (new Pods get traffic when Ready)", "Adds nodes"], answer: 1,
    explain: "Safer rollouts." },
  { q: "Right-sizing requests/limits should be based on…", options: ["Guesses forever", "Real usage metrics (ongoing discipline)", "Max possible"], answer: 1,
    explain: "Observe and tune." },
  { q: "initialDelaySeconds on a probe…", options: ["Delays the Pod", "Waits before the first probe check", "Restarts the node"], answer: 1,
    explain: "Give the app time to start." },
  { q: "Most flapping/OOM/latency incidents stem from…", options: ["Bad DNS", "Misconfigured probes and resources", "Too few Services"], answer: 1,
    explain: "Why this lesson is heavily tested." }
]}
);
