// Kubernetes quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Autoscaling (HPA/VPA/Cluster)",
  desc: "Horizontal & vertical Pod autoscaling and cluster autoscaling",
  questions: [
  { q: "The HorizontalPodAutoscaler scales…", options: ["Node CPU", "The number of Pod replicas", "Container memory limits"], answer: 1,
    explain: "HPA adds/removes replicas based on observed metrics." },
  { q: "HPA needs which component to read CPU/memory?", options: ["etcd", "metrics-server", "kube-proxy"], answer: 1,
    explain: "metrics-server supplies resource metrics via the metrics API." },
  { q: "HPA on CPU requires Pods to define…", options: ["A memory limit", "CPU requests", "A liveness probe"], answer: 1,
    explain: "Utilization is measured against the CPU request." },
  { q: "The Vertical Pod Autoscaler adjusts…", options: ["Replica count", "Pod CPU/memory requests & limits", "Node count"], answer: 1,
    explain: "VPA right-sizes the resources of individual Pods." },
  { q: "Why shouldn't HPA and VPA both act on CPU for the same workload?", options: ["It's illegal", "They conflict — one scales out while the other resizes", "VPA is faster"], answer: 1,
    explain: "Combining them on the same metric causes fighting; use different signals." },
  { q: "The Cluster Autoscaler scales…", options: ["Pod replicas", "The number of nodes in the cluster", "Container images"], answer: 1,
    explain: "It adds nodes when Pods can't schedule, removes underused ones." },
  { q: "What triggers the Cluster Autoscaler to add a node?", options: ["High CPU", "Pods stuck Pending for lack of resources", "A cron"], answer: 1,
    explain: "Unschedulable Pods signal the need for more node capacity." },
  { q: "HPA can scale on custom/external metrics via…", options: ["Only CPU", "The custom.metrics / external.metrics APIs (e.g., Prometheus adapter)", "kubectl top"], answer: 1,
    explain: "Adapters expose app metrics (QPS, queue depth) to HPA." },
  { q: "A good target for CPU-based HPA utilization is often…", options: ["100%", "Around 50–70% so there's headroom", "5%"], answer: 1,
    explain: "Leaves burst headroom while still being efficient." },
  { q: "HPA's stabilization window exists to…", options: ["Speed scaling", "Prevent flapping (rapid scale up/down)", "Save etcd"], answer: 1,
    explain: "Dampens oscillation from noisy metrics." },
  { q: "If Pods have no CPU requests, CPU-based HPA…", options: ["Works fine", "Can't compute utilization — won't scale properly", "Scales to zero"], answer: 1,
    explain: "Utilization is relative to the request; without it there's no baseline." },
  { q: "Scaling a Deployment to more replicas helps only if the app is…", options: ["Stateful & singleton", "Horizontally scalable / stateless", "Single-threaded"], answer: 1,
    explain: "Adding replicas helps workloads that parallelize across Pods." },
  { q: "The Cluster Autoscaler removing a node first…", options: ["Kills Pods instantly", "Drains/evicts its Pods so they reschedule", "Ignores Pods"], answer: 1,
    explain: "It respects graceful eviction (and PDBs) before removing capacity." },
  { q: "KEDA is used for…", options: ["Networking", "Event-driven autoscaling (incl. scale-to-zero) on queue/event metrics", "Storage"], answer: 1,
    explain: "KEDA scales on external event sources and can scale to zero." },
  { q: "HPA min/maxReplicas define…", options: ["CPU limits", "The bounds within which HPA may scale", "Node counts"], answer: 1,
    explain: "Guardrails so autoscaling stays in a safe range." },
  { q: "A PodDisruptionBudget interacts with autoscaling/drains by…", options: ["Speeding scale-down", "Limiting how many replicas can be voluntarily disrupted at once", "Setting CPU"], answer: 1,
    explain: "PDBs protect availability during evictions/node scale-down." },
  { q: "VPA in 'Auto' mode may…", options: ["Never restart Pods", "Recreate Pods to apply new resource values", "Add nodes"], answer: 1,
    explain: "Applying new requests generally requires Pod recreation." },
  { q: "Scaling on queue length (e.g., messages pending) is best done with…", options: ["CPU HPA", "Custom/external metrics HPA or KEDA", "VPA"], answer: 1,
    explain: "The meaningful signal is the backlog, not CPU." },
  { q: "The three autoscalers (HPA/VPA/Cluster) address, respectively…", options: ["All the same thing", "How many Pods / how big each Pod / how many nodes", "Networking layers"], answer: 1,
    explain: "Replicas, Pod size, and node capacity are the three dimensions." },
  { q: "Autoscaling reacts to load with some…", options: ["Zero latency", "Delay (metrics + scheduling + startup) — provision headroom", "Instant node boot"], answer: 1,
    explain: "There's lag; keep buffer for spikes." } ] },

{ title: "Quiz 7 · StatefulSets & Storage",
  desc: "PV/PVC, StorageClasses, StatefulSets, headless Services",
  questions: [
  { q: "A PersistentVolumeClaim (PVC) is…", options: ["Actual storage", "A user's request for storage that binds to a PV", "A Pod"], answer: 1,
    explain: "The PVC is the claim; the PV is the actual volume." },
  { q: "Dynamic provisioning is driven by…", options: ["A manual PV", "A StorageClass that creates PVs on demand", "The kubelet"], answer: 1,
    explain: "The StorageClass's provisioner creates a PV to satisfy a PVC." },
  { q: "StatefulSets give each Pod…", options: ["A random name", "A stable, ordinal identity (pod-0, pod-1) and its own PVC", "Shared storage"], answer: 1,
    explain: "Stable network ID and per-replica persistent storage." },
  { q: "StatefulSets are typically fronted by a…", options: ["LoadBalancer", "Headless Service (clusterIP: None) for stable DNS per Pod", "NodePort"], answer: 1,
    explain: "Headless Service gives each Pod a stable DNS record." },
  { q: "Deleting a StatefulSet by default…", options: ["Deletes the PVCs", "Leaves the PVCs (data) unless you remove them", "Deletes nodes"], answer: 1,
    explain: "Persistent data is retained for safety." },
  { q: "The accessMode ReadWriteOnce means…", options: ["Many nodes read-write", "Mounted read-write by a single node", "Read only"], answer: 1,
    explain: "RWO = one node RW; RWX = many nodes RW (needs supporting storage)." },
  { q: "The reclaimPolicy 'Retain' means when the PVC is deleted…", options: ["The volume is wiped", "The PV/data is kept for manual handling", "Nothing is stored"], answer: 1,
    explain: "Retain preserves data; Delete removes the underlying volume." },
  { q: "StatefulSet Pods are created/scaled…", options: ["All at once randomly", "In order (0,1,2…) and terminated in reverse", "Never scaled"], answer: 1,
    explain: "Ordered, graceful scaling is part of the guarantee." },
  { q: "volumeClaimTemplates in a StatefulSet produce…", options: ["One shared PVC", "A separate PVC per replica", "No storage"], answer: 1,
    explain: "Each ordinal Pod gets its own persistent volume." },
  { q: "A Deployment is a poor fit for a database because…", options: ["It's too fast", "Pods are interchangeable with no stable identity/storage", "It can't run containers"], answer: 1,
    explain: "Stateful data needs stable identity — use a StatefulSet." },
  { q: "An emptyDir volume's lifetime is…", options: ["Forever", "Tied to the Pod — gone when the Pod is deleted", "The cluster's"], answer: 1,
    explain: "emptyDir is ephemeral scratch space, not persistent." },
  { q: "A PV and PVC bind based on…", options: ["Pod name", "Matching capacity, accessModes, and StorageClass", "Namespace only"], answer: 1,
    explain: "The claim binds to a PV that satisfies its requirements." },
  { q: "'ReadWriteMany' typically requires…", options: ["Any disk", "A networked/shared filesystem (NFS, CephFS, etc.)", "Local SSD"], answer: 1,
    explain: "Block volumes are usually RWO; RWX needs shared storage." },
  { q: "The CSI (Container Storage Interface) is…", options: ["A network plugin", "The standard for storage drivers to integrate with K8s", "A scheduler"], answer: 1,
    explain: "CSI decouples storage vendors from the core." },
  { q: "A stable per-Pod DNS name for web-0 in a headless svc looks like…", options: ["web-0 only", "web-0.<svc>.<ns>.svc.cluster.local", "an IP only"], answer: 1,
    explain: "Ordinal hostname under the headless Service domain." },
  { q: "To safely scale a StatefulSet DB down you should…", options: ["Delete Pods at random", "Scale gracefully in reverse ordinal order, respecting quorum", "Delete the PVCs first"], answer: 1,
    explain: "Ordered scale-down protects data and quorum." },
  { q: "A PVC stuck 'Pending' often means…", options: ["The Pod crashed", "No matching PV / no default StorageClass to provision one", "etcd is down"], answer: 1,
    explain: "Nothing can satisfy the claim; check StorageClass/provisioner." },
  { q: "hostPath volumes are discouraged in production because…", options: ["Too slow", "They tie a Pod to a specific node's filesystem (not portable)", "They're encrypted"], answer: 1,
    explain: "Node-local paths break portability and HA." },
  { q: "The main reason StatefulSets exist is to provide…", options: ["Faster Pods", "Stable identity + stable storage + ordered operations", "Cheaper storage"], answer: 1,
    explain: "The three guarantees stateful apps need." },
  { q: "Backups of stateful data should be handled by…", options: ["Kubernetes automatically", "Explicit backup tooling (e.g., Velero) / DB-native backups", "The scheduler"], answer: 1,
    explain: "K8s persists volumes but doesn't back them up for you." } ] },

{ title: "Quiz 8 · Helm & Packaging",
  desc: "Charts, values, templating, releases, upgrades",
  questions: [
  { q: "Helm is best described as…", options: ["A container runtime", "The package manager for Kubernetes", "A CNI plugin"], answer: 1,
    explain: "It packages, templates, versions, and deploys K8s apps." },
  { q: "A Helm chart is…", options: ["A single YAML", "A bundle of templated manifests + default values", "A container image"], answer: 1,
    explain: "Charts template manifests parameterized by values." },
  { q: "values.yaml provides…", options: ["The runtime", "Default configuration substituted into templates", "The cluster state"], answer: 1,
    explain: "Values parameterize the templates; overridable at install." },
  { q: "A deployed instance of a chart is called a…", options: ["Pod", "Release", "Namespace"], answer: 1,
    explain: "Each install/upgrade creates/updates a named release." },
  { q: "Override a value at install with…", options: ["kubectl edit", "--set key=value or -f myvalues.yaml", "a new image"], answer: 1,
    explain: "--set and custom values files override defaults." },
  { q: "helm upgrade does…", options: ["Deletes everything", "Applies changes to an existing release (new revision)", "Only prints"], answer: 1,
    explain: "It reconciles the release to the new chart/values." },
  { q: "helm rollback lets you…", options: ["Delete a namespace", "Revert a release to a previous revision", "Scale nodes"], answer: 1,
    explain: "Helm tracks revisions so you can roll back." },
  { q: "Helm templating uses…", options: ["Python", "Go templates ({{ .Values.x }})", "Jsonnet only"], answer: 1,
    explain: "Go template syntax with the values/release context." },
  { q: "The _helpers.tpl file usually holds…", options: ["Secrets", "Reusable named template snippets (e.g., labels, names)", "The image"], answer: 1,
    explain: "Common template helpers included across manifests." },
  { q: "Chart dependencies are declared in…", options: ["values.yaml", "Chart.yaml (dependencies) and vendored in charts/", "a Pod spec"], answer: 1,
    explain: "Subcharts are listed as dependencies and pulled in." },
  { q: "helm template renders manifests…", options: ["And applies them", "Locally to YAML without installing (great for CI/diff)", "To etcd"], answer: 1,
    explain: "Renders client-side so you can inspect/gitops the output." },
  { q: "Chart.yaml's version vs appVersion: appVersion is…", options: ["The chart's version", "The version of the app the chart deploys", "The K8s version"], answer: 1,
    explain: "Chart version = packaging; appVersion = the application." },
  { q: "A common way to keep secrets out of plaintext values is…", options: ["Commit them", "helm-secrets/SOPS or external secret managers", "Base64 in Git"], answer: 1,
    explain: "Encrypt secrets rather than committing them plainly." },
  { q: "Reasons to use Helm over raw kubectl apply include…", options: ["Nothing", "Templating, reuse across envs, versioned releases, easy rollback", "Faster Pods"], answer: 1,
    explain: "Parameterization and release lifecycle management." },
  { q: "In GitOps, Helm charts are often…", options: ["Applied by CI creds", "Rendered/managed by the agent (Argo/Flux) from Git", "Not usable"], answer: 1,
    explain: "Argo CD/Flux natively support Helm-based sources." },
  { q: "A Helm 'hook' lets you…", options: ["Nothing", "Run jobs at lifecycle points (pre-install, post-upgrade)", "Scale nodes"], answer: 1,
    explain: "Hooks order actions like migrations around release events." },
  { q: "Kustomize differs from Helm by…", options: ["Being a runtime", "Overlaying/patching base manifests without templating language", "Requiring Go"], answer: 1,
    explain: "Kustomize patches YAML; Helm templates+packages." },
  { q: "helm list shows…", options: ["Pods", "Installed releases and their revisions/status", "Nodes"], answer: 1,
    explain: "Release inventory in the namespace/cluster." },
  { q: "Pinning a chart/app version in Git matters because…", options: ["It doesn't", "Reproducible, auditable deploys (no surprise 'latest')", "It's faster"], answer: 1,
    explain: "Deterministic deployments; avoid drift from moving tags." },
  { q: "A values override precedence (highest) is…", options: ["Chart defaults", "--set > -f file > chart defaults", "Random"], answer: 1,
    explain: "Explicit --set beats files, which beat chart defaults." } ] },

{ title: "Quiz 9 · Security, RBAC & Scheduling",
  desc: "RBAC, ServiceAccounts, NetworkPolicies, affinity, taints",
  questions: [
  { q: "RBAC controls…", options: ["Pod CPU", "Who (subjects) can do what (verbs) on which resources", "Storage"], answer: 1,
    explain: "Role-based access control authorizes API actions." },
  { q: "A Role vs ClusterRole differs by…", options: ["Verbs", "Scope: Role is namespaced, ClusterRole is cluster-wide", "Speed"], answer: 1,
    explain: "Namespaced vs cluster-scoped permissions." },
  { q: "A RoleBinding does…", options: ["Defines permissions", "Grants a Role's permissions to subjects (users/SAs/groups)", "Runs Pods"], answer: 1,
    explain: "Binding connects a Role to who gets it." },
  { q: "Pods authenticate to the API using a…", options: ["Password", "ServiceAccount token", "SSH key"], answer: 1,
    explain: "Each Pod runs as a ServiceAccount with a mounted token." },
  { q: "The RBAC best practice is…", options: ["cluster-admin for all", "Least privilege — grant only needed verbs/resources", "No RBAC"], answer: 1,
    explain: "Minimize blast radius of any compromised credential." },
  { q: "By default, Pods in a cluster can talk to each other…", options: ["Never", "Freely — the network is flat unless restricted", "Only same node"], answer: 1,
    explain: "No isolation until a NetworkPolicy restricts traffic." },
  { q: "A NetworkPolicy is…", options: ["Ignored always", "A rule restricting ingress/egress by Pod/namespace selectors", "A Service"], answer: 1,
    explain: "It firewalls Pod traffic (needs a CNI that enforces it)." },
  { q: "NetworkPolicies require…", options: ["Nothing", "A CNI plugin that enforces them (Calico, Cilium)", "A LoadBalancer"], answer: 1,
    explain: "The policy is inert without an enforcing CNI." },
  { q: "A default-deny NetworkPolicy…", options: ["Allows all", "Blocks all traffic to selected Pods until explicitly allowed", "Deletes Pods"], answer: 1,
    explain: "Start closed, then whitelist required flows." },
  { q: "Node affinity ATTRACTS Pods to nodes; taints…", options: ["Also attract", "REPEL Pods unless they have a matching toleration", "Delete nodes"], answer: 1,
    explain: "Affinity pulls; taints push away." },
  { q: "requiredDuringScheduling affinity that can't be met causes…", options: ["A crash", "The Pod to stay Pending", "A new node"], answer: 1,
    explain: "Hard requirement unmet = unschedulable." },
  { q: "Spreading replicas across zones for HA is best via…", options: ["Same node", "Pod anti-affinity or topologySpreadConstraints", "More CPU"], answer: 1,
    explain: "Spread across failure domains, don't stack." },
  { q: "The taint effect that also EVICTS running Pods is…", options: ["NoSchedule", "NoExecute", "PreferNoSchedule"], answer: 1,
    explain: "NoExecute blocks scheduling and evicts non-tolerating Pods." },
  { q: "To reserve GPU nodes for GPU workloads you…", options: ["Do nothing", "Taint the nodes and add matching tolerations (+ affinity) to GPU Pods", "Use more replicas"], answer: 1,
    explain: "Taints keep others off; tolerations/affinity place the right Pods." },
  { q: "A securityContext with runAsNonRoot: true…", options: ["Speeds Pods", "Prevents the container from running as root", "Adds storage"], answer: 1,
    explain: "Reduces impact of a container compromise." },
  { q: "Pod Security Admission enforces…", options: ["Networking", "Baseline/restricted security standards on namespaces", "Autoscaling"], answer: 1,
    explain: "Replaces PodSecurityPolicy for pod-level hardening." },
  { q: "Secrets in etcd should be…", options: ["Plaintext", "Encrypted at rest (encryption provider) + RBAC-restricted", "Public"], answer: 1,
    explain: "Enable encryption-at-rest and limit who can read Secrets." },
  { q: "'IgnoredDuringExecution' in affinity means…", options: ["Rules never apply", "Rules affect scheduling only, not already-running Pods", "Pods restart"], answer: 1,
    explain: "Label changes after placement don't move running Pods." },
  { q: "Disabling the default SA token mount (automountServiceAccountToken: false) helps…", options: ["Speed", "Reduce credential exposure for Pods that don't call the API", "Storage"], answer: 1,
    explain: "Don't hand out API tokens Pods don't need." },
  { q: "The overall security posture goal is…", options: ["Convenience", "Defense in depth: least-privilege RBAC, network policy, hardened Pods, encrypted secrets", "One firewall"], answer: 1,
    explain: "Layered controls, each limiting blast radius." } ] },

{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Cumulative — sampling every Kubernetes topic",
  questions: [
  { q: "etcd's role is…", options: ["Run containers", "The cluster's consistent key-value source of truth", "Load balance"], answer: 1,
    explain: "All state lives in etcd, written only via the API server." },
  { q: "A Deployment manages Pods via…", options: ["Directly", "A ReplicaSet it controls", "kube-proxy"], answer: 1,
    explain: "Deployment → ReplicaSet → Pods; enables rollouts." },
  { q: "A ClusterIP Service is reachable…", options: ["From the internet", "Only inside the cluster", "Via SSH"], answer: 1,
    explain: "Internal virtual IP; use Ingress/LB for external access." },
  { q: "A readiness probe failing causes the Pod to…", options: ["Restart", "Be removed from Service endpoints (no traffic)", "Be deleted"], answer: 1,
    explain: "Readiness gates traffic; liveness gates restarts." },
  { q: "OOMKilled (exit 137) means…", options: ["Bad image", "The container exceeded its memory limit", "No endpoints"], answer: 1,
    explain: "Kernel killed it for breaching the memory limit." },
  { q: "HPA scales replicas and needs…", options: ["Nothing", "metrics-server and CPU requests defined", "A StatefulSet"], answer: 1,
    explain: "Utilization is computed from metrics vs requests." },
  { q: "A database in Kubernetes should use a…", options: ["Deployment", "StatefulSet with per-replica PVCs", "DaemonSet"], answer: 1,
    explain: "Stable identity + persistent per-Pod storage." },
  { q: "Dynamic storage provisioning uses a…", options: ["Manual PV", "StorageClass", "ConfigMap"], answer: 1,
    explain: "The provisioner creates PVs to satisfy PVCs." },
  { q: "Helm packages apps as…", options: ["Images", "Charts (templated manifests + values)", "Namespaces"], answer: 1,
    explain: "Charts template and version K8s apps." },
  { q: "GitOps makes the source of truth…", options: ["The cluster", "A Git repository, reconciled by an in-cluster agent", "CI logs"], answer: 1,
    explain: "Argo CD/Flux pull desired state from Git." },
  { q: "A default-deny NetworkPolicy…", options: ["Allows all", "Blocks traffic until explicitly allowed", "Needs no CNI"], answer: 1,
    explain: "Start closed; whitelist required flows (enforced by CNI)." },
  { q: "RBAC least privilege means…", options: ["cluster-admin everywhere", "Grant only the verbs/resources actually needed", "No auth"], answer: 1,
    explain: "Limit the blast radius of any credential." },
  { q: "A Pod stuck Pending usually indicates…", options: ["A crash loop", "It can't be scheduled (resources/taints/affinity/PV)", "OOM"], answer: 1,
    explain: "describe events reveal why it won't schedule." },
  { q: "ImagePullBackOff points to…", options: ["A memory leak", "A bad tag or missing registry auth", "A readiness probe"], answer: 1,
    explain: "The kubelet can't pull the image." },
  { q: "For a 503 with empty endpoints, first check…", options: ["Node CPU", "Service selector match and Pod readiness", "etcd"], answer: 1,
    explain: "Selector mismatch or failing readiness = no endpoints." },
  { q: "NoExecute taints differ from NoSchedule by…", options: ["Being softer", "Also evicting already-running non-tolerating Pods", "Adding nodes"], answer: 1,
    explain: "NoExecute blocks AND evicts." },
  { q: "An Ingress provides…", options: ["Pod storage", "L7 HTTP routing (host/path) to Services", "Node scaling"], answer: 1,
    explain: "Ingress + controller route external HTTP/S to Services." },
  { q: "A ConfigMap holds ___ and a Secret holds ___", options: ["secrets / config", "non-sensitive config / sensitive data (base64, RBAC-limited)", "Pods / nodes"], answer: 1,
    explain: "Same shape; Secrets add access control and encryption-at-rest." },
  { q: "The reconciliation loop is why Kubernetes…", options: ["Is imperative", "Self-heals — continuously converging actual to desired state", "Needs Docker"], answer: 1,
    explain: "Controllers observe→compare→act, continuously." },
  { q: "In an incident, you should mitigate (rollback/scale/cordon) …", options: ["After full root-cause", "BEFORE deep root-causing, to restore service fast", "Never"], answer: 1,
    explain: "Stabilize first, investigate after." } ] }
);
