// kubernetes quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · StatefulSets, Jobs & CronJobs",
  desc: "Stable identity, ordered rollouts, PVC retention, retry semantics and the 100-miss trap",
  questions: [
  { q: "A StatefulSet gives you three guarantees a Deployment cannot:", options: ["Automatic backups, failover and replication", "Stable ordinal names, per-pod storage reattached by ordinal, and ordered operations", "Faster scheduling, better spread, cheaper storage"], answer: 1,
    explain: "Delete db-1 and it returns as db-1 — new node, new IP, same PVC and same data. That triple is the entire point of the object." },
  { q: "spec.serviceName on a StatefulSet must reference…", options: ["A headless Service — it is what creates the per-pod DNS records", "The Deployment's Service", "Any ClusterIP Service"], answer: 0,
    explain: "Without it there are no db-0.svc.ns.svc.cluster.local records, so clustered software has no stable way to name its peers." },
  { q: "Clustered databases deadlock on first boot without…", options: ["An init container", "A PodDisruptionBudget", "publishNotReadyAddresses: true on the peer Service"], answer: 2,
    explain: "Readiness needs peers and peer discovery needs readiness. Measured as three pods stuck at 0/1 permanently until the field was set." },
  { q: "With the default podManagementPolicy, a StatefulSet pod stuck in CrashLoopBackOff…", options: ["Blocks every lower ordinal from being updated — indefinitely", "Triggers an automatic rollback", "Is skipped"], answer: 0,
    explain: "Verified unchanged after 15 minutes. It protects the cluster, but a broken ordinal 0 means nothing above it ever starts." },
  { q: "podManagementPolicy: Parallel is appropriate for…", options: ["Single-replica workloads", "Any database", "Software whose members self-organise, such as Cassandra or Elasticsearch"], answer: 2,
    explain: "It keeps identity and storage stable while removing sequencing. The field is immutable — changing it needs --cascade=orphan and recreation." },
  { q: "updateStrategy.rollingUpdate.partition: 2 means…", options: ["Wait two minutes between pods", "Update two pods at a time", "Only ordinals >= 2 are updated — a canary by ordinal"], answer: 2,
    explain: "Deployments have no equivalent. Lowering the partition promotes; raising it and deleting the canary aborts." },
  { q: "Scaling a StatefulSet from 5 to 2 replicas deletes the three PVCs…", options: ["Immediately", "No — they are kept, bound, unused and still billed", "After 30 days"], answer: 1,
    explain: "Deleting the StatefulSet keeps them too. persistentVolumeClaimRetentionPolicy changes it, at the cost of a hasty scale destroying data." },
  { q: "kubectl delete pod --force --grace-period=0 on a StatefulSet pod is dangerous because…", options: ["It bypasses the PDB", "It corrupts the PVC", "It removes the object with no confirmation the process stopped — producing two pods with one identity"], answer: 2,
    explain: "Demonstrated with two db-0 pods existing while the original was still writing. Delete the Node object or use the out-of-service taint instead." },
  { q: "A StatefulSet by itself provides…", options: ["Identity, storage and ordering — no leader concept, no failover, no backup", "Automatic replication", "Failover and backups"], answer: 0,
    explain: "Everything that makes a database production-ready lives in an operator or the engine. A bare single-replica StatefulSet is a single point of failure with good name management." },
  { q: "In a Job, restartPolicy: Never versus OnFailure differs in that Never…", options: ["Does not retry at all", "Creates a NEW POD per attempt, preserving each attempt's logs", "Ignores backoffLimit"], answer: 1,
    explain: "OnFailure restarts the container in one pod, overwriting logs — and container restarts do not consume the backoff budget." },
  { q: "backoffLimit counts…", options: ["POD failures", "Container restarts", "Seconds of delay"], answer: 0,
    explain: "With OnFailure a container can crash-loop far longer than backoffLimit suggests, because the pod itself has not failed." },
  { q: "Job retries are delayed on a schedule of…", options: ["10s, 20s, 40s… doubling to a 6-minute cap", "No delay", "A fixed 30 seconds"], answer: 0,
    explain: "A Job with the default backoffLimit: 6 takes over ten minutes to report failure, which makes failure alerting inherently delayed." },
  { q: "The only mechanism that stops a hung Job is…", options: ["activeDeadlineSeconds", "backoffLimit", "ttlSecondsAfterFinished"], answer: 0,
    explain: "It is a wall-clock cap that overrides backoffLimit. Without it a Job can stay Active for days holding resources." },
  { q: "completionMode: Indexed gives each pod…", options: ["A separate PVC", "A stable index in its name and environment, so work partitions with no coordinator", "A random suffix"], answer: 1,
    explain: "With completions unset instead, the Job behaves as a work queue: it succeeds when any pod exits 0 and none remain." },
  { q: "podFailurePolicy with action Ignore on DisruptionTarget is what makes…", options: ["Jobs run faster", "Long batch work viable on spot capacity — preemptions stop consuming the retry budget", "Jobs idempotent"], answer: 1,
    explain: "Measured: six preemptions with failed=0, where the default failed after four. FailJob on a known-fatal exit code stops pointless retries." },
  { q: "A CronJob that misses more than 100 scheduled start times…", options: ["Catches up on all of them", "Skips to the next schedule", "Stops permanently, logging 'too many missed start times'"], answer: 2,
    explain: "That is 100 minutes at */1 and about 8 hours at */5. startingDeadlineSeconds bounds the look-back window and fixes it instantly." },
  { q: "concurrencyPolicy: Replace on a job that runs longer than its interval results in…", options: ["Skipped occurrences", "Every long run being killed, so only the final one ever completes", "Overlapping runs"], answer: 1,
    explain: "Measured: 5 runs started, 1 finished. Forbid at least finishes what it starts, and emits JobAlreadyActive events when it skips." },
  { q: "Without spec.timeZone, a CronJob schedule runs in…", options: ["UTC — the controller's zone — so it drifts with DST twice a year", "The submitter's zone", "The cluster's local zone"], answer: 0,
    explain: "This is why 'the 3am job ran at 4am' appears every spring and autumn." },
  { q: "Kubernetes guarantees a CronJob runs…", options: ["At most once", "Exactly once per schedule", "At LEAST once — node failure, overlap and controller restarts all duplicate work"], answer: 2,
    explain: "Idempotency must live in the workload: a dedup key set in the same transaction as the effect, or an advisory lock." },
  { q: "For CronJobs you should alert on…", options: ["TIME SINCE LAST SUCCESS — four of the five common failure modes are silent", "Job failures", "Pod restarts"], answer: 0,
    explain: "The 100-miss trap, an accidental suspend, a broken schedule and a Forbid blocked by a stuck job all produce silence, not errors." },
]},
{ title: "Quiz 7 · Probes, Requests, Limits & QoS",
  desc: "The probe remedy rule, startup probes, QoS eviction order and the CPU limit trade-off",
  questions: [
  { q: "The rule that prevents most probe-caused outages is…", options: ["A probe may only test what its own remedy can fix", "Always use httpGet", "Set failureThreshold to 1"], answer: 0,
    explain: "Restarting a container cannot repair someone else's database, so a liveness probe must never consult one." },
  { q: "A liveness probe that checks the database causes…", options: ["Faster failure detection", "Nothing unusual", "Correlated restarts of every replica during a dependency blip"], answer: 2,
    explain: "Measured: an 8-second outage restarted 4 of 4 replicas and produced 137 failures on endpoints that never touch the database." },
  { q: "Readiness probe failure results in…", options: ["A container restart", "Removal from Service endpoints — reversible, restart count unchanged", "Pod deletion"], answer: 1,
    explain: "Liveness restarts (irreversible, restart count +1); readiness sheds traffic (reversible). Different remedies, different rules." },
  { q: "timeoutSeconds defaults to…", options: ["10 seconds", "1 second — shorter than a JVM GC pause or a throttled container's response", "30 seconds"], answer: 1,
    explain: "Measured: a 2-second response restarted a healthy server twice in 30 s, and zero times at timeout: 4." },
  { q: "An app that takes 90 seconds to boot, with default liveness settings…", options: ["Is marked unready but keeps running", "Crash-loops forever, killed at ~30 s every time", "Starts normally"], answer: 1,
    explain: "initialDelaySeconds fixes the boot and permanently blinds detection; a startup probe gives both a generous boot budget and fast detection afterwards." },
  { q: "While a startup probe is running…", options: ["Liveness and readiness also run", "Liveness and readiness are suppressed entirely", "The pod is not scheduled"], answer: 1,
    explain: "It stops at the first success, so a generous failureThreshold × periodSeconds budget costs nothing on a fast boot." },
  { q: "A TCP probe on a queue worker's metrics port…", options: ["Detects a wedged consumer loop", "Is the recommended approach", "Never detects it — the port answers while the loop is dead"], answer: 2,
    explain: "Measured: the consumer was dead for two minutes with 0 restarts. A heartbeat-file mtime check caught the same wedge in 48 s." },
  { q: "Requests and limits are enforced by different mechanisms: requests set…", options: ["cpu.weight (a share under contention) and the scheduling reservation", "memory.max", "The OOM score only"], answer: 0,
    explain: "Limits set cpu.max (throttling) and memory.max (an OOM kill). The scheduler never looks at limits." },
  { q: "CPU is compressible and memory is not, which means exceeding…", options: ["A CPU limit throttles; a memory limit KILLS", "Either limit throttles", "Either limit kills the container"], answer: 0,
    explain: "There is no way to give a process less memory, which is why memory limits should always be set and CPU limits are a judgement call." },
  { q: "The Guaranteed QoS class requires…", options: ["Only a memory limit", "requests == limits for CPU and memory on EVERY container", "Any request to be set"], answer: 1,
    explain: "One container without limits demotes the whole pod to Burstable. Guaranteed is an eviction tier, not a performance tier." },
  { q: "Under node memory pressure, the kubelet evicts Burstable pods in order of…", options: ["Absolute memory usage", "Age", "Usage relative to their REQUEST — most over-request first"], answer: 2,
    explain: "A pod requesting 128Mi and using 1.8Gi was evicted before one requesting 3Gi and using 1.5Gi. Under-requesting is actively dangerous." },
  { q: "At a fixed 62% average CPU, tightening the CPU limit from none to 1 core moved p99 latency to…", options: ["Under 20 ms", "488 ms, with 37% of periods throttled", "Roughly unchanged"], answer: 1,
    explain: "Average utilisation is identical in every configuration, which is why nr_throttled belongs on the dashboard next to CPU." },
  { q: "The defensible default policy on limits is…", options: ["Always set both", "ALWAYS set memory limits; set CPU limits for batch and untrusted work, usually not for latency-critical services", "Never set either"], answer: 1,
    explain: "cpu.weight from the request already provides proportional fairness under contention — measured at ~3:1 for a 1500m:500m ratio with no limits." },
  { q: "A pod Evicted differs from a container OOMKilled in that Evicted means…", options: ["The NODE ran short and the kubelet chose this pod", "The container exceeded its own limit", "The image was deleted"], answer: 0,
    explain: "The fix for evictions is to raise the REQUEST, not the limit — the request is what protects it in the ranking." },
  { q: "kubectl top reporting 1284Mi where the real figure is 412Mi is explained by…", options: ["A metrics-server bug", "Page cache being counted in cgroup memory accounting", "Multiple containers"], answer: 1,
    explain: "The honest figure is memory.current − inactive_file. Alert on OOM kills, not on a percentage that page cache inflates." },
  { q: "A JVM in a 512Mi container with -Xmx512m is OOM-killed because…", options: ["Metaspace, thread stacks, code cache and direct buffers all live OUTSIDE the heap", "The flag is ignored", "512Mi is below the JVM minimum"], answer: 0,
    explain: "Budget 25–30% of the container limit for non-heap memory, and prefer MaxRAMPercentage so the heap tracks the limit." },
  { q: "Setting a runtime's heap limit BELOW the container limit gives you…", options: ["A diagnosable heap error with a stack trace instead of a silent SIGKILL", "Worse performance", "Nothing"], answer: 0,
    explain: "That debuggability win is independent of the memory saved — the process ends itself rather than being killed without warning." },
  { q: "A LimitRange and a ResourceQuota must be applied in which order?", options: ["Quota first", "Order does not matter", "LimitRange FIRST — a quota on CPU or memory makes requests mandatory and rejects every manifest omitting them"], answer: 2,
    explain: "Adding a quota to a live namespace without defaults breaks every deployment on its next apply." },
  { q: "maxLimitRequestRatio in a LimitRange prevents…", options: ["Namespace overcommit", "The 'tiny request, huge limit' pattern that makes nodes look free and then evict", "Pods without limits"], answer: 1,
    explain: "Neither LimitRange nor ResourceQuota affects running pods — both are admission-time only." },
  { q: "Deriving limits from measurement rather than guessing produced…", options: ["Higher costs", "0 OOM kills, 0.7% throttling and 52 ms p99, versus 4 kills, 31% and 488 ms", "A marginal improvement"], answer: 1,
    explain: "It also gave 8× the pod density. Limits are measurements with an expiry date — re-derive quarterly." },
]},
{ title: "Quiz 8 · Autoscaling & Disruptions",
  desc: "The HPA formula, VPA conflicts, cluster autoscaler latency, PDBs and graceful shutdown",
  questions: [
  { q: "The HPA's desired replica count is…", options: ["currentReplicas + 1 per threshold breach", "maxReplicas × utilisation", "ceil(currentReplicas × currentMetric / targetMetric)"], answer: 2,
    explain: "Evaluated every 15 seconds, with a ±10% tolerance, counting only READY pods." },
  { q: "For CPU, the HPA's 'utilisation' is a percentage of…", options: ["The pod's REQUEST", "The node's capacity", "The container's limit"], answer: 0,
    explain: "Doubling the request halved measured utilisation from 84% to 42% at identical load — and the HPA scaled DOWN." },
  { q: "An HPA on CPU whose pods have no CPU request…", options: ["Uses the node average", "Never scales — it reports <unknown>/70% with ScalingActive=False", "Uses 100% as the default"], answer: 1,
    explain: "With no request there is no denominator. It is the single most common 'the HPA isn't working'." },
  { q: "The default scaleDown stabilizationWindowSeconds is…", options: ["0", "60", "300 — the HPA uses the maximum recommendation from the last five minutes"], answer: 2,
    explain: "Scale-up is immediate and can double every 15 s. The asymmetry is deliberate: under-capacity is an outage, over-capacity is only money." },
  { q: "Shortening the scale-down window to 15 seconds produced…", options: ["23 scaling events in 10 minutes — the oscillation the window prevents", "No change", "Faster, cleaner scaling"], answer: 0,
    explain: "Scaling down raises per-pod load, which triggers a scale-up, which lowers it again." },
  { q: "40,000 queued messages with workers at 4% CPU means…", options: ["CPU is the wrong signal for I/O-bound work — scale on queue depth or message age", "The workers are broken", "The HPA is misconfigured"], answer: 0,
    explain: "Message age is often better than depth: 1,000 draining in seconds is fine; 10 messages an hour old is not." },
  { q: "KEDA's capability that a plain HPA lacks is…", options: ["Faster reaction", "Custom metrics", "Scaling to ZERO replicas"], answer: 2,
    explain: "minReplicas must be at least 1 without the alpha gate. For a consumer idle most of the day, zero-to-one on the first message is the whole value." },
  { q: "Running an HPA on CPU together with a VPA on CPU…", options: ["Oscillates — the VPA lowers the request, which raises utilisation, which makes the HPA scale up", "Is rejected by the API", "Is the recommended combination"], answer: 0,
    explain: "Measured 3 → 23 replicas with 31 VPA evictions under unchanged load. Restrict the VPA to memory, or run it in Off mode." },
  { q: "VPA in Off mode…", options: ["Produces recommendations only, with no evictions and no runtime behaviour", "Is disabled entirely", "Applies changes at pod creation"], answer: 0,
    explain: "It turns right-sizing into a reviewable backlog. Auto mode recreates pods to apply requests, which is a hidden source of restarts." },
  { q: "The Cluster Autoscaler adds nodes in response to…", options: ["High CPU utilisation", "PENDING pods", "A schedule"], answer: 1,
    explain: "Measured 194 seconds from Pending to serving. Negative-priority balloon pods cut that to 12 seconds at the cost of standing reservation." },
  { q: "A node stays in the cluster despite being nearly empty. A likely cause is…", options: ["Autoscaling is disabled", "A bare pod, local storage without safe-to-evict, or a PDB allowing zero disruptions", "It is the control plane"], answer: 1,
    explain: "Each pins the node indefinitely. A node is also only a candidate below ~50% REQUEST utilisation, so over-requesting hides idle nodes." },
  { q: "A PodDisruptionBudget protects against…", options: ["Node hardware failure", "Voluntary disruptions only — drains, the autoscaler, operators", "All pod terminations"], answer: 1,
    explain: "It is a contract with cooperative processes that use the eviction API. A node that catches fire ignores it entirely." },
  { q: "The difference between evicting and deleting a pod is that eviction…", options: ["Is a REQUEST that can be refused with 429 when a PDB would be violated", "Is faster", "Skips the grace period"], answer: 0,
    explain: "kubectl delete pod consults no PDB and is never blocked, which is why drain uses the eviction API." },
  { q: "A PDB with minAvailable equal to the replica count gives…", options: ["ALLOWED DISRUPTIONS: 0 — every drain hangs forever and the autoscaler stops reclaiming nodes", "The same as maxUnavailable: 1", "Maximum safety"], answer: 0,
    explain: "Prefer maxUnavailable: 1, which cannot be silently broken by scaling down. Alert on ALLOWED DISRUPTIONS: 0." },
  { q: "unhealthyPodEvictionPolicy: AlwaysAllow fixes the deadlock where…", options: ["The PDB selector matches nothing", "A crash-looping pod already counts as unavailable and blocks the drain that would rescue it", "Two PDBs overlap"], answer: 1,
    explain: "Without it, an unhealthy pod consumes the budget and pins its own node." },
  { q: "kubectl drain --disable-eviction…", options: ["Speeds up the drain", "Bypasses EVERY PodDisruptionBudget in the cluster by deleting directly", "Skips DaemonSet pods"], answer: 1,
    explain: "Measured deleting three pods at once against a budget of one, with no event and no warning. It is an incident-only tool." },
  { q: "A failed or cancelled drain leaves the node…", options: ["Cordoned — silently removing capacity until someone runs uncordon", "Tainted NoExecute", "Ready"], answer: 0,
    explain: "Always pair a drain with an explicit uncordon in automation, and use --timeout to bound a hang." },
  { q: "On pod deletion, preStop and endpoint removal are…", options: ["Both instantaneous", "Sequential — endpoints first", "Concurrent: preStop then SIGTERM run in sequence WHILE endpoint removal happens in parallel"], answer: 2,
    explain: "That race is why deploys drop requests — measured at 22 per 1200, and 0 after adding preStop: sleep 10." },
  { q: "terminationGracePeriodSeconds covers…", options: ["preStop AND the shutdown together", "Only the preStop hook", "Only the shutdown after SIGTERM"], answer: 0,
    explain: "A 10-second preStop with a 30-second grace period leaves 20 seconds to drain — which looks like random request failures if the app needs more." },
  { q: "A spot-instance termination handler is valuable because it…", options: ["Prevents reclamation", "Extends the notice period", "Converts an involuntary event into a voluntary one — cordon and drain, honouring PDBs"], answer: 2,
    explain: "Without it the node simply disappears and you are on the ~340-second involuntary path with no graceful shutdown at all." },
]},
{ title: "Quiz 9 · RBAC, Pod Security & Admission",
  desc: "Subjects and bindings, escalation paths, PSA levels, webhooks and mutation ordering",
  questions: [
  { q: "In Kubernetes, a User is…", options: ["A ServiceAccount alias", "An API object you create", "A string asserted by an external authenticator — there is no User object"], answer: 2,
    explain: "kubectl get users fails. User lifecycle belongs to your OIDC provider or CA, which is why certificates are awkward: they cannot be revoked." },
  { q: "The genuinely useful Role/Binding combination is…", options: ["Role + ClusterRoleBinding", "Role + RoleBinding only", "ClusterRole + RoleBinding — the rules defined once, scoped to that namespace"], answer: 2,
    explain: "It is how the built-in view/edit/admin roles are meant to be used, and it means updating one ClusterRole updates every namespace." },
  { q: "The built-in edit ClusterRole includes…", options: ["Neither Secrets nor exec", "Only read access", "Secrets AND pods/exec"], answer: 2,
    explain: "view deliberately excludes Secrets. admin adds Roles and RoleBindings within the namespace." },
  { q: "RBAC supports deny rules…", options: ["No — it is purely additive, so a cluster-wide grant silently overrides namespaced roles", "Yes, with an explicit deny verb", "Only for cluster-scoped resources"], answer: 0,
    explain: "Permissions are the union of every binding naming the subject, so 'everything except X' must be enumerated as what IS allowed." },
  { q: "resourceNames in a rule cannot restrict…", options: ["list and watch — listing returns collections", "update", "get"], answer: 0,
    explain: "A rule naming one object simply does not grant list at all, which is a common source of confusion." },
  { q: "Granting create pods in a namespace effectively also grants…", options: ["Cluster-admin", "Reading every Secret in that namespace, and any other ServiceAccount's permissions", "Nothing further"], answer: 1,
    explain: "The kubelet mounts the Secret on the pod's behalf. RBAC cannot express 'may create pods but only with ServiceAccount X' — that needs admission policy." },
  { q: "The escalate, bind and impersonate verbs are notable because each is…", options: ["Read-only", "Deprecated", "Effectively cluster-admin — they bypass the built-in privilege-escalation check"], answer: 2,
    explain: "Normally you cannot grant permissions you do not hold. In an audit these matter more than cluster-admin bindings, because they look innocuous." },
  { q: "A projected ServiceAccount token differs from the legacy Secret token in that it…", options: ["Expires in about an hour, is audience-scoped, and is BOUND TO THE POD", "Is longer", "Is stored in etcd"], answer: 0,
    explain: "Verified returning Unauthorized seconds after the pod was deleted. Legacy Secret tokens never expired." },
  { q: "The cheapest RBAC hardening for workloads that never call the API is…", options: ["A restrictive Role", "automountServiceAccountToken: false", "A NetworkPolicy"], answer: 1,
    explain: "One audit found 47 pods carrying a credential they never use. Workload identity removes the credential entirely for cloud access." },
  { q: "Admission control differs from RBAC in that RBAC answers…", options: ["'Is this YAML valid'", "'Is the namespace correct'", "'May you create A pod', while admission answers 'may you create THIS pod'"], answer: 2,
    explain: "That gap is where hostPath, privileged and host namespaces live — the difference between 'can deploy' and 'owns the node'." },
  { q: "A namespace with no Pod Security labels defaults to…", options: ["baseline", "privileged — no restrictions at all", "restricted"], answer: 1,
    explain: "Labels are the entire configuration surface, and enforce-version should be pinned so a cluster upgrade cannot tighten rules under you." },
  { q: "Under enforce=restricted, applying a non-compliant Deployment…", options: ["Succeeds — PSA validates PODS, so the failure appears as FailedCreate events", "Is rejected immediately", "Mutates the Deployment"], answer: 0,
    explain: "That is exactly why warn mode matters: it returns the required-field list on the object you actually applied." },
  { q: "The restricted level requires all of…", options: ["Only a seccomp profile", "runAsNonRoot, allowPrivilegeEscalation: false, capabilities.drop: [ALL] and seccompProfile: RuntimeDefault", "Only runAsNonRoot"], answer: 1,
    explain: "Verified in the container as CapEff 0, NoNewPrivs 1 and Seccomp 2. It also bans hostPath, host namespaces, hostPort and privileged." },
  { q: "A pod mounting hostPath: / from a ServiceAccount with only create pods can…", options: ["Do nothing useful", "Read other pods' mounted Secrets and the kubelet's credentials", "Only read its own files"], answer: 1,
    explain: "Its RBAC is irrelevant. One baseline label blocked that, privileged: true and a mounted daemon socket alike." },
  { q: "The correct Pod Security rollout order is…", options: ["warn + audit at restricted, fix, then enforce=baseline, then restricted", "enforce=restricted everywhere immediately", "audit only, indefinitely"], answer: 0,
    explain: "Enforcing everywhere at once breaks infrastructure workloads silently, because the Deployment is accepted and only the pods are rejected." },
  { q: "Infrastructure that genuinely needs hostPath should be…", options: ["Placed in its own privileged namespace with tight RBAC on who may deploy there", "Granted cluster-admin", "Exempted per pod with an annotation"], answer: 0,
    explain: "'Who can deploy into a privileged namespace' is one auditable query — a much better control than per-pod exceptions nobody reviews." },
  { q: "A validating webhook with failurePolicy: Fail whose Service is deleted makes…", options: ["Only its own resources fail", "Every write in the cluster fail after the timeout, while reads keep working", "The API server crash"], answer: 1,
    explain: "Self-healing breaks too: replacement pods cannot be created. Recovery works only because webhooks do not gate their own configuration objects." },
  { q: "Safe webhook configuration includes a namespaceSelector that…", options: ["Matches only the webhook's own namespace", "EXCLUDES kube-system, so you can still fix the cluster", "Matches all namespaces"], answer: 1,
    explain: "Together with failurePolicy: Ignore for non-security controls, short timeouts and narrow rules, and never gating the webhook's own pods." },
  { q: "Mutating and validating admission run in which order?", options: ["Mutating FIRST — so PSA evaluates the pod after a sidecar has been injected", "In parallel", "Validating first"], answer: 0,
    explain: "A compliant pod was rejected for an injected Envoy sidecar requiring NET_ADMIN — an error naming a container the author never wrote." },
  { q: "That ordering can be used deliberately to…", options: ["Skip validation", "Mutate seccompProfile and allowPrivilegeEscalation into every pod, making legacy workloads compliant with no manifest changes", "Reorder webhooks"], answer: 1,
    explain: "Verified: a bare kubectl run succeeded under enforce=restricted. Only --dry-run=server sees the mutated object; a client dry run proves nothing." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review, including Helm, GitOps and production debugging",
  questions: [
  { q: "Helm is best described as…", options: ["A Kubernetes controller", "A local template renderer plus a release ledger stored as Secrets in the cluster", "A package registry"], answer: 1,
    explain: "It is imperative: nothing reconciles a release, so drift is invisible until the next upgrade. Deleting the namespace destroys the history." },
  { q: "helm upgrade --set image.tag=1.20 deploys which tag?", options: ["1.20", "1.2 — the value is coerced to a float", "latest"], answer: 1,
    explain: "It fails silently because 1.2 is often a real tag. Always use --set-string for tags and version numbers." },
  { q: "A failed pre-upgrade hook leaves the release…", options: ["Deleted", "Rolled back", "In pending-upgrade, blocking every subsequent deploy including the fix"], answer: 2,
    explain: "Recover with helm rollback or by deleting the pending release Secret. --atomic prevents the state entirely." },
  { q: "CRDs placed in a chart's crds/ directory are…", options: ["Ignored", "Upgraded with the chart", "Installed ONCE and never upgraded or deleted"], answer: 2,
    explain: "New fields are then silently pruned by the old schema, with no error. Apply CRDs explicitly before upgrading." },
  { q: "The rendered-manifest pattern means…", options: ["helm template in CI with the output committed, so PRs show the actual objects changing", "Rendering charts inside the cluster", "Using Kustomize instead"], answer: 0,
    explain: "A one-line template change that quartered production memory limits was invisible in the template diff and obvious in the rendered one." },
  { q: "The GitOps principle with the biggest operational impact is…", options: ["Version control", "Declarative configuration", "Continuous reconciliation — manual changes are reverted, not merely detected"], answer: 2,
    explain: "An emergency kubectl fix has roughly a three-minute half-life, which is why a documented break-glass procedure matters." },
  { q: "An Argo CD Application showing Synced + Degraded means…", options: ["The sync failed", "The repo is unreachable", "Git was applied faithfully and the workload is broken"], answer: 2,
    explain: "Synced is as meaningful as kubectl apply returning 0. Alert on Degraded; treat OutOfSync as information." },
  { q: "prune: true without allowEmpty: false is dangerous because…", options: ["A build rendering zero manifests reads as 'Git declares nothing' — and everything is pruned", "It ignores finalizers", "It deletes old ReplicaSets"], answer: 0,
    explain: "Annotate PVCs and namespaces with Prune=false, and add a CI check that refuses a render producing too few resources." },
  { q: "Argo CD sync waves are used to…", options: ["Stagger replicas", "Order resources — CRDs and namespaces before config, config before data, data before apps", "Rate-limit the API server"], answer: 1,
    explain: "Without them a custom resource can be applied before its CRD exists. A failing PreSync hook correctly blocks the whole deploy." },
  { q: "In GitOps, secrets should be handled by committing…", options: ["Base64-encoded values in a private repo", "Nothing, and applying them by hand", "REFERENCES — an ExternalSecret, or SOPS/Sealed Secrets if the value must live in Git"], answer: 2,
    explain: "ESO also rotates with no Git commit at all. Sealed Secrets are tied to one cluster's key, which complicates disaster recovery." },
  { q: "The break-glass procedure under GitOps is…", options: ["Disable auto-sync, fix, COMMIT the same change, re-enable", "kubectl edit and move on", "Delete the Application"], answer: 0,
    explain: "Forgetting the commit means the controller reverts the fix minutes later, and the audit trail attributes the change to the controller." },
  { q: "kubectl describe pod showing 'Events: <none>' on a pod that failed this morning means…", options: ["The pod was recreated", "The events EXPIRED — the default TTL is about an hour", "Nothing went wrong"], answer: 1,
    explain: "Status persists while events do not, which is why events should be shipped to your logging pipeline." },
  { q: "The field that distinguishes an OOM kill from an ignored SIGTERM is…", options: ["The exit code alone", "status.containerStatuses[].lastState.terminated.reason", "restartCount"], answer: 1,
    explain: "Both produce exit 137. reason: OOMKilled means the memory limit; otherwise it is a stop timeout on a process that ignored SIGTERM." },
  { q: "To debug a distroless container with no shell you use…", options: ["kubectl exec with a full path", "kubectl debug --target, an ephemeral container sharing its namespaces", "A :debug image variant in production"], answer: 1,
    explain: "Its filesystem is reachable at /proc/1/root. Ephemeral containers cannot be removed, so use --copy-to on a pod you intend to keep." },
  { q: "A pod IP is reachable but names are not. That is the signature of…", options: ["A CNI failure", "A NetworkPolicy blocking port 53, or CoreDNS being down", "A wrong targetPort"], answer: 1,
    explain: "Testing in layers — pod IP, DNS, ClusterIP, ingress — means each step eliminates one subsystem." },
  { q: "All failing pods being on one node points at…", options: ["The workloads", "The node — conditions, kubelet, disk", "The scheduler"], answer: 1,
    explain: "Asking 'one pod, one workload, one node, or everything?' first eliminates most of the search space before any command is run." },
  { q: "When the API and the node disagree about whether a container is running, the ground truth is…", options: ["crictl on the node", "kubectl get pods", "The Deployment status"], answer: 0,
    explain: "The API reflects what the kubelet last managed to report. kubectl debug node/ plus chroot /host gets you there." },
  { q: "Reads work but every write fails cluster-wide. The most likely cause is…", options: ["etcd is full", "A failing admission webhook", "The scheduler is down"], answer: 1,
    explain: "Admission is the one synchronous step; everything else retries and converges. A webhook stops convergence entirely." },
  { q: "Thousands of identical Warning events are…", options: ["Normal noise", "A metrics-server bug", "Themselves a diagnosis — a controller retrying something impossible — and they consume etcd"], answer: 2,
    explain: "Counting events by reason is often faster than reading any of them, and an event flood can turn one broken workload into cluster-wide slowness." },
  { q: "The general principle behind observing OOM kills, evictions and node failures is…", options: ["Increase log verbosity", "Anything that can kill your process cannot be observed BY your process", "Use a sidecar logger"], answer: 1,
    explain: "Container events, kernel messages and externally-scraped metrics are the layers that survive a SIGKILL — application logs are not." },
]},
);
