// kubernetes quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations: Architecture & the API",
  desc: "Reconciliation loops, the component split, objects and apply, etcd and deletion",
  questions: [
  { q: "Kubernetes controllers are level-triggered rather than edge-triggered, which means…", options: ["They run only when you invoke kubectl", "They react to events and must replay missed ones", "They compare desired with observed state, so a missed event is corrected on the next pass"], answer: 2,
    explain: "Level-triggering is why missed events, duplicate deliveries and controller restarts are all harmless — the loop re-derives everything from current state." },
  { q: "The kube-scheduler's entire output for a pod is…", options: ["Creating the pod object", "Writing spec.nodeName", "Starting the container"], answer: 1,
    explain: "Set nodeName by hand and the pod runs with no scheduler involved; stop the scheduler and pods sit Pending with an empty nodeName and no events at all." },
  { q: "Scheduling decisions are based on…", options: ["Actual CPU and memory usage", "The pods' limits", "The pods' resource REQUESTS"], answer: 2,
    explain: "Requests are reservations. A node measured at 1–4% CPU rejected new pods because 91% of its CPU was already booked by requests." },
  { q: "kubectl apply returns exit 0. What has been proven?", options: ["The object was written to etcd — nothing more", "The image exists and was pulled", "The workload is running and healthy"], answer: 0,
    explain: "Measured, the apply took 0.19 s and the rollout 23 s. A bad image gives exit 0 from apply and ImagePullBackOff in the cluster; use kubectl rollout status in CI." },
  { q: "You edit a ReplicaSet owned by a Deployment. What happens?", options: ["The change persists", "The Deployment controller reverts it within about a second", "The Deployment is updated to match"], answer: 1,
    explain: "Anything with ownerReferences is continuously driven back to what its owner specifies. Always change the object at the top of the ownership chain." },
  { q: "A two-member etcd cluster compared with a single member is…", options: ["WORSE — quorum is 2, so it tolerates zero failures with twice the failure surface", "Identical", "More resilient"], answer: 0,
    explain: "Raft quorum is a majority. 3 members tolerate 1 failure, 5 tolerate 2, and even counts add failure surface without adding tolerance." },
  { q: "The control plane is completely down. What still works?", options: ["Only reads via kubectl", "Running pods keep running and Service traffic keeps flowing; nothing can CHANGE", "Nothing — the cluster is offline"], answer: 1,
    explain: "The kubelet caches its assigned pods and kube-proxy rules are already programmed. The sharp edge is that endpoint updates freeze, so a pod that dies stays in Service endpoints." },
  { q: "kubectl delete actually…", options: ["Sets metadata.deletionTimestamp; the object survives until every finalizer is removed", "Removes the object immediately", "Marks it for garbage collection after 30 days"], answer: 0,
    explain: "Deletion is a request. A PVC stuck Terminating usually holds pvc-protection because a pod still mounts it." },
  { q: "A namespace has been stuck in Terminating for hours. The most common cause is…", options: ["An unavailable APIService, so contents cannot be enumerated", "A network partition", "Too many objects inside it"], answer: 0,
    explain: "The status conditions name it exactly — DeletionDiscoveryFailure. Fixing or deleting the broken APIService completes the deletion in seconds." },
  { q: "Force-patching a finalizer off a stuck object…", options: ["Has no effect", "Deletes the object while leaking whatever it was protecting — orphaned disks, load balancers still billing", "Is the recommended fix"], answer: 1,
    explain: "The finalizer is a controller saying it has not finished. Removing it gives a clean kubectl get and a mess underneath." },
  { q: "Every Kubernetes object has spec and status. The rule is…", options: ["Both are yours to write", "spec is desired state (you write it); status is observed state (controllers write it)", "status is a copy of spec"], answer: 1,
    explain: "Status lives on its own subresource and a controller overwrites anything you write there within seconds — like editing a thermometer." },
  { q: "How do you tell whether a controller has SEEN your change?", options: ["The object exists", "readyReplicas is non-zero", "status.observedGeneration equals metadata.generation"], answer: 2,
    explain: "observedGeneration answers 'was it processed'; conditions answer 'did it work'. They are different questions." },
  { q: "A condition's status field can be…", options: ["A numeric score", "\"True\", \"False\" or \"Unknown\" — strings, where Unknown means unobservable", "Only true or false"], answer: 1,
    explain: "Automation that treats conditions as booleans turns 'we cannot tell' into 'it is broken' and remediates on a monitoring failure." },
  { q: "kubectl apply knows to DELETE a field you removed from your YAML because…", options: ["It diffs against the cluster only", "It recreates the object", "It performs a three-way merge using the last-applied-configuration annotation"], answer: 2,
    explain: "In last-applied but not the new YAML means delete; only on the live object means leave alone — which is why apply does not wipe fields set by webhooks or an HPA." },
  { q: "An object created with kubectl create and later managed with apply…", options: ["Has no last-applied annotation, so the first apply cannot delete removed fields", "Cannot be applied at all", "Behaves identically"], answer: 0,
    explain: "The warning about the missing annotation is real: a stale nodeSelector survived the apply that removed it. Server-side apply has no such problem." },
  { q: "Server-side apply differs from client-side apply mainly because…", options: ["It is faster", "It skips validation", "The API server tracks per-FIELD ownership in managedFields, turning silent last-writer-wins into an explicit conflict"], answer: 2,
    explain: "It needs no apply history, avoids the annotation size limit, and tells you which manager owns a contended field." },
  { q: "Your GitOps tool and an HPA both set spec.replicas. The correct fix is…", options: ["REMOVE replicas from the manifest so the HPA is the sole owner", "Disable the HPA", "Add --force-conflicts"], answer: 0,
    explain: "Measured at 23 scaling events in ten minutes. --force-conflicts takes ownership from the controller legitimately managing the field." },
  { q: "--dry-run=client differs from --dry-run=server in that the client version…", options: ["Requires a cluster", "Only parses YAML — it skips defaulting, admission webhooks, quota and RBAC entirely", "Is more thorough"], answer: 1,
    explain: "A manifest every policy webhook will reject passes a client dry run. The server dry run runs the full pipeline except the etcd write." },
  { q: "A Service whose selector matches no pods is…", options: ["Perfectly valid — you get a Service with zero endpoints and no error anywhere", "Rejected by the API server", "Automatically deleted"], answer: 0,
    explain: "The failure presents as connection timeouts. kubectl get endpointslices is the one command that separates 'selector matches nothing' from 'pods not Ready'." },
  { q: "An admission webhook with failurePolicy: Fail whose Service is missing causes…", options: ["A warning in the audit log", "Only that webhook's resources to fail", "EVERY write in the cluster to fail after the timeout, while reads keep working"], answer: 2,
    explain: "Admission is the one synchronous step. Everything else retries and converges; a failing webhook stops convergence entirely." },
]},
{ title: "Quiz 2 · Pods, Deployments & Scheduling",
  desc: "Namespace sharing, sidecars, rollouts, surge arithmetic, affinity, taints and spread",
  questions: [
  { q: "Containers in one pod share…", options: ["Everything, including the filesystem", "Network, IPC and UTS namespaces — but NOT the mount namespace", "Only the node"], answer: 1,
    explain: "They reach each other on localhost and share one IP, but each has its own filesystem: sharing files needs a volume." },
  { q: "Two containers in the same pod both try to listen on port 8080. The result is…", options: ["The second fails with 'address already in use', because they share one network namespace", "Kubernetes load-balances between them", "Both work — they are isolated"], answer: 0,
    explain: "One network namespace means one port space. It is also why a pod is the wrong unit for two independent services." },
  { q: "A container crashes and restarts. The pod IP…", options: ["Is released and reassigned", "Stays the same — the pause container holds the namespaces open", "Changes"], answer: 1,
    explain: "Only a pod recreation gets a new IP. Every replica in a rolling update gets a new one, which is why pod IPs must never be configured anywhere." },
  { q: "A pod shows Running with 0/1 ready. That means…", options: ["The container crashed", "The process is up but readiness is failing, so it is in no Service's endpoints", "It is starting up"], answer: 1,
    explain: "Phase and readiness answer different questions. Monitoring that alerts on phase shows green while a Service has zero endpoints." },
  { q: "CrashLoopBackOff is…", options: ["A pod that cannot be scheduled", "A restart DELAY — 10s, 20s, 40s… capped at 5 minutes — not a cause", "A distinct error condition"], answer: 1,
    explain: "kubectl logs shows nothing during backoff because the current container has not started. Use --previous and read lastState.terminated." },
  { q: "Init containers affect scheduling because a pod's effective request is…", options: ["max(largest init request, sum of app requests)", "Only the app containers", "The sum of all containers"], answer: 0,
    explain: "An 8Gi init container made a 256Mi app unschedulable on 4Gi nodes — the request applies for the pod's whole life." },
  { q: "An ordinary sidecar in a Job pod causes…", options: ["A scheduling failure", "Faster completion", "The Job never to complete, because a pod is Succeeded only when ALL containers exit"], answer: 2,
    explain: "Measured: 30+ minutes and counting versus 14 seconds once converted to a native sidecar." },
  { q: "A native sidecar is declared as…", options: ["An initContainer with restartPolicy: Always", "A separate pod", "A normal container with an annotation"], answer: 0,
    explain: "That gives start-before and stop-after ordering, restarts on crash, and exclusion from the pod's completion calculation." },
  { q: "A bare pod (no controller) on a node that is drained…", options: ["Blocks the drain indefinitely", "Is rescheduled elsewhere", "Is deleted permanently — it has no ownerReferences, so nothing recreates it"], answer: 2,
    explain: "kubectl drain even requires --force to do it, and warns you. Pod specs are also immutable apart from image, tolerations and activeDeadlineSeconds." },
  { q: "A Deployment creates a new ReplicaSet when…", options: ["Replicas change", "Any field changes", "The pod TEMPLATE changes, producing a different pod-template-hash"], answer: 2,
    explain: "Scaling creates no revision, and reverting a template reuses the existing ReplicaSet rather than creating one." },
  { q: "With replicas: 4 and default maxSurge/maxUnavailable of 25%, during a rollout you see…", options: ["At most 5 pods existing and as few as 3 ready", "8 pods at peak", "Exactly 4 pods throughout"], answer: 0,
    explain: "25% of 4 rounds up to 1 for surge and down to 1 for unavailable — measured exactly as predicted." },
  { q: "maxUnavailable: 0 guarantees full capacity but…", options: ["Deadlocks permanently if there is no headroom for the surge pod — quota or full nodes", "Is always safe", "Doubles the rollout time"], answer: 0,
    explain: "A pods=4 quota froze a rollout at '0 of 4 updated' forever: no old pod may go, and the new one cannot be created." },
  { q: "You change a ConfigMap's contents. The Deployment…", options: ["Restarts one pod", "Does nothing — the contents are not part of the pod template", "Rolls out automatically"], answer: 1,
    explain: "Env vars never update; a mounted directory updates in ~60 s but the process keeps what it parsed; subPath mounts never update at all." },
  { q: "A rollout fails with ProgressDeadlineExceeded. Kubernetes then…", options: ["Rolls back automatically", "Marks the rollout failed and STOPS — verified unchanged 15 minutes later", "Retries indefinitely"], answer: 1,
    explain: "Available stays true because the old version keeps serving. Rollback is your pipeline's job: rollout status --timeout || rollout undo." },
  { q: "kubectl rollout undo restores…", options: ["The previous cluster snapshot", "Only the pod template — never ConfigMaps, schema, Services or RBAC", "The entire application state"], answer: 1,
    explain: "That is why config should be referenced by a content-hashed immutable name: then rollback restores image and configuration together." },
  { q: "Every pod silently carries a toleration for node.kubernetes.io/unreachable with tolerationSeconds of…", options: ["30", "300 — which is why pods take about 5–6 minutes to leave a dead node", "0"], answer: 1,
    explain: "Measured ~341 s end to end: ~40 s to mark the node Unknown, then the 300 s toleration before eviction." },
  { q: "Required pod anti-affinity with more replicas than domains results in…", options: ["Automatic relaxation of the rule", "The extra pods staying Pending forever", "Even distribution"], answer: 1,
    explain: "5 replicas on 3 nodes gave 3 Running and 2 Pending. Topology spread with maxSkew distributes instead — 2/2/1, all Running." },
  { q: "Topology spread constraints are evaluated…", options: ["Only at scheduling time — and never repaired afterwards", "Continuously, and re-balanced", "Every 5 minutes"], answer: 0,
    explain: "After a zone outage and recovery, every replica can end up in one zone. Alert on observed distribution, not on the constraint existing." },
  { q: "To dedicate nodes to one workload you need…", options: ["A taint plus a toleration plus affinity — affinity attracts but does not repel others", "Node affinity alone", "A separate cluster"], answer: 0,
    explain: "Verified: with a toleration alone the pods scattered; the taint keeps everyone else off and affinity directs yours there." },
  { q: "Preemption respects PodDisruptionBudgets…", options: ["On a best-effort basis only — it prefers non-violating victims but will violate a PDB if it must", "Always", "Never"], answer: 0,
    explain: "Demonstrated evicting a pod against a PDB showing zero allowed disruptions. A high globalDefault priority also silently disables preemption as a mechanism." },
]},
{ title: "Quiz 3 · Services, Endpoints & Cluster DNS",
  desc: "ClusterIP internals, per-connection balancing, externalTrafficPolicy, CoreDNS and ndots",
  questions: [
  { q: "A Service's ClusterIP is…", options: ["An IP on a proxy pod", "The first pod's IP", "A virtual IP with no process behind it — DNAT rules programmed on every node"], answer: 2,
    explain: "You cannot ping it, nothing is bound to it, and no interface holds it — yet curl works, because netfilter rewrites the destination." },
  { q: "kube-proxy's iptables 'load balancing' is implemented as…", options: ["Round-robin", "statistic mode random probability rules with cumulative probabilities", "Least connections"], answer: 1,
    explain: "With 4 endpoints the probabilities are 1/4, then 1/3 of the remainder, then 1/2 — arithmetically uniform, but random per connection." },
  { q: "Only pods that are ______ appear as Service endpoints.", options: ["Running", "Scheduled", "Ready"], answer: 2,
    explain: "A Service with zero endpoints raises no error, no condition and no event — which is why kubectl get endpointslices is the first triage command." },
  { q: "Your gRPC service has 8 replicas and one pod receives all traffic. Why?", options: ["Balancing is per CONNECTION, and gRPC holds one long-lived connection", "A bug in kube-proxy", "The Service selector is wrong"], answer: 0,
    explain: "Measured 200/0/0/0 on one keep-alive connection versus 48/53/51/48 without. Scaling up does not help — new pods received zero traffic." },
  { q: "The fixes for per-connection pinning are…", options: ["A headless Service with client-side round-robin, an L7 proxy, or bounded connection age", "More replicas", "sessionAffinity: None"], answer: 0,
    explain: "The same problem affects database pools and WebSockets. It is not a gRPC bug — it is what a connection-level load balancer does." },
  { q: "externalTrafficPolicy: Local preserves the client IP but…", options: ["Splits traffic per NODE, so a node with one pod gets the same share as one with three", "Only works with NodePort", "Requires an extra hop"], answer: 0,
    explain: "Measured 133/134/133 across a three-pod node versus 400 to a single pod on another. Nodes with no local pod drop the traffic entirely." },
  { q: "Requests fail during a rolling update even with maxUnavailable: 0 because…", options: ["The Service is recreated", "Readiness probes are too slow", "Endpoint removal and SIGTERM happen in PARALLEL, so rules may still point at a stopped pod"], answer: 2,
    explain: "Measured 22 failures per 1200 requests, and 0 after adding preStop: sleep 10 with a longer grace period." },
  { q: "A headless Service (clusterIP: None) provides…", options: ["A VIP with no ports", "External access only", "DNS returning every ready pod IP, with no VIP and no kube-proxy rules"], answer: 2,
    explain: "DNS is its entire feature — the basis of StatefulSet per-pod identity and client-side load balancing." },
  { q: "A headless Service with no ready endpoints resolves to…", options: ["An empty answer", "NXDOMAIN", "The ClusterIP"], answer: 1,
    explain: "A ClusterIP Service still resolves and simply routes nowhere. That difference is a useful diagnostic." },
  { q: "A Service without a selector, paired with a hand-written EndpointSlice, is used to…", options: ["Give an in-cluster name to an external dependency, repointable with one patch", "Disable a Service temporarily", "Create a headless Service"], answer: 0,
    explain: "It makes a migration cutover a single object change, with no client reconfiguration and no TLS SNI problem." },
  { q: "ExternalName Services are risky with TLS because…", options: ["They are only a CNAME — no SNI rewriting, so certificates must match the EXTERNAL hostname", "They terminate TLS", "They do not support TLS"], answer: 0,
    explain: "The client resolves the CNAME and connects directly, so verify-full fails against the in-cluster name." },
  { q: "Resolving an external name like api.stripe.com from a pod costs how many DNS queries by default?", options: ["One", "Ten — the search path is tried first, and A/AAAA are queried in parallel", "Two"], answer: 1,
    explain: "Measured 48 ms and ten queries versus 7 ms and two with a trailing dot. Eight of the ten are guaranteed NXDOMAIN." },
  { q: "The reason for that is /etc/resolv.conf's…", options: ["options ndots:5 — names with fewer than 5 dots try every search domain first", "nameserver entry", "search domain count"], answer: 0,
    explain: "Fix with dnsConfig ndots: 2 or fully-qualified names; the trade is that bare same-namespace names stop resolving." },
  { q: "Requests that take exactly 5.000 seconds and then succeed are usually…", options: ["TCP retransmits", "Slow database queries", "A conntrack race on the parallel A/AAAA UDP queries"], answer: 2,
    explain: "Both packets try to create the same conntrack entry; one is dropped and the resolver waits out its 5-second timeout. NodeLocal DNSCache fixes it properly." },
  { q: "A pod with hostNetwork: true and default dnsPolicy…", options: ["Resolves cluster names normally", "Silently uses the NODE's resolver — cluster names fail while external names work", "Cannot resolve anything"], answer: 1,
    explain: "The pod still reports dnsPolicy: ClusterFirst. Host-network pods need dnsPolicy: ClusterFirstWithHostNet." },
  { q: "An egress NetworkPolicy that forgets port 53…", options: ["Is rejected by the API", "Breaks everything, with no error mentioning DNS", "Only affects DNS lookups of external names"], answer: 1,
    explain: "The distinguishing test is that connecting to a pod IP directly still works. Allow both UDP and TCP 53." },
  { q: "publishNotReadyAddresses: true on a headless Service exists to…", options: ["Expose failing pods to clients", "Speed up rollouts", "Break the bootstrap deadlock where readiness needs peers and peer discovery needs readiness"], answer: 2,
    explain: "Without it three cluster members sat at 0/1 permanently. Clustered software therefore wants two Services — one for peers, one for clients." },
  { q: "In a Service with ports 8080:3000, other pods should connect to…", options: ["The pod IP", "servicename:8080", "servicename:3000 — the container port"], answer: 2,
    explain: "8080 exists only on the host side of the NAT. Publishing is for reaching the service from outside the cluster." },
  { q: "kube-proxy in iptables mode at thousands of Services suffers from…", options: ["Rule sync time growing sharply — every endpoint change pays a full resync", "Dropped packets", "Memory exhaustion"], answer: 0,
    explain: "IPVS uses hash tables with real algorithms; nftables mode is the direction of travel." },
  { q: "kube-proxy health-checks endpoints before routing to them…", options: ["Yes, every 10 seconds", "Only for LoadBalancer Services", "No — it programs whatever the EndpointSlice says"], answer: 2,
    explain: "Readiness probes are the only health signal in the path, which is why a frozen endpoint list during a control-plane outage black-holes traffic." },
]},
{ title: "Quiz 4 · Ingress, Gateway API & Network Policies",
  desc: "Controllers, pathType, TLS, and the additive allowlist model of NetworkPolicy",
  questions: [
  { q: "An Ingress object with no controller installed…", options: ["Is rejected by the API server", "Routes traffic using kube-proxy", "Does nothing at all — it never gets an ADDRESS and emits no events"], answer: 2,
    explain: "An Ingress is a routing table waiting for a program to read it. The controller is an ordinary Deployment behind a LoadBalancer Service." },
  { q: "The most common cause of an Ingress that silently does nothing is…", options: ["A wrong backend port", "A missing TLS secret", "An omitted ingressClassName, so no controller claims it"], answer: 2,
    explain: "It is adopted only if some IngressClass is annotated as default. The failure is total silence, not an error." },
  { q: "Replacing 40 LoadBalancer Services with one ingress saves roughly…", options: ["Nothing", "Half the cost", "$800/month versus $20, plus 39 DNS records and certificate renewals"], answer: 2,
    explain: "The capability difference matters too: per-REQUEST balancing, host and path routing, and X-Forwarded-For." },
  { q: "With pathType: Prefix, the rule /api matches…", options: ["/api, /api/ and /apifoo", "Only /api exactly", "/api, /api/ and /api/v1 — but NOT /apifoo"], answer: 2,
    explain: "Prefix matches path ELEMENTS, so /apifoo falls through to the / rule. Longest match wins regardless of rule order." },
  { q: "ingress-nginx's default proxy-body-size is…", options: ["1 MB — uploads above it fail with 413, and only in the cluster", "100 MB", "Unlimited"], answer: 0,
    explain: "Together with the 60-second proxy-read-timeout it is the pair that breaks uploads and SSE in production but never locally." },
  { q: "A browser warning about a self-signed 'Kubernetes Ingress Controller Fake Certificate' means…", options: ["The certificate expired", "The request's SNI matched no configured TLS host, so the default certificate was served", "The controller is compromised"], answer: 1,
    explain: "openssl s_client -servername shows which certificate you are actually served. The cause is a hostname mismatch or a missing TLS block." },
  { q: "Ingress annotations are validated by the API server…", options: ["No — they are unchecked strings, so a typo is silently ignored", "Yes, against the controller's schema", "Only in strict mode"], answer: 0,
    explain: "A typo'd proxy-body-sizes was accepted and did nothing. This unvalidated sprawl is what motivated the Gateway API." },
  { q: "The Gateway API's main structural contribution is…", options: ["Native TLS", "Better performance", "A role split — GatewayClass, Gateway (platform team) and HTTPRoute (app teams) — with typed, validated fields"], answer: 2,
    explain: "An invalid weight was rejected at apply time, where the equivalent Ingress annotation was accepted and ignored." },
  { q: "A 503 from an ingress versus a 502 tells you…", options: ["503 is a timeout", "Nothing useful", "503 means zero endpoints; 502 means an endpoint existed and refused"], answer: 2,
    explain: "503 is a Service problem (selector or readiness); 502 is a port, protocol or application problem. They are one command apart." },
  { q: "By default, a pod in namespace A can reach a pod in namespace B…", options: ["Directly by pod IP, on any port — namespaces are not a network boundary", "Not at all", "Only through a Service"], answer: 0,
    explain: "Namespaces are an RBAC, quota and naming boundary. NetworkPolicy is the only mechanism that changes it, and it is opt-in." },
  { q: "A pod that no NetworkPolicy selects is…", options: ["Unrestricted in both directions", "Isolated from other namespaces", "Default-deny"], answer: 0,
    explain: "The moment any policy selects it for a direction, that direction becomes default-deny and all matching policies are unioned." },
  { q: "NetworkPolicy supports deny rules…", options: ["Only for egress", "No — it is purely additive, so 'allow all except X' must be restructured as an allowlist", "Yes, with a deny action"], answer: 1,
    explain: "You can only add allowances. There is no way to subtract from a permission granted by another policy." },
  { q: "Putting namespaceSelector and podSelector in SEPARATE list items means…", options: ["OR — anything in those namespaces, or that pod label in ANY namespace", "AND — both must match", "It is invalid"], answer: 0,
    explain: "Measured, a hostile namespace granted itself access by labelling a pod app=api, widening the rule from 2 namespaces to 7 pods anywhere." },
  { q: "Allowing egress to a Service's ClusterIP in an ipBlock…", options: ["Does nothing — DNAT rewrote the destination to a pod IP before the policy is evaluated", "Allows all traffic", "Works correctly"], answer: 0,
    explain: "For the same reason the rule's port is the CONTAINER port (targetPort), not the Service port." },
  { q: "On a CNI that does not implement NetworkPolicy, applying one…", options: ["Falls back to iptables", "Is accepted and enforced by nothing — a deny-all test still returned 200", "Fails with an error"], answer: 1,
    explain: "A policy that is silently ignored is worse than none, because it creates confidence without protection. Run a deny-all test on every cluster." },
  { q: "NetworkPolicies do not apply to…", options: ["hostNetwork pods, which use the node's network namespace", "StatefulSet pods", "Pods with multiple containers"], answer: 0,
    explain: "Restricting who may use hostNetwork is a Pod Security admission concern, not a network policy one." },
  { q: "NetworkPolicies are stateful, which means…", options: ["They remember previous connections for auditing", "Reply traffic is implicit — you never write egress rules for responses", "They persist across restarts"], answer: 1,
    explain: "An ingress rule on the target permits the response without any egress rule, which is why over-broad egress rules are usually a misunderstanding." },
  { q: "The safest namespace selector label to use in a policy is…", options: ["The namespace's UID", "A custom team label", "kubernetes.io/metadata.name, which the API server sets and users cannot forge"], answer: 2,
    explain: "Pod labels are set by whoever creates the pod, so a bare cross-namespace podSelector is not a security control." },
  { q: "The correct rollout order for default-deny is…", options: ["Verify the CNI, label namespaces, ALLOW DNS first, then deny ingress, then egress", "Egress first, then ingress", "Enforce everywhere at once"], answer: 0,
    explain: "Allowing DNS first prevents the classic incident where a deny-all breaks every application with errors that never mention name resolution." },
  { q: "NetworkPolicy cannot express…", options: ["Namespace selectors", "Port restrictions", "Hostname/FQDN egress rules — the API takes CIDRs only"], answer: 2,
    explain: "'Allow calls to api.stripe.com' needs an egress proxy enforcing an L7 allowlist, or non-portable CNI extensions." },
]},
{ title: "Quiz 5 · ConfigMaps, Secrets & Storage",
  desc: "Update semantics, encryption at rest, reclaim policies, access modes and CSI limits",
  questions: [
  { q: "A Kubernetes Secret differs from a ConfigMap chiefly in that it is…", options: ["Encrypted", "base64-encoded with separate RBAC verbs — plaintext in etcd unless encryption at rest is configured", "Stored outside the cluster"], answer: 1,
    explain: "Read straight out of etcd as plaintext, and present in every snapshot taken before encryption was enabled." },
  { q: "A ConfigMap consumed as environment variables updates when the ConfigMap changes…", options: ["Immediately", "Never — env vars are injected once at container start", "Within about a minute"], answer: 1,
    explain: "A mounted directory updates in ~60 s via an atomic symlink swap; subPath mounts never update at all." },
  { q: "Even when a mounted config file DOES update, the application usually…", options: ["Reloads automatically", "Crashes", "Keeps whatever it parsed at start-up unless it watches the file or handles SIGHUP"], answer: 2,
    explain: "'Config updates live' is a property of the filesystem, not of your service." },
  { q: "Setting immutable: true on a ConfigMap gives you…", options: ["Accidental-change protection AND a performance win — kubelets stop watching the object", "Encryption", "Automatic versioning"], answer: 0,
    explain: "It also forces the content-hashed name pattern, which is what makes rollback restore image and config together." },
  { q: "Enabling encryption at rest re-encrypts existing Secrets…", options: ["Immediately", "No — they must be rewritten, e.g. kubectl get secrets -A -o json | kubectl replace -f -", "After 24 hours"], answer: 1,
    explain: "Also note a local aescbc key protects a stolen backup but not a stolen control-plane disk; KMS v2 covers both." },
  { q: "A ServiceAccount granted create pods but explicitly denied get secrets can…", options: ["Only read its own token", "Read every Secret in the namespace by mounting it in a pod", "Read nothing"], answer: 1,
    explain: "The kubelet mounts the Secret on the pod's behalf. The namespace, not the RBAC verb, is the real secret boundary." },
  { q: "ConfigMaps are limited to roughly…", options: ["No limit", "1 MB per object, because etcd bounds object size", "10 MB"], answer: 1,
    explain: "They are not a file server. Large data belongs in an image layer, a volume, or object storage." },
  { q: "The strongest approach to credentials for cloud APIs is…", options: ["Workload identity — a projected token federated to cloud IAM, so no stored credential exists", "An encrypted Secret", "A ConfigMap"], answer: 0,
    explain: "Measured as a ~1-hour token with no access key to leak or rotate. Its trust policy must pin both namespace and ServiceAccount name." },
  { q: "An emptyDir volume with no sizeLimit can…", options: ["Not exceed 1 GB", "Fill the node's disk and cause DiskPressure evictions of UNRELATED pods", "Only affect its own pod"], answer: 1,
    explain: "Measured: an innocent pod evicted. With sizeLimit set, only the offender is evicted and the node never came under pressure." },
  { q: "An emptyDir with medium: Memory counts against…", options: ["The pod's MEMORY limit — exceeding it is an OOM kill", "Nothing", "The node's disk quota"], answer: 0,
    explain: "tmpfs pages are charged to the cgroup, so a 400 MB write in a 256Mi-limited pod is OOMKilled." },
  { q: "The default StorageClass reclaimPolicy on most managed clusters is…", options: ["Delete — deleting the PVC destroys the disk at the cloud provider", "Retain", "Recycle"], answer: 0,
    explain: "One kubectl delete pvc, one helm uninstall, or a namespace cleanup, and the data is gone — not detached, destroyed." },
  { q: "volumeBindingMode: WaitForFirstConsumer exists because…", options: ["It saves storage", "Immediate binding can provision the volume in a zone where the pod cannot be scheduled", "It is faster"], answer: 1,
    explain: "The symptom is a permanently Pending pod with 'volume node affinity conflict'. A Pending PVC under WaitForFirstConsumer is correct behaviour." },
  { q: "ReadWriteOnce actually means the volume may be mounted read-write by…", options: ["One container", "One NODE — any number of pods on that node", "One pod"], answer: 1,
    explain: "Verified: two pods on the same node both wrote 100 interleaved lines. ReadWriteOncePod is the mode people think RWO is." },
  { q: "A rolling update that places the new pod on a DIFFERENT node from an RWO volume produces…", options: ["Data corruption", "A Multi-Attach error and a stuck ContainerCreating", "Silent success"], answer: 1,
    explain: "It looks like a storage bug and is a strategy mismatch — the same RWO semantics that allow two writers on one node." },
  { q: "CSI attach limits (about 25 volumes per node on EBS) matter because…", options: ["They slow down mounts", "They cap pod density long before CPU or memory does — 'exceed max volume count'", "They limit volume size"], answer: 1,
    explain: "Measured with the node at 17% CPU and 26% memory. No utilisation dashboard shows attach slots." },
  { q: "Volume expansion is…", options: ["Online and ONE-WAY — shrinking, class changes and access-mode changes are all rejected", "Only possible offline", "Bidirectional"], answer: 0,
    explain: "Expanding on a class without allowVolumeExpansion is accepted and silently never happens — look for the ExternalExpanding warning." },
  { q: "After a node dies with an RWO volume attached, the replacement pod typically waits…", options: ["Until manually intervened", "About 12 minutes — 40 s to NotReady, 300 s toleration, then a ~6-minute force-detach", "Seconds"], answer: 1,
    explain: "The out-of-service taint recovers in seconds, but only when the node is verifiably dead — on a partitioned node it permits two writers." },
  { q: "A VolumeSnapshot is not a backup because…", options: ["It cannot be restored", "It lives in the same account and region, and is crash-consistent unless the database is quiesced", "It is too slow to restore"], answer: 1,
    explain: "Treat snapshots as fast rollback; real backups go elsewhere with engine-native tooling and are restore-tested." },
  { q: "A PVC stuck in Terminating usually holds which finalizer?", options: ["storage-protection", "kubernetes.io/pvc-protection — a pod still mounts it", "foregroundDeletion"], answer: 1,
    explain: "Delete the pod and the controller removes the finalizer itself. Force-patching it leaks the underlying disk." },
  { q: "A non-root pod hitting 'permission denied' on a fresh volume is fixed with…", options: ["runAsUser: 0", "A hostPath mount", "fsGroup in the pod's securityContext, or chowning the directory in the image"], answer: 2,
    explain: "Named volumes are created owned by root; this is the most common blocker when migrating workloads to non-root." },
]},
);
