// CSS quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · CSS Grid",
  desc: "Tracks, fr, minmax, auto-fill, areas, subgrid, placement",
  questions: [
  { q: "repeat(auto-fill, minmax(220px, 1fr)) produces…", options: ["Fixed 220px columns", "As many ≥220px columns as fit, sharing leftover space — responsive with zero media queries", "One column"], answer: 1,
    explain: "The single most useful grid line ever written — card grids without breakpoints." },
  { q: "auto-fill vs auto-fit differ when…", options: ["Never", "There are fewer items than columns: auto-fit collapses empty tracks so items stretch; auto-fill keeps ghost tracks", "Using gap"], answer: 1,
    explain: "Two cards in a wide container: auto-fit makes them wide; auto-fill leaves room for missing cards." },
  { q: "1fr means…", options: ["1 pixel", "One share of the FREE space after fixed tracks and gaps", "100%"], answer: 1,
    explain: "240px 1fr 2fr = fixed sidebar, then leftover split 1:2." },
  { q: "minmax(0, 1fr) instead of plain 1fr prevents…", options: ["Nothing", "Content blowouts — 1fr's implicit min-width:auto refuses to shrink below content", "Gaps"], answer: 1,
    explain: "Grid's version of the flexbox min-width:0 fix; long words/URLs stop breaking the layout." },
  { q: "grid-column: 1 / -1 spans…", options: ["One column", "From the first line to the LAST — full width regardless of column count", "Columns 1 and -1"], answer: 1,
    explain: "Negative line numbers count from the end — resilient to track-count changes." },
  { q: "grid-template-areas' killer feature is…", options: ["Performance", "The layout is VISIBLE in the CSS and re-mappable per breakpoint by redrawing the map", "Animation"], answer: 1,
    explain: "\"header header\" / \"nav main\" — the stylesheet is its own diagram." },
  { q: "grid-auto-rows controls…", options: ["Explicit rows", "The size of IMPLICIT rows created when content exceeds the template", "Row gaps"], answer: 1,
    explain: "Content beyond your defined rows lands in auto-generated tracks — this sizes them." },
  { q: "subgrid solves…", options: ["Nested scrolling", "Aligning card INTERNALS (title/body/button rows) across sibling cards", "Grid in flex"], answer: 1,
    explain: "Children adopt the parent's tracks: every card's button row aligns regardless of content length." },
  { q: "place-items: center is shorthand for…", options: ["justify-content + align-content", "align-items + justify-items — the 2-word centering of grid children", "text-align"], answer: 1,
    explain: "display:grid; place-items:center centers one child both ways — shortest centering in CSS." },
  { q: "justify-content in grid (vs justify-items) moves…", options: ["Items in their cells", "The whole TRACK GRID within the container when tracks don't fill it", "Text"], answer: 1,
    explain: "items = content within cells; content = the grid itself. Same pattern as align-*." },
  { q: "Explicit item placement (grid-row/column) vs source order:", options: ["Always match", "Placement is free — but keyboard/screen-reader order still follows DOM (a11y caution, same as flex order)", "Placement changes DOM"], answer: 1,
    explain: "Visual position ≠ reading order. Large divergences confuse keyboard users." },
  { q: "The named-lines syntax [sidebar-start] 240px [sidebar-end main-start] 1fr…", options: ["Is decorative", "Lets you place items by meaningful names instead of numbers", "Renames areas"], answer: 1,
    explain: "grid-column: main; reads better and survives track insertions." },
  { q: "A 12-column design-system grid is…", options: ["repeat(12, 1fr) with items spanning via grid-column: span n", "Twelve nested divs", "Impossible without a framework"], answer: 0,
    explain: "Bootstrap's core, natively: one line of template, spans per item." },
  { q: "grid-template-columns: repeat(3, 1fr) vs 33.33% ×3:", options: ["Identical", "fr accounts for gap automatically; percentages + gap overflow the container", "Percent is faster"], answer: 1,
    explain: "fr distributes space AFTER gaps; percentages don't know gaps exist — the overflow class of bugs." },
  { q: "Masonry-style layouts in pure grid are…", options: ["display: masonry (standardized, universal)", "Emerging (grid-template-rows: masonry behind flags) — production uses JS or column hacks today", "Impossible forever"], answer: 1,
    explain: "Know the status: specced and partially implemented; check support before promising it." },
  { q: "An item with grid-area: header but no such area defined…", options: ["Is removed", "Creates implicit named lines — usually landing somewhere surprising", "Throws an error"], answer: 1,
    explain: "CSS never errors loudly; typos in area names cause silent misplacement. DevTools' grid overlay reveals it." },
  { q: "dense in grid-auto-flow: row dense…", options: ["Compresses gaps", "Backfills holes with later smaller items — order visually scrambles (a11y caution)", "Sorts by size"], answer: 1,
    explain: "Great for photo walls where order is meaningless; risky for content where order matters." },
  { q: "Grid vs flexbox in one sentence:", options: ["Grid is newer, use it always", "Grid: container-driven 2D layout; Flex: content-driven 1D distribution — they compose", "Flex is faster"], answer: 1,
    explain: "Page shell in grid, toolbar innards in flex. Layers, not rivals." },
  { q: "Debugging grid placement is best done with…", options: ["console.log", "DevTools grid badge overlay — line numbers, area names, gaps visualized", "Border hacks"], answer: 1,
    explain: "Firefox and Chrome both ship first-class grid inspectors; build with them open." },
  { q: "aspect-ratio on grid cards + object-fit: cover on their images gives…", options: ["Stretched images", "Uniform card media that crops gracefully at any size", "Slow rendering"], answer: 1,
    explain: "The standard recipe for image grids that stay tidy with arbitrary photos." }
]},

{ title: "Quiz 7 · Responsive & Media Queries",
  desc: "Mobile-first, breakpoints, preference queries, fluid techniques",
  questions: [
  { q: "Mobile-first means base styles are…", options: ["For desktop, min-width queries subtract", "For mobile, min-width queries ADD complexity as space grows", "Written twice"], answer: 1,
    explain: "Adding is safer than undoing — desktop-first max-width stylesheets accumulate override bugs." },
  { q: "Breakpoints should be chosen by…", options: ["iPhone model widths", "Where YOUR content breaks — resize until the layout fails, set the query there", "Round numbers only"], answer: 1,
    explain: "768/1024 are conventions, not laws. Content-driven breakpoints survive new devices." },
  { q: "Without the viewport meta tag, media queries on phones…", options: ["Work normally", "Never fire — the browser renders a 980px virtual page and zooms out", "Fire twice"], answer: 1,
    explain: "The HTML and CSS layers meet here: no meta viewport, no responsive design." },
  { q: "prefers-reduced-motion: reduce should…", options: ["Be ignored — animations are brand", "Disable/shrink animations — vestibular disorders make motion physically unpleasant", "Only affect autoplay video"], answer: 1,
    explain: "A hard accessibility requirement; provide a near-instant transition path." },
  { q: "prefers-color-scheme: dark enables…", options: ["Forcing dark mode on users", "FOLLOWING the OS theme — pair with a manual toggle that wins via [data-theme]", "Battery savings only"], answer: 1,
    explain: "The production pattern: OS preference as default, explicit user choice as override." },
  { q: "@media (hover: none) targets…", options: ["Broken mice", "Touch-primary devices — hide hover-dependent affordances there", "Old browsers"], answer: 1,
    explain: "Hover-revealed buttons are unreachable on touch; pointer/hover queries detect input capability, not screen size." },
  { q: "The fluid techniques that REPLACE most media queries are…", options: ["More breakpoints", "auto-fill grids, clamp() type, max-width:100% media, flex wrapping", "JS resize listeners"], answer: 1,
    explain: "Intrinsically flexible first; queries only for what remains (usually page-shell changes)." },
  { q: "A data table too wide for phones should…", options: ["Shrink font to 8px", "Scroll horizontally inside its own overflow-x:auto wrapper", "Be deleted"], answer: 1,
    explain: "The page must never scroll sideways; the table scrolls within itself." },
  { q: "Range syntax @media (400px <= width <= 800px)…", options: ["Is invalid", "Is the modern readable form of min-/max-width pairs", "Only works in JS"], answer: 1,
    explain: "Supported across modern browsers; especially nice for exclusive bands (no double-apply at boundaries)." },
  { q: "Testing responsive work honestly requires…", options: ["DevTools only", "DevTools for iteration + at least one REAL phone (URL bars, notches, touch targets)", "A resize plugin"], answer: 1,
    explain: "Emulators don't reproduce browser chrome behavior, safe areas, or fat fingers." },
  { q: "env(safe-area-inset-bottom) exists for…", options: ["CSS variables", "iPhone home-bar/notch padding so content isn't obscured", "Android only"], answer: 1,
    explain: "Fixed bottom bars need it; pairs with viewport-fit=cover." },
  { q: "print stylesheets typically…", options: ["Are obsolete", "Hide nav/sidebar/ads, expand link URLs, force light colors — @media print", "Only change fonts"], answer: 1,
    explain: "Invoices, tickets, docs get printed; a 20-line print sheet is high-leverage polish." },
  { q: "Images that must never overflow their container need…", options: ["width: 100vw", "max-width: 100%; height: auto", "overflow: hidden"], answer: 1,
    explain: "The fluid-media rule in every reset; height:auto preserves ratio alongside the width/height attributes." },
  { q: "prefers-contrast / forced-colors matter because…", options: ["They're trendy", "High-contrast/forced-color users get YOUR colors stripped — test that UI remains comprehensible", "They boost SEO"], answer: 1,
    explain: "Windows High Contrast Mode replaces your palette with system colors; borders and outlines carry the UI." },
  { q: "A hamburger menu below 768px, inline links above, is best implemented…", options: ["Two HTMLs", "One markup, CSS shows/hides + a11y state (aria-expanded) on the toggle", "JS-generated nav"], answer: 1,
    explain: "Same DOM, responsive presentation, and the toggle button carries proper ARIA." },
  { q: "vw-based full-bleed sections inside a centered column use…", options: ["position: absolute", "width:100vw; margin-inline: calc(50% - 50vw) (or the modern breakout grid)", "Negative padding"], answer: 1,
    explain: "The classic 'escape the container' technique — beware scrollbar-width jitter (scrollbar-gutter helps)." },
  { q: "Device pixel ratio (2x/3x screens) affects…", options: ["CSS pixel math directly", "Which srcset/density image the browser downloads — CSS px stay logical", "Font rendering only"], answer: 1,
    explain: "CSS pixels are density-independent; imagery is where DPR matters (x descriptors / w+sizes)." },
  { q: "orientation: landscape queries are best for…", options: ["Primary layout logic", "Edge adjustments (short landscape phones) — width/height queries carry the main design", "Detecting tablets"], answer: 1,
    explain: "Orientation flips at odd sizes; width-based logic is more predictable." },
  { q: "The 44×44px minimum applies to…", options: ["Icons' artwork", "Touch TARGETS — padding can supply it even if the glyph is small", "Buttons only"], answer: 1,
    explain: "A 16px icon inside a 44px padded hit area satisfies the guideline." },
  { q: "Media queries in JS (matchMedia) are for…", options: ["Styling", "Behavior changes tied to the same breakpoints (swap components, disable drag) — keep the values shared via tokens", "Replacing CSS queries"], answer: 1,
    explain: "One source of truth for breakpoints, consumed by both CSS and matchMedia listeners." }
]},

{ title: "Quiz 8 · Animations & Custom Properties",
  desc: "Transitions, keyframes, compositor performance, variables, theming",
  questions: [
  { q: "The two properties that animate at 60fps without layout work are…", options: ["width and height", "transform and opacity", "top and left"], answer: 1,
    explain: "They run on the compositor thread — smooth even while JS is busy. Layout properties reflow the page per frame." },
  { q: "A sliding drawer should animate…", options: ["left: -300px → 0", "transform: translateX(-100%) → 0", "margin-left"], answer: 1,
    explain: "Same visual, different pipeline: transform composites; left forces layout every frame." },
  { q: "transition: all is discouraged because…", options: ["Invalid syntax", "It animates properties you didn't intend (including layout ones) and surprises later editors", "It's slower to type"], answer: 1,
    explain: "Name the properties: transition: background-color .15s, transform .15s." },
  { q: "Hover feedback duration that feels right is…", options: ["~50ms", "100–200ms (300+ for panels/modals)", "1s"], answer: 1,
    explain: "Too fast reads as flicker, too slow as lag. Motion design has conventions — use them." },
  { q: "@keyframes with 0%,100% { opacity:1 } 50% { opacity:.35 } + infinite creates…", options: ["A flash", "A skeleton-loading pulse", "A fade-out"], answer: 1,
    explain: "The standard loading shimmer — cheap (opacity only) and informative." },
  { q: "animation-play-state: paused is useful for…", options: ["Debugging only", "Pausing loops when the tab/section is hidden — battery and CPU respect", "Slow motion"], answer: 1,
    explain: "IntersectionObserver + paused state = animations only when visible." },
  { q: "prefers-reduced-motion handling in one rule:", options: ["Impossible", "@media (prefers-reduced-motion: reduce) { * { animation-duration:.01ms !important; transition-duration:.01ms !important } }", "JS only"], answer: 1,
    explain: "The blanket kill-switch — one of the few righteous uses of !important." },
  { q: "Animating box-shadow smoothly is best done by…", options: ["shadow keyframes", "A pseudo-element with the shadow, animating ITS opacity", "will-change"], answer: 1,
    explain: "Shadow interpolation repaints expensively; opacity on a pre-painted shadow composites." },
  { q: "will-change should be…", options: ["On everything animated", "Applied sparingly, just before animation, removed after — each use costs memory", "In every reset"], answer: 1,
    explain: "It pre-promotes layers; blanket use bloats GPU memory and can slow the page." },
  { q: "The View Transitions API gives you…", options: ["Route-change/DOM-change crossfades and morphs with a line of code", "3D transforms", "Faster JS"], answer: 0,
    explain: "document.startViewTransition(cb) — the platform's answer to app-like page transitions." },
  { q: "--brand: #2f8d46 differs from a Sass $variable because…", options: ["Syntax only", "It LIVES at runtime: inheritable, scope-able, changeable by JS/media queries; Sass compiles away", "It's slower"], answer: 1,
    explain: "Runtime variables enable theming, density modes, and JS-driven values Sass fundamentally can't do." },
  { q: "var(--surface, #fff) — the second argument is…", options: ["A unit", "The fallback when --surface is unset/invalid", "A comment"], answer: 1,
    explain: "Fallbacks make components usable outside their design system." },
  { q: "Dark mode's production pattern is…", options: ["A second stylesheet", "Semantic tokens (--bg, --ink) swapped by prefers-color-scheme AND [data-theme] override", "Filter: invert(1)"], answer: 1,
    explain: "Components reference semantics; themes swap values; user toggle beats OS default." },
  { q: "The three-tier token architecture is…", options: ["Random naming", "Raw palette (--green-600) → semantic (--color-action) → component (--btn-bg)", "One flat file"], answer: 1,
    explain: "Rebrand = tier 1; theme = tier 2; components never change. Material/Polaris/Primer all do this." },
  { q: "Custom properties inherit…", options: ["Never", "Like normal inherited properties — set on :root for global, on a subtree for scoped", "Only in shadow DOM"], answer: 1,
    explain: "Scoping (.card { --pad: 2rem }) is how component-level knobs work." },
  { q: "@property registration adds…", options: ["Nothing", "Type + initial value + ANIMATABILITY for a custom property (e.g., animating a gradient angle)", "Encryption"], answer: 1,
    explain: "Unregistered custom properties can't interpolate; @property syntax:'<angle>' unlocks it." },
  { q: "Animating height: auto has historically required hacks; the modern options are…", options: ["Still impossible", "grid-template-rows 0fr→1fr trick, or calc-size()/interpolate-size where supported", "max-height: 9999px is fine"], answer: 1,
    explain: "max-height hacks break timing on tall content; the 0fr trick is the reliable widely-supported answer." },
  { q: "Steps() timing (animation-timing-function: steps(10)) is used for…", options: ["Easing curves", "Sprite-sheet/typewriter frame-by-frame effects", "Performance"], answer: 1,
    explain: "Discrete jumps instead of interpolation — the retro/sprite animation tool." },
  { q: "JS reads/writes custom properties via…", options: ["el.style.vars", "getComputedStyle(el).getPropertyValue('--x') / el.style.setProperty('--x', v)", "dataset"], answer: 1,
    explain: "The bridge that lets JS drive theming, cursors-following-gradients, data-driven charts." },
  { q: "A theme toggle that must not flash wrong-theme on load should…", options: ["Wait for React", "Set [data-theme] from localStorage in a tiny inline HEAD script before CSS paints", "Use a cookie only"], answer: 1,
    explain: "The FOUC-of-themes fix: decide the theme synchronously before first paint." }
]},

{ title: "Quiz 9 · Modern CSS (Containers, Layers, :has())",
  desc: "Container queries, cascade layers, :has(), nesting, new selectors",
  questions: [
  { q: "Container queries beat media queries when…", options: ["Always", "A component must adapt to ITS OWN space (sidebar vs main column on the same page)", "On mobile"], answer: 1,
    explain: "Media queries see only the viewport; design-system components live in many container sizes at once." },
  { q: "container: card / inline-size on a wrapper does what?", options: ["Styles the card", "Names a containment context and measures its WIDTH for @container queries", "Adds scrolling"], answer: 1,
    explain: "Children then use @container card (min-width: 420px) { … }." },
  { q: "A container query 'not firing' usually means…", options: ["Browser bug", "The container has no constrained width (children can't dictate it — that would be circular)", "Wrong units"], answer: 1,
    explain: "inline-size containment requires the container's width to come from layout, not content." },
  { q: "cqi units are…", options: ["Quiz units", "1% of the container's inline size — component-relative fluid type", "Viewport units"], answer: 1,
    explain: "clamp(1rem, 5cqi, 1.5rem): typography scaling with the card, not the screen." },
  { q: "@layer's core rule is…", options: ["Layers add specificity", "A LATER layer beats an earlier one regardless of selector specificity", "Alphabetical order"], answer: 1,
    explain: "Priority by policy: @layer reset, base, components, utilities — a simple utility class outguns an ID chain from an earlier layer." },
  { q: "Unlayered styles vs layered:", options: ["Layered win", "UNLAYERED beat all layers — the escape hatch (and migration hazard)", "They error"], answer: 1,
    explain: "When adopting layers, un-migrated CSS silently dominates — move everything or expect surprises." },
  { q: "Third-party CSS you can't edit belongs…", options: ["Last in the file", "Imported INTO a low layer: @import url(lib.css) layer(vendor)", "In an iframe"], answer: 1,
    explain: "Its specificity becomes irrelevant; your components layer always wins." },
  { q: ".field:has(input:invalid) enables…", options: ["Input styling", "Styling the WRAPPER (label, border, icon) based on the input's state — no JS", "Form submission"], answer: 1,
    explain: "The parent selector: error states, checked-card patterns, has-image cards — all CSS now." },
  { q: "body:has(dialog[open]) { overflow: hidden } implements…", options: ["Modal focus trap", "Scroll-locking the page while any modal is open — declaratively", "Backdrop blur"], answer: 1,
    explain: "A whole class of 'toggle a body class from JS' code deleted." },
  { q: ":has() performance guidance:", options: ["Unlimited use", "Keep the anchor narrow (.card:has(…)) — broad div:has()/*:has() re-checks ancestors on every mutation", "Never use it"], answer: 1,
    explain: "Powerful ≠ free; the engine must invalidate upward. Narrow anchors keep it cheap." },
  { q: "Native CSS nesting (& syntax)…", options: ["Requires Sass", "Ships in browsers — component-scoped structure without a build step", "Is invalid"], answer: 1,
    explain: ".card { & .title { } &:hover { } } — Sass's killer feature, standardized." },
  { q: "Deep nesting (4+ levels) is discouraged because…", options: ["It errors", "It couples CSS to DOM structure and compounds specificity — same lesson as descendant selectors", "It's slow to parse"], answer: 1,
    explain: "Nesting is organization sugar; the flat-specificity discipline still applies." },
  { q: ":focus-visible vs :focus:", options: ["Identical", ":focus-visible shows rings for keyboard/AT users but not mouse clicks — ending the 'designers hate outlines' war", ":focus is deprecated"], answer: 1,
    explain: "Style :focus-visible boldly; everyone wins." },
  { q: "@scope provides…", options: ["Faster selectors", "Style boundaries (scope root + optional lower limit) without renaming classes", "Shadow DOM"], answer: 1,
    explain: "@scope (.card) to (.card-content) — styles that apply within a region and STOP at slots." },
  { q: "color-mix(in oklch, var(--brand), white 20%) computes…", options: ["A gradient", "A LIGHTER brand tint at runtime — hover states without exporting new hexes", "Transparency"], answer: 1,
    explain: "Runtime color math + tokens = tint/shade scales generated from one source color." },
  { q: "The :popover-open / popover attribute pair gives…", options: ["Tooltips via JS", "Native top-layer popovers with light-dismiss — no z-index management", "Modals only"], answer: 1,
    explain: "popover + popovertarget wire up dropdown behavior with zero JavaScript." },
  { q: "text-wrap: balance / pretty are examples of…", options: ["Experimental toys", "Typography intelligence moving into the engine — heading balance, orphan control", "Print-only features"], answer: 1,
    explain: "One-property upgrades; know they exist and apply them to headings/paragraphs." },
  { q: "@supports selector(:has(a)) is used to…", options: ["Speed up :has()", "Feature-detect SELECTOR support and provide fallbacks", "Polyfill"], answer: 1,
    explain: "Progressive enhancement for selector-level features, parallel to property-level @supports." },
  { q: "The scientific way to adopt modern features is…", options: ["Use everything immediately", "Check Baseline/caniuse against YOUR support policy; enhance progressively", "Wait 10 years"], answer: 1,
    explain: "'Baseline widely available' is the green light for most products; a written support policy ends debates." },
  { q: "Style queries (@container style(--theme: dark))…", options: ["Query computed colors", "Condition children on a parent's CUSTOM PROPERTY value — context-aware components", "Replace classes"], answer: 1,
    explain: "The frontier: components restyling by declared context, not just size." }
]},

{ title: "Quiz 10 · The Mock Exam (Architecture, Performance & A11y)",
  desc: "20 mixed exam-level questions — the whole track, interview difficulty",
  questions: [
  { q: "BEM's .card__title--featured encodes…", options: ["Three elements", "Block card, element title, modifier featured — flat (0,1,0) specificity by design", "A Sass function"], answer: 1,
    explain: "The naming IS the architecture: unique, greppable, never needs nesting to be unambiguous." },
  { q: "Your utility .hidden loses to a component's #app .modal .content. The architectural fix:", options: ["!important everywhere", "Cascade layers with utilities LAST — layer order beats specificity", "Rename classes"], answer: 1,
    explain: "@layer components, utilities makes every utility beat every component selector, by policy." },
  { q: "A design system bans raw hex values in components via…", options: ["Code review vigilance", "Stylelint rules rejecting non-token colors — consistency as build failure", "Trust"], answer: 1,
    explain: "Automation beats discipline: what CI enforces, nobody debates." },
  { q: "The page's CSS is 900KB, 82% unused (per Coverage tab). First move:", options: ["Minify harder", "Purge unused rules via build tooling and split by route", "Inline it all"], answer: 1,
    explain: "Unused CSS still blocks rendering: parse cost + network. Purge, split, then inline the critical slice." },
  { q: "Critical CSS means…", options: ["Important styles", "Inlining above-the-fold styles in <head>, loading the rest async — first paint without waiting on the network", "CSS with !important"], answer: 1,
    explain: "News/e-commerce sites paint headlines in <1s this way." },
  { q: "An animation stutters while JS crunches data. Diagnosis:", options: ["Need a faster GPU", "It animates layout properties on the main thread — move to transform/opacity (compositor)", "Too many colors"], answer: 1,
    explain: "Compositor animations survive main-thread congestion; layout animations die with it." },
  { q: "content-visibility: auto on long comment sections…", options: ["Hides them", "Skips render work for off-screen content — with contain-intrinsic-size reserving scroll space", "Lazy-loads images"], answer: 1,
    explain: "Often halves initial rendering cost on long pages; the placeholder size prevents scrollbar jumps." },
  { q: "Layout thrashing is…", options: ["Too many divs", "Alternating DOM reads (offsetHeight) and writes in a loop — forcing layout per iteration", "Large stylesheets"], answer: 1,
    explain: "Batch: read everything, then write everything. Purple 'Layout' storms in the Performance panel confirm it." },
  { q: "A component works in the app but breaks on a customer's site (embedded widget). The robust isolation is…", options: ["More specific selectors", "Shadow DOM (style encapsulation both ways) — the web-component embed pattern", "!important on everything"], answer: 1,
    explain: "Hostile-host CSS can't pierce the shadow boundary; your styles can't leak out either." },
  { q: "Focus ring policy for a polished product:", options: ["outline: none globally", ":focus-visible { outline: 2px solid var(--brand); outline-offset: 2px }", "Browser default only"], answer: 1,
    explain: "Keyboard users get clear rings; mouse users aren't bothered; WCAG satisfied." },
  { q: "Text must survive 200% zoom without loss. This requires…", options: ["Bigger fonts", "rem-based sizing + no fixed-height text containers that clip", "A zoom polyfill"], answer: 1,
    explain: "WCAG 1.4.4: fixed px heights clip enlarged text — min-height and flexible containers instead." },
  { q: "Windows High Contrast (forced-colors) strips your palette. UI must then rely on…", options: ["Filters", "Structure: borders, outlines, system colors — test with forced-colors: active", "SVG backgrounds"], answer: 1,
    explain: "If state was only a background-color change, it vanishes; borders and text carry meaning." },
  { q: "Which stack respects BOTH OS dark mode and a user's explicit toggle?", options: ["prefers-color-scheme alone", "Semantic tokens + prefers-color-scheme default + [data-theme] attribute override", "Two CSS files"], answer: 1,
    explain: "Attribute (user choice) must out-cascade the media query (OS default) — order/specificity arranged deliberately." },
  { q: "A teammate proposes vw-only font sizing 'for fluidity'. You flag…", options: ["Nothing", "Zoom/user-font-size accessibility breakage — clamp() with rem terms is the compliant fluid pattern", "Rendering cost"], answer: 1,
    explain: "Pure-viewport type ignores user text preferences and can pin zoom — a WCAG 1.4.4 failure." },
  { q: "The Coverage tab + per-route code splitting attack which metric?", options: ["INP only", "Render-blocking CSS/JS bytes → faster FCP/LCP", "CLS"], answer: 1,
    explain: "Ship less to parse before paint — the highest-leverage loading lever." },
  { q: "gap vs margins between cards in review:", options: ["Stylistic tie", "gap — container-declared spacing, no collapsing/last-child hacks, wrap-safe", "margins — more control"], answer: 1,
    explain: "Spacing policy belongs to the layout container, not negotiated per child." },
  { q: "Your modal library needs no z-index at all because…", options: ["Low z-index everywhere", "It uses <dialog>/top layer — above all stacking contexts by spec", "It's an iframe"], answer: 1,
    explain: "Top layer ended modal z-index wars; adopt platform primitives before inventing." },
  { q: "Container queries' architectural significance is…", options: ["Fewer keystrokes", "Components become truly context-independent — publishable to a design system without viewport assumptions", "Faster rendering"], answer: 1,
    explain: "The same ProductCard adapts in sidebar, main, or modal — reusability media queries never allowed." },
  { q: "The single most award-worthy CSS habit this track taught:", options: ["Memorizing properties", "Tokens + flat specificity + layers: a SYSTEM where the 1000th component looks like the 1st", "Using the newest features"], answer: 1,
    explain: "Architecture over memorization: consistency, theming, and maintainability all fall out of the system. 🏆" },
  { q: "Ship-blocking CSS review checklist includes…", options: ["Tabs vs spaces", "Focus states, contrast in both themes, reduced-motion path, no raw values, wide-content overflow handling", "Alphabetized properties"], answer: 1,
    explain: "Five checks that catch 90% of real-world CSS defects before users do." }
]}
);
