// CSS quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Selectors & Specificity",
  desc: "Selector types, combinators, specificity scoring, the cascade",
  questions: [
  { q: "Specificity of .card .title vs #main — which wins?", options: [".card .title (two classes)", "#main (one ID beats any number of classes)", "Whichever is later in the file"], answer: 1,
    explain: "Compare (ID, CLASS, ELEMENT) left to right: (1,0,0) > (0,2,0). Count of lower tiers never beats a higher tier." },
  { q: "When two rules have EQUAL specificity, the winner is…", options: ["The shorter one", "The one later in the stylesheet (source order)", "Alphabetical"], answer: 1,
    explain: "That's the 'cascading' in CSS — last equal rule wins." },
  { q: ".btn:hover has specificity…", options: ["(0,1,0)", "(0,2,0) — pseudo-classes count as a class", "(0,1,1)"], answer: 1,
    explain: "Pseudo-classes (:hover, :focus, :nth-child) each count at class level; pseudo-ELEMENTS (::before) count at element level." },
  { q: ":where(.card) p has specificity…", options: ["(0,1,1)", "(0,0,1) — :where() contributes ZERO", "(0,2,0)"], answer: 1,
    explain: "That's its purpose: design systems ship overridable defaults with it. :is() takes its most specific argument instead." },
  { q: "The child combinator .nav > a selects…", options: ["All descendants", "Direct children only", "The first link"], answer: 1,
    explain: "Space = any depth descendant; > = one level; + = next sibling; ~ = all later siblings." },
  { q: "li:nth-child(2n) selects…", options: ["Every 2nd li… IF li is the child at those positions", "The 2nd li always", "Two lists"], answer: 0,
    explain: "nth-child counts ALL siblings by position; nth-of-type counts only elements of that type — the classic gotcha." },
  { q: "input:user-invalid vs input:invalid —", options: ["Identical", ":user-invalid applies only AFTER the user interacted — no red errors on pristine forms", ":invalid is deprecated"], answer: 1,
    explain: "Styling :invalid alone flags required fields as errors before the user typed anything." },
  { q: "!important should be reserved for…", options: ["Fixing anything quickly", "Utility classes that must always win (.hidden) — and little else", "Third-party overrides only"], answer: 1,
    explain: "Each !important escalates the arms race; the next override needs another one. Utilities are the one legitimate systemic use." },
  { q: "Inline style=\"…\" loses only to…", options: ["IDs", "!important declarations", "Later stylesheets"], answer: 1,
    explain: "Cascade order: importance > inline > specificity > source order." },
  { q: "a:visited styling is limited by browsers because…", options: ["It's slow", "History sniffing — sites could detect where you've been", "It's deprecated"], answer: 1,
    explain: "Only color-ish properties allowed, and getComputedStyle lies about them. A privacy boundary, not a bug." },
  { q: "The universal reset *, *::before, *::after { box-sizing: border-box } has specificity…", options: ["(0,0,0) — anything overrides it", "(0,1,0)", "It's !important implicitly"], answer: 0,
    explain: "* contributes nothing — which is exactly why resets use it: they never fight your real styles." },
  { q: "Attribute selector [type=\"email\"] counts as…", options: ["An element", "A class-level selector", "An ID-level selector"], answer: 1,
    explain: "Attribute selectors and pseudo-classes both weigh in at the class tier." },
  { q: "Keeping specificity FLAT in a codebase means…", options: ["No selectors", "Styling with single classes; avoiding IDs and deep descendant chains", "Using !important consistently"], answer: 1,
    explain: "#sidebar div.widget ul li a (1,3,3) is unoverridable without escalation; .widget-link (0,1,0) is maintainable." },
  { q: ".dark .card .title beats .card__title because…", options: ["It's more readable", "(0,3,0) > (0,1,0) — which is exactly why BEM prefers the flat single class", "It doesn't"], answer: 1,
    explain: "Flat naming (BEM) exists to keep every selector at (0,1,0) so overrides stay trivial." },
  { q: "To debug 'why isn't my style applying', the fastest tool is…", options: ["Adding !important and testing", "DevTools Styles panel — shows matching rules, crossed-out losers, and the winner", "Rewriting the selector"], answer: 1,
    explain: "It answers specificity questions in seconds, including which rule won and from which file/line." },
  { q: ":is(.article, .aside) :is(h2, h3) replaces how many plain selectors?", options: ["2", "4 (.article h2, .article h3, .aside h2, .aside h3)", "8"], answer: 1,
    explain: "Grouping without combinatorial explosion — that's :is()'s job." },
  { q: "The selector div:has(> img) selects…", options: ["The img", "The div that directly contains an img — a parent selector at last", "All imgs in divs"], answer: 1,
    explain: ":has() selects the ANCHOR element based on what's inside it — 25 years of wishing, delivered." },
  { q: "Class names are case-…", options: ["Insensitive", "Sensitive (.Card ≠ .card)", "Sensitive only in strict mode"], answer: 1,
    explain: "HTML tag names are case-insensitive but class/id values are case-sensitive in selectors." },
  { q: "Which selector is INVALID and kills its whole rule (pre-@supports)?", options: [".a, .b", ".card:hover", ".a, :unknown-pseudo"], answer: 2,
    explain: "One invalid selector in a comma list invalidates the entire rule in older engines — :is() is forgiving; plain lists are not." },
  { q: "Specificity of the selector inside :not(.foo) is…", options: ["Zero", "Counted — :not() takes the specificity of its argument", "Element-level"], answer: 1,
    explain: ":not(), :is(), :has() contribute their argument's specificity; only :where() zeroes it." }
]},

{ title: "Quiz 2 · Box Model & Display",
  desc: "border-box, margins, collapsing, display values, overflow",
  questions: [
  { q: "With box-sizing: border-box, width: 300px means…", options: ["Content = 300px, padding/border extra", "Content + padding + border = 300px", "Everything incl. margin = 300px"], answer: 1,
    explain: "Margin is NEVER inside width in either model. border-box is the universal production default." },
  { q: "Default (content-box): .card { width: 300px; padding: 20px; border: 1px } renders how wide?", options: ["300px", "342px (300 + 40 + 2)", "320px"], answer: 1,
    explain: "This surprise is why every stylesheet starts with the border-box reset." },
  { q: "Two stacked paragraphs each with margin: 24px 0 have a gap of…", options: ["48px", "24px — vertical margins COLLAPSE to the larger", "0"], answer: 1,
    explain: "Collapsing applies to block flow only; flex/grid children never collapse margins (one reason gap is preferred)." },
  { q: "The classic centering for a fixed-width block is…", options: ["margin: 0 auto", "text-align: center", "position: center"], answer: 0,
    explain: "auto side margins split the leftover space. text-align centers INLINE content, not the block itself." },
  { q: "display: none vs visibility: hidden —", options: ["Identical", "none removes the box entirely; hidden keeps the space reserved", "hidden is faster"], answer: 1,
    explain: "Both also remove content from the accessibility tree — for screen-reader-visible hiding use the .sr-only clip pattern." },
  { q: "width/height on an inline element (span)…", options: ["Work normally", "Are ignored — inline boxes size to their content", "Apply to the line"], answer: 1,
    explain: "That's why inline-block exists: flows in text but respects box properties." },
  { q: "margin: 8px 16px 24px 4px applies in order…", options: ["left right top bottom", "top right bottom left (clockwise)", "top bottom left right"], answer: 1,
    explain: "Clockwise from the top. Two values = vertical | horizontal." },
  { q: "padding-inline (vs padding-left/right) exists because…", options: ["It's shorter", "Logical properties flip automatically for RTL languages (Arabic, Hebrew)", "Performance"], answer: 1,
    explain: "inline = text-flow axis, block = stacking axis. International products use logical properties." },
  { q: "Percentage padding (padding-top: 56.25%) resolves against…", options: ["The element's height", "The parent's WIDTH — basis of the old aspect-ratio hack", "The viewport"], answer: 1,
    explain: "All four padding/margin percentages use parent width. Modern code uses aspect-ratio: 16/9 instead." },
  { q: "A child's margin-top 'leaking' outside its parent (parent doesn't move, child does) is…", options: ["A browser bug", "Margin collapsing through the parent — fix with parent padding/border or display:flow-root", "float behavior"], answer: 1,
    explain: "Adjacent parent/first-child top margins collapse when nothing separates them." },
  { q: "overflow: hidden on a container…", options: ["Just clips", "Clips AND creates a new formatting context (contains floats, stops margin collapse)", "Scrolls"], answer: 1,
    explain: "The side effects were historically used as hacks; display:flow-root does the context part cleanly." },
  { q: "min-width beats max-width beats width when they conflict —", options: ["True: min > max > width", "False, width always wins", "They average"], answer: 0,
    explain: "The resolution order matters when responsive constraints collide." },
  { q: "aspect-ratio: 16/9 on an element…", options: ["Crops it", "Maintains the ratio from the specified dimension — no padding hacks", "Only works on video"], answer: 1,
    explain: "Combine with width:100% for fluid, ratio-stable cards, maps, and embeds." },
  { q: "gap between siblings is preferred over margins because…", options: ["Shorter to type", "No collapsing, no first/last-child exceptions, works in wrap", "It animates"], answer: 1,
    explain: "gap is the container declaring spacing policy once vs each child negotiating its own." },
  { q: "outline differs from border in that outline…", options: ["Is thicker", "Takes NO layout space and may be non-rectangular — perfect for focus rings", "Only supports solid"], answer: 1,
    explain: "That's why focus styles use outline: visibility without layout shift." },
  { q: "box-shadow affects layout…", options: ["Yes, adds size", "Never — purely painted, may overlap neighbors", "Only with spread"], answer: 1,
    explain: "Like outline, shadows don't take space — plan overlap accordingly." },
  { q: "display: inline-block's classic quirk is…", options: ["No padding", "A ~4px gap between elements from literal whitespace in the HTML", "It floats"], answer: 1,
    explain: "The newline between tags renders as a space. Flex/grid containers don't have this problem — another reason they won." },
  { q: "height: 100% on a child requires…", options: ["Nothing", "The parent to have a defined height (or use height chains/flex instead)", "position: absolute"], answer: 1,
    explain: "Percent heights resolve against a DEFINED parent height; undefined → auto. Modern layouts use flex/grid or dvh." },
  { q: "The rendered total width of: width 200px + padding 16px×2 + border 2px×2 + margin 10px×2 (border-box) is…", options: ["200px box + 20px total margin space", "236px", "256px"], answer: 0,
    explain: "border-box absorbs padding+border into the 200px; margins (20px total) sit outside the box as spacing." },
  { q: "position: static elements ignore…", options: ["margin", "top/right/bottom/left and z-index", "display"], answer: 1,
    explain: "Offsets and z-index need a positioned element (relative/absolute/fixed/sticky)." }
]},

{ title: "Quiz 3 · Colors, Units & Typography",
  desc: "Color spaces, rem/em/ch/vw, clamp(), font loading, readability",
  questions: [
  { q: "rem units are relative to…", options: ["The parent's font-size", "The ROOT font-size (html element, 16px default)", "The viewport"], answer: 1,
    explain: "em = parent-relative (compounds when nested); rem = root-relative (predictable) — the default for type & spacing." },
  { q: "Why rem for font sizes instead of px?", options: ["Renders sharper", "Respects users who raise their browser's default font size — an accessibility requirement", "Saves bytes"], answer: 1,
    explain: "px ignores the user's font-size preference (browser zoom still works, but the setting doesn't). WCAG audits check 200% text scaling." },
  { q: "clamp(1.8rem, 4vw, 2.6rem) means…", options: ["Random between bounds", "Fluid 4vw, never below 1.8rem, never above 2.6rem", "Three breakpoints"], answer: 1,
    explain: "Fluid typography without media queries — min, preferred, max." },
  { q: "max-width: 65ch on paragraphs enforces…", options: ["65% width", "~65 characters per line — the readable-measure sweet spot (45–75)", "65 chars hard-wrap"], answer: 1,
    explain: "1ch = width of '0' in the current font. Long lines exhaust eyes; short ones fracture reading rhythm." },
  { q: "line-height: 1.6 (unitless) vs 1.6em —", options: ["Identical", "Unitless re-computes per element's OWN font-size when inherited; em inherits a FIXED computed value", "em is newer"], answer: 1,
    explain: "The em version bites when children change font-size — always use unitless line-height." },
  { q: "100vh on mobile Safari famously…", options: ["Works fine", "Overflows because the URL bar collapses — use 100dvh", "Equals 100%"], answer: 1,
    explain: "dvh (dynamic viewport height) tracks the real visible height as browser chrome shows/hides." },
  { q: "hsl(140 50% 37%) is often preferred over hex in design work because…", options: ["Smaller files", "Hue/saturation/lightness are independently tweakable — dark/light variants are arithmetic", "It's required for animation"], answer: 1,
    explain: "Lightness ±10% = hover states; same hue family = coherent palettes. oklch does this perceptually-uniformly." },
  { q: "oklch's advantage over hsl is…", options: ["Browser support", "Perceptual uniformity — equal lightness values LOOK equally light across hues", "Shorter syntax"], answer: 1,
    explain: "hsl's 50% lightness yellow looks far brighter than 50% blue; oklab/oklch fixed this — the modern palette-building space." },
  { q: "rgb(47 141 70 / 0.8) — the /0.8 is…", options: ["Line-height", "Alpha (opacity of the color)", "A ratio"], answer: 1,
    explain: "Modern space-separated syntax with slash-alpha works in rgb(), hsl(), oklch()." },
  { q: "currentColor refers to…", options: ["The brand color", "The element's computed color value — great for SVG icons matching text", "Black"], answer: 1,
    explain: "border: 1px solid currentColor; svg { fill: currentColor } — icons follow text color automatically." },
  { q: "WCAG minimum contrast for body text is…", options: ["2:1", "4.5:1 (3:1 for large text/UI parts)", "7:1 always"], answer: 1,
    explain: "DevTools' color picker shows the ratio live. Check every token pair in BOTH themes." },
  { q: "The system font stack (system-ui, …) costs…", options: ["One request", "Zero bytes and zero ms — it uses the OS's native UI font", "A license fee"], answer: 1,
    explain: "Ship webfonts only when brand demands; then preload + font-display: swap." },
  { q: "font-display: swap trades…", options: ["Nothing", "A flash of fallback font (FOUT) instead of invisible text (FOIT)", "Quality for speed"], answer: 1,
    explain: "Visible text immediately beats invisible text; size-adjust on the fallback minimizes the swap jump." },
  { q: "Which unit for a 1px hairline border?", options: ["0.06rem", "px — fixed details shouldn't scale with user font size", "em"], answer: 1,
    explain: "px is right where physical precision matters: borders, shadows, tiny radii. Type and spacing: rem." },
  { q: "em padding on a button (padding: .6em 1.2em) gives you…", options: ["Fixed padding", "Padding that scales with the BUTTON's font-size — size variants for free", "Broken layout"], answer: 1,
    explain: "One rule; .btn-lg { font-size: 1.25rem } scales the whole button proportionally." },
  { q: "letter-spacing guidance:", options: ["Negative everywhere", "Slightly negative for large headings; never negative for body text", "Always 0"], answer: 1,
    explain: "Big type has visually loose spacing (tighten ~-0.02em); body text needs its designed spacing to stay legible." },
  { q: "text-wrap: balance is for…", options: ["Justifying paragraphs", "Evening out line lengths in HEADINGS (no 1-word orphan lines)", "Tables"], answer: 1,
    explain: "Headline-quality wrapping in one property; text-wrap: pretty targets paragraph orphans." },
  { q: "A '10px root hack' (html { font-size: 62.5% }) is discouraged because…", options: ["Math is hard", "It breaks the user's chosen default size assumption for every rem in third-party content", "It's invalid"], answer: 1,
    explain: "Modern tooling (design tokens, calc) removed the need for decimal-friendly rem math." },
  { q: "vw units on font-size WITHOUT clamp risk…", options: ["Nothing", "Unreadably small text on phones and huge on 4K — and they ignore user zoom text preferences", "Slow paint"], answer: 1,
    explain: "Always bound fluid type with clamp(min, fluid, max) and include a rem term so zoom works." },
  { q: "Variable fonts are…", options: ["Fonts that change randomly", "One file exposing weight/width axes — replacing several static files", "CSS-generated"], answer: 1,
    explain: "font-variation-settings / font-weight: 100–900 from a single woff2 — fewer requests, smooth weight animation." }
]},

{ title: "Quiz 4 · Positioning & Stacking",
  desc: "position values, containing blocks, z-index, stacking contexts, sticky",
  questions: [
  { q: "position: absolute positions the element against…", options: ["The viewport always", "The nearest NON-STATIC ancestor (or initial containing block if none)", "Its parent always"], answer: 1,
    explain: "Forgetting position:relative on the intended parent = badge flies to a page corner. The #1 positioning bug." },
  { q: "position: sticky requires…", options: ["JavaScript", "An offset (top: 0) and a scrollable ancestor without overflow:hidden between", "position:fixed fallback"], answer: 1,
    explain: "Sticky that 'doesn't work' is almost always an overflow:hidden/auto ancestor or missing offset." },
  { q: "z-index: 9999 loses to z-index: 10 when…", options: ["Never", "The 9999 element is inside a stacking context whose ROOT has a lower index than the competitor", "Using grid"], answer: 1,
    explain: "z-index competes within its context; children can never escape their context's level." },
  { q: "Which property does NOT create a stacking context?", options: ["transform", "opacity: 0.99", "color"], answer: 2,
    explain: "transform, filter, opacity<1, will-change, position+z-index, isolation:isolate all create contexts — color doesn't." },
  { q: "The production fix for z-index chaos is…", options: ["Bigger numbers", "A token scale (--z-dropdown:100 … --z-toast:400) and banning raw values", "Avoiding position"], answer: 1,
    explain: "Every mature codebase adopts a scale after its first 999999 incident." },
  { q: "inset: 0 is shorthand for…", options: ["margin: 0", "top:0; right:0; bottom:0; left:0", "padding: 0"], answer: 1,
    explain: "With position:absolute + inset:0 the element stretches to fill its containing block — overlay pattern." },
  { q: "A full-screen modal backdrop typically uses…", options: ["position: absolute", "position: fixed; inset: 0 (viewport-pinned regardless of scroll)", "position: sticky"], answer: 1,
    explain: "…or better, the <dialog> element whose ::backdrop and top-layer rendering avoid z-index entirely." },
  { q: "The 'top layer' (dialog.showModal, popover) is special because…", options: ["It's faster", "It renders above ALL stacking contexts — z-index can't compete with it", "It's position:fixed"], answer: 1,
    explain: "The platform's escape hatch from stacking wars — why modern modals/popovers beat div overlays." },
  { q: "transform on an ancestor breaks position: fixed descendants by…", options: ["Hiding them", "Making the ancestor their containing block — 'fixed' becomes ancestor-relative", "Disabling them"], answer: 1,
    explain: "A notorious gotcha: a page-wide transform (e.g., animation) suddenly re-anchors every fixed element inside it." },
  { q: "Sticky table headers are…", options: ["JS-only", "thead th { position: sticky; top: 0 } inside a scrolling container", "Impossible with borders"], answer: 1,
    explain: "Border-collapse interactions are the classic snag — use border on cells or separate borders." },
  { q: "position: relative WITHOUT offsets is commonly used to…", options: ["Do nothing", "Anchor absolute children and/or enable z-index", "Center content"], answer: 1,
    explain: "It changes nothing visually but makes the element a containing block — the 'anchor wrapper' pattern." },
  { q: "An absolutely positioned element's width defaults to…", options: ["100%", "Shrink-to-fit its content", "The parent's width"], answer: 1,
    explain: "Out-of-flow boxes size to content unless you set width or pin both left+right." },
  { q: "Two positioned siblings, no z-index: who's on top?", options: ["The first in DOM", "The LATER one in DOM order", "Random"], answer: 1,
    explain: "Painting order: later siblings paint above earlier ones at equal stacking level." },
  { q: "isolation: isolate is used to…", options: ["Disable events", "Create a stacking context deliberately — capping children's z-index inside a component", "Stop inheritance"], answer: 1,
    explain: "Design systems wrap components in isolation so internal z-indexes can't fight the page." },
  { q: "Centering an absolute overlay of unknown size:", options: ["top/left 50% + translate(-50%,-50%) or inset:0 + margin:auto + fit-content", "Only flexbox can", "text-align: center"], answer: 0,
    explain: "Both classic patterns work; the translate version is most common for tooltips/popovers." },
  { q: "Sticky positioning ends when…", options: ["The user clicks", "Its PARENT's bottom edge scrolls past — it never leaves its parent", "The page ends"], answer: 1,
    explain: "Sticky is 'relative until threshold, then fixed WITHIN the parent's bounds'." },
  { q: "Anchor positioning (anchor-name/position-anchor) addresses…", options: ["Faster paint", "Tooltips/popovers positioned relative to another element WITHOUT JS measurement", "Print layout"], answer: 1,
    explain: "The newest positioning capability — declarative tethering that previously required Popper.js." },
  { q: "Scroll-driven UI like a progress bar tied to scroll is now possible via…", options: ["Only JS", "animation-timeline: scroll() — scroll-driven animations", "position: sticky tricks"], answer: 1,
    explain: "CSS scroll-driven animations move work off the main thread entirely." },
  { q: "fixed elements and iOS keyboards/URL bars:", options: ["Always perfect", "Visual-viewport quirks are real — test on hardware; dvh and env(safe-area-inset-*) help", "Only Android has issues"], answer: 1,
    explain: "Mobile browser chrome interacts with fixed/vh in ways emulators hide." },
  { q: "A dropdown clipped by its card container is caused by…", options: ["z-index", "overflow: hidden on an ancestor — no z-index value can escape clipping", "Wrong position value"], answer: 1,
    explain: "Clipping ≠ stacking. Fixes: remove the overflow, use position:fixed, or portal/top-layer the dropdown." }
]},

{ title: "Quiz 5 · Flexbox",
  desc: "Axes, grow/shrink/basis, alignment, wrapping, classic patterns",
  questions: [
  { q: "justify-content aligns along…", options: ["The cross axis", "The MAIN axis (horizontal in a row)", "Both"], answer: 1,
    explain: "align-items = cross axis. Flip flex-direction to column and their visual meanings swap." },
  { q: "flex: 1 expands to…", options: ["flex-grow:1 only", "grow:1, shrink:1, basis:0 — siblings share space EQUALLY regardless of content", "100% width"], answer: 1,
    explain: "basis:0 is the key: distribution ignores content size. flex:auto (basis:auto) divides leftover space instead." },
  { q: "A rigid 240px sidebar in flex is…", options: ["width: 240px", "flex: 0 0 240px (no grow, no shrink, fixed basis)", "min-width: 240px"], answer: 1,
    explain: "Plain width still shrinks by default (shrink:1) when space runs out." },
  { q: "margin-left: auto on a flex item…", options: ["Centers it", "Absorbs all free space to its left — pushes it (and followers) to the far end", "Is ignored"], answer: 1,
    explain: "The classic navbar trick: logo left, auto-margin before the links → links right." },
  { q: "Long unbreakable content blowing a flex layout open is fixed by…", options: ["overflow: scroll on body", "min-width: 0 on the item (default min-width:auto refuses to shrink below content)", "White-space: wrap"], answer: 1,
    explain: "THE flexbox bug everyone hits. Then text-overflow: ellipsis can actually work." },
  { q: "gap in flexbox…", options: ["Only works in grid", "Sets spacing between items — no margin gymnastics, works with wrap", "Adds outer padding"], answer: 1,
    explain: "Container declares spacing once; no first/last-child exceptions." },
  { q: "align-items: baseline is for…", options: ["Vertical centering", "Aligning items by their TEXT baseline — mixed-size text in one row", "Stretching"], answer: 1,
    explain: "A label next to a big metric number aligns on the text line, not box edges." },
  { q: "flex-wrap: wrap + align-content controls…", options: ["Single-line alignment", "How multiple LINES pack on the cross axis", "Item order"], answer: 1,
    explain: "align-items = items within a line; align-content = the lines themselves (only meaningful when wrapping)." },
  { q: "The sticky-footer page layout is…", options: ["position: fixed footer", "body{min-height:100dvh; display:flex; flex-direction:column} main{flex:1}", "margin-top: auto on html"], answer: 1,
    explain: "main absorbs free space; the footer sits at the bottom even on short pages, and normal flow returns on long ones." },
  { q: "order: -1 on a flex item…", options: ["Removes it", "Displays it first visually WITHOUT changing DOM order", "Reverses the container"], answer: 1,
    explain: "⚠ Screen readers and tab order follow the DOM — large visual reordering harms accessibility." },
  { q: "flex-shrink: 3 vs siblings' 1 means…", options: ["It shrinks 3px", "When space is short, it gives up space ~3× faster (weighted by basis)", "It wins space"], answer: 1,
    explain: "Grow distributes surplus; shrink distributes deficit — both are ratios." },
  { q: "Centering one child both ways:", options: ["margin: auto everywhere", "display:flex; justify-content:center; align-items:center (or grid + place-items)", "text-align + vertical-align"], answer: 1,
    explain: "The interview joke that's genuinely one line now." },
  { q: "The media-object pattern (avatar + expanding text) is…", options: ["float: left", ".row{display:flex; gap:.8rem} .body{flex:1; min-width:0}", "Grid-only"], answer: 1,
    explain: "min-width:0 lets long usernames/URLs truncate instead of exploding the row." },
  { q: "justify-content: space-between vs space-around:", options: ["Same", "between: no outer edges gaps; around: half-size outer gaps (space-evenly: all equal)", "around is deprecated"], answer: 1,
    explain: "Three distribution flavors; between is the navbar default." },
  { q: "flex-basis vs width — which wins in a row?", options: ["width", "flex-basis (when not auto) takes precedence as the starting size", "The larger one"], answer: 1,
    explain: "basis:auto defers to width/content; any explicit basis overrides width for flex sizing." },
  { q: "align-self does what?", options: ["Aligns text", "Overrides align-items for ONE item", "Sets baseline"], answer: 1,
    explain: "Per-item cross-axis exception — e.g., one bottom-aligned button in a top-aligned row." },
  { q: "A 3-equal-columns layout that must NOT reflow per content is better in…", options: ["Flexbox", "Grid (container-controlled tracks); flex items flex by content by design", "Tables"], answer: 1,
    explain: "The one-dimensional/content-out vs two-dimensional/layout-in distinction — the interview question." },
  { q: "flex-direction: column with height: 100% children requires…", options: ["Nothing special", "The container to have a real height — columns don't create height from nowhere", "flex-basis: 100%"], answer: 1,
    explain: "Same percent-height rule as everywhere: the reference must be defined." },
  { q: "Nested flex containers are…", options: ["An anti-pattern", "Completely normal — page rows of columns of rows is idiomatic composition", "Slower than grid"], answer: 1,
    explain: "Compose freely: grid for the page shell, flex inside components, flex inside those." },
  { q: "In flex rows, images sometimes stretch weirdly because…", options: ["Bad encoding", "Default align-items: stretch distorts them — set align-self or align-items to flex-start/center", "They need width"], answer: 1,
    explain: "Replaced elements + stretch = surprise distortion; a one-line alignment fix." }
]}
);
