// CI/CD quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Secrets & OIDC Auth",
  desc: "Pipeline secrets, OIDC federation, least privilege",
  questions: [
  { q: "Pipeline secrets should be…", options: ["Hardcoded in YAML", "Stored in a secret store and injected at runtime", "In the README"], answer: 1,
    explain: "Never commit secrets." },
  { q: "OIDC in CI lets the pipeline…", options: ["Store long-lived cloud keys", "Exchange a short-lived identity token for temporary cloud creds", "Skip auth"], answer: 1,
    explain: "No static cloud secrets to leak." },
  { q: "The big win of OIDC over stored keys is…", options: ["Slower", "Short-lived, scoped credentials (nothing long-lived to steal)", "More secrets"], answer: 1,
    explain: "Smaller blast radius." },
  { q: "Secrets in CI logs should be…", options: ["Printed", "Masked/redacted", "Emailed"], answer: 1,
    explain: "Avoid accidental exposure." },
  { q: "Least privilege for pipeline tokens means…", options: ["Admin everywhere", "Only the permissions the job needs", "No permissions ever"], answer: 1,
    explain: "Limit what a leak can do." },
  { q: "A leaked long-lived cloud key is dangerous because…", options: ["It expires instantly", "It grants standing access until rotated", "It's encrypted"], answer: 1,
    explain: "Why OIDC/short-lived is better." },
  { q: "OIDC trust is configured by…", options: ["Sharing passwords", "The cloud trusting the CI provider's identity token (claims like repo/branch)", "Nothing"], answer: 1,
    explain: "Scope trust to specific repos/branches." },
  { q: "Storing secrets per-environment (dev/prod) helps…", options: ["Nothing", "Separation + least privilege per environment", "Speed"], answer: 1,
    explain: "Prod creds ≠ dev creds." },
  { q: "A secret that only certain branches can access…", options: ["Is impossible", "Limits who can use prod credentials (environment protection)", "Is insecure"], answer: 1,
    explain: "Protected environments/branches." },
  { q: "Rotating secrets regularly…", options: ["Is pointless", "Limits the window a leaked secret is useful", "Breaks OIDC"], answer: 1,
    explain: "Defense in depth." },
  { q: "Hardcoding an API key in the workflow file…", options: ["Is fine if private", "Risks leaking it (repo clone/fork/logs)", "Is encrypted"], answer: 1,
    explain: "Use the secret store." },
  { q: "OIDC federation is increasingly preferred for…", options: ["Nothing", "Cloud auth from CI (AWS/GCP/Azure) without static keys", "Storing passwords"], answer: 1,
    explain: "Keyless, short-lived access." },
  { q: "A secrets manager (Vault/cloud) provides…", options: ["Only storage", "Central storage, rotation, access control, and audit", "Faster CI"], answer: 1,
    explain: "Managed secret lifecycle." },
  { q: "Third-party actions with access to secrets are risky because…", options: ["They're slow", "A malicious/compromised action can exfiltrate them", "Nothing"], answer: 1,
    explain: "Pin to SHA; limit secret exposure." },
  { q: "Scoping an OIDC token to a specific repo+branch prevents…", options: ["All use", "Other repos/branches from assuming that cloud role", "Caching"], answer: 1,
    explain: "Tighten the trust policy." },
  { q: "Passing prod secrets to PRs from forks is…", options: ["Safe", "Dangerous (untrusted code could steal them)", "Required"], answer: 1,
    explain: "Restrict secrets on fork PRs." },
  { q: "The ideal credential lifetime for a deploy job is…", options: ["Forever", "Just long enough for the job (minutes)", "One year"], answer: 1,
    explain: "Short-lived via OIDC." },
  { q: "Auditing secret access lets you…", options: ["Nothing", "Detect misuse (who used what, when)", "Skip rotation"], answer: 1,
    explain: "Accountability." },
  { q: "Environment-level required reviewers protect…", options: ["Lint", "Access to sensitive deploy credentials/actions", "Caching"], answer: 1,
    explain: "Human gate before prod." },
  { q: "The overall secrets principle is…", options: ["Convenience over safety", "Least privilege, short-lived, injected at runtime, never committed", "Share widely"], answer: 1,
    explain: "The secure baseline." }
]},
{ title: "Quiz 7 · Docker in CI",
  desc: "Building images in pipelines, layer cache, tags, scanning",
  questions: [
  { q: "A container image is a great CI artifact because…", options: ["It's mutable", "It's immutable and bundles app + deps (build once)", "It's source"], answer: 1,
    explain: "Perfect promote-through-envs unit." },
  { q: "Docker layer caching in CI…", options: ["Slows builds", "Reuses unchanged layers to speed rebuilds", "Leaks secrets"], answer: 1,
    explain: "Key on inputs (Dockerfile/lockfile)." },
  { q: "Tagging an image with the git SHA gives…", options: ["Ambiguity", "Traceability (which commit built it)", "Slower pulls"], answer: 1,
    explain: "Provenance for deploys." },
  { q: "Deploying the :latest tag from CI is…", options: ["Best practice", "Risky — mutable, irreproducible", "Required"], answer: 1,
    explain: "Pin an immutable tag/digest." },
  { q: "Scanning images in CI (Trivy/Scout) should…", options: ["Only warn", "Fail the build on high/critical CVEs", "Be skipped"], answer: 1,
    explain: "Block vulnerable images pre-deploy." },
  { q: "Build-time secrets in Docker CI should use…", options: ["ENV/ARG (leaks)", "BuildKit --mount=type=secret (not persisted in layers)", "COPY .env"], answer: 1,
    explain: "Avoid baking secrets into layers." },
  { q: "Multi-stage builds in CI help by…", options: ["Bloating images", "Shipping only artifacts (small, secure images)", "Adding tools"], answer: 1,
    explain: "From the Docker track." },
  { q: "A BuildKit cache mount (--mount=type=cache)…", options: ["Leaks data", "Persists package-manager cache across builds", "Deletes cache"], answer: 1,
    explain: "Faster dependency installs." },
  { q: "'docker build' followed by 'push' in CI produces…", options: ["Nothing", "A versioned image in a registry to deploy", "A branch"], answer: 1,
    explain: "The release artifact." },
  { q: "Running tests inside a container in CI gives…", options: ["Inconsistency", "A reproducible, isolated test environment", "Slower flakiness"], answer: 1,
    explain: "Consistent envs." },
  { q: "Pinning the base image by digest (FROM ...@sha256)…", options: ["Is mutable", "Makes builds reproducible + tamper-evident", "Breaks CI"], answer: 1,
    explain: "Supply-chain hygiene." },
  { q: ".dockerignore in CI…", options: ["Slows builds", "Shrinks context, stabilizes cache, avoids leaking files", "Deletes images"], answer: 1,
    explain: "Keep .git/node_modules/.env out." },
  { q: "Generating an SBOM during the image build…", options: ["Is useless", "Records contents for CVE/audit response", "Breaks the build"], answer: 1,
    explain: "Supply-chain visibility." },
  { q: "Signing the built image (cosign) enables…", options: ["Faster pulls", "Verification of authenticity/integrity at deploy", "Nothing"], answer: 1,
    explain: "Reject unsigned images." },
  { q: "A registry pull-through cache/mirror in CI…", options: ["Adds risk only", "Improves reliability + avoids rate limits", "Slows builds"], answer: 1,
    explain: "Vet + speed public images." },
  { q: "Reusing a cached layer requires…", options: ["Any change", "The layer's inputs to be unchanged", "A new base"], answer: 1,
    explain: "Order least→most changing." },
  { q: "The image you test in CI should be…", options: ["Rebuilt for prod", "The exact image promoted to prod", "Different"], answer: 1,
    explain: "Test-what-you-ship." },
  { q: "Building images without BuildKit caching typically…", options: ["Is fastest", "Re-does work every run (slow)", "Is required"], answer: 1,
    explain: "Enable caching." },
  { q: "A distroless final image from CI is…", options: ["Bigger + insecure", "Small with a reduced attack surface (no shell)", "Un-deployable"], answer: 1,
    explain: "Multi-stage benefit." },
  { q: "Tagging strategy for images should be…", options: ["Only :latest", "Immutable, traceable (semver + git SHA/digest)", "Random"], answer: 1,
    explain: "Reproducible releases." }
]},
{ title: "Quiz 8 · Deployment Strategies",
  desc: "Recreate, rolling, blue/green, canary, rollback, DB migrations",
  questions: [
  { q: "Deployment strategies primarily control…", options: ["Build speed", "Blast radius and rollback speed of a release", "Test coverage"], answer: 1,
    explain: "Safe, reversible releases." },
  { q: "A rolling update…", options: ["Stops all then starts all", "Replaces instances gradually (no downtime)", "Runs two full envs"], answer: 1,
    explain: "The common K8s default." },
  { q: "Blue/green deployment…", options: ["Ramps a %", "Runs two envs and switches traffic all at once (instant rollback)", "Has downtime"], answer: 1,
    explain: "Flip back to roll back." },
  { q: "Canary deployment…", options: ["Sends all traffic at once", "Sends a small % to the new version, then ramps on good metrics", "Never rolls back"], answer: 1,
    explain: "Smallest blast radius." },
  { q: "Blue/green's main cost is…", options: ["Downtime", "Running two full environments during the switch", "No rollback"], answer: 1,
    explain: "Double infra briefly." },
  { q: "Canary requires…", options: ["Nothing", "Good metrics + traffic splitting (+ ideally automated analysis)", "Downtime"], answer: 1,
    explain: "Observability-driven." },
  { q: "Recreate strategy…", options: ["Zero downtime", "Stops old, starts new (downtime) — simplest", "Ramps traffic"], answer: 1,
    explain: "Fine for non-critical/dev." },
  { q: "The universal deployment DB trap is…", options: ["Too many indexes", "Old + new code share one DB → migrations must be backward-compatible", "Slow queries"], answer: 1,
    explain: "Expand/contract pattern." },
  { q: "Expand/contract migrations mean…", options: ["Drop columns first", "Add new (both versions work), migrate, remove old later", "Never migrate"], answer: 1,
    explain: "Backward-compatible changes." },
  { q: "Rollback for blue/green is…", options: ["Slow rebuild", "Instant (switch traffic back to the old env)", "Impossible"], answer: 1,
    explain: "Old env still running." },
  { q: "Rollback for canary is…", options: ["A full redeploy", "Route canary traffic to 0% (few users affected)", "Downtime"], answer: 1,
    explain: "Minimal impact." },
  { q: "A smoke test before cutover…", options: ["Is wasteful", "Validates the new version before it takes traffic", "Deploys it"], answer: 1,
    explain: "Catch breakage early." },
  { q: "Automated canary analysis (Flagger/Argo Rollouts)…", options: ["Needs a human each step", "Promotes/aborts based on metrics automatically", "Only builds images"], answer: 1,
    explain: "Progressive delivery." },
  { q: "Choosing a strategy depends on…", options: ["Team size only", "How costly a bad release is for that service", "The language"], answer: 1,
    explain: "Match risk to strategy." },
  { q: "Rolling update pace in K8s is controlled by…", options: ["replicas only", "maxSurge / maxUnavailable", "Nothing"], answer: 1,
    explain: "From the K8s track." },
  { q: "A backward-incompatible migration mid-rollout…", options: ["Is safe", "Breaks the still-running old version", "Speeds deploys"], answer: 1,
    explain: "Why expand/contract exists." },
  { q: "Recovery time (MTTR) is minimized by…", options: ["Manual rebuilds", "Instant-rollback strategies (blue/green, canary)", "Bigger batches"], answer: 1,
    explain: "Fast, ideally automated rollback." },
  { q: "The two questions every strategy answers are…", options: ["Cost and color", "How many users a bad release hits + how fast you undo it", "Language and OS"], answer: 1,
    explain: "Exposure + reversibility." },
  { q: "For a critical user-facing service, avoid…", options: ["Canary", "Recreate (downtime)", "Blue/green"], answer: 1,
    explain: "Prefer zero-downtime strategies." },
  { q: "Progressive delivery combines…", options: ["Only builds", "Deployment strategies + feature flags + metrics, done gradually", "Manual QA"], answer: 1,
    explain: "Measured, incremental rollout." }
]},
{ title: "Quiz 9 · Progressive Delivery, Performance, Supply-chain & DORA",
  desc: "Feature flags, fast pipelines, SBOM/SLSA/signing, DORA metrics",
  questions: [
  { q: "Feature flags primarily…", options: ["Speed builds", "Decouple deploy from release (runtime feature control)", "Store secrets"], answer: 1,
    explain: "Turn features on/off without deploying." },
  { q: "A feature flag kill-switch lets you…", options: ["Redeploy to fix", "Disable a broken feature in seconds (no rollback deploy)", "Nothing"], answer: 1,
    explain: "Instant mitigation." },
  { q: "'Flag debt' is…", options: ["A billing issue", "Accumulated complexity/risk from unremoved flags", "A test type"], answer: 1,
    explain: "Owner + expiry + cleanup." },
  { q: "If the flag service is unreachable, the app should…", options: ["Crash", "Fall back to a safe default", "Delete flags"], answer: 1,
    explain: "No single point of failure." },
  { q: "The biggest pipeline-speed lever is usually…", options: ["More meetings", "Caching (deps/layers/build outputs)", "Bigger batches"], answer: 1,
    explain: "Turn repeated work into a lookup." },
  { q: "A good cache key is derived from…", options: ["The commit SHA (never hits)", "A hash of the inputs (e.g., lockfile)", "A constant (never invalidates)"], answer: 1,
    explain: "Reused when inputs unchanged." },
  { q: "Test sharding across N runners…", options: ["Slows tests", "Cuts wall-clock time ~N×", "Removes tests"], answer: 1,
    explain: "Parallelize the suite." },
  { q: "Fast pipelines improve delivery because…", options: ["They don't", "Quick feedback enables small, frequent, safe deploys", "They skip tests"], answer: 1,
    explain: "Latency shapes batch size." },
  { q: "An SBOM answers…", options: ["How fast is CI", "What's inside the artifact (for CVE response)", "Who deployed"], answer: 1,
    explain: "Software bill of materials." },
  { q: "Provenance/attestation (SLSA) records…", options: ["Test results", "How and where an artifact was built", "Coverage"], answer: 1,
    explain: "Verifiable build origin." },
  { q: "Signing artifacts (cosign/Sigstore) proves…", options: ["Speed", "Authenticity + integrity (untampered)", "Coverage"], answer: 1,
    explain: "Verify at deploy time." },
  { q: "Pinning a third-party action to a commit SHA prevents…", options: ["Caching", "A moved tag injecting malicious code (Codecov-style)", "Parallelism"], answer: 1,
    explain: "Immutability of the dependency." },
  { q: "Supply-chain attacks (SolarWinds) targeted…", options: ["The running app only", "The BUILD/pipeline itself", "The database"], answer: 1,
    explain: "Trust the build, not just tests." },
  { q: "The four DORA metrics are…", options: ["LOC, bugs, commits, PRs", "Deploy frequency, lead time, change failure rate, recovery time", "CPU, RAM, disk, net"], answer: 1,
    explain: "Two speed, two stability." },
  { q: "DORA's key finding is…", options: ["Speed vs stability trade-off", "Elite teams achieve BOTH speed and stability", "Slow is safe"], answer: 1,
    explain: "Same practices drive both." },
  { q: "Change Failure Rate measures…", options: ["Deploy speed", "% of deploys causing a failure/incident", "Build time"], answer: 1,
    explain: "A stability metric." },
  { q: "Lead Time for Changes measures…", options: ["Time to build only", "Commit → running in production", "Meeting length"], answer: 1,
    explain: "A throughput metric." },
  { q: "Using DORA as individual KPIs…", options: ["Is ideal", "Causes gaming (Goodhart's law)", "Improves morale"], answer: 1,
    explain: "Team/system-level signal, not targets." },
  { q: "Platform engineering builds…", options: ["More tickets", "A self-service internal platform (golden paths) to scale good delivery", "A monolith"], answer: 1,
    explain: "Paved road, treated as a product." },
  { q: "A 'paved road' platform means…", options: ["A mandate/cage", "The easy default is the secure/correct one (with escape hatches)", "No standards"], answer: 1,
    explain: "Make the right way the easy way." }
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review across the whole CI/CD track",
  questions: [
  { q: "Trunk-based development favors…", options: ["Long-lived branches", "Short-lived branches merged frequently", "No branches"], answer: 1,
    explain: "Less integration pain." },
  { q: "The core purpose of CI is…", options: ["Deploy to prod", "Fast automated build/test feedback on every change", "Write code"], answer: 1,
    explain: "Catch issues early." },
  { q: "GitHub Actions jobs run… by default", options: ["Sequentially", "In parallel (unless needs:)", "Never"], answer: 1,
    explain: "Fan out for speed." },
  { q: "The test pyramid has the MOST…", options: ["E2E tests", "Unit tests", "Manual tests"], answer: 1,
    explain: "Fast, stable base." },
  { q: "'Build once, deploy many' means…", options: ["Rebuild per env", "Promote one immutable artifact through envs", "Never build"], answer: 1,
    explain: "Consistency + test-what-you-ship." },
  { q: "OIDC in CI provides…", options: ["Long-lived keys", "Short-lived, scoped cloud credentials (no static keys)", "No auth"], answer: 1,
    explain: "Smaller blast radius." },
  { q: "A container image as an artifact is…", options: ["Mutable source", "Immutable app + deps (build once)", "A branch"], answer: 1,
    explain: "Promote through environments." },
  { q: "Canary deployment…", options: ["All traffic at once", "Small % first, ramp on good metrics", "Downtime"], answer: 1,
    explain: "Smallest blast radius." },
  { q: "The deployment DB trap is fixed with…", options: ["Dropping columns first", "Expand/contract (backward-compatible migrations)", "No migrations"], answer: 1,
    explain: "Old + new code share the DB." },
  { q: "Feature flags decouple…", options: ["Build from test", "Deploy from release", "Nothing"], answer: 1,
    explain: "Runtime feature control." },
  { q: "The biggest CI speed lever is…", options: ["Bigger batches", "Caching keyed on input hashes", "Sequential jobs"], answer: 1,
    explain: "Reuse repeated work." },
  { q: "Pin third-party CI actions to…", options: ["A moving tag", "A commit SHA", "latest"], answer: 1,
    explain: "Prevent malicious tag swaps." },
  { q: "An SBOM tells you…", options: ["How fast CI is", "What's inside the artifact", "Who approved"], answer: 1,
    explain: "CVE/audit response." },
  { q: "Signing + verifying artifacts ensures…", options: ["Speed", "Authenticity and integrity", "Coverage"], answer: 1,
    explain: "cosign/Sigstore at deploy." },
  { q: "The four DORA metrics balance…", options: ["Cost and size", "Speed (frequency, lead time) and stability (failure rate, recovery)", "CPU and RAM"], answer: 1,
    explain: "Both improve together." },
  { q: "Blue/green rollback is…", options: ["Slow rebuild", "Instant (flip back to the old env)", "Impossible"], answer: 1,
    explain: "Old env still live." },
  { q: "Quality gates should be…", options: ["Advisory", "Enforced/blocking for critical criteria", "Removed"], answer: 1,
    explain: "Otherwise ignored." },
  { q: "Fail fast means…", options: ["Never fail", "Run quick checks before slow ones", "Skip tests"], answer: 1,
    explain: "Fast feedback on breaks." },
  { q: "Platform engineering delivers…", options: ["More tickets", "Self-service golden paths (paved road)", "A monolith"], answer: 1,
    explain: "Scale good delivery." },
  { q: "The through-line of modern CI/CD is…", options: ["Big, rare, manual releases", "Small, frequent, automated, safe, reversible releases", "No automation"], answer: 1,
    explain: "Speed + stability together." }
]}
);
