// cicd quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Runners and Pipeline Reliability",
  desc: "Hosted vs self-hosted, ephemerality, runner security, capacity, SLIs, retries, timeouts, incidents",
  questions: [
  { q: "The honest business case for self-hosted runners must include…", options: ["Only the hosted bill", "Only the instance cost", "Engineer-days of maintenance — 31 days in the measured first year"], answer: 2,
    explain: "$4,100/year of claimed savings against $21,080 of engineer time and a $7,188 hosted bill. Self-host for capability, not cost." },
  { q: "The strongest legitimate reason to self-host is…", options: ["Nicer YAML", "The build needs private network access", "Cost at small scale"], answer: 1,
    explain: "Then hardware, compliance and genuine scale economics. Warm caches — the weakest reason — are usually better solved with a registry cache." },
  { q: "A persistent runner let one repository's build pass for six weeks because…", options: ["The runner was faster", "Another repository's job had globally installed a CLI it used but never declared", "Its tests were cached"], answer: 1,
    explain: "It failed the day it landed on a fresh machine, with no related change. Ephemeral runners remove the whole class." },
  { q: "A self-hosted runner that builds fork pull requests is…", options: ["Standard practice", "Safe if the repo is private", "Effectively unauthenticated remote code execution inside your network"], answer: 2,
    explain: "An audit found runners able to open a socket to the production database and read the instance IAM role from the metadata endpoint." },
  { q: "Runner labels are…", options: ["A scheduling hint — any workflow with pool access can request them", "Encrypted", "A security boundary"], answer: 0,
    explain: "Use platform-level runner groups scoped to named repositories. Several published breaches follow the label-as-boundary path." },
  { q: "Runner pools should be sized from…", options: ["The p95 of concurrent demand", "The number of engineers", "Average concurrency"], answer: 0,
    explain: "Averages said 3 concurrent jobs where the p95 was 11 and the peak 20. Autoscale between a small warm floor and the burst ceiling." },
  { q: "Cold-pool scale-up measured 4m40s. The largest single component was…", options: ["Instance launch", "Boot plus agent registration, then the toolchain image pull", "The autoscaler poll"], answer: 1,
    explain: "98 s of boot/registration and 90 s of image pull. Two warm runners at $94/month took p50 job start from 380 s to 12 s." },
  { q: "Autoscaling on pool CPU utilisation is wrong because…", options: ["A queued job consumes no CPU, so the signal arrives after people are waiting", "CPU is hard to measure", "It is expensive"], answer: 0,
    explain: "Scale on queued-job count, ideally webhook-driven rather than polled." },
  { q: "The dominant cause of infrastructure failures in the measured quarter was…", options: ["OOM kills", "DNS", "Disk exhaustion — 61%"], answer: 2,
    explain: "And a nightly `docker system prune -af` made it worse: it deleted the layer cache everyone needed and still filled up by afternoon." },
  { q: "186 of 299 failures were infrastructure. How had they been reported?", options: ["As flaky tests", "As infrastructure incidents", "Not at all"], answer: 0,
    explain: "Classifying by error signature routes the work to the team that can fix it and makes retries defensible." },
  { q: "The pipeline should be treated as production because…", options: ["It runs containers", "It has YAML", "When it is down or slow, every engineer is blocked"], answer: 2,
    explain: "A 40-minute outage cost ~51 engineer-hours (~$4,335); eleven of them cost $47,685 — eight times that year's customer-facing SLO breaches." },
  { q: "You should alert on…", options: ["Every failed run", "Nothing — people will report it", "Rates: infrastructure failure rate, first-attempt pass rate, queue depth that will not drain"], answer: 2,
    explain: "A single failure is normal. Page on rates and you hear about problems from a monitor rather than the fourth person to give up." },
  { q: "Retries should be triggered by…", options: ["Any failure", "The number of attempts so far", "A classified error signature — infra_* or external_*"], answer: 2,
    explain: "Blanket retries turn a broken commit into 12m30s of identical failures and hide real outages." },
  { q: "Silent retries during a registry outage caused…", options: ["Faster recovery", "Nothing", "A 40-minute problem to become a four-hour one"], answer: 2,
    explain: "Jobs stayed 'in progress', no failure rate rose, and nothing alerted. Emit a metric per retry and alert on the retry rate." },
  { q: "Which step is safe to retry automatically?", options: ["A database migration", "A dependency install", "A deploy"], answer: 1,
    explain: "Retry only idempotent steps. Deploys, migrations and notifications go through a lock and a fresh run instead." },
  { q: "A job with no timeout inherits a default of…", options: ["Six hours on GitHub Actions", "No limit", "10 minutes"], answer: 0,
    explain: "One hung job held its concurrency group and blocked the merge queue all afternoon while 14 PRs waited." },
  { q: "A sensible job timeout is roughly…", options: ["10x the average", "The p50 duration", "2x the p95, with an alert at 1.5x"], answer: 2,
    explain: "Alert before the timeout so someone can attach to a live hung job — a timeout is a post-mortem notification." },
  { q: "A watchdog that dumps process state after 120 s of log silence gives you…", options: ["A faster job", "Why it hung, which a timeout never tells you", "Better test coverage"], answer: 1,
    explain: "In the measured case it revealed every thread blocked on a connection pool exhausted by a leaked session — found on the first occurrence." },
  { q: "The environment preamble printed at the start of every job should include…", options: ["Only the commit", "Commit, attempt, runner, CPUs, memory, free disk, tool versions and filtered env", "Nothing — it is noise"], answer: 1,
    explain: "It answers most 'why here and not locally?' questions before anything fails, and cut median time-to-diagnose from 34 minutes to 6." },
  { q: "The most valuable action item from a CI incident postmortem is usually about…", options: ["Detection", "Tooling choice", "The specific cause"], answer: 0,
    explain: "The next outage will have a different cause. In the registry incident the fix was one config line; nobody knew for 90 minutes." },
]},
{ title: "Quiz 7 · Deployment: Strategies, Environments and Promotion",
  desc: "Blast radius, draining, canary statistics, rollback drills, environment parity, digest promotion",
  questions: [
  { q: "Deployment strategies are best chosen by…", options: ["Which diagram looks safest", "Blast radius multiplied by detection time", "What the platform supports"], answer: 1,
    explain: "Canary at 5% cut failed requests 20x against a full rollout; adding automated analysis (8 min to 90 s detection) made it 100x." },
  { q: "A canary without automated analysis is…", options: ["A delay, not a control", "Better than blue/green", "Sufficient"], answer: 0,
    explain: "Manual detection measured 11 minutes in working hours and 40+ outside them. The routing is the cheap half." },
  { q: "Every strategy except recreate requires…", options: ["A service mesh", "Double capacity", "Two versions of your code running simultaneously to be safe"], answer: 2,
    explain: "Schema, message formats, caches, sessions, static assets and internal APIs must all tolerate both versions." },
  { q: "`maxUnavailable: 25%` at peak on a service running at 70% utilisation…", options: ["Took measured p99 from 190 ms to 940 ms", "Is free", "Speeds up the rollout safely"], answer: 0,
    explain: "Surge instead when you have headroom; reduce capacity only when you do not, and not at peak." },
  { q: "Readiness meaning 'the port is open' caused…", options: ["6.4x p99 for the first 30 seconds of each batch", "Failed deploys", "Nothing"], answer: 0,
    explain: "Readiness must mean dependencies reachable, pools warm and a warm-up request completed — and gate each batch on healthy-and-error-free." },
  { q: "Without a preStop delay and graceful shutdown, the measured service dropped…", options: ["Nothing", "Half its traffic", "1,840 in-flight requests per deploy"], answer: 2,
    explain: "Invisible at 0.046% of daily traffic. The grace period must exceed preStop plus your slowest request." },
  { q: "Blue/green's instant rollback does NOT roll back…", options: ["Traffic routing", "The application version", "Data written by the new version, or side effects like emails and payments"], answer: 2,
    explain: "The database does not switch with it — which is why expand/contract migrations are what actually make rollback possible." },
  { q: "A 'blue/green' that tears down blue at cut-over is…", options: ["Recreate with extra steps — the instant rollback does not exist", "Standard", "Safer"], answer: 0,
    explain: "Keeping blue alive for the bake period is the property you paid double capacity for." },
  { q: "At 4,000 rps with a 0.2% baseline error rate, 1% of traffic for five minutes can detect…", options: ["Any regression", "Only a catastrophe — roughly a doubling", "A 20% relative increase"], answer: 1,
    explain: "12,000 samples give ~24 expected errors with sigma ≈ 4.9. Catching +25% needs ~262,000 samples per arm — 109 minutes at 1%, or 11 at 10%." },
  { q: "Canary metrics should be compared against…", options: ["The concurrent control group", "A fixed threshold only", "Yesterday's numbers"], answer: 0,
    explain: "Comparing to history makes every Monday morning look like a regression. Also put an absolute floor on the error gate." },
  { q: "Which signal is most sensitive at small canary sample sizes?", options: ["New exception signatures", "p99 latency", "Conversion rate"], answer: 0,
    explain: "It is binary and fires on the first occurrence. p99 is a tail statistic and needs far more samples than p50." },
  { q: "An undrilled rollback measured…", options: ["74 seconds", "7m10s — wrong command, deleted image", "Instant"], answer: 1,
    explain: "The runbook flag had been renamed five months earlier and retention had deleted the previous image. After fixes and three monthly drills: 74 seconds." },
  { q: "Which quietly removes your ability to roll back?", options: ["Adding a nullable column", "A destructive migration in the same release", "Deploying by digest"], answer: 1,
    explain: "Also: data written in a new format, irreversible side effects, deleted artifacts and config drift." },
  { q: "A December deployment freeze produces a January release whose probability of containing a bad change is…", options: ["Unchanged", "About 88% at 140 changes", "Lower"], answer: 1,
    explain: "12 changes carry 17%. Freezing everything converts many small risks into one enormous one, with 140 suspects." },
  { q: "An environment earns its cost when…", options: ["It mirrors production exactly", "It exists", "It answers a question a cheaper environment cannot"], answer: 2,
    explain: "In the measured audit staging caught 8 incidents and CAUSED 9, at $75,120/year." },
  { q: "In that audit, what share of incidents were NOT reproducible in staging?", options: ["17%", "55%", "5%"], answer: 1,
    explain: "Data volume, real traffic patterns, third-party behaviour, production-only config and scale — of which only some are fixable in staging." },
  { q: "The highest-risk category of environment drift is…", options: ["Different hostnames", "Different instance counts", "A config key that exists in only one environment"], answer: 2,
    explain: "The production code path has then never run anywhere else. Generate all environments from one template so a missing key fails the build." },
  { q: "Promotion should move…", options: ["An immutable digest", "A tag", "A branch merge"], answer: 0,
    explain: "Branch promotion rebuilds, so production runs untested bytes, and the branches diverge until a hotfix exists in only one of them." },
  { q: "A shared staging environment measured a median wait of…", options: ["5 minutes", "No wait", "47 minutes, with 23 coordination messages a day"], answer: 2,
    explain: "Per-PR previews replaced it at $310/month against $4,900 — using a schema per PR on one shared database server and scale-to-zero." },
  { q: "Preview environments accumulated 214 orphans because…", options: ["The TTL was too short", "The teardown-on-close workflow can itself fail — you also need a TTL and a nightly reaper", "Teams forgot"], answer: 1,
    explain: "$2,100/month, which is how the whole idea gets cancelled. Alert when the live-preview count exceeds a threshold." },
]},
{ title: "Quiz 8 · Data and Delivery: Migrations and Feature Flags",
  desc: "Expand/contract, locks, backfills, rehearsal, deploy vs release, bucketing, guardrails, flag debt",
  questions: [
  { q: "The asymmetry that makes migrations the hardest part of CD is…", options: ["Databases are slow", "Schemas are complex", "Code rolls back in seconds; data does not roll back at all"], answer: 2,
    explain: "A successful rollback onto a dropped column still leaves the service down — the rollback completes and nothing works." },
  { q: "Expand/contract is…", options: ["One deployment with six steps", "A backup strategy", "Several releases with rollback windows between them"], answer: 2,
    explain: "Expand, dual write, backfill, switch reads, stop writing the old, contract — typically two to four releases for one rename." },
  { q: "The expand/contract phase people skip is…", options: ["Backfill", "Expand", "Stop writing the old column"], answer: 2,
    explain: "They go from switching reads straight to dropping, while some service — a report, a worker, a dashboard — is still writing the old column." },
  { q: "`ADD COLUMN state text NOT NULL DEFAULT gen_random_uuid()` on 41M rows measured…", options: ["An exclusive lock held for 4m12s, queueing 61,000 requests", "0.4 s", "A warning only"], answer: 0,
    explain: "A volatile default rewrites every row. Add nullable, set a constant default, backfill in batches, then add a validated NOT NULL constraint." },
  { q: "A migration WAITING for a lock is dangerous because…", options: ["It times out", "It consumes CPU", "Every subsequent query on that table queues behind it"], answer: 2,
    explain: "A long-running SELECT plus a migration is a table-wide outage before the migration even starts. `SET lock_timeout` changes the failure mode." },
  { q: "`CREATE INDEX CONCURRENTLY` requires…", options: ["A superuser", "Running outside a transaction — which most migration tools wrap around each migration", "A maintenance window"], answer: 1,
    explain: "A failed concurrent build can also leave an INVALID index that must be dropped before retrying." },
  { q: "A single `UPDATE` backfilling 40M rows measured…", options: ["Two minutes", "38 minutes, 94 s replica lag and 22 GB of WAL", "No impact"], answer: 1,
    explain: "The batched version took 51 minutes with a 40 ms longest lock and 5.2 s peak lag — and could be stopped and resumed." },
  { q: "A backfill should be throttled on…", options: ["Time of day", "CPU", "Measured replica lag"], answer: 2,
    explain: "Lag is what users experience — a replica 90 seconds behind serves a customer their order list without the order they just placed." },
  { q: "Migrations should run…", options: ["Manually by a DBA", "In a dedicated pipeline job holding an advisory lock", "On application startup"], answer: 1,
    explain: "On startup every replica races; MySQL's non-transactional DDL then leaves a schema matching no migration version." },
  { q: "Staging said a migration took 0.3 s; production took 4m12s because…", options: ["The query differed", "Staging had 180,000 rows against 41.3M", "Production is slower"], answer: 1,
    explain: "Rehearse against a restored production-sized snapshot, and publish duration and longest blocking lock on the pull request." },
  { q: "The compatibility matrix cell nobody tests is…", options: ["OLD code against the NEW schema", "Old code against the old schema", "New code against the new schema"], answer: 0,
    explain: "That cell is the rollback guarantee — the whole reason expand/contract exists." },
  { q: "Before dropping a column you should wait through…", options: ["A week", "One deploy", "At least one month boundary"], answer: 2,
    explain: "The monthly reconciliation job that reads a column once every thirty days is invisible to a two-week observation window and catastrophic on the 1st." },
  { q: "Renaming a column before dropping it is useful because…", options: ["It is faster", "It is reversible in one statement and makes remaining readers fail loudly", "It compresses the table"], answer: 1,
    explain: "Leave it renamed for a release; if nothing breaks, drop it. If something does, rename it back in milliseconds." },
  { q: "Feature flags separate…", options: ["Build from compile", "Deploying code from releasing a behaviour", "Testing from staging"], answer: 1,
    explain: "Which is what allows incomplete work to merge daily and turns rollback into a 200 ms flip rather than a deploy." },
  { q: "Evaluating flags by calling the vendor's API per request caused…", options: ["Nothing measurable", "A 41-minute checkout outage when the vendor timed out", "Higher costs only"], answer: 1,
    explain: "Stream the ruleset into memory, cache it on disk, evaluate in microseconds, and never throw from a flag check." },
  { q: "A flag's hardcoded default matters because…", options: ["It is what runs during a flag-service outage — and must match the live value", "It documents intent", "It is used in tests only"], answer: 0,
    explain: "Nine mismatches meant the next outage would silently disable features everyone used. A five-line CI job catches them." },
  { q: "Bucketing must hash the subject id together with…", options: ["The timestamp", "The environment", "The flag key"], answer: 2,
    explain: "Otherwise the same unlucky 5% of users receives every experiment, and all results are correlated." },
  { q: "Without exposure logging, a flag ramp is…", options: ["Still safe", "Faster", "A slow rollout that produces no information — no metric can be split by variant"], answer: 2,
    explain: "Emit an event at the decision point in the same commit as the flag; guardrails have nothing to compare otherwise." },
  { q: "In the measured estate, how many of 312 flags were doing nothing but adding branches?", options: ["12", "221", "None"], answer: 1,
    explain: "141 expired release toggles, 132 permanently on, 39 concluded experiments — and 27 of 31 kill switches had never been exercised." },
  { q: "Checking an A/B test daily rather than at a fixed end date took the false-positive rate from…", options: ["5% to 6%", "4.9% to 22.4%", "It has no effect"], answer: 1,
    explain: "Demonstrated on two identical variants. Fix the end date in advance, or use sequential methods designed for continuous monitoring." },
]},
{ title: "Quiz 9 · Security and Supply Chain",
  desc: "OIDC, masking, least privilege, script injection, provenance, signing, SBOMs, dependencies",
  questions: [
  { q: "The right threat model for CI is…", options: ["An attacker guesses a password", "Someone steals a secret from a vault", "Someone runs code in a context that already has the secret"], answer: 2,
    explain: "Contributors, third-party actions and every dependency's install script can all cause code to run with the job's identity." },
  { q: "OIDC federation replaces a static cloud key by…", options: ["Encrypting it", "Rotating it weekly", "Having the CI provider sign a short-lived token describing the run"], answer: 2,
    explain: "Nothing is stored, and the credentials expire in minutes — so there is no secret to leak and a stolen one is quickly useless." },
  { q: "An OIDC trust policy that checks only the `aud` claim is…", options: ["Invalid", "Correctly scoped", "Assumable by every workflow on the platform"], answer: 2,
    explain: "That claim is identical for everyone. Condition on `sub`, pinning repository plus branch or environment." },
  { q: "The strongest OIDC condition for a platform-owned deploy path is…", options: ["`job_workflow_ref` pinned to the reviewed reusable workflow at a tag", "`repository_owner`", "`actor`"], answer: 0,
    explain: "It means a team cannot obtain production credentials by writing their own workflow, even in the right repository and branch." },
  { q: "Secret masking fails on…", options: ["Long values", "Exact string matches", "base64, URL encoding, splitting and JSON serialisation"], answer: 2,
    explain: "`echo -n \"$S\" | base64` prints the secret in full. Masking is a backstop; scope and lifetime are the controls." },
  { q: "`pull_request_target` plus a checkout of the PR head is…", options: ["The standard preview pattern", "Required for forks", "The 'pwn request' — code execution with your secrets from any contributor"], answer: 2,
    explain: "Build fork PRs with `pull_request` — read-only token, no secrets — and publish results from a separate trusted `workflow_run` job." },
  { q: "`run: echo \"PR: ${{ github.event.pull_request.title }}\"` is vulnerable because…", options: ["Titles can be long", "The expression is interpolated into the shell script before it runs", "echo is unsafe"], answer: 1,
    explain: "A crafted title executes arbitrary commands. Pass untrusted data through `env:` and quote it; actionlint flags the pattern." },
  { q: "When a live cloud key is pushed to a public repository, the first action is…", options: ["Delete the repository", "Rewrite git history", "Rotate or revoke the credential"], answer: 2,
    explain: "Measured: cloned by a scanner in 11 seconds, used at 61, RunInstances attempted at 94. History rewriting cannot reach forks or caches." },
  { q: "Workflow permissions should start at…", options: ["Write", "Read-all", "`permissions: {}` — deny everything, then add the minimum per job"], answer: 2,
    explain: "One estate went from 54 of 61 workflows holding a write token to zero able to modify workflow files." },
  { q: "The most valuable separation in a pipeline is…", options: ["Build from test", "The job that installs dependencies from the job that holds publishing credentials", "Test from lint"], answer: 1,
    explain: "The build job executes enormous amounts of third-party code; merging them gives every transitive dependency your registry credentials." },
  { q: "Vulnerability scanning and provenance differ in that scanning finds…", options: ["Known-bad, while provenance establishes known-good", "Only licence issues", "Everything"], answer: 0,
    explain: "An attacker who compromises a build step produces an artifact with zero CVEs. Scanning is silent about that." },
  { q: "Provenance answers…", options: ["Whether it is vulnerable", "Where it came from: commit, repository, workflow, builder and inputs", "What is inside the image"], answer: 1,
    explain: "It is signed, so the person publishing the artifact cannot forge it — which is what SLSA L2 and L3 are about." },
  { q: "One audited estate signed 100% of its images. How many places verified a signature?", options: ["Only production", "All deploy paths", "Zero"], answer: 2,
    explain: "Signing without enforced verification changes nothing. Design the enforcement point first; signing is the easy half." },
  { q: "`cosign verify` with no identity assertion proves…", options: ["The image is from your pipeline", "Only that someone signed it", "That the SBOM is valid"], answer: 1,
    explain: "Pin `--certificate-identity-regexp` to the repository, workflow and branch, and pin the OIDC issuer." },
  { q: "An SBOM should be generated from…", options: ["The source tree", "The lockfile", "The final image digest"], answer: 2,
    explain: "The source tree listed 214 components where the image contained 389 — base-image packages, a vendored binary, and the one with the CVE." },
  { q: "With SBOMs attached per digest, answering 'which services ship this library?' took…", options: ["Six minutes, and it was complete", "Three days", "An hour"], answer: 0,
    explain: "Without them, grepping 60 lockfiles took three days and missed anything vendored or bundled." },
  { q: "Admission policy enforcement should be rolled out…", options: ["Never", "Audit-first — the measured first audit found 61 workloads that would have been rejected", "Immediately, in enforce mode"], answer: 1,
    explain: "44 were legacy, 9 external, 5 from the wrong workflow — and 3 had been built by hand, which was the real finding." },
  { q: "In the measured service, 47 packages were chosen and how many were installed?", options: ["1,284", "120", "47"], answer: 0,
    explain: "A 27x amplification from 891 maintainer namespaces, 38 of which execute code at install time." },
  { q: "Weekly grouped dependency updates against quarterly batches measured…", options: ["More effort overall", "No difference", "2 engineer-days a month vs 19 per batch, with fewer regressions"], answer: 2,
    explain: "And security fixes adopted in 2 days rather than up to 90 — plus quarterly batches get skipped because they are frightening." },
  { q: "847 advisories reduced to how many that were exploitable in the measured configuration?", options: ["All of them", "Nine", "One hundred"], answer: 1,
    explain: "847 raw → 31 in the production tree → 9 exploitable → 7 fixable. Gate on new+reachable+fixable; track the rest with an SLA." },
]},
{ title: "Quiz 10 · Mixed mock exam",
  desc: "Twenty questions drawn from every section of the track",
  questions: [
  { q: "Which number is most predictive of conflicts, review quality and revert rate?", options: ["Test coverage", "Lines of code", "Branch age at merge"], answer: 2,
    explain: "Measured 4% conflicts under a day against 61% at 14+ days, with the oldest 6.6% of PRs producing 44% of reverts." },
  { q: "A job in CI is a fresh machine; a step is…", options: ["A separate machine", "A new shell on that machine", "A container image"], answer: 1,
    explain: "Files persist between steps, shell state does not, and nothing at all persists between jobs." },
  { q: "The dominant cost of an end-to-end test is…", options: ["Diagnosis — 71 minutes measured, with 44% of failures being test fragility", "Its runtime", "Writing it"], answer: 0,
    explain: "About 8 engineer-hours per e2e test per year, against 0.07 for a unit test." },
  { q: "At 0.1% per-test flakiness across 1,100 tests, the share of green runs is…", options: ["33%", "99%", "90%"], answer: 0,
    explain: "Which is why teams stop reading failures — and why three production incidents came from real failures retried until green." },
  { q: "A gate people route around is…", options: ["Neutral", "Worse than no gate", "Better than nothing"], answer: 1,
    explain: "Same cost, false assurance, and it trains everyone that red means 'find the workaround'." },
  { q: "'Build once, promote the digest' exists because…", options: ["Digests are shorter", "Tags are mutable, so the bytes tested must be the bytes deployed", "It is faster"], answer: 1,
    explain: "Three builds of one commit let a base-image glibc change reach production only — three hours of debugging against an identical commit hash." },
  { q: "The four performance levers, in the order that pays, begin with…", options: ["Don't run it at all", "Make the work faster", "Buy bigger runners"], answer: 0,
    explain: "Cancellation, path filters and impact selection took 38 minutes to 19m20s before anyone touched code." },
  { q: "Queue time in the measured pipeline was…", options: ["6m20s of a 38-minute feedback loop, and invisible on dashboards", "Negligible", "The whole problem"], answer: 0,
    explain: "Measure `startedAt − createdAt`; its shape tells you whether the cause is a concurrency ceiling, pool size or autoscaler lag." },
  { q: "Disk exhaustion accounted for what share of one quarter's infrastructure failures?", options: ["20%", "5%", "61%"], answer: 2,
    explain: "All reported as flaky tests. A nightly `prune -af` made it worse by deleting the shared layer cache." },
  { q: "Retries should be decided by…", options: ["How many attempts remain", "Whether the author asks", "The failure's classified signature"], answer: 2,
    explain: "Retry infra_* and external_*; never 'the job failed', and never a non-idempotent step like a deploy or migration." },
  { q: "Without connection draining, the measured service lost…", options: ["Half its traffic", "Nothing", "1,840 requests per deploy"], answer: 2,
    explain: "0.046% of daily traffic — invisible in aggregate dashboards, which is why you must slice metrics by the deploy window." },
  { q: "A canary at 1% for five minutes typically cannot detect…", options: ["A crash loop", "A new exception type", "A 20–25% relative error-rate increase"], answer: 2,
    explain: "Size share and bake time from the effect you need to catch: ~262,000 samples per arm for +25% at a 0.2% baseline." },
  { q: "The compatibility matrix cell that proves rollback works is…", options: ["Old code against the new schema", "New code against the new schema", "Old code against the old schema"], answer: 0,
    explain: "It is also the cell almost nobody tests, which is why 'we could not roll back' is usually a schema story." },
  { q: "Feature flags make trunk-based development practical by…", options: ["Reducing test counts", "Letting incomplete work merge daily while staying dark", "Replacing code review"], answer: 1,
    explain: "Branch age stays under a day, and rollback becomes a 200 ms flip rather than a deploy." },
  { q: "A flag SDK must, when the flag service is unreachable…", options: ["Throw so the problem is visible", "Block until it recovers", "Serve the cached ruleset, or the hardcoded default — never throw"], answer: 2,
    explain: "Evaluating over the network per request turned a vendor timeout into a 41-minute checkout outage." },
  { q: "An OIDC role whose trust policy lacks a `sub` condition is…", options: ["Correctly scoped", "Assumable by any workflow on the platform", "Unusable"], answer: 1,
    explain: "Audit every CI role for this — it looks reasonable in review because the `aud` check is present." },
  { q: "Signing images without verifying them at deploy time…", options: ["Changes nothing about your posture", "Is impossible", "Materially improves security"], answer: 0,
    explain: "One estate signed 1,284 images and verified none. Enforce at admission, with identity pinned to the release workflow." },
  { q: "Change failure rate is only meaningful when reported…", options: ["Per engineer", "Paired with deployment frequency", "Alone, as a headline"], answer: 1,
    explain: "Throughput and stability constrain each other; reporting one alone produced a measured 340% frequency rise from empty redeploys." },
  { q: "Lead time measured from merge rather than first commit…", options: ["Hides the review queue, which is usually the real constraint", "Is the standard definition", "Is more accurate"], answer: 0,
    explain: "Same team, same quarter: 9 days from first commit, 4 hours from merge. Publish which definition you use and never change it silently." },
  { q: "A platform team's success metric should be…", options: ["Voluntary adoption", "Tickets closed", "Compliance percentage"], answer: 0,
    explain: "Compliance is satisfiable without using the thing — 100% compliance hid 41 escape scripts and 9 trivially-passing checks." },
]},
);
