// CI/CD quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Git Workflows & Branching",
  desc: "Trunk-based vs GitFlow, short-lived branches, merge strategy",
  questions: [
  { q: "Trunk-based development means…", options: ["Many long-lived branches", "Small, short-lived branches merged frequently to main", "No branches ever"], answer: 1,
    explain: "Frequent integration reduces merge pain." },
  { q: "A key benefit of short-lived branches is…", options: ["More conflicts", "Less merge conflict / integration pain", "Slower delivery"], answer: 1,
    explain: "Integrate early and often." },
  { q: "GitFlow is characterized by…", options: ["Only main", "Multiple long-lived branches (develop, release, feature)", "No releases"], answer: 1,
    explain: "Heavier; suits scheduled releases." },
  { q: "Trunk-based dev pairs naturally with…", options: ["Manual deploys only", "Feature flags (merge incomplete work safely)", "No CI"], answer: 1,
    explain: "Decouple deploy from release." },
  { q: "Continuous Integration requires…", options: ["Merging rarely", "Merging to a shared main frequently with automated checks", "No tests"], answer: 1,
    explain: "The 'integration' in CI." },
  { q: "Long-lived feature branches tend to…", options: ["Reduce risk", "Drift and cause big, painful merges", "Speed up CI"], answer: 1,
    explain: "Divergence grows over time." },
  { q: "A protected main branch typically requires…", options: ["Direct pushes", "PR review + passing checks before merge", "Nothing"], answer: 1,
    explain: "Quality gate on the trunk." },
  { q: "Squash merging…", options: ["Keeps every WIP commit", "Combines a PR's commits into one clean commit", "Deletes history"], answer: 1,
    explain: "Cleaner main history." },
  { q: "Trunk-based dev generally improves…", options: ["Lead time & deploy frequency", "Nothing measurable", "Only test coverage"], answer: 1,
    explain: "Small batches ship faster (DORA)." },
  { q: "A release branch in GitFlow is for…", options: ["Daily work", "Stabilizing a version before release", "Hotfixing main only"], answer: 1,
    explain: "Scheduled-release model." },
  { q: "Merging small changes frequently reduces…", options: ["Test coverage", "Merge conflicts and integration risk", "Deploy frequency"], answer: 1,
    explain: "Core CI principle." },
  { q: "Feature flags let you merge to main when…", options: ["Only when 100% complete", "Even if a feature is incomplete (behind an off flag)", "Never"], answer: 1,
    explain: "Enables trunk-based dev." },
  { q: "A downside of GitFlow for fast-moving teams is…", options: ["Too simple", "Overhead and slower integration", "No branches"], answer: 1,
    explain: "Heavy for continuous delivery." },
  { q: "Rebasing a feature branch onto main…", options: ["Creates conflicts intentionally", "Replays your commits on the latest main (linear history)", "Deletes commits"], answer: 1,
    explain: "Keeps history clean; avoid on shared branches." },
  { q: "The main branch in trunk-based dev should be…", options: ["Often broken", "Always releasable (green)", "Ignored"], answer: 1,
    explain: "Keep the trunk deployable." },
  { q: "Pull requests exist to…", options: ["Slow everyone down", "Enable review + automated checks before merge", "Skip CI"], answer: 1,
    explain: "Quality + collaboration gate." },
  { q: "Small PRs are preferred because…", options: ["They're harder to review", "They're easier to review and safer to merge", "They break CI"], answer: 1,
    explain: "Faster feedback, less risk." },
  { q: "Continuous Delivery means…", options: ["Auto-deploy every commit to prod", "Every change is ALWAYS in a deployable state (release on demand)", "No releases"], answer: 1,
    explain: "Deployable ≠ auto-deployed." },
  { q: "Continuous Deployment means…", options: ["Manual approvals always", "Every passing change auto-deploys to production", "No pipeline"], answer: 1,
    explain: "One step beyond delivery." },
  { q: "The overall aim of a good branching model is…", options: ["Maximize branches", "Fast, safe integration and releasable main", "Avoid merging"], answer: 1,
    explain: "Enable frequent, low-risk delivery." }
]},
{ title: "Quiz 2 · CI Fundamentals",
  desc: "What CI does, pipelines, stages, fast feedback",
  questions: [
  { q: "The core purpose of CI is to…", options: ["Deploy to prod", "Automatically build & test every change for fast feedback", "Write code"], answer: 1,
    explain: "Catch problems early." },
  { q: "A CI pipeline is triggered by…", options: ["Manual copy", "Events (push, PR, tag) automatically", "Nothing"], answer: 1,
    explain: "Automation on commit/PR." },
  { q: "A typical CI stage order is…", options: ["Deploy → build → test", "Build → test → (package) — fast checks first", "Test → nothing"], answer: 1,
    explain: "Fail fast on quick checks." },
  { q: "'Fail fast' means…", options: ["Never fail", "Run quick checks first so bad changes fail in seconds", "Ignore failures"], answer: 1,
    explain: "Lint/unit before slow e2e." },
  { q: "CI catches integration problems by…", options: ["Waiting for release", "Building/testing merged changes continuously", "Manual QA only"], answer: 1,
    explain: "Continuous verification." },
  { q: "A red pipeline should…", options: ["Be ignored", "Block the merge/deploy until fixed", "Auto-deploy anyway"], answer: 1,
    explain: "Keep main green." },
  { q: "CI reduces 'works on my machine' by…", options: ["Nothing", "Building/testing in a clean, consistent environment", "Using laptops"], answer: 1,
    explain: "Reproducible pipeline env." },
  { q: "Unit tests in CI run…", options: ["Rarely", "Fast, on every change (first line of defense)", "Only nightly"], answer: 1,
    explain: "Quick, high-signal checks." },
  { q: "A build ARTIFACT is…", options: ["Source code", "The packaged output (binary/image) produced once and reused", "A branch"], answer: 1,
    explain: "Build once, deploy many." },
  { q: "CI feedback should be…", options: ["Slow", "Fast (minutes) so developers act on it", "Optional"], answer: 1,
    explain: "Latency shapes behavior." },
  { q: "A pipeline 'job' is…", options: ["A single command", "A set of steps running in an environment (often parallelizable)", "A commit"], answer: 1,
    explain: "Jobs can run concurrently." },
  { q: "Running checks on a PR before merge…", options: ["Is pointless", "Prevents broken code from reaching main", "Slows nothing"], answer: 1,
    explain: "Gate before integration." },
  { q: "CI without automated tests is…", options: ["Ideal", "Mostly just automated building (weak safety net)", "Impossible"], answer: 1,
    explain: "Tests give CI its value." },
  { q: "Reproducible builds mean…", options: ["Random outputs", "Same inputs → same output (trustworthy artifacts)", "Faster CPUs"], answer: 1,
    explain: "Determinism aids trust/debugging." },
  { q: "A good pipeline is…", options: ["Manual and long", "Automated, fast, and reliable", "Flaky"], answer: 1,
    explain: "Trust requires reliability." },
  { q: "CI is a prerequisite for…", options: ["Nothing", "Continuous Delivery/Deployment", "Manual releases only"], answer: 1,
    explain: "CD builds on CI." },
  { q: "Flaky tests in CI…", options: ["Help", "Erode trust and cause wasteful reruns", "Speed pipelines"], answer: 1,
    explain: "Quarantine and fix them." },
  { q: "The 'build once' principle means…", options: ["Rebuild per environment", "Build a single artifact and promote it through envs", "Never build"], answer: 1,
    explain: "Consistency across stages." },
  { q: "CI status should be…", options: ["Hidden", "Visible to the team (a broken build is everyone's problem)", "Ignored"], answer: 1,
    explain: "Shared ownership of green." },
  { q: "The ultimate goal of CI is…", options: ["More meetings", "Fast, reliable feedback enabling frequent safe integration", "Fewer commits"], answer: 1,
    explain: "Speed + safety." }
]},
{ title: "Quiz 3 · GitHub Actions",
  desc: "Workflows, jobs, steps, triggers, matrix, runners",
  questions: [
  { q: "A GitHub Actions workflow is defined in…", options: ["package.json", "YAML under .github/workflows/", "A Dockerfile"], answer: 1,
    explain: "Declarative pipeline config." },
  { q: "'on:' in a workflow specifies…", options: ["The runner", "The trigger events (push, pull_request, schedule)", "The secrets"], answer: 1,
    explain: "When the workflow runs." },
  { q: "A workflow contains…", options: ["Only one step", "Jobs, each with steps", "Only secrets"], answer: 1,
    explain: "Jobs → steps hierarchy." },
  { q: "By default, jobs in a workflow…", options: ["Run sequentially", "Run in PARALLEL unless 'needs:' is set", "Never run"], answer: 1,
    explain: "Fan out for speed." },
  { q: "'needs:' between jobs creates…", options: ["Parallelism", "A dependency (ordering)", "A secret"], answer: 1,
    explain: "Only use for real dependencies." },
  { q: "'runs-on:' sets…", options: ["The trigger", "The runner (e.g., ubuntu-latest)", "The branch"], answer: 1,
    explain: "Where the job executes." },
  { q: "A 'uses:' step…", options: ["Runs a shell command", "Invokes a reusable action", "Sets a secret"], answer: 1,
    explain: "Composable building blocks." },
  { q: "A 'run:' step…", options: ["Invokes an action", "Runs shell commands", "Defines a trigger"], answer: 1,
    explain: "Arbitrary commands." },
  { q: "A matrix strategy is used to…", options: ["Store secrets", "Run a job across multiple configs/shards in parallel", "Deploy"], answer: 1,
    explain: "e.g., multiple Node versions or test shards." },
  { q: "Secrets in Actions are accessed via…", options: ["Plaintext in YAML", "${{ secrets.NAME }} (masked in logs)", "The repo README"], answer: 1,
    explain: "Never hardcode secrets." },
  { q: "actions/cache is used to…", options: ["Deploy", "Cache dependencies/build outputs across runs", "Store secrets"], answer: 1,
    explain: "Speed via caching." },
  { q: "Third-party actions should be pinned to…", options: ["A moving tag", "A full commit SHA (supply-chain safety)", "Nothing"], answer: 1,
    explain: "Prevents malicious tag swaps." },
  { q: "concurrency with cancel-in-progress…", options: ["Runs everything", "Cancels superseded runs on new pushes", "Adds runners"], answer: 1,
    explain: "Don't waste runners on stale commits." },
  { q: "A workflow artifact (upload-artifact)…", options: ["Is a secret", "Persists build outputs for later jobs/download", "Is a runner"], answer: 1,
    explain: "Pass data between jobs/runs." },
  { q: "environment: with required reviewers…", options: ["Speeds deploys", "Gates a deploy job behind manual approval", "Disables CI"], answer: 1,
    explain: "Protected deployment environments." },
  { q: "A self-hosted runner is…", options: ["Always faster and free", "Your own machine running jobs (warm caches, custom hardware)", "A GitHub secret"], answer: 1,
    explain: "Trade-off: you maintain/secure it." },
  { q: "GITHUB_TOKEN in a workflow is…", options: ["A permanent PAT", "An auto-generated, scoped, short-lived token", "Your password"], answer: 1,
    explain: "Least-privilege by default." },
  { q: "pull_request vs push triggers differ in…", options: ["Nothing", "What event starts the workflow (PR events vs branch pushes)", "The runner OS"], answer: 1,
    explain: "Choose the right trigger." },
  { q: "Reusable/composite workflows help…", options: ["Duplicate YAML", "Share pipeline logic across repos/jobs (DRY)", "Store secrets"], answer: 1,
    explain: "Avoid copy-paste pipelines." },
  { q: "A job step failing by default…", options: ["Is ignored", "Fails the job (unless continue-on-error)", "Passes the job"], answer: 1,
    explain: "Fail-fast semantics." }
]},
{ title: "Quiz 4 · Testing & Quality Gates",
  desc: "Test pyramid, coverage, linting, security scans, gates",
  questions: [
  { q: "The test pyramid says have MOST…", options: ["E2E tests", "Fast unit tests (fewer integration, fewest e2e)", "Manual tests"], answer: 1,
    explain: "Fast, cheap, stable base." },
  { q: "E2E tests are…", options: ["Fastest and most numerous", "Slow, fewer, high-value (test the whole flow)", "Unnecessary"], answer: 1,
    explain: "Top of the pyramid." },
  { q: "A quality gate…", options: ["Auto-approves", "Blocks the pipeline unless criteria are met", "Deploys code"], answer: 1,
    explain: "e.g., tests pass + coverage threshold." },
  { q: "Linting checks…", options: ["Runtime bugs only", "Code style/quality statically (fast feedback)", "Deployments"], answer: 1,
    explain: "Cheap early check." },
  { q: "SAST scans…", options: ["Running apps", "Source code for security issues (static)", "Networks"], answer: 1,
    explain: "Static application security testing." },
  { q: "SCA scans…", options: ["Your own code", "Dependencies for known CVEs", "Runners"], answer: 1,
    explain: "Software composition analysis." },
  { q: "Code coverage measures…", options: ["Code quality", "How much code is exercised by tests", "Performance"], answer: 1,
    explain: "A signal, not a guarantee." },
  { q: "Chasing 100% coverage can…", options: ["Guarantee quality", "Produce low-value tests / false confidence", "Speed CI"], answer: 1,
    explain: "Coverage ≠ correctness." },
  { q: "Fast tests should run…", options: ["After slow ones", "Before slow ones (fail fast)", "Never"], answer: 1,
    explain: "Quick feedback on obvious breaks." },
  { q: "Flaky tests should be…", options: ["Ignored", "Quarantined and fixed", "Run more"], answer: 1,
    explain: "They erode trust." },
  { q: "Secret scanning in CI catches…", options: ["Slow tests", "Committed credentials/keys", "Style issues"], answer: 1,
    explain: "Prevent leaked secrets." },
  { q: "Integration tests verify…", options: ["A single function", "Multiple components working together", "UI styling only"], answer: 1,
    explain: "Middle of the pyramid." },
  { q: "A gate on 'no high/critical CVEs' means…", options: ["Warnings only", "The build FAILS if a critical vuln is found", "Nothing"], answer: 1,
    explain: "Enforce, don't just report." },
  { q: "Running e2e on every tiny change is…", options: ["Always ideal", "Often too slow — gate/schedule them wisely", "Impossible"], answer: 1,
    explain: "Balance coverage vs speed." },
  { q: "Quality gates should be…", options: ["Advisory only", "Enforced (blocking) for critical criteria", "Removed"], answer: 1,
    explain: "Otherwise they're ignored." },
  { q: "IaC scanning checks…", options: ["Test coverage", "Terraform/K8s configs for misconfigurations", "Latency"], answer: 1,
    explain: "Shift security left." },
  { q: "Shift-left means…", options: ["Test after release", "Catch issues EARLIER in the pipeline (cheaper to fix)", "Skip testing"], answer: 1,
    explain: "Earlier = cheaper." },
  { q: "A good test suite is…", options: ["Slow and flaky", "Fast, reliable, and meaningful", "100% e2e"], answer: 1,
    explain: "Trustworthy signal." },
  { q: "Mutation testing evaluates…", options: ["Coverage %", "Whether tests actually catch injected bugs", "Performance"], answer: 1,
    explain: "Test effectiveness, not just coverage." },
  { q: "The point of quality gates is…", options: ["Slow teams down", "Prevent low-quality/insecure code from progressing", "Skip review"], answer: 1,
    explain: "Automated standards enforcement." }
]},
{ title: "Quiz 5 · Artifacts & Versioning",
  desc: "Build-once artifacts, immutability, semver, registries",
  questions: [
  { q: "The 'build once, deploy many' principle means…", options: ["Rebuild per environment", "Build ONE artifact and promote it through envs", "Never build"], answer: 1,
    explain: "Consistency + reproducibility." },
  { q: "A build artifact should be…", options: ["Mutable", "Immutable (never changed after build)", "Rebuilt each deploy"], answer: 1,
    explain: "What you tested is what you ship." },
  { q: "Rebuilding per environment risks…", options: ["Nothing", "Environment drift (different bytes in prod)", "Faster deploys"], answer: 1,
    explain: "Promote one artifact instead." },
  { q: "Semantic versioning (semver) is…", options: ["Random numbers", "MAJOR.MINOR.PATCH conveying change type", "A branch name"], answer: 1,
    explain: "Communicates compatibility." },
  { q: "A breaking change bumps the…", options: ["PATCH", "MAJOR version", "Nothing"], answer: 1,
    explain: "MAJOR = incompatible API changes." },
  { q: "A backward-compatible feature bumps the…", options: ["MAJOR", "MINOR version", "Build number only"], answer: 1,
    explain: "MINOR = added functionality." },
  { q: "A bug fix bumps the…", options: ["MAJOR", "PATCH version", "MINOR"], answer: 1,
    explain: "PATCH = backward-compatible fixes." },
  { q: "An artifact registry stores…", options: ["Source only", "Built artifacts/images for distribution", "Secrets"], answer: 1,
    explain: "npm/Maven/container registries, etc." },
  { q: "Deploying by immutable digest/version (not 'latest') gives…", options: ["Ambiguity", "Reproducible, traceable deploys", "Faster builds"], answer: 1,
    explain: "Know exactly what's running." },
  { q: "Tying an artifact to its git commit (traceability) lets you…", options: ["Nothing", "Know exactly which source produced it", "Skip tests"], answer: 1,
    explain: "Provenance/debugging." },
  { q: "A container image is a good artifact because…", options: ["It's mutable", "It's immutable and bundles app + deps", "It's source code"], answer: 1,
    explain: "Perfect build-once unit (Docker track)." },
  { q: "Mutable 'latest' tags in prod are…", options: ["Best practice", "Risky — they can point to different bytes over time", "Immutable"], answer: 1,
    explain: "Pin versions/digests." },
  { q: "Retention/cleanup policies on a registry…", options: ["Waste money", "Garbage-collect old artifacts (cost/space)", "Break builds"], answer: 1,
    explain: "Registry hygiene." },
  { q: "Promoting an artifact means…", options: ["Rebuilding it", "Moving the SAME tested artifact dev → staging → prod", "Deleting it"], answer: 1,
    explain: "No rebuild between stages." },
  { q: "Pre-release versions (e.g., 1.2.0-rc.1) indicate…", options: ["Stable release", "A candidate not yet final", "A patch"], answer: 1,
    explain: "Semver pre-release identifiers." },
  { q: "Storing an SBOM with an artifact helps…", options: ["Nothing", "Answer 'what's inside / are we affected by a CVE?'", "Speed builds"], answer: 1,
    explain: "Supply-chain visibility." },
  { q: "Version pinning of dependencies (lockfiles) ensures…", options: ["Random versions", "Reproducible dependency resolution", "Latest always"], answer: 1,
    explain: "Deterministic builds." },
  { q: "An artifact's checksum/digest lets you…", options: ["Guess contents", "Verify integrity (it wasn't altered)", "Deploy faster"], answer: 1,
    explain: "Content-addressable integrity." },
  { q: "Automated version bumping (e.g., from commit messages)…", options: ["Is impossible", "Can derive semver from conventional commits", "Breaks CI"], answer: 1,
    explain: "e.g., semantic-release." },
  { q: "The reason to never rebuild for prod is…", options: ["Speed only", "The prod artifact might differ from what you tested", "Cost only"], answer: 1,
    explain: "Test-what-you-ship integrity." }
]}
);
