// nodejs quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Runtime, Modules & the Basics",
  desc: "V8, libuv, ESM/CJS, npm, globals, process",
  questions: [
  { q: "Node = V8 + …?", options: ["jQuery", "libuv (async I/O event loop) + core C++ bindings", "a browser DOM"], answer: 1,
    explain: "V8 runs the JS; libuv provides the event loop and async I/O. There is no DOM/window in Node." },
  { q: "The modern module system for new Node code is…", options: ["AMD", "CommonJS (require)", "ES Modules (import/export)"], answer: 2,
    explain: "ESM is the standard; recognize CJS require/module.exports in legacy code. Set \"type\":\"module\" in package.json." },
  { q: "npm ci differs from npm install by…", options: ["Ignoring the lockfile", "Installing EXACTLY the lockfile, clean, failing on mismatch — reproducible", "Being slower"], answer: 1,
    explain: "CI/deploys use npm ci so the tested tree is the shipped tree." },
  { q: "process.env is for…", options: ["Process memory stats", "The event loop", "Environment variables — config and secrets injected at runtime"], answer: 2,
    explain: "12-factor config lives in env vars, never hardcoded; secrets come from a secret manager." },
  { q: "__dirname is unavailable in ESM; the replacement is…", options: ["process.cwd()", "__filename still works", "import.meta.url (+ fileURLToPath)"], answer: 2,
    explain: "ESM has no __dirname/__filename; derive paths from import.meta.url." },
  { q: "node:fs vs fs import specifier — the node: prefix…", options: ["Explicitly targets a built-in, avoiding shadowing by an npm package named 'fs'", "Is required always", "Is decoration"], answer: 0,
    explain: "node: prefixes make built-in imports unambiguous and are the recommended style." },
  { q: "package.json \"scripts\" exist to…", options: ["Define canonical team commands (dev/test/build) run via npm run", "Document code", "Configure V8"], answer: 0,
    explain: "One source of truth for how to run the project; CI uses the same scripts." },
  { q: "The event loop being single-threaded means…", options: ["Each request gets a thread", "One thread runs your JS; blocking it blocks ALL requests", "Node can't do concurrency"], answer: 1,
    explain: "Concurrency comes from async I/O, not threads-per-request. CPU work must not block." },
  { q: "dependencies vs devDependencies:", options: ["Same thing", "Alphabetical split", "Runtime-shipped vs build/test-only (excluded via --omit=dev in prod)"], answer: 2,
    explain: "A test runner in dependencies bloats the production image." },
  { q: "globalThis in Node refers to…", options: ["The global object (works across Node/browser/workers)", "window", "module.exports"], answer: 0,
    explain: "There's no window in Node; globalThis is the portable global reference." },
  { q: "Reading a file WITHOUT blocking uses…", options: ["a while loop", "fs.promises.readFile / await", "fs.readFileSync"], answer: 1,
    explain: "Sync APIs block the single thread — never on the request path in a server." },
  { q: "The Buffer type is for…", options: ["Caching", "Raw binary data (files, network, crypto)", "Logging"], answer: 1,
    explain: "Buffers hold bytes; strings need an encoding to become Buffers and back." },
  { q: "package-lock.json should be…", options: ["committed — it pins the exact resolved dependency tree", "deleted on conflicts", "gitignored"], answer: 0,
    explain: "The lockfile is the reproducibility contract; 'works on my machine' is usually lock drift." },
  { q: "A CommonJS module's exports mechanism is…", options: ["export default", "module.exports / exports", "window.x"], answer: 1,
    explain: "require() reads module.exports; ESM uses static import/export enabling tree-shaking." },
  { q: "Top-level await is available in…", options: ["Only inside functions", "Nowhere", "ES modules"], answer: 2,
    explain: "ESM supports top-level await (handy for config/init); it delays dependent modules." },
  { q: "process.argv contains…", options: ["Env vars", "Command-line arguments", "Exit codes"], answer: 1,
    explain: "argv[0]=node, argv[1]=script path, rest = user args; libraries like commander parse them." },
  { q: "Why is Node good for I/O-bound APIs specifically?", options: ["Non-blocking I/O lets one thread juggle thousands of waiting connections cheaply", "Fast CPU math", "Multithreading by default"], answer: 0,
    explain: "While one request awaits the DB, the thread serves others. CPU-bound work is Node's weakness." },
  { q: "nvm / Volta / the engines field manage…", options: ["Memory", "The Node VERSION per project", "Dependencies"], answer: 1,
    explain: "Pin Node versions so everyone runs the same runtime; engines documents the requirement." },
  { q: "A native addon or WASM is used when…", options: ["Never needed", "You need C/C++/Rust-speed CPU work callable from Node", "For all I/O"], answer: 1,
    explain: "Image processing, crypto, compression often use native/WASM under a JS API." },
  { q: "The correct 2026 project starter is roughly…", options: ["npm init, ESM, TypeScript, a test runner, ESLint/Prettier, .env handling", "Just index.js", "Copy a gist"], answer: 0,
    explain: "Same tooling discipline as the JS modules lesson — automated quality from day one." },
]},
{ title: "Quiz 2 · HTTP & Express Fundamentals",
  desc: "http module, routing, req/res, status codes, Express basics",
  questions: [
  { q: "Express is…", options: ["A bundler", "A minimal HTTP framework: routing + middleware over node:http", "A database"], answer: 1,
    explain: "It structures the raw http server into routes and a middleware pipeline." },
  { q: "The correct status for a successfully created resource is…", options: ["200", "204", "201 Created (+ Location header)"], answer: 2,
    explain: "201 signals creation; 200 = OK, 204 = no content, 202 = accepted (async)." },
  { q: "app.get('/users/:id') — id is read via…", options: ["req.params.id", "req.query.id", "req.body.id"], answer: 0,
    explain: "params = path segments, query = ?a=b, body = request payload." },
  { q: "To parse a JSON request body you need…", options: ["express.json() middleware", "Nothing", "req.json()"], answer: 0,
    explain: "Without a body parser, req.body is undefined." },
  { q: "A route handler that never sends a response…", options: ["Returns null", "Auto-404s", "Hangs the request until timeout"], answer: 2,
    explain: "You must res.send/json/end or call next(); otherwise the client waits." },
  { q: "400 vs 401 vs 403 vs 404:", options: ["bad request / unauthenticated / authenticated-but-forbidden / not found", "All 'error'", "Random"], answer: 0,
    explain: "401 = who are you; 403 = I know you, no; 404 = doesn't exist (also used to hide existence)." },
  { q: "req.query values are always…", options: ["Strings (parse/validate them)", "Numbers", "Booleans"], answer: 0,
    explain: "?page=2 gives \"2\"; coerce and validate (zod) before use." },
  { q: "The idempotent HTTP methods include…", options: ["GET, PUT, DELETE (same call, same effect)", "POST", "Only GET"], answer: 0,
    explain: "POST is non-idempotent (creates each time); idempotency matters for retries." },
  { q: "res.json(obj) does…", options: ["Only stringifies", "Logs obj", "Sets Content-Type: application/json AND sends the serialized body"], answer: 2,
    explain: "It handles the header + JSON.stringify + send in one call." },
  { q: "Route order in Express matters because…", options: ["Alphabetical", "The FIRST matching route/middleware wins — specific before catch-all", "It doesn't"], answer: 1,
    explain: "Put '*' 404 handlers last; specific routes before parameterized ones when ambiguous." },
  { q: "500 means…", options: ["Not found", "Server error — OUR fault, log loudly, don't leak details", "Client error"], answer: 1,
    explain: "5xx = server; 4xx = client. Return a generic message for 5xx, details to logs." },
  { q: "Reading a header:", options: ["req.getHeader()", "req.header only", "req.headers['content-type'] (lowercased)"], answer: 2,
    explain: "Node lowercases incoming header names; req.get('X') is Express's helper." },
  { q: "CORS is needed when…", options: ["Always", "Never for APIs", "A browser on a DIFFERENT origin calls your API — configure allowed origins"], answer: 2,
    explain: "CORS is a browser policy; set specific origins, not '*', for credentialed requests." },
  { q: "Streaming a large file to the response uses…", options: ["res.send(buffer)", "pipeline(createReadStream, res)", "res.json"], answer: 1,
    explain: "Streaming = constant memory; buffering the whole file risks OOM (streams lesson)." },
  { q: "The 429 status means…", options: ["Redirect", "Too Many Requests — rate limited (send Retry-After)", "Server error"], answer: 1,
    explain: "Rate limiting returns 429; clients should back off." },
  { q: "A REST collection endpoint for listing users is…", options: ["POST /users/list", "GET /getUsers", "GET /users"], answer: 2,
    explain: "REST uses nouns + HTTP verbs: GET /users, POST /users, GET /users/:id." },
  { q: "Sending 204 implies…", options: ["An error", "Success with NO body (e.g., DELETE)", "Redirect"], answer: 1,
    explain: "204 No Content — don't attach a body." },
  { q: "The raw node:http server callback signature is…", options: ["(err, data)", "(req, res)", "(req)"], answer: 1,
    explain: "http.createServer((req,res)=>…); Express wraps this with routing + middleware." },
  { q: "Content negotiation via the Accept header lets…", options: ["The client request JSON vs HTML etc.; the server responds accordingly", "Caching only", "Auth"], answer: 0,
    explain: "APIs typically serve JSON; res.format() can branch on Accept." },
  { q: "A 301 vs 302 redirect:", options: ["Same", "301 permanent (cached/SEO), 302 temporary", "Both errors"], answer: 1,
    explain: "Permanent moves use 301; temporary/situational use 302/307." },
]},
{ title: "Quiz 3 · Middleware & the Request Pipeline",
  desc: "Middleware order, next(), error middleware, composition",
  questions: [
  { q: "Express middleware signature is…", options: ["(req, res)", "(err, req, res)", "(req, res, next)"], answer: 2,
    explain: "next() passes control on; error middleware has FOUR args (err, req, res, next)." },
  { q: "Middleware runs in…", options: ["Reverse order", "Registration order — a pipeline each request flows through", "Random order"], answer: 1,
    explain: "app.use order defines the chain: logging → parse → auth → routes → error handler." },
  { q: "Forgetting to call next() (and not responding)…", options: ["Auto-continues", "Hangs the request", "Errors immediately"], answer: 1,
    explain: "Middleware must either respond or call next()." },
  { q: "Error-handling middleware is identified by…", options: ["A try/catch", "Its name", "Having FOUR parameters (err first)"], answer: 2,
    explain: "Express detects the 4-arg signature and routes errors to it." },
  { q: "The error handler should be registered…", options: ["LAST, after all routes", "First", "In the middle"], answer: 0,
    explain: "Errors bubble to the end of the pipeline; it maps them to responses." },
  { q: "Throwing in an ASYNC handler in older Express…", options: ["Is caught automatically", "Is NOT caught — wrap or use express-async-errors / Express 5", "Crashes always"], answer: 1,
    explain: "Async rejections bypass the error handler unless wrapped; Express 5 fixes this." },
  { q: "Cross-cutting concerns (auth, logging, rate limit) belong in…", options: ["Every handler copy-pasted", "The database", "Middleware applied once"], answer: 2,
    explain: "Middleware is how you apply a concern across many routes DRY-ly." },
  { q: "Attaching req.user in auth middleware means…", options: ["Downstream handlers read the authenticated user off the request", "A memory leak", "A hack"], answer: 0,
    explain: "Middleware enriches the request object for later stages." },
  { q: "Router-level middleware (express.Router) is for…", options: ["Grouping routes + shared middleware under a path prefix", "Nothing", "Databases"], answer: 0,
    explain: "Modularizes large apps: const r = Router(); app.use('/api/users', r)." },
  { q: "helmet() middleware adds…", options: ["Compression", "Security headers (CSP, HSTS, nosniff…)", "Caching"], answer: 1,
    explain: "One line applies the HTML-security-lesson headers to every response." },
  { q: "A per-request id middleware helps with…", options: ["Auth", "Speed", "Log correlation — trace one request across log lines"], answer: 2,
    explain: "req.id on every log line + in the response ties them together (errors lesson)." },
  { q: "Order bug: body parser AFTER the route that reads req.body →", options: ["Faster", "req.body is undefined in that route", "Fine"], answer: 1,
    explain: "Middleware must run BEFORE the handler that depends on it." },
  { q: "Terminating middleware (sends a response) means…", options: ["It errors", "It calls next()", "It ends the pipeline (res.send) — later middleware won't run"], answer: 2,
    explain: "A response ends the chain; don't call next() after responding." },
  { q: "Validation middleware (zod) typically…", options: ["Caches", "Parses/validates req and either passes clean data on or throws a 400", "Logs"], answer: 1,
    explain: "Validate at the boundary; hand typed data to handlers (the TS boundary rule)." },
  { q: "next('route') vs next(err):", options: ["Same", "'route' skips to the next matching route; next(err) jumps to error handling", "Both error"], answer: 1,
    explain: "next(err) short-circuits to the 4-arg handler; next('route') skips remaining handlers of THIS route." },
  { q: "Compression middleware…", options: ["Encrypts", "Validates", "gzip/br-compresses responses to cut bytes over the wire"], answer: 2,
    explain: "Often better at the reverse-proxy/CDN layer, but available as middleware." },
  { q: "The middleware pattern generalizes to…", options: ["Only Express", "Koa, Fastify hooks, and the 'onion'/pipeline model broadly", "Nothing"], answer: 1,
    explain: "Composable request pipelines are a broad server pattern; Fastify uses hooks/plugins." },
  { q: "Global error middleware should log 5xx at…", options: ["info", "error (and 4xx at warn) — severity matches whose fault it is", "silent"], answer: 1,
    explain: "5xx = our bug (loud + alert); 4xx = client (quiet)." },
  { q: "Rate limiting across MULTIPLE instances requires…", options: ["A shared store (Redis) — memory counters don't coordinate across processes", "Nothing", "In-memory counters"], answer: 0,
    explain: "The stateless-tier rule: shared state goes to Redis (scaling lesson)." },
  { q: "The single biggest benefit of the middleware model is…", options: ["Security", "Composability — build request handling from small, reusable, ordered units", "Speed"], answer: 1,
    explain: "Concerns are layered independently and reused across routes." },
]},
{ title: "Quiz 4 · REST API Design & Validation",
  desc: "Resource modeling, status codes, pagination, versioning, validation",
  questions: [
  { q: "RESTful design centers on…", options: ["Nouns (resources) + HTTP methods for actions", "RPC calls", "Verbs in URLs (/getUser)"], answer: 0,
    explain: "GET/POST/PUT/PATCH/DELETE on /users, /users/:id — the verb is the method." },
  { q: "PUT vs PATCH:", options: ["Same", "PATCH creates", "PUT replaces the whole resource; PATCH updates fields"], answer: 2,
    explain: "PUT is idempotent full-replace; PATCH applies a partial change." },
  { q: "Validate incoming data…", options: ["In the DB only", "Never, trust the client", "At the boundary (zod/Joi) — reject bad input with 400 before logic"], answer: 2,
    explain: "Client validation is UX; the server MUST re-validate (HTML forms lesson)." },
  { q: "Pagination for large collections uses…", options: ["limit/offset or cursor-based paging", "Return everything", "Random sampling"], answer: 0,
    explain: "Cursor pagination is stabler under inserts; always bound page size." },
  { q: "API versioning is commonly done via…", options: ["/v1/ path or a version header — so changes don't break clients", "Renaming fields silently", "Never version"], answer: 0,
    explain: "Breaking changes need a new version; additive changes can be unversioned." },
  { q: "A 422 vs 400:", options: ["Same", "Both client errors; 422 = well-formed but semantically invalid (many APIs just use 400)", "422 is server"], answer: 1,
    explain: "Pick one convention and be consistent; return field-level error details." },
  { q: "Idempotency keys on POST /payments prevent…", options: ["Double-charging on client retries (same key → same result, one charge)", "Nothing", "Slow requests"], answer: 0,
    explain: "Critical for money: retries must not duplicate side effects." },
  { q: "Returning the created resource's location uses…", options: ["201 + Location header pointing to /resource/:id", "Body only", "302 redirect"], answer: 0,
    explain: "Clients learn where to fetch the new resource." },
  { q: "Filtering/sorting a collection is expressed via…", options: ["POST bodies", "Query params: ?status=paid&sort=-createdAt", "New endpoints per filter"], answer: 1,
    explain: "Keep one collection endpoint; parameterize via query." },
  { q: "Consistent error responses should include…", options: ["A machine-readable code + message (+ field errors + request id)", "Just a string", "Stack traces"], answer: 0,
    explain: "Clients branch on code; never leak stacks. Ties to the errors lesson." },
  { q: "HATEOAS refers to…", options: ["A database", "Hypermedia links in responses guiding clients to related actions", "A cache"], answer: 1,
    explain: "Full REST maturity; most APIs adopt it partially or not at all — know the term." },
  { q: "N+1 queries in a list endpoint mean…", options: ["A security bug", "One query per row (fetching relations in a loop) — batch or join instead", "Good performance"], answer: 1,
    explain: "The DB-lesson classic; use joins, IN queries, or dataloaders." },
  { q: "Returning 200 with {\"error\":...} instead of a 4xx/5xx is…", options: ["Best practice", "An anti-pattern — HTTP status IS the error channel", "Required"], answer: 1,
    explain: "Clients, proxies, and monitoring rely on status codes; don't hide errors in 200s." },
  { q: "Rate-limit headers (X-RateLimit-*) let clients…", options: ["See remaining quota and back off before hitting 429", "Cache", "Authenticate"], answer: 0,
    explain: "Good API citizenship; pair with 429 + Retry-After." },
  { q: "A GET endpoint should…", options: ["Mutate data", "Be safe (no side effects) and idempotent — cacheable", "Delete resources"], answer: 1,
    explain: "GETs with side effects break caching, prefetching, and crawlers." },
  { q: "OpenAPI/Swagger provides…", options: ["Auth", "A database", "A machine-readable API contract → docs, client codegen, validation"], answer: 2,
    explain: "Contract-first APIs generate types/clients and catch drift." },
  { q: "Soft delete (deletedAt) vs hard delete:", options: ["Soft delete flags the row (recoverable, audit); hard delete removes it", "Soft is slower always", "Identical"], answer: 0,
    explain: "Choose per domain; soft delete needs query filters everywhere." },
  { q: "Bulk operations should…", options: ["Be disallowed", "Loop single requests", "Offer a batch endpoint with partial-success semantics (allSettled-style)"], answer: 2,
    explain: "One request, per-item results — avoids chatty round-trips." },
  { q: "The response envelope decision (raw vs {data, meta}) should be…", options: ["Random per endpoint", "Consistent across the API", "Always raw"], answer: 1,
    explain: "Consistency lets clients write one response handler; document the choice." },
  { q: "Backward-compatible schema change means…", options: ["Removing a field", "ADDING optional fields (old clients ignore them)", "Renaming fields"], answer: 1,
    explain: "Additive = safe; removals/renames are breaking → version it (expand/contract)." },
]},
{ title: "Quiz 5 · Authentication & Authorization",
  desc: "Sessions vs JWT, hashing, OAuth, cookies, authz",
  questions: [
  { q: "Passwords must be stored…", options: ["Plaintext for support", "HASHED with bcrypt/argon2 + per-password salt", "Encrypted (reversible)"], answer: 1,
    explain: "Hashing is one-way; slow salted hashes resist brute force. Never encrypt/store plaintext." },
  { q: "Authentication vs authorization:", options: ["AuthN = who you are; AuthZ = what you may do", "Same", "AuthZ comes first"], answer: 0,
    explain: "Verify identity, THEN check permissions per action/resource." },
  { q: "Session-based auth stores state…", options: ["Server-side (session id in a cookie) — revocable instantly", "In localStorage", "In the token"], answer: 0,
    explain: "Sessions are stateful and easy to revoke; scale via a shared session store (Redis)." },
  { q: "A JWT is…", options: ["A signed (not encrypted) token: header.payload.signature — self-contained, verify the signature", "Encrypted always", "A session id"], answer: 0,
    explain: "Payload is base64, readable — never put secrets in it; the signature proves integrity." },
  { q: "JWT's main weakness vs sessions is…", options: ["Revocation — a valid token works until expiry unless you add a denylist", "Size", "Speed"], answer: 0,
    explain: "Mitigate with short-lived access tokens + refresh tokens + rotation." },
  { q: "Auth tokens belong in…", options: ["the URL", "HttpOnly Secure SameSite cookies — JS (and XSS) can't read them", "localStorage"], answer: 1,
    explain: "localStorage is XSS-readable (JS security lesson); HttpOnly cookies aren't." },
  { q: "The access + refresh token pattern gives…", options: ["Nothing", "Weaker security", "Short-lived access (limits theft window) + long-lived refresh (rotated) for UX"], answer: 2,
    explain: "Refresh rotation + reuse-detection is the standard for JWT revocation-ish behavior." },
  { q: "OAuth 2.0 / OIDC is for…", options: ["Rate limiting", "Delegated auth ('Sign in with Google') — you never see the user's password", "Password storage"], answer: 1,
    explain: "Authorization Code + PKCE is the current best-practice flow; OIDC adds identity." },
  { q: "CSRF is mitigated primarily by…", options: ["SameSite cookies (+ anti-CSRF tokens / Origin checks)", "CORS", "HTTPS"], answer: 0,
    explain: "CORS does NOT prevent CSRF; SameSite=Lax/Strict is the main defense." },
  { q: "bcrypt's cost factor controls…", options: ["Salt size", "Hash length", "Work factor — higher = slower = more brute-force resistant (tune to hardware)"], answer: 2,
    explain: "Raise the cost as hardware improves; argon2id is the modern preference." },
  { q: "RBAC means…", options: ["Rate-based access", "Role-Based Access Control — permissions grouped into roles", "Random access"], answer: 1,
    explain: "Users get roles; roles grant permissions. ABAC adds attribute/context rules." },
  { q: "A protected route's server check is…", options: ["MANDATORY — client-side guards are UX, the API enforces", "Optional if the UI hides the button", "Only for admins"], answer: 0,
    explain: "Never trust the client; the API is the security boundary (router lesson echo)." },
  { q: "Broken Object-Level Authorization (BOLA/IDOR) is…", options: ["A cache miss", "Accessing another user's resource by id because the server didn't check ownership — OWASP #1 API risk", "A UI bug"], answer: 1,
    explain: "Always verify the authenticated user owns/may access the requested resource." },
  { q: "Storing a JWT signing secret…", options: ["In the repo", "In env/secret manager, rotated; asymmetric (RS256) for multi-service verify", "In the token"], answer: 1,
    explain: "Leaked secret = forge any token. RS256 lets services verify with a public key." },
  { q: "MFA adds security by…", options: ["A longer password", "Requiring a second factor (TOTP/passkey) beyond the password", "Encrypting the DB"], answer: 1,
    explain: "Defends against credential theft; passkeys/WebAuthn are phishing-resistant." },
  { q: "Rate-limiting the login endpoint prevents…", options: ["Nothing", "CSRF", "Credential stuffing / brute force"], answer: 2,
    explain: "Throttle + lockout + CAPTCHA on repeated failures." },
  { q: "'Login' should return errors that are…", options: ["Generic ('invalid credentials') to avoid username enumeration", "Detailed", "Specific ('wrong password')"], answer: 0,
    explain: "Don't reveal whether the email exists; same for password reset responses." },
  { q: "Refresh token rotation with reuse detection means…", options: ["Tokens never change", "Each refresh issues a new one; a replayed old token signals theft → revoke the family", "Nothing"], answer: 1,
    explain: "Detects stolen refresh tokens and invalidates the session lineage." },
  { q: "Password reset tokens must be…", options: ["Single-use, short-lived, and stored hashed", "Reusable", "In the URL forever"], answer: 0,
    explain: "Treat them like credentials; expire and invalidate after use." },
  { q: "The safest place to enforce authz logic is…", options: ["Frontend", "A central server-side layer (middleware/policies) applied consistently", "Per-component"], answer: 1,
    explain: "Scattered checks drift; centralize policy so every route enforces it." },
]},
);
