// Node.js quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Databases & Persistence",
  desc: "Pools, transactions, SQL injection, N+1, ORMs, migrations",
  questions: [
  { q: "A database CONNECTION POOL exists to…", options: ["Encrypt data", "Reuse a bounded set of connections — opening one per request is slow and exhausts the DB", "Cache queries"], answer: 1,
    explain: "Pools cap concurrent connections and recycle them; size to the DB's limits." },
  { q: "SQL injection is prevented by…", options: ["Escaping quotes yourself", "Parameterized queries / prepared statements", "Hiding the query"], answer: 1,
    explain: "Never string-concatenate user input into SQL; pass values as parameters ($1, ?)." },
  { q: "A transaction guarantees…", options: ["Speed", "Atomicity — all statements commit or none do (ACID)", "Caching"], answer: 1,
    explain: "BEGIN/COMMIT/ROLLBACK; money transfers and multi-table writes need them." },
  { q: "The N+1 query problem is…", options: ["A network error", "One query per parent row to fetch relations — fix with joins/IN/dataloader", "A pool leak"], answer: 1,
    explain: "Loading 100 users then a query each for their orders = 101 queries; batch it." },
  { q: "An index speeds reads by…", options: ["Compressing rows", "Letting the DB find rows without scanning the whole table — at write/space cost", "Caching results"], answer: 1,
    explain: "Index the columns you filter/sort/join on; too many indexes slow writes." },
  { q: "ORM vs query builder vs raw SQL — the trade-off is…", options: ["ORM always best", "Convenience/safety vs control; know SQL regardless of the abstraction", "Raw always best"], answer: 1,
    explain: "ORMs speed CRUD but hide N+1s and complex queries; you still must understand SQL." },
  { q: "Database migrations are…", options: ["Backups", "Versioned, ordered schema changes checked into git and run in CI/CD", "Manual ALTERs in prod"], answer: 1,
    explain: "Reproducible schema evolution; never hand-edit production schemas." },
  { q: "Zero-downtime schema change uses…", options: ["Big-bang ALTER", "Expand/contract: add new, backfill, migrate code, then remove old", "Downtime windows"], answer: 1,
    explain: "Old and new code run together during deploys, so changes must be backward-compatible." },
  { q: "Connection leak (not releasing to the pool) causes…", options: ["Faster queries", "Pool exhaustion — new requests hang waiting for a free connection", "Data loss"], answer: 1,
    explain: "Always release in finally / use the pool's query helper that auto-releases." },
  { q: "Optimistic vs pessimistic locking:", options: ["Same", "Optimistic = version check on write (retry on conflict); pessimistic = lock rows upfront", "Both lock"], answer: 1,
    explain: "Optimistic scales better under low contention; pessimistic for hot rows." },
  { q: "SELECT * in production code is discouraged because…", options: ["It's illegal", "It fetches unneeded columns, breaks on schema change, and hurts index-only scans", "It's slow to type"], answer: 1,
    explain: "Select explicit columns; more stable and often faster." },
  { q: "Read replicas are used to…", options: ["Store backups", "Offload READ traffic from the primary (accepting replication lag)", "Speed writes"], answer: 1,
    explain: "Most apps are read-heavy; replicas scale reads (System Design track)." },
  { q: "A statement timeout protects against…", options: ["Injection", "A slow/runaway query holding a connection and cascading failures", "Deadlocks only"], answer: 1,
    explain: "Bound query time so one bad query can't stall the pool." },
  { q: "Storing money as a floating-point number is…", options: ["Fine", "A bug — use integer minor units or DECIMAL/NUMERIC", "Faster"], answer: 1,
    explain: "IEEE floats can't represent 0.10 exactly (JS types lesson); use exact types." },
  { q: "The repository pattern…", options: ["Caches", "Isolates data access behind an interface — swappable, testable", "Is an ORM"], answer: 1,
    explain: "Keeps SQL/ORM details out of business logic; eases testing." },
  { q: "Batch inserts vs row-by-row:", options: ["Same speed", "Batching (multi-row INSERT / COPY) is dramatically faster for bulk loads", "Row-by-row is faster"], answer: 1,
    explain: "Each round-trip has overhead; batch within a transaction (streams lesson import)." },
  { q: "SQL vs NoSQL choice hinges on…", options: ["Popularity", "Data shape, relationships, consistency needs, and access patterns", "Language"], answer: 1,
    explain: "Relational + transactions → SQL; flexible documents/scale patterns → NoSQL (DB tracks)." },
  { q: "A deadlock happens when…", options: ["The server crashes", "Two transactions each hold a lock the other needs — the DB kills one; retry", "The pool is full"], answer: 1,
    explain: "Acquire locks in a consistent order to reduce them; handle the retry." },
  { q: "EXPLAIN / query plans tell you…", options: ["The result", "HOW the DB executes a query (seq scan vs index) — the tuning tool", "Errors"], answer: 1,
    explain: "Seq scans on big tables = missing index; read the plan before optimizing." },
  { q: "Eventual consistency means…", options: ["Data is lost", "Replicas converge after a delay — reads may be briefly stale", "Strong consistency"], answer: 1,
    explain: "A distributed-systems trade-off (CAP); design UX around read-your-writes where needed." }
]},

{ title: "Quiz 7 · Errors, Logging & Observability",
  desc: "Error taxonomy, operational vs programmer, structured logs, the 3 pillars",
  questions: [
  { q: "Operational vs programmer errors:", options: ["Same", "Expected runtime failures (handle per-request) vs bugs (log + crash/restart)", "Both crash"], answer: 1,
    explain: "isOperational decides: known failure → respond & continue; bug → clean restart." },
  { q: "Structured JSON logging beats console.log strings because…", options: ["Prettier", "Log platforms INDEX fields — you query level:error AND path:/checkout", "Smaller"], answer: 1,
    explain: "Queryable, correlatable, alertable; pino is the Node standard." },
  { q: "A per-request child logger carries…", options: ["Nothing", "Context (reqId, userId) on every line automatically — enables tracing", "The whole DB"], answer: 1,
    explain: "reqId ties log lines to each other and to the response." },
  { q: "Stack traces should be sent to…", options: ["The client", "Logs only — a generic message goes to the client (no info disclosure)", "Nowhere"], answer: 1,
    explain: "Leaking stacks reveals paths/versions; keep details server-side." },
  { q: "unhandledRejection/uncaughtException handlers should…", options: ["Fix and continue", "Log the evidence, then exit for a clean restart (state may be corrupt)", "Be omitted"], answer: 1,
    explain: "Last-resort loud-then-exit; a supervisor restarts a fresh process." },
  { q: "Error chaining with { cause } provides…", options: ["Speed", "Business context on top + the root cause underneath in the log", "Encryption"], answer: 1,
    explain: "Re-throwing without cause destroys the trail (JS errors lesson)." },
  { q: "The three observability pillars are…", options: ["CPU, RAM, disk", "Logs, metrics, traces", "Dev, staging, prod"], answer: 1,
    explain: "Logs = events, metrics = rates/latencies, traces = request path across services." },
  { q: "Logging secrets/PII/tokens is…", options: ["Helpful", "A compliance breach — redact; log ids not values", "Required"], answer: 1,
    explain: "pino redact paths strip sensitive fields; never log passwords/tokens." },
  { q: "An empty catch {} is…", options: ["Defensive", "The cardinal sin — bugs vanish silently", "Required for async"], answer: 1,
    explain: "Handle, or log and rethrow; lint no-empty catch." },
  { q: "Log levels (trace…fatal) let you…", options: ["Nothing", "Control verbosity per environment and filter noise from signal", "Encrypt"], answer: 1,
    explain: "debug in dev, info+ in prod; error/fatal drive alerts." },
  { q: "Metrics like p99 latency and event-loop LAG belong…", options: ["In logs", "On a dashboard with alerting — the earliest blocking signal", "Nowhere"], answer: 1,
    explain: "Loop lag rising under load = something is blocking (event-loop lesson)." },
  { q: "A distributed TRACE lets you…", options: ["Store data", "Follow one request across multiple services to find the slow hop", "Log locally"], answer: 1,
    explain: "OpenTelemetry propagates a trace id across service boundaries." },
  { q: "Alerting should page on…", options: ["Every log line", "Symptoms users feel (SLO breaches: error rate, latency)", "Info logs"], answer: 1,
    explain: "Alert on symptoms + error budgets, not raw occurrences — reduces fatigue." },
  { q: "A generic 5xx client message + full server log is because…", options: ["Laziness", "Security (no leaks) + debuggability (full detail internally) — both", "Speed"], answer: 1,
    explain: "reqId in the response lets support correlate to the detailed log." },
  { q: "Correlating a user's error report to logs uses…", options: ["Guessing", "The request id returned in the response, searched in the log platform", "The stack trace they screenshot"], answer: 1,
    explain: "reqId is the thread connecting the two — why it's on every line." },
  { q: "Health of the event loop is measured with…", options: ["console.log", "perf_hooks monitorEventLoopDelay", "process.exit"], answer: 1,
    explain: "Track mean/max delay; export it as a metric." },
  { q: "Sentry-style error aggregation groups by…", options: ["Time", "Stack/fingerprint — dedupes occurrences, alerts on NEW types & spikes", "User"], answer: 1,
    explain: "You fix error TYPES, not individual events." },
  { q: "A good error message contains…", options: ["'Error'", "What failed, for which entity, and next step ('Invoice #4211 timeout after 3 retries')", "The whole stack"], answer: 1,
    explain: "Written for the 3am responder (errors lesson)." },
  { q: "Retrying an operational error (503) vs a programmer error:", options: ["Retry both", "Retry transient operational failures with backoff; never retry bugs", "Retry neither"], answer: 1,
    explain: "The taxonomy answers 'is it retryable?'." },
  { q: "SLOs and error budgets are…", options: ["Logs", "Reliability targets (99.9%) that govern alerting and release pace", "Metrics dashboards only"], answer: 1,
    explain: "Burn the budget → slow down and stabilize (System Design observability)." }
]},

{ title: "Quiz 8 · Event Loop, Streams & Performance",
  desc: "libuv phases, blocking, thread pool, streams, backpressure",
  questions: [
  { q: "Node's event loop phases (order) include…", options: ["Only timers", "timers → pending → poll → check → close", "Random"], answer: 1,
    explain: "nextTick + microtasks drain between every phase and callback." },
  { q: "process.nextTick priority vs promises:", options: ["Lower", "Higher — nextTick runs before promise microtasks", "Equal"], answer: 1,
    explain: "Recursive nextTick starves the loop; prefer promises in app code." },
  { q: "setImmediate inside an I/O callback vs setTimeout(0):", options: ["Timeout wins", "setImmediate wins (poll → check is next; timers is a loop away)", "Random"], answer: 1,
    explain: "In the main module they race; inside I/O it's deterministic." },
  { q: "CPU-bound work on the request path…", options: ["Is fine", "Blocks the single thread — freezing ALL requests", "Uses more cores"], answer: 1,
    explain: "Offload to worker_threads or a job queue (scaling lesson)." },
  { q: "The libuv thread pool (default 4) handles…", options: ["Network sockets", "fs, dns.lookup, async crypto, zlib — NOT sockets (those use the OS)", "Nothing"], answer: 1,
    explain: "Saturating it queues 'async' work; tune UV_THREADPOOL_SIZE or use workers." },
  { q: "Streams process data…", options: ["All at once", "In chunks → constant memory for huge inputs", "Twice"], answer: 1,
    explain: "readFile buffers everything (OOM risk); streaming is bounded memory." },
  { q: "Backpressure is…", options: ["A cache", "Flow control: write() returns false → pause the reader until 'drain'", "An error"], answer: 1,
    explain: "Without it a fast producer buffers unbounded in memory → OOM." },
  { q: "The safe way to connect streams is…", options: [".pipe() bare", "pipeline() — propagates errors and cleans up", "manual loops"], answer: 1,
    explain: "pipe without error handling leaks descriptors on failure." },
  { q: "Readable streams can be consumed with…", options: ["Only callbacks", "for await…of (async iteration) with natural backpressure", "JSON.parse"], answer: 1,
    explain: "Streams are async-iterable (generators lesson); readline for line-by-line." },
  { q: "The four stream types are…", options: ["In, out, up, down", "Readable, Writable, Transform, Duplex", "Sync, async, fast, slow"], answer: 1,
    explain: "gzip is a Transform; TCP sockets are Duplex." },
  { q: "Ignoring write()'s return value in a write loop causes…", options: ["Nothing", "Unbounded buffering (OOM) despite 'streaming'", "Faster writes"], answer: 1,
    explain: "That's exactly what backpressure/pipeline prevent." },
  { q: "JSON.parse on a 30MB string in a handler…", options: ["Is async", "BLOCKS the loop (CPU-bound, no async version) → latency spike", "Streams"], answer: 1,
    explain: "Stream/paginate large data or parse in a worker (event-loop lesson)." },
  { q: "Event-loop lag rising under load indicates…", options: ["Healthy", "Something is BLOCKING the thread — investigate sync work", "Low traffic"], answer: 1,
    explain: "It's the p99-latency early warning; keep it on the dashboard." },
  { q: "One thread serving 10k connections works because…", options: ["10k threads", "Network I/O is async (OS epoll); the thread runs OTHER callbacks while awaiting", "Magic"], answer: 1,
    explain: "Connections are cheap state, not threads — until CPU work hogs the loop." },
  { q: "Streaming a 2GB download instead of readFile+send gives…", options: ["More memory use", "Constant memory, lower TTFB, backpressure-matched to the client", "Slower start"], answer: 1,
    explain: "Buffering 2GB × concurrency = OOM; streaming avoids it." },
  { q: "A Transform stream is used to…", options: ["Only read", "Read → modify → write (gzip, encrypt, parse) inline in a pipeline", "Store data"], answer: 1,
    explain: "pipeline(read, gzip, write) compresses with constant memory." },
  { q: "Destroying a source stream on client abort prevents…", options: ["Nothing", "Orphaned reads continuing after the client left", "Faster reads"], answer: 1,
    explain: "res.on('close') → source.destroy() releases resources." },
  { q: "Heavy CPU crypto (bcrypt) many-parallel can…", options: ["Never block", "Saturate the 4-thread pool, queuing other async work", "Speed up I/O"], answer: 1,
    explain: "Raise the pool size or move to workers for heavy crypto." },
  { q: "The right tool for a 40s report generation is…", options: ["Do it in the handler", "Enqueue a job (202) + worker processes — decouple latency from duration", "Bigger timeout"], answer: 1,
    explain: "The async-job pattern (scaling lesson)." },
  { q: "Reading a huge log file line-by-line without OOM uses…", options: ["readFileSync", "readline over a read stream (async iteration)", "JSON.parse"], answer: 1,
    explain: "Constant memory regardless of file size (streams lesson)." }
]},

{ title: "Quiz 9 · Scaling, Testing & Production",
  desc: "Cluster vs workers, stateless tier, supertest, graceful shutdown, health",
  questions: [
  { q: "One Node process uses…", options: ["All cores", "One CPU core — scale with process-per-core (cluster/PM2/K8s)", "No cores"], answer: 1,
    explain: "Cluster/orchestration runs N processes for throughput." },
  { q: "Horizontal scaling REQUIRES…", options: ["Bigger servers", "A STATELESS web tier — sessions/caches/counters externalized to Redis/DB", "In-memory state"], answer: 1,
    explain: "In-memory session breaks the moment a second instance exists." },
  { q: "Cluster vs worker_threads:", options: ["Same", "Cluster = request throughput across cores; workers = CPU-bound compute off the loop", "Workers scale requests"], answer: 1,
    explain: "Different axes; cluster doesn't fix a single blocking computation." },
  { q: "Integration tests should hit…", options: ["Mocked DB", "A REAL test DB (containers / transaction rollback) — mocking hides SQL bugs", "Production"], answer: 1,
    explain: "Mocking the DB tests your mock, not your queries." },
  { q: "supertest is used to…", options: ["Load test", "Drive real routes through the full middleware stack in tests", "Mock the DB"], answer: 1,
    explain: "Export app (no listen) and request(app).post(...).expect(201)." },
  { q: "Mock at the boundary means…", options: ["Mock your repo", "Intercept third-party HTTP (nock/MSW), not your own code", "Mock everything"], answer: 1,
    explain: "Your request-building and error handling run for real; only edges are faked." },
  { q: "Graceful shutdown on SIGTERM…", options: ["Exits instantly", "Stops accepting, drains in-flight requests, closes resources — zero-downtime deploys", "Ignores signals"], answer: 1,
    explain: "K8s/Docker send SIGTERM on rollout; honoring it prevents dropped requests." },
  { q: "Liveness vs readiness probes:", options: ["Same", "Liveness fail = RESTART; readiness fail = stop routing traffic (don't restart)", "Both restart"], answer: 1,
    explain: "A DB blip → unready (un-route), still alive (no crash loop)." },
  { q: "Test isolation is best achieved with…", options: ["Shared fixtures", "Transaction-per-test rollback (or truncate) — pristine, fast", "Sleeping"], answer: 1,
    explain: "Shared mutable state → order-dependent flakes (the mutation trap)." },
  { q: "The testing trophy prioritizes…", options: ["Mostly unit", "Many INTEGRATION tests (real stack) + few unit + few E2E", "Only E2E"], answer: 1,
    explain: "Integration catches routing/middleware/validation/error-mapping together." },
  { q: "A production Dockerfile should…", options: ["Run as root, include devDeps", "Multi-stage, --omit=dev, small base, USER node, NODE_ENV=production", "Copy everything"], answer: 1,
    explain: "Least privilege + small attack surface + no dev bloat (production lesson)." },
  { q: "NODE_ENV=production…", options: ["Does nothing", "Skips dev overhead; libraries optimize", "Enables debug"], answer: 1,
    explain: "Express and many libs check it for perf/behavior." },
  { q: "The async-job pattern for heavy work is…", options: ["Block the response", "POST enqueues a job → 202 + jobId → worker processes it → client polls/webhook", "Bigger timeouts"], answer: 1,
    explain: "Decouples request latency from work duration; the queue absorbs spikes." },
  { q: "A worker POOL (piscina) is preferable to spawn-per-task because…", options: ["Slower", "It reuses threads sized to cores — avoiding churn/memory", "It's required"], answer: 1,
    explain: "Same as thread-pool reasoning; bound to hardware." },
  { q: "Testing authorization (BOLA) means asserting…", options: ["Only 200s", "User A CANNOT access user B's resource (404/403)", "Speed"], answer: 1,
    explain: "The OWASP #1 API risk; cover it in integration tests (auth lesson)." },
  { q: "Force-exit timeout in graceful shutdown exists because…", options: ["Speed", "If draining hangs, exit anyway rather than block the deploy forever", "It's optional"], answer: 1,
    explain: "setTimeout(()=>exit(1), 10s).unref() as the backstop." },
  { q: "Sticky sessions / pub-sub adapter for websockets solve…", options: ["Nothing", "Cross-instance message delivery when connections land on different pods", "Auth"], answer: 1,
    explain: "Stateful sockets need Redis pub/sub or affinity in a multi-instance tier." },
  { q: "Determinism in tests (clock/uuid) is achieved by…", options: ["Real time", "Injecting them or fake timers — so tests don't flake", "Random"], answer: 1,
    explain: "Non-deterministic time/random causes intermittent failures." },
  { q: "Zero-downtime deploy also requires DB migrations that are…", options: ["Big-bang", "Backward-compatible (expand/contract) so old+new run together", "Downtime"], answer: 1,
    explain: "Old pods serve during rollout; schema must not break them." },
  { q: "PM2 / Kubernetes provide…", options: ["A database", "Process supervision: restarts, rolling deploys, health checks, autoscaling", "A framework"], answer: 1,
    explain: "Orchestration operationalizes cluster/health/shutdown concepts." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "Your API freezes for all users intermittently. Most likely cause?", options: ["Slow DB replica", "Something CPU-bound (sync crypto/JSON.parse/loop) blocking the single thread", "Too few routes"], answer: 1,
    explain: "Confirm with event-loop lag; move the work to workers/async variants." },
  { q: "Passwords in your DB are AES-encrypted. Correct?", options: ["Yes, encryption is strong", "No — passwords must be HASHED (argon2/bcrypt), not reversibly encrypted", "Only if the key rotates"], answer: 1,
    explain: "Encryption is reversible; a key leak exposes all passwords. Hash + salt." },
  { q: "GET /orders/123 returns another user's order. Which vuln?", options: ["XSS", "BOLA/IDOR — missing ownership check", "CSRF"], answer: 1,
    explain: "Verify the authenticated user may access the requested id (auth lesson)." },
  { q: "Deploys drop in-flight requests (users see 502s). Fix?", options: ["Bigger servers", "Graceful shutdown: readiness→unready, drain server, then exit on SIGTERM", "Retry client-side"], answer: 1,
    explain: "A lifecycle bug — honor SIGTERM and drain (production lesson)." },
  { q: "A list endpoint runs 200 queries for 200 items. Diagnosis?", options: ["Pool leak", "N+1 — batch with a join / IN / dataloader", "Deadlock"], answer: 1,
    explain: "One query per relation in a loop; fetch relations in bulk." },
  { q: "setInterval(()=>heavyParse(),100) makes latency spike. Why?", options: ["Timers are slow", "heavyParse blocks the loop each tick — offload to a worker", "Memory leak"], answer: 1,
    explain: "CPU on the main thread starves request handling." },
  { q: "Your session-based login breaks after adding a second instance. Cause?", options: ["Bad password", "In-memory sessions aren't shared — move them to Redis (stateless tier)", "CORS"], answer: 1,
    explain: "Horizontal scaling needs externalized state (scaling lesson)." },
  { q: "A 2GB file download OOMs under load. Fix?", options: ["More RAM forever", "Stream it (pipeline) instead of readFile + send", "Compress the RAM"], answer: 1,
    explain: "Buffering the whole file × concurrency = OOM; stream for constant memory." },
  { q: "Tests pass but production SQL breaks. Likely cause?", options: ["Flaky CI", "The DB was MOCKED in tests — use a real test DB", "Wrong Node version"], answer: 1,
    explain: "Mocking the DB validated assumptions, not queries (testing lesson)." },
  { q: "JWTs can't be revoked instantly. Standard mitigation?", options: ["Longer tokens", "Short-lived access tokens + rotating refresh tokens (+ denylist if needed)", "Store in localStorage"], answer: 1,
    explain: "Limits the theft window; refresh rotation detects reuse." },
  { q: "A slow upstream hangs your whole fleet. Missing?", options: ["More routes", "Timeouts (AbortSignal.timeout) + circuit breaking at every hop", "A cache"], answer: 1,
    explain: "Unbounded waits cascade; bound every external call." },
  { q: "error-handling middleware never catches your async errors. Why?", options: ["Wrong port", "Async rejections bypass it without wrapping (pre-Express 5)", "It's disabled"], answer: 1,
    explain: "Wrap handlers / use express-async-errors / Express 5." },
  { q: "String-concatenating user input into SQL. Risk?", options: ["Slow query", "SQL injection — use parameterized queries", "Deadlock"], answer: 1,
    explain: "Never build SQL from raw input; parameterize (DB + security lessons)." },
  { q: "A DB outage makes K8s restart-loop your pods. Cause?", options: ["Bad image", "Liveness probe fails on DB down — should be READINESS (un-route, not restart)", "OOM"], answer: 1,
    explain: "Don't tie liveness to external deps; use readiness (production lesson)." },
  { q: "console.log JSON everywhere, can't debug a specific request. Missing?", options: ["More logs", "Structured logging + a request id correlating all lines", "A profiler"], answer: 1,
    explain: "reqId + JSON fields make logs queryable (errors lesson)." },
  { q: "Retrying a 400 Bad Request repeatedly. Correct?", options: ["Yes, retry all", "No — 4xx are client errors; retry only transient operational failures with backoff", "Retry once"], answer: 1,
    explain: "The taxonomy says which errors are retryable." },
  { q: "Payment endpoint double-charges on client retry. Fix?", options: ["Faster server", "Idempotency keys — same key returns the same result, one charge", "Disable retries"], answer: 1,
    explain: "Money endpoints must be idempotent (REST lesson)." },
  { q: "Your 'async' crypto calls queue mysteriously under load. Cause?", options: ["V8 bug", "libuv thread pool (4) saturated — raise UV_THREADPOOL_SIZE or use workers", "Network"], answer: 1,
    explain: "Async crypto/zlib/fs share the pool; sockets don't (event-loop lesson)." },
  { q: "Secrets are baked into your Docker image. Problem?", options: ["None", "Anyone with the image reads them — inject at runtime via secret manager", "Slower build"], answer: 1,
    explain: "Never bake secrets; also run non-root (production + security lessons)." },
  { q: "The single most important Node backend mental model is…", options: ["Memorize APIs", "One thread + async I/O: never block the loop; scale stateless + queues + workers", "Use TypeScript"], answer: 1,
    explain: "Every scaling/perf/reliability answer derives from it. 🏆" }
]}
);
