// python quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Syntax, Types & Variables",
  desc: "The name/object model, mutability, copying and identity",
  questions: [
  { q: "In Python, assignment binds…", options: ["A copy of the value to the variable", "A name to an object; the object holds the value", "A value into a variable's storage box"], answer: 1,
    explain: "Names are labels attached to objects. `b = a` gives one object two labels — nothing is copied, which is why mutating through one is visible through the other." },
  { q: "`a is b` differs from `a == b` because…", options: ["`is` works only on numbers", "`is` compares identity — the same object — while `==` compares value", "`is` is faster for the same result"], answer: 1,
    explain: "Two equal lists are `==` but not `is`. Use `is` only for singletons: None, True, False." },
  { q: "`x = 256; y = 256; x is y` is True, but the same with 257 may be False because…", options: ["It is undefined behaviour", "CPython pre-caches small integers, so they are shared objects", "Integers above 256 are mutable"], answer: 1,
    explain: "An implementation detail, not a language rule — which is exactly why identity is the wrong operator for comparing values." },
  { q: "`def f(items=[])` is a bug because the default list is…", options: ["Created fresh on each call but never cleared", "Created once, when the `def` executes, and shared by every call", "Immutable and cannot be appended to"], answer: 1,
    explain: "Defaults are evaluated at definition time and stored on the function. You can watch it accumulate in `f.__defaults__`." },
  { q: "The correct fix for a mutable default is…", options: ["Declare it global", "Copy the default inside the function", "`def f(items=None)` then `if items is None: items = []`"], answer: 2,
    explain: "None is the sentinel; the fresh object is created per call. Immutable defaults (0, None, \"\", tuples) are safe as-is." },
  { q: "`copy.copy(obj)` versus `copy.deepcopy(obj)`:", options: ["They are identical for lists", "Shallow copies are read-only", "Shallow copies the container but shares the nested objects; deep copies recursively"], answer: 2,
    explain: "After a shallow copy of a list of lists, mutating an inner list is visible through both." },
  { q: "Which of these is immutable?", options: ["dict", "list", "tuple"], answer: 2,
    explain: "Tuples cannot be reassigned — but a tuple CONTAINING a list still has a mutable interior, which is why `([1],)` is unhashable." },
  { q: "Python is best described as…", options: ["Strongly and dynamically typed", "Weakly and dynamically typed", "Strongly and statically typed"], answer: 0,
    explain: "Dynamic: names have no declared type. Strong: `\"1\" + 1` raises rather than silently coercing, unlike JavaScript." },
  { q: "The values that are falsy include…", options: ["Only False and None", "0, 0.0, \"\", [], {}, set(), None, False", "Any value except True"], answer: 1,
    explain: "Empty containers are falsy, which is why `if items:` reads well — and why `if count:` is a bug when 0 is a legitimate value." },
  { q: "`x += [1]` on a list differs from `x = x + [1]` in that…", options: ["`+=` mutates the list in place, so other names bound to it see the change", "They are exactly equivalent", "`+=` is only valid for numbers"], answer: 0,
    explain: "`+=` calls `__iadd__` for lists, extending in place; `x = x + [1]` binds a new list, leaving other references pointing at the old one." },
  { q: "A tuple can be used as a dict key only when…", options: ["Everything inside it is also hashable", "It contains only strings", "It has fewer than 10 elements"], answer: 0,
    explain: "Hashability is recursive. `(1, 2)` works; `(1, [2])` raises TypeError because lists are unhashable." },
  { q: "`None` should be tested with…", options: ["`== None`", "`is None`", "`not x`"], answer: 1,
    explain: "None is a singleton, so identity is exact. `not x` is wrong — it is also true for 0, \"\" and empty containers." },
  { q: "The walrus operator `:=` exists to…", options: ["Declare a constant", "Compare with type coercion", "Assign inside an expression, such as a while condition or comprehension filter"], answer: 2,
    explain: "`while (chunk := f.read(8192)):` avoids the read-once-before-the-loop-and-again-inside duplication." },
  { q: "Passing a list to a function and appending inside it…", options: ["Raises unless the parameter is marked mutable", "Modifies only a local copy", "Modifies the caller's list, because the name inside refers to the same object"], answer: 2,
    explain: "Python passes object references by value. Rebinding the parameter does not affect the caller; mutating the object does." },
  { q: "`type(x) == list` is generally worse than `isinstance(x, list)` because…", options: ["It is slower", "It rejects subclasses of list", "It does not work for built-ins"], answer: 1,
    explain: "isinstance respects the type hierarchy, which is what polymorphism requires." },
  { q: "`0.1 + 0.2 == 0.3` is False because…", options: ["Python rounds inconsistently", "== is not defined for floats", "Binary floating point cannot represent 0.1 or 0.2 exactly"], answer: 2,
    explain: "Use `math.isclose` for tolerance, or `decimal.Decimal` when exactness matters — money being the obvious case." },
  { q: "The scope of a name assigned inside a function is…", options: ["Determined at runtime by the caller", "Local, unless declared `global` or `nonlocal`", "Global unless declared local"], answer: 1,
    explain: "Any assignment anywhere in the body makes the name local for the whole body — which is why reading it before that line raises UnboundLocalError." },
  { q: "Strings are immutable, so `s += \"x\"` in a loop…", options: ["Mutates the string in place efficiently", "Is a syntax error", "Builds a new string each iteration — O(n²) overall"], answer: 2,
    explain: "Accumulate into a list and `\"\".join(parts)` at the end, which is linear." },
  { q: "`del x` removes…", options: ["Only the value, leaving the name defined", "The name binding; the object is collected when nothing references it", "The object from memory immediately"], answer: 1,
    explain: "Names are removed; objects are reference-counted, so the object dies only when the last reference does." },
  { q: "Everything in Python being an object means…", options: ["Primitives do not exist at all in any form", "Every value must be wrapped in a class you write", "Functions, classes and modules can be assigned, passed and stored"], answer: 2,
    explain: "This is what makes decorators, higher-order functions and monkeypatching possible." },
]},
{ title: "Quiz 2 · Control Flow & Functions",
  desc: "Truthiness, loops, parameters, closures, pattern matching and exceptions",
  questions: [
  { q: "`for ... else` executes the else block…", options: ["Always, after the loop", "Only if the loop finished without hitting `break`", "Only if the loop body never ran"], answer: 1,
    explain: "It is the search idiom: else means 'not found'. Reads badly enough that many teams avoid it — but it appears in interviews." },
  { q: "The five kinds of function parameter are…", options: ["required, optional, default, variadic, typed", "positional-only, positional-or-keyword, var-positional, keyword-only, var-keyword", "public, private, static, class, instance"], answer: 1,
    explain: "`def f(a, /, b, *args, c, **kwargs)` uses all five. `/` and `*` are the separators." },
  { q: "In `def f(a, /, b)`, the `/` means…", options: ["`a` is positional-only and cannot be passed by keyword", "`a` is optional", "Integer division of the arguments"], answer: 0,
    explain: "It lets you rename the parameter later without breaking callers — which is why many stdlib functions use it." },
  { q: "In `def f(*, timeout)`, the bare `*` means…", options: ["timeout accepts any number of values", "timeout is unpacked from a tuple", "timeout is keyword-only — `f(5)` raises"], answer: 2,
    explain: "Keyword-only parameters make call sites self-documenting: `f(timeout=5)` rather than a bare `5`." },
  { q: "LEGB describes name resolution order as…", options: ["Local, Enclosing, Global, Built-in", "Late, Early, Global, Boxed", "Lexical, Explicit, Global, Bound"], answer: 0,
    explain: "The first scope that has the name wins; built-ins are last, which is why naming a variable `list` shadows the type." },
  { q: "`[lambda: i for i in range(3)]` produces functions that all return 2 because…", options: ["Closures capture the VARIABLE, not its value at creation time", "Lambdas cannot capture loop variables", "The list comprehension runs backwards"], answer: 0,
    explain: "Late binding. Bind eagerly with a default: `lambda i=i: i`." },
  { q: "`nonlocal x` in a nested function…", options: ["Rebinds `x` in the nearest enclosing function scope", "Declares `x` read-only", "Creates a module-level global"], answer: 0,
    explain: "Without it, assigning to `x` creates a new local and the outer value is untouched." },
  { q: "A closure is…", options: ["A function plus the enclosing bindings it references", "Any function defined at module level", "A function that closes its file handles"], answer: 0,
    explain: "You can inspect them: `f.__closure__` holds the captured cells." },
  { q: "`match` statements match by…", options: ["Identity only", "Structure — the shape of the value, with capture into names", "Regular expressions on the string form"], answer: 1,
    explain: "`case Point(x=0, y=y):` destructures and binds. It is structural pattern matching, not a switch." },
  { q: "In a `match`, a bare name in a case pattern…", options: ["Is a syntax error", "Compares against that variable's value", "CAPTURES the value — it always matches and rebinds the name"], answer: 2,
    explain: "The classic trap: `case RED:` does not compare with the constant, it captures everything. Use a dotted name, `case Colour.RED:`." },
  { q: "EAFP means…", options: ["Check every precondition before acting", "Explicitly annotate function parameters", "Try the operation and handle the failure, rather than checking first"], answer: 2,
    explain: "It avoids the check-then-act race, and is idiomatic — but raising is expensive, so LBYL wins in a hot loop where failure is common." },
  { q: "A bare `except:` is dangerous because it also catches…", options: ["Nothing extra — it is just style", "SyntaxError at import time", "KeyboardInterrupt and SystemExit, making the program impossible to stop"], answer: 2,
    explain: "`except Exception:` at minimum; ideally the specific types you can actually handle." },
  { q: "The `else` clause of a `try` runs…", options: ["Only if no exception was raised in the try block", "Always, before finally", "Only if an exception was handled"], answer: 0,
    explain: "It keeps the success path out of the `try`, so an exception raised there is not accidentally caught by your own handler." },
  { q: "`raise NewError(...) from exc` differs from a plain raise by…", options: ["Preserving the original exception as `__cause__` in the traceback chain", "Suppressing the traceback", "Retrying the operation"], answer: 0,
    explain: "`from None` deliberately hides the chain, which is right when the original is noise." },
  { q: "A `return` inside `finally`…", options: ["Raises SyntaxError", "Swallows any in-flight exception and returns instead", "Is ignored"], answer: 1,
    explain: "It discards the propagating exception silently — one of the nastiest ways to lose an error." },
  { q: "`asyncio.TaskGroup` raises which type when a child task fails?", options: ["The child's exception directly", "asyncio.CancelledError", "An ExceptionGroup, even when only one task failed"], answer: 2,
    explain: "So `except ValueError:` never fires. You need `except*`, and that is the trap when porting from gather()." },
  { q: "With `except*`, when a group contains both a ValueError and a TimeoutError…", options: ["The group is discarded", "Only the first matching clause runs", "Every matching clause runs, each receiving its own sub-group"], answer: 2,
    explain: "Unlike ordinary except, they are not alternatives. Unmatched members are re-raised as a smaller group afterwards." },
  { q: "Generators pause at `yield` and…", options: ["Resume with all local state intact when next() is called again", "Copy their frame to the heap on every call", "Restart the function body from the top"], answer: 0,
    explain: "The frame is suspended, not discarded — which is what makes generators memory-cheap for large sequences." },
  { q: "`while ... else` is most useful for…", options: ["Retry loops where the else marks 'never succeeded'", "Loops over dictionaries", "Infinite loops"], answer: 0,
    explain: "Same semantics as `for ... else`: the else runs when the loop was not exited by `break`." },
  { q: "Recursion in CPython is limited because…", options: ["There is no tail-call optimisation, and a recursion limit guards the C stack", "The GIL forbids nested frames", "Recursion is disallowed beyond three levels"], answer: 0,
    explain: "Deep recursion raises RecursionError; iterative solutions or an explicit stack are the fix, not raising the limit." },
]},
{ title: "Quiz 3 · Data Structures",
  desc: "Complexity per operation, hashing, ordering and choosing by access pattern",
  questions: [
  { q: "`x in my_list` is O(n) while `x in my_set` is O(1) because…", options: ["A set hashes the value and looks in one bucket; a list scans element by element", "Sets are smaller", "Lists are unsorted"], answer: 0,
    explain: "This single swap is the most common real performance fix in Python code — a membership test inside a loop turns O(n²) into O(n)." },
  { q: "`list.insert(0, x)` is O(n) because…", options: ["It copies the whole list twice", "Every existing element must shift one position", "It rehashes the list"], answer: 1,
    explain: "`collections.deque` gives O(1) appends and pops at BOTH ends — the right structure for a queue." },
  { q: "Dicts preserve insertion order…", options: ["Only when keys are strings", "As a guaranteed language feature since 3.7", "By accident, and it must not be relied on"], answer: 1,
    explain: "It was a CPython implementation detail in 3.6 and became a language guarantee in 3.7." },
  { q: "An object can be a dict key only if it is…", options: ["Immutable", "A string or a number", "Hashable — and hash must stay consistent with equality"], answer: 2,
    explain: "Hashable is the real requirement. Most immutable built-ins are hashable, but a custom mutable class with __hash__ is legal and dangerous." },
  { q: "If you override `__eq__` without `__hash__`, the class becomes…", options: ["A syntax error", "Hashable by identity as before", "Unhashable — Python sets __hash__ to None"], answer: 2,
    explain: "Otherwise two equal objects could hash differently and break every dict and set invariant." },
  { q: "Mutating an object AFTER using it as a dict key…", options: ["Makes the entry effectively unreachable — it hashes to a different bucket", "Updates the key automatically", "Raises immediately"], answer: 0,
    explain: "The value is still in the dict, and lookups by an equal object fail. This is why keys should be immutable in practice." },
  { q: "`sorted()` differs from `list.sort()` in that…", options: ["sorted is unstable", "They are aliases", "sorted returns a new list and works on any iterable; sort mutates in place and returns None"], answer: 2,
    explain: "`x = my_list.sort()` binding None is a classic bug." },
  { q: "Python's sort is stable, meaning…", options: ["It never raises", "Equal elements keep their original relative order", "It always runs in O(n)"], answer: 1,
    explain: "Stability lets you sort by multiple keys in passes — sort by secondary key first, then primary." },
  { q: "`collections.defaultdict(list)` differs from a plain dict by…", options: ["Being ordered", "Creating the default value on a missing key lookup, then storing it", "Rejecting missing keys"], answer: 1,
    explain: "Note that merely READING a missing key inserts it — which surprises people iterating a defaultdict while checking membership." },
  { q: "`Counter(words).most_common(3)` returns…", options: ["The first three distinct words", "A sorted list of all counts", "The three most frequent items with their counts"], answer: 2,
    explain: "Counter is a dict subclass built for exactly this, and it beats a hand-rolled frequency loop for both speed and clarity." },
  { q: "A `set` cannot contain…", options: ["Strings", "Lists, because they are unhashable", "Tuples"], answer: 1,
    explain: "Use `frozenset` or a tuple when you need a hashable collection inside a set." },
  { q: "Slicing a list, `x[:]`, produces…", options: ["A deep copy", "A view onto the original", "A shallow copy"], answer: 2,
    explain: "The container is new; the elements are the same objects. Unlike NumPy, plain-Python slices are not views." },
  { q: "`dict.get(k)` versus `dict[k]` for a missing key:", options: ["get returns None (or a default); the subscript raises KeyError", "Both raise", "Both return None"], answer: 0,
    explain: "Choose deliberately: a KeyError is right when absence is a bug, and a default is right when it is expected." },
  { q: "Merging dicts with `a | b` (3.9+) resolves duplicate keys by…", options: ["Keeping the left value", "Raising on a conflict", "Taking the value from the right operand"], answer: 2,
    explain: "Same rule as `{**a, **b}` — later wins." },
  { q: "A tuple is preferable to a list when…", options: ["The collection is a fixed-size record whose shape is meaningful", "The data is numeric", "You need to append later"], answer: 0,
    explain: "Tuples signal 'this is one thing with parts'; lists signal 'a sequence of like items'. A NamedTuple or dataclass is better still once the parts have names." },
  { q: "`list.remove(x)` removes…", options: ["The first element equal to x, raising ValueError if none", "Every occurrence of x", "The element at index x"], answer: 0,
    explain: "`del lst[i]` and `lst.pop(i)` work by index; remove works by value." },
  { q: "Iterating a list while removing from it…", options: ["Skips elements, because the indices shift under the iterator", "Is safe and idiomatic", "Raises RuntimeError"], answer: 0,
    explain: "Build a new list with a comprehension instead. Mutating a DICT during iteration does raise RuntimeError." },
  { q: "`heapq` gives you…", options: ["O(log n) push and pop of the smallest item, on a plain list", "A sorted list at all times", "A hash-based priority queue"], answer: 0,
    explain: "The right structure for 'top k' and scheduling. It is a min-heap; negate the keys for a max-heap." },
  { q: "`bisect.insort` keeps a list sorted with…", options: ["O(1) insertion", "O(log n) search but O(n) insertion because of the shift", "O(n log n) per insert"], answer: 1,
    explain: "The search is cheap and the insert is not — for many insertions, a heap or a tree structure is a better fit." },
  { q: "Choosing a structure should start from…", options: ["Whichever is shortest to type", "The size of the data", "The access pattern — lookup by key, ordered scan, membership, or FIFO/LIFO"], answer: 2,
    explain: "Access pattern determines complexity; size only determines whether the complexity matters yet." },
]},
{ title: "Quiz 4 · Strings, Files & I/O",
  desc: "Unicode, the bytes boundary, formatting, pathlib and safe file writing",
  questions: [
  { q: "A Python `str` is a sequence of…", options: ["UTF-8 encoded characters", "Bytes", "Unicode code points"], answer: 2,
    explain: "Encoding happens at the boundary — `str.encode()` produces bytes; `bytes.decode()` produces str." },
  { q: "`open(path)` without an encoding argument uses…", options: ["The file's byte-order mark", "Always UTF-8", "The platform default (locale-dependent) unless encoding is specified"], answer: 2,
    explain: "This is why a file that reads fine on Linux raises UnicodeDecodeError on a Windows machine. Always pass `encoding=\"utf-8\"`." },
  { q: "UnicodeDecodeError means…", options: ["The bytes are not valid in the encoding you claimed", "The string contains emoji", "The file is too large"], answer: 0,
    explain: "It is a statement about a mismatch between the bytes and your assumption, not about the text being unusual." },
  { q: "`\"\".join(parts)` beats `s += part` in a loop because…", options: ["+= adds separators", "Strings are immutable, so += builds a new string each iteration — O(n²) overall", "join is implemented in C"], answer: 1,
    explain: "join allocates once, after computing the total length." },
  { q: "`f\"{value!r}\"` differs from `f\"{value}\"` by using…", options: ["repr() rather than str() — the debugging form", "Right alignment", "A raw string"], answer: 0,
    explain: "repr shows quotes and escapes, so `\"5\"` and `5` are distinguishable in a log line." },
  { q: "`f\"{x = }\"` produces…", options: ["A syntax error", "'x = 5' — the expression text and its value, for debugging", "The formatted value only"], answer: 1,
    explain: "Added in 3.8, and it removes most one-off print debugging boilerplate." },
  { q: "`str.strip(\"ab\")` removes…", options: ["Any leading and trailing characters that are 'a' or 'b'", "All a and b characters everywhere", "The literal substring \"ab\" from both ends"], answer: 0,
    explain: "It takes a SET of characters. `removeprefix`/`removesuffix` (3.9+) are what people usually meant." },
  { q: "Opening a file with `with open(...) as f:` guarantees…", options: ["The whole file is read into memory", "The file is closed even if the block raises", "The file is locked against other processes"], answer: 1,
    explain: "The context manager's __exit__ runs on the way out, exception or not." },
  { q: "Iterating a file object yields…", options: ["Lines, streamed one at a time without loading the whole file", "The entire contents as one string", "Bytes"], answer: 0,
    explain: "`for line in f:` is the memory-safe way to process a multi-gigabyte log." },
  { q: "`newline=\"\"` when writing CSV exists because…", options: ["It disables encoding", "The csv module writes its own line endings; without it you get a blank line between rows on Windows", "It makes the file smaller"], answer: 1,
    explain: "Text mode translates \\n on write, and csv has already emitted \\r\\n." },
  { q: "`pathlib.Path` is preferred over `os.path` string joining because…", options: ["It is faster", "Paths are objects with operators and methods, so separators and platform differences are handled", "os.path is deprecated"], answer: 1,
    explain: "`p / \"sub\" / \"file.txt\"` beats nested os.path.join calls, and `.read_text()` / `.write_text()` cover most file access." },
  { q: "To write a file safely so a crash cannot leave it half-written…", options: ["Flush after every line", "Open with mode 'w+'", "Write to a temp file in the same directory, then os.replace() it onto the target"], answer: 2,
    explain: "os.replace is atomic on the same filesystem, so readers see either the old file or the new one." },
  { q: "Reading a 5 GB file with `f.read()`…", options: ["Loads the entire content into memory", "Raises automatically above 2 GB", "Streams it lazily"], answer: 0,
    explain: "Iterate lines, or read fixed-size chunks with a walrus loop." },
  { q: "`bytes` and `str` concatenated together…", options: ["Raise TypeError — Python does not coerce between them", "Produce str", "Produce bytes"], answer: 0,
    explain: "Python 3's hard separation is exactly what made the 2-to-3 migration painful and encoding bugs rare afterwards." },
  { q: "Normalising user-entered Unicode before comparing matters because…", options: ["The same visible character can have multiple code-point sequences (NFC vs NFD)", "Strings are interned", "Comparison is case-sensitive"], answer: 0,
    explain: "`unicodedata.normalize(\"NFC\", s)` — otherwise a name typed on macOS may not equal the same name from a web form." },
  { q: "`len(\"héllo\")` counts…", options: ["Bytes in UTF-8", "Code points", "Grapheme clusters as a user perceives them"], answer: 1,
    explain: "None of the three always agree: an emoji with a skin-tone modifier is several code points and one perceived character." },
  { q: "`str.format` and f-strings differ mainly in that f-strings…", options: ["Are evaluated inline at runtime where they appear, and are faster", "Cannot use expressions", "Support fewer format specifiers"], answer: 0,
    explain: "The shared mini-language (`:>10`, `:.2f`, `:,`) is identical; f-strings just embed the expression." },
  { q: "Building SQL or shell commands with f-strings is dangerous because…", options: ["User input is interpolated verbatim — injection", "f-strings are slow", "They cannot contain quotes"], answer: 0,
    explain: "Parameterised queries and `subprocess` argument lists exist for this; string formatting is for display." },
  { q: "`print()` writes to…", options: ["stdout, with a flush on every call", "stdout, buffered — which is why output can appear out of order with stderr", "stderr"], answer: 1,
    explain: "`print(..., flush=True)`, or logging, when ordering across streams matters." },
  { q: "The `logging` module is preferred over `print` for applications because…", options: ["It is faster", "It carries levels, destinations, formatting and per-module control without editing call sites", "print is deprecated"], answer: 1,
    explain: "You can raise a single module to DEBUG in production without touching code." },
]},
{ title: "Quiz 5 · OOP & Dataclasses",
  desc: "Objects, MRO, dataclasses, properties, slots and when not to use a class",
  questions: [
  { q: "`self` is…", options: ["A reference to the class", "Just the conventional name for the first parameter — the instance", "A keyword the interpreter injects"], answer: 1,
    explain: "Nothing enforces the name; the binding is what matters, and `cls` is the same idea for classmethods." },
  { q: "`__init__` differs from `__new__` in that…", options: ["They are aliases", "__new__ creates the object; __init__ initialises the already-created instance", "__init__ runs first"], answer: 1,
    explain: "__new__ matters for immutable types and singletons; almost all ordinary classes only need __init__." },
  { q: "A class attribute assigned a mutable default is shared because…", options: ["Python copies it per instance", "It lives on the class, so every instance sees the same object", "It is thread-local"], answer: 1,
    explain: "The class-level version of the mutable-default bug; assign per-instance in __init__ instead." },
  { q: "`@dataclass` generates…", options: ["Database persistence methods", "__init__, __repr__ and __eq__ from the annotated fields", "Only a constructor"], answer: 1,
    explain: "`order=True` adds comparisons, and `frozen=True` makes instances immutable and hashable." },
  { q: "A mutable default in a dataclass field must use…", options: ["`= []` directly", "`field(default_factory=list)`", "`= None` always"], answer: 1,
    explain: "The dataclass machinery raises on a mutable default — one of the few places Python actively prevents the classic bug." },
  { q: "`frozen=True` on a dataclass gives you…", options: ["Immutability and a generated __hash__, so instances can be dict keys", "Thread safety for its contents", "Faster attribute access"], answer: 0,
    explain: "Note it is shallow: a frozen dataclass holding a list still has a mutable interior." },
  { q: "`__slots__` improves memory by…", options: ["Sharing attributes between instances", "Removing the per-instance __dict__ and using fixed descriptors", "Compressing attribute values"], answer: 1,
    explain: "Real savings at millions of instances; the cost is no dynamic attributes and complications with multiple inheritance." },
  { q: "`@property` lets you…", options: ["Cache a value automatically", "Expose a computed value with attribute syntax, so a plain attribute can gain logic later without changing callers", "Make an attribute private"], answer: 1,
    explain: "It is why Python has no culture of writing getters up front — you add them only when needed, without breaking the API." },
  { q: "`@staticmethod` versus `@classmethod`:", options: ["They are identical", "staticmethod receives the instance", "classmethod receives the class as its first argument; staticmethod receives nothing special"], answer: 2,
    explain: "classmethod is how alternative constructors are written: `Date.from_iso(...)` returning `cls(...)` respects subclasses." },
  { q: "Python's MRO for multiple inheritance is computed by…", options: ["C3 linearisation, which guarantees a consistent order", "The order methods were defined", "Left-to-right depth-first"], answer: 0,
    explain: "`Class.__mro__` shows it. C3 rejects hierarchies it cannot linearise, at class-creation time." },
  { q: "`super().__init__()` in a multiple-inheritance hierarchy calls…", options: ["All parents at once", "The next class in the MRO, which may not be the direct parent", "The direct parent only"], answer: 1,
    explain: "That is what makes cooperative multiple inheritance work — and why every class in the chain must call super()." },
  { q: "A leading underscore, `_value`, means…", options: ["A convention signalling internal use; nothing prevents access", "Enforced private access", "The attribute is read-only"], answer: 0,
    explain: "Double underscore triggers name mangling to `_Class__value`, which is for avoiding subclass collisions, not security." },
  { q: "Composition is usually preferred over inheritance because…", options: ["Python does not support inheritance well", "It is faster", "Inheritance couples you to the parent's implementation and is hard to change later"], answer: 2,
    explain: "Inherit for genuine 'is-a' substitutability; compose for 'has-a' or 'uses-a'." },
  { q: "Duck typing means…", options: ["Compatibility is decided by the methods an object actually has, not its declared type", "Only built-in types can be used polymorphically", "Explicit interface declarations are required"], answer: 0,
    explain: "`typing.Protocol` gives static checking for exactly this pattern without forcing inheritance." },
  { q: "`__repr__` should ideally…", options: ["Return None", "Be identical to __str__", "Return an unambiguous string, ideally one that could recreate the object"], answer: 2,
    explain: "It is what you see in a debugger, a list and a traceback — a default `<object at 0x7f…>` wastes a debugging session." },
  { q: "Defining `__eq__` makes instances comparable, and to keep them usable in sets you must also…", options: ["Nothing else", "Define __hash__ (or use a frozen dataclass)", "Define __len__"], answer: 1,
    explain: "Python sets __hash__ to None when you define __eq__, making instances unhashable by default." },
  { q: "A context manager class requires…", options: ["__enter__ and __exit__", "__init__ and __del__", "__iter__ and __next__"], answer: 0,
    explain: "Or use `@contextlib.contextmanager` over a generator, which is shorter for the common case." },
  { q: "`__del__` is a poor place for cleanup because…", options: ["Its timing is not guaranteed and exceptions in it are ignored", "It never runs", "It requires inheritance"], answer: 0,
    explain: "Deterministic cleanup belongs in a context manager; __del__ is a last-resort safety net at best." },
  { q: "A class whose only content is a method taking all its data as arguments is…", options: ["A sign the class is unnecessary — a plain function would do", "Good encapsulation", "Required for testability"], answer: 0,
    explain: "Modules are Python's namespace. A stateless class is a function with extra ceremony." },
  { q: "`NamedTuple` versus `@dataclass`:", options: ["NamedTuple is immutable, iterable and tuple-compatible; dataclass is more flexible and mutable by default", "They are equivalent", "NamedTuple supports methods, dataclass does not"], answer: 0,
    explain: "Choose NamedTuple when tuple-ness is genuinely wanted (unpacking, indexing); a frozen dataclass when it is not." },
]},
);
