// python quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Comprehensions, Iterators & Generators",
  desc: "Comprehensions, lazy generators, itertools, the iterator protocol",
  questions: [
  { q: "[x*x for x in nums if x>0] is a…", options: ["Loop", "List comprehension (transform + filter)", "Generator"], answer: 1,
    explain: "Faster than an append-loop; {} and {k:v} give set/dict comps." },
  { q: "sum(x*x for x in range(1_000_000)) uses…", options: ["A tuple", "A million-item list", "A lazy generator expression — O(1) memory"], answer: 2,
    explain: "Parentheses (not brackets) = lazy, streamed one item at a time." },
  { q: "yield makes a function…", options: ["Async", "A generator (lazy, resumable, stateful)", "Return early"], answer: 1,
    explain: "Calling it runs no body; each next() resumes after the last yield." },
  { q: "Reading a 10GB file with a generator gives…", options: ["Constant memory (one line at a time)", "OOM", "Faster CPU"], answer: 0,
    explain: "yield line inside `with open` streams it." },
  { q: "An infinite generator (while True: yield) is safe because…", options: ["It caches", "Laziness — take only what you consume (islice)", "It's not"], answer: 1,
    explain: "Values compute on demand; islice(gen, 10) takes 10." },
  { q: "A generator, once exhausted…", options: ["Is empty on the next iteration (one-shot)", "Errors", "Restarts"], answer: 0,
    explain: "Recreate it or use a list if you need multiple passes." },
  { q: "itertools.groupby requires…", options: ["A dict", "Pre-sorting by the key (it groups CONSECUTIVE keys)", "Nothing"], answer: 1,
    explain: "It's a single lazy pass; unsorted → fragmented groups." },
  { q: "list comp vs generator: use a generator when…", options: ["You need len()", "You need indexing", "Data is large/streamed and consumed once"], answer: 2,
    explain: "Lists for random access/len/multiple passes; generators for memory." },
  { q: "len(a_generator) …", options: ["Returns count", "Raises TypeError (generators aren't sized)", "Returns 0"], answer: 1,
    explain: "Materialize with list() if you truly need length." },
  { q: "A for-loop internally calls…", options: ["map()", "iter() then next() until StopIteration", "range()"], answer: 1,
    explain: "The iterator protocol underlies comprehensions, unpacking, *args." },
  { q: "itertools.chain(a, b) does…", options: ["Lazily concatenates iterables", "Zips", "Sorts"], answer: 0,
    explain: "Flatten without building an intermediate list." },
  { q: "A nested comprehension you have to squint at should be…", options: ["Kept", "Nested deeper", "Rewritten as a loop for readability"], answer: 2,
    explain: "Comprehensions are for clarity; complex logic → explicit loop." },
  { q: "yield from another_gen…", options: ["Is invalid", "Delegates: yields all values from another iterable", "Returns it"], answer: 1,
    explain: "Generator composition (like JS yield*)." },
  { q: "{u.id: u for u in users} is a…", options: ["Dict comprehension (build a lookup index)", "List", "Set"], answer: 0,
    explain: "keyBy in one expression." },
  { q: "accumulate([1,2,3,4]) yields…", options: ["[1,2,3,4]", "[10]", "Running totals 1,3,6,10"], answer: 2,
    explain: "itertools for prefix sums lazily." },
  { q: "Generator memory advantage matters most for…", options: ["Large/infinite/streamed data consumed once", "Small lists", "Sorting"], answer: 0,
    explain: "O(1) vs O(n) — the whole point." },
  { q: "combinations(items, 2) / product(a, b) replace…", options: ["Manual nested loops for combinatorics", "Nothing", "sorting"], answer: 0,
    explain: "Lazy, readable combinatorial iteration." },
  { q: "A generator's state between yields is…", options: ["Preserved (locals survive) — a resumable frame", "Global", "Lost"], answer: 0,
    explain: "Fibonacci keeps a, b across yields." },
  { q: "next(gen, default) …", options: ["Returns default instead of raising StopIteration when exhausted", "Errors at end", "Restarts"], answer: 0,
    explain: "Safe single-step consumption." },
  { q: "Comprehensions vs map/filter in Python:", options: ["Identical always", "Comprehensions are usually more readable and idiomatic", "map wins"], answer: 1,
    explain: "Prefer comprehensions; map/filter still fine with existing functions." },
]},
{ title: "Quiz 7 · Decorators, Context Managers & Typing",
  desc: "Decorators, wraps, lru_cache, with, type hints, Protocol",
  questions: [
  { q: "A decorator is…", options: ["A function taking a function and returning a replacement", "A class", "A loop"], answer: 0,
    explain: "@deco is sugar for fn = deco(fn)." },
  { q: "Custom decorators must use…", options: ["Nothing", "@functools.wraps (preserve __name__/__doc__) + forward *args/**kwargs", "global"], answer: 1,
    explain: "Skipping wraps breaks introspection/logging." },
  { q: "A decorator that takes arguments needs…", options: ["A class only", "One function", "THREE nested functions (factory → decorator → wrapper)"], answer: 2,
    explain: "@retry(3) = retry(3)(fn)." },
  { q: "@lru_cache memoizes…", options: ["Pure functions of HASHABLE args (bound size to avoid leaks)", "Any function", "I/O calls"], answer: 0,
    explain: "Wrong for impure/mutating-arg functions; @cache is unbounded." },
  { q: "A context manager guarantees…", options: ["Speed", "Teardown (__exit__) even on exception", "Nothing"], answer: 1,
    explain: "Files close, locks release, transactions roll back." },
  { q: "@contextmanager turns a generator into…", options: ["A context manager (before yield = setup, after = teardown)", "A decorator", "A loop"], answer: 0,
    explain: "try/yield/finally around one yield." },
  { q: "__exit__ returning True…", options: ["Does nothing", "Re-raises", "SUPPRESSES the exception (usually you want False)"], answer: 2,
    explain: "Return False/None to let exceptions propagate." },
  { q: "Python type hints at runtime are…", options: ["Enforced", "Erased/ignored — a checker (mypy/pyright) validates them", "Compiled"], answer: 1,
    explain: "def f(x:int) doesn't reject f('s'); validate external data separately." },
  { q: "list[str], dict[str,int] (3.9+) replace…", options: ["typing.List/Dict — builtin generics", "Nothing", "Any"], answer: 0,
    explain: "Modern hint syntax; X | None for optionals (3.10+)." },
  { q: "unknown external data should be validated with…", options: ["Pydantic (runtime validation) — hints don't run", "Type hints", "Any"], answer: 0,
    explain: "Same boundary rule as TS/zod; Pydantic ≈ zod." },
  { q: "A Protocol types…", options: ["Inheritance", "Nothing", "Structural/duck typing (anything with the right methods)"], answer: 2,
    explain: "Static face of composition; no explicit 'implements'." },
  { q: "Overusing Any…", options: ["Helps", "Is required", "Disables checking (contagious) — 'mypy passes but catches nothing'"], answer: 2,
    explain: "Prefer precise types / unknown-then-narrow; ban Any in lint." },
  { q: "Hints without a checker in CI…", options: ["Are enforced", "Are fine", "Drift and lie over time — run mypy/pyright as a gate"], answer: 2,
    explain: "The value is the checker + boundary validation." },
  { q: "Literal[\"asc\",\"desc\"] gives…", options: ["Any string", "A typo-proof set of exact allowed values", "A number"], answer: 1,
    explain: "The Python equivalent of a string-literal union." },
  { q: "@property + a setter…", options: ["Exposes controlled read/write as attribute access", "Is impossible", "Is static"], answer: 0,
    explain: "@x.setter guards writes; getter computes reads." },
  { q: "cast() to silence mypy…", options: ["Validates", "Lies to the checker — narrow properly instead; use only when you truly know more", "Is safe"], answer: 1,
    explain: "Like TS `as` — a smell that needs justification." },
  { q: "with open(...) as f is preferred because…", options: ["Shorter", "Faster read", "Deterministic close on success OR exception"], answer: 2,
    explain: "The context-manager guarantee." },
  { q: "TypeVar T enables…", options: ["Constants", "Async", "Generics: def first(xs: list[T]) -> T | None"], answer: 2,
    explain: "Preserves the relationship between input and output types." },
  { q: "Flask @app.route and pytest @fixture are…", options: ["Ordinary decorators you consume", "Classes", "Special syntax"], answer: 0,
    explain: "Same mechanism you can write yourself." },
  { q: "mypy --strict is comparable to…", options: ["Nothing", "A formatter", "TypeScript strict mode — catches the most (esp. Optional handling)"], answer: 2,
    explain: "Turn it on for new code; ratchet legacy." },
]},
{ title: "Quiz 8 · Concurrency: GIL, Threads, Async",
  desc: "The GIL, threads vs processes vs asyncio, thread safety",
  questions: [
  { q: "The GIL means…", options: ["Threads are fast", "Only one thread runs Python bytecode at a time (no CPU parallelism for pure Python)", "Python has no threads"], answer: 1,
    explain: "Released during I/O and in C extensions, so threads overlap I/O." },
  { q: "For CPU-bound parallelism, use…", options: ["Multiple PROCESSES (ProcessPoolExecutor) — own GIL/core each", "Threads", "asyncio"], answer: 0,
    explain: "Threads give no speedup for pure-Python CPU work." },
  { q: "For many concurrent I/O tasks (APIs/DB), the cheapest tool is…", options: ["Processes", "Threads only", "asyncio (one thread, thousands of awaits)"], answer: 2,
    explain: "No GIL fight when everything is waiting." },
  { q: "For blocking (non-async) I/O libraries, use…", options: ["asyncio directly", "ThreadPoolExecutor (GIL released during I/O)", "Processes"], answer: 1,
    explain: "Threads overlap the waits even with the GIL." },
  { q: "A blocking call inside asyncio…", options: ["Freezes the ENTIRE event loop", "Is fine", "Runs in parallel"], answer: 0,
    explain: "Use async libs or asyncio.to_thread/run_in_executor." },
  { q: "'threading didn't speed up my number crunching' — cause?", options: ["Slow disk", "The GIL — use multiprocessing for CPU-bound work", "Bad code"], answer: 1,
    explain: "The canonical GIL surprise." },
  { q: "counter += 1 across threads without a lock…", options: ["Is fine", "Can lose updates (read-modify-write race) despite the GIL", "Is atomic"], answer: 1,
    explain: "The GIL prevents corruption, not logical races — use a Lock." },
  { q: "asyncio.gather(*coros) does…", options: ["Runs coroutines concurrently and collects results", "Blocks", "Runs sequentially"], answer: 0,
    explain: "Like Promise.all — parallel I/O on one loop." },
  { q: "Processes cost more than threads because…", options: ["Separate memory + pickling args/results across the boundary", "The GIL", "They're slower always"], answer: 0,
    explain: "Worth it only when compute dwarfs the overhead." },
  { q: "'coroutine was never awaited' means…", options: ["Syntax error", "It ran", "You called an async fn without awaiting it"], answer: 2,
    explain: "await coroutines; asyncio.run at the top level." },
  { q: "The GIL is released…", options: ["Always", "During I/O waits and inside many C extensions (numpy)", "Never"], answer: 1,
    explain: "Why threads help I/O-bound but not CPU-bound work." },
  { q: "async/await in Python is…", options: ["Multiprocessing", "Cooperative concurrency on one event loop (like JS)", "Multithreading"], answer: 1,
    explain: "Same don't-block-the-loop rule as Node." },
  { q: "asyncio.to_thread(fn) is for…", options: ["Running a BLOCKING call off the loop without freezing it", "Nothing", "CPU work"], answer: 0,
    explain: "Offload blocking I/O; process pool for CPU." },
  { q: "3.13's free-threaded build…", options: ["Is an experimental no-GIL option — know it exists; default reality still has the GIL", "Removes asyncio", "Is standard"], answer: 0,
    explain: "The GIL mental model remains the default." },
  { q: "Prefer over shared mutable state…", options: ["Globals", "More locks", "Message passing (queue.Queue) — fewer races"], answer: 2,
    explain: "Same philosophy as the JS workers lesson." },
  { q: "For 1000 concurrent HTTP calls, choose…", options: ["asyncio with an async HTTP client", "1000 threads", "1000 processes"], answer: 0,
    explain: "Cheapest concurrency for I/O-bound fan-out." },
  { q: "For resizing 10k images, choose…", options: ["ProcessPoolExecutor (CPU-bound, needs cores)", "Threads", "asyncio"], answer: 0,
    explain: "True parallelism past the GIL." },
  { q: "A legacy blocking DB driver in a threadpool works because…", options: ["Magic", "The GIL releases during the driver's I/O, so threads overlap waits", "It's async"], answer: 1,
    explain: "Match tool to workload AND library nature." },
  { q: "multiprocessing shares data via…", options: ["Pickling / shared memory (separate address spaces)", "Threads", "Direct references"], answer: 0,
    explain: "No shared heap; pass data across the boundary." },
  { q: "The one rule organizing Python concurrency:", options: ["I/O-bound → threads/async; CPU-bound → processes (because of the GIL)", "Use more cores", "Always use asyncio"], answer: 0,
    explain: "Every choice derives from it." },
]},
{ title: "Quiz 9 · Testing, Packaging & FastAPI",
  desc: "pytest, fixtures, venv/lockfiles, FastAPI, Pydantic, DI",
  questions: [
  { q: "pytest assertions use…", options: ["assertEqual", "plain assert (with rich failure introspection)", "expect()"], answer: 1,
    explain: "pytest.raises for exceptions; -k / ::name to select." },
  { q: "@pytest.mark.parametrize gives…", options: ["Fixtures", "Table-driven tests (one test, many cases)", "Mocks"], answer: 1,
    explain: "Cover edge branches without copy-paste." },
  { q: "A fixture with yield…", options: ["Mocks", "Loops", "Provides setup before + teardown after (runs even on failure)"], answer: 2,
    explain: "conftest.py shares them; scopes function→session." },
  { q: "The #1 mocking bug is patching…", options: ["Nothing", "Too much", "Where the function is DEFINED instead of where it's USED"], answer: 2,
    explain: "patch the module that imported it." },
  { q: "Mock in tests should target…", options: ["Your own logic", "The DB always", "External EDGES (email/HTTP/clock) — not your code"], answer: 2,
    explain: "Real test DB for integration; mocking your logic tests the mock." },
  { q: "A virtual environment…", options: ["Speeds Python", "Is optional in prod", "Isolates per-project Python + packages (avoids global conflicts)"], answer: 2,
    explain: "The #1 'works on my machine' fix." },
  { q: "The lockfile (uv.lock/poetry.lock)…", options: ["Pins the exact transitive tree — commit it; CI installs from it", "Is generated at runtime", "Is optional"], answer: 0,
    explain: "Reproducibility, like npm's package-lock." },
  { q: "if __name__ == '__main__':…", options: ["Never runs", "Runs only on direct execution, not import", "Always runs"], answer: 1,
    explain: "Guards entry points so imports don't trigger side effects." },
  { q: "FastAPI derives validation/docs from…", options: ["A config file", "Comments", "Type hints + Pydantic models"], answer: 2,
    explain: "One source: typed models → 422 validation, serialization, /docs." },
  { q: "response_model in FastAPI…", options: ["Speeds responses", "Adds auth", "Shapes/validates output and prevents leaking internal fields"], answer: 2,
    explain: "Never return the raw DB model (leaks passwords etc.)." },
  { q: "Bad request body in FastAPI returns…", options: ["200", "422 automatically (Pydantic validation)", "500"], answer: 1,
    explain: "Validation at the boundary, for free from the model." },
  { q: "Depends() provides…", options: ["Threads", "Logging only", "Dependency injection (DB/auth/pagination) — overridable in tests"], answer: 2,
    explain: "app.dependency_overrides swaps real deps for fakes." },
  { q: "A blocking call in an async FastAPI endpoint…", options: ["Speeds up", "Is fine", "Stalls the loop — use async drivers or a sync def (threadpool)"], answer: 2,
    explain: "Same don't-block-the-loop rule." },
  { q: "Coverage 100%…", options: ["Proves quality", "Is required", "Measures lines run, not correctness — cover meaningful branches"], answer: 2,
    explain: "A gap-finder, not a target." },
  { q: "A transaction-rollback db fixture gives…", options: ["Fast, isolated integration tests (pristine state per test)", "Slow tests", "Mocked data"], answer: 0,
    explain: "Same pattern as the Node testing lesson." },
  { q: "pip install -e . does…", options: ["Nothing", "Editable install so imports resolve during development", "Uploads to PyPI"], answer: 1,
    explain: "src-layout + editable install is the shippable structure." },
  { q: "pydantic-settings loads config from…", options: ["Code", "The DB", "Environment variables (never hardcode secrets)"], answer: 2,
    explain: "12-factor config; secrets from env/secret manager." },
  { q: "Serving FastAPI in production uses…", options: ["uvicorn/gunicorn workers = cores, behind a reverse proxy", "One uvicorn worker", "The dev server"], answer: 0,
    explain: "Process-per-core for throughput (Node scaling parallel)." },
  { q: "Testing a FastAPI app uses…", options: ["Real network", "httpx AsyncClient + dependency_overrides against a test DB", "Selenium"], answer: 1,
    explain: "Integration through the real stack with fakes for edges." },
  { q: "authz enforced only in the UI is…", options: ["Fine", "A vuln (BOLA) — the API must enforce ownership/permissions", "Faster"], answer: 1,
    explain: "Never trust the client; server is the boundary." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "def f(x, items=[]) accumulates across calls. Root cause?", options: ["A bug in Python", "Default args evaluated once — the list is shared. Fix: None sentinel", "Scope"], answer: 1,
    explain: "The signature-default gotcha (#1 function question)." },
  { q: "b = a.copy() on nested data; b[0].append(x) changes a[0]. Why?", options: ["Deep copy failed", "Shallow copy shares inner objects — use copy.deepcopy", "a is b"], answer: 1,
    explain: "Same shallow/deep story as JS spread vs structuredClone." },
  { q: "A membership check in a loop over a 100k list is slow. Fix?", options: ["Build a set once — O(n) instead of O(n²)", "Sort it", "Faster CPU"], answer: 0,
    explain: "in on list is O(n); on set is O(1)." },
  { q: "threading didn't speed up CPU-heavy work. Why and fix?", options: ["Bad threads", "The GIL — use multiprocessing (ProcessPoolExecutor)", "Add threads"], answer: 1,
    explain: "Threads only help I/O-bound work." },
  { q: "One time.sleep froze your whole asyncio server. Cause?", options: ["A blocking call on the single event loop — use asyncio.sleep / to_thread", "Slow disk", "Too few workers"], answer: 0,
    explain: "Never block the loop (concurrency + fastapi lessons)." },
  { q: "Your mock of send_email didn't apply. Cause?", options: ["Wrong email", "Bad fixture", "Patched where DEFINED, not where the code LOOKS IT UP"], answer: 2,
    explain: "patch the importing module's namespace." },
  { q: "'café' from a file reads as 'cafÃ©' on Windows. Cause?", options: ["Bad font", "Corrupt file", "Missing encoding='utf-8' → platform default used"], answer: 2,
    explain: "Always specify the encoding." },
  { q: "type hint says int but a str got through and crashed later. Why?", options: ["Python is weak", "mypy bug", "Hints are erased at runtime — validate external data (Pydantic) + run mypy"], answer: 2,
    explain: "The boundary-validation rule." },
  { q: "Building a big string with += is slow. Fix?", options: ["Faster CPU", "\"\".join(pieces) — strings are immutable (+=  is O(n²))", "Use bytes"], answer: 1,
    explain: "Single allocation via join." },
  { q: "super() called the wrong class in multiple inheritance. Cause?", options: ["Missing self", "super() follows the MRO, not 'the parent' — check __mro__", "A bug"], answer: 1,
    explain: "C3 linearization drives cooperative inheritance." },
  { q: "Your custom decorator broke logging (wrong function name). Cause?", options: ["No return", "Slow", "Missing @functools.wraps on the wrapper"], answer: 2,
    explain: "wraps preserves __name__/__doc__." },
  { q: "@lru_cache caused a memory leak. Cause?", options: ["Threads", "A bug", "Unbounded cache (@cache) — use lru_cache(maxsize=N)"], answer: 2,
    explain: "Bound hot caches; cache only pure hashable-arg functions." },
  { q: "A 10GB file crashed with OOM on f.read(). Fix?", options: ["Iterate line-by-line (or a generator) — constant memory", "More RAM", "readlines"], answer: 0,
    explain: "Streaming beats loading (streams parallel)." },
  { q: "Money math shows 0.30000000000000004. Fix?", options: ["decimal.Decimal or integer cents — floats are inexact", "Use str", "Round always"], answer: 0,
    explain: "IEEE-754 (types lesson)." },
  { q: "Returning the DB model from FastAPI leaked a password field. Fix?", options: ["response_model=PublicUser to shape output", "Hide in UI", "Encrypt it"], answer: 0,
    explain: "Control exposure at the serialization boundary." },
  { q: "'works on my machine' — different deps in prod. Cause?", options: ["No committed lockfile / no venv — pin and sync from the lock", "Slow network", "Bad code"], answer: 0,
    explain: "venv + lockfile + CI sync (packaging lesson)." },
  { q: "for i in range(len(x)) then x[i] is…", options: ["Required", "Optimal", "Unpythonic/error-prone — use enumerate or iterate directly"], answer: 2,
    explain: "enumerate/zip are the idioms." },
  { q: "GET /users/5 returns another user's data. Vulnerability?", options: ["BOLA/IDOR — missing ownership check on the server", "CSRF", "XSS"], answer: 0,
    explain: "Enforce authz in the API, not the UI." },
  { q: "Tests pass alone but fail together. Likely cause?", options: ["Slow DB", "Flaky pytest", "Shared mutable state / order dependence — isolate via fixtures"], answer: 2,
    explain: "The mutation trap in test suites." },
  { q: "The single most important Python mental model is…", options: ["Use type hints", "Names bound to objects + the GIL (I/O vs CPU tool choice)", "Memorize stdlib"], answer: 1,
    explain: "Mutation/copy/argument behavior AND concurrency choices both derive from these. 🏆" },
]},
);
