// Python quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Syntax, Types & Variables",
  desc: "Name/object model, is vs ==, strong+dynamic typing, mutability",
  questions: [
  { q: "In Python, a variable is…", options: ["A box holding a value", "A NAME bound to an object (assignment binds, doesn't copy)", "A typed slot"], answer: 1,
    explain: "y = x makes y another name for the SAME object — the root of aliasing/mutation behavior." },
  { q: "a is b vs a == b:", options: ["Identical", "is = same object (identity); == = same value", "is is faster =="], answer: 1,
    explain: "Use is only for singletons (None/True/False); == compares value via __eq__." },
  { q: "\"5\" + 3 in Python…", options: ["\"53\"", "Raises TypeError — Python is strongly typed (no implicit coercion)", "8"], answer: 1,
    explain: "Convert explicitly: int(\"5\")+3. Strong typing = errors instead of silent coercion." },
  { q: "Which are IMMUTABLE?", options: ["list, dict, set", "int, str, tuple, frozenset", "everything"], answer: 1,
    explain: "Immutable+hashable types can be dict keys / set members." },
  { q: "Check for null with…", options: ["== None", "is None (identity for the singleton)", "== null"], answer: 1,
    explain: "None is a singleton; is None is unambiguous and immune to custom __eq__." },
  { q: "The falsy values include…", options: ["Only False and None", "False, None, 0, 0.0, \"\", [], {}, set()", "Any empty object"], answer: 1,
    explain: "Everything else is truthy; use `if x:` not `if x == True`." },
  { q: "Python integers…", options: ["Overflow at 2^63", "Have arbitrary precision (2**1000 works)", "Are 32-bit"], answer: 1,
    explain: "No int overflow; floats are IEEE-754 (0.1+0.2 != 0.3) — use decimal for money." },
  { q: "type() vs isinstance():", options: ["Same", "isinstance respects subclasses (the right type check)", "type is safer"], answer: 1,
    explain: "isinstance(x,(int,float)) handles inheritance; type(x)==int doesn't." },
  { q: "n = 5; n = \"hi\" is allowed because Python is…", options: ["Weakly typed", "Dynamically typed (names aren't typed; can rebind to any type)", "Untyped"], answer: 1,
    explain: "Dynamic: a name can point to any type. Strong: no implicit cross-type coercion." },
  { q: "f-strings are…", options: ["Old syntax", "The modern formatting: f\"{name}: {x:.2f}\"", "Slower than +"], answer: 1,
    explain: "Support expressions, formatting mini-language, and f\"{x=}\" debug form." },
  { q: "a, b = b, a does…", options: ["Nothing", "Swaps via tuple packing/unpacking, no temp", "Errors"], answer: 1,
    explain: "The right side builds a tuple, then unpacks it." },
  { q: "Small ints and short strings sometimes have a is b == True because…", options: ["A bug", "They're cached/interned — never rely on identity for values", "They're always the same"], answer: 1,
    explain: "Use == for value equality; is only for None/True/False." },
  { q: "PEP 8 dictates…", options: ["Nothing enforced", "snake_case, 4-space indent, UPPER_CASE constants — enforced by ruff/black", "camelCase"], answer: 1,
    explain: "Cultural standard; formatters/linters automate it (like Prettier/ESLint)." },
  { q: "Storing money as float is…", options: ["Fine", "A bug — use decimal.Decimal or integer cents", "Faster"], answer: 1,
    explain: "IEEE floats can't represent 0.10 exactly." },
  { q: "id(x) returns…", options: ["The value", "The object's identity (what `is` compares)", "The type"], answer: 1,
    explain: "Two names to one object share an id." },
  { q: "Passing a list to a function and appending inside…", options: ["Doesn't affect the caller", "Mutates the caller's list (same object)", "Copies it"], answer: 1,
    explain: "Pass-by-object-reference: mutation is visible; rebinding the param is not." },
  { q: "bool is…", options: ["Separate from int", "A subclass of int (True == 1, False == 0)", "A string"], answer: 1,
    explain: "So True + True == 2; a common trivia point." },
  { q: "a = [1]; b = a; b = [9] — what is a?", options: ["[9]", "[1] — b was REBOUND, not mutated", "error"], answer: 1,
    explain: "Rebinding b doesn't affect a; only mutation through a shared reference would." },
  { q: "Digit separators like 1_000_000…", options: ["Are invalid", "Are legal and improve readability", "Change the value"], answer: 1,
    explain: "Underscores in numeric literals are ignored by the parser." },
  { q: "Explicit conversion int(\"12px\")…", options: ["Returns 12", "Raises ValueError (whole string must be numeric)", "Returns 0"], answer: 1,
    explain: "Validate/try around conversions of untrusted input." }
]},

{ title: "Quiz 2 · Control Flow & Functions",
  desc: "Loops, mutable defaults, LEGB, arguments, match",
  questions: [
  { q: "def f(x, cart=[]): cart.append(x) — calling twice gives cart…", options: ["Fresh each time", "The SAME list across calls (mutable default evaluated once)", "Error"], answer: 1,
    explain: "The #1 Python gotcha. Fix: default None, create inside." },
  { q: "The fix for a mutable default is…", options: ["Use a tuple", "default=None; if x is None: x = []", "Global"], answer: 1,
    explain: "The sentinel pattern gives a fresh object per call." },
  { q: "Iterate with index the Pythonic way:", options: ["for i in range(len(x))", "for i, v in enumerate(x)", "while loop"], answer: 1,
    explain: "enumerate(x, start=1) gives index+value cleanly." },
  { q: "Iterate two lists in parallel:", options: ["Nested loops", "for a, b in zip(list1, list2)", "Index math"], answer: 1,
    explain: "zip pairs them; stops at the shortest." },
  { q: "LEGB is…", options: ["A library", "Name resolution: Local → Enclosing → Global → Built-in", "A loop"], answer: 1,
    explain: "Reading walks outward; writing an outer name needs global/nonlocal." },
  { q: "Assigning to a name inside a function makes it…", options: ["Global", "Local for the WHOLE function (UnboundLocalError if read before assign)", "Enclosing"], answer: 1,
    explain: "Use nonlocal (enclosing) or global (module) to rebind outer names." },
  { q: "for...else: the else runs when…", options: ["The loop is empty", "The loop finished WITHOUT break", "Always"], answer: 1,
    explain: "Handy for search loops: else = 'not found'." },
  { q: "def f(a, /, b, *, c): the / and * mean…", options: ["Division", "a is positional-only; c is keyword-only", "Defaults"], answer: 1,
    explain: "API-design tools controlling call style." },
  { q: "*args and **kwargs capture…", options: ["Nothing", "Extra positional args (tuple) and keyword args (dict)", "Types"], answer: 1,
    explain: "Forward them for signature-agnostic wrappers (decorators lesson)." },
  { q: "match/case is…", options: ["Just a switch", "Structural pattern matching (destructures, guards, wildcards)", "Regex"], answer: 1,
    explain: "case [x, *rest], case {\"k\": v}, case _ — more than a switch." },
  { q: "Returning multiple values returns…", options: ["A list", "A tuple (unpack: a, b = f())", "Nothing"], answer: 1,
    explain: "return a, b packs a tuple; the caller unpacks it." },
  { q: "The conditional expression (ternary) is…", options: ["cond ? a : b", "a if cond else b", "if cond a else b"], answer: 1,
    explain: "Python's inline conditional." },
  { q: "Default arguments are evaluated…", options: ["Per call", "ONCE, when the def executes", "Never"], answer: 1,
    explain: "Why mutable defaults are shared across calls." },
  { q: "A closure that modifies an enclosing variable needs…", options: ["global", "nonlocal", "nothing"], answer: 1,
    explain: "nonlocal rebinds the enclosing function's name; global rebinds module-level." },
  { q: "Bare `except:` is bad because…", options: ["It's slow", "It catches KeyboardInterrupt/SystemExit too", "It's invalid"], answer: 1,
    explain: "Use except Exception: or specific types." },
  { q: "range(2, 10, 2) yields…", options: ["2..10 all", "2, 4, 6, 8 (start, stop-exclusive, step)", "2, 10"], answer: 1,
    explain: "stop is exclusive; range is lazy." },
  { q: "continue vs break:", options: ["Same", "continue skips to the next iteration; break exits the loop", "Both exit"], answer: 1,
    explain: "continue → next item; break → leave (and skip for-else)." },
  { q: "Prefer returning values over global because…", options: ["It's shorter", "Explicit data flow, testability, no hidden state", "Globals don't work"], answer: 1,
    explain: "Same purity argument as the JS functions lesson." },
  { q: "lambda is…", options: ["A statement", "A small anonymous function expression (lambda x: x*2)", "A loop"], answer: 1,
    explain: "Use for tiny key= functions; named def for anything non-trivial." },
  { q: "A function with no return statement returns…", options: ["0", "None", "empty"], answer: 1,
    explain: "Implicit None; don't rely on it for meaningful values." }
]},

{ title: "Quiz 3 · Data Structures",
  desc: "list/dict/set/tuple, Big-O, copies, collections",
  questions: [
  { q: "`x in a_list` is…", options: ["O(1)", "O(n) — a linear scan", "O(log n)"], answer: 1,
    explain: "Use a set/dict for O(1) membership; list-scan in a loop is accidental O(n²)." },
  { q: "`x in a_set` / dict key lookup is…", options: ["O(n)", "O(1) average (hash table)", "O(log n)"], answer: 1,
    explain: "Hashing → one bucket check; requires hashable (immutable) keys." },
  { q: "d[\"missing\"] vs d.get(\"missing\"):", options: ["Same", "[] raises KeyError; get returns None/default", "Both raise"], answer: 1,
    explain: "d.get(k, default) or defaultdict avoid KeyError crashes." },
  { q: "a.copy() on a nested list is…", options: ["A deep copy", "SHALLOW — inner objects are shared", "An alias"], answer: 1,
    explain: "Mutating an inner element leaks to the original; use copy.deepcopy." },
  { q: "list.pop(0) in a loop is…", options: ["O(1)", "O(n) each → O(n²); use collections.deque", "Fast"], answer: 1,
    explain: "deque gives O(1) at both ends — the queue structure." },
  { q: "defaultdict(list) helps by…", options: ["Sorting", "Auto-creating [] for missing keys — no if-exists boilerplate", "Caching"], answer: 1,
    explain: "groups[k].append(v) just works — grouping made clean." },
  { q: "Counter is for…", options: ["Timing", "Frequency counts + most_common() in one line", "IDs"], answer: 1,
    explain: "Counter(words).most_common(3)." },
  { q: "Which can be a dict key?", options: ["A list", "A tuple (hashable/immutable)", "A set"], answer: 1,
    explain: "Keys must be hashable; mutable list/dict/set can't." },
  { q: "Dicts preserve…", options: ["No order", "Insertion order (guaranteed 3.7+)", "Sorted order"], answer: 1,
    explain: "Iteration follows insertion order." },
  { q: "sorted(x, key=lambda u: (u.role, -u.score)) does…", options: ["One-level sort", "Multi-level: by role asc, then score desc", "Random"], answer: 1,
    explain: "Tuple key = lexicographic multi-sort; -score descends." },
  { q: "nums[::-1] is…", options: ["An error", "The reversed list (slice with step -1)", "The first element"], answer: 1,
    explain: "Slicing is start:stop:step, stop exclusive." },
  { q: "heapq.nlargest(3, data, key=...) is…", options: ["O(n log n)", "Top-K in ~O(n log k) — no full sort", "O(n²)"], answer: 1,
    explain: "A heap for priority/top-K without sorting everything." },
  { q: "Modifying a list while iterating it…", options: ["Is fine", "Skips elements / can raise — iterate a copy or build new", "Reverses it"], answer: 1,
    explain: "Never mutate the collection you're looping over." },
  { q: "list vs tuple — pick tuple when…", options: ["Never", "Fixed record / need hashability (dict key / set member)", "Always"], answer: 1,
    explain: "Immutability enables hashing and signals 'don't change me'." },
  { q: "{**d1, **d2} produces…", options: ["An error", "A merged dict (d2 wins on conflicts); also d1 | d2", "A set"], answer: 1,
    explain: "Shallow merge; nested dicts still shared." },
  { q: "set operations a & b, a | b, a - b are…", options: ["Invalid", "Intersection, union, difference — O(min/sum) each", "String ops"], answer: 1,
    explain: "Sets give clean, fast algebra for membership problems." },
  { q: "[...] list comp vs (...) generator memory:", options: ["Same", "List builds all in memory; generator is lazy O(1)", "Generator is bigger"], answer: 1,
    explain: "Use a genexpr for one-time consumption of large data (generators lesson)." },
  { q: "d.setdefault(k, []).append(v) does…", options: ["Overwrites", "Gets or creates d[k]=[] then appends — grouping idiom", "Deletes"], answer: 1,
    explain: "defaultdict is usually cleaner for repeated use." },
  { q: "The right structure for a BFS queue is…", options: ["list.pop(0)", "collections.deque", "set"], answer: 1,
    explain: "O(1) popleft; list.pop(0) is O(n)." },
  { q: "Turning an O(n²) list-membership loop into O(n) uses…", options: ["A faster CPU", "A pre-built set for lookups", "sorting"], answer: 1,
    explain: "The classic Python optimization." }
]},

{ title: "Quiz 4 · Strings, Files & I/O",
  desc: "Immutability, encoding, with, pathlib, bytes vs str",
  questions: [
  { q: "Building a string with += in a loop is…", options: ["Fine", "O(n²) (strings are immutable) — use \"\".join(pieces)", "Fast"], answer: 1,
    explain: "Each += copies the whole accumulated string." },
  { q: "str vs bytes:", options: ["Same", "str = Unicode text; bytes = raw octets — decode/encode at boundaries", "bytes is faster text"], answer: 1,
    explain: "Files/network are bytes; convert with a known encoding." },
  { q: "open(\"f.txt\") without encoding…", options: ["Always UTF-8", "Uses the platform default → mojibake/UnicodeDecodeError across OSes", "Fails"], answer: 1,
    explain: "Always pass encoding=\"utf-8\" for portability." },
  { q: "`with open(...)` guarantees…", options: ["Speed", "The file closes even on exception (context manager)", "Nothing"], answer: 1,
    explain: "Manual close() is skipped on exceptions unless try/finally." },
  { q: "Reading a 10GB file without OOM:", options: ["f.read()", "Iterate the file object line-by-line", "readlines()"], answer: 1,
    explain: "for line in f streams; constant memory." },
  { q: "Mode \"w\" on an existing file…", options: ["Appends", "TRUNCATES it (use \"a\" to append, \"x\" to create-exclusive)", "Errors"], answer: 1,
    explain: "\"w\" wipes existing content — a data-loss footgun." },
  { q: "pathlib.Path is preferred over os.path because…", options: ["It's older", "Object API, / join operator, OS-correct, readable", "It's faster only"], answer: 1,
    explain: "Path('a') / 'b'; .exists(); .glob('*.csv')." },
  { q: "len(\"café\") vs len(\"café\".encode()):", options: ["Equal", "4 chars vs 5 bytes (é is 2 UTF-8 bytes)", "Both 5"], answer: 1,
    explain: "Character count ≠ byte count for non-ASCII." },
  { q: "Parsing real CSV should use…", options: ["str.split(',')", "the csv module (handles quotes/escapes)", "regex"], answer: 1,
    explain: "Hand-splitting breaks on quoted commas." },
  { q: "f\"{ratio:.1%}\" formats 0.256 as…", options: ["0.256", "25.6%", "256%"], answer: 1,
    explain: "The f-string mini-language handles percent, precision, alignment." },
  { q: "\"Hello\".replace(\"l\",\"L\") — the original string is…", options: ["Modified", "Unchanged (strings immutable; a NEW string returns)", "Empty"], answer: 1,
    explain: "All str methods return new strings." },
  { q: "json.dumps(obj, indent=2) is for…", options: ["Parsing", "Pretty-printing/serializing an object to JSON text", "Compression"], answer: 1,
    explain: "json.loads parses; json.dump writes to a file." },
  { q: "UnicodeDecodeError usually means…", options: ["Corrupt CPU", "Wrong/assumed encoding when decoding bytes", "Out of memory"], answer: 1,
    explain: "Specify the correct encoding." },
  { q: "\", \".join(parts) requires parts to be…", options: ["Any type", "Strings (join maps over strings)", "Numbers"], answer: 1,
    explain: "join(str(x) for x in parts) if converting." },
  { q: "s.strip() does…", options: ["Deletes s", "Returns a new string with leading/trailing whitespace removed", "Splits s"], answer: 1,
    explain: "strip()/lstrip()/rstrip(); pass chars to strip specific ones." },
  { q: "Writing JSON to a file:", options: ["print to file", "json.dump(obj, f) inside `with open(..., 'w')`", "f.write(obj)"], answer: 1,
    explain: "dump writes to a file; dumps returns a string." },
  { q: "p.glob(\"*.csv\") returns…", options: ["A string", "An iterator of matching Paths", "A count"], answer: 1,
    explain: "pathlib globbing; rglob for recursive." },
  { q: "io.StringIO is useful for…", options: ["Files only", "An in-memory text buffer (efficient string building / fake files in tests)", "Networking"], answer: 1,
    explain: "Alternative to join for incremental building." },
  { q: "Opening a binary file uses mode…", options: ["\"r\"", "\"rb\"/\"wb\" (bytes, no decoding)", "\"t\""], answer: 1,
    explain: "Binary mode reads/writes bytes without an encoding." },
  { q: "The safest way to handle a resource with cleanup is…", options: ["try/finally everywhere", "a context manager (with)", "hope"], answer: 1,
    explain: "with automates the try/finally — files, locks, transactions." }
]},

{ title: "Quiz 5 · OOP & Dataclasses",
  desc: "self, dunders, MRO, dataclass, composition, method types",
  questions: [
  { q: "`self` is…", options: ["A keyword", "The explicit instance parameter (first arg of methods)", "Global"], answer: 1,
    explain: "Python makes the receiver explicit, unlike JS's implicit this." },
  { q: "Class attribute vs instance attribute:", options: ["Same", "Class attr shared by all instances; instance attr per object", "Both per object"], answer: 1,
    explain: "A mutable class attribute is shared state (a gotcha)." },
  { q: "__repr__ is for…", options: ["Math", "A dev-readable representation (debugging/logs)", "Equality"], answer: 1,
    explain: "Define it or get useless <object at 0x..>; @dataclass generates it." },
  { q: "@dataclass generates…", options: ["Nothing", "__init__, __repr__, __eq__ (+ __hash__ if frozen)", "Only __init__"], answer: 1,
    explain: "frozen=True → immutable+hashable; slots=True → less memory." },
  { q: "A mutable default in a dataclass field needs…", options: ["= []", "field(default_factory=list)", "None"], answer: 1,
    explain: "Same shared-mutable trap as function defaults." },
  { q: "super() means…", options: ["The parent class", "The NEXT class in the MRO", "The base object"], answer: 1,
    explain: "MRO-relative — the key to cooperative multiple inheritance." },
  { q: "The MRO is…", options: ["Random", "The C3-linearized search order (Class.__mro__)", "Alphabetical"], answer: 1,
    explain: "Determines attribute lookup and super() chaining." },
  { q: "Python privacy is…", options: ["Enforced by the compiler", "Convention: _name (internal), __name (mangled, not private)", "Impossible"], answer: 1,
    explain: "'We're all consenting adults' — design a clear public API." },
  { q: "@classmethod's first param is…", options: ["self", "cls (the class) — used for alternative constructors", "nothing"], answer: 1,
    explain: "from_json(cls, d): return cls(...)." },
  { q: "@staticmethod…", options: ["Takes self", "Takes neither self nor cls — a namespaced helper", "Takes cls"], answer: 1,
    explain: "Logically grouped function that needs no instance/class." },
  { q: "Dunder methods let you…", options: ["Hide data", "Hook into syntax: __len__→len(), __iter__→for, __add__→+", "Speed up"], answer: 1,
    explain: "Implementing them is what 'Pythonic' means for custom types." },
  { q: "__eq__ without __hash__ makes an object…", options: ["Faster", "Unhashable → unusable in sets/dict keys", "Immutable"], answer: 1,
    explain: "Define both, or use a frozen dataclass." },
  { q: "@property lets a method…", options: ["Be static", "Be accessed like an attribute (computed field)", "Be private"], answer: 1,
    explain: "obj.balance runs code but reads like a field." },
  { q: "Composition over inheritance means…", options: ["Never use classes", "Assemble behavior from injected parts rather than deep hierarchies", "Multiple inheritance"], answer: 1,
    explain: "Inherit stable contracts; compose capabilities (duck typing/Protocol)." },
  { q: "Duck typing means…", options: ["A type system", "If it has the needed methods, it works — no explicit interface", "Slow types"], answer: 1,
    explain: "typing.Protocol adds static checking to it (typing lesson)." },
  { q: "isinstance over type() because…", options: ["Shorter", "It respects subclasses", "It's faster"], answer: 1,
    explain: "type(x)==C misses subclass instances." },
  { q: "new object with __init__…", options: ["Runs once per class", "Runs per instance to set up state", "Never runs"], answer: 1,
    explain: "__init__ initializes; __new__ creates (rarely overridden)." },
  { q: "A frozen dataclass is…", options: ["Slow", "Immutable and hashable — usable as dict keys / set members", "Mutable"], answer: 1,
    explain: "Mirrors the immutability discipline." },
  { q: "Deep inheritance hierarchies…", options: ["Are best practice", "Age badly (fragile base class, MRO surprises) — prefer composition", "Are required"], answer: 1,
    explain: "Same verdict as the JS classes lesson." },
  { q: "For runtime data validation + serialization, prefer…", options: ["dataclass", "Pydantic (validates types at runtime; dataclass doesn't)", "namedtuple"], answer: 1,
    explain: "dataclass annotations aren't enforced; Pydantic checks (typing/fastapi lessons)." }
]}
);
