// Python quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Comprehensions, Iterators & Generators",
  desc: "Comprehensions, lazy generators, itertools, the iterator protocol",
  questions: [
  { q: "[x*x for x in nums if x>0] is a…", options: ["Loop", "List comprehension (transform + filter)", "Generator"], answer: 1,
    explain: "Faster than an append-loop; {} and {k:v} give set/dict comps." },
  { q: "sum(x*x for x in range(1_000_000)) uses…", options: ["A million-item list", "A lazy generator expression — O(1) memory", "A tuple"], answer: 1,
    explain: "Parentheses (not brackets) = lazy, streamed one item at a time." },
  { q: "yield makes a function…", options: ["Return early", "A generator (lazy, resumable, stateful)", "Async"], answer: 1,
    explain: "Calling it runs no body; each next() resumes after the last yield." },
  { q: "Reading a 10GB file with a generator gives…", options: ["OOM", "Constant memory (one line at a time)", "Faster CPU"], answer: 1,
    explain: "yield line inside `with open` streams it." },
  { q: "An infinite generator (while True: yield) is safe because…", options: ["It's not", "Laziness — take only what you consume (islice)", "It caches"], answer: 1,
    explain: "Values compute on demand; islice(gen, 10) takes 10." },
  { q: "A generator, once exhausted…", options: ["Restarts", "Is empty on the next iteration (one-shot)", "Errors"], answer: 1,
    explain: "Recreate it or use a list if you need multiple passes." },
  { q: "itertools.groupby requires…", options: ["Nothing", "Pre-sorting by the key (it groups CONSECUTIVE keys)", "A dict"], answer: 1,
    explain: "It's a single lazy pass; unsorted → fragmented groups." },
  { q: "list comp vs generator: use a generator when…", options: ["You need len()", "Data is large/streamed and consumed once", "You need indexing"], answer: 1,
    explain: "Lists for random access/len/multiple passes; generators for memory." },
  { q: "len(a_generator) …", options: ["Returns count", "Raises TypeError (generators aren't sized)", "Returns 0"], answer: 1,
    explain: "Materialize with list() if you truly need length." },
  { q: "A for-loop internally calls…", options: ["range()", "iter() then next() until StopIteration", "map()"], answer: 1,
    explain: "The iterator protocol underlies comprehensions, unpacking, *args." },
  { q: "itertools.chain(a, b) does…", options: ["Zips", "Lazily concatenates iterables", "Sorts"], answer: 1,
    explain: "Flatten without building an intermediate list." },
  { q: "A nested comprehension you have to squint at should be…", options: ["Kept", "Rewritten as a loop for readability", "Nested deeper"], answer: 1,
    explain: "Comprehensions are for clarity; complex logic → explicit loop." },
  { q: "yield from another_gen…", options: ["Is invalid", "Delegates: yields all values from another iterable", "Returns it"], answer: 1,
    explain: "Generator composition (like JS yield*)." },
  { q: "{u.id: u for u in users} is a…", options: ["Set", "Dict comprehension (build a lookup index)", "List"], answer: 1,
    explain: "keyBy in one expression." },
  { q: "accumulate([1,2,3,4]) yields…", options: ["[10]", "Running totals 1,3,6,10", "[1,2,3,4]"], answer: 1,
    explain: "itertools for prefix sums lazily." },
  { q: "Generator memory advantage matters most for…", options: ["Small lists", "Large/infinite/streamed data consumed once", "Sorting"], answer: 1,
    explain: "O(1) vs O(n) — the whole point." },
  { q: "combinations(items, 2) / product(a, b) replace…", options: ["Nothing", "Manual nested loops for combinatorics", "sorting"], answer: 1,
    explain: "Lazy, readable combinatorial iteration." },
  { q: "A generator's state between yields is…", options: ["Lost", "Preserved (locals survive) — a resumable frame", "Global"], answer: 1,
    explain: "Fibonacci keeps a, b across yields." },
  { q: "next(gen, default) …", options: ["Errors at end", "Returns default instead of raising StopIteration when exhausted", "Restarts"], answer: 1,
    explain: "Safe single-step consumption." },
  { q: "Comprehensions vs map/filter in Python:", options: ["map wins", "Comprehensions are usually more readable and idiomatic", "Identical always"], answer: 1,
    explain: "Prefer comprehensions; map/filter still fine with existing functions." }
]},

{ title: "Quiz 7 · Decorators, Context Managers & Typing",
  desc: "Decorators, wraps, lru_cache, with, type hints, Protocol",
  questions: [
  { q: "A decorator is…", options: ["A class", "A function taking a function and returning a replacement", "A loop"], answer: 1,
    explain: "@deco is sugar for fn = deco(fn)." },
  { q: "Custom decorators must use…", options: ["Nothing", "@functools.wraps (preserve __name__/__doc__) + forward *args/**kwargs", "global"], answer: 1,
    explain: "Skipping wraps breaks introspection/logging." },
  { q: "A decorator that takes arguments needs…", options: ["One function", "THREE nested functions (factory → decorator → wrapper)", "A class only"], answer: 1,
    explain: "@retry(3) = retry(3)(fn)." },
  { q: "@lru_cache memoizes…", options: ["Any function", "Pure functions of HASHABLE args (bound size to avoid leaks)", "I/O calls"], answer: 1,
    explain: "Wrong for impure/mutating-arg functions; @cache is unbounded." },
  { q: "A context manager guarantees…", options: ["Speed", "Teardown (__exit__) even on exception", "Nothing"], answer: 1,
    explain: "Files close, locks release, transactions roll back." },
  { q: "@contextmanager turns a generator into…", options: ["A decorator", "A context manager (before yield = setup, after = teardown)", "A loop"], answer: 1,
    explain: "try/yield/finally around one yield." },
  { q: "__exit__ returning True…", options: ["Does nothing", "SUPPRESSES the exception (usually you want False)", "Re-raises"], answer: 1,
    explain: "Return False/None to let exceptions propagate." },
  { q: "Python type hints at runtime are…", options: ["Enforced", "Erased/ignored — a checker (mypy/pyright) validates them", "Compiled"], answer: 1,
    explain: "def f(x:int) doesn't reject f('s'); validate external data separately." },
  { q: "list[str], dict[str,int] (3.9+) replace…", options: ["Nothing", "typing.List/Dict — builtin generics", "Any"], answer: 1,
    explain: "Modern hint syntax; X | None for optionals (3.10+)." },
  { q: "unknown external data should be validated with…", options: ["Type hints", "Pydantic (runtime validation) — hints don't run", "Any"], answer: 1,
    explain: "Same boundary rule as TS/zod; Pydantic ≈ zod." },
  { q: "A Protocol types…", options: ["Inheritance", "Structural/duck typing (anything with the right methods)", "Nothing"], answer: 1,
    explain: "Static face of composition; no explicit 'implements'." },
  { q: "Overusing Any…", options: ["Helps", "Disables checking (contagious) — 'mypy passes but catches nothing'", "Is required"], answer: 1,
    explain: "Prefer precise types / unknown-then-narrow; ban Any in lint." },
  { q: "Hints without a checker in CI…", options: ["Are enforced", "Drift and lie over time — run mypy/pyright as a gate", "Are fine"], answer: 1,
    explain: "The value is the checker + boundary validation." },
  { q: "Literal[\"asc\",\"desc\"] gives…", options: ["Any string", "A typo-proof set of exact allowed values", "A number"], answer: 1,
    explain: "The Python equivalent of a string-literal union." },
  { q: "@property + a setter…", options: ["Is impossible", "Exposes controlled read/write as attribute access", "Is static"], answer: 1,
    explain: "@x.setter guards writes; getter computes reads." },
  { q: "cast() to silence mypy…", options: ["Is safe", "Lies to the checker — narrow properly instead; use only when you truly know more", "Validates"], answer: 1,
    explain: "Like TS `as` — a smell that needs justification." },
  { q: "with open(...) as f is preferred because…", options: ["Shorter", "Deterministic close on success OR exception", "Faster read"], answer: 1,
    explain: "The context-manager guarantee." },
  { q: "TypeVar T enables…", options: ["Constants", "Generics: def first(xs: list[T]) -> T | None", "Async"], answer: 1,
    explain: "Preserves the relationship between input and output types." },
  { q: "Flask @app.route and pytest @fixture are…", options: ["Special syntax", "Ordinary decorators you consume", "Classes"], answer: 1,
    explain: "Same mechanism you can write yourself." },
  { q: "mypy --strict is comparable to…", options: ["Nothing", "TypeScript strict mode — catches the most (esp. Optional handling)", "A formatter"], answer: 1,
    explain: "Turn it on for new code; ratchet legacy." }
]},

{ title: "Quiz 8 · Concurrency: GIL, Threads, Async",
  desc: "The GIL, threads vs processes vs asyncio, thread safety",
  questions: [
  { q: "The GIL means…", options: ["Python has no threads", "Only one thread runs Python bytecode at a time (no CPU parallelism for pure Python)", "Threads are fast"], answer: 1,
    explain: "Released during I/O and in C extensions, so threads overlap I/O." },
  { q: "For CPU-bound parallelism, use…", options: ["Threads", "Multiple PROCESSES (ProcessPoolExecutor) — own GIL/core each", "asyncio"], answer: 1,
    explain: "Threads give no speedup for pure-Python CPU work." },
  { q: "For many concurrent I/O tasks (APIs/DB), the cheapest tool is…", options: ["Processes", "asyncio (one thread, thousands of awaits)", "Threads only"], answer: 1,
    explain: "No GIL fight when everything is waiting." },
  { q: "For blocking (non-async) I/O libraries, use…", options: ["asyncio directly", "ThreadPoolExecutor (GIL released during I/O)", "Processes"], answer: 1,
    explain: "Threads overlap the waits even with the GIL." },
  { q: "A blocking call inside asyncio…", options: ["Runs in parallel", "Freezes the ENTIRE event loop", "Is fine"], answer: 1,
    explain: "Use async libs or asyncio.to_thread/run_in_executor." },
  { q: "'threading didn't speed up my number crunching' — cause?", options: ["Bad code", "The GIL — use multiprocessing for CPU-bound work", "Slow disk"], answer: 1,
    explain: "The canonical GIL surprise." },
  { q: "counter += 1 across threads without a lock…", options: ["Is atomic", "Can lose updates (read-modify-write race) despite the GIL", "Is fine"], answer: 1,
    explain: "The GIL prevents corruption, not logical races — use a Lock." },
  { q: "asyncio.gather(*coros) does…", options: ["Runs sequentially", "Runs coroutines concurrently and collects results", "Blocks"], answer: 1,
    explain: "Like Promise.all — parallel I/O on one loop." },
  { q: "Processes cost more than threads because…", options: ["They're slower always", "Separate memory + pickling args/results across the boundary", "The GIL"], answer: 1,
    explain: "Worth it only when compute dwarfs the overhead." },
  { q: "'coroutine was never awaited' means…", options: ["Syntax error", "You called an async fn without awaiting it", "It ran"], answer: 1,
    explain: "await coroutines; asyncio.run at the top level." },
  { q: "The GIL is released…", options: ["Never", "During I/O waits and inside many C extensions (numpy)", "Always"], answer: 1,
    explain: "Why threads help I/O-bound but not CPU-bound work." },
  { q: "async/await in Python is…", options: ["Multithreading", "Cooperative concurrency on one event loop (like JS)", "Multiprocessing"], answer: 1,
    explain: "Same don't-block-the-loop rule as Node." },
  { q: "asyncio.to_thread(fn) is for…", options: ["CPU work", "Running a BLOCKING call off the loop without freezing it", "Nothing"], answer: 1,
    explain: "Offload blocking I/O; process pool for CPU." },
  { q: "3.13's free-threaded build…", options: ["Removes asyncio", "Is an experimental no-GIL option — know it exists; default reality still has the GIL", "Is standard"], answer: 1,
    explain: "The GIL mental model remains the default." },
  { q: "Prefer over shared mutable state…", options: ["More locks", "Message passing (queue.Queue) — fewer races", "Globals"], answer: 1,
    explain: "Same philosophy as the JS workers lesson." },
  { q: "For 1000 concurrent HTTP calls, choose…", options: ["1000 threads", "asyncio with an async HTTP client", "1000 processes"], answer: 1,
    explain: "Cheapest concurrency for I/O-bound fan-out." },
  { q: "For resizing 10k images, choose…", options: ["asyncio", "ProcessPoolExecutor (CPU-bound, needs cores)", "Threads"], answer: 1,
    explain: "True parallelism past the GIL." },
  { q: "A legacy blocking DB driver in a threadpool works because…", options: ["It's async", "The GIL releases during the driver's I/O, so threads overlap waits", "Magic"], answer: 1,
    explain: "Match tool to workload AND library nature." },
  { q: "multiprocessing shares data via…", options: ["Direct references", "Pickling / shared memory (separate address spaces)", "Threads"], answer: 1,
    explain: "No shared heap; pass data across the boundary." },
  { q: "The one rule organizing Python concurrency:", options: ["Always use asyncio", "I/O-bound → threads/async; CPU-bound → processes (because of the GIL)", "Use more cores"], answer: 1,
    explain: "Every choice derives from it." }
]},

{ title: "Quiz 9 · Testing, Packaging & FastAPI",
  desc: "pytest, fixtures, venv/lockfiles, FastAPI, Pydantic, DI",
  questions: [
  { q: "pytest assertions use…", options: ["assertEqual", "plain assert (with rich failure introspection)", "expect()"], answer: 1,
    explain: "pytest.raises for exceptions; -k / ::name to select." },
  { q: "@pytest.mark.parametrize gives…", options: ["Fixtures", "Table-driven tests (one test, many cases)", "Mocks"], answer: 1,
    explain: "Cover edge branches without copy-paste." },
  { q: "A fixture with yield…", options: ["Loops", "Provides setup before + teardown after (runs even on failure)", "Mocks"], answer: 1,
    explain: "conftest.py shares them; scopes function→session." },
  { q: "The #1 mocking bug is patching…", options: ["Too much", "Where the function is DEFINED instead of where it's USED", "Nothing"], answer: 1,
    explain: "patch the module that imported it." },
  { q: "Mock in tests should target…", options: ["Your own logic", "External EDGES (email/HTTP/clock) — not your code", "The DB always"], answer: 1,
    explain: "Real test DB for integration; mocking your logic tests the mock." },
  { q: "A virtual environment…", options: ["Speeds Python", "Isolates per-project Python + packages (avoids global conflicts)", "Is optional in prod"], answer: 1,
    explain: "The #1 'works on my machine' fix." },
  { q: "The lockfile (uv.lock/poetry.lock)…", options: ["Is optional", "Pins the exact transitive tree — commit it; CI installs from it", "Is generated at runtime"], answer: 1,
    explain: "Reproducibility, like npm's package-lock." },
  { q: "if __name__ == '__main__':…", options: ["Always runs", "Runs only on direct execution, not import", "Never runs"], answer: 1,
    explain: "Guards entry points so imports don't trigger side effects." },
  { q: "FastAPI derives validation/docs from…", options: ["A config file", "Type hints + Pydantic models", "Comments"], answer: 1,
    explain: "One source: typed models → 422 validation, serialization, /docs." },
  { q: "response_model in FastAPI…", options: ["Speeds responses", "Shapes/validates output and prevents leaking internal fields", "Adds auth"], answer: 1,
    explain: "Never return the raw DB model (leaks passwords etc.)." },
  { q: "Bad request body in FastAPI returns…", options: ["500", "422 automatically (Pydantic validation)", "200"], answer: 1,
    explain: "Validation at the boundary, for free from the model." },
  { q: "Depends() provides…", options: ["Logging only", "Dependency injection (DB/auth/pagination) — overridable in tests", "Threads"], answer: 1,
    explain: "app.dependency_overrides swaps real deps for fakes." },
  { q: "A blocking call in an async FastAPI endpoint…", options: ["Is fine", "Stalls the loop — use async drivers or a sync def (threadpool)", "Speeds up"], answer: 1,
    explain: "Same don't-block-the-loop rule." },
  { q: "Coverage 100%…", options: ["Proves quality", "Measures lines run, not correctness — cover meaningful branches", "Is required"], answer: 1,
    explain: "A gap-finder, not a target." },
  { q: "A transaction-rollback db fixture gives…", options: ["Slow tests", "Fast, isolated integration tests (pristine state per test)", "Mocked data"], answer: 1,
    explain: "Same pattern as the Node testing lesson." },
  { q: "pip install -e . does…", options: ["Uploads to PyPI", "Editable install so imports resolve during development", "Nothing"], answer: 1,
    explain: "src-layout + editable install is the shippable structure." },
  { q: "pydantic-settings loads config from…", options: ["Code", "Environment variables (never hardcode secrets)", "The DB"], answer: 1,
    explain: "12-factor config; secrets from env/secret manager." },
  { q: "Serving FastAPI in production uses…", options: ["One uvicorn worker", "uvicorn/gunicorn workers = cores, behind a reverse proxy", "The dev server"], answer: 1,
    explain: "Process-per-core for throughput (Node scaling parallel)." },
  { q: "Testing a FastAPI app uses…", options: ["Real network", "httpx AsyncClient + dependency_overrides against a test DB", "Selenium"], answer: 1,
    explain: "Integration through the real stack with fakes for edges." },
  { q: "authz enforced only in the UI is…", options: ["Fine", "A vuln (BOLA) — the API must enforce ownership/permissions", "Faster"], answer: 1,
    explain: "Never trust the client; server is the boundary." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "def f(x, items=[]) accumulates across calls. Root cause?", options: ["A bug in Python", "Default args evaluated once — the list is shared. Fix: None sentinel", "Scope"], answer: 1,
    explain: "The signature-default gotcha (#1 function question)." },
  { q: "b = a.copy() on nested data; b[0].append(x) changes a[0]. Why?", options: ["Deep copy failed", "Shallow copy shares inner objects — use copy.deepcopy", "a is b"], answer: 1,
    explain: "Same shallow/deep story as JS spread vs structuredClone." },
  { q: "A membership check in a loop over a 100k list is slow. Fix?", options: ["Faster CPU", "Build a set once — O(n) instead of O(n²)", "Sort it"], answer: 1,
    explain: "in on list is O(n); on set is O(1)." },
  { q: "threading didn't speed up CPU-heavy work. Why and fix?", options: ["Bad threads", "The GIL — use multiprocessing (ProcessPoolExecutor)", "Add threads"], answer: 1,
    explain: "Threads only help I/O-bound work." },
  { q: "One time.sleep froze your whole asyncio server. Cause?", options: ["Slow disk", "A blocking call on the single event loop — use asyncio.sleep / to_thread", "Too few workers"], answer: 1,
    explain: "Never block the loop (concurrency + fastapi lessons)." },
  { q: "Your mock of send_email didn't apply. Cause?", options: ["Wrong email", "Patched where DEFINED, not where the code LOOKS IT UP", "Bad fixture"], answer: 1,
    explain: "patch the importing module's namespace." },
  { q: "'café' from a file reads as 'cafÃ©' on Windows. Cause?", options: ["Corrupt file", "Missing encoding='utf-8' → platform default used", "Bad font"], answer: 1,
    explain: "Always specify the encoding." },
  { q: "type hint says int but a str got through and crashed later. Why?", options: ["mypy bug", "Hints are erased at runtime — validate external data (Pydantic) + run mypy", "Python is weak"], answer: 1,
    explain: "The boundary-validation rule." },
  { q: "Building a big string with += is slow. Fix?", options: ["Faster CPU", "\"\".join(pieces) — strings are immutable (+=  is O(n²))", "Use bytes"], answer: 1,
    explain: "Single allocation via join." },
  { q: "super() called the wrong class in multiple inheritance. Cause?", options: ["A bug", "super() follows the MRO, not 'the parent' — check __mro__", "Missing self"], answer: 1,
    explain: "C3 linearization drives cooperative inheritance." },
  { q: "Your custom decorator broke logging (wrong function name). Cause?", options: ["Slow", "Missing @functools.wraps on the wrapper", "No return"], answer: 1,
    explain: "wraps preserves __name__/__doc__." },
  { q: "@lru_cache caused a memory leak. Cause?", options: ["A bug", "Unbounded cache (@cache) — use lru_cache(maxsize=N)", "Threads"], answer: 1,
    explain: "Bound hot caches; cache only pure hashable-arg functions." },
  { q: "A 10GB file crashed with OOM on f.read(). Fix?", options: ["More RAM", "Iterate line-by-line (or a generator) — constant memory", "readlines"], answer: 1,
    explain: "Streaming beats loading (streams parallel)." },
  { q: "Money math shows 0.30000000000000004. Fix?", options: ["Round always", "decimal.Decimal or integer cents — floats are inexact", "Use str"], answer: 1,
    explain: "IEEE-754 (types lesson)." },
  { q: "Returning the DB model from FastAPI leaked a password field. Fix?", options: ["Encrypt it", "response_model=PublicUser to shape output", "Hide in UI"], answer: 1,
    explain: "Control exposure at the serialization boundary." },
  { q: "'works on my machine' — different deps in prod. Cause?", options: ["Bad code", "No committed lockfile / no venv — pin and sync from the lock", "Slow network"], answer: 1,
    explain: "venv + lockfile + CI sync (packaging lesson)." },
  { q: "for i in range(len(x)) then x[i] is…", options: ["Optimal", "Unpythonic/error-prone — use enumerate or iterate directly", "Required"], answer: 1,
    explain: "enumerate/zip are the idioms." },
  { q: "GET /users/5 returns another user's data. Vulnerability?", options: ["XSS", "BOLA/IDOR — missing ownership check on the server", "CSRF"], answer: 1,
    explain: "Enforce authz in the API, not the UI." },
  { q: "Tests pass alone but fail together. Likely cause?", options: ["Flaky pytest", "Shared mutable state / order dependence — isolate via fixtures", "Slow DB"], answer: 1,
    explain: "The mutation trap in test suites." },
  { q: "The single most important Python mental model is…", options: ["Memorize stdlib", "Names bound to objects + the GIL (I/O vs CPU tool choice)", "Use type hints"], answer: 1,
    explain: "Mutation/copy/argument behavior AND concurrency choices both derive from these. 🏆" }
]}
);
