// python quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Comprehensions, Iterators & Generators",
  desc: "The iterator protocol, laziness, memory and where generators pay off",
  questions: [
  { q: "The iterator protocol requires…", options: ["__iter__ returning self, and __next__ raising StopIteration when exhausted", "__len__ and __getitem__", "__enter__ and __exit__"], answer: 0,
    explain: "An ITERABLE has __iter__; an ITERATOR also has __next__. A list is iterable but not an iterator, which is why you can loop it twice." },
  { q: "A generator differs from a list comprehension in that it…", options: ["Can only be used with numbers", "Is always faster", "Produces items lazily, one at a time, holding no full result in memory"], answer: 2,
    explain: "`sum(x*x for x in range(10_000_000))` uses constant memory; the list version allocates ten million ints." },
  { q: "Iterating an exhausted generator again…", options: ["Restarts from the beginning", "Yields nothing — generators are single-pass", "Raises StopIteration to the caller"], answer: 1,
    explain: "The silent bug: `list(gen)` then `sum(gen)` gives 0. If you need two passes, materialise it or build a fresh generator." },
  { q: "`yield` inside a function makes calling it…", options: ["Raise unless awaited", "Return a generator without executing any of the body", "Run the body immediately"], answer: 1,
    explain: "Nothing runs until the first next(). A generator that validates its arguments therefore reports errors far from the call site." },
  { q: "`yield from sub()` does what a `for x in sub(): yield x` loop does, plus…", options: ["Forwards send/throw/close and propagates the sub-generator's return value", "Runs it concurrently", "Nothing extra"], answer: 0,
    explain: "It matters for delegation and coroutines; for plain iteration the two are equivalent." },
  { q: "A comprehension's loop variable…", options: ["Is always global", "Has its own scope and does not leak", "Leaks into the enclosing scope, like Python 2"], answer: 1,
    explain: "Fixed in Python 3. The walrus operator is the deliberate exception — it does assign outward." },
  { q: "A nested comprehension `[y for row in grid for y in row]` reads…", options: ["Inner loop first", "Right to left", "In the same order as the equivalent nested for loops, left to right"], answer: 2,
    explain: "Write the for-loop version first and transcribe it. Beyond two levels, a loop is more readable than a comprehension." },
  { q: "`itertools.islice(gen, 5)` is preferable to `list(gen)[:5]` because…", options: ["It sorts the result", "It stops after five items instead of consuming everything", "It restarts the generator"], answer: 1,
    explain: "On an infinite or expensive generator, the slice version never terminates or does far too much work." },
  { q: "`zip(a, b)` stops when…", options: ["The shortest is exhausted — silently dropping the rest", "The longest iterable is exhausted", "Either contains None"], answer: 0,
    explain: "`strict=True` (3.10+) raises on a length mismatch, which is what you usually want; `zip_longest` pads instead." },
  { q: "`enumerate(items, start=1)` exists because…", options: ["Manual index counters are a common source of off-by-one bugs, and this reads as intent", "It sorts the items", "It is faster than range(len(items))"], answer: 0,
    explain: "`for i, item in enumerate(items)` is the idiom; `for i in range(len(items))` is a smell in review." },
  { q: "A generator expression passed directly as a sole function argument…", options: ["Always needs double parentheses", "Is a syntax error", "Needs no extra parentheses: `sum(x for x in xs)`"], answer: 2,
    explain: "Extra parens are required only when there are other arguments." },
  { q: "`itertools.chain(a, b)` versus `a + b` for lists:", options: ["chain is slower and allocates more", "They are identical", "chain iterates both lazily without building a combined list"], answer: 2,
    explain: "`chain.from_iterable` flattens a nested iterable lazily, which matters when the pieces are large or generated." },
  { q: "`any()` and `all()` short-circuit, meaning…", options: ["They stop at the first decisive element — which is why passing a generator matters", "They evaluate everything then decide", "They require a list"], answer: 0,
    explain: "`any(is_bad(x) for x in huge)` can stop after one item; `any([is_bad(x) for x in huge])` evaluates all of them first." },
  { q: "A generator's `.close()`…", options: ["Resets it to the start", "Raises GeneratorExit inside it at the paused yield, so `finally` blocks run", "Deletes it from memory"], answer: 1,
    explain: "This is what makes `try/finally` inside a generator a valid place to release resources." },
  { q: "Consuming a generator in a `with` block that opens a file, and returning the generator…", options: ["Is a bug: the with block exits and closes the file before the caller iterates", "Works — the file stays open", "Raises immediately"], answer: 0,
    explain: "Either yield from inside the with (keeping it open while consumed), or hand the caller the open file." },
  { q: "`reversed()` requires…", options: ["A sequence with __len__ and __getitem__, or __reversed__", "A sorted input", "Any iterable"], answer: 0,
    explain: "It cannot work on a plain generator, because there is no way to walk it backwards without buffering." },
  { q: "The memory advantage of generators disappears when…", options: ["The generator is short", "You materialise the result anyway, e.g. `list(gen)` or `sorted(gen)`", "You use itertools"], answer: 1,
    explain: "sorted() must see every element, so a generator saves nothing there — the benefit is in streaming pipelines that never collect." },
  { q: "`map(f, xs)` in Python 3 returns…", options: ["A list", "A lazy iterator", "A generator function"], answer: 1,
    explain: "So `map(print, xs)` does nothing until consumed — a common surprise for people coming from Python 2." },
  { q: "A comprehension is preferable to a for-loop with append when…", options: ["The list is large", "Always", "The transformation is a single expression and fits on a line or two"], answer: 2,
    explain: "Comprehensions with side effects, or with three nested clauses and a conditional, are worse than the loop they replaced." },
  { q: "`functools.reduce` is discouraged in Python because…", options: ["An explicit loop or a purpose-built function (sum, math.prod, any) is usually clearer", "It is removed in 3.12", "It cannot take a lambda"], answer: 0,
    explain: "Guido moved it out of builtins for exactly this reason — reduce with a non-obvious operator is write-only code." },
]},
{ title: "Quiz 7 · Decorators, Context Managers & Typing",
  desc: "Wrapping behaviour, resource guarantees and what type hints do and do not do",
  questions: [
  { q: "A decorator is…", options: ["A compiler directive", "A class attribute", "A function that takes a function and returns a replacement"], answer: 2,
    explain: "`@log` is exactly `f = log(f)`. Once you see that, the syntax stops being magic." },
  { q: "Without `functools.wraps`, a decorated function loses…", options: ["Its return value", "Its __name__, __doc__ and __wrapped__ metadata — breaking introspection, docs and some frameworks", "Its arguments"], answer: 1,
    explain: "It matters in practice: pytest, Sphinx and dependency-injection frameworks read those attributes." },
  { q: "A decorator that takes arguments requires…", options: ["Three levels: arguments → decorator → wrapper", "Two levels", "A class"], answer: 0,
    explain: "`@retry(times=3)` calls retry(3), which returns the actual decorator, which returns the wrapper." },
  { q: "Decorators are applied…", options: ["Top to bottom", "Bottom-up — the closest to the def wraps first", "In arbitrary order"], answer: 1,
    explain: "So `@a` over `@b` over `def f` is `a(b(f))`, and order matters when one caches and the other authorises." },
  { q: "`functools.lru_cache` on a method is risky because…", options: ["It cannot decorate methods", "It caches on `self`, keeping every instance alive for the process lifetime", "It ignores arguments"], answer: 1,
    explain: "A memory leak that looks like a cache. `functools.cached_property` or a per-instance cache is the fix." },
  { q: "`lru_cache` requires arguments to be…", options: ["Positional only", "Hashable, since they form the cache key", "Immutable strings"], answer: 1,
    explain: "Passing a list raises TypeError — and `cache_info()` is the first thing to check when a cache seems ineffective." },
  { q: "A context manager guarantees cleanup because…", options: ["It registers an atexit handler", "__exit__ runs on the way out whether the block completed or raised", "Python retries the block"], answer: 1,
    explain: "Returning True from __exit__ suppresses the exception — which should be rare and deliberate." },
  { q: "`@contextlib.contextmanager` turns a generator into a context manager where…", options: ["Code before yield is setup, code after is teardown", "yield must return a value", "The whole body is setup"], answer: 0,
    explain: "Wrap the yield in try/finally, or an exception in the block skips your teardown entirely." },
  { q: "`contextlib.suppress(FileNotFoundError)` is preferable to a bare try/except/pass because…", options: ["It is faster", "It logs the exception", "It states the intent explicitly and cannot accidentally grow to swallow more"], answer: 2,
    explain: "A `pass` in an except block invites someone to widen the exception later." },
  { q: "Type hints at runtime are…", options: ["Compiled away entirely", "Enforced by the interpreter", "Stored as annotations and otherwise ignored — a static-checker input"], answer: 2,
    explain: "`def f(x: int)` happily receives a string. Runtime validation needs pydantic or explicit checks." },
  { q: "`Optional[str]` means…", options: ["The argument may be omitted", "`str | None` — the value may be None", "The type is inferred"], answer: 1,
    explain: "Optionality of an ARGUMENT comes from having a default, which is a different thing entirely. `str | None` is the modern spelling." },
  { q: "A `typing.Protocol` provides…", options: ["Runtime interface enforcement", "A base class you must subclass", "Structural typing — anything with the right methods satisfies it, with no inheritance"], answer: 2,
    explain: "It gives duck typing static checking, and it is how you type a parameter as 'anything with .read()'." },
  { q: "`list[str]` versus `List[str]` (from typing):", options: ["Built-in generics work from 3.9+; the typing aliases are legacy", "They differ in behaviour", "Only List works with mypy"], answer: 0,
    explain: "The 3.12 `type` statement and `class Repo[T]:` syntax continue that direction, replacing explicit TypeVar in most cases." },
  { q: "`Any` differs from `object` because…", options: ["They are identical", "Any disables checking on that value; object accepts anything but permits no operations", "object is faster"], answer: 1,
    explain: "`Any` is an escape hatch that silently spreads; `object` is honest about knowing nothing, forcing a narrowing check." },
  { q: "Narrowing means…", options: ["Converting int to float", "Shrinking a container", "The checker deduces a more specific type inside a branch, e.g. after `if x is not None`"], answer: 2,
    explain: "`isinstance`, `is None`, and TypeGuard functions all narrow — which is why an early return is friendlier to the checker than a nested if." },
  { q: "`TypedDict` is useful for…", options: ["Typing a dict with a known set of string keys, such as a JSON payload", "Replacing dataclasses everywhere", "Enforcing types at runtime"], answer: 0,
    explain: "It describes the shape of data you receive; a dataclass models data you own." },
  { q: "Adding type hints to an untyped codebase is best done…", options: ["All at once with strict mode", "Only on new code, never on old", "Incrementally, module by module, with the checker in CI to prevent regressions"], answer: 2,
    explain: "Start with the boundaries — public functions and I/O — where hints catch the most and cost the least." },
  { q: "Mutable default arguments in a typed signature are…", options: ["Prevented by the checker", "Still the same bug — types do not change evaluation semantics", "Automatically copied"], answer: 1,
    explain: "Type checkers do not catch it; linters (ruff, flake8-bugbear) do." },
  { q: "The main practical benefit of type hints is…", options: ["Errors caught before running, plus editor autocomplete and safer refactors", "Runtime speed", "Smaller memory footprint"], answer: 0,
    explain: "The refactor benefit is the one people underrate: renaming a field and having the checker list every caller." },
  { q: "A decorator that changes a function's signature should…", options: ["Never be typed", "Use Any for everything", "Be avoided or typed with ParamSpec, or callers lose their checking"], answer: 2,
    explain: "`ParamSpec` and `Concatenate` let a decorator preserve or extend the wrapped signature for the checker." },
]},
{ title: "Quiz 8 · Concurrency: GIL, Threads, Async",
  desc: "What the GIL does, choosing a model, and the failure modes of each",
  questions: [
  { q: "The GIL prevents…", options: ["Threads from being created", "Any form of parallelism in Python", "Two threads executing Python bytecode simultaneously in one interpreter"], answer: 2,
    explain: "It protects interpreter internals such as reference counts. Processes sidestep it entirely, since each has its own interpreter." },
  { q: "Threads still help with I/O-bound work because…", options: ["I/O runs on the GPU", "The GIL is released during blocking I/O", "The GIL applies only to CPU code you wrote"], answer: 1,
    explain: "Waiting on a socket is not executing bytecode, so other threads run. Ten HTTP calls take about as long as one." },
  { q: "For CPU-bound work in one process, adding threads typically…", options: ["Makes it slightly slower, from GIL contention and switching", "Scales linearly with cores", "Is forbidden"], answer: 0,
    explain: "`ProcessPoolExecutor` is the answer — or moving the hot loop into NumPy or C, which release the GIL." },
  { q: "Python 3.13 introduced an experimental free-threaded build (PEP 703), officially supported from 3.14, which…", options: ["Replaces threads with processes", "Makes the GIL faster", "Removes the GIL, letting threads run bytecode in parallel"], answer: 2,
    explain: "It is not free: single-threaded code is somewhat slower, and C extensions must be rebuilt and audited for thread safety." },
  { q: "`await` by itself…", options: ["Runs the coroutine concurrently", "Means 'suspend until this finishes' — concurrency comes from TaskGroup, gather or create_task", "Spawns a thread"], answer: 1,
    explain: "Sequential awaits in a loop are exactly as slow as synchronous calls. This is the most common async mistake in review." },
  { q: "A blocking call inside an async handler…", options: ["Is scheduled on a thread automatically", "Freezes the whole event loop, stalling every other connection", "Raises RuntimeError"], answer: 1,
    explain: "`time.sleep`, `requests.get`, a blocking DB driver, or 500ms of CPU all do it. `asyncio.to_thread` moves it off the loop." },
  { q: "`asyncio.TaskGroup` improves on `gather()` because…", options: ["It is faster", "A failing task cancels its siblings instead of leaving them running", "It returns results in completion order"], answer: 1,
    explain: "gather leaves orphaned work burning quota after one failure; `gather(..., return_exceptions=True)` is right only when partial results are acceptable." },
  { q: "When a TaskGroup child fails, the group raises…", options: ["An ExceptionGroup — so a plain `except ValueError` does not catch it", "asyncio.TimeoutError", "The child's exception unchanged"], answer: 0,
    explain: "You need `except*`. Porting gather() to TaskGroup without converting the handlers silently stops handling errors." },
  { q: "Launching thousands of concurrent tasks without a limit typically fails with…", options: ["Exhausted file descriptors or an overwhelmed downstream — surfacing far from the cause", "A GIL deadlock", "MemoryError immediately"], answer: 0,
    explain: "An `asyncio.Semaphore` bounds concurrency; the symptom otherwise is 'Too many open files' in unrelated code." },
  { q: "`asyncio.run()` should be called…", options: ["Once, at the top-level entry point", "Once per task", "Inside every coroutine"], answer: 0,
    explain: "Calling it from inside a running loop raises. Libraries should expose coroutines and let the application own the loop." },
  { q: "A race condition on a shared counter across threads happens because…", options: ["Integers are immutable", "The GIL is disabled for integers", "`+=` is not atomic — read, add and write can interleave"], answer: 2,
    explain: "The GIL guarantees bytecode atomicity, not statement atomicity. Use a Lock, or an atomic structure like queue.Queue." },
  { q: "A deadlock most commonly arises from…", options: ["Two locks acquired in different orders by different threads", "Too many threads", "Using async"], answer: 0,
    explain: "Impose a global lock ordering, or use a single coarse lock — correctness first, then measure whether it costs anything." },
  { q: "`fork` as a multiprocessing start method is unsafe when the parent has threads because…", options: ["Memory is not copied", "The child inherits locks that may be held by threads that do not exist in it", "fork is slower"], answer: 1,
    explain: "This is why the Linux default changed to `spawn` in 3.14 — the deadlocks were subtle and platform-dependent." },
  { q: "Arguments to a `ProcessPoolExecutor` task must be…", options: ["Immutable", "Small", "Picklable, because they are serialised to the child process"], answer: 2,
    explain: "Lambdas and local functions are not picklable, which is the usual first error when moving from threads to processes." },
  { q: "The right default for many concurrent HTTP calls is…", options: ["asyncio with an async client, or a thread pool", "ProcessPoolExecutor", "A thread per request with no pool"], answer: 0,
    explain: "It is I/O-bound, so processes add serialisation cost and memory for nothing." },
  { q: "`asyncio.timeout()` (3.11+) cancels the block by…", options: ["Raising CancelledError inside the awaited task, which then propagates as TimeoutError", "Setting a flag you must check", "Killing the thread"], answer: 0,
    explain: "Cancellation is cooperative: a task that swallows CancelledError, or never awaits, cannot be cancelled." },
  { q: "Catching `CancelledError` and continuing is dangerous because…", options: ["It breaks cancellation — timeouts and shutdown stop working", "It leaks memory only", "It is a syntax error"], answer: 0,
    explain: "If you must catch it for cleanup, re-raise afterwards." },
  { q: "An unbounded `Queue` between a fast producer and a slow consumer…", options: ["Blocks the producer", "Applies backpressure automatically", "Grows until memory runs out"], answer: 2,
    explain: "`Queue(maxsize=N)` makes the producer wait, which is what backpressure means." },
  { q: "The single most useful question when choosing a concurrency model is…", options: ["How many cores are available", "Is the work I/O-bound or CPU-bound", "Which library is newest"], answer: 1,
    explain: "I/O-bound → async or threads; CPU-bound → processes or a native library. Everything else follows from that." },
  { q: "Diagnosing 'the async service is slow but CPU is idle' should start with…", options: ["Looking for a blocking call on the event loop", "Adding more workers", "Increasing the timeout"], answer: 0,
    explain: "Idle CPU with high latency means something is waiting, and in async that usually means the loop itself is blocked." },
]},
{ title: "Quiz 9 · Testing, Packaging & FastAPI",
  desc: "pytest mechanics, environments and building a production API",
  questions: [
  { q: "pytest discovers tests by…", options: ["An explicit registry file", "A decorator on each test", "Naming convention: test_*.py files, test_ functions, Test* classes"], answer: 2,
    explain: "A test that is not named correctly silently does not run — which is why a suddenly-fast suite is worth investigating." },
  { q: "A pytest fixture provides…", options: ["A mock object only", "Assertions", "Setup, and teardown after its yield, injected by parameter name"], answer: 2,
    explain: "Requesting it by name is dependency injection: the test declares what it needs and pytest builds it." },
  { q: "`scope=\"session\"` on a fixture means it is created…", options: ["Once per test", "Once for the whole run and shared", "Once per module"], answer: 1,
    explain: "Fast, and a source of cross-test coupling if the object carries mutable state." },
  { q: "`conftest.py` exists to…", options: ["Share fixtures across a directory without importing them", "Configure pytest options only", "Register plugins exclusively"], answer: 0,
    explain: "Fixtures defined there are visible to every test below it, with no import." },
  { q: "`@pytest.mark.parametrize` is preferable to a loop inside a test because…", options: ["Each case is a separate test, so all failures are reported with the failing input named", "It supports more types", "It runs faster"], answer: 0,
    explain: "A loop stops at the first failure and tells you nothing about the rest." },
  { q: "`monkeypatch` differs from `unittest.mock.patch` mainly by…", options: ["Being faster", "Being automatically undone at the end of the test", "Working only on classes"], answer: 1,
    explain: "It also handles environment variables and attributes cleanly: `monkeypatch.setenv(...)`." },
  { q: "The main risk of heavy mocking is…", options: ["Tests that pass while the real integration is broken, because the mock encodes an assumption that is wrong", "Mocks cannot be asserted on", "Slow tests"], answer: 0,
    explain: "Mock the boundary you own or the slow external call; do not mock the code under test." },
  { q: "A test that passes alone and fails in the suite usually indicates…", options: ["Insufficient timeout", "Shared state — module-level globals, a session fixture, or leftover data", "A pytest bug"], answer: 1,
    explain: "`pytest -p no:randomly` and running the pair in isolation narrows it quickly." },
  { q: "Testing an async function with pytest requires…", options: ["An async plugin such as pytest-asyncio (or anyio) and a marker", "Converting it to sync", "Nothing extra"], answer: 0,
    explain: "Without it, the coroutine is created and never awaited — and the test passes while asserting nothing." },
  { q: "A virtual environment isolates…", options: ["The Python interpreter version only", "The operating system", "Installed packages per project, so two projects can use different versions"], answer: 2,
    explain: "Installing into the system Python is how you break OS tooling that depends on it." },
  { q: "`pyproject.toml` versus `requirements.txt`:", options: ["requirements.txt is newer", "They are interchangeable", "pyproject declares what you WANT (ranges, metadata, build config); a lock file records exactly what was resolved"], answer: 2,
    explain: "Commit both: the declaration for humans, the lock for reproducibility." },
  { q: "A lock file matters because…", options: ["It pins the full transitive dependency graph, so CI and production install identical versions", "It encrypts credentials", "It speeds up imports"], answer: 0,
    explain: "Without it, a transitive dependency releasing a breaking version turns a green build red with no change from you." },
  { q: "`__init__.py` in a package directory…", options: ["Contains only imports", "Is mandatory in Python 3", "Marks a regular package and runs on import; namespace packages work without it"], answer: 2,
    explain: "Heavy work in it makes every import of the package slow, and can create import cycles." },
  { q: "A circular import usually indicates…", options: ["A missing __init__.py", "Too many packages", "Two modules with entangled responsibilities — the fix is structural, not a deferred import"], answer: 2,
    explain: "Moving the import inside a function hides it; extracting the shared piece into a third module fixes it." },
  { q: "In FastAPI, request bodies are validated by…", options: ["Pydantic models derived from the type hints — parsing and validation are the same step", "A middleware you write", "Manual isinstance checks"], answer: 0,
    explain: "This is where runtime validation and type hints finally meet: the annotation is the schema." },
  { q: "FastAPI's `Depends` provides…", options: ["Database migrations", "Background scheduling", "Dependency injection with caching per request, and override points for tests"], answer: 2,
    explain: "`app.dependency_overrides` is what makes route tests fast and hermetic." },
  { q: "Declaring an endpoint `async def` when it calls a blocking DB driver…", options: ["Raises at startup", "Blocks the event loop — a plain `def` endpoint would have been safer, since FastAPI runs it in a threadpool", "Is optimal"], answer: 1,
    explain: "FastAPI runs sync endpoints in a worker thread. `async def` plus blocking code is the worst combination." },
  { q: "Returning a Pydantic model with `response_model` set gives you…", options: ["Output filtering and documentation — fields not in the model are not leaked", "Automatic caching", "Faster serialisation only"], answer: 0,
    explain: "It is a security control as much as documentation: it stops a password hash leaking because someone added a column." },
  { q: "The right place for a slow, non-critical side effect (sending an email) in a request handler is…", options: ["A thread you never join", "Inline, before returning", "A background task or a queue, so the response is not held up"], answer: 2,
    explain: "BackgroundTasks covers the simple case; anything that must not be lost belongs in a real queue with retries." },
  { q: "Client-side or schema validation in an API is…", options: ["Sufficient security", "Only needed in production", "UX and documentation — the server must still validate and authorise every request"], answer: 2,
    explain: "Validation proves the shape is right; authorisation proves this caller may do it. They are different questions." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "Cross-topic questions at interview difficulty",
  questions: [
  { q: "A function's default `[]` accumulating values across calls is explained by…", options: ["Reference counting", "Late binding of closures", "Defaults being evaluated once at definition time and stored on the function object"], answer: 2,
    explain: "Visible in `f.__defaults__`. The closure late-binding trap is a different bug with a similar flavour." },
  { q: "`[lambda: i for i in range(3)]` all returning 2 is explained by…", options: ["Generator laziness", "Defaults evaluated once", "Closures capturing the variable rather than its value"], answer: 2,
    explain: "Bind eagerly with `lambda i=i: i` — which uses the default-evaluation rule to fix the closure rule." },
  { q: "A UI shows stale data after a list was 'updated in place'. In Python terms the equivalent bug is…", options: ["A race condition", "Two names bound to the same object, so one caller mutates another's data unknowingly", "A memory leak"], answer: 1,
    explain: "Passing a mutable argument and mutating it is the most common source of action-at-a-distance in Python code." },
  { q: "`sorted(data, key=lambda r: r.name)` is stable, so sorting by name then by department yields…", options: ["Names ordered within each department, if you sort by name FIRST then department", "Only the last sort's effect", "An arbitrary order"], answer: 0,
    explain: "Sort by the secondary key first, then the primary — stability preserves the earlier order within ties." },
  { q: "A service is slow, CPU sits at 20%, and the code is async. The first thing to check is…", options: ["A blocking call on the event loop", "The number of workers", "The garbage collector"], answer: 0,
    explain: "Idle CPU with high latency means waiting, and in an async service the loop itself is the usual thing that is stuck." },
  { q: "Converting `gather()` to `TaskGroup` and leaving `except ValueError:` in place results in…", options: ["Identical behaviour", "A syntax error", "Errors escaping unhandled, because the group raises an ExceptionGroup"], answer: 2,
    explain: "It compiles and runs, which is what makes it dangerous. `except*` is required." },
  { q: "A dict lookup by a tuple key stops finding entries after the tuple's contents were changed. The cause is…", options: ["Dict resizing", "The tuple was really a list, so mutation changed its hash bucket", "Hash randomisation between runs"], answer: 1,
    explain: "A tuple containing a list is unhashable, so the key must have been a mutable object with a custom __hash__ — or a list-backed structure." },
  { q: "`x = my_list.sort()` binding None happens because…", options: ["sort failed", "sort mutates in place and returns None by convention", "Lists are immutable"], answer: 1,
    explain: "The convention is deliberate: methods that mutate return None so you cannot chain them and pretend they are pure." },
  { q: "A CLI reads a file fine on Linux and raises UnicodeDecodeError on a colleague's Windows machine because…", options: ["`open()` used the platform default encoding rather than an explicit one", "The file is corrupt", "Windows cannot read UTF-8"], answer: 0,
    explain: "Always pass `encoding=\"utf-8\"`. The bug is in the code, not the file or the platform." },
  { q: "A `@lru_cache` on an instance method causes memory to grow forever because…", options: ["`self` is part of the key, so every instance is retained by the cache", "The cache never evicts", "Methods cannot be cached"], answer: 0,
    explain: "`cached_property` for per-instance caching; module-level functions for shared caching." },
  { q: "Test suite runtime drops 80% overnight and nobody optimised anything. The most likely cause is…", options: ["Better hardware", "Caching", "Tests silently stopped being collected — a renamed file or a broken import in conftest"], answer: 2,
    explain: "Check the collected count, not just the wall clock. pytest reports it on every run." },
  { q: "A dataclass with `field(default_factory=list)` rather than `= []` is required because…", options: ["The dataclass machinery raises on a mutable default", "It is faster", "Lists cannot be annotated"], answer: 0,
    explain: "One of the few places Python actively prevents the classic bug rather than documenting it." },
  { q: "Type checking passes, and production still raises `AttributeError: 'NoneType'`. The most likely reason is…", options: ["The checker is broken", "Optional was used incorrectly", "Data crossed a runtime boundary — JSON, a DB row, an untyped library — where hints are not enforced"], answer: 2,
    explain: "Hints are static. Boundaries need runtime validation, which is exactly what pydantic is for." },
  { q: "Two threads incrementing a shared counter lose updates because…", options: ["Integers are cached", "The GIL was released", "`+=` is read-modify-write and can interleave between bytecodes"], answer: 2,
    explain: "The GIL makes individual bytecodes atomic, not statements. A Lock, or a Queue, fixes it." },
  { q: "A generator pipeline yields nothing on the second pass because…", options: ["The GIL blocked it", "It raised silently", "Generators are single-pass and were already exhausted"], answer: 2,
    explain: "Materialise with `list()` if two passes are needed, or build a fresh generator each time." },
  { q: "A script works when run directly and fails with ImportError when imported. The usual cause is…", options: ["Relying on the script's directory being on sys.path — a package-relative import problem", "A circular import", "A missing __init__.py"], answer: 0,
    explain: "`python -m package.module` and a proper package layout fix it; sys.path manipulation hides it." },
  { q: "An API endpoint returns a user object including `password_hash` after a schema change. The control that would have prevented it is…", options: ["Input validation", "A rate limiter", "An explicit `response_model` filtering the output"], answer: 2,
    explain: "Output shape is a contract, and it is where accidental leaks happen when the model gains a field." },
  { q: "Deep recursion raising RecursionError is best fixed by…", options: ["Raising the recursion limit", "Adding tail-call syntax", "Rewriting iteratively, or using an explicit stack"], answer: 2,
    explain: "CPython has no tail-call optimisation, and raising the limit trades a clean exception for a hard crash." },
  { q: "`if user_count:` skipping the branch when the count is legitimately 0 is an instance of…", options: ["Truthiness applied where an explicit comparison was meant", "A type error", "Operator precedence"], answer: 0,
    explain: "`if user_count > 0:` or `if user_count is not None:` — the same class of bug as `{items.length && …}` in JSX." },
  { q: "The most useful first question when a Python service is 'slow' is…", options: ["Which Python version is it", "How many cores does it have", "Where is the time actually going — profile before changing anything"], answer: 2,
    explain: "cProfile or py-spy in under a minute beats an afternoon of plausible guesses, and the answer is regularly something nobody suspected." },
]},
);
