// ASP.NET Core quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · AuthN/AuthZ",
  desc: "JWT bearer auth, role vs policy authorization, OAuth2 vs OIDC, Identity",
  questions: [
  { q: "A JWT is…", options: ["A server-side session reference", "A self-contained, signed claim carrying its own data", "A database record"], answer: 1,
    explain: "No server-side lookup needed to validate." },
  { q: "Validating a JWT typically requires…", options: ["A database round-trip", "Checking the signature, expiry, issuer, and audience — computationally", "Nothing at all"], answer: 1,
    explain: "This statelessness is why JWTs scale well for APIs." },
  { q: "UseAuthentication() populates…", options: ["The response body", "HttpContext.User from a valid token's claims", "The database"], answer: 1,
    explain: "WHO is making the request." },
  { q: "[Authorize(Roles = \"Admin\")] is an example of…", options: ["Policy-based authorization only", "Role-based authorization (a simple case of policy-based)", "Authentication"], answer: 1,
    explain: "Roles are a built-in special case of policies." },
  { q: "Policy-based authorization can…", options: ["Only check one claim", "Combine multiple claims, custom logic, and injected services", "Never use custom logic"], answer: 1,
    explain: "More general and flexible than roles alone." },
  { q: "A custom IAuthorizationHandler can…", options: ["Not use DI", "Have services injected (e.g., for resource-based checks)", "Only check roles"], answer: 1,
    explain: "Enables DB-backed authorization logic." },
  { q: "OAuth 2.0 was designed primarily for…", options: ["Authentication", "Delegated AUTHORIZATION (scoped access on someone's behalf)", "Password storage"], answer: 1,
    explain: "Not originally an identity/login protocol." },
  { q: "OpenID Connect (OIDC) is…", options: ["Unrelated to OAuth2", "OAuth2 + a standardized IDENTITY layer (ID token)", "A replacement for JWTs"], answer: 1,
    explain: "Adds authentication on top of OAuth2's authorization." },
  { q: "Using a raw OAuth2 access token to 'prove' identity is…", options: ["The correct standard approach", "A historical misuse — OIDC's ID token is the correct tool", "Required by OAuth2"], answer: 1,
    explain: "Access tokens weren't designed to guarantee identity claims." },
  { q: "\"Sign in with Google\" buttons are powered by…", options: ["Raw OAuth2 only", "OIDC (OAuth2 + the identity layer)", "SignalR"], answer: 1,
    explain: "The standard delegated-login protocol." },
  { q: "ASP.NET Core Identity provides…", options: ["Only routing", "Password hashing, lockout, 2FA, and user management out of the box", "Caching"], answer: 1,
    explain: "For self-hosted user stores." },
  { q: "Storing passwords in plaintext is…", options: ["Acceptable for internal apps", "Never acceptable — use vetted hashing (e.g., ASP.NET Core Identity)", "Required by some frameworks"], answer: 1,
    explain: "Catastrophic if the database leaks." },
  { q: "Overly long-lived JWT access tokens are risky because…", options: ["They expire too fast", "A leaked token stays dangerous for a long time", "They can't be validated"], answer: 1,
    explain: "Prefer short-lived tokens + refresh tokens." },
  { q: "UseAuthentication() and UseAuthorization() ordering…", options: ["Doesn't matter", "Authentication MUST come first", "Authorization must come first"], answer: 1,
    explain: "Reiterated from the middleware pipeline lesson." },
  { q: "A [Authorize] attribute with no Roles/Policy specified requires…", options: ["Admin role", "ANY authenticated user", "Nothing — allows anonymous access"], answer: 1,
    explain: "Basic authentication requirement." },
  { q: "Inconsistently applying [Authorize] across endpoints risks…", options: ["Nothing", "Accidentally unprotected endpoints", "Faster performance"], answer: 1,
    explain: "Consider a deny-by-default global fallback policy." },
  { q: "TokenValidationParameters.ValidateLifetime ensures…", options: ["Tokens never expire", "EXPIRED tokens are rejected", "Faster validation"], answer: 1,
    explain: "A critical security check." },
  { q: "The IssuerSigningKey is used to…", options: ["Encrypt the payload", "Verify the token's SIGNATURE wasn't tampered with", "Store user data"], answer: 1,
    explain: "Cryptographic integrity check." },
  { q: "Resource-based authorization (checking DB ownership of a resource) is best implemented via…", options: ["Simple role checks", "A custom IAuthorizationHandler with injected services", "Data annotations"], answer: 1,
    explain: "Needs DI access to check ownership." },
  { q: "The general theme of AuthN/AuthZ in ASP.NET Core is…", options: ["One combined concept", "Two DISTINCT concerns (who vs what) handled by separate, ordered middleware", "Handled entirely by the database"], answer: 1,
    explain: "WHO (authentication) then WHAT (authorization)." }
]},
{ title: "Quiz 7 · Caching & Background Services",
  desc: "IMemoryCache vs IDistributedCache, output caching, BackgroundService scoping",
  questions: [
  { q: "IMemoryCache stores data…", options: ["In an external Redis store", "In the CURRENT PROCESS's memory", "In the database"], answer: 1,
    explain: "Fast but per-instance." },
  { q: "IDistributedCache (e.g., Redis) stores data…", options: ["Per-instance only", "In an EXTERNAL store, shared across all app instances", "Only in memory"], answer: 1,
    explain: "Consistent across horizontally-scaled replicas." },
  { q: "In a multi-instance deployment, IMemoryCache…", options: ["Is automatically synced", "Can be INCONSISTENT across instances", "Is always safe to use"], answer: 1,
    explain: "Each replica has its own separate cache." },
  { q: "GetOrCreateAsync is the standard pattern for…", options: ["Deleting cache entries", "'Get it, or compute+store it if missing'", "Clearing all caches"], answer: 1,
    explain: "The common caching idiom." },
  { q: "Output caching caches…", options: ["A single value", "The ENTIRE HTTP response for repeat requests", "Only database queries"], answer: 1,
    explain: "Even cheaper than app-level caching on a hit." },
  { q: "On an output cache HIT, the endpoint handler…", options: ["Still runs fully", "Does NOT run at all — cached bytes are served directly", "Runs partially"], answer: 1,
    explain: "Skips handler execution entirely." },
  { q: "A BackgroundService (via AddHostedService) is effectively…", options: ["Scoped", "A SINGLETON running for the app's whole lifetime", "Transient"], answer: 1,
    explain: "Instantiated once at startup." },
  { q: "Injecting DbContext (Scoped) directly into a BackgroundService's constructor causes…", options: ["No issue", "A captive dependency bug", "Faster background jobs"], answer: 1,
    explain: "The DbContext gets permanently captured/stale." },
  { q: "The correct pattern for a BackgroundService needing Scoped services is…", options: ["Inject them directly", "Inject IServiceScopeFactory and create a scope per unit of work", "Avoid Scoped services entirely"], answer: 1,
    explain: "A fresh scope on each iteration." },
  { q: "A BackgroundService loop should generally include…", options: ["No delay at all", "Task.Delay between iterations and CancellationToken handling", "Only synchronous code"], answer: 1,
    explain: "Avoid pegging CPU; support graceful shutdown." },
  { q: "Caching data that changes frequently with a long expiration risks…", options: ["Faster responses with no downside", "Serving STALE data to users", "Nothing significant"], answer: 1,
    explain: "Match cache duration to actual data volatility." },
  { q: "A cache key for user-specific sensitive data should…", options: ["Be shared across all users", "Include the user's identity to avoid data leakage", "Never include user info"], answer: 1,
    explain: "Prevents cross-user data leakage via a shared key." },
  { q: "The relationship between IMemoryCache/IDistributedCache and SignalR's backplane problem is…", options: ["Unrelated", "The SAME underlying issue — in-memory per-instance state breaks at scale", "Only a coincidence"], answer: 1,
    explain: "Both need externalized shared state (Redis) to scale horizontally." },
  { q: "AddStackExchangeRedisCache configures…", options: ["In-memory caching", "IDistributedCache backed by Redis", "SignalR"], answer: 1,
    explain: "The standard distributed cache provider." },
  { q: "DistributedCacheEntryOptions.SlidingExpiration…", options: ["Deletes entries immediately", "Evicts an entry after a period of no access", "Is for IMemoryCache only"], answer: 1,
    explain: "Common expiration strategy for both cache types." },
  { q: "A BackgroundService is registered with…", options: ["AddScoped", "AddHostedService<T>()", "AddTransient"], answer: 1,
    explain: "Hosted, long-running by the framework." },
  { q: "No cache invalidation strategy on writes results in…", options: ["Always-fresh data", "Users seeing outdated data after an update", "Faster writes"], answer: 1,
    explain: "Explicitly invalidate/update cached entries on writes." },
  { q: ".CacheOutput(policy => policy.Expire(...)) is applied to…", options: ["A service", "A specific endpoint/route for output caching", "A middleware globally always"], answer: 1,
    explain: "Declarative, per-endpoint output cache policy." },
  { q: "Why is IMemoryCache still useful despite its limitation?", options: ["It's never useful", "Fine for single-instance deployments or data where slight inconsistency is tolerable", "It's always better than Redis"], answer: 1,
    explain: "The right tool depends on deployment topology." },
  { q: "The captive-dependency pattern applies to BackgroundService because…", options: ["It's a coincidence", "BackgroundService IS effectively a Singleton per the .NET DI lesson's rule", "BackgroundServices are Scoped"], answer: 1,
    explain: "Concrete real-world application of that DI rule." }
]},
{ title: "Quiz 8 · SignalR (Realtime)",
  desc: "Transport negotiation, Hubs, client targeting, the backplane problem",
  questions: [
  { q: "SignalR negotiates between transports including…", options: ["Only WebSockets", "WebSockets, Server-Sent Events, and Long Polling", "Only HTTP polling"], answer: 1,
    explain: "Falls back gracefully when WebSockets aren't available." },
  { q: "Your Hub/client code when the transport changes…", options: ["Must be rewritten per transport", "Stays IDENTICAL regardless of the negotiated transport", "Only works with WebSockets"], answer: 1,
    explain: "SignalR abstracts the transport away." },
  { q: "A Hub is…", options: ["A client-side library", "The server-side RPC endpoint class", "A caching mechanism"], answer: 1,
    explain: "Clients invoke Hub methods." },
  { q: "SignalR's RPC model differs from HTTP request/response because…", options: ["Only the client can initiate calls", "The SERVER can also invoke methods on the CLIENT unprompted", "It's identical to HTTP"], answer: 1,
    explain: "RPC in BOTH directions over one persistent connection." },
  { q: "Clients.All.SendAsync(...) sends to…", options: ["Only the caller", "EVERY connected client", "No one"], answer: 1,
    explain: "A broadcast to all connections." },
  { q: "Clients.Caller sends to…", options: ["Everyone", "ONLY the client that invoked this Hub method", "A random client"], answer: 1,
    explain: "Reply just to the sender." },
  { q: "Clients.Group(\"lobby\") sends to…", options: ["Every connected client", "All connections added to the 'lobby' group", "Only the caller"], answer: 1,
    explain: "Targeted subset broadcasting." },
  { q: "Groups.AddToGroupAsync is typically called…", options: ["Never", "In OnConnectedAsync or another Hub method to add a connection to a group", "Only from JavaScript"], answer: 1,
    explain: "Server-side group management." },
  { q: "A single SignalR server instance tracks connections/groups…", options: ["In an external database always", "IN MEMORY, per that instance", "Nowhere"], answer: 1,
    explain: "The root of the scaling problem." },
  { q: "With multiple SignalR server instances and NO backplane…", options: ["All messages reach all clients correctly", "A message sent from instance A won't reach clients on instance B", "Nothing changes"], answer: 1,
    explain: "The classic multi-instance breakage." },
  { q: "A SignalR backplane is typically implemented with…", options: ["A local file", "Redis pub/sub shared across all instances", "In-memory only"], answer: 1,
    explain: "AddStackExchangeRedisBackplane." },
  { q: "The SignalR backplane problem is conceptually identical to…", options: ["Nothing else in this track", "The IMemoryCache vs IDistributedCache problem", "JWT validation"], answer: 1,
    explain: "Both are in-memory per-instance state breaking at scale." },
  { q: "Deploying SignalR behind a Kubernetes HPA with multiple replicas and no backplane…", options: ["Works perfectly", "Silently breaks cross-instance broadcasting", "Improves reliability"], answer: 1,
    explain: "Ties directly to the K8s autoscaling lesson's scaling story." },
  { q: "connection.on(\"ReceiveMessage\", handler) on the client…", options: ["Sends a message to the server", "Registers a handler for messages the SERVER pushes", "Closes the connection"], answer: 1,
    explain: "The client-side RPC receiving end." },
  { q: "connection.invoke(\"SendMessage\", ...) on the client…", options: ["Registers a handler", "Calls a method on the server-side Hub", "Disconnects"], answer: 1,
    explain: "Client-to-server RPC call." },
  { q: "Heavy business logic directly in Hub methods is…", options: ["Best practice", "An anti-pattern — delegate to injected services, same as controllers", "Required by SignalR"], answer: 1,
    explain: "Keep Hubs thin, same principle as controllers." },
  { q: "Clients.Others sends to…", options: ["Everyone including the caller", "Everyone EXCEPT the caller", "Only the caller"], answer: 1,
    explain: "Useful for 'someone else did X' notifications." },
  { q: "Not handling client reconnection can result in…", options: ["Better UX", "Silent disconnects going unnoticed by users", "No effect"], answer: 1,
    explain: "Use SignalR's automatic reconnect features." },
  { q: "SignalR is best suited for…", options: ["Simple CRUD APIs", "Real-time, server-push scenarios (chat, live notifications, collaboration)", "Batch file processing"], answer: 1,
    explain: "The right tool for unprompted server-to-client updates." },
  { q: "Clients.User(userId) targets…", options: ["A random client", "All connections belonging to one authenticated user across devices/tabs", "Only Group members"], answer: 1,
    explain: "Cross-device targeting by identity." }
]},
{ title: "Quiz 9 · Clean Architecture, CQRS & Production Readiness",
  desc: "Dependency rule, CQRS/MediatR, API versioning, health checks, OpenTelemetry",
  questions: [
  { q: "Clean Architecture's dependency rule states dependencies point…", options: ["Outward only", "INWARD only — toward Domain", "In no particular direction"], answer: 1,
    explain: "Domain depends on nothing." },
  { q: "The Domain layer should…", options: ["Reference EF Core directly", "Depend on NOTHING — no framework references at all", "Contain controllers"], answer: 1,
    explain: "Pure business rules, framework-agnostic." },
  { q: "Infrastructure implements interfaces…", options: ["It defines itself", "DEFINED in the Application/Domain layers", "From ASP.NET Core only"], answer: 1,
    explain: "Dependency inversion at the architecture level." },
  { q: "The payoff of Clean Architecture's dependency rule is…", options: ["Faster builds only", "Business logic is framework-agnostic, testable, and technology-swappable", "Less code overall"], answer: 1,
    explain: "Swap EF Core/SQL Server without touching business rules." },
  { q: "CQRS stands for…", options: ["Central Query Resource System", "Command Query Responsibility Segregation", "Cached Query Response Store"], answer: 1,
    explain: "Separates reads from writes as distinct code paths." },
  { q: "CQRS commands typically…", options: ["Just read data", "Change state and enforce business rules", "Never touch the database"], answer: 1,
    explain: "Writes with validation/invariants." },
  { q: "CQRS queries typically…", options: ["Enforce business invariants", "Read/shape data, often with lean DTOs and no tracking", "Modify state"], answer: 1,
    explain: "Read-only, optimized for display." },
  { q: "MediatR is commonly used to…", options: ["Replace DI entirely", "Decouple 'sending a request' from 'which handler processes it'", "Handle authentication"], answer: 1,
    explain: "Similar decoupling spirit to DI itself." },
  { q: "CQRS should be adopted…", options: ["For every app by default", "When reads/writes have genuinely different needs — not as a default", "Only for read-only apps"], answer: 1,
    explain: "Avoid unnecessary ceremony for simple CRUD." },
  { q: "A breaking API change without versioning…", options: ["Has no impact", "Breaks every client still calling the old contract", "Only affects new clients"], answer: 1,
    explain: "The same expand/contract problem, applied to APIs." },
  { q: "URL segment versioning (/api/v2/orders) is favored because it's…", options: ["Hidden from clients", "Explicit, cacheable, and unambiguous", "The only valid strategy"], answer: 1,
    explain: "The most common approach for public APIs." },
  { q: "Maintaining every API version indefinitely is…", options: ["Ideal", "A growing maintenance burden — deprecate on a communicated timeline", "Free"], answer: 1,
    explain: "Sunset old versions deliberately." },
  { q: "A liveness probe should check…", options: ["Full dependency health (DB, cache, APIs)", "Almost NOTHING — just whether the process is alive", "Nothing at all, ever"], answer: 1,
    explain: "Avoid cascading restarts from external outages." },
  { q: "A readiness probe should check…", options: ["Nothing", "REAL dependencies (DB, cache, critical APIs)", "Only the process's existence"], answer: 1,
    explain: "Determines if the Pod should receive traffic." },
  { q: "A failing readiness check causes Kubernetes to…", options: ["Restart the Pod", "Remove the Pod from Service endpoints WITHOUT restarting it", "Delete the Pod permanently"], answer: 1,
    explain: "The right response to an external dependency outage." },
  { q: "Structured logging (named placeholders) vs string interpolation…", options: ["Are functionally identical in production", "Keeps fields SEARCHABLE/FILTERABLE in log aggregators", "Is slower and pointless"], answer: 1,
    explain: "Structure enables precise querying at scale." },
  { q: "OpenTelemetry's distributed tracing helps by…", options: ["Replacing logging entirely", "Correlating one request's path across MULTIPLE microservices into one trace", "Only tracking a single service"], answer: 1,
    explain: "Essential for diagnosing latency/errors in microservices." },
  { q: "AddAspNetCoreInstrumentation/AddHttpClientInstrumentation/AddEntityFrameworkCoreInstrumentation…", options: ["Require manual tracing code everywhere", "Auto-instrument incoming requests, outgoing calls, and DB queries", "Only work with SignalR"], answer: 1,
    explain: "Automatic OpenTelemetry instrumentation." },
  { q: "Graceful shutdown (handling SIGTERM via IHostApplicationLifetime) matters because…", options: ["It's optional and rarely relevant", "Kubernetes sends SIGTERM before killing a Pod — in-flight requests should drain first", "It speeds up startup"], answer: 1,
    explain: "Ties directly to K8s rolling updates/Pod eviction behavior." },
  { q: "Containerizing an ASP.NET Core app for production should use…", options: ["The full SDK image shipped to prod", "A multi-stage build (SDK to build, runtime-only to ship), running as non-root", "No containerization at all"], answer: 1,
    explain: "Directly applies the Docker optimization and security lessons." }
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review across the whole ASP.NET Core track",
  questions: [
  { q: "Service registrations must happen…", options: ["After Build()", "BEFORE builder.Build()", "Anytime, order doesn't matter"], answer: 1,
    explain: "The DI container is finalized at Build()." },
  { q: "A complex type parameter in a Minimal API defaults to binding from…", options: ["The route", "The request BODY", "Headers"], answer: 1,
    explain: "The default inference rule." },
  { q: "[ApiController] gives you automatic…", options: ["Caching", "400 responses on invalid model state", "Authentication"], answer: 1,
    explain: "Short-circuits before the action runs." },
  { q: "DbContext should be registered as…", options: ["Singleton", "Scoped", "Transient"], answer: 1,
    explain: "One per HTTP request; not thread-safe." },
  { q: "Injecting a Scoped service into a Singleton is called…", options: ["Best practice", "A captive dependency", "Dependency inversion"], answer: 1,
    explain: "The classic DI lifetime bug, recurring across this track." },
  { q: "A global exception handler is preferred over scattered try/catch because…", options: ["It's slower", "It centralizes consistent error shapes and avoids leaking internals", "It replaces all logging"], answer: 1,
    explain: "One place, consistent format." },
  { q: "The middleware pipeline is structurally…", options: ["A flat list", "A NESTED chain — each middleware wraps the rest", "Random order"], answer: 1,
    explain: "Code before/after next() runs in/reverse-out order." },
  { q: "UseAuthentication() must run…", options: ["After UseAuthorization()", "BEFORE UseAuthorization()", "It doesn't matter"], answer: 1,
    explain: "Need identity established before checking permissions." },
  { q: "A JWT is validated…", options: ["Via a database lookup", "Computationally (signature, expiry, issuer/audience) — stateless", "By SignalR"], answer: 1,
    explain: "Why JWTs scale well for APIs." },
  { q: "OIDC adds to OAuth2…", options: ["Nothing new", "A standardized IDENTITY layer (ID token) for authentication", "Caching"], answer: 1,
    explain: "OAuth2 alone handles delegated authorization, not identity." },
  { q: "IMemoryCache across multiple app instances is…", options: ["Automatically synced", "Inconsistent — each instance has its own separate cache", "Always safe"], answer: 1,
    explain: "Use IDistributedCache (Redis) for multi-instance consistency." },
  { q: "A BackgroundService should access Scoped services via…", options: ["Direct constructor injection", "IServiceScopeFactory, creating a scope per unit of work", "Static fields"], answer: 1,
    explain: "It's effectively a Singleton — avoids captive dependencies." },
  { q: "SignalR requires a backplane (Redis) when…", options: ["Running a single instance", "Scaling to MULTIPLE server instances", "Never"], answer: 1,
    explain: "In-memory connection tracking is per-instance." },
  { q: "Clean Architecture's Domain layer should…", options: ["Reference EF Core and ASP.NET Core", "Depend on NOTHING — pure business rules", "Contain controllers"], answer: 1,
    explain: "Dependency inversion — Infrastructure implements Domain's interfaces." },
  { q: "CQRS is worth adopting when…", options: ["Every project, by default", "Reads and writes have genuinely different needs", "Never — always avoid it"], answer: 1,
    explain: "Not a default pattern for simple CRUD." },
  { q: "API versioning solves the same underlying problem as…", options: ["Caching", "Database migration expand/contract (the CI/CD lesson)", "Middleware ordering"], answer: 1,
    explain: "Old and new contracts coexisting during a transition." },
  { q: "A liveness probe checking database connectivity risks…", options: ["Nothing", "Cascading restarts of healthy Pods during a DB outage", "Faster recovery"], answer: 1,
    explain: "Dependency checks belong in readiness, not liveness." },
  { q: "Structured logging matters because…", options: ["It looks nicer", "Fields stay searchable/filterable in production log aggregators", "It's required by C#"], answer: 1,
    explain: "String interpolation flattens data into an opaque blob." },
  { q: "OpenTelemetry propagates trace context…", options: ["Only within one service", "ACROSS service boundaries in a microservices architecture", "Only for database calls"], answer: 1,
    explain: "Correlates one request's full path across multiple services." },
  { q: "The overarching theme connecting DI lifetimes, caching, SignalR, and health checks across this track is…", options: ["They're unrelated topics", "Correctly reasoning about state/scope (per-request, per-instance, shared) at production scale", "Avoiding ASP.NET Core features"], answer: 1,
    explain: "The recurring lesson: know what's Scoped/Singleton, per-instance vs shared, and design accordingly." }
]}
);
