// ASP.NET Core quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Minimal APIs & Routing",
  desc: "builder/app pattern, endpoint mapping, parameter binding, route constraints",
  questions: [
  { q: "WebApplication.CreateBuilder(args) begins…", options: ["The pipeline configuration phase", "The service registration/configuration phase", "Request handling"], answer: 1,
    explain: "Phase 1: register services before Build()." },
  { q: "Service registrations (builder.Services.Add...) must happen…", options: ["After Build()", "BEFORE builder.Build()", "Anytime"], answer: 1,
    explain: "The DI container is finalized at Build()." },
  { q: "app.MapGet/MapPost define…", options: ["Middleware", "Endpoints mapped to routes", "DbContext options"], answer: 1,
    explain: "The core of Minimal API routing." },
  { q: "A parameter named to match a route segment like {id} binds from…", options: ["The query string", "The route", "The request body"], answer: 1,
    explain: "Route-segment name matching." },
  { q: "A simple type NOT matching a route segment binds from…", options: ["The body", "The query string", "Headers only"], answer: 1,
    explain: "e.g., string q in ?q=hello." },
  { q: "A complex type parameter (a class/record) defaults to binding from…", options: ["The route", "The request BODY (JSON)", "Nothing"], answer: 1,
    explain: "The default for POST/PUT payloads." },
  { q: "A parameter type registered in DI (like IOrderService) is…", options: ["Bound from the query", "Resolved as an injected SERVICE, not client data", "Ignored"], answer: 1,
    explain: "Same binding rules distinguish services from client data." },
  { q: "Results.Ok(data) returns HTTP status…", options: ["404", "200", "201"], answer: 1,
    explain: "Success with a JSON body." },
  { q: "Results.Created(uri, data) returns HTTP status…", options: ["200", "201 with a Location header", "204"], answer: 1,
    explain: "For successful resource creation." },
  { q: "Results.NoContent() is typically used after a…", options: ["GET", "successful DELETE with no body to return", "failed request"], answer: 1,
    explain: "204 — success, nothing to return." },
  { q: "{id:int} in a route template is a…", options: ["A validation rule", "A route CONSTRAINT (shape filter + type conversion)", "A middleware"], answer: 1,
    explain: "Filters routing, not business validation." },
  { q: "A request that fails a route constraint…", options: ["Reaches the handler anyway", "Doesn't match that route (may 404)", "Throws a 500"], answer: 1,
    explain: "Constraints operate at routing time." },
  { q: "{*path} in a route template is…", options: ["A single segment", "A catch-all matching multiple segments including slashes", "Invalid syntax"], answer: 1,
    explain: "Useful for file paths." },
  { q: "MapGroup(\"/users\") is used to…", options: ["Register a service", "Share a prefix and config across related endpoints", "Bind a parameter"], answer: 1,
    explain: "Reduces repetition across related endpoints." },
  { q: "Applying .RequireAuthorization() on a MapGroup…", options: ["Only affects one endpoint", "Applies to all endpoints registered within that group", "Does nothing"], answer: 1,
    explain: "Shared config at the group level." },
  { q: "[FromQuery]/[FromBody]/[FromRoute] attributes are used to…", options: ["Register services", "Explicitly override binding inference when ambiguous", "Define routes"], answer: 1,
    explain: "Escape hatches for the default inference rules." },
  { q: "Two routes that can BOTH match the same request cause…", options: ["The first one always wins silently", "An AmbiguousMatchException", "A compile error"], answer: 1,
    explain: "A request-time routing failure." },
  { q: "A record like ProductFilter(string? Category, int Page = 1) as a GET parameter…", options: ["Can't bind from query string", "Binds ALL its properties from the query string automatically", "Only binds Category"], answer: 1,
    explain: "Complex query-parameter binding without manual parsing." },
  { q: "Minimal APIs and Controllers…", options: ["Are entirely separate frameworks", "Run on the SAME underlying pipeline/DI/config", "Cannot be mixed in one app"], answer: 1,
    explain: "A structural/style choice, not a different framework." },
  { q: "app.Run() …", options: ["Registers services", "Starts the Kestrel server and begins listening for requests", "Builds the DI container"], answer: 1,
    explain: "The final step after builder → app configuration." }
]},
{ title: "Quiz 2 · Dependency Injection & Configuration",
  desc: "Service lifetimes in ASP.NET Core, config layering, the Options pattern",
  questions: [
  { q: "Configuration sources are layered such that…", options: ["Earlier sources always win", "LATER sources override earlier ones", "Only one source is ever used"], answer: 1,
    explain: "appsettings.json → env-specific JSON → env vars → CLI args." },
  { q: "appsettings.{Environment}.json is used for…", options: ["Secrets only", "Environment-specific config overrides", "Nothing in modern apps"], answer: 1,
    explain: "e.g., appsettings.Development.json." },
  { q: "Environment variables typically inject…", options: ["Only UI settings", "Secrets/production config, per the Docker env-secrets principle", "Nothing useful"], answer: 1,
    explain: "One image, config from the environment." },
  { q: "Nested config keys in environment variables use…", options: ["A colon", "A DOUBLE UNDERSCORE (__)", "A dot"], answer: 1,
    explain: "e.g., Smtp__Host." },
  { q: "The Options pattern binds a config section to…", options: ["A raw string", "A strongly-typed POCO class", "A database table"], answer: 1,
    explain: "Injectable, refactor-safe configuration." },
  { q: "IOptions<T> is registered as…", options: ["Scoped", "Singleton — computed once at startup", "Transient"], answer: 1,
    explain: "Never changes at runtime." },
  { q: "IOptionsSnapshot<T> is registered as…", options: ["Singleton", "Scoped — re-read per request", "Transient"], answer: 1,
    explain: "Fresh values per request if the source changed." },
  { q: "IOptionsMonitor<T> provides…", options: ["No change tracking", "Live change notifications via .OnChange()", "Only startup values"], answer: 1,
    explain: "For long-lived services reacting to config changes." },
  { q: "IOptionsMonitor<T> is best for…", options: ["Per-request scoped work", "Long-lived services (e.g., background workers)", "Never used in practice"], answer: 1,
    explain: "Singleton with live updates." },
  { q: "Committing real secrets in appsettings.json is…", options: ["Best practice", "A leak risk — use env vars/secrets managers", "Required"], answer: 1,
    explain: "Never commit real credentials." },
  { q: "app.Environment.IsDevelopment() is typically used to…", options: ["Register services", "Gate dev-only middleware like Swagger/detailed errors", "Bind routes"], answer: 1,
    explain: "Different behavior per ASPNETCORE_ENVIRONMENT." },
  { q: "Reading raw IConfiguration[\"Smtp:Host\"] strings everywhere is…", options: ["Best practice", "Error-prone (magic strings) — the Options pattern is preferred", "Faster than Options"], answer: 1,
    explain: "No compile-time safety, hard to test." },
  { q: "The captive-dependency rule from the .NET DI lesson applies in ASP.NET Core to…", options: ["Nothing new", "Singleton services depending on Scoped ones", "Only Minimal APIs"], answer: 1,
    explain: "Same lifetime rules, web-app context." },
  { q: "Command-line arguments have…", options: ["The lowest config precedence", "The HIGHEST config precedence", "No effect on configuration"], answer: 1,
    explain: "Override everything else." },
  { q: "AddDbContext registers DbContext with…", options: ["Singleton lifetime", "Scoped lifetime (the default)", "Transient lifetime"], answer: 1,
    explain: "One per HTTP request." },
  { q: "Forgetting Configure<T>() for an Options POCO results in…", options: ["A compile error", "IOptions<T>.Value silently returning defaults", "An immediate crash"], answer: 1,
    explain: "Always pair the POCO with its binding call." },
  { q: "The Options pattern makes configuration…", options: ["Harder to test", "Just another injectable, strongly-typed dependency", "Unavailable in tests"], answer: 1,
    explain: "Inject a fake IOptions<T> in unit tests." },
  { q: "Environment-driven behavior in Program.cs (dev vs prod) mirrors…", options: ["Nothing from other tracks", "The Docker/K8s 'config from the environment' principle", "A deprecated pattern"], answer: 1,
    explain: "Same core idea across the whole stack." },
  { q: "Constructor injection in ASP.NET Core controllers/services uses…", options: ["A different DI system than Minimal APIs", "THE SAME built-in DI container as everything else", "No DI at all"], answer: 1,
    explain: "One unified DI system across the framework." },
  { q: "Config precedence order (low to high) is roughly…", options: ["CLI args → env vars → JSON", "appsettings.json → env-specific JSON → env vars → CLI args", "Random"], answer: 1,
    explain: "Later sources override earlier ones." }
]},
{ title: "Quiz 3 · Controllers & MVC",
  desc: "[ApiController], action results, filters, controllers vs Minimal APIs",
  questions: [
  { q: "[ApiController] enables…", options: ["Manual validation only", "AUTOMATIC 400 responses on invalid model state", "Slower binding"], answer: 1,
    explain: "Short-circuits before the action runs." },
  { q: "Without [ApiController], you typically must…", options: ["Do nothing extra", "Manually check ModelState.IsValid", "Use Minimal APIs instead"], answer: 1,
    explain: "No automatic validation short-circuiting." },
  { q: "[Route(\"api/[controller]\")] with a class named OrdersController resolves to…", options: ["api/OrdersController", "api/orders (or Orders, case varies by convention)", "api/[controller]"], answer: 1,
    explain: "[controller] token substitutes the class name minus 'Controller'." },
  { q: "ActionResult<T> lets an action…", options: ["Only return T", "Return either a typed T OR any IActionResult (NotFound, BadRequest, etc.)", "Never return data"], answer: 1,
    explain: "Flexible, explicit HTTP semantics." },
  { q: "CreatedAtAction is used to…", options: ["Return 404", "Return 201 with a Location header pointing at a GET action", "Delete a resource"], answer: 1,
    explain: "REST convention for resource creation." },
  { q: "Filters (IActionFilter) run…", options: ["Only in Minimal APIs", "At specific points around MVC action execution", "Never in ASP.NET Core"], answer: 1,
    explain: "Authorization/Resource/Action/Exception/Result filters." },
  { q: "Filters vs middleware: filters are…", options: ["Identical to middleware", "MVC/controller-specific, finer-grained hooks", "Only for authentication"], answer: 1,
    explain: "Middleware runs for every request regardless of routing outcome." },
  { q: "Middleware vs filters: middleware…", options: ["Only runs for controllers", "Runs for EVERY request through the pipeline", "Has access to action arguments directly"], answer: 1,
    explain: "No inherent awareness of MVC-specific concepts." },
  { q: "Business logic directly in controller actions is…", options: ["Best practice", "An anti-pattern — delegate to injected services", "Required"], answer: 1,
    explain: "Keep controllers thin (orchestration only)." },
  { q: "Controllers use constructor injection…", options: ["Differently than other ASP.NET Core code", "The SAME way as any DI-managed class", "Not at all"], answer: 1,
    explain: "One unified DI system." },
  { q: "[ApiController] also improves…", options: ["Nothing else", "Binding source inference (less need for explicit [FromX])", "Only routing speed"], answer: 1,
    explain: "Smarter defaults, similar to Minimal APIs." },
  { q: "Controllers are generally favored over Minimal APIs when…", options: ["The API is tiny", "There are MANY related endpoints sharing conventions/filters", "Never — always use Minimal APIs"], answer: 1,
    explain: "Structure pays off at larger scale." },
  { q: "Minimal APIs are generally favored when…", options: ["You need heavy shared conventions", "The API is lean or microservice-style", "Filters are required"], answer: 1,
    explain: "Less ceremony for simpler APIs." },
  { q: "A single app can…", options: ["Only use one style", "MIX Controllers and Minimal APIs", "Never combine the two"], answer: 1,
    explain: "Both run on the same pipeline." },
  { q: "Return BadRequest(ModelState) is often…", options: ["Required manually even with [ApiController]", "Redundant, since [ApiController] already handles it automatically", "Invalid syntax"], answer: 1,
    explain: "Trust the automatic 400 behavior." },
  { q: "IActionFilter's OnActionExecuting runs…", options: ["After the action", "BEFORE the action method executes", "Only on errors"], answer: 1,
    explain: "OnActionExecuted runs after." },
  { q: "Overusing filters for logic that belongs in one action causes…", options: ["Clearer code", "Hard-to-trace 'magic' behavior spread across the codebase", "Faster execution always"], answer: 1,
    explain: "Reserve filters for genuinely cross-cutting concerns." },
  { q: "Not setting the Location header on a Create action…", options: ["Has no consequence", "Violates REST conventions clients may rely on", "Is required for security"], answer: 1,
    explain: "CreatedAtAction sets it automatically." },
  { q: "Exception filters specifically handle…", options: ["Successful responses", "Exceptions thrown during action execution", "Route matching"], answer: 1,
    explain: "One of the filter pipeline's stages." },
  { q: "The core behavioral difference [ApiController] adds is…", options: ["Faster HTTP", "Automatic model validation enforcement", "Built-in caching"], answer: 1,
    explain: "The single biggest practical difference from plain controllers." }
]},
{ title: "Quiz 4 · EF Core & Validation/Error Handling",
  desc: "DbContext lifetime, Unit of Work, repository debate, validation, global exception handling",
  questions: [
  { q: "DbContext should be registered as…", options: ["Singleton", "Scoped (AddDbContext's default)", "Transient always"], answer: 1,
    explain: "It's not thread-safe; one per request fits." },
  { q: "Injecting DbContext into a Singleton service causes…", options: ["No issue", "A captive dependency (stale/disposed context)", "Faster queries"], answer: 1,
    explain: "The .NET DI lesson's rule, applied concretely." },
  { q: "SaveChangesAsync() implements the…", options: ["Repository pattern", "Unit of Work pattern (atomic commit of all pending changes)", "Singleton pattern"], answer: 1,
    explain: "All accumulated changes commit together." },
  { q: "Modern guidance on generic Repository<T> wrappers around EF Core is…", options: ["Always use them", "Often unnecessary — DbContext/DbSet<T> is already a clean, testable abstraction", "Required by EF Core"], answer: 1,
    explain: "Domain-specific methods are more defensible than generic CRUD wrappers." },
  { q: "A domain-specific service method with a meaningful business query is…", options: ["An anti-pattern", "A reasonable pattern, unlike a generic CRUD repository", "The same as no abstraction at all"], answer: 1,
    explain: "Adds real value vs pure indirection." },
  { q: "Auto-migrating the database on every app startup in production is…", options: ["Best practice", "Risky — prefer a separate, deliberate deployment step", "Required"], answer: 1,
    explain: "Uncontrolled schema changes during scaling/deploys are dangerous." },
  { q: "With [ApiController], invalid data-annotation input…", options: ["Reaches the action anyway", "Is automatically rejected with 400 before the action runs", "Causes a 500"], answer: 1,
    explain: "Automatic short-circuiting." },
  { q: "Minimal APIs validate data annotations…", options: ["Automatically, like [ApiController]", "NOT automatically — must be wired explicitly", "Never, under any config"], answer: 1,
    explain: "A key structural difference from controllers." },
  { q: "FluentValidation is preferred over data annotations for…", options: ["Simple [Required] checks", "Cross-field rules, conditional logic, DB-backed rules needing DI", "Nothing — they're identical"], answer: 1,
    explain: "Annotations can't express these well." },
  { q: "A global exception handler (app.UseExceptionHandler) is preferred because…", options: ["It's slower", "It centralizes consistent error shapes and prevents leaking internals", "It replaces all validation"], answer: 1,
    explain: "One place instead of scattered try/catch." },
  { q: "Returning ex.Message to clients for unhandled 500 errors is…", options: ["Best practice", "A security risk — leaks internal details", "Required by ASP.NET Core"], answer: 1,
    explain: "Log full detail server-side; return a generic message externally." },
  { q: "ProblemDetails (RFC 7807) is…", options: ["A custom error format per team", "A standardized error response shape", "Only for 200 responses"], answer: 1,
    explain: "Consistent, well-understood by clients/tooling." },
  { q: "Using exceptions for expected validation failures is…", options: ["Recommended", "An anti-pattern — return explicit 400s instead", "The only option"], answer: 1,
    explain: "Ties back to the .NET exceptions lesson's principle." },
  { q: "AsNoTracking() should be used for…", options: ["Writes you'll SaveChanges()", "Read-only queries to skip tracking overhead", "Never used in ASP.NET Core"], answer: 1,
    explain: "The .NET EF Core lesson's core performance lever." },
  { q: "Multiple related mutations across DbSets typically call SaveChangesAsync()…", options: ["Once per mutation", "ONCE for the whole logical unit of work", "Never"], answer: 1,
    explain: "Atomic commit of all accumulated changes." },
  { q: "A generic repository often ends up…", options: ["More capable than DbSet<T>", "A thinner, less capable API than DbSet<T>'s IQueryable surface", "Identical to DbSet<T>"], answer: 1,
    explain: "One of the arguments against generic wrappers." },
  { q: "An endpoint filter (in newer ASP.NET Core) can bring Minimal APIs closer to…", options: ["Middleware-only behavior", "[ApiController]-like centralized validation for a route group", "Nothing useful"], answer: 1,
    explain: "Apply validation once across grouped endpoints." },
  { q: "Data annotations are best suited for…", options: ["Complex cross-field rules", "Simple, per-property constraints", "DB-backed uniqueness checks"], answer: 1,
    explain: "FluentValidation covers the harder cases." },
  { q: "A validator class in FluentValidation can…", options: ["Never use DI", "Have services injected (e.g., for DB-backed rules)", "Only validate primitives"], answer: 1,
    explain: "Unlike stateless data annotation attributes." },
  { q: "The core theme connecting EF Core registration and validation/errors in ASP.NET Core is…", options: ["Unrelated topics", "Consistent, centralized handling beats scattered, ad hoc logic", "Avoid EF Core entirely"], answer: 1,
    explain: "DI lifetimes, Unit of Work, and global error handling all centralize responsibility." }
]},
{ title: "Quiz 5 · Middleware Pipeline",
  desc: "Nested chain model, standard ordering, short-circuiting, custom middleware",
  questions: [
  { q: "The middleware pipeline is best understood as…", options: ["A flat, independent list", "A NESTED chain — each middleware wraps everything after it", "A random execution order"], answer: 1,
    explain: "Like nested function calls / a sandwich." },
  { q: "Code BEFORE `await next()` in a middleware runs…", options: ["On the way out (response)", "On the way IN (request), in registration order", "Never"], answer: 1,
    explain: "First-registered runs first, on the way in." },
  { q: "Code AFTER `await next()` runs…", options: ["On the way in", "On the way OUT (response), in REVERSE registration order", "Immediately, ignoring next()"], answer: 1,
    explain: "Last-in, first-out on the way back." },
  { q: "UseExceptionHandler() should be registered…", options: ["Last", "FIRST — so it wraps everything and can catch downstream exceptions", "Anywhere"], answer: 1,
    explain: "If registered late, it can't catch earlier exceptions." },
  { q: "UseAuthentication() must come…", options: ["After UseAuthorization()", "BEFORE UseAuthorization()", "It doesn't matter"], answer: 1,
    explain: "Need to know WHO before checking WHAT they can do." },
  { q: "UseAuthorization() without prior UseAuthentication() results in…", options: ["Correct authorization", "No populated User to check — authorization effectively fails/misbehaves", "Faster requests"], answer: 1,
    explain: "HttpContext.User isn't populated yet." },
  { q: "Middleware can 'short-circuit' the pipeline by…", options: ["Always calling next()", "NOT calling next(), stopping further processing", "Throwing an exception always"], answer: 1,
    explain: "The mechanism auth/rate-limiting middleware use to reject requests." },
  { q: "A common example of short-circuiting is…", options: ["Logging middleware", "Auth middleware rejecting an unauthorized request with 401/403", "Routing"], answer: 1,
    explain: "Stops before expensive downstream work runs." },
  { q: "Custom middleware can be written…", options: ["Only inline", "Inline (app.Use) OR as a dedicated class (app.UseMiddleware<T>)", "Only as a class"], answer: 1,
    explain: "Classes support DI of dependencies more cleanly." },
  { q: "UseRouting() is responsible for…", options: ["Authentication", "Determining WHICH endpoint will handle the request", "Serving static files"], answer: 1,
    explain: "A prerequisite for routing-aware middleware like authorization." },
  { q: "UseCors() should generally be placed…", options: ["Before UseRouting()", "AFTER UseRouting(), BEFORE UseAuthorization()", "Anywhere randomly"], answer: 1,
    explain: "Follows the documented standard ordering." },
  { q: "Forgetting to call next() in custom middleware…", options: ["Has no effect", "Silently stops the pipeline — nothing downstream runs", "Throws a compile error"], answer: 1,
    explain: "A common, hard-to-spot bug." },
  { q: "Heavy SYNCHRONOUS work in middleware…", options: ["Has no cost", "Blocks a thread for every request passing through", "Only affects that one request"], answer: 1,
    explain: "Use async for I/O-bound middleware work." },
  { q: "UseStaticFiles() is typically placed…", options: ["After routing", "Early — to short-circuit before routing/auth for static assets", "Last"], answer: 1,
    explain: "Serves files without invoking the full pipeline." },
  { q: "The middleware pipeline's 'sandwich' analogy means…", options: ["Middleware runs in isolation", "Each layer wraps the REST of the pipeline, nested", "Order is irrelevant"], answer: 1,
    explain: "The key mental model for understanding execution order." },
  { q: "A dedicated middleware CLASS's InvokeAsync method receives…", options: ["Nothing", "HttpContext (and can have services injected via the constructor)", "Only a string"], answer: 1,
    explain: "Enables DI of dependencies like ILogger<T>." },
  { q: "Registering the same middleware logic twice by accident…", options: ["Is harmless", "Causes duplicated behavior (e.g., double logging/auth checks)", "Is automatically deduplicated"], answer: 1,
    explain: "Register each middleware exactly once, in the right position." },
  { q: "The standard order places UseHttpsRedirection()…", options: ["After MapControllers()", "Early — before other processing of an insecure request", "Never needed"], answer: 1,
    explain: "Redirect before doing unnecessary work on an HTTP request." },
  { q: "Why does registration order matter so much in ASP.NET Core middleware?", options: ["It doesn't, really", "Because the pipeline is nested — earlier middleware wraps and controls access to later middleware", "Only for logging middleware"], answer: 1,
    explain: "The core reason ordering bugs are so common and consequential." },
  { q: "MapControllers()/endpoint mapping is typically…", options: ["First in the pipeline", "Near the END — after routing, auth, and other cross-cutting middleware", "Irrelevant to ordering"], answer: 1,
    explain: "Endpoints run after the pipeline has processed the request." }
]}
);
