// aspnet quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Minimal APIs & Routing",
  desc: "builder/app pattern, endpoint mapping, parameter binding, route constraints",
  questions: [
  { q: "WebApplication.CreateBuilder(args) begins…", options: ["Request handling", "The pipeline configuration phase", "The service registration/configuration phase"], answer: 2,
    explain: "Phase 1: register services before Build()." },
  { q: "Service registrations (builder.Services.Add...) must happen…", options: ["After Build()", "BEFORE builder.Build()", "Anytime"], answer: 1,
    explain: "The DI container is finalized at Build()." },
  { q: "app.MapGet/MapPost define…", options: ["Endpoints mapped to routes", "Middleware", "DbContext options"], answer: 0,
    explain: "The core of Minimal API routing." },
  { q: "A parameter named to match a route segment like {id} binds from…", options: ["The route", "The query string", "The request body"], answer: 0,
    explain: "Route-segment name matching." },
  { q: "A simple type NOT matching a route segment binds from…", options: ["Headers only", "The body", "The query string"], answer: 2,
    explain: "e.g., string q in ?q=hello." },
  { q: "A complex type parameter (a class/record) defaults to binding from…", options: ["Nothing", "The request BODY (JSON)", "The route"], answer: 1,
    explain: "The default for POST/PUT payloads." },
  { q: "A parameter type registered in DI (like IOrderService) is…", options: ["Bound from the query", "Resolved as an injected SERVICE, not client data", "Ignored"], answer: 1,
    explain: "Same binding rules distinguish services from client data." },
  { q: "Results.Ok(data) returns HTTP status…", options: ["200", "201", "404"], answer: 0,
    explain: "Success with a JSON body." },
  { q: "Results.Created(uri, data) returns HTTP status…", options: ["201 with a Location header", "200", "204"], answer: 0,
    explain: "For successful resource creation." },
  { q: "Results.NoContent() is typically used after a…", options: ["GET", "successful DELETE with no body to return", "failed request"], answer: 1,
    explain: "204 — success, nothing to return." },
  { q: "{id:int} in a route template is a…", options: ["A validation rule", "A middleware", "A route CONSTRAINT (shape filter + type conversion)"], answer: 2,
    explain: "Filters routing, not business validation." },
  { q: "A request that fails a route constraint…", options: ["Throws a 500", "Doesn't match that route (may 404)", "Reaches the handler anyway"], answer: 1,
    explain: "Constraints operate at routing time." },
  { q: "{*path} in a route template is…", options: ["Invalid syntax", "A single segment", "A catch-all matching multiple segments including slashes"], answer: 2,
    explain: "Useful for file paths." },
  { q: "MapGroup(\"/users\") is used to…", options: ["Share a prefix and config across related endpoints", "Register a service", "Bind a parameter"], answer: 0,
    explain: "Reduces repetition across related endpoints." },
  { q: "Applying .RequireAuthorization() on a MapGroup…", options: ["Does nothing", "Applies to all endpoints registered within that group", "Only affects one endpoint"], answer: 1,
    explain: "Shared config at the group level." },
  { q: "[FromQuery]/[FromBody]/[FromRoute] attributes are used to…", options: ["Explicitly override binding inference when ambiguous", "Register services", "Define routes"], answer: 0,
    explain: "Escape hatches for the default inference rules." },
  { q: "Two routes that can BOTH match the same request cause…", options: ["An AmbiguousMatchException", "A compile error", "The first one always wins silently"], answer: 0,
    explain: "A request-time routing failure." },
  { q: "A record like ProductFilter(string? Category, int Page = 1) as a GET parameter…", options: ["Can't bind from query string", "Binds ALL its properties from the query string automatically", "Only binds Category"], answer: 1,
    explain: "Complex query-parameter binding without manual parsing." },
  { q: "Minimal APIs and Controllers…", options: ["Cannot be mixed in one app", "Are entirely separate frameworks", "Run on the SAME underlying pipeline/DI/config"], answer: 2,
    explain: "A structural/style choice, not a different framework." },
  { q: "app.Run() …", options: ["Starts the Kestrel server and begins listening for requests", "Builds the DI container", "Registers services"], answer: 0,
    explain: "The final step after builder → app configuration." },
]},
{ title: "Quiz 2 · Dependency Injection & Configuration",
  desc: "Service lifetimes in ASP.NET Core, config layering, the Options pattern",
  questions: [
  { q: "Configuration sources are layered such that…", options: ["LATER sources override earlier ones", "Earlier sources always win", "Only one source is ever used"], answer: 0,
    explain: "appsettings.json → env-specific JSON → env vars → CLI args." },
  { q: "appsettings.{Environment}.json is used for…", options: ["Nothing in modern apps", "Secrets only", "Environment-specific config overrides"], answer: 2,
    explain: "e.g., appsettings.Development.json." },
  { q: "Environment variables typically inject…", options: ["Only UI settings", "Secrets/production config, per the Docker env-secrets principle", "Nothing useful"], answer: 1,
    explain: "One image, config from the environment." },
  { q: "Nested config keys in environment variables use…", options: ["A dot", "A DOUBLE UNDERSCORE (__)", "A colon"], answer: 1,
    explain: "e.g., Smtp__Host." },
  { q: "The Options pattern binds a config section to…", options: ["A database table", "A strongly-typed POCO class", "A raw string"], answer: 1,
    explain: "Injectable, refactor-safe configuration." },
  { q: "IOptions<T> is registered as…", options: ["Scoped", "Transient", "Singleton — computed once at startup"], answer: 2,
    explain: "Never changes at runtime." },
  { q: "IOptionsSnapshot<T> is registered as…", options: ["Scoped — re-read per request", "Transient", "Singleton"], answer: 0,
    explain: "Fresh values per request if the source changed." },
  { q: "IOptionsMonitor<T> provides…", options: ["Only startup values", "Live change notifications via .OnChange()", "No change tracking"], answer: 1,
    explain: "For long-lived services reacting to config changes." },
  { q: "IOptionsMonitor<T> is best for…", options: ["Per-request scoped work", "Never used in practice", "Long-lived services (e.g., background workers)"], answer: 2,
    explain: "Singleton with live updates." },
  { q: "Committing real secrets in appsettings.json is…", options: ["Required", "Best practice", "A leak risk — use env vars/secrets managers"], answer: 2,
    explain: "Never commit real credentials." },
  { q: "app.Environment.IsDevelopment() is typically used to…", options: ["Bind routes", "Gate dev-only middleware like Swagger/detailed errors", "Register services"], answer: 1,
    explain: "Different behavior per ASPNETCORE_ENVIRONMENT." },
  { q: "Reading raw IConfiguration[\"Smtp:Host\"] strings everywhere is…", options: ["Best practice", "Faster than Options", "Error-prone (magic strings) — the Options pattern is preferred"], answer: 2,
    explain: "No compile-time safety, hard to test." },
  { q: "The captive-dependency rule from the .NET DI lesson applies in ASP.NET Core to…", options: ["Singleton services depending on Scoped ones", "Nothing new", "Only Minimal APIs"], answer: 0,
    explain: "Same lifetime rules, web-app context." },
  { q: "Command-line arguments have…", options: ["The lowest config precedence", "The HIGHEST config precedence", "No effect on configuration"], answer: 1,
    explain: "Override everything else." },
  { q: "AddDbContext registers DbContext with…", options: ["Scoped lifetime (the default)", "Transient lifetime", "Singleton lifetime"], answer: 0,
    explain: "One per HTTP request." },
  { q: "Forgetting Configure<T>() for an Options POCO results in…", options: ["An immediate crash", "IOptions<T>.Value silently returning defaults", "A compile error"], answer: 1,
    explain: "Always pair the POCO with its binding call." },
  { q: "The Options pattern makes configuration…", options: ["Unavailable in tests", "Harder to test", "Just another injectable, strongly-typed dependency"], answer: 2,
    explain: "Inject a fake IOptions<T> in unit tests." },
  { q: "Environment-driven behavior in Program.cs (dev vs prod) mirrors…", options: ["The Docker/K8s 'config from the environment' principle", "Nothing from other tracks", "A deprecated pattern"], answer: 0,
    explain: "Same core idea across the whole stack." },
  { q: "Constructor injection in ASP.NET Core controllers/services uses…", options: ["No DI at all", "A different DI system than Minimal APIs", "THE SAME built-in DI container as everything else"], answer: 2,
    explain: "One unified DI system across the framework." },
  { q: "Config precedence order (low to high) is roughly…", options: ["CLI args → env vars → JSON", "Random", "appsettings.json → env-specific JSON → env vars → CLI args"], answer: 2,
    explain: "Later sources override earlier ones." },
]},
{ title: "Quiz 3 · Controllers & MVC",
  desc: "[ApiController], action results, filters, controllers vs Minimal APIs",
  questions: [
  { q: "[ApiController] enables…", options: ["AUTOMATIC 400 responses on invalid model state", "Manual validation only", "Slower binding"], answer: 0,
    explain: "Short-circuits before the action runs." },
  { q: "Without [ApiController], you typically must…", options: ["Use Minimal APIs instead", "Do nothing extra", "Manually check ModelState.IsValid"], answer: 2,
    explain: "No automatic validation short-circuiting." },
  { q: "[Route(\"api/[controller]\")] with a class named OrdersController resolves to…", options: ["api/OrdersController", "api/[controller]", "api/orders (or Orders, case varies by convention)"], answer: 2,
    explain: "[controller] token substitutes the class name minus 'Controller'." },
  { q: "ActionResult<T> lets an action…", options: ["Only return T", "Never return data", "Return either a typed T OR any IActionResult (NotFound, BadRequest, etc.)"], answer: 2,
    explain: "Flexible, explicit HTTP semantics." },
  { q: "CreatedAtAction is used to…", options: ["Return 201 with a Location header pointing at a GET action", "Return 404", "Delete a resource"], answer: 0,
    explain: "REST convention for resource creation." },
  { q: "Filters (IActionFilter) run…", options: ["Only in Minimal APIs", "At specific points around MVC action execution", "Never in ASP.NET Core"], answer: 1,
    explain: "Authorization/Resource/Action/Exception/Result filters." },
  { q: "Filters vs middleware: filters are…", options: ["Only for authentication", "Identical to middleware", "MVC/controller-specific, finer-grained hooks"], answer: 2,
    explain: "Middleware runs for every request regardless of routing outcome." },
  { q: "Middleware vs filters: middleware…", options: ["Only runs for controllers", "Runs for EVERY request through the pipeline", "Has access to action arguments directly"], answer: 1,
    explain: "No inherent awareness of MVC-specific concepts." },
  { q: "Business logic directly in controller actions is…", options: ["An anti-pattern — delegate to injected services", "Required", "Best practice"], answer: 0,
    explain: "Keep controllers thin (orchestration only)." },
  { q: "Controllers use constructor injection…", options: ["Not at all", "The SAME way as any DI-managed class", "Differently than other ASP.NET Core code"], answer: 1,
    explain: "One unified DI system." },
  { q: "[ApiController] also improves…", options: ["Only routing speed", "Binding source inference (less need for explicit [FromX])", "Nothing else"], answer: 1,
    explain: "Smarter defaults, similar to Minimal APIs." },
  { q: "Controllers are generally favored over Minimal APIs when…", options: ["There are MANY related endpoints sharing conventions/filters", "Never — always use Minimal APIs", "The API is tiny"], answer: 0,
    explain: "Structure pays off at larger scale." },
  { q: "Minimal APIs are generally favored when…", options: ["Filters are required", "You need heavy shared conventions", "The API is lean or microservice-style"], answer: 2,
    explain: "Less ceremony for simpler APIs." },
  { q: "A single app can…", options: ["Only use one style", "MIX Controllers and Minimal APIs", "Never combine the two"], answer: 1,
    explain: "Both run on the same pipeline." },
  { q: "Return BadRequest(ModelState) is often…", options: ["Invalid syntax", "Required manually even with [ApiController]", "Redundant, since [ApiController] already handles it automatically"], answer: 2,
    explain: "Trust the automatic 400 behavior." },
  { q: "IActionFilter's OnActionExecuting runs…", options: ["BEFORE the action method executes", "Only on errors", "After the action"], answer: 0,
    explain: "OnActionExecuted runs after." },
  { q: "Overusing filters for logic that belongs in one action causes…", options: ["Faster execution always", "Hard-to-trace 'magic' behavior spread across the codebase", "Clearer code"], answer: 1,
    explain: "Reserve filters for genuinely cross-cutting concerns." },
  { q: "Not setting the Location header on a Create action…", options: ["Has no consequence", "Violates REST conventions clients may rely on", "Is required for security"], answer: 1,
    explain: "CreatedAtAction sets it automatically." },
  { q: "Exception filters specifically handle…", options: ["Successful responses", "Route matching", "Exceptions thrown during action execution"], answer: 2,
    explain: "One of the filter pipeline's stages." },
  { q: "The core behavioral difference [ApiController] adds is…", options: ["Faster HTTP", "Automatic model validation enforcement", "Built-in caching"], answer: 1,
    explain: "The single biggest practical difference from plain controllers." },
]},
{ title: "Quiz 4 · EF Core & Validation/Error Handling",
  desc: "DbContext lifetime, Unit of Work, repository debate, validation, global exception handling",
  questions: [
  { q: "DbContext should be registered as…", options: ["Scoped (AddDbContext's default)", "Transient always", "Singleton"], answer: 0,
    explain: "It's not thread-safe; one per request fits." },
  { q: "Injecting DbContext into a Singleton service causes…", options: ["A captive dependency (stale/disposed context)", "No issue", "Faster queries"], answer: 0,
    explain: "The .NET DI lesson's rule, applied concretely." },
  { q: "SaveChangesAsync() implements the…", options: ["Unit of Work pattern (atomic commit of all pending changes)", "Repository pattern", "Singleton pattern"], answer: 0,
    explain: "All accumulated changes commit together." },
  { q: "Modern guidance on generic Repository<T> wrappers around EF Core is…", options: ["Always use them", "Often unnecessary — DbContext/DbSet<T> is already a clean, testable abstraction", "Required by EF Core"], answer: 1,
    explain: "Domain-specific methods are more defensible than generic CRUD wrappers." },
  { q: "A domain-specific service method with a meaningful business query is…", options: ["A reasonable pattern, unlike a generic CRUD repository", "The same as no abstraction at all", "An anti-pattern"], answer: 0,
    explain: "Adds real value vs pure indirection." },
  { q: "Auto-migrating the database on every app startup in production is…", options: ["Required", "Best practice", "Risky — prefer a separate, deliberate deployment step"], answer: 2,
    explain: "Uncontrolled schema changes during scaling/deploys are dangerous." },
  { q: "With [ApiController], invalid data-annotation input…", options: ["Reaches the action anyway", "Causes a 500", "Is automatically rejected with 400 before the action runs"], answer: 2,
    explain: "Automatic short-circuiting." },
  { q: "Minimal APIs validate data annotations…", options: ["Automatically, like [ApiController]", "Never, under any config", "NOT automatically — must be wired explicitly"], answer: 2,
    explain: "A key structural difference from controllers." },
  { q: "FluentValidation is preferred over data annotations for…", options: ["Nothing — they're identical", "Cross-field rules, conditional logic, DB-backed rules needing DI", "Simple [Required] checks"], answer: 1,
    explain: "Annotations can't express these well." },
  { q: "A global exception handler (app.UseExceptionHandler) is preferred because…", options: ["It replaces all validation", "It's slower", "It centralizes consistent error shapes and prevents leaking internals"], answer: 2,
    explain: "One place instead of scattered try/catch." },
  { q: "Returning ex.Message to clients for unhandled 500 errors is…", options: ["Best practice", "A security risk — leaks internal details", "Required by ASP.NET Core"], answer: 1,
    explain: "Log full detail server-side; return a generic message externally." },
  { q: "ProblemDetails (RFC 7807) is…", options: ["A standardized error response shape", "Only for 200 responses", "A custom error format per team"], answer: 0,
    explain: "Consistent, well-understood by clients/tooling." },
  { q: "Using exceptions for expected validation failures is…", options: ["The only option", "An anti-pattern — return explicit 400s instead", "Recommended"], answer: 1,
    explain: "Ties back to the .NET exceptions lesson's principle." },
  { q: "AsNoTracking() should be used for…", options: ["Read-only queries to skip tracking overhead", "Never used in ASP.NET Core", "Writes you'll SaveChanges()"], answer: 0,
    explain: "The .NET EF Core lesson's core performance lever." },
  { q: "Multiple related mutations across DbSets typically call SaveChangesAsync()…", options: ["Never", "Once per mutation", "ONCE for the whole logical unit of work"], answer: 2,
    explain: "Atomic commit of all accumulated changes." },
  { q: "A generic repository often ends up…", options: ["Identical to DbSet<T>", "A thinner, less capable API than DbSet<T>'s IQueryable surface", "More capable than DbSet<T>"], answer: 1,
    explain: "One of the arguments against generic wrappers." },
  { q: "An endpoint filter (in newer ASP.NET Core) can bring Minimal APIs closer to…", options: ["Middleware-only behavior", "[ApiController]-like centralized validation for a route group", "Nothing useful"], answer: 1,
    explain: "Apply validation once across grouped endpoints." },
  { q: "Data annotations are best suited for…", options: ["Complex cross-field rules", "DB-backed uniqueness checks", "Simple, per-property constraints"], answer: 2,
    explain: "FluentValidation covers the harder cases." },
  { q: "A validator class in FluentValidation can…", options: ["Only validate primitives", "Never use DI", "Have services injected (e.g., for DB-backed rules)"], answer: 2,
    explain: "Unlike stateless data annotation attributes." },
  { q: "The core theme connecting EF Core registration and validation/errors in ASP.NET Core is…", options: ["Consistent, centralized handling beats scattered, ad hoc logic", "Avoid EF Core entirely", "Unrelated topics"], answer: 0,
    explain: "DI lifetimes, Unit of Work, and global error handling all centralize responsibility." },
]},
{ title: "Quiz 5 · Middleware Pipeline",
  desc: "Nested chain model, standard ordering, short-circuiting, custom middleware",
  questions: [
  { q: "The middleware pipeline is best understood as…", options: ["A NESTED chain — each middleware wraps everything after it", "A flat, independent list", "A random execution order"], answer: 0,
    explain: "Like nested function calls / a sandwich." },
  { q: "Code BEFORE `await next()` in a middleware runs…", options: ["On the way IN (request), in registration order", "On the way out (response)", "Never"], answer: 0,
    explain: "First-registered runs first, on the way in." },
  { q: "Code AFTER `await next()` runs…", options: ["On the way in", "On the way OUT (response), in REVERSE registration order", "Immediately, ignoring next()"], answer: 1,
    explain: "Last-in, first-out on the way back." },
  { q: "UseExceptionHandler() should be registered…", options: ["Last", "FIRST — so it wraps everything and can catch downstream exceptions", "Anywhere"], answer: 1,
    explain: "If registered late, it can't catch earlier exceptions." },
  { q: "UseAuthentication() must come…", options: ["BEFORE UseAuthorization()", "It doesn't matter", "After UseAuthorization()"], answer: 0,
    explain: "Need to know WHO before checking WHAT they can do." },
  { q: "UseAuthorization() without prior UseAuthentication() results in…", options: ["No populated User to check — authorization effectively fails/misbehaves", "Faster requests", "Correct authorization"], answer: 0,
    explain: "HttpContext.User isn't populated yet." },
  { q: "Middleware can 'short-circuit' the pipeline by…", options: ["NOT calling next(), stopping further processing", "Throwing an exception always", "Always calling next()"], answer: 0,
    explain: "The mechanism auth/rate-limiting middleware use to reject requests." },
  { q: "A common example of short-circuiting is…", options: ["Auth middleware rejecting an unauthorized request with 401/403", "Logging middleware", "Routing"], answer: 0,
    explain: "Stops before expensive downstream work runs." },
  { q: "Custom middleware can be written…", options: ["Inline (app.Use) OR as a dedicated class (app.UseMiddleware<T>)", "Only inline", "Only as a class"], answer: 0,
    explain: "Classes support DI of dependencies more cleanly." },
  { q: "UseRouting() is responsible for…", options: ["Determining WHICH endpoint will handle the request", "Authentication", "Serving static files"], answer: 0,
    explain: "A prerequisite for routing-aware middleware like authorization." },
  { q: "UseCors() should generally be placed…", options: ["Anywhere randomly", "AFTER UseRouting(), BEFORE UseAuthorization()", "Before UseRouting()"], answer: 1,
    explain: "Follows the documented standard ordering." },
  { q: "Forgetting to call next() in custom middleware…", options: ["Silently stops the pipeline — nothing downstream runs", "Throws a compile error", "Has no effect"], answer: 0,
    explain: "A common, hard-to-spot bug." },
  { q: "Heavy SYNCHRONOUS work in middleware…", options: ["Has no cost", "Blocks a thread for every request passing through", "Only affects that one request"], answer: 1,
    explain: "Use async for I/O-bound middleware work." },
  { q: "UseStaticFiles() is typically placed…", options: ["Last", "Early — to short-circuit before routing/auth for static assets", "After routing"], answer: 1,
    explain: "Serves files without invoking the full pipeline." },
  { q: "The middleware pipeline's 'sandwich' analogy means…", options: ["Each layer wraps the REST of the pipeline, nested", "Order is irrelevant", "Middleware runs in isolation"], answer: 0,
    explain: "The key mental model for understanding execution order." },
  { q: "A dedicated middleware CLASS's InvokeAsync method receives…", options: ["HttpContext (and can have services injected via the constructor)", "Only a string", "Nothing"], answer: 0,
    explain: "Enables DI of dependencies like ILogger<T>." },
  { q: "Registering the same middleware logic twice by accident…", options: ["Is harmless", "Causes duplicated behavior (e.g., double logging/auth checks)", "Is automatically deduplicated"], answer: 1,
    explain: "Register each middleware exactly once, in the right position." },
  { q: "The standard order places UseHttpsRedirection()…", options: ["Early — before other processing of an insecure request", "Never needed", "After MapControllers()"], answer: 0,
    explain: "Redirect before doing unnecessary work on an HTTP request." },
  { q: "Why does registration order matter so much in ASP.NET Core middleware?", options: ["Only for logging middleware", "It doesn't, really", "Because the pipeline is nested — earlier middleware wraps and controls access to later middleware"], answer: 2,
    explain: "The core reason ordering bugs are so common and consequential." },
  { q: "MapControllers()/endpoint mapping is typically…", options: ["First in the pipeline", "Near the END — after routing, auth, and other cross-cutting middleware", "Irrelevant to ordering"], answer: 1,
    explain: "Endpoints run after the pipeline has processed the request." },
]},
);
