// docker quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations: What a Container Actually Is",
  desc: "Process not VM, measured start times, images vs containers, the runtime stack",
  questions: [
  { q: "A container differs from a VM in that it…", options: ["Shares the host kernel (isolated by namespaces/cgroups)", "Runs its own guest kernel", "Needs a hypervisor"], answer: 0,
    explain: "No guest OS — that's why containers are lightweight and start fast." },
  { q: "Measured cold starts: a container ran in ~0.4 s where an equivalent VM took ~24 s. The difference is because…", options: ["There is no guest kernel to boot — the container is just a process the host already knows how to run", "Containers skip filesystem checks", "The container image was smaller"], answer: 0,
    explain: "A container is a normal process with a restricted view. Nothing boots, so start-up cost is process creation, not machine initialisation." },
  { q: "Container isolation compared with a VM is best described as…", options: ["Configuration-enforced: namespaces, cgroups, capabilities, seccomp and an LSM over ONE shared kernel", "Hardware-enforced, like a hypervisor", "Identical in strength"], answer: 0,
    explain: "Every part of the boundary is a policy the daemon sets, and each can be weakened by a flag. A kernel bug is an escape for every container on the host." },
  { q: "An image is…", options: ["A read-only template (layers) you run containers from", "A running process", "A network"], answer: 0,
    explain: "Image = blueprint; container = a running instance of it." },
  { q: "A container is…", options: ["The same as an image", "A registry", "A running (or stopped) instance of an image"], answer: 2,
    explain: "Many containers can run from one image." },
  { q: "A container stops when…", options: ["Its PID 1 exits — everything else in the container is killed with it", "Its memory limit is reached", "The host reboots"], answer: 0,
    explain: "The lifetime is exactly PID 1's lifetime. A process that daemonises into the background makes PID 1 return, and the container exits immediately." },
  { q: "docker run does what?", options: ["Only builds", "Pushes to a registry", "Creates + starts a container from an image"], answer: 2,
    explain: "It pulls (if needed), creates, and starts." },
  { q: "The Docker daemon (dockerd)…", options: ["Is the CLI", "Is a registry", "Is the background service that builds/runs containers"], answer: 2,
    explain: "The CLI talks to the daemon via its API." },
  { q: "'Works on my machine' problems are reduced because…", options: ["The image bundles app + deps + config consistently", "Docker is faster", "It uses more RAM"], answer: 0,
    explain: "Same image runs the same everywhere." },
  { q: "Containers are ideal for…", options: ["Packaging and running apps consistently across environments", "Only Linux GUIs", "Replacing databases"], answer: 0,
    explain: "Portable, reproducible app packaging." },
  { q: "docker ps shows…", options: ["Images", "Volumes", "Running containers (add -a for all)"], answer: 2,
    explain: "docker ps -a includes stopped/exited ones." },
  { q: "docker images lists…", options: ["Networks", "Local images", "Containers"], answer: 1,
    explain: "Images stored on the host." },
  { q: "A stopped container…", options: ["Is deleted", "Still exists (can be started again) until removed", "Loses its config"], answer: 1,
    explain: "docker start restarts it; docker rm deletes it." },
  { q: "VMs are preferable when you need…", options: ["Smaller size", "Strong isolation / a different kernel", "Fast startup"], answer: 1,
    explain: "Hostile multi-tenant or different-OS workloads." },
  { q: "You run an image on a new host and get `exec format error`. The FIRST thing to check is…", options: ["Whether the disk is full", "The container's memory limit", "The image architecture against the host: `docker image inspect --format '{{.Architecture}}'` vs `uname -m`"], answer: 2,
    explain: "Architecture mismatch is the classic cause — an arm64 image built on a laptop run on an x86 host. CRLF shebangs and a missing dynamic loader produce the same or a similar message." },
  { q: "A container's default user is…", options: ["nobody", "A random user", "root (uid 0) unless you set USER"], answer: 2,
    explain: "A security concern addressed later." },
  { q: "Mounting `/var/run/docker.sock` into a container gives that container…", options: ["Root on the host — it can ask the root daemon to start a privileged container mounting /", "Only its own logs", "Read-only metrics access"], answer: 0,
    explain: "This is documented, intended behaviour, not a vulnerability. The container's own UID is irrelevant: the payload runs in the daemon, which is root." },
  { q: "Containers are 'ephemeral' meaning…", options: ["They can't be deleted", "Their writable filesystem is disposable on removal", "They never stop"], answer: 1,
    explain: "Persist data in volumes, not the container." },
  { q: "One image can produce…", options: ["Only VMs", "Only one container", "Many identical containers"], answer: 2,
    explain: "Scale horizontally from one image." },
  { q: "In the runtime stack, when `dockerd` is restarted while containers are running…", options: ["They keep running — each container's `containerd-shim` is its real parent and survives the daemon restart", "They are paused until it returns", "All containers are killed"], answer: 0,
    explain: "The shim owns the container's process and holds its stdio, which is exactly why a daemon upgrade need not be an outage." },
]},
{ title: "Quiz 2 · Images, Layers & the Dockerfile",
  desc: "Union FS and whiteouts, the build cache, shell vs exec form, docker history",
  questions: [
  { q: "Each Dockerfile instruction creates…", options: ["A layer", "A container", "A network"], answer: 0,
    explain: "Images are stacks of read-only layers." },
  { q: "FROM specifies…", options: ["The base image to build on", "The ports", "The final command"], answer: 0,
    explain: "Every Dockerfile starts from a base." },
  { q: "For best cache reuse, you should…", options: ["Never copy", "COPY . . first", "Copy manifests + install deps BEFORE copying source"], answer: 2,
    explain: "Code changes shouldn't bust the deps-install layer." },
  { q: "A `RUN apt-get update && apt-get install -y curl` layer is reused from cache based on…", options: ["The command STRING alone — the cache has no idea the remote packages moved", "Whether the packages changed upstream", "A checksum of the installed files"], answer: 0,
    explain: "This is why a cached `apt-get update` can pair with a much later install and fetch stale or missing packages. Bust it deliberately or combine the commands." },
  { q: "CMD vs ENTRYPOINT: CMD is…", options: ["Always fixed", "The default command/args, easily overridden at run", "The base image"], answer: 1,
    explain: "ENTRYPOINT sets the executable; CMD gives default args." },
  { q: "RUN executes…", options: ["At BUILD time, creating a layer", "Never", "At container start"], answer: 0,
    explain: "CMD/ENTRYPOINT run at container start." },
  { q: "COPY vs ADD: prefer COPY because…", options: ["COPY compresses", "ADD has surprising extras (URL fetch, auto-extract)", "ADD is faster"], answer: 1,
    explain: "Use COPY unless you need ADD's features." },
  { q: "WORKDIR does what?", options: ["Sets the working directory for subsequent instructions", "Copies files", "Exposes a port"], answer: 0,
    explain: "Creates + cd's into the directory." },
  { q: "EXPOSE…", options: ["Opens a firewall", "Publishes a port to the host", "Documents the listening port (doesn't publish)"], answer: 2,
    explain: "Publishing is -p at run time." },
  { q: "Deleting a file in a later layer…", options: ["Only adds a whiteout marker — the bytes are still present in the earlier layer and extractable with `docker save`", "Removes it from the image", "Shrinks the image"], answer: 0,
    explain: "Layers are additive. A secret 'removed' in a later RUN is fully recoverable from the published image; the only remedy is to rotate it." },
  { q: "docker build -t myapp:1.0 . does…", options: ["Builds an image tagged myapp:1.0 from the context", "Runs a container", "Pushes it"], answer: 0,
    explain: "The '.' is the build context." },
  { q: "The build context is…", options: ["The files sent to the daemon for the build", "The base image", "The registry"], answer: 0,
    explain: ".dockerignore trims it." },
  { q: "ENV sets…", options: ["Build-only vars", "Environment variables baked into the image/runtime", "Ports"], answer: 1,
    explain: "Don't put secrets here — they persist in layers." },
  { q: "ARG is…", options: ["A volume", "A build-time variable (visible in docker history)", "A runtime env var"], answer: 1,
    explain: "Not for secrets — it leaks into history." },
  { q: "`docker history` on a published image reveals…", options: ["Nothing useful", "The full build commands, including any value passed via `ARG` — which is why build args are not a secret mechanism", "Only the layer sizes"], answer: 1,
    explain: "ARG values are recorded in image metadata. Use BuildKit's `--mount=type=secret`, which leaves nothing in the layer or the history." },
  { q: "Layers being read-only means…", options: ["They can't be cached", "They're shared across containers; a thin writable layer sits on top", "You can't run them"], answer: 1,
    explain: "Space-efficient sharing." },
  { q: "Reordering a Dockerfile so dependency installation precedes the source COPY took a measured rebuild from 23.4 s to 0.74 s. The rule is…", options: ["Combine every instruction into one RUN", "Always use fewer layers", "Put the least-frequently-changing steps first — a changed layer invalidates every layer after it"], answer: 2,
    explain: "The cascade is the whole cost model of the build cache: order by rate of change, not by readability." },
  { q: "`CMD npm start` (shell form) versus `CMD [\"npm\",\"start\"]` (exec form) matters because…", options: ["Shell form makes /bin/sh PID 1, so SIGTERM never reaches your process — measured as a 10.3 s stop ending in exit 137, versus 0.4 s and exit 0", "Exec form is shorter", "Shell form is faster to start"], answer: 0,
    explain: "sh does not forward signals to its child. Docker waits out the stop timeout and then SIGKILLs, so in-flight work is lost on every deploy." },
  { q: "A .dockerignore file…", options: ["Deletes images", "Ignores containers", "Excludes files from the build context"], answer: 2,
    explain: "Like .gitignore, for builds." },
  { q: "The first write to an existing large file in an image layer is slow because…", options: ["Copy-up: the union filesystem must copy the whole file to the writable layer first — a one-byte write to a 300 MB file measured 310× slower", "The layer is compressed", "Docker scans it for viruses"], answer: 0,
    explain: "This is why databases and other write-heavy paths belong on a volume, which bypasses the union filesystem entirely." },
]},
{ title: "Quiz 3 · Running Containers: Storage & Networking",
  desc: "Volumes vs binds, copy-up, port publishing, user-defined bridge DNS",
  questions: [
  { q: "Data written inside a container (no volume) is…", options: ["Synced to the host", "Persistent", "Lost when the container is removed"], answer: 2,
    explain: "The writable layer is ephemeral." },
  { q: "Mounting a NAMED volume over a non-empty image directory…", options: ["Hides the image's files", "Fails with an error", "Pre-populates the empty volume with the image's contents on first use"], answer: 2,
    explain: "Named volumes pre-populate; BIND mounts do the opposite and hide whatever the image had there. Confusing the two is the most common storage surprise." },
  { q: "Mounting a BIND mount over a non-empty image directory…", options: ["Hides the image's files completely — the host directory wins, even if it is empty", "Pre-populates the host directory", "Merges the two"], answer: 0,
    explain: "An empty host directory bind-mounted over /app produces an empty /app. This is the classic 'my node_modules disappeared' bug." },
  { q: "For a database's data in production, use…", options: ["A bind mount to /tmp", "The container FS", "A named volume (or external managed DB)"], answer: 2,
    explain: "Survives container recreation." },
  { q: "With `-p 8080:3000`, another container on the same network should connect to…", options: ["localhost:8080", "servicename:3000 — the container port; 8080 exists only on the host side of the NAT", "host:8080"], answer: 1,
    explain: "Published ports are for reaching the service from outside the host. Container-to-container traffic needs no publishing at all." },
  { q: "EXPOSE without -p means…", options: ["Port is documented but NOT published", "Firewall opens", "Port is reachable from host"], answer: 0,
    explain: "You still need -p to reach it from the host." },
  { q: "On the DEFAULT bridge network, containers…", options: ["Cannot reach each other at all", "Have NO DNS — name resolution only works on user-defined networks, which is why Compose creates one", "Resolve each other by name"], answer: 1,
    explain: "The embedded resolver at 127.0.0.11 is a user-defined-network feature. The legacy `--link` flag existed to paper over this." },
  { q: "A user-defined network gives…", options: ["DNS resolution by container name", "No isolation", "Slower networking"], answer: 0,
    explain: "api can reach 'db' by name — no hardcoded IPs." },
  { q: "Hardcoding a container's IP is bad because…", options: ["It's slower", "IPs are secret", "IPs change on restart"], answer: 2,
    explain: "Use service/container names instead." },
  { q: "tmpfs mounts store data…", options: ["In memory only (gone on stop)", "On disk", "In a registry"], answer: 0,
    explain: "Good for secrets/temp data." },
  { q: "docker network create appnet creates…", options: ["A container", "A volume", "A user-defined network with DNS"], answer: 2,
    explain: "Attach containers with --network appnet." },
  { q: "A published port on a cloud VM with UFW configured to deny inbound is…", options: ["Reachable only from localhost", "Still reachable — Docker's DNAT happens in the nat table PREROUTING, before UFW's INPUT rules are consulted", "Blocked by UFW"], answer: 1,
    explain: "Demonstrated: publishing a database port bypasses the host firewall. Bind to loopback (`127.0.0.1:5432:5432`) or do not publish it." },
  { q: "Host network mode (--network host)…", options: ["Adds isolation", "Blocks all ports", "Shares the host's network stack (no port mapping, less isolation)"], answer: 2,
    explain: "Max performance, weaker isolation." },
  { q: "'none' network mode means…", options: ["Host mode", "No networking (fully isolated)", "Default bridge"], answer: 1,
    explain: "For fully offline containers." },
  { q: "Overlay networks are for…", options: ["Multi-host container communication (orchestration)", "Single host", "Volumes"], answer: 0,
    explain: "Swarm/Kubernetes across machines." },
  { q: "Compose helps networking by…", options: ["Nothing", "Auto-creating a user-defined network (services reach each other by name)", "Disabling DNS"], answer: 1,
    explain: "Why api can use postgres://db:5432." },
  { q: "The 'stateless container' principle means…", options: ["Never restart", "Design so containers can be killed/recreated; state lives in volumes", "No data anywhere"], answer: 1,
    explain: "Orchestrators recreate containers freely." },
  { q: "A service answers `docker exec app curl localhost:3000` but refuses connections from the host despite `-p 8080:3000`. The cause is…", options: ["A firewall rule", "The wrong published port", "The application bound to 127.0.0.1 INSIDE its own network namespace — nothing outside that namespace, including the port-forwarder, can reach it"], answer: 2,
    explain: "`ss -ltn` in the container's netns shows `127.0.0.1:3000`. Testing from inside the container hides the bug because it shares the namespace." },
  { q: "docker volume ls lists…", options: ["Images", "Networks", "Volumes"], answer: 2,
    explain: "Manage persistent storage." },
  { q: "Removing a container with -v (docker rm -v)…", options: ["Also removes anonymous volumes", "Removes images", "Keeps volumes"], answer: 0,
    explain: "Named volumes persist unless explicitly removed." },
]},
{ title: "Quiz 4 · Compose & Health Checks",
  desc: "Project namespace, .env vs env_file, merge rules, readiness gating, start_period",
  questions: [
  { q: "Docker Compose is for…", options: ["Building base images", "Declaring & running multi-container apps in one YAML", "Scanning CVEs"], answer: 1,
    explain: "up/down the whole stack with one command." },
  { q: "In Compose, services reach each other by…", options: ["MAC address", "Hardcoded IP", "Service NAME (auto DNS on a shared network)"], answer: 2,
    explain: "api → postgres://db:5432 using service name 'db'." },
  { q: "Plain `depends_on: [db]` guarantees…", options: ["Only that the db container was STARTED — measured 27% cold-start failure on a naive stack", "That migrations have run", "The database is accepting connections"], answer: 0,
    explain: "'Started' means the entrypoint was executed. Postgres has not run initdb, let alone bound its port." },
  { q: "To gate a service on a dependency actually being usable, you need…", options: ["`restart: always`", "A longer `sleep` in the entrypoint", "A healthcheck on the dependency plus `depends_on: {db: {condition: service_healthy}}`"], answer: 2,
    explain: "This took the measured failure rate from 27% to 0. A one-shot job is gated with `service_completed_successfully` instead." },
  { q: "docker compose up -d does…", options: ["Only builds", "Builds/creates network/starts all services detached", "Deletes volumes"], answer: 1,
    explain: "-d = detached (background)." },
  { q: "`docker compose down` (no flags)…", options: ["Only stops containers", "Deletes named volumes", "Removes containers and networks, KEEPS named volumes — but still discards anonymous ones"], answer: 2,
    explain: "`down -v` destroys named volumes irreversibly. Name every volume that holds data, or a plain `down` will discard it." },
  { q: "'build:' in a service means…", options: ["Nothing", "Pull an image", "Build from a local Dockerfile"], answer: 2,
    explain: "'image:' pulls a prebuilt one instead." },
  { q: "A named volume in Compose is declared…", options: ["Under top-level 'volumes:' and referenced by services", "In .env", "Only inline"], answer: 0,
    explain: "For DB persistence across down/up." },
  { q: "`compose.override.yaml` is…", options: ["Loaded only with an explicit -f", "Ignored by Compose v2", "Loaded AUTOMATICALLY — so a stray dev override on a server is silently merged into a production deploy"], answer: 2,
    explain: "Deploy with an explicit `-f` list, and verify with `docker compose config`: the raw YAML is never what ran." },
  { q: "`.env` next to the Compose file differs from a service's `env_file:` because…", options: ["They are aliases", "`.env` is encrypted", "`.env` is read by the Compose CLI to fill ${VAR} in the YAML; `env_file` is read when the container is created and becomes the process environment"], answer: 2,
    explain: "A value in `.env` that the YAML never references does not reach the application — the highest-frequency Compose bug. Forward it with `environment: [VAR]`." },
  { q: "`start_period` in a healthcheck…", options: ["Delays the first check", "Sets the total timeout", "Is a GRACE WINDOW: checks still run, but failures do not count toward `retries`, and the first success flips the container healthy immediately"], answer: 2,
    explain: "Verified by watching the failing streak climb while the status stays `starting`. Too short a window creates a restart loop that can never finish booting." },
  { q: "Compose is best suited for…", options: ["Multi-host production at scale", "Replacing databases", "Single-host dev and simple deploys"], answer: 2,
    explain: "Kubernetes handles multi-host orchestration." },
  { q: "You outgrow Compose for Kubernetes when you need…", options: ["A YAML file", "Volumes", "Multi-host scheduling, autoscaling, self-healing, rolling updates"], answer: 2,
    explain: "Cluster-scale orchestration." },
  { q: "docker compose logs -f api…", options: ["Follows one service's logs", "Deletes logs", "Restarts api"], answer: 0,
    explain: "-f = follow." },
  { q: "Secrets committed in compose.yaml are…", options: ["Safe", "Encrypted", "A leak risk — use .env/secrets instead"], answer: 2,
    explain: "Keep credentials out of version control." },
  { q: "The Compose network is…", options: ["A user-defined network (name resolution included)", "The default bridge", "Host mode"], answer: 0,
    explain: "That's why service-name DNS works." },
  { q: "Merging `-f base.yaml -f prod.yaml`, a `ports` entry in the base file…", options: ["Is CONCATENATED — multi-value sequences can only be added to, never removed by an override", "Is replaced by the override", "Causes an error"], answer: 0,
    explain: "Scalars and `command` replace, mappings merge, and `ports`/`volumes` concatenate. Keep the base file the minimum that no environment needs to remove." },
  { q: "'restart: unless-stopped' means…", options: ["Restart once", "Auto-restart on failure/reboot unless you stopped it", "Never restart"], answer: 1,
    explain: "A restart policy for resilience." },
  { q: "The concepts in Compose (services, networks, volumes)…", options: ["Don't transfer", "Are Docker-only forever", "Map directly to Kubernetes concepts"], answer: 2,
    explain: "Compose is a conceptual on-ramp to k8s." },
  { q: "docker compose ps shows…", options: ["The status of the stack's services", "Volumes only", "Images"], answer: 0,
    explain: "Which services are up/healthy." },
]},
{ title: "Quiz 5 · Multi-stage, BuildKit & Image Size",
  desc: "Discarded stages, scratch traps, the build graph, cross-compilation, base choice",
  questions: [
  { q: "Multi-stage builds let you…", options: ["Run multiple containers", "Skip Dockerfiles", "Build in one stage and ship only the artifact from a clean stage"], answer: 2,
    explain: "The build toolchain is discarded." },
  { q: "The key multi-stage instruction is…", options: ["COPY --from=builder", "RUN", "EXPOSE"], answer: 0,
    explain: "Copies just the artifact from a previous stage." },
  { q: "Files created and then deleted in a DISCARDED build stage…", options: ["Remain in the final image's history", "Increase the final image size", "Leave nothing at all — only what the final stage COPYs --from is kept, which took a measured image from 1.19 GB to 14.2 MB"], answer: 2,
    explain: "This is the real power of multi-stage: the toolchain, caches and any build-time secret simply never exist in the published image." },
  { q: "For the smallest base with a static Go binary, use…", options: ["ubuntu", "node:22", "scratch or distroless"], answer: 2,
    explain: "Just the binary, no OS/shell." },
  { q: "A static binary in a `scratch` image commonly fails on its first HTTPS call because…", options: ["scratch blocks networking", "There are no CA certificates — you must COPY ca-certificates.crt in, and add a numeric USER, since scratch has no /etc/passwd either", "TLS needs a shell"], answer: 1,
    explain: "scratch contains literally nothing. Timezone data is the third thing people discover they are missing." },
  { q: "In the runtime stage, install deps with…", options: ["npm install -g everything", "npm ci (all)", "npm ci --omit=dev (prod only)"], answer: 2,
    explain: "Don't ship dev dependencies." },
  { q: "Base image size ranking (roughly): node:22 vs alpine…", options: ["node:22 (~1GB) ≫ node:22-alpine (~150MB)", "alpine is bigger", "Equal"], answer: 0,
    explain: "Pick the smallest base that works." },
  { q: "Switching a Python image to Alpine took a measured build from 38 s to 24 MINUTES and produced a LARGER image because…", options: ["musl means manylinux wheels do not match, so every C extension is compiled from source — and the toolchain lands in the image", "Alpine has no Python", "Alpine downloads are slower"], answer: 0,
    explain: "Alpine is the wrong default for Python. `python:3.12-slim` is usually smaller in practice and builds in seconds." },
  { q: "Cleaning apt caches in a SEPARATE `RUN` after the install…", options: ["Makes the image LARGER — the files are already committed in the previous layer, and the cleanup adds a whiteout layer on top", "Has no effect", "Shrinks the image"], answer: 0,
    explain: "The cleanup must happen in the same RUN as the install, or it removes nothing from the image." },
  { q: "--target=builder lets you…", options: ["Push", "Build only up to a named stage (e.g., for CI tests)", "Skip building"], answer: 1,
    explain: "Handy for a test stage." },
  { q: "BuildKit differs from the legacy builder principally because…", options: ["It builds a dependency GRAPH rather than executing a script, so independent stages run in parallel and unreferenced ones are skipped entirely", "It is written in Go", "It compresses layers better"], answer: 0,
    explain: "The graph model is what makes `--mount=type=cache`, `--mount=type=secret` and multi-platform builds possible." },
  { q: "docker history helps optimization by…", options: ["Showing per-layer sizes to find bloat", "Signing images", "Running the app"], answer: 0,
    explain: "Locate the fat layer." },
  { q: "Copying too much from the builder…", options: ["Is fine", "Speeds pulls", "Reintroduces bloat — copy only the artifact"], answer: 2,
    explain: "Copy the binary/dist, not source + caches." },
  { q: "Smaller images benefit…", options: ["Pull speed, deploy speed, cost, AND attack surface", "Only storage", "Nothing"], answer: 0,
    explain: "Multiple wins at once." },
  { q: "Compiled languages benefit most from multi-stage because…", options: ["A self-contained binary needs no toolchain at runtime", "They're interpreted", "They can't be containerized"], answer: 0,
    explain: "Ship a tiny binary in scratch/distroless." },
  { q: ".dockerignore helps optimization by…", options: ["Deleting images", "Shrinking context, stabilizing cache, avoiding leaked files", "Nothing"], answer: 1,
    explain: "Keep node_modules/.git/.env out." },
  { q: "Two sometimes-competing goals are…", options: ["CPU and GPU", "Color and font", "Small final image vs fast builds"], answer: 2,
    explain: "Multi-stage for size; layer/cache for speed." },
  { q: "Building an arm64 image on an x86 host: cross-compiling in a native stage beat QEMU emulation by a measured…", options: ["No difference", "1.2×", "15.4×"], answer: 2,
    explain: "Emulating every instruction of a compiler is enormously slow. Build natively with `--platform=$BUILDPLATFORM` and cross-compile to the target." },
  { q: "The 'dive' tool is used to…", options: ["Run containers", "Deploy", "Explore image layers and find wasted space"], answer: 2,
    explain: "Interactive per-layer inspection." },
  { q: "A single-stage build with build tools in the final image…", options: ["Is smallest", "Ships unused toolchain (bloat + attack surface)", "Is required"], answer: 1,
    explain: "The problem multi-stage solves." },
]},
);
