// Docker quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Environment & Secrets",
  desc: "Runtime config, why secrets leak into layers, BuildKit secrets",
  questions: [
  { q: "Configuration should come from…", options: ["Baked into the image", "The environment at runtime (12-factor)", "The Dockerfile only"], answer: 1,
    explain: "One image runs unchanged across environments." },
  { q: "Putting a secret in ENV in a Dockerfile…", options: ["Is secure", "Stores it in a readable image layer", "Encrypts it"], answer: 1,
    explain: "Anyone with the image can read it." },
  { q: "A build ARG secret leaks via…", options: ["Nothing", "docker history", "The network"], answer: 1,
    explain: "ARGs appear in the image history." },
  { q: "COPY .env into an image is bad because…", options: ["It's slow", "The secret becomes a permanent layer", "It fails"], answer: 1,
    explain: "Even deleting it later leaves it in the earlier layer." },
  { q: "Deleting a secret in a LATER layer…", options: ["Removes it fully", "Does NOT remove it from the earlier layer", "Shrinks the image"], answer: 1,
    explain: "Layers are additive/immutable." },
  { q: "The golden rule for secrets is…", options: ["Bake at build", "Inject at RUNTIME, never bake into the image", "Use ARG"], answer: 1,
    explain: "Images are distributed and may be public." },
  { q: "Runtime secrets are best delivered as…", options: ["ENV in Dockerfile", "Mounted files (e.g., /run/secrets) or runtime env from a manager", "COPY"], answer: 1,
    explain: "Files leak less than env for sensitive values." },
  { q: "BuildKit's --mount=type=secret…", options: ["Bakes the secret in", "Exposes it transiently to one RUN, not persisted in a layer", "Is insecure"], answer: 1,
    explain: "For build-time secrets like a private token." },
  { q: "Env vars are 'leaky' because…", options: ["They're encrypted", "They show in docker inspect, are inherited by children, appear in dumps", "They're files"], answer: 1,
    explain: "Prefer files for highly sensitive values." },
  { q: "Production secrets typically live in…", options: ["The Dockerfile", "A secrets manager (Vault/AWS/GCP) or k8s Secrets", "Git"], answer: 1,
    explain: "Central store with rotation and audit." },
  { q: "Kubernetes Secrets by default are…", options: ["Encrypted", "Base64-encoded (enable encryption-at-rest)", "Plaintext files in git"], answer: 1,
    explain: "Base64 is encoding, not encryption." },
  { q: "Cloud IAM instance roles are good because…", options: ["They store static secrets", "No stored secret — the runtime gets short-lived scoped creds", "They're free"], answer: 1,
    explain: "Nothing long-lived to leak." },
  { q: "The same image across dev/staging/prod differs only by…", options: ["The base image", "Configuration injected from the environment", "The Dockerfile"], answer: 1,
    explain: "One reproducible artifact, per-env config." },
  { q: "--env-file .env at runtime…", options: ["Bakes vars in the image", "Loads env vars when running the container", "Creates a volume"], answer: 1,
    explain: "Config supplied at run time." },
  { q: "Best practice for credential lifetime is…", options: ["Long-lived static", "Short-lived, rotated, scoped", "Never expire"], answer: 1,
    explain: "Limits blast radius if leaked." },
  { q: "Docker/Compose secrets are mounted at…", options: ["/etc/passwd", "/run/secrets", "/app/.env in a layer"], answer: 1,
    explain: "The app reads the secret from a file." },
  { q: "Committing secrets to git is…", options: ["Fine if private repo", "A leak risk — use .env (gitignored)/managers", "Encrypted"], answer: 1,
    explain: "Repos get cloned, forked, leaked." },
  { q: "Baking per-environment config into images causes…", options: ["Reproducibility", "Separate images per env (drift, unreproducible)", "Nothing"], answer: 1,
    explain: "One image + external config instead." },
  { q: "docker inspect can reveal…", options: ["Nothing", "A container's env vars (why env secrets leak)", "The source code"], answer: 1,
    explain: "Sensitive env values are visible." },
  { q: "The safest handling for a DB password is…", options: ["ENV in Dockerfile", "Mounted file from a secrets manager at runtime", "ARG"], answer: 1,
    explain: "Out of the image, injected at runtime." }
]},
{ title: "Quiz 7 · Debugging Containers",
  desc: "Logs, exit codes, exec/inspect, connectivity, OOM",
  questions: [
  { q: "Your FIRST step when a container misbehaves is…", options: ["Rebuild", "docker logs", "Delete the image"], answer: 1,
    explain: "The error is almost always in the logs." },
  { q: "docker ps -a shows…", options: ["Only running containers", "All containers including exited (with exit codes)", "Images"], answer: 1,
    explain: "See why/when something exited." },
  { q: "A container that 'exits immediately' usually means…", options: ["Docker is broken", "Its PID 1 process crashed or finished", "The image is missing"], answer: 1,
    explain: "A container lives only as long as its main process." },
  { q: "To get a shell inside a running container…", options: ["docker build", "docker exec -it <c> sh", "docker pull"], answer: 1,
    explain: "Poke around live." },
  { q: "To explore a crashing image interactively…", options: ["Delete it", "docker run -it --entrypoint sh myimage", "Rebuild"], answer: 1,
    explain: "Override the failing entrypoint to get a shell." },
  { q: "Exit code 137 usually means…", options: ["Success", "SIGKILL — often OOM-killed", "Bad syntax"], answer: 1,
    explain: "128 + 9; check memory limits." },
  { q: "Exit code 143 means…", options: ["Segfault", "SIGTERM (graceful stop)", "OOM"], answer: 1,
    explain: "128 + 15." },
  { q: "docker inspect gives…", options: ["Only logs", "Full JSON: env, mounts, network, exit code, OOMKilled flag", "Nothing useful"], answer: 1,
    explain: "Deep config/state details." },
  { q: "Two containers can't talk — first check…", options: ["CPU", "They're on the same user-defined network", "Disk"], answer: 1,
    explain: "Default bridge lacks name resolution." },
  { q: "An app unreachable even with -p may be bound to…", options: ["0.0.0.0", "127.0.0.1 inside the container", "The registry"], answer: 1,
    explain: "Bind to 0.0.0.0 to be reachable." },
  { q: "docker stats shows…", options: ["Image layers", "Live CPU/memory usage", "Networks"], answer: 1,
    explain: "See if a container is near its memory limit." },
  { q: "docker events streams…", options: ["Nothing", "Real-time daemon events (starts, stops, OOM kills)", "Logs only"], answer: 1,
    explain: "Catch kills/deaths as they happen." },
  { q: "Distroless images are hard to debug because…", options: ["They're huge", "They have no shell (exec sh fails)", "They can't run"], answer: 1,
    explain: "Use docker/kubectl debug or a debug variant." },
  { q: "kubectl debug (Kubernetes)…", options: ["Deletes the pod", "Attaches a debug container sharing the pod's namespaces", "Scales up"], answer: 1,
    explain: "Debug shell-less pods." },
  { q: "A build not using cache is usually because…", options: ["Docker is slow", "An early layer changed (reorder / check .dockerignore)", "The registry is down"], answer: 1,
    explain: "Cache busts cascade to later layers." },
  { q: "File changes not appearing in a dev container means…", options: ["Docker bug", "You're editing the image, not a bind mount", "OOM"], answer: 1,
    explain: "Bind-mount the source for live edits." },
  { q: "docker logs -f --tail 100…", options: ["Deletes logs", "Follows the last 100 lines live", "Rebuilds"], answer: 1,
    explain: "Tail + follow." },
  { q: "Exit code 0 means…", options: ["Crash", "Clean/successful exit", "OOM"], answer: 1,
    explain: "The process finished normally." },
  { q: "Permission denied on a volume often means…", options: ["Docker is down", "UID mismatch (non-root USER vs host file ownership)", "No network"], answer: 1,
    explain: "Align UIDs / fix ownership." },
  { q: "A mysterious sudden death with exit 137 is…", options: ["A network issue", "A memory problem until proven otherwise", "Always a bug in Docker"], answer: 1,
    explain: "OOM-killed; raise limit or fix the leak." }
]},
{ title: "Quiz 8 · Container Security",
  desc: "Non-root, capabilities, read-only FS, scanning, privileged",
  questions: [
  { q: "The #1 container security rule is…", options: ["Use latest", "Don't run as root (USER non-root)", "Expose all ports"], answer: 1,
    explain: "Escape as root = host root." },
  { q: "Root in the container maps to…", options: ["A random user", "Root on the host kernel", "nobody"], answer: 1,
    explain: "Shared kernel — escapes are dangerous." },
  { q: "Container isolation vs a VM is…", options: ["Stronger", "Weaker (shared kernel)", "The same"], answer: 1,
    explain: "Defense-in-depth: assume breach." },
  { q: "--privileged is dangerous because…", options: ["It's slow", "It grants near-full host access", "It's deprecated"], answer: 1,
    explain: "Almost never needed in prod." },
  { q: "Mounting /var/run/docker.sock into a container…", options: ["Is safe", "Effectively grants host root (control the daemon)", "Speeds builds"], answer: 1,
    explain: "Avoid entirely in untrusted contexts." },
  { q: "--cap-drop ALL then add-only-needed…", options: ["Breaks everything", "Limits what even root-in-container can do", "Is pointless"], answer: 1,
    explain: "Least privilege on Linux capabilities." },
  { q: "A read-only root filesystem (--read-only)…", options: ["Prevents the app from running", "Stops attackers writing/modifying the FS (use tmpfs for scratch)", "Is slower"], answer: 1,
    explain: "Hardening against persistence." },
  { q: "Image CVE scanning tools include…", options: ["git", "Trivy, Grype, Snyk, docker scout", "npm"], answer: 1,
    explain: "Gate CI on HIGH/CRITICAL findings." },
  { q: "A minimal base image improves security by…", options: ["Nothing", "Fewer packages (fewer CVEs) and no shell to exploit", "More tools"], answer: 1,
    explain: "distroless/alpine reduce attack surface." },
  { q: "no-new-privileges:true prevents…", options: ["Networking", "Privilege escalation (e.g., via setuid)", "Volumes"], answer: 1,
    explain: "A key runtime hardening flag." },
  { q: "In Kubernetes, hardening is set via…", options: ["Dockerfile only", "securityContext (runAsNonRoot, readOnlyRootFilesystem, drop caps)", "The registry"], answer: 1,
    explain: "Pod/container security controls." },
  { q: "seccomp/AppArmor/SELinux…", options: ["Speed up builds", "Restrict syscalls / enforce mandatory access control", "Are registries"], answer: 1,
    explain: "Extra kernel-level confinement." },
  { q: "Resource limits (memory/CPU) help security by…", options: ["Nothing", "Containing DoS/noisy-neighbor blast radius", "Encrypting data"], answer: 1,
    explain: "Limit what a compromised container consumes." },
  { q: "For hostile multi-tenant workloads, consider…", options: ["Running as root", "VM-based sandboxes (gVisor, Kata, Firecracker)", "--privileged"], answer: 1,
    explain: "Stronger isolation than plain containers." },
  { q: "Secrets in image layers are…", options: ["Encrypted", "Readable by anyone with the image", "Deleted automatically"], answer: 1,
    explain: "Inject at runtime instead." },
  { q: "Pinning base images by digest helps…", options: ["Speed", "Reproducibility + supply-chain integrity", "Nothing"], answer: 1,
    explain: "Immutable content reference." },
  { q: "namespaces + cgroups provide…", options: ["A guest kernel", "Isolation (view) + resource limits — but shared kernel", "Encryption"], answer: 1,
    explain: "The basis of container isolation." },
  { q: "Many official images ship…", options: ["Only root", "A non-root user (e.g., 'node') you can USE", "No users"], answer: 1,
    explain: "Use it via USER." },
  { q: "Scanning should run…", options: ["Never", "In CI, failing the build on critical CVEs", "Only in prod after deploy"], answer: 1,
    explain: "Block vulnerable images before deploy." },
  { q: "Running as root + writable FS + all caps + host mounts =", options: ["Secure", "Trivial host takeover after any RCE", "Faster"], answer: 1,
    explain: "The anti-pattern to avoid entirely." }
]},
{ title: "Quiz 9 · Internals, Registry & Supply Chain",
  desc: "Namespaces/cgroups, union FS, registries, tags vs digests, SBOM",
  questions: [
  { q: "A container is technically…", options: ["A mini-VM", "A host process isolated by namespaces + cgroups + union FS", "A hypervisor"], answer: 1,
    explain: "No guest OS." },
  { q: "Namespaces control…", options: ["How much you use", "WHAT a process can SEE (PID/NET/MNT/UTS/IPC/USER)", "Encryption"], answer: 1,
    explain: "Isolated views of resources." },
  { q: "cgroups control…", options: ["What you see", "HOW MUCH you use (CPU/memory/IO/PIDs)", "DNS"], answer: 1,
    explain: "Resource limits; cause OOM kills." },
  { q: "The union filesystem (overlay2) provides…", options: ["A single flat FS", "Layered, copy-on-write filesystem (shared read-only + writable layer)", "Encryption"], answer: 1,
    explain: "Why images layer and share." },
  { q: "Copy-on-write means writing a lower-layer file…", options: ["Edits the shared layer", "Copies it up to the writable layer first", "Fails"], answer: 1,
    explain: "Keeps shared layers immutable." },
  { q: "Read-only image layers are…", options: ["Copied per container", "SHARED across containers from the image", "Encrypted"], answer: 1,
    explain: "Space-efficient." },
  { q: "The container runtime stack is roughly…", options: ["CLI only", "docker/dockerd → containerd → runc", "npm → node"], answer: 1,
    explain: "runc creates the namespaces/cgroups." },
  { q: "Kubernetes talks to the runtime via…", options: ["Docker only", "the CRI (e.g., containerd) — no Docker required", "SSH"], answer: 1,
    explain: "OCI/CRI standards decouple from Docker." },
  { q: "A registry is…", options: ["A container", "The distribution hub images are pushed/pulled from", "A volume"], answer: 1,
    explain: "Docker Hub, ghcr, ECR, ACR, Harbor…" },
  { q: "A tag is…", options: ["Immutable content", "A MUTABLE pointer that can be re-pushed", "A digest"], answer: 1,
    explain: "latest can change over time." },
  { q: "A digest (sha256:…) is…", options: ["Mutable", "IMMUTABLE — derived from the image content", "A tag"], answer: 1,
    explain: "Pin by digest for reproducibility." },
  { q: "Deploying :latest in production is bad because…", options: ["It's slow", "It's mutable → irreproducible/tampering risk", "It's expensive"], answer: 1,
    explain: "Deploy by digest or immutable version tag." },
  { q: "cosign is used to…", options: ["Build images", "Sign and verify image provenance", "Scan CVEs"], answer: 1,
    explain: "Sigstore signing; verify integrity/origin." },
  { q: "An SBOM is…", options: ["A base image", "A bill of materials — every package/version in the image", "A network"], answer: 1,
    explain: "Answer 'are we affected by this CVE?' fast." },
  { q: "SLSA provenance/attestations record…", options: ["The color", "HOW/WHERE the image was built (commit, CI run), cryptographically", "The size"], answer: 1,
    explain: "Trust the artifact's origin." },
  { q: "Enforcing 'only signed images run' uses…", options: ["A firewall", "Admission policies (Kyverno, OPA Gatekeeper, policy-controller)", "docker logs"], answer: 1,
    explain: "Reject unsigned/untrusted images at deploy." },
  { q: "Typosquatted public images are mitigated by…", options: ["Using any image", "Trusted/official images, private mirrors, allowlists", "latest tag"], answer: 1,
    explain: "Vet what you pull." },
  { q: "A memory limit exceeded triggers…", options: ["A restart only", "The kernel OOM killer (cgroups) → exit 137", "A rebuild"], answer: 1,
    explain: "cgroups enforce the ceiling." },
  { q: "The PID namespace makes the container see its main process as…", options: ["PID 9999", "PID 1", "The host's PID"], answer: 1,
    explain: "Isolated process tree." },
  { q: "Scan-on-push at the registry…", options: ["Does nothing", "Blocks vulnerable images at storage time", "Deletes images"], answer: 1,
    explain: "Harbor/ECR/Scout feature." }
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review across the whole Docker track",
  questions: [
  { q: "A container vs VM: the container…", options: ["Has its own kernel", "Shares the host kernel (lightweight, weaker isolation)", "Needs a hypervisor"], answer: 1,
    explain: "Core distinction." },
  { q: "For DB persistence, use…", options: ["The container FS", "A named volume (or external managed DB)", "ENV"], answer: 1,
    explain: "The writable layer is ephemeral." },
  { q: "-p 8080:80 maps…", options: ["container 8080 → host 80", "host 8080 → container 80", "nothing"], answer: 1,
    explain: "-p HOST:CONTAINER." },
  { q: "depends_on guarantees…", options: ["Readiness", "Start order only", "Networking"], answer: 1,
    explain: "Add healthchecks + app retries for readiness." },
  { q: "COPY --from=builder is central to…", options: ["Compose", "Multi-stage builds", "Networking"], answer: 1,
    explain: "Copy only the artifact into a clean stage." },
  { q: "A secret in ENV/ARG in a Dockerfile is…", options: ["Encrypted", "Readable via history/inspect (leak)", "Deleted"], answer: 1,
    explain: "Inject at runtime instead." },
  { q: "Your first debugging step is…", options: ["Rebuild", "docker logs", "Delete the image"], answer: 1,
    explain: "The error is almost always there." },
  { q: "Exit code 137 =", options: ["Success", "OOM/SIGKILL", "Syntax error"], answer: 1,
    explain: "Check memory limits." },
  { q: "The #1 security rule is…", options: ["Use latest", "Don't run as root", "Expose all ports"], answer: 1,
    explain: "Escape as root = host root." },
  { q: "Never do this in production:", options: ["Use volumes", "--privileged / mount the docker socket", "Scan images"], answer: 1,
    explain: "Effectively host root." },
  { q: "Deploy by … for reproducibility.", options: [":latest", "immutable digest (sha256)", "a random tag"], answer: 1,
    explain: "Tags are mutable pointers." },
  { q: "A container = a process +", options: ["a guest OS", "namespaces + cgroups + union FS", "a hypervisor"], answer: 1,
    explain: "Kernel features around a process." },
  { q: "cgroups enforce…", options: ["What you see", "Resource limits (and OOM kills)", "DNS"], answer: 1,
    explain: "CPU/memory/IO ceilings." },
  { q: "For the smallest image with a Go binary…", options: ["ubuntu", "scratch/distroless (multi-stage)", "node:22"], answer: 1,
    explain: "Ship just the binary." },
  { q: "Order Dockerfile layers…", options: ["Randomly", "Least→most changing (deps before source)", "Alphabetically"], answer: 1,
    explain: "Maximize cache reuse." },
  { q: "Multi-container apps get name-based DNS via…", options: ["The default bridge", "A user-defined network (or Compose)", "Host mode"], answer: 1,
    explain: "No hardcoded IPs." },
  { q: "An SBOM lets you…", options: ["Build faster", "Query the fleet for a CVE's affected packages instantly", "Encrypt"], answer: 1,
    explain: "Fast vulnerability response." },
  { q: "EXPOSE without -p…", options: ["Publishes the port", "Only documents it", "Opens a firewall"], answer: 1,
    explain: "Publishing needs -p." },
  { q: ".dockerignore keeps out…", options: ["The Dockerfile", "node_modules/.git/.env (context + secrets)", "The base image"], answer: 1,
    explain: "Smaller context, stable cache, no leaks." },
  { q: "Scan images for CVEs…", options: ["Never", "In CI, failing on critical findings", "Only after an incident"], answer: 1,
    explain: "Block vulnerable images pre-deploy." }
]}
);
