// Docker quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Containers vs VMs & Basics",
  desc: "What a container is, vs VMs, images vs containers, the daemon",
  questions: [
  { q: "A container differs from a VM in that it…", options: ["Runs its own guest kernel", "Shares the host kernel (isolated by namespaces/cgroups)", "Needs a hypervisor"], answer: 1,
    explain: "No guest OS — that's why containers are lightweight and start fast." },
  { q: "Containers start in milliseconds because…", options: ["They boot a tiny OS", "There's no guest kernel to boot — just a process", "They use SSD"], answer: 1,
    explain: "A container is a host process, not a booted machine." },
  { q: "Compared to a VM, container isolation is…", options: ["Stronger", "Weaker (shared kernel)", "Identical"], answer: 1,
    explain: "A kernel bug/misconfig can cross the boundary — security matters." },
  { q: "An image is…", options: ["A running process", "A read-only template (layers) you run containers from", "A network"], answer: 1,
    explain: "Image = blueprint; container = a running instance of it." },
  { q: "A container is…", options: ["The same as an image", "A running (or stopped) instance of an image", "A registry"], answer: 1,
    explain: "Many containers can run from one image." },
  { q: "A container lives as long as…", options: ["The host is up", "Its PID 1 (main) process runs", "24 hours"], answer: 1,
    explain: "When the main process exits, the container stops." },
  { q: "docker run does what?", options: ["Only builds", "Creates + starts a container from an image", "Pushes to a registry"], answer: 1,
    explain: "It pulls (if needed), creates, and starts." },
  { q: "The Docker daemon (dockerd)…", options: ["Is the CLI", "Is the background service that builds/runs containers", "Is a registry"], answer: 1,
    explain: "The CLI talks to the daemon via its API." },
  { q: "'Works on my machine' problems are reduced because…", options: ["Docker is faster", "The image bundles app + deps + config consistently", "It uses more RAM"], answer: 1,
    explain: "Same image runs the same everywhere." },
  { q: "Containers are ideal for…", options: ["Only Linux GUIs", "Packaging and running apps consistently across environments", "Replacing databases"], answer: 1,
    explain: "Portable, reproducible app packaging." },
  { q: "docker ps shows…", options: ["Images", "Running containers (add -a for all)", "Volumes"], answer: 1,
    explain: "docker ps -a includes stopped/exited ones." },
  { q: "docker images lists…", options: ["Containers", "Local images", "Networks"], answer: 1,
    explain: "Images stored on the host." },
  { q: "A stopped container…", options: ["Is deleted", "Still exists (can be started again) until removed", "Loses its config"], answer: 1,
    explain: "docker start restarts it; docker rm deletes it." },
  { q: "VMs are preferable when you need…", options: ["Fast startup", "Strong isolation / a different kernel", "Smaller size"], answer: 1,
    explain: "Hostile multi-tenant or different-OS workloads." },
  { q: "The OCI standard ensures…", options: ["Docker lock-in", "Interoperable image/runtime formats across tools", "Faster CPUs"], answer: 1,
    explain: "Images run on containerd, Podman, k8s, etc." },
  { q: "A container's default user is…", options: ["A random user", "root (uid 0) unless you set USER", "nobody"], answer: 1,
    explain: "A security concern addressed later." },
  { q: "docker pull nginx fetches…", options: ["Source code", "The nginx image from a registry", "A container"], answer: 1,
    explain: "Images come from registries (default Docker Hub)." },
  { q: "Containers are 'ephemeral' meaning…", options: ["They never stop", "Their writable filesystem is disposable on removal", "They can't be deleted"], answer: 1,
    explain: "Persist data in volumes, not the container." },
  { q: "One image can produce…", options: ["Only one container", "Many identical containers", "Only VMs"], answer: 1,
    explain: "Scale horizontally from one image." },
  { q: "Docker Desktop on Mac/Windows runs Linux containers via…", options: ["Native Windows kernel", "A lightweight Linux VM", "The cloud"], answer: 1,
    explain: "Linux containers need a Linux kernel." }
]},
{ title: "Quiz 2 · Images, Layers & Dockerfile",
  desc: "Dockerfile instructions, layers, caching, CMD vs ENTRYPOINT",
  questions: [
  { q: "Each Dockerfile instruction creates…", options: ["A container", "A layer", "A network"], answer: 1,
    explain: "Images are stacks of read-only layers." },
  { q: "FROM specifies…", options: ["The final command", "The base image to build on", "The ports"], answer: 1,
    explain: "Every Dockerfile starts from a base." },
  { q: "For best cache reuse, you should…", options: ["COPY . . first", "Copy manifests + install deps BEFORE copying source", "Never copy"], answer: 1,
    explain: "Code changes shouldn't bust the deps-install layer." },
  { q: "A cache-busted layer invalidates…", options: ["Only itself", "Itself and every layer after it", "Nothing"], answer: 1,
    explain: "Order least→most changing." },
  { q: "CMD vs ENTRYPOINT: CMD is…", options: ["Always fixed", "The default command/args, easily overridden at run", "The base image"], answer: 1,
    explain: "ENTRYPOINT sets the executable; CMD gives default args." },
  { q: "RUN executes…", options: ["At container start", "At BUILD time, creating a layer", "Never"], answer: 1,
    explain: "CMD/ENTRYPOINT run at container start." },
  { q: "COPY vs ADD: prefer COPY because…", options: ["ADD is faster", "ADD has surprising extras (URL fetch, auto-extract)", "COPY compresses"], answer: 1,
    explain: "Use COPY unless you need ADD's features." },
  { q: "WORKDIR does what?", options: ["Copies files", "Sets the working directory for subsequent instructions", "Exposes a port"], answer: 1,
    explain: "Creates + cd's into the directory." },
  { q: "EXPOSE…", options: ["Publishes a port to the host", "Documents the listening port (doesn't publish)", "Opens a firewall"], answer: 1,
    explain: "Publishing is -p at run time." },
  { q: "To combine install + cleanup so size shrinks…", options: ["Use separate RUNs", "Do it in ONE RUN (&&)", "Use ADD"], answer: 1,
    explain: "Cleanup in a later layer doesn't shrink earlier ones." },
  { q: "docker build -t myapp:1.0 . does…", options: ["Runs a container", "Builds an image tagged myapp:1.0 from the context", "Pushes it"], answer: 1,
    explain: "The '.' is the build context." },
  { q: "The build context is…", options: ["The registry", "The files sent to the daemon for the build", "The base image"], answer: 1,
    explain: ".dockerignore trims it." },
  { q: "ENV sets…", options: ["Build-only vars", "Environment variables baked into the image/runtime", "Ports"], answer: 1,
    explain: "Don't put secrets here — they persist in layers." },
  { q: "ARG is…", options: ["A runtime env var", "A build-time variable (visible in docker history)", "A volume"], answer: 1,
    explain: "Not for secrets — it leaks into history." },
  { q: "docker history myimage shows…", options: ["Run logs", "Layers and their sizes/commands", "Networks"], answer: 1,
    explain: "Find the fat layer / leaked build args." },
  { q: "Layers being read-only means…", options: ["You can't run them", "They're shared across containers; a thin writable layer sits on top", "They can't be cached"], answer: 1,
    explain: "Space-efficient sharing." },
  { q: "A good Dockerfile orders instructions…", options: ["Randomly", "Least-frequently-changing first", "Alphabetically"], answer: 1,
    explain: "Maximizes cache hits." },
  { q: "The exec form CMD [\"node\",\"a.js\"] is preferred over shell form because…", options: ["It's shorter", "It runs the process directly as PID 1 (signals work)", "It's colored"], answer: 1,
    explain: "Shell form wraps in /bin/sh -c, breaking signal handling." },
  { q: "A .dockerignore file…", options: ["Ignores containers", "Excludes files from the build context", "Deletes images"], answer: 1,
    explain: "Like .gitignore, for builds." },
  { q: "LABEL is used for…", options: ["Running code", "Adding metadata (maintainer, version) to the image", "Networking"], answer: 1,
    explain: "Key/value metadata." }
]},
{ title: "Quiz 3 · Volumes & Networking",
  desc: "Persistence, named volumes vs bind mounts, bridge/DNS, ports",
  questions: [
  { q: "Data written inside a container (no volume) is…", options: ["Persistent", "Lost when the container is removed", "Synced to the host"], answer: 1,
    explain: "The writable layer is ephemeral." },
  { q: "A named volume is…", options: ["A host path you pick", "Docker-managed persistent storage", "A network"], answer: 1,
    explain: "Best for production data (DBs)." },
  { q: "A bind mount…", options: ["Is Docker-managed", "Maps a specific host directory into the container", "Is memory-only"], answer: 1,
    explain: "Great for live code editing in dev." },
  { q: "For a database's data in production, use…", options: ["The container FS", "A named volume (or external managed DB)", "A bind mount to /tmp"], answer: 1,
    explain: "Survives container recreation." },
  { q: "-p 8080:80 means…", options: ["container:8080 → host:80", "host:8080 → container:80", "Nothing"], answer: 1,
    explain: "-p HOST:CONTAINER publishes the port." },
  { q: "EXPOSE without -p means…", options: ["Port is reachable from host", "Port is documented but NOT published", "Firewall opens"], answer: 1,
    explain: "You still need -p to reach it from the host." },
  { q: "On the DEFAULT bridge, containers…", options: ["Resolve each other by name", "Do NOT get name resolution", "Can't communicate"], answer: 1,
    explain: "Use a user-defined network for DNS by name." },
  { q: "A user-defined network gives…", options: ["Slower networking", "DNS resolution by container name", "No isolation"], answer: 1,
    explain: "api can reach 'db' by name — no hardcoded IPs." },
  { q: "Hardcoding a container's IP is bad because…", options: ["IPs are secret", "IPs change on restart", "It's slower"], answer: 1,
    explain: "Use service/container names instead." },
  { q: "tmpfs mounts store data…", options: ["On disk", "In memory only (gone on stop)", "In a registry"], answer: 1,
    explain: "Good for secrets/temp data." },
  { q: "docker network create appnet creates…", options: ["A volume", "A user-defined network with DNS", "A container"], answer: 1,
    explain: "Attach containers with --network appnet." },
  { q: "-p 127.0.0.1:8080:80 does…", options: ["Exposes to the internet", "Binds only to localhost", "Nothing"], answer: 1,
    explain: "Restricts access to the host itself." },
  { q: "Host network mode (--network host)…", options: ["Adds isolation", "Shares the host's network stack (no port mapping, less isolation)", "Blocks all ports"], answer: 1,
    explain: "Max performance, weaker isolation." },
  { q: "'none' network mode means…", options: ["Default bridge", "No networking (fully isolated)", "Host mode"], answer: 1,
    explain: "For fully offline containers." },
  { q: "Overlay networks are for…", options: ["Single host", "Multi-host container communication (orchestration)", "Volumes"], answer: 1,
    explain: "Swarm/Kubernetes across machines." },
  { q: "Compose helps networking by…", options: ["Nothing", "Auto-creating a user-defined network (services reach each other by name)", "Disabling DNS"], answer: 1,
    explain: "Why api can use postgres://db:5432." },
  { q: "The 'stateless container' principle means…", options: ["No data anywhere", "Design so containers can be killed/recreated; state lives in volumes", "Never restart"], answer: 1,
    explain: "Orchestrators recreate containers freely." },
  { q: "Bind-mounting over node_modules can…", options: ["Speed builds", "Shadow the image's modules with the host's", "Encrypt them"], answer: 1,
    explain: "Use an anonymous volume for node_modules." },
  { q: "docker volume ls lists…", options: ["Networks", "Volumes", "Images"], answer: 1,
    explain: "Manage persistent storage." },
  { q: "Removing a container with -v (docker rm -v)…", options: ["Keeps volumes", "Also removes anonymous volumes", "Removes images"], answer: 1,
    explain: "Named volumes persist unless explicitly removed." }
]},
{ title: "Quiz 4 · Docker Compose",
  desc: "Multi-container apps, service DNS, depends_on, volumes, profiles",
  questions: [
  { q: "Docker Compose is for…", options: ["Building base images", "Declaring & running multi-container apps in one YAML", "Scanning CVEs"], answer: 1,
    explain: "up/down the whole stack with one command." },
  { q: "In Compose, services reach each other by…", options: ["Hardcoded IP", "Service NAME (auto DNS on a shared network)", "MAC address"], answer: 1,
    explain: "api → postgres://db:5432 using service name 'db'." },
  { q: "depends_on controls…", options: ["Readiness", "START ORDER only (not readiness)", "Networking"], answer: 1,
    explain: "The dependency's app may still be initializing." },
  { q: "To wait until a dependency is READY…", options: ["depends_on alone", "healthcheck + condition: service_healthy (and app retries)", "sleep 60"], answer: 1,
    explain: "Gate on health and make the app resilient." },
  { q: "docker compose up -d does…", options: ["Only builds", "Builds/creates network/starts all services detached", "Deletes volumes"], answer: 1,
    explain: "-d = detached (background)." },
  { q: "docker compose down -v also…", options: ["Keeps data", "Removes named volumes (data loss!)", "Rebuilds"], answer: 1,
    explain: "Be careful in production." },
  { q: "'build:' in a service means…", options: ["Pull an image", "Build from a local Dockerfile", "Nothing"], answer: 1,
    explain: "'image:' pulls a prebuilt one instead." },
  { q: "A named volume in Compose is declared…", options: ["Only inline", "Under top-level 'volumes:' and referenced by services", "In .env"], answer: 1,
    explain: "For DB persistence across down/up." },
  { q: "compose.override.yaml is…", options: ["Ignored", "Auto-merged (great for dev-only settings)", "For prod only"], answer: 1,
    explain: "e.g., bind mounts for live editing in dev." },
  { q: "env_file: .env lets you…", options: ["Bake secrets in images", "Load environment variables from a file", "Create networks"], answer: 1,
    explain: "Keep .env gitignored." },
  { q: "Profiles (--profile debug) enable…", options: ["All services", "Optional services only when requested", "Volumes"], answer: 1,
    explain: "Keep optional tools out of the default up." },
  { q: "Compose is best suited for…", options: ["Multi-host production at scale", "Single-host dev and simple deploys", "Replacing databases"], answer: 1,
    explain: "Kubernetes handles multi-host orchestration." },
  { q: "You outgrow Compose for Kubernetes when you need…", options: ["A YAML file", "Multi-host scheduling, autoscaling, self-healing, rolling updates", "Volumes"], answer: 1,
    explain: "Cluster-scale orchestration." },
  { q: "docker compose logs -f api…", options: ["Deletes logs", "Follows one service's logs", "Restarts api"], answer: 1,
    explain: "-f = follow." },
  { q: "Secrets committed in compose.yaml are…", options: ["Safe", "A leak risk — use .env/secrets instead", "Encrypted"], answer: 1,
    explain: "Keep credentials out of version control." },
  { q: "The Compose network is…", options: ["The default bridge", "A user-defined network (name resolution included)", "Host mode"], answer: 1,
    explain: "That's why service-name DNS works." },
  { q: "Multiple compose files (-f a -f b)…", options: ["Conflict", "Merge/override in order (e.g., base + prod)", "Are illegal"], answer: 1,
    explain: "Layer environment-specific config." },
  { q: "'restart: unless-stopped' means…", options: ["Never restart", "Auto-restart on failure/reboot unless you stopped it", "Restart once"], answer: 1,
    explain: "A restart policy for resilience." },
  { q: "The concepts in Compose (services, networks, volumes)…", options: ["Don't transfer", "Map directly to Kubernetes concepts", "Are Docker-only forever"], answer: 1,
    explain: "Compose is a conceptual on-ramp to k8s." },
  { q: "docker compose ps shows…", options: ["Images", "The status of the stack's services", "Volumes only"], answer: 1,
    explain: "Which services are up/healthy." }
]},
{ title: "Quiz 5 · Multi-stage Builds & Optimization",
  desc: "Smaller images, base choice, COPY --from, layers, BuildKit",
  questions: [
  { q: "Multi-stage builds let you…", options: ["Run multiple containers", "Build in one stage and ship only the artifact from a clean stage", "Skip Dockerfiles"], answer: 1,
    explain: "The build toolchain is discarded." },
  { q: "The key multi-stage instruction is…", options: ["RUN", "COPY --from=builder", "EXPOSE"], answer: 1,
    explain: "Copies just the artifact from a previous stage." },
  { q: "Multi-stage builds improve…", options: ["Only speed", "BOTH image size and security (smaller attack surface)", "Only colors"], answer: 1,
    explain: "Less software = fewer CVEs." },
  { q: "For the smallest base with a static Go binary, use…", options: ["ubuntu", "scratch or distroless", "node:22"], answer: 1,
    explain: "Just the binary, no OS/shell." },
  { q: "distroless/scratch images lack…", options: ["A binary", "A shell and package manager", "The app"], answer: 1,
    explain: "Smaller attack surface, harder to debug." },
  { q: "In the runtime stage, install deps with…", options: ["npm ci (all)", "npm ci --omit=dev (prod only)", "npm install -g everything"], answer: 1,
    explain: "Don't ship dev dependencies." },
  { q: "Base image size ranking (roughly): node:22 vs alpine…", options: ["alpine is bigger", "node:22 (~1GB) ≫ node:22-alpine (~150MB)", "Equal"], answer: 1,
    explain: "Pick the smallest base that works." },
  { q: "A caution with Alpine (musl libc)…", options: ["It's always broken", "Native modules built for glibc may misbehave — test", "It's huge"], answer: 1,
    explain: "musl vs glibc differences." },
  { q: "Cleaning apt caches must happen…", options: ["In any layer", "In the SAME RUN that installed", "Never"], answer: 1,
    explain: "Later cleanup doesn't shrink earlier layers." },
  { q: "--target=builder lets you…", options: ["Skip building", "Build only up to a named stage (e.g., for CI tests)", "Push"], answer: 1,
    explain: "Handy for a test stage." },
  { q: "BuildKit's --mount=type=cache…", options: ["Leaks secrets", "Persists a package-manager cache across builds", "Deletes cache"], answer: 1,
    explain: "Faster repeat installs (npm/pip/apt)." },
  { q: "docker history helps optimization by…", options: ["Running the app", "Showing per-layer sizes to find bloat", "Signing images"], answer: 1,
    explain: "Locate the fat layer." },
  { q: "Copying too much from the builder…", options: ["Is fine", "Reintroduces bloat — copy only the artifact", "Speeds pulls"], answer: 1,
    explain: "Copy the binary/dist, not source + caches." },
  { q: "Smaller images benefit…", options: ["Only storage", "Pull speed, deploy speed, cost, AND attack surface", "Nothing"], answer: 1,
    explain: "Multiple wins at once." },
  { q: "Compiled languages benefit most from multi-stage because…", options: ["They can't be containerized", "A self-contained binary needs no toolchain at runtime", "They're interpreted"], answer: 1,
    explain: "Ship a tiny binary in scratch/distroless." },
  { q: ".dockerignore helps optimization by…", options: ["Nothing", "Shrinking context, stabilizing cache, avoiding leaked files", "Deleting images"], answer: 1,
    explain: "Keep node_modules/.git/.env out." },
  { q: "Two sometimes-competing goals are…", options: ["Color and font", "Small final image vs fast builds", "CPU and GPU"], answer: 1,
    explain: "Multi-stage for size; layer/cache for speed." },
  { q: "BuildKit builds independent stages…", options: ["Serially only", "In parallel", "Never"], answer: 1,
    explain: "Faster multi-stage builds." },
  { q: "The 'dive' tool is used to…", options: ["Run containers", "Explore image layers and find wasted space", "Deploy"], answer: 1,
    explain: "Interactive per-layer inspection." },
  { q: "A single-stage build with build tools in the final image…", options: ["Is smallest", "Ships unused toolchain (bloat + attack surface)", "Is required"], answer: 1,
    explain: "The problem multi-stage solves." }
]}
);
