// LeetCode Patterns quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Binary Tree Patterns & Topological Sort",
  desc: "Recursive tree skeleton, range-based BST validation, DAG ordering, cycle detection",
  questions: [
  { q: "Most binary tree problems fit a recursive skeleton where you define…", options: ["Only the base case", "Base case, recursive calls on children, and how to COMBINE results", "Only the combine step"], answer: 1,
    explain: "Three design decisions define each specific problem." },
  { q: "In 'Diameter of Binary Tree,' the helper function RETURNS…", options: ["The diameter directly", "HEIGHT — while tracking diameter as a side effect", "Nothing"], answer: 1,
    explain: "What a function returns isn't always the same as the final answer." },
  { q: "Validating a BST correctly requires…", options: ["Only comparing a node to its immediate children", "Passing a (min, max) RANGE down through the whole recursion", "Sorting the tree first"], answer: 1,
    explain: "Local-only checks miss violations several levels deep." },
  { q: "Lowest Common Ancestor is found by…", options: ["Finding paths to both nodes separately, then comparing", "Letting p/q signals bubble up, converging at the first node with different-subtree hits", "Sorting the tree"], answer: 1,
    explain: "An elegant single-pass approach." },
  { q: "maxDepth's base case (an empty subtree) returns…", options: ["1", "0", "-1"], answer: 1,
    explain: "An empty tree has height 0." },
  { q: "Recomputing height inside a separate traversal for every node causes…", options: ["O(n) total", "O(n²) total — height recomputed repeatedly", "O(log n)"], answer: 1,
    explain: "Compute auxiliary values in the SAME traversal as the main check." },
  { q: "Topological sort orders nodes of…", options: ["Any graph", "A DIRECTED ACYCLIC GRAPH (DAG)", "An undirected graph only"], answer: 1,
    explain: "Models 'must happen before' dependencies." },
  { q: "Kahn's algorithm processes nodes with…", options: ["The highest in-degree first", "ZERO in-degree first (no unmet prerequisites)", "Random order"], answer: 1,
    explain: "BFS-based topological sort." },
  { q: "Kahn's algorithm detects a cycle when…", options: ["The queue is empty at the start", "order.length is LESS than the total number of nodes at the end", "It never detects cycles"], answer: 1,
    explain: "Cyclic nodes never reach in-degree zero." },
  { q: "DFS-based topological sort pushes nodes onto the result…", options: ["Before exploring children", "AFTER fully exploring all descendants (post-order)", "In a fixed order"], answer: 1,
    explain: "This is why the final result must be reversed." },
  { q: "The DFS-based topological sort result must be…", options: ["Sorted", "REVERSED at the end", "Left as-is"], answer: 1,
    explain: "Post-order finish sequence is backward from the desired order." },
  { q: "The three-state (0/1/2) visited tracking in DFS topological sort distinguishes…", options: ["Nothing useful", "'In progress' (on current path) from 'fully done' — detects back-edges/cycles", "Only visited vs unvisited"], answer: 1,
    explain: "Revisiting a state-1 node means a cycle." },
  { q: "'Course Schedule' (can all courses be finished) is fundamentally…", options: ["A binary search problem", "A cycle-detection problem on a dependency graph", "A sliding window problem"], answer: 1,
    explain: "If there's a cycle, courses can't all be completed." },
  { q: "'Alien Dictionary' builds a graph by…", options: ["Sorting characters alphabetically", "Comparing ADJACENT words to infer character-order edges", "Random assignment"], answer: 1,
    explain: "Then topologically sorts the resulting character graph." },
  { q: "A tree traversal never needs a visited set because…", options: ["Trees can have cycles too", "Trees are cycle-free by definition", "It's optional either way"], answer: 1,
    explain: "General graphs DO need explicit visited tracking." },
  { q: "'What does this function return?' is described as…", options: ["An unimportant detail", "The single most important design question in tree recursion", "Only relevant for BSTs"], answer: 1,
    explain: "Drives the whole recursive design." },
  { q: "In-degree in a topological sort context means…", options: ["Outgoing edges", "The number of INCOMING edges (unmet prerequisites)", "The node's depth"], answer: 1,
    explain: "Decremented as prerequisites get processed." },
  { q: "A valid topological order for a given DAG is…", options: ["Always unique", "Often NOT unique — multiple valid orderings can exist", "Impossible to compute"], answer: 1,
    explain: "Problems typically accept any correct order." },
  { q: "Serialize/deserialize a binary tree commonly uses…", options: ["Only in-order traversal", "Pre-order traversal WITH null markers", "Binary search"], answer: 1,
    explain: "Null markers let deserialization reconstruct the exact structure." },
  { q: "Kahn's (BFS) vs DFS-based topological sort — both…", options: ["Give different valid orderings only one is correct", "Are equally valid ways to produce A correct topological order", "Only Kahn's is correct"], answer: 1,
    explain: "Choose based on context (already doing DFS, or need explicit level-like processing)." }
]},
{ title: "Quiz 7 · Union-Find & Heaps/Top-K",
  desc: "Path compression, union by rank, bounded heaps, streaming top-K",
  questions: [
  { q: "Union-Find (DSU) supports two operations:", options: ["Insert and delete", "find (which group) and union (merge groups)", "Push and pop"], answer: 1,
    explain: "Both nearly O(1) amortized with optimizations." },
  { q: "Path compression works by…", options: ["Deleting nodes", "Rewiring visited nodes to point DIRECTLY at the root during find()", "Sorting the parent array"], answer: 1,
    explain: "Flattens the tree for future lookups." },
  { q: "Union by rank always attaches…", options: ["The taller tree under the shorter one", "The SHORTER tree under the TALLER tree's root", "A random tree under another"], answer: 1,
    explain: "Bounds height growth to O(log n) even without compression." },
  { q: "Combined, path compression + union by rank give amortized time of…", options: ["O(n)", "O(α(n)) — inverse Ackermann, effectively O(1)", "O(log n) always"], answer: 1,
    explain: "α(n) ≤ 5 for any practically possible n." },
  { q: "Checking 'same component' should compare…", options: ["x === y directly", "find(x) === find(y) — the ROOTS", "Nothing — just call union()"], answer: 1,
    explain: "Comparing raw values checks identity, not group membership." },
  { q: "union()'s return value (true/false) is useful for…", options: ["Nothing", "Detecting 'this edge creates a cycle' or counting merges", "Only debugging"], answer: 1,
    explain: "false means the two elements were already connected." },
  { q: "Union-Find is preferred over BFS/DFS specifically when…", options: ["The graph is static and queried once", "Edges arrive INCREMENTALLY and connectivity is queried repeatedly", "You need the actual path between nodes"], answer: 1,
    explain: "Union-Find only tracks connectivity, not paths." },
  { q: "'Redundant Connection' (find the edge creating a cycle) is solved with…", answer: 1, options: ["Binary search", "Union-Find — the first edge where union() returns false", "A trie"],
    explain: "Process edges in order; the first already-connected pair is the answer." },
  { q: "A min-heap gives O(1) access to…", options: ["The maximum element", "The MINIMUM element", "A random element"], answer: 1,
    explain: "That's the defining property of a min-heap." },
  { q: "To find the K LARGEST elements, use a…", options: ["Max-heap of size K", "MIN-heap of size K — evict the smallest candidate", "Sorted array only"], answer: 1,
    explain: "The counter-intuitive but essential heap inversion." },
  { q: "To find the K SMALLEST elements, use a…", options: ["Min-heap of size K", "MAX-heap of size K — evict the largest candidate", "No heap needed"], answer: 1,
    explain: "Symmetric to the top-K-largest case." },
  { q: "Bounding a heap to size K changes complexity from…", options: ["O(n) to O(n²)", "O(n log n) (full sort) to O(n log K)", "O(1) to O(n)"], answer: 1,
    explain: "A real asymptotic win when K ≪ n." },
  { q: "Top K Frequent Elements combines…", options: ["Only sorting", "A frequency hash map + a bounded heap on (value, count) pairs", "Only binary search"], answer: 1,
    explain: "A common two-step pattern composition." },
  { q: "Merge K Sorted Lists with a heap achieves…", options: ["O(N·k)", "O(N log k) — never holding more than k candidates at once", "O(N²)"], answer: 1,
    explain: "Better than naive pairwise merging for large k." },
  { q: "Merge K Sorted Lists seeds the heap with…", options: ["All nodes from all lists", "Just the HEAD node of each list", "Nothing initially"], answer: 1,
    explain: "Each popped node's successor is pushed to represent its list going forward." },
  { q: "Heaps are especially valuable for…", options: ["One-time sorting only", "STREAMING/incrementally-arriving data needing a continuously maintained min/max", "Static arrays only"], answer: 1,
    explain: "'Median of a data stream' is the canonical example." },
  { q: "'Find Median from Data Stream' typically uses…", options: ["One heap", "TWO heaps — a max-heap for the lower half, a min-heap for the upper half", "A trie"], answer: 1,
    explain: "Balances both halves for O(log n) insertion, O(1) median access." },
  { q: "Forgetting to cap a heap at size K in a top-K problem results in…", options: ["A faster solution", "The heap growing to size n — no asymptotic benefit over full sorting", "An error"], answer: 1,
    explain: "Always pop after pushing if size exceeds K." },
  { q: "Union-Find without path compression risks…", options: ["Faster find() calls", "find() degrading toward O(n) on adversarial chain-like input", "No risk at all"], answer: 1,
    explain: "Always include the recursive parent-rewiring line." },
  { q: "'Accounts Merge' (merging accounts sharing an email) is naturally modeled as…", options: ["A sorting problem", "A Union-Find grouping problem", "A binary search problem"], answer: 1,
    explain: "Union accounts that share any email." }
]},
{ title: "Quiz 8 · Backtracking & Dynamic Programming",
  desc: "Choose/explore/un-choose, memoization, the four-question DP recipe",
  questions: [
  { q: "Backtracking differs from plain brute force by…", options: ["Being slower", "PRUNING invalid branches early, before fully building them out", "Using more memory"], answer: 1,
    explain: "The isValid() check before recursing is the key difference." },
  { q: "The backtracking skeleton is…", options: ["Sort, merge, filter", "Choose → Explore → Un-choose", "Push, pop, push"], answer: 1,
    explain: "Every backtracking problem fits this shape." },
  { q: "The #1 backtracking bug is…", options: ["Too much pruning", "Pushing a REFERENCE to the mutable path instead of a copy into results", "Using recursion"], answer: 1,
    explain: "Always results.push([...path])." },
  { q: "Subsets uses a `start` index to…", options: ["Track depth only", "Enforce increasing index order, preventing duplicate subsets in different orders", "Speed up recursion"], answer: 1,
    explain: "[1,2] and [2,1] shouldn't both appear as separate subsets." },
  { q: "Permutations use a `used` array instead of a `start` index because…", options: ["Order doesn't matter", "ORDER matters — every unused element is tried at every position", "It's arbitrary"], answer: 1,
    explain: "Unlike subsets/combinations." },
  { q: "Handling duplicate values in Subsets requires…", options: ["No special handling", "Sorting first, then skipping repeated values at the SAME recursive depth", "Removing duplicates before starting"], answer: 1,
    explain: "The i > start && nums[i]===nums[i-1] check." },
  { q: "DP applies when a problem has…", options: ["Just optimal substructure", "BOTH overlapping subproblems AND optimal substructure", "Neither property"], answer: 1,
    explain: "Both properties are independently necessary." },
  { q: "'Overlapping subproblems' means…", options: ["Subproblems never repeat", "The SAME subproblem is solved multiple times during recursion", "The problem has no recursive structure"], answer: 1,
    explain: "This is what memoization exploits." },
  { q: "The four-question DP recipe starts with…", options: ["Writing the recurrence", "Precisely defining what dp[i] REPRESENTS", "Choosing top-down or bottom-up"], answer: 1,
    explain: "Skipping this step is why most DP attempts fail." },
  { q: "Top-down DP (memoization) is…", options: ["Purely iterative", "The natural recursive solution PLUS a cache", "Always slower than bottom-up"], answer: 1,
    explain: "Closer to how you'd first think about the problem." },
  { q: "Bottom-up DP (tabulation) builds the answer…", options: ["Recursively from the top", "ITERATIVELY from the base case upward", "Randomly"], answer: 1,
    explain: "No recursion/call-stack overhead." },
  { q: "0/1 Knapsack's recurrence considers, for each item…", options: ["Only including it", "INCLUDE or EXCLUDE it — the core skeleton for many DP problems", "Only excluding it"], answer: 1,
    explain: "This include/exclude pattern generalizes broadly." },
  { q: "Space-optimizing 0/1 Knapsack from 2D to 1D requires iterating the capacity dimension…", options: ["Forward", "BACKWARD — to avoid reusing an item more than once", "In any order"], answer: 1,
    explain: "Forward iteration would incorrectly allow reuse (that's correct for UNBOUNDED knapsack instead)." },
  { q: "A problem with optimal substructure but NO overlapping subproblems (like merge sort)…", options: ["Benefits greatly from memoization", "Doesn't benefit from memoization — nothing to cache", "Isn't solvable recursively"], answer: 1,
    explain: "Each subproblem is only ever solved once regardless." },
  { q: "Naive recursive Fibonacci is O(2ⁿ) because…", options: ["Recursion is always exponential", "It recomputes the SAME subproblems repeatedly with no caching", "n is always huge"], answer: 1,
    explain: "Memoization fixes this to O(n)." },
  { q: "'Word Search' (find a word in a grid) uses backtracking with…", options: ["No visited tracking", "A visited-marking/unmarking pattern as part of choose/un-choose", "A trie always required"], answer: 1,
    explain: "Mark visited on entry, unmark on backtrack." },
  { q: "N-Queens benefits from backtracking's pruning because…", options: ["It has no constraints", "An invalid queen placement can be rejected IMMEDIATELY, avoiding wasted exploration", "It's always fast regardless"], answer: 1,
    explain: "Early rejection cuts the search space by orders of magnitude." },
  { q: "'Longest Common Subsequence' is typically solved with…", options: ["Backtracking only", "2D Dynamic Programming over two strings", "A single min-heap"], answer: 1,
    explain: "dp[i][j] representing LCS length of prefixes." },
  { q: "Coin Change (unbounded — items reusable) space-optimizes by iterating…", options: ["Backward, same as 0/1 knapsack", "FORWARD — allowing the just-updated value to be reused", "Neither direction matters"], answer: 1,
    explain: "The opposite of 0/1 knapsack's backward requirement." },
  { q: "The relationship between backtracking and DP is…", options: ["Completely unrelated", "Backtracking explores without memoizing; DP adds caching when subproblems overlap", "Identical algorithms"], answer: 1,
    explain: "A backtracking solution with overlapping subproblems can often become a DP solution." }
]},
{ title: "Quiz 9 · Greedy, Trie & Bit Manipulation",
  desc: "Exchange arguments, prefix trees, XOR tricks",
  questions: [
  { q: "A greedy algorithm makes…", options: ["Multiple reconsidered choices", "ONE locally-best choice per step, NEVER reconsidered", "Random choices"], answer: 1,
    explain: "This commitment is what requires proof of correctness." },
  { q: "The standard technique to PROVE a greedy algorithm correct is…", options: ["Testing it on a few examples", "The EXCHANGE ARGUMENT", "Assuming it's correct because it's simple"], answer: 1,
    explain: "Show any optimal solution can be modified to match greedy without becoming worse." },
  { q: "Interval scheduling (max non-overlapping / min removals) sorts by…", options: ["Start time", "END time — maximizes remaining room for future choices", "Interval length"], answer: 1,
    explain: "Proven correct via an exchange argument." },
  { q: "Jump Game's greedy solution tracks…", options: ["Every possible path", "Just the farthest reachable index so far", "A full DP table"], answer: 1,
    explain: "No need to know WHICH path — only whether one exists." },
  { q: "Greedy FAILS for coin change when…", options: ["Denominations are canonical (like standard currency)", "Denominations are ARBITRARY (e.g., [1,3,4] targeting 6)", "The target is small"], answer: 1,
    explain: "A classic greedy-vs-DP counter-example." },
  { q: "When greedy's correctness can't be proven or a counter-example is found, use…", options: ["Greedy anyway", "Dynamic Programming instead — always safe, considers all possibilities", "Binary search"], answer: 1,
    explain: "DP is the safe fallback greedy is only a speed optimization over." },
  { q: "A Trie stores strings as…", options: ["Independent hash keys", "SHARED paths from the root, one node per character", "Sorted arrays"], answer: 1,
    explain: "Common prefixes share the same nodes." },
  { q: "Trie insert/search/startsWith all cost…", options: ["O(n), n = number of stored words", "O(L), L = the QUERY's length — independent of how many words are stored", "O(n log n)"], answer: 1,
    explain: "The core advantage over a hash set for prefix operations." },
  { q: "The isEndOfWord flag distinguishes…", options: ["Nothing important", "'This exact string was inserted' from 'this is merely a prefix of something longer'", "Upper vs lowercase"], answer: 1,
    explain: "Without it, search() would be too permissive." },
  { q: "A hash set CANNOT efficiently answer…", options: ["Exact match queries", "'Does any word start with this prefix?' — without scanning all words", "Any query at all"], answer: 1,
    explain: "This is exactly what a trie is built for." },
  { q: "Word Search II combines a Trie with…", options: ["Binary search", "Backtracking — pruning paths that no longer match ANY target word", "Union-Find"], answer: 1,
    explain: "Shared trie structure prunes all non-matching words simultaneously." },
  { q: "XOR-ing an entire array together finds the single non-duplicate when others appear…", options: ["Any number of times", "Exactly TWICE — via self-cancellation (a^a=0)", "Three times"], answer: 1,
    explain: "For triples, you need bit-counting modulo 3 instead." },
  { q: "n & (n-1) clears…", options: ["All bits", "Exactly the LOWEST set bit of n", "The highest set bit"], answer: 1,
    explain: "Used for both isPowerOfTwo and countSetBits." },
  { q: "isPowerOfTwo(n) checks…", options: ["n % 2 === 0", "n > 0 && (n & (n-1)) === 0", "n is odd"], answer: 1,
    explain: "A power of two has exactly one set bit." },
  { q: "Brian Kernighan's algorithm counts set bits in time proportional to…", options: ["The total bit width (e.g., 32)", "The NUMBER OF SET BITS specifically", "n itself"], answer: 1,
    explain: "Faster than checking every bit position when few bits are set." },
  { q: "Confusing & with && in bit manipulation code causes…", options: ["No difference", "Wrong results — one is bitwise, the other is logical", "Faster execution"], answer: 1,
    explain: "A common careless-error trap." },
  { q: "'Single Number II' (others appear THREE times) requires…", options: ["Plain XOR", "Counting set bits per position, MODULO 3", "Sorting the array"], answer: 1,
    explain: "Plain XOR only correctly cancels pairs, not triples." },
  { q: "Bitmasks representing subsets use…", options: ["A separate array per subset", "An n-bit integer, where bit i set means item i is included", "A trie"], answer: 1,
    explain: "An alternative to backtracking-based subset generation, often used as DP indices." },
  { q: "Right shift (>>) on negative numbers in most languages…", options: ["Fills with zeros always", "Uses ARITHMETIC shift, filling with 1s (sign extension)", "Is undefined behavior always"], answer: 1,
    explain: "Use unsigned right shift (>>> in JS) when zero-fill is needed." },
  { q: "The overarching theme connecting Greedy, Trie, and Bit Manipulation is…", options: ["They're unrelated topics", "Each solves a specific problem SHAPE with an O(1)-space or provably-optimal trick, once you recognize the shape", "They're all about sorting"], answer: 1,
    explain: "Recognition of the right tool for the right shape is the core interview skill." }
]},
{ title: "Quiz 10 · Mixed Pattern Recognition (Mock Exam)",
  desc: "Read a problem description, name the correct pattern — comprehensive review",
  questions: [
  { q: "\"Find the longest substring with at most K distinct characters.\" Which pattern?", options: ["Two Pointers (converging)", "Sliding Window", "Binary Search"], answer: 1,
    explain: "Contiguous substring with a condition." },
  { q: "\"Given a SORTED array, find two numbers that add up to target.\" Which pattern?", options: ["Hash Map", "Two Pointers (converging)", "Sliding Window"], answer: 1,
    explain: "Sortedness enables the pointer approach with no extra space." },
  { q: "\"Minimize the maximum load a worker must carry\" with n up to 10⁹. Which pattern?", options: ["Greedy", "Binary Search on the answer", "Backtracking"], answer: 1,
    explain: "Huge constraints + minimize/maximize → search the answer space." },
  { q: "\"Detect if a linked list has a cycle\" in O(1) space. Which pattern?", options: ["Fast & Slow Pointers", "Hash Set", "Union-Find"], answer: 0,
    explain: "O(1) space rules out the hash-set approach." },
  { q: "\"Find all UNIQUE triplets summing to zero.\" What's the optimal first step?", options: ["Build a hash map of all pairs", "SORT the array", "Try all triplets with pruning"], answer: 1,
    explain: "Enables the two-pointer scan per anchor element." },
  { q: "\"Merge overlapping meeting times.\" Which pattern?", options: ["Merge Intervals", "Binary Search", "Trie"], answer: 0,
    explain: "Sort by start time, sweep once." },
  { q: "\"Course prerequisites — can you finish all courses?\" Which pattern?", options: ["Dynamic Programming", "Topological Sort (cycle detection)", "Greedy"], answer: 1,
    explain: "A cycle in the dependency graph means it's impossible." },
  { q: "\"Find the Kth largest element in an unsorted array.\" Which pattern?", options: ["Sort everything, O(n log n)", "A size-K MIN-heap, O(n log K)", "Backtracking"], answer: 1,
    explain: "The bounded-heap top-K pattern." },
  { q: "\"Generate all possible subsets of a set.\" Which pattern?", options: ["Backtracking (or bitmask enumeration)", "Binary Search", "Union-Find"], answer: 0,
    explain: "Choose/explore/un-choose, or an n-bit integer per subset." },
  { q: "\"Number of connected components in a graph, with edges added incrementally.\" Which pattern?", options: ["DFS re-run after each edge", "Union-Find", "Binary Search"], answer: 1,
    explain: "Incremental connectivity is Union-Find's specialty." },
  { q: "\"Does any word in the dictionary start with this prefix?\" Which pattern?", options: ["Hash Set", "Trie", "Sliding Window"], answer: 1,
    explain: "Hash sets can't efficiently answer prefix queries." },
  { q: "\"Find the single number that appears once; all others appear twice.\" Which pattern?", options: ["XOR (Bit Manipulation)", "Sorting", "Backtracking"], answer: 0,
    explain: "Self-canceling property of XOR." },
  { q: "\"Minimum number of coins to make an amount, ARBITRARY denominations.\" Which pattern?", options: ["Greedy", "Dynamic Programming", "Two Pointers"], answer: 1,
    explain: "Greedy provably fails for arbitrary denominations." },
  { q: "\"Maximum non-overlapping intervals you can attend.\" Which pattern?", options: ["Greedy (sort by end time)", "Backtracking", "Union-Find"], answer: 0,
    explain: "Provable via an exchange argument." },
  { q: "\"Serialize and deserialize a binary tree.\" Which pattern?", options: ["Binary Tree traversal (pre-order + null markers)", "Union-Find", "Sliding Window"], answer: 0,
    explain: "Reconstructs exact structure from a traversal with markers." },
  { q: "\"Shortest path in an unweighted maze.\" Which pattern?", options: ["DFS", "BFS", "Backtracking"], answer: 1,
    explain: "BFS's level-order guarantees the shortest path." },
  { q: "\"Find all words in a grid matching a large dictionary.\" Which pattern?", options: ["Trie + Backtracking combined", "Sliding Window", "Binary Search"], answer: 0,
    explain: "Shared trie prunes many words' searches simultaneously." },
  { q: "\"Reverse a linked list in groups of K.\" Which pattern?", options: ["Two Pointers converging", "Linked List In-place Reversal (recursive or iterative)", "Greedy"], answer: 1,
    explain: "The three-pointer skeleton, applied per group." },
  { q: "\"Count subarrays whose sum equals K.\" Which pattern?", options: ["Prefix Sum + hash map (seeded with {0:1})", "Sliding Window", "Binary Search"], answer: 0,
    explain: "Negative numbers can appear, ruling out plain sliding window." },
  { q: "\"Is n a power of two?\" Which pattern?", options: ["Bit Manipulation — n & (n-1) === 0", "Dynamic Programming", "Backtracking"], answer: 0,
    explain: "A single-set-bit check, O(1)." }
]}
);
