// LeetCode Patterns quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations",
  desc: "Big-O, amortized cost, arrays/strings essentials, hashing",
  questions: [
  { q: "A nested loop with the SAME n on both loops is…", options: ["O(n)", "O(n²)", "O(log n)"], answer: 1,
    explain: "Two loops over the same n → quadratic." },
  { q: "A loop where the counter DOUBLES each iteration is…", options: ["O(n)", "O(log n)", "O(n²)"], answer: 1,
    explain: "Halving/doubling patterns give logarithmic complexity." },
  { q: "Dynamic array push() is described as…", options: ["Always O(n)", "O(1) amortized", "O(log n)"], answer: 1,
    explain: "Occasional O(n) resizes average out across many pushes." },
  { q: "Recursion has hidden space cost from…", options: ["The heap only", "The call stack (O(depth))", "Nothing extra"], answer: 1,
    explain: "Even with O(1) locals, recursion depth costs space." },
  { q: "n ≤ 10⁹ in constraints usually signals…", options: ["Brute force is fine", "You need O(log n), often binary search on the answer", "Use nested loops"], answer: 1,
    explain: "Reading constraints tells you the expected complexity." },
  { q: "String concatenation in a loop (s += char) is…", options: ["O(n)", "O(n²) — strings are immutable", "O(1)"], answer: 1,
    explain: "Each += copies the whole accumulated string so far." },
  { q: "The fix for accidental O(n²) string building is…", options: ["Use more loops", "Build with an array/buffer, join once", "Avoid strings entirely"], answer: 1,
    explain: "One allocation at the end instead of n allocations." },
  { q: "The 'read/write pointer' pattern achieves in-place array modification in…", options: ["O(n) time, O(n) space", "O(n) time, O(1) space", "O(n²) time"], answer: 1,
    explain: "No second array needed." },
  { q: "Prefix/suffix precomputation turns 'answer this for every position' from…", options: ["O(n) to O(n²)", "O(n²) to O(n)", "O(1) to O(n)"], answer: 1,
    explain: "Trade a bit of space for a big speed win." },
  { q: "A hash map/set trades…", options: ["Time for time", "SPACE for TIME (O(1) average lookup)", "Nothing — no trade-off exists"], answer: 1,
    explain: "The core idea behind most hashing-based optimizations." },
  { q: "In Two Sum, checking for the complement should happen…", options: ["After inserting the current element", "BEFORE inserting the current element", "Never — just insert everything first"], answer: 1,
    explain: "Avoids pairing an element with itself." },
  { q: "Group Anagrams uses a sorted string as a hash key because…", options: ["It's faster to hash", "It's a CANONICAL form identical for all anagrams", "Sorting is required by the problem"], answer: 1,
    explain: "Same letters, sorted, always produce the same key." },
  { q: "Using a fixed-size 26-element array instead of a Map is preferred when…", options: ["The alphabet is unknown/large", "The alphabet is small and known (lowercase English)", "Never — Maps are always better"], answer: 1,
    explain: "Less overhead for a known small alphabet." },
  { q: "Why is 'Longest Consecutive Sequence' O(n) despite a loop inside a loop?", options: ["It's actually O(n²)", "The inner while loop only runs for sequence STARTS, visiting each number once total", "JavaScript optimizes it automatically"], answer: 1,
    explain: "Amortized: only sequence-start numbers trigger the inner loop." },
  { q: "Amortized analysis is used to justify…", options: ["Worst-case-only reasoning", "Averaging occasional expensive operations across many cheap ones", "Ignoring space complexity"], answer: 1,
    explain: "Dynamic array resizing is the classic example." },
  { q: "A hash map's worst-case operation cost is…", options: ["Always O(1)", "O(n) under pathological collisions (rare in practice)", "Always O(log n)"], answer: 1,
    explain: "State this precisely: O(1) average, O(n) worst case." },
  { q: "Reading problem CONSTRAINTS before coding helps you…", options: ["Nothing useful", "Infer which complexity (and pattern) is actually expected", "Only matters for competitive programming"], answer: 1,
    explain: "A core, transferable interview habit." },
  { q: "An O(n log n) algorithm on n=10⁵ performs roughly…", options: ["10¹⁰ operations (too slow)", "~1.7×10⁶ operations (fast)", "10² operations"], answer: 1,
    explain: "Comfortably within typical time limits." },
  { q: "JS Maps (unlike many languages' hash maps) preserve…", options: ["Sorted order", "INSERTION order during iteration", "No particular order"], answer: 1,
    explain: "A language-specific exception worth knowing." },
  { q: "Stating BOTH time and space complexity in an interview is…", options: ["Unnecessary", "Expected — a hash-map solution's O(n) space is a real trade-off to name", "Only needed for space-constrained problems"], answer: 1,
    explain: "Complete complexity analysis includes both dimensions." }
]},
{ title: "Quiz 2 · Two Pointers & Sliding Window",
  desc: "Converging pointers, window expansion/contraction, recognition cues",
  questions: [
  { q: "Two pointers converging from both ends works well on…", options: ["Unsorted data", "SORTED arrays (pair-sum, palindrome checks)", "Linked lists only"], answer: 1,
    explain: "Sortedness lets you safely discard pairs by moving pointers." },
  { q: "In the converging-pointer Two Sum, if current sum < target…", options: ["Move right pointer left", "Move LEFT pointer right (need a bigger sum)", "Stop — no solution"], answer: 1,
    explain: "Increasing the smaller side increases the sum." },
  { q: "3Sum's complexity is…", options: ["O(n)", "O(n²) — sort plus a two-pointer scan per anchor", "O(n³)"], answer: 1,
    explain: "Fix one element, Two-Sum the rest." },
  { q: "Trapping Rain Water's two-pointer solution achieves…", options: ["O(n) time, O(n) space", "O(n) time, O(1) space", "O(n²) time"], answer: 1,
    explain: "Beats the prefix-max-arrays approach on space." },
  { q: "A sliding window is used for problems about…", options: ["Fixed pairs", "CONTIGUOUS subarrays/substrings satisfying a condition", "Sorting"], answer: 1,
    explain: "Window expands/contracts over contiguous ranges." },
  { q: "A sliding window typically EXPANDS by…", options: ["Moving the left pointer", "Moving the RIGHT pointer forward", "Resetting entirely"], answer: 1,
    explain: "Grow to include more elements." },
  { q: "A sliding window CONTRACTS by…", options: ["Moving the right pointer", "Moving the LEFT pointer forward, when the window becomes invalid", "Never — it only grows"], answer: 1,
    explain: "Shrink from the left once a condition is violated." },
  { q: "Sliding Window generally does NOT work when…", options: ["Looking for a fixed-size window", "The array contains NEGATIVE numbers and you need max-sum subarray", "The condition is monotonic"], answer: 1,
    explain: "Window validity is no longer monotonic with negatives present." },
  { q: "'Longest substring with at most K distinct characters' is solved with…", options: ["Two Pointers (converging)", "Sliding Window", "Binary Search"], answer: 1,
    explain: "A classic sliding window recognition cue." },
  { q: "'Detect a cycle in a linked list in O(1) space' points to…", options: ["Sliding Window", "Fast & Slow Pointers", "Two Pointers converging"], answer: 1,
    explain: "Not the same as the converging two-pointer pattern." },
  { q: "Two Pointers replaces a nested loop, turning O(n²) into…", options: ["O(n log n)", "O(n) with O(1) extra space", "O(1)"], answer: 1,
    explain: "The core value proposition of the pattern." },
  { q: "For 'find two numbers in a SORTED array summing to target', prefer…", options: ["A hash map", "Two Pointers (no extra space needed since it's sorted)", "Sorting again"], answer: 1,
    explain: "Sortedness lets two pointers work directly, O(1) space." },
  { q: "For 'find two numbers in an UNSORTED array summing to target' with no sort allowed, prefer…", options: ["Two Pointers", "A hash map (O(n) time, O(n) space)", "Nested loops only"], answer: 1,
    explain: "Sorting would cost O(n log n) and lose original indices unless tracked." },
  { q: "A monotonic window-validity condition means…", options: ["The window's validity flips unpredictably", "Once valid/invalid, expanding/shrinking moves it predictably in one direction", "The window never changes size"], answer: 1,
    explain: "This monotonicity is what sliding window relies on." },
  { q: "The window size in sliding window problems is…", options: ["Always fixed", "Sometimes fixed, sometimes variable depending on the problem", "Never used"], answer: 1,
    explain: "Both fixed-size and variable-size window variants exist." },
  { q: "'Minimum window substring containing all characters of T' is a…", options: ["Two Pointers converging problem", "Variable-size Sliding Window problem", "Binary search problem"], answer: 1,
    explain: "Expand to find validity, contract to minimize." },
  { q: "Palindrome checks with two pointers compare…", options: ["Adjacent elements", "Both ENDS of the string, moving inward", "Random pairs"], answer: 1,
    explain: "left++ and right-- until they meet." },
  { q: "Merging two sorted arrays/lists is a classic use of…", options: ["Backtracking", "Two Pointers (one per list)", "A hash map"], answer: 1,
    explain: "One pointer per sorted sequence, advance the smaller." },
  { q: "'Container with most water' uses two pointers because…", options: ["The array must be sorted first", "Moving the SHORTER side is provably the only useful move", "It's a graph problem"], answer: 1,
    explain: "Moving the taller side can never improve the area." },
  { q: "Sliding window's time complexity for a single pass is typically…", options: ["O(n²)", "O(n) — each pointer moves forward at most n times total", "O(log n)"], answer: 1,
    explain: "Both pointers move monotonically forward, bounding total work." }
]},
{ title: "Quiz 3 · Prefix Sum, Fast/Slow Pointers & Merge Intervals",
  desc: "Range queries, cycle detection, interval scheduling",
  questions: [
  { q: "A prefix sum array lets you answer any range-sum query in…", options: ["O(n)", "O(1) after an O(n) precompute", "O(log n)"], answer: 1,
    explain: "The core trade-off: precompute once, query fast." },
  { q: "For 'count subarrays summing to K,' the hash map must be seeded with…", options: ["Nothing", "{0: 1} — representing the empty prefix", "{K: 1}"], answer: 1,
    explain: "Without it, subarrays starting at index 0 are undercounted." },
  { q: "sum(i, j) in terms of prefix sums equals…", options: ["prefix[i] + prefix[j]", "prefix[j] − prefix[i]", "prefix[i] × prefix[j]"], answer: 1,
    explain: "The key algebraic identity behind the pattern." },
  { q: "2D prefix sums use which technique to compute a rectangle sum in O(1)?", options: ["Binary search", "Inclusion-exclusion", "Recursion"], answer: 1,
    explain: "Add/subtract overlapping regions correctly." },
  { q: "Fast & slow pointers detect a cycle by…", options: ["Using a hash set of visited nodes", "Having the fast pointer eventually LAP the slow one, in O(1) space", "Sorting the list"], answer: 1,
    explain: "No extra space needed, unlike a hash-set approach." },
  { q: "The gap between fast and slow pointers, once both are in a cycle, decreases by…", options: ["2 per iteration", "Exactly 1 per iteration", "It's random"], answer: 1,
    explain: "Guarantees they meet within one cycle length." },
  { q: "To find the START of a cycle (not just detect one), you…", options: ["Just return the meeting point", "Reset one pointer to head, advance both at 1x until they meet again", "Restart the algorithm from scratch"], answer: 1,
    explain: "Distance from head equals distance from meeting point to cycle start." },
  { q: "Finding a linked list's middle with fast/slow pointers takes…", options: ["Two full passes", "ONE pass — no need to count length first", "O(n²) time"], answer: 1,
    explain: "Fast reaches the end exactly when slow reaches the middle." },
  { q: "Merge Intervals should sort by…", options: ["End time always", "START time — the critical first step", "Interval length"], answer: 1,
    explain: "After sorting by start, only compare against the last merged interval." },
  { q: "After sorting by start time, merging only needs to compare each interval against…", options: ["Every previous interval", "Only the LAST merged interval", "The first interval only"], answer: 1,
    explain: "Sorting establishes this invariant, making one pass sufficient." },
  { q: "Meeting Rooms II (minimum rooms needed) uses…", options: ["A single sorted array", "TWO separate sorted arrays (starts and ends) swept with two pointers", "A hash map"], answer: 1,
    explain: "Tracks maximum concurrent overlap." },
  { q: "For interval scheduling (max overlap), sorting by END time — not start time — is correct for MEETING ROOMS specifically because…", options: ["It's arbitrary", "Meeting Rooms II sorts starts/ends SEPARATELY, not as combined intervals", "End time is always the only valid choice for every interval problem"], answer: 1,
    explain: "Different interval problems justify different sort keys — always verify with an exchange argument." },
  { q: "'Insert Interval' into an ALREADY-sorted list can be done in…", options: ["O(n log n) by re-sorting", "O(n) via a three-phase linear scan", "O(1)"], answer: 1,
    explain: "No need to re-sort already-sorted input." },
  { q: "The three phases of Insert Interval are…", options: ["Sort, merge, filter", "Before (no overlap), overlapping (merge), after (no overlap)", "Push, pop, push"], answer: 1,
    explain: "Exploits the pre-sorted, non-overlapping precondition." },
  { q: "A prefix sum array is best suited for…", options: ["Frequently MUTATING arrays", "STATIC arrays with many range queries", "Linked lists"], answer: 1,
    explain: "Frequent updates need a Fenwick/Segment Tree instead." },
  { q: "Comparing node VALUES instead of node REFERENCES in cycle detection risks…", options: ["Nothing", "False positives on lists with duplicate values but no actual cycle", "Faster detection"], answer: 1,
    explain: "Always compare identity (===), not .val." },
  { q: "'Equilibrium index' (left sum = right sum) is solved using…", options: ["Backtracking", "Prefix AND suffix sums", "A trie"], answer: 1,
    explain: "Precompute both, then find where they're equal." },
  { q: "Not using a dummy head when reversing/modifying a linked list sublist can cause…", options: ["Faster code", "Special-case bugs when the operation starts at the very first node", "No difference at all"], answer: 1,
    explain: "A dummy node eliminates the special case entirely." },
  { q: "'Subarray sums divisible by K' extends the prefix-sum hash trick by…", options: ["Ignoring K entirely", "Using prefix sum MODULO K as the hash key", "Sorting the array first"], answer: 1,
    explain: "Same core sum(i,j) identity, applied under modular arithmetic." },
  { q: "Merge Intervals reduces an inherently pairwise comparison problem to…", options: ["A single O(n) linear sweep after an O(n log n) sort", "A O(n²) comparison of every pair", "A binary search"], answer: 1,
    explain: "Sorting is what makes the single-pass sweep valid." }
]},
{ title: "Quiz 4 · Binary Search & Monotonic Stack",
  desc: "Search space reduction, next-greater-element, amortized stack cost",
  questions: [
  { q: "Binary search requires the search space to be…", options: ["Random", "MONOTONIC (sorted, or a condition that flips once)", "Unsorted"], answer: 1,
    explain: "A predicate that's false-then-true (or vice versa) across the range." },
  { q: "'Binary search on the answer' is used when…", options: ["The input array itself is sorted", "You're searching a RANGE OF POSSIBLE ANSWERS, not the input array directly", "Never — only classic array search applies"], answer: 1,
    explain: "e.g., minimize the maximum load, given huge constraints." },
  { q: "n ≤ 10⁹ combined with 'minimize/maximize X' strongly suggests…", options: ["Brute force", "Binary search on the answer", "A hash map"], answer: 1,
    explain: "Constraints this large rule out linear/quadratic scans." },
  { q: "A monotonic stack maintains…", options: ["Random order", "Strictly increasing or decreasing order", "Insertion order only"], answer: 1,
    explain: "Violating elements trigger pops." },
  { q: "In 'next greater element,' the stack stores…", options: ["Values", "INDICES — so distances/widths can be computed", "Nothing — it's not needed"], answer: 1,
    explain: "Values are always one lookup away; positions aren't recoverable from bare values." },
  { q: "The monotonic stack pattern is O(n) despite a nested loop because…", options: ["It's actually O(n²)", "Each element is pushed once and popped at most once — amortized O(n)", "JavaScript optimizes it"], answer: 1,
    explain: "Same amortized reasoning as dynamic array resizing." },
  { q: "Balanced Parentheses uses a stack because…", options: ["Order doesn't matter", "LIFO naturally matches 'most recently opened must close first'", "It's the only possible approach"], answer: 1,
    explain: "The nesting structure maps directly to stack semantics." },
  { q: "In Largest Rectangle in Histogram, a sentinel value (0) is added to…", options: ["Speed up the algorithm", "Force the stack to fully drain at the end, computing every remaining bar's rectangle", "Avoid an off-by-one error only"], answer: 1,
    explain: "Without it, elements still on the stack never get resolved." },
  { q: "When a monotonic stack pops a bar in the histogram problem, its rectangle's boundaries are found…", options: ["By a separate search", "'For free' — the nearest shorter bars on both sides, as a side effect of the invariant", "By re-scanning the array"], answer: 1,
    explain: "The stack's ordering property yields both boundaries automatically." },
  { q: "Binary search's time complexity is…", options: ["O(n)", "O(log n)", "O(n log n)"], answer: 1,
    explain: "Halves the search space each iteration." },
  { q: "A common binary search bug is…", options: ["Using log n time", "Infinite loops from incorrect mid/boundary updates", "Being too fast"], answer: 1,
    explain: "Off-by-one errors in updating left/right bounds." },
  { q: "'Daily Temperatures' (days until warmer) uses…", options: ["Two pointers", "A monotonic stack storing indices", "Binary search"], answer: 1,
    explain: "Next-greater-element with a distance computation." },
  { q: "Storing values instead of indices on a monotonic stack fails when…", options: ["Never — it's always fine", "You need distances/widths, or the array has duplicate values", "The array is very small"], answer: 1,
    explain: "Position information can't be recovered from a bare value." },
  { q: "Remove K Digits (smallest resulting number) is a…", options: ["Binary search problem", "Greedy monotonic-stack variant", "Backtracking problem"], answer: 1,
    explain: "Pop larger digits when a smaller one would help, greedily." },
  { q: "Consistently using &lt; vs &lt;= in a monotonic stack's pop condition affects…", options: ["Nothing", "Whether equal elements are treated as 'greater' — must match the problem's exact definition", "Only performance"], answer: 1,
    explain: "A precise, deliberate choice, not arbitrary." },
  { q: "Binary search variants beyond exact match include…", options: ["Only exact-value search", "Finding the first/last occurrence, or search-on-answer over a value range", "Only sorting"], answer: 1,
    explain: "The 'variants' in the pattern name matter." },
  { q: "The empty-stack check in Balanced Parentheses matters because…", options: ["It never matters", "stack.pop() on an empty array can cause a false match or error", "It only affects performance"], answer: 1,
    explain: "A string starting with a closing bracket needs this guard." },
  { q: "A rotated sorted array search is solved with…", options: ["Linear scan only", "A modified binary search exploiting partial sortedness", "A monotonic stack"], answer: 1,
    explain: "One half of the array is always properly sorted." },
  { q: "The amortized argument for monotonic stacks mirrors the amortized argument for…", options: ["Binary search", "Dynamic array resizing (push/pop each happen at most once per element)", "Hash map collisions"], answer: 1,
    explain: "Both rely on bounding TOTAL operations across the whole run, not per-iteration." },
  { q: "Explaining a monotonic stack solution's complexity in an interview should mention…", options: ["Just 'O(n²) because of the nested loop'", "The amortized O(n) argument — each element pushed/popped at most once", "Nothing about complexity"], answer: 1,
    explain: "Correctly characterizing the true complexity is part of the answer." }
]},
{ title: "Quiz 5 · Linked List Reversal & BFS/DFS",
  desc: "Three-pointer reversal, graph traversal, shortest path guarantees",
  questions: [
  { q: "Linked list reversal uses three pointers:", options: ["left, right, mid", "prev, curr, and a saved next", "start, end, pivot"], answer: 1,
    explain: "The universal skeleton for every reversal variant." },
  { q: "The #1 bug in linked list reversal is…", options: ["Using too many variables", "Overwriting curr.next BEFORE saving it, losing the rest of the list", "Using recursion"], answer: 1,
    explain: "Always save next first, then reassign." },
  { q: "A dummy head node in sublist reversal eliminates…", options: ["The need for a loop", "The special case of reversing starting at the very first node", "All bugs automatically"], answer: 1,
    explain: "Every sublist now has a valid predecessor to update." },
  { q: "Reverse-in-groups-of-K can be solved…", options: ["Only iteratively", "Both recursively (O(n/k) stack) and iteratively (O(1) space)", "Only with a hash map"], answer: 1,
    explain: "Know the trade-off between the two approaches." },
  { q: "Finding a linked list's middle combines naturally with…", options: ["Trie construction", "Palindrome-check and list-reordering problems", "Union-Find"], answer: 1,
    explain: "Fast/slow pointers + reversal is a common composition." },
  { q: "BFS explores a graph…", options: ["Deep first, one branch at a time", "WIDE first, level by level", "Randomly"], answer: 1,
    explain: "Uses a queue." },
  { q: "DFS explores a graph…", options: ["Level by level", "DEEP first, via a stack or recursion", "Only on trees"], answer: 1,
    explain: "Commits to one branch fully before backtracking." },
  { q: "BFS guarantees the shortest path in…", options: ["Any graph", "An UNWEIGHTED graph", "A weighted graph"], answer: 1,
    explain: "Weighted graphs need Dijkstra's algorithm instead." },
  { q: "In BFS, nodes should be marked visited…", options: ["When dequeued", "When ENQUEUED — the #1 BFS correctness rule", "Never — it's not needed"], answer: 1,
    explain: "Prevents duplicate enqueueing and incorrect distances." },
  { q: "The 'snapshot queue size' trick in BFS is used to…", options: ["Speed up the algorithm", "Process exactly one LEVEL per iteration (level-order/distance tracking)", "Avoid using a queue"], answer: 1,
    explain: "Without it, you lose the ability to report which level a node was found at." },
  { q: "Recursive DFS risks…", options: ["Being too fast", "Stack overflow on very deep/large graphs", "Never finding a solution"], answer: 1,
    explain: "Switch to iterative DFS with an explicit stack for very deep inputs." },
  { q: "Iterative DFS typically marks nodes visited…", options: ["On push", "On POP/processing (unlike BFS's enqueue-time marking)", "Never"], answer: 1,
    explain: "A subtle but important difference from BFS." },
  { q: "Number of Islands (grid DFS) can mark visited cells by…", options: ["A separate Set only", "MUTATING the grid itself (e.g., '1' → '0')", "Sorting the grid"], answer: 1,
    explain: "A classic space-saving trick." },
  { q: "'Shortest number of steps/moves' in an unweighted graph is a strong cue for…", options: ["DFS", "BFS", "Backtracking"], answer: 1,
    explain: "BFS's level-by-level exploration guarantees this." },
  { q: "'Explore all possible paths' or 'does any path exist' is a strong cue for…", options: ["BFS specifically", "DFS (or either, but DFS is often simpler for existence checks)", "Binary search"], answer: 1,
    explain: "No need for BFS's shortest-path guarantee here." },
  { q: "A general graph (not a tree) traversal ALWAYS needs…", options: ["Nothing extra", "A visited set/array to avoid infinite loops from cycles", "A heap"], answer: 1,
    explain: "Trees are cycle-free by definition; general graphs are not." },
  { q: "BFS space complexity is roughly…", options: ["O(depth)", "O(width) — can be large for wide graphs", "Always O(1)"], answer: 1,
    explain: "The queue can hold an entire level's worth of nodes." },
  { q: "DFS space complexity is roughly…", options: ["O(width)", "O(depth) — can be large for deep graphs", "Always O(n²)"], answer: 1,
    explain: "Bounded by the recursion/stack depth." },
  { q: "'Clone Graph' is typically solved using…", options: ["Binary search", "BFS or DFS with a visited map tracking original→copy nodes", "A monotonic stack"], answer: 1,
    explain: "Either traversal works; the visited map prevents infinite recursion on cycles." },
  { q: "Choosing between BFS and DFS should be based primarily on…", options: ["Personal preference only", "Whether the problem needs shortest-path guarantees (BFS) or just any/all paths (DFS)", "Which is faster to type"], answer: 1,
    explain: "The decisive interview distinction between the two." }
]}
);
