// LeetCode Patterns quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations",
  desc: "Big-O, amortized cost, arrays/strings essentials, hashing",
  questions: [
  { q: "A nested loop with the SAME n on both loops is…", options: ["O(log n)", "O(n²)", "O(n)"], answer: 1,
    explain: "Two loops over the same n → quadratic." },
  { q: "A loop where the counter DOUBLES each iteration is…", options: ["O(n)", "O(n²)", "O(log n)"], answer: 2,
    explain: "Halving/doubling patterns give logarithmic complexity." },
  { q: "Dynamic array push() is described as…", options: ["Always O(n)", "O(1) amortized", "O(log n)"], answer: 1,
    explain: "Occasional O(n) resizes average out across many pushes." },
  { q: "Recursion has hidden space cost from…", options: ["Nothing extra", "The call stack (O(depth))", "The heap only"], answer: 1,
    explain: "Even with O(1) locals, recursion depth costs space." },
  { q: "n ≤ 10⁹ in constraints usually signals…", options: ["Use nested loops", "You need O(log n), often binary search on the answer", "Brute force is fine"], answer: 1,
    explain: "Reading constraints tells you the expected complexity." },
  { q: "String concatenation in a loop (s += char) is…", options: ["O(n)", "O(1)", "O(n²) — strings are immutable"], answer: 2,
    explain: "Each += copies the whole accumulated string so far." },
  { q: "The fix for accidental O(n²) string building is…", options: ["Use more loops", "Build with an array/buffer, join once", "Avoid strings entirely"], answer: 1,
    explain: "One allocation at the end instead of n allocations." },
  { q: "The 'read/write pointer' pattern achieves in-place array modification in…", options: ["O(n) time, O(1) space", "O(n²) time", "O(n) time, O(n) space"], answer: 0,
    explain: "No second array needed." },
  { q: "Prefix/suffix precomputation turns 'answer this for every position' from…", options: ["O(n) to O(n²)", "O(n²) to O(n)", "O(1) to O(n)"], answer: 1,
    explain: "Trade a bit of space for a big speed win." },
  { q: "A hash map/set trades…", options: ["Time for time", "Nothing — no trade-off exists", "SPACE for TIME (O(1) average lookup)"], answer: 2,
    explain: "The core idea behind most hashing-based optimizations." },
  { q: "In Two Sum, checking for the complement should happen…", options: ["After inserting the current element", "Never — just insert everything first", "BEFORE inserting the current element"], answer: 2,
    explain: "Avoids pairing an element with itself." },
  { q: "Group Anagrams uses a sorted string as a hash key because…", options: ["Sorting is required by the problem", "It's faster to hash", "It's a CANONICAL form identical for all anagrams"], answer: 2,
    explain: "Same letters, sorted, always produce the same key." },
  { q: "Using a fixed-size 26-element array instead of a Map is preferred when…", options: ["Never — Maps are always better", "The alphabet is unknown/large", "The alphabet is small and known (lowercase English)"], answer: 2,
    explain: "Less overhead for a known small alphabet." },
  { q: "Why is 'Longest Consecutive Sequence' O(n) despite a loop inside a loop?", options: ["The inner while loop only runs for sequence STARTS, visiting each number once total", "It's actually O(n²)", "JavaScript optimizes it automatically"], answer: 0,
    explain: "Amortized: only sequence-start numbers trigger the inner loop." },
  { q: "Amortized analysis is used to justify…", options: ["Worst-case-only reasoning", "Ignoring space complexity", "Averaging occasional expensive operations across many cheap ones"], answer: 2,
    explain: "Dynamic array resizing is the classic example." },
  { q: "A hash map's worst-case operation cost is…", options: ["Always O(1)", "O(n) under pathological collisions (rare in practice)", "Always O(log n)"], answer: 1,
    explain: "State this precisely: O(1) average, O(n) worst case." },
  { q: "Reading problem CONSTRAINTS before coding helps you…", options: ["Infer which complexity (and pattern) is actually expected", "Only matters for competitive programming", "Nothing useful"], answer: 0,
    explain: "A core, transferable interview habit." },
  { q: "An O(n log n) algorithm on n=10⁵ performs roughly…", options: ["10¹⁰ operations (too slow)", "10² operations", "~1.7×10⁶ operations (fast)"], answer: 2,
    explain: "Comfortably within typical time limits." },
  { q: "JS Maps (unlike many languages' hash maps) preserve…", options: ["Sorted order", "No particular order", "INSERTION order during iteration"], answer: 2,
    explain: "A language-specific exception worth knowing." },
  { q: "Stating BOTH time and space complexity in an interview is…", options: ["Unnecessary", "Expected — a hash-map solution's O(n) space is a real trade-off to name", "Only needed for space-constrained problems"], answer: 1,
    explain: "Complete complexity analysis includes both dimensions." },
]},
{ title: "Quiz 2 · Two Pointers & Sliding Window",
  desc: "Converging pointers, window expansion/contraction, recognition cues",
  questions: [
  { q: "Two pointers converging from both ends works well on…", options: ["Unsorted data", "SORTED arrays (pair-sum, palindrome checks)", "Linked lists only"], answer: 1,
    explain: "Sortedness lets you safely discard pairs by moving pointers." },
  { q: "In the converging-pointer Two Sum, if current sum < target…", options: ["Move right pointer left", "Stop — no solution", "Move LEFT pointer right (need a bigger sum)"], answer: 2,
    explain: "Increasing the smaller side increases the sum." },
  { q: "3Sum's complexity is…", options: ["O(n³)", "O(n)", "O(n²) — sort plus a two-pointer scan per anchor"], answer: 2,
    explain: "Fix one element, Two-Sum the rest." },
  { q: "Trapping Rain Water's two-pointer solution achieves…", options: ["O(n) time, O(1) space", "O(n²) time", "O(n) time, O(n) space"], answer: 0,
    explain: "Beats the prefix-max-arrays approach on space." },
  { q: "A sliding window is used for problems about…", options: ["Sorting", "CONTIGUOUS subarrays/substrings satisfying a condition", "Fixed pairs"], answer: 1,
    explain: "Window expands/contracts over contiguous ranges." },
  { q: "A sliding window typically EXPANDS by…", options: ["Resetting entirely", "Moving the left pointer", "Moving the RIGHT pointer forward"], answer: 2,
    explain: "Grow to include more elements." },
  { q: "A sliding window CONTRACTS by…", options: ["Moving the LEFT pointer forward, when the window becomes invalid", "Never — it only grows", "Moving the right pointer"], answer: 0,
    explain: "Shrink from the left once a condition is violated." },
  { q: "Sliding Window generally does NOT work when…", options: ["The condition is monotonic", "The array contains NEGATIVE numbers and you need max-sum subarray", "Looking for a fixed-size window"], answer: 1,
    explain: "Window validity is no longer monotonic with negatives present." },
  { q: "'Longest substring with at most K distinct characters' is solved with…", options: ["Binary Search", "Sliding Window", "Two Pointers (converging)"], answer: 1,
    explain: "A classic sliding window recognition cue." },
  { q: "'Detect a cycle in a linked list in O(1) space' points to…", options: ["Sliding Window", "Two Pointers converging", "Fast & Slow Pointers"], answer: 2,
    explain: "Not the same as the converging two-pointer pattern." },
  { q: "Two Pointers replaces a nested loop, turning O(n²) into…", options: ["O(n) with O(1) extra space", "O(n log n)", "O(1)"], answer: 0,
    explain: "The core value proposition of the pattern." },
  { q: "For 'find two numbers in a SORTED array summing to target', prefer…", options: ["A hash map", "Two Pointers (no extra space needed since it's sorted)", "Sorting again"], answer: 1,
    explain: "Sortedness lets two pointers work directly, O(1) space." },
  { q: "For 'find two numbers in an UNSORTED array summing to target' with no sort allowed, prefer…", options: ["Nested loops only", "A hash map (O(n) time, O(n) space)", "Two Pointers"], answer: 1,
    explain: "Sorting would cost O(n log n) and lose original indices unless tracked." },
  { q: "A monotonic window-validity condition means…", options: ["Once valid/invalid, expanding/shrinking moves it predictably in one direction", "The window never changes size", "The window's validity flips unpredictably"], answer: 0,
    explain: "This monotonicity is what sliding window relies on." },
  { q: "The window size in sliding window problems is…", options: ["Never used", "Always fixed", "Sometimes fixed, sometimes variable depending on the problem"], answer: 2,
    explain: "Both fixed-size and variable-size window variants exist." },
  { q: "'Minimum window substring containing all characters of T' is a…", options: ["Two Pointers converging problem", "Binary search problem", "Variable-size Sliding Window problem"], answer: 2,
    explain: "Expand to find validity, contract to minimize." },
  { q: "Palindrome checks with two pointers compare…", options: ["Random pairs", "Both ENDS of the string, moving inward", "Adjacent elements"], answer: 1,
    explain: "left++ and right-- until they meet." },
  { q: "Merging two sorted arrays/lists is a classic use of…", options: ["Two Pointers (one per list)", "Backtracking", "A hash map"], answer: 0,
    explain: "One pointer per sorted sequence, advance the smaller." },
  { q: "'Container with most water' uses two pointers because…", options: ["It's a graph problem", "The array must be sorted first", "Moving the SHORTER side is provably the only useful move"], answer: 2,
    explain: "Moving the taller side can never improve the area." },
  { q: "Sliding window's time complexity for a single pass is typically…", options: ["O(n²)", "O(n) — each pointer moves forward at most n times total", "O(log n)"], answer: 1,
    explain: "Both pointers move monotonically forward, bounding total work." },
]},
{ title: "Quiz 3 · Prefix Sum, Fast/Slow Pointers & Merge Intervals",
  desc: "Range queries, cycle detection, interval scheduling",
  questions: [
  { q: "A prefix sum array lets you answer any range-sum query in…", options: ["O(1) after an O(n) precompute", "O(n)", "O(log n)"], answer: 0,
    explain: "The core trade-off: precompute once, query fast." },
  { q: "For 'count subarrays summing to K,' the hash map must be seeded with…", options: ["{0: 1} — representing the empty prefix", "{K: 1}", "Nothing"], answer: 0,
    explain: "Without it, subarrays starting at index 0 are undercounted." },
  { q: "sum(i, j) in terms of prefix sums equals…", options: ["prefix[j] − prefix[i]", "prefix[i] × prefix[j]", "prefix[i] + prefix[j]"], answer: 0,
    explain: "The key algebraic identity behind the pattern." },
  { q: "2D prefix sums use which technique to compute a rectangle sum in O(1)?", options: ["Binary search", "Recursion", "Inclusion-exclusion"], answer: 2,
    explain: "Add/subtract overlapping regions correctly." },
  { q: "Fast & slow pointers detect a cycle by…", options: ["Having the fast pointer eventually LAP the slow one, in O(1) space", "Sorting the list", "Using a hash set of visited nodes"], answer: 0,
    explain: "No extra space needed, unlike a hash-set approach." },
  { q: "The gap between fast and slow pointers, once both are in a cycle, decreases by…", options: ["Exactly 1 per iteration", "2 per iteration", "It's random"], answer: 0,
    explain: "Guarantees they meet within one cycle length." },
  { q: "Floyd's second phase finds the cycle ENTRANCE because, at the meeting point…", options: ["The meeting point is always the entrance", "F = kC − a, so walking F steps from the head and F from the meeting point both land on the entrance", "F = kC + a, so both pointers must move at speed 2"], answer: 1,
    explain: "slow travelled F+a and fast 2(F+a) = F+a+kC, so F = kC − a. Phase 2 moves both pointers at EQUAL speed." },
  { q: "Finding a linked list's middle with fast/slow pointers takes…", options: ["Two full passes", "O(n²) time", "ONE pass — no need to count length first"], answer: 2,
    explain: "Fast reaches the end exactly when slow reaches the middle." },
  { q: "Merge Intervals should sort by…", options: ["End time always", "START time — the critical first step", "Interval length"], answer: 1,
    explain: "After sorting by start, only compare against the last merged interval." },
  { q: "After sorting by start time, merging only needs to compare each interval against…", options: ["Every previous interval", "The first interval only", "Only the LAST merged interval"], answer: 2,
    explain: "Sorting establishes this invariant, making one pass sufficient." },
  { q: "Meeting Rooms II (minimum rooms needed) uses…", options: ["TWO separate sorted arrays (starts and ends) swept with two pointers", "A hash map", "A single sorted array"], answer: 0,
    explain: "Tracks maximum concurrent overlap." },
  { q: "For MAXIMUM non-overlapping intervals you must sort by END, because…", options: ["It is only a convention", "Earlier starts leave more room", "Finishing earliest leaves the most room for everything after — provable by an exchange argument"], answer: 2,
    explain: "Sorting by start is wrong about 21% of the time: one long interval like [1,100] swallows the whole answer." },
  { q: "'Insert Interval' into an ALREADY-sorted list can be done in…", options: ["O(1)", "O(n) via a three-phase linear scan", "O(n log n) by re-sorting"], answer: 1,
    explain: "No need to re-sort already-sorted input." },
  { q: "The three phases of Insert Interval are…", options: ["Sort, merge, filter", "Before (no overlap), overlapping (merge), after (no overlap)", "Push, pop, push"], answer: 1,
    explain: "Exploits the pre-sorted, non-overlapping precondition." },
  { q: "A prefix sum array is best suited for…", options: ["Frequently MUTATING arrays", "Linked lists", "STATIC arrays with many range queries"], answer: 2,
    explain: "Frequent updates need a Fenwick/Segment Tree instead." },
  { q: "Brent's cycle-detection algorithm differs from Floyd's mainly by…", options: ["Making roughly half as many next() calls and yielding the cycle length directly", "Using O(n) space", "Only working on linked lists"], answer: 0,
    explain: "Brent teleports the slow pointer in powers of two instead of walking it — valuable when next() is expensive." },
  { q: "'Equilibrium index' (left sum = right sum) is solved using…", options: ["Prefix AND suffix sums", "Backtracking", "A trie"], answer: 0,
    explain: "Precompute both, then find where they're equal." },
  { q: "Not using a dummy head when reversing/modifying a linked list sublist can cause…", options: ["Faster code", "No difference at all", "Special-case bugs when the operation starts at the very first node"], answer: 2,
    explain: "A dummy node eliminates the special case entirely." },
  { q: "When timestamps are bounded integers, 'maximum concurrent' is best solved with…", options: ["A difference array in O(n + T) — no sort at all", "Binary search", "Sorting events, always"], answer: 0,
    explain: "On realistic scheduling data (86,400 seconds in a day) this is over 100x faster than sorting millions of events." },
  { q: "Merge Intervals reduces an inherently pairwise comparison problem to…", options: ["A O(n²) comparison of every pair", "A binary search", "A single O(n) linear sweep after an O(n log n) sort"], answer: 0,
    explain: "Sorting is what makes the single-pass sweep valid." },
]},
{ title: "Quiz 4 · Binary Search & Monotonic Stack",
  desc: "Search space reduction, next-greater-element, amortized stack cost",
  questions: [
  { q: "Binary search requires the search space to be…", options: ["Random", "MONOTONIC (sorted, or a condition that flips once)", "Unsorted"], answer: 1,
    explain: "A predicate that's false-then-true (or vice versa) across the range." },
  { q: "The boundary/predicate binary-search template replaces all the variants because…", options: ["It avoids recursion", "It is shorter to type", "Every variant becomes a choice of MONOTONE predicate, with one loop condition and one update rule"], answer: 2,
    explain: "lower_bound, upper_bound, count and insert position are all firstTrue(0, n, f) with a different f." },
  { q: "n ≤ 10⁹ combined with 'minimize/maximize X' strongly suggests…", options: ["Brute force", "A hash map", "Binary search on the answer"], answer: 2,
    explain: "Constraints this large rule out linear/quadratic scans." },
  { q: "A monotonic stack maintains…", options: ["Insertion order only", "Random order", "Strictly increasing or decreasing order"], answer: 2,
    explain: "Violating elements trigger pops." },
  { q: "In 'next greater element,' the stack stores…", options: ["INDICES — so distances/widths can be computed", "Nothing — it's not needed", "Values"], answer: 0,
    explain: "Values are always one lookup away; positions aren't recoverable from bare values." },
  { q: "The monotonic stack pattern is O(n) despite a nested loop because…", options: ["JavaScript optimizes it", "It's actually O(n²)", "Each element is pushed once and popped at most once — amortized O(n)"], answer: 2,
    explain: "Same amortized reasoning as dynamic array resizing." },
  { q: "Balanced Parentheses uses a stack because…", options: ["LIFO naturally matches 'most recently opened must close first'", "It's the only possible approach", "Order doesn't matter"], answer: 0,
    explain: "The nesting structure maps directly to stack semantics." },
  { q: "In Largest Rectangle in Histogram, a sentinel value (0) is added to…", options: ["Speed up the algorithm", "Force the stack to fully drain at the end, computing every remaining bar's rectangle", "Avoid an off-by-one error only"], answer: 1,
    explain: "Without it, elements still on the stack never get resolved." },
  { q: "In Largest Rectangle in Histogram, the width when popping bar j at index i is…", options: ["i − j", "i − (stack top after popping) − 1, because BOTH boundaries are exclusive", "i − left"], answer: 1,
    explain: "Everything between the new stack top and i was already popped, which means it was taller." },
  { q: "Binary search's time complexity is…", options: ["O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explain: "Halves the search space each iteration." },
  { q: "A NON-monotone predicate (such as nums[i] === target) passed to binary search…", options: ["Silently returns wrong answers on a large fraction of inputs — about 20% when fuzzed", "Errors immediately", "Still works fine"], answer: 0,
    explain: "Binary search needs the F…F,T…T shape. Equality gives F,F,T,F — verify the shape before trusting the search." },
  { q: "'Daily Temperatures' (days until warmer) uses…", options: ["Two pointers", "Binary search", "A monotonic stack storing indices"], answer: 2,
    explain: "Next-greater-element with a distance computation." },
  { q: "Storing values instead of indices on a monotonic stack fails when…", options: ["Never — it's always fine", "You need distances/widths, or the array has duplicate values", "The array is very small"], answer: 1,
    explain: "Position information can't be recovered from a bare value." },
  { q: "Remove K Digits (smallest resulting number) is a…", options: ["Binary search problem", "Backtracking problem", "Greedy monotonic-stack variant"], answer: 2,
    explain: "Pop larger digits when a smaller one would help, greedily." },
  { q: "Consistently using &lt; vs &lt;= in a monotonic stack's pop condition affects…", options: ["Only performance", "Whether equal elements are treated as 'greater' — must match the problem's exact definition", "Nothing"], answer: 1,
    explain: "A precise, deliberate choice, not arbitrary." },
  { q: "Binary search variants beyond exact match include…", options: ["Only exact-value search", "Finding the first/last occurrence, or search-on-answer over a value range", "Only sorting"], answer: 1,
    explain: "The 'variants' in the pattern name matter." },
  { q: "The empty-stack check in Balanced Parentheses matters because…", options: ["stack.pop() on an empty array can cause a false match or error", "It only affects performance", "It never matters"], answer: 0,
    explain: "A string starting with a closing bracket needs this guard." },
  { q: "In findMin on a rotated sorted array, nums[mid] must be compared with…", options: ["nums[hi] — comparing with nums[lo] fails on a NON-rotated array", "nums[lo]", "The target"], answer: 0,
    explain: "On [1,2,3] every midpoint exceeds nums[lo], sending the search right, away from the true minimum." },
  { q: "The amortized argument for monotonic stacks mirrors the amortized argument for…", options: ["Hash map collisions", "Dynamic array resizing (push/pop each happen at most once per element)", "Binary search"], answer: 1,
    explain: "Both rely on bounding TOTAL operations across the whole run, not per-iteration." },
  { q: "Explaining a monotonic stack solution's complexity in an interview should mention…", options: ["The amortized O(n) argument — each element pushed/popped at most once", "Nothing about complexity", "Just 'O(n²) because of the nested loop'"], answer: 0,
    explain: "Correctly characterizing the true complexity is part of the answer." },
]},
{ title: "Quiz 5 · Linked List Reversal & BFS/DFS",
  desc: "Three-pointer reversal, graph traversal, shortest path guarantees",
  questions: [
  { q: "Linked list reversal uses three pointers:", options: ["start, end, pivot", "prev, curr, and a saved next", "left, right, mid"], answer: 1,
    explain: "The universal skeleton for every reversal variant." },
  { q: "The order of the four lines in the linked-list reversal loop is forced because…", options: ["Any order works", "Line 2 overwrites the pointer line 1 saved, and line 3 must follow line 2 or cur points at itself", "Of style conventions"], answer: 1,
    explain: "Derive it from the data dependencies rather than memorising: save, reverse, advance prev, advance cur." },
  { q: "A dummy head node in sublist reversal eliminates…", options: ["The need for a loop", "All bugs automatically", "The special case of reversing starting at the very first node"], answer: 2,
    explain: "Every sublist now has a valid predecessor to update." },
  { q: "Reverse-Nodes-in-k-Group must count k nodes BEFORE reversing because…", options: ["A trailing group of fewer than k must be left untouched — reversing then undoing is wrong", "It is faster", "The count is needed for the return value"], answer: 0,
    explain: "Also seed the reversal with prev = groupNext, not null, or the group's tail is orphaned." },
  { q: "Finding a linked list's middle combines naturally with…", options: ["Palindrome-check and list-reordering problems", "Union-Find", "Trie construction"], answer: 0,
    explain: "Fast/slow pointers + reversal is a common composition." },
  { q: "BFS explores a graph…", options: ["Randomly", "WIDE first, level by level", "Deep first, one branch at a time"], answer: 1,
    explain: "Uses a queue." },
  { q: "DFS explores a graph…", options: ["DEEP first, via a stack or recursion", "Only on trees", "Level by level"], answer: 0,
    explain: "Commits to one branch fully before backtracking." },
  { q: "BFS guarantees the shortest path in…", options: ["An UNWEIGHTED graph", "Any graph", "A weighted graph"], answer: 0,
    explain: "Weighted graphs need Dijkstra's algorithm instead." },
  { q: "BFS must mark nodes visited when PUSHING rather than when dequeuing because…", options: ["Marking on dequeue lets a node enter the queue once per incoming edge — O(E) entries and wrong level counts", "Both are equally correct", "It is more readable"], answer: 0,
    explain: "Iterative DFS is the opposite: it marks on POP." },
  { q: "The 'snapshot queue size' trick in BFS is used to…", options: ["Avoid using a queue", "Process exactly one LEVEL per iteration (level-order/distance tracking)", "Speed up the algorithm"], answer: 1,
    explain: "Without it, you lose the ability to report which level a node was found at." },
  { q: "Recursive DFS risks…", options: ["Stack overflow on very deep/large graphs", "Being too fast", "Never finding a solution"], answer: 0,
    explain: "Switch to iterative DFS with an explicit stack for very deep inputs." },
  { q: "Iterative DFS typically marks nodes visited…", options: ["On push", "On POP/processing (unlike BFS's enqueue-time marking)", "Never"], answer: 1,
    explain: "A subtle but important difference from BFS." },
  { q: "Number of Islands (grid DFS) can mark visited cells by…", options: ["A separate Set only", "Sorting the grid", "MUTATING the grid itself (e.g., '1' → '0')"], answer: 2,
    explain: "A classic space-saving trick." },
  { q: "'Distance to the nearest X' across a grid is best solved by…", options: ["DFS", "MULTI-SOURCE BFS — seed every X at level 0 and expand once", "BFS from each X separately"], answer: 1,
    explain: "Per-source BFS is O(sources × cells); multi-source is O(cells) — about 190x faster on a 200x200 grid." },
  { q: "'Explore all possible paths' or 'does any path exist' is a strong cue for…", options: ["DFS (or either, but DFS is often simpler for existence checks)", "Binary search", "BFS specifically"], answer: 0,
    explain: "No need for BFS's shortest-path guarantee here." },
  { q: "A general graph (not a tree) traversal ALWAYS needs…", options: ["A visited set/array to avoid infinite loops from cycles", "Nothing extra", "A heap"], answer: 0,
    explain: "Trees are cycle-free by definition; general graphs are not." },
  { q: "BFS space complexity is roughly…", options: ["O(width) — can be large for wide graphs", "Always O(1)", "O(depth)"], answer: 0,
    explain: "The queue can hold an entire level's worth of nodes." },
  { q: "DFS space complexity is roughly…", options: ["Always O(n²)", "O(width)", "O(depth) — can be large for deep graphs"], answer: 2,
    explain: "Bounded by the recursion/stack depth." },
  { q: "'Clone Graph' is typically solved using…", options: ["A monotonic stack", "BFS or DFS with a visited map tracking original→copy nodes", "Binary search"], answer: 1,
    explain: "Either traversal works; the visited map prevents infinite recursion on cycles." },
  { q: "Choosing between BFS and DFS should be based primarily on…", options: ["Personal preference only", "Which is faster to type", "Whether the problem needs shortest-path guarantees (BFS) or just any/all paths (DFS)"], answer: 2,
    explain: "The decisive interview distinction between the two." },
]},
);
