// dotnet quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Delegates, Events & Lambdas",
  desc: "Func/Action/Predicate, multicast delegates, event encapsulation, closures",
  questions: [
  { q: "A delegate is…", options: ["A type-safe reference to a method", "A collection type", "A class"], answer: 0,
    explain: "C#'s equivalent of a function pointer." },
  { q: "Func<T, TResult> represents a delegate that…", options: ["Returns void", "Only works with strings", "Takes a T and RETURNS a TResult"], answer: 2,
    explain: "The last type parameter is the return type." },
  { q: "Action<T> represents a delegate that…", options: ["Returns a value", "Takes a T and returns VOID", "Is only for events"], answer: 1,
    explain: "No return value." },
  { q: "Predicate<T> is…", options: ["A custom type you must define", "The same as Action<T>", "A built-in delegate: T in, bool out"], answer: 2,
    explain: "Used by APIs like List<T>.Find." },
  { q: "A lambda expression like `x => x.IsActive` is…", options: ["Concise syntax for creating a delegate instance inline", "Only valid in LINQ", "A new language concept unrelated to delegates"], answer: 0,
    explain: "Every LINQ Where/Select call uses this." },
  { q: "A multicast delegate…", options: ["Can only wrap one method", "Can wrap MULTIPLE methods, invoked in order", "Is invalid in C#"], answer: 1,
    explain: "+= adds another target." },
  { q: "The `event` keyword restricts external code to…", options: ["Only invocation", "Only += and -= (not direct invocation or reassignment)", "Full read/write access"], answer: 1,
    explain: "Enforces encapsulation for publish/subscribe." },
  { q: "A plain public delegate field (not `event`) allows external code to…", options: ["Only subscribe", "Overwrite it entirely, discarding all other subscribers", "Nothing extra"], answer: 1,
    explain: "The key risk `event` prevents." },
  { q: "Invoking an event safely uses…", options: ["The ?.Invoke(...) null-conditional pattern", "A try/catch always", "Direct call with no check"], answer: 0,
    explain: "Guards against zero subscribers (null)." },
  { q: "Forgetting to unsubscribe (-=) a long-lived event handler can cause…", options: ["A compile error", "Faster execution", "A memory leak — the subscriber can't be garbage collected"], answer: 2,
    explain: "The publisher holds a reference to the subscriber." },
  { q: "A closure is…", options: ["A delegate with no parameters", "A sealed class", "A lambda that captures a variable from its enclosing scope"], answer: 2,
    explain: "Captures by reference, not by value snapshot." },
  { q: "A lambda capturing an outer variable…", options: ["Cannot modify it", "Gets a snapshot at creation time", "Captures BY REFERENCE — sees later changes to that variable"], answer: 2,
    explain: "Both can read and write the shared variable." },
  { q: "Historically, capturing a for-loop variable in a lambda…", options: ["Was a classic pitfall (shared variable across iterations)", "Always worked correctly", "Was impossible"], answer: 0,
    explain: "Modern C# gives each iteration its own captured variable." },
  { q: "You'd define a custom delegate type today mainly when…", options: ["Always, instead of Func/Action", "Never — they're deprecated", "Func/Action/Predicate genuinely don't fit the need"], answer: 2,
    explain: "Built-in generics cover nearly every case." },
  { q: "If one subscriber in a multicast delegate throws an exception…", options: ["The remaining subscribers still run normally", "It can stop remaining handlers from running", "Nothing happens"], answer: 1,
    explain: "A subtlety worth handling carefully." },
  { q: "EventHandler<TEventArgs> is…", options: ["A common built-in delegate shape for events", "A LINQ operator", "A collection type"], answer: 0,
    explain: "Standard .NET event pattern." },
  { q: "Delegates enable treating methods as…", options: ["Types only", "Exceptions", "VALUES — passed as arguments, stored in variables"], answer: 2,
    explain: "First-class functions in C#." },
  { q: "The -= operator on a multicast delegate…", options: ["Removes a method from the invocation list", "Adds a method", "Clears everything"], answer: 0,
    explain: "Unsubscribing." },
  { q: "Why is `event` the idiomatic choice over a raw delegate field for pub/sub?", options: ["It's faster", "It removes the need for lambdas", "It prevents external code from bypassing the publisher's control"], answer: 2,
    explain: "Encapsulation of who can raise/clear the event." },
  { q: "Every LINQ method like Where(Func<T,bool>)…", options: ["Is a method accepting a delegate parameter", "Avoids delegates entirely", "Only works with events"], answer: 0,
    explain: "LINQ is built entirely on delegates." },
]},
{ title: "Quiz 7 · Async: Tasks, Patterns & Threading",
  desc: "The await mental model, deadlocks, WhenAll, SemaphoreSlim, Channels, cancellation",
  questions: [
  { q: "Task<T> represents…", options: ["An operation that WILL complete in the future with a result", "A synchronous method", "A completed value only"], answer: 0,
    explain: "Like a Promise in JS." },
  { q: "await BLOCKS the calling thread while waiting?", options: ["Yes, always", "Only in ASP.NET Core", "No — it frees the thread back to the pool"], answer: 2,
    explain: "The core async/await mental model." },
  { q: "A cancelled operation signals cancellation by…", options: ["Setting a global flag", "Throwing OperationCanceledException — the cooperative protocol, not an error", "Returning null"], answer: 1,
    explain: "Catch OCE at the entry point and exit quietly; pass the CancellationToken down every async call." },
  { q: "async/await primarily helps with…", options: ["Faster math operations", "I/O-BOUND waiting (network, disk, DB)", "CPU-bound parallel computation"], answer: 1,
    explain: "For CPU-bound work, use Task.Run/Parallel instead." },
  { q: "Calling .Result or .Wait() on an async method can cause…", options: ["Faster execution", "A DEADLOCK in contexts with a SynchronizationContext", "Nothing unusual"], answer: 1,
    explain: "Classic WPF/WinForms/classic ASP.NET trap." },
  { q: "The deadlock fix is generally described as…", options: ["'Async all the way' — await up the entire call chain", "Always use .Result", "Add more threads"], answer: 0,
    explain: "Never mix sync blocking with async code." },
  { q: "ASP.NET Core (modern, Core) has…", options: ["No async support", "The same SynchronizationContext as WPF", "NO SynchronizationContext by default"], answer: 2,
    explain: "Makes this specific deadlock less likely there, but the rule still applies everywhere." },
  { q: "ConfigureAwait(false) is used to…", options: ["Block the thread", "Avoid capturing/resuming on the original context (library code hygiene)", "Cancel a task"], answer: 1,
    explain: "Slightly cheaper; avoids contributing to deadlocks in some hosts." },
  { q: "Awaiting two independent operations SEQUENTIALLY…", options: ["Takes roughly the SUM of both durations", "Is always fastest", "Runs them concurrently"], answer: 0,
    explain: "The second doesn't start until the first finishes." },
  { q: "Task.WhenAll is used to…", options: ["Run tasks one at a time", "Cancel all tasks", "Wait for multiple already-started tasks to all complete"], answer: 2,
    explain: "Total time becomes roughly the SLOWER of the two." },
  { q: "To run two operations concurrently, you should…", options: ["Use .Result on both", "Await each immediately as called", "Call both first WITHOUT awaiting, then Task.WhenAll"], answer: 2,
    explain: "Starting them first lets them overlap." },
  { q: "async void should generally be used…", options: ["Never, under any circumstance", "Everywhere", "Only for UI event handlers (exceptions can't be caught by callers otherwise)"], answer: 2,
    explain: "Prefer async Task elsewhere." },
  { q: "A critical section that contains an await should be protected with…", options: ["SemaphoreSlim(1,1) with WaitAsync/Release — lock can't contain await", "lock — it works fine", "volatile fields"], answer: 0,
    explain: "Monitors are thread-affine; the continuation may resume on another thread, so C# forbids await inside lock." },
  { q: "The compiler transforms an async method into…", options: ["A regular synchronous method", "A state machine with continuations", "A delegate"], answer: 1,
    explain: "How execution can 'pause and resume'." },
  { q: "A continuation after an await may resume…", options: ["Possibly on a DIFFERENT thread pool thread", "Never", "Always on the same thread"], answer: 0,
    explain: "Unless a specific context is captured." },
  { q: "Wrapping CPU-bound work in `async` alone (no Task.Run)…", options: ["Frees a thread during computation", "Improves performance automatically", "Still blocks a thread — no real benefit from async here"], answer: 2,
    explain: "async solves I/O waiting, not CPU-bound work." },
  { q: "A BOUNDED Channel<T> with FullMode.Wait gives you…", options: ["Faster writes", "Backpressure — producers await when the queue is full instead of growing memory unboundedly", "Automatic retries"], answer: 1,
    explain: "An unbounded queue with a slow consumer hides overload until OutOfMemory; bounded pushes the slowdown to producers." },
  { q: "After Task.WhenAll(taskA, taskB) completes, reading taskA.Result is…", options: ["A deadlock", "Always risky", "Safe — you know it's already complete"], answer: 2,
    explain: "No blocking occurs since it's already finished." },
  { q: "IAsyncEnumerable<T> consumed with `await foreach` is better than Task<List<T>> when…", options: ["The data is small", "Items arrive incrementally — constant memory and immediate first results", "You need the full list up front"], answer: 1,
    explain: "One item in flight instead of the whole list; streaming files, DB result sets, paged APIs." },
  { q: "The main scalability win of async/await in a web server is…", options: ["Smaller memory per request always", "Faster CPU cycles", "Serving many more concurrent requests with a limited thread pool"], answer: 2,
    explain: "Threads aren't blocked during I/O waits." },
]},
{ title: "Quiz 8 · Testing (xUnit)",
  desc: "Fact/Theory, constructor-based setup, mocking with DI, async tests",
  questions: [
  { q: "xUnit uses … for test setup (no [SetUp] attribute).", options: ["The test method itself", "The CONSTRUCTOR of the test class", "A static method"], answer: 1,
    explain: "A new instance is created per test." },
  { q: "xUnit uses … for teardown.", options: ["IDisposable.Dispose()", "A finalizer only", "[TearDown]"], answer: 0,
    explain: "Called after each test method." },
  { q: "A new instance of the test class is created…", options: ["For EVERY test method", "Never", "Once for the whole test class"], answer: 0,
    explain: "Deliberate design for test isolation." },
  { q: "[Fact] marks…", options: ["A parameterized test", "A setup method", "A single test case with no parameters"], answer: 2,
    explain: "Runs once." },
  { q: "[Theory] with [InlineData] marks…", options: ["A parameterized test run once per data set", "A teardown method", "A single test"], answer: 0,
    explain: "Avoids copy-pasting near-identical tests." },
  { q: "Arrange-Act-Assert structures a test as…", options: ["Setup → perform ONE action → verify the outcome", "Random order", "Only assertions"], answer: 0,
    explain: "Keeps tests readable and focused." },
  { q: "Depending on an interface (not a concrete class) enables…", options: ["Nothing new for testing", "Faster runtime only", "Substituting a mock/fake with zero changes to the class under test"], answer: 2,
    explain: "The core DI-testing payoff." },
  { q: "WebApplicationFactory<Program> integration tests are valuable because they exercise…", options: ["The real wiring — routing, DI, middleware, serialization, EF — in an in-memory server", "Nothing a unit test can't cover", "Only controller logic in isolation"], answer: 0,
    explain: "The layer that catches deploy-breaking failures unit tests structurally cannot see." },
  { q: "Moq's .Verify(...) is used to…", options: ["Create a mock", "Assert that a specific call was made (and how many times)", "Configure behavior"], answer: 1,
    explain: "Confirms interaction, not just outcome." },
  { q: "An async test method should be declared as…", options: ["A regular void method", "async void", "async Task"], answer: 2,
    explain: "So the test runner can await completion and catch failures." },
  { q: "async void test methods are problematic because…", options: ["The test runner can't await them — failures may be silently missed", "xUnit doesn't support async", "They're faster"], answer: 0,
    explain: "Always use async Task for async tests." },
  { q: "Sharing mutable state across tests via static fields typically causes…", options: ["More reliable tests", "Order-dependent, flaky test failures", "Faster test runs only"], answer: 1,
    explain: "xUnit's per-test instantiation is designed to avoid this by default." },
  { q: "Testing a class's private implementation details instead of its public behavior…", options: ["Produces brittle tests that break on harmless refactors", "Is best practice", "Improves coverage meaningfully"], answer: 0,
    explain: "Test observable behavior, not internals." },
  { q: "[InlineData] provides…", options: ["A mock object", "A set of literal argument values for a [Theory] test", "A teardown hook"], answer: 1,
    explain: "One test execution per InlineData entry." },
  { q: "xUnit's per-test-instance design primarily prevents…", options: ["Compilation errors", "Accidentally shared mutable state between tests", "Slow tests"], answer: 1,
    explain: "A structural safeguard against a common flakiness source." },
  { q: "Time-dependent logic ('archive orders older than 30 days') is tested without flakiness by…", options: ["Thread.Sleep in the test", "Running tests only in the morning", "Injecting TimeProvider and using a fake clock the test controls"], answer: 2,
    explain: "Never let tested code read ambient time; inject the clock and pin the boundary cases." },
  { q: "Testing whether a method threw a specific exception uses…", options: ["Assert.Equal only", "A try/catch with no assertion", "Assert.Throws<T>(...)"], answer: 2,
    explain: "A common xUnit assertion pattern." },
  { q: "Testing EF Core code against the InMemory provider instead of a real engine (e.g. Testcontainers) misses…", options: ["Unique constraints, real transactions, and LINQ translation failures", "Only performance differences", "Nothing important"], answer: 0,
    explain: "InMemory is an object store, not a database — it executes LINQ-to-Objects, so everything 'translates'." },
  { q: "The main reason for one logical assertion focus per test is…", options: ["Faster test discovery", "Clarity — knowing exactly which behavior broke when a test fails", "xUnit requires it"], answer: 1,
    explain: "AAA structure supports this discipline." },
  { q: "The key architectural practice enabling effective unit testing in C# is…", options: ["Avoiding all exceptions", "Depending on interfaces/abstractions rather than concrete implementations", "Using more static methods"], answer: 1,
    explain: "Ties directly back to the OOP and DI lessons." },
]},
{ title: "Quiz 9 · Memory, Performance, DI & EF Core",
  desc: "GC generations, IDisposable, Span<T>, benchmarking, service lifetimes, N+1 queries",
  questions: [
  { q: "Gen 0 collections are…", options: ["Rare and expensive", "Frequent and cheap — most objects die young", "Only for value types"], answer: 1,
    explain: "The generational GC hypothesis." },
  { q: "Objects of 85,000 bytes or more are allocated on…", options: ["Gen 0 like everything else", "The stack", "The Large Object Heap — collected only with Gen 2 and not compacted by default"], answer: 2,
    explain: "Repeated large temp arrays cause LOH churn → frequent expensive full collections; rent from ArrayPool instead." },
  { q: "IDisposable exists because…", options: ["The GC handles everything perfectly", "It replaces the GC entirely", "The GC doesn't understand UNMANAGED resources (files, sockets, connections)"], answer: 2,
    explain: "Deterministic cleanup for what the GC can't see." },
  { q: "A `using` statement/declaration guarantees…", options: ["The GC never runs", "Faster allocation", "Dispose() runs even if an exception occurs"], answer: 2,
    explain: "Deterministic, exception-safe cleanup." },
  { q: "Span<T> gives you…", options: ["A zero-allocation VIEW into existing memory", "A new heap allocation", "A thread-safe collection"], answer: 0,
    explain: "Pointer + length, no copy." },
  { q: "Span<T> is restricted to…", options: ["Async methods only", "Heap storage only", "Stack-only usage (ref struct) — can't be a class field"], answer: 2,
    explain: "Ensures it never outlives its memory." },
  { q: "Memory climbs steadily, the GC runs, but Gen 2 never drops. This indicates…", options: ["Allocation pressure only", "A GC bug", "A leak — objects are still REACHABLE (static collections, event subscriptions, timers)"], answer: 2,
    explain: "Diff two heap snapshots, find the accumulating type, and read its retention path to root — that path IS the diagnosis." },
  { q: "Benchmarking two methods with Stopwatch in a Debug build is unreliable because…", options: ["Loops are always optimized away", "Debug disables JIT optimization and early iterations measure JIT/tier-0 compilation, not steady-state code", "Stopwatch is inaccurate"], answer: 1,
    explain: "Use BenchmarkDotNet in Release with [MemoryDiagnoser]: warmup to steady state, statistics, and allocations per op." },
  { q: "Scoped services get…", options: ["One instance forever", "A new instance every injection", "ONE instance per request/scope"], answer: 2,
    explain: "The typical lifetime for most application services." },
  { q: "Singleton services get…", options: ["A new instance every time", "One per request", "ONE instance for the entire application lifetime"], answer: 2,
    explain: "For truly shared, thread-safe state." },
  { q: "A 'captive dependency' occurs when…", options: ["A Scoped service depends on a Transient one", "A Singleton depends on a Scoped service", "Two Transients depend on each other"], answer: 1,
    explain: "The classic DI lifetime bug." },
  { q: "DbContext should be registered as…", options: ["Scoped (AddDbContext's default)", "Transient always", "Singleton"], answer: 0,
    explain: "It isn't thread-safe; Scoped fits one-request-one-context." },
  { q: "A Singleton that legitimately needs a Scoped dependency should…", options: ["Inject it directly in the constructor", "Never use it at all", "Inject IServiceScopeFactory and create a scope on demand"], answer: 2,
    explain: "Avoids capturing a stale/disposed instance." },
  { q: "The N+1 query problem happens when…", options: ["Accessing a navigation property in a loop triggers a query PER item", "One query fetches everything needed", "A query returns too many columns"], answer: 0,
    explain: "1 query + N queries for related data." },
  { q: ".Include() in EF Core is used to…", options: ["Eager-load related data in ONE query with a JOIN", "Delete an entity", "Disable tracking"], answer: 0,
    explain: "The main fix for N+1." },
  { q: ".AsNoTracking() should be used for…", options: ["Only Singleton services", "Read-only queries — skips unnecessary change-tracking overhead", "Queries you'll SaveChanges() on"], answer: 1,
    explain: "Faster, less memory for pure reads." },
  { q: "Filtering with .Where() BEFORE materializing a query…", options: ["Filters in application memory", "Translates to SQL WHERE, filtering on the database", "Has no benefit"], answer: 1,
    explain: "Avoid ToList() then filtering in C#." },
  { q: "Symptoms: latency spikes to seconds, CPU sits at 10%, thread count climbing. The likely cause is…", options: ["A CPU-bound hot loop", "Thread-pool starvation from sync-over-async (.Result/.Wait blocking pool threads)", "Too little RAM"], answer: 1,
    explain: "Blocked threads can't run continuations, so awaited tasks can't complete — low CPU with soaring latency is the signature." },
  { q: "Using synchronous EF Core calls (ToList()) in an async web app…", options: ["Is recommended", "Blocks a thread pool thread during I/O", "Has no downside"], answer: 1,
    explain: "Always prefer the async equivalents (ToListAsync)." },
  { q: "The GC's role vs IDisposable's role can be summarized as…", options: ["GC reclaims managed memory eventually; IDisposable releases unmanaged resources promptly/deterministically", "They do the same thing", "IDisposable replaces the GC"], answer: 0,
    explain: "Complementary, not overlapping, responsibilities." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review across the whole .NET (C#) track",
  questions: [
  { q: "Reference type assignment copies…", options: ["Nothing", "The object's data", "The REFERENCE — both variables point to the same object"], answer: 2,
    explain: "Value types copy data; reference types share the object." },
  { q: "A record's equality is based on…", options: ["Reference identity", "Random hashing", "VALUE — all property values"], answer: 2,
    explain: "Unlike classes, which use reference equality by default." },
  { q: "The #1 real-world collection performance bug is…", options: ["Using IEnumerable<T>", "List.Contains() repeatedly instead of HashSet/Dictionary", "Using generics"], answer: 1,
    explain: "Turns O(n) into accidental O(n²)." },
  { q: "throw; (bare) vs throw ex; in a catch block…", options: ["Are identical", "throw; preserves the stack trace; throw ex; resets it", "throw ex; is always correct"], answer: 1,
    explain: "Always prefer bare throw when re-throwing." },
  { q: "Deferred LINQ execution means a query…", options: ["Never executes", "Doesn't execute until enumerated (foreach/ToList/Count...)", "Runs immediately when defined"], answer: 1,
    explain: "Materialize with ToList() for a stable snapshot." },
  { q: "The `event` keyword (vs a plain delegate field) prevents…", options: ["External code from overwriting/clearing all subscribers", "Multicast behavior", "Subscribing at all"], answer: 0,
    explain: "Restricts external access to += / -= only." },
  { q: "await does NOT…", options: ["Resume execution later", "Free the thread while waiting", "Block the calling thread"], answer: 2,
    explain: "It frees the thread, then resumes as a continuation." },
  { q: "The classic async deadlock is caused by…", options: ["Using ConfigureAwait(false)", "Using Task.WhenAll", "Calling .Result/.Wait() on async code in a context with a SynchronizationContext"], answer: 2,
    explain: "Fix: async all the way up." },
  { q: "`required` combined with `init` on a property means…", options: ["It's automatically validated at runtime", "Callers MUST set it at creation, and it's immutable afterwards", "The property can be changed anytime"], answer: 1,
    explain: "With nullable reference types, this trio produces models that are valid by construction — compile errors instead of runtime null checks." },
  { q: "`counter++` executed from two threads without synchronization…", options: ["Throws an exception", "Is atomic and safe", "Loses increments — it's a non-atomic load-add-store"], answer: 2,
    explain: "Use Interlocked for single atomic ops, lock for multi-step invariants, or thread-local accumulation merged once." },
  { q: "A captive dependency is a Singleton depending on a…", options: ["Static class", "Transient service", "Scoped service"], answer: 2,
    explain: "The classic DI lifetime bug." },
  { q: "The N+1 query problem is fixed with…", options: ["EF Core's .Include() for eager loading", "More RAM", "Deleting indexes"], answer: 0,
    explain: "Turns N+1 queries into one JOIN query." },
  { q: "Two threads deadlock when each holds a lock the other wants. The standard prevention is…", options: ["Adding more locks", "Global lock ORDERING — every code path acquires locks in the same canonical order", "Using Thread.Sleep between acquisitions"], answer: 1,
    explain: "A consistent order makes a circular wait impossible; the alternative is redesigning so no path holds two locks." },
  { q: "NativeAOT compiles…", options: ["DIRECTLY to native machine code at build time", "To IL, JIT-compiled at runtime", "Only for Windows"], answer: 0,
    explain: "Millisecond startup, smaller footprint, no JIT." },
  { q: "NativeAOT's main trade-off is…", options: ["Larger binaries", "Slower startup", "Losing runtime reflection/dynamic code generation flexibility"], answer: 2,
    explain: "Requires the compiler to know all code ahead of time." },
  { q: "Span<T> avoids allocation by…", options: ["Providing a view (pointer + length) into existing memory", "Copying to a new array", "Using the heap more efficiently"], answer: 0,
    explain: "Restricted to stack-only usage as a ref struct." },
  { q: "Source generators (JSON contexts, [LoggerMessage], [GeneratedRegex]) matter because they…", options: ["Move work reflection did at RUNTIME to compile time — faster, compile-checked, and NativeAOT-safe", "Shorten your source files", "Replace the need for tests"], answer: 0,
    explain: "Trimmed native binaries can't reflect over members at runtime; generated code is statically reachable." },
  { q: "Nullable reference types are enforced…", options: ["Only in Release builds", "At runtime with exceptions", "At COMPILE TIME via static analysis (warnings)"], answer: 2,
    explain: "No runtime null-check insertion." },
  { q: "Task.WhenAll is used to…", options: ["Run tasks sequentially", "Cancel tasks", "Wait for multiple already-started tasks to complete concurrently"], answer: 2,
    explain: "Total time ≈ the slower operation, not the sum." },
  { q: "The overarching theme across this .NET track is…", options: ["Memorize syntax only", "Understand WHY behind the syntax — value/reference semantics, lifetimes, deferred execution, thread behavior — to avoid subtle production bugs", "Avoid modern C# features"], answer: 1,
    explain: "Mechanism-level understanding, not just API familiarity." },
]},
);
