// dotnet quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · C# Syntax, Types & Control Flow",
  desc: "Value vs reference types, nullable reference types, pattern matching",
  questions: [
  { q: "Value types are…", options: ["Always null by default", "Copied on assignment", "Stored as pointers"], answer: 1,
    explain: "Structs/int/bool etc. copy independently." },
  { q: "Reference types on assignment…", options: ["Copy the object", "Are always immutable", "Copy the REFERENCE — both point to the same object"], answer: 2,
    explain: "Mutations through one are visible through the other." },
  { q: "Passing a struct into a method and mutating it inside…", options: ["Throws an error", "Does NOT affect the caller (it's a copy)", "Affects the caller's copy"], answer: 1,
    explain: "Value-type parameters are copied by default." },
  { q: "Nullable reference types (NRT) are…", options: ["A compile-time-only static analysis feature", "A runtime null-check mechanism", "Only for value types"], answer: 0,
    explain: "No runtime behavior change — advisory warnings." },
  { q: "string? vs string under NRT…", options: ["string? explicitly allows null; string does not (by default)", "string? is a value type", "No difference"], answer: 0,
    explain: "Makes null-handling intent explicit." },
  { q: "The null-forgiving operator (!) …", options: ["Suppresses a compiler warning with NO runtime safety", "Converts to Nullable<T>", "Adds a runtime check"], answer: 0,
    explain: "Trust me — but you can still get a NullReferenceException." },
  { q: "A switch EXPRESSION (x switch {...}) …", options: ["Is a statement only", "Can't use type patterns", "Evaluates to a value and supports rich pattern matching"], answer: 2,
    explain: "More expressive than switch statements." },
  { q: "A property pattern like Circle { Radius: > 10 } …", options: ["Only matches exact values", "Is invalid syntax", "Matches type AND destructures a property condition"], answer: 2,
    explain: "Combines type check + property test inline." },
  { q: "A `when` clause in a switch arm…", options: ["Only works with strings", "Is required always", "Adds an arbitrary boolean guard condition"], answer: 2,
    explain: "For conditions patterns alone can't express." },
  { q: "var is…", options: ["Dynamic typing", "Only for value types", "Type inference — the compiler still enforces a concrete type"], answer: 2,
    explain: "Not the same as dynamic." },
  { q: "Strings in C# are…", options: ["Reference types that behave immutably", "Structs", "Mutable value types"], answer: 0,
    explain: "Every 'mutation' returns a new string." },
  { q: "Comparing two class instances with == by default compares…", options: ["Reference identity (same object?)", "Their field values", "Nothing — it's a compile error"], answer: 0,
    explain: "Unless the class overrides equality (or is a record)." },
  { q: "A struct being compared to null (without Nullable<T>)…", options: ["Generally isn't valid — value types aren't inherently nullable", "Is always valid", "Always returns true"], answer: 0,
    explain: "Need T? (Nullable<T>) for a genuinely nullable value type." },
  { q: "Discarding a string method's return value (e.g., str.Trim();)…", options: ["Has no effect — strings are immutable, the original is unchanged", "Throws an error", "Mutates the original"], answer: 0,
    explain: "A classic bug — always use the returned value." },
  { q: "The compiler trusting a variable is non-null after an `if (x is not null)` check is called…", options: ["Flow analysis / null-state tracking", "Boxing", "Garbage collection"], answer: 0,
    explain: "Part of NRT's compile-time analysis." },
  { q: "A wildcard pattern `_` in a switch expression…", options: ["Matches nothing", "Is a syntax error", "Matches anything not caught by earlier patterns (default case)"], answer: 2,
    explain: "The catch-all arm." },
  { q: "Explicit types are often preferred over var when…", options: ["The right-hand side doesn't make the type clear", "Never — always use var", "The type is obvious"], answer: 0,
    explain: "A readability trade-off, not a safety one." },
  { q: "#nullable enable is…", options: ["Off by default forever", "On by default in modern project templates", "A runtime flag"], answer: 1,
    explain: "Compile-time feature, enabled per project/file." },
  { q: "A relational pattern like `> 10` in a switch…", options: ["Only works on strings", "Matches numeric ranges directly in a case", "Is invalid"], answer: 1,
    explain: "Part of C#'s rich pattern matching." },
  { q: "The core reason value vs reference type distinction matters is…", options: ["Syntax highlighting", "Performance only", "It determines whether mutation inside a method is visible to the caller"], answer: 2,
    explain: "Explains a huge share of real C# bugs." },
]},
{ title: "Quiz 2 · OOP: Classes, Interfaces & Records",
  desc: "Identity vs value semantics, interfaces, abstract classes",
  questions: [
  { q: "A class models…", options: ["Identity — distinct instances even with identical data", "Only static methods", "Pure data with value equality"], answer: 0,
    explain: "Reference equality by default." },
  { q: "A record models…", options: ["Only mutable data", "Identity", "Value semantics — equal if all data matches"], answer: 2,
    explain: "Auto-generated value-based equality." },
  { q: "Two records with identical property values…", options: ["Throw an exception", "ARE equal with == (value comparison)", "Are never equal"], answer: 1,
    explain: "Unlike classes, which compare by reference." },
  { q: "A `with` expression on a record…", options: ["Returns a NEW record with specified changes, original untouched", "Mutates the original", "Deletes the record"], answer: 0,
    explain: "Non-destructive mutation." },
  { q: "Record properties in the positional syntax are…", options: ["Mutable by default", "init-only by default (immutable after construction)", "Always private"], answer: 1,
    explain: "Immutability without manual readonly everywhere." },
  { q: "An interface defines…", options: ["A record", "Implementation details", "A contract — what a type CAN DO"], answer: 2,
    explain: "'Can do', not 'is a'." },
  { q: "A class can implement…", options: ["Zero interfaces only", "Only one interface", "MULTIPLE interfaces"], answer: 2,
    explain: "Unlike single class inheritance." },
  { q: "A class can inherit from…", options: ["Only ONE base class", "Many abstract classes", "No base class ever"], answer: 0,
    explain: "Single inheritance in C#." },
  { q: "Programming against an interface instead of a concrete class enables…", options: ["Nothing extra", "Swapping implementations and easy testing with fakes/mocks", "Faster compilation only"], answer: 1,
    explain: "The foundation of dependency injection." },
  { q: "init accessors allow a property to be set…", options: ["Only during object construction/initialization", "Anytime", "Never"], answer: 0,
    explain: "Immutability with clean initialization syntax." },
  { q: "private set on a property means…", options: ["Anyone can set it", "It's read-only forever", "Only code WITHIN the class can set it"], answer: 2,
    explain: "Encapsulation — controlled mutation." },
  { q: "Abstract classes are best for…", options: ["Pure data", "A family of closely related types sharing real implementation", "Cross-cutting unrelated capabilities"], answer: 1,
    explain: "'Is a' with shared code." },
  { q: "Deep inheritance hierarchies tend to cause…", options: ["The fragile base class problem", "Faster runtime", "Simpler code"], answer: 0,
    explain: "Prefer composition + interfaces." },
  { q: "A DTO/API payload is typically best modeled as a…", options: ["Record (immutable, value equality)", "Class with public setters", "Interface"], answer: 0,
    explain: "Idiomatic modern C# for data." },
  { q: "Records auto-generate…", options: ["Equals, GetHashCode, and ToString based on properties", "Only a constructor", "Nothing extra"], answer: 0,
    explain: "Significant boilerplate reduction." },
  { q: "Testing with a fake implementation of an interface is possible because…", options: ["Consuming code depends on the abstraction, not a concrete type", "Records are immutable", "Interfaces have no methods"], answer: 0,
    explain: "Swap real for fake with zero consumer changes." },
  { q: "A primary constructor (C# 12) is used to…", options: ["Define an interface", "Replace records entirely", "Reduce boilerplate for simple constructor + field assignment"], answer: 2,
    explain: "e.g., class CheckoutService(IPaymentProcessor processor)." },
  { q: "Public setters on every property risk…", options: ["Faster serialization only", "Better encapsulation", "Objects being mutated into invalid states from anywhere"], answer: 2,
    explain: "Prefer init/private set + validation." },
  { q: "Comparing a class instance to a record's equality behavior…", options: ["Is identical", "Both throw errors", "Differs — class is reference equality by default, record is value equality"], answer: 2,
    explain: "The core class-vs-record distinction." },
  { q: "The class-vs-record decision is fundamentally about…", options: ["File naming", "Performance only", "Identity semantics vs value semantics"], answer: 2,
    explain: "Eliminates a category of equality bugs." },
]},
{ title: "Quiz 3 · Collections & Generics",
  desc: "Collection interfaces, concrete types, generics, boxing",
  questions: [
  { q: "IEnumerable<T> provides…", options: ["Forward-only iteration — the base of LINQ", "Indexed access", "Key-based lookup"], answer: 0,
    explain: "The most fundamental collection interface." },
  { q: "A method should accept the…", options: ["Most specific type possible", "NARROWEST interface it actually needs", "Broadest type always"], answer: 1,
    explain: "Maximizes flexibility for callers." },
  { q: "List<T>.Contains() is…", options: ["O(1)", "O(n) — linear scan", "O(log n)"], answer: 1,
    explain: "No hashing involved." },
  { q: "Dictionary<K,V> lookup is…", options: ["O(n²)", "O(1) average — hash table", "O(n)"], answer: 1,
    explain: "The most-used fast-lookup structure." },
  { q: "HashSet<T> is ideal for…", options: ["FIFO processing", "Ordered data", "Uniqueness checks and O(1) average membership testing"], answer: 2,
    explain: "Also supports set operations." },
  { q: "Calling List.Contains() repeatedly in a loop against N items…", options: ["Is always fast", "Becomes an accidental O(n²)", "Stays O(n)"], answer: 1,
    explain: "Switch to HashSet/Dictionary for repeated checks." },
  { q: "Queue<T> is a…", options: ["LIFO structure", "FIFO structure", "Hash table"], answer: 1,
    explain: "First-in-first-out — BFS, task queues." },
  { q: "Stack<T> is a…", options: ["LIFO structure", "Sorted structure", "FIFO structure"], answer: 0,
    explain: "Last-in-first-out — undo history, DFS." },
  { q: "ConcurrentDictionary<K,V> is used for…", options: ["Single-threaded code only", "Immutable data", "Thread-safe shared state across threads"], answer: 2,
    explain: "Avoids manual locking." },
  { q: "Generics let you write code that…", options: ["Only works with one type", "Requires runtime casting", "Works with ANY type, checked at compile time"], answer: 2,
    explain: "Type-safe and reusable." },
  { q: "Using `object` parameters instead of generics costs…", options: ["Nothing", "Type safety AND boxing overhead for value types", "Only compile time"], answer: 1,
    explain: "Generics avoid both problems." },
  { q: "`where T : IComparable<T>` is an example of…", options: ["A collection type", "A method body", "A generic constraint"], answer: 2,
    explain: "Requires T support specific operations." },
  { q: "`where T : new()` requires…", options: ["T to be a struct", "T to have a public parameterless constructor", "T to implement IDisposable"], answer: 1,
    explain: "Lets the generic method call new T()." },
  { q: "Boxing occurs when…", options: ["A reference type is copied", "A generic method is called", "A value type is wrapped in a heap-allocated object (e.g., via object)"], answer: 2,
    explain: "Costs an allocation; generics avoid it." },
  { q: "ArrayList (non-generic) vs List<T>…", options: ["List<T> avoids boxing and adds type safety", "They're identical", "ArrayList is preferred today"], answer: 0,
    explain: "Use generic collections." },
  { q: "Mutating a collection while foreach-iterating it…", options: ["Is always safe", "Silently skips items", "Throws InvalidOperationException"], answer: 2,
    explain: "Iterate a copy or use a for loop instead." },
  { q: "IList<T> adds over ICollection<T>…", options: ["Indexed access and Insert/RemoveAt", "Key-based lookup", "Thread safety"], answer: 0,
    explain: "list[i], Insert, RemoveAt." },
  { q: "The most common real-world performance bug with collections is…", options: ["Repeated List.Contains() instead of HashSet/Dictionary", "Using generics", "Using IEnumerable<T>"], answer: 0,
    explain: "Turns O(n) work into accidental O(n²)." },
  { q: "ISet<T> guarantees…", options: ["Ordered elements", "Key-value pairs", "Unique elements with set operations"], answer: 2,
    explain: "Union, intersect, except, etc." },
  { q: "A method accepting List<T> when it only needs to iterate…", options: ["Is the best design", "Forces unnecessary allocations from callers who have other collection types", "Is required by C#"], answer: 1,
    explain: "Accept IEnumerable<T> instead when that's all you need." },
]},
{ title: "Quiz 4 · Exceptions & Nullability",
  desc: "try/catch, custom exceptions, TryXxx patterns, null operators",
  questions: [
  { q: "`throw;` (bare) in a catch block…", options: ["Preserves the ORIGINAL stack trace", "Resets the stack trace", "Is invalid syntax"], answer: 0,
    explain: "Always prefer bare throw when re-throwing." },
  { q: "`throw ex;` in a catch block…", options: ["RESETS the stack trace to the catch block", "Is identical to throw;", "Preserves the stack trace"], answer: 0,
    explain: "Hides where the error actually originated." },
  { q: "finally blocks…", options: ["ALWAYS run — success, exception, or early return", "Never run on exception", "Run only on success"], answer: 0,
    explain: "Guaranteed cleanup." },
  { q: "An exception FILTER — `catch (Exception ex) when (condition)` — differs from catching and re-throwing because…", options: ["Non-matching exceptions continue with the stack NOT yet unwound", "It's just shorter syntax", "Filters can't access the exception"], answer: 0,
    explain: "Filters run at the throw site's stack state, preserving dump/debugger fidelity; a filter that logs and returns false observes everything without catching." },
  { q: "Using try/catch for a routine missing dictionary key is…", options: ["An anti-pattern — exceptions are for exceptional cases", "Best practice", "Required"], answer: 0,
    explain: "Use TryGetValue instead." },
  { q: "TryGetValue / TryParse patterns…", options: ["Are slower than exceptions", "Always throw", "Avoid exception overhead for normal 'might not be there' outcomes"], answer: 2,
    explain: "Return bool + out parameter instead." },
  { q: "Exceptions in .NET are…", options: ["Only for syntax errors", "Free performance-wise", "Relatively expensive (stack unwinding, trace capture)"], answer: 2,
    explain: "Reserve them for genuine failures." },
  { q: "int? is…", options: ["Nullable<int> — a value type wrapper allowing null", "The same as int", "A reference type"], answer: 0,
    explain: "A real runtime nullable wrapper struct." },
  { q: "The ?. operator…", options: ["Throws on null", "Always returns false", "Short-circuits to null if the left side is null"], answer: 2,
    explain: "Null-conditional access." },
  { q: "The ?? operator…", options: ["Checks equality", "Is the null-forgiving operator", "Provides a fallback value if the left side is null"], answer: 2,
    explain: "Null-coalescing." },
  { q: "The ??= operator…", options: ["Assigns only if the variable is currently null", "Compares two values", "Always reassigns"], answer: 0,
    explain: "Null-coalescing assignment." },
  { q: "The ! (null-forgiving) operator…", options: ["Suppresses a compiler warning with NO runtime safety", "Adds a runtime null check", "Is the same as ??"], answer: 0,
    explain: "Trust me — but can still NullReferenceException at runtime." },
  { q: "user?.Address?.City short-circuits…", options: ["Never", "Only at the last property", "At the FIRST null in the chain"], answer: 2,
    explain: "Address and City aren't accessed if user is null." },
  { q: "Empty catch blocks (catching and doing nothing)…", options: ["Cause errors to vanish silently — dangerous", "Improve performance", "Are good practice"], answer: 0,
    explain: "At minimum, log the exception." },
  { q: "Catching Exception broadly should be…", options: ["Used sparingly, typically at application boundaries", "The default approach", "Never used"], answer: 0,
    explain: "Prefer catching specific types first." },
  { q: "Nullable value types (T?) differ from nullable reference types in that…", options: ["T? has no runtime cost", "T? is a real runtime wrapper; NRT is compile-time-only", "They're identical mechanisms"], answer: 1,
    explain: "Different mechanisms, same underlying goal." },
  { q: "`bool TryGet(string key, [NotNullWhen(true)] out User? user)` tells the compiler that…", options: ["user is never null", "The method never throws", "user is guaranteed non-null on the paths where the method returned true"], answer: 2,
    explain: "Nullability attributes teach the flow analysis your contract, so callers get no warning inside `if (TryGet(...))` without using `!`." },
  { q: "Overusing the ! operator risks…", options: ["Suppressing real warnings and reintroducing NullReferenceException risk", "Slower compilation only", "Nothing"], answer: 0,
    explain: "Only use it when genuinely verified non-null." },
  { q: "Wrapping an original exception in a new one should…", options: ["Pass the original as the innerException", "Never be done", "Discard the original"], answer: 0,
    explain: "Preserves debugging context." },
  { q: "The general principle for exceptions is…", options: ["Avoid them entirely", "Use them for all control flow", "Reserve them for genuinely exceptional, unrecoverable-at-this-level failures"], answer: 2,
    explain: "Normal outcomes use TryXxx / return values instead." },
]},
{ title: "Quiz 5 · LINQ Deep Dive",
  desc: "Deferred execution, method vs query syntax, core operators",
  questions: [
  { q: "Most LINQ operators (Where, Select...) are…", options: ["Only for arrays", "LAZILY / deferred executed until enumeration", "Immediately executed"], answer: 1,
    explain: "Nothing runs until foreach/ToList/Count/etc." },
  { q: "A deferred query enumerated AFTER its source is mutated…", options: ["Throws an error", "Reflects a frozen snapshot from creation time", "Reflects the CURRENT state of the source at enumeration time"], answer: 2,
    explain: "A common source of confusing bugs." },
  { q: ".ToList() on a query…", options: ["Forces IMMEDIATE execution, producing a stable snapshot", "Does nothing", "Keeps it lazy"], answer: 0,
    explain: "Materializes the result now." },
  { q: "Enumerating the same deferred query twice…", options: ["Re-runs the ENTIRE query pipeline each time", "Is cached automatically", "Reuses the first result"], answer: 0,
    explain: "Costly for EF Core — repeated DB round-trips." },
  { q: "Method syntax vs query syntax in LINQ…", options: ["Compile to the same underlying method calls", "Query syntax is deprecated/invalid", "Produce different results"], answer: 0,
    explain: "Method syntax is far more common in practice." },
  { q: "First() vs FirstOrDefault()…", options: ["Identical behavior", "FirstOrDefault() throws on empty", "First() throws on empty; FirstOrDefault() returns default(T)"], answer: 2,
    explain: "Choose based on whether 'no match' is expected." },
  { q: "Single() throws when…", options: ["Zero matches OR more than one match exists", "Never throws", "Exactly one match exists"], answer: 0,
    explain: "Enforces 'exactly one' as an invariant." },
  { q: "Any() vs Count() > 0…", options: ["Any() short-circuits on the first match; Count() may enumerate everything", "Identical performance always", "Count() is always faster"], answer: 0,
    explain: "Prefer Any() for existence checks." },
  { q: "SelectMany() is used to…", options: ["Sort elements", "Flatten a collection-of-collections into one sequence", "Filter elements"], answer: 1,
    explain: "e.g., all tags across all posts." },
  { q: "GroupBy() is analogous to…", options: ["SQL JOIN", "SQL GROUP BY", "SQL WHERE"], answer: 1,
    explain: "Groups elements by a key." },
  { q: "Join() is analogous to…", options: ["SQL JOIN — correlating two sequences by key", "SQL GROUP BY", "SQL ORDER BY"], answer: 0,
    explain: "Combines related sequences." },
  { q: "Calling .ToList() synchronously on an EF Core IQueryable…", options: ["Is always fine", "Is required", "Blocks a thread during I/O — bad for scalability"], answer: 2,
    explain: "Use .ToListAsync() with await instead." },
  { q: "Materializing a query early with .ToList() when it will be reused is…", options: ["Wasteful", "Both a correctness and performance fix for repeated enumeration", "Never necessary"], answer: 1,
    explain: "Avoids re-running the pipeline multiple times." },
  { q: "IEnumerable<T> vs IQueryable<T>…", options: ["IQueryable can translate expressions to another provider (e.g., SQL)", "Identical always", "IEnumerable is database-specific"], answer: 0,
    explain: "IQueryable is the basis for EF Core query translation." },
  { q: "Using First() when a sequence might be empty risks…", options: ["A silent null", "An unhandled InvalidOperationException", "A compile error"], answer: 1,
    explain: "Use FirstOrDefault() with an explicit check instead." },
  { q: "LINQ's deferred execution is efficient because…", options: ["It always caches results", "You never pay for work on data you don't end up consuming", "It runs on a separate thread"], answer: 1,
    explain: "Laziness avoids wasted computation." },
  { q: "Chaining many LINQ operators over huge in-memory collections in a hot path…", options: ["Is always faster than a loop", "Can add real allocation/iteration overhead worth profiling", "Has zero overhead"], answer: 1,
    explain: "Sometimes a plain loop wins in extremely hot code." },
  { q: "A query built with Where().Select() but never enumerated…", options: ["Throws an error", "Has already run", "Has NOT executed anything yet"], answer: 2,
    explain: "Deferred execution — nothing runs until enumeration." },
  { q: "Query syntax (`from x in ... where ... select ...`) is…", options: ["Faster than method syntax", "Less common in practice but compiles the same way", "Only for arrays"], answer: 1,
    explain: "A style choice, not a different mechanism." },
  { q: "The safest default when reusing a LINQ query result multiple times is to…", options: ["Avoid LINQ entirely", "Materialize it once with ToList()/ToArray()", "Re-enumerate it each time"], answer: 1,
    explain: "Prevents redundant re-execution." },
]},
);
