// .NET (C#) quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · C# Syntax, Types & Control Flow",
  desc: "Value vs reference types, nullable reference types, pattern matching",
  questions: [
  { q: "Value types are…", options: ["Stored as pointers", "Copied on assignment", "Always null by default"], answer: 1,
    explain: "Structs/int/bool etc. copy independently." },
  { q: "Reference types on assignment…", options: ["Copy the object", "Copy the REFERENCE — both point to the same object", "Are always immutable"], answer: 1,
    explain: "Mutations through one are visible through the other." },
  { q: "Passing a struct into a method and mutating it inside…", options: ["Affects the caller's copy", "Does NOT affect the caller (it's a copy)", "Throws an error"], answer: 1,
    explain: "Value-type parameters are copied by default." },
  { q: "Nullable reference types (NRT) are…", options: ["A runtime null-check mechanism", "A compile-time-only static analysis feature", "Only for value types"], answer: 1,
    explain: "No runtime behavior change — advisory warnings." },
  { q: "string? vs string under NRT…", options: ["No difference", "string? explicitly allows null; string does not (by default)", "string? is a value type"], answer: 1,
    explain: "Makes null-handling intent explicit." },
  { q: "The null-forgiving operator (!) …", options: ["Adds a runtime check", "Suppresses a compiler warning with NO runtime safety", "Converts to Nullable<T>"], answer: 1,
    explain: "Trust me — but you can still get a NullReferenceException." },
  { q: "A switch EXPRESSION (x switch {...}) …", options: ["Is a statement only", "Evaluates to a value and supports rich pattern matching", "Can't use type patterns"], answer: 1,
    explain: "More expressive than switch statements." },
  { q: "A property pattern like Circle { Radius: > 10 } …", options: ["Only matches exact values", "Matches type AND destructures a property condition", "Is invalid syntax"], answer: 1,
    explain: "Combines type check + property test inline." },
  { q: "A `when` clause in a switch arm…", options: ["Is required always", "Adds an arbitrary boolean guard condition", "Only works with strings"], answer: 1,
    explain: "For conditions patterns alone can't express." },
  { q: "var is…", options: ["Dynamic typing", "Type inference — the compiler still enforces a concrete type", "Only for value types"], answer: 1,
    explain: "Not the same as dynamic." },
  { q: "Strings in C# are…", options: ["Mutable value types", "Reference types that behave immutably", "Structs"], answer: 1,
    explain: "Every 'mutation' returns a new string." },
  { q: "Comparing two class instances with == by default compares…", options: ["Their field values", "Reference identity (same object?)", "Nothing — it's a compile error"], answer: 1,
    explain: "Unless the class overrides equality (or is a record)." },
  { q: "A struct being compared to null (without Nullable<T>)…", options: ["Is always valid", "Generally isn't valid — value types aren't inherently nullable", "Always returns true"], answer: 1,
    explain: "Need T? (Nullable<T>) for a genuinely nullable value type." },
  { q: "Discarding a string method's return value (e.g., str.Trim();)…", options: ["Mutates the original", "Has no effect — strings are immutable, the original is unchanged", "Throws an error"], answer: 1,
    explain: "A classic bug — always use the returned value." },
  { q: "The compiler trusting a variable is non-null after an `if (x is not null)` check is called…", options: ["Boxing", "Flow analysis / null-state tracking", "Garbage collection"], answer: 1,
    explain: "Part of NRT's compile-time analysis." },
  { q: "A wildcard pattern `_` in a switch expression…", options: ["Matches nothing", "Matches anything not caught by earlier patterns (default case)", "Is a syntax error"], answer: 1,
    explain: "The catch-all arm." },
  { q: "Explicit types are often preferred over var when…", options: ["The type is obvious", "The right-hand side doesn't make the type clear", "Never — always use var"], answer: 1,
    explain: "A readability trade-off, not a safety one." },
  { q: "#nullable enable is…", options: ["Off by default forever", "On by default in modern project templates", "A runtime flag"], answer: 1,
    explain: "Compile-time feature, enabled per project/file." },
  { q: "A relational pattern like `> 10` in a switch…", options: ["Is invalid", "Matches numeric ranges directly in a case", "Only works on strings"], answer: 1,
    explain: "Part of C#'s rich pattern matching." },
  { q: "The core reason value vs reference type distinction matters is…", options: ["Performance only", "It determines whether mutation inside a method is visible to the caller", "Syntax highlighting"], answer: 1,
    explain: "Explains a huge share of real C# bugs." }
]},
{ title: "Quiz 2 · OOP: Classes, Interfaces & Records",
  desc: "Identity vs value semantics, interfaces, abstract classes",
  questions: [
  { q: "A class models…", options: ["Pure data with value equality", "Identity — distinct instances even with identical data", "Only static methods"], answer: 1,
    explain: "Reference equality by default." },
  { q: "A record models…", options: ["Identity", "Value semantics — equal if all data matches", "Only mutable data"], answer: 1,
    explain: "Auto-generated value-based equality." },
  { q: "Two records with identical property values…", options: ["Are never equal", "ARE equal with == (value comparison)", "Throw an exception"], answer: 1,
    explain: "Unlike classes, which compare by reference." },
  { q: "A `with` expression on a record…", options: ["Mutates the original", "Returns a NEW record with specified changes, original untouched", "Deletes the record"], answer: 1,
    explain: "Non-destructive mutation." },
  { q: "Record properties in the positional syntax are…", options: ["Mutable by default", "init-only by default (immutable after construction)", "Always private"], answer: 1,
    explain: "Immutability without manual readonly everywhere." },
  { q: "An interface defines…", options: ["Implementation details", "A contract — what a type CAN DO", "A record"], answer: 1,
    explain: "'Can do', not 'is a'." },
  { q: "A class can implement…", options: ["Only one interface", "MULTIPLE interfaces", "Zero interfaces only"], answer: 1,
    explain: "Unlike single class inheritance." },
  { q: "A class can inherit from…", options: ["Many abstract classes", "Only ONE base class", "No base class ever"], answer: 1,
    explain: "Single inheritance in C#." },
  { q: "Programming against an interface instead of a concrete class enables…", options: ["Nothing extra", "Swapping implementations and easy testing with fakes/mocks", "Faster compilation only"], answer: 1,
    explain: "The foundation of dependency injection." },
  { q: "init accessors allow a property to be set…", options: ["Anytime", "Only during object construction/initialization", "Never"], answer: 1,
    explain: "Immutability with clean initialization syntax." },
  { q: "private set on a property means…", options: ["Anyone can set it", "Only code WITHIN the class can set it", "It's read-only forever"], answer: 1,
    explain: "Encapsulation — controlled mutation." },
  { q: "Abstract classes are best for…", options: ["Cross-cutting unrelated capabilities", "A family of closely related types sharing real implementation", "Pure data"], answer: 1,
    explain: "'Is a' with shared code." },
  { q: "Deep inheritance hierarchies tend to cause…", options: ["Simpler code", "The fragile base class problem", "Faster runtime"], answer: 1,
    explain: "Prefer composition + interfaces." },
  { q: "A DTO/API payload is typically best modeled as a…", options: ["Class with public setters", "Record (immutable, value equality)", "Interface"], answer: 1,
    explain: "Idiomatic modern C# for data." },
  { q: "Records auto-generate…", options: ["Nothing extra", "Equals, GetHashCode, and ToString based on properties", "Only a constructor"], answer: 1,
    explain: "Significant boilerplate reduction." },
  { q: "Testing with a fake implementation of an interface is possible because…", options: ["Records are immutable", "Consuming code depends on the abstraction, not a concrete type", "Interfaces have no methods"], answer: 1,
    explain: "Swap real for fake with zero consumer changes." },
  { q: "A primary constructor (C# 12) is used to…", options: ["Replace records entirely", "Reduce boilerplate for simple constructor + field assignment", "Define an interface"], answer: 1,
    explain: "e.g., class CheckoutService(IPaymentProcessor processor)." },
  { q: "Public setters on every property risk…", options: ["Better encapsulation", "Objects being mutated into invalid states from anywhere", "Faster serialization only"], answer: 1,
    explain: "Prefer init/private set + validation." },
  { q: "Comparing a class instance to a record's equality behavior…", options: ["Is identical", "Differs — class is reference equality by default, record is value equality", "Both throw errors"], answer: 1,
    explain: "The core class-vs-record distinction." },
  { q: "The class-vs-record decision is fundamentally about…", options: ["File naming", "Identity semantics vs value semantics", "Performance only"], answer: 1,
    explain: "Eliminates a category of equality bugs." }
]},
{ title: "Quiz 3 · Collections & Generics",
  desc: "Collection interfaces, concrete types, generics, boxing",
  questions: [
  { q: "IEnumerable<T> provides…", options: ["Indexed access", "Forward-only iteration — the base of LINQ", "Key-based lookup"], answer: 1,
    explain: "The most fundamental collection interface." },
  { q: "A method should accept the…", options: ["Most specific type possible", "NARROWEST interface it actually needs", "Broadest type always"], answer: 1,
    explain: "Maximizes flexibility for callers." },
  { q: "List<T>.Contains() is…", options: ["O(1)", "O(n) — linear scan", "O(log n)"], answer: 1,
    explain: "No hashing involved." },
  { q: "Dictionary<K,V> lookup is…", options: ["O(n)", "O(1) average — hash table", "O(n²)"], answer: 1,
    explain: "The most-used fast-lookup structure." },
  { q: "HashSet<T> is ideal for…", options: ["Ordered data", "Uniqueness checks and O(1) average membership testing", "FIFO processing"], answer: 1,
    explain: "Also supports set operations." },
  { q: "Calling List.Contains() repeatedly in a loop against N items…", options: ["Stays O(n)", "Becomes an accidental O(n²)", "Is always fast"], answer: 1,
    explain: "Switch to HashSet/Dictionary for repeated checks." },
  { q: "Queue<T> is a…", options: ["LIFO structure", "FIFO structure", "Hash table"], answer: 1,
    explain: "First-in-first-out — BFS, task queues." },
  { q: "Stack<T> is a…", options: ["FIFO structure", "LIFO structure", "Sorted structure"], answer: 1,
    explain: "Last-in-first-out — undo history, DFS." },
  { q: "ConcurrentDictionary<K,V> is used for…", options: ["Single-threaded code only", "Thread-safe shared state across threads", "Immutable data"], answer: 1,
    explain: "Avoids manual locking." },
  { q: "Generics let you write code that…", options: ["Only works with one type", "Works with ANY type, checked at compile time", "Requires runtime casting"], answer: 1,
    explain: "Type-safe and reusable." },
  { q: "Using `object` parameters instead of generics costs…", options: ["Nothing", "Type safety AND boxing overhead for value types", "Only compile time"], answer: 1,
    explain: "Generics avoid both problems." },
  { q: "`where T : IComparable<T>` is an example of…", options: ["A method body", "A generic constraint", "A collection type"], answer: 1,
    explain: "Requires T support specific operations." },
  { q: "`where T : new()` requires…", options: ["T to be a struct", "T to have a public parameterless constructor", "T to implement IDisposable"], answer: 1,
    explain: "Lets the generic method call new T()." },
  { q: "Boxing occurs when…", options: ["A reference type is copied", "A value type is wrapped in a heap-allocated object (e.g., via object)", "A generic method is called"], answer: 1,
    explain: "Costs an allocation; generics avoid it." },
  { q: "ArrayList (non-generic) vs List<T>…", options: ["ArrayList is preferred today", "List<T> avoids boxing and adds type safety", "They're identical"], answer: 1,
    explain: "Use generic collections." },
  { q: "Mutating a collection while foreach-iterating it…", options: ["Is always safe", "Throws InvalidOperationException", "Silently skips items"], answer: 1,
    explain: "Iterate a copy or use a for loop instead." },
  { q: "IList<T> adds over ICollection<T>…", options: ["Key-based lookup", "Indexed access and Insert/RemoveAt", "Thread safety"], answer: 1,
    explain: "list[i], Insert, RemoveAt." },
  { q: "The most common real-world performance bug with collections is…", options: ["Using generics", "Repeated List.Contains() instead of HashSet/Dictionary", "Using IEnumerable<T>"], answer: 1,
    explain: "Turns O(n) work into accidental O(n²)." },
  { q: "ISet<T> guarantees…", options: ["Ordered elements", "Unique elements with set operations", "Key-value pairs"], answer: 1,
    explain: "Union, intersect, except, etc." },
  { q: "A method accepting List<T> when it only needs to iterate…", options: ["Is the best design", "Forces unnecessary allocations from callers who have other collection types", "Is required by C#"], answer: 1,
    explain: "Accept IEnumerable<T> instead when that's all you need." }
]},
{ title: "Quiz 4 · Exceptions & Nullability",
  desc: "try/catch, custom exceptions, TryXxx patterns, null operators",
  questions: [
  { q: "`throw;` (bare) in a catch block…", options: ["Resets the stack trace", "Preserves the ORIGINAL stack trace", "Is invalid syntax"], answer: 1,
    explain: "Always prefer bare throw when re-throwing." },
  { q: "`throw ex;` in a catch block…", options: ["Preserves the stack trace", "RESETS the stack trace to the catch block", "Is identical to throw;"], answer: 1,
    explain: "Hides where the error actually originated." },
  { q: "finally blocks…", options: ["Run only on success", "ALWAYS run — success, exception, or early return", "Never run on exception"], answer: 1,
    explain: "Guaranteed cleanup." },
  { q: "Custom exception types are useful because…", options: ["They're required by the compiler", "Callers can catch specifically and react to that failure mode", "They run faster"], answer: 1,
    explain: "Structured, catchable information." },
  { q: "Using try/catch for a routine missing dictionary key is…", options: ["Best practice", "An anti-pattern — exceptions are for exceptional cases", "Required"], answer: 1,
    explain: "Use TryGetValue instead." },
  { q: "TryGetValue / TryParse patterns…", options: ["Always throw", "Avoid exception overhead for normal 'might not be there' outcomes", "Are slower than exceptions"], answer: 1,
    explain: "Return bool + out parameter instead." },
  { q: "Exceptions in .NET are…", options: ["Free performance-wise", "Relatively expensive (stack unwinding, trace capture)", "Only for syntax errors"], answer: 1,
    explain: "Reserve them for genuine failures." },
  { q: "int? is…", options: ["A reference type", "Nullable<int> — a value type wrapper allowing null", "The same as int"], answer: 1,
    explain: "A real runtime nullable wrapper struct." },
  { q: "The ?. operator…", options: ["Throws on null", "Short-circuits to null if the left side is null", "Always returns false"], answer: 1,
    explain: "Null-conditional access." },
  { q: "The ?? operator…", options: ["Checks equality", "Provides a fallback value if the left side is null", "Is the null-forgiving operator"], answer: 1,
    explain: "Null-coalescing." },
  { q: "The ??= operator…", options: ["Always reassigns", "Assigns only if the variable is currently null", "Compares two values"], answer: 1,
    explain: "Null-coalescing assignment." },
  { q: "The ! (null-forgiving) operator…", options: ["Adds a runtime null check", "Suppresses a compiler warning with NO runtime safety", "Is the same as ??"], answer: 1,
    explain: "Trust me — but can still NullReferenceException at runtime." },
  { q: "user?.Address?.City short-circuits…", options: ["Never", "At the FIRST null in the chain", "Only at the last property"], answer: 1,
    explain: "Address and City aren't accessed if user is null." },
  { q: "Empty catch blocks (catching and doing nothing)…", options: ["Are good practice", "Cause errors to vanish silently — dangerous", "Improve performance"], answer: 1,
    explain: "At minimum, log the exception." },
  { q: "Catching Exception broadly should be…", options: ["The default approach", "Used sparingly, typically at application boundaries", "Never used"], answer: 1,
    explain: "Prefer catching specific types first." },
  { q: "Nullable value types (T?) differ from nullable reference types in that…", answer: 1,
    options: ["They're identical mechanisms", "T? is a real runtime wrapper; NRT is compile-time-only", "T? has no runtime cost"],
    explain: "Different mechanisms, same underlying goal." },
  { q: "A method signature using TryParse returns success via…", options: ["An exception", "A bool return value plus an out parameter", "A null check only"], answer: 1,
    explain: "No exception thrown for the 'failed to parse' case." },
  { q: "Overusing the ! operator risks…", options: ["Nothing", "Suppressing real warnings and reintroducing NullReferenceException risk", "Slower compilation only"], answer: 1,
    explain: "Only use it when genuinely verified non-null." },
  { q: "Wrapping an original exception in a new one should…", options: ["Discard the original", "Pass the original as the innerException", "Never be done"], answer: 1,
    explain: "Preserves debugging context." },
  { q: "The general principle for exceptions is…", options: ["Use them for all control flow", "Reserve them for genuinely exceptional, unrecoverable-at-this-level failures", "Avoid them entirely"], answer: 1,
    explain: "Normal outcomes use TryXxx / return values instead." }
]},
{ title: "Quiz 5 · LINQ Deep Dive",
  desc: "Deferred execution, method vs query syntax, core operators",
  questions: [
  { q: "Most LINQ operators (Where, Select...) are…", options: ["Immediately executed", "LAZILY / deferred executed until enumeration", "Only for arrays"], answer: 1,
    explain: "Nothing runs until foreach/ToList/Count/etc." },
  { q: "A deferred query enumerated AFTER its source is mutated…", options: ["Reflects a frozen snapshot from creation time", "Reflects the CURRENT state of the source at enumeration time", "Throws an error"], answer: 1,
    explain: "A common source of confusing bugs." },
  { q: ".ToList() on a query…", options: ["Keeps it lazy", "Forces IMMEDIATE execution, producing a stable snapshot", "Does nothing"], answer: 1,
    explain: "Materializes the result now." },
  { q: "Enumerating the same deferred query twice…", options: ["Reuses the first result", "Re-runs the ENTIRE query pipeline each time", "Is cached automatically"], answer: 1,
    explain: "Costly for EF Core — repeated DB round-trips." },
  { q: "Method syntax vs query syntax in LINQ…", options: ["Produce different results", "Compile to the same underlying method calls", "Query syntax is deprecated/invalid"], answer: 1,
    explain: "Method syntax is far more common in practice." },
  { q: "First() vs FirstOrDefault()…", options: ["Identical behavior", "First() throws on empty; FirstOrDefault() returns default(T)", "FirstOrDefault() throws on empty"], answer: 1,
    explain: "Choose based on whether 'no match' is expected." },
  { q: "Single() throws when…", options: ["Exactly one match exists", "Zero matches OR more than one match exists", "Never throws"], answer: 1,
    explain: "Enforces 'exactly one' as an invariant." },
  { q: "Any() vs Count() > 0…", options: ["Identical performance always", "Any() short-circuits on the first match; Count() may enumerate everything", "Count() is always faster"], answer: 1,
    explain: "Prefer Any() for existence checks." },
  { q: "SelectMany() is used to…", options: ["Filter elements", "Flatten a collection-of-collections into one sequence", "Sort elements"], answer: 1,
    explain: "e.g., all tags across all posts." },
  { q: "GroupBy() is analogous to…", options: ["SQL JOIN", "SQL GROUP BY", "SQL WHERE"], answer: 1,
    explain: "Groups elements by a key." },
  { q: "Join() is analogous to…", options: ["SQL GROUP BY", "SQL JOIN — correlating two sequences by key", "SQL ORDER BY"], answer: 1,
    explain: "Combines related sequences." },
  { q: "Calling .ToList() synchronously on an EF Core IQueryable…", options: ["Is always fine", "Blocks a thread during I/O — bad for scalability", "Is required"], answer: 1,
    explain: "Use .ToListAsync() with await instead." },
  { q: "Materializing a query early with .ToList() when it will be reused is…", options: ["Wasteful", "Both a correctness and performance fix for repeated enumeration", "Never necessary"], answer: 1,
    explain: "Avoids re-running the pipeline multiple times." },
  { q: "IEnumerable<T> vs IQueryable<T>…", options: ["Identical always", "IQueryable can translate expressions to another provider (e.g., SQL)", "IEnumerable is database-specific"], answer: 1,
    explain: "IQueryable is the basis for EF Core query translation." },
  { q: "Using First() when a sequence might be empty risks…", options: ["A silent null", "An unhandled InvalidOperationException", "A compile error"], answer: 1,
    explain: "Use FirstOrDefault() with an explicit check instead." },
  { q: "LINQ's deferred execution is efficient because…", options: ["It always caches results", "You never pay for work on data you don't end up consuming", "It runs on a separate thread"], answer: 1,
    explain: "Laziness avoids wasted computation." },
  { q: "Chaining many LINQ operators over huge in-memory collections in a hot path…", options: ["Has zero overhead", "Can add real allocation/iteration overhead worth profiling", "Is always faster than a loop"], answer: 1,
    explain: "Sometimes a plain loop wins in extremely hot code." },
  { q: "A query built with Where().Select() but never enumerated…", options: ["Has already run", "Has NOT executed anything yet", "Throws an error"], answer: 1,
    explain: "Deferred execution — nothing runs until enumeration." },
  { q: "Query syntax (`from x in ... where ... select ...`) is…", options: ["Faster than method syntax", "Less common in practice but compiles the same way", "Only for arrays"], answer: 1,
    explain: "A style choice, not a different mechanism." },
  { q: "The safest default when reusing a LINQ query result multiple times is to…", options: ["Re-enumerate it each time", "Materialize it once with ToList()/ToArray()", "Avoid LINQ entirely"], answer: 1,
    explain: "Prevents redundant re-execution." }
]}
);
