// vector-databases quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Filtering & Hybrid Search",
  desc: "Pre-, post- and during-traversal filtering, BM25, and fusing two rankings correctly.",
  questions: [
  { q: "Post-filtering must over-fetch candidates by approximately:", options: ["1 divided by the filter selectivity", "k times 2, always", "The square root of the corpus size"], answer: 0,
    explain: "To return k results after filtering you need roughly k/s candidates. At 0.1% selectivity that means 10,000 candidates for 10 results." },
  { q: "Pre-filtering (resolve the filter, then exact-scan the subset) becomes the better strategy when:", options: ["The filter is broad", "The corpus is small", "The filter is narrow"], answer: 2,
    explain: "Pre-filtering gets cheaper as the filter narrows while post-filtering gets more expensive — the opposite cost curves guarantee a crossover." },
  { q: "A filtered HNSW search returning 6 results for a top-10 request indicates:", options: ["A configuration error that raises an alert", "The corpus contains only 6 documents", "Eligible nodes were too sparse for the traversal budget — with no error raised"], answer: 2,
    explain: "The store returns fewer results silently. A RAG pipeline consuming this loses 40% of its context, which is why len(results) < k is worth alerting on." },
  { q: "Filtering during traversal differs from post-filtering in that it:", options: ["Skips the graph walk entirely", "Keeps searching until it finds enough ELIGIBLE candidates", "Applies the filter before embedding"], answer: 1,
    explain: "The walk continues past ineligible nodes rather than stopping after a fixed number of candidates of any kind." },
  { q: "The strategy that beats all filtering approaches where it applies is:", options: ["Removing the filter", "Partitioning by the filter, so it becomes routing", "Increasing ef_search"], answer: 1,
    explain: "One index per tenant turns the filter into routing: no selectivity problem, no traversal penalty, and each index is small enough to search exhaustively." },
  { q: "BM25 scores a document sharing no query terms as:", options: ["Negative", "Exactly zero", "A small positive number"], answer: 1,
    explain: "No term overlap means no score — the opposite failure mode to dense retrieval, which always returns something however irrelevant." },
  { q: "BM25's IDF component means that:", options: ["Long documents score higher", "Common terms dominate the score", "Rare terms dominate the score"], answer: 2,
    explain: "A token appearing in 3 of 2M documents carries enormous weight — exactly the token an embedding discards." },
  { q: "Dense retrieval handles which query type worst?", options: ["'Contracts without an arbitration clause'", "A general topic question", "A conceptual paraphrase"], answer: 0,
    explain: "Negation is not represented in embeddings; the topic dominates, so documents WITH arbitration clauses outrank those without." },
  { q: "Blending cosine and BM25 scores with fixed weights is wrong because:", options: ["Cosine is bounded and BM25 is unbounded — the scales are incomparable", "Weights cannot be tuned", "BM25 is always larger"], answer: 0,
    explain: "Adding a bounded quantity to an unbounded one makes the weights meaningless, and they end up overfitted to a handful of queries." },
  { q: "Per-query min-max normalisation of BM25 scores is harmful because it:", options: ["Makes a terrible best-hit look exactly as confident as an excellent one", "Reverses the ranking", "Is computationally expensive"], answer: 0,
    explain: "A raw score of 2.1 and one of 31.2 both become 1.0, manufacturing confidence that was never there." },
  { q: "Reciprocal Rank Fusion works by combining:", options: ["Raw distances", "Ranks, via 1/(k + rank)", "Normalised scores"], answer: 1,
    explain: "Ranks are comparable by construction, so RRF needs no per-corpus calibration and survives a model change without re-tuning." },
  { q: "In RRF, the constant k (conventionally 60) acts as:", options: ["The number of rankers", "The number of results returned", "A damping term that rewards agreement between rankers"], answer: 2,
    explain: "It flattens the gap between adjacent ranks, so a document ranked #2 by both rankers can beat one ranked #1 by only a single ranker." },
  { q: "RRF's main weakness is that it:", options: ["Requires labelled training data", "Cannot combine more than two rankers", "Penalises a document only one ranker could possibly find"], answer: 2,
    explain: "An exact-ID match that dense retrieval cannot find is penalised for the dense ranker's ignorance — weighting or a cross-encoder addresses this." },
  { q: "In hybrid search, filters must be applied to:", options: ["Both branches identically", "Neither branch", "The dense branch only"], answer: 0,
    explain: "Filtering only the dense side lets ineligible documents in through the lexical branch — in a multi-tenant system that is a data leak, not a relevance bug." },
  { q: "Fetching only k candidates per branch before fusion is a mistake because:", options: ["Fusion has almost nothing to choose between", "It breaks the RRF formula", "It is slower"], answer: 0,
    explain: "If both branches return 10 and agree on 7, fusion picks a top-10 from 13 documents — most of hybrid's benefit evaporates. Fetch 5-10x k." },
  { q: "The two branches of a hybrid retriever should run:", options: ["Sequentially, dense first", "In separate services only", "Concurrently, so cost is max rather than sum"], answer: 2,
    explain: "They are independent, so one asyncio.gather turns +8.5 ms into +1.9 ms — the single most important implementation detail." },
  { q: "SPLADE-style sparse learned vectors provide:", options: ["A replacement for filtering", "Term-level matching plus learned semantic expansion in one index", "Lossless compression of dense vectors"], answer: 1,
    explain: "Non-zero dimensions correspond to vocabulary terms, including expansions the model learned — fixing BM25's vocabulary mismatch without losing precision on rare terms." },
  { q: "When evaluating hybrid search, results should be segmented by query class because:", options: ["It is faster to compute", "Classes have different corpus sizes", "Aggregate numbers hide that all the gain came from exact-ID and rare-term queries"], answer: 2,
    explain: "Hybrid typically also regresses slightly on paraphrase queries — a fact the aggregate conceals and that could reverse the decision on some corpora." },
  { q: "Hybrid search improves negation queries by:", options: ["Making them worse", "A large margin", "Almost nothing — neither retriever represents 'without'"], answer: 2,
    explain: "Negation is a query-understanding problem requiring rewriting or filter extraction, not a retrieval one." },
  { q: "Estimating filter selectivity for strategy selection is best done with:", options: ["Per-field cardinality statistics, multiplied for conjunctions", "An exact count on every query", "A fixed constant"], answer: 0,
    explain: "A rough estimate suffices because the strategy boundaries are wide — and being wrong toward pre-filtering is safe, since it is slow but exact." },
]},
{ title: "Quiz 7 · Chunking & Ingestion",
  desc: "Chunk size, strategies, overlap, contextual headers, small-to-big and pipeline design.",
  questions: [
  { q: "Chunking is the highest-leverage RAG decision because:", options: ["It is the most expensive to compute", "It determines the embedding model", "Every downstream stage operates on chunks it did not choose and cannot repair"], answer: 2,
    explain: "A fact split across two chunks is retrievable by none of them, however good the embeddings, index, reranker or LLM." },
  { q: "Burying a correct answer among unrelated text lowers its embedding similarity because:", options: ["Longer text is penalised by cosine", "The vector approximates an average of all the content", "The model truncates the input"], answer: 1,
    explain: "This dilution effect means a chunk containing the answer can rank below one that does not — which is why bigger chunks are not the fix." },
  { q: "The correct resolution of the small-versus-large chunk tension is:", options: ["Index small units for precision, return large units for context", "Always use the largest chunk that fits", "Pick a middle value like 600 tokens"], answer: 0,
    explain: "The small-to-big pattern decouples the retrieval unit from the generation unit rather than compromising between their opposite optima." },
  { q: "Ranked by value, chunking strategies go:", options: ["Semantic > structural > recursive > fixed", "Fixed > recursive > structural > semantic", "Structural > recursive > semantic > fixed"], answer: 2,
    explain: "Structural wins because the author already decided what belongs together. Semantic chunking costs an embedding per sentence for 1-3 points on prose and ~0 on structured documents." },
  { q: "Splitting a PDF by page is a mistake because:", options: ["A page break is a typesetting artefact, not a semantic boundary", "Pages are too long", "PDFs cannot be parsed reliably"], answer: 0,
    explain: "It reliably cuts sentences and tables in half — one of the most common production ingestion bugs." },
  { q: "Chunking a table without repeating the header row makes it:", options: ["Unusable — the numbers survive but the meaning does not", "Slightly less useful", "Faster to embed"], answer: 0,
    explain: "Column names are what give figures meaning, so every table chunk must carry the header." },
  { q: "With structural chunking, appropriate overlap is:", options: ["50%", "Zero — the boundaries are already semantic", "20-25%"], answer: 1,
    explain: "Overlap compensates for arbitrary boundaries. When headings or clauses define the splits, it only duplicates content." },
  { q: "An under-counted cost of heavy overlap is that:", options: ["Near-duplicate chunks compete for the same top-k slots", "Embedding takes longer", "Indexes cannot be built"], answer: 0,
    explain: "A top-5 result set can hold three copies of essentially the same passage, so the context window carries less distinct information than it appears to." },
  { q: "A contextual header prepends the document and heading path to a chunk. You should:", options: ["Embed the contextualised text but store and display the raw text", "Embed and display the contextualised text", "Only display it, never embed it"], answer: 0,
    explain: "The header is a retrieval aid; showing it wastes LLM context on a breadcrumb and confuses citations." },
  { q: "Contextual headers typically improve documentation recall by:", options: ["5-10 points — more than most chunking-strategy upgrades", "Under 1 point", "50 points"], answer: 0,
    explain: "'The maximum is 5' is unretrievable alone; 'Webhooks > Retry policy: The maximum is 5' is precise — and it is nearly free." },
  { q: "In small-to-big retrieval, deduplicating parent ids matters because:", options: ["Several matching children usually share one parent, returning the same section repeatedly", "It reduces embedding cost", "Parents may be corrupted"], answer: 0,
    explain: "Multiple hits in one section is a useful relevance signal, but without dedupe you fill the context window with duplicates." },
  { q: "Summary indexing (embedding an LLM summary of a section) is unique among these patterns because it:", options: ["Costs nothing", "Requires no LLM", "Can LOSE information, making omitted details unretrievable"], answer: 2,
    explain: "If the summary omits a detail, that detail becomes unfindable — so it should supplement chunk-level indexing rather than replace it." },
  { q: "Ingestion should be idempotent primarily so that:", options: ["Chunks stay ordered", "It runs faster", "Re-running it produces no duplicates, making chunking iteration affordable"], answer: 2,
    explain: "Deterministic chunk ids plus content hashing make a full re-chunk-and-re-index routine, which is what lets you sweep chunking parameters at all." },
  { q: "Upserting chunks without deleting removed ones causes:", options: ["Slower ingestion", "Duplicate ids", "Stale chunks from a shrunken document remaining retrievable forever"], answer: 2,
    explain: "A document going from 12 chunks to 8 leaves chunks 9-12 in the index. Delete by document, then insert." },
  { q: "A content hash per document exists to:", options: ["Skip re-embedding unchanged documents", "Order chunks correctly", "Detect corruption"], answer: 0,
    explain: "It usually skips 95%+ of a re-run, and avoiding needless re-embedding also prevents degrading the index with tombstones." },
  { q: "Embedding calls should be batched because:", options: ["Per-chunk calls are network-bound and 10-20x slower", "The API requires it", "Batching improves vector quality"], answer: 0,
    explain: "10,000 individual requests take ~25 minutes; 100 batched requests take ~90 seconds for identical vectors." },
  { q: "A mean pairwise cosine of 0.62 between RANDOM chunks indicates:", options: ["A dimensionality problem", "An unusually good corpus", "Shared boilerplate flattening the vector space"], answer: 2,
    explain: "Unrelated chunks should be well separated. Stripping repeated footers or templates is often the single largest recall win available." },
  { q: "A chunk-length histogram showing 18% of chunks under 50 tokens suggests:", options: ["Chunk size is too large", "Optimal granularity", "Parse failures producing fragments like 'Table 4.2' or table separators"], answer: 2,
    explain: "Fragments are unretrievable noise that still cost index memory and can occupy top-k slots. Enforce a minimum length or merge them." },
  { q: "The `model` field stored on each chunk enables you to:", options: ["Select the right reranker", "Compress vectors better", "Detect a partially-migrated index"], answer: 2,
    explain: "A mix of model values means the migration is incomplete — and vectors from different models are not comparable." },
  { q: "When retrieval quality is poor, you should sweep chunking BEFORE upgrading the embedding model because:", options: ["Chunking has no effect on cost", "Models are hard to change", "Most failures are split answers and missing context, not semantic misses"], answer: 2,
    explain: "Typical failure analyses attribute 50 of 61 retrieval failures to chunking and context; the model addresses the smallest bucket at the highest cost." },
]},
{ title: "Quiz 8 · Retrieval Pipelines & Reranking",
  desc: "The retrieval funnel, bi- vs cross-encoders, query transformations and context assembly.",
  questions: [
  { q: "A retrieval funnel narrows candidates in stages because:", options: ["Each stage uses a different database", "The most accurate scoring method is far too slow to run over the whole corpus", "Vector stores limit result sizes"], answer: 1,
    explain: "Accuracy and cost move together, so each stage spends the budget the previous one saved." },
  { q: "The asymmetry that governs funnel design is:", options: ["A chunk missed at retrieval cannot be recovered downstream; a badly-ranked one can be rescued", "Recall matters only at the last stage", "Later stages are cheaper"], answer: 0,
    explain: "That is why stage one should be generous to the point of feeling wasteful — over-retrieving costs milliseconds, under-retrieving costs a wrong answer." },
  { q: "A bi-encoder embeds query and document:", options: ["Independently, meeting only at the dot product", "Together, with full attention between them", "Using two different models"], answer: 0,
    explain: "Because the document vector does not depend on the query, documents can be embedded at ingestion and indexed — the property that makes retrieval possible." },
  { q: "A cross-encoder cannot replace retrieval because:", options: ["It only works on short text", "It is less accurate", "Its scores do not exist until the query arrives, so nothing can be pre-indexed"], answer: 2,
    explain: "Scoring 2M pairs at ~500/second is over an hour per query — it can only refine a shortlist." },
  { q: "Reranking typically changes which metric most?", options: ["nDCG@k", "Corpus size", "recall@k"], answer: 0,
    explain: "The reranker finds nothing new — it reorders what retrieval already returned. A recall-only view makes it look useless." },
  { q: "The knee in the retrieve-then-rerank candidate curve is usually around:", options: ["1000+ candidates", "25-100 candidates", "5-10 candidates"], answer: 1,
    explain: "Beyond it the reranker mostly re-sorts documents that were never going to win, and latency scales linearly." },
  { q: "If retrieval recall@50 is 0.93 and post-rerank accuracy@5 is 0.89, you should:", options: ["Improve retrieval", "Improve the reranker", "Reduce the candidate count"], answer: 0,
    explain: "The reranker is capturing nearly everything retrieval found, so the ceiling is retrieval's — the gap between the two numbers tells you which stage binds." },
  { q: "Cross-encoder scores are:", options: ["Uncalibrated logits whose scale differs per model", "Calibrated probabilities in [0,1]", "Cosine similarities"], answer: 0,
    explain: "A threshold of 'score > 0.5' copied from another model is meaningless; thresholds must be fitted on your own data." },
  { q: "Looping over reranker.predict() one pair at a time instead of batching is:", options: ["Roughly 7x slower for identical scores", "More accurate", "Equally fast"], answer: 0,
    explain: "It is the easiest way to make reranking look unaffordable when it is not." },
  { q: "A cross-encoder with max_length=512 scoring a 600-token chunk will:", options: ["Automatically split the chunk", "Silently truncate, judging the chunk on partial text", "Raise an error"], answer: 1,
    explain: "If the answer was in the truncated tail, the reranker scores the chunk as irrelevant — check what fraction of pairs is being truncated." },
  { q: "Returning empty context when nothing clears a relevance threshold is:", options: ["Always a bug", "Better than feeding the model irrelevant chunks and inviting fabrication", "Impossible to implement"], answer: 1,
    explain: "An honest 'I don't know' beats a confident wrong answer, particularly in support and compliance contexts." },
  { q: "Conversational query rewriting is essential in chat because:", options: ["A follow-up like 'and how do I turn that off?' embeds to nothing useful", "It reduces token cost", "It improves the reranker"], answer: 0,
    explain: "Without it every follow-up turn retrieves noise — this is the difference between a chat RAG system working and not." },
  { q: "Query rewriting should be skipped when:", options: ["The query is long", "Filters are present", "There is no conversation history"], answer: 2,
    explain: "On the first turn there are no references to resolve, so the LLM call cannot help and only adds latency to the most common request shape." },
  { q: "HyDE (Hypothetical Document Embeddings) works by:", options: ["Embedding an LLM-generated hypothetical answer instead of the question", "Hiding part of the query", "Generating multiple queries"], answer: 0,
    explain: "It addresses question/answer phrasing asymmetry, and helps most on jargon-heavy corpora — but costs a full LLM call and can hallucinate off-target." },
  { q: "Decomposition helps compound queries because:", options: ["It reduces the candidate count", "Shorter queries embed faster", "One vector for two questions sits between them and may retrieve neither well"], answer: 2,
    explain: "'What are the rate limits and how do I request an increase?' averages two distinct questions into a single unhelpful point." },
  { q: "The 'lost in the middle' effect means models attend most reliably to:", options: ["The exact centre of the context", "Only the first chunk", "The beginning and the end"], answer: 2,
    explain: "So context should be ordered best-first and second-best-last, rather than strictly descending by relevance." },
  { q: "Context budgets should be enforced by:", options: ["Chunk count", "Character count", "Token count"], answer: 2,
    explain: "Five chunks may be 600 tokens or 6,000 depending on chunking — budgeting by count silently overruns the model's limit." },
  { q: "Including source and date metadata in the context matters because:", options: ["It reduces token cost", "It improves embedding quality", "It enables citations and lets the model prefer current over superseded documents"], answer: 2,
    explain: "Without dates the model has no way to choose between a two-year-old document and the current one, and will happily average them." },
  { q: "When adding query transformations, the right approach is to:", options: ["Add only the most expensive one", "Stack all of them, since each sounds like an improvement", "Add one at a time and measure it against the stage below"], answer: 2,
    explain: "Stacking produces seconds of latency and no attributable stage; most pipelines find hybrid plus a reranker captures nearly all the gain." },
  { q: "The single fastest way to determine whether a failure is retrieval or generation is:", options: ["Switch embedding models", "Feed the model the gold-standard chunks directly and see if the answer is correct", "Increase the candidate count"], answer: 1,
    explain: "If gold context yields 94% correct answers, generation is fine and retrieval is the problem — one cheap experiment settles the argument." },
]},
{ title: "Quiz 9 · Evaluation, Scaling & Operations",
  desc: "Eval sets, metrics, significance testing, memory sizing, cost, caching and monitoring.",
  questions: [
  { q: "The primary retrieval metric for a RAG system is:", options: ["MRR", "precision@k", "recall@k"], answer: 2,
    explain: "The LLM cannot use a chunk it never saw. Presence in the context matters far more than position within it." },
  { q: "recall and nDCG should be reported together because:", options: ["They always move together", "A reranker changes nDCG without changing recall, and more candidates can do the reverse", "nDCG is easier to compute"], answer: 1,
    explain: "Either metric alone produces a wrong conclusion about a genuinely useful change." },
  { q: "A practical minimum size for a decision-making evaluation set is:", options: ["20-50 queries", "10,000 queries", "200 queries, with 500 as a target"], answer: 2,
    explain: "Below 200 the confidence interval is wider than any improvement you can make, so real gains and noise are indistinguishable." },
  { q: "LLM-generated evaluation queries are biased because they:", options: ["Share vocabulary with their source chunk, inflating scores", "Contain no negations", "Are too difficult"], answer: 0,
    explain: "This makes lexical retrieval look unrealistically strong. Ask explicitly for paraphrases, and replace with real queries as logs accumulate." },
  { q: "Labelling exactly one relevant chunk per query:", options: ["Overstates recall", "Systematically undercounts recall", "Is the correct approach"], answer: 1,
    explain: "Other chunks may answer equally well, so a system retrieving them is scored as wrong. Pooling across several systems fixes it." },
  { q: "A +3 point metric gain at n=100 queries is:", options: ["Usually indistinguishable from noise", "Definitely a real improvement", "Always a regression"], answer: 0,
    explain: "With 50-100 queries and no significance test, two identical systems produce a '+3 point win' roughly a quarter to a third of the time." },
  { q: "Comparing two RAG systems should use a paired test because:", options: ["Unpaired tests are invalid", "Both ran on the same queries, and pairing removes variance from query difficulty", "It is faster to compute"], answer: 1,
    explain: "Some queries are simply harder; pairing controls for that and greatly increases sensitivity." },
  { q: "Faithfulness evaluation measures whether:", options: ["Retrieval found the right chunk", "The answer matches a reference answer", "Every claim in the answer is supported by the retrieved context"], answer: 2,
    explain: "It detects hallucination without needing to know the true answer — only whether claims follow from what was supplied." },
  { q: "An LLM judge should be validated by:", options: ["Trusting the model card", "Measuring agreement against human labels on ~100 examples", "Comparing to another LLM"], answer: 1,
    explain: "Below roughly 80% judge-human agreement the output is not a measurement. Human-human agreement (~0.91) is the realistic ceiling." },
  { q: "Binary judgements with a rubric are preferred over 1-5 scores because:", options: ["They are faster", "Rubrics are optional", "1-5 scores cluster at 4 and barely discriminate"], answer: 2,
    explain: "'Is this claim supported: yes/no' produces a signal that moves; 'rate faithfulness 1-5' produces a constant." },
  { q: "A CI quality gate should check per query class rather than only the aggregate because:", options: ["Aggregates are hard to compute", "A change can gain on one class and collapse another while the overall number stays flat", "Classes have different sizes"], answer: 1,
    explain: "That trade is exactly the change you most want blocked, and an aggregate-only gate passes it." },
  { q: "Auto-updating the CI baseline after each run is dangerous because:", options: ["It is slow", "Baselines cannot be stored", "Tolerated regressions ratchet quality downward one acceptable step at a time"], answer: 2,
    explain: "Each individual change is within tolerance, and collectively they produce a much worse system." },
  { q: "Vector search capacity planning is dominated by:", options: ["Network bandwidth", "Memory, because the index must stay resident", "CPU cores"], answer: 1,
    explain: "If the index does not fit in RAM plus page cache, every query performs disk reads and no tuning recovers the latency." },
  { q: "In a typical mid-size RAG deployment, the largest cost line is:", options: ["Query embeddings", "Vector database hosting", "LLM generation tokens"], answer: 2,
    explain: "Generation is commonly ~78% of the bill, which is why retrieving fewer, better chunks is usually the biggest available saving." },
  { q: "A retrieval cache key must include the filters because omitting them:", options: ["Reduces the hit rate", "Serves one tenant's results to another — a data leak", "Breaks the TTL"], answer: 1,
    explain: "It is a correctness and security bug, not a staleness bug, and it is invisible when testing with a single tenant." },
  { q: "Semantic caching is risky because queries like 'enable webhooks' and 'disable webhooks':", options: ["Cannot be embedded", "Never appear together", "Sit around 0.94 cosine similarity with opposite answers"], answer: 2,
    explain: "That is above most cache thresholds. Use 0.97 or higher, exclude negations, and treat it as a latency optimisation carrying correctness risk." },
  { q: "Which pair of signals best detects silent vector-search degradation?", options: ["Disk usage and uptime", "Results-returned < k, and a falling median max retrieval score", "CPU usage and error rate"], answer: 1,
    explain: "Vector search degrades without erroring, so availability metrics stay green while quality falls. These two catch it weeks earlier." },
  { q: "Recall cannot be measured on live production queries because:", options: ["Latency budgets forbid it", "It is too expensive", "There is no ground truth for a real user query"], answer: 2,
    explain: "The workaround is a scheduled canary: run eval-set queries against production hourly and score them against known answers." },
  { q: "An embedding model migration must use a parallel index because:", options: ["Vectors from different models are not comparable, so a mixed index is meaningless", "It is faster", "The old index becomes read-only"], answer: 0,
    explain: "In-place migration produces two incompatible vector spaces in one index — arbitrary results, and no rollback." },
  { q: "Context poisoning refers to:", options: ["Superseded documents retrieving correctly and producing confidently wrong, correctly-cited answers", "Corrupted vectors", "Malicious documents injected by users"], answer: 0,
    explain: "It passes faithfulness checks because the claims are supported by real documents — the corpus was wrong, not the retrieval." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Full-track review: foundations, indexing, the landscape, RAG pipelines, evaluation and operations.",
  questions: [
  { q: "Which failure CANNOT be recovered by any downstream stage of a RAG pipeline?", options: ["A relevant chunk never retrieved at all", "Context ordered suboptimally", "A relevant chunk ranked 8th instead of 2nd"], answer: 0,
    explain: "Recall early, precision late: reranking and assembly can fix ordering, but nothing can retrieve what the first stage missed." },
  { q: "A team reports poor RAG quality and proposes upgrading the embedding model. The best first response is to:", options: ["Approve it — models drive quality", "Add more shards", "Attribute failures to a stage first; chunking and context usually dominate"], answer: 2,
    explain: "Typical analyses find ~50 of 61 retrieval failures are chunking and missing context, and ~10 are semantic misses — the model is the most expensive fix for the smallest bucket." },
  { q: "Which change is simultaneously a quality improvement AND a large cost reduction?", options: ["Reranking to 5 good chunks instead of sending 10 mediocre ones", "Adding more shards", "Increasing chunk overlap"], answer: 0,
    explain: "It halves the dominant LLM input cost while usually improving answers, since the extra chunks landed where the model does not attend." },
  { q: "A pgvector query returns correct results but takes 1800 ms instead of 3 ms. The most likely cause is:", options: ["Insufficient RAM", "Too many rows", "The query operator does not match the index's operator class, so it sequential-scans"], answer: 2,
    explain: "pgvector never errors on a metric mismatch — check idx_scan in pg_stat_user_indexes, and assert on the query plan in CI." },
  { q: "A store returns 6 results for a top-10 request with no error. Two plausible causes are:", options: ["Network timeout or an auth failure", "A very selective filter, or tombstones exhausting candidates", "Wrong embedding model or wrong dimensions"], answer: 1,
    explain: "Both are silent context losses. Pre-filtering fixes the first; compaction tuning fixes the second." },
  { q: "Which is the correct pairing?", options: ["Shards for QPS, replicas for capacity", "Shards for capacity, replicas for QPS", "Both add capacity and QPS equally"], answer: 1,
    explain: "Every shard runs a full top-k search, so sharding multiplies work and worsens tail latency; replicas load-balance with flat latency." },
  { q: "The best single memory-cost lever in a vector workload is usually:", options: ["int8 scalar quantisation with rescoring", "Switching vector database vendors", "Reducing the number of results returned"], answer: 0,
    explain: "4x less vector memory for 1-2 recall points that rescoring largely returns — frequently turning a three-node cluster into one node." },
  { q: "Which query does hybrid search improve LEAST?", options: ["A rare technical term", "An exact error code", "'Contracts without an arbitration clause'"], answer: 2,
    explain: "Neither embeddings nor BM25 represent negation, so it needs query understanding — a rewriting or filter-extraction step upstream." },
  { q: "The correct way to fuse dense and lexical rankings is:", options: ["0.7 x cosine + 0.3 x BM25", "Take the union and sort by cosine", "Reciprocal Rank Fusion on ranks"], answer: 2,
    explain: "The two score scales are incomparable, and per-query min-max normalisation manufactures confidence that was never there." },
  { q: "Small-to-big retrieval resolves the chunk-size tension by:", options: ["Choosing a compromise size", "Indexing small children and returning their parent sections", "Using two embedding models"], answer: 1,
    explain: "Retrieval and generation have opposite optimal sizes, so decoupling them beats compromising — and dedupe the parent ids." },
  { q: "Re-embedding unchanged documents on every ingestion run is bad because it:", options: ["Only wastes money", "Wastes money AND degrades the index, since each update is a tombstone plus an insert", "Corrupts the vectors"], answer: 1,
    explain: "A content hash per document usually skips 95%+ of a re-run and avoids the churn entirely." },
  { q: "An index rebuilt with the wrong embedding model would first be detected by:", options: ["An error in the logs", "A falling median max retrieval score", "Rising CPU usage"], answer: 1,
    explain: "There is no error — distances in a mismatched space are meaningless but still return results. The score distribution is the tell." },
  { q: "A restarted vector store node shows p50 latency of 340 ms instead of 4 ms. The cause is:", options: ["A corrupt index", "Insufficient replicas", "A cold page cache — the index is being read from disk"], answer: 2,
    explain: "Warm the node with sample queries and gate readiness on cache hit rate before adding it to the load balancer." },
  { q: "You measure recall@10 rising from 0.79 to 0.82 on 100 queries. You should:", options: ["Run a paired significance test; at n=100 this is likely noise", "Ship it — that is a 3-point gain", "Revert, since the gain is too small"], answer: 0,
    explain: "The identical delta is significant at n=500 and not at n=100 — report the confidence interval and the win/loss split." },
  { q: "Which statement about cross-encoders is TRUE?", options: ["They score query and document together, so nothing can be pre-indexed", "They can replace ANN retrieval at scale", "They are faster than bi-encoders"], answer: 0,
    explain: "That is precisely why they run second, over a shortlist, rather than over the corpus." },
  { q: "Answer quality has decayed over six months with no code deployed. The FIRST thing to check is:", options: ["The embedding model version", "The LLM provider's changelog", "Index physical state — tombstone ratio, segment count, cache hit rate"], answer: 2,
    explain: "It is the cheapest check and frequently the answer; a tell is that latency degraded alongside quality, which a pure corpus problem would not cause." },
  { q: "Keeping source text in your primary database rather than only in the vector store is important because:", options: ["Vector stores cannot store text", "It keeps the index a derived artefact, so migrations and model changes are re-indexes", "It makes queries faster"], answer: 1,
    explain: "It is what makes every future re-evaluation affordable and every migration reversible." },
  { q: "A CI evaluation gate reports overall recall down 1.4 points (within tolerance) and exact-ID recall down 33 points. It should:", options: ["Fail on the per-class regression", "Pass, since the aggregate is within tolerance", "Auto-update the baseline"], answer: 0,
    explain: "Blocking exactly this change is the most valuable thing a per-class gate does, and an aggregate-only gate would let it through." },
  { q: "The correct ordering of RAG optimisation levers by typical payoff is:", options: ["Index parameters, then chunking, then caching", "Model upgrade first, then everything else", "Chunking and context, then retrieval strategy, then reranking, then the model"], answer: 2,
    explain: "Chunking and contextual headers routinely deliver 20+ points; a model upgrade typically adds 2 for a full re-index." },
  { q: "Which statement best summarises when to leave pgvector for a dedicated store?", options: ["When there is a measured signal: index not resident, rebuild exceeding the window, or search degrading OLTP", "When the team wants a real vector database", "When the corpus exceeds one million vectors"], answer: 0,
    explain: "The operational cost of a second stateful system is permanent, so the trigger must be measured rather than a scale milestone." },
]},
);
