// vector-databases quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations & Embeddings",
  desc: "What vector databases are for, embeddings, vector space and why meaning becomes geometry.",
  questions: [
  { q: "What problem does a vector database solve that a keyword index does not?", options: ["Finding items by meaning rather than exact term overlap", "Guaranteeing ACID transactions", "Storing larger volumes of text"], answer: 0,
    explain: "Vector search retrieves by semantic proximity, so a paraphrase sharing no vocabulary with the document can still match. Keyword indexes require literal term overlap." },
  { q: "An embedding is best described as:", options: ["A fixed-length list of numbers positioning the text in a semantic space", "A hash of the text used for deduplication", "A compressed copy of the text that can be decoded back"], answer: 0,
    explain: "An embedding is a dense vector — a point in a learned space where distance approximates semantic relatedness. It is lossy and cannot be decoded back to the original text." },
  { q: "Two chunks of text produce vectors with cosine similarity 0.94. This means:", options: ["The texts share at least 94% of their words", "One text is 94% the length of the other", "The model places them very close in meaning"], answer: 2,
    explain: "Cosine similarity measures the angle between vectors, which reflects the model's judgement of semantic relatedness. It says nothing directly about shared vocabulary or length." },
  { q: "Why must the same embedding model be used for indexing and querying?", options: ["Different models produce vectors in incompatible spaces", "It is only a performance optimisation", "Query vectors are always shorter than document vectors"], answer: 0,
    explain: "Each model learns its own geometry, so distances between vectors from different models have no meaning. Mixing them produces arbitrary results, not merely degraded ones." },
  { q: "What does it mean that embeddings are 'lossy'?", options: ["Information in the text is discarded and cannot be recovered from the vector", "Some vectors fail to be stored", "Precision is lost during float arithmetic only"], answer: 0,
    explain: "Compressing a passage into a few hundred numbers necessarily discards detail — which is why exact identifiers and rare tokens survive poorly." },
  { q: "A single embedding for a long, multi-topic document tends to:", options: ["Be identical to the embedding of its first sentence", "Sit near the average of its topics and match none of them well", "Match every query about any of its topics strongly"], answer: 1,
    explain: "The vector approximates an average of the content, so it is not close to any single topic. This dilution effect is the core reason for chunking." },
  { q: "Which query type is dense retrieval WORST at?", options: ["A paraphrase using entirely different vocabulary", "A general conceptual question", "An exact error code such as ERR_CONN_4021"], answer: 2,
    explain: "Rare identifier tokens contribute almost nothing to an embedding, so dense retrieval returns topically-similar documents rather than the exact match." },
  { q: "Normalising vectors to unit length means:", options: ["Dimensionality is reduced", "Cosine similarity and inner product become equivalent", "All vectors become identical"], answer: 1,
    explain: "On unit vectors the inner product equals the cosine, which is why normalising at ingestion lets you use the cheaper inner-product operator." },
  { q: "The 'vector space' learned by an embedding model encodes relatedness as:", options: ["Alphabetical ordering of tokens", "Geometric proximity between points", "Frequency counts per document"], answer: 1,
    explain: "Training arranges the space so semantically related inputs land near one another — meaning becomes geometry, which is what makes nearest-neighbour search useful." },
  { q: "Which is NOT a legitimate use of a vector database?", options: ["Semantic search over documentation", "Serving as the authoritative system of record for your source text", "Recommendation by item similarity"], answer: 1,
    explain: "The index is a derived artefact. Keeping source text in a primary database is what makes re-indexing, model changes and store migrations possible." },
  { q: "Why do embedding models have a maximum input length?", options: ["Storage limits in the vector database", "Cosine similarity fails on long inputs", "The underlying transformer has a fixed context window"], answer: 2,
    explain: "The model architecture bounds the input; text beyond the limit is truncated silently, so a chunk longer than the window loses its tail." },
  { q: "Two documents about opposite actions — 'enable webhooks' and 'disable webhooks' — typically have:", options: ["Exactly zero similarity", "Very high cosine similarity, since the topic dominates", "Very low cosine similarity, since the meanings oppose"], answer: 1,
    explain: "Embeddings capture topic far more strongly than negation or polarity, so opposites in the same domain sit close together. This is why semantic caching is risky." },
  { q: "What is the retrieval unit in a RAG system?", options: ["The individual token", "The whole document", "The chunk"], answer: 2,
    explain: "Chunks are what get embedded, indexed, retrieved and passed to the LLM — which is why chunking decisions propagate through every downstream stage." },
  { q: "Dimensionality of a typical modern text embedding is around:", options: ["384 to 3072", "8 to 16", "millions"], answer: 0,
    explain: "Common models produce 384, 768, 1536 or 3072 dimensions. Higher dimensionality generally captures more nuance at proportionally more memory." },
  { q: "If a query embedding is far from every document in the index, the search will:", options: ["Return the nearest documents anyway, however irrelevant", "Return an error", "Return an empty result set"], answer: 0,
    explain: "Nearest-neighbour search always returns the k nearest points. Detecting 'nothing relevant' requires checking the score, which is why a low max score is worth alerting on." },
  { q: "The main advantage of storing source text alongside vectors is:", options: ["It reduces index memory", "It allows re-embedding and migration without re-collecting data", "It makes searches faster"], answer: 1,
    explain: "Because the index is derived from the text, keeping text means a model change or store migration becomes a re-index rather than a data migration." },
  { q: "Embedding a query and embedding a document with the same model produces vectors that:", options: ["Cannot be compared at all", "Require a translation matrix to compare", "Live in the same space and are directly comparable"], answer: 2,
    explain: "That shared space is exactly what makes bi-encoder retrieval possible — documents can be embedded in advance and compared to a query vector at search time." },
  { q: "Which statement about embedding models is TRUE?", options: ["Larger dimensionality always yields better retrieval", "Any two models can be mixed if dimensions match", "Model choice matters less than chunking in most RAG systems"], answer: 2,
    explain: "Measured failure analyses consistently find chunking and context problems dominate over semantic misses — the model is rarely the largest lever." },
  { q: "A 'chunk' that consists only of the string 'Table 4.2' is:", options: ["Useful context for the LLM", "Unretrievable noise that still costs index memory", "Automatically dropped by every vector store"], answer: 1,
    explain: "Fragments carry no meaning to embed, cannot retrieve usefully, and can still occupy top-k slots. Enforce a minimum chunk length during ingestion." },
  { q: "What is the primary reason to normalise embeddings at ingestion?", options: ["It reduces memory", "It improves the model's accuracy", "It lets you use the cheapest distance operator with cosine semantics"], answer: 2,
    explain: "On unit vectors, inner product equals cosine exactly, and inner product needs no division or square root — the cheapest operator with the semantics you want." },
]},
{ title: "Quiz 2 · Similarity Metrics & Dimensionality",
  desc: "Cosine, dot product, Euclidean distance, normalisation, and the curse of dimensionality.",
  questions: [
  { q: "Cosine similarity measures:", options: ["The angle between two vectors, ignoring magnitude", "The number of shared dimensions", "The straight-line distance between two points"], answer: 0,
    explain: "Cosine is magnitude-invariant — it compares direction only, which is why it is the default for text embeddings where length varies." },
  { q: "For unit-length vectors, inner product and cosine similarity are:", options: ["Unrelated", "Exactly equal", "Inversely proportional"], answer: 1,
    explain: "Cosine is the inner product divided by the product of magnitudes; when both magnitudes are 1, the division is a no-op." },
  { q: "Euclidean (L2) distance differs from cosine in that it:", options: ["Cannot be used for embeddings", "Always produces values between 0 and 1", "Is sensitive to vector magnitude"], answer: 2,
    explain: "L2 accounts for magnitude as well as direction. On normalised vectors, L2 and cosine produce the same ranking." },
  { q: "In pgvector, the operator `<#>` returns:", options: ["Cosine distance", "The NEGATIVE inner product", "L2 distance"], answer: 1,
    explain: "pgvector negates the inner product so that every operator sorts ascending. A perfect match scores -1, which trips up code written as `score > 0.7`." },
  { q: "The 'curse of dimensionality' refers to:", options: ["Vectors becoming too large to store", "Distances between points becoming increasingly similar as dimensions grow", "Models refusing to train above 1000 dimensions"], answer: 1,
    explain: "In high dimensions the ratio between nearest and farthest distances approaches 1, so the contrast that nearest-neighbour search depends on weakens." },
  { q: "Why does the curse of dimensionality NOT make text embeddings useless?", options: ["Real embeddings occupy a lower-dimensional manifold, not the full space uniformly", "Text embeddings are always low-dimensional", "The curse only applies to integers"], answer: 0,
    explain: "The theoretical result assumes uniformly distributed points. Learned embeddings cluster on a much lower-dimensional structure, preserving useful contrast." },
  { q: "Querying a pgvector index built with `vector_cosine_ops` using the `<->` operator will:", options: ["Raise an error", "Automatically convert the metric", "Silently fall back to a sequential scan"], answer: 2,
    explain: "Postgres simply cannot use the index for a mismatched operator class. Results are correct but hundreds of times slower — a silent performance bug." },
  { q: "Which metric should you generally choose for normalised text embeddings?", options: ["Hamming distance", "Inner product, for the cheapest computation with cosine semantics", "L1 (Manhattan) distance"], answer: 1,
    explain: "Normalise at ingestion, then use inner product: it equals cosine exactly on unit vectors and avoids a division and square root." },
  { q: "If two vectors point in exactly opposite directions, their cosine similarity is:", options: ["1", "0", "-1"], answer: 2,
    explain: "Cosine ranges from -1 (opposite) through 0 (orthogonal) to 1 (identical direction)." },
  { q: "Cosine DISTANCE (as opposed to similarity) for identical vectors is:", options: ["-1", "0", "1"], answer: 1,
    explain: "Cosine distance is 1 minus cosine similarity, so identical direction gives distance 0. Distances sort ascending; similarities sort descending." },
  { q: "Why is magnitude-invariance useful for text embeddings?", options: ["It makes long documents rank higher", "Document length should not by itself change semantic similarity", "It reduces storage"], answer: 1,
    explain: "Two passages about the same topic should be close regardless of one being longer, and cosine gives exactly that property." },
  { q: "A dataset where all pairwise cosine similarities between random chunks average 0.62 suggests:", options: ["The embedding model has too few dimensions", "Shared boilerplate pulling all vectors together", "An excellent, well-separated corpus"], answer: 1,
    explain: "Unrelated chunks should be well separated. High mean pairwise similarity usually means repeated footers, headers or templates — stripping them is often the largest recall win available." },
  { q: "Increasing embedding dimensionality from 384 to 1536 generally:", options: ["Always improves retrieval quality proportionally", "Increases memory 4x with diminishing quality returns", "Reduces the index size"], answer: 1,
    explain: "Memory scales linearly with dimensions while quality gains taper, which is why dimension truncation is often a good trade." },
  { q: "Matryoshka embeddings are notable because:", options: ["They require no normalisation", "They compress losslessly", "They can be truncated to fewer dimensions with graceful quality loss"], answer: 2,
    explain: "They are trained so that leading dimensions carry the most information, letting you trade memory for a small, predictable quality cost." },
  { q: "Which is TRUE about L2 distance and cosine on normalised vectors?", options: ["They produce opposite rankings", "L2 is undefined for normalised vectors", "They produce the same ranking of results"], answer: 2,
    explain: "On the unit sphere, L2 distance is a monotonic function of cosine distance, so the ordering of neighbours is identical." },
  { q: "A perfect match scoring -1 under pgvector's `<#>` operator means code filtering `WHERE score > 0.7` will:", options: ["Return precisely the WORST results", "Work correctly", "Return an empty set always"], answer: 0,
    explain: "Because the score is negated, the best matches are the most negative. A greater-than filter selects the least similar rows." },
  { q: "When comparing embeddings from a model that does NOT output normalised vectors, you should:", options: ["Use cosine, or normalise first and use inner product", "Always use raw inner product", "Use Hamming distance"], answer: 0,
    explain: "Raw inner product on unnormalised vectors is magnitude-sensitive, so longer texts can score higher for reasons unrelated to meaning." },
  { q: "In high dimensions, the ratio of the farthest to the nearest neighbour distance tends toward:", options: ["1", "Infinity", "0"], answer: 0,
    explain: "That convergence toward 1 is the mathematical statement of the curse — everything becomes roughly equidistant, eroding meaningful contrast." },
  { q: "Dimension truncation should always be:", options: ["Avoided entirely", "Validated against your evaluation set first", "Applied blindly to save memory"], answer: 1,
    explain: "Non-Matryoshka models degrade sharply rather than gracefully when truncated, so a ten-minute check against a judged query set is essential." },
  { q: "Which distance metric is a poor fit for dense text embeddings?", options: ["Inner product on normalised vectors", "Cosine", "Hamming distance"], answer: 2,
    explain: "Hamming distance counts differing bits and suits binary codes, not dense float vectors — though it becomes relevant after binary quantisation." },
]},
{ title: "Quiz 3 · Exact kNN, ANN & HNSW",
  desc: "Brute force versus approximate search, graph traversal, and the parameters that control recall.",
  questions: [
  { q: "Exact k-nearest-neighbour search over a corpus is:", options: ["Exhaustive, with recall exactly 1.0 and cost linear in corpus size", "Only possible with an index", "Approximate but very fast"], answer: 0,
    explain: "Brute force compares the query against every vector — perfectly accurate, and linear in n, which is why it stops scaling." },
  { q: "Approximate nearest neighbour (ANN) search trades:", options: ["Accuracy for storage", "A small amount of recall for a large speedup", "Memory for latency"], answer: 1,
    explain: "ANN structures skip most of the corpus, achieving sublinear query time at the cost of occasionally missing a true neighbour." },
  { q: "Recall@10 of 0.95 for an ANN index means:", options: ["On average, 9.5 of the true top-10 neighbours are found", "95% of queries return results", "Results are 95% similar to the query"], answer: 0,
    explain: "Recall@k measures the overlap between the approximate result set and the exact top-k — the standard way to quantify ANN quality." },
  { q: "HNSW builds its index as:", options: ["A flat list of clusters", "A balanced B-tree", "A multi-layer navigable small-world graph"], answer: 2,
    explain: "Upper layers have sparse long-range links for fast approach; the bottom layer is dense for fine-grained search." },
  { q: "In HNSW, the `m` parameter controls:", options: ["The number of links per node", "The search beam width", "The number of layers"], answer: 0,
    explain: "m sets graph connectivity: higher m means better recall and more memory, and it is fixed at build time." },
  { q: "The `ef_search` parameter controls:", options: ["The number of graph layers", "The size of the candidate list during search — the recall/latency dial", "Index memory usage"], answer: 1,
    explain: "ef_search is the live tuning knob: raising it explores more candidates for better recall at higher latency, and it needs no rebuild." },
  { q: "Which HNSW parameter can be changed WITHOUT rebuilding the index?", options: ["ef_search", "m", "ef_construction"], answer: 0,
    explain: "ef_search is a query-time setting, so it can be tuned per session or even per query. m and ef_construction are baked into the built graph." },
  { q: "Setting ef_search below k will:", options: ["Prevent the search from returning k good results", "Work fine", "Raise an error"], answer: 0,
    explain: "The candidate list must be larger than k for the search to have anything to choose from; ef must comfortably exceed k." },
  { q: "Why does HNSW require a LIMIT in pgvector queries?", options: ["The index is only used for top-k ordering", "SQL syntax requires it", "To prevent memory exhaustion"], answer: 0,
    explain: "Without a LIMIT the planner has no top-k to optimise, so it falls back to scanning and sorting the whole table." },
  { q: "The main disadvantage of HNSW compared with IVF is:", options: ["It cannot handle updates at all", "Higher memory usage and slower builds", "Lower recall"], answer: 1,
    explain: "HNSW stores a graph on top of the vectors and builds slowly, but achieves better recall per unit of search work." },
  { q: "Deleting a node from a built HNSW graph is avoided because:", options: ["Every neighbour list pointing at it would need repair, risking disconnection", "Deletes are not supported by the algorithm", "The format is read-only"], answer: 0,
    explain: "Repairing each referring list means re-running neighbour selection; skipping the repair leaves under-connected regions that become unreachable — a silent recall loss." },
  { q: "As HNSW search visits more nodes, recall:", options: ["Rises with diminishing returns, forming a knee", "Rises linearly forever", "Falls"], answer: 0,
    explain: "Recall/latency curves have a knee: beyond it you pay substantially more latency for a fraction of a point of recall." },
  { q: "Which is TRUE about exact search on a filtered subset?", options: ["It requires an ANN index", "It is always slower than ANN", "For a small enough subset it is both faster AND exactly correct"], answer: 2,
    explain: "Scanning a few thousand eligible vectors takes milliseconds with recall 1.0, beating approximation over the whole corpus." },
  { q: "HNSW's upper layers exist to:", options: ["Back up the bottom layer", "Provide long-range links for rapid approach to the query's neighbourhood", "Store metadata"], answer: 1,
    explain: "The hierarchy lets a search cross the space in a few hops before descending to the dense bottom layer for refinement." },
  { q: "A reasonable default for `m` in HNSW is:", options: ["2", "16", "512"], answer: 1,
    explain: "m=16 balances recall against memory for most workloads; raise it for very high dimensionality or when recall plateaus below target." },
  { q: "The correct way to tune ef_search is:", options: ["Set it as high as latency allows", "Leave it at the default", "Sweep it against measured recall until the target is met, then check latency"], answer: 2,
    explain: "Tuning is a measurement, not a guess: find the smallest value achieving your recall target, then confirm latency fits the budget." },
  { q: "`ef_construction` affects:", options: ["The number of results returned", "The quality of the graph built, and build time", "Query latency directly"], answer: 1,
    explain: "Higher ef_construction produces a better-connected graph at the cost of slower builds; it cannot be changed without rebuilding." },
  { q: "Compared with brute force, HNSW query time scales approximately:", options: ["Quadratically with n", "Linearly with n", "Logarithmically with n"], answer: 2,
    explain: "The hierarchical structure gives roughly logarithmic scaling, which is why it remains fast as corpora grow." },
  { q: "Adaptive escalation of ef_search means:", options: ["Raising ef for queries where the initial results look weak", "Using different ef values per shard", "Increasing ef every day"], answer: 0,
    explain: "Because ef_search is a per-query setting, you can spend more effort selectively on high-stakes or low-scoring queries." },
  { q: "Recall of an ANN index should be measured against:", options: ["The model's training data", "Another ANN index", "Exact brute-force results as ground truth"], answer: 2,
    explain: "Ground truth must be exact, or you are measuring agreement between two approximations rather than actual recall." },
]},
{ title: "Quiz 4 · IVF, Quantisation & Tuning",
  desc: "Inverted file indexes, product and scalar quantisation, and the recall/latency/memory triangle.",
  questions: [
  { q: "An IVF index works by:", options: ["Hashing vectors into buckets by exact value", "Clustering vectors into lists and searching only the nearest clusters", "Building a navigable graph"], answer: 1,
    explain: "IVF partitions the space with centroids; a query probes only the closest lists, skipping most of the corpus." },
  { q: "The `probes` (or `nprobe`) parameter in IVF controls:", options: ["How many clusters are searched per query", "The number of clusters built", "Vector dimensionality"], answer: 0,
    explain: "More probes means more clusters searched: higher recall, higher latency. It is IVF's equivalent of ef_search." },
  { q: "Unlike HNSW, an IVF index MUST be built:", options: ["On an empty table", "After data is loaded, because it needs rows to cluster", "Only on normalised vectors"], answer: 1,
    explain: "The centroids are derived from the data, so building on an empty table produces a useless index — a real hazard in migration scripts." },
  { q: "Product quantisation (PQ) compresses vectors by:", options: ["Splitting them into sub-vectors and replacing each with a codebook id", "Removing dimensions at random", "Storing only the first 8 dimensions"], answer: 0,
    explain: "Each sub-vector is mapped to its nearest centroid in a learned codebook, giving very high compression at some accuracy cost." },
  { q: "Scalar quantisation to int8 typically reduces vector memory by:", options: ["2x", "4x", "64x"], answer: 1,
    explain: "float32 uses 4 bytes per component and int8 uses 1, so vector memory drops 4x for roughly 1-2 recall points." },
  { q: "The recall lost to quantisation can largely be recovered by:", options: ["Increasing dimensionality", "Adding more shards", "Rescoring top candidates against full-precision vectors"], answer: 2,
    explain: "Quantised vectors narrow the field cheaply; a rescoring pass over ~100 candidates using exact vectors restores ranking accuracy for a few milliseconds." },
  { q: "The recall/latency/memory triangle means:", options: ["All three can be optimised simultaneously", "Only two of the three exist in practice", "Improving one generally costs one of the others"], answer: 2,
    explain: "Every ANN configuration is a point on this trade-off surface; the engineering task is choosing where to sit, not escaping it." },
  { q: "A reasonable IVF `lists` value for 1M vectors is approximately:", options: ["10", "1000", "1000000"], answer: 1,
    explain: "The rule of thumb is rows/1000 up to a million rows, then sqrt(rows) beyond it." },
  { q: "Compared with HNSW, IVF generally offers:", options: ["Better handling of very high dimensions", "Faster builds and lower memory", "Better recall per unit of search work"], answer: 1,
    explain: "IVF builds much faster and uses less memory, but needs more probing to reach the same recall as HNSW." },
  { q: "Binary quantisation reduces each component to:", options: ["1 byte", "1 bit", "2 bytes"], answer: 1,
    explain: "Binary codes give extreme compression and very fast Hamming-distance comparison, but require a rescoring pass to be usable." },
  { q: "The correct way to choose quantisation is:", options: ["Avoid quantisation entirely", "Always use the highest compression available", "Measure recall at each level against your evaluation set and pick the cheapest that meets target"], answer: 2,
    explain: "Compression cost in recall is corpus-dependent, so it is a measurement rather than a rule — and the memory savings are frequently the largest cost lever available." },
  { q: "`maintenance_work_mem` matters during pgvector index builds because:", options: ["It sets the number of index layers", "It controls query concurrency", "If the graph does not fit in memory the build spills to disk and takes far longer"], answer: 2,
    explain: "Sizing it to roughly the expected index size can be the difference between minutes and hours on a large build." },
  { q: "Which index type can be created on an empty table and populated incrementally?", options: ["HNSW", "IVFFlat", "Neither"], answer: 0,
    explain: "HNSW needs no pre-existing data to cluster, which makes it a natural fit for incremental ingestion pipelines." },
  { q: "Increasing IVF probes from 10 to 40 will typically:", options: ["Have no effect", "Decrease both", "Increase recall and latency"], answer: 2,
    explain: "More clusters searched means more of the corpus examined — the same recall/latency trade as ef_search in HNSW." },
  { q: "PQ's accuracy cost compared with scalar quantisation is:", options: ["Higher, because it approximates sub-vectors with centroids", "Lower", "Identical"], answer: 0,
    explain: "PQ achieves far greater compression but discards more information, typically costing 5-15 recall points without rescoring." },
  { q: "Tuning should always be validated against:", options: ["Published ANN benchmarks", "The vendor's documentation defaults", "Your own corpus and query distribution"], answer: 2,
    explain: "Public benchmarks use static, unfiltered, single-node indexes on public datasets — a workload resembling no production system." },
  { q: "Product quantisation with m=96 sub-vectors and 8 bits each stores each vector in:", options: ["96 bits", "96 bytes", "768 bytes"], answer: 1,
    explain: "8 bits per sub-vector code times 96 sub-vectors is 768 bits, i.e. 96 bytes — a massive reduction from 6144 bytes for 1536 float32 components." },
  { q: "float16 quantisation typically costs:", options: ["10-15 recall points", "Half the recall", "Nothing measurable in recall"], answer: 2,
    explain: "Halving precision from float32 to float16 is usually free in quality terms, making it an easy first step before int8." },
  { q: "Which statement about IVF centroids is TRUE?", options: ["They drift as data changes, degrading recall over time", "They are recomputed on every query", "They are fixed forever once built"], answer: 0,
    explain: "As the data distribution shifts away from the original clustering, recall degrades — periodic rebuilds address it." },
  { q: "The single best memory lever for most vector workloads is:", options: ["Adding shards", "int8 scalar quantisation with rescoring", "Reducing the number of results returned"], answer: 1,
    explain: "It cuts vector memory 4x for a recall cost that rescoring largely returns — often turning a multi-node cluster into a single node." },
]},
{ title: "Quiz 5 · pgvector & Dedicated Stores",
  desc: "SQL-native vectors, the architecture of dedicated stores, sharding, replication and consistency.",
  questions: [
  { q: "pgvector's fundamental design decision is that a vector is:", options: ["An ordinary Postgres column type", "A separate index file", "A stored procedure"], answer: 0,
    explain: "Because it is a column, transactions, foreign keys, joins, row-level security, backups and monitoring all apply to it unchanged." },
  { q: "The biggest correctness advantage of pgvector over a dedicated store is:", options: ["Transactional consistency between vectors and the rows they describe", "Faster queries", "Higher recall"], answer: 0,
    explain: "ON DELETE CASCADE removes a document's chunks atomically, eliminating orphaned vectors that cite deleted documents — a class of bug two-system setups cannot avoid." },
  { q: "pgvector's biggest performance advantage is:", options: ["Filtered search, because the planner chooses a strategy per query", "Raw ANN throughput", "Lower memory usage"], answer: 0,
    explain: "Postgres uses the vector index for broad filters and switches to a btree plus exact scan for narrow ones — automatically and exactly correctly." },
  { q: "Nearly every dedicated vector store shares which architecture?", options: ["A single mutable B-tree", "Immutable segments plus a mutable buffer plus background compaction", "A distributed hash table"], answer: 1,
    explain: "This Lucene-derived shape explains most surprising behaviour: freshness lag, latency creep during ingestion, and tombstones." },
  { q: "In a dedicated store, a successful write means the vector is:", options: ["Durable, but not necessarily searchable yet", "Immediately searchable", "Both durable and indexed"], answer: 0,
    explain: "The write is in the WAL, but it becomes searchable only once buffered or flushed — which is why tests need explicit strong consistency rather than sleeps." },
  { q: "Deleted vectors in a dedicated store are:", options: ["Moved to a separate archive index", "Removed immediately from the graph", "Tombstoned, still traversed, and reclaimed only at compaction"], answer: 2,
    explain: "Removing a node from a built HNSW graph would require repairing every neighbour list pointing at it, so stores mark and filter instead." },
  { q: "A tombstone ratio above roughly 20% causes:", options: ["No measurable effect", "Immediate errors", "Recall and latency to degrade together"], answer: 2,
    explain: "Dead nodes consume memory, traversal time and candidate slots, so top-k requests start returning fewer results while getting slower." },
  { q: "Sharding a vector collection primarily adds:", options: ["Memory capacity, at the cost of worse tail latency", "Query throughput", "Better recall"], answer: 0,
    explain: "Every shard runs a full top-k search and the coordinator merges, so total work multiplies and the query is only as fast as its slowest shard." },
  { q: "Replicas primarily add:", options: ["Higher recall", "Query throughput, with latency staying flat", "Memory capacity"], answer: 1,
    explain: "Replicas are full copies, so queries load-balance across them — the rule is shards for capacity, replicas for QPS." },
  { q: "Resharding a collection is expensive because:", options: ["It requires downtime by design", "Vectors cannot be copied", "Shard assignment is usually a hash of the id, so changing the count relocates nearly everything"], answer: 2,
    explain: "In practice resharding means creating a new collection and re-indexing, which is why shard count deserves thought before creation." },
  { q: "Searching more segments in a store causes:", options: ["Higher recall and lower latency", "No change", "Lower recall and higher latency"], answer: 2,
    explain: "Each segment is searched separately and results merged, so per-segment recall compounds unfavourably while total work rises — making compaction a performance control." },
  { q: "Which is NOT a good reason to leave pgvector for a dedicated store?", options: ["The corpus reached one million vectors", "Index rebuilds exceed the maintenance window", "The index no longer fits in RAM"], answer: 0,
    explain: "A million 1536-dimension vectors is roughly 6 GB plus a modest graph — comfortable for Postgres. Migrate on measured signals, not round numbers." },
  { q: "FAISS differs from the other stores discussed because it is:", options: ["A library with no persistence, filtering, replication or API", "A managed cloud service", "A SQL extension"], answer: 0,
    explain: "FAISS gives you an in-memory index object; everything operational is yours to build — right when building a store, usually wrong when building an application." },
  { q: "Qdrant's notable differentiator is:", options: ["Filters applied during graph traversal rather than after", "Automatic embedding generation", "Being the only store with HNSW"], answer: 0,
    explain: "Filterable HNSW keeps searching until it finds enough eligible candidates, avoiding post-filtering's collapse on selective filters." },
  { q: "In pgvector, `idx_scan = 0` on the embedding index means:", options: ["The table is empty", "The index is corrupt", "Every query is sequential-scanning instead of using the index"], answer: 2,
    explain: "It is the definitive signal of an operator mismatch, a missing LIMIT, or an invalid index — the difference between 3 ms and 1800 ms." },
  { q: "Updating a vector in a dedicated store is implemented as:", options: ["An in-place overwrite", "A tombstone plus an insert", "A no-op if dimensions match"], answer: 1,
    explain: "Segments are immutable, so re-embedding unchanged content actively degrades the index as well as wasting money — content-hash and skip." },
  { q: "The p99 of a 10-shard fan-out is roughly:", options: ["One shard's p50", "One shard's p99.9", "The same as one shard's p99"], answer: 1,
    explain: "A query is only fast if every shard is fast, so with independent latencies the former p99 becomes roughly a p90 and the real p99 comes from each shard's tail." },
  { q: "A payload or metadata index in a dedicated store is:", options: ["Required, or filters degenerate into scans", "Created automatically", "Only useful for sorting"], answer: 0,
    explain: "Most stores require explicit field indexes; without one, filtering is the most common cause of 'our vector store is slow when we filter'." },
  { q: "Choosing a store from published ANN benchmark leaderboards is unwise because they measure:", options: ["Static, unfiltered, single-node indexes on public datasets", "Only managed services", "Too many stores at once"], answer: 0,
    explain: "That workload resembles no production system — it says nothing about filtered recall, continuous ingestion, tombstones or failure behaviour." },
  { q: "A safe migration between vector stores should be:", options: ["A re-index with dual-write, shadow evaluation, then gradual traffic shift", "A big-bang cutover during a maintenance window", "A direct copy of vector files"], answer: 0,
    explain: "Shadow evaluation typically reveals a query class where the new store is worse — usually heavily-filtered queries — and finding that before cutover costs a config change rather than an incident." },
]},
);
