// redis quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Introduction & Data Model",
  desc: "In-memory, single-threaded, data structures, vs Memcached",
  questions: [
  { q: "Redis is fast primarily because it…", options: ["Keeps data in RAM (in-memory)", "Compresses everything", "Uses many threads"], answer: 0,
    explain: "RAM access is orders of magnitude faster than disk." },
  { q: "Redis executes commands…", options: ["With row locks", "Single-threaded, one at a time (atomic, no locks)", "In parallel"], answer: 1,
    explain: "Serial execution makes each command atomic." },
  { q: "A slow O(n) command in Redis…", options: ["Is parallelized", "Blocks ALL clients (single-threaded)", "Runs in background"], answer: 1,
    explain: "Avoid KEYS * on large keyspaces; use SCAN." },
  { q: "The Redis data model is…", options: ["String keys → typed values (String/Hash/List/Set/ZSet)", "Documents", "Tables"], answer: 0,
    explain: "The value's type determines available commands." },
  { q: "Redis is best described as…", options: ["Only a cache", "A relational DB", "An in-memory data-structure store (cache + much more)"], answer: 2,
    explain: "Rate limiting, leaderboards, queues, pub/sub, locks." },
  { q: "Redis is bound by…", options: ["CPU cores", "RAM (the whole dataset lives in memory)", "Disk size"], answer: 1,
    explain: "Shard with Cluster when it exceeds one node's RAM." },
  { q: "INCR is atomic without a lock because…", options: ["It's slow", "Single-threaded execution serializes commands", "It uses transactions"], answer: 1,
    explain: "No interleaving between commands." },
  { q: "Key naming convention uses…", options: ["Random ids", "namespace:id:field (colon-separated)", "No structure"], answer: 1,
    explain: "e.g., user:1000:profile; enables SCAN patterns." },
  { q: "Redis typically…", options: ["Stores files", "Replaces the primary DB", "Complements a primary DB (fast layer in front)"], answer: 2,
    explain: "Usually not the sole system of record." },
  { q: "Redis vs Memcached — Redis adds…", options: ["Data structures, persistence, replication, pub/sub, scripting", "Nothing", "Only threads"], answer: 0,
    explain: "The default modern choice." },
  { q: "Memcached's advantage is…", options: ["Simplicity + multi-threaded pure string cache", "Persistence", "Data structures"], answer: 0,
    explain: "Fine for a simple huge string cache." },
  { q: "SCAN is preferred over KEYS because…", options: ["It's exact", "It's cursor-based and non-blocking", "It sorts"], answer: 1,
    explain: "KEYS blocks the single thread." },
  { q: "A sorted set is used for…", options: ["Queues", "Objects", "Leaderboards/ranking (scored + ordered)"], answer: 2,
    explain: "The most interview-relevant structure." },
  { q: "Single-threaded is a…", options: ["Limitation only", "Deliberate design (atomicity, no lock overhead)", "Bug"], answer: 1,
    explain: "100k+ ops/sec per core; scale via instances." },
  { q: "Redis modern versions use threads for…", options: ["I/O and background tasks (execution stays serial)", "Command execution", "Nothing"], answer: 0,
    explain: "The hot command path is single-threaded." },
  { q: "Storing data larger than RAM…", options: ["Works via disk", "Is automatic", "Causes evictions/OOM — RAM is the limit"], answer: 2,
    explain: "Cap memory + eviction policy; shard if needed." },
  { q: "A List in Redis is…", options: ["Unique-only", "An ordered collection (push/pop both ends)", "Sorted"], answer: 1,
    explain: "Queues/stacks; O(1) at ends." },
  { q: "A Hash stores…", options: ["Unique members", "Field→value maps (objects)", "Ranked members"], answer: 1,
    explain: "Efficient for records/objects." },
  { q: "The 'don't block the thread' rule mirrors…", options: ["Node's event loop discipline", "SQL indexes", "Sharding"], answer: 0,
    explain: "One slow op stalls everyone." },
  { q: "Choosing the right data structure is…", options: ["Automatic", "The core Redis skill (match structure to access pattern)", "Optional"], answer: 1,
    explain: "Like MongoDB schema design." },
]},
{ title: "Quiz 2 · Strings, Keys & TTL",
  desc: "String commands, atomic counters, expiration, SCAN",
  questions: [
  { q: "INCR does…", options: ["Insert", "Index", "Atomically increment and return the new value"], answer: 2,
    explain: "Race-safe counters without app locks." },
  { q: "App-side read-modify-write counting…", options: ["Races (lost updates) — use INCR", "Is faster", "Is atomic"], answer: 0,
    explain: "Two clients both read+write the same value." },
  { q: "SET key val EX 300…", options: ["Sets value + TTL atomically", "Two commands", "No TTL"], answer: 0,
    explain: "Preferred over SET then EXPIRE (crash-safe)." },
  { q: "TTL makes Redis a good…", options: ["Queue", "Primary DB", "CACHE (keys auto-expire, bounding memory/staleness)"], answer: 2,
    explain: "Sessions, cached queries, rate windows." },
  { q: "SET key val NX…", options: ["Sets only if the key does NOT exist", "Sets only if exists", "Always sets"], answer: 0,
    explain: "XX = only if exists; used for locks/run-once." },
  { q: "Key expiration works via…", options: ["Immediate deletion", "Lazy (on access) + active (periodic sampling)", "Full scans"], answer: 1,
    explain: "Bounds memory without scanning all keys." },
  { q: "TTL key returns -1 when…", options: ["Key is gone", "The key has no expiry", "TTL expired"], answer: 1,
    explain: "-2 = key doesn't exist." },
  { q: "SET then EXPIRE (two commands) risks…", options: ["Nothing", "Slower reads", "A crash between them → TTL-less key (leak)"], answer: 2,
    explain: "Use atomic SET EX." },
  { q: "KEYS pattern in production…", options: ["Is fastest", "Is fine", "Blocks the single thread — latency for all"], answer: 2,
    explain: "Use SCAN (cursor)." },
  { q: "UNLINK vs DEL…", options: ["UNLINK frees memory asynchronously (better for big keys)", "UNLINK is slower", "Same"], answer: 0,
    explain: "Non-blocking deletion." },
  { q: "MSET/MGET…", options: ["Sort keys", "Batch multiple keys in one round trip", "Are invalid"], answer: 1,
    explain: "Reduce network round trips." },
  { q: "INCRBYFLOAT…", options: ["Atomically adds a float to a numeric string", "Rounds", "Errors on strings"], answer: 0,
    explain: "For counters/prices (mind float precision)." },
  { q: "PERSIST key…", options: ["Deletes", "Sets a TTL", "Removes the TTL (makes it permanent)"], answer: 2,
    explain: "Opposite of EXPIRE." },
  { q: "Expired-but-not-removed keys…", options: ["Still count toward memory until removed", "Never happen", "Free memory instantly"], answer: 0,
    explain: "Lazy+active expiration; usually negligible." },
  { q: "GETSET does…", options: ["Only get", "Set new value and return the old (atomic swap)", "Only set"], answer: 1,
    explain: "One-shot swap." },
  { q: "The atomic-counter pattern underlies…", options: ["Nothing", "Sorting", "Rate limiters, view counters, unique IDs"], answer: 2,
    explain: "INCR + EXPIRE (use-cases lesson)." },
  { q: "SCAN returns…", options: ["A cursor + a batch (loop until cursor 0)", "All keys at once", "Sorted keys"], answer: 0,
    explain: "Non-blocking iteration." },
  { q: "Huge single string values…", options: ["Cause big-value latency/memory — split or use hashes", "Are ideal", "Compress automatically"], answer: 0,
    explain: "Keep values modest." },
  { q: "Cache keys should…", options: ["Be permanent", "Always have a TTL (bound memory)", "Never expire"], answer: 1,
    explain: "Even with explicit invalidation." },
  { q: "SET NX is the basis of…", options: ["Sorting", "Pub/Sub", "A simple lock / run-once (locks lesson)"], answer: 2,
    explain: "Only one client 'wins' the SET." },
]},
{ title: "Quiz 3 · Data Structures",
  desc: "Hashes, Lists, Sets, Sorted Sets, choosing structures",
  questions: [
  { q: "A Hash is best for…", options: ["Objects (field→value)", "Queues", "Rankings"], answer: 0,
    explain: "Store a user/product under one key with fields." },
  { q: "A List with BLPOP implements…", options: ["A blocking queue (producer/consumer)", "A cache", "A leaderboard"], answer: 0,
    explain: "Wait for the next job without polling." },
  { q: "A Set provides…", options: ["Ordering", "Scores", "Unique membership + set algebra (SINTER/SUNION/SDIFF)"], answer: 2,
    explain: "'Followers of both A and B' = one SINTER." },
  { q: "A Sorted Set is THE structure for…", options: ["Leaderboards/ranking (scored, O(log n))", "Presence", "Objects"], answer: 0,
    explain: "ZADD/ZREVRANGE/ZREVRANK." },
  { q: "ZREVRANGE leaderboard 0 9 returns…", options: ["A rank", "Top 10 (descending by score)", "Bottom 10"], answer: 1,
    explain: "ZRANGE is ascending." },
  { q: "SISMEMBER is…", options: ["O(n)", "A sort", "O(1) membership check"], answer: 2,
    explain: "Sets are hash-based." },
  { q: "HINCRBY does…", options: ["Renames", "Atomically increments a hash field", "Deletes a field"], answer: 1,
    explain: "Per-field counters in an object." },
  { q: "Random-access into a List is…", options: ["O(1)", "O(log n)", "O(n) — don't use as an array"], answer: 2,
    explain: "O(1) only at the ends." },
  { q: "HyperLogLog is for…", options: ["Ordering", "Exact counts", "APPROXIMATE unique counts in tiny memory"], answer: 2,
    explain: "PFADD/PFCOUNT for millions of uniques." },
  { q: "Bitmaps are for…", options: ["Queues", "Objects", "Presence/flags over huge id ranges (SETBIT/BITCOUNT)"], answer: 2,
    explain: "One bit per id." },
  { q: "Polling a list queue in a loop…", options: ["Is efficient", "Wastes CPU — use BLPOP (blocking)", "Is required"], answer: 1,
    explain: "Blocking pop waits efficiently." },
  { q: "ZINCRBY does…", options: ["Removes", "Atomically changes a member's score", "Adds a member"], answer: 1,
    explain: "Bump a score on an event." },
  { q: "ZRANK returns…", options: ["A member's rank (position)", "The score", "The count"], answer: 0,
    explain: "ZREVRANK for descending order." },
  { q: "SINTER computes…", options: ["The intersection of sets", "Difference", "Union"], answer: 0,
    explain: "SUNION/SDIFF for union/difference." },
  { q: "A capped 'recent items' list uses…", options: ["LTRIM to bound length", "No limit", "EXPIRE only"], answer: 0,
    explain: "Prevent unbounded growth." },
  { q: "SMEMBERS/HGETALL on huge collections…", options: ["Return big O(n) replies that block — use SSCAN/HSCAN", "Are fine", "Sort"], answer: 0,
    explain: "Bounded reads or scans." },
  { q: "Storing an object as many string keys vs a hash:", options: ["Hash is more memory-efficient + per-field updates", "Same", "Strings are better"], answer: 0,
    explain: "Compact small-hash encoding." },
  { q: "A reliable work queue at scale prefers…", options: ["Pub/Sub", "Lists only", "Streams + consumer groups (acks, replay)"], answer: 2,
    explain: "Lists are simple; Streams add reliability." },
  { q: "Autocomplete/lexicographic ranges use…", options: ["Bitmaps", "Hashes", "Sorted sets (ZRANGEBYLEX)"], answer: 2,
    explain: "Also GEO commands for geospatial." },
  { q: "Choosing a structure means matching it to…", options: ["The ACCESS PATTERN (how you read/write)", "The data size", "The language"], answer: 0,
    explain: "The core Redis design skill." },
]},
{ title: "Quiz 4 · Caching Patterns",
  desc: "Cache-aside, invalidation, stampede/penetration/avalanche",
  questions: [
  { q: "Cache-aside on a write should…", options: ["DELETE the cache key (avoid stale-value race)", "Update the cache value", "Do nothing"], answer: 0,
    explain: "Next read reloads fresh data." },
  { q: "Why delete instead of update the cache?", options: ["Simpler only", "Faster", "Concurrent writes can leave the cache holding an old value"], answer: 2,
    explain: "Delete forces a clean reload." },
  { q: "Cache-aside read flow is…", options: ["Cache only", "Check cache → miss → load DB → set with TTL", "Write DB then cache"], answer: 1,
    explain: "The default web-app pattern." },
  { q: "You should set a TTL even with explicit invalidation because…", options: ["It's faster", "A missed invalidation self-heals within the TTL", "It's required"], answer: 1,
    explain: "The safety net." },
  { q: "A cache stampede is…", options: ["A cold cache", "A hot key expires → many concurrent misses hammer the DB", "A memory leak"], answer: 1,
    explain: "Thundering herd." },
  { q: "Stampede fixes include…", options: ["None", "Rebuild lock (SET NX) / stale-while-revalidate / jittered TTLs", "Bigger cache only"], answer: 1,
    explain: "Collapse N rebuilds into one." },
  { q: "Cache penetration is…", options: ["Stampede", "Cold restart", "Requests for keys that don't exist always miss → hit DB"], answer: 2,
    explain: "Often malicious probing." },
  { q: "Penetration fixes:", options: ["Sharding", "Bigger TTLs", "Cache the null/'not found' + Bloom filter"], answer: 2,
    explain: "Stop repeated misses on absent keys." },
  { q: "Cache avalanche is…", options: ["One hot key", "Penetration", "Cold restart / mass simultaneous expiry → DB overwhelmed"], answer: 2,
    explain: "Correlated misses at once." },
  { q: "Avalanche fixes:", options: ["Nothing", "Bigger keys", "Warming + jittered TTLs + DB rate-limit + HA Redis"], answer: 2,
    explain: "Protect the DB during recovery." },
  { q: "Jittered TTLs prevent…", options: ["Leaks", "Penetration", "Synchronized mass expiry (stampede/avalanche)"], answer: 2,
    explain: "Randomize expiry times." },
  { q: "Write-through caching…", options: ["Loses data", "Is fastest", "Writes cache + DB together (always fresh, double latency)"], answer: 2,
    explain: "vs cache-aside's lazy population." },
  { q: "Write-behind (write-back)…", options: ["Is synchronous", "Writes cache, async-flushes to DB (fast, risk of loss)", "Is safest"], answer: 1,
    explain: "Data loss if cache dies before flush." },
  { q: "The cache is…", options: ["The source of truth", "Permanent", "Disposable — the DB is the source of truth"], answer: 2,
    explain: "Design for eviction/loss." },
  { q: "Distributed invalidation options:", options: ["TTL / explicit DEL / event-driven (pub/sub, CDC)", "Only TTL", "None"], answer: 0,
    explain: "Depends on staleness tolerance." },
  { q: "Cache-aside is popular because it's…", options: ["Always fresh", "Simple and resilient (cache down ≠ app down)", "Complex"], answer: 1,
    explain: "First read is a miss; brief staleness." },
  { q: "A rebuild lock uses…", options: ["PUBLISH", "ZADD", "SET NX so one request rebuilds while others wait"], answer: 2,
    explain: "Stampede mitigation." },
  { q: "Staleness tolerance should be…", options: ["Always zero", "Defined per data type to pick the invalidation strategy", "Ignored"], answer: 1,
    explain: "Drives TTL vs event-driven choice." },
  { q: "Invalidation is famously…", options: ["One of the two hard problems in CS", "Easy", "Automatic"], answer: 0,
    explain: "Naming and cache invalidation." },
  { q: "A cold cache exposed to full traffic causes…", options: ["Avalanche (100% miss → DB overwhelmed)", "Penetration", "Nothing"], answer: 0,
    explain: "Warm before serving." },
]},
{ title: "Quiz 5 · Pub/Sub & Streams",
  desc: "Fire-and-forget vs durable log, consumer groups",
  questions: [
  { q: "Redis Pub/Sub delivers to…", options: ["All future subscribers", "Only subscribers connected AT publish time", "One subscriber"], answer: 1,
    explain: "No storage, no replay." },
  { q: "Pub/Sub message durability is…", options: ["None (at-most-once, fire-and-forget)", "Exactly-once", "At-least-once"], answer: 0,
    explain: "Offline subscribers miss messages forever." },
  { q: "Pub/Sub is good for…", options: ["Event sourcing", "Job queues", "Ephemeral real-time signals (notifications, presence, cache invalidation)"], answer: 2,
    explain: "Where a miss is acceptable." },
  { q: "Streams differ from Pub/Sub by…", options: ["Being faster", "Persisting entries (replayable log)", "Broadcasting"], answer: 1,
    explain: "Read what you missed from your last id." },
  { q: "XADD does…", options: ["Appends an entry to a stream (auto id with *)", "Acks", "Reads"], answer: 0,
    explain: "Append-only log." },
  { q: "A consumer group delivers each message to…", options: ["None", "All consumers", "Exactly ONE consumer in the group (load balance)"], answer: 2,
    explain: "XREADGROUP; ACK when done." },
  { q: "XACK marks a message…", options: ["Processed (acknowledged)", "Deleted", "Pending"], answer: 0,
    explain: "Removes it from the pending list." },
  { q: "XPENDING shows…", options: ["Delivered-but-not-yet-acked messages", "Acked ones", "All messages"], answer: 0,
    explain: "Track in-flight work." },
  { q: "A crashed consumer's messages are recovered via…", options: ["PUBLISH", "XDEL", "XCLAIM/XAUTOCLAIM (reassign to another consumer)"], answer: 2,
    explain: "At-least-once delivery." },
  { q: "Streams delivery semantics are…", options: ["At-most-once", "Exactly-once", "At-least-once (with acks)"], answer: 2,
    explain: "Make handlers idempotent." },
  { q: "Unbounded stream growth is fixed by…", options: ["Ignoring it", "TTL", "XADD ... MAXLEN ~ N (capped stream)"], answer: 2,
    explain: "Bound memory usage." },
  { q: "Using Pub/Sub for critical messages…", options: ["Silently loses them on disconnect — use Streams", "Is fine", "Is durable"], answer: 0,
    explain: "The classic mistake." },
  { q: "XREAD BLOCK 5000 STREAMS events $…", options: ["Waits up to 5s for NEW entries (tail -f)", "Deletes", "Reads history"], answer: 0,
    explain: "$ = only new messages." },
  { q: "Streams are essentially a…", options: ["Redis-native Kafka-lite (durable log)", "Set", "Cache"], answer: 0,
    explain: "For reliable pipelines." },
  { q: "You outgrow Redis Streams for…", options: ["Small jobs", "Very high throughput / long retention (memory-bound) → Kafka", "Any use"], answer: 1,
    explain: "Kafka for the big-data backbone." },
  { q: "PSUBSCRIBE does…", options: ["Pattern-based subscription (news.*)", "Acks", "Persists"], answer: 0,
    explain: "Wildcard channel matching." },
  { q: "A missed Pub/Sub cache-invalidation is…", options: ["Bounded by the TTL (acceptable)", "Catastrophic", "Impossible"], answer: 0,
    explain: "Why Pub/Sub suffices for cache signals." },
  { q: "Streams let a reconnecting consumer…", options: ["Start over only", "Lose messages", "Read from its last id (no loss)"], answer: 2,
    explain: "Ids enable resuming." },
  { q: "Pub/Sub overhead vs Streams:", options: ["Lower/simpler (no storage) — use when loss is OK", "Higher", "Same"], answer: 0,
    explain: "Simplicity vs durability trade." },
  { q: "The decision rule is…", options: ["Always Streams", "Always Pub/Sub", "Loss OK → Pub/Sub; reliable/replayable → Streams"], answer: 2,
    explain: "Match delivery guarantee to need." },
]},
);
