// redis quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Persistence (RDB & AOF)",
  desc: "Snapshots, append-only file, durability trade-offs",
  questions: [
  { q: "RDB persistence is…", options: ["A log of writes", "Real-time", "Periodic point-in-time snapshots"], answer: 2,
    explain: "Compact binary; fast restart/backups." },
  { q: "RDB's downside is…", options: ["Huge files", "Losing everything since the last snapshot on crash", "Slow restart"], answer: 1,
    explain: "Could be minutes of data." },
  { q: "AOF persistence is…", options: ["In-memory only", "A log of every write, replayed on restart", "A snapshot"], answer: 1,
    explain: "More durable; larger file, slower replay." },
  { q: "appendfsync everysec is often described as losing at most 1 second. In reality…", options: ["Redis waits up to 2s for a lagging fsync then proceeds UNSYNCED, so the real window is seconds", "It loses nothing", "It is an exact guarantee"], answer: 0,
    explain: "Measured: 16,652 writes that returned +OK did not survive a SIGKILL. Under disk pressure the window widens further." },
  { q: "The production best practice is…", options: ["Enable BOTH RDB and AOF", "RDB only", "AOF only"], answer: 0,
    explain: "AOF durability + RDB fast backups." },
  { q: "On restart with both, Redis recovers from…", options: ["RDB", "Memory", "The AOF (more complete)"], answer: 2,
    explain: "AOF has the most recent writes." },
  { q: "Enabling AOF and restarting by editing redis.conf (rather than CONFIG SET appendonly yes) risks…", options: ["Nothing, both are equivalent", "Starting EMPTY - with AOF on and no AOF file, Redis ignores an existing RDB", "A slower startup only"], answer: 1,
    explain: "CONFIG SET appendonly yes creates the AOF from memory first. Editing the file and restarting has no AOF to load." },
  { q: "100,000 INCRs on a single key produced a 3.9MB AOF. After BGREWRITEAOF it became…", options: ["133 bytes - the rewrite stores STATE, not the history of commands", "Roughly the same size", "Larger, due to the RDB preamble"], answer: 0,
    explain: "An unrewritten AOF logs every command; the rewrite records only the resulting dataset. Churn-heavy workloads inflate it enormously." },
  { q: "For a pure cache, persistence…", options: ["Barely matters (data reconstructable from DB)", "Must be AOF always", "Is critical"], answer: 0,
    explain: "Match config to loss tolerance." },
  { q: "For a session store, use…", options: ["No persistence", "AOF everysec (≤1s loss)", "RDB only"], answer: 1,
    explain: "Recent writes matter." },
  { q: "Single-node persistence protects against…", options: ["Everything", "That node's restart/crash — not hardware loss", "Hardware loss"], answer: 1,
    explain: "Add replication + backups for real durability." },
  { q: "WAIT 1 100 does…", options: ["Blocks until ≥1 replica has the write (100ms timeout)", "Sleeps", "Snapshots"], answer: 0,
    explain: "Replica-acknowledged durability." },
  { q: "latest_fork_usec reports 184000. That number is…", options: ["An internal statistic with no client impact", "The time to write the RDB file", "The duration every client was stalled - the fork blocks the whole server"], answer: 2,
    explain: "Measured: fork time scaled linearly at ~12ms per GB, and maximum client ping tracked it almost exactly." },
  { q: "Copy-on-write memory overhead during a save is driven mainly by…", options: ["How SCATTERED the writes are - pages touched, not writes performed", "The size of the RDB file", "The number of writes"], answer: 0,
    explain: "Measured: 48,500 writes to 100 keys cost 4.8MB; 44,000 writes across 400,000 keys cost 67MB - 14x for the same volume." },
  { q: "Durability is…", options: ["Layered: fsync + replicas + off-box backups", "Automatic", "A single setting"], answer: 0,
    explain: "No one mechanism covers everything." },
  { q: "Disabling persistence entirely is fine for…", options: ["A pure disposable cache", "Queues", "Sessions"], answer: 0,
    explain: "Data reconstructable from the source of truth." },
  { q: "The core persistence question is…", options: ["How big is RAM?", "Which format?", "How much data can you afford to lose?"], answer: 2,
    explain: "Drives the config choice." },
  { q: "aof-use-rdb-preamble gives…", options: ["No AOF", "A hybrid RDB+AOF format (fast load + durability)", "Slower loads"], answer: 1,
    explain: "Best of both on restart." },
  { q: "Off-box RDB backups protect against…", options: ["Nothing", "Slow reads", "Disaster recovery (whole-node loss)"], answer: 2,
    explain: "Copy snapshots off the machine." },
  { q: "For a Redis-as-source-of-truth critical store…", options: ["AOF always + replication + backups", "RDB only", "No persistence"], answer: 0,
    explain: "Maximum durability layers." },
]},
{ title: "Quiz 7 · Replication & Sentinel",
  desc: "Primary/replica, async lag, failover, quorum",
  questions: [
  { q: "REPLICAOF makes a node…", options: ["A Sentinel", "A primary", "A read-only replica of the primary"], answer: 2,
    explain: "Copies the primary's data." },
  { q: "A primary is killed with writes in flight and a replica is promoted. Measured outcome:", options: ["All writes survive", "Thousands of acknowledged writes simply do not exist - replication is asynchronous", "Redis replays them from the backlog"], answer: 1,
    explain: "Measured: 12,796 keys the primary had acknowledged were absent after promotion, with no error to any client." },
  { q: "How often did a read immediately after a write return stale data from a replica in testing?", options: ["Almost never - lag is sub-millisecond", "Always", "57% of the time - sub-millisecond lag is still enough when the read follows the write directly"], answer: 2,
    explain: "The read-your-own-writes bug. Fix with sticky routing after a write, per-endpoint routing, or WAIT on critical writes." },
  { q: "Sentinel provides…", options: ["Sharding", "Monitoring + automatic failover + primary discovery", "Persistence"], answer: 1,
    explain: "Promotes a replica on primary failure." },
  { q: "Sentinel failover requires…", options: ["No agreement", "One Sentinel", "A QUORUM of Sentinels to agree"], answer: 2,
    explain: "Prevents needless/split failovers." },
  { q: "Run how many Sentinels?", options: ["Odd number (3+) across failure domains", "Even number", "One"], answer: 0,
    explain: "Majority must be reachable." },
  { q: "With 3 Sentinels and quorum 1, can a single Sentinel in a minority partition promote a replica?", options: ["Only if the primary is truly down", "Yes, quorum 1 permits it", "No - detection uses the quorum, but performing a failover always needs a MAJORITY of all Sentinels"], answer: 2,
    explain: "Quorum and majority are two different thresholds. Conflating them is the most common Sentinel misunderstanding." },
  { q: "Clients find the current primary via…", options: ["DNS only", "A fixed IP", "Sentinel-aware discovery"], answer: 2,
    explain: "Don't hardcode the primary address." },
  { q: "During failover, writes…", options: ["Are queued forever", "Never fail", "Fail briefly (retry with backoff)"], answer: 2,
    explain: "Seconds of unavailability." },
  { q: "Unreplicated writes on a failed primary are…", options: ["Lost (async replication)", "Recovered", "Queued"], answer: 0,
    explain: "min-replicas-to-write shrinks the window." },
  { q: "Replicas scale…", options: ["READS (and provide redundancy)", "Storage", "Writes"], answer: 0,
    explain: "Each holds the full dataset." },
  { q: "min-replicas-to-write with min-replicas-max-lag 10 during a partition…", options: ["Eliminates split-brain data loss", "Bounds it - the primary accepted 104 writes before self-protecting, and those were still lost on heal", "Prevents failover entirely"], answer: 1,
    explain: "Measured directly. Redis has no consensus on the data path, so the setting shrinks the divergence window rather than closing it." },
  { q: "The majority principle also appears in…", options: ["MongoDB elections and consensus (Raft)", "Only Redis", "Nowhere else"], answer: 0,
    explain: "Quorum is universal in distributed systems." },
  { q: "A single Redis node is…", options: ["Highly available", "A single point of failure", "Sharded"], answer: 1,
    explain: "Add replicas + Sentinel." },
  { q: "A hit-rate dashboard reads 97% while users report misses. The likely cause is…", options: ["A Redis bug", "It computes hits/(hits+misses) from RAW cumulative counters - the average since boot, not the rate now", "Replica lag"], answer: 1,
    explain: "Measured: a cache with a 0% real hit rate still displayed 66.7% raw. Every INFO stats counter must be graphed as a delta between scrapes." },
  { q: "The default repl-backlog-size of 1MB is dangerous because…", options: ["It wastes memory", "It slows down writes", "A brief blip exhausts it, forcing a FULL resync - fork plus retransfer of the entire dataset"], answer: 2,
    explain: "Measured: 15x slower resync at 1MB versus 256MB for the same disconnect. Alert on sync_partial_err - each one is a full sync." },
  { q: "Spreading Sentinels across failure domains prevents…", options: ["Lag", "Evictions", "Correlated failure (all Sentinels down together)"], answer: 2,
    explain: "Don't co-locate them all." },
  { q: "WAIT complements replication by…", options: ["Requiring a write reach N replicas before proceeding", "Sharding", "Evicting"], answer: 0,
    explain: "For critical-write durability." },
  { q: "The fastest single command for diagnosing why writes are failing is…", options: ["INFO errorstats - it groups every error by reply code (OOM, READONLY, NOSCRIPT, CROSSSLOT)", "SLOWLOG GET", "MONITOR"], answer: 0,
    explain: "OOM climbing while evicted_keys stays at 0 immediately identifies a non-evicting policy. MONITOR cut throughput 54% in testing." },
  { q: "HA needs (minimum)…", options: ["Replicas + automatic failover (Sentinel or Cluster)", "Only persistence", "One node"], answer: 0,
    explain: "Persistence ≠ availability." },
]},
{ title: "Quiz 8 · Distributed Locks",
  desc: "SET NX PX, atomic release, fencing, Redlock",
  questions: [
  { q: "A correct lock acquire is…", options: ["INCR", "SET key val", "SET key uniqueToken NX PX ttl"], answer: 2,
    explain: "Mutual exclusion + auto-expire + owner identity." },
  { q: "The TTL on a lock prevents…", options: ["Fast work", "A crashed holder deadlocking it forever", "Concurrency"], answer: 1,
    explain: "Auto-release on crash." },
  { q: "The unique token is needed to…", options: ["Only release YOUR lock (not someone else's)", "Speed up", "Sort"], answer: 0,
    explain: "Critical for correct release." },
  { q: "A holder overruns its TTL, another client acquires the lock, then the first calls DEL. Measured result:", options: ["It deleted the SECOND holder's lock, so a third client could enter the critical section", "Redis raises an error", "The DEL is ignored"], answer: 0,
    explain: "Shown directly in a timeline. Lua compare-and-delete refused the same release because the token no longer matched." },
  { q: "Correct release uses…", options: ["EXPIRE", "An atomic Lua check-and-delete (delete if token matches)", "GET then DEL"], answer: 1,
    explain: "GET-then-DEL races; Lua is atomic." },
  { q: "Work takes 2s with a 1s lock TTL and no watchdog. How many workers were in the critical section at once?", options: ["0, acquisition fails", "Always exactly 1", "3 - the lock expired every second while the work ran for two"], answer: 2,
    explain: "Measured. A watchdog renewing at 1/3 of the TTL restored exclusion to exactly 1 holder." },
  { q: "For hard correctness, add…", options: ["Fencing tokens + idempotency at the resource", "More Redis", "Longer TTLs"], answer: 0,
    explain: "Locks manage contention; fencing ensures correctness." },
  { q: "Fencing tokens work only when…", options: ["The protected RESOURCE enforces them with a conditional write (WHERE last_token < :t)", "The lock TTL is long enough", "Redis is in Cluster mode"], answer: 0,
    explain: "Measured: a fenced resource rejected the stale writer while an unfenced one let the stale writer win. Sending an email cannot be fenced - make it idempotent." },
  { q: "Redlock across 5 independent primaries costs, measured on loopback…", options: ["About 4.5x the latency, and its validity window went NEGATIVE at 45ms per-node latency", "Less, due to parallelism", "The same as a single-instance lock"], answer: 0,
    explain: "Acquisition is N sequential round trips, and elapsed time is subtracted from the lock validity. Real networks make this worse." },
  { q: "The Redlock debate concludes…", options: ["Never lock", "It's bulletproof", "For correctness use fencing/idempotency (or etcd/ZooKeeper); simple locks for efficiency"], answer: 2,
    explain: "Kleppmann vs antirez." },
  { q: "A single-Redis lock can be lost on…", options: ["Failover (async replication may not have it)", "Reads", "SCAN"], answer: 0,
    explain: "Why Redlock/consensus exists." },
  { q: "Inside MULTI/EXEC, one queued command fails at runtime. The other commands…", options: ["Have ALREADY APPLIED - Redis transactions give isolation, not rollback", "Are never executed", "Are rolled back automatically"], answer: 0,
    explain: "A deliberate design choice: undo logging would slow the common path. Always inspect the EXEC results array, or use Lua to validate first." },
  { q: "TTL vs work-duration mismatch causes…", options: ["Lock expiring mid-work → double execution", "Nothing", "Deadlock"], answer: 0,
    explain: "Keep critical sections short." },
  { q: "Idempotent operations make…", options: ["Locks faster", "Duplicate execution harmless (defense in depth)", "Locks unnecessary"], answer: 1,
    explain: "Pairs with fencing." },
  { q: "A run-once cron across N instances uses…", options: ["A queue", "Pub/Sub", "SET NX PX — whoever wins runs it"], answer: 2,
    explain: "One instance acquires the lock." },
  { q: "A global lock ran at 287 ops/s; per-key locks at 1,690 ops/s; a plain INCR at 8,571 ops/s. The lesson is…", options: ["Global locks are fine at scale", "Locks are always too slow", "Check for a lock-free atomic alternative first - a single Redis command is already atomic"], answer: 2,
    explain: "All three were equally correct. INCR was 30x faster than the global lock because it needs no coordination at all." },
  { q: "When correctness is critical, consider…", options: ["etcd/ZooKeeper (consensus) instead of a timeout lock", "No lock", "Bigger TTLs"], answer: 0,
    explain: "Designed for that guarantee." },
  { q: "A Lua script has already written data and is now blocking the server. SCRIPT KILL…", options: ["Is REFUSED as UNKILLABLE - the only escape is SHUTDOWN NOSAVE, losing data", "Terminates it cleanly", "Pauses it until it can be resumed"], answer: 0,
    explain: "Killing a script mid-write would break atomicity. Bound every script by its arguments: a chunked version had p99 1.4ms vs 84ms unbounded." },
  { q: "The cache stampede rebuild lock is…", options: ["Pub/Sub", "A leaderboard", "SET NX so one request rebuilds (caching lesson)"], answer: 2,
    explain: "Same lock primitive." },
  { q: "The three lock essentials are…", options: ["NX (exclusion) + TTL (auto-release) + unique token (identity)", "Lua only", "Speed, size, TTL"], answer: 0,
    explain: "Missing any is a bug." },
]},
{ title: "Quiz 9 · Cluster, Use Cases & Memory",
  desc: "Hash slots, patterns, eviction, capacity",
  questions: [
  { q: "A cluster client receives ASK instead of MOVED. It must…", options: ["Update its slot map, as with MOVED", "Reconnect to a different node", "Send ASKING then retry on that node ONCE, without updating the slot map - the slot is mid-migration"], answer: 2,
    explain: "During migration a slot's keys are split across two nodes. Treating ASK as MOVED corrupts the slot map and breaks the migration." },
  { q: "Fixed slots exist to…", options: ["Speed hashing", "Save memory", "Decouple keys from node count (move slots, not rehash all)"], answer: 2,
    explain: "Consistent-hashing-like rebalancing." },
  { q: "A multi-key op across different slots…", options: ["Returns CROSSSLOT error", "Is slow", "Works"], answer: 0,
    explain: "Can't coordinate across nodes atomically." },
  { q: "A team hits CROSSSLOT errors and fixes them by tagging every key {global}. The measured result:", options: ["Even distribution across the cluster", "100% of keys on ONE node - the cluster is now a single instance", "Errors persist"], answer: 1,
    explain: "Tag on a high-cardinality identifier. Even 3 region values gave a 33/0/67 split - low-cardinality tags gamble rather than distribute." },
  { q: "Cluster failover is…", options: ["Built-in (per-shard replicas promoted automatically)", "Sentinel-based", "Manual"], answer: 0,
    explain: "No separate Sentinel needed." },
  { q: "You shard with Cluster when…", options: ["Reads are slow", "Always", "Dataset/write volume exceeds one node's RAM"], answer: 2,
    explain: "Exhaust vertical scaling + replicas first." },
  { q: "A rate limiter (fixed window) uses…", options: ["INCR + EXPIRE per user/window", "Pub/Sub", "A sorted set only"], answer: 0,
    explain: "Atomic; sliding window uses a sorted set." },
  { q: "A leaderboard uses…", options: ["A list", "A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)"], answer: 2,
    explain: "The canonical use case." },
  { q: "A session store uses…", options: ["A set", "A list", "SET EX with sliding TTL"], answer: 2,
    explain: "Fast, auto-expiring, shared across instances." },
  { q: "Atomic check-then-act logic uses…", options: ["A Lua script (EVAL) — atomic server-side", "Two commands", "Pub/Sub"], answer: 0,
    explain: "MULTI/EXEC lacks conditional logic." },
  { q: "When Redis hits maxmemory with noeviction…", options: ["Evicts keys", "Crashes", "Rejects writes with an error (reads still work)"], answer: 2,
    explain: "Safe for a data store." },
  { q: "allkeys-lru is right for…", options: ["A session store", "A queue", "A cache (evict cold keys, they reload)"], answer: 2,
    explain: "Eviction policy is a correctness choice." },
  { q: "volatile-lru is configured but some keys are written without a TTL. When memory fills…", options: ["NOTHING is evicted and writes fail with OOM - volatile-* only considers keys that have a TTL", "Those keys are evicted last", "Redis switches policy automatically"], answer: 0,
    explain: "Measured: identical behaviour to noeviction - 0 evictions and hard OOM. Audit expires vs keys in INFO keyspace." },
  { q: "After a batch job scans a large cold keyspace, which policy kept the hot set?", options: ["allkeys-lfu kept 171 of 200 hot keys; LRU kept only 18, because the scan made cold keys look recent", "Both performed identically", "allkeys-lru kept it"], answer: 0,
    explain: "LFU counts frequency, so a single-touch scan cannot displace the hot set. LRU still won on a recency-driven workload." },
  { q: "To reduce memory, prefer…", options: ["Hashes for objects (compact encoding) + TTLs", "Big values", "Many string keys"], answer: 0,
    explain: "Plus HyperLogLog/Bitmaps, short keys." },
  { q: "maxmemory should be set…", options: ["Unset", "Above RAM", "Below physical RAM (hit eviction, not the OS OOM killer)"], answer: 2,
    explain: "OOM kill is catastrophic." },
  { q: "500,000 unique visitors stored as a SET took 36.2MB. As a HyperLogLog it took…", options: ["About 500KB", "About 12KB - roughly 3,000x smaller, at 0.43% error, and the size is FIXED regardless of cardinality", "About 4MB"], answer: 1,
    explain: "The trade is that a HyperLogLog can count but never enumerate. Use a set only when you must list who." },
  { q: "One key takes 99.8% of traffic in a cluster. Adding nodes…", options: ["Spreads the load evenly", "Automatically shards the key", "Changes nothing - one key is one slot on one node; the fix is application-level (L1 cache or splitting the key)"], answer: 2,
    explain: "Measured: an L1 cache cut Redis calls 426x for a read-heavy hot key. Splitting a key only helps when shards land on different nodes." },
  { q: "Capacity planning needs headroom for…", options: ["Only keys", "Replication + RDB fork copy-on-write spike", "Nothing"], answer: 1,
    explain: "Fork can transiently double memory." },
  { q: "A cluster needs how many primaries for majority?", options: ["2", "≥3 (across failure domains)", "1"], answer: 1,
    explain: "Majority for failover decisions." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "A KEYS * command caused a latency spike for all clients. Cause?", options: ["Network", "Eviction", "It's O(n) and blocks the single thread — use SCAN"], answer: 2,
    explain: "Never KEYS in production." },
  { q: "App-side counter loses increments under load. Fix?", options: ["A lock", "Use INCR (atomic, no lost updates)", "A queue"], answer: 1,
    explain: "Redis is single-threaded/atomic." },
  { q: "A hot cache key expired and the DB got hammered. Name + fix?", options: ["Penetration; Bloom filter", "Stampede; rebuild lock / SWR / jittered TTLs", "Avalanche; warming"], answer: 1,
    explain: "Collapse concurrent rebuilds." },
  { q: "Requests for random non-existent ids keep hitting the DB. Name + fix?", options: ["Penetration; cache negatives / Bloom filter", "Avalanche", "Stampede; lock"], answer: 0,
    explain: "Absent-key misses." },
  { q: "A Redis restart caused a DB flood. Name + fix?", options: ["Penetration", "Stampede", "Avalanche; warm cache + jitter + DB rate-limit + HA"], answer: 2,
    explain: "Cold cache, 100% miss." },
  { q: "Critical messages vanish when a subscriber reconnects. Cause?", options: ["Streams", "Cluster", "Pub/Sub is fire-and-forget — use Streams"], answer: 2,
    explain: "No persistence/replay in Pub/Sub." },
  { q: "Your distributed lock let two jobs run at once. Likely cause?", options: ["Released with bare DEL (deleted another owner's lock)", "TTL too long", "NX missing"], answer: 0,
    explain: "Use atomic Lua token check." },
  { q: "Redis was OOM-killed by the OS. Fix?", options: ["More TTLs only", "Set maxmemory below RAM + an eviction policy", "Add replicas"], answer: 1,
    explain: "Hit eviction, not the OOM killer." },
  { q: "Sessions vanished under memory pressure. Cause?", options: ["allkeys eviction deleted non-reconstructable data — use noeviction/volatile-*", "Cluster", "Persistence off"], answer: 0,
    explain: "Eviction policy is a correctness choice." },
  { q: "MGET user:1 user:2 fails in the cluster. Cause + fix?", options: ["Add nodes", "Bad client", "CROSSSLOT — co-locate with hash tags {user:1}"], answer: 2,
    explain: "Multi-key needs the same slot." },
  { q: "After a primary crash, a few writes were lost. Why?", options: ["Eviction", "Bug", "Async replication — unreplicated writes lost (min-replicas-to-write)"], answer: 2,
    explain: "Failover trade-off." },
  { q: "Reading from a replica returned stale data. Fix?", options: ["More replicas", "Sharding", "Read from the primary for read-your-writes"], answer: 2,
    explain: "Replication lag." },
  { q: "Writes returned +OK but vanished after a crash with AOF enabled. The reason is…", options: ["appendfsync everysec acknowledges before fsync - Redis acks before durability, by design", "The RDB overwrote the AOF", "AOF was corrupted"], answer: 0,
    explain: "Measured: 16,652 acknowledged writes lost to a SIGKILL. appendfsync always costs ~10x throughput and still cannot survive machine loss." },
  { q: "You need a leaderboard for 10M players. Structure?", options: ["A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)", "A list"], answer: 1,
    explain: "O(log n) ranking." },
  { q: "A fixed-window rate limiter admitted 20 requests against a limit of 10 per 2s. The fix is…", options: ["Shorten the window", "A sliding window counter or token bucket - fixed window permits 2x across a boundary anyone can compute", "Raise the limit"], answer: 1,
    explain: "Measured directly. The sliding window counter uses two counters and came within 5% of exact; the sliding log is exact but ~760x the memory." },
  { q: "A multi-step recipe raced between commands. Fix?", options: ["Pub/Sub", "A Lua script (atomic) or MULTI/EXEC+WATCH", "Two round trips"], answer: 1,
    explain: "Single-threaded Lua = atomic." },
  { q: "Memory grows despite MAXLEN trimming and TTLs. Check FIRST…", options: ["The Streams PEL and TTL coverage (expires vs keys) - MAXLEN bounds the stream, not the pending list", "Client output buffers", "Fragmentation"], answer: 0,
    explain: "Unacknowledged entries leak invisibly to XLEN, and volatile-* with TTL-less keys evicts nothing. Both look healthy on a dashboard." },
  { q: "You need durable, replayable, load-balanced job processing. Use?", options: ["A list only", "Streams + consumer groups (or Kafka at huge scale)", "Pub/Sub"], answer: 1,
    explain: "At-least-once with acks." },
  { q: "One Sentinel triggered a needless failover. Fix?", options: ["Fewer Sentinels", "Require a quorum (odd number, 3+)", "Disable Sentinel"], answer: 1,
    explain: "Majority must agree." },
  { q: "The question that should drive every Redis design decision is…", options: ["How fast is it?", "How much RAM do we have?", "What happens if this data disappears? - repopulates = cache; users re-login = sessions; orders lost = wrong architecture"], answer: 2,
    explain: "Measured: an orders-in-Redis design lost 3,116 of 50,000 acknowledged writes at failover. Database as truth, Redis derived, costs 0." },
]},
);
