// Redis quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Introduction & Data Model",
  desc: "In-memory, single-threaded, data structures, vs Memcached",
  questions: [
  { q: "Redis is fast primarily because it…", options: ["Uses many threads", "Keeps data in RAM (in-memory)", "Compresses everything"], answer: 1,
    explain: "RAM access is orders of magnitude faster than disk." },
  { q: "Redis executes commands…", options: ["In parallel", "Single-threaded, one at a time (atomic, no locks)", "With row locks"], answer: 1,
    explain: "Serial execution makes each command atomic." },
  { q: "A slow O(n) command in Redis…", options: ["Runs in background", "Blocks ALL clients (single-threaded)", "Is parallelized"], answer: 1,
    explain: "Avoid KEYS * on large keyspaces; use SCAN." },
  { q: "The Redis data model is…", options: ["Tables", "String keys → typed values (String/Hash/List/Set/ZSet)", "Documents"], answer: 1,
    explain: "The value's type determines available commands." },
  { q: "Redis is best described as…", options: ["Only a cache", "An in-memory data-structure store (cache + much more)", "A relational DB"], answer: 1,
    explain: "Rate limiting, leaderboards, queues, pub/sub, locks." },
  { q: "Redis is bound by…", options: ["Disk size", "RAM (the whole dataset lives in memory)", "CPU cores"], answer: 1,
    explain: "Shard with Cluster when it exceeds one node's RAM." },
  { q: "INCR is atomic without a lock because…", options: ["It's slow", "Single-threaded execution serializes commands", "It uses transactions"], answer: 1,
    explain: "No interleaving between commands." },
  { q: "Key naming convention uses…", options: ["Random ids", "namespace:id:field (colon-separated)", "No structure"], answer: 1,
    explain: "e.g., user:1000:profile; enables SCAN patterns." },
  { q: "Redis typically…", options: ["Replaces the primary DB", "Complements a primary DB (fast layer in front)", "Stores files"], answer: 1,
    explain: "Usually not the sole system of record." },
  { q: "Redis vs Memcached — Redis adds…", options: ["Nothing", "Data structures, persistence, replication, pub/sub, scripting", "Only threads"], answer: 1,
    explain: "The default modern choice." },
  { q: "Memcached's advantage is…", options: ["Data structures", "Simplicity + multi-threaded pure string cache", "Persistence"], answer: 1,
    explain: "Fine for a simple huge string cache." },
  { q: "SCAN is preferred over KEYS because…", options: ["It's exact", "It's cursor-based and non-blocking", "It sorts"], answer: 1,
    explain: "KEYS blocks the single thread." },
  { q: "A sorted set is used for…", options: ["Objects", "Leaderboards/ranking (scored + ordered)", "Queues"], answer: 1,
    explain: "The most interview-relevant structure." },
  { q: "Single-threaded is a…", options: ["Limitation only", "Deliberate design (atomicity, no lock overhead)", "Bug"], answer: 1,
    explain: "100k+ ops/sec per core; scale via instances." },
  { q: "Redis modern versions use threads for…", options: ["Command execution", "I/O and background tasks (execution stays serial)", "Nothing"], answer: 1,
    explain: "The hot command path is single-threaded." },
  { q: "Storing data larger than RAM…", options: ["Works via disk", "Causes evictions/OOM — RAM is the limit", "Is automatic"], answer: 1,
    explain: "Cap memory + eviction policy; shard if needed." },
  { q: "A List in Redis is…", options: ["Sorted", "An ordered collection (push/pop both ends)", "Unique-only"], answer: 1,
    explain: "Queues/stacks; O(1) at ends." },
  { q: "A Hash stores…", options: ["Ranked members", "Field→value maps (objects)", "Unique members"], answer: 1,
    explain: "Efficient for records/objects." },
  { q: "The 'don't block the thread' rule mirrors…", options: ["SQL indexes", "Node's event loop discipline", "Sharding"], answer: 1,
    explain: "One slow op stalls everyone." },
  { q: "Choosing the right data structure is…", options: ["Optional", "The core Redis skill (match structure to access pattern)", "Automatic"], answer: 1,
    explain: "Like MongoDB schema design." }
]},

{ title: "Quiz 2 · Strings, Keys & TTL",
  desc: "String commands, atomic counters, expiration, SCAN",
  questions: [
  { q: "INCR does…", options: ["Insert", "Atomically increment and return the new value", "Index"], answer: 1,
    explain: "Race-safe counters without app locks." },
  { q: "App-side read-modify-write counting…", options: ["Is atomic", "Races (lost updates) — use INCR", "Is faster"], answer: 1,
    explain: "Two clients both read+write the same value." },
  { q: "SET key val EX 300…", options: ["Two commands", "Sets value + TTL atomically", "No TTL"], answer: 1,
    explain: "Preferred over SET then EXPIRE (crash-safe)." },
  { q: "TTL makes Redis a good…", options: ["Primary DB", "CACHE (keys auto-expire, bounding memory/staleness)", "Queue"], answer: 1,
    explain: "Sessions, cached queries, rate windows." },
  { q: "SET key val NX…", options: ["Always sets", "Sets only if the key does NOT exist", "Sets only if exists"], answer: 1,
    explain: "XX = only if exists; used for locks/run-once." },
  { q: "Key expiration works via…", options: ["Full scans", "Lazy (on access) + active (periodic sampling)", "Immediate deletion"], answer: 1,
    explain: "Bounds memory without scanning all keys." },
  { q: "TTL key returns -1 when…", options: ["Key is gone", "The key has no expiry", "TTL expired"], answer: 1,
    explain: "-2 = key doesn't exist." },
  { q: "SET then EXPIRE (two commands) risks…", options: ["Nothing", "A crash between them → TTL-less key (leak)", "Slower reads"], answer: 1,
    explain: "Use atomic SET EX." },
  { q: "KEYS pattern in production…", options: ["Is fine", "Blocks the single thread — latency for all", "Is fastest"], answer: 1,
    explain: "Use SCAN (cursor)." },
  { q: "UNLINK vs DEL…", options: ["Same", "UNLINK frees memory asynchronously (better for big keys)", "UNLINK is slower"], answer: 1,
    explain: "Non-blocking deletion." },
  { q: "MSET/MGET…", options: ["Are invalid", "Batch multiple keys in one round trip", "Sort keys"], answer: 1,
    explain: "Reduce network round trips." },
  { q: "INCRBYFLOAT…", options: ["Errors on strings", "Atomically adds a float to a numeric string", "Rounds"], answer: 1,
    explain: "For counters/prices (mind float precision)." },
  { q: "PERSIST key…", options: ["Deletes", "Removes the TTL (makes it permanent)", "Sets a TTL"], answer: 1,
    explain: "Opposite of EXPIRE." },
  { q: "Expired-but-not-removed keys…", options: ["Free memory instantly", "Still count toward memory until removed", "Never happen"], answer: 1,
    explain: "Lazy+active expiration; usually negligible." },
  { q: "GETSET does…", options: ["Only get", "Set new value and return the old (atomic swap)", "Only set"], answer: 1,
    explain: "One-shot swap." },
  { q: "The atomic-counter pattern underlies…", options: ["Nothing", "Rate limiters, view counters, unique IDs", "Sorting"], answer: 1,
    explain: "INCR + EXPIRE (use-cases lesson)." },
  { q: "SCAN returns…", options: ["All keys at once", "A cursor + a batch (loop until cursor 0)", "Sorted keys"], answer: 1,
    explain: "Non-blocking iteration." },
  { q: "Huge single string values…", options: ["Are ideal", "Cause big-value latency/memory — split or use hashes", "Compress automatically"], answer: 1,
    explain: "Keep values modest." },
  { q: "Cache keys should…", options: ["Never expire", "Always have a TTL (bound memory)", "Be permanent"], answer: 1,
    explain: "Even with explicit invalidation." },
  { q: "SET NX is the basis of…", options: ["Sorting", "A simple lock / run-once (locks lesson)", "Pub/Sub"], answer: 1,
    explain: "Only one client 'wins' the SET." }
]},

{ title: "Quiz 3 · Data Structures",
  desc: "Hashes, Lists, Sets, Sorted Sets, choosing structures",
  questions: [
  { q: "A Hash is best for…", options: ["Rankings", "Objects (field→value)", "Queues"], answer: 1,
    explain: "Store a user/product under one key with fields." },
  { q: "A List with BLPOP implements…", options: ["A leaderboard", "A blocking queue (producer/consumer)", "A cache"], answer: 1,
    explain: "Wait for the next job without polling." },
  { q: "A Set provides…", options: ["Ordering", "Unique membership + set algebra (SINTER/SUNION/SDIFF)", "Scores"], answer: 1,
    explain: "'Followers of both A and B' = one SINTER." },
  { q: "A Sorted Set is THE structure for…", options: ["Objects", "Leaderboards/ranking (scored, O(log n))", "Presence"], answer: 1,
    explain: "ZADD/ZREVRANGE/ZREVRANK." },
  { q: "ZREVRANGE leaderboard 0 9 returns…", options: ["Bottom 10", "Top 10 (descending by score)", "A rank"], answer: 1,
    explain: "ZRANGE is ascending." },
  { q: "SISMEMBER is…", options: ["O(n)", "O(1) membership check", "A sort"], answer: 1,
    explain: "Sets are hash-based." },
  { q: "HINCRBY does…", options: ["Deletes a field", "Atomically increments a hash field", "Renames"], answer: 1,
    explain: "Per-field counters in an object." },
  { q: "Random-access into a List is…", options: ["O(1)", "O(n) — don't use as an array", "O(log n)"], answer: 1,
    explain: "O(1) only at the ends." },
  { q: "HyperLogLog is for…", options: ["Exact counts", "APPROXIMATE unique counts in tiny memory", "Ordering"], answer: 1,
    explain: "PFADD/PFCOUNT for millions of uniques." },
  { q: "Bitmaps are for…", options: ["Objects", "Presence/flags over huge id ranges (SETBIT/BITCOUNT)", "Queues"], answer: 1,
    explain: "One bit per id." },
  { q: "Polling a list queue in a loop…", options: ["Is efficient", "Wastes CPU — use BLPOP (blocking)", "Is required"], answer: 1,
    explain: "Blocking pop waits efficiently." },
  { q: "ZINCRBY does…", options: ["Adds a member", "Atomically changes a member's score", "Removes"], answer: 1,
    explain: "Bump a score on an event." },
  { q: "ZRANK returns…", options: ["The score", "A member's rank (position)", "The count"], answer: 1,
    explain: "ZREVRANK for descending order." },
  { q: "SINTER computes…", options: ["Union", "The intersection of sets", "Difference"], answer: 1,
    explain: "SUNION/SDIFF for union/difference." },
  { q: "A capped 'recent items' list uses…", options: ["No limit", "LTRIM to bound length", "EXPIRE only"], answer: 1,
    explain: "Prevent unbounded growth." },
  { q: "SMEMBERS/HGETALL on huge collections…", options: ["Are fine", "Return big O(n) replies that block — use SSCAN/HSCAN", "Sort"], answer: 1,
    explain: "Bounded reads or scans." },
  { q: "Storing an object as many string keys vs a hash:", options: ["Same", "Hash is more memory-efficient + per-field updates", "Strings are better"], answer: 1,
    explain: "Compact small-hash encoding." },
  { q: "A reliable work queue at scale prefers…", options: ["Lists only", "Streams + consumer groups (acks, replay)", "Pub/Sub"], answer: 1,
    explain: "Lists are simple; Streams add reliability." },
  { q: "Autocomplete/lexicographic ranges use…", options: ["Hashes", "Sorted sets (ZRANGEBYLEX)", "Bitmaps"], answer: 1,
    explain: "Also GEO commands for geospatial." },
  { q: "Choosing a structure means matching it to…", options: ["The data size", "The ACCESS PATTERN (how you read/write)", "The language"], answer: 1,
    explain: "The core Redis design skill." }
]},

{ title: "Quiz 4 · Caching Patterns",
  desc: "Cache-aside, invalidation, stampede/penetration/avalanche",
  questions: [
  { q: "Cache-aside on a write should…", options: ["Update the cache value", "DELETE the cache key (avoid stale-value race)", "Do nothing"], answer: 1,
    explain: "Next read reloads fresh data." },
  { q: "Why delete instead of update the cache?", options: ["Faster", "Concurrent writes can leave the cache holding an old value", "Simpler only"], answer: 1,
    explain: "Delete forces a clean reload." },
  { q: "Cache-aside read flow is…", options: ["Write DB then cache", "Check cache → miss → load DB → set with TTL", "Cache only"], answer: 1,
    explain: "The default web-app pattern." },
  { q: "You should set a TTL even with explicit invalidation because…", options: ["It's required", "A missed invalidation self-heals within the TTL", "It's faster"], answer: 1,
    explain: "The safety net." },
  { q: "A cache stampede is…", options: ["A cold cache", "A hot key expires → many concurrent misses hammer the DB", "A memory leak"], answer: 1,
    explain: "Thundering herd." },
  { q: "Stampede fixes include…", options: ["Bigger cache only", "Rebuild lock (SET NX) / stale-while-revalidate / jittered TTLs", "None"], answer: 1,
    explain: "Collapse N rebuilds into one." },
  { q: "Cache penetration is…", options: ["Cold restart", "Requests for keys that don't exist always miss → hit DB", "Stampede"], answer: 1,
    explain: "Often malicious probing." },
  { q: "Penetration fixes:", options: ["Bigger TTLs", "Cache the null/'not found' + Bloom filter", "Sharding"], answer: 1,
    explain: "Stop repeated misses on absent keys." },
  { q: "Cache avalanche is…", options: ["One hot key", "Cold restart / mass simultaneous expiry → DB overwhelmed", "Penetration"], answer: 1,
    explain: "Correlated misses at once." },
  { q: "Avalanche fixes:", options: ["Nothing", "Warming + jittered TTLs + DB rate-limit + HA Redis", "Bigger keys"], answer: 1,
    explain: "Protect the DB during recovery." },
  { q: "Jittered TTLs prevent…", options: ["Penetration", "Synchronized mass expiry (stampede/avalanche)", "Leaks"], answer: 1,
    explain: "Randomize expiry times." },
  { q: "Write-through caching…", options: ["Is fastest", "Writes cache + DB together (always fresh, double latency)", "Loses data"], answer: 1,
    explain: "vs cache-aside's lazy population." },
  { q: "Write-behind (write-back)…", options: ["Is safest", "Writes cache, async-flushes to DB (fast, risk of loss)", "Is synchronous"], answer: 1,
    explain: "Data loss if cache dies before flush." },
  { q: "The cache is…", options: ["The source of truth", "Disposable — the DB is the source of truth", "Permanent"], answer: 1,
    explain: "Design for eviction/loss." },
  { q: "Distributed invalidation options:", options: ["Only TTL", "TTL / explicit DEL / event-driven (pub/sub, CDC)", "None"], answer: 1,
    explain: "Depends on staleness tolerance." },
  { q: "Cache-aside is popular because it's…", options: ["Complex", "Simple and resilient (cache down ≠ app down)", "Always fresh"], answer: 1,
    explain: "First read is a miss; brief staleness." },
  { q: "A rebuild lock uses…", options: ["ZADD", "SET NX so one request rebuilds while others wait", "PUBLISH"], answer: 1,
    explain: "Stampede mitigation." },
  { q: "Staleness tolerance should be…", options: ["Ignored", "Defined per data type to pick the invalidation strategy", "Always zero"], answer: 1,
    explain: "Drives TTL vs event-driven choice." },
  { q: "Invalidation is famously…", options: ["Easy", "One of the two hard problems in CS", "Automatic"], answer: 1,
    explain: "Naming and cache invalidation." },
  { q: "A cold cache exposed to full traffic causes…", options: ["Nothing", "Avalanche (100% miss → DB overwhelmed)", "Penetration"], answer: 1,
    explain: "Warm before serving." }
]},

{ title: "Quiz 5 · Pub/Sub & Streams",
  desc: "Fire-and-forget vs durable log, consumer groups",
  questions: [
  { q: "Redis Pub/Sub delivers to…", options: ["All future subscribers", "Only subscribers connected AT publish time", "One subscriber"], answer: 1,
    explain: "No storage, no replay." },
  { q: "Pub/Sub message durability is…", options: ["At-least-once", "None (at-most-once, fire-and-forget)", "Exactly-once"], answer: 1,
    explain: "Offline subscribers miss messages forever." },
  { q: "Pub/Sub is good for…", options: ["Job queues", "Ephemeral real-time signals (notifications, presence, cache invalidation)", "Event sourcing"], answer: 1,
    explain: "Where a miss is acceptable." },
  { q: "Streams differ from Pub/Sub by…", options: ["Being faster", "Persisting entries (replayable log)", "Broadcasting"], answer: 1,
    explain: "Read what you missed from your last id." },
  { q: "XADD does…", options: ["Reads", "Appends an entry to a stream (auto id with *)", "Acks"], answer: 1,
    explain: "Append-only log." },
  { q: "A consumer group delivers each message to…", options: ["All consumers", "Exactly ONE consumer in the group (load balance)", "None"], answer: 1,
    explain: "XREADGROUP; ACK when done." },
  { q: "XACK marks a message…", options: ["Deleted", "Processed (acknowledged)", "Pending"], answer: 1,
    explain: "Removes it from the pending list." },
  { q: "XPENDING shows…", options: ["All messages", "Delivered-but-not-yet-acked messages", "Acked ones"], answer: 1,
    explain: "Track in-flight work." },
  { q: "A crashed consumer's messages are recovered via…", options: ["XDEL", "XCLAIM/XAUTOCLAIM (reassign to another consumer)", "PUBLISH"], answer: 1,
    explain: "At-least-once delivery." },
  { q: "Streams delivery semantics are…", options: ["At-most-once", "At-least-once (with acks)", "Exactly-once"], answer: 1,
    explain: "Make handlers idempotent." },
  { q: "Unbounded stream growth is fixed by…", options: ["Ignoring it", "XADD ... MAXLEN ~ N (capped stream)", "TTL"], answer: 1,
    explain: "Bound memory usage." },
  { q: "Using Pub/Sub for critical messages…", options: ["Is fine", "Silently loses them on disconnect — use Streams", "Is durable"], answer: 1,
    explain: "The classic mistake." },
  { q: "XREAD BLOCK 5000 STREAMS events $…", options: ["Reads history", "Waits up to 5s for NEW entries (tail -f)", "Deletes"], answer: 1,
    explain: "$ = only new messages." },
  { q: "Streams are essentially a…", options: ["Cache", "Redis-native Kafka-lite (durable log)", "Set"], answer: 1,
    explain: "For reliable pipelines." },
  { q: "You outgrow Redis Streams for…", options: ["Any use", "Very high throughput / long retention (memory-bound) → Kafka", "Small jobs"], answer: 1,
    explain: "Kafka for the big-data backbone." },
  { q: "PSUBSCRIBE does…", options: ["Persists", "Pattern-based subscription (news.*)", "Acks"], answer: 1,
    explain: "Wildcard channel matching." },
  { q: "A missed Pub/Sub cache-invalidation is…", options: ["Catastrophic", "Bounded by the TTL (acceptable)", "Impossible"], answer: 1,
    explain: "Why Pub/Sub suffices for cache signals." },
  { q: "Streams let a reconnecting consumer…", options: ["Lose messages", "Read from its last id (no loss)", "Start over only"], answer: 1,
    explain: "Ids enable resuming." },
  { q: "Pub/Sub overhead vs Streams:", options: ["Higher", "Lower/simpler (no storage) — use when loss is OK", "Same"], answer: 1,
    explain: "Simplicity vs durability trade." },
  { q: "The decision rule is…", options: ["Always Streams", "Loss OK → Pub/Sub; reliable/replayable → Streams", "Always Pub/Sub"], answer: 1,
    explain: "Match delivery guarantee to need." }
]}
);
