// Redis quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Persistence (RDB & AOF)",
  desc: "Snapshots, append-only file, durability trade-offs",
  questions: [
  { q: "RDB persistence is…", options: ["A log of writes", "Periodic point-in-time snapshots", "Real-time"], answer: 1,
    explain: "Compact binary; fast restart/backups." },
  { q: "RDB's downside is…", options: ["Slow restart", "Losing everything since the last snapshot on crash", "Huge files"], answer: 1,
    explain: "Could be minutes of data." },
  { q: "AOF persistence is…", options: ["A snapshot", "A log of every write, replayed on restart", "In-memory only"], answer: 1,
    explain: "More durable; larger file, slower replay." },
  { q: "appendfsync everysec means…", options: ["Zero loss", "Lose ≤1s of data (the common balance)", "No durability"], answer: 1,
    explain: "always = ~0 loss (slow); no = OS-decided." },
  { q: "The production best practice is…", options: ["RDB only", "Enable BOTH RDB and AOF", "AOF only"], answer: 1,
    explain: "AOF durability + RDB fast backups." },
  { q: "On restart with both, Redis recovers from…", options: ["RDB", "The AOF (more complete)", "Memory"], answer: 1,
    explain: "AOF has the most recent writes." },
  { q: "appendfsync always trades…", options: ["Nothing", "Latency for ~zero data loss", "Durability for speed"], answer: 1,
    explain: "fsync every write is slow." },
  { q: "AOF file growth is handled by…", options: ["Manual deletion", "Periodic rewrite (BGREWRITEAOF) to compact form", "TTL"], answer: 1,
    explain: "Keeps the file bounded." },
  { q: "For a pure cache, persistence…", options: ["Is critical", "Barely matters (data reconstructable from DB)", "Must be AOF always"], answer: 1,
    explain: "Match config to loss tolerance." },
  { q: "For a session store, use…", options: ["No persistence", "AOF everysec (≤1s loss)", "RDB only"], answer: 1,
    explain: "Recent writes matter." },
  { q: "Single-node persistence protects against…", options: ["Hardware loss", "That node's restart/crash — not hardware loss", "Everything"], answer: 1,
    explain: "Add replication + backups for real durability." },
  { q: "WAIT 1 100 does…", options: ["Sleeps", "Blocks until ≥1 replica has the write (100ms timeout)", "Snapshots"], answer: 1,
    explain: "Replica-acknowledged durability." },
  { q: "RDB uses a fork that can…", options: ["Halve memory", "Transiently spike memory (copy-on-write)", "Never use memory"], answer: 1,
    explain: "Headroom needed on write-heavy nodes." },
  { q: "BGSAVE triggers…", options: ["A blocking save", "A background snapshot", "AOF rewrite"], answer: 1,
    explain: "Non-blocking RDB snapshot." },
  { q: "Durability is…", options: ["A single setting", "Layered: fsync + replicas + off-box backups", "Automatic"], answer: 1,
    explain: "No one mechanism covers everything." },
  { q: "Disabling persistence entirely is fine for…", options: ["Sessions", "A pure disposable cache", "Queues"], answer: 1,
    explain: "Data reconstructable from the source of truth." },
  { q: "The core persistence question is…", options: ["Which format?", "How much data can you afford to lose?", "How big is RAM?"], answer: 1,
    explain: "Drives the config choice." },
  { q: "aof-use-rdb-preamble gives…", options: ["Slower loads", "A hybrid RDB+AOF format (fast load + durability)", "No AOF"], answer: 1,
    explain: "Best of both on restart." },
  { q: "Off-box RDB backups protect against…", options: ["Nothing", "Disaster recovery (whole-node loss)", "Slow reads"], answer: 1,
    explain: "Copy snapshots off the machine." },
  { q: "For a Redis-as-source-of-truth critical store…", options: ["RDB only", "AOF always + replication + backups", "No persistence"], answer: 1,
    explain: "Maximum durability layers." }
]},

{ title: "Quiz 7 · Replication & Sentinel",
  desc: "Primary/replica, async lag, failover, quorum",
  questions: [
  { q: "REPLICAOF makes a node…", options: ["A primary", "A read-only replica of the primary", "A Sentinel"], answer: 1,
    explain: "Copies the primary's data." },
  { q: "Replication is…", options: ["Synchronous", "Asynchronous (replicas can lag)", "Two-phase"], answer: 1,
    explain: "Primary acks before replicas have it." },
  { q: "Reading from a replica can return…", options: ["Fresh data always", "Stale data (lag) — read primary for freshness", "Errors"], answer: 1,
    explain: "Read-your-writes needs the primary." },
  { q: "Sentinel provides…", options: ["Sharding", "Monitoring + automatic failover + primary discovery", "Persistence"], answer: 1,
    explain: "Promotes a replica on primary failure." },
  { q: "Sentinel failover requires…", options: ["One Sentinel", "A QUORUM of Sentinels to agree", "No agreement"], answer: 1,
    explain: "Prevents needless/split failovers." },
  { q: "Run how many Sentinels?", options: ["Even number", "Odd number (3+) across failure domains", "One"], answer: 1,
    explain: "Majority must be reachable." },
  { q: "Quorum prevents…", options: ["Lag", "Split-brain (two primaries) during partitions", "Evictions"], answer: 1,
    explain: "Only the majority side promotes." },
  { q: "Clients find the current primary via…", options: ["A fixed IP", "Sentinel-aware discovery", "DNS only"], answer: 1,
    explain: "Don't hardcode the primary address." },
  { q: "During failover, writes…", options: ["Never fail", "Fail briefly (retry with backoff)", "Are queued forever"], answer: 1,
    explain: "Seconds of unavailability." },
  { q: "Unreplicated writes on a failed primary are…", options: ["Recovered", "Lost (async replication)", "Queued"], answer: 1,
    explain: "min-replicas-to-write shrinks the window." },
  { q: "Replicas scale…", options: ["Writes", "READS (and provide redundancy)", "Storage"], answer: 1,
    explain: "Each holds the full dataset." },
  { q: "min-replicas-to-write…", options: ["Speeds writes", "Refuses writes unless N replicas are current (less loss)", "Adds Sentinels"], answer: 1,
    explain: "Durability vs availability trade." },
  { q: "The majority principle also appears in…", options: ["Only Redis", "MongoDB elections and consensus (Raft)", "Nowhere else"], answer: 1,
    explain: "Quorum is universal in distributed systems." },
  { q: "A single Redis node is…", options: ["Highly available", "A single point of failure", "Sharded"], answer: 1,
    explain: "Add replicas + Sentinel." },
  { q: "Managed Redis (ElastiCache) handles…", options: ["Nothing", "Sentinel/failover for you", "Only caching"], answer: 1,
    explain: "Common production choice." },
  { q: "A replica's initial sync uses…", options: ["AOF only", "A full RDB sync, then command streaming", "Nothing"], answer: 1,
    explain: "Then stays current via the stream." },
  { q: "Spreading Sentinels across failure domains prevents…", options: ["Lag", "Correlated failure (all Sentinels down together)", "Evictions"], answer: 1,
    explain: "Don't co-locate them all." },
  { q: "WAIT complements replication by…", options: ["Sharding", "Requiring a write reach N replicas before proceeding", "Evicting"], answer: 1,
    explain: "For critical-write durability." },
  { q: "Redis Cluster's failover is…", options: ["Sentinel-based", "Built-in (per-shard replicas, no separate Sentinel)", "Manual"], answer: 1,
    explain: "Cluster has its own failover." },
  { q: "HA needs (minimum)…", options: ["One node", "Replicas + automatic failover (Sentinel or Cluster)", "Only persistence"], answer: 1,
    explain: "Persistence ≠ availability." }
]},

{ title: "Quiz 8 · Distributed Locks",
  desc: "SET NX PX, atomic release, fencing, Redlock",
  questions: [
  { q: "A correct lock acquire is…", options: ["SET key val", "SET key uniqueToken NX PX ttl", "INCR"], answer: 1,
    explain: "Mutual exclusion + auto-expire + owner identity." },
  { q: "The TTL on a lock prevents…", options: ["Fast work", "A crashed holder deadlocking it forever", "Concurrency"], answer: 1,
    explain: "Auto-release on crash." },
  { q: "The unique token is needed to…", options: ["Speed up", "Only release YOUR lock (not someone else's)", "Sort"], answer: 1,
    explain: "Critical for correct release." },
  { q: "Releasing with a bare DEL is dangerous because…", options: ["It's slow", "Your expired lock may be re-acquired → you delete another owner's", "It errors"], answer: 1,
    explain: "Two processes then run concurrently." },
  { q: "Correct release uses…", options: ["GET then DEL", "An atomic Lua check-and-delete (delete if token matches)", "EXPIRE"], answer: 1,
    explain: "GET-then-DEL races; Lua is atomic." },
  { q: "If a holder stalls past the TTL…", options: ["Nothing happens", "The lock expires → another process acquires it (double execution)", "It renews"], answer: 1,
    explain: "No timeout-lock fully prevents this." },
  { q: "For hard correctness, add…", options: ["Longer TTLs", "Fencing tokens + idempotency at the resource", "More Redis"], answer: 1,
    explain: "Locks manage contention; fencing ensures correctness." },
  { q: "A fencing token is…", options: ["Random", "A monotonically increasing number the resource checks (rejects stale)", "A TTL"], answer: 1,
    explain: "Refuses a delayed old holder's writes." },
  { q: "Redlock acquires a lock across…", options: ["One node", "Multiple independent Redis primaries (majority)", "Replicas"], answer: 1,
    explain: "Survives single-node failover." },
  { q: "The Redlock debate concludes…", options: ["It's bulletproof", "For correctness use fencing/idempotency (or etcd/ZooKeeper); simple locks for efficiency", "Never lock"], answer: 1,
    explain: "Kleppmann vs antirez." },
  { q: "A single-Redis lock can be lost on…", options: ["Reads", "Failover (async replication may not have it)", "SCAN"], answer: 1,
    explain: "Why Redlock/consensus exists." },
  { q: "NX in the lock provides…", options: ["Expiry", "Mutual exclusion (only if not exists)", "Identity"], answer: 1,
    explain: "One winner." },
  { q: "TTL vs work-duration mismatch causes…", options: ["Nothing", "Lock expiring mid-work → double execution", "Deadlock"], answer: 1,
    explain: "Keep critical sections short." },
  { q: "Idempotent operations make…", options: ["Locks unnecessary", "Duplicate execution harmless (defense in depth)", "Locks faster"], answer: 1,
    explain: "Pairs with fencing." },
  { q: "A run-once cron across N instances uses…", options: ["A queue", "SET NX PX — whoever wins runs it", "Pub/Sub"], answer: 1,
    explain: "One instance acquires the lock." },
  { q: "For efficiency locks (avoid duplicate work), a simple lock is…", options: ["Never OK", "Fine (occasional double-run is just inefficient)", "Required to be Redlock"], answer: 1,
    explain: "Correctness locks are stricter." },
  { q: "When correctness is critical, consider…", options: ["Bigger TTLs", "etcd/ZooKeeper (consensus) instead of a timeout lock", "No lock"], answer: 1,
    explain: "Designed for that guarantee." },
  { q: "The lock value should be…", options: ["A constant", "A per-owner unique token", "The TTL"], answer: 1,
    explain: "So release only affects your lock." },
  { q: "The cache stampede rebuild lock is…", options: ["A leaderboard", "SET NX so one request rebuilds (caching lesson)", "Pub/Sub"], answer: 1,
    explain: "Same lock primitive." },
  { q: "The three lock essentials are…", options: ["Speed, size, TTL", "NX (exclusion) + TTL (auto-release) + unique token (identity)", "Lua only"], answer: 1,
    explain: "Missing any is a bug." }
]},

{ title: "Quiz 9 · Cluster, Use Cases & Memory",
  desc: "Hash slots, patterns, eviction, capacity",
  questions: [
  { q: "Redis Cluster distributes data via…", options: ["Random nodes", "16384 hash slots (CRC16(key) % 16384)", "Ranges of keys"], answer: 1,
    explain: "Each primary owns a slot range." },
  { q: "Fixed slots exist to…", options: ["Speed hashing", "Decouple keys from node count (move slots, not rehash all)", "Save memory"], answer: 1,
    explain: "Consistent-hashing-like rebalancing." },
  { q: "A multi-key op across different slots…", options: ["Works", "Returns CROSSSLOT error", "Is slow"], answer: 1,
    explain: "Can't coordinate across nodes atomically." },
  { q: "Hash tags {…} force keys into…", options: ["Different slots", "The SAME slot (only the brace part is hashed)", "No slot"], answer: 1,
    explain: "Co-locate related keys for multi-key ops." },
  { q: "Cluster failover is…", options: ["Sentinel-based", "Built-in (per-shard replicas promoted automatically)", "Manual"], answer: 1,
    explain: "No separate Sentinel needed." },
  { q: "You shard with Cluster when…", options: ["Reads are slow", "Dataset/write volume exceeds one node's RAM", "Always"], answer: 1,
    explain: "Exhaust vertical scaling + replicas first." },
  { q: "A rate limiter (fixed window) uses…", options: ["A sorted set only", "INCR + EXPIRE per user/window", "Pub/Sub"], answer: 1,
    explain: "Atomic; sliding window uses a sorted set." },
  { q: "A leaderboard uses…", options: ["A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)", "A list"], answer: 1,
    explain: "The canonical use case." },
  { q: "A session store uses…", options: ["A list", "SET EX with sliding TTL", "A set"], answer: 1,
    explain: "Fast, auto-expiring, shared across instances." },
  { q: "Atomic check-then-act logic uses…", options: ["Two commands", "A Lua script (EVAL) — atomic server-side", "Pub/Sub"], answer: 1,
    explain: "MULTI/EXEC lacks conditional logic." },
  { q: "When Redis hits maxmemory with noeviction…", options: ["Evicts keys", "Rejects writes with an error (reads still work)", "Crashes"], answer: 1,
    explain: "Safe for a data store." },
  { q: "allkeys-lru is right for…", options: ["A session store", "A cache (evict cold keys, they reload)", "A queue"], answer: 1,
    explain: "Eviction policy is a correctness choice." },
  { q: "allkeys eviction on session/queue data…", options: ["Is fine", "Silently DELETES non-reconstructable data (a bug)", "Errors"], answer: 1,
    explain: "Use noeviction / volatile-* there." },
  { q: "Redis LRU/LFU is…", options: ["Exact", "An efficient sampled APPROXIMATION (maxmemory-samples)", "Random"], answer: 1,
    explain: "Accuracy-for-efficiency trade." },
  { q: "To reduce memory, prefer…", options: ["Many string keys", "Hashes for objects (compact encoding) + TTLs", "Big values"], answer: 1,
    explain: "Plus HyperLogLog/Bitmaps, short keys." },
  { q: "maxmemory should be set…", options: ["Above RAM", "Below physical RAM (hit eviction, not the OS OOM killer)", "Unset"], answer: 1,
    explain: "OOM kill is catastrophic." },
  { q: "HyperLogLog trades…", options: ["Nothing", "Exactness for tiny memory (approx unique counts)", "Speed"], answer: 1,
    explain: "Kilobytes for millions of uniques." },
  { q: "A hot slot (one tenant dominates) causes…", options: ["Balance", "One node overloaded — spread keys / avoid over-concentrated hash tags", "Nothing"], answer: 1,
    explain: "Distribution matters even with slots." },
  { q: "Capacity planning needs headroom for…", options: ["Nothing", "Replication + RDB fork copy-on-write spike", "Only keys"], answer: 1,
    explain: "Fork can transiently double memory." },
  { q: "A cluster needs how many primaries for majority?", options: ["1", "≥3 (across failure domains)", "2"], answer: 1,
    explain: "Majority for failover decisions." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "A KEYS * command caused a latency spike for all clients. Cause?", options: ["Network", "It's O(n) and blocks the single thread — use SCAN", "Eviction"], answer: 1,
    explain: "Never KEYS in production." },
  { q: "App-side counter loses increments under load. Fix?", options: ["A lock", "Use INCR (atomic, no lost updates)", "A queue"], answer: 1,
    explain: "Redis is single-threaded/atomic." },
  { q: "A hot cache key expired and the DB got hammered. Name + fix?", options: ["Penetration; Bloom filter", "Stampede; rebuild lock / SWR / jittered TTLs", "Avalanche; warming"], answer: 1,
    explain: "Collapse concurrent rebuilds." },
  { q: "Requests for random non-existent ids keep hitting the DB. Name + fix?", options: ["Stampede; lock", "Penetration; cache negatives / Bloom filter", "Avalanche"], answer: 1,
    explain: "Absent-key misses." },
  { q: "A Redis restart caused a DB flood. Name + fix?", options: ["Stampede", "Avalanche; warm cache + jitter + DB rate-limit + HA", "Penetration"], answer: 1,
    explain: "Cold cache, 100% miss." },
  { q: "Critical messages vanish when a subscriber reconnects. Cause?", options: ["Streams", "Pub/Sub is fire-and-forget — use Streams", "Cluster"], answer: 1,
    explain: "No persistence/replay in Pub/Sub." },
  { q: "Your distributed lock let two jobs run at once. Likely cause?", options: ["NX missing", "Released with bare DEL (deleted another owner's lock)", "TTL too long"], answer: 1,
    explain: "Use atomic Lua token check." },
  { q: "Redis was OOM-killed by the OS. Fix?", options: ["More TTLs only", "Set maxmemory below RAM + an eviction policy", "Add replicas"], answer: 1,
    explain: "Hit eviction, not the OOM killer." },
  { q: "Sessions vanished under memory pressure. Cause?", options: ["Persistence off", "allkeys eviction deleted non-reconstructable data — use noeviction/volatile-*", "Cluster"], answer: 1,
    explain: "Eviction policy is a correctness choice." },
  { q: "MGET user:1 user:2 fails in the cluster. Cause + fix?", options: ["Bad client", "CROSSSLOT — co-locate with hash tags {user:1}", "Add nodes"], answer: 1,
    explain: "Multi-key needs the same slot." },
  { q: "After a primary crash, a few writes were lost. Why?", options: ["Bug", "Async replication — unreplicated writes lost (min-replicas-to-write)", "Eviction"], answer: 1,
    explain: "Failover trade-off." },
  { q: "Reading from a replica returned stale data. Fix?", options: ["More replicas", "Read from the primary for read-your-writes", "Sharding"], answer: 1,
    explain: "Replication lag." },
  { q: "Data was lost after a crash despite 'persistence'. Likely config?", options: ["AOF always", "RDB-only (lost since last snapshot) — add AOF everysec", "Both enabled"], answer: 1,
    explain: "Match persistence to loss tolerance." },
  { q: "You need a leaderboard for 10M players. Structure?", options: ["A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)", "A list"], answer: 1,
    explain: "O(log n) ranking." },
  { q: "A rate limiter allows 2× the limit at minute boundaries. Fix?", options: ["Bigger window", "Sliding window (sorted set) or token bucket", "More Redis"], answer: 1,
    explain: "Fixed-window edge bursts." },
  { q: "A multi-step recipe raced between commands. Fix?", options: ["Two round trips", "A Lua script (atomic) or MULTI/EXEC+WATCH", "Pub/Sub"], answer: 1,
    explain: "Single-threaded Lua = atomic." },
  { q: "Redis memory keeps growing with no bound. Cause?", options: ["Too few nodes", "No TTLs on cache keys / no maxmemory", "Replication"], answer: 1,
    explain: "TTL everything; cap memory." },
  { q: "You need durable, replayable, load-balanced job processing. Use?", options: ["Pub/Sub", "Streams + consumer groups (or Kafka at huge scale)", "A list only"], answer: 1,
    explain: "At-least-once with acks." },
  { q: "One Sentinel triggered a needless failover. Fix?", options: ["Fewer Sentinels", "Require a quorum (odd number, 3+)", "Disable Sentinel"], answer: 1,
    explain: "Majority must agree." },
  { q: "The single most important Redis mental model is…", options: ["Memorize commands", "In-memory + single-threaded → atomic ops, RAM-bound, pick the right structure", "Always shard"], answer: 1,
    explain: "Speed, atomicity, data-structure choice, and limits all derive from it. 🏆" }
]}
);
