// redis quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Persistence (RDB & AOF)",
  desc: "Snapshots, append-only file, durability trade-offs",
  questions: [
  { q: "RDB persistence is…", options: ["A log of writes", "Real-time", "Periodic point-in-time snapshots"], answer: 2,
    explain: "Compact binary; fast restart/backups." },
  { q: "RDB's downside is…", options: ["Huge files", "Losing everything since the last snapshot on crash", "Slow restart"], answer: 1,
    explain: "Could be minutes of data." },
  { q: "AOF persistence is…", options: ["In-memory only", "A log of every write, replayed on restart", "A snapshot"], answer: 1,
    explain: "More durable; larger file, slower replay." },
  { q: "appendfsync everysec means…", options: ["No durability", "Lose ≤1s of data (the common balance)", "Zero loss"], answer: 1,
    explain: "always = ~0 loss (slow); no = OS-decided." },
  { q: "The production best practice is…", options: ["Enable BOTH RDB and AOF", "RDB only", "AOF only"], answer: 0,
    explain: "AOF durability + RDB fast backups." },
  { q: "On restart with both, Redis recovers from…", options: ["RDB", "Memory", "The AOF (more complete)"], answer: 2,
    explain: "AOF has the most recent writes." },
  { q: "appendfsync always trades…", options: ["Nothing", "Durability for speed", "Latency for ~zero data loss"], answer: 2,
    explain: "fsync every write is slow." },
  { q: "AOF file growth is handled by…", options: ["TTL", "Manual deletion", "Periodic rewrite (BGREWRITEAOF) to compact form"], answer: 2,
    explain: "Keeps the file bounded." },
  { q: "For a pure cache, persistence…", options: ["Barely matters (data reconstructable from DB)", "Must be AOF always", "Is critical"], answer: 0,
    explain: "Match config to loss tolerance." },
  { q: "For a session store, use…", options: ["No persistence", "AOF everysec (≤1s loss)", "RDB only"], answer: 1,
    explain: "Recent writes matter." },
  { q: "Single-node persistence protects against…", options: ["Everything", "That node's restart/crash — not hardware loss", "Hardware loss"], answer: 1,
    explain: "Add replication + backups for real durability." },
  { q: "WAIT 1 100 does…", options: ["Blocks until ≥1 replica has the write (100ms timeout)", "Sleeps", "Snapshots"], answer: 0,
    explain: "Replica-acknowledged durability." },
  { q: "RDB uses a fork that can…", options: ["Transiently spike memory (copy-on-write)", "Never use memory", "Halve memory"], answer: 0,
    explain: "Headroom needed on write-heavy nodes." },
  { q: "BGSAVE triggers…", options: ["AOF rewrite", "A blocking save", "A background snapshot"], answer: 2,
    explain: "Non-blocking RDB snapshot." },
  { q: "Durability is…", options: ["Layered: fsync + replicas + off-box backups", "Automatic", "A single setting"], answer: 0,
    explain: "No one mechanism covers everything." },
  { q: "Disabling persistence entirely is fine for…", options: ["A pure disposable cache", "Queues", "Sessions"], answer: 0,
    explain: "Data reconstructable from the source of truth." },
  { q: "The core persistence question is…", options: ["How big is RAM?", "Which format?", "How much data can you afford to lose?"], answer: 2,
    explain: "Drives the config choice." },
  { q: "aof-use-rdb-preamble gives…", options: ["No AOF", "A hybrid RDB+AOF format (fast load + durability)", "Slower loads"], answer: 1,
    explain: "Best of both on restart." },
  { q: "Off-box RDB backups protect against…", options: ["Nothing", "Slow reads", "Disaster recovery (whole-node loss)"], answer: 2,
    explain: "Copy snapshots off the machine." },
  { q: "For a Redis-as-source-of-truth critical store…", options: ["AOF always + replication + backups", "RDB only", "No persistence"], answer: 0,
    explain: "Maximum durability layers." },
]},
{ title: "Quiz 7 · Replication & Sentinel",
  desc: "Primary/replica, async lag, failover, quorum",
  questions: [
  { q: "REPLICAOF makes a node…", options: ["A Sentinel", "A primary", "A read-only replica of the primary"], answer: 2,
    explain: "Copies the primary's data." },
  { q: "Replication is…", options: ["Asynchronous (replicas can lag)", "Two-phase", "Synchronous"], answer: 0,
    explain: "Primary acks before replicas have it." },
  { q: "Reading from a replica can return…", options: ["Errors", "Fresh data always", "Stale data (lag) — read primary for freshness"], answer: 2,
    explain: "Read-your-writes needs the primary." },
  { q: "Sentinel provides…", options: ["Sharding", "Monitoring + automatic failover + primary discovery", "Persistence"], answer: 1,
    explain: "Promotes a replica on primary failure." },
  { q: "Sentinel failover requires…", options: ["No agreement", "One Sentinel", "A QUORUM of Sentinels to agree"], answer: 2,
    explain: "Prevents needless/split failovers." },
  { q: "Run how many Sentinels?", options: ["Odd number (3+) across failure domains", "Even number", "One"], answer: 0,
    explain: "Majority must be reachable." },
  { q: "Quorum prevents…", options: ["Split-brain (two primaries) during partitions", "Lag", "Evictions"], answer: 0,
    explain: "Only the majority side promotes." },
  { q: "Clients find the current primary via…", options: ["DNS only", "A fixed IP", "Sentinel-aware discovery"], answer: 2,
    explain: "Don't hardcode the primary address." },
  { q: "During failover, writes…", options: ["Are queued forever", "Never fail", "Fail briefly (retry with backoff)"], answer: 2,
    explain: "Seconds of unavailability." },
  { q: "Unreplicated writes on a failed primary are…", options: ["Lost (async replication)", "Recovered", "Queued"], answer: 0,
    explain: "min-replicas-to-write shrinks the window." },
  { q: "Replicas scale…", options: ["READS (and provide redundancy)", "Storage", "Writes"], answer: 0,
    explain: "Each holds the full dataset." },
  { q: "min-replicas-to-write…", options: ["Refuses writes unless N replicas are current (less loss)", "Speeds writes", "Adds Sentinels"], answer: 0,
    explain: "Durability vs availability trade." },
  { q: "The majority principle also appears in…", options: ["MongoDB elections and consensus (Raft)", "Only Redis", "Nowhere else"], answer: 0,
    explain: "Quorum is universal in distributed systems." },
  { q: "A single Redis node is…", options: ["Highly available", "A single point of failure", "Sharded"], answer: 1,
    explain: "Add replicas + Sentinel." },
  { q: "Managed Redis (ElastiCache) handles…", options: ["Nothing", "Sentinel/failover for you", "Only caching"], answer: 1,
    explain: "Common production choice." },
  { q: "A replica's initial sync uses…", options: ["AOF only", "Nothing", "A full RDB sync, then command streaming"], answer: 2,
    explain: "Then stays current via the stream." },
  { q: "Spreading Sentinels across failure domains prevents…", options: ["Lag", "Evictions", "Correlated failure (all Sentinels down together)"], answer: 2,
    explain: "Don't co-locate them all." },
  { q: "WAIT complements replication by…", options: ["Requiring a write reach N replicas before proceeding", "Sharding", "Evicting"], answer: 0,
    explain: "For critical-write durability." },
  { q: "Redis Cluster's failover is…", options: ["Sentinel-based", "Built-in (per-shard replicas, no separate Sentinel)", "Manual"], answer: 1,
    explain: "Cluster has its own failover." },
  { q: "HA needs (minimum)…", options: ["Replicas + automatic failover (Sentinel or Cluster)", "Only persistence", "One node"], answer: 0,
    explain: "Persistence ≠ availability." },
]},
{ title: "Quiz 8 · Distributed Locks",
  desc: "SET NX PX, atomic release, fencing, Redlock",
  questions: [
  { q: "A correct lock acquire is…", options: ["INCR", "SET key val", "SET key uniqueToken NX PX ttl"], answer: 2,
    explain: "Mutual exclusion + auto-expire + owner identity." },
  { q: "The TTL on a lock prevents…", options: ["Fast work", "A crashed holder deadlocking it forever", "Concurrency"], answer: 1,
    explain: "Auto-release on crash." },
  { q: "The unique token is needed to…", options: ["Only release YOUR lock (not someone else's)", "Speed up", "Sort"], answer: 0,
    explain: "Critical for correct release." },
  { q: "Releasing with a bare DEL is dangerous because…", options: ["Your expired lock may be re-acquired → you delete another owner's", "It's slow", "It errors"], answer: 0,
    explain: "Two processes then run concurrently." },
  { q: "Correct release uses…", options: ["EXPIRE", "An atomic Lua check-and-delete (delete if token matches)", "GET then DEL"], answer: 1,
    explain: "GET-then-DEL races; Lua is atomic." },
  { q: "If a holder stalls past the TTL…", options: ["The lock expires → another process acquires it (double execution)", "It renews", "Nothing happens"], answer: 0,
    explain: "No timeout-lock fully prevents this." },
  { q: "For hard correctness, add…", options: ["Fencing tokens + idempotency at the resource", "More Redis", "Longer TTLs"], answer: 0,
    explain: "Locks manage contention; fencing ensures correctness." },
  { q: "A fencing token is…", options: ["A monotonically increasing number the resource checks (rejects stale)", "A TTL", "Random"], answer: 0,
    explain: "Refuses a delayed old holder's writes." },
  { q: "Redlock acquires a lock across…", options: ["One node", "Replicas", "Multiple independent Redis primaries (majority)"], answer: 2,
    explain: "Survives single-node failover." },
  { q: "The Redlock debate concludes…", options: ["Never lock", "It's bulletproof", "For correctness use fencing/idempotency (or etcd/ZooKeeper); simple locks for efficiency"], answer: 2,
    explain: "Kleppmann vs antirez." },
  { q: "A single-Redis lock can be lost on…", options: ["Failover (async replication may not have it)", "Reads", "SCAN"], answer: 0,
    explain: "Why Redlock/consensus exists." },
  { q: "NX in the lock provides…", options: ["Identity", "Mutual exclusion (only if not exists)", "Expiry"], answer: 1,
    explain: "One winner." },
  { q: "TTL vs work-duration mismatch causes…", options: ["Lock expiring mid-work → double execution", "Nothing", "Deadlock"], answer: 0,
    explain: "Keep critical sections short." },
  { q: "Idempotent operations make…", options: ["Locks faster", "Duplicate execution harmless (defense in depth)", "Locks unnecessary"], answer: 1,
    explain: "Pairs with fencing." },
  { q: "A run-once cron across N instances uses…", options: ["A queue", "Pub/Sub", "SET NX PX — whoever wins runs it"], answer: 2,
    explain: "One instance acquires the lock." },
  { q: "For efficiency locks (avoid duplicate work), a simple lock is…", options: ["Never OK", "Fine (occasional double-run is just inefficient)", "Required to be Redlock"], answer: 1,
    explain: "Correctness locks are stricter." },
  { q: "When correctness is critical, consider…", options: ["etcd/ZooKeeper (consensus) instead of a timeout lock", "No lock", "Bigger TTLs"], answer: 0,
    explain: "Designed for that guarantee." },
  { q: "The lock value should be…", options: ["A per-owner unique token", "A constant", "The TTL"], answer: 0,
    explain: "So release only affects your lock." },
  { q: "The cache stampede rebuild lock is…", options: ["Pub/Sub", "A leaderboard", "SET NX so one request rebuilds (caching lesson)"], answer: 2,
    explain: "Same lock primitive." },
  { q: "The three lock essentials are…", options: ["NX (exclusion) + TTL (auto-release) + unique token (identity)", "Lua only", "Speed, size, TTL"], answer: 0,
    explain: "Missing any is a bug." },
]},
{ title: "Quiz 9 · Cluster, Use Cases & Memory",
  desc: "Hash slots, patterns, eviction, capacity",
  questions: [
  { q: "Redis Cluster distributes data via…", options: ["Ranges of keys", "Random nodes", "16384 hash slots (CRC16(key) % 16384)"], answer: 2,
    explain: "Each primary owns a slot range." },
  { q: "Fixed slots exist to…", options: ["Speed hashing", "Save memory", "Decouple keys from node count (move slots, not rehash all)"], answer: 2,
    explain: "Consistent-hashing-like rebalancing." },
  { q: "A multi-key op across different slots…", options: ["Returns CROSSSLOT error", "Is slow", "Works"], answer: 0,
    explain: "Can't coordinate across nodes atomically." },
  { q: "Hash tags {…} force keys into…", options: ["No slot", "The SAME slot (only the brace part is hashed)", "Different slots"], answer: 1,
    explain: "Co-locate related keys for multi-key ops." },
  { q: "Cluster failover is…", options: ["Built-in (per-shard replicas promoted automatically)", "Sentinel-based", "Manual"], answer: 0,
    explain: "No separate Sentinel needed." },
  { q: "You shard with Cluster when…", options: ["Reads are slow", "Always", "Dataset/write volume exceeds one node's RAM"], answer: 2,
    explain: "Exhaust vertical scaling + replicas first." },
  { q: "A rate limiter (fixed window) uses…", options: ["INCR + EXPIRE per user/window", "Pub/Sub", "A sorted set only"], answer: 0,
    explain: "Atomic; sliding window uses a sorted set." },
  { q: "A leaderboard uses…", options: ["A list", "A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)"], answer: 2,
    explain: "The canonical use case." },
  { q: "A session store uses…", options: ["A set", "A list", "SET EX with sliding TTL"], answer: 2,
    explain: "Fast, auto-expiring, shared across instances." },
  { q: "Atomic check-then-act logic uses…", options: ["A Lua script (EVAL) — atomic server-side", "Two commands", "Pub/Sub"], answer: 0,
    explain: "MULTI/EXEC lacks conditional logic." },
  { q: "When Redis hits maxmemory with noeviction…", options: ["Evicts keys", "Crashes", "Rejects writes with an error (reads still work)"], answer: 2,
    explain: "Safe for a data store." },
  { q: "allkeys-lru is right for…", options: ["A session store", "A queue", "A cache (evict cold keys, they reload)"], answer: 2,
    explain: "Eviction policy is a correctness choice." },
  { q: "allkeys eviction on session/queue data…", options: ["Is fine", "Errors", "Silently DELETES non-reconstructable data (a bug)"], answer: 2,
    explain: "Use noeviction / volatile-* there." },
  { q: "Redis LRU/LFU is…", options: ["Random", "An efficient sampled APPROXIMATION (maxmemory-samples)", "Exact"], answer: 1,
    explain: "Accuracy-for-efficiency trade." },
  { q: "To reduce memory, prefer…", options: ["Hashes for objects (compact encoding) + TTLs", "Big values", "Many string keys"], answer: 0,
    explain: "Plus HyperLogLog/Bitmaps, short keys." },
  { q: "maxmemory should be set…", options: ["Unset", "Above RAM", "Below physical RAM (hit eviction, not the OS OOM killer)"], answer: 2,
    explain: "OOM kill is catastrophic." },
  { q: "HyperLogLog trades…", options: ["Nothing", "Speed", "Exactness for tiny memory (approx unique counts)"], answer: 2,
    explain: "Kilobytes for millions of uniques." },
  { q: "A hot slot (one tenant dominates) causes…", options: ["One node overloaded — spread keys / avoid over-concentrated hash tags", "Nothing", "Balance"], answer: 0,
    explain: "Distribution matters even with slots." },
  { q: "Capacity planning needs headroom for…", options: ["Only keys", "Replication + RDB fork copy-on-write spike", "Nothing"], answer: 1,
    explain: "Fork can transiently double memory." },
  { q: "A cluster needs how many primaries for majority?", options: ["2", "≥3 (across failure domains)", "1"], answer: 1,
    explain: "Majority for failover decisions." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "A KEYS * command caused a latency spike for all clients. Cause?", options: ["Network", "Eviction", "It's O(n) and blocks the single thread — use SCAN"], answer: 2,
    explain: "Never KEYS in production." },
  { q: "App-side counter loses increments under load. Fix?", options: ["A lock", "Use INCR (atomic, no lost updates)", "A queue"], answer: 1,
    explain: "Redis is single-threaded/atomic." },
  { q: "A hot cache key expired and the DB got hammered. Name + fix?", options: ["Penetration; Bloom filter", "Stampede; rebuild lock / SWR / jittered TTLs", "Avalanche; warming"], answer: 1,
    explain: "Collapse concurrent rebuilds." },
  { q: "Requests for random non-existent ids keep hitting the DB. Name + fix?", options: ["Penetration; cache negatives / Bloom filter", "Avalanche", "Stampede; lock"], answer: 0,
    explain: "Absent-key misses." },
  { q: "A Redis restart caused a DB flood. Name + fix?", options: ["Penetration", "Stampede", "Avalanche; warm cache + jitter + DB rate-limit + HA"], answer: 2,
    explain: "Cold cache, 100% miss." },
  { q: "Critical messages vanish when a subscriber reconnects. Cause?", options: ["Streams", "Cluster", "Pub/Sub is fire-and-forget — use Streams"], answer: 2,
    explain: "No persistence/replay in Pub/Sub." },
  { q: "Your distributed lock let two jobs run at once. Likely cause?", options: ["Released with bare DEL (deleted another owner's lock)", "TTL too long", "NX missing"], answer: 0,
    explain: "Use atomic Lua token check." },
  { q: "Redis was OOM-killed by the OS. Fix?", options: ["More TTLs only", "Set maxmemory below RAM + an eviction policy", "Add replicas"], answer: 1,
    explain: "Hit eviction, not the OOM killer." },
  { q: "Sessions vanished under memory pressure. Cause?", options: ["allkeys eviction deleted non-reconstructable data — use noeviction/volatile-*", "Cluster", "Persistence off"], answer: 0,
    explain: "Eviction policy is a correctness choice." },
  { q: "MGET user:1 user:2 fails in the cluster. Cause + fix?", options: ["Add nodes", "Bad client", "CROSSSLOT — co-locate with hash tags {user:1}"], answer: 2,
    explain: "Multi-key needs the same slot." },
  { q: "After a primary crash, a few writes were lost. Why?", options: ["Eviction", "Bug", "Async replication — unreplicated writes lost (min-replicas-to-write)"], answer: 2,
    explain: "Failover trade-off." },
  { q: "Reading from a replica returned stale data. Fix?", options: ["More replicas", "Sharding", "Read from the primary for read-your-writes"], answer: 2,
    explain: "Replication lag." },
  { q: "Data was lost after a crash despite 'persistence'. Likely config?", options: ["RDB-only (lost since last snapshot) — add AOF everysec", "AOF always", "Both enabled"], answer: 0,
    explain: "Match persistence to loss tolerance." },
  { q: "You need a leaderboard for 10M players. Structure?", options: ["A hash", "A sorted set (ZADD/ZREVRANGE/ZREVRANK)", "A list"], answer: 1,
    explain: "O(log n) ranking." },
  { q: "A rate limiter allows 2× the limit at minute boundaries. Fix?", options: ["Bigger window", "Sliding window (sorted set) or token bucket", "More Redis"], answer: 1,
    explain: "Fixed-window edge bursts." },
  { q: "A multi-step recipe raced between commands. Fix?", options: ["Pub/Sub", "A Lua script (atomic) or MULTI/EXEC+WATCH", "Two round trips"], answer: 1,
    explain: "Single-threaded Lua = atomic." },
  { q: "Redis memory keeps growing with no bound. Cause?", options: ["Too few nodes", "No TTLs on cache keys / no maxmemory", "Replication"], answer: 1,
    explain: "TTL everything; cap memory." },
  { q: "You need durable, replayable, load-balanced job processing. Use?", options: ["A list only", "Streams + consumer groups (or Kafka at huge scale)", "Pub/Sub"], answer: 1,
    explain: "At-least-once with acks." },
  { q: "One Sentinel triggered a needless failover. Fix?", options: ["Fewer Sentinels", "Require a quorum (odd number, 3+)", "Disable Sentinel"], answer: 1,
    explain: "Majority must agree." },
  { q: "The single most important Redis mental model is…", options: ["Always shard", "Memorize commands", "In-memory + single-threaded → atomic ops, RAM-bound, pick the right structure"], answer: 2,
    explain: "Speed, atomicity, data-structure choice, and limits all derive from it. 🏆" },
]},
);
