// JavaScript quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Variables, Types & Operators",
  desc: "let/const, types, coercion, equality, modern operators",
  questions: [
  { q: "const arr = []; arr.push(1); — result?", options: ["TypeError", "Works — const blocks REASSIGNMENT, not mutation", "Silent no-op"], answer: 1,
    explain: "const freezes the binding, not the value. Object.freeze() is the (shallow) value-freezer." },
  { q: "The modern declaration policy is…", options: ["var by default", "const by default, let when reassignment is needed, var never", "let everywhere"], answer: 1,
    explain: "Enforced by prefer-const/no-var lint rules in every serious codebase." },
  { q: "typeof null returns…", options: ["\"null\"", "\"object\" — a 30-year-old bug kept for compatibility", "\"undefined\""], answer: 1,
    explain: "Check null with x === null; check 'nullish' with x == null (matches undefined too — the one useful ==)." },
  { q: "0.1 + 0.2 === 0.3 is…", options: ["true", "false — IEEE-754 floats; money must be integer cents", "A syntax error"], answer: 1,
    explain: "0.30000000000000004. Compare with Number.EPSILON tolerance or work in integers." },
  { q: "undefined vs null:", options: ["Identical", "undefined = never assigned; null = deliberately empty", "null is newer"], answer: 1,
    explain: "APIs signal 'intentionally nothing' with null; the language itself produces undefined." },
  { q: "1 == \"1\" is true because…", options: ["They're equal", "== coerces types before comparing — which is why === is the default", "Strings are numbers"], answer: 1,
    explain: "eqeqeq lint rule bans ==; the coercion table is famously unmemorable." },
  { q: "NaN === NaN evaluates to…", options: ["true", "false — NaN equals nothing; use Number.isNaN()", "TypeError"], answer: 1,
    explain: "The only value in JS not equal to itself. Array.prototype.includes uses SameValueZero and DOES find NaN." },
  { q: "The eight falsy values include…", options: ["\"0\" and []", "false, 0, -0, 0n, \"\", null, undefined, NaN — everything else is truthy", "Any empty object"], answer: 1,
    explain: "\"0\", [], {} are all TRUTHY — the classic quiz trap." },
  { q: "count || 10 vs count ?? 10 differ when count is…", options: ["undefined", "0 or \"\" — || replaces legitimate falsy values; ?? only replaces null/undefined", "null"], answer: 1,
    explain: "?? exists precisely because || eats valid zeros and empty strings." },
  { q: "user?.address?.city when address is undefined gives…", options: ["TypeError", "undefined — optional chaining short-circuits safely", "null"], answer: 1,
    explain: "Also works for calls (fn?.()) and indexes (arr?.[0]). Don't chain ?. everywhere — it hides real bugs." },
  { q: "typeof [] returns…", options: ["\"array\"", "\"object\" — use Array.isArray()", "\"list\""], answer: 1,
    explain: "Arrays are objects with special length behavior; typeof can't distinguish them." },
  { q: "BigInt (10n) exists because…", options: ["Decoration", "Number is unsafe beyond 2^53−1 (Number.MAX_SAFE_INTEGER) — IDs from databases can exceed it", "It's faster"], answer: 1,
    explain: "Mixing BigInt and Number throws — JSON, DOM APIs, and Math don't accept BigInt either. Use for large integer IDs." },
  { q: "\"5\" + 3 and \"5\" - 3 evaluate to…", options: ["8 and 2", "\"53\" and 2 — + concatenates with strings; - always coerces to number", "Both NaN"], answer: 1,
    explain: "The asymmetry that fuels a thousand memes. Convert explicitly: Number(x), String(x)." },
  { q: "Template literals `Hi ${name}` beat concatenation because…", options: ["Performance", "Readability, multi-line support, and expression interpolation", "They escape HTML"], answer: 1,
    explain: "They do NOT escape HTML — interpolating user input into innerHTML is still XSS." },
  { q: "let x; console.log(x) prints…", options: ["ReferenceError", "undefined — declared but unassigned", "null"], answer: 1,
    explain: "Distinct from an UNDECLARED variable, which throws ReferenceError." },
  { q: "Object.is(-0, 0) and Object.is(NaN, NaN):", options: ["true, false", "false, true — Object.is fixes ===' s two oddities", "Both true"], answer: 1,
    explain: "Rarely needed but a favorite trivia question; ===' s NaN and signed-zero behaviors are the exceptions." },
  { q: "The ternary a ? b : c should be used for…", options: ["All conditionals", "Simple value selection — nested ternaries belong refactored into if/else or lookup maps", "Loops"], answer: 1,
    explain: "One level: fine and idiomatic. Two+: reviewers will (rightly) object." },
  { q: "Symbol's primary use is…", options: ["Math", "Collision-proof property keys and protocol hooks (Symbol.iterator)", "Encryption"], answer: 1,
    explain: "Library metadata on objects without name clashes; the iteration protocol lives at Symbol.iterator." },
  { q: "structuredClone(obj) vs JSON.parse(JSON.stringify(obj)):", options: ["Identical", "structuredClone handles Dates, Maps, Sets, cycles — JSON round-trip corrupts or throws on them", "JSON is safer"], answer: 1,
    explain: "The JSON hack drops undefined, functions, converts Dates to strings, and explodes on circular refs." },
  { q: "Number(\"12px\") vs parseInt(\"12px\"):", options: ["Both 12", "NaN vs 12 — parseInt reads leading digits; Number wants the WHOLE string numeric", "Both NaN"], answer: 1,
    explain: "Know both behaviors; parseInt also wants its radix argument (parseInt(x, 10)) in older codebases." }
]},

{ title: "Quiz 2 · Functions, Scope & Closures",
  desc: "Declarations vs arrows, hoisting, closures, this, debounce",
  questions: [
  { q: "Calling greet() BEFORE function greet(){} in the file…", options: ["ReferenceError", "Works — function declarations hoist entirely", "undefined is not a function"], answer: 1,
    explain: "Declarations hoist with their body; const fn = () => {} hoists only the binding (TDZ) — calling early throws." },
  { q: "The Temporal Dead Zone is…", options: ["A timing API", "The region between scope start and a let/const declaration where access throws", "Garbage collection"], answer: 1,
    explain: "let/const ARE hoisted — just uninitialized. That's why the error says 'Cannot access before initialization'." },
  { q: "A closure is…", options: ["A closed tab", "A function plus the scope it was created in — variables survive as long as the function does", "A private class"], answer: 1,
    explain: "makeCounter()'s count lives on between calls because the returned function references it." },
  { q: "for (var i=0;i<3;i++) setTimeout(()=>console.log(i)) prints…", options: ["0 1 2", "3 3 3 — one function-scoped i shared by all three closures", "undefined ×3"], answer: 1,
    explain: "let creates a fresh binding per iteration → 0 1 2. The most-asked closure question in interviews." },
  { q: "Debounce (search-as-you-type) works by…", options: ["Throttling the server", "A closed-over timer reset on every call — fn fires only after ms of silence", "Web Workers"], answer: 1,
    explain: "clearTimeout(timer); timer = setTimeout(...) — the timer variable in the closure is the whole trick." },
  { q: "Throttle differs from debounce:", options: ["Same thing", "Throttle guarantees execution every N ms during activity; debounce waits for silence", "Throttle is async"], answer: 1,
    explain: "Scroll handlers → throttle (regular updates); search input → debounce (act when typing stops)." },
  { q: "const f = user.greet; f() — this inside is…", options: ["user", "undefined (strict/modules) — this is decided by the CALL, and f() is a bare call", "window always"], answer: 1,
    explain: "The receiver is whatever's left of the dot AT CALL TIME. Detached methods lose it — bind or wrap in an arrow." },
  { q: "Arrow functions' this is…", options: ["The caller", "Inherited from where the arrow was WRITTEN — they have no own this", "Always undefined"], answer: 1,
    explain: "Why setInterval(() => this.tick(), 1000) works in a class and function(){} doesn't." },
  { q: "The modern this rule of thumb:", options: ["Arrows everywhere", "Methods = regular functions (need dynamic this); callbacks = arrows (inherit it)", "bind everything"], answer: 1,
    explain: "Covers 99% of code. Arrow methods on objects break call-site receivers; function callbacks lose this." },
  { q: "fn.bind(x) returns…", options: ["Nothing, mutates fn", "A NEW function with this fixed to x — original untouched", "x"], answer: 1,
    explain: "bind also pre-fills arguments (partial application). call/apply invoke immediately with the given this." },
  { q: "function createWallet(balance) returning {deposit, getBalance} demonstrates…", options: ["Classes are dead", "Private state via closure — balance is unreachable except through the API", "Memory leaks"], answer: 1,
    explain: "Before #private fields, closures were THE encapsulation tool — still idiomatic for factories/modules." },
  { q: "Default parameter (role = \"viewer\") triggers when the argument is…", options: ["Any falsy value", "undefined only (including omitted) — null does NOT trigger defaults", "null or undefined"], answer: 1,
    explain: "f(null) passes null through; f() and f(undefined) get the default. A subtle API-design gotcha." },
  { q: "Rest params (...nums) vs the arguments object:", options: ["Identical", "Rest is a real Array and works in arrows; arguments is array-like, absent in arrows, legacy", "arguments is faster"], answer: 1,
    explain: "New code uses rest exclusively; recognizing arguments matters for old codebases." },
  { q: "A function taking 4+ positional args should…", options: ["Add more docs", "Take an options object — self-documenting call sites, non-breaking extension", "Split into 4 functions"], answer: 1,
    explain: "createUser(\"D\", {role:\"admin\"}) reads; createUser(\"D\", true, false, 3) doesn't." },
  { q: "A pure function is one that…", options: ["Uses no variables", "Same inputs → same output, no side effects — trivially testable, safely cacheable", "Has no parameters"], answer: 1,
    explain: "Architecture skill: pure core, effects (network/DOM/log) pushed to the edges. React/Redux formalize this." },
  { q: "const log = (level) => (tag) => (msg) => …; const warnAuth = log('WARN')('auth') demonstrates…", options: ["A syntax error", "Currying — config captured early via closures, data supplied late; specialize once, reuse many times", "Recursion"], answer: 1,
    explain: "Each call closes over its argument and returns a function awaiting the next. The 'config first, data last' convention makes curried fns drop into map/filter pipelines." },
  { q: "A memoized function starts returning STALE results. The root cause is almost always…", options: ["The cache is too small", "The function is IMPURE — it reads inputs (globals, time, mutable state) not captured in the cache key", "Map is buggy"], answer: 1,
    explain: "Memoization is only correct for pure functions: arg→result caching assumes args are the ONLY inputs. Fix: make every real input an explicit argument." },
  { q: "React hooks 'stale closure' bugs happen because…", options: ["React caches wrong", "Each render's functions capture THAT render's variables — the same makeCounter mechanics", "Hooks are async"], answer: 1,
    explain: "An interval reading count from render #1 logs 1 forever unless deps/refs are used. Closures 101 wearing a React costume." },
  { q: "Recursion depth in JS is limited by…", options: ["Nothing", "The call stack (~10⁴ frames) — RangeError: Maximum call stack size exceeded; convert to loops for deep data", "The event loop"], answer: 1,
    explain: "No guaranteed tail-call optimization in practice (only Safari implements it). Deep trees → iterative + explicit stack." },
  { q: "console.log(this) at the top level of an ES module prints…", options: ["window", "undefined — modules are strict; top-level this is not the global object", "globalThis"], answer: 1,
    explain: "Use globalThis for the actual global across environments (browser/Node/workers)." }
]},

{ title: "Quiz 3 · Arrays, Objects & Data Wrangling",
  desc: "map/filter/reduce, mutation vs copy, destructuring, Map/Set",
  questions: [
  { q: "map/filter/reduce respectively…", options: ["Mutate the array", "Transform each item / keep passing items / fold to one value — all returning NEW arrays or values", "Only work on numbers"], answer: 1,
    explain: "The transform trio behind 90% of application data flow: API response in, view model out." },
  { q: "Which set MUTATES the original array?", options: ["map, filter, slice, concat", "push, pop, splice, sort, reverse", "toSorted, toReversed, with"], answer: 1,
    explain: "sort() mutating surprises everyone once. The to* variants are the modern immutable versions." },
  { q: "React doesn't re-render after items.push(x) because…", options: ["push is async", "Same array reference — frameworks detect change by reference; copy instead ([...items, x])", "push returns length"], answer: 1,
    explain: "Reference equality is the change-detection contract; in-place mutation is invisible to it." },
  { q: "[...users].sort(...) vs users.sort(...):", options: ["Identical", "The spread copies first — original preserved; bare sort mutates in place", "Spread is slower so never"], answer: 1,
    explain: "Or users.toSorted(...) where available — expresses the intent directly." },
  { q: "arr.sort() with no comparator sorts [10, 9, 1] as…", options: ["[1, 9, 10]", "[1, 10, 9] — default sort is STRING-based; numbers need (a,b) => a-b", "[10, 9, 1]"], answer: 1,
    explain: "\"10\" < \"9\" lexicographically. The single most common sort bug." },
  { q: "find vs filter:", options: ["Aliases", "find → first match (or undefined); filter → ALL matches as an array", "find throws when absent"], answer: 1,
    explain: "some/every are the boolean cousins: any-pass / all-pass." },
  { q: "reduce((sum,u)=>sum+u.score, 0) — the 0 is…", options: ["A length limit", "The initial accumulator — omitting it uses element[0] and breaks on empty arrays", "Optional decoration"], answer: 1,
    explain: "Always pass the initial value; empty-array reduce without one throws TypeError." },
  { q: "Spread {...user, score: 95} performs…", options: ["Deep copy", "SHALLOW copy — nested objects still shared; structuredClone for deep", "A reference alias"], answer: 1,
    explain: "Mutating copy.address.city changes the original's too — the shallow-copy bug class." },
  { q: "const { score: points = 0 } = user does…", options: ["Sets user.score to 0", "Extracts user.score AS the variable points, defaulting to 0 if undefined", "Renames the property"], answer: 1,
    explain: "Extract + rename + default in one pattern; works in function parameters too." },
  { q: "Object keys are always…", options: ["Any type", "Strings or Symbols — obj[1] and obj[\"1\"] are the same key; use Map for object keys", "Case-insensitive"], answer: 1,
    explain: "A plain {} coerces object keys to \"[object Object]\" — Map keeps any key type by identity." },
  { q: "[...new Set(arr)] is the idiom for…", options: ["Sorting", "Deduplication (by SameValueZero identity — objects dedupe by reference)", "Flattening"], answer: 1,
    explain: "For dedupe-by-property, keyBy with a Map: new Map(arr.map(x => [x.id, x])).values()." },
  { q: "ids.forEach(async id => await save(id)) …", options: ["Runs sequentially", "Fires all and waits for NONE — forEach ignores returned promises", "Throws"], answer: 1,
    explain: "Sequential: for…of with await. Parallel: await Promise.all(ids.map(...)). The forEach-async bug is everywhere." },
  { q: "Object.groupBy(users, u => u.role) returns…", options: ["An array of arrays", "{ admin: […], viewer: […] } — declarative grouping (also Map.groupBy)", "A Map only"], answer: 1,
    explain: "Replaces the classic reduce-into-object boilerplate." },
  { q: "A user's birthday 'July 18' saved as new Date('2026-07-18') displays as July 17 for US users because…", options: ["A browser bug", "Date-only ISO strings parse as UTC MIDNIGHT — still the previous day in timezones west of UTC", "Months are 0-indexed"], answer: 1,
    explain: "The classic off-by-one-day bug. Local date: new Date(2026, 6, 18) — or treat date-only values as calendar dates (strings/Temporal.PlainDate), never instants." },
  { q: "names.sort() puts 'Zoe' before 'ada' and 'file10' before 'file2'. The human-correct fix:", options: ["toLowerCase everything first", "sort(new Intl.Collator(locale, { numeric: true }).compare) — locale-aware, numeric-aware comparison", "Sorting is locale-independent"], answer: 1,
    explain: "Default sort compares UTF-16 code units (uppercase < lowercase, digits lexicographic). Intl.Collator/localeCompare handles case, accents, and numeric ordering." },
  { q: "Comparing {a:1} === {a:1} yields…", options: ["true", "false — objects compare by REFERENCE, not shape", "TypeError"], answer: 1,
    explain: "Deep equality needs a utility (or JSON tricks with all their caveats). Reference semantics underpin memoization and React deps." },
  { q: "Object.entries + fromEntries enable…", options: ["Cloning only", "Object transforms via array methods: filter/map entries, rebuild the object", "Sorting keys permanently"], answer: 1,
    explain: "Object.fromEntries(Object.entries(obj).filter(([k,v]) => v != null)) — strip nullish fields in one line." },
  { q: "A WeakMap is chosen over Map when…", options: ["You need iteration", "Keys are objects whose lifetime you DON'T control — entries vanish with the key (no leaks)", "Keys are strings"], answer: 1,
    explain: "Metadata about DOM nodes/instances; not iterable by design. String keys can't be weak." },
  { q: "JSON.stringify drops or mangles…", options: ["Nothing", "undefined values, functions, Symbols; Dates become strings; Maps/Sets become {}", "Only comments"], answer: 1,
    explain: "JSON is a data format, not a JS serializer — know what survives the round trip." },
  { q: "for…of vs for…in on arrays:", options: ["Interchangeable", "of → values (correct); in → string KEYS incl. inherited enumerables (wrong tool)", "in is faster"], answer: 1,
    explain: "for…in on arrays iterates \"0\",\"1\",… plus anything enumerable on the prototype chain — a bug farm." }
]},

{ title: "Quiz 4 · DOM, Events & Browser APIs",
  desc: "Selection, manipulation, bubbling, delegation, forms, observers",
  questions: [
  { q: "A live notifications feed (server→client only). WebSocket or SSE?", options: ["WebSocket — it's newer", "SSE — one-directional push over plain HTTP with auto-reconnect and Last-Event-ID replay built in", "Polling every second"], answer: 1,
    explain: "Reserve WebSocket for genuinely bidirectional high-frequency traffic (chat, multiplayer). SSE gives you free the two hardest resilience features you'd hand-build on WS." },
  { q: "textContent vs innerHTML for user data:", options: ["innerHTML — it's richer", "textContent — always literal text; innerHTML parses markup (XSS)", "They're equal"], answer: 1,
    explain: "The security-critical distinction; frameworks default to the textContent-equivalent." },
  { q: "Event bubbling means…", options: ["Events fire twice", "Events propagate child → ancestors → document — enabling delegation", "Sound effects"], answer: 1,
    explain: "Capture phase runs the other way first (rarely used; addEventListener's third arg)." },
  { q: "Event delegation on a 1000-row table is…", options: ["1000 listeners", "ONE listener on the table using e.target.closest('[data-action]') — rows added later work automatically", "Impossible"], answer: 1,
    explain: "Fewer listeners, dynamic-content-proof — how frameworks implement events internally." },
  { q: "e.preventDefault() vs e.stopPropagation():", options: ["Aliases", "preventDefault stops the BROWSER action (nav, submit); stopPropagation stops BUBBLING to ancestors", "Both stop everything"], answer: 1,
    explain: "stopPropagation silently breaks analytics/outside-click handlers — use deliberately, not defensively." },
  { q: "Reading a whole form in one line:", options: ["Loop over inputs", "Object.fromEntries(new FormData(form))", "form.values()"], answer: 1,
    explain: "FormData collects every named field — including files; also POSTs directly via fetch(url, {body: fd})." },
  { q: "DOMContentLoaded wrappers are unnecessary when scripts use…", options: ["async", "defer / type=module — they already run after parsing", "setTimeout(0)"], answer: 1,
    explain: "Deferred scripts see the complete DOM by contract." },
  { q: "Batch-inserting 500 rows efficiently uses…", options: ["500 appendChild calls in a loop is fine", "DocumentFragment (or one insertAdjacentHTML) — touch the live DOM once", "innerHTML +="], answer: 1,
    explain: "innerHTML += re-parses everything each iteration (O(n²)) and destroys listeners — the worst option." },
  { q: "AbortController with addEventListener gives you…", options: ["Error handling", "Bulk listener removal via one signal.abort() — component-cleanup pattern", "Passive events"], answer: 1,
    explain: "One controller per component; abort on unmount removes every listener registered with its signal." },
  { q: "{ passive: true } on scroll/touch listeners…", options: ["Ignores events", "Promises you won't preventDefault — the browser scrolls without waiting for your JS", "Runs them later"], answer: 1,
    explain: "Perceptible scroll-smoothness win on mobile; browsers default it on some events for this reason." },
  { q: "IntersectionObserver replaces scroll-position math for…", options: ["Nothing", "Visibility detection: lazy-loading, infinite scroll, analytics impressions, nav highlighting", "Resizing"], answer: 1,
    explain: "Async and off-main-thread-ish vs scroll handlers firing getBoundingClientRect per frame." },
  { q: "e.target vs e.currentTarget:", options: ["Same node", "target = the actual click origin; currentTarget = the element THIS listener is attached to", "currentTarget is deprecated"], answer: 1,
    explain: "Inside delegated handlers, target is the row clicked; currentTarget is the table." },
  { q: "A WebSocket closes with code 1006. A robust client should…", options: ["Reconnect immediately in a loop", "Treat it as an unexpected drop: reconnect with exponential backoff + JITTER, then resync missed state", "Never reconnect — 1006 is fatal"], answer: 1,
    explain: "1006 = died without a close frame (network/proxy/server crash). Jitter prevents the thundering herd of synchronized retries; an intentional-close flag suppresses reconnect on logout." },
  { q: "input vs change events on a text field:", options: ["Identical", "input fires per keystroke; change fires on commit (blur/Enter)", "change is per-key"], answer: 1,
    explain: "Live search → input (debounced); validation-on-leave → change/blur." },
  { q: "element.closest(sel) walks…", options: ["Down into children", "UP through ancestors (including itself) to the first match", "Both directions"], answer: 1,
    explain: "The delegation workhorse: from the clicked icon up to the row/button that owns the action." },
  { q: "MutationObserver is for…", options: ["Mutating elements", "Reacting to DOM changes (third-party widgets, embeds) — with disconnect() to avoid leaks", "Form validation"], answer: 1,
    explain: "Watching what you don't control; overuse on broad subtrees is a performance smell." },
  { q: "WebSocket apps need app-level heartbeats (ping/pong ~30s) because…", options: ["The protocol requires it", "Half-dead connections look alive for minutes, and idle proxies silently kill quiet sockets — TCP keepalive won't save you", "It speeds up messages"], answer: 1,
    explain: "TCP keepalive defaults are hours and unreachable from browser JS; proxies commonly cut idle connections ~60s. A missed pong = bounded-time dead-connection detection → reconnect." },
  { q: "classList.toggle('open', isOpen) does…", options: ["Toggles randomly", "Adds when isOpen is true, removes when false — the conditional second argument", "Errors on booleans"], answer: 1,
    explain: "Cleaner than if/else add/remove pairs scattered around." },
  { q: "localStorage vs sessionStorage vs cookies:", options: ["Interchangeable", "localStorage persists per-origin; sessionStorage per-tab; cookies go to the SERVER on every request", "Cookies are biggest"], answer: 1,
    explain: "Auth tokens: HttpOnly cookies (JS can't read them). Storage is synchronous — don't hammer it in loops." },
  { q: "requestAnimationFrame is the right tool for…", options: ["API polling", "Visual updates synced to the render cycle — smooth animations/measurements", "Heavy computation"], answer: 1,
    explain: "Runs before next paint (~60fps, pauses in background tabs). Computation belongs in Workers." }
]},

{ title: "Quiz 5 · Async: Promises, await & the Event Loop",
  desc: "Promise states, combinators, error flows, microtasks, ordering",
  questions: [
  { q: "A Promise's states are…", options: ["open/closed", "pending → fulfilled | rejected — settled once, permanently", "async/sync"], answer: 1,
    explain: "Settling is one-way and single-shot; extra resolve/reject calls are ignored." },
  { q: "fetch() rejects its promise when…", options: ["HTTP 404/500", "Network failure only — HTTP errors resolve with ok:false; check res.ok yourself", "Invalid JSON"], answer: 1,
    explain: "The most-forgotten line in JS: if (!res.ok) throw new Error(`HTTP ${res.status}`)." },
  { q: "Three independent fetches — fastest correct pattern:", options: ["await a; await b; await c", "const [a,b,c] = await Promise.all([...]) — total time = the slowest, not the sum", "Nested .then chains"], answer: 1,
    explain: "Sequential awaits on independent work is the #1 async performance bug in code review." },
  { q: "Promise.all rejects…", options: ["Never", "Fast — on the FIRST rejection; use allSettled when partial success is acceptable", "After all settle"], answer: 1,
    explain: "allSettled returns [{status:'fulfilled', value}|{status:'rejected', reason}] for every input." },
  { q: "Promise.race([fetchData(), timeout(5000)]) implements…", options: ["Load balancing", "A timeout — first to SETTLE wins (AbortSignal.timeout is the modern fetch version)", "Retries"], answer: 1,
    explain: "race settles with the first settle (either way); any() waits for the first FULFILLMENT." },
  { q: "console order of: log(1); setTimeout(()=>log(2)); Promise.resolve().then(()=>log(3)); log(4)", options: ["1 4 3 2", "1 4 2 3", "1 2 3 4"], answer: 0,
    explain: "Script runs (1,4) → microtasks drain (3) → next macrotask (2). Microtasks ALWAYS beat waiting macrotasks." },
  { q: "await literally does what to the surrounding function?", options: ["Blocks the thread", "Pauses THE ASYNC FUNCTION, yields the thread, resumes via the microtask queue", "Spawns a thread"], answer: 1,
    explain: "Everything after await is effectively a .then callback — the a c b ordering question follows directly." },
  { q: "try/catch fails to catch savePrefs() (no await) because…", options: ["catch is broken", "The rejection happens AFTER the try block exits — un-awaited promises escape it", "fetch can't throw"], answer: 1,
    explain: "Fire-and-forget needs .catch attached, or await it. Unhandled rejections surface as global errors." },
  { q: "An async function ALWAYS returns…", options: ["Its literal value", "A Promise — return x resolves it; throw rejects it", "undefined"], answer: 1,
    explain: "Even async () => 5 returns Promise<5>; callers must await or .then." },
  { q: "Sequential vs parallel loops with await:", options: ["forEach handles both", "for…of + await = sequential; Promise.all(arr.map(...)) = parallel; pick by dependency", "Always parallel"], answer: 1,
    explain: "Rate-limited APIs sometimes NEED sequential (or a concurrency-pool like p-limit) — deliberate choice, not accident." },
  { q: "AbortController with fetch solves…", options: ["Slow servers", "Cancelling stale requests (user typed a new query, navigated away) — preventing stale-response races", "Retries"], answer: 1,
    explain: "Without cancellation, an older slower search response can overwrite a newer one — the classic search-box bug." },
  { q: "A microtask loop that queues itself (then(() => queue again))…", options: ["Is throttled by the browser", "Starves rendering FOREVER — microtasks drain completely before paint", "Runs at 60fps"], answer: 1,
    explain: "Worse than setTimeout loops, which at least let frames through between macrotasks." },
  { q: "setTimeout(fn, 0) actually means…", options: ["Immediately", "Next macrotask at the earliest (~4ms clamp, later if busy) — never use timers for ordering correctness", "Before promises"], answer: 1,
    explain: "queueMicrotask exists for 'right after this, before anything else'; timers are for TIME." },
  { q: "Retry with exponential backoff looks like…", options: ["while(true) fetch", "for attempt i: try/return; catch: await delay(base * 2**i (+ jitter))", "Promise.race of 5 fetches"], answer: 1,
    explain: "Backoff + jitter is how production clients avoid stampeding a recovering server (ties to the System Design track)." },
  { q: "Promise.any([mirror1(), mirror2()]) resolves with…", options: ["Both results", "The first FULFILLMENT — rejections are ignored unless all reject (AggregateError)", "The fastest settle"], answer: 1,
    explain: "Redundant sources / mirror racing. race would fail fast if the first settle is a rejection." },
  { q: "Top-level await is available…", options: ["Everywhere", "In ES MODULES — and it delays dependent modules until resolved", "Only in Node"], answer: 1,
    explain: "Handy for config/init; overuse serializes your module graph's startup." },
  { q: "The 'async waterfall' code smell is…", options: ["Using await at all", "Sequential awaits on INDEPENDENT operations — latency adds up needlessly", "Too many .then"], answer: 1,
    explain: "Spot it in review: three awaits, no data dependency → Promise.all. 900ms becomes 300ms." },
  { q: "unhandledrejection listeners are for…", options: ["Fixing bugs automatically", "Last-resort telemetry (report to Sentry) — not a substitute for local handling", "Silencing errors"], answer: 1,
    explain: "Pair with window 'error'. Log loudly, fix the source; never treat global handlers as control flow." },
  { q: "Node's process.nextTick vs microtasks:", options: ["Identical", "nextTick runs even BEFORE promise microtasks — Node-specific priority queue", "It's a macrotask"], answer: 1,
    explain: "The classic Node follow-up. Browser rule stays: after each callback, microtasks drain to empty." },
  { q: "Converting a callback API to promises uses…", options: ["async keyword on it", "new Promise((resolve, reject) => legacyFn(args, (err, data) => err ? reject(err) : resolve(data))) — or util.promisify", "await directly"], answer: 1,
    explain: "The 'promisification' pattern — bridging Node-style callbacks into async/await code." }
]}
);
