// javascript quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Prototypes, Classes & Modules",
  desc: "Prototype chain, class syntax, private fields, ESM, tooling",
  questions: [
  { q: "Property lookup on an object that lacks the property…", options: ["Returns null", "Walks UP the prototype chain until found or the chain ends (→ undefined)", "Throws"], answer: 1,
    explain: "Delegation, not copying: [1,2].map exists because arrays delegate to Array.prototype." },
  { q: "class methods are stored…", options: ["Once, on ClassName.prototype — shared by all instances", "Copied onto every instance", "In a registry"], answer: 0,
    explain: "A thousand instances share one greet function via the chain — memory efficiency by design." },
  { q: "new Fn() does what four things?", options: ["Just calls Fn", "Creates an object linked to Fn.prototype, binds this to it, runs the body, returns the object (unless an object is explicitly returned)", "Clones Fn"], answer: 1,
    explain: "Implementing 'myNew' from these four steps is a standard interview exercise." },
  { q: "#balance in a class is…", options: ["Truly private — enforced by the language, inaccessible outside (SyntaxError)", "A convention like _balance", "A comment"], answer: 0,
    explain: "Unlike the underscore convention, #fields don't exist to outside code at all." },
  { q: "In a subclass constructor, before using this you must…", options: ["Call this.init()", "Call super(...) — the parent constructor creates the object", "Nothing"], answer: 1,
    explain: "ReferenceError otherwise: derived constructors don't own the instance until super returns it." },
  { q: "The senior stance on deep inheritance hierarchies:", options: ["The deeper the better", "Prefer composition — base-class changes ripple through every subclass; JS ecosystems moved to functions + composition", "Required for OOP"], answer: 1,
    explain: "React's class→hooks migration is the era-defining example. Classes still shine for services/models/errors." },
  { q: "Object.keys(obj) vs for…in:", options: ["Identical", "keys → OWN enumerable properties; for…in ALSO walks inherited ones", "for…in is sorted"], answer: 1,
    explain: "Own-vs-inherited is the distinction; Object.hasOwn(obj, k) is the modern check." },
  { q: "Mutating Array.prototype in app code is…", options: ["Faster", "A handy extension point", "Forbidden — global collisions and future-spec conflicts (SmooshGate!) — write utility functions"], answer: 2,
    explain: "TC39 had to rename flatten→flat because a library had squatted the name globally. Don't be that library." },
  { q: "ES module imports are…", options: ["Copies of values", "Lazy by default", "Live, hoisted, static bindings — enabling tree-shaking and cycle tolerance"], answer: 2,
    explain: "Static structure = bundlers can prove what's unused and drop it. CommonJS require is dynamic — none of that." },
  { q: "A module imported by 5 files runs…", options: ["Once — modules are singletons; everyone shares the instance", "5 times", "Per import syntax"], answer: 0,
    explain: "Module-level state is shared state; deliberate for caches, accidental for bugs." },
  { q: "Dynamic import('./charts.js')…", options: ["Returns a Promise of the module — THE code-splitting point for lazy features", "Blocks parsing", "Is invalid ESM"], answer: 0,
    explain: "Bundlers split chunks exactly at dynamic imports; heavy features load on demand." },
  { q: "package-lock.json should be…", options: ["Committed — it pins the exact dependency tree; npm ci reproduces it in CI", "Deleted on conflicts", "Git-ignored"], answer: 0,
    explain: "'Works on my machine' is usually a lockfile-drift story. npm ci, never npm install, in pipelines." },
  { q: "dependencies vs devDependencies:", options: ["Style choice", "Alphabetical split", "Runtime-shipped vs build/test-only — misplacement bloats production installs"], answer: 2,
    explain: "Server deploys install --omit=dev; a test runner in dependencies rides along to production." },
  { q: "\"^3.23.0\" in package.json allows…", options: ["Only 3.23.0", "Any 3.x ≥ 3.23.0 (same major) — the lockfile pins the actual choice", "Any version"], answer: 1,
    explain: "Semver ranges express tolerance; major bumps (4.x) are breaking by convention and excluded." },
  { q: "Tree-shaking removes…", options: ["Comments", "Unused EXPORTS, provable via static ESM imports — side-effectful modules resist it", "Whitespace"], answer: 1,
    explain: "import { one } from 'lib' keeps one function; require('lib') keeps everything." },
  { q: "The standard 2026 frontend toolchain quartet is…", options: ["Vite (build/dev) · ESLint (bugs) · Prettier (format) · Vitest/Jest (tests)", "Webpack only", "Grunt/Bower/JSHint/QUnit"], answer: 0,
    explain: "Plus husky/lint-staged so it all runs pre-commit — style debates end mechanically." },
  { q: "Symbol.iterator on a class enables…", options: ["for…of / spread / destructuring over your object — the iteration protocol", "JSON support", "Private fields"], answer: 0,
    explain: "*[Symbol.iterator]() { yield … } — your TimeRange iterates like an array." },
  { q: "getter syntax get balance() { … } is invoked by…", options: ["Only internally", "obj.balance() — as a method", "obj.balance — property READ syntax running code"], answer: 2,
    explain: "Computed properties reading like fields; setters guard writes. Overusing hidden computation in getters surprises maintainers." },
  { q: "static methods (Account.from(json)) live on…", options: ["The class itself — factories, registries, namespacing related helpers", "The prototype chain of instances", "Instances"], answer: 0,
    explain: "Instances don't see them; that's the point — they're about the TYPE, not an object." },
  { q: "CommonJS (require/module.exports) in 2026 is…", options: ["Legacy-but-everywhere: recognize and interoperate, write new code as ESM", "Removed from Node", "The recommended style"], answer: 0,
    explain: "Node supports both; the ecosystem's default direction (and packages' \"type\": \"module\") is ESM." },
]},
{ title: "Quiz 7 · Event Loop, Generators & Iterators",
  desc: "Task queues, rendering, ordering puzzles, function*, yield, async iteration",
  questions: [
  { q: "The event loop's cycle is…", options: ["Parallel threads", "One macrotask → drain ALL microtasks → maybe render → repeat", "Random scheduling"], answer: 1,
    explain: "The single model that answers every 'what logs first' question." },
  { q: "Microtasks include…", options: ["Promise .then/await continuations and queueMicrotask", "click handlers", "setTimeout callbacks"], answer: 0,
    explain: "Macrotasks: timers, I/O, UI events. Microtasks queued DURING draining also run before anything else." },
  { q: "async function f(){ log('a'); await null; log('b') } f(); log('c') prints…", options: ["a b c", "c a b", "a c b — await yields at that line; the rest is a microtask"], answer: 2,
    explain: "await null still suspends — the continuation goes to the microtask queue behind the running script." },
  { q: "A 200ms synchronous loop causes…", options: ["Only slow logs", "Nothing visible", "Frozen clicks, scrolling, AND rendering — one thread runs it all"], answer: 2,
    explain: "Under ~16ms per task keeps 60fps; 50ms+ tasks damage INP. Chunk or offload." },
  { q: "Rendering happens…", options: ["After every line", "Between macrotasks (not between microtasks) — starve the loop, freeze the paint", "On a render thread free of JS"], answer: 1,
    explain: "Why microtask-recursion is worse than setTimeout-recursion: frames never get a turn." },
  { q: "To paint a spinner BEFORE heavy work starts:", options: ["Use alert", "Just set spinner.hidden=false and loop", "Show it, then yield (setTimeout 0 / requestAnimationFrame chain) before crunching"], answer: 2,
    explain: "DOM writes render only when the loop breathes; back-to-back write+crunch paints nothing." },
  { q: "Chunking long work with await new Promise(r => setTimeout(r)) every N items…", options: ["Parallelizes it", "Slows it pointlessly", "Lets input/rendering interleave — responsive UI during processing (scheduler.yield is the emerging API)"], answer: 2,
    explain: "Cooperative scheduling on one thread. True parallelism = Workers (next quiz)." },
  { q: "function* / yield gives you…", options: ["Async functions", "Threads", "A PAUSABLE function returning an iterator — state persists between .next() calls"], answer: 2,
    explain: "A resumable stack frame: local variables survive across yields — the generator superpower." },
  { q: "Infinite generators (while(true) yield id++) are safe because…", options: ["They're not", "Laziness — values compute only when pulled; take(3) pulls three and stops", "The GC stops them"], answer: 1,
    explain: "Laziness turns 'infinite' into 'as many as consumed'." },
  { q: "yield* other() means…", options: ["Parallel yield", "DELEGATE — yield every value from another iterable/generator inline", "Multiply yields"], answer: 1,
    explain: "Generator composition: pipelines assembled from small generators." },
  { q: "for await (const user of fetchAllUsers()) consumes…", options: ["Arrays only", "Promises in parallel", "An ASYNC iterator — pagination/streams as one clean sequence, breakable early"], answer: 2,
    explain: "break stops fetching remaining pages entirely — laziness + async = efficient API consumption." },
  { q: "async/await under the hood is essentially…", options: ["Threads", "Generators + a promise-driving runner — await ≈ yield to the scheduler", "eval magic"], answer: 1,
    explain: "Pre-2017 code literally used co(function*(){ yield fetch(...) }). The syntax standardized the pattern." },
  { q: "gen.return()/gen.throw() let consumers…", options: ["Restart it", "Do nothing", "Inject early termination or errors INTO the paused generator — triggering its finally cleanup"], answer: 2,
    explain: "How break in for…of/for-await propagates cleanup upstream (closing file handles, aborting fetches)." },
  { q: "Node's loop differs from the browser's by…", options: ["Phases (timers → I/O → check/setImmediate) plus process.nextTick ahead of microtasks", "No differences", "Having no microtasks"], answer: 0,
    explain: "setImmediate vs setTimeout(0) ordering is the classic Node interview curveball." },
  { q: "Custom iterables implement…", options: [".forEach", ".map", "[Symbol.iterator]() returning {next() → {value, done}}"], answer: 2,
    explain: "That protocol is all for…of, spread, and destructuring ever call." },
  { q: "requestAnimationFrame callbacks run…", options: ["Before the next paint (~60fps, throttled in background tabs)", "After images load", "Every ms"], answer: 0,
    explain: "The hook for visual updates; NOT for polling or computation." },
  { q: "Two awaited fetches in sequence when independent cost…", options: ["a + b — the waterfall; Promise.all makes it max(a, b)", "max(a, b)", "Nothing extra"], answer: 0,
    explain: "The event-loop lens on the async-waterfall bug: each await parks the function for a full round trip." },
  { q: "queueMicrotask(fn) exists for…", options: ["'Right after the current code, before ANYTHING else' — without hacky Promise.resolve().then", "Background work", "Slower timers"], answer: 0,
    explain: "Batching/deduping state flushes — the tool frameworks use internally." },
  { q: "Async generators (async function*) combine…", options: ["Threads and locks", "yield's laziness with await's asynchrony — paginated APIs, event streams, file readers", "Workers and promises"], answer: 1,
    explain: "The production face of generators: yield* items per page, await the next page, consumer never knows." },
  { q: "A truly CPU-bound 5-second computation belongs…", options: ["Chunked on the main thread", "In a Web Worker — chunking keeps UI alive but still burns the only UI thread for 5s total", "In a microtask"], answer: 1,
    explain: "Chunking = responsive-but-slow; Worker = responsive AND the main thread free. Know which trade you're making." },
]},
{ title: "Quiz 8 · Errors, TypeScript & Robustness",
  desc: "Error patterns, custom errors, TS types, narrowing, strict mode",
  questions: [
  { q: "throw new Error('x') beats throw 'x' because…", options: ["Error carries .stack (and .cause) — string throws are undebuggable in production", "Strings are slower", "Strings can't be caught"], answer: 0,
    explain: "A stack trace is the difference between a 5-minute fix and an afternoon." },
  { q: "new Error('Order 42 failed', { cause: err }) provides…", options: ["Deduplication", "An error CHAIN — business context on top, root cause preserved underneath", "Retry logic"], answer: 1,
    explain: "Log the top error, see the whole story. Re-throwing without cause destroys the trail." },
  { q: "In tests, mocking belongs at…", options: ["Nowhere, mocks are bad", "Every import — isolate everything", "PROCESS BOUNDARIES (network, db, clock, random) — mocking your own modules freezes the call graph"], answer: 2,
    explain: "Over-mocked suites break on every refactor while real bugs in the mocked-out code sail through. Dependency injection beats module-mock machinery." },
  { q: "The right place to catch is…", options: ["Every function", "main() only", "Where you can DO something (retry, fallback, UI) — else let it bubble to a logging boundary"], answer: 2,
    explain: "Catch-log-rethrow at every layer = 5 duplicate logs per incident. Handle or pass, never both-everywhere." },
  { q: "Custom error taxonomy (ValidationError, NotFoundError extends AppError) enables…", options: ["instanceof-based handling at boundaries: 400 vs 404 vs 500, field UI vs toast vs page", "Faster throws", "Shorter messages"], answer: 0,
    explain: "Type-dispatched error handling is how services map failures to responses coherently." },
  { q: "Errors-as-values ({ok:true,value}|{ok:false,error}) suits…", options: ["EXPECTED failures (parse, validation) — visible in the flow; throws stay for bugs/unexpected states", "All errors", "Only Go programs"], answer: 0,
    explain: "Deliberately mixing both styles — results for planned failure, exceptions for surprises — is the senior move." },
  { q: "In TypeScript, annotate…", options: ["BOUNDARIES (params, returns, APIs) — let inference handle locals", "Nothing, TS guesses", "Every variable"], answer: 0,
    explain: "const count = 3 needs no : number. Signatures are contracts; locals are noise." },
  { q: "role: \"admin\" | \"viewer\" (literal union) buys you…", options: ["Slower builds", "Typo-proof enums at compile time with zero runtime cost", "Runtime checks"], answer: 1,
    explain: "role=\"admn\" is now a red squiggle, not a production incident. Discriminated unions extend this to whole shapes." },
  { q: "unknown vs any for res.json():", options: ["unknown forces validation before use; any switches the checker OFF and spreads through everything it touches", "any is stricter", "Same thing"], answer: 0,
    explain: "Every any is a hole in the ship. unknown + zod parse = typed AND runtime-checked." },
  { q: "Types are erased at runtime, therefore…", options: ["External data (APIs, forms, JSON) needs RUNTIME validation — zod/valibot generate both", "They're useless", "TS validates JSON"], answer: 0,
    explain: "interface User cannot check what the server actually sent; schema validation can — one schema, both worlds." },
  { q: "Narrowing means…", options: ["Minification", "Smaller files", "TS following your runtime checks (typeof, in, instanceof, literal ===) to refine types per branch"], answer: 2,
    explain: "if (r.status === 'ok') → r.data exists in this branch — autocomplete proves the checker followed you." },
  { q: "strict: true matters most for…", options: ["strictNullChecks — null/undefined become visible in types, killing the billion-dollar mistake at compile time", "Style", "Speed"], answer: 0,
    explain: "string | undefined must be handled before use. Non-negotiable on new projects." },
  { q: "Partial<User>, Pick, Omit, Record are…", options: ["Utility TYPES deriving new shapes from existing ones — update payloads, subsets, dictionaries", "Runtime helpers", "Decorators"], answer: 0,
    explain: "Derive, don't duplicate: interfaces stay single-source-of-truth." },
  { q: "window 'error' + 'unhandledrejection' handlers should…", options: ["Report to telemetry (Sentry etc.) as last-resort visibility — not act as control flow", "Reload the page", "Fix state and continue"], answer: 0,
    explain: "Global handlers are smoke detectors, not sprinkler systems." },
  { q: "A good production error message contains…", options: ["'Something went wrong'", "What failed, for which entity, and actionable context: 'Invoice #4211 send failed (timeout after 3 retries)'", "The stack only"], answer: 1,
    explain: "Your 3am on-call self is the audience — write for them." },
  { q: "finally blocks run…", options: ["Only on success", "Only on errors", "On success, throw, AND early return — the cleanup guarantee (locks, spinners, handles)"], answer: 2,
    explain: "spinner.hide() in finally survives every exit path; after the try it survives only the happy one." },
  { q: "err instanceof MyError can fail unexpectedly when…", options: ["err is null", "Never", "Errors cross realms (iframes) or class identity differs (duplicate bundles) — .name/.code checks are hardier at boundaries"], answer: 2,
    explain: "The subtle production gotcha behind 'instanceof stopped working after the bundler change'." },
  { q: "satisfies (config satisfies Config) gives you…", options: ["A cast", "Shape validation WITHOUT widening — literal types preserved for downstream inference", "Runtime checks"], answer: 1,
    explain: "The modern alternative to 'as Config', which silences instead of checks." },
  { q: "expect({a:1}).toBe({a:1}) fails but toEqual passes because…", options: ["toBe is deprecated", "toBe checks IDENTITY (same reference); toEqual checks deep STRUCTURE — two fresh objects are equal, never identical", "toEqual ignores keys"], answer: 1,
    explain: "toBe for primitives/same-object checks, toEqual for data, toBeCloseTo for floats (0.1+0.2 !== 0.3)." },
  { q: "it('rejects', () => { expect(load(-1)).rejects.toThrow(); }) passes even when load() is broken because…", options: ["The rejects matcher returns a PROMISE that's never awaited — the test ends before the assertion runs", "rejects is unreliable", "toThrow needs a string"], answer: 0,
    explain: "The classic async false positive. Fix: async test + await expect(...).rejects.toThrow(); expect.assertions(n) guards try/catch styles." },
]},
{ title: "Quiz 9 · Memory, Workers & Security",
  desc: "GC, leaks, profiling, Web Workers, XSS sinks, supply chain",
  questions: [
  { q: "The garbage collector frees…", options: ["Whatever is UNREACHABLE from roots (globals, stack, live closures) — leaks are accidental reachability", "Old variables", "Everything on navigation"], answer: 0,
    explain: "Mark & sweep: a leak is a path you forgot exists — the Retainers panel shows exactly that path." },
  { q: "The four classic leak sources are…", options: ["Forgotten timers/listeners, detached DOM references, unbounded caches, accidental globals/accumulators", "Strings, numbers, booleans, null", "CSS, HTML, JSON, SVG"], answer: 0,
    explain: "All four are 'still reachable by accident'. Component cleanup (AbortController, clearInterval) addresses the first two." },
  { q: "setInterval(() => render(bigData), 1000) never cleared keeps…", options: ["Just the interval", "Its closure — bigData and everything it references — alive FOREVER", "Only 1KB"], answer: 1,
    explain: "Timers are GC roots; their closures pin whole object graphs. The unmount-cleanup discipline exists for this." },
  { q: "A WeakMap for DOM-node metadata beats a Map because…", options: ["It's iterable", "It's faster", "Entries evaporate when the node becomes unreachable — impossible to leak through the cache"], answer: 2,
    explain: "Weak references don't count as reachability. Not iterable BY DESIGN (contents may vanish anytime)." },
  { q: "The heap-snapshot leak workflow is…", options: ["Use console.log", "One snapshot, read it", "Snapshot A → repeat the suspect action 5× → snapshot B → compare growth, filter 'Detached', read Retainers"], answer: 2,
    explain: "Sawtooth memory = healthy churn; an ever-rising staircase = leak. The 5× makes growth unmistakable." },
  { q: "Web Workers exist because…", options: ["CPU-bound work (parsing MBs, image processing) blocks the ONLY UI thread — workers are real parallel threads", "fetch is slow", "They're required for modules"], answer: 0,
    explain: "async doesn't move computation; it just reorders waiting. Compute needs another thread." },
  { q: "postMessage transfers data by…", options: ["Shared reference", "Structured CLONE (copy) — or zero-copy transfer of ArrayBuffers via the transfer list", "JSON strings"], answer: 1,
    explain: "worker.postMessage(buf, [buf]) moves 64MB in ~0ms, emptying the sender's buffer — know both modes." },
  { q: "Workers cannot access…", options: ["fetch and timers", "Promises", "The DOM and window — results come back via messages; DOM writes stay on main"], answer: 2,
    explain: "The no-shared-state design is deliberate: message passing avoids the entire data-race bug class." },
  { q: "Worker overhead means…", options: ["Never use workers", "Always use workers", "Tasks under ~30-50ms aren't worth the postMessage round trip — measure, then offload the repeat offenders"], answer: 2,
    explain: "Heuristic: recurring main-thread tasks >50ms (visible in the Performance panel) are worker candidates." },
  { q: "A Service Worker differs from a dedicated Worker by being…", options: ["Faster", "Deprecated", "A network PROXY with its own lifecycle — offline caching, push — not a compute thread"], answer: 2,
    explain: "Three siblings: dedicated (compute), shared (cross-tab), service (network/PWA). Different jobs." },
  { q: "The eval-family sinks to never feed external input are…", options: ["eval, new Function, setTimeout(string), plus innerHTML-style HTML sinks", "JSON.parse, structuredClone", "console.log"], answer: 0,
    explain: "Code-from-strings and markup-from-strings are the two injection families; both have safe alternatives." },
  { q: "Prototype pollution attacks work by…", options: ["CSS injection", "Malicious __proto__/constructor keys in merged JSON landing on Object.prototype — every object 'gains' attacker properties", "Slow scripts"], answer: 1,
    explain: "Defenses: skip magic keys in merges, Object.create(null) targets, audited merge libraries." },
  { q: "Tokens in localStorage vs HttpOnly cookies:", options: ["localStorage is safer", "Any XSS can read localStorage; HttpOnly cookies are invisible to JS entirely", "No difference"], answer: 1,
    explain: "Session theft off the table even under successful XSS — the layered-defense mindset." },
  { q: "Your real attack surface is mostly…", options: ["The CDN", "node_modules — hijacked packages (event-stream, ua-parser-js) run in every user's browser", "Your own code"], answer: 1,
    explain: "npm audit, lockfiles + npm ci, overrides for transitive pins, provenance — CI-enforced." },
  { q: "postMessage listeners must…", options: ["Check e.origin AND validate the payload shape before acting", "Trust same-tab messages", "Reply immediately"], answer: 0,
    explain: "Any page can postMessage your window. Origin check + schema parse — both directions (never send secrets to '*')." },
  { q: "SharedArrayBuffer + Atomics enable…", options: ["TRUE shared memory between threads (WASM multithreading) — gated behind cross-origin isolation headers", "Faster JSON", "Bigger arrays"], answer: 0,
    explain: "The deep end: app code rarely needs it; know it exists and why COOP/COEP gate it (Spectre)." },
  { q: "API keys bundled into frontend JS are…", options: ["Encrypted by HTTPS", "Safe if minified", "PUBLIC — anyone can read the bundle; powerful keys live server-side, browsers get scoped short-lived tokens"], answer: 2,
    explain: "Minification is not encryption. The proxy-your-secrets pattern is non-negotiable." },
  { q: "el.setAttribute('href', userUrl) needs…", options: ["encodeURIComponent", "Nothing — attributes are safe", "Scheme validation — javascript: URLs execute on click"], answer: 2,
    explain: "URL sanitization (http/https/mailto allowlist) is separate from HTML escaping — both required." },
  { q: "FinalizationRegistry/WeakRef in app code are…", options: ["Almost always a design smell — GC timing is non-deterministic; explicit lifecycle beats finalizers", "Required for workers", "Everyday tools"], answer: 0,
    explain: "Exotic interop aside, if correctness depends on WHEN GC runs, the design is broken." },
  { q: "Comlink-style wrappers improve workers by…", options: ["Making them faster", "Adding DOM access", "Turning postMessage plumbing into awaitable function calls — ergonomics, same mechanics"], answer: 2,
    explain: "await parseInWorker(csv) reads like local code; the message protocol hides underneath." },
]},
{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "console.log(a); var a = 1; vs console.log(b); let b = 1;", options: ["Both print 1", "Both throw", "undefined vs ReferenceError (TDZ) — var hoists initialized-to-undefined, let hoists uninitialized"], answer: 2,
    explain: "One question, three concepts: hoisting, TDZ, var vs let. A screening classic." },
  { q: "[1,2,3].map(parseInt) returns…", options: ["[1,2,3]", "[1,2,3] as strings", "[1, NaN, NaN] — map passes (value, INDEX); parseInt reads index as radix"], answer: 2,
    explain: "parseInt('2', 1) is NaN. Fix: .map(Number) or .map(x => parseInt(x, 10)). Callback-arity awareness." },
  { q: "Search box: responses for 'ja' arrive AFTER 'java', showing stale results. Correct fix:", options: ["AbortController canceling the previous request per keystroke (debounce helps but doesn't fix ordering)", "Longer debounce", "Faster server"], answer: 0,
    explain: "It's a race, not a speed problem. Cancel stale requests; optionally ignore out-of-order responses by tag." },
  { q: "A dashboard tab grows to 2GB over a day. First diagnostic:", options: ["Disable JS", "Add more RAM", "Heap snapshots before/after repeated flows; filter Detached; read Retainers paths"], answer: 2,
    explain: "Leak triage is a workflow, not a guess. Usual suspects: uncleared intervals, listeners, unbounded caches." },
  { q: "Clicking any row's ⭐ triggers the ROW opening too. The precise fix is…", options: ["preventDefault", "z-index", "stopPropagation on the star (fine) or better: delegation checking e.target.closest scope"], answer: 2,
    explain: "Two handlers, one bubbling path — resolve deliberately. closest-based delegation naturally separates concerns." },
  { q: "for (const [i, x] of items.entries()) is preferred over forEach for async because…", options: ["It's faster", "await works properly inside for…of; forEach ignores promises", "forEach is deprecated"], answer: 1,
    explain: "Async control flow demands real loops (or Promise.all on mapped promises)." },
  { q: "Object.freeze({ a: { b: 1 } }) — obj.a.b = 2:", options: ["Succeeds — freeze is SHALLOW; deep-freeze requires recursion", "Silently ignored in all modes", "Throws always"], answer: 0,
    explain: "Shallowness strikes again: spread copies, freeze, everything. (Top-level writes throw only in strict mode.)" },
  { q: "The team ships a 3MB bundle. The highest-leverage fix is…", options: ["HTTP/3", "A faster framework", "Code-splitting on routes/features via dynamic import + auditing the bundle visualizer"], answer: 2,
    explain: "Ship less JS: hydration cost, parse cost, INP all scale with bytes. Measure first (visualizer), split at boundaries." },
  { q: "await inside a top-level for…of calling an API 500 times takes 8 min. The 30-second version:", options: ["Batch with Promise.all over chunks (concurrency pool) respecting rate limits", "setTimeout between calls", "Remove await"], answer: 0,
    explain: "Sequential→parallel with bounded concurrency (e.g., 10 at a time) — the production-grade middle ground." },
  { q: "JSON.parse(JSON.stringify(state)) corrupted your Dates and dropped a method. Modern fix:", options: ["structuredClone(state) for data (Dates/Maps survive); methods signal state should be plain data anyway", "Custom reviver everywhere", "Lodash always"], answer: 0,
    explain: "structuredClone still won't copy functions — state objects with methods are the deeper design smell." },
  { q: "typeof x === 'object' guards crash on null because…", options: ["null is undefined", "typeof is broken", "typeof null === 'object' — guard must be x !== null && typeof x === 'object'"], answer: 2,
    explain: "The 30-year-old bug appearing in real validation code — memorize the null-first guard." },
  { q: "Intl.NumberFormat/DateTimeFormat should replace…", options: ["Hand-rolled currency/date formatting — locale rules are NOT your string concatenations", "Nothing, too slow", "Only backend formatting"], answer: 0,
    explain: "1.234,56 € vs $1,234.56 vs ¥1,235 — the platform knows; your regex doesn't. Free, correct, fast." },
  { q: "A user reports the page freezes when pasting 200KB into a field with an 'input' handler doing regex highlighting. Fix path:", options: ["Debounce the handler + move highlighting off-thread (worker) or use CSS Custom Highlight API", "Bigger regex", "Block pasting"], answer: 0,
    explain: "Input storms × heavy sync work = INP death. Coalesce events, offload compute." },
  { q: "\"use strict\" is implicit in…", options: ["Nowhere anymore", "Only Node", "ES modules and class bodies — silent-failure sloppy mode is effectively legacy"], answer: 2,
    explain: "Assignments to undeclared variables throw, this is undefined in bare calls — strictness by default is why." },
  { q: "Feature-detecting an API (if ('IntersectionObserver' in window)) beats…", options: ["User-agent sniffing — capability, not identity; UA strings lie and freeze", "try/catch", "Nothing"], answer: 0,
    explain: "Progressive enhancement rests on capability checks; UA parsing is a maintenance tarpit." },
  { q: "Your unit test mutates a shared fixture array via sort(); later tests fail mysteriously. Lesson:", options: ["Jest bug", "Mutation strikes again — toSorted/copies in tests too; shared mutable fixtures are landmines", "Tests are flaky"], answer: 1,
    explain: "The mutating-methods table pays rent everywhere, including test suites." },
  { q: "Optional chaining EVERYWHERE (a?.b?.c?.d ?? fallback) is a smell because…", options: ["It's not — chain everything", "It's slow", "It hides broken invariants — if a.b must exist, crashing early beats silently computing with fallbacks"], answer: 2,
    explain: "?. at genuine optionality, loud failures at violated invariants. Defensive soup postpones bugs, doesn't fix them." },
  { q: "The interviewer asks you to implement Promise.all. The core is…", options: ["Recursion", "async/await magic", "A results array + completed counter; resolve when counter === length; reject on first error"], answer: 2,
    explain: "Index-stable results (results[i] = value), count settlements, one reject short-circuits. 10 lines, much signal." },
  { q: "React's useEffect cleanup returning () => controller.abort() maps to which vanilla concepts?", options: ["Hydration", "Listener/request lifecycle cleanup — the leak-prevention discipline, framework-flavored", "Virtual DOM"], answer: 1,
    explain: "Frameworks rename the fundamentals; the fundamentals grade the interview." },
  { q: "Three functions repeat if (type==='csv')…else if (type==='json')…else if (type==='xml')…. The refactor:", options: ["An abstract class hierarchy", "A switch statement", "Strategy pattern — a lookup object { csv: toCsv, json: toJson, xml: toXml }; adding a format = adding one entry"], answer: 2,
    explain: "JS idiom: first-class functions make strategy a lookup object, no interfaces needed. Each strategy is independently testable; the tested dispatcher never changes. 🏆" },
]},
);
