// Angular quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Routing & Guards",
  desc: "Route config, router-outlet, lazy loading, guard types",
  questions: [
  { q: "The Router maps…", options: ["Components to services", "URL paths to components", "Pipes to templates"], answer: 1,
    explain: "Via a routes configuration array." },
  { q: "<router-outlet /> marks…", options: ["A pipe location", "Where the matched route's component renders", "A service injection point"], answer: 1,
    explain: "The rendering placeholder." },
  { q: "The wildcard route (**) must be placed…", options: ["First", "Last in the routes array", "Anywhere"], answer: 1,
    explain: "Otherwise it swallows all other routes." },
  { q: "loadComponent / loadChildren enable…", options: ["Eager loading", "Lazy loading — code splits into on-demand chunks", "Server rendering"], answer: 1,
    explain: "Only downloaded when the route is visited." },
  { q: "The main performance benefit of lazy loading is…", options: ["Faster HTTP calls", "Smaller initial bundle / faster first load", "Better SEO"], answer: 1,
    explain: "Unvisited features aren't downloaded." },
  { q: "canActivate guards run…", options: ["After leaving a route", "Before entering a route (e.g., auth checks)", "Only on the root route"], answer: 1,
    explain: "Return true or a redirect UrlTree." },
  { q: "canDeactivate guards run…", options: ["Before entering", "Before LEAVING a route (e.g., unsaved changes)", "Never"], answer: 1,
    explain: "Confirmation before navigating away." },
  { q: "canActivateChild protects…", options: ["A single route", "An entire subtree of child routes at once", "Nothing"], answer: 1,
    explain: "Avoids repeating the guard on each child." },
  { q: "resolve guards are used to…", options: ["Block navigation forever", "Prefetch data before the component activates", "Style a route"], answer: 1,
    explain: "Avoids a flash of empty state." },
  { q: "Modern Angular guards are typically…", options: ["Classes only", "Plain functions (e.g., CanActivateFn) using inject()", "Pipes"], answer: 1,
    explain: "Functional guards, not class-based." },
  { q: "routerLink vs Router.navigate() are…", options: ["The same, no difference", "Declarative vs imperative navigation", "Unrelated to routing"], answer: 1,
    explain: "Template attribute vs code call." },
  { q: "routerLinkActive is used to…", options: ["Disable a link", "Highlight/style the currently active link", "Redirect"], answer: 1,
    explain: "Common nav-bar pattern." },
  { q: "Navigating from /products/1 to /products/2 typically…", options: ["Destroys and recreates the component", "Reuses the same component instance", "Throws an error"], answer: 1,
    explain: "Same route config, different param." },
  { q: "Reading a route param with a one-time snapshot…", options: ["Always stays fresh", "Goes stale on navigations that reuse the component", "Is the only option"], answer: 1,
    explain: "Use paramMap reactively (or toSignal it) instead." },
  { q: "canMatch guards run…", options: ["After matching", "Even BEFORE route matching decides which config to use", "Only on errors"], answer: 1,
    explain: "e.g., choosing between configs via a feature flag." },
  { q: "A guard returning a UrlTree (via router.parseUrl)…", options: ["Blocks navigation with no redirect", "Redirects the user elsewhere", "Crashes the app"], answer: 1,
    explain: "Common for unauthenticated redirects to /login." },
  { q: "Centralizing auth checks in a guard vs inside every component…", options: ["Is worse", "Avoids duplication and forgetting checks on new routes", "Makes no difference"], answer: 1,
    explain: "One place to enforce access control." },
  { q: "Route parameters are declared with…", options: ["A pipe", "A colon prefix, e.g. 'products/:id'", "@Input()"], answer: 1,
    explain: "Matches dynamic URL segments." },
  { q: "Standalone components made lazy loading…", options: ["Harder", "Simpler than the old NgModule-based approach", "Impossible"], answer: 1,
    explain: "Per-route/per-component loading, no module wrapper needed." },
  { q: "A route with no matching path falls through to…", options: ["The root route", "The wildcard (**) route if defined", "An error page automatically"], answer: 1,
    explain: "Define a NotFoundComponent for it." }
]},
{ title: "Quiz 7 · Reactive Forms",
  desc: "FormControl/Group/Array, validators, cross-field & async validation",
  questions: [
  { q: "In reactive forms, the source of truth for values/validation is…", options: ["The template/DOM", "The component class (explicit form model)", "CSS"], answer: 1,
    explain: "Unlike template-driven [(ngModel)] forms." },
  { q: "FormGroup represents…", options: ["A single input", "A named collection of controls", "A dynamic list"], answer: 1,
    explain: "An object shape of controls." },
  { q: "FormArray represents…", options: ["A fixed set of named controls", "A dynamic, indexed list of controls", "A single value"], answer: 1,
    explain: "For add/remove rows (e.g., phone numbers)." },
  { q: "FormBuilder is used to…", options: ["Validate HTTP calls", "Build FormGroup/FormControl/FormArray with less boilerplate", "Route requests"], answer: 1,
    explain: "A convenience service." },
  { q: "Reactive forms are more testable than template-driven forms because…", options: ["They use less code always", "You can test the form model directly without rendering the DOM", "They don't need validators"], answer: 1,
    explain: "The class-based model is directly assertable." },
  { q: "Cross-field validation (e.g., password match) belongs on…", options: ["Each individual control", "The parent FormGroup", "The template only"], answer: 1,
    explain: "A single control can't see another field's value." },
  { q: "A validator function returns…", options: ["A boolean only", "null (valid) or an error object", "A Promise always"], answer: 1,
    explain: "Sync validators are pure functions." },
  { q: "An async validator (e.g., 'is username taken?') returns…", options: ["A plain object", "An Observable or Promise", "Nothing"], answer: 1,
    explain: "For checks requiring a network call." },
  { q: "While an async validator resolves, the control's status is…", options: ["INVALID", "PENDING", "VALID"], answer: 1,
    explain: "Then updates to VALID/INVALID." },
  { q: "Showing validation errors before a field is touched is…", options: ["Good UX", "Bad UX — gate on control.touched", "Required by Angular"], answer: 1,
    explain: "Avoid errors on initial page load." },
  { q: "Combining debounceTime + distinctUntilChanged with an async validator prevents…", options: ["Nothing", "Firing a network request on every keystroke", "Form submission"], answer: 1,
    explain: "Wait for typing to pause; skip redundant checks." },
  { q: "[formGroup] and formControlName in a template…", options: ["Own their own state", "Bind to the form model defined in the class", "Are unrelated to reactive forms"], answer: 1,
    explain: "The template reflects the class-based model." },
  { q: "Dynamic forms (add/remove fields at runtime) are…", options: ["Awkward with template-driven forms, natural with reactive forms", "Equally easy in both", "Impossible in Angular"], answer: 1,
    explain: "FormArray handles this well." },
  { q: "form.markAllAsTouched() is typically called…", options: ["On page load", "On submit, to surface validation errors", "Never"], answer: 1,
    explain: "Reveals errors that were hidden until interaction." },
  { q: "valueChanges on a control is…", options: ["A one-time snapshot", "An Observable emitting on every value change", "A signal"], answer: 1,
    explain: "Can be piped with RxJS operators." },
  { q: "Mixing template-driven and reactive forms in one form is…", options: ["Recommended", "Confusing — pick one approach per form", "Required"], answer: 1,
    explain: "Conflicting sources of truth." },
  { q: "Rebuilding the entire form on every value change…", options: ["Is efficient", "Loses focus/performance — use patchValue/setValue instead", "Is required"], answer: 1,
    explain: "Update the existing model, don't recreate it." },
  { q: "Validators.required, Validators.email, Validators.minLength are…", options: ["Custom validators you must write", "Built-in Angular validators", "Pipes"], answer: 1,
    explain: "Ship with @angular/forms." },
  { q: "A FormGroup-level validator's second constructor argument is…", options: ["{ validators: fn }", "A template reference", "A pipe name"], answer: 1,
    explain: "Where cross-field validators are attached." },
  { q: "Reactive forms compose naturally with…", options: ["Nothing else", "RxJS (valueChanges is an Observable)", "Only synchronous code"], answer: 1,
    explain: "A key reason they scale better than template-driven forms." }
]},
{ title: "Quiz 8 · HttpClient & Interceptors",
  desc: "Observable-based HTTP, interceptor chains, immutable requests, RxJS patterns",
  questions: [
  { q: "HttpClient methods return…", options: ["Promises", "Observables (cold, lazy)", "Signals directly"], answer: 1,
    explain: "Nothing fires until subscribed." },
  { q: "Calling http.get() without subscribing…", options: ["Fires the request anyway", "Never actually sends the request", "Throws an error"], answer: 1,
    explain: "Cold Observables are lazy by design." },
  { q: "An interceptor is registered via…", options: ["@Component", "provideHttpClient(withInterceptors([...]))", "A pipe"], answer: 1,
    explain: "Applies to every request/response." },
  { q: "Interceptors are best compared to…", options: ["CSS", "Middleware — each can inspect/modify requests and responses", "Pipes"], answer: 1,
    explain: "A chain, like Express middleware." },
  { q: "A common interceptor use case is…", options: ["Styling components", "Adding auth headers to every request centrally", "Routing"], answer: 1,
    explain: "Avoids repeating logic at every call site." },
  { q: "HttpRequest objects are…", options: ["Mutable", "Immutable — modify via req.clone({...})", "Deleted after use"], answer: 1,
    explain: "Mirrors the immutable-update discipline elsewhere in Angular." },
  { q: "An error interceptor commonly uses…", options: ["ngOnInit", "catchError to detect a 401 and redirect", "A structural directive"], answer: 1,
    explain: "Centralized error handling." },
  { q: "switchMap in a typeahead search…", options: ["Runs all requests in parallel", "Cancels the previous in-flight request when a new one starts", "Queues requests in order"], answer: 1,
    explain: "Only the latest search term's result matters." },
  { q: "mergeMap for a search-as-you-type box risks…", options: ["Nothing", "A race condition where stale results overwrite fresh ones", "Faster results always"], answer: 1,
    explain: "No cancellation of in-flight requests." },
  { q: "toSignal() is used with HTTP to…", options: ["Cancel a request", "Bridge an HTTP Observable's latest value into a signal for templates", "Add headers"], answer: 1,
    explain: "Combines HttpClient with the signals model." },
  { q: "Interceptors can modify…", options: ["Only requests", "Both outgoing requests AND incoming responses/errors", "Neither"], answer: 1,
    explain: "next(req).pipe(...) lets you touch the response too." },
  { q: "The Observable-based HTTP model allows…", options: ["Nothing extra vs Promises", "Retry, cancel (unsubscribe), race, and combine before hitting the network", "Only single requests"], answer: 1,
    explain: "The composability payoff of using RxJS operators." },
  { q: "Forgetting to consume an HttpClient Observable results in…", options: ["An error", "The request silently never firing", "A default response"], answer: 1,
    explain: "A classic 'why didn't my API call fire' bug." },
  { q: "Interceptors registered with withInterceptors apply to…", options: ["One specific call", "EVERY request made through HttpClient", "Only GET requests"], answer: 1,
    explain: "Global, centralized hooks." },
  { q: "debounceTime before an HTTP search call is used to…", options: ["Speed up requests", "Wait for typing to pause before firing a request", "Cancel all requests"], answer: 1,
    explain: "Reduces request volume." },
  { q: "req.clone({ setHeaders: {...} }) is used because…", options: ["Headers can be set directly", "Requests are immutable — you must produce a new one", "It deletes the old request"], answer: 1,
    explain: "No direct mutation allowed." },
  { q: "A 401 response is commonly handled by…", options: ["Ignoring it", "An interceptor redirecting to a login page", "A custom pipe"], answer: 1,
    explain: "Centralized auth-failure handling." },
  { q: "For 'only the latest result matters' scenarios, prefer…", options: ["mergeMap", "switchMap", "concatMap"], answer: 1,
    explain: "Cancels stale in-flight requests." },
  { q: "HttpClient's laziness is fundamentally different from…", options: ["RxJS Subjects", "fetch()/axios, which fire immediately on call", "Angular components"], answer: 1,
    explain: "A common gotcha for developers new to Angular." },
  { q: "The main reason to centralize error handling in an interceptor is…", options: ["Fewer lines of CSS", "Consistent error UX across the whole app, defined once", "It's required by TypeScript"], answer: 1,
    explain: "Avoids scattered, inconsistent handling." }
]},
{ title: "Quiz 9 · RxJS, NgRx & Testing",
  desc: "Flattening operators, Subjects, Redux pattern, TestBed",
  questions: [
  { q: "switchMap on a repeated action…", options: ["Runs all in parallel", "Cancels the previous inner Observable", "Queues them in order"], answer: 1,
    explain: "Cancel-and-replace semantics." },
  { q: "exhaustMap is ideal for…", options: ["Search boxes", "A submit button — ignoring extra clicks while one is in-flight", "Parallel uploads"], answer: 1,
    explain: "Ignores new emissions while busy." },
  { q: "concatMap…", options: ["Cancels previous requests", "Queues inner Observables, running them one at a time in order", "Runs everything in parallel"], answer: 1,
    explain: "Preserves order, no interleaving." },
  { q: "A typeahead permanently died after one 500 (works after reload). The bug is…", options: ["The server", "catchError on the OUTER stream — one inner error terminated the long-lived pipeline; catch INSIDE the switchMap instead", "Missing debounce"], answer: 1,
    explain: "Errors are terminal. Inner catchError sacrifices one request; outer catchError kills the whole keystroke pipeline forever. The #1 production RxJS/NgRx-effects bug." },
  { q: "A component manually subscribes to a WebSocket stream for side effects. The modern leak-proof form is…", options: ["ngOnDestroy + a destroy$ Subject", "pipe(takeUntilDestroyed()) — completes the stream when the component is destroyed", "No cleanup needed"], answer: 1,
    explain: "takeUntilDestroyed replaces the destroy$-Subject boilerplate. Better still: consume via toSignal/async pipe so there's no manual subscribe at all." },
  { q: "combineLatest emits…", options: ["Once, when all complete", "Whenever ANY source emits, using the latest of each", "Never"], answer: 1,
    explain: "Reactive recombination on every change." },
  { q: "forkJoin is the RxJS analog of…", options: ["Promise.race", "Promise.all — waits for all to complete, emits once", "setTimeout"], answer: 1,
    explain: "Good for parallel independent HTTP calls." },
  { q: "In NgRx, a reducer is…", options: ["Impure and async-capable", "A pure function: (state, action) => newState", "A component"], answer: 1,
    explain: "Never mutates state directly." },
  { q: "NgRx Effects exist because…", options: ["Reducers can contain HTTP calls", "Reducers must be pure — Effects handle async side effects", "They replace actions"], answer: 1,
    explain: "Effects dispatch a new action with the result." },
  { q: "NgRx selectors are…", options: ["Impure and uncached", "Memoized, composable functions deriving data from state", "Reducers"], answer: 1,
    explain: "Analogous to computed() signals." },
  { q: "NgRx should be adopted when…", options: ["Every app, by default", "State is widely shared across many unrelated features, needing traceability", "Never"], answer: 1,
    explain: "A scaling tool, not a default." },
  { q: "Redux DevTools time-travel debugging relies on…", options: ["Impure reducers", "Pure reducers and immutable state transitions", "HTTP calls in reducers"], answer: 1,
    explain: "Deterministic replay of actions." },
  { q: "TestBed.createComponent() renders the template…", options: ["Immediately", "Only after fixture.detectChanges() is called", "Never"], answer: 1,
    explain: "Change detection doesn't run automatically in tests." },
  { q: "Overriding a provider in TestBed lets you…", options: ["Nothing new", "Swap a real service for a fake/mock in tests", "Skip compiling the component"], answer: 1,
    explain: "The core DI-testing payoff." },
  { q: "HttpTestingController is used to…", options: ["Make real HTTP calls in tests", "Mock and assert on HTTP requests without a real network", "Test signals"], answer: 1,
    explain: "expectOne + flush + verify." },
  { q: "fakeAsync + tick() are used to…", options: ["Speed up production code", "Deterministically test time-based RxJS operators without real waiting", "Test components only"], answer: 1,
    explain: "e.g., testing debounceTime." },
  { q: "Testing a plain service with no injected dependencies…", options: ["Requires TestBed", "Can be done via direct instantiation (new ServiceName())", "Is impossible"], answer: 1,
    explain: "No Angular testing utilities needed." },
  { q: "Component test harnesses provide…", options: ["Fragile CSS-selector queries", "A stable API decoupled from a component's internal DOM", "A replacement for TestBed"], answer: 1,
    explain: "Tests survive markup refactors." },
  { q: "httpMock.verify() checks that…", options: ["All tests passed", "No unexpected HTTP requests were made", "The app compiled"], answer: 1,
    explain: "Catches extra/unintended requests." },
  { q: "Picking the wrong flattening operator is described as…", options: ["A minor style issue", "The classic source of RxJS race-condition bugs", "Impossible to happen"], answer: 1,
    explain: "switchMap/mergeMap/concatMap/exhaustMap have very different semantics." }
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Comprehensive review across the whole Angular track",
  questions: [
  { q: "Reading a required input in the CONSTRUCTOR throws / gives undefined because…", options: ["Inputs are private", "Inputs bind AFTER construction — the constructor is for DI wiring; setup belongs in ngOnInit (or computed/effect)", "The compiler removed it"], answer: 1,
    explain: "Constructor = JavaScript instantiation, before Angular binds anything. The classic lifecycle interview question." },
  { q: "@for in modern Angular REQUIRES…", options: ["No extra syntax", "A track expression", "A pipe"], answer: 1,
    explain: "Stable item identity for diffing." },
  { q: "Data flows from parent to child via…", options: ["Outputs", "Inputs", "Effects"], answer: 1,
    explain: "Events flow the other way, via outputs." },
  { q: "Signals replace Zone.js's coarse checking with…", options: ["Polling", "Fine-grained, dependency-tracked reactivity", "Manual refresh calls"], answer: 1,
    explain: "Read = subscribe, write = notify dependents only." },
  { q: "computed() should be…", options: ["Impure with side effects", "A pure, memoized derivation", "Used for HTTP calls"], answer: 1,
    explain: "Use effect() for side effects instead." },
  { q: "A pure pipe reruns when…", options: ["Every cycle", "Its input reference changes", "Never"], answer: 1,
    explain: "In-place mutation won't trigger it." },
  { q: "The async pipe's key benefit is…", options: ["Faster HTTP", "Auto-subscribe AND auto-unsubscribe", "Better styling"], answer: 1,
    explain: "Eliminates manual subscription-management bugs." },
  { q: "providedIn: 'root' gives…", options: ["A new instance per component", "One singleton instance for the app", "No instance"], answer: 1,
    explain: "The default DI scope." },
  { q: "To make &lt;app-star-rating formControlName=\"rating\"&gt; work, StarRatingComponent must…", options: ["Extend FormControl", "Implement ControlValueAccessor (writeValue, registerOnChange/OnTouched, setDisabledState) and provide NG_VALUE_ACCESSOR", "Emit a valueChange output"], answer: 1,
    explain: "CVA is the adapter between the forms API and any widget — value flow, touched, disabled, and validators all integrate. Every design-system input is a CVA." },
  { q: "Lazy loading (loadComponent/loadChildren) primarily improves…", options: ["SEO only", "Initial bundle size / load performance", "Form validation"], answer: 1,
    explain: "Route-based code splitting." },
  { q: "canDeactivate guards protect against…", options: ["Unauthorized entry", "Accidentally losing unsaved changes on navigation", "Slow HTTP calls"], answer: 1,
    explain: "A confirmation before leaving a route." },
  { q: "Cross-field form validation belongs on…", options: ["A single FormControl", "The parent FormGroup", "The template"], answer: 1,
    explain: "Needs to read multiple fields at once." },
  { q: "HttpClient requests are…", options: ["Eager, like fetch()", "Lazy Observables — nothing fires until subscribed", "Synchronous"], answer: 1,
    explain: "A key HttpClient/RxJS gotcha." },
  { q: "For a submit button, the right flattening operator is usually…", options: ["mergeMap", "exhaustMap (ignore clicks while busy)", "combineLatest"], answer: 1,
    explain: "Prevents duplicate submissions." },
  { q: "After a list refresh, users' inline-edit text jumps to different rows. The cause is…", options: ["A CSS bug", "Tracking by $index (or unstable identity) — DOM/state reuse follows POSITION, not item; track a stable business key", "Too many rows"], answer: 1,
    explain: "track item.id lets Angular match rows across updates so DOM and row state move WITH the data. Index-tracking glues state to positions — the focus-jumping bug family." },
  { q: "NgRx reducers must be pure because…", options: ["It's a style preference", "Redux DevTools time-travel relies on deterministic replay", "They run on the server"], answer: 1,
    explain: "Side effects belong in Effects instead." },
  { q: "NgRx is best reserved for…", options: ["Every Angular app by default", "Widely-shared, complex state needing traceability at scale", "Small apps only"], answer: 1,
    explain: "Signals + services handle most apps well." },
  { q: "In component tests, change detection…", options: ["Runs automatically", "Requires an explicit fixture.detectChanges() call", "Is disabled entirely"], answer: 1,
    explain: "A common 'why isn't my assertion seeing the DOM' gotcha." },
  { q: "Zoneless Angular is enabled by…", options: ["More Zone.js patches", "Signals' explicit, trackable dependency model", "Bigger bundles"], answer: 1,
    explain: "No longer needs tree-wide dirty checking." },
  { q: "Non-destructive hydration in SSR…", options: ["Rebuilds the DOM from scratch", "Reuses server-rendered DOM nodes, avoiding flicker", "Disables interactivity"], answer: 1,
    explain: "Modern Angular's improved hydration approach." }
]}
);
