// AWS quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Accounts, IAM & Regions",
  desc: "Global structure, IAM building blocks, policy evaluation",
  questions: [
  { q: "A Region contains multiple…", options: ["Accounts", "Availability Zones", "IAM users"], answer: 1,
    explain: "A Region has 3+ isolated AZs (independent data centers)." },
  { q: "For high availability within a Region you spread across…", options: ["Regions", "multiple AZs", "edge locations"], answer: 1,
    explain: "Multiple AZs survive a single data-center failure." },
  { q: "Which is a GLOBAL (not regional) service?", options: ["EC2", "IAM", "RDS"], answer: 1,
    explain: "IAM, Route 53, CloudFront, and billing are global." },
  { q: "The root user should be…", options: ["used daily", "locked away with MFA, used rarely", "deleted"], answer: 1,
    explain: "Root has near-unlimited power; protect it, use scoped IAM identities." },
  { q: "An IAM role is…", options: ["a permanent user with keys", "an identity assumed temporarily (temp credentials)", "a network"], answer: 1,
    explain: "Assumed via STS; issues short-lived, auto-rotating credentials." },
  { q: "Best way to give an EC2 instance AWS permissions is…", options: ["bake in access keys", "attach an IAM role", "put keys in user-data"], answer: 1,
    explain: "Roles give temporary creds — nothing to leak or rotate." },
  { q: "In IAM policy evaluation, an explicit Deny…", options: ["can be overridden by Allow", "always wins", "is ignored"], answer: 1,
    explain: "Explicit Deny overrides any Allow." },
  { q: "The default result when no policy allows an action is…", options: ["Allow", "Deny (implicit)", "error"], answer: 1,
    explain: "Deny by default; an explicit Allow is required." },
  { q: "An IAM policy statement's core elements are…", options: ["Name, Owner", "Effect, Action, Resource (+ Condition)", "CIDR, Port"], answer: 1,
    explain: "Effect (Allow/Deny), Action, Resource, optional Condition." },
  { q: "Service Control Policies (SCPs) can…", options: ["grant new permissions", "only cap/subtract permissions (ceiling)", "assume roles"], answer: 1,
    explain: "SCPs are org-wide ceilings; they never grant." },
  { q: "You should attach policies to…", options: ["each user individually", "groups (then add users)", "the root user"], answer: 1,
    explain: "Manage permissions via groups for scalability." },
  { q: "Separating prod/staging/dev into different ACCOUNTS gives…", options: ["cheaper bills only", "a strong blast-radius/isolation boundary", "faster EC2"], answer: 1,
    explain: "The account is the primary isolation boundary." },
  { q: "AWS Organizations is used to…", options: ["run containers", "manage many accounts (billing + guardrails)", "store objects"], answer: 1,
    explain: "Consolidated billing + SCP guardrails across accounts." },
  { q: "For human access across many accounts, prefer…", options: ["one IAM user each with keys", "IAM Identity Center (SSO)/federation", "the root user"], answer: 1,
    explain: "Federate/SSO and assume roles — no per-person static keys." },
  { q: "MFA on privileged identities…", options: ["is unnecessary", "protects against password compromise", "slows the API"], answer: 1,
    explain: "A second factor blocks credential-only compromise." },
  { q: "An ARN is…", options: ["a region code", "the unique Amazon Resource Name identifying a resource", "an IAM verb"], answer: 1,
    explain: "ARNs identify resources in policies." },
  { q: "A permission boundary…", options: ["grants extra access", "caps the max permissions an identity can have", "is a subnet"], answer: 1,
    explain: "A ceiling on an identity; combines with SCPs." },
  { q: "The least-privilege principle means…", options: ["grant admin to be safe", "grant only the permissions actually needed", "deny everything"], answer: 1,
    explain: "Minimize blast radius of any credential." },
  { q: "Edge locations are used mainly by…", options: ["RDS", "CloudFront/Route 53", "IAM"], answer: 1,
    explain: "Hundreds of PoPs serving content close to users." },
  { q: "Resource-based policies (e.g., an S3 bucket policy) specify…", options: ["instance size", "who (incl. other accounts) can access the resource", "the region"], answer: 1,
    explain: "Attached to the resource; can allow cross-account access." } ] },

{ title: "Quiz 2 · EC2 & Auto Scaling",
  desc: "Instances, purchasing models, ALB/ASG, scaling",
  questions: [
  { q: "An AMI is…", options: ["a firewall", "the template (OS + software) an instance boots from", "a load balancer"], answer: 1,
    explain: "Amazon Machine Image = the boot template." },
  { q: "EBS volumes are…", options: ["ephemeral local disks", "network-attached persistent block storage", "object storage"], answer: 1,
    explain: "EBS persists across stop/start, unlike instance store." },
  { q: "Instance store data is…", options: ["persistent", "ephemeral — lost on stop/terminate", "backed up automatically"], answer: 1,
    explain: "Put durable data on EBS/S3/RDS, not instance store." },
  { q: "Spot instances offer big discounts but…", options: ["never get reclaimed", "can be reclaimed with 2-min notice", "are always on"], answer: 1,
    explain: "Use Spot for interruptible, fault-tolerant work." },
  { q: "For steady baseline load, the cheapest model is…", options: ["On-Demand", "Savings Plans / Reserved", "Spot for the DB"], answer: 1,
    explain: "Commit 1–3 years for up to ~72% off." },
  { q: "An Auto Scaling Group provides…", options: ["only cost savings", "elasticity + self-healing (replaces unhealthy instances)", "object storage"], answer: 1,
    explain: "Maintains desired count, replaces failed instances, scales." },
  { q: "For HA, an ASG should span…", options: ["one AZ", "multiple AZs", "multiple accounts"], answer: 1,
    explain: "An AZ outage then removes only a fraction of capacity." },
  { q: "An Application Load Balancer operates at…", options: ["Layer 4 (TCP)", "Layer 7 (HTTP/S)", "Layer 2"], answer: 1,
    explain: "ALB does host/path routing, TLS, WebSockets." },
  { q: "A Network Load Balancer is best for…", options: ["HTTP path routing", "extreme throughput/low latency, TCP/UDP, static IPs", "email"], answer: 1,
    explain: "NLB is Layer 4, high performance." },
  { q: "Target-tracking scaling means…", options: ["fixed instance count", "keep a metric (e.g., 50% CPU) at target — add/remove to hold it", "scale only on schedule"], answer: 1,
    explain: "The simplest, common scaling policy." },
  { q: "Instances behind an ASG should be…", options: ["stateful singletons", "stateless (state in RDS/S3/ElastiCache)", "using instance store for the DB"], answer: 1,
    explain: "Stateless lets any instance be added/replaced." },
  { q: "Scheduled scaling suits…", options: ["random spikes", "predictable time-based load (e.g., 9am weekdays)", "no load"], answer: 1,
    explain: "Scale ahead of known patterns." },
  { q: "The ALB routes traffic only to…", options: ["all targets", "healthy targets (per health checks)", "the first AZ"], answer: 1,
    explain: "Health checks gate which targets receive traffic." },
  { q: "User data is…", options: ["a metric", "a boot script that runs on first launch", "a security group"], answer: 1,
    explain: "Bootstraps the instance at launch." },
  { q: "A good use of Spot is…", options: ["primary database", "stateless CI runners / batch workers", "a stateful singleton"], answer: 1,
    explain: "Interruptible, fault-tolerant workloads." },
  { q: "The instance type (e.g., c7g.xlarge) determines…", options: ["the region", "the hardware profile (CPU/mem family + size)", "the AMI"], answer: 1,
    explain: "Families target general/compute/memory/GPU." },
  { q: "To cut EC2 cost on steady load, you should…", options: ["run all On-Demand", "cover baseline with Savings Plans, spikes On-Demand, Spot for interruptible", "use bigger instances"], answer: 1,
    explain: "Mix purchasing models by workload." },
  { q: "A mixed-instances ASG policy lets you…", options: ["only use one type", "blend On-Demand and Spot across instance types", "disable scaling"], answer: 1,
    explain: "Diversify for cost + Spot resilience." },
  { q: "Replacing a failed instance automatically is…", options: ["manual work", "done by the ASG via health checks", "impossible"], answer: 1,
    explain: "Self-healing is a core ASG feature." },
  { q: "Dedicated Hosts are for…", options: ["cheapest compute", "compliance/licensing needing physical isolation", "serverless"], answer: 1,
    explain: "Physical-server isolation at a premium." } ] },

{ title: "Quiz 3 · S3 & CloudFront",
  desc: "Object storage, security, storage classes, CDN",
  questions: [
  { q: "S3 is…", options: ["a block disk", "object storage (objects by key, HTTP API, ~infinite scale)", "a relational DB"], answer: 1,
    explain: "Not a filesystem; objects addressed by key." },
  { q: "S3 durability is around…", options: ["99%", "99.999999999% (11 nines)", "50%"], answer: 1,
    explain: "Replicated across AZs for extreme durability." },
  { q: "S3 buckets by default are…", options: ["public", "private (Block Public Access on)", "world-writable"], answer: 1,
    explain: "Private by default; keep Block Public Access on." },
  { q: "To serve a private object temporarily, use…", options: ["a public bucket", "a presigned URL", "an IAM user per visitor"], answer: 1,
    explain: "Time-limited signed link without making the bucket public." },
  { q: "The safe way to serve web content from S3 is…", options: ["make the bucket public", "CloudFront with Origin Access Control (bucket stays private)", "email the files"], answer: 1,
    explain: "OAC lets only CloudFront read the private bucket." },
  { q: "S3 'folders' are really…", options: ["real directories", "key prefixes in a flat namespace", "separate buckets"], answer: 1,
    explain: "S3 is a flat key-value object store." },
  { q: "For unknown/changing access patterns, use…", options: ["Glacier Deep Archive", "S3 Intelligent-Tiering", "One Zone-IA"], answer: 1,
    explain: "Auto-moves objects between tiers, no retrieval-fee surprises." },
  { q: "Lifecycle policies let you…", options: ["encrypt only", "auto-transition objects to colder classes and expire them", "make buckets public"], answer: 1,
    explain: "The main lever for S3 cost." },
  { q: "Glacier Deep Archive is for…", options: ["hot data", "archival (cheapest storage, slow retrieval)", "static websites"], answer: 1,
    explain: "Lowest storage cost, hours to retrieve." },
  { q: "CloudFront is…", options: ["a database", "a CDN caching content at edge locations", "a queue"], answer: 1,
    explain: "Reduces latency and origin load; edge TLS + Shield/WAF." },
  { q: "A CloudFront cache HIT means…", options: ["origin is called", "content served from the edge instantly", "an error"], answer: 1,
    explain: "Only misses go to the origin." },
  { q: "To avoid invalidations on deploy, you can…", options: ["disable caching", "version/fingerprint asset filenames", "make files public"], answer: 1,
    explain: "Changed filenames sidestep cache invalidation." },
  { q: "Over-specific cache keys (many headers/cookies) cause…", options: ["better hit ratio", "poor cache hit ratio + more origin load", "encryption"], answer: 1,
    explain: "Minimize cache-key dimensions for good hit ratio." },
  { q: "You cannot ___ an S3 object; you replace it.", options: ["read", "partially edit/append", "delete"], answer: 1,
    explain: "Objects are replaced whole, not partially edited." },
  { q: "S3 encryption at rest (SSE) is…", options: ["off by default", "on by default (SSE-S3/SSE-KMS)", "impossible"], answer: 1,
    explain: "Encryption at rest; enforce TLS in transit too." },
  { q: "Block Public Access should be…", options: ["turned off to work", "left ON unless the content is truly public", "deleted"], answer: 1,
    explain: "Leaving it on prevents the classic public-bucket breach." },
  { q: "EBS vs S3: EBS is…", options: ["object storage", "block storage attached to one instance", "a CDN"], answer: 1,
    explain: "EBS = block disk; S3 = objects; EFS = shared file." },
  { q: "The standard secure static-site stack is…", options: ["public S3 only", "private S3 + CloudFront (OAC, ACM HTTPS) + Route 53", "EC2 + FTP"], answer: 1,
    explain: "Cheap, fast, HTTPS, bucket private." },
  { q: "Versioning on a critical bucket protects against…", options: ["higher latency", "accidental/malicious deletion or overwrite", "region outage"], answer: 1,
    explain: "Keeps prior versions; pair with Object Lock for compliance." },
  { q: "One Zone-IA trades ___ for lower cost.", options: ["throughput", "durability (single AZ)", "encryption"], answer: 1,
    explain: "Cheaper but less durable than multi-AZ IA." } ] },

{ title: "Quiz 4 · VPC Networking",
  desc: "Subnets, routing, gateways, security groups vs NACLs",
  questions: [
  { q: "A VPC is…", options: ["a virtual server", "your isolated virtual network (CIDR + subnets)", "an S3 bucket"], answer: 1,
    explain: "You control IP range, subnets, routing, firewalls." },
  { q: "A subnet lives in…", options: ["all AZs", "exactly one AZ", "one Region only, spanning AZs"], answer: 1,
    explain: "Each subnet is within a single AZ." },
  { q: "What makes a subnet 'public'?", options: ["a checkbox", "a route 0.0.0.0/0 → Internet Gateway", "its size"], answer: 1,
    explain: "Public = route to an IGW (+ public IPs)." },
  { q: "A NAT Gateway lets private subnets…", options: ["receive inbound internet traffic", "make OUTBOUND internet calls (no inbound)", "store objects"], answer: 1,
    explain: "Outbound-only egress for private resources." },
  { q: "Databases should live in…", options: ["public subnets", "isolated private subnets", "the Internet Gateway"], answer: 1,
    explain: "No internet route; access via app SG only." },
  { q: "Security groups are…", options: ["stateless, allow+deny", "stateful, allow-only, on the instance/ENI", "subnet-level"], answer: 1,
    explain: "Return traffic auto-allowed; allow rules only." },
  { q: "Network ACLs are…", options: ["stateful", "stateless, allow+deny, at the subnet boundary", "attached to instances"], answer: 1,
    explain: "Must allow both directions; first-match-wins." },
  { q: "Security groups can reference…", options: ["only IPs", "other security groups (e.g., DB SG allows from app SG)", "AMIs"], answer: 1,
    explain: "SG-to-SG rules follow instances as they scale." },
  { q: "A common NACL bug is…", options: ["allowing too little disk", "forgetting they're stateless (blocking return traffic)", "encryption"], answer: 1,
    explain: "Must allow ephemeral return ports explicitly." },
  { q: "To reach S3/DynamoDB privately (no NAT), use…", options: ["a public subnet", "a VPC Gateway Endpoint", "an Internet Gateway"], answer: 1,
    explain: "Endpoints keep AWS-service traffic off the internet." },
  { q: "For HA, deploy NAT Gateways…", options: ["one for all AZs", "one per AZ", "none"], answer: 1,
    explain: "Avoids a single point of failure + cross-AZ charges." },
  { q: "Connecting two VPCs at scale (hub) uses…", options: ["an IGW", "Transit Gateway (or peering for 1:1)", "a NAT"], answer: 1,
    explain: "Transit Gateway is the many-VPC hub." },
  { q: "Connecting on-prem to AWS uses…", options: ["S3", "Site-to-Site VPN or Direct Connect", "CloudFront"], answer: 1,
    explain: "VPN over internet, or a dedicated line (Direct Connect)." },
  { q: "Exposing SSH/DB ports to 0.0.0.0/0 is…", options: ["fine", "dangerous — restrict to known IPs / use SSM", "required"], answer: 1,
    explain: "Open ports invite brute-force/breach." },
  { q: "An Internet Gateway provides…", options: ["outbound-only", "two-way internet access for public subnets", "storage"], answer: 1,
    explain: "Attached to the VPC for public connectivity." },
  { q: "Overlapping CIDRs between VPCs…", options: ["are fine", "break peering/routing", "improve speed"], answer: 1,
    explain: "Plan non-overlapping ranges up front." },
  { q: "The primary, fine-grained network control is usually…", options: ["NACLs", "security groups", "route tables"], answer: 1,
    explain: "SGs are the main control; NACLs are coarse guardrails." },
  { q: "A bastion host / SSM Session Manager is used to…", options: ["store data", "reach private instances without exposing them", "cache content"], answer: 1,
    explain: "SSM avoids opening SSH to the internet entirely." },
  { q: "AWS PrivateLink lets you…", options: ["peer all VPCs", "expose/consume a service privately across VPCs", "run Lambda"], answer: 1,
    explain: "Interface endpoints to a service without internet." },
  { q: "Route tables decide…", options: ["instance size", "where a subnet's traffic goes (local/IGW/NAT/peering)", "IAM access"], answer: 1,
    explain: "Routing defines public vs private behavior." } ] },

{ title: "Quiz 5 · RDS & DynamoDB",
  desc: "Relational vs NoSQL, Multi-AZ, replicas, partition keys",
  questions: [
  { q: "RDS is…", options: ["object storage", "managed relational SQL databases", "a CDN"], answer: 1,
    explain: "Managed Postgres/MySQL/Aurora/etc." },
  { q: "Multi-AZ RDS provides…", options: ["read scaling", "a synchronous standby for automatic failover (availability)", "cheaper storage"], answer: 1,
    explain: "Standby isn't readable; it's for HA failover." },
  { q: "Read replicas provide…", options: ["automatic failover", "async readable copies to scale reads", "backups only"], answer: 1,
    explain: "Offload read traffic; not an HA mechanism." },
  { q: "Multi-AZ vs read replica — Multi-AZ is for…", options: ["read scaling", "availability (failover)", "sharding"], answer: 1,
    explain: "Availability vs read scalability — a classic distinction." },
  { q: "Aurora's storage is…", options: ["single copy", "distributed, replicated 6 ways across 3 AZs", "instance store"], answer: 1,
    explain: "Separates compute from a resilient storage layer." },
  { q: "DynamoDB is…", options: ["relational", "managed NoSQL key-value/document store", "a queue"], answer: 1,
    explain: "Serverless NoSQL with flat low latency at scale." },
  { q: "A good DynamoDB partition key has…", options: ["low cardinality", "high cardinality + even access (no hot value)", "one value"], answer: 1,
    explain: "Even distribution avoids hot partitions/throttling." },
  { q: "A DynamoDB Scan…", options: ["reads by key efficiently", "reads the whole table (slow/costly)", "is always best"], answer: 1,
    explain: "Prefer Query by key / use a GSI over Scan." },
  { q: "You design a DynamoDB table around…", options: ["normalized entities", "your access patterns", "random keys"], answer: 1,
    explain: "Model for how you'll query (often single-table design)." },
  { q: "A sort key enables…", options: ["nothing", "range queries within a partition (composite key)", "encryption"], answer: 1,
    explain: "Partition + sort = composite primary key." },
  { q: "DynamoDB Streams provide…", options: ["backups", "a change feed of item modifications", "caching"], answer: 1,
    explain: "React to changes (e.g., trigger Lambda)." },
  { q: "DAX is…", options: ["a queue", "an in-memory cache for DynamoDB", "a replica"], answer: 1,
    explain: "Microsecond reads in front of DynamoDB." },
  { q: "Choose RDS/relational when you need…", options: ["only key lookups", "joins, complex queries, multi-row transactions", "unlimited scale above all"], answer: 1,
    explain: "Relational shines with varied queries & relationships." },
  { q: "Choose DynamoDB when…", options: ["queries are ad-hoc/complex", "access patterns are known + you need huge scale/flat latency", "you need joins"], answer: 1,
    explain: "Predictable access at scale with zero DB ops." },
  { q: "Aurora Serverless v2…", options: ["never scales", "auto-scales capacity to load", "is NoSQL"], answer: 1,
    explain: "Good for spiky/variable relational workloads." },
  { q: "A hot partition in DynamoDB causes…", options: ["cheaper reads", "throttling", "more durability"], answer: 1,
    explain: "Skewed key concentrates load; fix with better key/sharding." },
  { q: "Databases should be placed in…", options: ["public subnets", "private/isolated subnets", "the CDN"], answer: 1,
    explain: "Never expose the DB to the internet." },
  { q: "Point-in-time recovery (PITR) gives…", options: ["read scaling", "restore to any second in the retention window", "caching"], answer: 1,
    explain: "Automated backups + PITR protect against data loss." },
  { q: "DynamoDB Global Tables provide…", options: ["single-region only", "multi-region active-active replication", "no replication"], answer: 1,
    explain: "Cross-region low-latency reads/writes." },
  { q: "Aurora Global Database is for…", options: ["local caching", "cross-region replication (~1s lag) for DR/global reads", "queuing"], answer: 1,
    explain: "Region-level DR and global read latency." } ] }
);
