// aws quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Compute: EC2, EBS, Auto Scaling & Containers",
  desc: "vCPUs and Graviton, burstable traps, EBS performance, ASG health, ECS/EKS/Fargate",
  questions: [
  { q: "A vCPU on most Intel/AMD EC2 instances is…", options: ["A hyperthread — which is why scaling measured 4.72× on x86 against 7.90× on Graviton", "A physical core", "A container"], answer: 0,
    explain: "Graviton vCPUs are physical cores. That difference turned a 15% price gap into an 88% price/performance gap in the measured workload." },
  { q: "A T2 instance that exhausts its CPU credits…", options: ["Bursts indefinitely", "Throttles to its baseline (as low as 20%) — p99 went from 178 ms to 4,241 ms while the CPU graph looked idle", "Stops"], answer: 1,
    explain: "The graph looks fine because the instance is capped, not busy. Always alarm on CPUCreditBalance for burstable families." },
  { q: "T3 instances in unlimited mode fail differently: they…", options: ["Silently bill surplus credits — one fleet accrued $884/month with no performance symptom at all", "Throttle harder", "Terminate"], answer: 0,
    explain: "T2 fails visibly in latency; T3 fails invisibly on the invoice. Both are the wrong family for sustained load." },
  { q: "gp2 volume IOPS are…", options: ["Fixed at 3,000", "Configurable independently", "Tied to volume SIZE, with a burst balance that runs out — a measured drop from 2,987 to 301 IOPS"], answer: 2,
    explain: "gp3 decouples IOPS from size and is usually cheaper. Also check the INSTANCE's EBS bandwidth baseline, which is often the real ceiling." },
  { q: "Restoring an EBS volume from a snapshot gives…", options: ["Zero performance", "Full performance immediately", "Lazy loading — 1,204 IOPS against a steady-state 11,890, taking about an hour to reach baseline under load"], answer: 2,
    explain: "The volume reports available long before it is usable at full speed. Fast Snapshot Restore fixes it at roughly $547/month per snapshot per AZ." },
  { q: "On Nitro instances, device names appear as /dev/nvme*, which…", options: ["Requires a new AMI", "Is cosmetic", "Breaks fstab entries written for /dev/xvd* — mount by UUID or label instead"], answer: 2,
    explain: "The instance boots and then fails to mount its data volume, which looks like a storage failure and is a naming assumption." },
  { q: "An Auto Scaling group with HealthCheckType: EC2…", options: ["Replaces instances whose application has died", "Is the recommended setting", "Only replaces instances whose EC2 status checks fail — capacity leaked 6 → 3 while desired still read 6"], answer: 2,
    explain: "Use ELB health checks so the ASG replaces instances the load balancer considers unhealthy — and set a health check grace period, or you get an infinite boot loop." },
  { q: "Target tracking oscillated 4 → 19 → 5 → 17 instances because…", options: ["Time-to-serve (252 s) exceeded the evaluation window (180 s), so the loop reacted before the previous action took effect", "The ALB was misconfigured", "The metric was wrong"], answer: 0,
    explain: "--default-instance-warmup plus warm pools fixed it, improving p99 AND reducing instance-hours at the same time." },
  { q: "CloudWatch's default EC2 metrics do NOT include…", options: ["Memory utilisation — it requires the CloudWatch agent", "Network", "CPU"], answer: 0,
    explain: "Scaling or alarming on memory needs the agent installed; many teams discover this during an OOM incident." },
  { q: "'Should we use ECS or Fargate?' is…", options: ["A cost question", "A category error — ECS and EKS are orchestrators, Fargate is a capacity provider you can use with either", "A reasonable question"], answer: 1,
    explain: "The real questions are 'which orchestrator?' and 'do I want to manage the capacity?'" },
  { q: "In ECS, the execution role and the task role differ: the task role is…", options: ["Used by the agent to pull images and write logs", "Used by YOUR CODE — and the container credential endpoint serves only the task role", "The same thing"], answer: 1,
    explain: "The execution role belongs to the agent. Confusing them produces 'my code cannot read the bucket even though the role allows it'." },
  { q: "With awsvpc networking, an m5.large was capped at 2 tasks with 45% CPU idle because…", options: ["ENI density — task placement was an ADDRESSING limit before it was a resource limit", "CPU shares", "Memory limits"], answer: 0,
    explain: "ENI trunking raised it to 10 tasks on the same instance. Density limits are usually addressing, not compute." },
  { q: "Fargate's CPU/memory options are…", options: ["Fully arbitrary", "Only two sizes", "A fixed menu of valid combinations, which forces wasted vCPU for memory-heavy workloads"], answer: 2,
    explain: "The measured crossover was around 61% cluster utilisation: below it Fargate wins, and a cluster at 17% used made Fargate 55% cheaper." },
  { q: "EKS access entries replaced aws-auth. The migration trap is…", options: ["The node-group role must be recreated as EC2_LINUX before the one-way switch, or every node goes NotReady", "Nothing", "It requires a new cluster"], answer: 0,
    explain: "The switch cannot be undone, so the ordering matters more than usual." },
  { q: "ECR pull-through cache is worth configuring because…", options: ["Docker Hub's per-IP pull limit fails deploys exactly when you are scaling out", "It is faster", "It reduces storage"], answer: 0,
    explain: "The failure appears under load, which is when you least want an image-pull error." },
  { q: "A container exiting with code 137 and NO OutOfMemoryError in the log means…", options: ["A failed health check", "A crash in the app", "The kernel OOM-killed it — typically a JVM sized against the whole cgroup limit"], answer: 2,
    explain: "The JVM never got to throw; the process was killed. Size the heap as a fraction of the container limit, not the host." },
  { q: "Spot capacity in an ASG is best used with…", options: ["On-demand only", "A single instance type", "Diversified instance types and AZs plus capacity-optimised allocation"], answer: 2,
    explain: "Diversification is what makes interruption rare enough to be manageable; a single type concentrates the risk." },
  { q: "Placement groups (cluster) improve…", options: ["Availability", "Network performance between instances — at the cost of concentrating them in one AZ", "Cost"], answer: 1,
    explain: "It is an explicit trade of resilience for latency and bandwidth; spread placement groups make the opposite trade." },
  { q: "Instance metadata service v2 (IMDSv2) should be enforced because…", options: ["IMDSv1 allows SSRF-based credential theft; --http-tokens required plus --http-put-response-hop-limit 1 blocks it", "It is faster", "It is required for ASGs"], answer: 0,
    explain: "The lesson demonstrates the theft end to end. Enforcing IMDSv2 is one of the highest-value one-line changes in EC2." },
  { q: "The correct first question when an ASG will not scale is…", options: ["Is the scaling METRIC one that actually moves with demand? An I/O-bound fleet sits at low CPU while latency explodes", "Is the AMI correct?", "Is the quota raised?"], answer: 0,
    explain: "ALBRequestCountPerTarget tracks demand directly; CPU tracks demand only for CPU-bound work." },
]},
{ title: "Quiz 7 · Serverless & Messaging",
  desc: "Lambda lifecycle and concurrency, API Gateway limits, SQS/SNS/EventBridge semantics",
  questions: [
  { q: "Lambda's INIT phase runs…", options: ["Once per execution environment — warm invocations skipped it and went from 412 ms to 71 ms", "Once per invocation", "Never"], answer: 0,
    explain: "The same reuse that gives the speed-up leaks state between invocations: a global left populated by one user is visible to the next." },
  { q: "Lambda concurrency is calculated as…", options: ["Memory ÷ 128", "requests per second × average duration in seconds", "Requests per second"], answer: 1,
    explain: "100 rps at 200 ms is 20 concurrent executions. It is Little's Law again, and it is the number that meets the account limit." },
  { q: "Reserved concurrency set to 0…", options: ["DISABLES the function — it is both a floor and a ceiling", "Means unlimited", "Has no effect"], answer: 0,
    explain: "That property makes it a legitimate emergency stop for a runaway function, and a memorable outage when set by accident." },
  { q: "The account concurrency pool is shared, which means…", options: ["One function's bug is every function's outage — a thumbnailer held 947 of 1,000 concurrent executions", "Only VPC functions compete", "Functions are isolated"], answer: 0,
    explain: "Reserved concurrency on noisy functions, and as a floor on user-facing ones, is the only real isolation." },
  { q: "An asynchronous Lambda invocation that keeps failing…", options: ["Retries forever", "Retries twice and then silently drops the event unless a DLQ or on-failure destination is configured — about 2,996 events a week were lost", "Returns an error to the caller"], answer: 1,
    explain: "There is no caller to return to. Always configure a destination for async invocations." },
  { q: "One poison record on a Kinesis shard…", options: ["Fails only that batch", "Blocks that shard for up to 24 hours, with IteratorAge growing linearly", "Is skipped"], answer: 1,
    explain: "BisectBatchOnFunctionError isolated the bad record in 15 splits; a linearly growing IteratorAge is the signature to alarm on." },
  { q: "Lambda in front of RDS is a structural mismatch because…", options: ["Each concurrent execution takes a connection — 387 connections against a limit of 90; raising max_connections traded refusals for 8.4-second queries", "Lambda cannot reach a VPC", "RDS is too slow"], answer: 0,
    explain: "RDS Proxy multiplexes many client connections onto few database ones, which is the actual fix." },
  { q: "API Gateway's 29-second integration timeout means…", options: ["Nothing happens", "The function is killed", "The client gets a 504 while the function CONTINUES and bills — 47 customers were charged twice"], answer: 2,
    explain: "The fix is idempotency first: a client-supplied key with a conditional write, so the retry cannot double-charge." },
  { q: "SnapStart's snapshot is shared across environments, so…", options: ["It cannot be used with Java", "Randomness or unique IDs generated during INIT can be identical across executions", "Cold starts get worse"], answer: 1,
    explain: "Re-seed anything unique in a runtime hook rather than at initialisation." },
  { q: "The queue/topic/bus/stream decision is best made on…", options: ["Backpressure, retention and replay requirements", "Language support", "Cost"], answer: 0,
    explain: "SQS gives backpressure and no replay; Kinesis gives ordered retention and replay; SNS fans out without retention; EventBridge routes with rules and an archive." },
  { q: "A visibility timeout shorter than processing time causes…", options: ["Message loss", "Duplicate processing — 14 of 20 jobs ran twice while every metric looked perfect", "Throttling"], answer: 1,
    explain: "Set the timeout above p99 processing time (or heartbeat it) and make consumers idempotent regardless." },
  { q: "SQS long polling versus short polling is…", options: ["Only for FIFO", "A latency-for-cost trade", "Strictly better: 401× fewer requests AND about 10× lower latency"], answer: 2,
    explain: "Short polling exists mostly for legacy reasons; there is no reason to keep it in new code." },
  { q: "SNS filter policies reduced deliveries by…", options: ["Nothing measurable", "40% overall and 99.2% for one subscriber that had been receiving everything and discarding most of it", "Only in FIFO topics"], answer: 1,
    explain: "Filtering at the topic saves the invocation, not just the work — it moves the discard from your compute bill to the platform." },
  { q: "A poison message received 43 times in 90 seconds is bounded by…", options: ["maxReceiveCount on a redrive policy, sending it to a DLQ — with a rate-limited redrive when you replay", "Visibility timeout alone", "Deleting the queue"], answer: 0,
    explain: "Redriving a full DLQ at once simply reproduces the incident, which is why the rate limit matters." },
  { q: "In SQS FIFO, the message group ID controls…", options: ["Ordering only", "Deduplication only", "Ordering AND parallelism — one group measured 304 msg/s with 20 idle workers, sixty groups reached 18,420"], answer: 2,
    explain: "Order is preserved within a group, so a single group serialises the entire queue no matter how many consumers you run." },
  { q: "EventBridge archive and replay is…", options: ["Retroactive", "NOT retroactive — only events after the archive was created can be replayed", "Automatic"], answer: 1,
    explain: "A FilterArns-scoped replay recovered 3,632 events for one broken consumer without re-delivering to three healthy ones." },
  { q: "Every AWS messaging service is at-least-once, so idempotency keys should be based on…", options: ["A timestamp", "The BUSINESS identifier (order ID, payment ID) — a redelivered message has a new message ID", "The message ID"], answer: 1,
    explain: "Deduplicating on message ID protects against nothing, because the retry arrives as a different message." },
  { q: "SQS is best described as giving you…", options: ["Ordering by default", "Extra capacity", "Backpressure and buffering — patience, not throughput"], answer: 2,
    explain: "If arrival rate exceeds service rate on average, the backlog grows without bound: one reached 4.1 million before messages started ageing out of retention." },
  { q: "For a worker fleet, the right scaling metric is…", options: ["CPU", "Backlog per instance = target latency ÷ average processing time (300 ÷ 1.9 = 157)", "Queue depth"], answer: 1,
    explain: "Raw depth oscillates because it collapses as soon as you add workers; per-instance backlog is self-normalising." },
  { q: "The alarm that catches a queue's true failure mode is…", options: ["Queue depth above a threshold", "ApproximateAgeOfOldestMessage, plus an alarm on the backlog growing monotonically for 30 minutes", "Consumer count"], answer: 1,
    explain: "Age maps to a user-visible promise; monotonic growth is the signature of arrival exceeding service, which waiting never fixes." },
]},
{ title: "Quiz 8 · Data: S3, RDS/Aurora & DynamoDB",
  desc: "Object-store reality, Multi-AZ versus scale, replica lag, partitions and single-table design",
  questions: [
  { q: "S3 folders are…", options: ["Only in the console", "Real directories", "Synthetic — CommonPrefixes is a listing convenience, and mv is a COPY followed by a DELETE"], answer: 2,
    explain: "Listing a billion objects costs about a million requests, $5 and 5.5 hours, because there is no directory to read." },
  { q: "Which of these is still widely repeated but WRONG today?", options: ["S3 supports versioning", "S3 charges for storage", "S3 is eventually consistent for new objects, so add random prefixes for performance"], answer: 2,
    explain: "Strong read-after-write consistency arrived in December 2020, and random prefixes stopped being necessary for performance in 2018." },
  { q: "S3 request rates are limited…", options: ["Per PREFIX — spreading across 8 prefixes took a workload from 3,204 to 25,500 req/s", "Per account", "Per bucket"], answer: 0,
    explain: "503 SlowDown is the signal. Adaptive retries absorbed a 31% throttle rate while the prefixes were restructured." },
  { q: "With versioning enabled, DELETE…", options: ["Is blocked", "Frees the storage", "Writes a delete marker — so deleting made the bucket BIGGER, and 10.2 TB was hidden from the console and s3 ls while CloudWatch and the invoice counted it"], answer: 2,
    explain: "Lifecycle rules must handle noncurrent versions and expired delete markers, or storage grows forever." },
  { q: "BlockPublicPolicy is notable because it…", options: ["REFUSES TO STORE the policy — so the policy you are debugging is not the one in effect", "Warns you", "Applies only to new buckets"], answer: 0,
    explain: "People edit a policy repeatedly with no change in behaviour because the PUT is being rejected." },
  { q: "Object Lock in compliance mode is…", options: ["Advisory", "Irreversible even by root until the retain-until date — which is what regulators mean by immutable", "Reversible by the account root"], answer: 1,
    explain: "Governance mode is reversible by anyone with the permission, so it is useful for testing and worth nothing against a compromised admin." },
  { q: "RDS Multi-AZ gives you…", options: ["Both", "Read scaling", "Availability only — there is no standby endpoint; it costs about the same as single-AZ plus a replica while buying the opposite thing"], answer: 2,
    explain: "The standby is not even listed. Read replicas scale reads; Multi-AZ survives an AZ failure." },
  { q: "Measured RDS failover times varied hugely by client: 38 s from the AWS CLI, 49 s in Node, 9 s behind RDS Proxy, and…", options: ["Instant in Java", "The same everywhere", "NEVER on a default JVM, because of its DNS cache"], answer: 2,
    explain: "Failover time is dominated by client-side caching, not by the database." },
  { q: "Read replica lag under load measured…", options: ["0 of 200 read-your-write failures when idle, and 187 of 200 under write load", "Constant", "Always high"], answer: 0,
    explain: "Testing replica routing on an idle system proves nothing. Route reads sticky-to-primary for a window after any write." },
  { q: "Aurora replicates by shipping…", options: ["Redo log records to a shared storage layer — 21 ms lag against 1,841 s, and 4.6 minutes versus 47 to add a replica, with no writer impact", "Full pages", "Binlogs"], answer: 0,
    explain: "The storage-level design is why Aurora replicas are fast to add and cheap to run." },
  { q: "Setting RDS backup retention to 0…", options: ["Keeps the last snapshot", "Silently disables point-in-time recovery", "Is not allowed"], answer: 1,
    explain: "It is a one-character change that removes your ability to recover from logical damage." },
  { q: "A database restore returns…", options: ["The same endpoint", "A NEW hostname, the default parameter group, the default security group and no Multi-AZ — real RTO was 32 minutes against a runbook claiming 11", "An identical instance"], answer: 1,
    explain: "Add indirection (an internal CNAME or a secret resolved at connect time) before the incident, or recovery includes a deploy." },
  { q: "Performance Insights wait events were used to choose…", options: ["A different engine", "A larger instance", "A $0 index worth a 32× improvement over an $8,064/year resize worth 1.3×"], answer: 2,
    explain: "Wait events tell you what the database is waiting ON, which is the difference between fixing the problem and paying for it." },
  { q: "In DynamoDB you should model from…", options: ["Entities and relationships", "The relational schema", "ACCESS PATTERNS — the questions the application asks"], answer: 2,
    explain: "Single-table design is the consequence: every pattern is served by one Query, with a hot-partition review of the INDEX keys as well as the table keys." },
  { q: "A hot partition measured 69% throttled requests while the table showed…", options: ["Full utilisation", "An error", "2.5% of provisioned capacity consumed — doubling capacity changed nothing until the key was sharded, which reached 21,840 writes/s"], answer: 2,
    explain: "Per-partition ceilings (3,000 RCU / 1,000 WCU) mean aggregate capacity is meaningless if one key is hot." },
  { q: "FilterExpression in a Query or Scan applies…", options: ["Before the read, saving capacity", "AFTER the read — 482,104 items and 60,263 RCU to return 12, against 1.5 RCU using a GSI", "Only to Scans"], answer: 1,
    explain: "ScannedCount versus Count is the diagnostic: a huge gap means you are paying to read and discard." },
  { q: "A throttled GSI…", options: ["Affects only index queries", "Rejects BASE-TABLE writes — 92% of them, while the table itself sat at 1% utilisation", "Is impossible"], answer: 1,
    explain: "The index write must succeed for the table write to complete, so an under-provisioned GSI takes down the table." },
  { q: "Read-modify-write on a DynamoDB counter…", options: ["Lost 947 of 1,000 increments silently; the atomic conditional update is both correct AND cheaper", "Is safe", "Requires a transaction"], answer: 0,
    explain: "One conditional UpdateItem beats a read plus a write in cost, latency and correctness simultaneously." },
  { q: "DynamoDB on-demand absorbs a spike of roughly…", options: ["Any size", "Twice the previous peak instantly — beyond that it still throttles, so ramp before a known event", "Ten times"], answer: 1,
    explain: "Pre-warming by gradually raising traffic in the days before a sale raises the remembered peak." },
  { q: "The S3 lifecycle rule that took a bucket from 14.0 TB to 2.6 TB worked by…", options: ["Expiring noncurrent versions, incomplete multipart uploads and delete markers alongside transitions — an 81% reduction", "Deleting old objects", "Changing storage class only"], answer: 0,
    explain: "Incomplete multipart uploads in particular accumulate invisibly and are billed as storage." },
]},
{ title: "Quiz 9 · Operations & Architecture",
  desc: "Observability defaults, IaC state, encryption, Well-Architected trade-offs, DR and scaling",
  questions: [
  { q: "CloudTrail data events are…", options: ["On by default", "Free", "OFF by default — so 'who downloaded that export?' is unanswerable; scoped to one bucket it cost $0.04/month against $200 for everything"], answer: 2,
    explain: "Management events are on; object-level reads and writes are not. Scope them to the buckets that matter rather than skipping them." },
  { q: "Alarming on the AVERAGE of a latency metric…", options: ["Is standard practice and correct", "Is impossible", "Hides partial failures — 3 broken hosts of 20 read 1,243 ms while p99 was 8,103 ms"], answer: 2,
    explain: "Watching p50 alongside p99 separates 'everything is slow' from 'a subset is failing', which are different incidents." },
  { q: "A CloudWatch alarm in INSUFFICIENT_DATA…", options: ["Is an alarm", "Always pages", "Is not — so a PARTIAL failure fires while a TOTAL failure goes silent"], answer: 2,
    explain: "Fix with --treat-missing-data breaching, a traffic-volume alarm and a canary, so 'no data' cannot mean 'no problem'." },
  { q: "High-cardinality dimensions on CloudWatch custom metrics…", options: ["Are priced per metric — one design computed to $37M/month, replaced by EMF at $32.40 with per-customer latency still queryable", "Are free", "Are capped automatically"], answer: 0,
    explain: "Embedded Metric Format keeps the cardinality in logs, where it is cheap, and extracts only the aggregates as metrics." },
  { q: "In CloudWatch Logs, the dominant cost is usually…", options: ["Ingestion at about $0.50/GB", "Insights queries", "Retention at $0.03/GB-month"], answer: 0,
    explain: "Shortening retention barely moves the bill; reducing what you emit does." },
  { q: "X-Ray by default sampled…", options: ["A small fraction — 0.20% of traffic in the measured system", "All requests", "Errors only"], answer: 0,
    explain: "Also remember annotations are indexed and searchable while metadata is not: putting deployVersion in an annotation turns 'when did this start?' into a filter." },
  { q: "The main value of infrastructure as code is…", options: ["Review and reproducibility — and the hard part is STATE, not syntax", "Cost control", "Automation speed"], answer: 0,
    explain: "Two concurrent applies orphaned a real resource, and state files hold passwords in plaintext even when the variable is marked sensitive." },
  { q: "A one-line change produced Replacement: True on a production database. The lesson is…", options: ["Use the console", "Review the PLAN, and fail CI when a plan proposes replacing a stateful resource", "Never change parameters"], answer: 1,
    explain: "The diff in the source file looks harmless; the plan is where the destruction is visible." },
  { q: "DeletionPolicy: Retain protects against…", options: ["Deletion, but NOT replacement — a retained database was destroyed anyway when a change forced a replacement", "Drift", "Everything"], answer: 0,
    explain: "Use UpdateReplacePolicy as well, and treat 'forces replacement' as a review gate." },
  { q: "In CDK, renaming a construct is dangerous because…", options: ["It breaks compilation", "It changes the Region", "Logical IDs derive from the construct path, so a cosmetic rename destroys and recreates the resource"], answer: 2,
    explain: "The bucket disappears with its contents. Check the diff, not just the code." },
  { q: "Drift should be triaged as…", options: ["Always revert", "Ignore", "Revert it or ADOPT it — decided from CloudTrail — and then made impossible with an SCP so it cannot recur"], answer: 2,
    explain: "Reverting without knowing why the change was made re-creates the incident it fixed." },
  { q: "RDS encryption at rest…", options: ["Is a MIGRATION — snapshot, copy encrypted, restore, cut over: about 80 minutes plus a real maintenance window, and the restore returns defaults", "Is on by default everywhere", "Can be toggled on a running instance"], answer: 0,
    explain: "'We'll enable encryption later' quietly means a project, which is why databases created unencrypted stay that way for years." },
  { q: "Lambda environment variables are…", options: ["Encrypted from everyone", "Readable by anyone with ReadOnlyAccess — so they are not a place for secrets", "Write-only"], answer: 1,
    explain: "Use Secrets Manager or Parameter Store with a KMS key whose policy is scoped, and fetch at runtime with a short cache." },
  { q: "Secret rotation breaks services when…", options: ["The rotation function fails", "Only half of it is implemented — the secret rotates but the application read the password once at startup", "The KMS key changes"], answer: 1,
    explain: "A TTL cache plus one retry on auth failure cut failures to 1; RDS Proxy with IAM auth took it to 0." },
  { q: "Three high-severity GuardDuty findings went unread for six days while mining ran. The fix was…", options: ["Disabling GuardDuty", "Routing findings to an automated containment function that snapshots before isolating and never terminates", "More dashboards"], answer: 1,
    explain: "A detective service is not a control until its findings reach a human or an automation. Terminating destroys the forensic evidence." },
  { q: "Leaked temporary credentials cannot be deleted, so you revoke them by…", options: ["Attaching a deny conditioned on aws:TokenIssueTime, so existing sessions fail while the workload recovers on its next refresh", "Waiting", "Deleting the role"], answer: 0,
    explain: "This is the one revocation mechanism for STS sessions, and it is worth having written down before you need it." },
  { q: "The Well-Architected pillars…", options: ["Are ranked", "CONFLICT — architecture is choosing which to sacrifice, deliberately and in writing", "Reinforce each other"], answer: 1,
    explain: "Reliability wants spare capacity; cost wants less of everything. A system scoring highly on all six is usually over-built for its requirements." },
  { q: "Six components each with a respectable SLA, in series, measured…", options: ["The best component's availability", "99.32% — 293 minutes a month, with one homegrown auth service contributing 215 of them", "99.99%"], answer: 1,
    explain: "Serial dependencies multiply, and the weakest serial component dominates. Removing something from the critical path is often the cheapest availability win." },
  { q: "Going from 99.99% to 99.999% availability was priced at…", options: ["Roughly the same as the previous nine", "About $960,000 to save $3,600 of downtime — each nine costs roughly ten times the last", "Free with multi-AZ"], answer: 1,
    explain: "Compute the break-even downtime cost and record it as a dated revisit trigger; that ends the argument permanently." },
  { q: "High availability protects against a component failing. Disaster recovery is needed when…", options: ["State is destroyed or a Region is lost — Multi-AZ replicated an accidental DELETE to the standby in 11 ms", "An instance dies", "Latency rises"], answer: 0,
    explain: "A backup must be older, immutable, isolated and proven. A copy missing any of the four is storage, not a backup." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Cumulative — sampling foundations, IAM, cost, networking, compute, data, operations and architecture",
  questions: [
  { q: "A DR plan requires issuing an ACM certificate and raising a vCPU quota in the failover Region during the event. This violates…", options: ["Least privilege", "Encryption at rest", "Static stability — recovery must not depend on the control plane of the impaired thing, or on a support queue"], answer: 2,
    explain: "In the measured drill, the quota ticket alone took 3h20m of a 4h11m attempt that ultimately failed." },
  { q: "The client-observed failover time was 7m12s against a runbook claiming 90 seconds. The dominant terms were…", options: ["Health check interval", "Route 53 propagation", "The JVM DNS cache and connection pools holding sockets to dead IPs"], answer: 2,
    explain: "Fixing networkaddress.cache.ttl and pool maxLifetime brought the same failover to 1m35s with no infrastructure change." },
  { q: "DynamoDB global tables resolve concurrent cross-Region writes by…", options: ["Merging them", "Rejecting one with an error", "Last writer wins — silently, with no error, metric or log line"], answer: 2,
    explain: "Multi-active is a routing decision: pin entities to a home Region, or model data so writes cannot collide." },
  { q: "Throughput measured 8,760 req/s at 16 instances and 7,900 at 24. The correct response is…", options: ["Add more instances", "Stop and find the serialisation — past the knee, capacity costs money and makes latency worse", "Increase instance size"], answer: 1,
    explain: "The cause was a row-level lock on a shared sequence table; fixing it moved the peak beyond 64 instances, where connections became the new constraint." },
  { q: "Under 1.4× overload, admission control that rejected 6.1% of requests in 2 ms produced…", options: ["Worse outcomes", "p99 of 310 ms and 94% goodput, against 14.2 s and 61% when everything was accepted", "Identical results"], answer: 1,
    explain: "Accepting everything spent 1,277 req/s of capacity on responses that timed-out clients discarded." },
  { q: "A 4% dependency error rate became a full outage because…", options: ["The ASG scaled in", "The dependency failed completely", "Un-jittered client retries amplified load 3×, and the service stayed down 16 minutes after the dependency recovered"], answer: 2,
    explain: "Full jitter, a fleet-wide retry budget, circuit breakers and idempotency keys are the four fixes, and they compose." },
  { q: "An SCP allowing s3:* attached to an OU grants…", options: ["Nothing — SCPs only subtract", "Full S3 access", "Read access"], answer: 0,
    explain: "Permissions come from identity and resource policies; the SCP only defines the ceiling." },
  { q: "A /28 subnet gives you how many usable addresses?", options: ["14", "16", "11"], answer: 2,
    explain: "AWS reserves five addresses in every subnet, which makes small subnets fill much sooner than expected." },
  { q: "Aurora Global Database replication lag measured p50 310 ms in business hours but…", options: ["Reached 21.7 s during the nightly batch — roughly 4,000 orders of RPO", "Was unmeasurable", "Stayed under a second always"], answer: 0,
    explain: "Alarm on the p99 of replication lag and state RPO as a measured percentile with its batch-window exception." },
  { q: "A restored 2 TB RDS instance reported 'available' at 21 minutes and then…", options: ["Failed", "Served 18× normal latency for 40 minutes while EBS hydrated blocks lazily from S3", "Served normally"], answer: 1,
    explain: "Define RTO as 'meets the latency SLO', and use Fast Snapshot Restore or a warming pass when the gap matters." },
  { q: "iam:PassRole on * plus lambda:CreateFunction gives an attacker…", options: ["Nothing", "Administrator, by running code as a privileged role", "Read-only access"], answer: 1,
    explain: "Scope PassRole to specific roles; it is one of the most reliable privilege-escalation paths in AWS." },
  { q: "A 4× S3 bill was diagnosed by grouping by…", options: ["Service", "Usage type — it was PUT requests, while storage barely moved", "Region"], answer: 1,
    explain: "Service-level grouping only tells you the bill went up, which you already knew." },
  { q: "A FilterExpression that returned 12 items consumed 60,263 RCU because…", options: ["Filtering happens AFTER the read — a GSI served the same query for 1.5 RCU", "The items were large", "The table was throttled"], answer: 0,
    explain: "The ScannedCount versus Count gap is the diagnostic for paying to read and discard." },
  { q: "An ASG whose health check type is EC2…", options: ["Replaces instances with dead applications", "Cannot be used with an ALB", "Only reacts to EC2 status checks — measured capacity leaked from 6 to 3 while desired still read 6"], answer: 2,
    explain: "Use ELB health checks with a grace period long enough for boot, or you swap silent capacity loss for a boot loop." },
  { q: "Which pair of AWS facts is still commonly repeated but no longer true?", options: ["EBS snapshots are incremental", "S3 charges for requests; DynamoDB has partition limits", "S3 is eventually consistent for new objects; random key prefixes improve S3 performance"], answer: 2,
    explain: "Strong consistency arrived in 2020 and prefix randomisation stopped being necessary in 2018 — both still appear in interview answers." },
  { q: "SQS FIFO throughput was 304 msg/s on one message group and 18,420 across sixty, because the group ID controls…", options: ["Deduplication", "Ordering AND parallelism", "Retention"], answer: 1,
    explain: "One group serialises the queue regardless of consumer count." },
  { q: "The KMS key policy relative to an IAM policy granting kms:* is…", options: ["Advisory", "Authoritative — access is denied unless the key policy delegates to IAM", "Overridden by IAM"], answer: 1,
    explain: "The error names the resource-based policy, and it is the last place people look." },
  { q: "Cells with shuffle sharding — 8 cells, 2 per tenant — mean a poison-pill tenant fully affects…", options: ["All tenants", "12.5%", "About 3.6% of tenants (1 of 28 pairs)"], answer: 2,
    explain: "Plain sharding into 8 would take out 12.5%; a single shared fleet takes out 100%." },
  { q: "The most valuable output of a Well-Architected review is often…", options: ["The list of findings", "A dated, named acceptance that a finding will NOT be fixed, with its revisit trigger", "The score"], answer: 1,
    explain: "'Single-Region accepted, target already exceeded' is a decision. Without written acceptances, every trade-off is re-litigated whenever someone new asks." },
  { q: "Across the whole track, the recurring lesson about defaults is that they…", options: ["Are safe starting points", "Should never be changed", "Are optimised for getting started, not for production — data events off, average-based alarms, EC2 health checks, short pool lifetimes, gp2 sizing, T-family bursting"], answer: 2,
    explain: "Nearly every measured failure in this track began with a default that was reasonable on day one and wrong at scale." },
]},
);
