// kafka quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Schemas & Event Design",
  desc: "Formats, the registry, compatibility, keys and payload design",
  questions: [
  { q: "Why does Avro binary data need the writer's schema to decode?", options: ["It is encrypted with it", "It stores field names but not types", "The payload contains values only, in the schema's field order — no names or tags"], answer: 2,
    explain: "That is why every record carries a schema id, and why Avro resolution (reader vs writer schema) is what makes evolution work." },
  { q: "The Confluent wire format prepends…", options: ["The schema's full JSON", "A magic byte 0 and a 4-byte schema id", "A CRC and a timestamp"], answer: 1,
    explain: "A consumer reads the id, fetches and caches that schema once, and decodes with it. `Unknown magic byte!` means something bypassed the serializer." },
  { q: "The default subject naming strategy registers schemas under…", options: ["The producer's client id", "The record's class name", "`<topic>-key` and `<topic>-value`"], answer: 2,
    explain: "`RecordNameStrategy` and `TopicRecordNameStrategy` are the alternatives when several event types share a topic." },
  { q: "`auto.register.schemas=true` in production is risky because…", options: ["Any deployment can register an unreviewed schema version", "It disables compatibility checks", "It slows producers"], answer: 0,
    explain: "The compatibility check still runs, but the change was never reviewed. Register from CI and turn auto-registration off." },
  { q: "Under BACKWARD compatibility you must deploy…", options: ["Producers first", "Either order", "Consumers first"], answer: 2,
    explain: "BACKWARD means new readers can read old data. Shipping the producer first breaks consumers still on the previous schema." },
  { q: "FORWARD compatibility lets you deploy…", options: ["Only during a maintenance window", "Producers first", "Consumers first"], answer: 1,
    explain: "Old readers can read new data, so producers may lead. FULL allows either order, at the cost of a narrower set of legal changes." },
  { q: "Three pairwise-compatible schema versions can still break a replay because…", options: ["Compaction removes old schemas", "Schema ids are reused", "Non-transitive modes check only against the previous version, not all of them"], answer: 2,
    explain: "Consumers can read any version still in the log, so long-retention or compacted topics want the `*_TRANSITIVE` modes." },
  { q: "In Avro, the universally safe change is…", options: ["Renaming a field", "Changing a field's type", "Adding a field with a default"], answer: 2,
    explain: "It is both backward and forward compatible. Adding a field without a default is forward-compatible only." },
  { q: "In Protobuf, the contract is…", options: ["The field number — never reuse one; reserve removed numbers", "The message name", "The field name"], answer: 0,
    explain: "Names can change freely; reusing a number makes old records decode into the wrong field." },
  { q: "A proto3 scalar field without `optional` cannot distinguish…", options: ["Repeated from singular", "Two producers", "'Unset' from the zero value"], answer: 2,
    explain: "So `amount = 0` and 'this producer is too old to send an amount' look identical. Use `optional` where absence means something." },
  { q: "A record that cannot be deserialized blocks its partition because…", options: ["It fails inside `poll()`, before application code sees it", "It corrupts the offset index", "The broker refuses further writes"], answer: 0,
    explain: "Catch `RecordDeserializationException`, dead-letter the raw bytes and seek past exactly one record." },
  { q: "A record's key should be…", options: ["A field that groups records for analytics", "A random value for even distribution", "The immutable id of the entity whose events must stay ordered"], answer: 2,
    explain: "Keying by a mutable attribute moves an entity's events to a new partition when that attribute changes — and strands stale values on compacted topics." },
  { q: "Order lifecycle events (`OrderPlaced`, `OrderPaid`, `OrderShipped`) belong…", options: ["In one topic per event type", "In one company-wide events topic", "In one topic per aggregate, keyed by order id"], answer: 2,
    explain: "Kafka provides no ordering across topics, so separate topics let 'paid' be processed before 'placed'." },
  { q: "Delta payloads (`+50`) are dangerous in Kafka because…", options: ["At-least-once delivery makes duplicates normal, and each duplicate corrupts the total", "They compress poorly", "They cannot be compacted"], answer: 0,
    explain: "Publish the business event plus the resulting state and a version, so duplicates are harmless and stale records are detectable." },
  { q: "Ordering consumer-side logic by `occurredAt` is unreliable because…", options: ["Kafka rewrites timestamps", "Producer clocks skew and ties cannot be ordered", "Timestamps are not stored"], answer: 1,
    explain: "Use a per-entity version assigned by the single writer, in the same transaction as the change." },
  { q: "Record headers are the right place for…", options: ["Monetary amounts", "The event id and version", "Tracing and routing metadata"], answer: 2,
    explain: "Headers are not covered by the schema registry and some tools drop them, so anything business logic depends on belongs in the payload." },
  { q: "Crypto-shredding means…", options: ["Compacting a topic with tombstones", "Overwriting records with random bytes", "Encrypting personal fields per person, then deleting the key to erase them everywhere"], answer: 2,
    explain: "Tombstones remove data only from the one compacted topic; deleting the key makes every copy, including backups, unreadable." },
  { q: "Publishing raw table CDC as a public contract means…", options: ["Consumers get well-designed events", "Every database migration becomes a breaking change for consumers", "Schemas evolve automatically"], answer: 1,
    explain: "Capture an outbox of designed events instead, so the published contract is owned and versioned by the producing team." },
  { q: "A 'god topic' carrying 40 event types across the company causes…", options: ["Lower storage cost", "Better ordering guarantees", "Shared partition counts, retention and access control, with everyone reading everything"], answer: 2,
    explain: "Split by aggregate or bounded context, each owned by a team, with its own key, partition count, retention and ACLs." },
  { q: "The safest way to rename a field on a FULL_TRANSITIVE topic is…", options: ["Delete and recreate the subject", "Expand and contract: add the new field with a default, migrate consumers, then remove the old one", "Set compatibility to NONE for one release"], answer: 1,
    explain: "And the removal must wait for retention to age out records lacking the new field — on a compacted topic, until every key has been rewritten." },
]},
{ title: "Quiz 7 · Retention, Compaction & Kafka Streams",
  desc: "Cleanup policies, the log cleaner, state stores and topologies",
  questions: [
  { q: "`cleanup.policy=compact` keeps…", options: ["Records newer than `retention.ms`", "At least the latest record for every key, indefinitely", "Only the first record per key"], answer: 1,
    explain: "It models current state. `compact,delete` adds a time bound so entities untouched for a while disappear." },
  { q: "The log cleaner's offset map holds roughly how many keys with default settings?", options: ["About 5 million per pass", "Unlimited", "One per partition"], answer: 0,
    explain: "128 MB of dedupe buffer at 24 bytes per entry. More distinct keys in the dirty head means several passes to compact fully." },
  { q: "A new compacted topic still holds every update after days. The usual reason is…", options: ["Compaction is broken", "The keys are null", "The active segment has not rolled, and the dirty ratio has not been reached"], answer: 2,
    explain: "Only closed segments are eligible, and cleaning starts at `min.cleanable.dirty.ratio` (0.5). Shorten `segment.ms` on low-volume topics." },
  { q: "A tombstone is…", options: ["A record with an empty-string value", "A special admin command", "A record with a null value"], answer: 2,
    explain: "An empty string deletes nothing. The tombstone itself survives for `delete.retention.ms` after cleaning so consumers can see the deletion." },
  { q: "A stateful consumer offline longer than `delete.retention.ms`…", options: ["Rebuilds automatically", "Fails to start", "Never sees the tombstones and keeps deleted entities forever"], answer: 2,
    explain: "Make that setting longer than any plausible downtime, and have such consumers rebuild from the beginning after a long outage." },
  { q: "Compaction guarantees that a consumer reading from the start sees…", options: ["At least the latest record for each key that was not deleted", "Exactly one record per key", "Every version of every key"], answer: 0,
    explain: "The dirty head and active segment still hold duplicates, so consumers must apply 'latest value wins'." },
  { q: "A compacted topic's size is driven by…", options: ["The write rate", "The number of distinct keys times the value size", "The partition count"], answer: 1,
    explain: "Plus the dirty portion before cleaning, times the replication factor. Tiered storage does not apply to compacted topics." },
  { q: "A silently stopped log cleaner shows up as…", options: ["Failed produce requests", "Consumer lag", "Steadily growing disk use on compacted topics, including `__consumer_offsets`"], answer: 2,
    explain: "Alert on `time-since-last-run-ms` and `uncleanable-partitions-count`, not only on a disk percentage." },
  { q: "Kafka Streams is…", options: ["A separate processing cluster", "A Java library whose parallelism is the input partition count", "A broker plugin"], answer: 1,
    explain: "You scale it by running more instances of your application; coordination, state backup and fault tolerance all use Kafka itself." },
  { q: "Counting the same topic as a KStream and as a KTable gives different answers because…", options: ["KTable deduplicates by value", "KStream ignores nulls", "A KStream counts events; a KTable treats records as upserts of the latest value per key"], answer: 2,
    explain: "Events belong in a KStream, compacted state in a KTable — where a null value means delete." },
  { q: "A GlobalKTable differs from a KTable in that…", options: ["It is stored on the brokers", "Every instance holds the whole table, removing the co-partitioning requirement", "It cannot be joined"], answer: 1,
    explain: "Convenient for small reference data; every instance must load it fully at start-up, so it is unsuitable for large tables." },
  { q: "State stores are made fault-tolerant by…", options: ["Snapshotting to object storage", "Replicating RocksDB files between instances", "Writing to a compacted changelog topic"], answer: 2,
    explain: "A task moving to another instance rebuilds its store by reading that changelog — which is why restore time scales with state size." },
  { q: "The single biggest lever on Streams failover time is…", options: ["`num.standby.replicas`", "`commit.interval.ms`", "`num.stream.threads`"], answer: 0,
    explain: "A warm standby turns a restore measured in tens of minutes into seconds, at the cost of a second copy of the state." },
  { q: "Using `map()` instead of `mapValues()` before a stateful step…", options: ["Disables caching", "Is always equivalent", "Marks the stream for repartitioning: a full round trip through Kafka per record"], answer: 2,
    explain: "Streams cannot inspect the lambda, so any key-changing operator triggers it — even when the key is returned unchanged." },
  { q: "Two topics joined in Streams must be co-partitioned, meaning…", options: ["Same partition count and the same partitioner and keys", "Stored on the same brokers", "Created at the same time"], answer: 0,
    explain: "Partition counts are checked at start-up; a partitioner mismatch is not, and produces joins that silently match nothing." },
  { q: "Streams record caches mean downstream receives…", options: ["One output per input record", "Fewer, deduplicated updates per key", "Only final window results"], answer: 1,
    explain: "Correctness is unaffected — final values always arrive — but consumers must treat KTable output as a sequence of states." },
  { q: "Adding one operator to a topology reset all aggregates because…", options: ["Unnamed operators get positional names, so the state store and its changelog topic were renamed", "Changelogs expire on deploy", "The application id changed"], answer: 0,
    explain: "Name every stateful operator with `Materialized.as` / `Named.as`, and assert `topology.describe()` in a test." },
  { q: "A Streams pod is OOM-killed with no Java exception. The usual cause is…", options: ["RocksDB native memory outside the JVM heap", "A memory leak in the topology", "Too many threads"], answer: 0,
    explain: "Bound it with a `RocksDBConfigSetter` sharing one block cache and write-buffer manager, and size the container for heap plus that budget." },
  { q: "`processing.guarantee=exactly_once_v2` changes the commit interval default to…", options: ["100 milliseconds", "1 second", "30 seconds"], answer: 0,
    explain: "Shorter commits keep `read_committed` consumers' latency low, at the cost of more transaction overhead." },
  { q: "`application.id` in Kafka Streams is…", options: ["Only a logging label", "The consumer group id and the prefix of every internal topic", "The state directory name only"], answer: 1,
    explain: "Changing it starts the application over under a new identity, leaving the old changelogs orphaned." },
]},
{ title: "Quiz 8 · Time, Windows, Connect & Errors",
  desc: "Stream time, joins, CDC pipelines and failure handling",
  questions: [
  { q: "Kafka Streams advances stream time using…", options: ["The broker's log append time only", "The largest record timestamp a task has seen", "The system clock"], answer: 1,
    explain: "So an idle input freezes stream time: windows do not close and `suppress()` emits nothing until records resume." },
  { q: "A windowed aggregation stops emitting overnight with no errors. The likely cause is…", options: ["Broker disk pressure", "Stream time frozen because the input went quiet", "A rebalance loop"], answer: 1,
    explain: "Fix it with heartbeat records, a wall-clock punctuator, or by accepting continuous updates instead of suppression." },
  { q: "Hopping windows are expensive because…", options: ["Each record is written into size ÷ advance overlapping windows", "They rewrite the changelog", "They disable caching"], answer: 0,
    explain: "A 5-minute window advancing every minute stores each record five times. Sliding windows give similar resolution for far less state." },
  { q: "Session windows can change results already emitted because…", options: ["They expire early", "They ignore grace periods", "A record arriving between two sessions merges them"], answer: 2,
    explain: "The merge deletes the old sessions and writes a combined one, so downstream must apply upserts and deletes." },
  { q: "The grace period controls…", options: ["The commit interval", "How long results are cached", "How long after a window's end late records are still accepted"], answer: 2,
    explain: "Records later than that are dropped silently and counted in `dropped-records-total` — a metric worth alerting on." },
  { q: "A stream-stream join buffers…", options: ["Both sides for the whole join window", "Only the smaller side", "Nothing; it matches in memory per record"], answer: 0,
    explain: "So a 48-hour join at high volume is hundreds of gigabytes of state — model it as a KTable with punctuated expiry instead." },
  { q: "A stream-table join enriches with…", options: ["The table's oldest value", "The table's current value, unless versioned stores are used", "The table's value as of the event's timestamp, always"], answer: 1,
    explain: "A lagging stream is therefore enriched with later data, and reprocessing gives different answers." },
  { q: "The most common Kafka Connect failure is…", options: ["Worker rebalances", "Insufficient tasks", "Converter mismatch between what was produced and what the connector expects"], answer: 2,
    explain: "And the key converter is the one most often forgotten, producing an error that names the value's classes." },
  { q: "A Connect cluster stores its connector configs, source offsets and status…", options: ["In three compacted Kafka topics", "On each worker's disk", "In the connectors themselves"], answer: 0,
    explain: "That is why workers are stateless and tasks move when one dies — and why those topics must be compacted and replicated." },
  { q: "Renaming a source connector causes a full re-ingest because…", options: ["Source offsets are keyed by connector name", "The target topic is recreated", "Configs are versioned by name"], answer: 0,
    explain: "Migrate the offsets (recent versions expose REST endpoints for it) or keep the name." },
  { q: "Dead-letter queues in Connect are available for…", options: ["Sink connectors only", "Both", "Source connectors only"], answer: 0,
    explain: "Enable `errors.tolerance=all` with `errors.deadletterqueue.context.headers.enable=true`, or the DLQ is a topic of bytes with no story." },
  { q: "Query-based CDC (a JDBC source) misses…", options: ["Deletes, and intermediate updates between polls", "Only schema changes", "Nothing important"], answer: 0,
    explain: "It can also skip rows committed out of order once the timestamp cursor has passed them. Log-based CDC reads the WAL or binlog instead." },
  { q: "A stopped Debezium connector can take down a Postgres database because…", options: ["It exhausts connections", "Its replication slot makes the server retain WAL until it is consumed", "It holds table locks"], answer: 1,
    explain: "Alert on slot lag, set `max_slot_wal_keep_size` as a backstop, and drop slots for retired connectors." },
  { q: "Debezium heartbeats matter when…", options: ["The network is unreliable", "The connector runs in Kubernetes", "The captured tables are quiet but the database is busy, so the slot never advances"], answer: 2,
    explain: "Without them, WAL accumulates for a slot that has nothing to report — a quiet weekend fills the disk." },
  { q: "The first question in error handling is…", options: ["How many retries?", "Which DLQ topic?", "Is this bad data or a bad dependency?"], answer: 2,
    explain: "Bad data must be dead-lettered; a bad dependency must be waited out. Treating one as the other causes the worst outcomes." },
  { q: "Sleeping between retries inside the poll loop…", options: ["Burns the `max.poll.interval.ms` budget and gets the consumer removed", "Blocks only that partition", "Is the recommended backoff"], answer: 0,
    explain: "Pause the partitions, keep calling `poll()`, and resume when the backoff expires — that keeps membership and ordering intact." },
  { q: "Retry topics trade away…", options: ["Ordering for the retried records", "Durability", "Throughput"], answer: 0,
    explain: "Fine for independent records; wrong for lifecycle events, where a retried `OrderPaid` can be overtaken by `OrderShipped`." },
  { q: "A dead-letter record should carry…", options: ["The original key and raw value bytes plus context headers", "Only the exception message", "A re-serialized object"], answer: 0,
    explain: "The record may have failed because it could not be deserialized; re-serializing would fail too. Headers carry topic, partition, offset and the error." },
  { q: "During a four-minute database outage, a consumer that dead-letters after three retries will…", options: ["Pause automatically", "Move the entire stream into the DLQ at full rate", "Protect the pipeline"], answer: 1,
    explain: "Circuit-break instead: above a high error ratio, pause all partitions and probe, so valid records simply wait." },
  { q: "Retrying hard into a failing dependency…", options: ["Has no effect", "Speeds recovery", "Multiplies load and prevents recovery"], answer: 2,
    explain: "Three retries per record turns 6,000 requests per second into 24,000. Pausing removes the load, which is what a recovering system needs." },
]},
{ title: "Quiz 9 · Operations: Cluster, Capacity, Performance & Security",
  desc: "KRaft, sizing, latency diagnosis, monitoring and access control",
  questions: [
  { q: "In KRaft, cluster metadata is…", options: ["A Kafka log replicated by a Raft quorum of controllers", "Held only in each broker's memory", "Stored in ZooKeeper"], answer: 0,
    explain: "Brokers are observers that fetch and apply metadata records, which is why controller failover no longer reloads everything." },
  { q: "Five controllers instead of three buys…", options: ["Tolerance of two controller losses instead of one", "More partitions per cluster", "Faster metadata writes"], answer: 0,
    explain: "Even numbers add nothing: four need three for a majority, the same as five, with more replication work." },
  { q: "A broker fails to start with `InconsistentClusterIdException`. On a broker holding real replicas you should…", options: ["Wipe and reformat it", "Change its node id", "Investigate why its configuration points at another cluster — never wipe"], answer: 2,
    explain: "Reformatting destroys its replicas, which must then be rebuilt from leaders — hours of replication and real risk." },
  { q: "When the controller quorum loses its majority…", options: ["Existing leaders keep serving, but no leader election, registration or topic change can happen", "Consumers fail first", "Everything stops immediately"], answer: 0,
    explain: "It looks healthy until the next failure, when those partitions go offline and stay there — a latent outage." },
  { q: "A broker that stops heartbeating for `broker.session.timeout.ms` is…", options: ["Fenced: its partitions move and it must re-register", "Ignored until it returns", "Restarted by the controller"], answer: 0,
    explain: "9 seconds by default, so long GC pauses cause partition movement and latency spikes as well as ISR churn." },
  { q: "`metadata.version` should be raised…", options: ["Automatically on restart", "Before rolling the software", "Only after every controller and broker runs the new release"], answer: 2,
    explain: "Otherwise nodes on the old release cannot rejoin. Treat a finalized version as one-way and soak before finalizing." },
  { q: "Cluster egress with RF 3 and three consumer groups, at 100 MB/s ingress, is roughly…", options: ["100 MB/s", "500 MB/s", "300 MB/s"], answer: 1,
    explain: "200 MB/s of replication plus 300 MB/s of consumer traffic. A fourth group adds another 100 MB/s — groups are a capacity decision." },
  { q: "The dominant restart cost on a partition-heavy broker is…", options: ["Log recovery after an unclean shutdown", "Rebuilding the page cache", "Reconnecting clients"], answer: 0,
    explain: "Each log is checked and recovered; raising `num.recovery.threads.per.data.dir` helps, and a clean shutdown skips it entirely." },
  { q: "A three-zone cluster should run at what steady-state utilisation?", options: ["80–90%", "Whatever the dashboards allow", "50–60% at peak"], answer: 2,
    explain: "Losing a zone concentrates traffic on the survivors, adds leadership, reconnecting consumers and later re-replication." },
  { q: "A benchmark that only reads the head of the log is misleading because…", options: ["It uses too few partitions", "It ignores compression", "Everything is served from the page cache; real catch-up reads hit disk and raise everyone's tail latency"], answer: 2,
    explain: "Include a consumer reading from the earliest offset, and kill a broker mid-run — those numbers set your real headroom." },
  { q: "Produce latency is high and `RemoteTimeMs` dominates the request breakdown. That means…", options: ["The client is slow to read responses", "Handler threads are saturated", "The leader is waiting for in-sync followers"], answer: 2,
    explain: "Find the slow broker from ISR shrink events, then look at its disk latency and GC pauses." },
  { q: "Raising `linger.ms` under heavy load can…", options: ["Only increase latency", "Disable compression", "Lower p99 latency and raise throughput by replacing many small requests with fewer full ones"], answer: 2,
    explain: "At low load it simply adds the wait. The producer's `batch-size-avg` and `record-queue-time-avg` say which side of the curve you are on." },
  { q: "A broker should have a small JVM heap because…", options: ["Heap memory is slower than disk", "Kafka is single-threaded", "The page cache does the caching, and large heaps lengthen GC pauses"], answer: 2,
    explain: "A pause longer than the session timeout or `replica.lag.time.max.ms` also causes fencing and ISR churn, not just latency." },
  { q: "Raising `fetch.min.bytes` on a low-volume topic…", options: ["Reduces latency", "Has no effect", "Adds up to `fetch.max.wait.ms` (500 ms) to every fetch"], answer: 2,
    explain: "The broker waits for data that never accumulates. Leave it at 1 unless the topic is genuinely busy." },
  { q: "`ActiveControllerCount` should be alerted on as…", options: ["A cluster-wide sum of exactly 1", "Greater than zero per node", "Zero on every node"], answer: 0,
    explain: "A per-node alert fires on every healthy follower. Zero means no controller; two means split brain." },
  { q: "A consumer group reporting zero lag may still be broken because…", options: ["Lag is always delayed", "A group with no members reports its last committed offsets", "Lag ignores the newest partition"], answer: 1,
    explain: "Alert on member count and last-poll age too — and remember `auto.offset.reset=latest` can put a group at the end after skipping data." },
  { q: "Kafka client metric cardinality explodes mainly because of…", options: ["Per-partition and per-topic dimensions multiplied by client instances", "Too many brokers", "JMX polling frequency"], answer: 0,
    explain: "Keep per-partition series for lag, aggregate the rest, and enforce it with an exporter allowlist." },
  { q: "A consumer with only a topic ACL fails with `GroupAuthorizationException`. It needs…", options: ["Read on the consumer group", "Cluster-level Describe", "Write on the topic"], answer: 0,
    explain: "The group is its own resource. Prefixed ACLs per team keep this manageable across many topics and groups." },
  { q: "With mTLS, an ACL for `User:orders-service` does not match because…", options: ["The principal is the certificate's full DN unless `ssl.principal.mapping.rules` maps it", "mTLS cannot be used with ACLs", "ACLs need the client id"], answer: 0,
    explain: "Authorizer denial logs show the principal the broker actually sees — the fastest way to settle it." },
  { q: "Kafka quotas enforce limits by…", options: ["Rejecting requests over the limit", "Delaying responses so the client slows down", "Closing the connection"], answer: 1,
    explain: "Throttle time appears in both client and broker metrics. Quotas are fairness and stability, not a security boundary." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Twenty interview-difficulty questions drawn from the whole track",
  questions: [
  { q: "A producer gets acknowledgements, a broker dies, and records are missing. Which configuration combination explains it?", options: ["`acks=all` with idempotence enabled", "`acks=all` with `min.insync.replicas=1` while followers were out of the ISR", "`acks=all` with RF 3 and `min.insync.replicas=2`"], answer: 1,
    explain: "The leader acknowledged alone. `acks=1` and unclean leader election are the other two routes to the same outcome." },
  { q: "A monthly batch job silently processed only the last hour of data. Why?", options: ["The topic was compacted", "Its consumer group's offsets expired after 7 days of being empty, and it reset to latest", "Its partition was reassigned"], answer: 1,
    explain: "Occasional jobs should choose their start position explicitly — by timestamp — rather than relying on committed offsets surviving." },
  { q: "Which change breaks per-key ordering for existing keys?", options: ["Enabling compression", "Adding partitions to a keyed topic", "Increasing the replication factor"], answer: 1,
    explain: "The modulus changes, so most keys move; old and new events for a key then sit in different partitions." },
  { q: "A pipeline shows duplicate database rows after every consumer rebalance. The best fix is…", options: ["Make the writes idempotent, keyed by a stable event id", "Switch to `acks=1`", "Disable rebalancing"], answer: 0,
    explain: "At-least-once delivery makes duplicates normal. Alternatively store offsets in the same database transaction as the results." },
  { q: "`read_committed` consumers stall while the partition's high watermark keeps rising. The cause is…", options: ["An open or hanging transaction holding the last stable offset", "A compaction backlog", "Consumer lag"], answer: 0,
    explain: "Diagnose with `kafka-transactions.sh describe-producers`; abort it if the coordinator's timeout will not." },
  { q: "One partition's lag grows while eleven others are flat. The first hypothesis should be…", options: ["Network saturation", "Broker disk failure", "A poison record blocking that partition, or a hot key"], answer: 2,
    explain: "Which is why lag alerts must be per partition: the group's total barely moves while an eighth of capacity is stopped." },
  { q: "A team wants Kafka for image-processing jobs with retries, delays and priorities. The correct response is…", options: ["Use Kafka with retry topics for everything", "Use a queue for the work, and Kafka for the facts that result", "Increase the partition count"], answer: 1,
    explain: "Those are queue features; Kafka has no per-message ack, delay or priority, and one slow job blocks its partition." },
  { q: "After a routine deploy, a Streams application's counts restart from zero. The cause is usually…", options: ["The changelog topic was compacted", "Unnamed operators renamed the state store and its changelog", "Standby replicas took over"], answer: 1,
    explain: "Name every stateful operator explicitly and assert `topology.describe()` in a test so topology changes fail review, not production." },
  { q: "Disk on three brokers grows steadily although traffic is unchanged. The first thing to check is…", options: ["Producer batch sizes", "Log cleaner health and retention on the oldest segments", "Consumer group count"], answer: 1,
    explain: "A stopped cleaner or a future-dated timestamp pinning segments both produce a linear climb with no other symptom." },
  { q: "Admin commands hang while produce and consume are unaffected. This points at…", options: ["The controller quorum lacking a majority", "An expired certificate", "Slow disks on the brokers"], answer: 0,
    explain: "The data plane runs on existing leaders; the control plane cannot commit metadata. Check `kafka-metadata-quorum.sh describe --status` first." },
  { q: "Every client lost access at 02:00 with TLS handshake failures. The most likely cause is…", options: ["A quota misconfiguration", "A broker disk filling", "An expired certificate or CA"], answer: 2,
    explain: "Rotate trust first (distribute the new CA), then present new certificates — the reverse order breaks every client simultaneously." },
  { q: "A schema change passed the registry check, yet consumers broke on release. The usual reason is…", options: ["The deployment order did not match the compatibility mode", "The registry was down", "The schema id changed"], answer: 0,
    explain: "BACKWARD requires consumers first. Non-transitive modes and semantic changes are the other two common explanations." },
  { q: "Consumers on an Avro topic fail with `Unknown magic byte!`. That means…", options: ["The schema registry is unavailable", "The topic is compacted", "Something produced records without the registry wire format, such as plain JSON"], answer: 2,
    explain: "Restrict who may produce with ACLs, dead-letter undecodable records, and use broker-side schema validation where available." },
  { q: "Cross-zone data transfer costs more than the brokers. The biggest single lever is…", options: ["Follower fetching so consumers read a same-zone replica", "Shorter retention", "Reducing the replication factor"], answer: 0,
    explain: "Consumer traffic is multiplied by the number of groups, and two-thirds of it crosses zones by default with leader-only fetching." },
  { q: "The best primary SLO for an event pipeline is…", options: ["Broker CPU below 70%", "End-to-end record age at processing", "Messages produced per second"], answer: 1,
    explain: "Every failure mode in the track shows up in it, and it is expressed in units the business understands." },
  { q: "Failing over consumers to a MirrorMaker 2 target cluster requires…", options: ["Offset translation from checkpoints, and idempotent consumers", "Recreating the consumer groups", "Nothing; offsets are identical"], answer: 0,
    explain: "The target topic is a different log with its own offsets, and translation is only as precise as the checkpoint interval." },
  { q: "Active-active replication across regions is safe when…", options: ["Writes are partitioned by region so each owns its keys", "Topics use identity naming", "Both regions write the same entities"], answer: 0,
    explain: "Kafka resolves no conflicts. Identity naming without cycle protection also makes records loop and multiply." },
  { q: "A cluster's replication lag to its DR region is your…", options: ["RTO", "SLA", "RPO"], answer: 2,
    explain: "It is exactly how much data a region loss would cost. Measure it continuously from the heartbeat topic and alert well inside the objective." },
  { q: "312 topics exist and 268 have exactly one consumer group. The best recommendation is…", options: ["Stop the default: route new low-volume single-consumer integrations to simpler options", "Merge them into one topic", "Remove Kafka entirely"], answer: 0,
    explain: "Over-application is more common than a wrong choice. Keep Kafka for the topics that use retention, replay and fan-out." },
  { q: "The thread connecting most Kafka incidents is…", options: ["Client library bugs", "Assuming a broader guarantee than Kafka actually gives", "Insufficient hardware"], answer: 1,
    explain: "Acknowledged is not durable by default, delivery is not once, ordering is not global, and a schema is only a contract if something enforces it." },
]},
);
