// kafka quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations: The Log, Not a Queue",
  desc: "Offsets, retention, partitions, KRaft, and what Kafka guarantees",
  questions: [
  { q: "What happens to a record when a consumer reads it?", options: ["It is marked invisible for a visibility timeout", "It is deleted once the consumer acknowledges it", "Nothing — the consumer's offset advances; the record stays until retention removes it"], answer: 2,
    explain: "Reading moves a position. Records leave only when retention (or compaction) removes them, whether or not anyone read them — which is why fan-out and replay are cheap." },
  { q: "A second team wants the same topic's data. What does that cost?", options: ["A new consumer group; no extra storage", "A copy of every record into a second topic", "A new partition per consumer"], answer: 0,
    explain: "Groups are independent and each tracks its own offsets. The cost is broker egress, not storage — which is why a new consumer group is still a capacity decision." },
  { q: "Kafka orders records…", options: ["By producer timestamp across the cluster", "Within a partition only", "Globally across a topic"], answer: 1,
    explain: "Ordering is per partition. Two records with different keys may land in different partitions, and there is no defined order between them." },
  { q: "A consumer group is stopped for 10 days with default settings and then restarts. What is the likely result?", options: ["It throws an error and refuses to start", "It silently jumps to the end of the log and skips everything in between", "It resumes exactly where it stopped"], answer: 1,
    explain: "Offsets expire after 7 days of an empty group, and retention is 7 days by default; with `auto.offset.reset=latest` the consumer starts at the end. One INFO log line is the only trace." },
  { q: "Why does `min.insync.replicas=1` undermine `acks=all`?", options: ["It disables replication entirely", "It forces acks=1 on the producer", "It lets the leader acknowledge alone when followers fall out of the ISR"], answer: 2,
    explain: "`acks=all` waits for the current ISR. If the ISR has shrunk to just the leader, 'all' means one copy — and losing that broker loses acknowledged writes." },
  { q: "Which is NOT a reason Kafka is fast?", options: ["Sequential appends and the OS page cache", "Keeping all recent records in the JVM heap for fast lookup", "Zero-copy transfer on plaintext connections"], answer: 1,
    explain: "Kafka deliberately does not cache in the heap — the page cache does it. That is why brokers run small heaps and why a large heap hurts throughput." },
  { q: "TLS reduces Kafka throughput partly because…", options: ["It disables zero-copy: data must be encrypted in user space", "It forces acks=all", "It doubles the replication factor"], answer: 0,
    explain: "`sendfile` cannot be used when bytes must be encrypted by the JVM, so TLS costs both CPU and the zero-copy path. Budget for it rather than disabling it." },
  { q: "A client connects to `bootstrap.servers` successfully, then every produce times out. The most likely cause is…", options: ["Wrong ACLs on the topic", "An expired consumer group", "`advertised.listeners` pointing at an address the client cannot reach"], answer: 2,
    explain: "Bootstrap succeeds on the address you typed; metadata then sends the client to the advertised address. In Docker or Kubernetes that is commonly `localhost`." },
  { q: "Kafka 4.0 and ZooKeeper:", options: ["ZooKeeper is optional but recommended", "ZooKeeper support was removed entirely; 4.x is KRaft-only", "ZooKeeper is required for ACLs only"], answer: 1,
    explain: "KRaft became production-ready in 3.3 and 4.0 dropped ZooKeeper. Clusters had to migrate on a 3.x release (3.9 being the bridge) before upgrading." },
  { q: "Retention deletes data by…", options: ["Removing individual expired records", "Rewriting the log without old records", "Deleting whole closed segments"], answer: 2,
    explain: "Deletion works on closed segment files, and the active segment is never deleted — so a quiet topic can hold data well past `retention.ms`." },
  { q: "Which workload fits Kafka WORST?", options: ["Change data capture from a database", "Image-processing jobs needing per-job retry, delay and priority", "Events consumed by five independent teams"], answer: 1,
    explain: "Per-message retries, delays and priorities are queue features. In Kafka one slow job blocks its partition and parallelism is capped by partition count." },
  { q: "A consumer group is stalled and producers are unaffected. Why?", options: ["The broker pauses the topic", "Kafka applies backpressure to producers when consumers lag", "Consumers never slow producers; lag simply grows"], answer: 2,
    explain: "That isolation is valuable and dangerous: nothing complains on your behalf, which is why lag is the signal you must alert on." },
  { q: "`auto.offset.reset=earliest` after an offset becomes invalid means…", options: ["Failing with an exception", "Skipping to the newest record", "Reprocessing from the oldest retained record"], answer: 2,
    explain: "`earliest` loses only what retention already deleted; `latest` additionally skips everything still retained. `none` throws so a human decides." },
  { q: "Which statement about Kafka's exactly-once is accurate?", options: ["It is scoped to Kafka-to-Kafka work: outputs and input offsets commit atomically", "It covers any sink, including databases and APIs", "It removes the need for idempotent consumers everywhere"], answer: 0,
    explain: "Transactions make a consume-transform-produce loop atomic inside Kafka. External effects need their own idempotency." },
  { q: "The broker's `auto.create.topics.enable=true` is risky because…", options: ["It creates topics with default, often unsafe settings on a typo", "It prevents topic deletion", "It disables ACLs"], answer: 0,
    explain: "A misspelled topic name silently becomes a real topic, frequently with replication factor 1 — and consumers then report zero lag on an empty topic forever." },
  { q: "Disk sizing for a topic is…", options: ["Ingress × retention × replication factor, plus headroom", "Number of partitions × segment size", "Ingress × retention"], answer: 0,
    explain: "Every byte exists RF times. Measure the compressed rate, since the broker stores what the producer sent." },
  { q: "What is the practical effect of a partition being the unit of parallelism?", options: ["Partitions are split between consumers dynamically mid-record", "Each consumer reads every partition", "More consumers than partitions leaves some idle"], answer: 2,
    explain: "One partition is read by exactly one member of a group, so the partition count caps a group's parallelism." },
  { q: "A record's key primarily determines…", options: ["Its partition, and therefore what it is ordered with", "Its compression codec", "Its retention period"], answer: 0,
    explain: "The key decides the partition through hashing, which decides ordering scope — and on compacted topics it is the identity compaction keeps." },
  { q: "Kafka's durability comes mainly from…", options: ["RAID on broker disks", "fsync on every write", "Replication to other brokers' page caches"], answer: 2,
    explain: "Kafka leaves flushing to the OS; an acknowledged record lives in the page cache of every in-sync replica. That is why replicas must sit in independent failure domains." },
  { q: "Which is the best first alert for a Kafka pipeline?", options: ["Consumer lag measured in time, per group", "Number of topics in the cluster", "Broker CPU above 80%"], answer: 0,
    explain: "Time lag maps to the business requirement and catches nearly every failure mode. CPU is a cause metric, useful once you are already investigating." },
]},
{ title: "Quiz 2 · Partitions, Segments & Producers",
  desc: "On-disk layout, batching, keys, and how send() really behaves",
  questions: [
  { q: "A partition on disk is…", options: ["A directory of segment files, each named after its first offset", "One large append-only file", "A database table with an index"], answer: 0,
    explain: "Segments are what make deletion cheap (unlink a whole file) and what the active-segment rule applies to." },
  { q: "Kafka's offset index is sparse because…", options: ["A full index would be nearly as large as the log; one entry per ~4 KB stays in memory", "Offsets are not unique", "It only indexes compacted records"], answer: 0,
    explain: "A lookup binary-searches the sparse index, then scans forward a few kilobytes — cheap, and the index stays memory-mapped." },
  { q: "The unit Kafka stores, compresses and replicates is…", options: ["The individual record", "The segment", "The record batch"], answer: 2,
    explain: "Offsets and timestamps are deltas from the batch base, so the broker can assign offsets by writing one `baseOffset` — and compression works across the whole batch." },
  { q: "Why can a consumer not read a record the leader already has?", options: ["It must wait for the high watermark, which is the minimum log end offset across the ISR", "Consumers read only from followers", "The record has not been fsynced yet"], answer: 0,
    explain: "Hiding records above the high watermark means a consumer never sees data that a leader failover could erase." },
  { q: "On a transactional or compacted topic, consumer offsets are…", options: ["Always consecutive", "Reset on every commit", "Increasing but with gaps, so they are not a record count"], answer: 2,
    explain: "Control records take offsets and compaction removes records, so 'end offset minus start offset' is an upper bound, not a count." },
  { q: "The Java client sends a keyed record to…", options: ["`murmur2(keyBytes) % numPartitions`", "A random partition", "The partition with the smallest lag"], answer: 0,
    explain: "The hash is over the serialized key bytes — so the same logical key serialized differently lands elsewhere." },
  { q: "A Python (librdkafka) producer and a Java producer write the same keys to one topic. What goes wrong by default?", options: ["librdkafka defaults to a CRC32-based partitioner, so keys split across partitions", "Nothing; the partitioners match", "The Python client cannot write keys"], answer: 0,
    explain: "Set `partitioner=murmur2_random` on librdkafka clients, and test it: per-key ordering silently disappears otherwise." },
  { q: "Going from 6 to 8 partitions on a keyed topic, roughly what share of keys keeps its partition?", options: ["100%", "75%", "25%"], answer: 2,
    explain: "A key stays only when `h % 6 == h % 8`, true for 6 of every 24 hash values. The other 75% move, breaking per-key order during the change." },
  { q: "A hot partition caused by a skewed key is fixed by…", options: ["Adding partitions", "Adding consumers", "Changing the key, for example by salting the large tenant into buckets"], answer: 2,
    explain: "The hot key hashes to one partition however many exist, and only one consumer may read it. Salting trades some ordering for spread." },
  { q: "Time-based retention uses which timestamp in a segment?", options: ["The largest", "The oldest", "The broker's clock at deletion"], answer: 0,
    explain: "So one record stamped years in the future pins its segment — and, since deletion runs oldest-first, blocks everything behind it." },
  { q: "`producer.send()` can block the calling thread when…", options: ["Never — it is fully asynchronous", "The topic has more than 100 partitions", "It is waiting for metadata or for buffer space, up to `max.block.ms`"], answer: 2,
    explain: "60 seconds by default. On an HTTP request thread that is an outage; lower it and decide deliberately what to do on failure." },
  { q: "A batch is sent when…", options: ["Only when `batch.size` is reached", "After every record", "`batch.size` is reached or `linger.ms` elapses, whichever first"], answer: 2,
    explain: "And batching is per partition, so keyed traffic spread over many partitions barely batches without a longer linger." },
  { q: "Calling `send(record).get()` for every record…", options: ["Caps throughput at roughly one round trip per record", "Improves durability", "Enables idempotence"], answer: 0,
    explain: "One record per batch, one request in flight. Send asynchronously and wait on the futures together if confirmation is needed." },
  { q: "Compression ratio depends most on…", options: ["Batch size — a batch of one record barely compresses", "The partition count", "The codec alone"], answer: 0,
    explain: "Fix batching before choosing a codec; compressing one-record batches is mostly wasted CPU." },
  { q: "`delivery.timeout.ms` is…", options: ["How long the buffer may hold records", "The time to wait for one request's response", "The total time from send() to the callback, including retries, after which the record is dropped"], answer: 2,
    explain: "It must be at least `linger.ms + request.timeout.ms`, and the producer refuses to start otherwise." },
  { q: "Setting `acks=1` without setting `enable.idempotence` explicitly causes…", options: ["Retries to be disabled", "Idempotence to be silently disabled", "A startup error"], answer: 1,
    explain: "The producer resolves the conflict quietly. Setting `enable.idempotence=true` explicitly turns the downgrade into a startup failure instead." },
  { q: "Producer callbacks run on…", options: ["The single sender (I/O) thread — so slow callbacks stall every send", "A pool of callback threads", "The application thread that called send()"], answer: 0,
    explain: "A database write in a callback becomes a Kafka outage under load: the sender stops sending, the buffer fills, and send() blocks." },
  { q: "Records still in the accumulator when a process is killed are…", options: ["Lost, and their callbacks never run", "Retried on next startup", "Recovered by the broker"], answer: 0,
    explain: "Close with a deadline shorter than the platform's kill timeout so failures surface through callbacks instead of vanishing." },
  { q: "The idempotent producer prevents duplicates caused by…", options: ["Application-level resends after a crash", "Consumers reprocessing after a rebalance", "The producer's own retries within one session"], answer: 2,
    explain: "Producer id, epoch and per-partition sequence numbers let the broker discard a batch it already wrote. Across restarts it is a new producer id." },
  { q: "Raising the broker's `message.max.bytes` alone lets a 5 MB record through?", options: ["Yes", "No — producer, topic and consumer limits must all allow it, and replication must fetch it", "Only for compacted topics"], answer: 1,
    explain: "Limits apply along the whole path. A record that large usually belongs in object storage with a reference in the event." },
]},
{ title: "Quiz 3 · Consumers, Groups & Rebalancing",
  desc: "The poll loop, assignment, lag, and the two liveness checks",
  questions: [
  { q: "What does `poll()` do besides returning records?", options: ["Commits offsets synchronously every time", "Only fetches data", "Joins the group, handles rebalances, proves progress, and may auto-commit"], answer: 2,
    explain: "The first `poll()` is what makes a consumer a group member, and calling it is what proves the consumer is still working." },
  { q: "A `KafkaConsumer` shared between two threads…", options: ["Works if both only read", "Throws `ConcurrentModificationException` — only `wakeup()` is safe from another thread", "Automatically synchronises"], answer: 1,
    explain: "One consumer per thread; `wakeup()` makes a blocked poll throw `WakeupException`, which is the standard shutdown path." },
  { q: "A consumer killed without `close()` leaves its partitions unread for…", options: ["About `session.timeout.ms` (45 s by default)", "A second or two", "Until an operator intervenes"], answer: 0,
    explain: "A clean close sends a leave-group request and triggers an immediate rebalance; a kill waits for missed heartbeats." },
  { q: "With 6 partitions and 8 consumers in one group…", options: ["Six consumers work and two are idle", "Each consumer gets 0.75 partitions", "The group refuses to start"], answer: 0,
    explain: "A partition goes to exactly one member. Extra members are standbys that still cause rebalances when they come and go." },
  { q: "Consumer memory peaks when…", options: ["The consumer is caught up", "It is catching up after an outage and every fetch returns full", "It commits offsets"], answer: 1,
    explain: "Worst case is roughly min(partitions × `max.partition.fetch.bytes`, brokers × `fetch.max.bytes`) — sized from a quiet day, it OOMs exactly when needed most." },
  { q: "The committed offset is…", options: ["The last record processed", "The first record of the current batch", "The next record the group should read"], answer: 2,
    explain: "Commit last processed + 1. Committing the last processed offset reprocesses one record on every restart." },
  { q: "Which lag measurement catches one stuck partition?", options: ["Average lag per topic", "Total lag per group", "Max lag across the group's partitions"], answer: 2,
    explain: "One stalled partition among twelve barely moves a total. Express it in time, too, so one threshold means the same on every topic." },
  { q: "A consumer is removed from its group while clearly still running because…", options: ["Its session timed out despite heartbeats", "Processing a batch took longer than `max.poll.interval.ms`", "It committed offsets too often"], answer: 1,
    explain: "There are two liveness checks: heartbeats (session) and progress (poll interval). Busy-but-alive fails the second." },
  { q: "The right fix for batches that exceed the poll interval is…", options: ["Raise `max.poll.interval.ms` first", "Increase `session.timeout.ms`", "Lower `max.poll.records` or make per-record work faster"], answer: 2,
    explain: "Raising the interval also delays detection of genuinely stuck consumers — and lengthens every rebalance in the classic protocol." },
  { q: "To apply backpressure while a downstream system recovers, a consumer should…", options: ["Close and reopen the consumer", "`pause()` the partitions and keep calling `poll()`", "Sleep inside the loop"], answer: 1,
    explain: "Pausing keeps group membership alive indefinitely; sleeping burns the poll budget and triggers a rebalance." },
  { q: "Keyed parallel workers inside a consumer must commit…", options: ["The highest finished offset", "The lowest offset not yet finished", "Nothing until shutdown"], answer: 1,
    explain: "Committing the highest finished offset skips records still in flight below it after a crash." },
  { q: "Follower fetching (`client.rack`) mainly reduces…", options: ["Consumer lag", "Rebalance frequency", "Cross-zone data transfer cost"], answer: 2,
    explain: "Consumers read a same-zone replica. Reads still stop at the high watermark, so consistency is unchanged; latency rises slightly." },
  { q: "Which does NOT trigger a rebalance?", options: ["A regex subscription matching a new topic", "A member joining or leaving", "A consumer committing offsets"], answer: 2,
    explain: "Commits are ordinary requests. Membership and subscription changes — and timeouts — are what rebalance a group." },
  { q: "With an eager assignor, a rebalance pauses…", options: ["Every partition in the group", "Only the partitions that move", "Nothing; consumption continues"], answer: 0,
    explain: "Members revoke everything before rejoining. Cooperative sticky revokes only what moves, at the cost of a second round." },
  { q: "During a classic-protocol rebalance, one member stuck in a 90-second batch…", options: ["Holds up the whole group's rebalance, up to `max.poll.interval.ms`", "Is removed immediately", "Has no effect on others"], answer: 0,
    explain: "The coordinator waits for every known member to rejoin, and a member rejoins only on its next `poll()`." },
  { q: "Since Kafka 3.0 the default assignor list allows switching to cooperative sticky with…", options: ["A full cluster restart", "Two rolling bounces", "One rolling bounce removing the range assignor"], answer: 2,
    explain: "The default `[RangeAssignor, CooperativeStickyAssignor]` already advertises cooperative support; an explicitly eager list still needs two bounces." },
  { q: "Static membership (`group.instance.id`) trades…", options: ["No rebalance on restart, for slower detection of a genuinely dead member", "Ordering for throughput", "Durability for latency"], answer: 0,
    explain: "The session timeout must cover a restart, and that same timeout is how long a dead member's partitions sit unread." },
  { q: "The KIP-848 consumer protocol, GA in Kafka 4.0, changes rebalancing by…", options: ["Making all assignments static", "Removing consumer groups", "Moving assignment to the broker and reconciling incrementally, with no group-wide barrier"], answer: 2,
    explain: "Members converge through heartbeats; session and heartbeat settings move to the broker. Opt in with `group.protocol=consumer`." },
  { q: "Autoscaling consumers on record lag can make lag worse because…", options: ["Kafka throttles new consumers", "Each scaling action causes a rebalance, which pauses consumption", "Lag metrics are delayed by an hour"], answer: 1,
    explain: "Cap replicas at the partition count, scale on time lag with stabilisation windows, and use cooperative or KIP-848 rebalancing." },
  { q: "A group with 12 members shows one member holding 0 partitions. That means…", options: ["The cluster is unhealthy", "More members than partitions, or a subscription matching nothing", "The member is the group leader"], answer: 1,
    explain: "Check the subscribed topic names: a typo with broker auto-creation on produces an empty topic and a member with nothing to do." },
]},
{ title: "Quiz 4 · Replication & Durability",
  desc: "ISR, acks, leader election, and surviving a zone loss",
  questions: [
  { q: "Followers replicate by…", options: ["Sending fetch requests to the leader, like consumers", "Receiving pushes from the leader", "Reading the leader's disk directly"], answer: 0,
    explain: "A follower's fetch offset tells the leader how far it has replicated — that is how the high watermark is computed." },
  { q: "A replica leaves the ISR when…", options: ["Its disk is more than 80% full", "It misses a single fetch", "It has not caught up to the leader's log end offset within `replica.lag.time.max.ms`"], answer: 2,
    explain: "30 seconds by default. A replica that is alive but stalled therefore holds up `acks=all` writes for up to that long." },
  { q: "Producer latency spikes to ~30 s for some partitions and then recovers. The most likely cause is…", options: ["A network partition between clients and brokers", "A broker alive but stalled, still in the ISR until `replica.lag.time.max.ms` expires", "Consumer rebalancing"], answer: 1,
    explain: "Look for 'Shrinking ISR' log lines naming the broker, then check its GC pauses and disk latency." },
  { q: "With RF 3, `min.insync.replicas=2` and `acks=all`, the cluster tolerates…", options: ["Two broker losses for writes", "One broker loss for both writes and acknowledged data", "No broker loss"], answer: 1,
    explain: "Writes are accepted while the ISR has 2; acknowledged data exists on at least 2 brokers. It is the standard production choice." },
  { q: "Setting `min.insync.replicas` equal to the replication factor means…", options: ["Any single broker restart stops writes", "Reads are also refused", "Maximum durability with no downside"], answer: 0,
    explain: "RF should be at least min ISR + 1, so a routine rolling restart does not block producers." },
  { q: "A partition below its minimum ISR…", options: ["Refuses acks=all writes but still serves reads", "Refuses reads and writes", "Deletes its data"], answer: 0,
    explain: "'Writes failing, reads fine' is the signature — and the fix is restoring brokers, not weakening acks." },
  { q: "Unclean leader election…", options: ["Allows an out-of-sync replica to lead, losing records it never received", "Is enabled by default", "Only affects internal topics"], answer: 0,
    explain: "Default false. Enabling it during an incident trades acknowledged data for availability, and it is frequently left on afterwards." },
  { q: "Leader epochs exist to…", options: ["Let a returning replica truncate correctly after a leader change", "Speed up compaction", "Order consumer groups"], answer: 0,
    explain: "A returning replica asks where its epoch ended and truncates past that point — so a truncation message on rejoin is correct behaviour." },
  { q: "The preferred leader of a partition is…", options: ["The first replica in its assignment list", "Always broker 1", "The replica with the lowest lag"], answer: 0,
    explain: "Automatic rebalancing moves leadership back to preferred leaders periodically, which keeps load spread after failures." },
  { q: "'Acknowledged' under `acks=all` means the record is…", options: ["In the page cache of every in-sync replica", "Written to at least one disk", "Fsynced to disk on every replica"], answer: 0,
    explain: "Durability comes from replication across independent failure domains, not from flushing — which is why racks and zones matter." },
  { q: "With 3 zones, RF 3 and `min.insync.replicas=2`, losing one zone means…", options: ["Reads and writes continue", "The cluster is unavailable", "Writes are refused"], answer: 0,
    explain: "Two replicas remain, which meets the minimum. Controllers must also be spread one per zone for the quorum to survive." },
  { q: "In a two-zone region, RF 4 with `min.insync.replicas=3` gives you…", options: ["Both writes and two-copy durability", "Durability during a zone loss, but writes stop", "Writes during a zone loss"], answer: 1,
    explain: "Two zones cannot give both. Choosing min ISR 2 instead keeps writes on the surviving zone's copies." },
  { q: "Between brokers in a rolling restart you should wait for…", options: ["Five minutes", "The next preferred leader election", "Zero under-replicated partitions cluster-wide"], answer: 2,
    explain: "Restarting too early leaves two replicas of some partitions down: writes refused at min ISR 2, or data on one copy." },
  { q: "Stopping a broker with SIGKILL instead of SIGTERM…", options: ["Skips controlled shutdown, so clients see errors and recovery is slower", "Corrupts the log irrecoverably", "Is faster and equivalent"], answer: 0,
    explain: "It also forces log recovery on restart, which on a partition-heavy broker is the dominant restart cost." },
  { q: "Partition reassignment should be run with `--throttle` because…", options: ["It prevents data loss", "Copying replicas otherwise starves client traffic", "It is required by the tool"], answer: 1,
    explain: "And `--verify` is what removes the throttle when the moves finish — skipping it leaves the cluster throttled." },
  { q: "`UnderMinIsrPartitionCount > 0` means…", options: ["Durability is degraded but writes continue", "The controller is down", "Those partitions are refusing acks=all writes right now"], answer: 2,
    explain: "It is a stronger signal than under-replicated partitions: producers are failing at this moment." },
  { q: "Which metric best predicts ISR churn?", options: ["Consumer lag", "`IsrShrinksPerSec` sustained above zero", "Topic count"], answer: 1,
    explain: "Repeated shrink/expand cycles point at GC pauses, disk latency or noisy neighbours on a particular broker." },
  { q: "`num.replica.fetchers` matters when…", options: ["Consumers are slow", "Topics are compacted", "A broker has many partitions and replication falls behind"], answer: 2,
    explain: "One fetcher thread per source broker can become the replication bottleneck on partition-heavy brokers." },
  { q: "Without `broker.rack` set…", options: ["Partitions cannot be reassigned", "Replication is disabled", "All replicas of a partition can land in one zone"], answer: 2,
    explain: "Rack awareness is what makes RF 3 survive a zone loss; without it the replication factor can be an illusion." },
  { q: "The KRaft controller quorum should be placed…", options: ["One per zone, three or five in total", "All in one zone for low latency", "On the busiest brokers"], answer: 0,
    explain: "Raft needs a majority; two of three controllers in one zone means losing that zone freezes all metadata changes." },
]},
{ title: "Quiz 5 · Offsets, Commits & Transactions",
  desc: "Where progress lives, commit strategies, and exactly-once inside Kafka",
  questions: [
  { q: "Committed offsets are stored…", options: ["In the compacted `__consumer_offsets` topic", "In ZooKeeper", "On the consumer's local disk"], answer: 0,
    explain: "A commit is a produce request keyed by (group, topic, partition); compaction keeps the latest value per key." },
  { q: "A group's coordinator is…", options: ["The leader of the `__consumer_offsets` partition its group id hashes to", "Elected by the consumers", "Always broker 1"], answer: 0,
    explain: "So all of a group's commits and membership traffic go to one broker — a very busy group loads that broker." },
  { q: "A dev cluster created `__consumer_offsets` with replication factor 1 and the setting reached production. The risk is…", options: ["Slower commits", "Losing one broker wipes the positions of every group whose partition it led", "Offsets expiring sooner"], answer: 1,
    explain: "Those groups then restart from `auto.offset.reset`. Check the internal topic's replication factor on every cluster." },
  { q: "Auto-commit is at-least-once only when…", options: ["`acks=all` is set on the producer", "The commit interval is under 1 second", "Processing finishes inside the poll loop before the next poll()"], answer: 2,
    explain: "Auto-commit runs inside `poll()` and commits the previous poll's positions — safe if those records are genuinely done." },
  { q: "Adding a thread pool to an auto-committing consumer causes…", options: ["Silent loss of records still queued when the next poll() commits", "Duplicate processing", "A rebalance storm"], answer: 0,
    explain: "Once processing leaves the loop, offsets advance past work that has not happened. Commit finished offsets manually instead." },
  { q: "`commitAsync` does not retry by itself because…", options: ["A late retry could land after a newer commit and rewind the group", "Retries are unsupported", "It always succeeds"], answer: 0,
    explain: "The next commit supersedes a failed one. If you do retry, only retry when no newer commit has been sent." },
  { q: "The recommended everyday pattern is…", options: ["Auto-commit with a 100 ms interval", "`commitSync` after every record", "`commitAsync` per batch, `commitSync` on revocation and shutdown"], answer: 2,
    explain: "Async keeps the loop fast; the two synchronous points are where the final position must be recorded." },
  { q: "In `onPartitionsLost` you should…", options: ["Clean up local state only — another member may already own them", "Commit offsets synchronously", "Seek to the beginning"], answer: 0,
    explain: "Committing there fails or clobbers the new owner's progress. `onPartitionsRevoked` is where committing is correct." },
  { q: "`CommitFailedException` after a long batch means…", options: ["The broker is down", "The consumer left the group and no longer owns those partitions", "Offsets were corrupted"], answer: 1,
    explain: "It is zombie protection: the records will be reprocessed elsewhere. Fix the slow loop rather than retrying the commit." },
  { q: "Storing consumer offsets in the sink database, in the same transaction as the results, gives…", options: ["Exactly-once delivery from Kafka", "Lower latency", "Exactly-once effect for that database"], answer: 2,
    explain: "Results and progress commit together, so a crash rolls back both. The consumer must `seek()` to the stored offset on assignment." },
  { q: "`kafka-consumer-groups.sh --reset-offsets` refuses to run when…", options: ["The group has active members", "The topic is compacted", "Offsets are older than retention"], answer: 0,
    explain: "Otherwise running consumers would immediately overwrite the reset with their own commits." },
  { q: "Before replaying a topic you should mainly check…", options: ["Broker CPU", "The partition count", "What side effects the consumer performs per record"], answer: 2,
    explain: "A replay re-runs emails, charges and webhooks unless they are idempotent. Export current offsets first as the rollback." },
  { q: "Transactions add, over the idempotent producer…", options: ["Atomic writes across partitions plus atomic input-offset commits, and fencing across restarts", "Higher throughput", "Compression across partitions"], answer: 0,
    explain: "That is what makes a consume-transform-produce loop exactly-once inside Kafka." },
  { q: "A transaction becomes visible to `read_committed` consumers when…", options: ["A commit marker is written to each partition involved", "The producer calls send()", "The segment rolls"], answer: 0,
    explain: "Markers take offsets of their own, which is one reason transactional topics show gaps in consumer offsets." },
  { q: "The default consumer `isolation.level` is…", options: ["`read_committed`", "`read_uncommitted` — so aborted records ARE delivered", "There is no default"], answer: 1,
    explain: "Every consumer of a transactional topic must opt in, or the producer's transactions protect nothing for them." },
  { q: "A `read_committed` consumer stops reading at…", options: ["The high watermark", "The last stable offset — the first record of the oldest open transaction", "The log start offset"], answer: 1,
    explain: "So one long-open transaction holds back committed records from other producers on the same partition." },
  { q: "After `abortTransaction()`, the loop must…", options: ["Commit the input offsets", "Seek the consumer back to its committed offsets", "Close the producer"], answer: 1,
    explain: "The consumer's position already moved past the batch; without the seek, the aborted records are silently skipped." },
  { q: "`transactional.id` should be…", options: ["A random UUID per start", "Stable per instance slot, unique between running instances", "Identical on every instance"], answer: 1,
    explain: "Random ids never fence a predecessor; a shared id makes instances fence each other so only one can run." },
  { q: "`ProducerFencedException` means…", options: ["Retry the transaction", "The broker is overloaded", "A newer producer with the same transactional id has taken over: close this one"], answer: 2,
    explain: "It is fatal for that producer. Abortable errors, by contrast, mean abort, rewind and retry." },
  { q: "`read_committed` consumers stall while `read_uncommitted` ones are fine. The likely cause is…", options: ["A hanging transaction holding the last stable offset", "Consumer lag", "A compaction backlog"], answer: 0,
    explain: "Find it with `kafka-transactions.sh describe-producers`, and abort it if the coordinator's timeout will not." },
]},
);
