// springboot quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · IoC, DI & Beans",
  desc: "The container, injection styles, scopes, lifecycle and proxies",
  questions: [
  { q: "The practical reason constructor injection is preferred over field injection is…", options: ["It uses less memory", "The object cannot be constructed in an invalid state, and it is testable without a container", "It is faster at runtime"], answer: 1,
    explain: "Required dependencies become final constructor parameters, so an incompletely-wired object cannot exist — and a unit test can `new` the class with mocks." },
  { q: "A circular dependency between two singletons injected by constructor…", options: ["Fails at startup with BeanCurrentlyInCreationException", "Works but leaks memory", "Is resolved silently by the container"], answer: 0,
    explain: "Neither bean can be constructed first. Field/setter injection hides the cycle; the constructor exposes it at startup, which is the better failure." },
  { q: "@Autowired on a single-constructor class since Spring 4.3 is…", options: ["Deprecated and ignored", "Optional — the single constructor is used automatically", "Required"], answer: 1,
    explain: "One constructor means no ambiguity, so the annotation adds nothing." },
  { q: "Injecting a prototype bean into a singleton gives you…", options: ["A compilation error", "One instance, created once, for the singleton's lifetime", "A new instance per use"], answer: 1,
    explain: "Injection happens once, at singleton creation. For a fresh instance per call you need ObjectProvider, a lookup method, or scoped proxies." },
  { q: "Bean singleton scope means one instance per…", options: ["Thread", "JVM", "ApplicationContext"], answer: 2,
    explain: "Two contexts in one JVM have separate singletons — which is why some tests see 'duplicate' beans." },
  { q: "The order of lifecycle callbacks after dependency injection is…", options: ["@PostConstruct → InitializingBean.afterPropertiesSet → custom init-method", "They run concurrently", "custom init-method → @PostConstruct → afterPropertiesSet"], answer: 0,
    explain: "Annotation first, then the interface callback, then the configured init method." },
  { q: "@PreDestroy on a prototype-scoped bean…", options: ["Runs when the object is garbage collected", "Runs at context shutdown", "Never runs — the container does not manage a prototype past creation"], answer: 2,
    explain: "The container hands over a prototype and forgets it, so destruction callbacks are the caller's problem." },
  { q: "A bean implementing BeanPostProcessor is special because…", options: ["It replaces the container", "It is created very early and cannot itself be proxied by AOP", "It runs last"], answer: 1,
    explain: "Post-processors must exist before the beans they process, so they miss auto-proxying and should stay dependency-light." },
  { q: "@Lazy on a bean means…", options: ["It is created in a background thread", "It is never created", "It is created on first use rather than at startup"], answer: 2,
    explain: "It trades startup time for a later first-request cost — and moves a wiring failure from startup to production traffic." },
  { q: "When two beans of the same type exist and neither is marked, injection…", options: ["Picks one at random", "Injects both as a list", "Fails with NoUniqueBeanDefinitionException"], answer: 2,
    explain: "Ambiguity is an error. @Primary, @Qualifier, or injecting a List/Map resolves it." },
  { q: "Injecting `List<PaymentHandler>` gives you…", options: ["Every bean of that type, ordered by @Order", "Only the primary bean", "A compilation error"], answer: 0,
    explain: "Collection injection is the idiomatic strategy pattern in Spring — add a bean, and it participates." },
  { q: "@Scope(\"prototype\") with a proxyMode of TARGET_CLASS on a bean injected into a singleton…", options: ["Fails at startup", "Injects a proxy that resolves a new instance per method call", "Does nothing"], answer: 1,
    explain: "The proxy defers resolution to invocation time, which is what makes per-use instances work through a singleton." },
  { q: "The reason a self-invoked @Transactional method has no transaction is…", options: ["A missing annotation", "The call never leaves the object, so it never passes through the proxy", "Transactions are disabled by default"], answer: 1,
    explain: "Proxy-based AOP intercepts external calls only. `this.method()` bypasses every aspect." },
  { q: "Spring uses a CGLIB proxy rather than a JDK dynamic proxy when…", options: ["The bean implements no interface", "The class is final", "The bean is a singleton"], answer: 0,
    explain: "JDK proxies require an interface; CGLIB subclasses the class — which is why final classes and final methods cannot be proxied." },
  { q: "ApplicationContext differs from BeanFactory chiefly by…", options: ["Supporting only XML", "Adding eager singleton instantiation, events, i18n and resource loading", "Being slower"], answer: 1,
    explain: "ApplicationContext is BeanFactory plus the enterprise features Boot relies on." },
  { q: "A bean that needs another bean only occasionally should use…", options: ["Field injection", "A static holder", "ObjectProvider<T>"], answer: 2,
    explain: "ObjectProvider defers lookup and handles absent or ambiguous beans without breaking startup." },
  { q: "@Component, @Service and @Repository differ in…", options: ["Their scope", "Nothing at all", "Semantics, plus @Repository's exception translation"], answer: 2,
    explain: "All three are stereotypes, but @Repository also translates persistence exceptions into Spring's DataAccessException hierarchy." },
  { q: "The main risk of holding request state in a singleton bean's field is…", options: ["Slower startup", "Larger heap", "Concurrent requests corrupting each other's state"], answer: 2,
    explain: "One instance serves every thread. Mutable instance state in a singleton is a data race by construction." },
  { q: "Startup time in a large context is usually dominated by…", options: ["Classpath scanning and framework metadata building (Hibernate, security)", "Constructor logic", "Garbage collection"], answer: 0,
    explain: "Scanning and metadata construction dominate; the 47-second startup case was fixed with narrower scanning, CDS and AOT — not faster constructors." },
  { q: "The advantage of failing at startup rather than on first request is…", options: ["It restarts faster", "Nothing — it is the same", "A misconfiguration is caught by the deploy, not by a customer"], answer: 2,
    explain: "A crash-looping pod halts a rolling deploy automatically; a lazily-discovered failure ships." },
]},
{ title: "Quiz 2 · Auto-Configuration & Starters",
  desc: "How Boot decides what to configure, and how to see and override it",
  questions: [
  { q: "Auto-configuration classes are discovered from…", options: ["Classpath scanning of your packages", "application.yml", "META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"], answer: 2,
    explain: "Boot 2.7+ uses the .imports file; the older spring.factories key is deprecated." },
  { q: "@ConditionalOnMissingBean makes auto-configuration…", options: ["Back off when you have defined your own bean of that type", "Run before your beans", "Log a warning"], answer: 0,
    explain: "It is the back-off mechanism: your bean wins, and Boot supplies a default only when you have not." },
  { q: "For @ConditionalOnMissingBean to see your bean, ordering matters because…", options: ["Auto-configuration runs after user configuration, and the condition evaluates against what already exists", "Beans are alphabetical", "It does not matter"], answer: 0,
    explain: "User configuration is processed first; that is why a bean defined in an auto-configuration class cannot reliably back off against another auto-configuration's bean without explicit ordering." },
  { q: "The fastest way to see why a bean does or does not exist is…", options: ["Adding print statements", "/actuator/conditions", "Reading the source"], answer: 1,
    explain: "The conditions report lists positive and negative matches with the reason for each." },
  { q: "A 'starter' is primarily…", options: ["A runtime agent", "A dependency aggregator with no code of its own", "A code generator"], answer: 1,
    explain: "Starters bring a curated, version-aligned dependency set; the configuration lives in the autoconfigure jar." },
  { q: "spring-boot-dependencies as a BOM gives you…", options: ["Faster builds", "Smaller jars", "Consistent, tested versions across the whole dependency set"], answer: 2,
    explain: "Managed versions prevent the incompatible-transitive-version failures that dominate manual dependency management." },
  { q: "@SpringBootApplication is shorthand for…", options: ["@Component + @Bean", "@Service + @RestController", "@Configuration + @EnableAutoConfiguration + @ComponentScan"], answer: 2,
    explain: "Three annotations in one, which is why the class's package determines the scan root." },
  { q: "Placing the main class in the root package matters because…", options: ["Of naming conventions only", "It affects the jar name", "Component scanning starts from that package downwards"], answer: 2,
    explain: "A main class in a sub-package silently fails to find beans in sibling packages." },
  { q: "To exclude one auto-configuration you would…", options: ["Set a system property", "Delete the starter", "@SpringBootApplication(exclude = DataSourceAutoConfiguration.class)"], answer: 2,
    explain: "Exclusion is per-class and is the correct answer to 'Boot configured something I do not want'." },
  { q: "@ConditionalOnProperty with matchIfMissing = true means…", options: ["The condition never passes", "The property must be absent", "The condition passes when the property is absent"], answer: 2,
    explain: "It is how a feature is enabled by default while remaining switchable." },
  { q: "@ConditionalOnClass works even when the class is absent because…", options: ["The class is loaded reflectively", "Boot catches NoClassDefFoundError", "Conditions are evaluated from bytecode metadata (ASM), not by loading the class"], answer: 2,
    explain: "Reading annotations without class loading is what makes conditional configuration safe on a partial classpath." },
  { q: "@AutoConfiguration(after = DataSourceAutoConfiguration.class) controls…", options: ["Startup logging", "Bean creation order", "The order in which auto-configuration classes are evaluated"], answer: 2,
    explain: "It orders evaluation so conditions see a consistent picture; bean creation order is still driven by dependencies." },
  { q: "A property set in application.yml is overridden by…", options: ["Nothing", "A @Value default", "An environment variable or a command-line argument"], answer: 2,
    explain: "Boot's ordered property sources put command-line arguments and environment variables above packaged files." },
  { q: "The DataSource Boot auto-configures with no explicit URL in a test is…", options: ["A production database", "None — startup fails", "An in-memory database if one is on the classpath"], answer: 2,
    explain: "H2/HSQLDB on the test classpath triggers an embedded DataSource, which is exactly the surprise when it is on the runtime classpath too." },
  { q: "Writing your own starter, the auto-configuration class should…", options: ["Be component-scanned", "Be listed in the .imports file and guarded by conditions", "Use @Component"], answer: 1,
    explain: "Auto-configuration must not be scanned — it is registered by the imports file so consumers do not need to scan your packages." },
  { q: "@ConfigurationProperties is preferred over many @Value fields because…", options: ["It is faster", "@Value is deprecated", "It supports type-safe binding, relaxed names, validation and IDE metadata"], answer: 2,
    explain: "One validated object beats scattered string keys — and a bad value fails at startup rather than at the code path that uses it." },
  { q: "Spring Boot's 'opinionated' design means…", options: ["It only supports one database", "It cannot be changed", "Sensible defaults that back off the moment you express an opinion"], answer: 2,
    explain: "The whole conditional model exists so defaults are overridable without configuration files." },
  { q: "A `NoSuchBeanDefinitionException` for a bean you expected Boot to provide usually means…", options: ["A bug in Boot", "A condition did not match — a missing class, a missing property, or a bean you defined", "The JVM is too old"], answer: 1,
    explain: "The conditions report names the unmatched condition, which is why it is the first place to look." },
  { q: "spring-boot-devtools in production is a problem because…", options: ["It is slow", "It enables restarts and exposes development conveniences that do not belong in production", "It breaks logging"], answer: 1,
    explain: "It is intended to be excluded from production artefacts, and Boot deliberately disables it for fully packaged applications." },
  { q: "Spring Boot compared with plain Spring adds…", options: ["Auto-configuration, starters, an embedded server, externalised config and Actuator", "A new language", "A different dependency injection container"], answer: 0,
    explain: "The core container is unchanged; Boot removes the configuration work around it." },
]},
{ title: "Quiz 3 · REST Controllers & Request Handling",
  desc: "Dispatch, binding, content negotiation, DTOs and status codes",
  questions: [
  { q: "Before your controller method runs, DispatcherServlet has already…", options: ["Opened a transaction", "Matched a handler, run filters and interceptors, and bound and converted arguments", "Committed the response"], answer: 1,
    explain: "Handler mapping, filters, interceptors, argument resolvers and message converters all run first — which is where most 'my method was never called' bugs live." },
  { q: "@RestController differs from @Controller by…", options: ["Adding validation", "Implying @ResponseBody on every method", "Enabling REST"], answer: 1,
    explain: "Without it, a returned String is treated as a view name — the classic 'why am I getting a 404 for my JSON' bug." },
  { q: "A filter differs from a HandlerInterceptor in that…", options: ["A filter is faster", "There is no difference", "A filter is part of the servlet container and sees every request, including ones no handler matches"], answer: 2,
    explain: "Filters wrap the servlet; interceptors are Spring MVC and run only for mapped handlers." },
  { q: "@RequestParam(required = false) on an `int` parameter…", options: ["Binds 0", "Is ignored", "Throws when the parameter is absent, because null cannot be unboxed"], answer: 2,
    explain: "Use Integer, or a defaultValue. This is a very common 500." },
  { q: "@PathVariable and @RequestParam differ in…", options: ["Nothing", "Type support", "Where the value comes from — the URI template versus the query string"], answer: 2,
    explain: "Different sources, same binding machinery." },
  { q: "Returning a JPA entity directly from a controller is risky mainly because…", options: ["The database schema becomes the API contract, and lazy associations serialise unpredictably", "Jackson cannot serialise entities", "It is slower"], answer: 0,
    explain: "A column rename becomes an API break, and a lazy proxy either triggers N+1 queries or fails outside the session." },
  { q: "ResponseEntity is worth returning when…", options: ["You need to control the status code or headers per response", "Only for errors", "Always"], answer: 0,
    explain: "For a plain 200 with a body, returning the object is cleaner; ResponseEntity earns its verbosity when status or headers vary." },
  { q: "A POST that creates a resource should return…", options: ["200 with the id", "204", "201 with a Location header"], answer: 2,
    explain: "201 Created plus Location is the contract clients and caches expect." },
  { q: "204 No Content means…", options: ["Success, and there is deliberately no body", "The resource was not found", "The request was rejected"], answer: 0,
    explain: "It is the correct answer to a successful DELETE or an update with nothing to return." },
  { q: "Content negotiation chooses a message converter based on…", options: ["The controller's package", "The URL extension only", "The Accept header, matched against the converters' supported media types"], answer: 2,
    explain: "A 406 means no converter could produce anything the client said it would accept." },
  { q: "@RequestBody binding failure produces…", options: ["A 500", "A null argument", "A 400, via HttpMessageNotReadableException"], answer: 2,
    explain: "Malformed JSON is client error; Spring's default handler already maps it to 400." },
  { q: "A controller method should contain…", options: ["Database access", "HTTP concerns only, delegating to a service", "The business logic, so it is easy to find"], answer: 1,
    explain: "Keeping logic out of controllers is what makes it testable without MockMvc and reusable from a listener or a scheduled job." },
  { q: "@RequestMapping(produces = \"application/json\") affects…", options: ["Validation", "Only the response header", "Mapping — a request whose Accept header cannot take JSON does not match this handler"], answer: 2,
    explain: "produces and consumes participate in handler matching, which is why a mismatch is a 406 or 415 rather than a 500." },
  { q: "Two handlers matching the same path with different HTTP methods is…", options: ["An error at startup", "Normal — the method is part of the mapping", "Resolved at random"], answer: 1,
    explain: "Path plus method plus headers plus content types form the mapping condition." },
  { q: "@ModelAttribute on a method parameter binds from…", options: ["The request body as JSON", "Query and form parameters, into an object", "Path variables only"], answer: 1,
    explain: "It is the form-binding counterpart to @RequestBody." },
  { q: "The right status for a request that is syntactically valid but breaks a business rule is usually…", options: ["400", "409 or 422, depending on whether it is a conflict or an unprocessable entity", "500"], answer: 1,
    explain: "400 says 'malformed'. A well-formed request that cannot be honoured deserves a more precise code." },
  { q: "HttpServletRequest can be injected into a singleton controller because…", options: ["Spring injects a request-scoped proxy that resolves per call", "It is a new object each time", "The controller is request-scoped"], answer: 0,
    explain: "The proxy resolves the current request from the thread — one of the ThreadLocal mechanisms that stops working in reactive code." },
  { q: "@CrossOrigin controls…", options: ["TLS", "Server-side authorisation", "The CORS headers the browser uses to decide whether JavaScript may read the response"], answer: 2,
    explain: "CORS is a browser policy. It is not a security control on the server side." },
  { q: "Returning `Optional<T>` from a controller method…", options: ["Is forbidden", "Serialises as a JSON wrapper unless handled", "Yields 404 automatically when empty"], answer: 1,
    explain: "Spring Data uses Optional idiomatically, but a controller should map empty to a 404 explicitly." },
  { q: "The best reason to keep DTOs separate from entities is…", options: ["Jackson requires it", "Performance", "The API and the schema then evolve independently"], answer: 2,
    explain: "It is the seam that lets you rename a column without breaking clients — and vice versa." },
]},
{ title: "Quiz 4 · Configuration, Profiles & Properties",
  desc: "Property sources, profiles, secrets and type-safe binding",
  questions: [
  { q: "The highest-precedence property source among these is…", options: ["@PropertySource", "A command-line argument", "application.yml in the jar"], answer: 1,
    explain: "Command-line arguments sit near the top of Boot's ordered list, above packaged files and environment variables." },
  { q: "An environment variable maps to a property through…", options: ["A manual mapping file", "Exact-case matching only", "Relaxed binding — SPRING_DATASOURCE_URL binds spring.datasource.url"], answer: 2,
    explain: "Relaxed binding is what makes container configuration work without editing files." },
  { q: "application-prod.yml is loaded when…", options: ["Always, after application.yml", "The file exists", "The prod profile is active"], answer: 2,
    explain: "Profile-specific files load only for active profiles, and their values override the base file." },
  { q: "@Profile(\"!test\") on a bean means…", options: ["It is never created", "It is created unless the test profile is active", "It is created only in tests"], answer: 1,
    explain: "The negation is the usual way to exclude expensive infrastructure from tests." },
  { q: "Branching on `if (env.equals(\"prod\"))` inside business logic is worse than a profile because…", options: ["The behaviour is untestable and invisible to configuration; profiles move the decision to wiring", "It does not compile", "It is slower"], answer: 0,
    explain: "Environment checks scattered through logic are the configuration equivalent of a hidden global." },
  { q: "@ConfigurationProperties with @Validated gives you…", options: ["Runtime warnings", "Startup failure on an invalid value, with the offending property named", "Nothing extra"], answer: 1,
    explain: "Failing the boot on a bad value is far better than discovering it in the code path that reads it, at 3am." },
  { q: "Binding a property to a Duration field accepts…", options: ["Only milliseconds as a number", "Only a string", "ISO-8601 or Boot's shorthand such as 30s and 5m"], answer: 2,
    explain: "Typed binding removes a whole class of unit-confusion bugs." },
  { q: "Storing a database password in application.yml committed to git is wrong mainly because…", options: ["It is slower to read", "YAML cannot hold secrets", "Anyone with repository access has the credential, and rotation means a redeploy"], answer: 2,
    explain: "Secrets belong in the environment or a secret manager, injected at runtime." },
  { q: "spring.config.import lets you…", options: ["Import Java classes", "Pull in additional config, such as an optional file or a config server", "Import beans"], answer: 1,
    explain: "It is the modern, ordered replacement for several older mechanisms." },
  { q: "A @Value(\"${missing.key}\") with no default causes…", options: ["An empty string", "Startup failure", "Null injection"], answer: 1,
    explain: "That failure is a feature — a missing required property should not survive to runtime." },
  { q: "Placeholder syntax ${a:default} means…", options: ["A type cast", "Use 'default' when a is unset", "Concatenate"], answer: 1,
    explain: "The colon separates a fallback value." },
  { q: "@ConfigurationProperties binding of a `List<String>` from an environment variable uses…", options: ["It cannot be done", "Indexed keys such as APP_HOSTS_0, APP_HOSTS_1, or a comma-separated value", "Commas only"], answer: 1,
    explain: "Both forms bind; indexed keys are the explicit one when values contain commas." },
  { q: "Profile groups exist to…", options: ["Activate several profiles with one name", "Rename profiles", "Order property sources"], answer: 0,
    explain: "`spring.profiles.group.prod=prod,metrics,cloud` avoids long activation lists." },
  { q: "The default profile applies when…", options: ["Always", "Only in tests", "No other profile is active"], answer: 2,
    explain: "It is a fallback, and relying on it in production is how a service runs with development settings." },
  { q: "Refreshing configuration without a restart requires…", options: ["Nothing — Boot reloads automatically", "A mechanism such as Spring Cloud Config with @RefreshScope, or a restart", "Editing the jar"], answer: 1,
    explain: "Plain Boot binds at startup. 'Config without redeploy' is an explicit capability you add." },
  { q: "@ConfigurationProperties on a record works because…", options: ["Records are special-cased", "Constructor binding is supported, and a record has one canonical constructor", "It does not work"], answer: 1,
    explain: "Constructor binding gives immutable configuration objects." },
  { q: "The reason profile-specific properties should not carry secrets is…", options: ["They are loaded late", "They are still in the artefact, so 'prod' secrets ship in every build", "They are unreadable"], answer: 1,
    explain: "A packaged file travels everywhere the jar goes, including to developer laptops." },
  { q: "/actuator/env with show-values set to never…", options: ["Hides the endpoint", "Lists property names and sources but masks the values", "Disables property binding"], answer: 1,
    explain: "You keep the diagnostic value — which source won — without exposing credentials." },
  { q: "Two profiles both defining the same key resolve by…", options: ["Alphabetical order", "An error", "The last activated profile winning"], answer: 2,
    explain: "Activation order matters, which is why long profile lists become hard to reason about." },
  { q: "The strongest argument for typed configuration objects over scattered @Value is…", options: ["Fewer characters", "It avoids reflection", "One place lists everything the application needs, validated at startup"], answer: 2,
    explain: "Discoverability and fail-fast validation, not syntax." },
]},
{ title: "Quiz 5 · Data, JPA & Transactions",
  desc: "Repositories, the persistence context, N+1, locking and transaction semantics",
  questions: [
  { q: "A Spring Data repository interface becomes a bean because…", options: ["It is scanned as a class", "You annotate it @Component", "Spring generates a proxy implementation at startup"], answer: 2,
    explain: "The proxy translates method names, @Query annotations and derived criteria into queries." },
  { q: "Inside a transaction, changing a managed entity's field without calling save()…", options: ["Does nothing", "Is written at flush, by dirty checking", "Throws"], answer: 1,
    explain: "The persistence context compares state at flush time — which is why 'I did not save it' updates surprise people." },
  { q: "The N+1 problem occurs when…", options: ["You call save() N times", "One query loads parents and one more per parent loads its children", "The pool has N connections"], answer: 1,
    explain: "It is invisible in unit tests and dominant under real data volumes." },
  { q: "The fix for N+1 that also breaks pagination is…", options: ["A fetch join on a collection, which forces in-memory paging", "EntityGraph", "Batch size"], answer: 0,
    explain: "Hibernate warns 'applying in memory' — it fetches everything and paginates in the JVM." },
  { q: "hibernate.default_batch_fetch_size reduces N+1 by…", options: ["Disabling laziness", "Loading lazy associations in batches, turning N queries into roughly N/size", "Caching results"], answer: 1,
    explain: "It is the least invasive of the fixes and works without changing any query." },
  { q: "@Transactional on a private method…", options: ["Works normally", "Has no effect — the proxy cannot intercept it", "Fails at startup"], answer: 1,
    explain: "Same reason as self-invocation: proxy-based AOP only wraps externally-called, visible methods." },
  { q: "By default, @Transactional rolls back on…", options: ["Unchecked exceptions and Errors only", "Any Exception", "Nothing"], answer: 0,
    explain: "A checked exception commits unless you specify rollbackFor — a genuine data-integrity trap." },
  { q: "REQUIRES_NEW differs from REQUIRED in that it…", options: ["Reuses the same transaction", "Disables rollback", "Suspends the current transaction and starts an independent one, using a second connection"], answer: 2,
    explain: "Two connections held at once is how a pool deadlocks when REQUIRES_NEW is used under load." },
  { q: "A remote HTTP call inside a @Transactional method is dangerous because…", options: ["It is slower", "It cannot be rolled back and it pins a database connection for the whole round trip", "Spring forbids it"], answer: 1,
    explain: "Both halves matter: the external effect is not transactional, and the connection is held while you wait." },
  { q: "@Transactional(readOnly = true) is worth setting because…", options: ["Hibernate can skip dirty-checking, and some drivers route to a replica", "It prevents all writes at the database", "It is faster to parse"], answer: 0,
    explain: "It is a hint with real effects, not a security control." },
  { q: "LazyInitializationException means…", options: ["A lazy association was accessed after the persistence context closed", "The query was malformed", "The entity was null"], answer: 0,
    explain: "Typically serialising an entity in a controller after the transaction ended — one more reason to map to DTOs inside the transaction." },
  { q: "@Version implements…", options: ["Pessimistic locking", "Optimistic locking — a mismatched version fails the update", "Schema versioning"], answer: 1,
    explain: "It is also the value worth exposing as an HTTP ETag for If-Match preconditions." },
  { q: "Two users editing the same record with no locking produces…", options: ["A constraint violation", "A lost update — the second write silently overwrites the first, both returning success", "A deadlock"], answer: 1,
    explain: "Nothing fails, which is exactly why it is discovered by complaints rather than by monitoring." },
  { q: "The connection pool should generally be sized…", options: ["From concurrency × query time, well below the thread count", "As large as the database allows", "Equal to the servlet thread count"], answer: 0,
    explain: "A pool as large as the thread pool moves the queue into the database, where contention is far more expensive." },
  { q: "hikaricp.connections.pending rising while query latency looks normal indicates…", options: ["A slow database", "A network fault", "Threads waiting for a connection — pool starvation, often from work held inside transactions"], answer: 2,
    explain: "It is the leading indicator that moves before latency does, which is why it is worth exporting explicitly." },
  { q: "spring.jpa.hibernate.ddl-auto in production should be…", options: ["update", "create", "validate or none"], answer: 2,
    explain: "update is unreviewable, unrepeatable and incomplete — it never drops a renamed column, so inserts fail." },
  { q: "Flyway refuses to start after an applied migration file is edited because…", options: ["Its recorded checksum no longer matches, so the schema can no longer be proven to match the script", "Migrations expire", "The file is locked"], answer: 0,
    explain: "That protection is what stops environments drifting silently — and it crash-loops every pod until resolved." },
  { q: "Running Flyway when 24 pods start simultaneously is safe because…", options: ["Flyway takes a lock; one applies and the rest wait, then find nothing pending", "Migrations are idempotent", "Only the first pod runs it"], answer: 0,
    explain: "The lock makes concurrent startup safe — though a slow migration then delays every pod's readiness." },
  { q: "The danger in `ALTER TABLE ... ADD COLUMN NOT NULL DEFAULT` is…", options: ["On some database versions it rewrites the whole table under an exclusive lock", "It cannot be rolled back", "Syntax"], answer: 0,
    explain: "One such migration held ACCESS EXCLUSIVE for 4m38s on 41M rows — a full outage from a three-line file." },
  { q: "Renaming a column in a single release during a rolling deploy fails because…", options: ["The index is lost", "Old pods are still querying the old name while both versions serve traffic", "Flyway forbids renames"], answer: 1,
    explain: "Expand/contract exists precisely because two versions run against one schema for minutes." },
]},
);
