// springboot quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Validation & Error Handling",
  desc: "Bean Validation, @ControllerAdvice, Problem Details and error security",
  questions: [
  { q: "@Valid on a @RequestBody parameter that fails validation produces…", options: ["MethodArgumentNotValidException, mapped to 400", "A 500", "A null argument"], answer: 0,
    explain: "Boot's default handler already returns 400; the work is shaping a useful body." },
  { q: "@Validated on the class differs from @Valid on a parameter by…", options: ["Enabling validation of method parameters and return values via a proxy", "Nothing", "Being faster"], answer: 0,
    explain: "@Validated drives method validation (and validation groups); @Valid is the standard cascade annotation." },
  { q: "Validating a nested object requires…", options: ["@Valid on the nested field, to cascade", "Nothing — it is automatic", "A custom validator"], answer: 0,
    explain: "Without the cascade annotation the nested constraints are simply not evaluated." },
  { q: "A custom constraint needs…", options: ["Only an annotation", "An annotation plus a ConstraintValidator implementation", "A Spring bean named validator"], answer: 1,
    explain: "And the validator can be a Spring bean, so it may inject a repository for uniqueness checks." },
  { q: "Validation groups exist to…", options: ["Group error messages", "Apply different constraint subsets in different contexts, such as create versus update", "Order validators"], answer: 1,
    explain: "The classic case: id must be null on create and present on update." },
  { q: "@ControllerAdvice is best described as…", options: ["A filter", "A global collection of @ExceptionHandler methods applied across controllers", "An interceptor"], answer: 1,
    explain: "It centralises error mapping so controllers stay free of try/catch." },
  { q: "When both a controller-local and a global @ExceptionHandler match, the winner is…", options: ["The global one", "The controller-local one", "Neither — it is ambiguous"], answer: 1,
    explain: "The more specific handler wins, which is what makes per-controller overrides possible." },
  { q: "RFC 7807 Problem Details standardises…", options: ["Status codes", "The error response body — type, title, status, detail, instance", "Logging format"], answer: 1,
    explain: "ProblemDetail is built into Spring 6, and a stable error shape is part of the API contract." },
  { q: "Returning an exception's message directly to clients is a security concern because…", options: ["They can leak SQL, file paths, class names and internal hostnames", "Messages are slow to serialise", "They are not JSON"], answer: 0,
    explain: "Error responses are an information-disclosure surface; log the detail, return a correlation id." },
  { q: "A stack trace in an HTTP response should be…", options: ["Always excluded, even locally", "Included in development only, never in production", "Always included"], answer: 1,
    explain: "server.error.include-stacktrace defaults to never for exactly this reason." },
  { q: "The best thing to return alongside a generic 500 message is…", options: ["A trace or correlation id that appears in the logs", "The exception class", "The server hostname"], answer: 0,
    explain: "It turns a support ticket into a single log search without disclosing anything." },
  { q: "An exception thrown inside a @Transactional service and caught in @ControllerAdvice…", options: ["Commits the transaction", "Has already caused the rollback — the transaction ended before the handler ran", "Prevents the rollback"], answer: 1,
    explain: "The transaction boundary is inside; by the time the advice sees the exception the decision is made." },
  { q: "Catching an exception inside a @Transactional method and continuing…", options: ["Rolls back immediately", "Is always safe", "May still leave the transaction marked rollback-only, failing the commit later"], answer: 2,
    explain: "UnexpectedRollbackException at commit is the usual symptom of swallowing an exception from an inner transactional call." },
  { q: "Designing exceptions, a good rule is…", options: ["One exception per class", "Model the domain failure, not the HTTP status, and map to status in one place", "Always use RuntimeException"], answer: 1,
    explain: "Domain exceptions stay reusable from listeners and jobs, where HTTP means nothing." },
  { q: "The status for a request whose JSON cannot be parsed is…", options: ["400", "422", "500"], answer: 0,
    explain: "Malformed syntax is 400; 422 is for well-formed content that cannot be processed." },
  { q: "Validating a query parameter with @Min requires…", options: ["A custom resolver", "Nothing extra", "@Validated on the controller class"], answer: 2,
    explain: "Parameter-level constraints need method validation enabled, which @Validated switches on." },
  { q: "ConstraintViolationException from method validation maps by default to…", options: ["500 — you usually need to handle it explicitly", "422", "400"], answer: 0,
    explain: "Unlike MethodArgumentNotValidException, it is not handled out of the box, which surprises people." },
  { q: "Field-level error details for a client should be…", options: ["A list naming the field, the rejected value's problem and the rule", "The raw violation set", "A single sentence"], answer: 0,
    explain: "A structured errors array is what lets a UI highlight the offending field." },
  { q: "Validation belongs at the API boundary and also in the domain because…", options: ["The boundary rejects malformed input; the domain protects invariants against every caller, including listeners and jobs", "Duplication is required by the spec", "It is faster"], answer: 0,
    explain: "HTTP is not the only entry point, and the invariant is the domain's responsibility." },
  { q: "The strongest reason to standardise the error format early is…", options: ["Aesthetics", "Clients parse it, so changing it later is a breaking change", "It reduces log volume"], answer: 1,
    explain: "The error body is part of the contract even when nobody documented it." },
]},
{ title: "Quiz 7 · Testing Spring Boot",
  desc: "Slices, mocking, transactional tests, Testcontainers and what to test",
  questions: [
  { q: "@SpringBootTest without a webEnvironment setting…", options: ["Starts a real server", "Loads nothing", "Loads the full context with a mock servlet environment"], answer: 2,
    explain: "MOCK is the default; RANDOM_PORT starts a real server for end-to-end tests." },
  { q: "@WebMvcTest loads…", options: ["Just the controller class", "The whole context", "The web layer only — controllers, advice, converters — with services mocked"], answer: 2,
    explain: "A slice keeps tests fast and focused; collaborators come from @MockitoBean." },
  { q: "@DataJpaTest by default…", options: ["Configures an embedded database and rolls each test back", "Skips transactions", "Uses the production database"], answer: 0,
    explain: "Roll-back-per-test keeps tests independent, and replacing the database can be disabled when you want the real engine." },
  { q: "The reason a @Transactional test can pass while production fails is…", options: ["The test never commits, so constraint violations and flush-time errors can be hidden until commit", "Different SQL", "Mocks behave differently"], answer: 0,
    explain: "Explicitly flushing, or testing without the rollback, exposes what commit would have." },
  { q: "@MockitoBean differs from @Mock by…", options: ["Being faster", "Replacing the bean in the Spring context, not just creating a mock object", "Supporting only interfaces"], answer: 1,
    explain: "It changes the context, which is also why overusing it fragments the context cache." },
  { q: "Every distinct context configuration in a test suite…", options: ["Is shared globally regardless of configuration", "Is cached and reused across test classes", "Is rebuilt per test class"], answer: 1,
    explain: "The cache key is the configuration; each new combination of properties, mocks or profiles costs a full context startup." },
  { q: "The best reason to prefer a unit test over @SpringBootTest is…", options: ["Speed and precision — a failure names the logic, not the wiring", "Coverage tools require it", "Spring tests are unreliable"], answer: 0,
    explain: "Constructor injection is what makes this possible: `new` the class with test doubles." },
  { q: "Testcontainers is worth the startup cost because…", options: ["It replaces mocks", "It is faster than H2", "Tests run against the real database engine, catching dialect, constraint and locking behaviour H2 hides"], answer: 2,
    explain: "The bugs that reach production are usually the ones an in-memory database cannot reproduce." },
  { q: "@ServiceConnection with a Testcontainers container…", options: ["Mocks the datasource", "Starts the container", "Wires the container's connection details into the context automatically"], answer: 2,
    explain: "It removes the @DynamicPropertySource boilerplate that used to be required." },
  { q: "MockMvc tests…", options: ["Send real HTTP over a socket", "Only test the controller method", "Exercise the Spring MVC stack without a network"], answer: 2,
    explain: "Filters, converters, validation and exception handling all run — but there is no server or socket." },
  { q: "WebTestClient against a RANDOM_PORT server adds…", options: ["Real HTTP, so serialisation, status codes and headers are exercised end to end", "Nothing", "Only reactive support"], answer: 0,
    explain: "It is the right tool when the contract itself is what you are asserting." },
  { q: "A flaky test that passes alone and fails in a suite usually indicates…", options: ["A JUnit bug", "Shared state — a static field, a cached context bean, or data left behind", "A slow machine"], answer: 1,
    explain: "Test independence is the property being violated, and ordering only reveals it." },
  { q: "@DirtiesContext should be used…", options: ["Never", "Liberally, for safety", "Sparingly — it evicts the cached context and slows the whole suite"], answer: 2,
    explain: "It is the right tool when a test genuinely mutates the context, and a suite-wide cost when it is not." },
  { q: "Testing a @Scheduled method is best done by…", options: ["Waiting for the schedule", "Calling the method directly and testing the schedule separately", "Disabling scheduling"], answer: 1,
    explain: "Sleeping in tests trades determinism for wall-clock time and still proves little." },
  { q: "@Sql on a test method…", options: ["Executes a script before or after the test", "Generates entities", "Validates SQL syntax"], answer: 0,
    explain: "It is the straightforward way to seed a known dataset." },
  { q: "Asserting on a returned mock's interactions rather than on outcomes tends to…", options: ["Improve coverage meaningfully", "Run faster", "Couple the test to the implementation, so refactoring breaks tests that describe nothing"], answer: 2,
    explain: "Verify interactions where the interaction *is* the behaviour, such as a message being published." },
  { q: "@TestConfiguration differs from @Configuration in a test by…", options: ["Not being picked up by component scanning of the application", "Being mandatory", "Running later"], answer: 0,
    explain: "It is intended to be imported deliberately or nested inside the test class." },
  { q: "The clearest sign a test suite is testing the framework rather than the code is…", options: ["Long test names", "Assertions that a repository method returns what the repository was told to return", "Use of Testcontainers"], answer: 1,
    explain: "Spring Data's derived queries are already tested; your queries and your logic are not." },
  { q: "For a reactive chain, StepVerifier's advantage over blocking assertions is…", options: ["It is shorter", "It runs in parallel", "It asserts on the signal sequence, including errors and completion, and supports virtual time"], answer: 2,
    explain: "Virtual time verifies a fifteen-minute backoff schedule in milliseconds, deterministically." },
  { q: "The test most worth writing for a resilience configuration is…", options: ["That the annotation is present", "That the YAML parses", "That a failing dependency actually produces the fallback and the breaker opens"], answer: 2,
    explain: "Resilience configuration is silently wrong far more often than it is absent — self-invocation alone disables it." },
]},
{ title: "Quiz 8 · Security, AOP & Cross-Cutting Concerns",
  desc: "The filter chain, authorisation, proxies, caching, @Async and scheduling",
  questions: [
  { q: "Spring Security is implemented primarily as…", options: ["A servlet filter chain", "A controller advice", "An interceptor"], answer: 0,
    explain: "Being a filter is why it sees requests that never reach a handler — including ones that 404." },
  { q: "In a SecurityFilterChain, rule order matters because…", options: ["The first matching rule wins, so a broad permitAll before a specific rule opens everything", "Rules are alphabetical", "Later rules override earlier ones"], answer: 0,
    explain: "A misordered permitAll is one of the most common real authorisation holes." },
  { q: "Authentication and authorisation differ as…", options: ["Login versus logout", "Who you are, versus what you may do", "Two names for the same thing"], answer: 1,
    explain: "401 means unauthenticated; 403 means authenticated but not permitted." },
  { q: "@PreAuthorize is enforced by…", options: ["The controller", "The filter chain", "A method-level proxy, so self-invocation bypasses it"], answer: 2,
    explain: "The same proxy limitation as @Transactional applies to security annotations." },
  { q: "CSRF protection is relevant when…", options: ["Using JWTs in an Authorization header", "Any API is exposed", "Browsers send credentials automatically, such as with cookie-based sessions"], answer: 2,
    explain: "A token sent explicitly by JavaScript is not attached automatically, which is why stateless token APIs commonly disable CSRF." },
  { q: "Storing passwords requires…", options: ["A slow, salted, adaptive hash such as bcrypt or argon2", "Symmetric encryption", "A fast hash such as SHA-256"], answer: 0,
    explain: "Speed is the attacker's advantage; adaptive work factors are the defence." },
  { q: "A JWT's chief operational drawback is…", options: ["Size", "It cannot carry claims", "It cannot be revoked before expiry without extra state"], answer: 2,
    explain: "Short lifetimes plus refresh tokens, or a denylist, are the usual mitigations." },
  { q: "Method security on a service rather than the controller is preferable because…", options: ["It is faster", "Controllers cannot be secured", "The rule applies to every caller — listeners, jobs and other controllers"], answer: 2,
    explain: "HTTP is not the only entry point, so the boundary that matters is the domain operation." },
  { q: "Spring AOP applies advice by…", options: ["Creating a runtime proxy around the bean", "Modifying the class loader", "Bytecode weaving at compile time"], answer: 0,
    explain: "That is why only external, non-final, non-private methods are advised." },
  { q: "Adding @Transactional to a bean changes the injected type to…", options: ["A proxy — a JDK proxy of its interfaces, or a CGLIB subclass", "An interface only", "The same class"], answer: 0,
    explain: "Which is why injecting the concrete class can fail when only a JDK interface proxy exists." },
  { q: "@Cacheable on a method that returns null with cacheNulls off…", options: ["Throws", "Re-executes the method on every call for that key", "Caches the null"], answer: 1,
    explain: "A cache that never stores the negative result gives no protection against a lookup storm for a missing key." },
  { q: "@Cacheable and @CachePut differ in that…", options: ["@CachePut always executes the method and updates the cache", "They are identical", "@CachePut reads only"], answer: 0,
    explain: "@Cacheable short-circuits the call on a hit; @CachePut is for write-through updates." },
  { q: "A cache stampede happens when…", options: ["A popular key expires and many concurrent requests all miss and recompute it", "The cache is too large", "The TTL is too long"], answer: 0,
    explain: "Jittered TTLs, or single-flight loading, are the standard defences." },
  { q: "@Async returning void means…", options: ["The task cannot fail", "It runs synchronously", "Exceptions are invisible unless an AsyncUncaughtExceptionHandler is configured"], answer: 2,
    explain: "Silent failure is the default, which is why void @Async needs a handler." },
  { q: "The default @Async executor in modern Boot is…", options: ["The common ForkJoinPool", "A SimpleAsyncTaskExecutor with no bound, historically — define your own with a bounded queue", "A fixed pool of 8"], answer: 1,
    explain: "An unbounded queue turns a slow consumer into an OutOfMemoryError; one measured case reached 1.9M queued tasks with every other metric normal." },
  { q: "Exporting executor queue depth matters because…", options: ["It is required by Micrometer", "A growing async backlog is invisible in CPU, latency and error rate until the heap dies", "It reduces GC"], answer: 1,
    explain: "It is one of the two saturation metrics that move first and are off by default." },
  { q: "@Scheduled with fixedDelay differs from fixedRate by…", options: ["Measuring from the end of the previous run rather than its start", "Using cron syntax", "Running in parallel"], answer: 0,
    explain: "fixedRate can overlap or queue when a run exceeds the period; fixedDelay cannot." },
  { q: "A @Scheduled job in a service running 24 pods…", options: ["Runs once across the cluster", "Runs on every pod unless you add leader election or a distributed lock", "Runs on the oldest pod"], answer: 1,
    explain: "Nothing coordinates schedulers by default — this is a very common duplicate-work bug." },
  { q: "The default scheduler pool size of one means…", options: ["A long-running job delays every other scheduled task", "Jobs run in parallel", "Only one job may be defined"], answer: 0,
    explain: "Sizing the scheduler pool is necessary as soon as you have more than one job." },
  { q: "The right home for work that must not be lost is…", options: ["An @Async executor", "A scheduled job", "A durable queue or an outbox table, not an in-memory executor"], answer: 2,
    explain: "Executor queues are discarded at shutdown; durability requires storage." },
]},
{ title: "Quiz 9 · Observability, Resilience & Production",
  desc: "Probes, metrics, timeouts, breakers, bulkheads, deployment and the JVM in containers",
  questions: [
  { q: "Liveness and readiness differ in that a failing liveness probe…", options: ["Logs a warning", "Removes the pod from the load balancer", "Kills and restarts the pod"], answer: 2,
    explain: "Readiness removes traffic and is reversible; liveness destroys warm state, so it should be slow and reluctant." },
  { q: "Putting a downstream service check in your health endpoint causes…", options: ["Nothing", "Faster detection", "Cascading failure — every instance is removed for a dependency that only some endpoints need"], answer: 2,
    explain: "It also becomes a load multiplier: 24 pods × every 10 s is 8,640 requests an hour at a struggling dependency." },
  { q: "Averaging p99 latency across instances is…", options: ["Slightly imprecise", "Standard practice", "Arithmetically meaningless — percentiles do not add"], answer: 2,
    explain: "Export histogram buckets, which are additive, and compute the quantile with histogram_quantile." },
  { q: "Using a customer id as a metric tag risks…", options: ["Unbounded cardinality — one such tag created 2.4M series and OOM'd the metrics server", "Slower queries only", "Nothing, if the cardinality is under a million"], answer: 0,
    explain: "If you cannot list a tag's possible values, it is not a tag. High-cardinality data belongs in logs and traces." },
  { q: "management.endpoints.web.exposure.include: \"*\" is dangerous because…", options: ["It exposes /heapdump — every secret in memory — and a writable /loggers", "It disables health", "It is slow"], answer: 0,
    explain: "The control that matters is a separate management port on an internal network, not just an exposure list." },
  { q: "The default read timeout in RestTemplate and RestClient is…", options: ["Infinite", "30 seconds", "5 seconds"], answer: 0,
    explain: "'It has always worked' means the dependency has not hung yet." },
  { q: "A dependency slowing from 40 ms to 8 s takes a service down because…", options: ["CPU saturates", "Memory fills", "Concurrency demand is arrival rate × service time — 250/s × 8 s needs 2,000 threads against 200"], answer: 2,
    explain: "Capacity is request-seconds, not requests, which is why the outage happened at 6% CPU." },
  { q: "The third timeout people forget is…", options: ["Session timeout", "DNS timeout", "Connection-pool acquisition timeout"], answer: 2,
    explain: "Without it threads block before the request starts, where the read timeout can never fire." },
  { q: "Retrying after a read timeout on a non-idempotent operation is dangerous because…", options: ["The request may have been fully processed — only the response was lost", "The server rejects retries", "It is slow"], answer: 0,
    explain: "That assumption charged 1,143 customers twice during one gateway latency spike." },
  { q: "Three layers each retrying three times produces…", options: ["3× load", "27× load on a dependency that is already failing", "No extra load"], answer: 1,
    explain: "Retry is the only resilience pattern that adds load to a failing system — hence budgets, jitter and one retry layer." },
  { q: "A circuit breaker did not open while a dependency answered 200 in 9 seconds because…", options: ["The failure rate was 0% — slowness is not failure without slow-call thresholds", "The threshold was too low", "Breakers ignore timeouts"], answer: 0,
    explain: "slowCallDurationThreshold and slowCallRateThreshold address the failure that actually happens most: not down, just slow." },
  { q: "Resilience4j's default minimumNumberOfCalls of 100 means…", options: ["The breaker opens sooner", "A low-traffic endpoint may never reach a decision during an incident", "Nothing in practice"], answer: 1,
    explain: "Time-based windows with a minimum around ten are the usual correction." },
  { q: "Sharing one HTTP connection pool across three downstreams means…", options: ["Nothing", "Better utilisation", "One hung dependency starves the others, which then look broken too"], answer: 2,
    explain: "One pool per downstream is the cheapest bulkhead available." },
  { q: "The correct decorator order when stacking Resilience4j annotations is…", options: ["Retry outermost, wrapping CircuitBreaker, TimeLimiter and Bulkhead", "CircuitBreaker outermost", "Order does not matter"], answer: 0,
    explain: "Inverted, one logical call records a single outcome after three attempts, so the breaker sees a third of the failures it should." },
  { q: "server.shutdown: graceful is needed because…", options: ["Otherwise SIGTERM closes the context immediately and cuts in-flight requests mid-response", "It is the default", "It speeds up shutdown"], answer: 0,
    explain: "And the shutdown-phase timeout must exceed your slowest request while staying under the grace period." },
  { q: "Graceful shutdown still dropped requests until a preStop sleep was added because…", options: ["Kubernetes sends SIGTERM immediately while endpoint removal takes seconds to propagate", "Spring was too slow", "The probe failed"], answer: 0,
    explain: "The pod stops accepting connections while traffic is still routed to it; a 5-second preStop took 1,847 dropped requests to zero." },
  { q: "Exit code 137 with no stack trace usually means…", options: ["A failed liveness probe", "The kernel OOM-killed the container — RSS exceeded the limit", "An OutOfMemoryError"], answer: 1,
    explain: "Heap is not the process: metaspace, code cache, thread stacks and direct buffers add 25–40%." },
  { q: "-XX:MaxRAMPercentage is preferred over -Xmx because…", options: ["It disables GC tuning", "It sizes from the container limit, so changing the limit actually changes the heap", "It is newer"], answer: 1,
    explain: "A hard-coded -Xmx silently wastes a raised limit and OOMKills on a lowered one." },
  { q: "p99 of 2.4 s at 34% average CPU in a container points to…", options: ["CFS throttling — the quota is exhausted in a burst and every thread freezes for the rest of the period", "A slow database", "Insufficient heap"], answer: 0,
    explain: "Removing the CPU limit brought p99 to 180 ms; averages hide throttling completely." },
  { q: "The highest-value observability investment for a new service is usually…", options: ["A propagated trace id in logs and error responses", "Dashboards", "More metrics"], answer: 0,
    explain: "It converts 'the site broke around 3pm' into one log search, for roughly twenty lines of code." },
]},
{ title: "Quiz 10 · APIs, Messaging & Reactive — Mock Exam",
  desc: "Compatibility, versioning, pagination, Kafka semantics and WebFlux trade-offs",
  questions: [
  { q: "Adding an optional field to a response broke a partner integration because…", options: ["JSON forbids new fields", "The field was too large", "Their deserialiser had FAIL_ON_UNKNOWN_PROPERTIES enabled, so the whole payload was rejected"], answer: 2,
    explain: "'Additive is safe' assumes tolerant readers — which you cannot verify in clients you do not control." },
  { q: "Adding a new enum value to a response is…", options: ["Breaking in practice — a strict client fails to parse the entire response, not just that field", "Only a documentation change", "Always safe"], answer: 0,
    explain: "Receivers need a default unknown constant; publishers should treat it as a breaking change." },
  { q: "Changing the default sort order of a list endpoint is…", options: ["Safe, since the schema is unchanged", "Impossible", "Breaking in effect — every client's results change, and no diff tool sees it"], answer: 2,
    explain: "The invisible breaks are the dangerous ones precisely because review cannot catch them." },
  { q: "The expensive part of supporting an API version is…", options: ["Branching in the domain logic that must be maintained until the last client leaves", "The URL", "The controller"], answer: 0,
    explain: "One measured codebase had 67 version conditionals and a pricing bug left live in v2 for five months." },
  { q: "Removing a retired endpoint should return…", options: ["301", "404", "410 Gone, with a body naming the replacement"], answer: 2,
    explain: "A silent 404 tells the client author their URL is wrong; 410 tells them what happened." },
  { q: "Offset pagination over changing data is incorrect because…", options: ["It cannot sort", "Positions shift as rows are inserted or deleted, so clients see duplicates and miss rows", "OFFSET is slow"], answer: 1,
    explain: "One export run duplicated 47 orders and missed 51 — and OFFSET 500000 also took 4.2 s per page." },
  { q: "Keyset pagination requires a unique tie-breaker in the sort because…", options: ["Databases require it", "It is faster", "Rows sharing a timestamp straddle the page boundary and one is lost"], answer: 2,
    explain: "Comparing the tuple (created_at, id) makes the ordering total." },
  { q: "Returning Slice instead of Page avoids…", options: ["The COUNT(*) query, which measured 2.9 s against a 4 ms page", "Sorting", "Serialisation cost"], answer: 0,
    explain: "A Next button needs 'is there more', not an exact total." },
  { q: "Two agents editing one resource silently lose an edit unless…", options: ["The database locks the row for the session", "Requests are serialised", "An ETag is returned and If-Match is required, so the stale write gets 412"], answer: 2,
    explain: "Both writes return 200 otherwise; 61 support edits vanished in a month before this was noticed." },
  { q: "An OpenAPI document generated from your controllers cannot…", options: ["Include examples", "Detect a breaking change — it regenerates to match the break", "Describe schemas"], answer: 1,
    explain: "What makes it a contract is a committed baseline plus a diff gate in CI." },
  { q: "In Kafka, ordering is guaranteed…", options: ["Across a topic", "Across a consumer group", "Within a partition only"], answer: 2,
    explain: "A null key sent an order and its cancellation to different partitions and shipped 214 cancelled items." },
  { q: "Adding consumers beyond the partition count…", options: ["Leaves the extra consumers idle — parallelism is capped by partitions", "Causes rebalancing forever", "Increases throughput linearly"], answer: 0,
    explain: "Each partition is assigned to exactly one consumer in a group." },
  { q: "enable.auto.commit: true can lose messages because…", options: ["Commits are asynchronous", "It commits too late", "Offsets are committed on a timer for records returned by the previous poll, processed or not"], answer: 2,
    explain: "One eviction mid-batch acknowledged 1,412 records that were never processed, with no error anywhere." },
  { q: "Kafka's exactly-once semantics apply to…", options: ["Producers only", "Any side effect a consumer performs", "Kafka-to-Kafka pipelines — your database write and your email are outside the transaction"], answer: 2,
    explain: "For a consumer that writes to a database, the honest design is at-least-once plus idempotency." },
  { q: "Processing that exceeds max.poll.interval.ms causes…", options: ["A slower consumer", "A dropped record", "Partition revocation mid-batch, a group-wide rebalance, and reprocessing — the death spiral"], answer: 2,
    explain: "500 records × 800 ms is 400 s against a 300 s default; one case produced 47 rebalances and 4.1M lag at 11% CPU." },
  { q: "A single unprocessable record can block a partition for hours because…", options: ["Kafka retries forever by design", "The broker rejects the offset", "A consumer cannot reach offset N+1 without committing past N"], answer: 2,
    explain: "Five healthy partitions made total lag look normal — alert on max per-partition lag, never the sum." },
  { q: "Non-blocking retry topics trade away…", options: ["Ordering — the failed record returns after records published later", "Durability", "Throughput"], answer: 0,
    explain: "Where per-key ordering matters, use bounded blocking retries and then a dead letter topic." },
  { q: "In reactive code, calling repo.save(x) and ignoring the result…", options: ["Saves asynchronously", "Throws immediately", "Does nothing at all — no subscription, no work, and no error"], answer: 2,
    explain: "One listener logged 4,100 saved orders against zero rows, found two days later by a report." },
  { q: "flatMap's default concurrency of 256 matters because…", options: ["One request can open 256 simultaneous downstream calls, taking a dependency from 40 ms to 8.7 s", "It limits throughput", "It buffers results"], answer: 0,
    explain: "Reactive removes the thread limit that used to bound outbound concurrency accidentally; pass an explicit limit." },
  { q: "The honest summary of WebFlux versus MVC with virtual threads is…", options: ["WebFlux is faster per request", "They are identical", "WebFlux raises the concurrency ceiling and adds streaming and backpressure; virtual threads give the ceiling with ordinary code"], answer: 2,
    explain: "At ordinary concurrency the reactive p99 measured slightly worse — the win is a ceiling, plus capabilities blocking code cannot express." },
]},
);
