// Spring Boot quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Validation & Error Handling",
  desc: "@Valid, Jakarta constraints, @RestControllerAdvice, ProblemDetail",
  questions: [
  { q: "@Valid on a @RequestBody triggers…", options: ["Nothing", "Jakarta Bean Validation before the method runs", "Serialization"], answer: 1,
    explain: "Constraint violations are caught at the boundary." },
  { q: "A validation failure on a body throws…", options: ["NPE", "MethodArgumentNotValidException", "IOException"], answer: 1,
    explain: "Map it to 400 in an advice." },
  { q: "@NotBlank checks…", options: ["Non-null only", "A string is present and not blank", "A number range"], answer: 1,
    explain: "Stronger than @NotNull for strings." },
  { q: "Centralized exception handling uses…", options: ["try/catch everywhere", "@RestControllerAdvice + @ExceptionHandler", "Nothing"], answer: 1,
    explain: "One place maps exceptions to responses." },
  { q: "A catch-all handler should…", options: ["Return the stack trace", "Log detail server-side, return a generic message", "Ignore the error"], answer: 1,
    explain: "Leaking stack traces is an info-disclosure risk." },
  { q: "Validation must run…", options: ["Only in the UI", "Server-side at the trust boundary", "Nowhere"], answer: 1,
    explain: "Clients can bypass UI validation via direct API calls." },
  { q: "Invalid input maps to…", options: ["500", "400 Bad Request", "200"], answer: 1,
    explain: "It's a client error." },
  { q: "ProblemDetail implements…", options: ["A custom format", "RFC 7807 (application/problem+json)", "XML"], answer: 1,
    explain: "A standardized, interoperable error shape." },
  { q: "Domain exceptions should be thrown in…", options: ["Controllers with status codes", "Services; mapped to HTTP in the advice", "The database"], answer: 1,
    explain: "Keeps HTTP concerns out of business logic." },
  { q: "@Validated on the controller class enables…", options: ["Nothing", "Validation of @RequestParam/@PathVariable", "Async"], answer: 1,
    explain: "Method-parameter constraints then apply." },
  { q: "@Size(min=8) on a password checks…", options: ["Its value", "Its length", "Its type"], answer: 1,
    explain: "String/collection length constraint." },
  { q: "Returning 200 with an error body is bad because…", options: ["It's slow", "Clients can't detect failure by status", "It's illegal"], answer: 1,
    explain: "Use the correct status code." },
  { q: "@Valid validates nested objects when…", options: ["Never", "The nested field is also annotated @Valid", "Always automatically"], answer: 1,
    explain: "Cascade requires @Valid on the field." },
  { q: "A ConstraintViolationException comes from…", options: ["@RequestBody", "@Validated param constraints", "Jackson"], answer: 1,
    explain: "Different from the body's MethodArgumentNotValidException." },
  { q: "Leaking exception detail to clients enables…", options: ["Nothing", "Reconnaissance (versions, paths, SQL)", "Faster debugging for them"], answer: 1,
    explain: "Keep messages generic externally." },
  { q: "Client-side validation is…", options: ["A security control", "A UX convenience, not a trust boundary", "Sufficient alone"], answer: 1,
    explain: "The server must validate independently." },
  { q: "Per-field validation messages are built from…", options: ["The stack trace", "BindingResult.getFieldErrors()", "The URL"], answer: 1,
    explain: "Collect them into a field→message map." },
  { q: "@ExceptionHandler(NotFoundException.class) should return…", options: ["500", "404", "200"], answer: 1,
    explain: "Map a missing resource to 404." },
  { q: "The advice pattern beats per-controller try/catch because…", options: ["It's faster", "It's DRY, consistent, and prevents leaked traces", "It's required"], answer: 1,
    explain: "One place owns HTTP translation." },
  { q: "@Email validates…", options: ["Length", "Email format", "Uniqueness"], answer: 1,
    explain: "Format only — uniqueness is a business/DB check." }
]},

{ title: "Quiz 7 · Testing Spring Boot",
  desc: "Slices, MockMvc, @DataJpaTest, Testcontainers, @MockBean",
  questions: [
  { q: "The fastest tests are…", options: ["@SpringBootTest", "Plain JUnit + Mockito (no context)", "@WebMvcTest"], answer: 1,
    explain: "Constructor injection lets you `new` the class with mocks." },
  { q: "@WebMvcTest loads…", options: ["The whole app", "Only the web layer + one controller", "Only JPA"], answer: 1,
    explain: "Collaborators are mocked via @MockBean." },
  { q: "@DataJpaTest is for…", options: ["Controllers", "Repositories and queries", "Security"], answer: 1,
    explain: "It configures JPA and a test DB, rolling back each test." },
  { q: "@SpringBootTest should be used…", options: ["For every test", "Sparingly, for true integration tests", "Never"], answer: 1,
    explain: "It loads the full context and is slow." },
  { q: "MockMvc lets you…", options: ["Query a real DB", "Perform requests against the controller and assert responses", "Deploy"], answer: 1,
    explain: "Tests routing, validation, status, and JSON." },
  { q: "@MockBean replaces…", options: ["A file", "A bean in the context with a Mockito mock", "The database"], answer: 1,
    explain: "Isolates the slice under test." },
  { q: "Prefer Testcontainers over H2 because…", options: ["It's faster", "It runs the real DB engine — no dialect surprises", "It needs no Docker"], answer: 1,
    explain: "H2 differs from Postgres and gives false confidence." },
  { q: "The testing pyramid should be mostly…", options: ["Full integration tests", "Unit tests and slices", "Manual tests"], answer: 1,
    explain: "A thin layer of full-context tests on top." },
  { q: "@DynamicPropertySource is used to…", options: ["Add fields", "Point Spring at a Testcontainer's URL/credentials", "Skip config"], answer: 1,
    explain: "Wires container connection details into properties." },
  { q: "A web slice with a real service means…", options: ["Best isolation", "The test depends on the DB/logic — mock it instead", "Faster tests"], answer: 1,
    explain: "@MockBean the collaborators." },
  { q: "You should also test…", options: ["Only happy paths", "Error/validation paths (400/404)", "Nothing"], answer: 1,
    explain: "Broken error handling ships otherwise." },
  { q: "@DataJpaTest keeps tests isolated by…", options: ["Doing nothing", "Rolling back each test's transaction", "Deleting the schema"], answer: 1,
    explain: "State doesn't leak between tests." },
  { q: "TestRestTemplate / WebTestClient makes…", options: ["Mock calls", "Real HTTP calls against the running app", "DB calls"], answer: 1,
    explain: "Used in full integration tests." },
  { q: "The Boot 3.4+ successor to @MockBean is…", options: ["@FakeBean", "@MockitoBean", "@StubBean"], answer: 1,
    explain: "Same idea, newer annotation." },
  { q: "Constructor injection helps testing by…", options: ["Nothing", "Letting you build the class with mocks, no Spring", "Speeding runtime"], answer: 1,
    explain: "No reflection or context needed." },
  { q: "starter-test includes…", options: ["Only JUnit 4", "JUnit 5, Mockito, AssertJ, MockMvc", "Nothing"], answer: 1,
    explain: "A curated test bundle." },
  { q: "Order-dependent test failures usually mean…", options: ["Good isolation", "State leaks between tests", "Fast tests"], answer: 1,
    explain: "Rely on rollback / fresh containers." },
  { q: "A @WebMvcTest asserting a 400 proves…", options: ["The DB works", "Validation + the error advice work", "Security works"], answer: 1,
    explain: "It exercises the web/validation path." },
  { q: "The narrowest test that proves your point is…", options: ["Always @SpringBootTest", "Preferred — faster and more focused", "Discouraged"], answer: 1,
    explain: "Pick the smallest slice that covers the behavior." },
  { q: "@Container static field with Testcontainers…", options: ["Runs per method", "Starts the container for the test class", "Does nothing"], answer: 1,
    explain: "A static container is shared across the class." }
]},

{ title: "Quiz 8 · Spring Security",
  desc: "Filter chain, authn vs authz, JWT, CSRF, method security",
  questions: [
  { q: "Spring Security is fundamentally…", options: ["A database", "A filter chain in front of your app", "A controller"], answer: 1,
    explain: "Filters run before your controller on each request." },
  { q: "Authentication answers…", options: ["What can you do?", "Who are you?", "How fast?"], answer: 1,
    explain: "Authorization answers what you may do." },
  { q: "401 Unauthorized means…", options: ["Not allowed", "Not authenticated (who are you?)", "Server error"], answer: 1,
    explain: "403 means authenticated but forbidden." },
  { q: "403 Forbidden means…", options: ["Bad credentials", "Authenticated but lacking permission", "Not found"], answer: 1,
    explain: "Identity known, permission denied." },
  { q: "Passwords must be stored…", options: ["In plaintext", "Hashed with BCrypt/Argon2 via PasswordEncoder", "Base64-encoded"], answer: 1,
    explain: "One-way, salted, adaptive hashing." },
  { q: "For a stateless REST API, auth typically uses…", options: ["Session cookies", "A signed JWT in the Authorization header", "IP address"], answer: 1,
    explain: "Enables horizontal scaling without a session store." },
  { q: "A JWT payload is…", options: ["Encrypted", "Signed but readable — no secrets in claims", "Hidden"], answer: 1,
    explain: "Signing proves integrity, not confidentiality." },
  { q: "Disabling CSRF is acceptable when…", options: ["Always", "The API is stateless with header-token auth (no cookies)", "Never"], answer: 1,
    explain: "Keep CSRF on for cookie/session auth." },
  { q: "Method-level authorization uses…", options: ["@Secure", "@PreAuthorize (with @EnableMethodSecurity)", "@Auth"], answer: 1,
    explain: "e.g. @PreAuthorize(\"hasRole('ADMIN')\")." },
  { q: "The JWT filter typically extends…", options: ["HttpServlet", "OncePerRequestFilter", "Controller"], answer: 1,
    explain: "It validates the token once per request." },
  { q: "JWT revocation is hard because…", options: ["Tokens are encrypted", "A valid signature is trusted until expiry", "There are no claims"], answer: 1,
    explain: "Use short expiry + refresh tokens." },
  { q: "The current user can be injected with…", options: ["@RequestBody", "@AuthenticationPrincipal", "@PathVariable"], answer: 1,
    explain: "It pulls the principal from the SecurityContext." },
  { q: "Modern security config declares a…", options: ["WebSecurityConfigurerAdapter", "SecurityFilterChain @Bean (lambda DSL)", "web.xml"], answer: 1,
    explain: "The adapter class is deprecated." },
  { q: "STATELESS session policy means…", options: ["Use sessions", "No server-side session — rely on the token", "One session per app"], answer: 1,
    explain: "Fits token-based auth." },
  { q: "Defence in depth means…", options: ["One check is enough", "URL rules + @PreAuthorize on sensitive ops", "No checks"], answer: 1,
    explain: "Layered authorization." },
  { q: "UI-only auth checks are…", options: ["Sufficient", "Bypassable via direct API calls — enforce server-side", "Best practice"], answer: 1,
    explain: "The server is the real boundary." },
  { q: "BCrypt verifies a login by…", options: ["Decrypting the hash", "matches(raw, storedHash) — one-way", "Comparing plaintext"], answer: 1,
    explain: "It hashes and compares; it can't decrypt." },
  { q: "A stolen long-lived JWT is dangerous because…", options: ["It expires instantly", "It stays valid until expiry with no easy revocation", "It's encrypted"], answer: 1,
    explain: "Short expiry + refresh tokens limit exposure." },
  { q: "The chain returns 401 when…", options: ["A role check fails", "The authentication filter can't establish identity", "The DB is down"], answer: 1,
    explain: "403 is for a failed authorization rule." },
  { q: "hasRole('ADMIN') on /api/admin/** restricts by…", options: ["IP", "Authority/role", "Time of day"], answer: 1,
    explain: "URL-level authorization by role." }
]},

{ title: "Quiz 9 · Actuator, Caching, Async & Scheduling",
  desc: "Observability, health probes, metrics, @Cacheable, @Async, @Scheduled",
  questions: [
  { q: "Actuator adds…", options: ["A database", "Health/metrics/diagnostics endpoints", "A UI framework"], answer: 1,
    explain: "One starter, production-grade endpoints." },
  { q: "Actuator endpoints are exposed by default…", options: ["All of them", "Minimally — you opt in via exposure.include", "None ever"], answer: 1,
    explain: "Expose only what you need, secured." },
  { q: "Liveness probe failure should cause…", options: ["Traffic removal only", "A pod restart", "Nothing"], answer: 1,
    explain: "Readiness failure removes it from the load balancer." },
  { q: "Readiness probe failure should cause…", options: ["A restart", "Removal from the load balancer (no restart)", "A crash"], answer: 1,
    explain: "The pod may just be warming up." },
  { q: "Micrometer is…", options: ["A logger", "A vendor-neutral metrics facade", "A database"], answer: 1,
    explain: "One API, many backends (Prometheus, Datadog)." },
  { q: "High-cardinality metric tags (e.g. userId) cause…", options: ["Nothing", "Time-series explosion and cost/memory blow-up", "Faster metrics"], answer: 1,
    explain: "Keep tag values bounded." },
  { q: "The three pillars of observability are…", options: ["CPU, RAM, disk", "Metrics, logs, traces", "Dev, test, prod"], answer: 1,
    explain: "Spring provides all three." },
  { q: "@Cacheable caches by…", options: ["Return type", "The method arguments", "Time only"], answer: 1,
    explain: "Same args → cached result; runs only on a miss." },
  { q: "The default cache in production should be replaced with…", options: ["Nothing", "Caffeine (TTL/size) or Redis (shared)", "A file"], answer: 1,
    explain: "The default ConcurrentMap has no eviction/expiry." },
  { q: "@Async must have…", options: ["Nothing", "A bounded Executor bean defined", "A database"], answer: 1,
    explain: "The default can create unbounded threads." },
  { q: "@Scheduled across many instances…", options: ["Runs once total", "Runs on every instance (needs a distributed lock)", "Never runs"], answer: 1,
    explain: "Use ShedLock/clustered scheduler for run-once." },
  { q: "@Async, @Cacheable, @Transactional, @Scheduled share which gotcha?", options: ["They're slow", "Self-invocation bypasses the AOP proxy", "They need XML"], answer: 1,
    explain: "Internal this.method() calls skip the proxy." },
  { q: "A fire-and-forget @Async void method…", options: ["Reports errors", "Swallows exceptions unless a handler is set", "Blocks the caller"], answer: 1,
    explain: "Return a CompletableFuture to handle results/errors." },
  { q: "@CacheEvict is used to…", options: ["Add to the cache", "Remove entries (e.g. on delete)", "Time the method"], answer: 1,
    explain: "@CachePut updates; @CacheEvict removes." },
  { q: "@Scheduled(cron=\"0 0 3 * * *\") runs…", options: ["Every 3s", "At 03:00 daily", "Once at startup"], answer: 1,
    explain: "Cron: sec min hour dom mon dow." },
  { q: "fixedDelay vs fixedRate: fixedDelay measures from…", options: ["Start to start", "The end of the previous run", "Midnight"], answer: 1,
    explain: "fixedRate is start-to-start; fixedDelay waits after completion." },
  { q: "Custom health for a downstream dependency uses…", options: ["A controller", "A HealthIndicator bean", "A filter"], answer: 1,
    explain: "It reports UP/DOWN with details." },
  { q: "HTTP request metrics (count, latency, status)…", options: ["Need custom code", "Come for free with Actuator/Micrometer", "Aren't available"], answer: 1,
    explain: "http.server.requests is auto-instrumented." },
  { q: "Cache invalidation strategy should be…", options: ["Ignored", "A sensible TTL + evict on writes", "Cache forever"], answer: 1,
    explain: "The hard part of caching is staleness." },
  { q: "Actuator endpoints like /env and /heapdump should be…", options: ["Public", "Secured / on a separate management port", "Deleted"], answer: 1,
    explain: "They expose config and internals." }
]},

{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Interview-difficulty questions across the whole track",
  questions: [
  { q: "The core of Spring is…", options: ["An ORM", "The IoC container that creates and wires beans", "A web server"], answer: 1,
    explain: "Everything else plugs into the container." },
  { q: "Constructor injection is preferred because it…", options: ["Is shorter", "Yields final fields and framework-free testability", "Runs faster"], answer: 1,
    explain: "Explicit, immutable, fail-fast, testable." },
  { q: "Auto-configuration works via…", options: ["Reflection magic", "@Conditional-guarded bean registration", "Bytecode rewriting"], answer: 1,
    explain: "Inspectable conditions based on classpath and beans." },
  { q: "You override an auto-configured bean by…", options: ["Editing Boot", "Defining your own bean (backs off via @ConditionalOnMissingBean)", "You can't"], answer: 1,
    explain: "Your bean wins." },
  { q: "The API boundary should use…", options: ["JPA entities", "DTOs/records", "Raw maps"], answer: 1,
    explain: "Decouples API from schema; avoids lazy-init leaks." },
  { q: "A created resource returns…", options: ["200", "201 + Location", "204"], answer: 1,
    explain: "Correct REST semantics." },
  { q: "Config precedence: which wins?", options: ["The packaged file", "Command-line args / env vars over the file", "Random"], answer: 1,
    explain: "Later sources override earlier ones." },
  { q: "Secrets belong…", options: ["In application.yml", "In env vars / a vault, never in git", "In code"], answer: 1,
    explain: "Keep credentials out of the artifact." },
  { q: "The N+1 problem is fixed with…", options: ["More RAM", "JOIN FETCH / @EntityGraph", "EAGER everything"], answer: 1,
    explain: "Fetch the association in one query." },
  { q: "@Transactional self-invocation…", options: ["Works", "Is ignored (proxy bypassed)", "Errors"], answer: 1,
    explain: "Shared proxy gotcha with @Async/@Cacheable." },
  { q: "In prod, ddl-auto should be…", options: ["update", "validate (+ Flyway migrations)", "create-drop"], answer: 1,
    explain: "Never let Hibernate mutate the prod schema." },
  { q: "Validate untrusted input…", options: ["In the UI only", "Server-side at the trust boundary", "Never"], answer: 1,
    explain: "Clients can bypass the UI." },
  { q: "Global error handling uses…", options: ["try/catch per controller", "@RestControllerAdvice", "Nothing"], answer: 1,
    explain: "Consistent typed errors, no leaked traces." },
  { q: "401 vs 403: 403 means…", options: ["Not authenticated", "Authenticated but not permitted", "Not found"], answer: 1,
    explain: "401 = who are you; 403 = not allowed." },
  { q: "A JWT is…", options: ["Encrypted and secret", "Signed and readable — no secrets in claims", "A session id"], answer: 1,
    explain: "Signature proves integrity, not confidentiality." },
  { q: "Prefer Testcontainers over H2 because…", options: ["It's faster", "It runs the real DB engine", "It needs no Docker"], answer: 1,
    explain: "Avoids dialect false-positives." },
  { q: "The fastest tests use…", options: ["@SpringBootTest", "Plain JUnit + Mockito (no context)", "@DataJpaTest"], answer: 1,
    explain: "Slices and full-context tests are slower." },
  { q: "Liveness vs readiness: readiness failure…", options: ["Restarts the pod", "Removes it from the load balancer", "Does nothing"], answer: 1,
    explain: "Liveness restarts; readiness gates traffic." },
  { q: "@Scheduled in a multi-instance deploy needs…", options: ["Nothing", "A distributed lock (ShedLock) for run-once", "More CPU"], answer: 1,
    explain: "Otherwise every instance runs the job." },
  { q: "Zero-downtime rolling deploys need…", options: ["Nothing special", "Graceful shutdown + readiness probes", "A bigger heap"], answer: 1,
    explain: "Drain in-flight requests; gate traffic on readiness." }
]}
);
