// Spring Boot quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · IoC, DI & Beans",
  desc: "Inversion of control, dependency injection, beans, scope",
  questions: [
  { q: "Inversion of Control means…", options: ["Your code creates its dependencies", "The container creates and wires dependencies", "Code runs backwards"], answer: 1,
    explain: "The framework, not your code, controls object creation and wiring." },
  { q: "The preferred injection style is…", options: ["Field (@Autowired on a field)", "Constructor injection", "Static setter"], answer: 1,
    explain: "Constructor injection gives final fields, explicit deps, and easy testing." },
  { q: "A key benefit of constructor injection is…", options: ["Shorter code", "You can `new` the class with mocks in a unit test", "It's faster at runtime"], answer: 1,
    explain: "No Spring context needed — pass mocks directly to the constructor." },
  { q: "A 'bean' is…", options: ["A config file", "An object the container creates and manages", "A Java primitive"], answer: 1,
    explain: "Beans are container-managed objects with a lifecycle." },
  { q: "The default bean scope is…", options: ["prototype", "singleton (one instance per context)", "request"], answer: 1,
    explain: "One shared instance is injected everywhere by default." },
  { q: "Because singletons are shared across threads, beans should be…", options: ["Mutable", "Stateless", "Synchronized everywhere"], answer: 1,
    explain: "Mutable fields on a singleton are shared state and a race risk." },
  { q: "@Service, @Repository, @Controller are all…", options: ["Unrelated", "Specializations of @Component", "Deprecated"], answer: 1,
    explain: "All are stereotypes discovered by component scanning." },
  { q: "To register a third-party class you can't annotate, use…", options: ["@Service on it", "A @Bean method in a @Configuration class", "Nothing works"], answer: 1,
    explain: "@Bean factory methods build and register objects you don't own." },
  { q: "Two beans of one interface with no qualifier causes…", options: ["It picks one at random", "NoUniqueBeanDefinitionException", "A warning only"], answer: 1,
    explain: "Ambiguity fails startup unless resolved." },
  { q: "To pick a default among multiple candidates, use…", options: ["@Primary", "@Default", "@Main"], answer: 0,
    explain: "@Primary marks the preferred bean; @Qualifier names one explicitly." },
  { q: "@Qualifier is used to…", options: ["Speed up beans", "Name which specific bean to inject", "Validate config"], answer: 1,
    explain: "It disambiguates by bean name at the injection point." },
  { q: "Injecting List<PaymentGateway> gives you…", options: ["An error", "All beans of that type", "Only the primary"], answer: 1,
    explain: "Spring injects every matching bean into the collection." },
  { q: "@PostConstruct runs…", options: ["Before wiring", "After wiring, before the bean is used", "On shutdown"], answer: 1,
    explain: "It's a post-initialization hook; @PreDestroy runs at shutdown." },
  { q: "@Scope(\"prototype\") means…", options: ["One shared instance", "A new instance every time it's requested", "One per thread"], answer: 1,
    explain: "Prototype beans are created on each injection/lookup." },
  { q: "Why avoid `new OrderService(...)` yourself?", options: ["It's slower", "The container won't inject its dependencies or proxy it", "It's illegal Java"], answer: 1,
    explain: "Manually constructed objects aren't managed — deps are null, no AOP." },
  { q: "Field injection is discouraged because it…", options: ["Is verbose", "Hides dependencies and needs reflection to test", "Doesn't compile"], answer: 1,
    explain: "Hidden deps and reflection-based test setup make it inferior." },
  { q: "Beans not found are often caused by…", options: ["Too much RAM", "Living outside the scanned package", "Wrong Java version"], answer: 1,
    explain: "@ComponentScan is relative to the main class's package." },
  { q: "DI operationalizes which OOP principle?", options: ["Inheritance everywhere", "Program to interfaces + composition", "Global state"], answer: 1,
    explain: "You depend on interfaces and compose via the container." },
  { q: "Per-request state on a singleton bean should live…", options: ["In an instance field", "In method parameters / local variables", "In a static field"], answer: 1,
    explain: "Keep singletons stateless; pass state through the call." },
  { q: "The IoC container's core job is to…", options: ["Compile code", "Create, wire, and manage the lifecycle of beans", "Serve HTTP only"], answer: 1,
    explain: "That management is the foundation everything else builds on." }
]},

{ title: "Quiz 2 · Auto-Config & Starters",
  desc: "Starters, auto-configuration, @SpringBootApplication",
  questions: [
  { q: "A 'starter' dependency is…", options: ["A single class", "A curated, version-managed bundle of dependencies", "A build tool"], answer: 1,
    explain: "e.g. starter-web pulls MVC, Jackson, and embedded Tomcat." },
  { q: "@SpringBootApplication combines…", options: ["Only @Configuration", "@Configuration + @ComponentScan + @EnableAutoConfiguration", "Nothing"], answer: 1,
    explain: "It's a convenience meta-annotation of those three." },
  { q: "Auto-configuration decides what to configure based on…", options: ["Random defaults", "Classpath contents and your existing beans (conditions)", "The OS"], answer: 1,
    explain: "@Conditional* guards each auto-config class." },
  { q: "@ConditionalOnMissingBean means the auto-config…", options: ["Always runs", "Backs off if you define your own bean of that type", "Never runs"], answer: 1,
    explain: "Defining your own bean overrides the default." },
  { q: "You override an auto-configured bean by…", options: ["Editing the framework", "Declaring your own @Bean of the same type", "It can't be done"], answer: 1,
    explain: "Most auto-config uses @ConditionalOnMissingBean and backs off." },
  { q: "The Boot parent POM / BOM provides…", options: ["Source code", "Managed, compatible dependency versions", "Runtime speed"], answer: 1,
    explain: "You don't specify starter versions — the BOM pins them." },
  { q: "Component scanning is relative to…", options: ["The project root", "The @SpringBootApplication class's package and below", "The classpath root"], answer: 1,
    explain: "Beans in sibling/parent packages aren't scanned by default." },
  { q: "To see the auto-config report, run with…", options: ["--debug", "--verbose", "--report"], answer: 0,
    explain: "It prints which conditions matched and why." },
  { q: "Over HTTP, the condition report is at…", options: ["/report", "/actuator/conditions", "/debug"], answer: 1,
    explain: "Actuator exposes the same condition-evaluation report." },
  { q: "To exclude an auto-config, use…", options: ["@SpringBootApplication(exclude=...)", "@Delete", "You can't"], answer: 0,
    explain: "Or spring.autoconfigure.exclude in properties." },
  { q: "Adding starter-web auto-configures…", options: ["Nothing", "DispatcherServlet, Jackson, an embedded server", "A database only"], answer: 1,
    explain: "It wires the whole web stack from the classpath." },
  { q: "Adding a JDBC driver + JPA starter gives you a…", options: ["Nothing", "Auto-configured DataSource (if configured)", "REST controller"], answer: 1,
    explain: "Boot builds a DataSource from spring.datasource.* properties." },
  { q: "Auto-configuration is essentially…", options: ["Reflection magic", "Ordinary conditional bean registration", "Bytecode rewriting"], answer: 1,
    explain: "It's inspectable @Conditional-guarded @Bean definitions." },
  { q: "A common 'no qualifying bean' cause is…", options: ["Slow disk", "Code outside the scanned package", "Wrong port"], answer: 1,
    explain: "Move code under the main application package." },
  { q: "You should add starters that…", options: ["You might need someday", "You actually use", "Are the newest"], answer: 1,
    explain: "Unused starters add bloat, startup time, and attack surface." },
  { q: "@EnableAutoConfiguration is turned on by…", options: ["@RestController", "@SpringBootApplication", "@Service"], answer: 1,
    explain: "It's one of the three annotations it bundles." },
  { q: "Where are auto-config classes registered?", options: ["In your main method", "In META-INF import files inside starters", "In application.yml"], answer: 1,
    explain: "Boot loads them from the AutoConfiguration.imports file." },
  { q: "Convention over configuration means…", options: ["No config allowed", "Sensible defaults you only override when needed", "XML everywhere"], answer: 1,
    explain: "Defaults cover the common case; you tune the exceptions." },
  { q: "The risk of auto-config 'magic' is…", options: ["It's slow", "Devs who don't understand it struggle to debug/override", "It's insecure by design"], answer: 1,
    explain: "Understand the mechanisms via the condition report." },
  { q: "Starter-test brings in…", options: ["Only JUnit", "JUnit 5, Mockito, AssertJ, MockMvc", "Nothing"], answer: 1,
    explain: "A curated testing bundle for Spring Boot." }
]},

{ title: "Quiz 3 · REST Controllers",
  desc: "@RestController, mapping, DTOs, status codes",
  questions: [
  { q: "@RestController equals…", options: ["@Controller only", "@Controller + @ResponseBody", "@Service"], answer: 1,
    explain: "Return values are serialized to the body, not resolved as views." },
  { q: "@PathVariable binds from…", options: ["The query string", "A URL path segment", "A header"], answer: 1,
    explain: "e.g. /users/{id} → id." },
  { q: "@RequestParam binds from…", options: ["The path", "The query string or form", "The body"], answer: 1,
    explain: "e.g. ?page=2&size=20." },
  { q: "@RequestBody binds from…", options: ["A header", "The request body (JSON → object)", "The URL"], answer: 1,
    explain: "Jackson deserializes JSON into the parameter type." },
  { q: "A newly created resource should return…", options: ["200", "201 Created (+ Location)", "204"], answer: 1,
    explain: "201 signals creation; Location points to the new resource." },
  { q: "A successful DELETE with no body returns…", options: ["200", "204 No Content", "404"], answer: 1,
    explain: "204 means success with nothing to return." },
  { q: "You should expose at the API boundary…", options: ["JPA entities", "DTOs / records", "Raw maps"], answer: 1,
    explain: "DTOs decouple the API from the schema and avoid leaks." },
  { q: "Returning a JPA entity risks…", options: ["Nothing", "Schema coupling and LazyInitializationException", "Faster responses"], answer: 1,
    explain: "Serializing lazy relations outside a tx throws." },
  { q: "Use ResponseEntity when you need…", options: ["Always", "Dynamic status or response headers", "Never"], answer: 1,
    explain: "Return the DTO directly otherwise." },
  { q: "Jackson handles JSON…", options: ["Only inbound", "Both serialization and deserialization automatically", "Not at all"], answer: 1,
    explain: "It's auto-configured by starter-web." },
  { q: "@ResponseStatus(HttpStatus.CREATED) sets…", options: ["The body", "A fixed 201 status", "A header only"], answer: 1,
    explain: "It declares a static non-200 status for the method." },
  { q: "Business logic in a controller is…", options: ["Best practice", "An anti-pattern — delegate to @Service", "Required"], answer: 1,
    explain: "Thin controllers keep layers testable." },
  { q: "@CrossOrigin(\"*\") is…", options: ["Recommended", "A security risk — whitelist explicit origins", "Required for CORS"], answer: 1,
    explain: "Wide-open CORS exposes your API broadly." },
  { q: "Using @Controller instead of @RestController for an API…", options: ["Is identical", "Returns a view name, not JSON", "Is faster"], answer: 1,
    explain: "You'd need @ResponseBody to serialize the body." },
  { q: "A missing resource should return…", options: ["200", "404 Not Found", "500"], answer: 1,
    explain: "Map a NotFoundException to 404." },
  { q: "@RequestHeader binds from…", options: ["The body", "An HTTP header", "The path"], answer: 1,
    explain: "e.g. Authorization." },
  { q: "@RequestMapping(\"/api/users\") on the class sets…", options: ["The port", "A base path for all its methods", "The content type"], answer: 1,
    explain: "Method mappings are relative to it." },
  { q: "A conflict (duplicate/version) maps best to…", options: ["400", "409 Conflict", "404"], answer: 1,
    explain: "409 signals a state conflict." },
  { q: "Input DTOs let you…", options: ["Nothing", "Shape/validate input separately from the entity", "Skip validation"], answer: 1,
    explain: "e.g. a create request without an id field." },
  { q: "The list endpoint filter ?role=ADMIN is bound with…", options: ["@PathVariable", "@RequestParam", "@RequestBody"], answer: 1,
    explain: "Query parameters use @RequestParam." }
]},

{ title: "Quiz 4 · Configuration & Profiles",
  desc: "application.yml, @ConfigurationProperties, precedence, profiles",
  questions: [
  { q: "Externalized config lets you…", options: ["Rebuild per environment", "Run the same jar everywhere driven by config", "Skip config"], answer: 1,
    explain: "One immutable artifact, reconfigured externally." },
  { q: "For a group of related settings, prefer…", options: ["Scattered @Value", "@ConfigurationProperties (typed, validated)", "Hardcoding"], answer: 1,
    explain: "Type safety, validation, and cohesion." },
  { q: "@Value is best for…", options: ["Large config trees", "A single one-off value", "Secrets"], answer: 1,
    explain: "Groups belong in a properties class." },
  { q: "Config precedence (later wins) is roughly…", options: ["Args < env < file", "File < profile file < env vars < command-line args", "Random"], answer: 1,
    explain: "Env vars and args override the packaged file." },
  { q: "Secrets should be…", options: ["In application.yml", "Injected via env vars / a vault, not committed", "In code comments"], answer: 1,
    explain: "Keep credentials out of git and the artifact." },
  { q: "${DB_PASSWORD:default} means…", options: ["Always 'default'", "Use env var, fall back to 'default' if unset", "An error"], answer: 1,
    explain: "Placeholder with a default value." },
  { q: "Profile-specific config lives in…", options: ["application.yml only", "application-{profile}.yml", "code"], answer: 1,
    explain: "e.g. application-prod.yml overrides shared defaults." },
  { q: "Activate a profile with…", options: ["--profile", "--spring.profiles.active=prod (or SPRING_PROFILES_ACTIVE)", "@Profile only"], answer: 1,
    explain: "Sets the active profile at runtime." },
  { q: "@Profile(\"dev\") on a @Bean means it…", options: ["Always exists", "Exists only when the dev profile is active", "Is deleted"], answer: 1,
    explain: "Profile-scoped beans switch per environment." },
  { q: "ddl-auto: create-drop in production…", options: ["Is safe", "Wipes data on restart", "Is required"], answer: 1,
    explain: "Use validate + migrations in prod." },
  { q: "@ConfigurationProperties + @Validated gives you…", options: ["Nothing", "Startup validation of config values", "Faster boot"], answer: 1,
    explain: "Bad config fails fast at startup." },
  { q: "Env var SPRING_DATASOURCE_URL maps to…", options: ["Nothing", "spring.datasource.url (relaxed binding)", "A file path"], answer: 1,
    explain: "Boot maps env var names to property keys." },
  { q: "Command-line --server.port=9000…", options: ["Is ignored", "Overrides the file's port (args win)", "Errors"], answer: 1,
    explain: "Args are near the top of the precedence order." },
  { q: "Hardcoding per-env values in code forces…", options: ["Nothing", "A rebuild per environment", "Faster deploys"], answer: 1,
    explain: "Externalize instead." },
  { q: "The base application.yml should hold…", options: ["Secrets", "Structure and non-secret defaults", "Nothing"], answer: 1,
    explain: "Profiles and env override the rest." },
  { q: "YAML vs .properties…", options: ["Only properties work", "Both work; YAML nests better", "Only YAML works"], answer: 1,
    explain: "Choose either; behavior is the same." },
  { q: "Forgetting to activate a profile in prod causes…", options: ["Nothing", "Prod to run with dev defaults", "A crash always"], answer: 1,
    explain: "Set SPRING_PROFILES_ACTIVE on the platform." },
  { q: "@EnableConfigurationProperties registers…", options: ["Controllers", "A @ConfigurationProperties class as a bean", "Profiles"], answer: 1,
    explain: "Or use @ConfigurationPropertiesScan." },
  { q: "Injecting the whole PaymentProps object beats @Value because…", options: ["It's shorter only", "It's cohesive, typed, and validated", "It's faster at runtime"], answer: 1,
    explain: "One object vs a dozen string injections." },
  { q: "A record is a good fit for @ConfigurationProperties because…", options: ["It's mutable", "It's immutable and concise for a settings group", "It's required"], answer: 1,
    explain: "Immutable config binds cleanly to a record." }
]},

{ title: "Quiz 5 · Spring Data JPA",
  desc: "Repositories, queries, N+1, transactions, fetching",
  questions: [
  { q: "Extending JpaRepository gives you…", options: ["Nothing", "CRUD, paging, and derived queries for free", "Only save()"], answer: 1,
    explain: "The implementation is generated by Spring Data." },
  { q: "A derived query method like findByEmail…", options: ["Needs an impl", "Is generated from the method name", "Is invalid"], answer: 1,
    explain: "Spring Data parses the name into a query." },
  { q: "The N+1 problem is…", options: ["A network error", "1 query for the list + 1 per row for a lazy association", "A GC issue"], answer: 1,
    explain: "Accessing a lazy relation in a loop fires many queries." },
  { q: "The fix for N+1 is…", options: ["More RAM", "JOIN FETCH or @EntityGraph", "EAGER everything"], answer: 1,
    explain: "Load the association in one query." },
  { q: "@Transactional belongs on…", options: ["Repositories", "Service methods (one business operation)", "Controllers"], answer: 1,
    explain: "The whole multi-step op commits or rolls back together." },
  { q: "Self-invoking a @Transactional method in the same class…", options: ["Works fine", "Bypasses the proxy — the annotation is ignored", "Errors"], answer: 1,
    explain: "Proxy-based advice only applies to external calls." },
  { q: "Default rollback triggers on…", options: ["All exceptions", "Unchecked (RuntimeException) only", "None"], answer: 1,
    explain: "Checked exceptions commit unless rollbackFor is set." },
  { q: "@ManyToOne defaults to…", options: ["LAZY", "EAGER", "None"], answer: 1,
    explain: "Collections default LAZY; *ToOne default EAGER." },
  { q: "The recommended production default is…", options: ["EAGER everywhere", "LAZY, fetching what you need per query", "No relations"], answer: 1,
    explain: "Avoid over-fetching; fetch explicitly." },
  { q: "Accessing a lazy relation outside a transaction throws…", options: ["Nothing", "LazyInitializationException", "NPE always"], answer: 1,
    explain: "Map to DTOs inside the tx." },
  { q: "@Enumerated should use…", options: ["ORDINAL (default)", "EnumType.STRING", "Neither"], answer: 1,
    explain: "ORDINAL corrupts data if you reorder the enum." },
  { q: "For custom logic beyond derivation, use…", options: ["Nothing", "@Query (JPQL or nativeQuery)", "A controller"], answer: 1,
    explain: "JPQL for entity queries, native for raw SQL." },
  { q: "You see the actual SQL with…", options: ["Nothing", "spring.jpa.show-sql=true", "--debug only"], answer: 1,
    explain: "Essential for spotting N+1." },
  { q: "findAll() on a huge table risks…", options: ["Nothing", "OutOfMemoryError", "Faster reads"], answer: 1,
    explain: "Page large result sets." },
  { q: "Page<User> from a Pageable query gives you…", options: ["Only rows", "Rows plus total count and paging metadata", "A single row"], answer: 1,
    explain: "getTotalElements() fires a COUNT query." },
  { q: "@Modifying is needed on…", options: ["SELECT @Query", "UPDATE/DELETE @Query", "All @Query"], answer: 1,
    explain: "It marks a query as a write." },
  { q: "In a @Transactional method, managed entities are…", options: ["Never saved", "Flushed on commit via dirty checking", "Read-only"], answer: 1,
    explain: "You often don't need an explicit save()." },
  { q: "Spring Data JPA sits on top of…", options: ["JDBC only", "Hibernate (the JPA provider)", "Redis"], answer: 1,
    explain: "It wraps Hibernate to remove boilerplate." },
  { q: "hibernate.default_batch_fetch_size helps with…", options: ["Security", "Batching lazy loads to reduce N+1", "Logging"], answer: 1,
    explain: "Turns N queries into N/batch." },
  { q: "findByRoleAndActiveTrue(role) is…", options: ["Invalid", "A derived query combining two conditions", "A native query"], answer: 1,
    explain: "Method-name keywords compose the WHERE clause." }
]}
);
