// typescript quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations: Erasure, Widening & Inference",
  desc: "What survives compilation, how literals widen, and where types come from",
  questions: [
  { q: "What does a TypeScript type do at run time?", options: ["It validates values when they are assigned", "Nothing — types are erased before the code runs", "It becomes a runtime shape check in the emitted JavaScript"], answer: 1,
    explain: "Compilation removes every annotation. That single fact explains why JSON.parse is unchecked, why brands vanish, and why a type predicate's body is never verified." },
  { q: "Which construct is NOT erasable, and therefore fails under `erasableSyntaxOnly`?", options: ["A generic type parameter", "An `enum`", "An interface"], answer: 1,
    explain: "`enum` emits a runtime object, so it cannot simply be deleted. `erasableSyntaxOnly` reports TS1294 for it, and for `namespace` and parameter properties." },
  { q: "`const x = \"hello\"` infers which type?", options: ["`string`", "`\"hello\"` — the literal type", "`any`"], answer: 1,
    explain: "A `const` binding cannot be reassigned, so the literal type is kept. The same initialiser with `let` widens to `string`." },
  { q: "`let x = \"hello\"` infers which type?", options: ["`string`", "`String`", "`\"hello\"`"], answer: 0,
    explain: "Widening: because the binding is mutable, the literal is generalised to its base primitive so a later assignment is legal." },
  { q: "What is the difference between `as const` and a type annotation on an object literal?", options: ["`as const` validates the shape; an annotation preserves literals", "`as const` preserves literals and makes it readonly; an annotation widens them and checks the shape", "They are equivalent"], answer: 1,
    explain: "They do different jobs, which is why `as const satisfies T` exists — it keeps the literals and still validates." },
  { q: "What does `satisfies T` do that a `: T` annotation does not?", options: ["It performs a runtime check", "It widens the value to T", "It checks the value against T while keeping the inferred type"], answer: 2,
    explain: "An annotation replaces the inferred type with T. `satisfies` checks against T and leaves the narrower inferred type in place." },
  { q: "`unknown` differs from `any` because…", options: ["`unknown` is a runtime type guard", "Nothing can be done with an `unknown` until it is narrowed", "`unknown` only accepts objects"], answer: 1,
    explain: "Both accept any value, but `unknown` refuses every operation until you narrow it — which is why it is the correct entry type for external data." },
  { q: "What is the type of `JSON.parse(\"{}\")`?", options: ["`object`", "`any`", "`unknown`"], answer: 1,
    explain: "It is `any`, which is why it silently disables checking downstream. Assigning it to `unknown` immediately is the discipline that closes the hole." },
  { q: "Which of these is true of `never`?", options: ["It is an alias for `undefined`", "It is assignable to every type", "Every type is assignable to it"], answer: 1,
    explain: "`never` is the empty type, so it is assignable everywhere and nothing (except `never`) is assignable to it — which is what makes exhaustiveness checks work." },
  { q: "TypeScript 7's compiler is notable because…", options: ["It dropped support for generics", "It requires a JVM", "It is written in Go and runs natively"], answer: 2,
    explain: "The native compiler is substantially faster than the JavaScript implementation, though a pathological type is still pathological — measure rather than assume." },
  { q: "In TypeScript 7, running `tsc file.ts` with no flags and no tsconfig…", options: ["uses strict mode by default", "requires a tsconfig.json to run", "disables all checking"], answer: 0,
    explain: "Verified by compiling a file with `const b: string = a` where `a` is `string | null`: TS2322 with no flags, silent under `--strict false`." },
  { q: "Why is `--showConfig` a poor way to check whether strict mode is on?", options: ["It requires a network connection", "It only prints options that were set explicitly", "It always reports strict: true"], answer: 1,
    explain: "Defaults do not appear in its output. Compiling a file that violates a check is the reliable test." },
  { q: "`type A = string` and `type B = string` are…", options: ["Distinct types that cannot be mixed", "Distinct only under strict mode", "The same type — an alias creates no new type"], answer: 2,
    explain: "An alias names a type; it does not create one. That is the gap branded types exist to close." },
  { q: "An excess property on an object literal assigned to a typed variable…", options: ["Is an error — excess property checking applies to fresh literals", "Widens the target type", "Is silently allowed"], answer: 0,
    explain: "Freshness triggers the check. Assigning the same object through a variable first bypasses it, which surprises people." },
  { q: "What is the inferred type of `const xs = [1, \"a\"]`?", options: ["`[number, string]`", "`unknown[]`", "`(string | number)[]`"], answer: 2,
    explain: "Arrays widen to an array of the union. `as const` or a `const` type parameter is what preserves the tuple." },
  { q: "`interface` and `type` differ mainly in that…", options: ["`interface` can be reopened and merged; `type` cannot", "`interface` is checked at run time", "`type` cannot describe objects"], answer: 0,
    explain: "Declaration merging is the real difference. It is why library augmentation targets interfaces, and why `type` is safer for closed definitions." },
  { q: "Which annotation is required for a value that may legitimately be absent?", options: ["`x: string` plus a runtime check", "`x: any`", "`x?: string` or `x: string | undefined`"], answer: 2,
    explain: "The two forms differ once `exactOptionalPropertyTypes` is on: `?` means 'may be absent', the union means 'present, possibly undefined'." },
  { q: "Under `strictNullChecks`, `Array.prototype.find` returns…", options: ["`T | null`", "`T`", "`T | undefined`"], answer: 2,
    explain: "The honest type. Without the flag it is just `T`, which is the single most common source of runtime undefined errors." },
  { q: "Why is `as` called an assertion rather than a cast?", options: ["It only works on primitives", "It converts the value at run time", "It changes what the compiler believes without checking or converting anything"], answer: 2,
    explain: "No code is emitted. It is a claim, which is why `JSON.parse(x) as User` provides exactly zero safety." },
  { q: "Bundlers and `tsc` differ in that a bundler…", options: ["strips types without checking them", "type-checks faster than tsc", "cannot process TypeScript"], answer: 0,
    explain: "Verified: esbuild compiled `const n: number = \"definitely not a number\"` and exited 0. Only `tsc` checks types." },
]},
{ title: "Quiz 2 · Structural Typing, Variance & Functions",
  desc: "Shape-based compatibility, parameter variance, overloads and predicates",
  questions: [
  { q: "TypeScript decides whether two types are compatible by…", options: ["Comparing their structure", "Comparing their declared names", "Checking an explicit `implements` clause"], answer: 0,
    explain: "Structural typing: an object literal satisfies an interface without declaring anything. That is why `implements` guarantees nothing about assignability." },
  { q: "What does `implements` actually do?", options: ["Makes the class assignable only where that interface is expected", "Checks that the class satisfies the interface", "Supplies types for the method parameters"], answer: 1,
    explain: "It is a check and nothing more. It notably does NOT provide contextual types — `log(msg) {}` is still an implicit-any error." },
  { q: "A function type's parameters are checked…", options: ["Covariantly", "Bivariantly, always", "Contravariantly, under `strictFunctionTypes`"], answer: 2,
    explain: "A function accepting a wider parameter can stand in for one accepting a narrower parameter. Methods remain bivariant for compatibility reasons." },
  { q: "Why are method parameters bivariant while function-property parameters are not?", options: ["Methods are compiled differently", "A deliberate unsoundness kept for compatibility with array and DOM types", "Methods cannot be generic"], answer: 1,
    explain: "It is a known hole. Declaring a callback as a function-typed property rather than a method gets the stricter checking." },
  { q: "`(x: string) => void` is assignable to `(x: string | number) => void`?", options: ["No, under `strictFunctionTypes`", "Only for methods", "Yes"], answer: 0,
    explain: "The narrower parameter cannot accept everything the wider signature promises to pass. This is TS2322 under the flag." },
  { q: "A function returning `string` assigned where `() => void` is expected…", options: ["Compiles — the return value is simply discarded", "Is an error", "Widens the target to `() => string`"], answer: 0,
    explain: "This void-return rule is deliberate, and it is exactly why `arr.forEach(async …)` compiles and silently awaits nothing." },
  { q: "What is a type predicate?", options: ["A compiler flag", "A runtime assertion library", "A function whose return type is written `v is T`"], answer: 2,
    explain: "It narrows its argument inside the true branch. The compiler never checks that the body justifies the claim." },
  { q: "The compiler verifies a type predicate's body…", options: ["Not at all", "Only under strict mode", "Fully"], answer: 0,
    explain: "Verified: a predicate checking only `typeof v === \"object\"` compiles clean and then throws TypeError at run time." },
  { q: "What does `asserts v is T` do?", options: ["Narrows for the rest of the scope, throwing on failure", "Performs a runtime cast", "Returns a boolean"], answer: 0,
    explain: "It suits boundaries where failure means aborting, and it removes the need to nest the rest of the function in an `if`." },
  { q: "Calling an assertion function through an un-annotated alias gives…", options: ["TS2345", "TS2775", "No error"], answer: 1,
    explain: "\"Assertions require every name in the call target to be declared with an explicit type annotation\" — control-flow analysis must know statically that the call asserts." },
  { q: "When should you prefer overloads to a conditional return type?", options: ["On a public API, for readable errors and completions", "Never — conditional types are always better", "Only for generic functions"], answer: 0,
    explain: "A conditional return type shows unresolved in tooltips and produces errors quoting the conditional. Overloads give exact completions." },
  { q: "`ReturnType` applied to an overloaded function gives…", options: ["A union of all return types", "An error", "The last overload's return type"], answer: 2,
    explain: "Silently. Deriving types from overloaded functions therefore gives one arbitrary case." },
  { q: "`Parameters<typeof f>` for `f(a: string, b?: number)` is…", options: ["`(string | number)[]`", "`[a: string, b?: number | undefined]`", "`[string, number]`"], answer: 1,
    explain: "Labels and optionality are preserved, which is why a wrapper built on it shows the original parameter names in completions." },
  { q: "An optional parameter and a parameter typed `| undefined` differ because…", options: ["The union form cannot receive undefined", "They are identical", "The optional one may be omitted at the call site"], answer: 2,
    explain: "`b?: number` lets the caller omit the argument; `b: number | undefined` requires passing something, even if it is undefined." },
  { q: "`this` parameters in TypeScript…", options: ["Are a compile-time-only first parameter used to type `this`", "Are not supported", "Are a real runtime parameter"], answer: 0,
    explain: "It is erased, and it is how a callback that depends on its `this` binding can be typed correctly." },
  { q: "A class with a `private` member is structurally compatible with a structurally identical class that has none?", options: ["Only under strict mode", "Yes", "No — private members make the comparison nominal"], answer: 2,
    explain: "Private members participate in assignability, which is the mechanism behind using a private field for genuine nominal typing." },
  { q: "Excess property checking applies to…", options: ["Fresh object literals", "Only function arguments", "All assignments"], answer: 0,
    explain: "Freshness is the trigger. Assigning through an intermediate variable loses freshness and the check no longer applies." },
  { q: "`readonly` on an array type prevents…", options: ["`push` and index assignment", "Mutating the elements", "Passing it to a function"], answer: 0,
    explain: "It stops mutating the array itself, not the objects inside it. Depth requires an explicit DeepReadonly." },
  { q: "The safest constraint for 'any function' is…", options: ["`Function`", "`any`", "`(...args: never[]) => unknown`"], answer: 2,
    explain: "`Function` accepts anything callable and types nothing. The `never[]` form works because parameters are contravariant." },
  { q: "Why does `const r: string = identity(42)` fail?", options: ["`identity` has no type parameter", "Inference runs from the arguments, so T was already `number`", "The annotation is invalid"], answer: 1,
    explain: "TS2322 at the assignment. An annotation is a requirement on the result, not an instruction to the inference algorithm." },
]},
{ title: "Quiz 3 · Narrowing & Generics",
  desc: "Control-flow analysis, discriminated unions, type parameters and constraints",
  questions: [
  { q: "Which of these narrows a union?", options: ["`typeof x === \"string\"`", "A comment naming the type", "An `as` assertion"], answer: 0,
    explain: "Control-flow analysis understands `typeof`, `instanceof`, `in`, equality against a literal, and truthiness. An assertion changes belief without narrowing logic." },
  { q: "A discriminated union is narrowed most reliably by…", options: ["Checking for a property with `in`", "Using `instanceof`", "Switching on a shared literal-typed discriminant"], answer: 2,
    explain: "A literal discriminant makes each branch unambiguous and enables the `never` exhaustiveness check." },
  { q: "Narrowing is lost when a value is…", options: ["Captured in a closure that may run later", "Compared twice", "Passed to a function"], answer: 0,
    explain: "The compiler cannot know when the closure runs, so it conservatively resets the narrowing — a common surprise in callbacks." },
  { q: "Assigning a narrowed value to another variable…", options: ["Narrows via aliasing only for `const` declarations", "Keeps the narrowing on both", "Always loses the narrowing"], answer: 0,
    explain: "Aliased narrowing works for a `const` holding the condition, but not for a mutable binding the compiler cannot prove is unchanged." },
  { q: "`typeof null` returns…", options: ["`\"object\"`", "`\"undefined\"`", "`\"null\"`"], answer: 0,
    explain: "A JavaScript quirk the type system respects — which is why a null check must accompany `typeof v === \"object\"`." },
  { q: "The exhaustiveness check works by…", options: ["Using a `Record` type", "Throwing in the default branch", "Assigning the narrowed value to `never` in the default branch"], answer: 2,
    explain: "Once every case is handled the value's type is `never`; a missing case makes the assignment fail, naming the variant." },
  { q: "What did the verified exhaustiveness error look like when a `tri` case was forgotten?", options: ["TS7030: not all code paths return a value", "TS2322: not assignable to type 'never', naming the tri member", "No error until run time"], answer: 1,
    explain: "The message quotes the whole unhandled member, which is what makes the pattern actionable rather than merely strict." },
  { q: "A generic is better than `any` because…", options: ["It performs a runtime check", "It is faster at run time", "It relates the input type to the output type"], answer: 2,
    explain: "`first<T>(xs: readonly T[]): T | undefined` preserves the caller's element type; the `any` version destroys it." },
  { q: "A type parameter that appears only once in a signature is…", options: ["Optimal", "Required for inference", "Usually a disguised `unknown`"], answer: 2,
    explain: "It relates nothing. `function log<T>(v: T): void` is identical in behaviour to `log(v: unknown): void`." },
  { q: "`function parse<T>(json: string): T` is problematic because…", options: ["T must be constrained", "It cannot be called", "The body cannot produce a T — it is `as T` in disguise"], answer: 2,
    explain: "Every call site gets a fully typed value backed by nothing. Taking a validator makes the parameter appear twice and the type earned." },
  { q: "`pick<T extends object, K extends keyof T>(o: T, k: K): T[K]` called with a bad key gives…", options: ["`unknown`", "TS2345 naming the valid key union", "No error"], answer: 1,
    explain: "Verified: `Argument of type '\"nope\"' is not assignable to parameter of type '\"x\"'`." },
  { q: "`pick({ x: 1, y: \"s\" }, \"y\")` returns which type?", options: ["`unknown`", "`string | number`", "`string`"], answer: 2,
    explain: "The `T[K]` indexed access gives the exact property type, not a union of all value types." },
  { q: "What does a `const` type parameter — `<const T>` — do?", options: ["Preserves literal types at the call site without `as const`", "Requires a constant argument", "Makes the parameter readonly at run time"], answer: 0,
    explain: "Verified: `pair([\"a\",\"b\"])` gives `readonly [\"a\", \"b\"]` where the plain version widens to `string[]`." },
  { q: "Inferring from an empty array, as in `first([])`, gives…", options: ["`never[]`, so nothing fits later", "An error", "`unknown[]`"], answer: 0,
    explain: "There is nothing to infer from. Supplying the type argument explicitly — `first<string>([])` — is the fix." },
  { q: "Contextual typing is the exception to 'inference flows from arguments' because…", options: ["The expected parameter type flows into a callback's parameters", "It requires an annotation", "It only applies to classes"], answer: 0,
    explain: "That is why `nums.map(n => n * 2)` knows `n` is a number without any annotation." },
  { q: "Generics exist at run time?", options: ["No — they are erased, so `new T()` is impossible", "Yes, as metadata", "Only for classes"], answer: 0,
    explain: "If a body must construct a T, the caller has to pass a constructor or factory explicitly." },
  { q: "A default type argument of `any` is dangerous because…", options: ["It causes a compile error", "Every caller who omits it silently loses checking", "It conflicts with constraints"], answer: 1,
    explain: "A default should be a useful concrete type, or absent entirely." },
  { q: "The idiomatic way to type an event emitter so the payload follows the name is…", options: ["Overloads per event", "A map type plus `<K extends keyof M>(name: K, payload: M[K])`", "`Record<string, unknown>`"], answer: 1,
    explain: "The keyof/indexed-access pairing does the work, and one emitter then handles every event with exact payload checking." },
  { q: "`keyof` a union type gives…", options: ["Only the keys the members have in common", "The union of all members' keys", "`string`"], answer: 0,
    explain: "It is the intersection. This is precisely why `Omit` destroys a discriminated union." },
  { q: "When should you introduce a generic?", options: ["When a caller's type must travel through the function", "Whenever a function takes an object", "Pre-emptively, for flexibility"], answer: 0,
    explain: "Generalise on the second real caller. 'Might be useful later' is complexity with one user." },
]},
{ title: "Quiz 4 · Conditional & Mapped Types",
  desc: "Distribution, infer, homomorphism, key remapping and template literals",
  questions: [
  { q: "`extends` in a conditional type asks…", options: ["Whether both are classes", "Whether the left type is assignable to the right", "Whether the left type inherits from the right"], answer: 1,
    explain: "It is the structural assignability question, which is why `{a:1;b:2} extends {a:number}` is true." },
  { q: "`IsString<string | number>` where `IsString<T> = T extends string ? \"yes\" : \"no\"` is…", options: ["`\"no\"`", "`\"yes\" | \"no\"`", "`never`"], answer: 1,
    explain: "Verified by assignability: both literals are accepted, so the type is the union — the conditional distributed over the union." },
  { q: "How do you stop a conditional type distributing?", options: ["Add `readonly`", "Use an interface", "Wrap both sides in a tuple: `[T] extends [U]`"], answer: 2,
    explain: "The checked type is then no longer a naked type parameter, so the test runs once against the whole union." },
  { q: "`IsString<never>` evaluates to…", options: ["`\"no\"`", "`never`", "`\"yes\"`"], answer: 1,
    explain: "`never` is the empty union, so distributing over it produces zero results. `[never] extends [string]` gives `\"yes\"` instead." },
  { q: "A conditional type applied to `any` returns…", options: ["The union of both branches", "`any`", "The true branch"], answer: 0,
    explain: "`any` satisfies the test and also does not. A conditional returning a suspicious union usually has an `any` upstream." },
  { q: "`unknown extends string` is…", options: ["false", "both", "true"], answer: 0,
    explain: "`unknown` is assignable only to `unknown` and `any`. `never extends string`, by contrast, is true." },
  { q: "Where is `infer` valid?", options: ["Anywhere in a type alias", "Only in function parameters", "Only in the `extends` clause of a conditional type"], answer: 2,
    explain: "Outside that position it is a syntax error." },
  { q: "`infer H extends string` in a tuple pattern does what when the head is a number?", options: ["Widens to `string`", "Infers `never`", "Falls to the false branch — the match itself fails"], answer: 2,
    explain: "Verified: `FirstStr<[\"x\", 1]>` is `\"x\"` but `FirstStr<[1, \"x\"]>` is `\"none\"`." },
  { q: "The same `infer` variable used in two covariant positions produces…", options: ["The first candidate only", "A union of the candidates", "An error"], answer: 1,
    explain: "Verified: `Both<{ a: string; b: number }>` is `string | number`." },
  { q: "Unbounded recursion in a conditional type produces…", options: ["TS2590", "A hang with no error", "TS2589"], answer: 2,
    explain: "\"Type instantiation is excessively deep and possibly infinite.\" A depth-counter tuple bounds it by construction." },
  { q: "Which mapped type form preserves `readonly` and `?` modifiers?", options: ["Both equally", "`{ [K in Extract<keyof T, string>]: … }`", "`{ [K in keyof T]: … }`"], answer: 2,
    explain: "Only the homomorphic form. Verified: changing the key source silently drops `readonly` and turns arrays into objects." },
  { q: "`Partial<string[]>` evaluates to…", options: ["`(string | undefined)[]`", "`string[] | undefined`", "An object with numeric keys"], answer: 0,
    explain: "Homomorphic maps pass arrays through as arrays, mapping the elements." },
  { q: "`-readonly` and `-?` in a mapped type…", options: ["Add those modifiers", "Are syntax errors", "Remove them"], answer: 2,
    explain: "The `-` prefix removes. Removal needs its own syntax precisely because homomorphic maps preserve by default." },
  { q: "An `as` clause in a mapped type…", options: ["Adds a key alongside the original", "Breaks homomorphism", "Renames the key, and keeps homomorphism"], answer: 2,
    explain: "The original key is gone — accessing it gives TS2339 — but modifiers are still preserved." },
  { q: "Mapping a key to `never` in the `as` clause…", options: ["Removes the property", "Sets its value to never", "Is an error"], answer: 0,
    explain: "That is how key filtering works." },
  { q: "Filtering with `T[K] extends string` on a type with `name?: string` gives…", options: ["`\"id\"` only — the optional's type includes undefined", "`never`", "`\"id\" | \"name\"`"], answer: 0,
    explain: "Verified. `NonNullable<T[K]> extends string` is the version that includes optional string properties." },
  { q: "Why write `K & string` when interpolating a key?", options: ["`keyof T` may include number and symbol keys", "For readability", "To make it readonly"], answer: 0,
    explain: "Template literals cannot interpolate symbols, so the intersection narrows each key to its string part." },
  { q: "`Capitalize<\"hello world\">` is…", options: ["`\"Hello World\"`", "`\"HELLO WORLD\"`", "`\"Hello world\"`"], answer: 2,
    explain: "Verified — it changes the first character only." },
  { q: "Template literal types combining unions produce…", options: ["A single string type", "The union of the slots", "The cross product of the slots"], answer: 2,
    explain: "`btn-${\"sm\"|\"lg\"}-${\"primary\"|\"danger\"}` is four members. The count multiplies with every slot." },
  { q: "A template literal union that is too large gives…", options: ["A silent `string`", "TS2589", "TS2590"], answer: 2,
    explain: "\"Expression produces a union type that is too complex to represent.\" Verified at one million members; ten thousand still compiles." },
]},
{ title: "Quiz 5 · Utility Types & Strictness",
  desc: "The standard helpers as they actually behave, and what `strict` does and does not cover",
  questions: [
  { q: "`Partial<T>` makes nested objects optional too?", options: ["Yes", "Only under strict mode", "No — it is shallow"], answer: 2,
    explain: "Verified: the nested property's type is `{ a: number } | undefined`, not a partial version of it." },
  { q: "`Readonly<Config>` prevents…", options: ["Reassigning a top-level property only", "Nothing at run time or compile time", "Both reassignment and nested mutation"], answer: 0,
    explain: "Verified: `r.nested.a = 1` compiles. It also does nothing at run time — `Object.freeze` is a separate decision." },
  { q: "`Pick<User, \"agee\">` with a typo gives…", options: ["TS2344 — the key must satisfy `keyof User`", "`unknown`", "No error"], answer: 0,
    explain: "`Pick` constrains its key parameter. `Omit` does not, which is the asymmetry." },
  { q: "`Omit<User, \"agee\">` with a typo gives…", options: ["`never`", "No error, and nothing is removed", "TS2344"], answer: 1,
    explain: "Verified: its key parameter is `PropertyKey`, so the typo compiles and `age` is still present. An `OmitStrict` wrapper closes it." },
  { q: "`Omit<Shape, \"kind\">` where `Shape` is a discriminated union produces…", options: ["The union with `kind` removed from each member", "A single type with neither member's fields", "An error"], answer: 1,
    explain: "Verified: both `st.r` and `st.s` give TS2339. `keyof` a union is the common keys only, so removing `kind` leaves nothing." },
  { q: "How do you omit a key across a union safely?", options: ["Use `Exclude` instead", "Use `Partial` first", "Distribute first: `T extends unknown ? Omit<T, K> : never`"], answer: 2,
    explain: "The naked type parameter makes the conditional distributive, so `Omit` is applied per member." },
  { q: "`Exclude<T, U>` is defined as…", options: ["`T extends U ? T : never`", "`T extends U ? never : T`", "`Omit<T, U>`"], answer: 1,
    explain: "A distributive conditional. `Extract` is the same shape with the branches swapped." },
  { q: "`Awaited<Promise<Promise<number>>>` is…", options: ["`Promise<number>`", "`number`", "`unknown`"], answer: 1,
    explain: "Verified — it unwraps recursively, and it also distributes over unions. Do not hand-roll it." },
  { q: "`InstanceType<C>` where `C` is a class gives…", options: ["The instance type", "A constraint error — you need `typeof C`", "The constructor type"], answer: 1,
    explain: "The bare class name is already the instance type; `typeof C` is the constructor." },
  { q: "`Record<\"a\" | \"b\", number>` missing the `b` key gives…", options: ["`undefined` for b", "No error", "TS2741 — the property is required"], answer: 2,
    explain: "A literal-union key is exhaustive, which makes it the right tool for a handler table keyed by a discriminant." },
  { q: "`Record<string, number>` accessed with a missing key gives…", options: ["An error", "`number` — every key appears to exist", "`number | undefined`"], answer: 1,
    explain: "Verified. `noUncheckedIndexedAccess` is what makes it honest, or use a `Map`." },
  { q: "Which is NOT enabled by `strict`?", options: ["`useUnknownInCatchVariables`", "`strictNullChecks`", "`noUncheckedIndexedAccess`"], answer: 2,
    explain: "Verified by compiling violations with and without `--strict false`: seven flags are members, and six useful checks including this one are outside." },
  { q: "The error code for `useUnknownInCatchVariables` being violated is…", options: ["TS18046", "TS2564", "TS7006"], answer: 0,
    explain: "\"'e' is of type 'unknown'.\" TS2564 is strictPropertyInitialization and TS7006 is noImplicitAny." },
  { q: "`exactOptionalPropertyTypes` makes `{ name: undefined }` assignable to `{ name?: string }`?", options: ["Only for nested objects", "No — TS2375", "Yes"], answer: 1,
    explain: "It separates 'absent' from 'explicitly undefined', which matters for `in` checks, `Object.keys` and JSON.stringify." },
  { q: "`noImplicitReturns` adds value over strict alone for…", options: ["Functions with an inferred return type", "Async functions only", "Functions with an annotated return type"], answer: 0,
    explain: "Verified: an annotated `: number` already fails under strict with TS2366; an inferred one is silent until TS7030." },
  { q: "In TypeScript 7, `alwaysStrict: false` in a config produces…", options: ["TS5108 — the value has been removed", "TS5023 — unknown option", "No error"], answer: 0,
    explain: "The option still exists but cannot be disabled. TS5023 is what you get for options removed entirely." },
  { q: "Which of these was removed outright in TypeScript 7?", options: ["`suppressExcessPropertyErrors`", "`noImplicitAny`", "`skipLibCheck`"], answer: 0,
    explain: "Verified as TS5023, along with `suppressImplicitAnyIndexErrors`, `keyofStringsOnly`, `noImplicitUseStrict` and the old import flags." },
  { q: "The safest way to clear a `strictNullChecks` error during a migration is…", options: ["`as any`", "A non-null assertion", "Handling the case, or fixing the upstream type"], answer: 2,
    explain: "Clearing errors with assertions produces a codebase that compiles under strict mode with exactly the same bugs, better hidden." },
  { q: "`@ts-expect-error` differs from `@ts-ignore` because…", options: ["It suppresses more error kinds", "It works on whole files", "It reports TS2578 when the error goes away"], answer: 2,
    explain: "Verified. That self-cleaning property is what makes a migration ratchet possible without manual audits." },
  { q: "Strict mode cannot protect you from…", options: ["Data arriving from outside the program", "Unsound function variance", "Implicit `any` parameters"], answer: 0,
    explain: "It verifies the program's internal consistency. `JSON.parse` is `any`, and every boundary claim is unchecked until you parse it." },
]},
);
