// linux quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations & the Filesystem",
  desc: "How Unix is put together, the directory tree, inodes, links and permissions.",
  questions: [
  { q: "What does the Unix philosophy \"everything is a file\" actually mean in practice?", options: ["The kernel stores all configuration in /etc as text files", "Every piece of data is stored on disk as a file", "Devices, pipes and sockets are all accessed through the same file-descriptor interface (read/write/close)"], answer: 2,
    explain: "It is about the interface, not storage. A socket, a pipe, a terminal and a disk file are all reached through a file descriptor and the same read/write/close syscalls, which is why shell redirection composes with almost anything." },
  { q: "What is the difference between an absolute and a relative path?", options: ["Absolute paths start with /, relative paths are resolved from the current working directory", "Absolute paths contain no symlinks", "Relative paths only work inside your home directory"], answer: 0,
    explain: "An absolute path starts at the root, so it means the same thing from anywhere. A relative path is interpreted from the process's current working directory, which every process carries as part of its state." },
  { q: "According to the Filesystem Hierarchy Standard, what belongs in /var?", options: ["Variable data that changes during normal operation — logs, spools, caches, databases", "User home directories", "Statically linked binaries needed for boot"], answer: 0,
    explain: "/var holds data that grows and changes: /var/log, /var/spool, /var/lib. It is the directory most likely to fill a disk, which is why it is often a separate filesystem." },
  { q: "What is an inode?", options: ["The first block of a file's contents", "The name of a file in a directory", "A structure holding a file's metadata and block pointers — everything about the file except its name"], answer: 2,
    explain: "The inode holds size, permissions, timestamps, link count and the pointers to data blocks. The filename lives in the directory entry, which maps a name to an inode number." },
  { q: "What is a directory, at the filesystem level?", options: ["An index maintained by the shell", "A contiguous region of disk reserved for its files", "A special kind of inode containing a list of name-to-inode-number mappings"], answer: 2,
    explain: "A directory is a file whose contents are pairs of (name, inode number). That is why renaming a file within a filesystem is cheap and why one inode can have several names." },
  { q: "What happens to a file's data when you delete one of its two hard links?", options: ["The data is deleted immediately", "The remaining link becomes a symlink", "Nothing — the link count drops to 1 and the data remains reachable through the other name"], answer: 2,
    explain: "Data is freed only when the link count reaches zero AND no process holds the file open. Hard links are equal names for the same inode; none is the 'original'." },
  { q: "Which statement about symbolic links is correct?", options: ["They cannot point to directories", "They can point across filesystems and can dangle if the target is removed", "They increase the target's link count"], answer: 1,
    explain: "A symlink stores a path as its contents, so it can cross filesystems and point at directories — and it breaks silently if the target disappears, unlike a hard link." },
  { q: "A file has mode 0644 and is owned by root:root. You are an ordinary user in no special groups. What can you do?", options: ["Read it only", "Read and write it", "Nothing — you are not the owner"], answer: 0,
    explain: "0644 is rw- for owner, r-- for group, r-- for others. You match 'others', so you get read only. Permission checks stop at the first matching class." },
  { q: "What does the execute bit mean on a directory?", options: ["You may traverse into it and access files whose names you know", "You may list its contents", "You may run programs stored in it"], answer: 0,
    explain: "On a directory, x means 'search' — permission to resolve a path through it. r is what lets you list names. A directory with x but not r is traversable but not listable." },
  { q: "What does the setuid bit on an executable do?", options: ["It makes the program run in the background", "It runs the program with the privileges of the file's owner rather than the caller", "It prevents the file from being deleted"], answer: 1,
    explain: "/usr/bin/passwd is setuid root so any user can update /etc/shadow through it. Every setuid binary is a potential privilege escalation, which is why they should be audited." },
  { q: "What is the purpose of the sticky bit on /tmp?", options: ["It keeps files in memory for faster access", "It prevents users from deleting files they do not own, even in a world-writable directory", "It makes files persist across reboots"], answer: 1,
    explain: "Without it, any user could delete any other user's files in a 1777 directory, because delete permission comes from the directory, not the file." },
  { q: "What does umask 022 result in for a newly created file requesting mode 0666?", options: ["0755", "0644", "0622"], answer: 1,
    explain: "umask clears bits: 0666 with 022 masked off gives 0644. It is a mask of permissions to remove, not permissions to grant." },
  { q: "Why is `chmod 777` on a directory almost always the wrong fix?", options: ["It is slow on large directories", "It grants write and delete to every user on the system, when the actual problem is usually ownership or group membership", "It breaks symbolic links inside"], answer: 1,
    explain: "777 is a blunt instrument that removes the boundary entirely. The correct fix is nearly always setting the right owner/group, or using a setgid directory for shared access." },
  { q: "What does the setgid bit on a directory do?", options: ["It makes new files inside inherit the directory's group", "It runs every program inside as the group owner", "It prevents the directory from being renamed"], answer: 0,
    explain: "Setgid on a directory is the standard mechanism for shared team directories — everything created inside belongs to the shared group automatically." },
  { q: "How many hard links does a newly created empty directory have?", options: ["3", "1", "2 — its own name and its '.' entry"], answer: 2,
    explain: "A directory's link count starts at 2 (the name in its parent, plus '.'), and each subdirectory adds one more via its '..' entry." },
  { q: "What is /proc?", options: ["A virtual filesystem generated by the kernel exposing process and system state as files", "A directory of process binaries", "A cache of recently run programs"], answer: 0,
    explain: "/proc has no disk backing at all. Reading /proc/PID/status makes the kernel generate the content on the fly, which is how tools like ps work." },
  { q: "You cannot delete a file even though you own it. What is the most likely reason?", options: ["The file is currently open", "The file is read-only", "You lack write permission on the containing directory"], answer: 2,
    explain: "Deletion removes a directory entry, so it is governed by write+execute on the directory, not by the file's own permissions." },
  { q: "What does `ls -i` show?", options: ["Whether each file is indexed", "File sizes in inodes", "The inode number of each entry"], answer: 2,
    explain: "Comparing inode numbers is how you confirm two names are hard links to the same file rather than two separate copies." },
  { q: "Why does moving a file within one filesystem take constant time regardless of its size?", options: ["The kernel copies it in the background", "Only the directory entry changes — the inode and data blocks are untouched", "Filesystems keep a move cache"], answer: 1,
    explain: "A same-filesystem mv is a rename: unlink the old name, link the new one. Across filesystems it becomes a genuine copy-then-delete, which is why it is slow and non-atomic." },
  { q: "What is the practical significance of rename() being atomic within a filesystem?", options: ["It makes moves faster", "It prevents two processes renaming the same file", "It is the primitive for safe file updates — a reader sees either the old file or the new one, never a partial write"], answer: 2,
    explain: "Write to a temp file, fsync it, rename over the target, then fsync the directory. This is the standard safe-save recipe, and the last step is the one usually omitted." },
]},
{ title: "Quiz 2 · The Shell",
  desc: "Expansion order, quoting, redirection, file descriptors and pipes.",
  questions: [
  { q: "In what order does bash process a command line?", options: ["Alphabetically by token", "Brace expansion, tilde, parameter/variable, command substitution, arithmetic, word splitting, then pathname expansion (globbing)", "Globbing first, then variable substitution"], answer: 1,
    explain: "The order matters enormously: variables are substituted before word splitting and globbing, which is exactly why an unquoted variable containing spaces or a '*' behaves unexpectedly." },
  { q: "Why does `rm $file` break when file=\"my report.txt\"?", options: ["After substitution the shell word-splits the result, so rm receives two arguments: 'my' and 'report.txt'", "The variable is not exported", "rm cannot handle spaces at all"], answer: 0,
    explain: "Word splitting happens after substitution. Quoting — `rm \"$file\"` — suppresses it and passes one argument." },
  { q: "What is the difference between single and double quotes?", options: ["Single quotes allow globbing", "No difference in bash", "Double quotes allow variable and command substitution; single quotes are entirely literal"], answer: 2,
    explain: "Use single quotes for regexes, awk programs and anything containing $ or backticks that must survive intact." },
  { q: "What does `2>&1` do?", options: ["Redirects stdout to stderr", "Merges both into a file named 1", "Redirects stderr to wherever stdout currently points"], answer: 2,
    explain: "It duplicates fd 1 into fd 2. Order matters: `cmd > f 2>&1` sends both to the file, while `cmd 2>&1 > f` sends stderr to the original stdout." },
  { q: "Why does `cmd 2>&1 > file` NOT put stderr in the file?", options: ["2>&1 copies the CURRENT stdout (the terminal) before the > redirect changes stdout", "stderr is unbuffered", "You must use &> instead"], answer: 0,
    explain: "Redirections are applied left to right. At the moment 2>&1 runs, stdout is still the terminal, so stderr goes there and only stdout is later redirected to the file." },
  { q: "What are file descriptors 0, 1 and 2 by convention?", options: ["stdin, stdout, stderr", "null, stdin, stdout", "stdout, stdin, stderr"], answer: 0,
    explain: "They are just small integers indexing the process's open-file table; the convention is what makes redirection and pipes composable." },
  { q: "What does a pipe `a | b` actually create?", options: ["A temporary file that b reads after a finishes", "A subshell that runs a then b", "A kernel buffer connecting a's stdout to b's stdin, with both processes running concurrently"], answer: 2,
    explain: "Both run at once. When the buffer fills, the writer blocks; when it empties, the reader blocks — that back-pressure is what makes pipelines memory-safe on huge inputs." },
  { q: "By default, what is the exit status of a pipeline?", options: ["Non-zero if any command failed", "The status of the first command", "The status of the last command"], answer: 2,
    explain: "This is why `set -o pipefail` exists: without it, `false | true` reports success and a failing first stage is invisible." },
  { q: "What is the difference between `>` and `>>`?", options: ["> creates the file, >> requires it to exist", ">> is faster", "> truncates the file to zero first; >> appends to the end"], answer: 2,
    explain: "Both create the file if missing. The important difference is that > destroys existing content immediately, before the command even runs." },
  { q: "What does `command < file` do?", options: ["Writes the command's output to the file", "Connects the file to the command's stdin", "Passes the filename as an argument"], answer: 1,
    explain: "The command reads the file's contents through fd 0 without ever knowing the filename — which is why `wc -l < f` prints no filename while `wc -l f` does." },
  { q: "What is a here-document?", options: ["A temporary file created by mktemp", "A shell function defined inline", "Inline text supplied on stdin, terminated by a delimiter"], answer: 2,
    explain: "`<<'EOF'` with the delimiter quoted keeps the body literal; unquoted, the shell expands variables and command substitutions inside it." },
  { q: "Why does `find . | while read f; do count=$((count+1)); done` leave count at 0?", options: ["count must be exported", "Each stage of a pipeline runs in a subshell, so the variable change is lost when it exits", "read cannot increment variables"], answer: 1,
    explain: "Use process substitution — `while ... done < <(find .)` — to keep the loop in the current shell." },
  { q: "What does `cmd &` do?", options: ["Runs cmd in the background, returning the prompt immediately", "Runs cmd with elevated privileges", "Runs cmd and discards its output"], answer: 0,
    explain: "The shell forks and does not wait. The job's PID is in $!, and `wait` collects it — background jobs still hold the terminal for output unless redirected." },
  { q: "What is the difference between `&&` and `;` between two commands?", options: ["&& runs the second only if the first succeeded; ; runs it unconditionally", "None", "; runs both in parallel"], answer: 0,
    explain: "`||` is the mirror image: run the second only if the first failed, which is the basis of the `cmd || die` idiom." },
  { q: "What does `$?` contain?", options: ["The exit status of the most recently completed foreground command", "The PID of the last background job", "The number of arguments"], answer: 0,
    explain: "0 means success by convention. It is overwritten by every command, so capture it immediately — including as the first line of a trap handler." },
  { q: "What is command substitution `$(cmd)`?", options: ["Runs cmd in the background", "Runs cmd and substitutes its stdout into the command line", "Defines cmd as an alias"], answer: 1,
    explain: "Trailing newlines are stripped. It is preferred over backticks because it nests cleanly and its quoting rules are far less surprising." },
  { q: "Why does `echo *` list your files?", options: ["* is an alias for ls", "echo has a built-in directory listing", "The shell expands the glob before echo ever runs — echo receives the filenames as arguments"], answer: 2,
    explain: "Globbing is done by the shell, not the program. This is also why `find . -name *.txt` breaks: the shell expands it before find sees it." },
  { q: "What is the difference between a shell builtin and an external command?", options: ["Externals cannot be scripted", "Builtins run inside the shell process itself; externals are separate programs found via PATH and require fork+exec", "Builtins are faster only"], answer: 1,
    explain: "It matters for things like cd, which MUST be a builtin — an external process could only change its own working directory, not the shell's." },
  { q: "What does `exec 3< file` do?", options: ["Runs file as a program", "Redirects fd 3 to stdin", "Opens the file on file descriptor 3 for the current shell"], answer: 2,
    explain: "This is how scripts hold a descriptor open — the basis of the flock idiom, where the lock is released automatically when the fd closes." },
  { q: "What is the practical difference between `>/dev/null 2>&1` and `&>/dev/null`?", options: ["The second only discards stderr", "The second is bash-specific shorthand for the same effect", "The first also closes the descriptors"], answer: 1,
    explain: "`&>` is a bash convenience. The long form is POSIX-portable, which matters in scripts with a /bin/sh shebang." },
]},
{ title: "Quiz 3 · Text Processing & Finding Files",
  desc: "grep, sed, awk, find and xargs — the tools that make the shell worth using.",
  questions: [
  { q: "What does `grep -q` do?", options: ["Searches quietly in the background", "Suppresses output and exits as soon as a match is found — for use in conditions", "Quotes the pattern"], answer: 1,
    explain: "It exits early on the first match, which makes `if grep -q pattern file` both idiomatic and efficient on large files." },
  { q: "What is the difference between `grep -F` and plain grep?", options: ["-F treats the pattern as a fixed string, disabling regex interpretation", "-F searches files recursively", "-F forces case sensitivity"], answer: 0,
    explain: "Essential when the pattern contains regex metacharacters like '.' or '['— and faster too, since no regex engine is involved." },
  { q: "What does `grep -v` do?", options: ["Verbose output", "Shows the version", "Inverts the match — prints lines that do NOT match"], answer: 2,
    explain: "Frequently combined as `grep -v '^#' | grep -v '^$'` to strip comments and blank lines from a config file." },
  { q: "In `sed 's/old/new/g'`, what does the trailing g do?", options: ["Applies to the whole file rather than one line", "Global — replaces every occurrence on each line, not just the first", "Enables greedy matching"], answer: 1,
    explain: "Without g, sed replaces only the first match per line. sed is line-oriented, so 'global' means within the line." },
  { q: "What does `sed -i` do, and what is the risk?", options: ["Ignores case; no risk", "Prints line numbers", "Edits files in place — and without a backup suffix, a bad expression destroys the original with no undo"], answer: 2,
    explain: "Always test without -i first, or use `sed -i.bak` so the original is preserved." },
  { q: "In awk, what do $0, $1 and NF refer to?", options: ["The script name, first argument, and number of arguments", "The file, first line, and number of lines", "The whole line, the first field, and the number of fields"], answer: 2,
    explain: "$NF is therefore the last field — a very common idiom for extracting the final column regardless of how many there are." },
  { q: "What does `awk '$3 > 100 {print $1}'` do?", options: ["Prints the first field of lines whose third field exceeds 100", "Compares fields 3 and 1", "Prints the first 100 lines"], answer: 0,
    explain: "awk's pattern-action model — an optional condition followed by a block — is what makes it far more suitable than grep for column-based data." },
  { q: "Why is `for f in $(ls)` a bug?", options: ["ls is not available in all shells", "ls is slow", "The output is word-split on whitespace and glob-expanded, so filenames with spaces, newlines or '*' break it"], answer: 2,
    explain: "Use `for f in ./*` for one directory, or `find -print0 | while IFS= read -r -d ''` for recursion. The ./ prefix also stops a file named '-rf' being read as a flag." },
  { q: "What does `find . -name '*.log' -mtime +7` match?", options: ["The 7 newest log files", "Log files last modified more than 7 days ago", "Log files modified in the last 7 days"], answer: 1,
    explain: "+7 means 'more than 7 days', -7 means 'less than 7 days', and 7 means exactly the 8th day back — the off-by-one that catches everyone." },
  { q: "Why quote the pattern in `find . -name '*.txt'`?", options: ["Quotes make it case-insensitive", "Otherwise the shell expands the glob before find runs, passing already-matched filenames", "find requires quotes"], answer: 1,
    explain: "Unquoted, it works in an empty directory and mysteriously fails when a .txt file exists in the current directory — one of the most confusing shell bugs." },
  { q: "What is the difference between `find -exec cmd {} \\;` and `find -exec cmd {} +`?", options: ["\\; is deprecated", "\\; runs the command once per file; + batches many files into one invocation", "+ runs in parallel"], answer: 1,
    explain: "The + form is dramatically faster on large result sets because it avoids one fork+exec per file, similar to what xargs does." },
  { q: "Why use `find -print0 | xargs -0`?", options: ["It is faster", "NUL is the only byte that cannot appear in a filename, so it is the only safe delimiter", "It sorts the output"], answer: 1,
    explain: "Newlines and spaces are legal in filenames; NUL is not. This pairing is the standard safe way to pipe filenames between programs." },
  { q: "What does `xargs -P4` do?", options: ["Prints every 4th result", "Passes 4 arguments per invocation", "Runs up to 4 invocations in parallel"], answer: 2,
    explain: "-n controls arguments per invocation, -P controls parallelism. Together they turn xargs into a simple job-parallel runner." },
  { q: "What does `cut -d: -f1 /etc/passwd` produce?", options: ["Every field except the first", "The first colon-separated field of every line — the usernames", "The first line"], answer: 1,
    explain: "cut is the right tool for fixed-delimiter data; awk is better when fields need conditions or the delimiter is whitespace-variable." },
  { q: "What does `sort | uniq -c | sort -rn` accomplish?", options: ["Removes duplicates in reverse order", "Sorts a file numerically twice", "Counts occurrences of each distinct line and ranks them most-frequent first"], answer: 2,
    explain: "The canonical 'top offenders' pipeline. uniq only collapses ADJACENT duplicates, which is why the first sort is mandatory." },
  { q: "What is the difference between `head -n 5` and `tail -n 5`?", options: ["head prints the first 5 lines, tail the last 5", "They are aliases", "head reads the whole file, tail does not"], answer: 0,
    explain: "`tail -f` follows a growing file; `tail -F` also survives the file being rotated and recreated, which is what you want for logs." },
  { q: "What does `tr -d '\\r'` do?", options: ["Replaces all r characters", "Deletes carriage-return characters — stripping Windows line endings", "Translates r to newline"], answer: 1,
    explain: "A CRLF file causes 'command not found' errors with an invisible \\r on the end, and this is the standard one-liner fix." },
  { q: "In a regex, what is the difference between `*` and `+`?", options: ["They are the same in POSIX", "* matches zero or more of the preceding element; + matches one or more", "* is greedy, + is lazy"], answer: 1,
    explain: "Note the shell's glob '*' means something entirely different — 'any characters' — which is a common source of confusion between the two contexts." },
  { q: "What does the regex anchor `^` mean, and how does it differ from grep's `-x`?", options: ["^ inverts the pattern", "^ matches the start of a line; -x requires the whole line to match", "They are identical"], answer: 1,
    explain: "`grep -qxF \"$line\" file` is the idiomatic 'is this exact line already present' check used for idempotent appends." },
  { q: "Why is `grep pattern file | wc -l` sometimes wrong for counting matches?", options: ["wc counts characters", "grep deduplicates output", "It counts matching LINES, not matches — a line with three matches counts once (use grep -o | wc -l)"], answer: 2,
    explain: "`grep -c` also counts lines. `grep -o pattern file | wc -l` counts individual matches, which is often what was actually intended." },
]},
{ title: "Quiz 4 · Processes, Signals & Job Control",
  desc: "fork, exec, process states, zombies, orphans, signals and graceful shutdown.",
  questions: [
  { q: "What does fork() return?", options: ["0 in the child and the child's PID in the parent", "Always 0 on success", "The child's PID in both processes"], answer: 0,
    explain: "The single call returns twice with different values, which is how each process knows which one it is — the basis of every process-creation idiom in Unix." },
  { q: "What does exec() do to the calling process?", options: ["Creates a new child process", "Replaces the current process image with a new program, keeping the same PID and file descriptors", "Runs a program and returns when it finishes"], answer: 1,
    explain: "On success exec never returns. The fork-then-exec split is what allows the child to set up redirections and drop privileges between the two steps." },
  { q: "What is a zombie process?", options: ["A process that has exited but whose exit status has not yet been collected by its parent", "A process whose parent has died", "A process using excessive CPU"], answer: 0,
    explain: "It holds only a PID table entry, no memory. Many zombies mean the parent is not calling wait() — the process to fix is the parent, not the zombies." },
  { q: "What happens to a process whose parent exits before it does?", options: ["It becomes a zombie immediately", "It is reparented to PID 1 (or the nearest subreaper), which will reap it", "It is killed"], answer: 1,
    explain: "This is the orphan case, and it is why PID 1 must call wait() — a container whose PID 1 does not will accumulate zombies forever." },
  { q: "What does process state D mean in ps output?", options: ["Debugging", "Uninterruptible sleep — usually blocked on disk or network I/O, and cannot be killed even with SIGKILL", "Dead"], answer: 1,
    explain: "D-state processes count toward Linux's load average, which is why a high load can mean I/O blocking rather than CPU demand." },
  { q: "Which signal cannot be caught, blocked, or ignored?", options: ["SIGKILL (9) and SIGSTOP (19)", "SIGTERM", "SIGINT"], answer: 0,
    explain: "That is precisely why cleanup handlers do not run on kill -9, and why anything that must not leak needs a second mechanism such as flock or systemd's RuntimeDirectory." },
  { q: "What is the difference between SIGTERM and SIGKILL?", options: ["SIGTERM is catchable and asks politely; SIGKILL is enforced by the kernel and cannot be handled", "SIGTERM only works on your own processes", "SIGKILL is slower"], answer: 0,
    explain: "Always send SIGTERM first to allow draining and cleanup. SIGKILL is the escalation after a grace period, which is exactly what systemd's TimeoutStopSec implements." },
  { q: "What does Ctrl-C send, and to what?", options: ["SIGKILL to the shell", "SIGTERM to the last background job", "SIGINT to the entire foreground process group"], answer: 2,
    explain: "It goes to the whole group, which is why interrupting a pipeline stops every stage. Ctrl-Z sends SIGTSTP and Ctrl-\\ sends SIGQUIT." },
  { q: "What does `kill -0 PID` do?", options: ["Sends no signal but performs the permission and existence check — used to test whether a process is alive", "Resets the process priority", "Kills the process immediately"], answer: 0,
    explain: "It is the standard way a PID-file-based lock validates whether the recorded process still exists." },
  { q: "Why does a process's exit status of 137 usually indicate an OOM kill?", options: ["It means the disk was full", "137 is a reserved application error code", "128 + 9 = SIGKILL, and the most common uncatchable kill in production is the OOM killer or a container memory limit"], answer: 2,
    explain: "Shell convention encodes signal deaths as 128+signum, so 143 is SIGTERM (128+15) and 130 is SIGINT (128+2)." },
  { q: "What is a process group, and why does it exist?", options: ["A set of related processes that can be signalled together — the shell puts each pipeline in one", "A collection of processes sharing memory", "Processes owned by the same user"], answer: 0,
    explain: "Job control depends on it: the terminal delivers signals to the foreground process group, so Ctrl-C reaches every stage of a pipeline at once." },
  { q: "What does `nohup cmd &` accomplish?", options: ["Runs cmd as root", "Makes cmd immune to SIGHUP so it survives the terminal closing", "Runs cmd with higher priority"], answer: 1,
    explain: "Closing a terminal sends SIGHUP to its jobs. Modern alternatives are `setsid`, tmux, or — for anything long-lived — a systemd unit." },
  { q: "What is the difference between `nice` and `renice`?", options: ["renice only works on your own processes", "nice sets priority when starting a process; renice changes it for one already running", "nice lowers priority, renice raises it"], answer: 1,
    explain: "Higher nice values mean lower priority. Only root can lower a nice value (increase priority), a restriction that prevents users starving each other." },
  { q: "What does `wait` do in a shell script?", options: ["Blocks until background jobs finish and collects their exit statuses", "Sleeps for one second", "Waits for user input"], answer: 0,
    explain: "Without it, a script can exit while its background jobs are still running — and their failures are invisible even with set -e." },
  { q: "Why should a service handle SIGTERM explicitly?", options: ["To stop accepting new work and finish in-flight requests before exiting — otherwise work is dropped", "To prevent being killed", "To log the shutdown reason"], answer: 0,
    explain: "Without a handler the process dies immediately at default disposition, dropping in-flight requests. With one, it can drain within the supervisor's grace period." },
  { q: "What is the difference between `ps aux` and `ps -ef`?", options: ["-ef shows threads", "aux shows only your processes", "They are different syntax conventions (BSD vs UNIX) producing broadly similar information"], answer: 2,
    explain: "ps accepts both styles for historical reasons. `ps -eo pid,comm,stat,wchan` is more useful when you need specific columns." },
  { q: "How does `pgrep -f pattern` differ from `pgrep pattern`?", options: ["-f matches against the full command line, not just the process name", "-f finds only foreground processes", "-f forces a match"], answer: 0,
    explain: "Essential for interpreted programs, where the process name is 'python3' and the distinguishing information is in the arguments." },
  { q: "What does the PPID column tell you?", options: ["The parent process ID — who forked this process", "The number of child processes", "The process priority"], answer: 0,
    explain: "A PPID of 1 means the original parent exited and the process was reparented — often a sign a daemon detached, or that a parent crashed." },
  { q: "Why is `kill -9` a poor first choice?", options: ["The process gets no chance to flush buffers, release locks, or finish in-flight work — it can leave corrupted state", "It is slower than SIGTERM", "It requires root"], answer: 0,
    explain: "SIGKILL should be the escalation after a grace period, not the opening move. Reaching for it habitually hides bugs in shutdown handling." },
  { q: "What does /proc/PID/fd/ contain?", options: ["The process's source code", "Cached file contents", "Symlinks for every open file descriptor, including sockets and deleted files"], answer: 2,
    explain: "It is how you recover a deleted-but-open log file's space by truncating through /proc/PID/fd/N, and how lsof attributes sockets to processes." },
]},
{ title: "Quiz 5 · Syscalls, Memory & the Kernel Boundary",
  desc: "The user/kernel divide, strace, virtual memory, overcommit and the OOM killer.",
  questions: [
  { q: "What is a system call?", options: ["A signal sent to the kernel", "A function in the C library", "The controlled entry point through which a userspace process requests a service from the kernel"], answer: 2,
    explain: "The CPU switches privilege level to execute kernel code. That transition has a cost, which is why syscall-heavy code shows up as high %sys time." },
  { q: "What does strace show you?", options: ["The program's memory layout", "Every system call a process makes, with arguments and return values", "Every function a program calls"], answer: 1,
    explain: "It shows the kernel boundary only — internal function calls are invisible. That is exactly why it answers 'which file did it fail to open' so well." },
  { q: "Why can strace slow a program by 10x or more?", options: ["It disables CPU caches", "It rewrites the binary", "Each traced syscall involves stopping the process and context-switching to the tracer twice"], answer: 2,
    explain: "That overhead makes it unsuitable for latency-sensitive production processes; `perf trace` or eBPF tools are far cheaper alternatives." },
  { q: "What does `strace -f` add?", options: ["Faster tracing", "Follows forked children as well as the parent", "Formats output as JSON"], answer: 1,
    explain: "Without -f you see the shell fork and then nothing, which is the most common reason strace 'shows nothing useful' on a wrapper script." },
  { q: "Which strace invocation best answers 'why can't this program find its config'?", options: ["strace -p PID", "strace -e trace=openat -f prog", "strace -c prog"], answer: 1,
    explain: "Filtering to file-opening syscalls shows every path attempted and which returned ENOENT — usually revealing an unexpected working directory or search order." },
  { q: "What does `strace -c` produce?", options: ["Only syscalls that failed", "A compressed trace file", "A count and time summary per syscall rather than a line-by-line trace"], answer: 2,
    explain: "It quickly reveals patterns like millions of tiny read() calls, which points at a missing buffer rather than slow storage." },
  { q: "On a healthy Linux system, why is free memory usually near zero?", options: ["Because swap is disabled", "The kernel fills idle RAM with reclaimable page cache, which it gives back instantly when needed", "A memory leak in the kernel"], answer: 1,
    explain: "Alert on MemAvailable, never MemFree. A free-memory alert fires constantly on healthy machines and trains everyone to ignore memory alerts." },
  { q: "What is the difference between VSZ and RSS?", options: ["They are the same measured differently", "VSZ is virtual address space reserved; RSS is physical memory actually resident", "VSZ is swap usage; RSS is RAM usage"], answer: 1,
    explain: "A JVM can show 8 GB VSZ and 512 MB RSS. Alerting on VSZ pages people for perfectly healthy processes." },
  { q: "Why is PSS often a better metric than RSS?", options: ["It includes swap", "It divides shared pages among the processes mapping them, so summing across forked workers does not double-count", "It is cheaper to compute"], answer: 1,
    explain: "Summing RSS across nginx or Postgres workers can imply gigabytes that do not exist. /proc/PID/smaps_rollup gives PSS without parsing thousands of lines." },
  { q: "What is memory overcommit?", options: ["The kernel granting more address space than it can physically back, since pages are only allocated on first touch", "Using more swap than RAM", "Allocating memory to multiple processes simultaneously"], answer: 0,
    explain: "It is why you can malloc 30 GB on a 15 GB machine and succeed — nothing was touched, so nothing was allocated." },
  { q: "Why does the OOM killer exist?", options: ["To enforce per-user quotas", "To reclaim page cache", "Because overcommit means the failure surfaces at page-fault time, and a page fault cannot return an error to the application"], answer: 2,
    explain: "The kernel cannot fail a page fault the way it can fail a syscall, so instead it kills a process. The two mechanisms are directly linked." },
  { q: "How does the OOM killer choose its victim?", options: ["It scores processes roughly by proportional memory use, adjusted by oom_score_adj", "The oldest process", "The process that requested the most recent allocation"], answer: 0,
    explain: "'Kill the biggest user' recovers the most memory but often targets the database. oom_score_adj (or systemd's OOMScoreAdjust=) biases the choice." },
  { q: "Why do application logs show nothing after an OOM kill?", options: ["The logs are buffered and lost", "The OOM killer deletes log entries", "SIGKILL cannot be caught, so the process has no opportunity to log anything"], answer: 2,
    explain: "The evidence is in dmesg, journalctl -k, `systemctl status` showing Result: oom-kill, or exit status 137." },
  { q: "A container is OOM-killed while the host has 8 GB free. Why?", options: ["The host reported memory incorrectly", "A kernel bug", "The cgroup OOM killer fired at memory.max — the container hit its own limit, not the host's"], answer: 2,
    explain: "memory.events is the definitive record, and dmesg says 'Memory cgroup out of memory' rather than plain 'Out of memory'." },
  { q: "Why is checking malloc's return for NULL nearly useless on Linux?", options: ["The C library retries automatically", "malloc never fails", "Overcommit means it almost always succeeds; the failure arrives later as a kill at first touch"], answer: 2,
    explain: "Strict mode (vm.overcommit_memory=2) makes the check meaningful again but breaks workloads that reserve sparse regions, so it is rarely used." },
  { q: "Which /proc/PID/smaps_rollup field best tracks a memory leak?", options: ["Rss", "Private_Dirty — memory only this process modified, which cannot be shared or dropped", "Swap"], answer: 1,
    explain: "Linear, unbounded growth in Private_Dirty is a leak; rise-then-plateau is a cache; a high plateau above the live set is allocator fragmentation." },
  { q: "What distinguishes allocator fragmentation from a genuine leak?", options: ["Fragmentation plateaus far above the live-object size while the application believes it freed the memory", "Fragmentation only affects the JVM", "Fragmentation grows faster"], answer: 0,
    explain: "glibc arenas hold freed memory without returning it. MALLOC_ARENA_MAX, jemalloc, or malloc_trim address it — code changes will not." },
  { q: "What does a non-zero, sustained si/so in vmstat indicate?", options: ["System interrupts", "Normal page cache activity", "Swap thrashing — continuous swap-in/swap-out, which makes a machine unresponsive without triggering an OOM kill"], answer: 2,
    explain: "This is why Kubernetes disables swap by default: hitting the limit then produces a clean, observable OOM kill instead of ambiguous slow degradation." },
  { q: "Why must a JVM or Node process be told the container memory limit?", options: ["Older runtimes read the HOST's RAM and size their heap from it, immediately exceeding a small container limit", "To allocate swap correctly", "To enable garbage collection"], answer: 0,
    explain: "-XX:MaxRAMPercentage or --max-old-space-size, leaving ~30% beyond the heap for thread stacks, metaspace and native buffers." },
  { q: "Why is /proc/pressure/memory a better early-warning signal than MemFree?", options: ["It updates more frequently", "It reports the percentage of time tasks were stalled waiting for memory, which rises well before an OOM kill", "It includes swap usage"], answer: 1,
    explain: "PSI catches thrashing and reclaim pressure while every other memory metric still looks acceptable — right up until the process dies." },
]},
);
