// Java quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Streams & Lambdas",
  desc: "Lambdas, pipeline, laziness, collectors, parallel",
  questions: [
  { q: "A lambda implements…", options: ["Any class", "A functional interface (exactly one abstract method)", "A record"], answer: 1,
    explain: "Runnable, Function, Predicate, Comparator..." },
  { q: "Intermediate stream ops (filter/map) are…", options: ["Eager", "LAZY (do nothing until a terminal op)", "Terminal"], answer: 1,
    explain: "collect/forEach/reduce/count trigger execution." },
  { q: "Terminal ops include…", options: ["filter, map", "collect, forEach, reduce, count, findFirst", "sorted, limit"], answer: 1,
    explain: "They produce a result/side effect and run the pipeline." },
  { q: "findFirst/limit/anyMatch are special because they…", options: ["Are eager", "Short-circuit (stop early)", "Sort"], answer: 1,
    explain: "Laziness enables processing huge/infinite sources." },
  { q: "Reusing a consumed stream…", options: ["Works", "Throws IllegalStateException (streams are one-shot)", "Restarts"], answer: 1,
    explain: "Create a new stream each time." },
  { q: "groupingBy(User::role, counting()) produces…", options: ["A list", "Map<Role, Long> of counts", "A set"], answer: 1,
    explain: "Collectors reduce to maps/stats/strings." },
  { q: "Lambdas in streams must be…", options: ["Stateful", "Side-effect-free (pure)", "Synchronized"], answer: 1,
    explain: "Laziness + parallelism make side effects buggy." },
  { q: "IntStream vs Stream<Integer>:", options: ["Same", "IntStream avoids boxing (faster for primitives)", "IntStream is slower"], answer: 1,
    explain: "mapToInt(...).sum() in hot paths." },
  { q: "parallelStream helps when…", options: ["Always", "Large, CPU-bound, stateless, associative work — measure!", "Small data"], answer: 1,
    explain: "Overhead/races make it a trap otherwise." },
  { q: "Forgetting a terminal op means…", options: ["It runs anyway", "Nothing happens (all lazy)", "Error"], answer: 1,
    explain: "Add collect/toList/forEach." },
  { q: "Method reference User::name is…", options: ["A field", "Shorthand for u -> u.name()", "A cast"], answer: 1,
    explain: "Static, instance, and constructor (::new) forms exist." },
  { q: "The pipeline processes elements…", options: ["Stage by stage over the whole list", "One at a time through all stages (fused)", "Randomly"], answer: 1,
    explain: "Enables short-circuiting and single-pass efficiency." },
  { q: "Collectors.joining(\", \") produces…", options: ["A list", "A single concatenated String", "A map"], answer: 1,
    explain: "Reduce a stream of strings to one." },
  { q: "peek() is mainly for…", options: ["Removing elements", "Debugging/observing without a terminal effect (demonstrates laziness)", "Sorting"], answer: 1,
    explain: "Nothing prints until a terminal op runs." },
  { q: "partitioningBy(pred) splits into…", options: ["N groups", "Map<Boolean, List<T>> (true/false)", "Sorted"], answer: 1,
    explain: "A binary groupingBy." },
  { q: "reduce is for…", options: ["Filtering", "Folding a stream into a single value with an accumulator", "Mapping"], answer: 1,
    explain: "sum/min/max have convenience methods." },
  { q: "Side effects in streams should go in…", options: ["map", "a terminal forEach (or better, collect to a result)", "filter"], answer: 1,
    explain: "Keep intermediates pure." },
  { q: "Overusing streams for a trivial loop…", options: ["Is best", "Can reduce readability — use the clearer option", "Is required"], answer: 1,
    explain: "Streams shine for transformations, not everything." },
  { q: "Optional is returned by stream ops like…", options: ["map", "findFirst/reduce/min/max (possibly empty)", "filter"], answer: 1,
    explain: "Handle absence with orElse/orElseThrow." },
  { q: "Comparator.comparing(User::score).reversed().thenComparing(User::name) sorts…", options: ["By name only", "By score desc, then name asc — composed comparators", "Randomly"], answer: 1,
    explain: "Composable, readable multi-key sorting." }
]},

{ title: "Quiz 7 · Exceptions & Optional",
  desc: "Checked vs unchecked, try-with-resources, chaining, Optional",
  questions: [
  { q: "Checked exceptions…", options: ["Are optional", "Must be caught or declared (compiler-enforced)", "Extend Error"], answer: 1,
    explain: "For recoverable conditions (IOException, SQLException)." },
  { q: "Unchecked exceptions extend…", options: ["Error", "RuntimeException (NPE, IllegalArgument) — programmer errors", "Throwable directly"], answer: 1,
    explain: "No compiler enforcement." },
  { q: "try-with-resources…", options: ["Is verbose", "Auto-closes AutoCloseables (even on exception), in reverse order", "Ignores errors"], answer: 1,
    explain: "Replaces error-prone finally { close() }." },
  { q: "Chaining a cause (new X(\"ctx\", e)) preserves…", options: ["Nothing", "The original stack trace/root cause", "Memory"], answer: 1,
    explain: "new X(e.getMessage()) loses the trace." },
  { q: "An empty catch {} is…", options: ["Defensive", "The cardinal sin — bugs vanish silently", "Required"], answer: 1,
    explain: "Log + rethrow; handle only what you can." },
  { q: "Errors (OutOfMemoryError) should be…", options: ["Caught and handled", "Not caught (JVM-level, unrecoverable)", "Logged and ignored"], answer: 1,
    explain: "Catch Exception, not Throwable/Error." },
  { q: "Optional is best used as…", options: ["A field", "A RETURN type signaling possible absence", "A parameter"], answer: 1,
    explain: "Not for fields/params/collections." },
  { q: "Optional.get() without checking…", options: ["Is safe", "Throws NoSuchElementException (the new NPE)", "Returns null"], answer: 1,
    explain: "Use orElse/orElseThrow/ifPresent/map." },
  { q: "For a possibly-absent collection, return…", options: ["Optional<List>", "an empty collection", "null"], answer: 1,
    explain: "Optional of a collection is an anti-pattern." },
  { q: "Using exceptions for control flow is…", options: ["Efficient", "Slow and unreadable — use return values/Optional for expected cases", "Required"], answer: 1,
    explain: "Exceptions are for exceptional conditions." },
  { q: "IllegalArgumentException signals…", options: ["A checked error", "A bad argument (precondition violation) — unchecked", "Success"], answer: 1,
    explain: "IllegalStateException for bad object state." },
  { q: "Multi-catch (catch (A | B e)) …", options: ["Is invalid", "Handles multiple exception types in one block", "Catches all"], answer: 1,
    explain: "Reduces duplication for shared handling." },
  { q: "finally runs…", options: ["Only on success", "Always (success, exception, or return)", "Only on error"], answer: 1,
    explain: "Cleanup guarantee; try-with-resources is cleaner for closing." },
  { q: "The 'billion-dollar mistake' is…", options: ["Generics", "null (Optional makes absence explicit in types)", "Threads"], answer: 1,
    explain: "Optional + avoiding null returns reduces NPEs by design." },
  { q: "Catch narrowly means…", options: ["Catch Exception broadly", "Catch specific types; let unexpected ones bubble to a boundary", "Never catch"], answer: 1,
    explain: "Broad catches mask real bugs." },
  { q: "findById returning Optional<User> lets callers…", options: ["Ignore absence", "Chain map/filter/orElseThrow safely", "Get null"], answer: 1,
    explain: "Composable absence handling." },
  { q: "try-with-resources works on any…", options: ["Object", "AutoCloseable", "Stream only"], answer: 1,
    explain: "Files, connections, streams implement it." },
  { q: "Rethrowing with context is preferred over…", options: ["Swallowing", "Both swallowing and logging-then-continuing after a bug", "Handling"], answer: 1,
    explain: "Preserve the cause; handle where you can act." },
  { q: "Optional.orElseGet(supplier) vs orElse(x):", options: ["Same", "orElseGet defers computing the default (lazy) — cheaper if x is expensive", "orElse is lazy"], answer: 1,
    explain: "Use orElseGet when the fallback is costly." },
  { q: "A NullPointerException is…", options: ["Checked", "Unchecked (a programmer error)", "An Error"], answer: 1,
    explain: "Design it away with Optional/null-avoidance." }
]},

{ title: "Quiz 8 · Modern Java & Concurrency",
  desc: "Records, sealed, patterns, threads, memory model, virtual threads",
  questions: [
  { q: "A record auto-generates…", options: ["Nothing", "Constructor, accessors, equals, hashCode, toString", "Only getters"], answer: 1,
    explain: "Immutable value classes for DTOs/keys." },
  { q: "Records are…", options: ["Mutable", "Immutable and final", "Abstract"], answer: 1,
    explain: "Model VALUES; use classes for entities/identity." },
  { q: "sealed types enable…", options: ["Encryption", "Exhaustive switches over a compiler-known set of subtypes", "Threading"], answer: 1,
    explain: "New variant → compile error until handled." },
  { q: "records + sealed + pattern matching gives…", options: ["Nothing new", "Algebraic-data-type modeling (type-safe discriminated unions)", "Slower code"], answer: 1,
    explain: "Same idea as TS/Python unions, checked by the compiler." },
  { q: "n++ across threads without sync…", options: ["Is atomic", "Can lose updates (read-modify-write race)", "Is fine"], answer: 1,
    explain: "Use AtomicInteger or synchronize." },
  { q: "The Java Memory Model governs…", options: ["Heap size", "VISIBILITY/ordering of writes across threads (happens-before)", "GC"], answer: 1,
    explain: "Why volatile/synchronized matter beyond atomicity." },
  { q: "volatile guarantees…", options: ["Atomicity of n++", "Visibility (not atomicity of compound ops)", "Mutual exclusion"], answer: 1,
    explain: "Good for a stop flag; not for counters." },
  { q: "For a thread-safe counter, use…", options: ["volatile int", "AtomicInteger (atomic CAS)", "a plain int"], answer: 1,
    explain: "volatile doesn't make ++ atomic." },
  { q: "Prefer for concurrent maps…", options: ["HashMap", "ConcurrentHashMap", "TreeMap"], answer: 1,
    explain: "Engineered for concurrency; over synchronizedMap." },
  { q: "Use Executors instead of raw Threads because…", options: ["No reason", "Pooling, lifecycle management, task submission", "They're faster only"], answer: 1,
    explain: "Submit tasks; the pool manages threads." },
  { q: "CompletableFuture is Java's analog of…", options: ["Threads", "JS Promises (compose async: thenCombine/allOf)", "Streams"], answer: 1,
    explain: "Run independent calls concurrently and combine." },
  { q: "Virtual threads (21+)…", options: ["Are OS threads", "Are lightweight (park on blocking) → millions; simple blocking code scales", "Replace GC"], answer: 1,
    explain: "Thread-per-request becomes viable for I/O." },
  { q: "Deadlock happens when…", options: ["A thread crashes", "Threads hold locks the others need (circular wait)", "The pool is full"], answer: 1,
    explain: "Acquire locks in a consistent global order." },
  { q: "synchronized(new Object()) per call…", options: ["Works", "Doesn't exclude (different monitors each time)", "Deadlocks"], answer: 1,
    explain: "Use a shared final lock object." },
  { q: "Compact constructor in a record is for…", options: ["Nothing", "Validation/normalization of components", "Inheritance"], answer: 1,
    explain: "Throw on invalid input; normalize fields." },
  { q: "A default branch on a sealed switch…", options: ["Is required", "Loses exhaustiveness safety (new cases slip through)", "Is faster"], answer: 1,
    explain: "Omit it so the compiler enforces completeness." },
  { q: "The best fix for shared-state races is…", options: ["More locks", "Don't share mutable state (immutability/message passing)", "volatile everywhere"], answer: 1,
    explain: "Then atomics/concurrent collections; synchronized last." },
  { q: "instanceof pattern + record deconstruction (case Circle(double r))…", options: ["Is invalid", "Destructures the record in a switch (21+)", "Casts unsafely"], answer: 1,
    explain: "Concise, exhaustive dispatch." },
  { q: "text blocks (\"\"\"...\"\"\") are…", options: ["Comments", "Multi-line string literals", "Records"], answer: 1,
    explain: "With .formatted() for values." },
  { q: "Records are the wrong choice for…", options: ["DTOs", "JPA entities (identity/lifecycle, mutability)", "Map keys"], answer: 1,
    explain: "Values → records; entities → classes." }
]},

{ title: "Quiz 9 · JVM, Testing & Spring Boot",
  desc: "Memory/GC, leaks, JIT, JUnit/Mockito, DI, Spring",
  questions: [
  { q: "Objects live on the…", options: ["Stack", "Heap (GC-managed)", "Metaspace"], answer: 1,
    explain: "Stack holds frames/locals/references." },
  { q: "Generational GC exploits…", options: ["Big heaps", "'Most objects die young' — fast Young-gen Minor GCs", "Multithreading"], answer: 1,
    explain: "Survivors promote to Old gen (slower Full GC)." },
  { q: "The default GC for most server apps is…", options: ["Serial", "G1 (balanced pause/throughput)", "Epsilon"], answer: 1,
    explain: "ZGC/Shenandoah for ultra-low pauses." },
  { q: "A memory leak in Java is…", options: ["Impossible (GC)", "Objects accidentally kept REACHABLE (unbounded caches, listeners)", "A native bug"], answer: 1,
    explain: "GC frees the unreachable; leaks are accidental reachability." },
  { q: "You diagnose a leak with…", options: ["print statements", "A heap dump + dominator tree (MAT/VisualVM)", "Restarting"], answer: 1,
    explain: "Rising Old gen after Full GC signals it." },
  { q: "The JIT compiler…", options: ["Runs once", "Profiles hot code and compiles it to native (needs warmup)", "Is optional"], answer: 1,
    explain: "Benchmark with JMH after warmup." },
  { q: "AssertJ's assertThat(x).isEqualTo(y) is preferred because…", options: ["It's faster", "Fluent, readable, richer failure messages", "It mocks"], answer: 1,
    explain: "Over JUnit's assertEquals." },
  { q: "@ParameterizedTest is for…", options: ["Mocking", "Running one test over many input cases (branches/edges)", "Setup"], answer: 1,
    explain: "@CsvSource/@MethodSource supply data." },
  { q: "Mockito should mock…", options: ["The class under test", "External collaborators (gateways/repos) — not your logic", "Value objects"], answer: 1,
    explain: "Over-mocking tests the mock." },
  { q: "For DB integration tests use…", options: ["A mock", "Testcontainers (real DB) — mocking hides SQL bugs", "H2 always"], answer: 1,
    explain: "H2 dialect differs from prod; mocks don't run SQL." },
  { q: "Constructor injection improves…", options: ["Speed", "Testability (pass mocks) + explicit required deps", "Memory"], answer: 1,
    explain: "Over @Autowired field injection." },
  { q: "Spring's core mechanism is…", options: ["Threads", "Dependency Injection / Inversion of Control (the container wires beans)", "GC"], answer: 1,
    explain: "You don't `new` dependencies; the container does." },
  { q: "@RestController + @Service + @Repository is…", options: ["Random", "A layered architecture (thin controller → logic → data)", "One class"], answer: 1,
    explain: "Keep controllers thin; logic in services." },
  { q: "Exposing JPA entities from controllers is…", options: ["Best practice", "An anti-pattern (couples API to schema, leaks, lazy-load errors)", "Required"], answer: 1,
    explain: "Map to DTOs/records." },
  { q: "@Valid on a @RequestBody gives…", options: ["500 errors", "Automatic 400 on validation failure", "Auth"], answer: 1,
    explain: "Jakarta Validation annotations enforce constraints." },
  { q: "Spring Data JPA generates queries from…", options: ["SQL files", "Repository METHOD NAMES (findByEmail)", "XML"], answer: 1,
    explain: "Watch N+1; use JOIN FETCH/@EntityGraph." },
  { q: "Global error handling uses…", options: ["try/catch in every controller", "@RestControllerAdvice → typed JSON, no stack leaks", "Filters only"], answer: 1,
    explain: "Centralized exception→response mapping." },
  { q: "Setting -Xms = -Xmx avoids…", options: ["OOM", "Heap resize pauses (size to the container)", "Leaks"], answer: 1,
    explain: "Steadier GC behavior." },
  { q: "Calling System.gc() is…", options: ["Recommended", "Discouraged (forces expensive Full GC)", "Required"], answer: 1,
    explain: "Let the JVM manage collection." },
  { q: "Spring Boot reduces boilerplate via…", options: ["Magic only", "Starters + auto-configuration + convention (understand it to debug)", "Nothing"], answer: 1,
    explain: "The risk is treating it as a black box." }
]},

{ title: "Quiz 10 · The Mock Exam (Mixed, Exam-Level)",
  desc: "20 cross-topic questions at interview difficulty",
  questions: [
  { q: "Integer a=1000,b=1000; a==b is false because…", options: ["A bug", "== compares references; only −128..127 are cached — use .equals", "1000 is odd"], answer: 1,
    explain: "The autoboxing/identity trap." },
  { q: "A method clears a passed list and the caller sees it, but reassigning the param doesn't. Why?", options: ["Pass by reference", "Pass-by-value of the reference: mutate yes, repoint no", "A bug"], answer: 1,
    explain: "The definitive Java argument-passing answer." },
  { q: "Your HashSet contains 'duplicate' objects. Cause?", options: ["A JVM bug", "equals overridden without hashCode (or broken)", "Too small"], answer: 1,
    explain: "Override both, or use a record." },
  { q: "Threads increment a shared int and lose updates. Fix?", options: ["volatile", "AtomicInteger (or synchronize) — ++ isn't atomic", "Nothing"], answer: 1,
    explain: "volatile gives visibility, not atomicity." },
  { q: "A background loop never sees a stop flag change. Cause?", options: ["Slow CPU", "Visibility — the flag needs volatile (or synchronization)", "GC"], answer: 1,
    explain: "The Java Memory Model / happens-before." },
  { q: "Adding to a List<? extends Number> won't compile because…", options: ["It's a bug", "extends = producer (read-only); exact subtype unknown", "Wrong import"], answer: 1,
    explain: "PECS: use ? super to add." },
  { q: "Streams pipeline does nothing. Cause?", options: ["Bad data", "No terminal operation (intermediates are lazy)", "Parallel"], answer: 1,
    explain: "Add collect/forEach/toList." },
  { q: "Memory climbs until OOM despite GC. Likely cause?", options: ["Too little heap only", "A leak — unbounded static cache/collection keeping objects reachable", "JIT"], answer: 1,
    explain: "Heap dump + dominator tree to confirm." },
  { q: "map.get(new Point(1,2)) returns null though you put it. Cause?", options: ["HashMap bug", "Point lacks proper equals/hashCode (or key was mutated)", "Concurrency"], answer: 1,
    explain: "Use a record for value keys." },
  { q: "A microbenchmark shows Java is 'slow'. Cause?", options: ["It is slow", "No JIT warmup — measure steady state with JMH", "Wrong JDK"], answer: 1,
    explain: "Early runs are interpreted." },
  { q: "resource leak from files. Best fix?", options: ["finally { close() }", "try-with-resources (auto-close, exception-safe)", "System.gc()"], answer: 1,
    explain: "Any AutoCloseable." },
  { q: "Optional.get() threw NoSuchElementException. Fix?", options: ["Ignore", "orElse/orElseThrow/ifPresent — never bare get()", "Return null"], answer: 1,
    explain: "get() is the new NPE." },
  { q: "Your Spring controller returns a JPA entity and serialization fails. Fix?", options: ["Bigger heap", "Map to a DTO/record (decouple API from schema, avoid lazy-load)", "Disable JPA"], answer: 1,
    explain: "Never expose entities." },
  { q: "A list endpoint runs 100+ queries. Diagnosis?", options: ["Slow DB", "N+1 — use JOIN FETCH/@EntityGraph", "Deadlock"], answer: 1,
    explain: "Fetch relations in bulk." },
  { q: "Modifying a list during for-each throws. Fix?", options: ["catch it", "removeIf / iterator.remove()", "clear()"], answer: 1,
    explain: "ConcurrentModificationException (fail-fast)." },
  { q: "You need exhaustive handling of a fixed set of shapes. Use…", options: ["enum only", "sealed interface + records + switch (compiler-checked)", "abstract class + instanceof chains"], answer: 1,
    explain: "Algebraic data types, safely." },
  { q: "A test mocks the database and passes, but prod SQL fails. Cause?", options: ["Flaky CI", "Mocking the DB tests the mock — use Testcontainers", "Wrong JDK"], answer: 1,
    explain: "Real DB for integration tests." },
  { q: "parallelStream made it slower/racy. Why?", options: ["Always faster", "Small/IO-bound data or shared mutable state — overhead/races", "GC"], answer: 1,
    explain: "Only large CPU-bound stateless work; measure." },
  { q: "String concatenation in a loop is slow. Fix?", options: ["More RAM", "StringBuilder (Strings are immutable; += is O(n²))", "char[]"], answer: 1,
    explain: "Single buffer vs repeated allocation." },
  { q: "The single most important Java mental model is…", options: ["Memorize APIs", "Primitives(value) vs references(pointer) + JVM manages memory/threads — everything derives", "Use Spring"], answer: 1,
    explain: "Argument passing, equals, collections, GC, and concurrency all follow from it. 🏆" }
]}
);
