// Java quiz bank — sets 6–10 (20 questions each, with explanations). Mapped to the deep curriculum.
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Concurrency Basics",
  desc: "Threads, races, synchronization, locks, deadlock",
  questions: [
  { q: "Threads share the… and have their own…", options: ["stack / heap", "heap / stack", "nothing / everything"], answer: 1,
    explain: "Shared heap (mutable state) is the source of concurrency hazards." },
  { q: "start() vs run(): calling run() directly…", options: ["Starts a new thread", "Runs synchronously on the current thread", "Errors"], answer: 1,
    explain: "Only start() creates a new thread." },
  { q: "Prefer Runnable over extending Thread because…", options: ["It's faster", "It decouples the task from how it's run", "It's required"], answer: 1,
    explain: "Same task works with a pool, virtual thread, etc." },
  { q: "count++ from two threads is…", options: ["Safe", "A race (read-modify-write not atomic)", "Impossible"], answer: 1,
    explain: "Lost updates; fix with atomics or synchronized." },
  { q: "synchronized provides…", options: ["Visibility only", "Mutual exclusion AND visibility (via the monitor)", "Speed"], answer: 1,
    explain: "Lock release happens-before the next acquire." },
  { q: "Prefer to synchronize on…", options: ["this / a public object", "A private final lock object", "A String literal"], answer: 1,
    explain: "Prevents external interference/deadlock." },
  { q: "ReentrantLock over synchronized when you need…", options: ["Nothing", "tryLock/timeout/interruptible/fairness", "Simplicity"], answer: 1,
    explain: "But you must unlock() in finally." },
  { q: "Deadlock is prevented by…", options: ["More locks", "A consistent global lock-acquisition order", "Bigger heap"], answer: 1,
    explain: "Breaks the circular-wait condition." },
  { q: "wait() must be called…", options: ["Anywhere", "Holding the lock, inside a while loop", "Once"], answer: 1,
    explain: "Guard against spurious wakeups; prefer j.u.c utilities." },
  { q: "For producer/consumer, use a…", options: ["synchronized map", "BlockingQueue (handles blocking/signaling)", "raw wait/notify"], answer: 1,
    explain: "No manual locking needed." },
  { q: "Lock contention…", options: ["Helps scaling", "Serializes threads and kills scalability", "Is free"], answer: 1,
    explain: "Reduce shared state; stripe; use atomics." },
  { q: "The best lock is…", options: ["A big one", "No lock (immutability/confinement)", "A fair one"], answer: 1,
    explain: "Immutable objects have nothing to race on." },
  { q: "A plain break in nested loops…", options: ["Exits both", "Exits only the inner loop", "Errors"], answer: 1,
    explain: "Use a labeled break or extract a method." },
  { q: "start() can be called…", options: ["Many times", "Once per Thread (else IllegalThreadStateException)", "Never"], answer: 1,
    explain: "Create a new thread or use a pool to rerun." },
  { q: "A terminated thread…", options: ["Can restart", "Cannot be restarted", "Auto-restarts"], answer: 1,
    explain: "run() returned or threw; make a new one." },
  { q: "Narrow synchronized blocks are better because…", options: ["They're shorter to type", "They hold the lock for less time (less contention)", "They're safer syntactically"], answer: 1,
    explain: "Never hold a lock during slow I/O." },
  { q: "The four deadlock (Coffman) conditions include…", options: ["Fast CPUs", "Circular wait", "Enough memory"], answer: 1,
    explain: "Break any one — circular wait is the practical lever." },
  { q: "A synchronized instance method locks on…", options: ["The class", "this", "A new object"], answer: 1,
    explain: "A static synchronized method locks on the Class object." },
  { q: "Raw threads are the wrong everyday level because…", options: ["They don't work", "They're expensive and manual — use executors", "They're deprecated"], answer: 1,
    explain: "Submit tasks to a pool instead." },
  { q: "A method that mutates a passed collection is…", options: ["Always fine", "A 'spooky action at a distance' risk", "Impossible"], answer: 1,
    explain: "Prefer returning a new value; document mutation." }
]},

{ title: "Quiz 7 · Concurrency Advanced",
  desc: "Memory model, executors, atomics, concurrent collections, virtual threads",
  questions: [
  { q: "The visibility problem is that…", options: ["Writes are always seen", "A write may never be seen by another thread without sync", "Reads are slow"], answer: 1,
    explain: "The stuck-loop bug: a non-volatile flag." },
  { q: "volatile guarantees…", options: ["Atomicity of count++", "Visibility and ordering (not compound atomicity)", "Locking"], answer: 1,
    explain: "volatile int count; count++ still races." },
  { q: "happens-before is established by…", options: ["Nothing", "Locks, volatiles, thread start/join, program order", "Comments"], answer: 1,
    explain: "No happens-before edge → no visibility guarantee." },
  { q: "Safe publication prevents…", options: ["Fast code", "Seeing a half-constructed object", "GC"], answer: 1,
    explain: "final fields + immutability are safely published by design." },
  { q: "Testing… concurrency correctness", options: ["Proves", "Cannot prove (nondeterministic) — reason via happens-before", "Speeds up"], answer: 1,
    explain: "Minimize shared mutable state." },
  { q: "You should submit tasks to…", options: ["new Thread()", "an ExecutorService pool", "the main thread"], answer: 1,
    explain: "Reuse, bounded resources, results, shutdown." },
  { q: "Callable differs from Runnable in that it…", options: ["Runs faster", "Returns a value (via a Future)", "Can't throw"], answer: 1,
    explain: "Future.get() blocks for the result." },
  { q: "For concurrency, submit all tasks then…", options: ["get() after each submit", "collect results (don't serialize)", "cancel them"], answer: 1,
    explain: "get() after each submit runs them one at a time." },
  { q: "newFixedThreadPool's unbounded queue risks…", options: ["Nothing", "OOM under overload (no backpressure)", "Deadlock"], answer: 1,
    explain: "Use a bounded queue + rejection policy in prod." },
  { q: "CompletableFuture over Future adds…", options: ["Nothing", "Composition (thenApply/thenCompose) and error handling", "Blocking"], answer: 1,
    explain: "No callback hell." },
  { q: "ConcurrentHashMap scales via…", options: ["One big lock", "Lock striping (per-bucket) + atomic compound ops", "No locking"], answer: 1,
    explain: "synchronizedMap serializes everything." },
  { q: "AtomicInteger updates are…", options: ["Locked", "Lock-free via CAS", "Blocking"], answer: 1,
    explain: "No deadlock; LongAdder for high contention." },
  { q: "The ABA problem is…", options: ["A typo", "A→B→A fools CAS (fix with a version stamp)", "A deadlock"], answer: 1,
    explain: "AtomicStampedReference solves it." },
  { q: "CopyOnWriteArrayList is for…", options: ["Write-heavy data", "Read-heavy, rarely-written lists (listeners)", "Sorted data"], answer: 1,
    explain: "It copies the array on every write." },
  { q: "The concurrency tool ladder starts with…", options: ["Locks", "Immutability/confinement", "Custom lock-free code"], answer: 1,
    explain: "Then atomics → concurrent collections → locks." },
  { q: "A virtual thread is scheduled by…", options: ["The OS", "The JVM (cheap, millions possible)", "You"], answer: 1,
    explain: "A platform thread is a 1:1 OS thread." },
  { q: "A blocking virtual thread…", options: ["Wastes an OS thread", "Unmounts from its carrier (OS thread runs others)", "Deadlocks"], answer: 1,
    explain: "Simple blocking code scales." },
  { q: "Virtual threads help for… but not…", options: ["CPU-bound / I/O", "I/O-bound / CPU-bound", "neither / both"], answer: 1,
    explain: "CPU work is still core-limited." },
  { q: "Pinning happens when a virtual thread blocks in…", options: ["a ReentrantLock", "a synchronized block (or native call)", "a loop"], answer: 1,
    explain: "Prefer ReentrantLock around blocking I/O." },
  { q: "You should NOT… virtual threads", options: ["create", "pool them (create one per task)", "block on them"], answer: 1,
    explain: "Pooling reintroduces the limits you're escaping." }
]},

{ title: "Quiz 8 · JVM, Memory & Performance",
  desc: "Class loading, JIT, stack/heap, references, GC, profiling",
  questions: [
  { q: "Class loading phases are…", options: ["Just loading", "Loading → Linking (verify/prepare/resolve) → Initialization", "Compile → run"], answer: 1,
    explain: "Classes load lazily on first active use." },
  { q: "Parent delegation means a loader…", options: ["Loads first itself", "Asks its parent first (protects core classes)", "Ignores parents"], answer: 1,
    explain: "Your fake java.lang.String is never used." },
  { q: "ClassNotFoundException vs NoClassDefFoundError: the latter is…", options: ["An explicit lookup failure", "A compile-time-present class missing/failed at runtime", "The same"], answer: 1,
    explain: "Often a packaging issue or a static-init failure." },
  { q: "The JIT makes Java fast by…", options: ["Precompiling everything", "Compiling hot code to native using the runtime profile", "Skipping checks"], answer: 1,
    explain: "Cost is warmup; hence benchmarks must warm up." },
  { q: "The stack holds… the heap holds…", options: ["objects / frames", "method frames (locals/refs) / objects", "nothing / everything"], answer: 1,
    explain: "Frames pop on return; heap objects live until unreachable." },
  { q: "The heap is generational because…", options: ["It looks nice", "Most objects die young (cheap frequent minor GCs)", "It's required"], answer: 1,
    explain: "Old gen collected rarely (expensive)." },
  { q: "GC collects objects that are…", options: ["Old", "Unreachable from GC roots", "Large"], answer: 1,
    explain: "Reachability handles cycles (unlike ref-counting)." },
  { q: "A WeakReference is collected…", options: ["Never", "At the next GC if only weakly reachable", "Under memory pressure only"], answer: 1,
    explain: "Soft = under memory pressure; WeakHashMap won't pin keys." },
  { q: "A memory leak in Java means…", options: ["Impossible", "Keeping references alive (retained reachable objects)", "A GC bug"], answer: 1,
    explain: "Static collections, listeners, ThreadLocals, unbounded caches." },
  { q: "StackOverflowError comes from…", options: ["Too many objects", "Too many nested calls (deep recursion)", "A leak"], answer: 1,
    explain: "Different from heap OOM." },
  { q: "Modern GC trades off…", options: ["Only speed", "Throughput vs latency vs footprint (can't max all)", "Nothing"], answer: 1,
    explain: "Stop-the-world pauses hurt interactive services." },
  { q: "The default collector (9+) is…", options: ["Serial", "G1 (balanced)", "Parallel"], answer: 1,
    explain: "ZGC/Shenandoah for low latency; Parallel for batch." },
  { q: "System.gc() is…", options: ["Required", "Only a hint — usually wrong to call", "Fast"], answer: 1,
    explain: "Let the JVM manage collection." },
  { q: "Set -Xms and -Xmx in production…", options: ["Differently", "Equal (avoid resize pauses)", "To max"], answer: 1,
    explain: "Predictability; size to the workload." },
  { q: "The first rule of performance is…", options: ["Optimize everything", "Measure, don't guess (profile first)", "Use more threads"], answer: 1,
    explain: "Time is almost never where you'd guess." },
  { q: "A naive timing-loop benchmark is wrong because of…", options: ["Nothing", "JIT warmup + dead-code elimination", "The OS"], answer: 1,
    explain: "Use JMH for microbenchmarks." },
  { q: "You should optimize…", options: ["The average latency", "Tail latency (p99/p99.9)", "Nothing"], answer: 1,
    explain: "Averages hide the slow requests users notice." },
  { q: "The biggest perf wins usually come from…", options: ["Micro-optimizing CPU", "Reducing I/O and algorithmic complexity", "More flags"], answer: 1,
    explain: "Network ≫ SSD ≫ memory ≫ cache in cost." },
  { q: "A flame graph's widest boxes are…", options: ["Idle", "The hotspots (most CPU time)", "Errors"], answer: 1,
    explain: "Profile under realistic load." },
  { q: "A steadily rising post-GC live set indicates…", options: ["Healthy churn", "A leak (not undersizing)", "Good GC"], answer: 1,
    explain: "Take a heap dump; raising -Xmx only delays OOM." }
]},

{ title: "Quiz 9 · Professional Java",
  desc: "Design patterns, SOLID, testing, build tools",
  questions: [
  { q: "A design pattern is…", options: ["A library", "A named reusable solution + shared vocabulary", "A framework"], answer: 1,
    explain: "Apply when a problem matches; don't force ('pattern fever')." },
  { q: "The best Singleton in Java is…", options: ["A static field", "A single-element enum", "A global"], answer: 1,
    explain: "Thread-safe, serialization/reflection-proof." },
  { q: "The Builder pattern is for…", options: ["One field", "Complex/optional-parameter construction → immutable object", "Threads"], answer: 1,
    explain: "Avoids telescoping constructors." },
  { q: "Lambdas turned Strategy into…", options: ["A class hierarchy", "A one-liner (functional interface + lambda)", "An enum"], answer: 1,
    explain: "Modern features subsume several classic patterns." },
  { q: "The Decorator pattern embodies…", options: ["Deep inheritance", "Composition over inheritance (wrap to add behavior)", "Singletons"], answer: 1,
    explain: "java.io is built on it." },
  { q: "SRP means…", options: ["One method per class", "One reason to change (one responsibility)", "No inheritance"], answer: 1,
    explain: "The class-level 'do one thing'." },
  { q: "OCP means…", options: ["Never change code", "Open for extension, closed for modification", "Always inherit"], answer: 1,
    explain: "Add types via polymorphism, don't edit tested code." },
  { q: "LSP means…", options: ["Small interfaces", "Subtypes substitutable without breaking behavior", "Depend on abstractions"], answer: 1,
    explain: "Square/Rectangle is the classic violation." },
  { q: "DIP is the theoretical basis of…", options: ["Inheritance", "Spring's dependency injection", "Streams"], answer: 1,
    explain: "Depend on abstractions, inject implementations." },
  { q: "DRY targets duplicated…", options: ["Appearance", "Knowledge (not coincidental similarity)", "Whitespace"], answer: 1,
    explain: "Rule of three guards against premature abstraction." },
  { q: "SOLID principles are…", options: ["Strict laws", "Guidelines serving safe/local/cheap change", "Optional"], answer: 1,
    explain: "Apply with judgment; break when dogma adds complexity." },
  { q: "A test follows…", options: ["Random structure", "Arrange-Act-Assert", "Assert-only"], answer: 1,
    explain: "One logical action and assertion per test." },
  { q: "Good tests are FIRST:…", options: ["Slow", "Fast, Isolated, Repeatable, Self-validating, Timely", "Manual"], answer: 1,
    explain: "Flaky tests are worse than none." },
  { q: "Tests should verify…", options: ["Implementation", "Behavior (so they survive refactoring)", "Line coverage"], answer: 1,
    explain: "Implementation-coupled tests break on every refactor." },
  { q: "Mocking lets you…", options: ["Skip tests", "Test a unit in isolation (mock external deps)", "Run faster only"], answer: 1,
    explain: "Enabled by constructor injection; don't over-mock." },
  { q: "The testing pyramid is mostly…", options: ["E2E tests", "Fast unit tests (base)", "Integration"], answer: 1,
    explain: "Inverted pyramid (mostly E2E) is an anti-pattern." },
  { q: "Code coverage is…", options: ["A goal (100%)", "A gap-finder, not a quality measure", "Useless"], answer: 1,
    explain: "You can have 100% coverage asserting nothing." },
  { q: "A build tool…", options: ["Only compiles", "Resolves deps, compiles, tests, packages — reproducibly", "Runs the app"], answer: 1,
    explain: "You never hand-manage the classpath." },
  { q: "Version conflicts ('jar hell') are diagnosed with…", options: ["Guessing", "The dependency tree (mvn dependency:tree)", "More memory"], answer: 1,
    explain: "Fix with pins/exclusions/BOMs." },
  { q: "Dependency hygiene is a… concern", options: ["Style", "Security (transitive CVEs, e.g. Log4Shell)", "Performance only"], answer: 1,
    explain: "Keep deps minimal, current, and scanned." }
]},

{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Interview-difficulty questions across the whole track",
  questions: [
  { q: "== on objects compares…", options: ["Content", "References (use .equals for value)", "Length"], answer: 1,
    explain: "Foundational trap." },
  { q: "Java is always…", options: ["Pass-by-reference", "Pass-by-value (of the reference for objects)", "Neither"], answer: 1,
    explain: "Mutate the shared object yes; repoint no." },
  { q: "Override equals but not hashCode →", options: ["Fine", "Objects vanish from hash collections", "Compile error"], answer: 1,
    explain: "Override both or use a record." },
  { q: "Favor… over inheritance", options: ["Static methods", "Composition", "Deep hierarchies"], answer: 1,
    explain: "Avoids the fragile base class problem." },
  { q: "PECS: read from a…, write to a…", options: ["super / extends", "extends producer / super consumer", "both extends"], answer: 1,
    explain: "Producer Extends, Consumer Super." },
  { q: "Streams are…", options: ["Eager", "Lazy and single-use", "Reusable"], answer: 1,
    explain: "No terminal → nothing runs." },
  { q: "Never use double for…", options: ["Loops", "Money", "Indexes"], answer: 1,
    explain: "BigDecimal or integer cents." },
  { q: "A record is…", options: ["Mutable", "An immutable data carrier (final, accessors, equals)", "An interface"], answer: 1,
    explain: "Shallowly immutable — copy mutable components." },
  { q: "volatile gives visibility but not…", options: ["ordering", "compound atomicity (count++ still races)", "anything"], answer: 1,
    explain: "Use AtomicInteger for counters." },
  { q: "Deadlock is prevented by…", options: ["More locks", "Consistent global lock ordering", "Bigger heap"], answer: 1,
    explain: "Breaks circular wait." },
  { q: "Virtual threads help… work", options: ["CPU-bound", "I/O-bound (unmount on block)", "no"], answer: 1,
    explain: "Watch for synchronized pinning." },
  { q: "GC collects objects that are…", options: ["Old", "Unreachable from roots", "Large"], answer: 1,
    explain: "A Java 'leak' is retained reachability." },
  { q: "You should optimize… latency", options: ["average", "tail (p99)", "no"], answer: 1,
    explain: "Averages hide the slow requests users feel." },
  { q: "The first rule of performance is…", options: ["Optimize all", "Measure, don't guess", "Add threads"], answer: 1,
    explain: "Profile to find the real hotspot." },
  { q: "The best Singleton is…", options: ["Static field", "A single-element enum", "A global"], answer: 1,
    explain: "Serialization/reflection-proof." },
  { q: "DIP underlies…", options: ["Streams", "Spring's dependency injection", "Generics"], answer: 1,
    explain: "Depend on abstractions, inject implementations." },
  { q: "Tests should verify…", options: ["Implementation", "Behavior", "Coverage %"], answer: 1,
    explain: "So they survive refactoring." },
  { q: "try-with-resources guarantees…", options: ["Speed", "close() on any exit", "Nothing"], answer: 1,
    explain: "Use it for every AutoCloseable." },
  { q: "Sealed + records + pattern matching let you…", options: ["Write less only", "Make illegal states unrepresentable", "Skip tests"], answer: 1,
    explain: "Exhaustive, compiler-checked handling." },
  { q: "The root cause behind ==, shallow copy, and mutable keys is…", options: ["Bad luck", "Reference vs value confusion", "The JVM"], answer: 1,
    explain: "Know what a variable actually holds." }
]}
);
