// java quiz bank — sets 6–10 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 6 · Concurrency Basics",
  desc: "Threads, races, synchronization, locks, deadlock",
  questions: [
  { q: "Threads share the… and have their own…", options: ["heap / stack", "stack / heap", "nothing / everything"], answer: 0,
    explain: "Shared heap (mutable state) is the source of concurrency hazards." },
  { q: "start() vs run(): calling run() directly…", options: ["Errors", "Runs synchronously on the current thread", "Starts a new thread"], answer: 1,
    explain: "Only start() creates a new thread." },
  { q: "Prefer Runnable over extending Thread because…", options: ["It's faster", "It decouples the task from how it's run", "It's required"], answer: 1,
    explain: "Same task works with a pool, virtual thread, etc." },
  { q: "count++ from two threads is…", options: ["Impossible", "A race (read-modify-write not atomic)", "Safe"], answer: 1,
    explain: "Lost updates; fix with atomics or synchronized." },
  { q: "synchronized provides…", options: ["Speed", "Visibility only", "Mutual exclusion AND visibility (via the monitor)"], answer: 2,
    explain: "Lock release happens-before the next acquire." },
  { q: "Prefer to synchronize on…", options: ["A String literal", "A private final lock object", "this / a public object"], answer: 1,
    explain: "Prevents external interference/deadlock." },
  { q: "ReentrantLock over synchronized when you need…", options: ["Simplicity", "tryLock/timeout/interruptible/fairness", "Nothing"], answer: 1,
    explain: "But you must unlock() in finally." },
  { q: "Deadlock is prevented by…", options: ["More locks", "Bigger heap", "A consistent global lock-acquisition order"], answer: 2,
    explain: "Breaks the circular-wait condition." },
  { q: "wait() must be called…", options: ["Once", "Anywhere", "Holding the lock, inside a while loop"], answer: 2,
    explain: "Guard against spurious wakeups; prefer j.u.c utilities." },
  { q: "For producer/consumer, use a…", options: ["raw wait/notify", "synchronized map", "BlockingQueue (handles blocking/signaling)"], answer: 2,
    explain: "No manual locking needed." },
  { q: "Lock contention…", options: ["Is free", "Serializes threads and kills scalability", "Helps scaling"], answer: 1,
    explain: "Reduce shared state; stripe; use atomics." },
  { q: "The best lock is…", options: ["A big one", "No lock (immutability/confinement)", "A fair one"], answer: 1,
    explain: "Immutable objects have nothing to race on." },
  { q: "A plain break in nested loops…", options: ["Errors", "Exits both", "Exits only the inner loop"], answer: 2,
    explain: "Use a labeled break or extract a method." },
  { q: "start() can be called…", options: ["Once per Thread (else IllegalThreadStateException)", "Never", "Many times"], answer: 0,
    explain: "Create a new thread or use a pool to rerun." },
  { q: "A terminated thread…", options: ["Can restart", "Auto-restarts", "Cannot be restarted"], answer: 2,
    explain: "run() returned or threw; make a new one." },
  { q: "Narrow synchronized blocks are better because…", options: ["They hold the lock for less time (less contention)", "They're safer syntactically", "They're shorter to type"], answer: 0,
    explain: "Never hold a lock during slow I/O." },
  { q: "The four deadlock (Coffman) conditions include…", options: ["Enough memory", "Fast CPUs", "Circular wait"], answer: 2,
    explain: "Break any one — circular wait is the practical lever." },
  { q: "A synchronized instance method locks on…", options: ["A new object", "this", "The class"], answer: 1,
    explain: "A static synchronized method locks on the Class object." },
  { q: "Raw threads are the wrong everyday level because…", options: ["They don't work", "They're expensive and manual — use executors", "They're deprecated"], answer: 1,
    explain: "Submit tasks to a pool instead." },
  { q: "A method that mutates a passed collection is…", options: ["Always fine", "A 'spooky action at a distance' risk", "Impossible"], answer: 1,
    explain: "Prefer returning a new value; document mutation." },
]},
{ title: "Quiz 7 · Concurrency Advanced",
  desc: "Memory model, executors, atomics, concurrent collections, virtual threads",
  questions: [
  { q: "The visibility problem is that…", options: ["A write may never be seen by another thread without sync", "Writes are always seen", "Reads are slow"], answer: 0,
    explain: "The stuck-loop bug: a non-volatile flag." },
  { q: "volatile guarantees…", options: ["Locking", "Visibility and ordering (not compound atomicity)", "Atomicity of count++"], answer: 1,
    explain: "volatile int count; count++ still races." },
  { q: "happens-before is established by…", options: ["Comments", "Nothing", "Locks, volatiles, thread start/join, program order"], answer: 2,
    explain: "No happens-before edge → no visibility guarantee." },
  { q: "Safe publication prevents…", options: ["Seeing a half-constructed object", "Fast code", "GC"], answer: 0,
    explain: "final fields + immutability are safely published by design." },
  { q: "Testing… concurrency correctness", options: ["Cannot prove (nondeterministic) — reason via happens-before", "Speeds up", "Proves"], answer: 0,
    explain: "Minimize shared mutable state." },
  { q: "You should submit tasks to…", options: ["the main thread", "an ExecutorService pool", "new Thread()"], answer: 1,
    explain: "Reuse, bounded resources, results, shutdown." },
  { q: "Callable differs from Runnable in that it…", options: ["Returns a value (via a Future)", "Runs faster", "Can't throw"], answer: 0,
    explain: "Future.get() blocks for the result." },
  { q: "For concurrency, submit all tasks then…", options: ["cancel them", "collect results (don't serialize)", "get() after each submit"], answer: 1,
    explain: "get() after each submit runs them one at a time." },
  { q: "newFixedThreadPool's unbounded queue risks…", options: ["OOM under overload (no backpressure)", "Nothing", "Deadlock"], answer: 0,
    explain: "Use a bounded queue + rejection policy in prod." },
  { q: "CompletableFuture over Future adds…", options: ["Blocking", "Composition (thenApply/thenCompose) and error handling", "Nothing"], answer: 1,
    explain: "No callback hell." },
  { q: "ConcurrentHashMap scales via…", options: ["No locking", "Lock striping (per-bucket) + atomic compound ops", "One big lock"], answer: 1,
    explain: "synchronizedMap serializes everything." },
  { q: "AtomicInteger updates are…", options: ["Locked", "Lock-free via CAS", "Blocking"], answer: 1,
    explain: "No deadlock; LongAdder for high contention." },
  { q: "The ABA problem is…", options: ["A→B→A fools CAS (fix with a version stamp)", "A typo", "A deadlock"], answer: 0,
    explain: "AtomicStampedReference solves it." },
  { q: "CopyOnWriteArrayList is for…", options: ["Sorted data", "Write-heavy data", "Read-heavy, rarely-written lists (listeners)"], answer: 2,
    explain: "It copies the array on every write." },
  { q: "The concurrency tool ladder starts with…", options: ["Locks", "Custom lock-free code", "Immutability/confinement"], answer: 2,
    explain: "Then atomics → concurrent collections → locks." },
  { q: "A virtual thread is scheduled by…", options: ["The JVM (cheap, millions possible)", "The OS", "You"], answer: 0,
    explain: "A platform thread is a 1:1 OS thread." },
  { q: "Pinning happens when a virtual thread blocks in…", options: ["a loop", "a synchronized block (or native call)", "a ReentrantLock"], answer: 1,
    explain: "Prefer ReentrantLock around blocking I/O." },
  { q: "The standard fix for deadlock from two threads locking A,B in opposite orders is…", options: ["More threads", "Bigger locks", "A consistent global lock order (e.g. by id)"], answer: 2,
    explain: "It breaks the circular-wait condition. tryLock-with-timeout is an alternative." },
  { q: "The classic 'check-then-act' race (if absent, put) is fixed by…", options: ["volatile", "A comment", "An atomic op like computeIfAbsent / CAS / one lock across both steps"], answer: 2,
    explain: "The check-and-act must be a single atomic operation." },
  { q: "Deadlock/livelock/starvation are ___ failures; a race is a ___ failure.", options: ["safety / liveness", "both the same", "liveness / safety"], answer: 2,
    explain: "Liveness = no progress; safety = no wrong result. Design for both." },
]},
{ title: "Quiz 8 · JVM, Memory & Performance",
  desc: "Class loading, JIT, stack/heap, references, GC, profiling",
  questions: [
  { q: "Class loading phases are…", options: ["Compile → run", "Loading → Linking (verify/prepare/resolve) → Initialization", "Just loading"], answer: 1,
    explain: "Classes load lazily on first active use." },
  { q: "Parent delegation means a loader…", options: ["Asks its parent first (protects core classes)", "Loads first itself", "Ignores parents"], answer: 0,
    explain: "Your fake java.lang.String is never used." },
  { q: "ClassNotFoundException vs NoClassDefFoundError: the latter is…", options: ["The same", "A compile-time-present class missing/failed at runtime", "An explicit lookup failure"], answer: 1,
    explain: "Often a packaging issue or a static-init failure." },
  { q: "The JIT makes Java fast by…", options: ["Compiling hot code to native using the runtime profile", "Skipping checks", "Precompiling everything"], answer: 0,
    explain: "Cost is warmup; hence benchmarks must warm up." },
  { q: "The stack holds… the heap holds…", options: ["objects / frames", "method frames (locals/refs) / objects", "nothing / everything"], answer: 1,
    explain: "Frames pop on return; heap objects live until unreachable." },
  { q: "The heap is generational because…", options: ["Most objects die young (cheap frequent minor GCs)", "It looks nice", "It's required"], answer: 0,
    explain: "Old gen collected rarely (expensive)." },
  { q: "GC collects objects that are…", options: ["Large", "Old", "Unreachable from GC roots"], answer: 2,
    explain: "Reachability handles cycles (unlike ref-counting)." },
  { q: "A WeakReference is collected…", options: ["Under memory pressure only", "At the next GC if only weakly reachable", "Never"], answer: 1,
    explain: "Soft = under memory pressure; WeakHashMap won't pin keys." },
  { q: "A memory leak in Java means…", options: ["Keeping references alive (retained reachable objects)", "Impossible", "A GC bug"], answer: 0,
    explain: "Static collections, listeners, ThreadLocals, unbounded caches." },
  { q: "StackOverflowError comes from…", options: ["A leak", "Too many nested calls (deep recursion)", "Too many objects"], answer: 1,
    explain: "Different from heap OOM." },
  { q: "Modern GC trades off…", options: ["Only speed", "Nothing", "Throughput vs latency vs footprint (can't max all)"], answer: 2,
    explain: "Stop-the-world pauses hurt interactive services." },
  { q: "The default collector (9+) is…", options: ["Serial", "G1 (balanced)", "Parallel"], answer: 1,
    explain: "ZGC/Shenandoah for low latency; Parallel for batch." },
  { q: "System.gc() is…", options: ["Required", "Fast", "Only a hint — usually wrong to call"], answer: 2,
    explain: "Let the JVM manage collection." },
  { q: "Set -Xms and -Xmx in production…", options: ["Equal (avoid resize pauses)", "To max", "Differently"], answer: 0,
    explain: "Predictability; size to the workload." },
  { q: "The first rule of performance is…", options: ["Measure, don't guess (profile first)", "Optimize everything", "Use more threads"], answer: 0,
    explain: "Time is almost never where you'd guess." },
  { q: "A naive timing-loop benchmark is wrong because of…", options: ["The OS", "JIT warmup + dead-code elimination", "Nothing"], answer: 1,
    explain: "Use JMH for microbenchmarks." },
  { q: "You should optimize…", options: ["The average latency", "Nothing", "Tail latency (p99/p99.9)"], answer: 2,
    explain: "Averages hide the slow requests users notice." },
  { q: "The biggest perf wins usually come from…", options: ["Reducing I/O and algorithmic complexity", "Micro-optimizing CPU", "More flags"], answer: 0,
    explain: "Network ≫ SSD ≫ memory ≫ cache in cost." },
  { q: "A flame graph's widest boxes are…", options: ["Idle", "The hotspots (most CPU time)", "Errors"], answer: 1,
    explain: "Profile under realistic load." },
  { q: "A steadily rising post-GC live set indicates…", options: ["A leak (not undersizing)", "Good GC", "Healthy churn"], answer: 0,
    explain: "Take a heap dump; raising -Xmx only delays OOM." },
]},
{ title: "Quiz 9 · Professional Java",
  desc: "Design patterns, SOLID, testing, build tools",
  questions: [
  { q: "A design pattern is…", options: ["A framework", "A named reusable solution + shared vocabulary", "A library"], answer: 1,
    explain: "Apply when a problem matches; don't force ('pattern fever')." },
  { q: "The best Singleton in Java is…", options: ["A single-element enum", "A static field", "A global"], answer: 0,
    explain: "Thread-safe, serialization/reflection-proof." },
  { q: "The Builder pattern is for…", options: ["One field", "Threads", "Complex/optional-parameter construction → immutable object"], answer: 2,
    explain: "Avoids telescoping constructors." },
  { q: "Lambdas turned Strategy into…", options: ["A one-liner (functional interface + lambda)", "A class hierarchy", "An enum"], answer: 0,
    explain: "Modern features subsume several classic patterns." },
  { q: "The Decorator pattern embodies…", options: ["Singletons", "Deep inheritance", "Composition over inheritance (wrap to add behavior)"], answer: 2,
    explain: "java.io is built on it." },
  { q: "SRP means…", options: ["No inheritance", "One method per class", "One reason to change (one responsibility)"], answer: 2,
    explain: "The class-level 'do one thing'." },
  { q: "OCP means…", options: ["Always inherit", "Open for extension, closed for modification", "Never change code"], answer: 1,
    explain: "Add types via polymorphism, don't edit tested code." },
  { q: "LSP means…", options: ["Subtypes substitutable without breaking behavior", "Small interfaces", "Depend on abstractions"], answer: 0,
    explain: "Square/Rectangle is the classic violation." },
  { q: "DIP is the theoretical basis of…", options: ["Spring's dependency injection", "Inheritance", "Streams"], answer: 0,
    explain: "Depend on abstractions, inject implementations." },
  { q: "DRY targets duplicated…", options: ["Whitespace", "Appearance", "Knowledge (not coincidental similarity)"], answer: 2,
    explain: "Rule of three guards against premature abstraction." },
  { q: "SOLID principles are…", options: ["Strict laws", "Optional", "Guidelines serving safe/local/cheap change"], answer: 2,
    explain: "Apply with judgment; break when dogma adds complexity." },
  { q: "A test follows…", options: ["Assert-only", "Arrange-Act-Assert", "Random structure"], answer: 1,
    explain: "One logical action and assertion per test." },
  { q: "Good tests are FIRST:…", options: ["Slow", "Fast, Isolated, Repeatable, Self-validating, Timely", "Manual"], answer: 1,
    explain: "Flaky tests are worse than none." },
  { q: "Tests should verify…", options: ["Behavior (so they survive refactoring)", "Implementation", "Line coverage"], answer: 0,
    explain: "Implementation-coupled tests break on every refactor." },
  { q: "Mocking lets you…", options: ["Test a unit in isolation (mock external deps)", "Skip tests", "Run faster only"], answer: 0,
    explain: "Enabled by constructor injection; don't over-mock." },
  { q: "The testing pyramid is mostly…", options: ["Integration", "E2E tests", "Fast unit tests (base)"], answer: 2,
    explain: "Inverted pyramid (mostly E2E) is an anti-pattern." },
  { q: "Code coverage is…", options: ["A gap-finder, not a quality measure", "A goal (100%)", "Useless"], answer: 0,
    explain: "You can have 100% coverage asserting nothing." },
  { q: "A build tool…", options: ["Only compiles", "Runs the app", "Resolves deps, compiles, tests, packages — reproducibly"], answer: 2,
    explain: "You never hand-manage the classpath." },
  { q: "Version conflicts ('jar hell') are diagnosed with…", options: ["Guessing", "More memory", "The dependency tree (mvn dependency:tree)"], answer: 2,
    explain: "Fix with pins/exclusions/BOMs." },
  { q: "Dependency hygiene is a… concern", options: ["Style", "Security (transitive CVEs, e.g. Log4Shell)", "Performance only"], answer: 1,
    explain: "Keep deps minimal, current, and scanned." },
]},
{ title: "Quiz 10 · Mixed Mock Exam",
  desc: "Interview-difficulty questions across the whole track",
  questions: [
  { q: "== on objects compares…", options: ["References (use .equals for value)", "Content", "Length"], answer: 0,
    explain: "Foundational trap." },
  { q: "Java is always…", options: ["Pass-by-reference", "Neither", "Pass-by-value (of the reference for objects)"], answer: 2,
    explain: "Mutate the shared object yes; repoint no." },
  { q: "Override equals but not hashCode →", options: ["Objects vanish from hash collections", "Compile error", "Fine"], answer: 0,
    explain: "Override both or use a record." },
  { q: "Favor… over inheritance", options: ["Static methods", "Deep hierarchies", "Composition"], answer: 2,
    explain: "Avoids the fragile base class problem." },
  { q: "PECS: read from a…, write to a…", options: ["extends producer / super consumer", "super / extends", "both extends"], answer: 0,
    explain: "Producer Extends, Consumer Super." },
  { q: "Streams are…", options: ["Eager", "Lazy and single-use", "Reusable"], answer: 1,
    explain: "No terminal → nothing runs." },
  { q: "Never use double for…", options: ["Indexes", "Money", "Loops"], answer: 1,
    explain: "BigDecimal or integer cents." },
  { q: "A record is…", options: ["An interface", "Mutable", "An immutable data carrier (final, accessors, equals)"], answer: 2,
    explain: "Shallowly immutable — copy mutable components." },
  { q: "volatile gives visibility but not…", options: ["ordering", "anything", "compound atomicity (count++ still races)"], answer: 2,
    explain: "Use AtomicInteger for counters." },
  { q: "Deadlock is prevented by…", options: ["More locks", "Consistent global lock ordering", "Bigger heap"], answer: 1,
    explain: "Breaks circular wait." },
  { q: "Virtual threads help… work", options: ["I/O-bound (unmount on block)", "CPU-bound", "no"], answer: 0,
    explain: "Watch for synchronized pinning." },
  { q: "GC collects objects that are…", options: ["Large", "Old", "Unreachable from roots"], answer: 2,
    explain: "A Java 'leak' is retained reachability." },
  { q: "You should optimize… latency", options: ["tail (p99)", "no", "average"], answer: 0,
    explain: "Averages hide the slow requests users feel." },
  { q: "The first rule of performance is…", options: ["Add threads", "Measure, don't guess", "Optimize all"], answer: 1,
    explain: "Profile to find the real hotspot." },
  { q: "The best Singleton is…", options: ["A global", "A single-element enum", "Static field"], answer: 1,
    explain: "Serialization/reflection-proof." },
  { q: "DIP underlies…", options: ["Streams", "Generics", "Spring's dependency injection"], answer: 2,
    explain: "Depend on abstractions, inject implementations." },
  { q: "Tests should verify…", options: ["Behavior", "Coverage %", "Implementation"], answer: 0,
    explain: "So they survive refactoring." },
  { q: "try-with-resources guarantees…", options: ["close() on any exit", "Speed", "Nothing"], answer: 0,
    explain: "Use it for every AutoCloseable." },
  { q: "Sealed + records + pattern matching let you…", options: ["Skip tests", "Write less only", "Make illegal states unrepresentable"], answer: 2,
    explain: "Exhaustive, compiler-checked handling." },
  { q: "The root cause behind ==, shallow copy, and mutable keys is…", options: ["The JVM", "Reference vs value confusion", "Bad luck"], answer: 1,
    explain: "Know what a variable actually holds." },
]},
);
