// java quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations",
  desc: "JVM/bytecode, types, operators, control flow, methods, strings, arrays",
  questions: [
  { q: "javac produces…", options: ["Machine code", "An executable", "Bytecode (portable, run by the JVM)"], answer: 2,
    explain: "Source → bytecode → JVM interprets/JIT-compiles it. Write once, run anywhere." },
  { q: "JDK vs JRE vs JVM: you develop with the…", options: ["JVM", "JDK (JRE + tools like javac)", "JRE"], answer: 1,
    explain: "JDK ⊃ JRE ⊃ JVM: develop / run / execute." },
  { q: "Is Java compiled or interpreted?", options: ["Interpreted only", "Compiled only", "Both — bytecode is interpreted then JIT-compiled"], answer: 2,
    explain: "Hence warmup: slow first, fast after the JIT optimizes hot code." },
  { q: "A primitive variable holds…", options: ["The value directly", "A pointer", "Nothing"], answer: 0,
    explain: "References hold a pointer to a heap object; primitives hold the value." },
  { q: "Is Java pass-by-value or pass-by-reference?", options: ["Pass-by-reference", "Depends", "Always pass-by-value (for objects, the reference's value)"], answer: 2,
    explain: "A method can mutate the shared object but can't repoint the caller's variable." },
  { q: "Integer a=1000,b=1000; a==b is…", options: ["error", "true", "false (outside the −128..127 cache; use .equals)"], answer: 2,
    explain: "== compares references for objects; never use it on wrappers." },
  { q: "7 / 2 evaluates to…", options: ["3.5", "3 (integer division truncates)", "4"], answer: 1,
    explain: "Make an operand double for 3.5." },
  { q: "Integer overflow in Java…", options: ["Wraps silently to a garbage value", "Is impossible", "Throws"], answer: 0,
    explain: "Use long or Math.addExact; never double for money." },
  { q: "-7 % 2 equals…", options: ["1", "0", "-1 (sign of the dividend)"], answer: 2,
    explain: "Use Math.floorMod for a non-negative modulo; test odd with != 0." },
  { q: "&& short-circuits, so a null-guard goes…", options: ["First (so the unsafe check runs only if safe)", "Anywhere", "Second"], answer: 0,
    explain: "if (x != null && x.ok()) avoids the NPE." },
  { q: "The modern arrow switch…", options: ["Falls through", "Has no fall-through and can return a value", "Needs break"], answer: 1,
    explain: "Safer than the classic colon form; exhaustive over enums/sealed types." },
  { q: "Your default loop for iterating a collection is…", options: ["while", "for-each (no index to get wrong)", "do-while"], answer: 1,
    explain: "Removes off-by-one; drop to indexed for only when you need the index." },
  { q: "A method signature is…", options: ["Name + return type", "Name + parameter types (NOT return type)", "Just the name"], answer: 1,
    explain: "So you can't overload on return type alone." },
  { q: "Overloading is resolved…", options: ["Randomly", "At runtime", "At compile time (by argument types)"], answer: 2,
    explain: "Overriding is runtime (dynamic dispatch)." },
  { q: "Deep recursion in Java risks…", options: ["Nothing", "StackOverflowError (no tail-call optimization)", "OOM"], answer: 1,
    explain: "Convert to iteration for deep/linear cases." },
  { q: "Strings are…", options: ["Primitives", "Mutable", "Immutable (every 'change' returns a new String)"], answer: 2,
    explain: "Enables the pool, thread-safety, stable hash keys." },
  { q: "Building a string in a loop with += is…", options: ["O(n²) — use StringBuilder", "Free", "O(n)"], answer: 0,
    explain: "Each += copies the whole accumulated string." },
  { q: "split(\".\") on a literal dot returns…", options: ["The parts", "An error", "An empty array (. is regex 'any char')"], answer: 2,
    explain: "Use split(\"\\\\.\"); split takes a regex." },
  { q: "A new String[3] is initialized to…", options: ["\"0\"", "null (reference-array default)", "Empty strings"], answer: 1,
    explain: "int[] defaults to 0; reference arrays to null." },
  { q: "Printing an array with println shows…", options: ["Type@hashcode (use Arrays.toString)", "Its contents", "An error"], answer: 0,
    explain: "Arrays don't override toString/equals — use the Arrays helpers." },
]},
{ title: "Quiz 2 · Object-Oriented Java",
  desc: "Encapsulation, inheritance, interfaces, equals/hashCode, enums, immutability",
  questions: [
  { q: "Encapsulation's real purpose is to…", options: ["Guarantee invariants (private fields + validating methods)", "Hide code", "Save memory"], answer: 0,
    explain: "Public fields make invariants impossible to enforce." },
  { q: "You get a free no-arg constructor…", options: ["Always", "Only if you declare no constructor", "Never"], answer: 1,
    explain: "Add any constructor and the default disappears." },
  { q: "Polymorphism works via…", options: ["Casting", "Compile-time binding", "Dynamic dispatch on the runtime type"], answer: 2,
    explain: "The overridden method of the actual object runs." },
  { q: "The core inheritance guideline is…", options: ["Deep hierarchies", "Favor composition over inheritance", "Inherit for reuse"], answer: 1,
    explain: "Inheritance is the tightest coupling (fragile base class)." },
  { q: "Calling an overridable method from a constructor…", options: ["Runs the subclass override before the subclass is initialized", "Is illegal", "Is fine"], answer: 0,
    explain: "Only call private/final/static methods in constructors." },
  { q: "A class can implement…", options: ["One interface", "No interfaces", "Many interfaces (but extend one class)"], answer: 2,
    explain: "Interfaces model capabilities that cut across types." },
  { q: "default methods were added to interfaces to…", options: ["Add state", "Let interfaces evolve without breaking implementers", "Replace classes"], answer: 1,
    explain: "e.g. stream()/forEach() added to Collection." },
  { q: "Choose an abstract class over an interface when you need…", options: ["Shared state/constructor", "Multiple inheritance", "A capability"], answer: 0,
    explain: "Interfaces have no instance state; abstract classes do." },
  { q: "The equals/hashCode contract: equal objects must have…", options: ["No hashCode", "Equal hashCodes", "Different hashCodes"], answer: 1,
    explain: "Break it and objects vanish from HashSet/HashMap." },
  { q: "Override equals but not hashCode and objects…", options: ["Throw", "Work fine", "Vanish from hash-based collections (wrong bucket)"], answer: 2,
    explain: "Override both, or use a record." },
  { q: "Comparable defines…", options: ["The single natural ordering (compareTo)", "No ordering", "Many orderings"], answer: 0,
    explain: "Comparator is external, composable orderings." },
  { q: "For a value class, equals should usually use…", options: ["getClass() always", "==", "instanceof (make the class final)", ""], answer: 2,
    explain: "final class + instanceof avoids the symmetry/substitutability dilemma." },
  { q: "An enum is…", options: ["Just named ints", "A String", "A full class (fields, methods, per-constant behavior)"], answer: 2,
    explain: "Type-safe, iterable, exhaustive-switchable." },
  { q: "The best singleton in Java is…", options: ["A static field", "A global variable", "A single-element enum"], answer: 2,
    explain: "One instance, thread-safe, serialization/reflection-proof." },
  { q: "Relying on enum ordinal() for persistence…", options: ["Is required", "Corrupts data if constants are reordered", "Is safe"], answer: 1,
    explain: "Store name() or an explicit code." },
  { q: "A non-static inner class holds…", options: ["Nothing extra", "An implicit reference to the outer instance (leak risk)", "A copy"], answer: 1,
    explain: "Make it static if it doesn't need the outer." },
  { q: "An immutable class needs…", options: ["A setter", "final class + final fields + no setters + defensive copies", "Only final fields"], answer: 1,
    explain: "final on a reference doesn't stop mutating the pointed-to object." },
  { q: "final on a reference variable prevents…", options: ["Everything", "Reassigning the reference (not mutating the object)", "Object mutation"], answer: 1,
    explain: "final ≠ immutable." },
  { q: "Defensive copying validates…", options: ["The original argument", "The copy (avoids a TOCTOU race)", "Nothing"], answer: 1,
    explain: "Copy first, then validate the copy, then store." },
  { q: "Immutability gives you… for free", options: ["Thread-safety, safe sharing, stable hash keys", "Speed only", "Nothing"], answer: 0,
    explain: "No shared mutable state → no races." },
]},
{ title: "Quiz 3 · Collections & Generics",
  desc: "List/Set/Map, internals & Big-O, generics, PECS, erasure",
  questions: [
  { q: "For unique elements you use a…", options: ["Map", "Set", "List"], answer: 1,
    explain: "List = ordered/duplicates; Map = key→value." },
  { q: "Objects in a HashSet/HashMap key need…", options: ["Nothing special", "Comparable", "Correct equals/hashCode (ideally immutable)"], answer: 2,
    explain: "Else dedupe/lookups fail." },
  { q: "The idiomatic word-count uses…", options: ["a loop", "get + put", "map.merge(word, 1, Integer::sum)"], answer: 2,
    explain: "Atomic and concise; computeIfAbsent builds multi-maps." },
  { q: "ArrayList get(i) is…", options: ["O(1) (contiguous array)", "O(n)", "O(log n)"], answer: 0,
    explain: "LinkedList get(i) is O(n)." },
  { q: "You should default to…", options: ["ArrayList (cache locality wins)", "LinkedList", "Vector"], answer: 0,
    explain: "LinkedList's O(1) insert needs a held node; index access is O(n)." },
  { q: "HashMap average get/put is…", options: ["O(log n)", "O(n)", "O(1) (bucket by hash)"], answer: 2,
    explain: "Long collision chains treeify to O(log n) (DoS defense)." },
  { q: "TreeMap gives you…", options: ["O(1) lookup", "Sorted order and range queries (O(log n))", "Insertion order"], answer: 1,
    explain: "Use it only when you need order; LinkedHashMap for insertion order." },
  { q: "Often the biggest perf factor in collections is…", options: ["Cache locality (contiguous beats scattered)", "Big-O only", "Thread count"], answer: 0,
    explain: "Same O(n) can differ 10–50× by memory access." },
  { q: "Generics give you…", options: ["Dynamic typing", "Runtime speed", "Compile-time type safety and no casts"], answer: 2,
    explain: "Errors caught early; List<String> enforced." },
  { q: "PECS means…", options: ["Producer Extends, Consumer Super", "Public Enum Class System", "Nothing"], answer: 0,
    explain: "? extends T to read; ? super T to write." },
  { q: "You can read T from a…", options: ["? super T", "Neither", "? extends T (a producer)"], answer: 2,
    explain: "You write T to a ? super T consumer." },
  { q: "<T extends Number> both restricts T and…", options: ["Boxes T", "Does nothing else", "Lets you call Number's methods on T"], answer: 2,
    explain: "Without a bound, T is treated as Object." },
  { q: "Type erasure means at runtime…", options: ["Types are kept", "List<String> and List<Integer> are both just List", "Generics don't exist"], answer: 1,
    explain: "Hence no new T[], no instanceof List<String>." },
  { q: "You cannot do…", options: ["List<String>", "Box<T>", "new T[10] (erasure)"], answer: 2,
    explain: "No generic array creation; pass a Class<T> or use a List." },
  { q: "Arrays are covariant, generics are…", options: ["Also covariant", "Invariant (compile-time safe)", "Contravariant"], answer: 1,
    explain: "Array covariance → runtime ArrayStoreException; generics catch it at compile time." },
  { q: "To create a T at runtime despite erasure…", options: ["Pass a Class<T> or a Supplier<T>", "new T()", "Impossible"], answer: 0,
    explain: "Thread the type in as data." },
  { q: "Removing from a List during for-each…", options: ["Works", "Throws ConcurrentModificationException", "Is faster"], answer: 1,
    explain: "Use removeIf or the iterator's remove()." },
  { q: "List.of(...) is…", options: ["A view", "Mutable", "Immutable (throws on modification)"], answer: 2,
    explain: "Copy into a new ArrayList to modify." },
  { q: "computeIfAbsent(k, key -> new ArrayList<>()) builds…", options: ["A Set", "Nothing", "A multi-map cleanly (no null checks)"], answer: 2,
    explain: "Creates the list on first use, returns existing after." },
  { q: "ArrayDeque is preferred over Stack because…", options: ["It's older", "Stack is a legacy synchronized class", "It's sorted"], answer: 1,
    explain: "Avoid Vector/Hashtable/Stack; use modern collections." },
]},
{ title: "Quiz 4 · Lambdas & Streams",
  desc: "Functional interfaces, method refs, capture, stream pipelines, collectors",
  questions: [
  { q: "A lambda is an implementation of…", options: ["Any class", "A thread", "A functional interface (one abstract method)"], answer: 2,
    explain: "It only works where such an interface is expected." },
  { q: "Predicate<T> is…", options: ["T → T", "T → boolean", "() → T"], answer: 1,
    explain: "Function T→R, Consumer T→void, Supplier ()→T." },
  { q: "String::toUpperCase is a…", options: ["Constructor ref", "Static ref", "Instance method ref of an arbitrary object"], answer: 2,
    explain: "The stream element becomes the receiver." },
  { q: "A captured local variable must be…", options: ["Static", "Effectively final", "Mutable"], answer: 1,
    explain: "Captured by value; the lambda may outlive the method." },
  { q: "In a lambda, 'this' refers to…", options: ["The enclosing instance", "The lambda", "null"], answer: 0,
    explain: "In an anonymous class, 'this' is the anon instance." },
  { q: "A stream pipeline is…", options: ["always eager", "source → intermediate (lazy) → terminal (eager)", "source → terminal only"], answer: 1,
    explain: "No terminal op → nothing runs." },
  { q: "Streams are…", options: ["Always parallel", "Eager, stage-by-stage", "Lazy and element-at-a-time (short-circuiting)"], answer: 2,
    explain: "findFirst/limit stop early." },
  { q: "map vs flatMap: flatMap…", options: ["Filters", "Is 1:1", "Flattens 1:many (Stream of streams → elements)"], answer: 2,
    explain: "map is exactly one output per input." },
  { q: "groupingBy produces…", options: ["A Map partitioned by a key (with optional downstream collector)", "A Set", "A List"], answer: 0,
    explain: "e.g. groupingBy(dept, counting())." },
  { q: "Parallel streams help for…", options: ["Large CPU-bound independent work on splittable sources", "Small data", "I/O-bound work"], answer: 0,
    explain: "Otherwise slower (overhead) or corrupt (races)." },
  { q: "Mutating shared state in a stream lambda…", options: ["Is fastest", "Is fine", "Breaks under parallelism — use collect/reduce"], answer: 2,
    explain: "Keep lambdas stateless and non-interfering." },
  { q: "A stream is…", options: ["Single-use (terminal consumes it)", "Reusable", "A collection"], answer: 0,
    explain: "Create a fresh one from the source each time." },
  { q: "toMap with duplicate keys…", options: ["Merges", "Ignores them", "Throws unless you provide a merge function"], answer: 2,
    explain: "Supply a BinaryOperator to resolve." },
  { q: "orElse(expensive()) vs orElseGet: orElse…", options: ["Always evaluates its argument (even when present)", "Throws", "Is lazy"], answer: 0,
    explain: "Use orElseGet(supplier) for lazy defaults." },
  { q: "A method reference is best when the lambda…", options: ["Has extra logic", "Is complex", "Just calls a named method with the same args"], answer: 2,
    explain: "Otherwise keep the lambda." },
  { q: "Consumer<T>'s method is…", options: ["apply", "accept", "get"], answer: 1,
    explain: "Predicate.test, Function.apply, Supplier.get." },
  { q: "Passing a Supplier<T> instead of a T enables…", options: ["Deferred/lazy evaluation", "Faster loops", "Nothing"], answer: 0,
    explain: "e.g. log.debug(() -> expensive())." },
  { q: "A functional interface has…", options: ["Many abstract methods", "No methods", "Exactly one abstract method"], answer: 2,
    explain: "@FunctionalInterface enforces it." },
  { q: "IntStream vs Stream<Integer> avoids…", options: ["Nothing", "Laziness", "Boxing overhead"], answer: 2,
    explain: "Primitive specializations for hot numeric pipelines." },
  { q: "forEach(list::add) to build a list is…", options: ["An anti-pattern — use collect(toList())", "Fastest", "Idiomatic"], answer: 0,
    explain: "Unsafe in parallel; express accumulation as a collector." },
]},
{ title: "Quiz 5 · Exceptions, Optional & Modern Java",
  desc: "Error handling, null safety, dates/money, records, sealed, pattern matching",
  questions: [
  { q: "Checked exceptions are…", options: ["Compiler-enforced (catch or declare)", "Not enforced", "Errors"], answer: 0,
    explain: "Unchecked (RuntimeException) are not; modern code favors unchecked." },
  { q: "try-with-resources guarantees…", options: ["close() on any exit (reverse order, suppressed exceptions)", "Nothing", "Faster I/O"], answer: 0,
    explain: "Use it for every AutoCloseable." },
  { q: "When wrapping an exception you should…", options: ["Log twice", "Chain the cause (new X(msg, e))", "Drop the cause"], answer: 1,
    explain: "Preserves the stack trace trail." },
  { q: "return in a finally block…", options: ["Is required", "Swallows the try's exception", "Is fine"], answer: 1,
    explain: "Never return/throw from finally." },
  { q: "The cardinal error-handling sin is…", options: ["Logging", "Rethrowing", "Swallowing (empty catch)"], answer: 2,
    explain: "Handle at the layer that can act; don't hide failures." },
  { q: "Optional's main value is on…", options: ["Return types (absence explicit in the type)", "Parameters", "Fields"], answer: 0,
    explain: "Don't use it as a field/parameter/collection wrapper." },
  { q: "optional.get() without checking…", options: ["Is safe", "Throws NoSuchElementException (an anti-pattern)", "Returns null"], answer: 1,
    explain: "Use orElse/orElseThrow/ifPresent/map." },
  { q: "The deepest null fix is…", options: ["Not creating nulls (empty collections, validation)", "try/catch", "Optional everywhere"], answer: 0,
    explain: "Optional is one tool in a broader strategy." },
  { q: "Never use double for…", options: ["Coordinates", "Money (0.1+0.2≠0.3)", "Loops"], answer: 1,
    explain: "Use BigDecimal or integer cents." },
  { q: "BigDecimal should be constructed from…", options: ["A String", "A double", "A float"], answer: 0,
    explain: "new BigDecimal(0.1) captures binary imprecision." },
  { q: "Store/compute times in… and convert for display", options: ["Epoch millis in local", "Local time", "UTC (Instant)"], answer: 2,
    explain: "Use region ZoneIds (DST-aware), not fixed offsets." },
  { q: "A record generates…", options: ["final fields, accessors, equals/hashCode/toString", "Setters", "Nothing"], answer: 0,
    explain: "Immutable data carrier in one line." },
  { q: "Sealed types enable…", options: ["Nothing", "Compiler-checked exhaustiveness (no default needed)", "Faster code"], answer: 1,
    explain: "Adding a subtype breaks every exhaustive switch." },
  { q: "Records + sealed + pattern matching let you…", options: ["Write less only", "Skip tests", "Make illegal states unrepresentable"], answer: 2,
    explain: "Algebraic data types — force every case to be handled." },
  { q: "A regex Pattern should be compiled…", options: ["Never", "On every call via String.matches()", "Once into a static final field, reused"], answer: 2,
    explain: "Compiling is expensive; matching is cheap. Pattern is thread-safe; Matcher is not." },
  { q: "A pattern like (a+)+ on hostile input can…", options: ["Backtrack exponentially (ReDoS) and hang a thread", "Never fail", "Only mismatch"], answer: 0,
    explain: "Nested/overlapping quantifiers are a DoS risk — use linear/possessive patterns, bound input." },
  { q: "For a runtime framework (Spring/JUnit) to read a custom annotation, it must have…", options: ["public fields", "@Retention(RUNTIME)", "@Target only"], answer: 1,
    explain: "SOURCE/CLASS retention is gone before the code runs — the framework sees nothing." },
  { q: "Reflection's setAccessible(true) is dangerous because it…", options: ["Never works", "Is slow only", "Bypasses private (breaks encapsulation) and can be blocked by the module system"], answer: 2,
    explain: "It also defers a mistyped method name to a runtime failure. Prefer compile-time codegen where possible." },
  { q: "In JPMS, a public class in a non-exported package is…", options: ["Accessible everywhere", "A compile error", "Invisible outside its module (strongly encapsulated)"], answer: 2,
    explain: "Accessibility now = access modifier AND package export status." },
  { q: "exports vs opens: a framework like Jackson reflecting into your private fields needs…", options: ["opens (runtime deep reflection)", "exports", "requires"], answer: 0,
    explain: "exports grants public-API access; opens grants reflective access. Qualify it: opens ... to jackson." },
]},
);
