// Java quiz bank — sets 1–5 (20 questions each, with explanations)
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Syntax, Types & Variables",
  desc: "Primitives vs references, ==, autoboxing, Strings",
  questions: [
  { q: "int y = x (both int) copies…", options: ["A reference", "The VALUE (primitives copied by value)", "Nothing"], answer: 1,
    explain: "Primitives hold the value directly; y and x are independent." },
  { q: "int[] b = a (arrays) copies…", options: ["The array", "The REFERENCE — a and b point to the same array", "Nothing"], answer: 1,
    explain: "References are copied by reference; mutating b[0] changes a[0]." },
  { q: "Is Java pass-by-reference?", options: ["Yes", "No — always pass-by-value (for objects, the reference's value is passed)", "Sometimes"], answer: 1,
    explain: "A method can mutate the object but can't repoint the caller's variable." },
  { q: "== on two String objects compares…", options: ["Value", "References (use .equals for value)", "Length"], answer: 1,
    explain: "Objects compare by reference with ==; .equals compares content." },
  { q: "Integer a=1000,b=1000; a==b is…", options: ["true", "false (different objects; only −128..127 are cached)", "error"], answer: 1,
    explain: "Never rely on == for Integer; use .equals." },
  { q: "Integer n=null; int z=n; throws…", options: ["Nothing", "NullPointerException (unboxing null)", "0"], answer: 1,
    explain: "Auto-unboxing a null wrapper NPEs." },
  { q: "Strings in Java are…", options: ["Mutable", "Immutable (methods return new strings)", "Primitives"], answer: 1,
    explain: "Enables the string pool, thread-safety, hashable keys." },
  { q: "Building a string in a loop should use…", options: ["+=", "StringBuilder (+ is O(n²))", "concat"], answer: 1,
    explain: "Each += allocates a new String." },
  { q: "var count = 10 is…", options: ["Dynamically typed", "Local type inference (still statically int)", "Untyped"], answer: 1,
    explain: "var infers the type; Java stays statically typed." },
  { q: "final int MAX = 100 means…", options: ["Static", "Cannot be reassigned (Java's const)", "Private"], answer: 1,
    explain: "final = constant reference/value." },
  { q: "Which are primitives?", options: ["String, Integer", "int, double, char, boolean (lowercase)", "List, Map"], answer: 1,
    explain: "Primitives are lowercase; wrappers (Integer) and everything else are references." },
  { q: "Collections like List<Integer> hold…", options: ["Primitives", "Objects (wrappers) — autoboxing converts int↔Integer", "Both"], answer: 1,
    explain: "Generics need reference types; primitives are boxed." },
  { q: "For money, use…", options: ["double", "BigDecimal (float/double have rounding errors)", "float"], answer: 1,
    explain: "Same IEEE-754 issue as every language." },
  { q: "The string pool means \"a\" == \"a\" is…", options: ["false", "true (literals are interned to the same object)", "error"], answer: 1,
    explain: "But new String(\"a\") == new String(\"a\") is false." },
  { q: "javac produces…", options: ["Native code", ".class bytecode run by the JVM", "an exe"], answer: 1,
    explain: "Write once, run anywhere via the JVM." },
  { q: "a.equals(b) on Integers compares…", options: ["References", "Values (always use for object equality)", "Hashcodes"], answer: 1,
    explain: "The safe equality check for wrappers/objects." },
  { q: "public class Hello must be in a file named…", options: ["anything.java", "Hello.java (public class name = filename)", "main.java"], answer: 1,
    explain: "The public class name must match the filename." },
  { q: "Autoboxing is…", options: ["Encryption", "Automatic int↔Integer conversion", "Threading"], answer: 1,
    explain: "Convenient but watch == and null-unboxing traps." },
  { q: "A reference variable can be…", options: ["Never null", "null (primitives can't)", "Only 0"], answer: 1,
    explain: "Only references can hold null; unboxing null NPEs." },
  { q: "text blocks \"\"\" ... \"\"\" provide…", options: ["Encryption", "Multi-line string literals", "Comments"], answer: 1,
    explain: "Modern multi-line strings; .formatted() for interpolation." }
]},

{ title: "Quiz 2 · Control Flow & Methods",
  desc: "switch, loops, overloading vs overriding, static, access",
  questions: [
  { q: "The switch EXPRESSION (arrow ->) differs from the statement by…", options: ["Being slower", "No fall-through, returns a value, must be exhaustive", "Needing break"], answer: 1,
    explain: "The old statement's fall-through was a classic bug source." },
  { q: "Overloading is resolved at…", options: ["Runtime", "Compile time (by argument types — static dispatch)", "Never"], answer: 1,
    explain: "Overriding is runtime (dynamic dispatch by object)." },
  { q: "Overriding is resolved at…", options: ["Compile time", "Runtime (by the actual object's type — polymorphism)", "Link time"], answer: 1,
    explain: "The basis of polymorphism; @Override marks it." },
  { q: "static means the member belongs to…", options: ["Each instance", "The CLASS (shared, called via ClassName.member)", "The package"], answer: 1,
    explain: "Good for stateless utilities; dangerous as mutable state." },
  { q: "void reset(int x){x=0} affects the caller's int?", options: ["Yes", "No — primitive copy", "Sometimes"], answer: 1,
    explain: "Pass-by-value: the copy is changed, not the caller's." },
  { q: "void clear(List l){l.clear()} affects the caller?", options: ["No", "Yes — mutates the same list object", "Error"], answer: 1,
    explain: "The reference points to the caller's list; mutation is visible." },
  { q: "void swap(List l){l=new ...} affects the caller?", options: ["Yes", "No — reassigns the local copy of the reference", "Throws"], answer: 1,
    explain: "Can't repoint the caller's variable (pass-by-value)." },
  { q: "int... nums (varargs) is received as…", options: ["A List", "an int[]", "a String"], answer: 1,
    explain: "Accepts any count incl. zero; treated as an array inside." },
  { q: "private members are visible to…", options: ["Subclasses", "The same class only", "The package"], answer: 1,
    explain: "public/protected/package-private/private control scope." },
  { q: "Enhanced for (for (var x : items)) is preferred over…", options: ["streams", "index loops for simple iteration", "while"], answer: 1,
    explain: "Fewer off-by-one bugs; streams for transformations." },
  { q: "Missing break in an old switch statement causes…", options: ["An error", "Fall-through to later cases", "Nothing"], answer: 1,
    explain: "Use the arrow switch expression to avoid it." },
  { q: "Pattern matching switch (case Integer i when i>0) needs Java…", options: ["8", "21+ (patterns + guards)", "1.0"], answer: 1,
    explain: "instanceof patterns 16+, switch patterns 21+." },
  { q: "static final int LIMIT = 50 is…", options: ["A variable", "A class-level constant", "A method"], answer: 1,
    explain: "The conventional 'constant' form." },
  { q: "= vs == in an if condition:", options: ["Same", "= assigns (only compiles for boolean); == compares", "Both compare"], answer: 1,
    explain: ".equals for objects; == for primitives/identity." },
  { q: "A method with the same name but different params is…", options: ["Overriding", "Overloading (compile-time)", "Shadowing"], answer: 1,
    explain: "Same class, different parameter lists." },
  { q: "protected members are visible to…", options: ["Everyone", "Same package + subclasses", "Same class only"], answer: 1,
    explain: "One step broader than package-private." },
  { q: "Labels (outer: for...) are for…", options: ["Naming", "Breaking/continuing outer loops in nested loops", "Comments"], answer: 1,
    explain: "Rare; usually a sign to extract a method." },
  { q: "do { } while(cond) runs the body…", options: ["Zero+ times", "At least once (condition checked after)", "Never"], answer: 1,
    explain: "vs while which may run zero times." },
  { q: "A static method can access…", options: ["Instance fields directly", "Only static members (no this)", "Everything"], answer: 1,
    explain: "No instance context; pass state as parameters." },
  { q: "Prefer returning values over mutating shared state because…", options: ["It's shorter", "Explicit flow, testability, fewer side effects", "It's required"], answer: 1,
    explain: "Same purity argument across languages." }
]},

{ title: "Quiz 3 · OOP: Classes & Interfaces",
  desc: "Four pillars, interface vs abstract, equals/hashCode, composition",
  questions: [
  { q: "Encapsulation means…", options: ["Inheritance", "Private state + public behavior enforcing invariants", "Polymorphism"], answer: 1,
    explain: "Fields private; controlled access via methods." },
  { q: "Polymorphism (Shape s = new Circle()) dispatches area() at…", options: ["Compile time", "Runtime (the actual object's method)", "Never"], answer: 1,
    explain: "Dynamic dispatch — one reference type, many runtime types." },
  { q: "A class can implement…", options: ["One interface", "MANY interfaces (extend only one class)", "No interfaces"], answer: 1,
    explain: "Multiple inheritance of TYPE via interfaces." },
  { q: "Interfaces since Java 8 can have…", options: ["Only abstract methods", "default and static methods (private since 9)", "Fields with state"], answer: 1,
    explain: "default methods add behavior without breaking implementers." },
  { q: "Override equals but not hashCode →", options: ["Faster", "Objects break as HashMap keys/HashSet members", "Compile error"], answer: 1,
    explain: "Equal objects must have equal hashCodes; override both." },
  { q: "'CAN-DO' capability → ; 'IS-A with shared state' →", options: ["class ; interface", "interface ; abstract class", "both interface"], answer: 1,
    explain: "Interface = capability; abstract class = shared base." },
  { q: "@Override does what?", options: ["Nothing", "Compiler-checks that you're actually overriding (catches signature typos)", "Runs code"], answer: 1,
    explain: "Always annotate overrides." },
  { q: "abstract class vs interface — abstract classes can have…", options: ["Nothing extra", "Instance fields/state and constructors", "Multiple inheritance"], answer: 1,
    explain: "Interfaces have no instance state; single inheritance for classes." },
  { q: "Favor composition over inheritance because…", options: ["It's faster", "Inheritance couples to base internals (fragile); composition is flexible/testable", "It's required"], answer: 1,
    explain: "Effective Java's canonical advice; basis of DI." },
  { q: "Program to interfaces means…", options: ["Only use interfaces", "Depend on abstractions (List) not concretions (ArrayList)", "No classes"], answer: 1,
    explain: "Enables swapping implementations and mocking." },
  { q: "The hashCode/equals contract: equal objects must…", options: ["Have different hashCodes", "Have EQUAL hashCodes", "Be identical"], answer: 1,
    explain: "Reverse isn't required; unequal may share (collision)." },
  { q: "instanceof pattern (o instanceof Account a) …", options: ["Just tests", "Tests AND binds a typed variable in one", "Casts unsafely"], answer: 1,
    explain: "16+; removes the separate cast." },
  { q: "Comparable<T> is used to…", options: ["Hash", "Define natural ordering (compareTo)", "Copy"], answer: 1,
    explain: "Comparator for external/multiple orderings." },
  { q: "A record generates equals/hashCode…", options: ["Incorrectly", "Correctly from its components (great for keys)", "Not at all"], answer: 1,
    explain: "Solves the equals/hashCode boilerplate safely." },
  { q: "Abstract methods must be…", options: ["Implemented in the abstract class", "Implemented by concrete subclasses", "Static"], answer: 1,
    explain: "Abstract classes can't be instantiated." },
  { q: "Deep inheritance hierarchies…", options: ["Are best practice", "Age badly (fragile base class) — prefer composition", "Are required"], answer: 1,
    explain: "Same verdict across OOP languages." },
  { q: "Public mutable fields are…", options: ["Fine", "An encapsulation violation (broken invariants)", "Faster"], answer: 1,
    explain: "Keep fields private; expose behavior." },
  { q: "A functional interface has…", options: ["Many abstract methods", "Exactly one abstract method (enables lambdas)", "No methods"], answer: 1,
    explain: "Runnable, Comparator, Function — targets for lambdas." },
  { q: "Interfaces enable polymorphism without…", options: ["Methods", "an inheritance (is-a) relationship", "Types"], answer: 1,
    explain: "Unrelated classes share a capability." },
  { q: "The four OOP pillars are…", options: ["MVC", "Encapsulation, inheritance, polymorphism, abstraction", "SOLID"], answer: 1,
    explain: "SOLID is a set of design principles, not the pillars." }
]},

{ title: "Quiz 4 · Collections Framework",
  desc: "List/Map/Set/Queue, Big-O, equals/hashCode, iteration",
  questions: [
  { q: "The default List implementation is…", options: ["LinkedList", "ArrayList (O(1) get, cache-friendly)", "Vector"], answer: 1,
    explain: "LinkedList rarely wins in practice." },
  { q: "ArrayList.get(i) is…", options: ["O(n)", "O(1)", "O(log n)"], answer: 1,
    explain: "Array-backed random access; mid-insert is O(n)." },
  { q: "HashMap get/put is…", options: ["O(n)", "O(1) average", "O(log n)"], answer: 1,
    explain: "Hash table; TreeMap is O(log n) sorted." },
  { q: "map.get(key) returns null for a 'present' key when…", options: ["The map is full", "The key class has bad/missing equals+hashCode", "Never"], answer: 1,
    explain: "Hash structures rely on both; use records or override both." },
  { q: "Modifying a list during a for-each throws…", options: ["Nothing", "ConcurrentModificationException", "NPE"], answer: 1,
    explain: "Use removeIf / iterator.remove()." },
  { q: "For a queue/stack, prefer…", options: ["Stack/Vector (legacy)", "ArrayDeque (fast both ends)", "LinkedList.get"], answer: 1,
    explain: "ArrayDeque beats legacy synchronized Stack/Vector." },
  { q: "getOrDefault / computeIfAbsent help avoid…", options: ["Nothing", "null checks and NPEs; enable grouping idioms", "Sorting"], answer: 1,
    explain: "computeIfAbsent(k, x->new ArrayList<>()).add(v) groups cleanly." },
  { q: "TreeMap provides…", options: ["No order", "Sorted keys + range/navigable queries (O(log n))", "O(1)"], answer: 1,
    explain: "LinkedHashMap = insertion order; HashMap = none." },
  { q: "List.of(1,2,3) is…", options: ["Mutable", "Immutable (throws on modify)", "A LinkedList"], answer: 1,
    explain: "Immutable factory methods." },
  { q: "Mutating a key AFTER inserting into a HashMap…", options: ["Is fine", "Breaks lookup (bucket no longer matches)", "Re-sorts"], answer: 1,
    explain: "Use immutable keys." },
  { q: "PriorityQueue offers…", options: ["FIFO only", "A heap (O(log n) offer/poll) for top-K/priority", "Sorted iteration"], answer: 1,
    explain: "Head is the min/max by comparator." },
  { q: "HashMap resolves collisions by…", options: ["Rejecting keys", "Chaining (and treeifying long chains)", "Overwriting"], answer: 1,
    explain: "Buckets hold multiple entries distinguished by equals." },
  { q: "Program to which type in method signatures?", options: ["ArrayList", "List/Map/Set (the interface)", "Object"], answer: 1,
    explain: "Flexibility to change implementations." },
  { q: "HashSet gives membership in…", options: ["O(n)", "O(1) average", "O(log n)"], answer: 1,
    explain: "Backed by a HashMap; needs good hashCode." },
  { q: "The safe removal idiom in a loop is…", options: ["list.remove in for-each", "list.removeIf(predicate) or iterator.remove()", "clear()"], answer: 1,
    explain: "Avoids ConcurrentModificationException." },
  { q: "LinkedList.get(i) is…", options: ["O(1)", "O(n) (node traversal)", "O(log n)"], answer: 1,
    explain: "Why ArrayList is the default List." },
  { q: "merge(\"k\",1,Integer::sum) does…", options: ["Deletes k", "Increments-or-initializes the value for k", "Sorts"], answer: 1,
    explain: "Concise counting idiom." },
  { q: "For thread-safe shared maps, use…", options: ["HashMap", "ConcurrentHashMap", "TreeMap"], answer: 1,
    explain: "java.util.concurrent collections over external locking." },
  { q: "entrySet() is the correct way to…", options: ["Sort", "Iterate a map's key+value pairs efficiently", "Copy"], answer: 1,
    explain: "Avoids a get() per key." },
  { q: "The Collections Framework is organized around…", options: ["Classes only", "Interfaces (List/Set/Map/Queue) with multiple impls", "Arrays"], answer: 1,
    explain: "Pick the impl for the access pattern." }
]},

{ title: "Quiz 5 · Generics",
  desc: "Type safety, erasure, wildcards/PECS, bounds",
  questions: [
  { q: "Generics provide…", options: ["Runtime types", "Compile-time type safety (no casts, checked containers)", "Speed"], answer: 1,
    explain: "List<String> vs raw List of Objects." },
  { q: "Type erasure means at runtime…", options: ["Types are kept", "The type parameter is ERASED (List<String> and List<Integer> are both List)", "Nothing"], answer: 1,
    explain: "For backward compatibility with raw types." },
  { q: "Because of erasure you CANNOT…", options: ["Use generics", "new T(), new T[], or instanceof List<String>", "Declare <T>"], answer: 1,
    explain: "The type isn't known at runtime." },
  { q: "PECS stands for…", options: ["A pattern", "Producer Extends, Consumer Super", "A collector"], answer: 1,
    explain: "Read → extends; write → super." },
  { q: "List<? extends Number> lets you…", options: ["Add numbers", "READ as Number (can't add — exact subtype unknown)", "Add anything"], answer: 1,
    explain: "Producer: safe to read, unsafe to write." },
  { q: "List<? super Integer> lets you…", options: ["Read as Integer", "ADD Integers (reads only guarantee Object)", "Nothing"], answer: 1,
    explain: "Consumer: safe to write." },
  { q: "<T extends Number> is a…", options: ["Wildcard", "Bounded type parameter (T must be a Number)", "Cast"], answer: 1,
    explain: "Constrains what T can be; enables .doubleValue()." },
  { q: "Raw types (List instead of List<String>)…", options: ["Are recommended", "Lose type safety (unchecked warnings, ClassCastException)", "Are faster"], answer: 1,
    explain: "Always parameterize." },
  { q: "new T[10] is…", options: ["Allowed", "A compile error (generic array creation, erasure)", "Slow"], answer: 1,
    explain: "Arrays are reified; generics erased — incompatible." },
  { q: "List<Object> vs List<?> :", options: ["Same", "List<Object> is a specific type; List<?> means 'unknown type'", "Both accept anything"], answer: 1,
    explain: "You can't add (except null) to a List<?>." },
  { q: "The diamond operator <> …", options: ["Is required always", "Infers the type argument (new ArrayList<>())", "Casts"], answer: 1,
    explain: "Reduces redundancy." },
  { q: "A generic method declares its type param…", options: ["On the class", "before the return type: <T> T first(List<T>)", "In annotations"], answer: 1,
    explain: "Independent of any class type param." },
  { q: "Collections.copy(dest, src) uses PECS as…", options: ["Both extends", "dest <? super T> (consumer), src <? extends T> (producer)", "Both super"], answer: 1,
    explain: "Canonical PECS example." },
  { q: "instanceof List<String> is…", options: ["Fine", "Illegal (erasure) — only instanceof List<?>", "Runtime-checked"], answer: 1,
    explain: "The parameter isn't available at runtime." },
  { q: "Comparable<T> and Comparator<T> are…", options: ["Classes", "Generic interfaces you implement for ordering", "Collectors"], answer: 1,
    explain: "Comparator.comparing(...).thenComparing(...)." },
  { q: "Why can't Java reify generics like C#?", options: ["It could", "Backward compatibility with pre-generics raw code required erasure", "Performance"], answer: 1,
    explain: "A deliberate compatibility trade-off." },
  { q: "A bounded wildcard maximizes…", options: ["Speed", "API flexibility (what callers can pass) while staying type-safe", "Memory"], answer: 1,
    explain: "PECS widens accepted argument types." },
  { q: "Unchecked warnings usually mean…", options: ["A bug in javac", "Raw types / unsafe casts defeating generics", "Success"], answer: 1,
    explain: "Fix by parameterizing; @SuppressWarnings only when proven safe." },
  { q: "You can add to a List<? extends Number>…", options: ["Any Number", "Only null (can't add elements)", "Integers"], answer: 1,
    explain: "The exact subtype is unknown — writes are unsafe." },
  { q: "Generics are primarily a … feature", options: ["Runtime", "Compile-time (erased afterward)", "JVM"], answer: 1,
    explain: "Type checking happens at compile time." }
]}
);
