// Java quiz bank — sets 1–5 (20 questions each, with explanations). Mapped to the deep curriculum.
window.QUIZ_SETS = window.QUIZ_SETS || [];
window.QUIZ_SETS.push(
{ title: "Quiz 1 · Foundations",
  desc: "JVM/bytecode, types, operators, control flow, methods, strings, arrays",
  questions: [
  { q: "javac produces…", options: ["Machine code", "Bytecode (portable, run by the JVM)", "An executable"], answer: 1,
    explain: "Source → bytecode → JVM interprets/JIT-compiles it. Write once, run anywhere." },
  { q: "JDK vs JRE vs JVM: you develop with the…", options: ["JVM", "JRE", "JDK (JRE + tools like javac)"], answer: 2,
    explain: "JDK ⊃ JRE ⊃ JVM: develop / run / execute." },
  { q: "Is Java compiled or interpreted?", options: ["Compiled only", "Both — bytecode is interpreted then JIT-compiled", "Interpreted only"], answer: 1,
    explain: "Hence warmup: slow first, fast after the JIT optimizes hot code." },
  { q: "A primitive variable holds…", options: ["A pointer", "The value directly", "Nothing"], answer: 1,
    explain: "References hold a pointer to a heap object; primitives hold the value." },
  { q: "Is Java pass-by-value or pass-by-reference?", options: ["Pass-by-reference", "Always pass-by-value (for objects, the reference's value)", "Depends"], answer: 1,
    explain: "A method can mutate the shared object but can't repoint the caller's variable." },
  { q: "Integer a=1000,b=1000; a==b is…", options: ["true", "false (outside the −128..127 cache; use .equals)", "error"], answer: 1,
    explain: "== compares references for objects; never use it on wrappers." },
  { q: "7 / 2 evaluates to…", options: ["3.5", "3 (integer division truncates)", "4"], answer: 1,
    explain: "Make an operand double for 3.5." },
  { q: "Integer overflow in Java…", options: ["Throws", "Wraps silently to a garbage value", "Is impossible"], answer: 1,
    explain: "Use long or Math.addExact; never double for money." },
  { q: "-7 % 2 equals…", options: ["1", "-1 (sign of the dividend)", "0"], answer: 1,
    explain: "Use Math.floorMod for a non-negative modulo; test odd with != 0." },
  { q: "&& short-circuits, so a null-guard goes…", options: ["Second", "First (so the unsafe check runs only if safe)", "Anywhere"], answer: 1,
    explain: "if (x != null && x.ok()) avoids the NPE." },
  { q: "The modern arrow switch…", options: ["Falls through", "Has no fall-through and can return a value", "Needs break"], answer: 1,
    explain: "Safer than the classic colon form; exhaustive over enums/sealed types." },
  { q: "Your default loop for iterating a collection is…", options: ["while", "for-each (no index to get wrong)", "do-while"], answer: 1,
    explain: "Removes off-by-one; drop to indexed for only when you need the index." },
  { q: "A method signature is…", options: ["Name + return type", "Name + parameter types (NOT return type)", "Just the name"], answer: 1,
    explain: "So you can't overload on return type alone." },
  { q: "Overloading is resolved…", options: ["At runtime", "At compile time (by argument types)", "Randomly"], answer: 1,
    explain: "Overriding is runtime (dynamic dispatch)." },
  { q: "Deep recursion in Java risks…", options: ["Nothing", "StackOverflowError (no tail-call optimization)", "OOM"], answer: 1,
    explain: "Convert to iteration for deep/linear cases." },
  { q: "Strings are…", options: ["Mutable", "Immutable (every 'change' returns a new String)", "Primitives"], answer: 1,
    explain: "Enables the pool, thread-safety, stable hash keys." },
  { q: "Building a string in a loop with += is…", options: ["O(n)", "O(n²) — use StringBuilder", "Free"], answer: 1,
    explain: "Each += copies the whole accumulated string." },
  { q: "split(\".\") on a literal dot returns…", options: ["The parts", "An empty array (. is regex 'any char')", "An error"], answer: 1,
    explain: "Use split(\"\\\\.\"); split takes a regex." },
  { q: "A new String[3] is initialized to…", options: ["Empty strings", "null (reference-array default)", "\"0\""], answer: 1,
    explain: "int[] defaults to 0; reference arrays to null." },
  { q: "Printing an array with println shows…", options: ["Its contents", "Type@hashcode (use Arrays.toString)", "An error"], answer: 1,
    explain: "Arrays don't override toString/equals — use the Arrays helpers." }
]},

{ title: "Quiz 2 · Object-Oriented Java",
  desc: "Encapsulation, inheritance, interfaces, equals/hashCode, enums, immutability",
  questions: [
  { q: "Encapsulation's real purpose is to…", options: ["Hide code", "Guarantee invariants (private fields + validating methods)", "Save memory"], answer: 1,
    explain: "Public fields make invariants impossible to enforce." },
  { q: "You get a free no-arg constructor…", options: ["Always", "Only if you declare no constructor", "Never"], answer: 1,
    explain: "Add any constructor and the default disappears." },
  { q: "Polymorphism works via…", options: ["Compile-time binding", "Dynamic dispatch on the runtime type", "Casting"], answer: 1,
    explain: "The overridden method of the actual object runs." },
  { q: "The core inheritance guideline is…", options: ["Inherit for reuse", "Favor composition over inheritance", "Deep hierarchies"], answer: 1,
    explain: "Inheritance is the tightest coupling (fragile base class)." },
  { q: "Calling an overridable method from a constructor…", options: ["Is fine", "Runs the subclass override before the subclass is initialized", "Is illegal"], answer: 1,
    explain: "Only call private/final/static methods in constructors." },
  { q: "A class can implement…", options: ["One interface", "Many interfaces (but extend one class)", "No interfaces"], answer: 1,
    explain: "Interfaces model capabilities that cut across types." },
  { q: "default methods were added to interfaces to…", options: ["Add state", "Let interfaces evolve without breaking implementers", "Replace classes"], answer: 1,
    explain: "e.g. stream()/forEach() added to Collection." },
  { q: "Choose an abstract class over an interface when you need…", options: ["Multiple inheritance", "Shared state/constructor", "A capability"], answer: 1,
    explain: "Interfaces have no instance state; abstract classes do." },
  { q: "The equals/hashCode contract: equal objects must have…", options: ["Different hashCodes", "Equal hashCodes", "No hashCode"], answer: 1,
    explain: "Break it and objects vanish from HashSet/HashMap." },
  { q: "Override equals but not hashCode and objects…", options: ["Work fine", "Vanish from hash-based collections (wrong bucket)", "Throw"], answer: 1,
    explain: "Override both, or use a record." },
  { q: "Comparable defines…", options: ["Many orderings", "The single natural ordering (compareTo)", "No ordering"], answer: 1,
    explain: "Comparator is external, composable orderings." },
  { q: "For a value class, equals should usually use…", options: ["getClass() always", "instanceof (make the class final)", "==", ""], answer: 1,
    explain: "final class + instanceof avoids the symmetry/substitutability dilemma." },
  { q: "An enum is…", options: ["Just named ints", "A full class (fields, methods, per-constant behavior)", "A String"], answer: 1,
    explain: "Type-safe, iterable, exhaustive-switchable." },
  { q: "The best singleton in Java is…", options: ["A static field", "A single-element enum", "A global variable"], answer: 1,
    explain: "One instance, thread-safe, serialization/reflection-proof." },
  { q: "Relying on enum ordinal() for persistence…", options: ["Is safe", "Corrupts data if constants are reordered", "Is required"], answer: 1,
    explain: "Store name() or an explicit code." },
  { q: "A non-static inner class holds…", options: ["Nothing extra", "An implicit reference to the outer instance (leak risk)", "A copy"], answer: 1,
    explain: "Make it static if it doesn't need the outer." },
  { q: "An immutable class needs…", options: ["Only final fields", "final class + final fields + no setters + defensive copies", "A setter"], answer: 1,
    explain: "final on a reference doesn't stop mutating the pointed-to object." },
  { q: "final on a reference variable prevents…", options: ["Object mutation", "Reassigning the reference (not mutating the object)", "Everything"], answer: 1,
    explain: "final ≠ immutable." },
  { q: "Defensive copying validates…", options: ["The original argument", "The copy (avoids a TOCTOU race)", "Nothing"], answer: 1,
    explain: "Copy first, then validate the copy, then store." },
  { q: "Immutability gives you… for free", options: ["Nothing", "Thread-safety, safe sharing, stable hash keys", "Speed only"], answer: 1,
    explain: "No shared mutable state → no races." }
]},

{ title: "Quiz 3 · Collections & Generics",
  desc: "List/Set/Map, internals & Big-O, generics, PECS, erasure",
  questions: [
  { q: "For unique elements you use a…", options: ["List", "Set", "Map"], answer: 1,
    explain: "List = ordered/duplicates; Map = key→value." },
  { q: "Objects in a HashSet/HashMap key need…", options: ["Nothing special", "Correct equals/hashCode (ideally immutable)", "Comparable"], answer: 1,
    explain: "Else dedupe/lookups fail." },
  { q: "The idiomatic word-count uses…", options: ["get + put", "map.merge(word, 1, Integer::sum)", "a loop"], answer: 1,
    explain: "Atomic and concise; computeIfAbsent builds multi-maps." },
  { q: "ArrayList get(i) is…", options: ["O(n)", "O(1) (contiguous array)", "O(log n)"], answer: 1,
    explain: "LinkedList get(i) is O(n)." },
  { q: "You should default to…", options: ["LinkedList", "ArrayList (cache locality wins)", "Vector"], answer: 1,
    explain: "LinkedList's O(1) insert needs a held node; index access is O(n)." },
  { q: "HashMap average get/put is…", options: ["O(n)", "O(1) (bucket by hash)", "O(log n)"], answer: 1,
    explain: "Long collision chains treeify to O(log n) (DoS defense)." },
  { q: "TreeMap gives you…", options: ["O(1) lookup", "Sorted order and range queries (O(log n))", "Insertion order"], answer: 1,
    explain: "Use it only when you need order; LinkedHashMap for insertion order." },
  { q: "Often the biggest perf factor in collections is…", options: ["Big-O only", "Cache locality (contiguous beats scattered)", "Thread count"], answer: 1,
    explain: "Same O(n) can differ 10–50× by memory access." },
  { q: "Generics give you…", options: ["Runtime speed", "Compile-time type safety and no casts", "Dynamic typing"], answer: 1,
    explain: "Errors caught early; List<String> enforced." },
  { q: "PECS means…", options: ["Nothing", "Producer Extends, Consumer Super", "Public Enum Class System"], answer: 1,
    explain: "? extends T to read; ? super T to write." },
  { q: "You can read T from a…", options: ["? super T", "? extends T (a producer)", "Neither"], answer: 1,
    explain: "You write T to a ? super T consumer." },
  { q: "<T extends Number> both restricts T and…", options: ["Does nothing else", "Lets you call Number's methods on T", "Boxes T"], answer: 1,
    explain: "Without a bound, T is treated as Object." },
  { q: "Type erasure means at runtime…", options: ["Types are kept", "List<String> and List<Integer> are both just List", "Generics don't exist"], answer: 1,
    explain: "Hence no new T[], no instanceof List<String>." },
  { q: "You cannot do…", options: ["List<String>", "new T[10] (erasure)", "Box<T>"], answer: 1,
    explain: "No generic array creation; pass a Class<T> or use a List." },
  { q: "Arrays are covariant, generics are…", options: ["Also covariant", "Invariant (compile-time safe)", "Contravariant"], answer: 1,
    explain: "Array covariance → runtime ArrayStoreException; generics catch it at compile time." },
  { q: "To create a T at runtime despite erasure…", options: ["new T()", "Pass a Class<T> or a Supplier<T>", "Impossible"], answer: 1,
    explain: "Thread the type in as data." },
  { q: "Removing from a List during for-each…", options: ["Works", "Throws ConcurrentModificationException", "Is faster"], answer: 1,
    explain: "Use removeIf or the iterator's remove()." },
  { q: "List.of(...) is…", options: ["Mutable", "Immutable (throws on modification)", "A view"], answer: 1,
    explain: "Copy into a new ArrayList to modify." },
  { q: "computeIfAbsent(k, key -> new ArrayList<>()) builds…", options: ["Nothing", "A multi-map cleanly (no null checks)", "A Set"], answer: 1,
    explain: "Creates the list on first use, returns existing after." },
  { q: "ArrayDeque is preferred over Stack because…", options: ["It's older", "Stack is a legacy synchronized class", "It's sorted"], answer: 1,
    explain: "Avoid Vector/Hashtable/Stack; use modern collections." }
]},

{ title: "Quiz 4 · Lambdas & Streams",
  desc: "Functional interfaces, method refs, capture, stream pipelines, collectors",
  questions: [
  { q: "A lambda is an implementation of…", options: ["Any class", "A functional interface (one abstract method)", "A thread"], answer: 1,
    explain: "It only works where such an interface is expected." },
  { q: "Predicate<T> is…", options: ["T → T", "T → boolean", "() → T"], answer: 1,
    explain: "Function T→R, Consumer T→void, Supplier ()→T." },
  { q: "String::toUpperCase is a…", options: ["Static ref", "Instance method ref of an arbitrary object", "Constructor ref"], answer: 1,
    explain: "The stream element becomes the receiver." },
  { q: "A captured local variable must be…", options: ["Mutable", "Effectively final", "Static"], answer: 1,
    explain: "Captured by value; the lambda may outlive the method." },
  { q: "In a lambda, 'this' refers to…", options: ["The lambda", "The enclosing instance", "null"], answer: 1,
    explain: "In an anonymous class, 'this' is the anon instance." },
  { q: "A stream pipeline is…", options: ["source → terminal only", "source → intermediate (lazy) → terminal (eager)", "always eager"], answer: 1,
    explain: "No terminal op → nothing runs." },
  { q: "Streams are…", options: ["Eager, stage-by-stage", "Lazy and element-at-a-time (short-circuiting)", "Always parallel"], answer: 1,
    explain: "findFirst/limit stop early." },
  { q: "map vs flatMap: flatMap…", options: ["Is 1:1", "Flattens 1:many (Stream of streams → elements)", "Filters"], answer: 1,
    explain: "map is exactly one output per input." },
  { q: "groupingBy produces…", options: ["A List", "A Map partitioned by a key (with optional downstream collector)", "A Set"], answer: 1,
    explain: "e.g. groupingBy(dept, counting())." },
  { q: "Parallel streams help for…", options: ["Small data", "Large CPU-bound independent work on splittable sources", "I/O-bound work"], answer: 1,
    explain: "Otherwise slower (overhead) or corrupt (races)." },
  { q: "Mutating shared state in a stream lambda…", options: ["Is fine", "Breaks under parallelism — use collect/reduce", "Is fastest"], answer: 1,
    explain: "Keep lambdas stateless and non-interfering." },
  { q: "A stream is…", options: ["Reusable", "Single-use (terminal consumes it)", "A collection"], answer: 1,
    explain: "Create a fresh one from the source each time." },
  { q: "toMap with duplicate keys…", options: ["Merges", "Throws unless you provide a merge function", "Ignores them"], answer: 1,
    explain: "Supply a BinaryOperator to resolve." },
  { q: "orElse(expensive()) vs orElseGet: orElse…", options: ["Is lazy", "Always evaluates its argument (even when present)", "Throws"], answer: 1,
    explain: "Use orElseGet(supplier) for lazy defaults." },
  { q: "A method reference is best when the lambda…", options: ["Has extra logic", "Just calls a named method with the same args", "Is complex"], answer: 1,
    explain: "Otherwise keep the lambda." },
  { q: "Consumer<T>'s method is…", options: ["apply", "accept", "get"], answer: 1,
    explain: "Predicate.test, Function.apply, Supplier.get." },
  { q: "Passing a Supplier<T> instead of a T enables…", options: ["Nothing", "Deferred/lazy evaluation", "Faster loops"], answer: 1,
    explain: "e.g. log.debug(() -> expensive())." },
  { q: "A functional interface has…", options: ["Many abstract methods", "Exactly one abstract method", "No methods"], answer: 1,
    explain: "@FunctionalInterface enforces it." },
  { q: "IntStream vs Stream<Integer> avoids…", options: ["Nothing", "Boxing overhead", "Laziness"], answer: 1,
    explain: "Primitive specializations for hot numeric pipelines." },
  { q: "forEach(list::add) to build a list is…", options: ["Idiomatic", "An anti-pattern — use collect(toList())", "Fastest"], answer: 1,
    explain: "Unsafe in parallel; express accumulation as a collector." }
]},

{ title: "Quiz 5 · Exceptions, Optional & Modern Java",
  desc: "Error handling, null safety, dates/money, records, sealed, pattern matching",
  questions: [
  { q: "Checked exceptions are…", options: ["Not enforced", "Compiler-enforced (catch or declare)", "Errors"], answer: 1,
    explain: "Unchecked (RuntimeException) are not; modern code favors unchecked." },
  { q: "try-with-resources guarantees…", options: ["Nothing", "close() on any exit (reverse order, suppressed exceptions)", "Faster I/O"], answer: 1,
    explain: "Use it for every AutoCloseable." },
  { q: "When wrapping an exception you should…", options: ["Drop the cause", "Chain the cause (new X(msg, e))", "Log twice"], answer: 1,
    explain: "Preserves the stack trace trail." },
  { q: "return in a finally block…", options: ["Is fine", "Swallows the try's exception", "Is required"], answer: 1,
    explain: "Never return/throw from finally." },
  { q: "The cardinal error-handling sin is…", options: ["Logging", "Swallowing (empty catch)", "Rethrowing"], answer: 1,
    explain: "Handle at the layer that can act; don't hide failures." },
  { q: "Optional's main value is on…", options: ["Fields", "Return types (absence explicit in the type)", "Parameters"], answer: 1,
    explain: "Don't use it as a field/parameter/collection wrapper." },
  { q: "optional.get() without checking…", options: ["Is safe", "Throws NoSuchElementException (an anti-pattern)", "Returns null"], answer: 1,
    explain: "Use orElse/orElseThrow/ifPresent/map." },
  { q: "The deepest null fix is…", options: ["Optional everywhere", "Not creating nulls (empty collections, validation)", "try/catch"], answer: 1,
    explain: "Optional is one tool in a broader strategy." },
  { q: "Never use double for…", options: ["Loops", "Money (0.1+0.2≠0.3)", "Coordinates"], answer: 1,
    explain: "Use BigDecimal or integer cents." },
  { q: "BigDecimal should be constructed from…", options: ["A double", "A String", "A float"], answer: 1,
    explain: "new BigDecimal(0.1) captures binary imprecision." },
  { q: "Store/compute times in… and convert for display", options: ["Local time", "UTC (Instant)", "Epoch millis in local"], answer: 1,
    explain: "Use region ZoneIds (DST-aware), not fixed offsets." },
  { q: "A record generates…", options: ["Nothing", "final fields, accessors, equals/hashCode/toString", "Setters"], answer: 1,
    explain: "Immutable data carrier in one line." },
  { q: "Sealed types enable…", options: ["Nothing", "Compiler-checked exhaustiveness (no default needed)", "Faster code"], answer: 1,
    explain: "Adding a subtype breaks every exhaustive switch." },
  { q: "Records + sealed + pattern matching let you…", options: ["Write less only", "Make illegal states unrepresentable", "Skip tests"], answer: 1,
    explain: "Algebraic data types — force every case to be handled." },
  { q: "A regex Pattern should be compiled…", options: ["On every call via String.matches()", "Once into a static final field, reused", "Never"], answer: 1,
    explain: "Compiling is expensive; matching is cheap. Pattern is thread-safe; Matcher is not." },
  { q: "A pattern like (a+)+ on hostile input can…", options: ["Never fail", "Backtrack exponentially (ReDoS) and hang a thread", "Only mismatch"], answer: 1,
    explain: "Nested/overlapping quantifiers are a DoS risk — use linear/possessive patterns, bound input." },
  { q: "For a runtime framework (Spring/JUnit) to read a custom annotation, it must have…", options: ["@Target only", "@Retention(RUNTIME)", "public fields"], answer: 1,
    explain: "SOURCE/CLASS retention is gone before the code runs — the framework sees nothing." },
  { q: "Reflection's setAccessible(true) is dangerous because it…", options: ["Is slow only", "Bypasses private (breaks encapsulation) and can be blocked by the module system", "Never works"], answer: 1,
    explain: "It also defers a mistyped method name to a runtime failure. Prefer compile-time codegen where possible." },
  { q: "In JPMS, a public class in a non-exported package is…", options: ["Accessible everywhere", "Invisible outside its module (strongly encapsulated)", "A compile error"], answer: 1,
    explain: "Accessibility now = access modifier AND package export status." },
  { q: "exports vs opens: a framework like Jackson reflecting into your private fields needs…", options: ["exports", "opens (runtime deep reflection)", "requires"], answer: 1,
    explain: "exports grants public-API access; opens grants reflective access. Qualify it: opens ... to jackson." }
]}
);
